### PR TITLE
Add new-style 2.0 command names for Airflow 1.10.x

### PR DESCRIPTION
**Pull request by ashb**
This introduces the new style commands for 1.10, but keeps all the
existing commands working, they just don't show in the top level
`airflow --help` anymore.

image

image

This was done by taking the argparse groups/sub-commands from master
(along with supporting functions) and copying it here, then providing
needed shims for compat.

I have not added any new sub-commands, nor changed any existing
behaviours, so the 1.10 commands won't change in behaviour.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
We should move the note from Updating guide too over here:

https://github.com/apache/airflow/blob/master/UPGRADING_TO_2.0.md#airflow-cli-changes-in-20

**Review by potiuk — APPROVED** [review]
Great idea!

**Comment by ashb** [comment]
Ohh _crap_. This might not be possible with anything less than python 3.7. The `required` option to subparsers wasn't added until 3.7.

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Tests are failing due to some interaction/side effect between tests.

**Comment by ashb** [comment]
Ah, side-effect of deleting elements out of the class-level dictionary meant we couldn't create more than a single parser object per process. Fixed in 4bd9f91 I hope

**Review by turbaszek — APPROVED** [review]

**Pull request merged**
