### PR TITLE
[AIRFLOW-2805] Display multiple timezones in the tooltip on TaskInstances

### PR DESCRIPTION
**Pull request by verdan**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow 2805](https://issues.apache.org/jira/browse/AIRFLOW-2805) issues and references them in the PR title. 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR implements multiple timezones for task instances. By default it will display UTC and User's local timezone. If the DAG's timezone is different from UTC and User's Local Timezone, then the tooltip will also display the third timezone i.e., DAG's timezone. 
This includes the new JS library momentJS, which also replaces the hard-coded JQClock.js file from the code base. (The clock in the navigation also uses momentJS now)
screen shot 2018-08-02 at 2 11 14 pm
screen shot 2018-08-02 at 2 11 39 pm
screen shot 2018-08-02 at 3 30 29 pm

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
It only affects JS files, and we don't have any tests for JS code yet.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Great work @verdan ! Can you please make sure to update the LICENSE file accordingly (ie. add moments.js under MIT and remove jqclock). In addition please fix your JIRA reference.

**Comment by verdan** [comment]
Can't remove jqClock from License, as it is still being used in `www` version of webserver.

**Comment by ron819** [comment]
Can this be cherry picked to 1.10.2? Also the Jira ticket is still open .. needs to be closed.

**Comment by ashb** [comment]
This one probably isn't easy to cherry-pick because it depends upon the switch to using npm/packages.json for managing front end libs which is only on master.

**Comment by zachliu** [comment]
@verdan This only deals with the `Graph View`. What about the `Tree View`? :grin:

**Pull request merged**
