### PR TITLE
Migrate from helm-unittest to python unittest

### PR DESCRIPTION
**Pull request by mik-laj**
I am waiting for the @dimberman 's change to be merged, but in the meantime I have converted all tests with an [automated script](https://gist.github.com/mik-laj/3ae253d5394b34447dcbd426fd19b389). 

Part of: https://github.com/apache/airflow/issues/11657
Depends on: https://github.com/apache/airflow/pull/11693

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
@OmairK Can you look at it?

**Comment by OmairK** [comment]
> @OmairK Can you look at it?

Thanks @mik-laj I will have a look at it.

**Comment by mik-laj** [comment]
The automatic converter is available here: https://gist.github.com/mik-laj/3ae253d5394b34447dcbd426fd19b389

**Review by dimberman — APPROVED** [review]
Ahh damn, you beat me to it :)

**Pull request merged**
