### PR TITLE
in-complete example for salesforce

### PR DESCRIPTION
**Pull request by jayantsande25**
Hi Team, can you show a working example of DAG with salesforce? Rightnow there isnt any example in here

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by jayantsande25** [comment]
Please add example DAG in salesforce connectors space.

**Comment by subkanthi** [comment]
> Please add example DAG in salesforce connectors space.

Im working on creating one for using the Salesforce Bulk API.

**Comment by jayantsande25** [comment]
Kanthi,
Thank you for your reply, let me know if you need help/need more details on
Bulk API.
I am good on salesforce side.
Alternately , you can use simple rest apis as well. Rest APIs are good when
data volume is small say upto 10,000 K records.
Anything more can be dealt with Bulk API.
it has latest version
https://developer.salesforce.com/docs/atlas.en-us.api_bulk_v2.meta/api_bulk_v2/introduction_bulk_api_2.htm

Thank you,
Jay

**Review by 0ex-d — COMMENTED** [review]
Not sure why this was put here

**Comment by xinbinhuang** [comment]
@jayantsande25 Can you open an issue instead? thank you :)

**Pull request closed without merging**
