### PR TITLE
[AIRFLOW-2139] Don't use private methods of a third-party package

### PR DESCRIPTION
**Pull request by mremes**
WIP but this at least poses problems when migrating into a newer `pandas-gbq` version.

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/projects/AIRFLOW/summary) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2139

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
No UI or API changes
### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
`pandas-gbq` already tests the functionality

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@kaxil what's your opinion on this?

**Comment by Fokko** [comment]
@hgrif do you have any experience with this?

**Comment by kaxil** [comment]
@Fokko I haven't used Pandas GBQ but I would do it in few days and update it here in case this PR is still open. 

@mremes Can you confirm that you have tried using `get_pandas_df()` method? Can you provide an example over here?

**Comment by hgrif** [comment]
@Fokko : No, I've never used it. The library is also being used in pandas btw: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_gbq.html

**Comment by mremes** [comment]
@kaxil using the hook in a custom operator. `get_pandas_df()` broke when `pandas-gbq` dependency is updated to [version 0.3.1](https://github.com/pydata/pandas-gbq/tree/0.3.1). It's doing what is expected, as can be read from the `read_gbq` docstring.

**Comment by mremes** [comment]
This is about replacing 2 years old code 😜I don't remember the state of the project at that stage. Pretty dangerous use of private methods though...

**Comment by kaxil** [comment]
Thank you @mremes @hgrif. I think this should be fine @Fokko

**Comment by Fokko** [comment]
@mremes Thanks for updating. I agree that using private methods is not good practice. But I've never used the code, so thanks @kaxil and @hgrif for taking a look at it. Cheers!

**Pull request closed without merging**
