### PR TITLE
[AIRFLOW-1338] Add GCP dataflow hook runner change to UPDATING.md

### PR DESCRIPTION
**Pull request by yk5**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

@fenglu-g please review and refer to a relevant commitor.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1338

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

GCP dataflow hook changed the default runner name to a new name 'DataflowRunner'.
This PR adds a release note regarding this backward-incompatible change to UPDATING.md.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

too straightforward change?

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by alexvanboxel** [comment]
This would brake people running it with the DataFlow v1 SDK. Note that v2 is still not officially out.

**Comment by yk5** [comment]
Please note that even [google-cloud-dataflow-0.6.0](https://pypi.python.org/pypi/google-cloud-dataflow/0.6.0) which is up-to-date in pypi already removed DataflowPipelineRunner from its supported names. 
The new name got introduced in 0.5.1 and the old name is officially removed in 0.6.0 ([release note](https://cloud.google.com/dataflow/release-notes/release-notes-python)).

I know this is a breaking change, but anybody starting airflow today by `pip install apache-airflow google-cloud-dataflow` will get the error "DataflowPipelineRunner is not a valid PipelineRunner name."

**Comment by alexvanboxel** [comment]
Allright, I'm wondering if we should note this in UPDATING.md. So people are warned, as this is master this would be a new Airflow 1.9 section.

**Comment by yk5** [comment]
Added a note. Is it the correct place?

**Comment by bolkedebruin** [comment]
Why was this closed? Will you open a new one?

**Comment by yk5** [comment]
Ah, that was my mistake. I accidentally removed the branch that included this PR while cleaning up my repo.
Actually the PR was ready at the lastest update (May 25), but hasn't gotten much attention. (both the reviewer and I forgot to proceed)
I will revive again and see if there's any conflict to resolve.

**Comment by yk5** [comment]
FYI, I revived the branch and reopened the PR.
Not sure it's good to sync the branch myself, so the files are as they were
at the last commit. (I remember some projects prohibits syncing the branch
during review.)

**Comment by yk5** [comment]
Hi, I merged to another committed PR that did the same thing, but here still UPDATING.md needs updates.
@criccomini Please review. Thanks!

**Pull request closed without merging**
