### PR TITLE
Implement SSH Execute Operator

### PR DESCRIPTION
**Pull request by KeenS**
#789 . Are there any missing stuff?

### CODE REVIEW

**Comment by KeenS** [comment]
Though I don't think I touched any relating code test claims 

```
from flask_admin.babel import Translations
ImportError: cannot import name Translations
```

. Why?
Concerning my codes,

```
/run_unit_tests.sh tests:SSHExecuteOperatorTest
```

passes all the test cases.

**Comment by bolkedebruin** [comment]
@Keens probably looks good. I think this is due to some change @mistercrunch is making.

And I see some import *, in test. It's frowned upon nowadays. So mistercrunch might want have that adjusted.

**Comment by mistercrunch** [comment]
Please squash into a set of meaningful commits if possible as you rebase.

**Comment by KeenS** [comment]
@bolkedebruin Sorry, I didn't tested the code under python3. Now I assure the code works under both python2 and 3.

**Comment by bolkedebruin** [comment]
ping @mistercrunch @KeenS can you rebase?

**Comment by KeenS** [comment]
rebased

**Comment by mistercrunch** [comment]
I took the time to review the code and it looks solid. I'd push that merge button if I could. Would you mind rebasing once more?

**Comment by KeenS** [comment]
Not at all. Rebased.

**Comment by ldct** [comment]
@KeenS why is the `--tmpdir` option passed to mktemp? also, why is the `-q` option passed to `ssh`?

**Comment by KeenS** [comment]
@zodiac 
`--tmpdir` is needed to create temp file at system temporary directory.
`-q` is needed to capture pure `mktemp` output.

**Pull request merged**
