### PR TITLE
Revert "Remove remaining Airflow 2.5 backcompat code from Google Prov…

### PR DESCRIPTION
**Pull request by potiuk**
…ider (#36366)"

This reverts commit 2c2763f806517ae514d5614d519966da02ff4371.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I think (though I have no idea how) this one triggered the (pretty repeatable) failure: https://github.com/apache/airflow/actions/runs/7331844040/job/19966037471

I don't think this is a direct cause - the error looks like a side-effect of some asyncio test - i just want to see if reverting it will bring the green status again (seems that it started to happen after this one was merged).

**Comment by potiuk** [comment]
It's a very strange one -- very consistently happening for Postgres 14 + Pyhon 3.10 (and only for that combination (!??!)... If that one will fail, I plan to merge it and then we can try to start looking for the reason.

**Comment by potiuk** [comment]
Yep. Looks like reverting this change brings bavck "green" status.

**Review by hussein-awala — APPROVED** [review]
LGTM, I will take a look once this one is merged.

**Comment by potiuk** [comment]
I believe this error is manifestation of this pytest-asyncIo issue: https://github.com/pytest-dev/pytest-asyncio/issues/200 

It looks like the way how pytest-asyncio implements their pytest fixtures is that it (sometimes) creates a new event loop to handle tests and when there are some pending tasks those tests are not cleaned immediately when the fixture event loop is leaving the test scope. So seems that the change in airflow/providers/google/cloud/log/stackdriver_task_handler.py (this is where asyncio code is used) is triggering a condition where stackdriver's test is leaving an asyncio task behind and that task only gets cancelled much later - and accidentally it produces a log entry in the same logger that is then verified in `test_disable_logging` .

**Comment by potiuk** [comment]
Added https://github.com/apache/airflow/pull/36442 to test the hypothesis

**Pull request merged**
