### PR TITLE
[AIRFLOW-1770] allow HiveOperator to take in a file

### PR DESCRIPTION
**Pull request by Acehaidrey**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow 1770](https://issues.apache.org/jira/browse/AIRFLOW-1770/) issues and references them in the PR title. For example, "[AIRFLOW-1770] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1770

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
The HiveOperator as it currently stands is not flexible enough to accept a hive file and operate on that. You need to read in the contents and pass it and if you do that you need to change the way hiveconfs are in your file to jinja templating.
Many teams already have their existing sql/hql files and don't want to convert them to make them as portable and decoupled as possible.
To accomplish this all we need to do is add the option to pass a hql_file and hiveconfs to the HiveOperator. We change the code in the execute to throw an error if both a hql_file and an hql statement are passed. If just hql_file the simplest way without changing the code of the hive hook is to just read the content of the hql_file and set it to be the self.hql. The hiveconfs get passed directly to the run_cli method and we can combine them with the already passed in hiveconfs.
If we want to make it optional to pass in the context as hiveconfs we can add that too as related to AIRFLOW-788.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I've included some tests to show it all works how we expect.
* Throw error if both hql and hql_file passed
* Test to show hql_file and hiveconfs option can pass correctly and run operator
* show mapred name set if none passed by default

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by saguziel** [comment]
Are you sure you can't just pass in a hive file as is? I see people do that internally, but it's unclear if that's something on just our internal branch (unlikely).

**Comment by Acehaidrey** [comment]
Hey @saguziel,
If it is possible maybe I’m missing how. I can’t pass a hive file path as the hql. I know you can read the file and then pass it. But that’s another step most analysts etc at Pandora have complained about. Is there already a way to pass a hive file and then pass hiveconfs to it without changing the hive file to be jinja templated?

**Comment by saguziel** [comment]
There are cases in our codebase where the path of an hql file is supplied as the hql argument.

**Comment by Acehaidrey** [comment]
Hm okay. I’ll have to check how to make that work. Do you have to put your sql files in a templates/ folder? To be able to template the file? And in the sql file must it be Jinja variables or can it be hiveconf vars like ${hiveconf:DAY}.
Can you provide me any more detail on how you have it set up?

**Comment by Acehaidrey** [comment]
```  File "/home/abmetrics/.virtualenvs/airflow/local/lib/python2.7/site-packages/airflow/models.py", line 2277, in resolve_template_files
    setattr(self, attr, env.loader.get_source(env, content)[0])
  File "/home/abmetrics/.virtualenvs/airflow/local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: /home/abmetrics/.virtualenvs/airflow/airflow_home/dags/examples/example_analytics_dag/example_analytics_dag.pyc/test.sql```

```from airflow.operators.hive_operator import HiveOperator
load_hive = \
    HiveOperator(
        task_id='load_hive',
        hql=os.path.join(os.path.realpath(__file__), 'test.sql'),
        dag=dag
    )```

From my experiences I get that TemplateNotFound error when trying to do this above operator command.
How do you get around it.

**Comment by Acehaidrey** [comment]
Going to close this PR since this one: https://github.com/apache/incubator-airflow/pull/2752 is more up to date and more minimal.

**Pull request closed without merging**
