### PR TITLE
Update graph nodes with operator style attributes.

### LINKED ISSUE #31949: Support Operator User Interface Elements in new graph view
### Description

The new graph UI looks good but currently doesn't support the color options mentioned here https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html#user-interface

### Use case/motivation

It would be great for these features to be supported in the new grid view as they are in the old one

### Related issues

[slack](https://apache-airflow.slack.com/archives/CCPRP7943/p1686866630874739?thread_ts=1686865767.351809&cid=CCPRP7943)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tirkarthi**
closes: #31949
related: #31949

The value from graph_data API is "fill:#ffee00;" . Please let me know if there is a simpler way to parse this instead of string manipulation. Sample dag with screenshot

```python
from datetime import datetime
from airflow.decorators import dag, task
from airflow.models.baseoperator import BaseOperator
from airflow.operators.bash import BashOperator


class HelloOperator(BaseOperator):
    ui_color = "#ffee00"
    ui_fgcolor = "#00ff04"
    custom_operator_name = "Howdy"


@dag(dag_id="gh32757", start_date=datetime(2023, 1, 1), catchup=False)
def mydag():

    @task
    def input(i):
        return i

    @task
    def output(i):
        return i

    bash = BashOperator(task_id="t1", bash_command="echo hello")
    hello = HelloOperator(task_id="t2")
    bash2 = BashOperator(task_id="t3", bash_command="echo bye")

    inputs = input.expand(i=[1, 2])
    output.expand(i=inputs)
    bash >> hello
    bash2

mydag()
```

image

### CODE REVIEW

**Comment by bbovenzi** [comment]
That `howdy` operator does not look good at all. I wonder if there is a different way we want to show the operator color instead of a background? Maybe make it a [tag](https://chakra-ui.com/docs/components/tag/usage)?

**Comment by tirkarthi** [comment]
The color selection for the operator could be bad on my part. This is how it looks in the traditional graph view as well. I just wanted to select some odd colors to see how border and other style attributes look.

image

**Comment by bbovenzi** [comment]
Here is what I was thinking about. What do you think?

Screenshot 2023-08-02 at 1 08 28 PM

**Comment by pierrejeambrun** [comment]
I personally think that Brent suggestion looks great!

**Comment by bbovenzi** [comment]
Decided to commit my changes so we can try to get this in for 2.7.

**Comment by tirkarthi** [comment]
Thanks @bbovenzi , this will be an improvement to differentiate operators based on custom colors. It can be changed based on feedback if users still want it as background color like the legacy graph view.

**Review by bbovenzi — APPROVED** [review]

**Pull request merged**
