### PR TITLE
[AIRFLOW-134] Add PR merge script

### PR DESCRIPTION
**Pull request by jlowin**
This script (based on the Spark utility here: https://github.com/apache/spark/blob/master/dev/merge_spark_pr.py) makes it simpler to merge PRs and automatically close JIRA issues.

It is a guided workflow that reduces the chance of committers inadvertently doing something they really didn’t mean to do.

Usage:

``` bash
# the script will prompt for a PR number
airflow/dev/merge-airflow-pr.py

# or you can pass one
airflow/dev/merge-airflow-pr.py 1515
```

… and just follow the instructions.

Bonus points for using the script to merge this PR.

Here is the output of `merge-airflow.pr.py --help`:

```
./merge-airflow-pr.py --help
Usage: merge-airflow-pr.py [OPTIONS] [PR_NUM]
    Utility for creating well-formed pull request merges and pushing them
    to Apache.

    This script assumes you already have a local Airflow git folder and that you
    have added remotes corresponding to both (i) the github apache Airflow
    mirror and (ii) the apache git repo.

    To configure the script, set the following env vars:
    - AIRFLOW_GIT
        The location of your Airflow git development area (defaults to the
        current working directory)

    - PR_REMOTE_NAME
        GitHub remote name (defaults to "github")

    - PUSH_REMOTE_NAME
        Apache git remote name (defaults to "apache")

    - JIRA_USERNAME
        ASF JIRA username. Required to automatically close JIRA issues

    - JIRA_PASSWORD
        ASF JIRA password. Required to automatically close JIRA issues

    - GITHUB_OAUTH_KEY
        Only required if you are exceeding the rate limit for a single IP
        address.

```

### CODE REVIEW

**Comment by jlowin** [comment]
(I used this script to merge #1483)

**Comment by criccomini** [comment]
Some docs on how to use this would be awesome. :) Either README.md or wiki

**Comment by criccomini** [comment]
LGTM

**Comment by criccomini** [comment]
https://cwiki.apache.org/confluence/display/AIRFLOW/Committers+Guide Seems like a good spot to update it

**Comment by jlowin** [comment]
@criccomini made some changes to make this more user friendly and add in-line docs. Almost entirely the same but could you have one more look? In particular you could take the `work_local` command for a spin, it only makes local changes and then deletes them when you're done looking at the PR. For example, to check out this PR: `airflow/dev/airflow-pr work_local 1515`.

(if there's a better name than `work_local` let me know... I wanted to be explicit that it's not going to push to master)

Also please see the [new README](https://github.com/jlowin/airflow/blob/0aefdb0f56e90322905a85d9f9ca79cebe51001d/dev/README.md)  for full docs. I will translate them into wiki markup _sigh_...

**Comment by criccomini** [comment]
LGTM

Ran locally with work_local, and everything worked! Very cool.

**Pull request merged**
