### PR TITLE
Remove verbose test on nosetests

### PR DESCRIPTION
**Pull request by ffinfo**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example,
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description

Making tests less verbose

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @ffinfo I don’t think it’s due to these two lines you changed. They have been “DEBUG” for quite Long time, while the verbose Travis log issue only started to appear about 2-3 days ago

**Comment by ffinfo** [comment]
@XD-DENG I do agree but still I see an improvement on the current version. Now the only debug lines I do see are the debug messages that are used in the tests itself, like here:
https://github.com/apache/airflow/blob/master/tests/contrib/sensors/test_hdfs_sensor.py#L65

So the massive spam in the log is gone now. What did trigger it to spawn now I don't know. My changes did maybe trigger the order of the tests. So maybe this was conflicting a bit?

All I know for now that this change does fix it ;).

ps: What to do with those debug messages in the tests? Don't think they are needed anyway.

**Comment by XD-DENG** [comment]
Hi @ffinfo I agree that the changes in this PR reduces the # of lines, but it's still much more than the earlier number (still more than 10K). In earlier builds before this issue arose, we normally have 8K lines in each test's log.

**Comment by XD-DENG** [comment]
Let's check together and see how we can fix this thoroughly.

**Comment by ffinfo** [comment]
@XD-DENG Agree. I can switch it even to `ERROR` instead of `INFO`? Not a clean solution but it does work.

Still fixing this with nose tests itself that it simply don't show it on stdout/stderr and only on error of fail showing it would be the best solution. I tried to look into this but would not fix this. Maybe any idea about this?

**Comment by XD-DENG** [comment]
Hi @ffinfo , I have no clear idea yet.

BTW, you made two changes, in `scripts/ci/5-run-tests.sh` and `tests/executors/test_celery_executor.py` separately. Do you know which change is the main "contributor"?

**Comment by ffinfo** [comment]
@XD-DENG The change in the nosetests is the main contributor. The celery test I just noted because I was searching for `debug` ;)

**Comment by ffinfo** [comment]
@XD-DENG and @ashb Can this be merged? We should take a look at this more but for now this helps the current builds. I think waiting on a better solution will take more time.

**Comment by XD-DENG** [comment]
Hi @ffinfo , seems we still have the issue after your latest change in this PR:
https://travis-ci.org/apache/airflow/jobs/505961942

Screen Shot 2019-03-16 at 10 16 57 AM

**Comment by ashb** [comment]
I'm trying one thing here https://travis-ci.org/ashb/airflow/builds/507169560 (switching from nosetests to py.test. Nose is quite old and unmaintained now. If switching gets us shorter logs that's a bonus and then we can start using other nice features of pytest too!)

**Comment by ffinfo** [comment]
@XD-DENG I have seen that issue also a long time ago already. Here the build still continues en getting the raw log is still possible. Travis sometimes even kills jobs when the log is to long, this change at least reduce the chance on that.

@ashb I think that would be awesome. Don't like using unmaintained package of course ;).

Although I think switching to pytest would hit other testing issues, like statefull tests because the order is changed. I have seen a lot of those problems in the past.

Merging this would at least reduce the logs for now. So can this be merged knowing this is a workaround till @ashb successfully makes the switch to pytest?

**Comment by mik-laj** [comment]
@ashb Is your change not to be discussed first? It looks like a big change.

CC: @potiuk

**Comment by ashb** [comment]
@mik-laj I wanted  to see  if "just" swapping the runner from nose to py.test 1) fixed the logging (it does) and 2) just works (it doesn't).

**Comment by ashb** [comment]
Merging this now as a tactical fix while we work out what a longer-term solution is.

**Comment by potiuk** [comment]
I also applied the change.to my wip docker change. I will happily help looking at nose alternatives soon. I think we should make some analysis and try few different test runners and compare (looks like candidate for an AIP)

**Pull request merged**
