### PR TITLE
Update statsd-mapping.yml to support Airflow 2.X pool metrics

### LINKED ISSUE #36245: Helm Chart tatsd-mappings.yml still referencing old (Airflow 1.x) Pool metrics
### Official Helm Chart version

1.8.0

### Apache Airflow version

2.5.3

### Kubernetes Version

v1.23.7

### Helm Chart configuration

_No response_

### Docker Image customizations

_No response_

### What happened

The `statsd-mappings.yml` is referencing old `airflow.pool.used_slots` which no longer exist since Airflow 2.0.0 release (ref: https://lists.apache.org/thread/ojn90zln7oc2d79jz6kpg6np1hr4t3cl).
It seems that as part of [[AIRFLOW-5662] Reduce DB queries used to emit pool usage metrics](https://github.com/apache/airflow/pull/6342) it was replaced with the following two metrics:
  - `airflow.pool.queued_slots`
  - `airflow.pool.running_slots`

N.B. this remains incorrect even on the latest version in `main`: https://github.com/apache/airflow/blob/1f6f34dba0dbc82778d25839cd78945736424692/chart/files/statsd-mappings.yml#L79C1-L82

### What you think should happen instead

`airflow.pool.queued_slots` and `airflow.pool.running_slots` should be exposed instead

### How to reproduce

N/A

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shohamy7**
---

closes: #36245
Updating the pool metrics in statsd mapping to Airflow 2.X pool metrics

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Nice!

**Comment by jedcunningham** [comment]
I fear this breaks backcompat? Am I missing something?

**Comment by shohamy7** [comment]
Hi @jedcunningham 
As far as I saw, the `airflow.pool.used_slots.*` was remove and currently the `statsd_exporter` does not export this metric (I didn't see this metrics mentioned anywhere else in the code, I think it was removed in this PR: https://github.com/apache/airflow/pull/6342).
So I don't think that this break compatibility :)

**Comment by jedcunningham** [comment]
That removal is fine, thanks for doing that digging. But moving existing metrics to use tags would be breaking for existing deployments no?

e.g.

```
Before:
airflow_pool_queued_slots_default_pool 0

After:
airflow_pool_queued_slots{pool="default_pool"} 0
```

Unfortunately, this is the spot we are in. Our next opportunity to revamp the default mapping will be in 2.0 of the chart.

In the meantime, taking advantage of `statsd.overrideMappings` is what folks should use in their own env.

**Pull request merged**
