### PR TITLE
Deletion of schema, login, password, port

### LINKED ISSUE #29113: sqlite conn id unclear
### What do you see as an issue?

The sqlite conn doc here https://airflow.apache.org/docs/apache-airflow-providers-sqlite/stable/operators.html is unclear.

Sqlite does not use username, password, port, schema. These need to be removed from the docs. Furthermore, it is unclear how to construct a conn string for sqlite, since the docs for constructing a conn string here https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html assume that all these fields are given. 

### Solving the problem

Remove unused arguments for sqlite in connection, and make it clearer how to construct a connection to sqlite

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by atharvmishra1999**
Closes:  #29113 

Deleted schema, login, password, port from docs to resolve the issue.
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by josh-fell — APPROVED** [review]
Nice!

The actual [Sqlite Connection doc](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-sqlite/connections/sqlite.rst) itself is also incorrect in the same manner. Would you like to add this update as well to the PR? It can be another PR if you feel more comfortable.

**Comment by potiuk** [comment]
> Sqlite Connection doc

Agree with @josh-fell - @atharvmishra1999 - It would be better to have it as part of the same PR actually. Could you please do it as well?

**Comment by josh-fell** [comment]
@atharvmishra1999 Would you be able to make the updates to [SQLite Connection doc](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-sqlite/connections/sqlite.rst) to close this out?

**Comment by pankajastro** [comment]
@josh-fell looks like [SQLite Connection doc](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-sqlite/connections/sqlite.rst) has been fixed so maybe we can rebase and merge this.

**Comment by josh-fell** [comment]
> @josh-fell looks like [SQLite Connection doc](https://github.com/apache/airflow/blob/main/docs/apache-airflow-providers-sqlite/connections/sqlite.rst) has been fixed so maybe we can rebase and merge this.

Yeah makes sense!

**Pull request merged**
