### PR TITLE
Allowing user to pin connection and variable at top

### LINKED ISSUE #21720: Add ability to pin Airflow Variable(s)/Connection(s) in the UI
### Description

I'd like to see functionality in the UI to allow pinning some Airflow Variables/Connections at the top of the list.

### Use case/motivation

In our deployment we have a couple of Airflow Variables, and Connections that are central to our operations. We typically have to use filter search in order to reach these Connection/Variable, since we maintain a long list.
It would be nice to have the ability to pin these few important artifacts to the top of the Variable/Connection list in the UI, such that they are readily accessible.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pateash**
closes: #21720 

---
### Description

This PR allows user to pin important Connection and Variables on Top.
Implementation is really straight forward, we will add a new column into the tables having information about pinned connection/variable and while rendering we sort according to pinned column.

### CODE REVIEW

**Comment by pateash** [comment]
Pinned Connections and views
image

image

**Comment by pateash** [comment]
Pinning at Top:
image

image

**Review by kaxil — CHANGES_REQUESTED** [review]
Since this is UI-only, I think we should be able to achieve it using JS or HTML without adding a column in the database.

cc @bbovenzi

**Comment by pateash** [comment]
> 

I think we have to have the information about the columns to be pinned stored in metadatabase.
Otherwise, it will be lost upon browser refresh and All the users will have to pin for them everytime.

**Comment by kaxil** [comment]
Can it not be stored in a browser cookie like https://github.com/apache/airflow/pull/11661/files

**Comment by ashb** [comment]
Storing this in the database (at least against the Connection table) explicitly won't fix the original ask by the user -- as they have a long list and different users would want different connections at the top..

**Comment by bbovenzi** [comment]
Without a db connection. We could use localstorage, but that would then only apply to that specific browser/computer. We already do this auto-refresh, and collapsing/expanding groups in tree/graph views.

**Comment by pateash** [comment]
@ashb I think that the user's ask was to be able to pin some useful connections at the top which help their team manage operations. 

Agree with @bbovenzi that we can use local storage, but that will not work everywhere, also different users will have to do it for themselves.

Also, I think the priority(pinning) should be up to the user to decide and it should be persistent.
I think it would be frustrating to loose that information once you switch devices or even browsers.

**Comment by SangwanP** [comment]
Hi @pateash, I created the issue: #21720. Technical implementation aside, I was expecting, from a user experience perspective, the pin would be a button on the {variable, connection} list page, similar to edit, delete, or show.
Additionally, having to pin through the edit page, might have some user permissions implications & connection password management issues.

**Comment by pateash** [comment]
@SangwanP thanks for the clarification.

@bbovenzi @kaxil @ashb 
if the requirement is to have user-specific temporary pinned connections/views, I agree that local storage is a better solution. 
If it isn't a useful feature to have persisted pinning, I will close this PR,

**Pull request closed without merging**
