### PR TITLE
Support creation of configmaps & secrets and extra env & envFrom configuration in Helm Chart

### PR DESCRIPTION
**Pull request by FloChehab**
Hello,

Here is a followup PR for what I was describing in https://github.com/apache/airflow/pull/10584#issuecomment-715530418.

This adds support for:

* Creating configMaps and secrets from the chart itself ; this can be used for https://github.com/apache/airflow/issues/11707 (especially connections values that should end up in a secret) and maybe other use cases.
* Adding extra `env` and `envFrom` items to the airflow containers created by the chart (strictly independent from `extraSecrets` / `extraConfigMaps`).

The values are of type string to enable for generic templating.

More information can be found in the commits messages.

Closes #10584

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
So cool! LGTM, I think it would be great that @dimberman takes a  look as well though !

**Comment by potiuk** [comment]
Some static checks are failing though :)

**Comment by FloChehab** [comment]
> Some static checks are failing though :)

I'll fix that soon, I was waiting for some feedback first before investing more into this PR :D

**Comment by FloChehab** [comment]
> Some static checks are failing though :)

I've rebased on master and fixed the style issues.

**Comment by potiuk** [comment]
Cool!

**Pull request merged**
