### PR TITLE
Add standard provider to chicken-egg-providers

### PR DESCRIPTION
**Pull request by potiuk**
Standard provider should be added to chicken-egg-providers as it has not yet been officially released, so we need  to add it.

This can only be done via "apache" PR as it is needed in build-images workflow. This is needed to unblock #42252

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by gopidesupavan — APPROVED** [review]

**Comment by gopidesupavan** [comment]
one test failing may be provider needs to be added here prod_image_installed_providers.txt ?

**Comment by potiuk** [comment]
> one test failing may be provider needs to be added also here prod_image_installed_providers.txt ?

Correct :D

**Review by amoghrajesh — COMMENTED** [review]
What about "edge"? 
This one LGTM

**Comment by gopidesupavan** [comment]
> What about "edge"? This one LGTM

Yes amogh, edge has no dependency on CI and other providers.

https://lists.apache.org/thread/1gshy5cjmp9wz5v8dozyh64jj3dyn5s4

**Review by jscheffl — APPROVED** [review]
Approved. Failure in CI are waiting for for in https://github.com/apache/airflow/pull/42762

**Review by amoghrajesh — APPROVED** [review]

**Pull request merged**
