### PR TITLE
Added extra annotations support

### PR DESCRIPTION
**Pull request by rahulgoyal2987**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM. @jedcunningham @dstandish ?

**Comment by potiuk** [comment]
BTW. You should also add test @rahulgoyal2987 (changing to requesting changes).

**Review by potiuk — CHANGES_REQUESTED** [review]
Looks good but tests needed.

**Comment by jedcunningham** [comment]
@rahulgoyal2987, gentle bump. Can you add tests for this?

**Pull request closed without merging**
