### PR TITLE
[AIRFLOW-6922] Support python3.8

### PR DESCRIPTION
**Pull request by blcksrx**
---
Issue link: [AIRFLOW-6922](https://issues.apache.org/jira/browse/AIRFLOW-6922)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
It seem that 3.8 `typing` have some different to 3.6 and 3.7, So maybe we could not just support it by this way

**Comment by malthe** [comment]
Seems to fail while building image:
```
WARNING: Error loading config file: /root/.docker/config.json: \
stat /root/.docker/config.json: permission denied
```

**Comment by joseangel-sc** [comment]
Have you seen how this relates to 
`cattrs==1.0` and 
`typing_extensions`  
?

I think there are some PRs open in this regard, so it is not really that simple to make the migration to 3.8

**Comment by blcksrx** [comment]
> Have you seen how this relates to
> `cattrs==1.0` and
> `typing_extensions`
> ?
> 
> I think there are some PRs open in this regard, so it is not really that simple to make the migration to 3.8

Yes, it's not simple it was just a try!

**Comment by ashb** [comment]
Yes we want to support python 3.8 -- but we need to decide what part of the matrix we suppport -- the way this is done right now this will make the tests significantly longer, which is not good for developer productivity, nor for our Travis bill.

**Comment by blcksrx** [comment]
> Yes we want to support python 3.8 -- but we need to decide what part of the matrix we suppport -- the way this is done right now this will make the tests significantly longer, which is not good for developer productivity, nor for our Travis bill.

You are right

**Pull request closed without merging**
