### PR TITLE
AirbyteHook - Consider incomplete status

### PR DESCRIPTION
**Pull request by jaimefr**
Screenshot 2021-07-13 at 11 37 47

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@jaimefr Could you please add a unit test for this change ?

**Comment by jaimefr** [comment]
> @jaimefr Could you please add a unit test for this change ?

Hello, this is my first contribution to the project and I'm not used to write tests. Could you help me by providing a similar test to the one you are asking me to add?

**Comment by marcosmarxm** [comment]
> > @jaimefr Could you please add a unit test for this change ?
> 
> Hello, this is my first contribution to the project and I'm not used to write tests. Could you help me by providing a similar test to the one you are asking me to add?

I can help you

**Comment by jaimefr** [comment]
> > > @jaimefr Could you please add a unit test for this change ?
> > 
> > 
> > Hello, this is my first contribution to the project and I'm not used to write tests. Could you help me by providing a similar test to the one you are asking me to add?
> 
> I can help you

That would be great!

**Comment by marcosmarxm** [comment]
@jaimefr you need to add a unit test for the case of incomplete status. You can use the example below to do that.

https://github.com/apache/airflow/blob/1e2837ac5498e72186a75a7efddf47c059e4a058/tests/providers/airbyte/hooks/test_airbyte.py#L80-L90

**Comment by jaimefr** [comment]
> @jaimefr you need to add a unit test for the case of incomplete status. You can use the example below to do that.
> 
> https://github.com/apache/airflow/blob/1e2837ac5498e72186a75a7efddf47c059e4a058/tests/providers/airbyte/hooks/test_airbyte.py#L80-L90

@marcosmarxm I have just added a test, it's OK or something is wrong?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Looks great to me! @potiuk it's need to bump doc and version somewhere?

Nope. That's it. The version upgrade/changelog generation is semi-automated

**Pull request merged**
