### PR TITLE
Reformat chart templates part 3

### PR DESCRIPTION
**Pull request by dnskr**
The PR reformats multiple chart templates as the continuation of https://github.com/apache/airflow/pull/29917 and https://github.com/apache/airflow/pull/29941
Less empty lines rendered when `helm template` is executed. Aligned indent style for templates.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM - Pending passing the tests.

**Comment by dnskr** [comment]
`Helm Unit Tests` were cancelled after 80 minutes and 98% of progress.
Is it possible to rerun it?

**Comment by potiuk** [comment]
I will re-run it but this likely means that there is some problem with your change. This is the second time it happens for the PR in a row:


Usually the tests on public runner are a bit faster than 80 minutes (not by long margin, so this might be small difference causing it, but it is a bit disturbing if it is consistently longer than usual:

https://github.com/apache/airflow/actions/runs/4590214027/jobs/8142557270?pr=30168

Let's see. Maybe it's time to seriously look at speeding those tests up. They take a long time to run.

**Comment by dnskr** [comment]
Helm unit tests are `Successful in 69m` this time.

I'm not super excited about unit tests for the helm chart. I mean it's quite hard to run and maintain them, but I don't know and cannot find better/faster existing alternative.

**Comment by potiuk** [comment]
so be it :)

**Pull request merged**
