### PR TITLE
fix: add pre-commit to ban urlparse

### LINKED ISSUE #27715: Add pre-commit rule to validate using `urlsplit` rather than `urlparse`
### Body

Originally suggested in https://github.com/apache/airflow/pull/27389#issuecomment-1297252026

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by wonhyeongseo**
closes: https://github.com/apache/airflow/issues/27715

Adds a pre-commit that checks for usage of `urlparse` or `urlunparse` in code. Appropriate name and description promoting the use of `urlsplit` and `urlunsplit` was added as well.

@eladkal, @potiuk, @Taragolis, may you please review this PR?

### CODE REVIEW

**Comment by potiuk** [comment]
You need to fix the static checks - install pre-commit and run it on your change and it will fix the problems automatically - then you just need to commit the changes that pre-commit will do for you.

**Comment by wonhyeongseo** [comment]
Thank you for your guidance, @potiuk. Running `pre-commit` made some changes, but the workflow is stuck on `Build PROD images`. May you please guide me on what to do next? Thanks again.
image

**Comment by potiuk** [comment]
You added by mistake some files that are normally excluded - those in provider_packages (see hte list of modifications). Remove them.

**Comment by wonhyeongseo** [comment]
Thank you so much @potiuk, I reverted the changes. Will re-entering the test-job to the queue help with this issue?
image

**Comment by wonhyeongseo** [comment]
Yes! Build is passing, thank you so much @potiuk! Test is blocked for some reason, I tried to figure out what's wrong but my knowledge is limited (sorry). May you please help me a little more sir? Thanks again!

**Comment by potiuk** [comment]
You need to restore `dev/breeze/README.md` - it's been also accidentally committed by you.

**Comment by wonhyeongseo** [comment]
All clear, @potiuk! I think we can go ahead with testing this PR now :) Thank you so much for your help!!

**Comment by uranusjr** [comment]
Please set up and run pre-commit locally to correctly regenerate BREEZE.rst. You can find instructions in CONTRIBUTING.rst

**Comment by potiuk** [comment]
> Please set up and run pre-commit locally to correctly regenerate BREEZE.rst. You can find instructions in CONTRIBUTING.rst

Yep. And rebase before that.

**Comment by eladkal** [comment]
@wonhyeongseo do you need help?

**Comment by wonhyeongseo** [comment]
Hello @eladkal, hope you are doing well. Sorry for being so late and thank you for helping out. I installed WSL2(ubuntu) and configured the correct dev environment with guidance from `CONTRIBUTING.md`. May you please tell me if there is anything to modify?

**Comment by Taragolis** [comment]
I restart failed pipeline (on wait/build images). Let's have a look maybe it pass now.

You could also join slack, if you not joined yet: https://s.apache.org/airflow-slack. Join to the `#airflow-breeze`, `#development` and `#throubleshouting, usual you could find any assistant related to Breeze or dev-environment quicker rather than in Github

**Comment by wonhyeongseo** [comment]
When I run `breeze static-checks --all-files` locally, files I have done nothing to keep popping up. My other PR didn't have this issue. What might be the problem? Thank you so much for helping out @Taragolis.
image

**Comment by potiuk** [comment]
You need rebase and resolve conflicts @wonhyeongseo -> this was likely temporary issue.

**Review by potiuk — APPROVED** [review]

**Comment by wonhyeongseo** [comment]
@potiuk Thank you so much for helping! Hope you have a great day 😄

**Pull request merged**
