### PR TITLE
[AIRFLOW-8969] Atlas Backend module improvements

### PR DESCRIPTION
**Pull request by crazzysun**
Issue #8969 

 - Create an Airflow operator atlas entity don't use execution date as part of the qualified name anymore.
 - Add config property for enabled/disabled creating missing inlets, outlets entities.
 - Add config property for enabled/disabled falling operator if sending lineage was failed
 - Add atlas timeout config property.
 - Add "template_fields" into the airflow operator typedef and add additional config property for setting any additional operator attributes.
 - Fix DataSet class wrapper, add abstract types for file and JDBC source.
 - Added utils methods for correct generating inlets and outlet objects.
 - Added unit tests for creating missing entities and falling operators.

PR uses v1-10-stable Atlas backend as a foundation ([link to PR to a v-1-10-stable branch of my fork](https://github.com/crazzysun/airflow/pull/1)).

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by mik-laj** [comment]
I am afraid that the most active reviewers are not familiar with Lineage. Therefore, you must find a person who can review this change. To do this, you must write a message on the mailing list. If this message is seen by a person who knows lineage, then you can go on. However, if no such person is found, then you need to find the latest discussion on the mailing list and write a private message asking for reviews  Airflow is a community managed project and communication with other members of this community is an important part of it.  We don't have any paid employees who handle pull requests. All work is based on volunteering or the involvement of companies that want to develop this project.

I hope this information will be helpful to you. if you have questions please let me know.

**Comment by bolkedebruin** [comment]
I'm having a look @mik-laj it remains an important area and more peopl are picking it up

**Comment by mik-laj** [comment]
@bolkedebruin thanks for the message.  I will engage you in the changes related to this area.

**Comment by thibaultbl** [comment]
Do you have any idea if Apache Atlas Lineage Backend will be reinstated anytime soon ?

**Pull request closed without merging**
