### PR TITLE
[AIRFLOW-2929] Add get and set for pool class in models

### PR DESCRIPTION
**Pull request by ChengzhiZhao**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Currently Pool class in models.py doesn't have get and set method, I suggest we add those methods to make them similar as Variable/Connection class, it will also be easier to have cli get more descriptive response as discussed [here](https://github.com/apache/incubator-airflow/pull/3730#discussion_r210185544)

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This PR is code refactoring so unit tests have been already includes.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by feng-tao — CHANGES_REQUESTED** [review]
1. This kind change needs unit test.
2. why we want to use Pool model class directly instead of the client given we have pool class in api client? This seem to be very inconsistent with the rest of request.

**Comment by ChengzhiZhao** [comment]
@feng-tao thanks for reviewing on this, I would need some suggestions here: 
1. Since this is refactoring changes, the tests/core.py should cover the unit tests for them, for example,  https://github.com/apache/incubator-airflow/blob/master/tests/core.py#L1493. Should I add more unit test?
2. I can remove pool class from api client, but my question is should we continue using `airflow.api.common.experimental` for pool or have all methods in Pool class like we did for `Variable`?

**Comment by ChengzhiZhao** [comment]
Add @Fokko and @r39132 to address the gap of [AIRFLOW-2882]

**Comment by Fokko** [comment]
Is the `from airflow.api.common.experimental import pool` still used? We try to unload code from the `models.py` since this file is huge :)

**Comment by ChengzhiZhao** [comment]
@feng-tao Any feedbacks on this PR? 
@Fokko please suggest if we still want to use `from airflow.api.common.experimental import pool` moving forward. Thanks both!

**Comment by OmerJog** [comment]
@Fokko Is this functionality needed and it's blocked by https://issues.apache.org/jira/browse/AIRFLOW-3579  or this PR is not needed at all?

**Comment by Fokko** [comment]
@OmerJog This would be a nice to have to the API. I think this PR is superseded by: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-13%3A+OpenAPI+3+based+API+definition

**Pull request closed without merging**
