### PR TITLE
[AIRFLOW-1081] Improve performance of duration chart

### PR DESCRIPTION
**Pull request by saguziel**
This commit reduces the number of queries to improve perf.

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1081

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes: This boils down the queries into two.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: There's already a (minimal) UI test for this, and this does not change existing behavior.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by amaliujia** [comment]
LGTM assume has tested the functionality of web UI.

**Comment by OpringaoDoTurno** [comment]
This merge seems to break the duration chart. 

Please look at the graph before and after reverting this commit:

Before: before
After: after

**Comment by saguziel** [comment]
@OpringaoDoTurno  Does this repro on reload? It appears to work fine internally

**Comment by OpringaoDoTurno** [comment]
@saguziel Yes, it reproduces. 
In fact, it is something that happens always (no amount of page reloads or server restarts has solved it) to some few DAGs (not all of them) but always to the same ones.

**Comment by OpringaoDoTurno** [comment]
Found it!

It seems it can be solved with a simple sort:
Old behaviour relied on `task.get_task_instances` and new one on `dag.get_task_instances` and seems to be differences between the two: one is (one is sorted by `execution_date`, the other isn't)

It can be solved adding a sort (`tis.sort(key=lambda x: x.execution_date)`) after `dag.get_task_instances` (around line 1422 in views.py your commit) 

I'll start preparing a pull request :)

**Pull request closed without merging**
