### PR TITLE
Fetch status in while loop so as to not exit too early

### PR DESCRIPTION
**Pull request by o-nikolas**
This fixes a condition described in #30626 for the AWS Quicksight hook.

There was a previous PR #30637 which is now closed, so I'm submitting what was left of those changes here.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — APPROVED** [review]
Is it possible to have unit test covering it?
hoping to avoid future regression

**Comment by o-nikolas** [comment]
CC: @vincbeck @AkshatJoshi-18

**Review by vincbeck — APPROVED** [review]

**Comment by o-nikolas** [comment]
> Is it possible to have unit test covering it? hoping to avoid future regression

Let me look and see :+1:

**Comment by o-nikolas** [comment]
Added a test case to cover this @eladkal
I confirmed it fails on `main` and passes on my branch.

**Review by vincbeck — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
