### PR TITLE
Make smtp provider tests discoverable

### PR DESCRIPTION
**Pull request by potiuk**
The tests for smtp provider were placed in "smtp.py" module which made them not discoverable during pytest collection.

Changing module makes them discoverable again (they all pass BTW!)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I found it during testing of #30305  (which is another nice side effect of splitting tests per-provider).

**Comment by potiuk** [comment]
BTW. I wonder if we do not have similar cases elsewhere). It would be great to review our "rests" folder and possibly find (and automaticallly prevent in the future) similar problems. Any ideas?

**Review by hussein-awala — APPROVED** [review]
LGTM

**Comment by hussein-awala** [comment]
> I wonder if we do not have similar cases elsewhere). It would be great to review our "rests" folder and possibly find (and automatically prevent in the future) similar problems. Any ideas?

I run a small script to check this, but I am not sure if it's enough:
```python
from pathlib import Path

if __name__ == '__main__':
    tests_path = Path("airflow/tests")
    not_discovered_files = set(tests_path.glob('**/*.py')) - set(tests_path.glob('**/test_*.py'))
    for file in not_discovered_files:
        with open(file) as f:
            content = f.read()
            if "def test" in content or "TestCase" in content:
                print(file)
```
And the output is:
```
airflow/tests/conftest.py
airflow/tests/test_utils/asserts.py
airflow/tests/test_utils/perf/perf_kit/__init__.py
airflow/tests/providers/databricks/utils/databricks.py
airflow/tests/system/utils/__init__.py
airflow/tests/system/providers/influxdb/example_influxdb.py
airflow/tests/system/providers/amazon/aws/example_lambda.py
```
After checking these files, I think we should rename `airflow/tests/providers/databricks/utils/databricks.py`

**Comment by potiuk** [comment]
Closing - there is a better fix (and no need to have test_* prefix) in #30315

**Pull request closed without merging**
