### PR TITLE
[AIRFLOW-6428] Fix import path for airflow.utils.dates.days_ago in Example DAGs

### PR DESCRIPTION
**Pull request by kaxil**
Import the `days_ago` function directly from `airflow.utils.dates` in all our Example DAGs.

~Currently, without the entry in __init__.py, IDEs show that it could not find the reference to dates in most of our example_dags as they contain `airflow.utils.dates.days_ago(1)` and hence if you try to find the reference for days_ago function or dates modules it can't find it.~

image
image

---
- [x] Description above provides context of the change
- [x] Commit message contains [\[AIRFLOW-6428\]](https://issues.apache.org/jira/browse/AIRFLOW-6428)
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Why don't we do it "differently" ... 

I am not sure why we are using those imports in this form? Do we have something that holds us back from changing all "days_ago" imports to the form that is much more pythonic (IMHO)? 

Adding anything to `__init__.py` inside the application creates unnecessary dependencies. Anybody using "airflow.utils.somethingelse" will add an implicit dependency to "airflow.utils.dates" if we add dates to `__init__.py` - even if it is not used directly. This adds unnecessary dependencies (and leads to circular dependencies).

I think most of our `__init__.py `should be empty (or removed  if we go to implicit python3 packages). I believe adding anything to `__init__.py` makes only sense if we provide a reusable library with one package - when if you import it, you should have access to all exposed functions. 

I am happy to discuss it though, as we might have different understanding - and maybe we should expose all "exposable" classes from unit in this way as part of the "official airflow interface" (but I still think import should be `from airflow.utils.xxx import yyy` anyway).

Just to summary - we have two options:

1. Import airflow and then rely on the __init__ packages
```
import airflow
```
and then using
```
airflow.utils.dates.days_ago(2)
```

2. Import the function directly (much better IMHO).

```
from airflow.utils.dates import days_ago
```

Option 1 (with importing the whole 'airflow').

Screenshot 2020-01-02 at 23 16 23

Option 2: (wiht importing only the function we need)

Screenshot 2020-01-02 at 23 09 14

WDYT @kaxil?

**Review by potiuk — CHANGES_REQUESTED** [review]
Just wanted to discuss general import approach in this case.

**Comment by kaxil** [comment]
> Just wanted to discuss general import approach in this case.

I agree the 2nd option sounds lot better, I have changed the PR and updated all the example DAGs by importing just the function from module instead of __init__.py.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Review by turbaszek — APPROVED** [review]

**Comment by potiuk** [comment]
Needs rebase @kaxil :(. 

BTW. I think we need a "Needs rebase" probot.

**Comment by potiuk** [comment]
Hmm https://github.com/tibdex/autorebase - but it seems a bit abandoned in favour of autosquash.

**Pull request merged**
