### PR TITLE
Fix type hints in airflow.macros

### PR DESCRIPTION
**Pull request by uranusjr**
I also took the chance to clean up docstrings in the package. This actually caught a bunch of bugs in the Hive macros; those are in a pretty bad shape.

### CODE REVIEW

**Comment by potiuk** [comment]
Well. I think we should entirely drop Hive macros. I am not sure if anyone is using them and they should *technically* be in Hive provider (and as you say they are in REALLY BAD SHAPE I believe. I think we should just deprecate them straight away now.

**Comment by potiuk** [comment]
I'd say we should turn the hive macros into "examples" in Hive provider. If someone wants to use them - there should be ready example for them to paste in their "plugins" folder.

**Comment by eladkal** [comment]
@potiuk we have https://github.com/apache/airflow/pull/19452 but wasn't finished

**Comment by uranusjr** [comment]
I know these are used by _someone_, because we had people reporting bugs in them. Maybe we should just do this and finish the move into provider separately (in the linked PR).

**Comment by potiuk** [comment]
> I know these are used by _someone_, because we had people reporting bugs in them. Maybe we should just do this and finish the move into provider separately (in the linked PR).

But that would require to add "plugin" capability to providers - which is a bit bigger feature and has some security implications.

**Comment by uranusjr** [comment]
That’s more reason to let the macros stay and improve them, isn’t it 🙂 I don’t think deprecating them for pending removal is a good idea, especially since we _probably_ want to add macros registration to providers at some point.

**Comment by potiuk** [comment]
> That’s more reason to let the macros stay and improve them, isn’t it slightly_smiling_face I don’t think deprecating them for pending removal is a good idea, especially since we probably want to add macros registration to providers at some point.

That's a good point and it **might** be something that we want to do (but I am not 100% sure). This is actually very relevant to multi-tenancy. Especially that providers are loaded in different contexts (workers, webserver, DAGprocessor, Scheduler, Triggerers) and adding more "capabilities" to providers should be carefully considered) - what does it mean that macros are "supported" ? Will that make provider's code executed when we just "initialize" macros? Where will it happen? Scheduler? Worker? Webserver? 
 
Speaking of which. Ihave a feeling (@ashb ? ) - this also has some "bigger" implications re: mutti-tenancy that we should think of separating plugins to three differenet kinds of plugins:

1) Those are add timtetables, trigers. (needed by scheduler and DagProcessor)
2) Those that provide features for workers (for example macros)
3) Those that modify UI

This is not needed in the first stages of mutli-tenancy but in the long-haul, conceptually those three usages are different kinds of "security zones" in the most complex setup where we separate those entities completely. And it makes the administrative side of it a bit more complex. You have to have "one" entity that allows you to install plugins (which are basicallyt packages) for all those security zones, which basically imposes strictest regulation in high-security deployments "i.e. only the Uber-Admin can install packages for any component of Airflow". Of course it can be mitigated (for example different images used by Scheduler, Worker, DAG Processor. Webserver (with different permissions  of installation packages for each of them), But conceptually Webserver does not need neither macros, nor timetables. Similarly worker only need macros and the rest is useless etc.

And it woudl be great for example to make sure that "workers" only import the plugins with macros, and no other. This can also be achieved by smart plugin manager initialization, but it's not entirely fool-proof I think if all those plugins are in the same "plugin" bag.

WDYT (long term, not now of course)?

**Comment by ashb** [comment]
@potiuk Are you thinking of something like using multiple entry_point groups to register different types of plugins etc?

**Comment by potiuk** [comment]
> @potiuk Are you thinking of something like using multiple entry_point groups to register different types of plugins etc?

Precisely

**Pull request closed without merging**
