### PR TITLE
Fix templates-ref.rst (replacement for execution_date is not dag_run.logical_date)

### PR DESCRIPTION
**Pull request by tomoemon**
This PR fixes the doc about a deprecation of execution_date.

- `dag_run.logical_date` is not same as `logical_date` (value within context)

The type of `dag_run.logical_date` is datetime.datetime.
And the type of `logical_date (within context)` is pendulum.DateTime.

I noticed this problem when I tried to call a method of `pendulum.DateTime` on the `dag_run.logical_date` variable and it failed

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
Personally I would prefer people use the value from `dag_run`, but I assume you have non-trivial reliance on Pendulum.

**Comment by tomoemon** [comment]
@uranusjr I appreciate your approval!

Reading the documentation, it is clear that Airflow developers want to use the dag_run object.

However, I could not see why a logical_date with the same name should have different types for context and dag_run. If you don't mind, could you please tell me what design philosophy is behind this difference?

**Review by hussein-awala — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> However, I could not see why a logical_date with the same name should have different types for context and dag_run. If you don't mind, could you please tell me what design philosophy is behind this difference?

I believe there is no philosophy, just historical reasons. When you have software like Airflow your decisions are based on layers of decisions taken in the past, sometimes by completely different people in completely different times and with completely different set of conditions that were valid 5 years ago and not valid today.

And with the huge codebase like we have, people rely on those decisions in their code, even if your new logic would be looking completely differently.

No matter how illogical thing is, we cannot **just change it** if people rely on it. It's a super-simplistic and a bit naive view that everything we have is super-logical and fully consistent. First of all it has to be "somewhat" consistent with both - current philosophy and with "past users" using it for years. 

It's a very delicate balance to have - you have to be careful not to break experience of 1000s of users you have but at the same time keep your own sanity - because "current view" is inconsistent. 

I think this @tomoemon  that everything can be explained by "current" consistency is really a bit simplistic and "naive" (and the "naive" word is I hope not an offending word, it's more to say that your view is limited to what you see now but when you look at history and expand it to include huge number of past users, you will understand that it does not have to have "philosophy" behind, it's enought that it has "users" behind.

Please don't get me wrong, but this is quite a bit of "theorethical" beauty you are seeking, where maintainers here deal with a "practical" aspect  of it and ....as the old saying is 

"in theory practice is the same as theory, but in practice, it's not".

**Comment by tomoemon** [comment]
@potiuk 
Thank you very much for your very detailed explanation. As you said, I just wanted to know if this is exactly the "intended design" or the "result of historical reasons".

I have been doing software development for more than 10 years, so I understand that it is very difficult to keep complete consistency all the time and in all places without breaking existing users' code.

However, even if that is not possible, I think it is a good idea to supplement the inconsistency for historical reasons in comments etc. so that "current" users are not confused.

**Comment by potiuk** [comment]
> However, even if that is not possible, I think it is a good idea to supplement the inconsistency for historical reasons in comments etc. so that "current" users are not confused.

Sure, now that you know it and got detailed explanation - I think you are one of the best people to determing where users like you would look for such comments and can add it. And I am really saying it because I believe it, not because I want to "frame you".  Things are often obvious to maintainers, because they have years of experience and  lots of assumptions they "soaked" for years. So they have often no idea that things like that should be documented, nor they have idea how and where users like you would look for this information. And what kind of information is needed.

Airflow is created by ~ 2600 contributors. Vast majority of those people are people like you who found they are missing something and contributed it back.

So now - since you got detailed explanation, you are probably the best person in the world to turn it in the comments - in the right places and the right wording that would be for good for people like you to understand when they are puzzled about something. Maybe even it should be explained in the documentation of ours (And it is super easy to add PR to documentation - just click on "Suggest a change on this page" and PR will be opened for you. This way you can become a contributor, give back for the free software you are using and generally get even more familiar with the code, structure, documentation building etc.

So - absolutely - you are more than welcome, after all that explanation to submit a PR to update the comment and docs. And even if you do not get it right in your first PR, the reviewers will comment, review, suggest and explain more - so that's even better opportunity to learn why things are the way they are. 

And this could be the same for any other aspect that is not clear. The people who are seeking for answers and do not find them are probaby the best people who can word and find the right places where the answers should be given - precisely in the places they were looking for them and did not find them.

I sincerely look forward for this and possibly other future PRs with clarification that those discussions and your curiosity might bring.

**Pull request merged**
