### PR TITLE
[AIRFLOW-3218] add support for poking a whole DAG

### PR DESCRIPTION
**Pull request by ms32035**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following 
  - https://issues.apache.org/jira/browse/AIRFLOW-3218

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Currently external task sensor requires a specific task to finish. This change adds support for DAG level checks, if task ID is not provided

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

``test_external_dag_sensor``

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by ms32035** [comment]
Tests get stuck for now, need to fix

**Comment by ms32035** [comment]
> Tests get stuck for now, need to fix

Now fixed

**Review by Fokko — COMMENTED** [review]
I like this PR. Could we also document this?

**Comment by ms32035** [comment]
Inline doc is updated as a part of the PR. Please point what else should I update.

**Comment by ms32035** [comment]
@Fokko, can you please let me know what else apart from the inline doc should be updated

**Review by Fokko — APPROVED** [review]
Was a busy week, sorry for the delay.  Looks good @ms32035

**Pull request merged**
