### PR TITLE
[AIRFLOW-1590] Fix unused module and variable

### PR DESCRIPTION
**Pull request by ProstoMaxim**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1590

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Fixed unused module import and variable.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Does not need testing, small fix.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ProstoMaxim** [comment]
Reopened instead of https://github.com/apache/incubator-airflow/pull/2591

**Comment by ProstoMaxim** [comment]
Tests crushed without a reason

**Comment by Fokko** [comment]
Master is failing, this needs to be fixed first.

**Comment by ProstoMaxim** [comment]
There is no feedback in jobs logs. Could the problem be with those tests themselves? In previous pull request I had same output in 1 of containers, then I re-pushed my code, tests re-run and all of them passed.

**Comment by Fokko** [comment]
Can you rebase against master?

**Comment by ProstoMaxim** [comment]
Done

**Comment by Fokko** [comment]
LGTM +1

**Pull request closed without merging**
