### PR TITLE
ISSUE-1123 Use impyla instead of pyhs2

### PR DESCRIPTION
**Pull request by bolkedebruin**
This patch moves the dependency from pyhs2 to impyla (impala).

### CODE REVIEW

**Comment by mistercrunch** [comment]
@artwr , looks like @bolkedebruin beat you to it :), would you mind testing it in our infra and giving the thumbs up?

**Comment by bolkedebruin** [comment]
:-). @artwr you also might want to have a look at 'get_pandas_df' as impyla provides its own for this (see impyla docs), but I  am not sure if this would be compatible with Airflow. It might be faster though. I haven't checked.

**Comment by bolkedebruin** [comment]
@mistercrunch @artwr how are we doing here?

**Comment by bolkedebruin** [comment]
Is superseded by #1170

**Pull request closed without merging**
