### PR TITLE
[AIRFLOW-1352] Revert MemoryHandler change (AIRFLOW-1335)

### PR DESCRIPTION
**Pull request by saguziel**
Revert "[AIRFLOW-1335] Use MemoryHandler for buffered logging"
This reverts commit 0d23d30d6812fe1eb3cfb52d2992131cbf028062.

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1352

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes: reverts

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: revert
 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by saguziel** [comment]
@aoen @bolkedebruin

**Comment by aoen** [comment]
LGTM, I thought the user who reported this mentioned that only need to lower case a letter in a function call to fix the issue though?

**Comment by saguziel** [comment]
Yeah there's some other issue with the way the API is used that I don't have the bandwidth to fix immediately

**Comment by saguziel** [comment]
Particularly the .stream call, that I can't find any documentation for.

**Pull request closed without merging**
