### PR TITLE
Fix postgres regression

### PR DESCRIPTION
**Pull request by bolkedebruin**
This fixes the issue with postgres tests not passing. It also adds postgres to the testing, hooray for exploding builds :-).

Also a bug fix and a small change in behavior for authentication: users will now actually be created in the db and will not be created with superuser privileges anymore.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Should we do 2.7/cloudera only for sqlite and postgres?

**Comment by bolkedebruin** [comment]
Haha, I'm in doubt thinking about it. Facts & thoughts:
- CDH/HDP are not really tested against yet. To make it useful we need a mini hive cluster. Hopefully I have something coming month. CDH and HDP both have different Hive versions and CDH seems to back port fixes a bit more.
- Sqlite is not used / should not be used in production, but comes in handy for development. Sqlite did suffer from regressions and so hampers development if it doesn't work
- Postgres is first class citizen in the os world and even enterprise world is picking it up
- Python 2.7 is mainstream, but python 3 demand is picking up quickly. I expect future major releases of linux distributions to start using python 3 as a standard soon.

So for now it doesn't really matter if we disable CDH/HDP at all. For backend testing it looks nicer to me to test within the same env, but as was mentioned in the other thread having it completely separated has also benefits.

So does this answer your question? I doubt it ;-)

**Comment by mistercrunch** [comment]
Agreed, let's comment out hortonwork for now. 

Until we have a mini cluster setup, I have a way to run tests against our Hadoop environment and will do so anytime someone touches one of the related operators/hooks.

**Comment by bolkedebruin** [comment]
@mistercrunch Ok, some more bug fixes and I have limited the build matrix to CDH only now.

**Comment by mistercrunch** [comment]
Nice! Merging.

**Pull request merged**
