### PR TITLE
AIP-47 - Migrate fargate DAG to new design

### PR DESCRIPTION
**Pull request by chethanuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by josh-fell** [comment]
@chethanuk-plutoflume There seem to be a conflict to resolve. Can you take a look when you get a chance?

**Comment by potiuk** [comment]
You need to solve conflict with rebase.

**Comment by eladkal** [comment]
@chethanuk-plutoflume are you still working on this PR?

**Comment by potiuk** [comment]
If  you do @chethanuk-plutoflume -> conflicts need to be resolved after sring normalization.

**Comment by chethanuk-plutoflume** [comment]
I think

**Pull request closed without merging**
