### PR TITLE
The scripts fixing ownership and cleaning tmp use docker run

### PR DESCRIPTION
**Pull request by potiuk**
They were using docker compose, but they can be simple docker-run
scripts.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by feluelle — APPROVED** [review]

**Comment by feluelle** [comment]
You said, it is a problem on linux, but I am not using linux. So shouldn't we do this **only** for linux systems?

**Comment by potiuk** [comment]
> You said, it is a problem on linux, but I am not using linux. So shouldn't we do this **only** for linux systems?

Fix ownership - yes - it''s not needed on Linux, but clearing tmp is a universal problem. The problem is that we are mounting tmp folder from sources as well (this is needed to get dockerised gcloud/other tools working) but then it needs to be cleaned up at exit

**Comment by feluelle** [comment]
I see, I got it now. Thanks Jarek :)

**Comment by potiuk** [comment]
> > You said, it is a problem on linux, but I am not using linux. So shouldn't we do this **only** for linux systems?

Actually, I re-reviewed it and I simplified it even more. I simply added universal in-container traps for all scripts run inside the CI container that will do it automatically at exiting the container :). So no need to run it as extra step at exit. I left it only in case of the production image (there we do not run this in-container scripts) and only run it on Linux (the in-container scripts already checked the host OS).

**Comment by potiuk** [comment]
and added a few missing flags :)

**Pull request merged**
