### PR TITLE
WIP [AIRFLOW-3601] add location support to BigQuery operators

### PR DESCRIPTION
**Pull request by yohei1126**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3601
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
  - location support for BigQueryHook was merged by the PR 4324 https://github.com/apache/incubator-airflow/pull/4324
  - To support BigQuery datasets in other than US and EU, the following operators needs to be updated:
    - `bigquery_check_operator.py`
    - `bigquery_get_data.py`
    - `bigquery_operator.py`
    - `bigquery_table_delete_operator.py`
    - `bigquery_to_bigquery.py`
      - `BigQueryOperator`
      - `BigQueryCreateEmptyTableOperator`
      - `BigQueryCreateExternalTableOperator`
      - `BigQueryDeleteDatasetOperator`
      - `BigQueryCreateEmptyDatasetOperator`
    - `bigquery_to_gcs.py`
    - `gcs_to_bq.py`
    - `bigquery_sensor.py`

### Tests

- [x] My PR adds the unit tests to check location support:
    - `bigquery_to_bigquery.py`
        - `BigQueryOperator`
          - `test_bigquery_hook.py`:  https://github.com/apache/incubator-airflow/pull/4324 added test for location support of the hook.
          - `test_bigquery_operator.py`: `BigQueryOperatorTest test_bigquery_operator_location`
        - `BigQueryCreateEmptyTableOperator`
          - `test_bigquery_hook.py`: `TestBigQueryBaseCursor test_create_empty_table_with_location`. A table insert request can have location in its request body ([doc](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource)).
          - `test_bigquery_operator.py`: `BigQueryCreateEmptyTableOperatorTest test_execute`
        - `BigQueryCreateExternalTableOperator`
          - `test_bigquery_hook.py`: `TestBigQueryExternalTableSourceFormat test_table_location` A table insert request can have location in its request body ([doc](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource)).
          - `test_bigquery_operator.py`:  `BigQueryCreateExternalTableOperatorTest test_execute`
        - `BigQueryDeleteDatasetOperator`
          - `test_bigquery_hook.py`:  No test since a delete request does not have lcoation in the request body ([doc](https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/delete)). 
          - `test_bigquery_operator.py`: `BigQueryDeleteDatasetOperatorTest test_execute`
        - `BigQueryCreateEmptyDatasetOperator`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by kaxil** [comment]
Thanks, I was planning to do this. @yohei1126 Can you please add tests for all the corresponding operators.

**Comment by yohei1126** [comment]
yes working on it

**Comment by yohei1126** [comment]
@kaxil Is there any instruction to run specific test locally? I want to debug the following error.

```
======================================================================
11) ERROR: test_table_location (tests.contrib.hooks.test_bigquery_hook.TestBigQueryExternalTableSourceFormat)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/contrib/hooks/test_bigquery_hook.py line 205 in test_table_location
      cursor.create_external_table(external_project_dataset_table, schema_fields, source_uris)
    airflow/contrib/hooks/bigquery_hook.py line 499 in create_external_table
      self.service.tables().insert(
   AttributeError: 'str' object has no attribute 'tables'
```

and it is weird the test failed but the job did not fail. 
https://travis-ci.org/apache/incubator-airflow/jobs/474431499

**Comment by ron819** [comment]
@yohei1126 Yep
https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md#running-unit-tests

**Comment by yohei1126** [comment]
@ron819 Thanks!

**Comment by yohei1126** [comment]
```
$ cd $AIRFLOW_HOME
$ virtualenv env
$ source env/bin/activate
$ pip install -e .[devel]
$ pip install tox
$ tox -e py35-backend_mysql -- tests/contrib/hooks/test_bigquery_hook.py
```
got this error even after `pip install cython`
```Complete output from command python setup.py egg_info:
    /Users/01087872/Documents/incubator-airflow/.tox/py35-backend_mysql/lib/python3.5/site-packages/setuptools/dist.py:42: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w1/9cq510fj2719932_y9wpyhynh55kwm/T/pip-wheel-jatqikpp/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ImportError: No module named 'Cython'
```

**Comment by yohei1126** [comment]
sorry I am running a test locally so this works.

```
$ ./run_unit_tests.sh tests.contrib.hooks.test_bigquery_hook:TestBigQueryBaseCursor.test_cancel_queries -s --logging-level=DEBUG
```

**Comment by kaxil** [comment]
You have flake8 errors too:

```
./airflow/contrib/hooks/bigquery_hook.py:496:111: E501 line too long (115 > 110 characters)
./airflow/contrib/operators/bigquery_get_data.py:85:32: W291 trailing whitespace
./tests/contrib/hooks/test_bigquery_hook.py:195:19: E225 missing whitespace around operator
./tests/contrib/hooks/test_bigquery_hook.py:196:19: E225 missing whitespace around operator
./tests/contrib/hooks/test_bigquery_hook.py:197:39: E225 missing whitespace around operator
./tests/contrib/hooks/test_bigquery_hook.py:198:22: E225 missing whitespace around operator
./tests/contrib/hooks/test_bigquery_hook.py:198:111: E501 line too long (119 > 110 characters)
./tests/contrib/hooks/test_bigquery_hook.py:199:20: E225 missing whitespace around operator
./tests/contrib/hooks/test_bigquery_hook.py:436:1: E302 expected 2 blank lines, found 1
./tests/contrib/operators/test_bigquery_operator.py:53:1: E302 expected 2 blank lines, found 1
./tests/contrib/operators/test_bigquery_operator.py:117:1: E302 expected 2 blank lines, found 1
./tests/contrib/operators/test_bigquery_operator.py:136:1: E302 expected 2 blank lines, found 1
./tests/contrib/operators/test_bigquery_operator.py:261:5: E303 too many blank lines (2)
```

**Comment by ron819** [comment]
Can you squash all commits?

**Comment by yohei1126** [comment]
fixed flake8 errors

**Comment by yohei1126** [comment]
sorry recreated a PR https://github.com/apache/airflow/pull/4448

**Pull request closed without merging**
