### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by jlowin**
- Split configuration into its own file (this was getting too big for the “installation” file)
- Add links to README

### CODE REVIEW

**Comment by mistercrunch** [comment]
Looks good, did you test that the docs are building ok and looking good?

**Comment by jlowin** [comment]
Good to go

**Comment by jlowin** [comment]
Actually one sec! there's a line about Airflow only being tested under 2.7 that I want to remove.

**Comment by jlowin** [comment]
Ok, done.

**Pull request merged**
