### PR TITLE
Have sshd send logs/output to stderr

### PR DESCRIPTION
**Pull request by ashb**
We don't need to detatch or background it, as sshd does that by default

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
This might give us a clue as to what the problem is? 🤞🏻

**Comment by ashb** [comment]
Well that's unexpected. By running it this way.... it's not erroring? I'll double check and re-run a couple of times, and if that is the case try running without putting logs to stderr (which messes up the test output a bit)

**Comment by ashb** [comment]
I don't think this does anything actually -- main and PRs aren't failing with this SSH error anymore

**Comment by uranusjr** [comment]
Probably just GitHub having issues. Looking back this seems to coincide with their recent downtime?

**Comment by potiuk** [comment]
> Probably just GitHub having issues. Looking back this seems to coincide with their recent downtime?

I don't think so. The downtime was very short (20 minutes or so) and it started to appear long time before (3-4 days ago). It could have been caused by some changes on the server side. I suspected lack of entropy on the server (that might cause the ssh server to start up for minutes while the keys are generated) but this issue with SSH started to appear about the same time on both Public Runners and our Self-hosted runners, so I suspect this is really some side-effect of other tests we run.

**Pull request closed without merging**
