### PR TITLE
[AIRFLOW-6886] Cleanup the SageMakerTrainingOperator result

### PR DESCRIPTION
**Pull request by BasPH**
The SageMakerTrainingOperator returns the response of `hook.describe_training_job()` wrapped in a dict with key `Training`. I don't see it used anywhere in the codebase, nor anywhere on the internet, so I suggest to simplify the result and return the JSON returned by `hook.describe_training_job()`.

Before:

```python
{
    'Training': {... SageMaker result here ...}
}
```

After:
```python
{... SageMaker result here ...}
```

This way, you avoid one useless step processing the results:

```python
# before
jobname = result["Training"]["TrainingJobName"]
# after
jobname = result["TrainingJobName"]
```

---
Issue link: [AIRFLOW-6886](https://issues.apache.org/jira/browse/AIRFLOW-6886)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Review by kaxil — APPROVED** [review]
Strange, not sure why "Training" was used ! I see this was added in https://github.com/apache/airflow/commit/ae39df5101e4e6f2c22568d87c1a42a87658eba8 @yangaws @ashb Any ideas?

**Comment by ashb** [comment]
Can't see an obvious reason for this, I'll ping Yang via email too in case he doesn't see the GitHub notification

**Comment by ashb** [comment]
The reason is for consistency with the rest of the suite of Sagemaker operators:

> I guess the CR author is only using SageMaker training operator. So this ‘Training’ field is weird and unnecessary to him. But if you look at other SageMaker operators, for example the batch transform one (https://github.com/apache/airflow/blob/1a9d218611502118132a93b0c12c1ad511cbdd6e/airflow/providers/amazon/aws/operators/sagemaker_transform.py#L117-L123) , it has two description results. So we definitely need a ‘Model’ field and a ‘Transform’ field here. And to make all SageMaker operators being consistent in the result format, I just had that ‘Training’ field although there’s only one description result.
>
> In this case I personally value consistency over cleanness (otherwise I won’t write it that way). So I don’t recommend to remove this ‘Training’ key although it’s useless. However if you guys think it’s better to remove it according to Airflow culture. I totally respect it. Just let Yuan Zha [Ed: member of the Sagemaker team at AWS, I have his email] knows this. He has more information on the impact of this change (whether customer’s workflow will be broken) and can stand for Amazon better than I can.

What do you think @BasPH? I think I'm leaning to a -0 after this clarification.

**Comment by kaxil** [comment]
> The reason is for consistency with the rest of the suite of Sagemaker operators:
> 
> > I guess the CR author is only using SageMaker training operator. So this ‘Training’ field is weird and unnecessary to him. But if you look at other SageMaker operators, for example the batch transform one (https://github.com/apache/airflow/blob/1a9d218611502118132a93b0c12c1ad511cbdd6e/airflow/providers/amazon/aws/operators/sagemaker_transform.py#L117-L123
> > ) , it has two description results. So we definitely need a ‘Model’ field and a ‘Transform’ field here. And to make all SageMaker operators being consistent in the result format, I just had that ‘Training’ field although there’s only one description result.
> > In this case I personally value consistency over cleanness (otherwise I won’t write it that way). So I don’t recommend to remove this ‘Training’ key although it’s useless. However if you guys think it’s better to remove it according to Airflow culture. I totally respect it. Just let Yuan Zha [Ed: member of the Sagemaker team at AWS, I have his email] knows this. He has more information on the impact of this change (whether customer’s workflow will be broken) and can stand for Amazon better than I can.
> 
> What do you think @BasPH? I think I'm leaning to a -0 after this clarification.

We we plan to revert the change in this PR, we should change this PR to add "comments" above the response so that the future users know why it is here

**Comment by BasPH** [comment]
Makes sense, let's leave it. I can update this PR to undo the changes and simply add a comment with this explanation.

**Review by feluelle — COMMENTED** [review]
+1 for a comment

**Pull request closed without merging**
