### PR TITLE
[AIRFLOW-2609] Fixed behavior of BranchPythonOperator

### PR DESCRIPTION
**Pull request by SandroLuck**
Current behavior: When you Branch from A  e.g. the BranchPythonOperator '->' (B or C,), and you make some B '->' C as well. The current behavior is that C will be skipped even though it's a downstream task of B.
To avoid this behavior this fix will check that only tasks which are not in the downstream of the branch are skipped. I think using this behavior the BranchyPythonOperator is more useful and behaves as expected.

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2609
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
No UI Changes description as above

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Same tests should apply

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by SandroLuck** [comment]
Deleted my old pull req because it had too many commits and it should be easier to understand like this

**Comment by SandroLuck** [comment]
This is a clean version of https://github.com/apache/incubator-airflow/pull/3495

**Comment by SandroLuck** [comment]
@Noremac201  @Fokko could you check this out again?

**Comment by Noremac201** [comment]
Be sure to re-add [AIRFLOW-2609] to your title.
I'd also add a test if I were you to make sure this behaves correctly in the future.

**Review by ashb — CHANGES_REQUESTED** [review]
Yes - this is going to need tests adding to make sure (what sounds like fairly critical behaviour) doesn't break again

**Comment by SandroLuck** [comment]
I'll have a look at it

**Pull request closed without merging**
