### PR TITLE
[AIRFLOW-61] Fix corner case with joining processes/queues

### PR DESCRIPTION
**Pull request by jlowin**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
https://issues.apache.org/jira/browse/AIRFLOW-61

### CODE REVIEW

**Comment by bolkedebruin** [comment]
+1, LGTM

Please elaborate on your commit why this is required.

**Comment by mistercrunch** [comment]
For the record @plypaul and I spoke on whether we want to keep the current joining logic in the future, which has then inconvenience on making the overall scheduler cycle as slow as the slowest DAG to process, or to change it in favor of an approach that would ship with whatever is ready to go on a predetermined schedule.

We'd like to insure that the sane DAGs aren't held up by the insane ones.

**Comment by jlowin** [comment]
@mistercrunch good thought. The scheduler could in theory just let its worker processes stay alive forever, constantly parsing DAGs and passing tasks back to the main process for executing. That would be a relatively minor change I think.

(and just to clarify for any future viewers of this thread -- this PR just corrects an edge case in the existing behavior)

**Comment by schnie** [comment]
Hey everyone.  I'm trying to get airflow working in production, but for some reason the scheduler stops working after a few hours.  I've added some more detailed logging and have tracked the issue back to the `while any(j.is_alive() for j in jobs):` loop introduced in this PR.  For some reason, after running fine for hours, the main process will get stuck in this loop.  I can run `top` on my airflow scheduler container and can see that the child process actually spawns, while the main process is looping endlessly using about 100% CPU.  From what I can tell, the `_do_dags` target function never actually runs when this happens.  Any ideas?

**Comment by bolkedebruin** [comment]
@schnie provide sample dag that exhibits this. Then it will become much easier to track this down. Next to that please create a Jira issue for it and provide as much info as you can

**Pull request merged**
