### PR TITLE
Fix rest API logging

### PR DESCRIPTION
**Pull request by bbovenzi**
Part of https://github.com/apache/airflow/issues/22352

Try to improve action logging in the REST API. Include `api.{name_of_function}`. We should probably try to capture more information for `extra` but audit log now reads like so:

Screenshot 2024-02-20 at 11 15 15 PM

This is a draft to get feedback on the format and then I will do it for basically all PATCH, PUT, POST, DELETE endpoints

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vincbeck** [comment]
LGTM

**Review by hussein-awala — APPROVED** [review]
LGTM

**Review by dstandish — APPROVED** [review]

**Comment by bbovenzi** [comment]
Made `extra` a json object instead of a tuple. Added request body to `extra`. And hiding sensitive fields for connections and variables:

Screenshot 2024-02-21 at 9 49 41 PM

**Review by dirrao — APPROVED** [review]

**Comment by jscheffl** [comment]
Looks good for me!

**Comment by bbovenzi** [comment]
Closing in favor of https://github.com/apache/airflow/pull/37734

I want to leave changes to variables+connections API and the `extra` field as a separate effort

**Pull request closed without merging**
