### PR TITLE
[AIRFLOW-3187] Update airflow.gif file with a slower version

### PR DESCRIPTION
**Pull request by PaulVelthuis93**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

https://issues.apache.org/jira/browse/AIRFLOW-3187

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The Airflow gif is extremely fast, this can be annoying. For this reason I would like to propose to make it slower. Also for people who can't handle fast changing pictures this can lead to pain in the eyes.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @PaulVelthuis93! Can you open a Jira ticket with the same description as the PR? Cheers

>

**Comment by PaulVelthuis93** [comment]
Hello Fokko,
Here is the link to the Jira issue:
https://issues.apache.org/jira/browse/AIRFLOW-3187

Have I done the linking correctly, or should it be linked differently with Jira?
best,
Paul Velthuis

**Comment by Fokko** [comment]
Thanks @PaulVelthuis93 

Can you rework the commit message, by prepending it with `[AIRFLOW-3187]`. https://help.github.com/articles/changing-a-commit-message/

**Comment by PaulVelthuis93** [comment]
@Fokko  I renamed the git commit message. Thanks for the remark

**Comment by Fokko** [comment]
Thanks @PaulVelthuis93

**Pull request merged**
