### PR TITLE
[AIRFLOW-4829] More descriptive exceptions for EMR sensors

### PR DESCRIPTION
**Pull request by jzucker2**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-4829\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4829
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-4829\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

My PR adds unit tests for EmrStepSensor and EmrJobFlowSensor

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
@jzucker2 I think this is good - but could you give a full example of what this exception message now looks like?

**Comment by jzucker2** [comment]
@ashb something like this:

```
Exception:
EMR job failed for code: BOOTSTRAP_FAILURE with message Master instance (i-02c25cade3cbfc453) failed attempting to download bootstrap action 1 file from S3
```

```
[2019-06-21 17:02:56,781] {emr_base_sensor.py:33} INFO - Job flow currently TERMINATED_WITH_ERRORS
[2019-06-21 17:02:56,799] {__init__.py:1580} ERROR - EMR job failed for code: BOOTSTRAP_FAILURE with message Master instance (i-02c25cade3cbfc453) failed attempting to download bootstrap action 1 file from S3
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/sensors/base_sensor_operator.py", line 108, in execute
    while not self.poke(context):
  File "/usr/local/lib/python2.7/dist-packages/airflow/sensors/emr_base_sensor.py", line 43, in poke
    raise AirflowException(final_message)
AirflowException: EMR job failed for code: BOOTSTRAP_FAILURE with message Master instance (i-02c25cade3cbfc453) failed attempting to download bootstrap action 1 file from S3
[2019-06-21 17:02:56,801] {__init__.py:1603} INFO - Marking task as UP_FOR_RETRY
[2019-06-21 17:02:57,012] {logging_mixin.py:95} INFO - [2019-06-21 17:02:57,011] {sendgrid.py:107} INFO - Email with subject Airflow alert: <TaskInstance: hourly_blocks_setup_integration_v1.job_flow_sensor 2019-06-21T16:52:17.574713+00:00 [up_for_retry]> is successfully sent to recipients: [{'to': [{'email': u'test@test.com'}, {'email': u'test2@test.com'}]}]
[2019-06-21 17:02:57,030] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor Traceback (most recent call last):
[2019-06-21 17:02:57,031] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/bin/airflow", line 32, in <module>
[2019-06-21 17:02:57,031] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     args.func(args)
[2019-06-21 17:02:57,031] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-06-21 17:02:57,031] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     return f(*args, **kwargs)
[2019-06-21 17:02:57,031] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 523, in run
[2019-06-21 17:02:57,032] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     _run(args, dag, ti)
[2019-06-21 17:02:57,032] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 442, in _run
[2019-06-21 17:02:57,032] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     pool=args.pool,
[2019-06-21 17:02:57,033] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/utils/db.py", line 73, in wrapper
[2019-06-21 17:02:57,033] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     return func(*args, **kwargs)
[2019-06-21 17:02:57,033] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2019-06-21 17:02:57,034] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     result = task_copy.execute(context=context)
[2019-06-21 17:02:57,034] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/sensors/base_sensor_operator.py", line 108, in execute
[2019-06-21 17:02:57,034] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     while not self.poke(context):
[2019-06-21 17:02:57,034] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor   File "/usr/local/lib/python2.7/dist-packages/airflow/sensors/emr_base_sensor.py", line 43, in poke
[2019-06-21 17:02:57,035] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor     raise AirflowException(final_message)
[2019-06-21 17:02:57,035] {base_task_runner.py:101} INFO - Job 67389: Subtask job_flow_sensor airflow.exceptions.AirflowException: EMR job failed for code: BOOTSTRAP_FAILURE with message Master instance (i-02c25cade3cbfc453) failed attempting to download bootstrap action 1 file from S3
[2019-06-21 17:02:58,890] {logging_mixin.py:95} INFO - [2019-06-21 17:02:58,890] {jobs.py:2562} INFO - Task exited with return code 1
```

**Comment by jzucker2** [comment]
@ashb would you like me to put that example somewhere in the project? Or is this pull request enough?

If you notice, I updated existing unit tests and added some new ones for the `EmrBaseSensor`, `EmrJobFlowSensor`, and `EmrStepSensor`

**Comment by ashb** [comment]
Oh nice. I just wanted to see what they looked like, I don't think we need them in the code anywhere.

**Pull request merged**
