### PR TITLE
Remove note about Python 3.10 support availability

### PR DESCRIPTION
**Pull request by gmsantos**
Airflow 2.3+ is released with Python 3.10 official support already.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
While we’re at it, perhaps it’s time to investigate into 3.11 support 😃

**Comment by uranusjr** [comment]
Breeze detection in the basic checks job seems broken. Failure unrelated.

**Comment by potiuk** [comment]
Detection is fine. It's the "basic static checks" job  has wrong sequence of steps (first setup python then checkout). Fixing it in a PR in a moment.

**Comment by potiuk** [comment]
> While we’re at it, perhaps it’s time to investigate into 3.11 support 😃

I would not have high hopes. We have a lot of dependencies and historically they will need time to catch-up :)

**Comment by potiuk** [comment]
Rebased after merging #24864 to see if it works :)

**Pull request merged**
