### PR TITLE
[AIRFLOW-XXX] Add FullContact to list of companies that use airflow

### PR DESCRIPTION
**Pull request by shamin**
Add FullContact to README.md

### CODE REVIEW

**Comment by r39132** [comment]
@shaminmeerankutty Why not include your github handle? The handle should be a point of contact, not necessarily a contributor, at a company.

**Comment by shamin** [comment]
@r39132 Is it okay to leave it empty. I just want to add that my company uses airflow and I am not directly involved in usage of airflow in my company.

**Comment by r39132** [comment]
Sure. I'll merge it. You should probably ask the folks who do manage it at your company if they can submit a PR to add their handles.

**Comment by shamin** [comment]
@r39132 Thanks, Sure will do that.

**Pull request merged**
