### PR TITLE
Initial implementation of new airflow provider for Teradata with Teradata Hook, Teradata Operator and Teradata to Teradata Transfer Operator.

### PR DESCRIPTION
**Pull request by sc250072**
* Initial implementation of new airflow provider for Teradata with Teradata Hook, Teradata Operator and Teradata to Teradata Transfer Operator.
* Ran static checks through airflow pre-commit before commit each change and before final PR raise to airflow.
* Ran Teradata provider unit and system tests locally before committing the changes and on teradata forked workflow. https://github.com/Teradata/airflow/actions/workflows/ci-teradata.yml
* Built the Teradata provider documentation using breeze build-docs.

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
Before looking at that and spending any time on it by anyone, you should be aware @SatishChGit  that you need to get approval on the devlist to contibute a new provider. 

Read this: https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers

And follow it. Note that in case of external services that have enough of the resources and possibly teams that can manage their providers, we have strong preference that they release and manage the providers on their own - we have no experience nor will to manage 3rd-party providers in the community unless the 3rd-party  will convince us that it's a good idea and convince us they will continue spending time on contributing and managing their implementation.

One of the big and important prerequisites is have a 3rd-party provide and commits to maintaining of system tests that they will run and dashboards such as https://airflow.apache.org/ecosystem/#airflow-provider-system-test-dashboards

Thre were a few discussions in the recent past wher we refused to accept such 3rd-party providers - for us such code increases maintenance burden and we generally prefer that the 3rd-parties do that on their own (especially when they are big and established providers like Teradata.

Example discussion about it here where we refused to accept such a provider (it has link to previous discussions) https://lists.apache.org/thread/f5tk9c734wlyv616vyy8r34ymth3dqbc

Here example discussion where decided to accept them (where Astronomer committed to maintenance, and made an effort to build and run their system dashboard for LLM-related providers: 

https://lists.apache.org/thread/0d669fmy4hn29h5c0wj0ottdskd77ktp

Read all that, also try to search the devlist for similar discussions and see which path you want to follow. If you would like to still contribute it, you should start with discussion on the devlist proposing it and explaining why you think we should accep the new provider.

**Comment by sunilkmallam** [comment]
> Before looking at that and spending any time on it by anyone, you should be aware @SatishChGit that you need to get approval on the devlist to contibute a new provider.
> 
> Read this: https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers
> 
> And follow it. Note that in case of external services that have enough of the resources and possibly teams that can manage their providers, we have strong preference that they release and manage the providers on their own - we have no experience nor will to manage 3rd-party providers in the community unless the 3rd-party will convince us that it's a good idea and convince us they will continue spending time on contributing and managing their implementation.
> 
> One of the big and important prerequisites is have a 3rd-party provide and commits to maintaining of system tests that they will run and dashboards such as https://airflow.apache.org/ecosystem/#airflow-provider-system-test-dashboards
> 
> Thre were a few discussions in the recent past wher we refused to accept such 3rd-party providers - for us such code increases maintenance burden and we generally prefer that the 3rd-parties do that on their own (especially when they are big and established providers like Teradata.
> 
> Example discussion about it here where we refused to accept such a provider (it has link to previous discussions) https://lists.apache.org/thread/f5tk9c734wlyv616vyy8r34ymth3dqbc
> 
> Here example discussion where decided to accept them (where Astronomer committed to maintenance, and made an effort to build and run their system dashboard for LLM-related providers:
> 
> https://lists.apache.org/thread/0d669fmy4hn29h5c0wj0ottdskd77ktp
> 
> Read all that, also try to search the devlist for similar discussions and see which path you want to follow. If you would like to still contribute it, you should start with discussion on the devlist proposing it and explaining why you think we should accep the new provider.

Hey Jarek @potiuk,

I'm Sunil Mallam, a Staff Product Manager at Teradata. I and Satish have had a few discussions with Kaxil about creating a proposal for becoming a Community Provider. I've actually reached out to him, but looks like he's away on a personal situation.

Our main goal to be a community provider is for Teradata's customers (approx. 700 of Fortune1000) to be confident in the quality and stability of the operators.

We have a team of engineers who are dedicated to build and support Third Party Connectors/Tools, which would make our contributions to Airflow consistent, i.e. end-to-end testing and adding/running relevant "system tests" with every upgrade (which we have considered for the initial implementation). Satish is working on the dashboard and we'd share the dashboard link shortly.

I will also send an official email to Kaxil with the proposal and the dashboard link, for review. Would you want me to include you in the email as well?

**Comment by potiuk** [comment]
As explained in my comment. It's not me or @kaxil you need to reach out to. Decisions here are not made by me or him - they are made on devlist. And it's the people at the devlist you need to convince, not me and not here. 

Our process is very clear on that - the devlist is the place where you need to first announce your intention, explain why and gain the approval.

**Comment by potiuk** [comment]
> As explained in my comment. It's not me or @kaxil you need to reach out to. Decisions here are not made by me or him - they are made on devlist. And it's the people at the devlist you need to convince, not me and not here.
> 
> Our process is very clear on that - the devlist is the place where you need to first announce your intention, explain why and gain the approval.

And just to put this all in perspective - if you look here https://airflow.apache.org/ecosystem/#third-party-airflow-plugins-and-providers  you will see that there are a LOT of providers - including those companies from Fortune 700 companies  - where they maintain their own providers.

So before you reach out to the devlist I also suggest you to read the links I posted.

For us (community) - taking code for maintenance is more often liability than asset. If you have dedicated team of engineers who want to work on providers - it will be generally easier for you to release and maintain it on your own. 

So I think you have to have a very good reason to convince the community that your provider is better in community than with your team.

**Comment by sunilkmallam** [comment]
> As explained in my comment. It's not me or @kaxil you need to reach out to. Decisions here are not made by me or him - they are made on devlist. And it's the people at the devlist you need to convince, not me and not here.
> 
> Our process is very clear on that - the devlist is the place where you need to first announce your intention, explain why and gain the approval.

We totally understand, Jarek. All we're looking for from you or Kaxil is, to understand what's the medium to present our case to devlist. Is it here along with the PR or an email or any other way?

**Comment by potiuk** [comment]
> > As explained in my comment. It's not me or @kaxil you need to reach out to. Decisions here are not made by me or him - they are made on devlist. And it's the people at the devlist you need to convince, not me and not here.
> > Our process is very clear on that - the devlist is the place where you need to first announce your intention, explain why and gain the approval.
> 
> We totally understand, Jarek. We're aware from our earlier conversations that our approval is subject to a review/evaluation from the devlist. All we're looking for from you or Kaxil is, to understand what's the medium to present our case to devlist. Is it an email to [dev-subscribe@airflow.apache.org](mailto:dev-subscribe@airflow.apache.org)?

Actually email and discussion thread to dev@airflow.apache.org. If you spend a little bit of time and read all that I wrote above, I pointed you at the past devlist threads that were discssing it. And I STRONGLY recommend to do the reading, look at the past discussions - and actually read the links I posted - where you have everything explained (if you actually read it that is).

**Pull request closed without merging**
