### PR TITLE
Add `active_deadline_seconds` parameter to `KubernetesPodOperator`

### PR DESCRIPTION
**Pull request by amoghrajesh**
Building on top of https://github.com/apache/airflow/pull/31146 to introduce the `active_deadline_seconds` for airflow KPO launched job pods.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by Lee-W — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Needs conflict resolution and fixes in tests ...

**Comment by amoghrajesh** [comment]
@potiuk I fixed the tests as well as rebased it. Can you take a look when free?

**Review by hussein-awala — APPROVED** [review]
I pushed a commit hoping it might fix the failed test. LGTM

**Review by aritra24 — APPROVED** [review]

**Comment by amoghrajesh** [comment]
@hussein-awala seems like the commit didn't do the trick here. I pushed a new fix now, might just do the trick now

**Comment by potiuk** [comment]
Nope. Seems like it break our K8S tests. FYI. There is a recipe how to setup the environment for K8S tests locally with breeze including step-by-step explanation and example (and Breeze's k8s is really a wizard-like  setup that hand-holds you while setting the environment up). 

https://github.com/apache/airflow/blob/main/TESTING.rst#kubernetes-tests

**Comment by hussein-awala** [comment]
:tada:

**Comment by amoghrajesh** [comment]
Silly mistake by me. Thanks Hussein!

**Comment by andyfcx** [comment]
Thanks @amoghrajesh

**Pull request merged**
