### PR TITLE
Add support for three-legged OAuth for Google connections. Useful for…

### PR DESCRIPTION
**Pull request by criccomini**
… developer-mode.

### CODE REVIEW

**Comment by criccomini** [comment]
This makes using Airflow with Google cloud pretty neat. When in developer-mode, you can spin up a local instance, and use `gcloud auth` to authenticate yourself. From there, you can query Google projects that you have access to.

**Comment by criccomini** [comment]
Confused as to why the build fails. The CI says `command successful`, and the coverage decreased -0.0%.

**Comment by criccomini** [comment]
Re-opened PR to see if a new execution will be triggered.

**Comment by criccomini** [comment]
OK, now it says -0.06%. Assuming this is because I added some new lines. Given that this is in contrib, and no one (other than me) is using it right now, I would argue that it's OK to merge in. I do have an open task to add some tests to this, but I don't want to block on it if that's OK.

**Comment by mistercrunch** [comment]
:+1:

**Pull request merged**
