### PR TITLE
Add support for envFrom in helm chart

### PR DESCRIPTION
**Pull request by FloChehab**
Hi,

I am doing more testing with the great airflow helm chart, and there is this small thing regarding env configuration that I think would be nice to improve.

I am not sure how the helm chart is tested, so I haven't added tests.

-----

Add support for envFrom in helm chart

* Adds 2 configurable values in the helm chart:
    * `envFromConfigMap` so that we can use a configMap for all env configuration can now move it outside of helm for instance)

    * `envFromSecret` so that we can use a secret for further env configuration can now move it  outside of helm for and prevent secrets from being in the pod's configuration)

"Automated" airflow configuration for kubernetes executor in the chart also updated accordingly.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by FloChehab** [comment]
Also,

regarding:
> "Automated" airflow configuration for kubernetes executor in the chart also updated accordingly.

I am not using the KubernetesExecutor, nor am I familiar with its configuration. I've done my best based on the existing logic in the helm chart and airflow default config file; I hope it's ok.

**Review by dimberman — DISMISSED** [review]

**Comment by FloChehab** [comment]
Hi @dimberman, just tested with the kubernetes executor. Everything looks good to me ; the "automated" injection for Secrets / ConfigMaps works as expected. There is just one weird thing going on (not related to this PR I think): Secrets get included twice (only once, as execpected, for the CMs).

For instance if in the scheduler pod we have:
```yaml
env:
    - name: AIRFLOW__KUBERNETES__ENV_FROM_SECRET_REF
      value: mysecret,mysecret2
    - name: AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF
      value: test-airflow,test-airflow2
```

In the pod created by the executor, I have:
```yaml
    envFrom:
    - configMapRef:
        name: test-airflow
    - configMapRef:
        name: test-airflow2
    - secretRef:
        name: mysecret
    - secretRef:
        name: mysecret2
    - secretRef:
        name: mysecret
    - secretRef:
        name: mysecret2
```

**Comment by FloChehab** [comment]
Not really stale, waiting for review.

**Comment by mik-laj** [comment]
Hi. We currently want to significantly simplify KubernetesExecutor/KubernetesPodOperators and delete many configuration options.  https://lists.apache.org/thread.html/rb1bcafea1b8f86e6d155aea7169c05805f7021e90f1636afc8019074%40%3Cdev.airflow.apache.org%3E
For this reason, it seems to me that your change is not very useful. Can you make sure that the appropriate features options can be passed using pod_template_file?
https://github.com/apache/airflow/blob/master/chart/values.yaml#L636

**Comment by mik-laj** [comment]
I don't know if we should adopt a more generic approach to `EnvFrom`.
https://github.com/apache/airflow/pull/11426/files
https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart
What do you think?

**Comment by FloChehab** [comment]
> I don't know if we should adopt a more generic approach to `EnvFrom`.
> https://github.com/apache/airflow/pull/11426/files
> https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart
> What do you think?

Hello,

The second link look pretty nice to me and I was initially going for something like that if I remember well.
The issue was about the integration with the KubernetesExecutor.

In my emails, I can see another comment of yours linked to that (that I guess you have deleted since):

> Hi. We currently want to significantly simplify KubernetesExecutor/KubernetesPodOperators and delete many configuration options. https://lists.apache.org/thread.html/rb1bcafea1b8f86e6d155aea7169c05805f7021e90f1636afc8019074%40%3Cdev.airflow.apache.org%3E
For this reason, it seems to me that your change is not very useful. Can you make sure that the appropriate features options can be passed using pod_template_file?
https://github.com/apache/airflow/blob/master/chart/values.yaml#L636

So what would you recommend ?
* Refactoring to use something like  https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart and ignoring the kubernetes executor ?
* Doing the first point ; but doing the integration with the KubernetesExecutor another way ?
* Something else ?

**Comment by FloChehab** [comment]
Hello @mik-laj / @dimberman , I have the following proposition to make (inspired by https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart) (i'll start from scratch again if this proposition sounds good to you):

1. Creating ConfigMaps & secrets from the chart:

  * adding the value `extraSecrets`:
    ```yaml
    secrets:
      airflow-connections:
        stringData:
          AIRFLOW_CONN_GCP: '...'
          AIRFLOW_CONN_INTERNAL_DB: '...'
      other-secret-variables:
        stringData:
          SECRET_VAR_1: '...'
          SECRET_VAR_2: '...'
    ```

    Which would yield 2 secrets:
    ```yaml
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: airflow-connections
      ...
    stringData:
      AIRFLOW_CONN_GCP: '...'
      AIRFLOW_CONN_INTERNAL_DB: '...'

    ---
    apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: other-secret-variables
      ...
    stringData:
      SECRET_VAR_1: '...'
      SECRET_VAR_2: '...'
    ```
    Those secrets would be mounted with envFrom.

  * adding the value `extraConfigMaps`, with exactly the same idea.

  * For the support of the kubernetes executor, I'll add the envFrom in pod template and nothing more (so no support for previous airflow versions and the old configuration)

  This should be the best in terms of flexibility without getting too complex.

2. Adding the value `extraEnv` & `extraEnvFrom`, which would use the standard `env` & `envFrom` syntax (again not supporting the "old" KubernetesExecutor configuration).

Given all of this and if we decide to drop the support for the old KubernetesExecutor configuration, we could remove the `env` and `secret` values from this chart (and do a lot cleaning in the helpers).

**Comment by FloChehab** [comment]
Hello @mik-laj & @dimberman,

I've taken a bit of time today to work on the proposition above and have implemented the first part which is to enable the provisioning of (extra)ConfigMaps and (extra)Secrets from this chart in a "generic way": https://github.com/MeilleursAgents/airflow/commit/7d52a8a6caff75ecd8d643070ed8772594f5a10d (it can be a bit annoying to provision them separately from airflow itself).

I plan on working on the second part (adding `extraEnv` & `extraEnvFrom` to use the secrets/configmaps created by `extraSecrets`/`extraConfigMap` -or any other mean-) in the coming days.

Does this change sounds good to you ?
Would you like me to open a PR for the first part ; or should I aim towards putting both part in the same PR ?

Thanks.

**Comment by FloChehab** [comment]
Hello, I've create a new PR for the new solution I was describing: #12164

**Pull request closed without merging**
