### PR TITLE
Google Cloud Providers - Introduce GoogleCloudBaseOperator

### PR DESCRIPTION
**Pull request by IKholopov**
As part of addressing #28751 the GoogleCloudBaseOperator is introduced to have common fix for all Google Cloud operators.

Refactored to a separate PR per @potiuk request.

### CODE REVIEW

**Review by dimberman — APPROVED** [review]

**Comment by dimberman** [comment]
LGTM if the tests pass we can merge. That said if you could please add some context at the top.  I realize that there is more info in the ticket but it would be nice to have a few sentences here as well to give larger context so future users who are running git blame don't have to dive through a hyperlink rabbithole to find out why this change was made.

**Comment by potiuk** [comment]
> LGTM if the tests pass we can merge. That said if you could please add some context at the top. I realize that there is more info in the ticket but it would be nice to have a few sentences here as well to give larger context so future users who are running git blame don't have to dive through a hyperlink rabbithole to find out why this change was made.

yep. Fully agree. Context is important.

**Comment by potiuk** [comment]
(best is to squash the commits and rebase on top of the main and add good description).

**Review by potiuk — APPROVED** [review]

**Comment by IKholopov** [comment]
> (best is to squash the commits and rebase on top of the main and add good description).

I've added a detailed description to the commit, let me know if you meant any other place to put description in (I am not too familiar with how GitHub merges PR/commit chain messages)

**Review by eladkal — APPROVED** [review]

**Pull request merged**
