### PR TITLE
openlineage: tests: do not check whitespace in returned SQL statement after splitting it

### PR DESCRIPTION
**Pull request by mobuchowski**
It's not important to check whether whitespace exactly matches in SQL statements after formatting it.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Reopened with "full-tests-needed"

**Review by vincbeck — APPROVED** [review]

**Comment by potiuk** [comment]
Still does not work :( same as my local

`breeze testing tests --test-type "Providers[openlineage]" --force-lowest-dependencies`

**Comment by mobuchowski** [comment]
@potiuk @vincbeck turns out `sqlparse` has some breaking changes for this between 0.5.0 and 0.5.1 releases. 

We don't really care whether there's some spaces at the end of some statements - I rewrote this test to just compare the SQL strings with all whitespace removed - as Jarek suggested before.

**Comment by vincbeck** [comment]
> @potiuk @vincbeck turns out `sqlparse` has some breaking changes for this between 0.5.0 and 0.5.1 releases.
> 
> We don't really care whether there's some spaces at the end of some statements - I rewrote this test to just compare the SQL strings with all whitespace removed - as Jarek suggested before.

Looking good! Thanks :)

**Pull request merged**
