### PR TITLE
[AIRFLOW-358][AIRFLOW-430] Add `connections` cli command

### PR DESCRIPTION
**Pull request by PedroMDuarte**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-358](https://issues.apache.org/jira/browse/AIRFLOW-358)
- [AIRFLOW-430](https://issues.apache.org/jira/browse/AIRFLOW-430)

Testing Done:
- core.CliTests.test_cli_connections_list
- core.CliTests.test_cli_connections_add_delete
- Travis CI tests pass on my branch
- Also tested functionality in a Docker airflow deploy.

### CODE REVIEW

**Comment by PedroMDuarte** [comment]
Here are a couple of screenshots that show the functionality

screen shot 2016-09-17 at 1 54 51 pm

screen shot 2016-09-17 at 1 57 42 pm

**Comment by PedroMDuarte** [comment]
Also, I just realized that I left a change in there that is not necessary.  I defined a `_types` variable in the `Connection` model which is only used in the webserver view.  It makes sense to me to leave the definition of _types in under the `Connection` model,  but if it is deemed out of scope I can take it back.

**Comment by msumit** [comment]
@PedroMDuarte +1 for taking connections list out of view and putting it under model.

**Comment by msumit** [comment]
@PedroMDuarte Plz follow the 50/72 rules for commit messages, i.e. commit heading should not be longer than 50 chars. You can write detailed description with each line limited to 72 chars.

**Comment by PedroMDuarte** [comment]
@msumit Thanks for the feedback!  Just updated the commit message.

**Comment by r39132** [comment]
@jgao54 Did you also have a similar PR? Just an FYI.

**Comment by r39132** [comment]
@PedroMDuarte Sorry for the delay! I'd like to merge your changes. Are you planning on taking out the `_types` variable?

**Comment by PedroMDuarte** [comment]
Hi @r39132 ,  in my opinion the `_types` variable has a better home in the models.   But since it is unrelated to the connections CLI functionality that was implemented I would be happy to revert that change.  Let me know what you think.  Also I will go ahead and rebase this within the next hour or so.

**Comment by msumit** [comment]
IMO models are the best place for such information. It also helps in keeping the code DRY. If someday we've to transfer these information to a db table, then it would be straight as well.

**Comment by r39132** [comment]
+1 Sorry for the delay!

**Comment by r39132** [comment]
@PedroMDuarte +1 Sorry for the delay. Merging.

**Pull request closed without merging**
