### PR TITLE
Revert "Randomize pod name (#12117)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 7825be50d80d04da0db8fcee55df5e1339864c88.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @szczeles -> I revert this one for now if it proves that the recent failures of one of the K8S tests are caused by it (it's very likely).  The root cause was that the K8S tests were not running in the PR with such a localized change (bug in the selective checks definition). It's been since fixed. 

The failing test was TestKubernetesPodOperatorSystem.test_pod_failure() and this is an Integration test with actual K8S cluster run via Kind.

I have a kind request if that proves to be true @szczeles. Could you please recreate the PR and fix the failing test along the way? I have also created a PR and description #12163  which I hope to merge after this one is fixed. It has some improvements and a detailed description on how to test and debug this - I'd love if you could try it out and see if this is an easy task.

The bad thing seems that it is not reproducible locally for me and I am not 100 sure why. Maybe we can work together with @dimberman  and find out how to fix it.

**Comment by potiuk** [comment]
Apologies for any problems, but I think some good things (like improved test framework for K8S tests) might come out of it.

**Comment by potiuk** [comment]
@szczeles -> I realized we have #12171 -> so possibly that one will fix the failing K8S and we will be able to close that one :)

**Comment by ashb** [comment]
Closing this as the fix is merged and I don't think we need this PR anymore.

**Pull request closed without merging**
