### PR TITLE
AIRFLOW-1649 - Adding xcom_push to S3KeySensor wildcard matches.

### PR DESCRIPTION
**Pull request by andylockran**
…essible to future tasks

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/AIRFLOW-1649) issue.

### Description

This PR allows for wildcard matches in S3KeySensor to write the matched files to the xcom of the ti.

### Tests

I haven't added a test, as there was no test for the S3KeySensor to extend, and writing from scratch is currently beyond my time commitment.

### CODE REVIEW

**Comment by dalupus** [comment]
You are pulling into the wrong branch.  Needs to pull into master.

Also please see the community guidelines for commit messages.

https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md#pull-request-guidelines

**Comment by dalupus** [comment]
also do we want to add a flag to make this optional?  there could be a lot of matches that people may not want to flood into the database via xcom.

**Comment by andylockran** [comment]
Thanks for your advice.  I'll close, add a flag to make this optional, and reopen a new PR into the master branch with a better commit message.

**Comment by ashb** [comment]
Did you re-open this elsewhere @andylockran? I'd like this functionality :)

**Comment by andylockran** [comment]
Sorry I missed this.

I’be been using it as an airflow plug-in as I was too busy to shepherd it through. 

Feel free to do the same and I’ll try and work on getting it into the standard codebase.

Andy

**Comment by ron819** [comment]
@andylockran any chance to revisit this?

**Pull request closed without merging**
