### PR TITLE
Update dag.py

### PR DESCRIPTION
**Pull request by yangmingfu404**
update start bug

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by yangmingfu404** [comment]
修复了airflow启动日志报错bug

**Review by yangmingfu404 — COMMENTED** [review]
修复启动日志报错bug

**Comment by potiuk** [comment]
Could you please add better English description - what problem does it solve?

**Comment by yangmingfu404** [comment]
When starting a project, an error is reported in the log

**Comment by potiuk** [comment]
> When starting a project, an error is reported in the log

When? How? How to reproduce it ? What makes it happen this way. It does not work like that for others so yuo must have been doing something wrong. 

Also any change we accept here must have corresponding unit tests, so you will have to figure out what causes it and how to get there and reproduce it in unit test (failing without this change), so you need to come with the scenario where it fails anyway.

**Comment by yangmingfu404** [comment]
When I start a project, if there is no file in the DAG directory, task will not be reported_ Dict gets none, but self task_ When dict.keys() takes value, set self task_ Dict is used as a dictionary, and errors are frequently reported in the log

**Comment by potiuk** [comment]
Nope. you do something wrong. self.task_dict  is set to empty dict in the constructor. it's impossible to not have it unless you do something strage. You have not explained what and how you install and run airflow, but almost for sure you do something very wrong.

**Comment by yangmingfu404** [comment]
Airflow is installed and started through official documents without any modification

**Comment by yangmingfu404** [comment]
> Airflow is installed and started through official documents without any modification
Through the following installation method

If there is no DAG file in our DAG directory, the log will not report self task_ Dict is empty. If there is a DAG process, it will report self task_ Dict is not a dictionary error
export AIRFLOW_HOME=~/airflow

# Install Airflow using the constraints file
AIRFLOW_VERSION=2.3.2
PYTHON_VERSION="$(python --version | cut -d " " -f 2 | cut -d "." -f 1-2)"
# For example: 3.7
CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
# For example: https://raw.githubusercontent.com/apache/airflow/constraints-2.3.2/constraints-3.7.txt
pip install "apache-airflow==${AIRFLOW_VERSION}" --constraint "${CONSTRAINT_URL}"

# The Standalone command will initialise the database, make a user,
# and start all components for you.
airflow standalone

**Comment by potiuk** [comment]
> Airflow is installed and started through official documents without any modification

You need to explain what you do and what you get. Logs. screenshots, evidences what exactly happens, what is the DAG you have .

You probably made a horrible mistake in the DAG you have.

**Comment by yangmingfu404** [comment]
> > Airflow通过官方文档安装启动，无需任何修改
> 
> 你需要解释你做了什么，你得到了什么。日志。屏幕截图，证明到底发生了什么，你拥有的 DAG 是什么。
> 
> 您可能在 DAG 中犯了一个可怕的错误。

`with DAG(
    dag_id='common_infer_flow',
    default_args=default_args,
    description='推理流程',
    schedule_interval=timedelta(minutes=1),
    start_date=datetime(2022, 1, 1),
    # start_date=datetime.now(),
    tags=['lucas', 'common'],
    catchup=False,
    max_active_runs=task_worker_num_dict.get("common_infer_flow", 1),
    # max_active_tasks=5,
) as dag:
    # 送标卡片任务：获取任务
    send_infer_lock = SimpleHttpOperator(
        task_id='send_infer_lock',
        method='POST',
        endpoint='/api/airflow/lock',
        data=json.dumps({'business_type': business_type, 'task_type': 'common_infer', 'instance_id': gen_instance_id()}),
        http_conn_id='haomo-airflow',
        headers=headers,
        log_response=True,
        response_check=lambda rps: http_response_check(rps),
        response_filter=lambda rps: http_response_filter(rps),
        dag=dag,
        retries=120,
        retry_delay=timedelta(minutes=2),
    )

    # 送标卡片任务：执行任务
    send_infer_execute = SimpleHttpOperator(
        task_id='send_infer_execute',
        method='POST',
        endpoint='/api/airflow/execute',
        data=send_infer_lock.output,
        http_conn_id='haomo-airflow',
        headers=headers,
        log_response=True,
        response_check=lambda rps: http_response_check(rps),
        response_filter=lambda rps: http_response_filter(rps),
        dag=dag,
    )

    # 送标卡片任务：同步结果
    send_infer_sync = SimpleHttpOperator(
        task_id='send_infer_sync',
        method='POST',
        endpoint='/api/airflow/sync',
        data=send_infer_execute.output,
        http_conn_id='haomo-airflow',
        headers=headers,
        log_response=True,
        response_check=lambda rps: http_response_check_sync(rps),
        response_filter=lambda rps: sync_http_response_filter(rps, next_task_type='', business_type=business_type),
        retries=720,
        retry_delay=timedelta(minutes=6),
        dag=dag,
    )

    # 扩帧任务
    send_infer_lock >> send_infer_execute >> send_infer_sync
`

**Comment by potiuk** [comment]
WHERE do you see errors, in what logs? when?

**Comment by potiuk** [comment]
Stack trace, details etc. What exactly you did to get there. Please, Not in this PR. I will close it, If you can exactly reproduce the issue, open a new Issue - otherwise open a Discussion with all the details. If during the dicussion or issue we will find PR is needed you can recreate it.

**Pull request closed without merging**
