### PR TITLE
[AIRFLOW-2318] Remove {table} parameter on COPY command

### PR DESCRIPTION
**Pull request by czarinacatambing**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3368 

### Description

The COPY command is incorrect. {table} parameter refers to the table in Redshift where the S3 file will be copied to, and not to a table that is inside AWS S3, so  "/{table}" needs to be removed from the COPY command

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
have you filed a jira ticket?

**Comment by czarinacatambing** [comment]
Hello, I just filed a jira ticket. Sorry, I overlooked that step.

**Comment by kaxil** [comment]
Please follow the commit guidelines

**Comment by ron819** [comment]
@ashb you might be interested in this PR https://issues.apache.org/jira/browse/AIRFLOW-2862

**Comment by ashb** [comment]
This PR as it stands would be a backwards-incompatible change so won't be accepted as is.

(The issue is valid though, just not this fix)

**Pull request closed without merging**
