### PR TITLE
[AIRFLOW-1978] WinRM windows operator and hook

### PR DESCRIPTION
**Pull request by cloneluke**
### JIRA
- [AIRFLOW-1978] My PR addresses the following
    - https://issues.apache.org/jira/browse/AIRFLOW-1978

### Description
- [x] This PR allows airflow DAGs to connect and run remote windows commands via winRM protocol. It uses https://github.com/diyan/pywinrm / https://pypi.python.org/pypi/pywinrm

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
@cloneluke Thx for the changes. Do you mind squashing your commits and rebasing?

**Comment by Fokko** [comment]
Please also add the hook and operator to the docs. Thanks!

**Comment by r39132** [comment]
@cloneluke ^

**Comment by cloneluke** [comment]
yes thanks, I will work on this, hopefully soon

**Comment by cloneluke** [comment]
rebased and squashed, please close and use: https://github.com/apache/incubator-airflow/pull/3316

**Comment by r39132** [comment]
Closing.

**Pull request closed without merging**
