### PR TITLE
Prepare cncf.kubernetes release 1.0.2

### PR DESCRIPTION
**Pull request by ashb**
Related #14463

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
Following the question before - Why not also release other providers? There were some changes in other providers as well and we initially discussed releasing 'batches' of the providers every three weeks. Do you plan to have separate voting on this one and separate on the others? I'd love to understand the thinking here, why cncf.kubernetes is going to be released separately from the others.

**Review by potiuk — CHANGES_REQUESTED** [review]
I think it would be great to agree some rules before proceeding with the releases - especially that voting process is an overhead.

**Comment by ashb** [comment]
@potiuk Because the whole point of separating providers was so that _each_ vote would be easier.

> We initially discussed releasing 'batches' of the providers every three weeks

I do not remember this. Perhaps I was not in that meeting.

By releasing one provider at a time as it is needed it makes the vote that much easier. And also: this is a bug fix, so is more urgent than "there are just new changes".

**Comment by potiuk** [comment]
FYI. I just run 'generate-provider-docmentation` and I think we should release:

* amazon
* apache.beam
* apache.spark
* cncf.kubernetes
* google
* jenkins
* microsoft.azure
* mysql
* salesforce
* slack
* ssh
* tableau
* telegram

It's just a matter of updatint provider,yaml with new version for all those and re-running `breeze generate-provider-documentation` - this way we generate all packages and we can vote on all of them.

Here are relevant snippets of the output when you run `generate provider-package-documentation.

```
Please update version in 'airflow/providers/amazon/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-24

================================================================================================  ===========  ==========================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ==========================================================================
`0d6cae417 <https://github.com/apache/airflow/commit/0d6cae4172ff185ec4c0fc483bf556ce3252b7b0>`_  2021-02-24   ``Avoid using threads in S3 remote logging uplod (#14414)``
`ca35bd7f7 <https://github.com/apache/airflow/commit/ca35bd7f7f6bc2fb4f2afd7762114ce262c61941>`_  2021-02-21   ``By default PIP will install all packages in .local folder (#14125)``
`1b1472630 <https://github.com/apache/airflow/commit/1b147263076d48772d417c5154f2db86fc6a6877>`_  2021-02-11   ``Allow AWS Operator RedshiftToS3Transfer To Run a Custom Query (#14177)``
`9034f277e <https://github.com/apache/airflow/commit/9034f277ef935df98b63963c824ba71e0dcd92c7>`_  2021-02-10   ``Document configuration for email backend credentials. (#14006)``
`8c5594b02 <https://github.com/apache/airflow/commit/8c5594b02ffbfc631ebc2366dbde6d8c4e56d550>`_  2021-02-08   ``includes the STS token if STS credentials are used (#11227)``
`cddbf9c11 <https://github.com/apache/airflow/commit/cddbf9c11d092422e6695d7a5a5c859fdf140753>`_  2021-02-06   ``Use MongoDB color for MongoToS3Operator (#14103)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ========================================================================

Please update version in 'airflow/providers/apache.beam/'provider.yaml' to 
prepare release.

UNKNOWN
.......

Latest change: 2021-02-05

================================================================================================  ===========  ======================================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ======================================================================================
`8a731f536 <https://github.com/apache/airflow/commit/8a731f536cc946cc62c20921187354b828df931e>`_  2021-02-05   ``Improve Apache Beam operators - refactor operator - common Dataflow logic (#14094)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ======================================================================================


Please update version in 'airflow/providers/apache.spark/'provider.yaml' to 
prepare release.

UNKNOWN
.......

Latest change: 2021-02-11

================================================================================================  ===========  =========================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  =========================================================
`f9c9e9c38 <https://github.com/apache/airflow/commit/f9c9e9c38f444a39987478f3d1a262db909de8c4>`_  2021-02-11   ``Use apache.spark provider without kubernetes (#14187)``
================================================================================================  ===========  =========================================================

Please update version in 'airflow/providers/cncf.kubernetes/'provider.yaml' to 
prepare release.

UNKNOWN
.......

Latest change: 2021-02-23

================================================================================================  ===========  ============================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ============================================================================
`809b4f9b1 <https://github.com/apache/airflow/commit/809b4f9b18c7040682e17879248d714f2664273d>`_  2021-02-23   ``Unique pod name (#14186)``
`649335c04 <https://github.com/apache/airflow/commit/649335c043a9312ef272fa77f2bb830d52cde056>`_  2021-02-07   ``Template k8s.V1EnvVar without adding custom attributes to dict. (#14123)``
`d4c4db8a1 <https://github.com/apache/airflow/commit/d4c4db8a1833d07b1c03e4c062acea49c79bf5d6>`_  2021-02-05   ``Allow users of the KPO to template environment variables (#14083)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ============================================================================

Please update version in 'airflow/providers/google/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-23Please update version in 'airflow/providers/mysql/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-17

================================================================================================  ===========  =======================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  =======================================================================
`cdc20904a <https://github.com/apache/airflow/commit/cdc20904a59610822968ab57aa127d989ec7e2a5>`_  2021-02-17   ``MySQL hook respects conn_name_attr (#14240)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  =======================================================================


================================================================================================  ===========  ========================================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ========================================================================================
`c28197998 <https://github.com/apache/airflow/commit/c281979982c36f16c4c346c996a0c8d6ca7c630d>`_  2021-02-23   ``Documentation and example dag for CloudDLPDeidentifyContentOperator, GCSObjectExistenc
`ca35bd7f7 <https://github.com/apache/airflow/commit/ca35bd7f7f6bc2fb4f2afd7762114ce262c61941>`_  2021-02-21   ``By default PIP will install all packages in .local folder (#14125)``
`a7e4266d6 <https://github.com/apache/airflow/commit/a7e4266d675d5283cdd34c6451c8ef0f2858a501>`_  2021-02-21   ``Refactor GoogleDriveToGCSOperator to use common methods (#14276)``
`1ab406663 <https://github.com/apache/airflow/commit/1ab406663ead7475ac14644553ac48466777bd78>`_  2021-02-16   ``Add GoogleDriveToLocalOperator (#14191)``
`59c94c679 <https://github.com/apache/airflow/commit/59c94c679e996ab7a75b4feeb1755353f60d030f>`_  2021-02-13   ``Add 'exists_ok' flag to BigQueryCreateEmptyTable(Dataset)Operator (#14026)``
`e31b27d59 <https://github.com/apache/airflow/commit/e31b27d593f7379f38ced34b6e4ce8947b91fcb8>`_  2021-02-13   ``Add materialized view support for BigQuery (#14201)``
`e3bcaa3ba <https://github.com/apache/airflow/commit/e3bcaa3ba351234effe52ad380345c4e39003fcb>`_  2021-02-12   ``Correct typo in GCSObjectsWtihPrefixExistenceSensor  (#14179)``
`7faa2d978 <https://github.com/apache/airflow/commit/7faa2d978c3a4e1eb2f7c6a931c9475712015f9f>`_  2021-02-10   ``Add BigQueryUpdateTableOperator (#14149)``
`1da697216 <https://github.com/apache/airflow/commit/1da69721651455c9108c00ca5f6723d6557524a9>`_  2021-02-10   ``Fixes to dataproc operators and hook (#14086)``
`02288cf2b <https://github.com/apache/airflow/commit/02288cf2baf590e448cd008f6216ccf8b776a67a>`_  2021-02-10   ``Add param to CloudDataTransferServiceOperator (#14118)``
`7d3864547 <https://github.com/apache/airflow/commit/7d38645472b0502212504b09d85b0e1271d74274>`_  2021-02-09   ``#9803 fix bug in copy operation without wildcard  (#13919)``
`b0c382426 <https://github.com/apache/airflow/commit/b0c382426c943cbf7bd7c09583d9c5d3137413ee>`_  2021-02-07   ``Add gdrive_to_gcs operator, drive sensor, additional functionality to drive hook, and 
`5d7d46bb3 <https://github.com/apache/airflow/commit/5d7d46bb33c1d529c1549b593ee27bbc7f56ea29>`_  2021-02-05   ``Improve GCSToSFTPOperator paths handling (#11284)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ========================================================================================

Please update version in 'airflow/providers/jenkins/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-08

================================================================================================  ===========  ====================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ====================================================================
`78adaed5e <https://github.com/apache/airflow/commit/78adaed5e62fa604d2ef2234ad560eb1c6530976>`_  2021-02-08   ``Add allowed_jenkins_states to JenkinsJobTriggerOperator (#14131)``
================================================================================================  ===========  ====================================================================

Please update version in 'airflow/providers/microsoft.azure/'provider.yaml' to 
prepare release.

UNKNOWN
.......

Latest change: 2021-02-25

================================================================================================  ===========  ==============================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ==============================================================================
`5bfa0f123 <https://github.com/apache/airflow/commit/5bfa0f123b39babe1ef66c139e59e452240a6bd7>`_  2021-02-25   ``BugFix: Fix remote log in azure storage blob displays in one line (#14313)``
`ca35bd7f7 <https://github.com/apache/airflow/commit/ca35bd7f7f6bc2fb4f2afd7762114ce262c61941>`_  2021-02-21   ``By default PIP will install all packages in .local folder (#14125)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ==============================================================================

Please update version in 'airflow/providers/mysql/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-17

================================================================================================  ===========  =======================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  =======================================================================
`cdc20904a <https://github.com/apache/airflow/commit/cdc20904a59610822968ab57aa127d989ec7e2a5>`_  2021-02-17   ``MySQL hook respects conn_name_attr (#14240)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  =======================================================================


< Release: 1.0.1
---
> Release: 1.0.2
92a93,111
> Cross provider package dependencies
> -----------------------------------
> 
> Those are dependencies that might be needed in order to use all the features of the package.
> You need to install the specified backport providers package in order to use them.
> 
> You can install such cross-provider dependencies when installing from PyPI. For example:
> 
> .. code-block:: bash
> 
>     pip install apache-airflow-providers-salesforce[tableau]
> 
> 
> ======================================================================================================  ===========
> Dependent package                                                                                       Extra
> ======================================================================================================  ===========
> `apache-airflow-providers-tableau <https://airflow.apache.org/docs/apache-airflow-providers-tableau>`_  ``tableau``
> ======================================================================================================  ===========

Please update version in 'airflow/providers/slack/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-18

================================================================================================  ===========  =======================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  =======================================================================
`8c060d55d <https://github.com/apache/airflow/commit/8c060d55dfb3ded21cb9d2305cffe14e1c610680>`_  2021-02-18   ``Don't allow SlackHook.call method accept *args (#14289)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  =======================================================================

Please update version in 'airflow/providers/ssh/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-08

================================================================================================  ===========  ==============================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ==============================================================================
`f180fa13b <https://github.com/apache/airflow/commit/f180fa13bf2a0ffa31b30bb21468510fe8a20131>`_  2021-02-08   ``Added support for DSS, ECDSA, and Ed25519 private keys in SSHHook (#12467)``
`10343ec29 <https://github.com/apache/airflow/commit/10343ec29f8f0abc5b932ba26faf49bc63c6bcda>`_  2021-02-05   ``Corrections in docs and tools after releasing provider RCs (#14082)``
================================================================================================  ===========  ==============================================================================


1.0.0
.....

Latest change: 2021-02-25

================================================================================================  ===========  ===================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  ===================================================================
`45e72ca83 <https://github.com/apache/airflow/commit/45e72ca83049a7db526b1f0fbd94c75f5f92cc75>`_  2021-02-25   ``Add Tableau provider separate from Salesforce Provider (#14030)``
================================================================================================  ===========  ===================================================================

Update index.rst for tableau


Generated /opt/airflow/docs/apache-airflow-providers-tableau/index.rst file for 

```


Please update version in 'airflow/providers/telegram/'provider.yaml' to prepare 
release.

UNKNOWN
.......

Latest change: 2021-02-10

================================================================================================  ===========  =======================================================================
Commit                                                                                            Committed    Subject
================================================================================================  ===========  =======================================================================
`106d2c85e <https://github.com/apache/airflow/commit/106d2c85ec4a240605830bf41962c0197b003135>`_  2021-02-10   ``Fix the AttributeError with text field in TelegramOperator (#13990)``
================================================================================================  ===========  =======================================================================

**Comment by ashb** [comment]
> It's just a matter of updatint provider,yaml with new version for all those and re-running breeze generate-provider-documentation - this way we generate all packages and we can vote on all of them.

No, it's a matter of *TESTING* each of those packages too. Doing that properly is more work than just throwing some tarballs up for a bote.

**Comment by potiuk** [comment]
> No, it's a matter of _TESTING_ each of those packages too. Doing that properly is more work than just throwing some tarballs up for a vote.

We've never tested either of those when we released airflow 1.10. Have anything changed in the procedure?

**Comment by ashb** [comment]
You haven't been testing things before putting them up to a vote: 😱 

I _always_ do.

**Comment by potiuk** [comment]
> You haven't been testing things before putting them up to a vote: 
> 
> I _always_ do.

When is the last time you tested google/jenkins/ssh operators when relleasing any version of 1.10 ? 

I think, honestly it's totally over-the top here as we have never been testing the providers (and 1.10 equivalent of those). If you want to introduce it - feel free to start a discussion, but it has never been brought to any discussion nor even raised as a problem.

Right now all the providers in questions are tested (in the  CI):

1) they are installing in latest airflow
2) All the operators/hooks/ etc. are importable
3) all the backport providers are also installable in 1.10.14 (and all classes import there).
4) all the unit tests are passing for the providers.

This is even more than we've tested in Airflow 1.10 to be honest. 

I am not sure what is your proposal then ? Should someone (who?) actually run all the tests for all the providers we release? what is the idea you have in mind how it should be done?

**Comment by ashb** [comment]
We haven't tested all of the providers in depth before precisely because releasing 13 at once (including the big three of azure, aws and gcp) is a lot of work, and those releases are less urgent.

But by chosing to release one at a time, it is much more possible to test each release in detail.

Essentially: what is the problem in releasing cncf.kubernetes on it's own right now? You are asking me to do about 3 days of work to test those (and yes, I/Astronomer did test these in detail for 2.0.0 release) - I personally am not willing to put my name down as release manager to a release I haven't tested.

**Comment by potiuk** [comment]
> Essentially: what is the problem in releasing cncf.kubernetes on it's own right now? You are asking me to do about 3 days of work to test those (and yes, I/Astronomer did test these in detail for 2.0.0 release) - I personally am not willing to put my name down as release manager to a release I haven't tested.

Nope . I asking to release all others based on tests we alredy have in CI. As we've always did. I think you are complicating things too much.  The release manager's responsbility is the mechanics of the releese only, not whether everything works: https://infra.apache.org/release-publishing.html. I am not asking any more than we've been doing before.

**Comment by potiuk** [comment]
And this is fantasticly surprising seeing this is a problem at all, especially we discussed all of this before and there are even meeting minutes from the dev call stating the process. I propose to proceed as we already agreed on those meetings and if there is a doubt about it, let's discuss it at the next meeting.

**Comment by ashb** [comment]
I'll say it even clearer. You are asking _me to do something I am not happy to do_.

If I release something, I have tested it until I am happy with it.

**Comment by potiuk** [comment]
> If I release something, I have tested it until I am happy with it.

So let me ask you this question: did you ever test Jenkins, ssh,  operators when releasing it? Because I know you did several times.

What is your counter-proposal then?  Do you have one? 

I am also extremely not happy with not releasing providers as batches of them either, until I hear a viable alternative solution of relasing the providers.

**Comment by ashb** [comment]
Did I test them for 1.10x? Not always, no. Was I happy about it? Hell no.

But now we have the means to do it better.

If you really feel that strongly about releasing them all in a batch, okay, but it is going to take me longer. I'm not just going to cut the release and push it out.

**Comment by potiuk** [comment]
I can do it tomorrow, I have completely no problem with releasing them in batch with the tests that we already have.

**Comment by potiuk** [comment]
If you do not feel comfortable with that - feel free to work out how to do it in a better way with more testing. I am happy to follow what we agreed - before - release both providers and backports in regular (3 weeks intervals) - same way as I've done so far. 

In the meantime, if you want to start thinking on how to do it better - maybe this is the right time to start thinking of it. Other than following the process the way I designed it and release whatever passes all the test we already have, but certainly no capacity to think about and introduce more sophisticated testing around it.

**Comment by kaxil** [comment]
My 2 cents:

- One of the key benefits of having separate providers was so that we can release them at a separate cadence from the core and release them on an ad-hoc basis. We started receiving few issues on Github on this Kubernetes Bug and so I wanted to release this provider asap since the fix was already merged around 18 Feb.
- For most of the providers I would check the changelog and based on my confidence in it would decide whether I should test or not.
- We should release all providers at a regular cadence too (I am hoping that the release policy guide for providers will cover the actual frequency - 2/3 weeks vs a month)

So I agree with the following principles (that you both stated separately) :

- We should be able to release providers on an ad-hoc basis -- if something breaks, fix it and release the provider. Easy to test and verify.
- We shouldn't need to test each item in the provider -- make the decision based on the Changelog -- if there are just doc updates for example or just changing a minor code, no point in testing.

**Comment by ashb** [comment]
I do not believe we ever said we would _only_ release providers in batches. I can't find any reference to such a decision in the (admittedly very terse) dev meeting notes, nor AIP-8.

**Comment by potiuk** [comment]
> I do not believe we ever said we would _only_ release providers in batches. I can't find any reference to such a decision in the (admittedly very terse) dev meeting notes, nor AIP-8.

Yes. We agreed that we CAN release them separately if there is an actual need to deviate from a regular schedule by default and that we release all providers in batches due to efficiency and overhead for voting process.

That's why in my first comment I asked what is justification for releasing it out-of-bands. 

> Following the question before - Why not also release other providers? There were some changes in other providers as well and we initially discussed releasing 'batches' of the providers every three weeks. Do you plan to have separate voting on this one and separate on the others? I'd love to understand the thinking here, why cncf.kubernetes is going to be released separately from the others.

That was my first ask is no reason why cncf.kubernetes should be released separately rather than with the rest of the providers - but apparentlly discussion has deviated from that. So let me repeat again - is there any reason why cncf.kubernetes cannot be released a bit later together with other providers as we agreed before? Is there are critical problem there?

If there is a critical problem - are we going also to release backport for that (when we are releasing providers - until end of March we are also release backports together with every batch of providers).

**Comment by ashb** [comment]
> that we release all providers in batches due to efficiency and overhead for voting process.
> 
> That's why in my first comment I asked what is justification for releasing it out-of-bands.

See this is where I disagree. I see a batch release as _MORE_ overhead. Releasing a single provider is much less work on everyone to vote on it. Releasing 13 at once encourages rubber-stamping the vote, or makes people not test it.

**Comment by potiuk** [comment]
> > that we release all providers in batches due to efficiency and overhead for voting process.
> > That's why in my first comment I asked what is justification for releasing it out-of-bands.
> 
> See this is where I disagree. I see a batch release as _MORE_ overhead. Releasing a single provider is much less work on everyone to vote on it. Releasing 13 at once encourages rubber-stamping the vote, or makes people not test it.

Yep. We disagree here for sure. 

I think you should propose new process how to apply it for all providers, when to release them and how to test them. I am happy to cease my responsibilities there if there is another process in place - but not sooner than that. And until then regular batches should be the rule and out-of-band ones should be exception. Happy to discuss it at the next dev call.

**Comment by kaxil** [comment]
Just adding a reason again on why I had create a separate issue to release Kubernetes Provider:

This issue was raised multiple times by our users: #13348, #13522 & #14287 and so I wanted to release this provider asap since the fix was already merged around 18 Feb (last batch or providers were released on 8 Feb).

**Comment by potiuk** [comment]
> This issue was raised multiple times by our users: #13348, #13522 & #14287 and so I wanted to release this provider asap since the fix was already merged around 18 Feb (the last batch of providers were released on 8 Feb).

Let's do it tomorrow then following the process we've already have - including releasing backports together with all providers (since this is a critical issue, it also affect 1.10 users). I have not seen an attempt to release backport package as well for that.

**Comment by potiuk** [comment]
Previously we discussed 3 weeks release schedule for providers. 3 weeks from last release.

The last round of providers RCs was sent precisely 3 weeks ago. So this is simply the RIGHT TIME to release all of them. And this is what I planned to do tomorrow.

I simply see no point in releasing cncf.kubernetes now since we are going to release all the other providers. That's why I was surprised why we *JUST* want to release the kubernetes one. 

If we start voting today on cncf.kubernetes alone and tomorrow on all the rest - in parallel on several different providers overlapping each other - THIS will be a mess and this is pretty much guarantee nobody tests anything anyway.

Am I missing something?

**Comment by kaxil** [comment]
> Previously we discussed 3 weeks release schedule for providers.
> 
> The last round of providers RCs was sent precisely 3 weeks ago. So this is simply the RIGHT TIME to release all of them. And this is what I planned to do tomorrow.
> 
> I simply see no point in releasing cncf.kubernetes now since we are going to release all the other providers. That's why I was surprised why we _JUST_ want to release the kubernetes one.
> 
> If we start voting today on cncf.kubernetes alone and tomorrow on all the rest - in parallel on several different providers overlapping each other - THIS will be a mess and this is pretty much guarantee nobody tests anything anyway.
> 
> Am I missing something?

I had posted about it 8 days ago (https://github.com/apache/airflow/issues/14287#issuecomment-781675876)

**Comment by potiuk** [comment]
> I don't mind either way now and we can discuss this in next Dev call -- but this was one of the times where we should have created an ad-hoc release straight-away.

Agree. As I mentioned I've totally missed that one mention in the PR. Maybe that would have been justified back then. Let's talk about it at the call indeed.

**Comment by potiuk** [comment]
Closing as this is covered by #14487

**Pull request closed without merging**
