### PR TITLE
[AIRFLOW-1018] Sanitize logging format and allow stdout for scheduler

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1018

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Airflow was using serveral logging formats which were difficult to
parse. The patch makes sure we always log PID.

Also the scheduler did not allow for stdout/stderr output for its
parsing of dags, this was a regression. Until we fix logging
properly - by not creating arbitrary files in arbitrary modules,
this is a workaround to allow logging to stdout/stderr.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

- Cannot add tests to cover stdout in a sane way

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

@criccomini @poulainv

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@saguziel PTAL

**Comment by saguziel** [comment]
Lgtm trusting your grep ability

**Comment by spazm** [comment]
@bolkedebruin , Is this duplicated by #2728 ? 

#2728 is closed.  Both PR's referenced Airflow-1018.

**Comment by ashb** [comment]
Closing this stale PR.

**Pull request closed without merging**
