### PR TITLE
Remove pandas upper limit now that SQLA is 1.4+

### PR DESCRIPTION
**Pull request by dstandish**

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Hmmm _something_ is still keeping it at pandas v1.3.5. I guess it's still using the constraints from main for this build?

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
> Hmmm _something_ is still keeping it at pandas v1.3.5. I guess it's still using the constraints from main for this build?

My bext guess is some of the dependencies in google provider (apache-beam) - but this is coming more from intuitiona and guess.  Unfortunately (and @uranusjr might have some other tricks which I am not aware of) it might be not easy guess if this is done through an extra (or even transitive extra as it happens) because `pip` only uses extra's limitations during installation, and any metadata connected to extra limitations is not available for inspection after installation is complete.

The way to check it (at least what I use):

1) Check with `pipdeptree` - if this is not an extra-originated limit - you will see the limit there 

```
docker run -it ghcr.io/apache/airflow/main/ci/python3.7 \ 
     ghcr.io/apache/airflow/main/ci/python3.7:2276fd417180d89da60d661023bf9b48d6b71c7f  bash
```

Then run:

```
pipdeptree | ls
```

Then look for pandas.

2) You can also take look at `pip logs` (starting here : https://github.com/apache/airflow/runs/5501411485?check_suite_focus=true#step:10:2520)  and try to guess from the logs where the limitation came from. But so far I think it did not have an information that could allow to determine it easliy. The change is coming in `pip` to make the log more useful to track the source of conflicts (https://github.com/pypa/pip/pull/10937), and I hope it's going to help a lot, but for now I could not really figure out much from the log.

3) Guess (intelligently). There are a few big packages with lots of dependencies. Apache Beam is one but few other google and amazon depencies that are the usual culprits, so the problem space is usually much smaller than 580 dependencies we have. 

What's helpful here is https://pypi.org/pypi/PACKAGE/json and specifically https://pypi.org/pypi/PACKAGE/VERSION/json that can help as it contains the meta-data. But when it comes to extras and transitive extras it's  more of a manual effort than automation, I think it's rather dificult to replicate what `pip` does fully (because of the complexity of qualifiers for example) but it is useful for manual verification as you do not have to download and unpack pacjage

**Comment by potiuk** [comment]
Hey @ashb  - can you please rebase the PR ? 

I took a deeper look and the reason why pandas is held back is rather straightforward - Pandas 1.4+ does not support Python 3.7 any more.

So there is no way it can be upgraded for 3.7.

The PR has `full tests needed` label added so we should see if Python 3.8+ will get `Pandas` updated.

**Comment by potiuk** [comment]
Reopened to rebuild and check for 3.8/3.9 pandas upgrade.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Yep. As expected. Pandas was upgraded to 1.4 in Python 3.8+ - so it was simply Python 3.7 that still uses old Pandas simply because Pandas 1.4 is Python 3.8+

**Pull request merged**
