### PR TITLE
Add check for coerce_datetime to Airflow 2-1 compatibility check

### PR DESCRIPTION
**Pull request by potiuk**
Checking coerce_datetime presence (and also consolidating all
2.1 checks in a single pre-commit check).

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Screenshot 2022-03-24 at 11 23 01

**Comment by potiuk** [comment]
@lwyszomi

**Comment by eladkal** [comment]
This probably means RC2 for google provider?

**Comment by lwyszomi** [comment]
@potiuk thanks :)

**Review by uranusjr — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
> This probably means RC2 for google provider?

Not really. This is just 2.1+ compatibility problem and it has been already released so it is not a "regression" in the new release.

BTW. It was actually me who introduce it here: https://github.com/apache/airflow/commit/372849486cd455a4ff4821b01805a442f1a78417 🤦

**Comment by lwyszomi** [comment]
@potiuk not only you 😄 #18088

**Comment by potiuk** [comment]
True. That was actually a teamwork :)

**Pull request merged**
