### PR TITLE
[AIRFLOW-1895] Fix add_time_zone migration

### PR DESCRIPTION
**Pull request by edgarRd**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1895

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Adding `nullable=False` to add_time_zone DB migration.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Tested DB migration locally in MySQL db with clean setup.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by edgarRd** [comment]
PTAL @bolkedebruin

**Comment by bolkedebruin** [comment]
LGTM, I would be fine with a `# flake8: noqa` at the top of this file btw. O and as both mysql builds are failing please check that.

**Comment by bolkedebruin** [comment]
@edgarRd can you please elaborate in the commit why it is required? Probably referring to the mysql documentation (http://docs.sqlalchemy.org/en/latest/dialects/mysql.html)? I think, given the changed support in sqlalchemy for time zones and nullability, it is smart to set the minimum version of sqlalchemy to 1.1.15.

**Comment by bolkedebruin** [comment]
@edgarRd any update?

**Comment by cinhil** [comment]
Hello,

Could we move forward on that PR. I just redo it on a fork before finding this PR...
So firstly
- A mysql index can never use a nullable column.
- If you look to the commit it is more a typo fix than something else. The column is set as nullable=false for postgresql as well
- If you look to older script it is already set as nullable=false for those two table. So without the PR, it looks to a erroneous change to a nullable column, what is obviously forbidden.

So we can assume this PR is fine. So the real question is why travis is failing ?
The truth is probably that:
- this PR is fine
- travis test is working before this PR only because the database migration failure does not makes travis failed but avoid the running of something else that screw the build

On my box, when the PR is apply, the initialization goes further. It even show me that fernet dependency was not installed.... But it fails once I enable a dag with a:
```
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'print_context-timezone_bxl_10m-2018-01-24 14:26:10.137224' for key 'PRIMARY'")
```
So clearly the PR make it not functional.

But on the other hand, without this PR makes part of the initialization skipped.
```
airflow_1  | sqlalchemy.exc.DataError: (_mysql_exceptions.DataError) (1171, 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead') [SQL: 'ALTER TABLE sla_miss MODIFY execution_date TIMESTAMP(6) NULL']
airflow_1  | [2018-01-24 14:42:26,997] {{driver.py:120}} INFO - Generating grammar tables from /usr/lib/python3.5/lib2to3/Grammar.txt
airflow_1  | [2018-01-24 14:42:27,030] {{driver.py:120}} INFO - Generating grammar tables from /usr/lib/python3.5/lib2to3/PatternGrammar.txt
airflow_1  | [2018-01-24 14:42:27,148] {{__init__.py:45}} INFO - Using executor LocalExecutor
```

So we should find the bug behind the bug. I will continue to search, but since I am new to this project I am not sure I will find it shortly.

**Comment by cinhil** [comment]
Hello,

I manage to fix the issue. It is caused by how alchemy/alembic manage timestamp.
For MySQL default value is mandatory for a NOT NULL column 
(read https://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html). 

For alchemy/alembic, if you do not set the value it will use current_time for create but also for update:
```
  `execution_date` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
```

To avoid this you need to specify the default value.
To share the fix I did create a new PR. Feel free to adapt this one or to use mine, I do not care: 
https://github.com/apache/incubator-airflow/pull/2969

Cheers,
Cinhil

**Comment by bolkedebruin** [comment]
@cinhil what version of sqlalchemy are you using?

**Comment by cinhil** [comment]
Hello,
This PR can be closed. It has been fixed by #2979
Cheers

**Pull request closed without merging**
