### PR TITLE
[AIRFLOW-4129] Escape HTML in generated tooltips

### PR DESCRIPTION
**Pull request by ashb**
Many of these properties aren't user generated, but it is better to be
safe

Make sure you have checked _all_ steps below.

### Jira
https://issues.apache.org/jira/browse/AIRFLOW-4129

### Description

Escape anything that we expect to be plain text when building tooltips.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
I have also created a second PR targeting the v1-10-stable branch.

**Comment by mik-laj** [comment]
Hi.
You should not implement your own security mechanisms when it is not required. Look how you can achieve a similar effect, but using the browser's API.
https://codepen.io/anon/pen/moGGaE
Greetings

Related PR: https://github.com/apache/airflow/pull/4948 (cross-link)

**Comment by ashb** [comment]
@mik-laj I agree, and I didn't like doing this, but there is no HTML element to set the property on - as this is setting an attribute which is then picked up by jQuery's tooltip.

**Comment by mik-laj** [comment]
It is still possible. You could create a new HTML element, like in my example. 

I will prepare my PR. Please wait.

**Comment by ashb** [comment]
Thanks. It was late last night when I was working on this. If you do it on one PR I'll fix up the other. Edit: oh you probably can't edit my PR can you :D

**Comment by mik-laj** [comment]
I will create a separate PR. You will move my commits to expected branch/PR/etc.

**Comment by mik-laj** [comment]
My new PR: https://github.com/apache/airflow/pull/4950

**Comment by ashb** [comment]
Closing in favour of #4950

**Pull request closed without merging**
