### PR TITLE
[AIRFLOW-XXX] Add clarity to gcs_download_operator params

### PR DESCRIPTION
**Pull request by leahecole**
Small docs change to add clarity to the gcs_download_operator parameters

### CODE REVIEW

**Comment by potiuk** [comment]
aaand rebase is needed :)

**Comment by potiuk** [comment]
Can you please rebase to latest apache/master @leahecole ? I think it will solve all the checks.

**Comment by leahecole** [comment]
sorry @potiuk - it's dippy lil formatting errors. I'm paying attention to it and trying to make the ci/cd pass. Meant I finally got around to setting up breeze and testing locally though!

**Comment by potiuk** [comment]
Thanks! @leahecole for contributing. Nice to hear Breeze is being used :)

**Pull request merged**
