### PR TITLE
Hook into Mypy to get rid of those cast()

### PR DESCRIPTION
**Pull request by uranusjr**
Follow-up to #25604. This is not really the most sound solution (we can get pretty crazy into the typing rabbit hole), but at least not worse than just type-hinting those as `Any`, since we at least get autocompletion.

### CODE REVIEW

**Comment by potiuk** [comment]
Needs rebase

**Comment by uranusjr** [comment]
For some reason this is breaking isort; it now thinks our first-class imports (`known_first_party`) are third-party :(

**Comment by potiuk** [comment]
I like how simple it is :). Indeed. Getting into rabbit-hole of MyPy plugins might be not the best idea, but this one is good enough approach which I really like.

**Review by potiuk — APPROVED** [review]

**Review by josh-fell — APPROVED** [review]
🎉

**Pull request merged**
