### PR TITLE
[AIRFLOW-6091] Add flushing in execute method for BigQueryCursor

### PR DESCRIPTION
**Pull request by zuku1985**
If you execute multiple queries results of old ones will be
flushed allowing to read results of recent execute without
any issues.

Make sure you have checked _all_ steps below.

### Jira

- [x ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6091
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ x] Here are some details about my PR, including screenshots of any UI changes:

My PR addresses issue with results buffer and reading flags not being cleaned in some cases what ends up in returning no data or even data from previous job in case of executing many queries with one cursor.

### Tests

- [ x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

My PR does not add any functionality to test

### Commits

- [ x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by zuku1985** [comment]
Test that failed seems to be totally unrelated to my change. What should I do to fix it?

**Review by turbaszek — APPROVED** [review]

**Comment by zuku1985** [comment]
@nuclearpinguin any hints what should I do to fix failing tests? I ran out of ideas :/

**Comment by potiuk** [comment]
I restarted the failing job. It's a flaky "run_on_kill" test that @nuclearpinguin is solving with the upcoming #6472 change.

**Comment by mik-laj** [comment]
Can you add tests to prevent regression?

**Comment by zuku1985** [comment]
I will need some hints on how to do it.

**Comment by mik-laj** [comment]
The best way to learn this is to read the source test codes for operators and hooks for other GCP services.  All services except BigQuery have one style and the way they are tested.  All services except BigQuery have one style and the way they are tested. It is also useful to know [unittest.mock](https://docs.python.org/3/library/unittest.mock.html).

**Comment by TobKed** [comment]
I agree with @mik-laj . Analysing some other tests is the best way to learn, preferably play with then locally, break thing and what happened. I am during improving BigQuery hooks test, fell free to check them out here: https://github.com/apache/airflow/pull/6777. 
Information how to run Breeze environment and run tests locally you can find in files `BREEZE.rst` and `TESTING.rst`

**Review by TobKed — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
