### PR TITLE
BUG Update `initialise_virtualenv.py` to use `uv sync`

### LINKED ISSUE #44078: BUG `./scripts/tools/initialize_virtualenv.py`
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

I have breeze installed then I ran this script 
```
python3.9 ./scripts/tools/initialise_virtualenv.py
``` 
to create a virtual env with `airflow` present in `/bin`. I activated the virtual env 
```
airflow version
``` 
in terminal and got this error message:

```
(apache-airflow) success@success-HP-Laptop-14-cf3xxx:~/Desktop/airflow$ airflow version
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 389, in resolve
    found = getattr(found, frag)
AttributeError: module 'airflow.utils.log' has no attribute 'file_processor_handler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
    self.importer(used)
  File "/home/success/Desktop/airflow/airflow/utils/log/file_processor_handler.py", line 27, in <module>
    from airflow.utils.helpers import parse_template_string
  File "/home/success/Desktop/airflow/airflow/utils/helpers.py", line 32, in <module>
    from airflow.utils.types import NOTSET
  File "/home/success/Desktop/airflow/airflow/utils/types.py", line 22, in <module>
    import airflow.sdk.types
ModuleNotFoundError: No module named 'airflow.sdk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/config.py", line 564, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.9/logging/config.py", line 722, in configure_handler
    klass = self.resolve(cname)
  File "/usr/lib/python3.9/logging/config.py", line 398, in resolve
    raise v
  File "/usr/lib/python3.9/logging/config.py", line 391, in resolve
    self.importer(used)
  File "/home/success/Desktop/airflow/airflow/utils/log/file_processor_handler.py", line 27, in <module>
    from airflow.utils.helpers import parse_template_string
  File "/home/success/Desktop/airflow/airflow/utils/helpers.py", line 32, in <module>
    from airflow.utils.types import NOTSET
  File "/home/success/Desktop/airflow/airflow/utils/types.py", line 22, in <module>
    import airflow.sdk.types
ValueError: Cannot resolve 'airflow.utils.log.file_processor_handler.FileProcessorHandler': No module named 'airflow.sdk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/success/Desktop/airflow/.venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/success/Desktop/airflow/airflow/__init__.py", line 78, in <module>
    settings.initialize()
  File "/home/success/Desktop/airflow/airflow/settings.py", line 750, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/home/success/Desktop/airflow/airflow/logging_config.py", line 74, in configure_logging
    raise e
  File "/home/success/Desktop/airflow/airflow/logging_config.py", line 69, in configure_logging
    dictConfig(logging_config)
  File "/usr/lib/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.9/logging/config.py", line 571, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'processor'
```

### What you think should happen instead?

3.0.dev0

### How to reproduce

Clone the source code from guthub
```
git clone https://github.com/apache/airflow.git
cd airflow
```

Install breeze
```
uv tool install -e ./dev/breeze
```
Create virtual env
```
python3.9 -m venv .venv
python3.9 ./scripts/tools/initialise_virtualenv.py
```
This should print out the version
```
airflow version
```

### Operating System

ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else?

No

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SuccessMoses**
closes: #44078

`uv` is the recommended tool for installing `airflow` and other dependecies. I updated the `./scripts/tool/initialise_virtualenv.py` file to use `uv sync` instead of `pip unstall`

### CODE REVIEW

**Comment by SuccessMoses** [comment]
even with this changes there is still a bug:
```
airflow version
```
Observation:
```
airflow) success@success-HP-Laptop-14-cf3xxx:~/Desktop/airflow$ airflow version
Traceback (most recent call last):
  File "/home/success/Desktop/airflow/.venv/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/success/Desktop/airflow/airflow/__init__.py", line 78, in <module>
    settings.initialize()
  File "/home/success/Desktop/airflow/airflow/settings.py", line 787, in initialize
    configure_orm()
  File "/home/success/Desktop/airflow/airflow/settings.py", line 494, in configure_orm
    async_engine = create_async_engine(SQL_ALCHEMY_CONN_ASYNC, future=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/success/Desktop/airflow/.venv/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 43, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/success/Desktop/airflow/.venv/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/success/Desktop/airflow/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 544, in create_engine
    dbapi = dialect_cls.dbapi(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/success/Desktop/airflow/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 321, in dbapi
    __import__("aiosqlite"), __import__("sqlite3")
```
## Hypothesis:
No modules named `aiosqlite` and `sqlite3`

**Comment by potiuk** [comment]
If we use `uv` to create venv. You should either activate it with sourcing `./venv/bin/activate`first  or using `uv run` to run the command in the venv you just created (the venv is created in projects's root `.venv` sub-folder.

**Comment by SuccessMoses** [comment]
Should I add `aiosqlite` to dependencies in `./pyproject.toml`

**Comment by potiuk** [comment]
No - it's already added by "hatch_build.py"  via sqlite dependency. What you needed to do (see the fixup I added) - is to run the airflow commands via "uv run" command.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
