### PR TITLE
Sync v2 1 2 stable v2

### PR DESCRIPTION
**Pull request by jhtimmins**
Sync remaining commits into v2-1-2

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Might also make sense to run constraints upgrade. I will run it

**Comment by potiuk** [comment]
BTW. Something wrong with airflow.compat missing (both pylint and tests)

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
Seems like this one https://github.com/apache/airflow/pull/16700 brings airflow.compat ?

**Comment by potiuk** [comment]
i think cherry picking 3db347edcfe444a67e59e8cf0019e80a02dbceab and 866a601b76e219b3c043e1dbbc8fb22300866351 should bring the compat change and remove pylint (some more cherry-picks might be needed)

**Comment by potiuk** [comment]
BTW. Constraints upgraded for `constraints-2-1` branch - following https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#manually-generating-constraint-files

**Review by ashb — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Pull request merged**
