### PR TITLE
Speed up tests that use BackfillJob

### PR DESCRIPTION
**Pull request by ashb**
Calling `heartbeat` was putting in a sleep in which isn't necessary/useful in tests, where we want it to run as quick as possible.

The sleep has been kept in "normal" mode as otherwise the status output (`[backfill progress] | finished run %s of %s |` etc.) will be essentially spammed, rather than only being printed every few seconds.

This makes the tests/jobs/ run in about 20s (vs 120s without the change.)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by ephraimbuddy — APPROVED** [review]

**Comment by uranusjr** [comment]
I wonder if we should just make `heartbeat` read the configuration directly instead of using `only_if_necessary`. That’s make it easier to further customise the behaviour for unit tests if we need to.

**Comment by ashb** [comment]
> I wonder if we should just make `heartbeat` read the configuration directly instead of using `only_if_necessary`. That’s make it easier to further customise the behaviour for unit tests if we need to.

`heartbeat()` is in BaseJob, and different jobs want different behavoiur here, so the "best" I think we could do is to provide override heartbeat in BackfillJob. But then we'd have to call `conf.getboolean` each time (or cache it -- it's a suprisingly slow operation)

So I'm not sure it really buys is that much.

**Comment by uranusjr** [comment]
Cool then, I was just wondering (and we can always make the change if it’s actually needed)

**Review by uranusjr — APPROVED** [review]
CI really doesn’t like to run today…

**Comment by ashb** [comment]
> CI really doesn’t like to run today…

It's running now -- just a bit of a queue

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Don't need tests for this one. :shipit:

**Pull request merged**
