### PR TITLE
[AIRFLOW-3600] Remove dagbag from trigger

### PR DESCRIPTION
**Pull request by ffinfo**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3600
  - https://issues.apache.org/jira/browse/AIRFLOW-3562

### Description

Removed DagBag from trigger call

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
@ffinfo can you explain the reasoning behind this PR?

**Comment by ffinfo** [comment]
@Fokko I did forgot the link in jira for this. This is part of AIRFLOW-3562

**Comment by Fokko** [comment]
Ok, thanks!

**Comment by feng-tao** [comment]
@ffinfo , @Fokko , it seems that trigger_dag test is quite flaky(test_trigger_dag_button), I have seen it fails in couples of prs(e.g: https://travis-ci.org/apache/airflow/jobs/476146347) especially on mysql ORM. Do you guys know what is happening?

**Comment by feng-tao** [comment]
@ffinfo , please let me know if you will investigate the issue. If not, I prefer to revert this change until the flaky test is fixed. What do you think @Fokko ?

**Comment by Fokko** [comment]
```
======================================================================
42) FAIL: test_trigger_dag_button (tests.www_rbac.test_views.TestTriggerDag)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/www_rbac/test_views.py line 1476 in test_trigger_dag_button
      self.assertIsNotNone(run)
   AssertionError: unexpectedly None
```
Hmm, are you sure that this PR is the source?

**Comment by feng-tao** [comment]
@Fokko , looking at recent commit, this is the one that modifies this part of the code. And the CI is not always fails with this test(sometimes works, sometimes not). Hence I suspect this pr is the case.

And we are not sure when this pr checked in CI is broken or not, right?

**Comment by feng-tao** [comment]
another failure in https://travis-ci.org/apache/airflow/jobs/476638427 for https://github.com/apache/airflow/pull/4436. It seems the test fails very consistently with mysql ORM.

**Pull request merged**
