### PR TITLE
[AIRFLOW-5773] Migrate AWS Athena components to /providers/aws [AIP-21]

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5773
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR migrates all AWS Athena components to `/providers/aws`. Since this is the first out of many AWS component to migrate, this PR also creates new modules and `__init__.py` files in `/providers/aws` and required config in docs.

Related PR migrating all AWS components, but decided to split because of size: https://github.com/apache/airflow/pull/6439.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add tests and note in UPDATING.md file?
https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py

**Comment by BasPH** [comment]
@mik-laj I don't understand the purpose of this file, what is it actually testing?

**Comment by mik-laj** [comment]
@BasPH This tests backwards compatibility. Ensures that the class is still available in the old location. When loading the module from the old location, a message with information about the new location must also be reported.  There are also tests in the same file that check if a message is reported when you try to use a class with the old name. This applies to the next steps when changing operator names. This test is very important because it makes it much easier to verify the correctness of the change.

Another saying. This facilitates the boring review process.

**Comment by mik-laj** [comment]
Can you add a note in UPDATING.md file?  Sorry to create confusion and I didn't say it before. Ie. I said in [the edited comment](https://github.com/apache/airflow/pull/6446#issuecomment-546682906), but Github may not have refreshed the comment.

**Comment by BasPH** [comment]
Added tests & section to UPDATING.md.

**Comment by mik-laj** [comment]
Awesome.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
