### PR TITLE
[AIRFLOW-4894]Add hook and operator for GCP DLP

### PR DESCRIPTION
**Pull request by zzlbuaa**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-4894) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Add a hook and operator for GCP Data Loss Prevention(DLP).

DLP API allows users to inspect or redact sensitive data in text contents or GCP storage locations.

The hook includes the following APIs that addresses most use cases in sensitive data inspection and redaction:
 - inspect/deidentify/reidentify for content items
 - create/delete/get/list/patch for inspectTemplates and storedInfoTypes
 - create/list/get/delete/cancel for dlpJobs

Since the dlp job are long-running and created asynchronously, the operator creates a dlp job(for storage inspection or risk analysis), keeps polling its status and waits for it to be done or canceled/deleted.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
See tests/contrib/hooks/test_gcp_data_loss_prevention_hook.py
and tests/contrib/operators/test_gcp_run_dlp_job.py

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ryanyuan** [comment]
@zzlbuaa I almost finished this feature for the ticket I’ve raised: [AIRFLOW-4811](https://issues.apache.org/jira/browse/AIRFLOW-4811). Have you checked if there are any exisiting tickets before you created one?

Please also notice that we are trying to move GCP codes from discovery API to its own python library. So if the feature is present in the python library, we should avoid using discovery API. 

Reference: #5531

**Comment by zzlbuaa** [comment]
@ryanyuan I'm new to open-source project and didn't create a ticket when I started working on this feature, and failed to check existing tickets in the process.

But one concern about GCP python client library is that it claims to have alpha support for DLP which is "still a work-in-progress and is more likely to get backwards-incompatible updates"[1], and that's one reason I used discovery API.

[1] https://github.com/googleapis/google-cloud-python

**Comment by mik-laj** [comment]
Alternative implementation is available: 
https://github.com/apache/airflow/pull/5539

**Comment by mik-laj** [comment]
@zzlbuaa Here is a guide that discusses the creation of integration with GCP.
https://docs.google.com/document/d/1_rTdJSLCt0eyrAylmmgYc3yZr-_h51fVlnvMmWqhCkY/edit?ts=5bb72dfd#heading=h.3sxddzjr5f6q

**Comment by ryanyuan** [comment]
@zzlbuaa Welcome!

In the future, when beta or GA comes out, it would be much easier and more backward compatible to migrate from alpha instead of discovery API. We also use alpha for GCP Container service and Text-to-Speech service.

**Comment by zzlbuaa** [comment]
> @zzlbuaa Here is a guide that discusses the creation of integration with GCP.
> https://docs.google.com/document/d/1_rTdJSLCt0eyrAylmmgYc3yZr-_h51fVlnvMmWqhCkY/edit?ts=5bb72dfd#heading=h.3sxddzjr5f6q

Thanks for the guide, it's very helpful. Curious, is this doc public or where can I find the doc if I don't have this link? @mik-laj

**Comment by mik-laj** [comment]
@zzlbuaa it's available on dev list:
https://lists.apache.org/thread.html/e8534d82be611ae7bcb21ba371546a4278aad117d5e50361fd8f14fe@%3Cdev.airflow.apache.org%3E
We plan to attach this document to the official documentation.

**Comment by criccomini** [comment]
@mik-laj @ryanyuan can you please provide guidance on how we're going to resolve the fact that we have two PRs?

Also, re: discovery vs GCP python library, I asked Google cloud PMs at last year's GCP Next what the deal is between these two libraries, and they 1) weren't aware of who even owned GCP python library 2) recommended using discovery API as features will be available there before the other library.

Also, the Google doc is locked. :(

cc @fenglu-g

**Comment by ryanyuan** [comment]
@criccomini 
Re: Client library vs api client, you can check the official explanation from here: 
https://cloud.google.com/apis/docs/client-libraries-explained

> Google Cloud Client Libraries use our latest client library model and are our recommended option for accessing Cloud APIs programmatically, where available.

**Comment by criccomini** [comment]
What's the diff between PRs other than the client libraries being used?

It looks like they both take `body` as a raw config. Am I missing anything else?

**Comment by mik-laj** [comment]
I think it is worth using native libraries - google-cloud-python. This is recommended in the guide. 
A native library allows you to provide improvements that may not exist now, but when we decide to use this library we will have a chance to use them in the future. Recently, native libraries appear very quickly. I noticed that they appeared earlier than the official REST documentation API has been updated.
 
If a Google employee does not appear in the discussion, we will have to accept solution supported by most people. However, I think an Google employee will appear quickly.

+1 for @ryanyuan implementation.

CC : @potiuk @kaxil  @wwlian @nuclearpinguin @sprzedwojski

**Comment by zzlbuaa** [comment]
@criccomini 
Re: diff between PRs
1. I did not cover deidentify-templates and job_triggers api calls in the hook, while @ryanyuan did. 
2. He has multiple operators corresponding to each single API calls, while I have only one run_dlp_job() operator to create a dlp-job asynchronously and keep polling its status until finish or fail/cancel, which calls create_dlp_job() and get_dlp_job().

**Comment by criccomini** [comment]
@zzlbuaa , @ryanyuan seems to only have one operator as well (as far as I can tell):

```
class RunDlpJobOperator(BaseOperator):
```

**Comment by zzlbuaa** [comment]
@criccomini, @ryanyuan seems to have multiple operators here: https://github.com/apache/airflow/pull/5539/commits/ecb67a2d68a0fa189e1b3810e65c1489604bb3bd#diff-03cb053ae7181e1396bf2d07ec755dc6

**Comment by criccomini** [comment]
Ah ha. Somehow GH wasn't loading full diff. :|

**Comment by criccomini** [comment]
Can we get either one of these in 1.10.4?

cc @ashb

**Comment by mik-laj** [comment]
@ryanyuan implementation have system tests also.  It's important, because this is the only sure way to automatically check the correct operation of the operator. 
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+System+Tests+for+external+systems

I think that we should make a decision about the library and then work on a specific PR and fill in its gaps.

**Comment by criccomini** [comment]
I'm fine with either PR. I just want to be able to either 1) cherry pick it into 1.10.3 with minimal merge conflicts and have it work or 2) get it into 1.10.4 so we can use it...

**Comment by mik-laj** [comment]
it does not have to go into the release so you can use it.  All you have to do is copy files with hook and operator to your directory with Airflow and import operators, like any other Python class.

**Comment by criccomini** [comment]
Yes, I'm aware of that. However, we don't fork open source projects. Without a commit in master, copy/paste starts to border on fork-ish. What I'm asking in (1) is a clean cherry pick, which at least means we're using a commit that's on master.

Also, for the record, @alexvanboxel and I discussed a long time ago about whether to use the discovery library or the idiomatic client, and landed on discovery because of the more immediate API access and also because of incompatibility between the discovery library and google-cloud library transitive dependencies. If you guys are changing this, please don't post them in a private Google doc buried in a thread from 2018.

**Comment by criccomini** [comment]
https://issues.apache.org/jira/browse/AIRFLOW-15

So, yea, here's the JIRA where we explicitly remove GCloud client

And here's the (still open) JIRA where we rebase the old stuff:

https://issues.apache.org/jira/browse/AIRFLOW-1894

Anyway.. mostly just grumbling that none of this is clearly documented. We burned quite a bit of time on this.

**Comment by mik-laj** [comment]
I contacted the Composer team. The best option is to use google-cloud-python. Discovery API is deprecated. All operators should use a google-cloud-python library, if it is possible. The alpha version API is not an exception, because the API is versioned.

Because we have two PRs about the same service, I'm closing this PR.

Further discussion available at:
https://github.com/apache/airflow/pull/5539

**Pull request closed without merging**
