### PR TITLE
build(chart): update statsd-exporter to 0.28.0

### PR DESCRIPTION
**Pull request by Lee-W**
## Why
https://github.com/apache/airflow/actions/runs/11828396054/job/32960017155

## What
 build(chart): update statsd-exporter to 0.28.0 #44009 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Review by jedcunningham — CHANGES_REQUESTED** [review]
Need a newsfragment for it, otherwise LGTM.

**Comment by Lee-W** [comment]
> Need a newsfragment for it, otherwise LGTM.

Just added! Thanks!

**Review by jedcunningham — APPROVED** [review]

**Review by jedcunningham — CHANGES_REQUESTED** [review]
Oops, actually, it needs to go in `chart/newsfragments` instead.

**Review by jedcunningham — APPROVED** [review]
(@Lee-W I'll give it a green so you can merge once you've fixed it)

**Comment by Lee-W** [comment]
> Oops, actually, it needs to go in `chart/newsfragments` instead.

ah got it, didn't notice there's this folder. let me fix it now

**Review by eladkal — CHANGES_REQUESTED** [review]
Why this PR targets v2-10-test branch?
Helm chart is released from main branch

**Comment by Lee-W** [comment]
> Why this PR targets v2-10-test branch? Helm chart is released from main branch

Hmmm... this is just for fixing the CI failure on `v2-10-test`

**Comment by Lee-W** [comment]
> > > Why this PR targets v2-10-test branch? Helm chart is released from main branch
> > 
> > 
> > Hmmm... this is just for fixing the CI failure on `v2-10-test`
> 
> Then why the newsfragment? I think me and Jed see this as feature not an internal fix to the CI. Is this already avaliable in main branch and this is just the "chery pick" to fix the CI?

Just notice there's indeed a PR for this on the main branch https://github.com/apache/airflow/pull/43393, but it was not backported

**Comment by eladkal** [comment]
> > > > Why this PR targets v2-10-test branch? Helm chart is released from main branch
> > > 
> > > 
> > > Hmmm... this is just for fixing the CI failure on `v2-10-test`
> > 
> > 
> > Then why the newsfragment? I think me and Jed see this as feature not an internal fix to the CI. Is this already avaliable in main branch and this is just the "chery pick" to fix the CI?
> 
> Just notice there's indeed a PR for this on the main branch #43393, but it was not backported

Ok then we need this PR against v2-10-test to be only backport and new pr against main with the newsfragment

**Comment by Lee-W** [comment]
> > > > > Why this PR targets v2-10-test branch? Helm chart is released from main branch
> > > > 
> > > > 
> > > > Hmmm... this is just for fixing the CI failure on `v2-10-test`
> > > 
> > > 
> > > Then why the newsfragment? I think me and Jed see this as feature not an internal fix to the CI. Is this already avaliable in main branch and this is just the "chery pick" to fix the CI?
> > 
> > 
> > Just notice there's indeed a PR for this on the main branch #43393, but it was not backported
> 
> Ok then we need this PR against v2-10-test to be only backport and new pr against main with the newsfragment

Sounds good. Then I think I don't need to do anything for this one, but will need to create an new one to main (for newsfragment)

**Comment by eladkal** [comment]
No need for news fragment on this PR after the fix in main

**Comment by Lee-W** [comment]
it seems to be fixed already. close this one

**Pull request closed without merging**
