### PR TITLE
[AIRFLOW-895] Address Apache release incompliancies

### PR DESCRIPTION
**Pull request by bolkedebruin**
Fixes missing licenses in NOTICE. Corrects license header and
removes HighCharts left overs.

Please accept this PR that addresses the following issues:
- AIRFLOW-895

@aoen @criccomini @mistercrunch

### CODE REVIEW

**Comment by artwr** [comment]
LGTM +1

**Comment by artwr** [comment]
Thanks for fixing this @bolkedebruin

**Comment by mistercrunch** [comment]
LGTM +1

**Comment by bolkedebruin** [comment]
Build is successful: https://travis-ci.org/bolkedebruin/airflow/builds/204756018 will merge

**Pull request closed without merging**
