### PR TITLE
Add global volume & volumeMounts to the chart

### LINKED ISSUE #27687: Allow global volume & volumeMounts in Helm chart
### Description

I think we should add this option to avoid repeating the declaration in all the component's subsections.
It would be something similar to `env`

### Use case/motivation

Avoid repeating volume & volumeMounts along all components

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by csp33**
closes: #27687 
Adds a global way to add volumes & volumeMounts for all containers (same as `env` for env vars)
image
image

### CODE REVIEW

**Comment by potiuk** [comment]
Small fix in static checks. But otherwise LGTM

**Review by potiuk — APPROVED** [review]
Others?

**Comment by csp33** [comment]
> Small fix in static checks. But otherwise LGTM

should be fixed now :)

**Comment by eladkal** [comment]
Static checks are failing

**Comment by csp33** [comment]
> Static checks are failing

Fixed

**Review by jedcunningham — APPROVED** [review]

**Comment by csp33** [comment]
Can this PR be merged now? @potiuk @jedcunningham  
Thanks!

**Comment by jedcunningham** [comment]
Thanks @csp33!

**Pull request merged**
