### PR TITLE
Convert Helm tests to use the new Python Breeze

### LINKED ISSUE #23085: Breeze: Running K8S tests with Kind with Breeze
There is the whole "kind" set of commands that should be implemented in the new Breeze. 

There are few sub-commands there that can be implemented gradually.

### PR DESCRIPTION
**Pull request by potiuk**
This PR converts the Helm tests to use the new Python Breeze.
It has all the features of previous Kind breeze command and more.

All the commands are now grupped under k8s group and they are very
easy to use locally (even easier than the previous version).

The CI part is also converted and simplified - i.e. the upgrade
test is now much faster (only tests one upgrade per job and it
runs withing the original Helm/Kubernetes tests jobs so it will
not have the cluster creation overhead.

Most importantly - this is almost the last step before we can get
rid of the old legacy breeze code and one that we can get rid of
the `./breeze-legacy` script because all functionality from the
old breeze has been moved to the Python version with this change.

This removl allows us also to remove a lot of the common library
bash code that is not used any more anywhere - even in CI.

The only change left is running regular tests in parallel.

Closes: #23085

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Almost the last one to replace old breeze. This one is big but it replaces the `kind` functionality used for Helm tests. 

I still will have to test the parallel runs and ci  but wanted to push it now.

**Comment by potiuk** [comment]
cc: @rossturk - this one also removes the breeze-legacy and we are getting very, very close to replacing it completely (but I already removed all the movie references from BREEZE.rst.

**Comment by potiuk** [comment]
I believe this one should be already green and mergable, and it is what I wanted it to be. It's WAY nicer comparing to what we had before and as explained in #26091 we will be able to further improve the development experience of Airlfow running on K8S for everyone as a follow-up.

@dstandish @ephraimbuddy  @jedcunningham  - I think you were one of the users there (or maybe non-users because of not-so-great experience).

This Python-Breeze version has a lot of improvements comparing to the legacy bash one:

* The CI has 1-1 mapping to the local development commands. You follow exactly the same sequence locally to run tests locally as you do in CI (screenshot below)

* The commands are consistent with the rest of the commands of breeze , and allow both local single-cluster running as well as CI running in parallel 

* The documentation is simplified - some of the duplication was removed and it's much clearer now how to approach it IMHO

* Also the commands to setup testable Airlfow instance are pretty much "wizard-like" (@rossturk that is the result of our discussions). When you create cluster, it tells you "NEXT STEP:" that you should configure it and tells you the command, when you configure it it asks you to build k8s as "NEXT STEP" and tells the command, and so on. It basically guides the user step-by-step on what to do next. You can literally re-run all k8c tests by running `breeze k8s create-cluster` and following the "NEXT STEPS" instructions. 

* The "K8S upgrade" step is now part of the regular jobs. We save a lot of time for setting up the clusters and deploying airlfow again as they are already set-up in previous steps and we simply need to add one "upgrade" step with some changed valiues (@ephraimbuddy  - you will be happy). This makes the tests less resource hungry and faster.

* I found and fixed a few stability issues that plagued us with the Helm tests. They should be much more solid now in general. That included necessary increase in our CI machine - to add more inotify watchers on system level for example (and few other lower-level stuff).

* It's all Python

* The output of CI is really nice and tells exactly what happens

Example succesful run with multiple clusters in parallel:

https://github.com/apache/airflow/runs/8114807752?check_suite_focus=true

Some screenshots:

Steps in the CI job:

image

Job summary:

image


Job details after unfolding:

image

**Comment by potiuk** [comment]
cc: @eladkal @Bowrna @edithturn -> Really close (I am looking at Bowrna's PR next).

**Comment by potiuk** [comment]
ALL GREEN!  Finally!

**Comment by potiuk** [comment]
Gently poking here .... - Less `bash` == GOOD

**Comment by potiuk** [comment]
I know it's big, but I could not figure a way how to split it - because it basically removes bash and replaces it with Python in Breeze and there are enough differences that it is hard to get this one half-done.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
