### PR TITLE
Bump typing-extensions and mypy for ParamSpec

### PR DESCRIPTION
**Pull request by uranusjr**
I want to use them in some `@task` signature improvements. Mypy added this in 0.950, but let's just bump to latest since why not.

Changelog of typing-extensions is spotty before 4.0, but ParamSpec was introduced some time before that (likely some time in 2021), and it seems to be a reasonble minimum to bump to.

See [PEP 612](https://peps.python.org/pep-0612/) for more about ParamSpec if you’re interested. But in short, it solves our problem when typing `@task`—the resulting task should accept the same arguments as the wrapped function inside, but when called should return an XComArg, instead of the wrapped function’s return value.

```python
# This is a Callable[[int, str], str]
def foo(a: int, b: str) -> str:
    return b * a

# How can we type the wrapped task as Callable[[int, str] XComArg]?
# ParamSpec makes this possible.
@task
def foo(a: int, b: str) -> str:
    return b * a
```

### CODE REVIEW

**Comment by potiuk** [comment]
Nice! Let's see how many errors it will produce to fix though :)

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
```
Run mypy for core......................................................................Failed
- hook id: run-mypy
- exit code: 2
/opt/airflow/airflow/providers/google/cloud/hooks/dataflow.py:541: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.961
/opt/airflow/airflow/providers/google/cloud/hooks/dataflow.py:541: : note: please use --show-traceback to print a traceback when reporting a bug
Run mypy for providers.................................................................Failed
- hook id: run-mypy
- exit code: 2
airflow/providers/google/cloud/hooks/dataflow.py:541: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.961
airflow/providers/google/cloud/hooks/dataflow.py:541: : note: please use --show-traceback to print a traceback when reporting a bug
```

Oh no

**Comment by uranusjr** [comment]
Alright, the failures are fixed. I am not sure with a lot of the changes I made, so please give an eye if you could.

**Review by potiuk — APPROVED** [review]
NIce!

**Pull request merged**
