### PR TITLE
Upgrade Postgres client in Docker images

### PR DESCRIPTION
**Pull request by mik-laj**
This client is a bit outdated.
```
$ docker run --rm --entrypoint sh python:3.7-slim-buster -c "apt update && apt search postgresql-client"
...

postgresql-client/oldstable 11+200+deb10u4 all
  front-end programs for PostgreSQL (supported version)

...
$ docker run --rm --entrypoint sh python:3.7-slim-bullseye -c "apt update && apt search postgresql-client"

...
postgresql-client/stable 13+225 all
  front-end programs for PostgreSQL (supported version)
...
```
When we install a package from the official repository, we have `14` version.

In addition, it unifies the parameters regarding the installation of database clients. Now we have a separate parameter for each database.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
NICE.

**Comment by potiuk** [comment]
I re-run it with "full tests needed" to see if it will work for all Python versions :)

**Comment by mik-laj** [comment]
One test failed, but it looks unrelated.
```
tests/providers/redis/operators/test_redis_publish.py::TestRedisPublishOperator::test_execute_hello: TypeError: 'NoneType' object is not subscriptable

```

**Comment by mik-laj** [comment]
We have a latest client in image
```
#10 22.28 Setting up postgresql-client-common (238.pgdg100+1) ...
#10 22.28 Setting up postgresql-client-14 (14.2-1.pgdg100+1) ...
#10 22.75 update-alternatives: using /usr/share/postgresql/14/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
#10 22.76 Setting up postgresql-client (14+238.pgdg100+1) ...
```

**Pull request merged**
