### PR TITLE
When either data_profiler_filter or superuser_filter aren't defined,…

### PR DESCRIPTION
**Pull request by mtagle**
… don't crash, and set user to have data_profiler or superuser access.

At present, if data_profiler_filter or superuser_filter aren't defined, dataprofiler and superuser aren't set in LDAPUser's init, resulting an an AttributeError when accessors are called.

### CODE REVIEW

**Comment by mistercrunch** [comment]
@bolkedebruin

**Comment by criccomini** [comment]
@bolkedebruin btw, without this patch, LDAP on master won't work unless dataprofiler/superuser filters are set (i.e. master is broken for default use case right now).

**Comment by bolkedebruin** [comment]
Ok. Will have a look at it towards the end of this week

**Comment by criccomini** [comment]
Gentle nudge here. :)

**Comment by bolkedebruin** [comment]
@criccomini In general the patch looks solid! I would like to see the tests also cover the use of data_profiler and superuser. This would require to add it to the ldap provisioning for a specific user.

After that please squash your commits in some meaningful ones.

**Comment by mtagle** [comment]
@bolkedebruin can you elaborate a bit on what you mean by "tests covering the use of data_profiler and superuser"?

**Comment by criccomini** [comment]
@mtagle I think he means that he wants a test that adds several users to the LDAP test. One would be a user with just basic access (no data profiler/super user), one with just data profiler, and one with just super user (and potentially one with both). Then verify that the data_profiler() and superuser() methods return True/False as expected.

**Comment by bolkedebruin** [comment]
Correct. The provisioning can be done by the files no need to encapsulate it in the test itself.

**Comment by mtagle** [comment]
@bolkedebruin could I get a further review/merge?

**Comment by mtagle** [comment]
ping @mistercrunch

**Comment by criccomini** [comment]
@mistercrunch I think this is ready to be committed.

**Comment by mistercrunch** [comment]
:+1:

**Pull request merged**
