### PR TITLE
Add a tip to trigger DAG screen

### PR DESCRIPTION
**Pull request by mik-laj**
Screenshot 2020-05-28 at 12 27 37

---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Worth adding a test to assert the text when `/trigger` is called?

**Comment by ashb** [comment]
> Worth adding a test to assert the text when `/trigger` is called?

Probably not -- we've already got tests that we can trigger config, checking that this text is shown feels like very low value, and unlikely to catch any bugs/regressions.

**Comment by mik-laj** [comment]
@mik-laj I'm not sure. Tests should test behavior, and this is a static value. The correct behaviour of this page should be covered by an existing test. For me, this is decoration, not application logic, so it doesn't have to be tested by unit test. That could lead to a nightmare because we couldn't easily make any changes. In the perfect world, it should be tested by the visual regression test. Such tests are easier to maintain.

**Comment by kaxil** [comment]
Yup, convinced :)

**Pull request merged**
