### PR TITLE
fix: try002 for provider cncf kubernetes

### LINKED ISSUE #38761: Fix remaining `TRY002` - raising `Exception` into the providers codebase
### Body

Follow-up task for https://github.com/apache/airflow/pull/38756

We enable this rule for avoid use to broad `Exception` raises in codebase which hard to catch
because it always required to catch `Exception` which might catch also other errors (TBH all of the errors which are not subclassed of `BaseException`).

### Easy way to find all linting problem into the module
1. Remove corresponding line to particular module into the [`pyproject.toml`](https://github.com/apache/airflow/blob/main/pyproject.toml#L381) in [tool.ruff.lint.per-file-ignores] related to ignore `TRY002` in providers.
2. Run ruff via [pre-commit](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst#pre-commit-hooks) hook 

```console
❯ pre-commit run ruff --all-files
Run 'ruff' for extremely fast Python linting.............................Failed
- hook id: ruff
- exit code: 1

airflow/providers/docker/operators/docker_swarm.py:150:19: TRY002 Create your own exception
airflow/providers/docker/operators/docker_swarm.py:172:23: TRY002 Create your own exception
airflow/providers/docker/operators/docker_swarm.py:177:19: TRY002 Create your own exception
airflow/providers/docker/operators/docker_swarm.py:186:19: TRY002 Create your own exception
Found 4 errors.

```

Some potential changes examples

```diff
         if not self.service:
-            raise Exception("The 'service' should be initialized before!")
+            raise RuntimeError("The 'service' should be initialized before!")
```

```diff
         try:
             from pandas.io import sql as psql
         except ImportError:
-            raise Exception(
+            raise AirflowOptionalProviderFeatureException(
                 "pandas library not installed, run: pip install "
                 "'apache-airflow-providers-common-sql[pandas]'."
             )

```

> [!TIP]
> Feel free to ask a suggestion/helps in slack channels `#contributors` or `#new-contributors`

> [!NOTE]
> It should not affect related tests but it would be nice to change `pytest.raises(Exception)` in related tests,
> however it could be done in other tasks later on, e.g. when we turn on 
> [`B017` assert-raises-exception](https://docs.astral.sh/ruff/rules/assert-raises-exception/)

> [!WARNING]
> Please consider to make changes in the one provider in the time

## Provider [airbyte](https://github.com/apache/airflow/tree/main/airflow/providers/airbyte)
- [x] `airflow/providers/airbyte/hooks/airbyte.py`
- [x] `airflow/providers/airbyte/operators/airbyte.py`
- [x] `airflow/providers/airbyte/sensors/airbyte.py`

## Provider [alibaba](https://github.com/apache/airflow/tree/main/airflow/providers/alibaba)
- [x] `airflow/providers/alibaba/cloud/hooks/oss.py`

## Provider [amazon](https://github.com/apache/airflow/tree/main/airflow/providers/amazon)
- [x] `airflow/providers/amazon/aws/operators/athena.py`
- [x] `airflow/providers/amazon/aws/operators/emr.py`

## Provider [apache.beam](https://github.com/apache/airflow/tree/main/airflow/providers/apache/beam)
- [x] `airflow/providers/apache/beam/hooks/beam.py`

## Provider [apache.cassandra](https://github.com/apache/airflow/tree/main/airflow/providers/apache/cassandra)
- [x] `airflow/providers/apache/cassandra/hooks/cassandra.py`

## Provider [apache.hdfs](https://github.com/apache/airflow/tree/main/airflow/providers/apache/hdfs)
- [x] `airflow/providers/apache/hdfs/hooks/hdfs.py`
- [x] `airflow/providers/apache/hdfs/sensors/hdfs.py`

## Provider [apache.hive](https://github.com/apache/airflow/tree/main/airflow/providers/apache/hive)
- [x] `airflow/providers/apache/hive/hooks/hive.py`

## Provider [cncf.kubernetes](https://github.com/apache/airflow/tree/main/airflow/providers/cncf/kubernetes)
- [ ] `airflow/providers/cncf/kubernetes/operators/pod.py`

## Provider [common.sql](https://github.com/apache/airflow/tree/main/airflow/providers/common/sql)
- [x] `airflow/providers/common/sql/hooks/sql.py`

## Provider [docker](https://github.com/apache/airflow/tree/main/airflow/providers/docker)
- [x] `airflow/providers/docker/operators/docker_swarm.py`

## Provider [fab](https://github.com/apache/airflow/tree/main/airflow/providers/fab)
- [x] `airflow/providers/fab/auth_manager/fab_auth_manager.py`
- [x] `airflow/providers/fab/auth_manager/security_manager/override.py`

## Provider [google](https://github.com/apache/airflow/tree/main/airflow/providers/google)
- [x] `airflow/providers/google/cloud/hooks/bigquery.py`
- [x] `airflow/providers/google/cloud/hooks/dataflow.py`
- [x] `airflow/providers/google/cloud/hooks/dataproc.py`
- [x] `airflow/providers/google/cloud/operators/dataproc.py`
- [x] `airflow/providers/google/leveldb/hooks/leveldb.py`

## Provider [imap](https://github.com/apache/airflow/tree/main/airflow/providers/imap)
- [x] `airflow/providers/imap/hooks/imap.py`

## Provider [microsoft.azure](https://github.com/apache/airflow/tree/main/airflow/providers/microsoft/azure)
- [x] `airflow/providers/microsoft/azure/operators/synapse.py`

## Provider [openlineage](https://github.com/apache/airflow/tree/main/airflow/providers/openlineage)
- [x] `airflow/providers/openlineage/utils/utils.py`

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by dondaum**
closes: #38761 

fix TRY002 for provider cncf kubernetes

### [cncf.kubernetes](https://github.com/apache/airflow/tree/main/airflow/providers/cncf/kubernetes)

- [x] airflow/providers/cncf/kubernetes/operators/pod.py

No affected test.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — APPROVED** [review]

**Comment by eladkal** [comment]
There are conflics to resolve

**Review by eladkal — APPROVED** [review]

**Comment by dondaum** [comment]
> There are conflics to resolve

Fixed. 

All try002 changes update the same pyproject.toml which lead to a lot of conflicts.

**Review by Taragolis — APPROVED** [review]

**Comment by Taragolis** [comment]
And the last rebase required. In addition could you also remove `# All the providers modules which do not follow TRY002 yet` since it the last PR which close https://github.com/apache/airflow/issues/38761

**Comment by dondaum** [comment]
> And the last rebase required. In addition could you also remove `# All the providers modules which do not follow TRY002 yet` since it the last PR which close #38761

Sure. Done. Thanks for all the support.

**Pull request merged**
