### PR TITLE
Initializes RedshiftSqlHook by extending the PostgresHook 

### PR DESCRIPTION
**Pull request by frankcash**
related: #16544

---

Adds `class RedshiftSqlHook`  that utilizes the `PostgresHook` to create a specific Hook for the Redshift SQL use case.  

**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by JavierLopezT** [comment]
I would call it just `RedshiftHook`

**Comment by frankcash** [comment]
I have no problem with that, in-fact I thought about it.  I just feel it could be confusing as there already is a `RedshiftHook` <https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/hooks/redshift.py#L25-L37>, but I am not sure of what type of applications there would be for having both of these hooks in the same task or even DAG as Redshift infra modifications are typically very slow

**Comment by JavierLopezT** [comment]
Given that all SQL-related hooks (Postgres, MySql, Snowflake...) don't have SQL in their names, and that most of the developers will start using RedshiftHook coming from PostgresHook, I would leave the code in a class called RedshiftHook. I think it can actually be in the same class as the other functions of redshift.

Also, the static checks and docs are failing. I would recommend you to use breeze for being aware of these fails in your local computer https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#setting-up-breeze

I have spent a lot of time making pull requests without Breeze, and believe me, it's worth the time you spend configuring everything because otherwise, you'll spend even more time making changes, uploading them to git, waiting for another run of the tests...

**Comment by uranusjr** [comment]
While I understand the superiority in the design aspect of putting everything in `RedshiftHook`, it is quite resource-consuming to implement since `AwsBaseHook` and `PostgresHook` have very different features and you can’t easily subclass them both. So the only choice would be composition, i.e. something like

```python
class RedshiftHook(BaseHook):
    def __init__(self, ...):
        ...
        self._aws_hook = AwsBaseHook(...)
        self._sql_hook = PostgresHook(...)

	# Cluster functions...
    def cluster_status(self, cluster_identifier: str) -> str:
        return self._aws_hook.get_conn()...

	# SQL functions...
    def get_records(self, sql, parameters=None):
        return self._sql_hook.get_records(sql, parameters=parameters)
```

It would be non-trivial to get everything line up correctly and cause maintenance burden. Splitting the AWS and SQL functionalities into two hooks is the better engineering solution IMO.

**Comment by josh-fell** [comment]
There may be some overlap between the desired functionality of this PR and #18447 which adds both a `RedshiftStatementHook` and `RedshiftOperator`. Just wanted to bring this up to the group.

**Pull request closed without merging**
