### PR TITLE
[AIRFLOW-1793] fix DockerOperator using docker_conn_id

### PR DESCRIPTION
**Pull request by m1racoli**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

There was a typo when instantiating the DockerHook from `docker_conn_id` using `base_url` instead of `docker_url`.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

The test `test_execute_with_docker_conn_id_use_hook` exists already.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks. Add test please so it wont happen again

**Comment by m1racoli** [comment]
I have adjusted the test `test_execute_with_docker_conn_id_use_hook` mocking the `DockerHook` constructor directly instead of the `get_hook` function of the operator.

**Comment by m1racoli** [comment]
Is something missing for this PR?

**Comment by ron819** [comment]
@m1racoli There are conflicts to resolve

**Pull request closed without merging**
