### PR TITLE
Introduce DAG SLA

### LINKED ISSUE #32816: AIP-57 - Implement DAG SLAs
### Description

Implement DAG SLAs as outlined in [AIP-57](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-57+Refactor+SLA+Feature)

This will require the addition of 2 new DAG attributes, and 1 new Dagrun attribute:
[DAG.sla](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L388): None | timedelta
[DAG.on_sla_miss_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L388): None | DagStateChangeCallback | list[DagStateChangeCallback]
[Dagrun.sla_missed](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L118): None | bool

In addition, [Dagrun.update_state](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L522) and [Dag.handle_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L1315) functions must be updated to handle SLA evaluation and SLA miss callbacks.

We will also mark the existing [DAG.sla_miss_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L407) for deprecation.

### Use case/motivation

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by sungwy**
closes #32816

### Summary

This PR introduces Dag SLAs as a part of **AIP-57 Refactor SLA Feature**.

After many discussions, the community has voted to introduce new SLA features aimed at replacing the existing SLA feature which has caused a lot of confusion and dissatisfaction in the user base over the years. The proposal introduces SLAs that are measured and contained within the lifetime of a Dag Run, and within the lifetime of a Task Instance which cost significantly less for the Airflow Infrastructure to compute than the existing concept of SLAs. The proposed SLA callback functions will also accept the TI context as the argument, which is a parameter that is used by other callback types (on_success_callback, on_failure_callback, on_execute_callback) to honor a consistent interface.

#### Added 
        sla: timedelta | None = None
        on_sla_miss_callback: None | DagStateChangeCallback | list[DagStateChangeCallback] = None

#### Marked for Deprecation
        sla_miss_callback: None | SLAMissCallback | list[SLAMissCallback] = None

#### Added 
        sla_missed = Column(Boolean, default=False)

#### Added
        sla_miss: bool | None = False
        dagrun_state: DagRunState
#### Removed
        is_failure_callback: bool | None = True

### Dag SLA Measurement Semantics 
SLA tracking logic is evaluated when the active Dag Run is checked for updates using DagRun.update_state which is executed in the main scheduling loop. Dag SLA is tracked for all run types except for DagRunType.BACKFILL_JOB if **sla** parameter is provided in the Dag definition. 

If **sla_missed** attribute of the Dag Run is already set to True, the scheduler loop will skip the SLA check for that dag run. This condition ensures that the SLA miss callback is generated only once when a scheduler loop has detected that the dag run has just missed its SLA and has been made the corresponding Dag Run record update in the DB.

SLA is measured against the time between the Dag Run start_date (time) and the current time. If SLA is less than the time between the current time and the Dag Run start_date, SLA has been missed for the active Dag Run. Using the start_date (instead of the scheduled start time according to the time table) allows us to keep a consistent measuring pattern across MANUAL and SCHEDULED run types, and keep the SLA evaluation logic simple for the initial version of this feature.

SLA callback is indicated by the sla_miss boolean flag on DagCallbackRequest. The State of the DagRun corresponding to the DagCallbackRequest is propagated through the dagrun_state parameter, which is also used to deduce whether a on_success_callback or a on_failure_callback must be executed along with the request. It is now possible for a DagCallbackRequest to be issued without a finished DagRun State (SUCCESS or FAILED); it is upto dagrun.handle_callback function to parse the parameters and execute the appropriate callback related to the given DagRun State or sla_miss flag.

### Note:
is_failure_callback is kept in DagCallbackRequest for backward compatibility, and is only used if dagrun_state parameter is not available on a given callback. This allows the Airflow instance to also be able to properly support DagCallbackRequests that were generated prior to the Airflow version upgrade, that have not yet been executed.

### CODE REVIEW

**Comment by syun64** [comment]
@dstandish @potiuk could I ask for your review on this PR?

**Comment by dstandish** [comment]
why do we rename `sla_miss_callback` to `on_ sla_miss_callback`?

**Comment by syun64** [comment]
> why do we rename `sla_miss_callback` to `on_ sla_miss_callback`?

We aren't renaming it, it's a different feature entirely. `sla_miss_callback` is the callback for the existing SLA mechanism that measures the SLA as a diff between the DAG and the task. `on_sla_miss_callback` is the callback with different argument interface that will be used. I was on the fence about the naming, but folks suggested against introducing a new name for the feature in discussions on [AIP-57](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-57+Refactor+SLA+Feature). So this is a cheap way of getting around naming collision between the old feature and the new feature, during the time the old feature is maintained prior to deprecation.

**Comment by michael-robbins-seek** [comment]
Will this DAG SLA be compatible at all with Data-aware scheduled dags?

**Comment by dstandish** [comment]
@syun64 sorry that i have not been active on this for a while.  my concern is that i don't think it's an SLA if it's evaluated against "when it started" -- i think an SLA is about "when it should have run"

the customer doesn't care when your dag started, they care about when their data is updated.  that is an overly-broad generalization but i think it illustrates the point.

i think that we can and should add an SLA on the dag. but to me i don't think that it's an SLA if you're evaluating against when it started running, even if for example the run started very late.

i think the fact that "when it should have run" does not make sense for manually triggered or dataset-triggered dags is not a good reason to change the definition for scheduled dags.  i think we need to come up with a different solution for those kinds of dags.

**Comment by mtsadler-branch** [comment]
@dstandish are you proposing to simply replace `start_date` with `data_interval_start` in this PR's code changes?

**Comment by dstandish** [comment]
> @dstandish are you proposing to simply replace `start_date` with `data_interval_start` in this PR's code changes?

I am not sure that interval start is the time when it's expected to run.  Isn't interval _end_ closer to that?

In any case, there are some folks who are picking this back up namely @eladkal @ferruzzi @shubham22 and you could chat with them perhaps on slack / github discussion / dev list to if you want to engage and help get SLA to a good place for Airflow 3.

**Comment by uranusjr** [comment]
The `run_after` value in `DagRunInfo` is probably the best for this purpose, but I’m not sure if it is available in this context.

**Comment by ferruzzi** [comment]
As @dstandish mentioned/alluded, for Airflow 3 (Coming Soon :tm:) we intend to do a complete overhaul of the existing SLA system so I'm not sure there is any benefit to reviving this PR at this point.  

The existing SLA system has been a constant source of discussion, debate, and confusion pretty much since it was introduced so the plan is to tear it out and replace it with a more clear implementation and better documentation in 3.0.  There will be a new AIP with a proposal for the complete rework of the SLA system Very Soon :tm: (sorry I can't be more specific, I have a few things in the air but it's a very high priority)

**Pull request closed without merging**
