### PR TITLE
[AIRFLOW-4981][AIRFLOW-4788] Always use pendulum DateTimes in task in…

### PR DESCRIPTION
**Pull request by arlopurcell**
…stance context

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-4981
  - https://issues.apache.org/jira/browse/AIRFLOW-4788

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
In certain situations, like when using fixed cron schedules such as `0
12 * * *`, the `execution_date`, `prev_execution_date`, and
`next_execution_date` variables in macros were native python `datetime`
objects instead of, as stated in the docs, pendulum `DateTime` objects.

### Tests

- [x] My PR adds the following unit tests 
  - `tests.models.test_taskinstance:TaskInstanceTest.test_pendulum_template_dates`
### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Simpler :)

**Comment by arlopurcell** [comment]
Thanks! Now the build is failing to even run the pre-test checks because `Package 'libmysqlclient-dev' has no installation candidate`? I don't think this is because of my change. 

For what it's worth, all the test are passing locally when i run `./scripts/ci/local_ci_run_airflow_testing.sh`

**Comment by ashb** [comment]
Rebase on to latest master should fix that hopefully

**Comment by arlopurcell** [comment]
Well, it's better after rebasing, but not quite working.

**Comment by arlopurcell** [comment]
One more rebase and we're there!

**Comment by arlopurcell** [comment]
Is there anything else I have to do to get this merged?

**Pull request merged**
