### PR TITLE
fix(chart): webserver probes timeout and period.

### PR DESCRIPTION
**Pull request by mikaeld**
Description
---
This PR fixes the default probes timeout and period values. Generally,  `timeoutSeconds` should be smaller than `periodSeconds`. Here are a [SO question](https://stackoverflow.com/questions/63308717/what-is-the-role-of-timeoutseconds-in-kubernetes-liveness-readiness-probes) addressing this issue and a [blog post](https://cloud.redhat.com/blog/liveness-and-readiness-probes) detailing the Liveness and Readiness Probes. Furthermore, some specific k8s implementations such as GKE [do not allow](https://cloud.google.com/load-balancing/docs/health-check-concepts#probes)  `timeoutSeconds` > `periodSeconds`.

> The timeout is the amount of time that Google Cloud waits for a response to a probe. Its value must be less than or equal to the check interval. Units are seconds.

Finally, the webserver probes are the only ones with default values where  `timeoutSeconds` > `periodSeconds`.

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Can you update the default values in the webserver deployment too?
https://github.com/apache/airflow/blob/73e03131d2003ea0c41d8721fff16ed836eb54aa/chart/templates/webserver/webserver-deployment.yaml#L206-L209
and
https://github.com/apache/airflow/blob/73e03131d2003ea0c41d8721fff16ed836eb54aa/chart/templates/webserver/webserver-deployment.yaml#L220-L223

**Comment by jedcunningham** [comment]
Just remove them instead. They'll never get used.

**Review by hussein-awala — APPROVED** [review]
LGTM

**Review by potiuk — APPROVED** [review]
Yep. Looks like those defaults are much more reasonable @jedcunningham @ephraimbuddy @dstandish -> do you recal (or maybe have some Astronomer setup for the chart) to know where the original settings were derived from ? Maybe there are good reasons the original settings were like that?

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
