### PR TITLE
Avoid too many conflicts when generating breeze images

### PR DESCRIPTION
**Pull request by potiuk**
The `breeze setup regenerate-command-images` used hash calculation to determine when to regenerate commands. There was only one file with hashes for all commands which often cause conflicts if several people changed adjacent commands. Also when one of the subcommands changed, this immediately invalidated the "parent" command where the subcommand was, however such invalidation is only needed if a new subcommand is added or if name or help description of the subcommand changes - because this is the only information displayed in the parent command.

This PR improves hash calculation and verification and calculation to avoid conflicts as much as possible. The hash will only have conflict when the same command is modified by the same people in parallel (signifying that indeed you need to regenerate the image for that command). This is achieved by:

* splitting hashes to separate files - each command has its own .txt file where hash of the command is kept

* when hash of the group command is calculated, only name and help text of the subcommands for the group are used to calculate hash

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Recently I noticed we have way more people working in paralell on some - often unrelated breeze commands, and that caused constant conflict generation when several people modified just neighbouring commands and commands that belonged to the same group - this change aims on reducint the number of conflicts by distributing the hashes among multiple files and by changing the algorithm to calculate "group" hashes to not change when subcommand's parameters change.

**Review by pierrejeambrun — COMMENTED** [review]
Really nice, this is something that I frequently encountered, and got used to just not solve conflicts add everything and rerun the command manually to get the latest image and hash update.

This will be a nice quality of life improvement!

Can’t do an in depth review atm but code looks good :)

**Comment by potiuk** [comment]
> Really nice, this is something that I frequently encountered, and got used to just not solve conflicts add everything and rerun the command manually to get the latest image and hash update.
> 
> This will be a nice quality of life improvement!
> 
> Can’t do an in depth review atm but code looks good :)

That's the goal :)

**Comment by potiuk** [comment]
> Really nice, this is something that I frequently encountered, and got used to just not solve conflicts add everything and rerun the command manually to get the latest image and hash update.

Right now those will also just run autoamtically when pre-commit is run (improved it last week).  Actually it was not a big issue until several people started to work on parallel on those breeze commands - or added things like new providers, changing versions of k8s, adding new static checks, adding new commands that indirectly influence the commands (by updating list of packages or list of versions of software or list of new providers etc. etc. 

Note that it will not solve all conflicts - if two people will add providers in-parallel, the second one to merge will still get conflict - but it will be a good one, it really means that you **should** regenerate the screenshots (and it will happen automatically once you resolve the conflict and commit it. 

But there should be far less conflicts where adding new K8s version for example will clash with new static check added because those will modify differnet command files.

**Comment by potiuk** [comment]
OK. Needed to also sort the parameters (otherwise their sequence was depending on the sequence of filed checked out by git :exploding_head:

**Comment by potiuk** [comment]
Should be ready :)

**Comment by utkarsharma2** [comment]
This is nice and much required change. :)
In our recent attempt to add an LLM provider, we had to get the PRs merged sequentially which was very time-consuming. Going forward such efforts should be quicker.

**Comment by amoghrajesh** [comment]
Really good! 
Very relatable issue with a nice elegant fix :)

**Review by amoghrajesh — APPROVED** [review]
> The hash will only have conflict when the same command is modified by the same people in parallel
Love this!

LGTM

**Review by utkarsharma2 — APPROVED** [review]

**Pull request merged**
