### PR TITLE
[AIRFLOW-286] Improve FTPHook to implement context manager interface

### PR DESCRIPTION
**Pull request by skudriashev**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-286

Testing Done:
- all unit tests passed on Travis CI

### CODE REVIEW

**Comment by skudriashev** [comment]
@bolkedebruin, please take a look :)

**Comment by skudriashev** [comment]
@mistercrunch, could you, please, have a look? Thanks.

**Comment by criccomini** [comment]
LGTM

**Comment by skudriashev** [comment]
@criccomini, thanks!

**Comment by jlowin** [comment]
Nice PR @skudriashev

**Comment by skudriashev** [comment]
@jlowin, thanks :smiley:

**Pull request closed without merging**
