### PR TITLE
Add more type annotations to AWS hooks

### PR DESCRIPTION
**Pull request by coopergillan**
### BEST REVIEWED COMMIT-BY-COMMIT

Add type annotations to several more AWS hooks. Fill in the last annotation for a few others as well.

related: #9708

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by coopergillan** [comment]
I need some help understanding the "no pylint" failure. It looks like it has to do with `black` formatting:

```bash
black.............................................................................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/runner/work/airflow/airflow/airflow/providers/amazon/aws/hooks/aws_dynamodb.py
reformatted /home/runner/work/airflow/airflow/airflow/providers/amazon/aws/hooks/base_aws.py
reformatted /home/runner/work/airflow/airflow/airflow/providers/amazon/aws/hooks/kinesis.py
All done! ✨ 🍰 ✨
3 files reformatted, 1440 files left unchanged.
```

Is this requiring that `black` formatting be included?

**Comment by potiuk** [comment]
There was an issue with latest release of black (released few days ago) that stopped respecting our configuration when running pre-commits. Please rebase to latest master @coopergillan (we just merged a workaround where we pinned black to  a working version (and opened an issue in black to get it fixed https://github.com/psf/black/issues/1667).

**Comment by coopergillan** [comment]
Hmmm, still failing. Do I need to make the changes shown in the CI failure output?

**Comment by mik-laj** [comment]
I pushed fixup commit. It should work now.

**Comment by coopergillan** [comment]
Thanks @mik-laj - did you have to copy paste the output in CI or is there a simple way to run `black`? Guessing I would want to be inside the `breeze` container?

**Comment by mik-laj** [comment]
When I'm on the local computer and have access to the repository, I ran:
```
pre-commit run black --all-files
```
ore-commit doesn't work in Breeze.

**Comment by coopergillan** [comment]
@mik-laj - got it, thanks. I haven't been able to get `pre-commit` to work so far. Is it compatible with `zsh`?

**Comment by potiuk** [comment]
> @mik-laj - got it, thanks. I haven't been able to get `pre-commit` to work so far. Is it compatible with `zsh`?

Can you share some more info on what does not work with pre-commit ?

Both pre-commit and breeze's should work with zsh. In fact black pre-commit works using black's docker image so it should work just fine even without breeze installed.

I guess you are on Mac @coopergillan ? 

If you have properly installed pre-commit python package (and python 3 as default) there might be problems with your docker installation.

Could you please check what settings do you have for Docker? Our dev env is pretty docker-heavy and default settings for Mac's docker might not be good enough. Docker on Mac runs in a separate VM and it has to have enough resources allocated (Docker -> Preferences):

2.5 GB memory, 2 CPU and 100GB of disc should be enough - but if you have far less disk/memory you might have various troubles:

If you have too much disk used for Docker - you can either increase it or follow the "troubleshooting" section in Breeze.rst - it has some steps explaining how you can clean it up.

**Comment by potiuk** [comment]
You can also try to run `pre-commit` via breeze. Breeze has 'static-check` command that makes sure that pre-commit is installed in your virtualenv and supports autocompletion. and it seems to work for your branch:
```
[jaroslawpotiuk:~/code/airflow] add-more-type-annotation-to-aws-packages+ 127 ± ./breeze static-check black -- --all-files

   CI image.

   Branch name:             master
   Docker image:            apache/airflow:master-python3.6-ci

   Airflow source version:  2.0.0.dev0
   Python version:          3.6
   DockerHub user:          apache
   DockerHub repo:          airflow
   Backend:                 sqlite


Making sure pre-commit is installed


Running: pre-commit run black --show-diff-on-failure --all-files

black....................................................................Passed

```

**Comment by coopergillan** [comment]
@potiuk - this is some great info, thanks. Usually I'm developing on a debian box inside of `breeze`. I haven't played with many of the menu options for `breeze` so I will give those a shot!

**Comment by mik-laj** [comment]
@coopergillan Should we use https://pypi.org/project/boto3-stubs/ or other similar packages?

**Comment by coopergillan** [comment]
@mik-laj - I haven't heard of that package. That looks interesting. I would have to check it out 👀

**Review by feluelle — APPROVED** [review]

**Comment by mik-laj** [comment]
@coopergillan  Should we merge it?

**Comment by coopergillan** [comment]
@mik-laj - just now getting back to this and seeing the approval. If you guys think this is good enough for now, let's merge it. I am happy to look into that package you provided though.

**Comment by coopergillan** [comment]
@mik-laj - wondering now it would be better to merge this and then open an issue to come back through and add more detail to the `boto3` type annotations. What do you think?

Any opinion @feluelle?

**Comment by mik-laj** [comment]
@coopergillan I'm on vacation Friday-Monday. I think we can merge it as is for now, but I'd like to look at it before merging.

**Comment by coopergillan** [comment]
Have a great time!

**Comment by feluelle** [comment]
It looks interesting, but I think it is better to introduce that (with a new dependency) in another PR. And look more in detail what it does and how it works.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
