### PR TITLE
Fixed an error introduced in selective checks

### PR DESCRIPTION
**Pull request by potiuk**
A few remnants of earlier version of the script caused occasional
errors. Error introduced in #11541

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @ephraimbuddy

**Comment by potiuk** [comment]
I noticed a typo (remnant from previous version of the script) causing failure fof @ephraimbuddy PR https://github.com/apache/airflow/pull/11261  . This is the fix. I think it should be merged even if it fails (the failing scripts are in master now :(

**Comment by ephraimbuddy** [comment]
Nice!!

**Comment by potiuk** [comment]
> Nice!!

Not really :(. Somehow my automated refactor missed it :(

**Comment by potiuk** [comment]
I do not know exactly how PRs from Github behave. sometimes they return "merge_comit_sha" and sometimes (like it was in this case) it was null. I switched to regular. github.sha everywhere (should be exactly the same). It should be fixed now.

**Comment by potiuk** [comment]
Hey @ephraimbuddy -> can you please rebase your PR on master - this is rather strange as my pRs are running fine rebaed on latest master q

**Comment by ephraimbuddy** [comment]
Ok

**Comment by potiuk** [comment]
REally strange error :(

**Pull request closed without merging**
