### PR TITLE
[AIRFLOW-4930] Send druid ingestion spec as data, not json

### PR DESCRIPTION
**Pull request by zxzl**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4930
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

https://issues.apache.org/jira/browse/AIRFLOW-4930

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
- Druid hook sends json string using `json=` argument of requests library, which makes it impossible to be parsed by Druid coordinator

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- I added the case `test_submit_correct_json_body` at druid_hook test. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by OmerJog** [comment]
@ashb @kaxil @potiuk  can review?

**Comment by awelsh93** [comment]
The change from data to json was in #3633 due to unicode issues - there is an unresolved comment (https://github.com/apache/airflow/pull/3633#issuecomment-458586850) which may be an alternative fix to your problem.

**Comment by zxzl** [comment]
@awelsh93 Thanks for letting me know relevant comment and previous issues. 

Yes I agree with https://github.com/apache/airflow/pull/3633#issuecomment-458586850 - druid operator passes json string (https://github.com/happyjulie/incubator-airflow/blob/d2b4035ee53db0751c87d390833afeefd6902084/airflow/contrib/operators/druid_operator.py#L61) but `json=` parameter in requests is for encoding dicts. 

I think it will be better if druid operator passes just dict loaded from json.

**Comment by OmerJog** [comment]
@Fokko  maybe you can give your input on the suggestion

**Review by Fokko — COMMENTED** [review]
Sorry for the late response. Thank you @OmerJog for pinging me. Would it be possible to annotate the `json_index_spec` argument in the function as a string? Passing this as data instead of json makes more sense.

**Comment by zxzl** [comment]
@Fokko Thanks for taking a look. I just added a `str` annotation to function - would you please check it ?

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
This should be in 2.0.0 and 1.10.7. Thanks @zxzl

**Pull request merged**
