### PR TITLE
[AIRFLOW-5088][AIP-24][BackPort] Persisting serialized DAG in DB for webserver scalability

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5088
  - https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-24+DAG+Persistence+in+DB+using+JSON+for+Airflow+Webserver+and+%28optional%29+Scheduler

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
**Backport of https://github.com/apache/airflow/pull/5743 for v1-10-* branches **
Based on #5701, this PR implements functionalities including writing serialized DAGs to DB in scheduler, reading DAGs from DB in webserver, controlled by [core] dagcached

The goal is to decouple webserver from the DAG folder, instead it reads everything from database.

Rendering template by functions is an exception, in that case it needs to re-import DAG, because functions are stringified in serialized DAG.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

cc @coufon

### CODE REVIEW

**Comment by kaxil** [comment]
**ToDo**:
- [x] Graph View & Tree View are broken currently because  https://github.com/apache/airflow/pull/5874 has not been merged to v1-10-* branch yet (The Graph View & Tree View uses `_upstream_tasks` to create an edge between tasks), so either we need to include `_upstream_tasks` attribute to the serialized JSON or we need to backport that PR in v1-10-* branches. - **Backported that PR in** 9b5fa1abb3970213c0ba68a0b212fc6dfdbad4db

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by tooptoop4** [comment]
cfg points to broken link https://airflow.apache.org/howto/enable-dag-serialization.html

**Comment by kaxil** [comment]
Thanks, will update it.

**Comment by kaxil** [comment]
Correct Link in case you are looking for it is:
https://airflow.apache.org/docs/1.10.7/dag-serialization.html

**Comment by tooptoop4** [comment]
for a .py that generates multi dynamic dags how can parsing the dag be avoided?

**Pull request merged**
