### PR TITLE
[AIRFLOW-4146] Fix CgroupTaskRunner errors

### PR DESCRIPTION
**Pull request by youngyjd**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [AIRFLOW-4146](https://issues.apache.org/jira/browse/AIRFLOW-4146) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4146
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
1. CgroupTaskRunner import errors is fixed in this PR.
2. Node.name() is encoded but it works fine in python2. However, python3 returns False for `'abc' = b'abc'`. We have to decode it since python2 support has been dropped in this project.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
1. Add test to ensure that `CgroupTaskRunner._init_()` method calls `super()._init_` to initiate CgroupTaskRunner object.
2. Add test to ensure that when task finishes, `CgroupTaskRunner.on_finish()` will call `super().on_finish()` to delete the temp cfg file.
3. import errors will be captured as well.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
Any chance you could add some unit tests covering some of this too? The CGroup runner isn't much used and without unit tests it will be hard for the Airflow community to continue supporting it (meaning we might remove it in a future version)

**Comment by youngyjd** [comment]
@ashb how do you want this to be tested? cgroup must be mounted on the system first to make this taskrunner work.

**Comment by feng-tao** [comment]
@youngyjd do we have existing tests for cgroupTaskRunner? If not, could we add that which we could mock the actual cgroup routine?

**Comment by youngyjd** [comment]
@feng-tao @ashb We don't have existing tests for CgroupTaskRunner, that's why even there is a package import error in CgroupTaskRunner but it has not been fixed ever. I haven't written any test for cgroups before so don't have an idea. Based on what I understand, cgroup first must be mount on disk first and `cgroup-bin` Ubuntu package must be installed, otherwise https://github.com/apache/airflow/blob/9e72767b8e4de7f5d18f7051a47344d4d94e6143/airflow/contrib/task_runner/cgroup_task_runner.py#L172 command will fail.

I have also looked into cgourpspy python package's source code and tests are few https://github.com/cloudsigma/cgroupspy/tree/master/cgroupspy. I am feeling that it is because cgroup relies on OS manipulation behavior so testing and mocking is hard?

I am not able to test unittest for CgroupTaskRunner on my Mac because Mac does not support Cgroup. I was not able to test it in Docker either because Docker is already running in a cgroup so it will enter this condition https://github.com/apache/airflow/blob/9e72767b8e4de7f5d18f7051a47344d4d94e6143/airflow/contrib/task_runner/cgroup_task_runner.py#L121-#L129, which skips the core functionality for CgroupTaskRunner.

How I verified this fix is working is that I pushed this change to our staging environment and directly tested it there, so it took me really a long time to get it work. 

See this original PR for CgroupTaskRunner: https://github.com/apache/airflow/pull/1934. The author just tested it in Airbnb Prod environment actually without writing any unittest.

What comes to my mind is that we can test import errors in CgroupTaskRunner so if base_task_runner.py moves to another location again, the test can capture it. I know this does not sound ideal, but I don't know what I can do. 

I am actually willing to write tests if you can provide me some examples and suggestions.

**Comment by ashb** [comment]
Even an a basic test checking for import errors would be better than nothing yes! If you can add something like that then we can merge this PR.

Yeah looking at how the runner is currently implemented it would be a right pain to mock. If you are up for it (in another PR) porting to cgroupspy would make it better to test.

Alternatively/additionally an extra "Job" in Travis (since that runs on Linux outside of docker) may be worth it. Lot more work so understand if you don't have time to do that

**Comment by feng-tao** [comment]
Agree, @youngyjd we could start with providing initial unit test coverages on certain methods and refactor the code to be easy testable later :)

**Review by feng-tao — APPROVED** [review]

**Comment by youngyjd** [comment]
@ashb Unittests regarding CgroupTaskRunner init and on_finish behavior have been added. Import error will be captured as well. Can you please take a look?

**Pull request merged**
