### PR TITLE
[AIRFLOW-2597] Restore original dbapi.run() behavior

### PR DESCRIPTION
**Pull request by KevinYang21**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2597) issues and references them in the PR title.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes
dbapi.run() right now commits only when autocommit is set to true or db does not support autocommit. Restoring behavior before [this commit](https://github.com/apache/incubator-airflow/commit/d642e38ec7eac129739042e77f78b1dae4f2615e#diff-3f191f9ec6c3dfda1cd2ef79a01725aa).
This is breaking CI now.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
fixes tests/operators/operators.py:PostgresTest.test_postgres_to_postgres

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by KevinYang21** [comment]
I was misunderstanding what `should_commit` was for and thus [this change](https://github.com/apache/incubator-airflow/pull/3485) doesn't completely fix the failing CI (~not sure why the CI passed in the PR tho~ cuz [this PR](https://github.com/apache/incubator-airflow/pull/3487) was created afterwards and merged before my PR was merged).

@imroc, I'm basically reverting your change, I don't see why it was not working for you before your change. Can you elaborate please? Thank you

@Fokko @bolkedebruin @artwr @kaxil @feng-tao PTAL

**Comment by feng-tao** [comment]
I think we should be very careful on any backward incompatible change and document it in the updating.md with unit test if it is really needed. I am +1 on the revert.

**Comment by kaxil** [comment]
Hmm.. Weird why the CI passed for that PR then... But yes, I am reverting the change. @imroc Please elaborate your issue here.

**Comment by KevinYang21** [comment]
@kaxil I edited my comment earlier, the PR you previously helped me merged passed the CI because [this PR](https://github.com/apache/incubator-airflow/pull/3487) was created afterwards and merged before my PR was merged.

**Comment by kaxil** [comment]
Oh ok 👍  @yrqls21 . @Fokko Can you please have a look if the failing K8s test is related or not? That's the only test that is failing on master now.

**Comment by imroc** [comment]
@kaxil @yrqls21  I wrote a DAG before, including some data insertion operation of mysql like this:
``` python 
hook = MySqlHook(mysql_conn_id='mysql_default', schema='test')

hook.run(
    'insert into some_table(some_field) values(%s)' % (some_value),
    autocommit=True)
```
After the task runs, data is not inserted, because it was not committed, But I set `autocommit=True`, I think it was a bug, so I submitted [this commit](https://github.com/apache/incubator-airflow/commit/d642e38ec7eac129739042e77f78b1dae4f2615e#diff-3f191f9ec6c3dfda1cd2ef79a01725aa)，and then it works, is it wrong with my usage?

**Comment by feng-tao** [comment]
@imroc , I think typically you should run session.commit() after the sql execution to persist the result. Besides you change the dbapi interface which inherits by most of the dbapi hooks which not all the hooks have autocommit support.

**Comment by KevinYang21** [comment]
@imroc You are correct, the query won't be committed for MySqlHook.run() even autocommit is set to `True`. Did some researches an I'm pretty sure it is because MySql [set autocommit in a different way](https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/connections.py#L249-L256). It should be `conn.autocommit(True)` instead of `conn.autocommit = True` like others. 

I shall do a quick PR to fix that. ETA tomorrow night.

**Comment by imroc** [comment]
@yrqls21  nice

**Pull request closed without merging**
