### PR TITLE
Add SIGUSR2 handler to Scheduler to dump executor state

### PR DESCRIPTION
**Pull request by ashb**
This provides a means to get a snapshot of the in-memory state of state
a running scheduler, without having to turn on debug logging/restart the
process.

```
[2020-11-05 14:02:07,856] {{airflow.jobs.scheduler_job.SchedulerJob scheduler_job.py:759}} INFO - --------------------------------------------------------------------------------
SIGUSR2 received, printing debug
--------------------------------------------------------------------------------
[2020-11-05 14:02:07,857] {{airflow.executors.celery_executor.CeleryExecutor base_executor.py:303}} INFO - executor.queued (0)
	
[2020-11-05 14:02:07,857] {{airflow.executors.celery_executor.CeleryExecutor base_executor.py:305}} INFO - executor.running (0)
	
[2020-11-05 14:02:07,857] {{airflow.executors.celery_executor.CeleryExecutor base_executor.py:309}} INFO - executor.event_buffer (0)
	
[2020-11-05 14:02:07,857] {{airflow.executors.celery_executor.CeleryExecutor celery_executor.py:361}} INFO - executor.tasks (0)
	
[2020-11-05 14:02:07,858] {{airflow.executors.celery_executor.CeleryExecutor celery_executor.py:366}} INFO - executor.adopted_task_timeouts (0)
	
[2020-11-05 14:02:07,858] {{airflow.jobs.scheduler_job.SchedulerJob scheduler_job.py:762}} INFO - --------------------------------------------------------------------------------
```

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add docs? I am thinking of the CLI command epilogue. Example: https://github.com/apache/airflow/blob/31dc6cf82734690bf95ade4554e7ebb183055311/airflow/cli/cli_parser.py#L1156

**Comment by ashb** [comment]
> Can you add docs? I am thinking of the CLI command epilogue. Example:
> 
> https://github.com/apache/airflow/blob/31dc6cf82734690bf95ade4554e7ebb183055311/airflow/cli/cli_parser.py#L1156

Done!

```
Start a scheduler instance

optional arguments:
  -h, --help            show this help message and exit
  -D, --daemon          Daemonize instead of running in the foreground
  -p, --do-pickle       Attempt to pickle the DAG object to send over to the workers, instead of letting workers run their version of the code
  -l LOG_FILE, --log-file LOG_FILE
                        Location of the log file
  -n NUM_RUNS, --num-runs NUM_RUNS
                        Set the number of runs to execute before exiting
  --pid [PID]           PID file location
  --stderr STDERR       Redirect stderr to this file
  --stdout STDOUT       Redirect stdout to this file
  -S SUBDIR, --subdir SUBDIR
                        File location or directory from which to look for the dag. Defaults to '[AIRFLOW_HOME]/dags' where [AIRFLOW_HOME] is the value you set for 'AIRFLOW_HOME' config you set in 'airflow.cfg' 

Signals:

  - SIGUSR2: Dump a snapshot of task state being tracked by the executor

```

**Comment by mik-laj** [comment]
Can you also call example? This will make my work easier, because I won't have to look for an example on the internet always.

```
pkill -USR2 airflow
```

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Done, and made the DagFile parser processes ignore this signal, making the `pkill -l "airflow scheduler" work` nicely

**Comment by ashb** [comment]
```
Signals:

  - SIGUSR2: Dump a snapshot of task state being tracked by the executor.

    Example:
        pkill -f -USR2 "airflow scheduler"
```

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
