### PR TITLE
Add airflow upgrade

### PR DESCRIPTION
**Pull request by turbaszek**
This PR is cherrypicking existing changes to v1-10-stable as per 
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#airflow-git-branches

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by turbaszek** [comment]
@ashb @potiuk let me know if I should split this to many PRs or just force push from my branch to stable

**Comment by ashb** [comment]
@turbaszek When doing cherry picks to v1-10-* we use the `-x` flag:

>  `-x`
>  When recording the commit, append a line that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit this change was cherry-picked from. This is done only for cherry picks without conflicts. Do not use this option if you are cherry-picking from your private branch because the information is useless to the recipient. If on the other hand you are cherry-picking between two publicly visible branches (e.g. backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful.

Is it much work to re-do these cherry picks to include those? Or to edit all the commit messages here to include the messages?

**Comment by potiuk** [comment]
@ashb  I think we should be Ok with the current approach - we have everything wee neeed to match the commits (PR#) and they are exactly with the commits that we have in v1-10-test, so when we later rebase v1-10-stable on top of v1-10-test (which I presume will happen) those commits from v1-10-stable will become empty commits and will be skipped automatically with `rebase --skip` - and we will be left with the commits from v1-10-test with proper "commit-from".

**Comment by turbaszek** [comment]
I can redo with `-x` as it's a minute of work (no conflicts)

**Comment by ashb** [comment]
Except we'd rebase v1-10-test on to v1-10-stable wouldn't we, so the commits on stable would be the ones we keep, no?

**Comment by potiuk** [comment]
I think it doesn't matter which way we rebase eventually.

**Comment by ashb** [comment]
Personally I've been treating v1-10-stable like we treat master -- i.e. don't rebase without a very good reason.

**Comment by potiuk** [comment]
Fine for me :). I think maybe it would be great to document the process we have on that, this way we would not have to make any personal assumptions. For sure - as learning we have to propose and document it all for the time when we will have more branches - when we branch off 2.0, we will have many more branches as we still are going to support 1.10 for quite a while.

**Comment by potiuk** [comment]
After Tomek's experience with telling people to make PRs to 1-10-test I added the mising explanation on v1-10-test/v1-10-stable branches in https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#airflow-git-branches  but maybe it's worth to explain the process we do on rebasing and how we treat those branches.

**Comment by turbaszek** [comment]
@ashb please tak a look at the following PRs and let merge them asap as I would like to unblock people with ongoing work:
https://github.com/apache/airflow/pull/11759
https://github.com/apache/airflow/pull/11760
https://github.com/apache/airflow/pull/11761
https://github.com/apache/airflow/pull/11762
https://github.com/apache/airflow/pull/11763
https://github.com/apache/airflow/pull/11764
https://github.com/apache/airflow/pull/11765
https://github.com/apache/airflow/pull/11766

**Comment by ashb** [comment]
Will do just as soon as I've walked the dog and had coffee!

**Comment by ashb** [comment]
Thanks for doing that @turbaszek - A nice git history makes me happy :D.

I'm going to close all but the last PR as it contains the commits from the previous ones, and I'll manually merge it (i.e. not using the github UI) to preserve the individual commits.

**Comment by turbaszek** [comment]
> Thanks for doing that @turbaszek - A nice git history makes me happy :D.
> 
> I'm going to close all but the last PR as it contains the commits from the previous ones, and I'll manually merge it (i.e. not using the github UI) to preserve the individual commits.

@ashb then I add rest commits as I didn't cherrypicked all of them

**Comment by ashb** [comment]
@turbaszek Thanks -- for future, we don't need one PR for each, just one for the end state/final commit.

**Comment by ashb** [comment]
Done!

**Pull request closed without merging**
