### PR TITLE
[AIP-51] Remove Executor coupling in ad_hoc_ti_run ui msg

### PR DESCRIPTION
**Pull request by o-nikolas**
Changes:
1. Update the UI warning message to not be coupled to specific executors for `supports_ad_hoc_ti_run`
1. Also move the default value (`False`) for `supports_ad_hoc_ti_run` into the `BaseExecutor` class instead of in `views.py`. All Executors should have the default value of `False`, unless overridden intentionally to `True` (which `CeleryExecutor`, `KubernetesExecutor` and `CeleryKubernetesExecutor` already do)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — APPROVED** [review]

**Review by XD-DENG — APPROVED** [review]

**Comment by XD-DENG** [comment]
Restarted the failed check to see if it's transient failure.

**Comment by XD-DENG** [comment]
Hi @o-nikolas , [the test failed again after I re-triggered it](https://github.com/apache/airflow/actions/runs/3551225297/jobs/5971279713). So it doesn't seem transient.

Please take a look

**Review by XD-DENG — DISMISSED** [review]
Test (https://github.com/apache/airflow/actions/runs/3551225297/jobs/5971279713) failed (still failed after I re-triggered it).

Requesting change to block , in order to avoid accidental merging.

**Comment by o-nikolas** [comment]
> Hi @o-nikolas , [the test failed again after I re-triggered it](https://github.com/apache/airflow/actions/runs/3551225297/jobs/5971279713). So it doesn't seem transient.
> 
> Please take a look

@XD-DENG 
I've increasingly seen tests in PRs failing like this. The step looks like it's simply timing out at around 40+ minutes in the cases I've seen, and you get no logs.

I think there is a way to run the tests with debug logging enabled, but I can't find the magic to trigger that in our readmes. I know @potiuk has mentioned it before, can you weigh in Jarek?

**Review by eladkal — APPROVED** [review]
LGTM

**Pull request merged**
