### PR TITLE
Revert "Update some dependencies (#9684)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit fd62b1c5262086597db2aa439a09d86794a33345.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
My #9690 was done one commit too late. I have not realized that but this setup update actually did break some tests. :). I think we should revert and reapplying this one after #9690. It would not be great to start the Summit with broken master.

**Comment by potiuk** [comment]
```
    def _dot_lookup(thing, comp, import_path):
        try:
>           return getattr(thing, comp)
E           AttributeError: module 'azure.mgmt.containerinstance.operations' has no attribute 'ContainerOperations'
```

**Review by feluelle — APPROVED** [review]
SGTM

**Review by Fokko — COMMENTED** [review]
LGTM

**Review by kaxil — COMMENTED** [review]
LGTM too

**Pull request merged**
