### PR TITLE
[AIRFLOW-3193] Pin docker requirement version

### PR DESCRIPTION
**Pull request by deagon**
Since the change of AIRFLOW-3203, the dockerpy client has upgraded
actually. Therefore, the requirements config should upgrade also to
avoid potentially misleading.

@XD-DENG @Fokko 

---

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3193\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3193
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-3193\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by deagon** [comment]
AIRFLOW-3203 linked to #4049.

**Comment by XD-DENG** [comment]
Thanks @deagon . You're correct: one part of my PR (https://github.com/apache/incubator-airflow/pull/4049) was to address the breaking change in `docker==3.0.0` and we do need to pin the version for it.

This PR looks sensible to me.

**Comment by XD-DENG** [comment]
Hi @ashb , would you mind to add this commit into 1.10.1? 

Understand that my PR #4049 (**[AIRFLOW-3203] Fix DockerOperator & some operator test**) is already cherry-picked into branch v1-10-test. The change made in that PR is partially meant to address a breaking change in Python package `docker==3.0.0`. But I missed to pin the `docker` version in that commit. This may result in issues for users who have `docker < 3.0.0` when they upgrade to 1.10.1.

Cheers.

**Comment by ashb** [comment]
@XD-DENG Ah cool. will do!

**Pull request merged**
