### PR TITLE
Fix typo in pyproject.toml

### PR DESCRIPTION
**Pull request by shahar1**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Review by vincbeck — APPROVED** [review]

**Comment by ashb** [comment]
This should have changed the import position via ruff. Something else might be going wrong.

**Comment by kaxil** [comment]
> This should have changed the import position via ruff. Something else might be going wrong.

@ashb you are right, main started failing. For weird reason it didn't fail on this PR.

PR to fix failures: https://github.com/apache/airflow/pull/43087

**Comment by potiuk** [comment]
@kaxil - @ashb - this one passed because it only triggered "basic checks" - pyproject.toml "non-dependencies" change is not considered as "source file change". Which maybe it should. I also see that "test_common" should be added as sources in selective checks to trigger tests when only test_common files change. PR is coming

**Comment by potiuk** [comment]
Fix to avoid it in the future https://github.com/apache/airflow/pull/43088

**Pull request merged**
