### PR TITLE
Add `languages` field to `get_ui_field_behaviour`

### LINKED ISSUE #41010: Setting the language of textarea field through `get_ui_field_behaviour`
### Description

Hi
While working on the PR https://github.com/apache/airflow/pull/40775 related to connection, I tried using `from flask_appbuilder.fieldwidgets import BS3TextAreaFieldWidget` to receive input in a textarea.

However, all textareas are being treated as JSON columns and are being converted to CodeMirror.
https://github.com/apache/airflow/blob/152d03e546ee72b7a73f78f22c40517a2ab8208f/airflow/www/static/js/connection_form.js#L365-L369

> Snowflake connection**

image

Through the entire Airflow codebase, Snowflake is the only provider using `BS3TextAreaFieldWidget` yet.
However, it would be good for decorating the connection if it could not only JSON but also plain string on textarea

### Use case/motivation

it seems like the existing values of get_ui_field_behaviour wouldn't be able to solve this issue.
so It might be possible to add fields like `textarea_languages` to `get_ui_field_behaviour`.

```python
    @classmethod
    def get_ui_field_behaviour(cls) -> dict[str, Any]:        
        return {
            "hidden_fields": ["host", "schema", "port", "login", "password", "extra"],
            "relabeling": {},
            "placeholders": {},
            "textarea_languages": {"extra": "json", "requirements": "text", "manifest": "yaml"},
        }
```

https://github.com/apache/airflow/blob/b4e82cf66fb4d833a25de5e2688b44e7b4ddf4bb/airflow/customized_form_field_behaviours.schema.json#L4-L26

```json
    "hidden_fields": {...},
    "relabeling": {...},
    "placeholders": {...},
    "textarea_languages": {
      "type": "object",
      "description": "Languages for the textarea fields(`text`, `json`, `yaml`)",
      "additionalProperties": {
        "type": "string"
      }
    }
```

And I looked into it further, and the CodeMirror might also be able to accept YAML input,
so it could handle not just JSON and plain strings, but also YAML

> [codemirror/yaml.min.js](https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/mode/yaml/yaml.min.js)
> [codemirror/yaml-lint.min.js](https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.2/addon/lint/yaml-lint.min.js)

In summary, it would be nice to specify certain columns in languages such as JSON or string. 
(YAML might be too much, so I just wanted to suggest it)

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by softyoungha**
closes: #41010 

Following the context of https://github.com/apache/airflow/issues/41010, add languages to get_ui_field_behaviour to enable the CodeMirror JSON editor for a specific field on the Connection Add/Edit page.

I considered YAML support, but JSON alone should be sufficient for users to define the Connection in the connection hook. I've left room for future modifications if the need arises.

### screenshot: Add Connection for `Kubernetes Cluster Connection`

image

Previously, the entire textarea was set to be changed to CodeMirror, but now only the fields set with json in languages and `extra` will be changed to CodeMirror.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
@jscheffl What are your thoughts?

**Comment by jscheffl** [comment]
I think the current behavior is not well and deserves an extension. Actually I am wondering how it ever worked because in SnowflakeHook also a private key is expected (like you would see in SSH) and JSON would also be non-appropriate.

So thanks for providing an extension.

I just believe it is at the wrong moment of time. We are currently planning to move on to a Airflow 3 release. For this we need to re-work especially the connection form widgets. So all efforts here would need to be thrown away for Airflow 3. Alongside also we are only accepting new features for Airflow 3, means the code you want to contribute will never go live. Probably (Except we miserably fail in planning or change our mind). We defined Airflow 2.10 being the last feature release in the Airflow 2 line and plan only to cut patch releases from there.

I assume we need to put this on the wish list for Airflow 3 and also would be happy if you like to contribute there. But as said, the UI is planned to be fully re-written, which also will affect the connection form. Basics are not settled so as of today it is a bit too early to show something off.

**Comment by potiuk** [comment]
100% with @jscheffl -> let's not loose time and mental energy for improving it for Airflow 2, we need to redesign it from scratch basically fof Airflow 3 basically.

**Comment by bbovenzi** [comment]
Closing for now. I'll let everyone know when the new UI is read for contributions. @softyoungha I would love if you want to get involved when we rebuild these forms.

**Comment by softyoungha** [comment]
@bbovenzi @jscheffl @potiuk 
Thank you for all your responses. 
I understand the situation, and I'll look forward to 3.0 with excitement :)

**Pull request closed without merging**
