### PR TITLE
[AIRFLOW-1142] Do not reset orphaned state for backfills

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

The scheduler could interfere with backfills when it resets the state
of tasks that were considered orphaned. This patch prevents the scheduler
from doing so and adds a guard in the backfill.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

New unit tests added

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

cc: @criccomini @joeschmid

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@aoen @saguziel @amaliujia I consider this a better fix than https://github.com/apache/incubator-airflow/pull/2236 as it is not just subdags affected.

**Comment by saguziel** [comment]
Is using the prefix the canonical way of identifying backfills?

**Comment by amaliujia** [comment]
I just queried our Airflow DB, and found a bunch of dagruns with "scheduled_" run_id prefix but belong to subdag DAGs.

I agree this PR's idea is better(cover backfill jobs). But it might be better to do filtering by querying DB. I updated #2236 and so now it queries DB and filtering out dagruns of subdag. 

I would suggest that still query DB to do filtering.

**Comment by bolkedebruin** [comment]
@amaliujia if you are running already with your patch you would see those in your db. It should not happen without it ("scheduled" in db for sub dag) <== I might be wrong here

*** please show me how a sub dag gets a scheduled run_id ***

If you still think that can happen please provide evidence how that can happen, ie where a subdag can get to "scheduled" dag run id. 

Also note the issue can also happen with normal backfills not just sub dags.

**Comment by bolkedebruin** [comment]
(Sorry was typing on a phone)

**Comment by joeschmid** [comment]
LGTM. I've tested this PR and am comfortable that it reliably addresses the issue we were seeing. (We are heavy users of subdags and had a test DAG with subdags that we used to recreate the issue consistently. I've been running that test DAG against this PR every few minutes without issue.)

@amaliujia I just looked in our Airflow DB and I can't find any rows in dag_run where a subdag had a run_id starting with 'scheduled_'. (I used 'WHERE dag_id LIKE '%.%' to filter for subdags. We have quite a lot of them so I'm pretty confident I would have seen one if it was possible.)

**Comment by bolkedebruin** [comment]
@saguziel it is yes (unfortunately)

**Comment by criccomini** [comment]
+1

**Comment by criccomini** [comment]
Waiting to merge until @amaliujia responds.

**Comment by amaliujia** [comment]
I rechecked the DB and the case I mentioned were old entries. Sorry about that so LGTM.

**Comment by bolkedebruin** [comment]
@saguziel @artwr @aoen this is blocking rc2 for 1.8.1. I think this is the right fix and not #2236 as that only addresses it partially. 

Sub dags are run by the backfill logic and thus their dag runs get set to "backfill_XX" by convention. If you really find subdags with a dag run that has a run id of "scheduled_xx", please verify that this wasn't done manually and explain why it happens (cause I think it shouldn't). 

Can you please have a look?

**Comment by plypaul** [comment]
@amaliujia - I agree with you that we should do filtering on the DB side.

**Comment by plypaul** [comment]
What's the advantage of going with a blacklist (i.e. not scheduling backfill DAGs) vs. a whitelist (i.e. scheduling only DAG runs created by the scheduler)? Is it to handle user-created DAG runs?

**Comment by bolkedebruin** [comment]
@plypaul yes (see also scheduler logic). 

I'm ok with changing to filtering in the db, however the impact should be small (run_id is not indexed in this case)

**Comment by bolkedebruin** [comment]
I'm assuming ok to merge after tests pass (lookup happens in DB now).

**Pull request closed without merging**
