### PR TITLE
[AIRFLOW-245]  Add access to task instance to executors

### PR DESCRIPTION
**Pull request by alexandrnikitin**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- _[AIRFLOW-245](https://issues.apache.org/jira/browse/AIRFLOW-245)_

Testing Done:

Reminders for contributors:
- Your PR's title must reference an issue on [Airflow's JIRA](https://issues.apache.org/jira/browse/AIRFLOW/). For example, a PR called "[AIRFLOW-1] My Amazing PR" would close JIRA issue #1. Please open a new issue if required!
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules).

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please make your commit follow the guidelines (description, commit message etc). In addition please include tests. Thanks!

**Comment by alexandrnikitin** [comment]
@bolkedebruin Thank you for the reply. I changed the commit. Regarding tests: There's not a single test of any of the executors. I don't know where to start from :disappointed:

**Comment by jlowin** [comment]
Something important to keep in mind -- the current version of `execute_async()` just requires the task key (a bunch of strings) and the command that runs the task (another string, something like `airflow run task`). That's because we make no assumptions about how the execution is implemented, or on what machine/environment, or even when it will be run. Passing a task object to the `execute_async()` method is contrary to that assumption. In particular, there is no guarantee that task objects are serializable.

The `key` should give enough information to load the task inside the executor by querying the database for the matching taskinstance -- I think that would be the far preferable way to implement the desired behavior in a custom executor.

**Comment by alexandrnikitin** [comment]
I close it for now.

**Pull request closed without merging**
