### PR TITLE
Add logout button to Airflow

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by criccomini** [comment]
Very basic patch. Tested that it works. One thing that's annoying is that the logout button shows when not logged in. I tried adding:

```
{% if current_user.is_authenticated %}
  <li><a href="{{ url_for('airflow.logout') }}">Logout</a></li>
{% endif %}
```

But it current_user seems totally messed up. When not logged in, current_user is `AnonymousUserMixin`, as expected, but when logged in, it's `None`. Open to suggestions on what to do there.

**Comment by mistercrunch** [comment]
can we use an icon with a tooltip?

Check out `glyphicon-off`

**Comment by criccomini** [comment]
@mistercrunch sure thing. Any ideas on how to make the logout link only show when we're logged in?

**Comment by criccomini** [comment]
Added a glyph. Still displays when logged out, which is annoying. Could use pointers on how to fix that.

**Comment by mistercrunch** [comment]
I'm fine with having it show when people are logged off.

**Pull request merged**
