### PR TITLE
[AIRFLOW-1410] Added flatten_results in bigquery hook constructor, ru…

### PR DESCRIPTION
**Pull request by AlexAslan**
Make sure you have checked _all_ steps below.

### JIRA
- [*] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1410

### Description
- [*] Here are some details about my PR, including screenshots of any UI changes:
	Added flatten_results in bigquery hook constructor, run query and bigquery operator constructor

### Tests
- [*] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
   	Covered by existing tests

### Commits
- [*] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [*] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please add tests and squash your commits

**Comment by kaxil** [comment]
This PR can be closed as this feature has already been added to the respective hook and operators.

@r39132 Can you please close this PR whenever you have time? Sorry for asking you to do this but I have not been able to figure out a way on closing PRs yet (I think I dont have permission to do that).

**Comment by Fokko** [comment]
@kaxil Closing a PR is done using an empty commit (using `--allow-empty`): https://github.com/apache/incubator-airflow/commit/cedcdb1f86e04f03cef13a727bdca00bdf7243be

The `closes apache/incubator-airflow#3403` will be picked up by the apache CI.

**Comment by kaxil** [comment]
Thank you @Fokko for letting me know 👍

**Pull request closed without merging**
