### PR TITLE
Rename `--extras` to `--airflow-extras` from `breeze prod-image build` command

### PR DESCRIPTION
**Pull request by vincbeck**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by ferruzzi** [comment]
Looks like --extras was replaced with --airflow-extras in https://github.com/apache/airflow/pull/23562 [here](https://github.com/apache/airflow/pull/23562/files#diff-ee5066dbc80cf551a440261fe04ef9b781a910ceb5717f392bb630d14b87c08aL230) so rather than remove it, maybe just update the correct new flag?

**Comment by vincbeck** [comment]
> Looks like --extras was replaced with --airflow-extras in #23562 [here](https://github.com/apache/airflow/pull/23562/files#diff-ee5066dbc80cf551a440261fe04ef9b781a910ceb5717f392bb630d14b87c08aL230) so rather than remove it, maybe just update the correct new flag?

You're right, nice catch! The difference between `airflow-extras` and `--additional-airflow-extras` is not clear tome though

**Comment by ferruzzi** [comment]
> The difference between airflow-extras and --additional-airflow-extras is not clear to me though

Yeah, I'm not 100% on the distinction there, but based on the documentation changes in that PR I linked I'm fairly confident that --airflow-extras was a direct replacement for -extras.

I _think_ --additional* is supposed to append to the existing --airflow-extras, but I'm not sure.

**Comment by vincbeck** [comment]
Fixed :)

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Yeah, I'm not 100% on the distinction there, but based on the documentation changes in that PR I linked I'm fairly confident that --airflow-extras was a direct replacement for -extras.
> 
> I _think_ --additional* is supposed to append to the existing --airflow-extras, but I'm not sure.

That was exactly the intention :). Any improvement to wording to explain it better is most welcome.

**Review by ferruzzi — APPROVED** [review]

**Comment by ferruzzi** [comment]
Some checks aren't passing, but they don't look related.   Feel free to merge once those go green.

**Comment by vincbeck** [comment]
> > Yeah, I'm not 100% on the distinction there, but based on the documentation changes in that PR I linked I'm fairly confident that --airflow-extras was a direct replacement for -extras.
> > I _think_ --additional* is supposed to append to the existing --airflow-extras, but I'm not sure.
> 
> That was exactly the intention :). Any improvement to wording to explain it better is most welcome.

I meant what is the value of having `--airflow-extras` and `--additional-airflow-extras` and not only one. What is the difference between `breeze prod-image build --airflow-extras extra1 --additional-airflow-extras extra2` and `breeze prod-image build --airflow-extras extra1,extra2`? It is more for my curiosity than a concern :)

**Comment by potiuk** [comment]
--additional is when you want to add one or two providers to the default ones

--extraa is when you want to change the  base set of extras

This makes a difference for example when you build slim image. Default PROD dockerfile adds about 20 or so extras (commonly used providers - Amazon, Google, etc.) . Slim image had only the pre installed providers which means that --extras is empty.


So in short : use --additional when you want to extend 'reference' image. Use --extras when you want to slim-down the basic set of extras that the reference image has

**Comment by vincbeck** [comment]
> --additional is when you want to add one or two providers to the default ones
> 
> --extraa is when you want to change the base set of extras
> 
> This makes a difference for example when you build slim image. Default PROD dockerfile adds about 20 or so extras (commonly used providers - Amazon, Google, etc.) . Slim image had only the pre installed providers which means that --extras is empty.
> 
> So in short : use --additional when you want to extend 'reference' image. Use --extras when you want to slim-down the basic set of extras that the reference image has

That makes perfect sense! Thanks!

**Pull request merged**
