### PR TITLE
Fixing non NOSASL use of beeline

### LINKED ISSUE #567: hive ldap with auth=noSasl bug
i have a little troube with CDH 5 cluster:
with 

```
<property>
  <name>hive.server2.authentication</name>
  <value>LDAP</value>
</property>
```

this change useful for properly working:

``` diff
diff --git a/airflow/hooks/hive_hooks.py b/airflow/hooks/hive_hooks.py
index 794c78a..ca15a64 100644
--- a/airflow/hooks/hive_hooks.py
+++ b/airflow/hooks/hive_hooks.py
@@ -86,7 +86,7 @@ class HiveCliHook(BaseHook):
                         jdbc_url = (
                             "jdbc:hive2://"
                             "{0}:{1}/{2}"
-                            ";auth=noSasl"
+                            #";auth=noSasl"
                         ).format(conn.host, conn.port, conn.schema)

                     cmd_extra += ['-u', jdbc_url]
```

i.e. NO sasl parameter need in this case, can u fix it?

### PR DESCRIPTION
**Pull request by mistercrunch**
- a bit of refactoring
  closes #567

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@mistercrunch is this entirely in line with #567? Maybe pull authMechanism and use it to set auth when available? That would allow auth=maprsasl as mentioned in the issue thread.

**Comment by mistercrunch** [comment]
@bolkedebruin , here's a second take on it

**Comment by bolkedebruin** [comment]
@mistercrunch seems good to me!

**Comment by syvineckruyk** [comment]
oddly enough in my environment ... I am passing user, schema, and extra parameters to beeline.

 {"use_beeline": true, "auth":"plain", "hive_cli_params": "-i /home/airflow/hiveconf.hql"}

The connection string is actually causing the trailing params/arguments to fail.
(-bash: -n: command not found)

enclosing the connection string in quotes has resolved the issue for me.

Would adding:
jdbc_url = '"{jdbc_url}"'.format(jdbc_url=jdbc_url) 
following:  
jdbc_url = jdbc_url.format(**locals())

be acceptable to you ? It could also be done in a single statement ... but would look a bit odd.

**Comment by syvineckruyk** [comment]
Moving this to a new issue.

**Pull request merged**
