### PR TITLE
Enforce system tests for Google operators

### PR DESCRIPTION
**Pull request by mik-laj**
---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by mik-laj** [comment]
If this change is accepted, I create tickets to fix these problems.

**Comment by turbaszek** [comment]
Adding system tests for Google services requires access to GCP resources (= funds). Should this be a requirement for a contribution to an open-source project?

**Comment by mik-laj** [comment]
Yes. Because we want to ensure high-quality integration with paid services also. If someone wants to write integration to the pad service, he should run it in a real environment and probably it has already started at least once so it's not a barrier.  The problem would be if the user could choose the service and there would be only paid options. There is no choice here. This is the principle of the tool.  Google sells paid services.

**Comment by turbaszek** [comment]
> Yes. Because we want to ensure high-quality integration with paid services also. If someone wants to write integration to the pad service, he should run it in a real environment and probably it has already started at least once so it's not a barrier. 

I agree in general. But what if someone has working operators but has no possibility to run system tests because of some corporate / company rules (creation of additional resources may need approval)?

**Comment by mik-laj** [comment]
So how does he create these operators? Based on your own experience and intuition? The code that goes to the Apache repository should be checked to see if it works properly, and not just look good. If it is not possible to check whether the operators are working, then they should be considered as non-working and should be brought to a usable state.

**Comment by turbaszek** [comment]
I fully understand your concerns. But still I'm not sure if it's common for OSS projects to have such requirements. @potiuk @ash @Fokko @bolkedebruin you are probably more knowledgable than me.

**Comment by potiuk** [comment]
I think we could introduce it once we get more system tests in (I hope to get more people involvement this coming week)

**Comment by potiuk** [comment]
And we should make it really easy and automatically executed .. Before that it makes little sense if we have no way to check that it continues to work.

**Comment by mik-laj** [comment]
What do you think about checking on CI and then informing you that the test is missing, but then let the author of the contribution knowingly decide? I see on the list a few operators that have been prepared by the Polidea team, so they should have system tests. However, these tests do not exist by mistake. Instead of "enforce" it is just to inform.
```
'tests/providers/google/cloud/operators/test_cloud_build_system.py',
'tests/providers/google/cloud/operators/test_datacatalog_system.py',
'tests/providers/google/cloud/operators/test_datafusion_system.py',
'tests/providers/google/cloud/operators/test_sheets_to_gcs_system.py',
'tests/providers/google/cloud/operators/test_speech_to_text_system.py',
'tests/providers/google/cloud/operators/test_text_to_speech_system.py',
'tests/providers/google/cloud/operators/test_translate_speech_system.py',
'tests/providers/google/suite/operators/test_gcs_to_gdrive_system.py',
'tests/providers/google/suite/operators/test_gcs_to_sheets_system.py'
```

**Comment by turbaszek** [comment]
> So how does he create these operators? Based on your own experience and intuition? The code that goes to the Apache repository should be checked to see if it works properly, and not just look good.

@mik-laj I've just encountered a problem with CheckOperators in BQ example. The tests are presents but this itself gives no value. Moreover, I am afraid that some people may just add those tests - because it's an easy task - without running them. So I think your proposition is valid only when we have system test running on CI as suggested by @potiuk

**Comment by potiuk** [comment]
No  please don't close it stalebot :pray:

**Comment by mik-laj** [comment]
We are only missing system tests for only two services. Has anyone changed their mind now?  I think it's worth adding these tests so that we can easily track these defects. I have one ticket that contains a lot of information about the state of Google integration. Unfortunately, it is very difficult for me to track the status of system tests. 
https://github.com/apache/airflow/issues/8280
Reliable data on the state of integration makes it easier for me to plan and perform other tasks.  For example, now I started working on updating google-cloud- * libraries and I only had a few small libraries left and it looked like a very small task. Now, however, I have noticed that system tests are missing and therefore it is very difficult for me to verify the state of this integration and then update it as well.

**Comment by mik-laj** [comment]
Superseded by https://github.com/apache/airflow/pull/8390

**Comment by ad-m** [comment]
@mik-laj , what do you mean? Is issue superseeded by itself?

**Comment by mik-laj** [comment]
Wrong link. Here is correct: https://github.com/apache/airflow/pull/17165

**Comment by ad-m** [comment]
@mik-laj thank you for clarification. It makes a lot of sense now.

**Pull request closed without merging**
