### PR TITLE
[AIRFLOW-6076] fix dag.cli() KeyError

### PR DESCRIPTION
**Pull request by penggongkui**
fix this issue: https://issues.apache.org/jira/browse/AIRFLOW-6076

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add tests to avoid regression?  Besides, thanks a lot for fixing this bug. This is not the first time we've tried to fix this, but I hope we'll have success this time.

**Comment by penggongkui** [comment]
Ok，could you please help me pass the ci error , I don't know what to do to
fix it

**Comment by mik-laj** [comment]
CI is green, but it still needs tests.

**Comment by penggongkui** [comment]
I have added some test cases

> CI is green, but it still needs tests.

**Comment by penggongkui** [comment]
@mik-laj could you please review this PR

how about add this to the 2.0.2 milestone

**Review by ashb — APPROVED** [review]

**Pull request merged**
