### PR TITLE
[AIRFLOW-3458] Move connection tests

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3458
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Models.Connection was moved to `models/connection.py` in #4335, but the tests weren't moved. This PR moves the Connection tests accordingly to `tests/models/test_connection.py`.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Only moved tests, not added/removed.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
@BasPH Can you rebase onto master?

**Comment by Fokko** [comment]
Error looks unrelated:
```
[33m======================================================================[0m
[33m66) ERROR: test_get_or_create_not_exist (tests.models.test_kubernetes.TestKubeWorkerIdentifier)[0m
[33m----------------------------------------------------------------------[0m
[0m   Traceback (most recent call last):[0m
    [34m.tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py[0m line [1m[36m1297[0m[0m in [36mpatched[0m
      arg = patching.__enter__()
    [34m.tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py[0m line [1m[36m1353[0m[0m in [36m__enter__[0m
      self.target = self.getter()
    [34m.tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py[0m line [1m[36m1523[0m[0m in [36m<lambda>[0m
      getter = lambda: _importer(target)
    [34m.tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py[0m line [1m[36m1210[0m[0m in [36m_importer[0m
      thing = _dot_lookup(thing, comp, import_path)
    [34m.tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py[0m line [1m[36m1199[0m[0m in [36m_dot_lookup[0m
      __import__(import_path)
[33m   [33m[1m[33mImportError[0m[0m
```

**Comment by ashb** [comment]
Could you target this against the same jira that moved the code please?

**Comment by feng-tao** [comment]
+1 on @ashb , I prefer we don't have two jira / commits for the same model move.

**Comment by BasPH** [comment]
I closed the new Jira ticket and changed to the original one.

**Comment by BasPH** [comment]
Tests still failing 👎 Will dive into it tonight....

**Comment by BasPH** [comment]
Finally managed to find some time. One failing test has been removed in the meantime, now the CI is nice and green :)

**Review by Fokko — APPROVED** [review]
Awesome! Thanks @BasPH

**Pull request merged**
