### PR TITLE
[providers-fab/v1-5] Invalidate user session on password reset (#45139)

### PR DESCRIPTION
**Pull request by potiuk**
* session expire on pass change

* fix statis checks

* add tests (cherry picked from commit cf401c48bb6d06f1b30fef59d2a07afab22118bc)

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Hmm. Still something wrong :(

**Comment by potiuk** [comment]
All right ! Now all workflows seems to be triggering !

**Comment by potiuk** [comment]
cc: @shubhamraj-git

**Review by gopidesupavan — APPROVED** [review]
Do we need any change log update?

**Review by jscheffl — APPROVED** [review]

**Comment by potiuk** [comment]
> Do we need any change log update?

It will be generated automatically - following the usual release provider process.

**Comment by potiuk** [comment]
Ah... I need to backport the click changes too :)

**Comment by potiuk** [comment]
And some more :)

**Review by shubhamraj-git — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Comment by potiuk** [comment]
I had to backport few fixes since that branch was relased - so it was a "bit" more involved - but all of them applied cleanly

**Comment by potiuk** [comment]
Everything is green here, so cool. But I want to keep history of the commits, so I had to redo it from the "apache/airflow" repository and will merge it by pushing the `providers-fab/v1-5` branch once approved there.

https://github.com/apache/airflow/pull/45185

**Pull request closed without merging**
