### PR TITLE
Move comment to the right position

### PR DESCRIPTION
**Pull request by federicsp**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by kaxil** [comment]
@federicsp Can you explain why do you feel that is the wrong position?

**Comment by federicsp** [comment]
the jinja template definition ends in the row 112

**Comment by uranusjr** [comment]
I believe the marker is in the correct position, judging from how the content flows in the rendered documentation. You could argue the identifier used here (`jinja_template`) is not descriptive and should be changed.

**Comment by potiuk** [comment]
Closing the change - seems not justified.

**Pull request closed without merging**
