### PR TITLE
Fix compatibility for older airflow versions for tests

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I noticed the #40693. had accidentally broken compatiblity of testing providers with older versions of Airlfow - this one should fix it and I will think about some more selective check trigger to catch it in PRs (cc @Lee-W ) - becasue it was not.

**Review by shahar1 — APPROVED** [review]

**Comment by potiuk** [comment]
Yeah. The failing tests passed, merging

**Comment by Lee-W** [comment]
Thanks @potiuk for taking the time to fix this! I didn't notice this one. Is there anything specific I should be more careful about next time?

**Comment by potiuk** [comment]
In this case it was because:

a) no provider was touched
b) but shared test/utils/db were  (and they are using by provider tests as well)

So the quick fix is to remember about it, but i will also enhance a selective checks to trigger provider tests automatically if tests/utils is touched (because it can break anyway any provider tests - and it should be a rare event).

**Comment by potiuk** [comment]
@Lee-W : https://github.com/apache/airflow/pull/40965

**Comment by potiuk** [comment]
This should run the needed tests if any similar change happens in the future.

**Pull request merged**
