### PR TITLE
[AIRFLOW-5798] Set default to None for external_task_id in ExternalTaskSensor

### PR DESCRIPTION
**Pull request by vladimir-gavrilenko**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Pycharm highlighted my code when I used `ExternalTaskSensor` to wait for an entire DAG completion.

Two options here: use `str or None` or `Optional[str]`. I can switch to the second option if necessary.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No tests for docs

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Looking at the constructor definitions, this parameter is required.  Why do you think it's optional? Should we not also change the function definitions?
https://github.com/apache/airflow/blob/d719e1f/airflow/sensors/external_task_sensor.py#L65

**Comment by vladimir-gavrilenko** [comment]
@mik-laj , this parameter is required, but if you want to wait for the entire DAG completion, not only the specific task, you should explicitly set this parameter to `None`. Pls see this: https://github.com/apache/airflow/blob/d719e1f/airflow/sensors/external_task_sensor.py#L38-L39

But should we also change the function definition is a good question, actually :-)

**Comment by feluelle** [comment]
> But should we also change the function definition is a good question, actually :-)

That's really a (somehow) tough question.
I would personally say 
~~yes, because using `None`` as default is quite common.~~ 
~~no, because actually we want the user to define a task_id according to the class name.~~
yes. :D

**Review by feluelle — APPROVED** [review]

**Comment by feluelle** [comment]
@vladimir-gavrilenko I created a Jira ticket because it contains changes to code.

**Pull request merged**
