### PR TITLE
[AIRFLOW-2870] Use abstract TaskInstance for migration

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2870
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

If we use the full model for migration it can have columns
added that are not available yet in the database. Using
an abstraction ensures only the columns that are required
for data migration are present.
### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Db migration

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

@ashb @gwax PTAL

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by ashb — APPROVED** [review]
LGTM

**Comment by gwax** [comment]
Clever approach; thanks for taking this on @bolkedebruin 

On attempting `upgradedb`, I run into the following error with this branch:

```
  File "/Users/georgelesliewaksman/.pyenv/versions/2.7.15/envs/temp2/lib/python2.7/site-packages/airflow/migrations/versions/cc1e65623dc7_add_max_tries_column_to_task_instance.py", line 98, in upgrade
    ti.max_tries = ti.try_number
AttributeError: 'TaskInstance' object has no attribute 'try_number'
```

Looks like we also need the "try_number" column on the migration version of the model:

```
try_number = Column(Integer, default=0)
```

**Comment by bolkedebruin** [comment]
Ah let me fix that

**Comment by bolkedebruin** [comment]
@gwax done. PTAL

**Comment by gwax** [comment]
That works for me now.

:shipit: !

**Pull request merged**
