### PR TITLE
Remove unused dependency - contextdecorator

### PR DESCRIPTION
**Pull request by mik-laj**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by TobKed — APPROVED** [review]

**Review by ashb — COMMENTED** [review]
@potiuk You added this dep in #6054 -- any idea if it's still needed?

**Comment by mik-laj** [comment]
@ashb l This library never installs because we don't support Python older than 3.6.
```
$ echo 3.6 3.7 3.8 3.9 | xargs -n 1 -I {} curl -s 'https://raw.githubusercontent.com/apache/airflow/constraints-master/constraints-{}.txt' | sort | uniq | grep -i contextdecorator
$ echo $?
1
```

**Comment by potiuk** [comment]
I think my change #6504 was when i brought back coverage (and this line was added in accidentally - but as @mik-laj noticed, it was harmless).

**Review by potiuk — APPROVED** [review]

**Comment by ashb** [comment]
Just checking it wasn't some kind of "side-effect needed" but yeah, would only affect py2.7 anyway. Good point :)

**Pull request merged**
