### PR TITLE
Adding workload management params for Hive

### PR DESCRIPTION
**Pull request by Jparks2532**
Dear Airflow Maintainers,

Please accept the following PR that
- Addresses the following issues (links to issues addressed by this PR) :
  - Adding queue, queue_priority, and Hive job names as parameters to Hive Operator

Reminder to contributors:
- You must add an Apache License header to all new files
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by Jparks2532** [comment]
@mistercrunch:  Check out my awesome PR

**Comment by bolkedebruin** [comment]
Can you please squash your commits and use the guidelines for your commit message? Then I'll merge

**Comment by bolkedebruin** [comment]
ping @Jparks2532

**Comment by artwr** [comment]
@Jparks2532 Can you close this since it has been merged to master?

**Pull request closed without merging**
