### PR TITLE
Add kwargs-based task expansion metadata

### PR DESCRIPTION
**Pull request by uranusjr**
Alternative approach to add dict content metadata for `expand_kwargs(xcom_arg)`. First step toward https://github.com/apache/airflow/issues/24021.

-----

Copying https://github.com/apache/airflow/pull/24101#issuecomment-1149537574

When we do

```python
xcom_arg  # Say this is {"a": [1, 2], "b": [3, 4, 5], "c": [6, 7]}
foo.expand_kwargs(xcom_arg)
```

we can only expand the task to either 2 or 3 instances (depending whether we implement the `zip` or `zip_longest` semantic). We don’t actually need three additional entries storing the length of each value, but only need to record the zipped value is 2 (or 3—I think we should store both values). This means we only need to add two additional column on TaskMap (without changing the primary key), `zip=2` and `zig_longest=3`. Both values would be NULL if the content is not kwarg-expandable.

### CODE REVIEW

**Comment by Tehada** [comment]
What if we slightly change input format to avoid imitation of zip_longest?:
```
xcom_arg  # Say this is [{"a": 1, "b": 3, "c": 6}, {"a": 2, "b": 4, "c": 7}]
foo.expand_kwargs(xcom_arg)
```

**Comment by uranusjr** [comment]
I actually had a discussion with @dstandish on Slack yesterday and we came to the same format 😛 With this syntax (list-of-dicts), we might need to record the keys in each dict instead. I’m going to try _not_ doing that for now and see if the performance is acceptable.

**Comment by Tehada** [comment]
@uranusjr , is it in public channel? If so, I can follow discussions there too to be up-to-date.

**Comment by uranusjr** [comment]
We did it in a private chat unfortunately, we didn’t plan it. I’m trying to summarise things into a documentation PR so we don’t need to go through too many iterations in implementations though, so keep an eye on that. (I’ll try to remember to ping you!)

**Comment by dstandish** [comment]
yeah i agree the rowdict is by far the more natural structure and we should go with that, even if we also possibly support columnar style at some point.  but generally speaking that columnar style is a lot more awkward to work with.

**Pull request closed without merging**
