### PR TITLE
[AIRFLOW-6416] Sort default connection by conn_id

### PR DESCRIPTION
**Pull request by zhongjiajie**
* Remove unnecessary annotation provide_session
* Sort create_default_connections by connection id
* Add sort connection id unittest

- [x] Description above provides context of the change
- [x] Commit message contains [\[AIRFLOW-XXXX\]](https://issues.apache.org/jira/browse/AIRFLOW-6416) or `[AIRFLOW-6416]` for document-only changes
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Oh, we already add more probot to repo, Mergeable is good!

**Comment by potiuk** [comment]
@zhongjiajie why do you want to remove @provide_session ? The way it works now, it will create a new session for each connection - each merge_conn will have a new session (which basically means new connection established with the database). With @provide_sesion, the session will be reused whereas with the new approach it will be create/commit/close for every single Connection entry.

**Review by potiuk — COMMENTED** [review]
We should not remove @provide_session as it is there to make all the connections reuse session rather than recreate sessions.

**Comment by zhongjiajie** [comment]
And we could not remove @provide_session in function `merge_conn` due to some unittest use it to create temp connections, do we? @potiuk

**Comment by zhongjiajie** [comment]
> @zhongjiajie why do you want to remove @provide_session ? The way it works now, it will create a new session for each connection - each merge_conn will have a new session (which basically means new connection established with the database). With @provide_sesion, the session will be reused whereas with the new approach it will be create/commit/close for every single Connection entry.

I think we don't need to create connect in function `create_default_connections`, because it will be create in function `merge_conn`, so I remove it. but when you comment in 

> We should not remove @provide_session as it is there to make all the connections reuse session rather than recreate sessions.

I get that point

**Comment by potiuk** [comment]
> And we could not remove @provide_session in function `merge_conn` due to some unittest use it to create temp connections, do we? @potiuk

The  @provide_session decorator (and merge_conn uses it) follow exactly the pattern of session/transaction passing. It's there to handle the case that a session is created once, transaction starts, and you reuse the session do everything in the same DB transaction. So it is really needed :)

**Comment by kaxil** [comment]
Do we need this? The connections in the Airflow UI are already sorted.

**Comment by zhongjiajie** [comment]
I think it maybe more easy to maintain the code, what do you think? @kaxil

**Comment by kaxil** [comment]
> I think it maybe more easy to maintain the code, what do you think? @kaxil

I don't have a strong opinion against it as you might be right it might be good to have it in alphabetical order. WDYT @potiuk ?

**Comment by potiuk** [comment]
No strong opinion - but I think it only makes sense if we enforce it afterwards (like we did with a number of  other pre-commit checks). It's low priority I think.

**Comment by zhongjiajie** [comment]
So what should I do in this situation ? close this PR or do some else? @potiuk  @kaxil

**Review by potiuk — APPROVED** [review]
I like that you added test for it :)

**Comment by zhongjiajie** [comment]
Thanks Jarek and Kaxil for review

**Pull request merged**
