### PR TITLE
Add Retry Mechanism for Vault Connection Failures

### PR DESCRIPTION
**Pull request by pawalat**
This pull request introduces a retry mechanism to handle Vault connection failures more gracefully. By employing the urllib3.util.Retry class, we can configure the retry behavior for specific HTTP status codes that are more likely to be transient, such as 412 (Precondition Failed), 500 (Internal Server Error), 502 (Bad Gateway), and 503 (Service Unavailable).

These changes are implemented within the Vault client file, using the hvac library, to enhance the robustness and reliability of the connection with Vault. The hvac library's Client class allows for the injection of a custom Session object, which we can configure with an HTTPAdapter instance to apply our desired retry behavior.

As mentioned in the [hvac documentation](https://hvac.readthedocs.io/en/stable/advanced_usage.html#retrying-failed-requests), thoughtful retrying of failed requests is crucial for a seamless experience with Vault, especially in the context of eventual consistency. Vault may return a 412 status code when data is not yet available on the node where the request was made. In addition, retrying 5xx status codes is generally advisable.

With these changes, Airflow's integration with Vault becomes more resilient and fault-tolerant, improving the overall user experience and stability of the system.

### CODE REVIEW

**Comment by potiuk** [comment]
There are static check failures that needs to be fixed.

**Comment by notatallshaw-gts** [comment]
@pawalat Do you need any assistance fixing this PR or are you good?

We experienced an outage today and came to the same conclusion that HashiCorp Provider should retry the connection based on the HVAC documentation.

**Comment by notatallshaw-gts** [comment]
@potiuk I would like to get this change landed in Airflow as it caused a small outage for our team so we're going to patch it locally anyway.

What's the etiquette here on opening my own PR that does the same thing? Is there a minimum amount of time I should wait before considering this PR stale?

**Comment by potiuk** [comment]
> What's the etiquette here on opening my own PR that does the same thing? Is there a minimum amount of time I should wait before considering this PR stale?

Use your own judgement. We do not have procedures/ettiquete for everything. 

And it's ok to have things in parallell :) , there isi somehow a fear that having two parallell things is somewhat bad. It's not. You learn, you iterate, you can solve problems and the original author might take a look and make their own changes. Everyone learns. The code has already been effectively offered for the community to take.  

But generally the usual time  is 72Hrs if we expect the person to see it and have a chance to resoibd - which accounts for time zone/weekends and the like.

**Comment by notatallshaw-gts** [comment]
Alternative PR is here with passing tests and additional test: https://github.com/apache/airflow/pull/31073

I think this PR can be closed given there has been no activity?

**Comment by potiuk** [comment]
sure

**Pull request closed without merging**
