### PR TITLE
Update redis-statefulset.yaml to include apiVersion and kind: PersistentVolumeClaim

### PR DESCRIPTION
**Pull request by darth-drew**
include v1 and PersistentVolumeClaim in volumeClaimTemplate

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
https://github.com/kubernetes/kubernetes/pull/87706 fixed a bug in the config you are trying to add, and since 1.17, K8S adds them automatically, do you have any specific reason to add them manually?

I'm not against adding them, but I'm just curious why 🤔

**Comment by darth-drew** [comment]
I should have included Issue# in PR. Please see https://github.com/apache/airflow/issues/41766

**Comment by hussein-awala** [comment]
I see, and adding them makes sense.

I will close the other PRs, could you apply the changes in a single PR? (this one)

**Comment by darth-drew** [comment]
Can you make it work with this: https://github.com/apache/airflow/pull/41771

**Comment by hussein-awala** [comment]
closed in favor of https://github.com/apache/airflow/pull/41771

**Pull request closed without merging**
