### PR TITLE
Adding run_id column to log table

### LINKED ISSUE #37597: Add dag run_id to Audit Log
### Description

In event logs, we keep track of `dag_id` and `task_id` when relevant. But any task action is happening to a task instance but it is hard to tell which task instance it was. Sometimes, we use `execution_date` but it would be better for us to switch to `run_id`. 

### Use case/motivation

With a `run_id` field,
We could filter the audit log and see only events that happened in a single dag run.
We could link directly to the task instance in question. Right now we can only link to the general dag.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SamWheating**
closes: https://github.com/apache/airflow/issues/37597

This adds the `run_id` column to the log table (without a backfill, see [discussion](https://github.com/apache/airflow/issues/37597#issuecomment-1965244838)) and exposes it in all of the different surfaces:
 - the `/eventLogs` API
 - the logs view (`/logs/list`)
 - the inset / react audit logs DagRun details page
  - the legacy (non-react) audit logs view in the DAG details page
  
#### Screenshots:

Dag-scoped audit logs:
image

Dagrun-scoped audit logs:
image

#### Open questions:

 - Should we be pre-populating the run_id filter in the inset audit logs view (similar to what we do with task_id when a single task is selected)? This would be more precise than just filtering on task_id + dates, but it would exclude relevant events which aren't tagged with a run_id (for example, pausing a DAG mid-execution)

### CODE REVIEW

**Comment by bbovenzi** [comment]
I prepopulating works and then after this I will open up the before/after fields to be user-editable but with some default options like a dag run's entire durations. The before/after range also doesn't capture changing the state or a note.

After this and https://github.com/apache/airflow/pull/37734. We probably want to make sure we are populating run_id everywhere we can.

**Review by potiuk — APPROVED** [review]
LGTM . But would love another maintainer's review

**Comment by potiuk** [comment]
Just a watch-out - we have two migrations in-progress. I think we have a protection that will make the secon one not mergable if the first is but there will be some re-work needed once the other mighration is merged https://github.com/apache/airflow/pull/37708

**Comment by jedcunningham** [comment]
We actually have 3 in flight :sweat_smile:: #37734

**Comment by potiuk** [comment]
> We actually have 3 in flight 😅: #37734

😱 😱 😱 😱 😱 😱 😱 😱 😱

**Comment by SamWheating** [comment]
> Just a watch-out - we have two migrations in-progress

Thanks for the heads up - I'll keep a close 👀 on the other two and try to keep this PR in a mergeable state.

**Comment by bbovenzi** [comment]
> We actually have 3 in flight 😅: #37734

Since we have two migrations touching Log. Should we do both at once?

**Comment by SamWheating** [comment]
> Since we have two migrations touching Log. Should we do both at once?

This is a pretty good idea. Which PR do you want to merge first? If needed I can port the DB changes from the other PR into this one.

**Comment by bbovenzi** [comment]
> > Since we have two migrations touching Log. Should we do both at once?
> 
> This is a pretty good idea. Which PR do you want to merge first? If needed I can port the DB changes from the other PR into this one.

The other Audit Log one still has errors in the CI. So let's merge this first. The only change I had to make over there is to increase the max size of the `event` string.

**Comment by SamWheating** [comment]
Looks like the migration PR was merged, I'll get this one updated.

**Comment by bbovenzi** [comment]
> > > Since we have two migrations touching Log. Should we do both at once?

@jedcunningham @potiuk What do you prefer? Two separate event log table migrations, or combine them?

**Review by bbovenzi — APPROVED** [review]
lgtm. We'll merge the two migrations in the second PR

**Pull request merged**
