### PR TITLE
Revert "[AIRFLOW-3992] 1-setup-env.sh should be re-runable"

### PR DESCRIPTION
**Pull request by ashb**
Reverts apache/airflow#4817

This is dangerous - it a user happens to run this on their host it will overwrite files!

cc @milton0825 @feng-tao

### CODE REVIEW

**Comment by milton0825** [comment]
@ashb I was assuming that we only invoke the script inside the Docker container but seems like that is not the case. Should we enforce that users to only run the script inside the container?

or we can use `-i` instead of `-f`
```
Cause ln to write a prompt to standard error if the target file exists.  If the
           response from the standard input begins with the character `y' or `Y', then
           unlink the target file so that the link may occur.  Otherwise, do not attempt
           the link.
```

**Comment by feng-tao** [comment]
@ashb will user run this script in local box instead of docker / CI? I don't get why user will like to run this script locally.

**Comment by ashb** [comment]
We only expect it to run in docker/docker-on-CI but if users do attempt to run this locally trying to follow run the CI locally we shouldn't overwrite files.

(I've had a report of this happening, so it's not an "it might happen" but "it has happened")

Given we also add to the end of authorized_keys maybe the better change here is to only run this script in the docker-container (by checking an env variable that we set somewhere?)

**Comment by ashb** [comment]
Closing in favour of #5003

**Pull request closed without merging**
