### PR TITLE
KubernetesExecutor: Use user-provided namespace from executor_config arg

### LINKED ISSUE #22298: pod_override ignores namespace configuration
### Apache Airflow version

2.0.2

### What happened

I've attempted to use the pod_override as per the documentation [here](https://airflow.apache.org/docs/apache-airflow/2.0.2/executor/kubernetes.html#pod-override). Labels, annotations, and service accounts work. However, attempting to override the namespace does not: I would expect the pod to be created in the namespace that I've set `pod_override` to, but it does not. 

My speculation is that the `pod_generator.py` code is incorrect [here](https://github.com/apache/airflow/blob/2.0.2/airflow/kubernetes/pod_generator.py#L405). The order of reconciliation goes: 

```
        # Reconcile the pods starting with the first chronologically,
        # Pod from the pod_template_File -> Pod from executor_config arg -> Pod from the K8s executor
        pod_list = [base_worker_pod, pod_override_object, dynamic_pod]
```

Note that dynamic pod takes precedence. Note that `dynamic_pod` has the namespace from whatever namespace is [passed](https://github.com/apache/airflow/blob/2.0.2/airflow/kubernetes/pod_generator.py#L373) in. It is initialized from `self.kube_config.kube_namespace` [here](https://github.com/apache/airflow/blob/ac77c89018604a96ea4f5fba938f2fbd7c582793/airflow/executors/kubernetes_executor.py#L245). Therefore, the kube config's namespace takes precedence and will override the namespace of the `pod_override`, because only one namespace can exist (unlike labels and annotations, which can be additive). This unfortunately means pods created by the KubernetesExecutor will run in the config's namespace. For what it's worth, I set the namespace via an env var:

```
AIRFLOW__KUBERNETES__NAMESPACE = "foobar"
```

This code flow remains the same on the latest version of Airflow -- I speculate that the bug still might be in. 

### What you think should happen instead

If we use pod_override with a namespace, the namespace where the pod is run should take the namespace desired in pod_override.

### How to reproduce

Create a DAG using a PythonOperator or any other operator. Use the pod_override:

```
        "pod_override": k8s.V1Pod(
                            metadata=k8s.V1ObjectMeta(namespace="fakenamespace",
                                                      annotations={"test": "annotation"},
                                                      labels={'foo': 'barBAZ'}),
                            spec=k8s.V1PodSpec(
                                    containers=[
                                        k8s.V1Container(
                                            name="base"
                                        )
                                    ],
                                    service_account_name="foobar"
                            )
                        )
```

Look at the k8s spec file or use `kubectl` to verify where this pod is attempted to start running. It should be `fakenamespace`, but instead will likely be in the same namespace as whatever is set in the config file.

### Operating System

Amazon EKS 1.19

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other 3rd-party Helm chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by lostkamp**
closes: #22298 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vanchaxy** [comment]
Hi, I also encountered this bug. For now, I overcome it with pod_hook. 

From what I see, at the start of the construct_pod (line 339) we check for the image in pod_override_object and use it in kube_image.
This should be removed if we change the order of pods as you did in this PR or the namespace should be overwritten in a similar way.

I see the problem that after this PR users of airflow can overwrite some important annotations/labels which airflow use to operate and this will break executor work.

My suggestion is:
1) Remove image overwriting at the start of the function (try... except block)
2) Split dynamic_pod into 2 different pods.  One with namespace and kube_image. Another with annotations/labels/name/args/env.
3) Change pod_list order to pod_template_file -> pod with namespace and image ->  pod from executor_config -> pod from from dynamic arguments (annotations/labels/...).

After this change, we will have two dynamic pods: one with values that we allow users to overwrite and another with values that should not be overwritten by users.

**Comment by dstandish** [comment]
> I see the problem that after this PR users of airflow can overwrite some important annotations/labels which airflow use to operate and this will break executor work.

@vanchaxy can you clarify your concern, perhaps with an example?  This approach seems reasonable to me.

**Comment by vanchaxy** [comment]
> can you clarify your concern, perhaps with an example?

@dstandish after this change the task like this will never work:
```
@task(executor_config="pod_override": k8s.V1Pod(metadata=k8s.V1ObjectMeta(labels={"airflow-worker": "wrong-value"})))
def start_task():
    print()
```

It's now only about `airflow-worker`: specifying any label/annotation that is defined in the dynamic pod can break the executor (dag_id/task_id/try_number/run_id/map_index/kubernetes_executor/etc). Basically, we want to allow only overriding of namespace/image but the suggested approach allows us to override any value. My suggestion is to split `dynamic_pod` into optional (allowed to override) and required (denied to override):
```
optional_dynamic_pod = k8s.V1Pod(
    metadata=k8s.V1ObjectMeta(namespace=namespace),
    spec=k8s.V1PodSpec(containers=[k8s.V1Container(image=image)]),
)

required_dynamic_pod = k8s.V1Pod(
    metadata=k8s.V1ObjectMeta(
        annotations=annotations,
        name=PodGenerator.make_unique_pod_id(pod_id),
        labels=labels,
    ),
    spec=k8s.V1PodSpec(
        containers=[
            k8s.V1Container(
                name="base",
                args=args,
                env=[k8s.V1EnvVar(name="AIRFLOW_IS_K8S_EXECUTOR_POD", value="True")],
            ),
        ],
    ),
)

pod_list = [base_worker_pod, optional_dynamic_pod, pod_override_object, required_dynamic_pod]
```

Also, regardless of implementation, this part of the function should be removed as it's no longer needed. 
```
        try:
            image = pod_override_object.spec.containers[0].image  # type: ignore
            if not image:
                image = kube_image
        except Exception:
            image = kube_image
```

**Comment by dstandish** [comment]
OK thanks for that @vanchaxy 

So I see the issue is we want to protect users from overriding something with `pod_override` that would break k8s executor.  Looking this through, there's already some logic to respect the image from pod override if one is provided.  We could do the same with namespace. labels and annotations are already additive so maybe nothing necessary there.  why not just do the same for namespace that we are doing for image?  any concerns with that solution?

**Comment by vanchaxy** [comment]
@dstandish no concerns with that, I wrote about this in the first message:

> or the namespace should be overwritten in a similar way

For me personally, solution with two pods just looks prettier/easier to understand than try/except with `pod_override_object.spec.containers[0].image` and try/except `pod_override_object.metadata.namespace`. But both solution does exactly the same, so we can go with any.

**Comment by dstandish** [comment]
great let's see what @lostkamp has to say.  given that pretty much everything else in "dynamic_pod" needs to be there, or can be additively merged, i don't really see the need to construct two pods; we can just have these two special case carveouts, which to me seems the simpler approach. though i'm not super strongly opinionated either way.

**Comment by dstandish** [comment]
looks like you might've had a rebase mishap @lostkamp

**Comment by lostkamp** [comment]
> looks like you might've had a rebase mishap @lostkamp

huh.. i'm not sure what happened, but clicking on "fetch upstream" in this branch resolved it apparently.

**Review by malthe — APPROVED** [review]
I agree with @dstandish that this is an easy to understand solution which seems to do the trick just fine.

**Review by XD-DENG — COMMENTED** [review]
Was permission considered? Say if the scheduler pod would have the permission to launch pods in the namespace provided by user? If not, how will this be handled properly?

**Comment by lostkamp** [comment]
> Was permission considered? Say if the scheduler pod would have the permission to launch pods in the namespace provided by user? If not, how will this be handled properly?

I did not consider this, because I think it is the user's responsibility to set the correct permissions. Does Airflow do permission checks in case the namespace is not overridden?

**Comment by XD-DENG** [comment]
> > Was permission considered? Say if the scheduler pod would have the permission to launch pods in the namespace provided by user? If not, how will this be handled properly?
> 
> I did not consider this, because I think it is the user's responsibility to set the correct permissions. Does Airflow do permission checks in case the namespace is not overridden?

Agreed that it's the user's responsibility to set the correct permissions.

But if the user forgot to do that or has made any human error (say typo in namespace name, etc.), how will the error be handled in a way so that it's obvious/friendly to the users?

**Comment by lostkamp** [comment]
I don't know, I guess at the moment it won't? But this is a larger issue that also applies to the default configured namespace in airflow.cfg right? So isn't this rather a separate issue / PR?

**Review by dstandish — APPROVED** [review]
I'm good with this.  It changes behavior, but I think of it as a bug fix not breaking change.  cc @ashb @jedcunningham

**Review by jedcunningham — APPROVED** [review]
I agree, bugfix.

@XD-DENG, we shouldn't need to do anything special for permissions, as it's just another error from the k8s api.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Hello @lostkamp  - I needed to revert this one because it caused main failure on Kubernetes tests. Can you please re-opoen this one (re-apply it again on main so that:

a) we can see why it did not trigger the tests before (our tests might be a bit too selective and I want to get it fixed) 
b) you can fix the tests

Sorry for that but we needed to unblock other failing PRs

**Pull request merged**
