### PR TITLE
Change stdout and stderr access mode to append in commands

### PR DESCRIPTION
**Pull request by zo-zoyo**
Starting Airflow components using the `--stdout` and `--stderr` arguments redirects the output streams to a log file. Currently the access type for these log files is `w+`.

My problem with this access mode is that it can create sparse files. If the log file is moved or deleted, a new one will be created and the stdout/stderr will be written into it, but not from the start of the file. Instead if the original log file was x characters long, the new log file will contain x null bytes, and the new lines will be appended after that. To fix this problem we need to open the file with an access mode that has the `O_APPEND` flag enabled.

Short list of access modes and flags:

| fopen() mode | open() flags |
| --- | --- |
| w+ | O_RDWR \| O_CREAT \| O_TRUNC |
| w | O_WRONLY \| O_CREAT \| O_TRUNC |
| a | O_WRONLY \| O_CREAT \| O_APPEND |
| a+ | O_RDWR \| O_CREAT \| O_APPEND |

Based on this I propose changing the access mode for these output files from `w+` to `a`. I don't think there's any need to have read access so `+` can be dismissed.

The problem with this solution is that the `a` mode does not have the `O_TRUNC` flag enabled, which means that the output file is not truncated when a component is restarted. To preserve this behaviour we can manually truncate the files with `handler.truncate(0)`. We could also set the flags manually for the handlers but I don't think that it will make the solution more readable.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I really like this approach It makes a lot of sense. I would love others to comment on it but it gets quite a big +1 from me.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Some tests needs fixing (and rebase woudl be great).

**Comment by uranusjr** [comment]
What’s the issue preventing `w` from being used here?

**Comment by potiuk** [comment]
From the issue description:

> What’s the issue preventing `w` from being used here?

My problem with this access mode is that it can create sparse files. If the log file is moved or deleted, a new one will be created and the stdout/stderr will be written into it, but not from the start of the file. Instead if the original log file was x characters long, the new log file will contain x null bytes, and the new lines will be appended after that. To fix this problem we need to open the file with an access mode that has the `O_APPEND` flag enabled.

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
CAn you fix the test failure @THISisZOLI ?

**Comment by THISisZOLI** [comment]
Hey, sorry for not responding, I didn't have computer access for a few days. Will look into the failed tests soon.

**Comment by potiuk** [comment]
> Hey, sorry for not responding, I didn't have computer access for a few days. Will look into the failed tests soon.

No worries :). It's open source, you fix things when you can!

**Comment by uranusjr** [comment]
Just simple failures so I fixed them.

**Pull request merged**
