### PR TITLE
[AIRFLOW-6822] AWS hooks should cache boto3 client

### PR DESCRIPTION
**Pull request by baolsen**
---
Issue link: [AIRFLOW-6822](https://issues.apache.org/jira/browse/AIRFLOW-6822)

Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by feluelle — APPROVED** [review]

**Comment by ashb** [comment]
To duplicate my comments from the Jira issue. I feel we could do this nicer with a lot less duplication:

In AwsHook:
```
from cached_property import cached_property

    @cached_property
    def conn(self):
        return self.get_client_type(self.client_type)

    def get_conn(self):
        # Compat shim
        return self.conn
```

And then in each subclass we only need to define:

```
class S3Hook(AwsHook):
    client_type = "S3"
```

for instance.

**Comment by baolsen** [comment]
> To duplicate my comments from the Jira issue. I feel we could do this nicer with a lot less duplication:
> 
> In AwsHook:
> 
> ```
> from cached_property import cached_property
> 
>     @cached_property
>     def conn(self):
>         return self.get_client_type(self.client_type, region=self.region_name)
> 
>     def get_conn(self):
>         # Compat shim
>         return self.conn
> ```
> 
> And then in each subclass we only need to define:
> 
> ```
> class S3Hook(AwsHook):
>     client_type = "S3"
> ```
> 
> for instance.
> 
> The lambda hook would need a custom property as it takes an extra arg, but the others wouldn't.

Makes sense. I had some trouble caching the get_client_type method due to the parameters for region etc, but your approach looks like it avoids that issue by wrapping it nicely. Thanks

**Comment by baolsen** [comment]
Hey @ashb 

Can you advise me on something... Please check
providers/amazon/aws/sensors/s3_prefix.py

Within the poke method, the hook is being recreated each time. Is there a reason for this - maybe something to do with the new reschedule behavior? I'm not sure why it is written like that and not just do 'self.hook = X' in the __init__ method of the sensor.

There are a few of the AWS sensors with different implementations around this, I thought its a good idea to change them to be more consistent as well

**Comment by baolsen** [comment]
Closing this PR as I've created a new branch - changes diverged quite a bit from what I thought at first.
Will re-open when ready

**Pull request closed without merging**
