### PR TITLE
[AIRFLOW-387] Close SQLAlchemy sessions properly

### PR DESCRIPTION
**Pull request by StephanErb**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-387 (Dropped postgres connections)

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adopts the `provide_session` helper in almost the entire
codebase. This ensures session are handled and closed consistently.
In particular, this ensures we don't forget to close and thus leak
database connections.

As an additional change, the `provide_session` helper has been extended
to also rollback and close created connections under error conditions.

As an additional helper, this commit also introduces a contextmanager
that provides the same functionality as the `provide_session`
decorator. This is helpful in cases where the scope of a session should
be smaller than the entire method where it is being used.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This is a refactoring under existing test coverage. 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ashb** [comment]
Is this the cause of all the connection messages I see in my RDS postgres server log?

**Comment by StephanErb** [comment]
@ashb If you are talking about messages such as 
```
2016-08-02 14:49:26 UTC LOG:  could not receive data from client: Connection reset by peer
2016-08-02 14:49:26 UTC LOG:  unexpected EOF on client connection
``` 
then I believe so, yes.

**Comment by bolkedebruin** [comment]
@Nice! This does warrant a wiki update on how to properly do db handling in Airflow.

**Comment by NielsZeilemaker** [comment]
@ashb raising the default `sql_alchemy_pool_size` to 15 also seemed to help reduce the database load for us. The default pool size of 5 seems to be much to low for airflow, and causes a lot of connections to be opened/closed, which could have stayed in the pool to be reused.

**Comment by StephanErb** [comment]
@NielsZeilemaker  for us monitoring indicates that there is always a very low number "active" sessions, but a high number of ones "idle" and "idle in transaction". This PR will address the latter and might thus also allow you to reduce your pool size again.

screen shot 2017-11-01 at 14 44 31

**Comment by NielsZeilemaker** [comment]
@StephanErb thanks, our connection graph currently looks like this:
image so its a little higher than yours. Regardless, Its a very nice improvement

**Comment by bolkedebruin** [comment]
Can you rebase? Then I'll merge

**Comment by StephanErb** [comment]
@bolkedebruin done :)

**Comment by bolkedebruin** [comment]
Can you verify what goes wrong in the builds?

**Comment by StephanErb** [comment]
These are all travis / apt errors in the form:
```
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/libv/libverto/libverto-libevent1_0.2.4-1ubuntu2_amd64.deb  503  Service Unavailable [IP: 104.197.100.230 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
apt-get.diagnostics
apt-get install failed
```
@bolkedebruin could you hit rebuild on the travis UI? Unfortunately I am lacking the permissions for that.

**Comment by bolkedebruin** [comment]
Please do an empty commit. We cannot either

**Comment by bolkedebruin** [comment]
Well that is not entirely what I meant with empty, but ok :-)

**Pull request closed without merging**
