### PR TITLE
Revert "Simplify fab has access lookup (#19294)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 3e9828022b03b60d9e112f1f64340a528c8407e3.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @ashb @jhtimmins  -> as explained in #21407 reverting this one will fix the flakly docker-compose" tests most likely (and actually the flaky tests had shown that there is a real issue (as mentioned in #21407 )

**Comment by potiuk** [comment]
Seems like I got a repetitive success with that one so this is quite likely the culprit of the flaky tests I will re-run it with "public runners" now but I think we will need to revert it and re-do the "simplify"

**Review by ashb — APPROVED** [review]
Unblocking CI.

Do we know how to reliably trigger the bug so we can test it's fixed when we reintroduce this changeset?

**Comment by potiuk** [comment]
> Do we know how to reliably trigger the bug so we can test it's fixed when we reintroduce this changeset?

Actually .... this does not seem like it ... 

The last run when I was using `Public Runners` actually triggered it - so my hypothesis was wrong. 

https://github.com/apache/airflow/runs/5128289741?check_suite_focus=true#step:7:2081

````
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 553, in process_deletes
airflow-webserver_1  |     state, child, None, True, uowcommit, False
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 610, in _synchronize
airflow-webserver_1  |     sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
airflow-webserver_1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/sync.py", line 88, in clear
airflow-webserver_1  |     "column '%s' on instance '%s'" % (r, orm_util.state_str(dest))
airflow-webserver_1  | AssertionError: Dependency rule tried to blank-out primary key column 'ab_permission.id' on instance '<Action at 0x7ff72cb09310>'
```

We need to look more. But it seems that it's rather reliably triggered on Public runners.

**Comment by potiuk** [comment]
There were few other problems there as well.

**Pull request closed without merging**
