### PR TITLE
relax python-telegram-bot

### PR DESCRIPTION
**Pull request by RosterIn**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
python-telegram-bot is following semver, and 14.0 will likely be incompatible with 13.x. So maybe `~=13.0` would be better here.

**Review by uranusjr — APPROVED** [review]

**Comment by RosterIn** [comment]
I get failure on doc build but I didn't change any docs nor I changed anything related to `gcp.rst`?

```
############################## Start docs build errors summary ##############################

============================== apache-airflow-providers-google ==============================
------------------------------ Error   1 --------------------
 WARNING: Could not lex literal_block as "terraform". Highlighting skipped.

File path: apache-airflow-providers-google/connections/gcp.rst (178)

 173 | ``Service Account Token Creator`` role granted on account A, and account A has this role on account
 174 | B, then we are able to impersonate account B.
 175 | 
 176 | For example, with the following ``terraform`` setup...
 177 | 
>178 | .. code-block:: terraform
 179 | 
 180 |         terraform {
 181 |           required_version = "> 0.11.14"
 182 |         }
 183 |         provider "google" {}

############################## End docs build errors summary ##############################
```

**Comment by uranusjr** [comment]
No idea either, but I wouldn’t worry about it.

**Comment by RosterIn** [comment]
@potiuk can it be merged ?

**Comment by potiuk** [comment]
This is likely an error that was there at the time you branched off. Can you please rebase this on the latest master just to be sure ?

**Review by ashb — APPROVED** [review]

**Comment by uranusjr** [comment]
The doc rendering issue was fixed in #15710. It’d be awesome if you could merge or rebase to the master branch!

**Pull request closed without merging**
