### PR TITLE
[AIRFLOW-2602] Show failed attempts in Gantt view

### PR DESCRIPTION
**Pull request by seelmann**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2602

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
    - Get failed attempts from `task_fail` table and show them in Gantt view.
    - Fix TaskFail class column definition to match actual database schema. Change was required to retrieve all records for one task instance run otherwise only one was returned by SQLAlchemy.
    - See screenshot attached to the Jira

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jgao54** [comment]
@seelmann  not sure if I follow. dag_id + task_id + execution_date is the composite primary key for the table, therefore it is unique by the db constraint. There should not be more than 1.  (unless the schema for this table was changed at some point in the past)

**Comment by seelmann** [comment]
@jgao54 For the `task_instance` table dag_id+task_id+execution_date is the composite primary key, correct.

But for `task_fail` table it's different. In the DB the primary key is `id` with a DB sequence, see the [migration script](https://github.com/apache/incubator-airflow/blob/master/airflow/migrations/versions/64de9cddf6c9_add_task_fails_journal_table.py#L47) and the schema below. The table and the model class were introduced in #1712, there you can see that the model class and the migration script don't match. My guess is that the model class was copied form the TaskInstance class. (I just see another thing, the `duration` column is defined as float in the model class but as integer in the DB)

For each failed attempt a [row is added](https://github.com/apache/incubator-airflow/blob/master/airflow/models.py#L1721) to the `task_fail` table, which somehow already works with the existing code. Until now there is no code that retrieves data from `task_fail`. I just noticed the issue when I tried to retrieve all failed attempts for a task instance that I only received one but in the DB there were multiple, I guess sqlalchemy did some filtering based on the model definition.

If you prefer I can first create a separate Jira and PR to discuss and fix the DB schema and model class issue.


```
                                         Table "public.task_fail"
     Column     |           Type           | Collation | Nullable |                Default                
----------------+--------------------------+-----------+----------+---------------------------------------
 id             | integer                  |           | not null | nextval('task_fail_id_seq'::regclass)
 task_id        | character varying(250)   |           | not null | 
 dag_id         | character varying(250)   |           | not null | 
 execution_date | timestamp with time zone |           | not null | 
 start_date     | timestamp with time zone |           |          | 
 end_date       | timestamp with time zone |           |          | 
 duration       | integer                  |           |          | 
Indexes:
    "task_fail_pkey" PRIMARY KEY, btree (id)
```

**Comment by jgao54** [comment]
@seelmann  Ah, good catch and thanks for clarifying! I did not look into the table's schema and took the mapped class's column declaration at face value. So was a bit confused.

This PR lgtm actually! I've created [AIRFLOW-2604](https://issues.apache.org/jira/browse/AIRFLOW-2604) and [AIRFLOW-2606](https://issues.apache.org/jira/browse/AIRFLOW-2606) for next steps (help wanted :))

**Review by jgao54 — APPROVED** [review]

**Comment by seelmann** [comment]
@jgao54 I rebased this change to #3516. I moved the SQLAlchemy model changes there to avoid clutter.

**Pull request merged**
