### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by topedmaria**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Please revise your commit. The list is alphabetically ordered, and the item is not properly formatted, it is `+1. Tokopedia (www.tokopedia.com)`, but it should be `+1. [Tokopedia](https://www.tokopedia.com/) [@topedmaria](https://github.com/topedmaria)`.

**Comment by topedmaria** [comment]
@Fokko , already update the readme as suggested.
May I know who will do the merging?

**Comment by Fokko** [comment]
Hi @topedmaria, the list is ordered. Please revise and squash your commits.

**Comment by topedmaria** [comment]
Hi Foko, 

 

I am sorry, I don’t understand why I need to revise again?

 

I already revised at 19th Jan based on your suggestion:

 

+1. [Tokopedia](https://www.tokopedia.com/) [@topedmaria](https://github.com/topedmaria).

 

I have checked the current readme, it still the same with the one that I committed before.

 

Thanks, 

Maria

**Comment by r39132** [comment]
@topedmaria After you fix your commit so that alphanumeric ordering of company names is maintained and after you squash your commits into a single one, then you will need to do a "git push --force origin master" where origin is your fork. Then, the PR will automatically update to show the single commit and the updated readme. You don't need to close/reopen the PR. Just push the newly squashed commit to origin.

**Comment by r39132** [comment]
@topedmaria if you look at the your commits in the PR, you will notice that none of them are from Jan 19. Remember, when you squash, not to "git pul"l again, since your squashed commit will get dropped. You need to squash and git force push.

**Comment by r39132** [comment]
I'm closing this as there has been no movement from the submitter.

**Pull request closed without merging**
