### PR TITLE
Bump min-version for docker and docker-compose

### PR DESCRIPTION
**Pull request by potiuk**
It's been quite some time since we bumped min versions for docker and docker-compose for Breeze and there are already a few cases where it held us back from more efficiently using some newer docker or docker-compose features (for example in #33547). Also docker-compose v1 is sufficiently old an unmaintained, that it's about time to get rid of it and ask the users to migrate to docker-compose v2.

The new min versions propose:

* Docker: 23.0.0 released 2023-02-01 (6 months ago)
* Docker Compose 2.14.0 release 2022-12-15 (8 months ago)

Docker v1 is not supported any more and the users are directed to migrate to v2 to continue using Breeze.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
I’m fine with this even just for `docker compose`. Docker is auto-updating anyway so it’s not unreasonable for most people to already on the latest version (much newer than these requirements) anyway.

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
OK. Seems that our CI's docker is too old :)

**Comment by potiuk** [comment]
But it looks like the version check works nicely BTW :)

**Comment by potiuk** [comment]
Ok. We should have now docker and docker compose updated for our self-hosted runners. Let's see.

**Comment by potiuk** [comment]
So far so good:

image

I set-up the "min-versions" in CI that correspond to the min-versions we have in Breeze - this way we will see in CI if we introduce something not supported by those in most cases (since we are running almost all our breeze commands as part of the CI jobs of ours).

**Comment by potiuk** [comment]
Looks great. Trying on public runners, just in case.

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
