### PR TITLE
Add statsd overrideMappings in helm chart values

### PR DESCRIPTION
**Pull request by BobDu**
I think, it will a part of the  PR #25219 .
Let's do some easier part first and roll it out to users.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Tests?

**Comment by BobDu** [comment]
> Tests?

Sorry, fix all test failing already.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
BTW. Seems like we can get rid of one of our images. And RedHat/Quay.io by RedHat looks credible enough for me.

**Comment by BobDu** [comment]
> BTW. Seems like we can get rid of one of our images. And RedHat/Quay.io by RedHat looks credible enough for me.

Of course, look this, repository `quay.io/prometheus` is maintain by prometheus official community.

https://prometheus.io/docs/prometheus/latest/installation/#using-docker

In addition, I have to say that the reason why I don't use the docker hub as much as possible.
https://www.docker.com/increase-rate-limits/

**Comment by potiuk** [comment]
> In addition, I have to say that the reason why I don't use the docker hub as much as possible.
https://www.docker.com/increase-rate-limits/

Yeah, I am well aware of that. Just FYI - all ASF images (those under apache/* ) are exempt from the limit  - this is one of the reasons we have our own customized image in the "apache/*" part of the registry.

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
