### PR TITLE
fix: rename directory for Windows users

### PR DESCRIPTION
**Pull request by Inetov**
it's just renaming the log directory for Windows users can clone your repository.
Windows not allow ":" in file/directory name.

### CODE REVIEW

**Comment by potiuk** [comment]
You will have to also fix some tests most likely

**Comment by Inetov** [comment]
> You will have to also fix some tests most likely

I did not find in the code where this name / path to the file would be used

**Comment by Taragolis** [comment]
> I did not find in the code where this name / path to the file would be used
https://github.com/apache/airflow/blob/main/tests/www/views/test_views_log.py

I don't think that is possible to change directory/filename seems like it test default log format.
However tests might create this files in temp directory.

Or windows users might run `git config core.protectNTFS false` before clone repo.

**Comment by uranusjr** [comment]
It could possible to override this in tests with `conf_var` or something. But either way the “fix” would be more involved than just renaming.

**Comment by Inetov** [comment]
> I don't think that is possible to change directory/filename seems like it test default log format. However tests might create this files in temp directory.
> 
> Or windows users might run `git config core.protectNTFS false` before clone repo or better clone inside WSL 2

OK, thanks! this is harder than it seemed, I don't have time to finish it yet

**Comment by potiuk** [comment]
Closing for now then

**Pull request closed without merging**
