### PR TITLE
CI: Introduce cross-provider backwards-compatiblity tests.

### PR DESCRIPTION
**Pull request by JDarDagran**
There is no mechanism forcing user to upgrade downstream dependent provider package when upgrading other providers. For each downstream dependent provider it is being downgraded to latest released version and tested against latest related providers.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by JDarDagran** [comment]
@potiuk seems like the general idea works. However, the fully automated way runs heavy tests for google/amazon multiple times. I wonder if there's a way to mark cross-provider tests somehow but at the moment it seems improbable.

**Comment by JDarDagran** [comment]
Also: I'm not sure how to deal with running all providers and airflow core from HEAD but selected providers to be installed and used from downloaded released package. So far I've been preparing all packages to wheels and installing all needed packages per test.

**Comment by potiuk** [comment]
> @potiuk seems like the general idea works. However, the fully automated way runs heavy tests for google/amazon multiple times. I wonder if there's a way to mark cross-provider tests somehow but at the moment it seems improbable.

I think we should only run the tests for the "upstream" provider. I.e. run only the upstream provider tests when older versions of downstram providers are installed. This will make the tests much smaller and it will avoid running long tests for amazon/google multiple times. For example I'd just downgrade all downstream providers for Google and run tests for Google provider only once. We do not care which provider is problematic in this case so we can downgrade all of them and check all of them at once.

> Also: I'm not sure how to deal with running all providers and airflow core from HEAD but selected providers to be installed and used from downloaded released package. So far I've been preparing all packages to wheels and installing all needed packages per test.

This is easy. We just need to figure which version of the providers to install, prepare all of them from head, remove the ones we want to replace and run:

```
pip download --no-deps apache-airflow-providers-xxxx==x.y.z apache-airflow-providers-nnnn==x.y.z --dest ./dist
```

**Comment by JDarDagran** [comment]
> I think we should only run the tests for the "upstream" provider. I.e. run only the upstream provider tests when older versions of downstram providers are installed. This will make the tests much smaller and it will avoid running long tests for amazon/google multiple times. For example I'd just downgrade all downstream providers for Google and run tests for Google provider only once. We do not care which provider is problematic in this case so we can downgrade all of them and check all of them at once.

That was my thinking too once I saw how long tests take. Will do the switch.

> This is easy. We just need to figure which version of the providers to install, prepare all of them from head, remove the ones we want to replace and run:
```pip download --no-deps apache-airflow-providers-xxxx==x.y.z apache-airflow-providers-nnnn==x.y.z --dest ./dist```

As this is ran in parallel - doesn't each parallel breeze instance use the same `./dist`? At the moment this is what I'm doing in the entrypoint script (with `--mount tests` and Airflow installed from prepared wheel):
```
uv pip uninstall --python "$(which python)" "apache-airflow-providers-${provider//./-}"
uv pip install --python "$(which python)" --constraint https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-source-providers-${PYTHON_MAJOR_MINOR_VERSION}.txt "apache-airflow-providers-${provider//./-}"
```
constraints are kind of blind shot but they worked.

**Comment by potiuk** [comment]
> As this is ran in parallel - doesn't each parallel breeze instance use the same ./dist? At the moment this is what I'm doing in the entrypoint script (with --mount tests and Airflow installed from prepared wheel)

Yes. We would have to run the tests sequentially to make it works

**Comment by JDarDagran** [comment]
> > As this is ran in parallel - doesn't each parallel breeze instance use the same ./dist? At the moment this is what I'm doing in the entrypoint script (with --mount tests and Airflow installed from prepared wheel)
> 
> Yes. We would have to run the tests sequentially to make it works (no `--run-in-parallel` and likely copying/moving providers once before.

Then how's that better than my current approach? Additionally, one would need to take care of managing installed/uninstalled/downloaded/removed providers in the sequence. Seems too complicated.

**Comment by potiuk** [comment]
Another option: we could actually pass a list of providers/versions to inside the container and let `entrypoint_ci.sh`  to reinstall the providers - then we could prepare all the providers from HEAD and each container run would:

* install all providers from dist
* reinstall those providers that we pass in each parallel run 

The second step should be as easy as `pip install --upgrade apache-airflow==${AIRFLOW_VERSION} apache-airflow-providers-aaaaa==x.y.z apache-airflow-providers==x.y.z`

**Comment by JDarDagran** [comment]
> Another option: we could actually pass a list of providers/versions to inside the container and let `entrypoint_ci.sh` to reinstall the providers - then we could prepare all the providers from HEAD and each container run would:
> 
> * install all providers from dist
> * reinstall those providers that we pass in each parallel run
> 
> The second step should be as easy as `pip install --upgrade apache-airflow==${AIRFLOW_VERSION} apache-airflow-providers-aaaaa==x.y.z apache-airflow-providers-bbbb==x.y.z`

Yep, reinstall over uninstall->install from PyPI looks good. What about constraints? Should I care at all?

**Comment by potiuk** [comment]
> Yep, reinstall over uninstall->install from PyPI looks good. What about constraints? Should I care at all?

Nope. you wil find a number of conflicts when you try to install older version of providers with newer constraints, so it's better to run without them. That is anyhow how users should install airflow:

a) install "golden" set of dependencies with constraint
b) download providers and other dependencies without the constraints.

Actually the whole exercise of figuring out the lowest dependencies is precisaly about point b) to be more reliable. If we know that Airflow works with "golden" dependencies and if airflow providers have a proper set of lower bindings, then it means that such downgrade in point b) should not lead to a problem because lower bindings will prevent "too far" downgrading.

**Pull request closed without merging**
