### PR TITLE
[AIRFLOW-3668] 'Zoom into sub DAG' button fix

### PR DESCRIPTION
**Pull request by Jaskon**
'Zoom into sub DAG' button had not shown on the graph.html page in subdag details dialog window

### CODE REVIEW

**Comment by ron819** [comment]
Can you also apply the fix to https://github.com/apache/airflow/blob/master/airflow/www_rbac/templates/airflow/graph.html#L161
?

**Comment by Jaskon** [comment]
Of course

**Comment by OmerJog** [comment]
@Jaskon can you rebase?
Due to merge of https://github.com/apache/airflow/pull/4339 the `airflow/www` was deprecated and the `airflow/www_rbac` was renamed as `airflow/www`

**Comment by ashb** [comment]
We probably want this fix as it is against v1-10-stable branch to fix this for 1.10.4.

**Comment by ashb** [comment]
Not needed anymore. 1.10.4 the code looks like:

```js

        if (d in task_instances)
            try_number = task_instances[d].try_number;
        else
            try_number = 0;
        if (task.task_type == "SubDagOperator")
            call_modal(d, execution_date, try_number, true);
        else
            call_modal(d, execution_date, try_number);
```

**Pull request closed without merging**
