### PR TITLE
[AIRFLOW-6247] Fix sort order in Alembic Migration template

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-6247

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
The current template (`script.py.mako`) for the migration script would fail the isort check. This PR fixes it.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Current static check (isort) checks the generated file.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by ashb** [comment]
How about we set up https://alembic.sqlalchemy.org/en/latest/autogenerate.html?highlight=mako#applying-post-processing-and-python-code-formatters-to-generated-revisions to pass it through black since we're moving to black as a project anyway?

Or black +and https://pypi.org/project/zimports/ as it sounds like black won't do import order?

**Comment by mik-laj** [comment]
@ashb we use isort for sort import order.

**Comment by ashb** [comment]
I think something like this might work then:

```
[post_write_hooks]
hooks=isort

isort.type=console_scripts
isort.entrypoint=isort
```

We'll need to update to alembic 1.2 but that's no bad thing.

**Comment by kaxil** [comment]
> I think something like this might work then:
> 
> ```
> [post_write_hooks]
> hooks=isort
> 
> isort.type=console_scripts
> isort.entrypoint=isort
> ```
> 
> We'll need to update to alembic 1.2 but that's no bad thing.

Done and manually tested it. Works fine.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
👍

**Pull request merged**
