### PR TITLE
Decouple volume_configurations from capacity_provider_strategy

### LINKED ISSUE #43046: Unnecessary dependence between capacity_provider_strategy and volume_configurations
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

apache-airflow-providers-amazon==8.29.0

### Apache Airflow version

2.9.2

### Operating System

Amazon Linux 2023.5.20240805

### Deployment

Amazon (AWS) MWAA

### Deployment details

Using a Python 3.11 environment with `botocore==1.34.106` and `apache-airflow-providers-amazon==8.29.0`.

This allows us to use the `volume_configurations` feature so we can deploy DAGs that use the `ECSRunTaskOperator` with EBS volume attachments configured at launch.

### What happened

Omitting `capacity_provider_strategy` from `EcsRunTaskOperator` prevents `volume_configurations` from being passed to `self.client.run_task(**run_opts)` in `EcsRunTaskOperator._start_task()`.

So, if you aren't using `capacity_provider_strategy` (in this case we are using `launch_type="FARGATE"`) this prevents an EBS volume configuration from being defined which throws the following error during DAG execution:

```python
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 543, in execute
    self._start_task()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 643, in _start_task
    response = self.client.run_task(**run_opts)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: The volume name '<volume_name>' in your request does not have a matching volume in your Task Definition that is configurable at launch.
```

### What you think should happen instead

`EcsRunTaskOperator.volume_configurations` should be passed to `self.client.run_task(**run_opts)` regardless of the value of `capacity_provider_strategy`.

### How to reproduce

1. Create an ECS task definition that includes `volume` and `mountPoint` definitions for an EBS volume.
2. Run a task using `ECSRunTaskOperator` with `volume_configurations` containing a `managedEBSVolume` defined and `capacity_provider_strategy` undefined.
3. Try to run the corresponding DAG with an EBS volume attached.

### Anything else

- Directly calling [ECS.Client.run_task](https://boto3.amazonaws.com/v1/documentation/api/1.34.106/reference/services/ecs/client/run_task.html) with the boto3 API with the same configuration passed to `EcsRunTaskOperator` (with camelCase keywords) works.
- Replacing ecs.py in my deployment with the code in #43047 fixes the issue and allows us to run these tasks.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pyrr**
closes: #43046 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by romsharon98 — APPROVED** [review]

**Comment by eladkal** [comment]
@pyrr can you rebase and resolve conflicts?
Also please add unit test to avoid regression

**Comment by pyrr** [comment]
@eladkal done.

**Review by romsharon98 — APPROVED** [review]

**Comment by romsharon98** [comment]
> @eladkal done.

Static checks need to be fixed

**Comment by pyrr** [comment]
> Static checks need to be fixed

@romsharon98 Fixed extra parameter issue-- should work now but I'm not sure how to run the unit tests on my end without waiting for you to trigger the workflow.

**Comment by romsharon98** [comment]
> > Static checks need to be fixed
> 
> @romsharon98 Fixed extra parameter issue-- should work now but I'm not sure how to run the unit tests on my end without waiting for you to trigger the workflow.

You can read more about how to run tests locally [here](https://github.com/apache/airflow/blob/main/contributing-docs/testing/unit_tests.rst#airflow-unit-tests)

**Comment by pyrr** [comment]
> > > Static checks need to be fixed
> > 
> > 
> > @romsharon98 Fixed extra parameter issue-- should work now but I'm not sure how to run the unit tests on my end without waiting for you to trigger the workflow.
> 
> You can read more about how to run tests locally [here](https://github.com/apache/airflow/blob/main/contributing-docs/testing/unit_tests.rst#airflow-unit-tests)

Thanks, will fix new error and QA tests on my side this time before requesting review.

**Comment by pyrr** [comment]
@romsharon98 

Tested locally + squashed the bug fix commits into one, good to retry workflow.

**Review by o-nikolas — APPROVED** [review]

**Comment by pyrr** [comment]
@o-nikolas 

Thanks for re-running the workflow, I see the tests are still failing. Not sure why since it works when I run the suite using breeze on my machine. Will investigate again.

**Comment by eladkal** [comment]
> @o-nikolas
> 
> Thanks for re-running the workflow, I see the tests are still failing. Not sure why since it works when I run the suite using breeze on my machine. Will investigate again.

It fails on static checks. You just need to install and enable pre commit. It will automaticly fix it

**Comment by pyrr** [comment]
Thanks @eladkal , I applied the pre-commit changes and fixed an additional issue with the expected_args.

Also @potiuk @ashb apologies for the code review request-- I committed another file I had modified locally for local testing.

**Pull request merged**
