### PR TITLE
[AIRFLOW-4478] Lazily instantiate default `Resources` object

### PR DESCRIPTION
**Pull request by jmcarp**
Instantiating `Resources` and its child classes takes non-negligible
time when users create many operators. To save time, create a shared
default `Resources` instance and use it unless a task specifies custom
resources.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
Are we sure self.resources are immutable ? I took a quick look and I am not 100% sure as they are used somewhere deep in kubernetes executor. I am a little concerned, that even if it's immutable now, maybe someone can try to mutate it later (for example if we do auto-scaling or down-scaling or smth like that). Maybe we could use frozendict instead (or similar) - this way we might prevent this scenario.

**Comment by jmcarp** [comment]
Thanks @potiuk. I reimplemented both `Resource` and `Resources` as `namedtuple`s both to clean up the code and to make sure both are immutable. I also see that the gpu and disk limits are undocumented and not referred to elsewhere in the code, so I propose that we drop them--I don't even think cgroups support limits on disk space or gpu shares, and they definitely aren't supported in cgroupspy. Last, it looks like the kubernetes system implements its own independent `Resources` class at https://github.com/apache/airflow/blob/master/airflow/kubernetes/pod.py#L19-L38 and doesn't overlap with these classes.

**Comment by jmcarp** [comment]
On second thought, I updated this to create `Resources` instances with default parameters lazily in `CgroupTaskRunner` instead of reimplementing the resource class hierarchy. This makes the diff smaller and pushes the change into the task runner, which the only part of the code that cares about this attribute. Ready for another look @potiuk.

**Comment by potiuk** [comment]
looks good now, but the JIRA Id is wrong.

**Comment by jmcarp** [comment]
Thanks, updated the ticket id.

**Comment by jmcarp** [comment]
Anything else I should update @potiuk?

**Comment by ashb** [comment]
Do we need to worry about someone mutating this object by mistake and affecting all other tasks?

I _think_ it would be limited to the one DAG due the the sub-process parsing mechanism. Sound right?

**Comment by jmcarp** [comment]
@ashb: I believe we still create a separate `Resources` instance for each task/runner under this patch. If `resources` is passed to the operator constructor, we instantiate a separate `Resources` in the constructor. If not, the `CgroupTaskRunner` lazily instantiates a default `Resources` at runtime. So I don't think there are any shared `Resources` instances that could affect multiple tasks.

**Comment by jmcarp** [comment]
Ping @ashb when you have time for another look.

**Comment by pedromachados** [comment]
@jmcarp It looks like the resources argument got changed from dict to array or was that an oversight?
 
https://github.com/apache/airflow/blob/c1bb60f542054a6dd6bc7332712020fc375ef140/airflow/models/baseoperator.py#L377

The documentation still states that it expects a dict: https://github.com/apache/airflow/blob/526c65a57204022596fb69e9478c5515ad0b880e/airflow/models/baseoperator.py#L191

**Comment by ashb** [comment]
@pedromachados Oversight :( (Not many people use resources so this wasn't noticed in our RC testing).

Could you create a Jira for this, and if possible open a PR with a fix a test that catches this?

**Pull request merged**
