### PR TITLE
Use sys.version_info to get the python version

### PR DESCRIPTION
**Pull request by joankaradimov**
I have a customized image that uses `continuumio/miniconda3:4.12.0` as its `PYTHON_BASE_IMAGE`. The `python --version` in the said Conda distribution outputs:
```
Python 3.9.18 | packaged by conda-forge | (9c4f8ef1, Jan 30 2024, 18:27:40)
[PyPy 7.3.15 with GCC 12.3.0]
```

In the `Dockerfile` this is piped to `cut -d " " -f 2 | cut -d "." -f 1-2`. The result is this:
```
3.9
7.3
```

As a result the `AIRFLOW_CONSTRAINTS_LOCATION` becomes:
```
https://raw.githubusercontent.com/apache/airflow/constraints-2.5.3/constraints-3.9%0A7.3.txt
```
(The `%0A` is a URL-encoded new line)

The python version is retrieved in 3 places in the `Dockerfile`. One uses `sys.version_info`, two use `python --version` with pipe/cut. I suggest for `sys.version_info` to be used consistently in all 3 places, as it gives a more predictable result.

### CODE REVIEW

**Comment by potiuk** [comment]
While the change is good, his is wrong place where to update it. The dockerfile scripts are inlined automatically by pre-commit from `scripts/docker/*.sh` - and you should modify them there, then (after installing pre-commit) they will be automatically inlined to the Dockerfiles by the pre-commit.

**Comment by joankaradimov** [comment]
> https://github.com/apache/airflow/blob/main/scripts/docker/common.sh#L102 -> this is where it should be modified.

And also in `scripts/docker/entrypoint_prod.sh`.

I suppose I should run the pre-commit hooks locally too?

**Comment by Taragolis** [comment]
> I suppose I should run the pre-commit hooks locally too?

Yep

**Comment by potiuk** [comment]
> I suppose I should run the pre-commit hooks locally too? 

This is what pre-commit is for (`pre-` + `commit`). You should run `pre-commit install` and since then it will be run automatically for you whenever you make commit - this is the way you do not have to send PR to CI to find out if your PR passess the first gate of static checks

**Review by uranusjr — APPROVED** [review]

**Comment by uranusjr** [comment]
IF you really really really want to avoid installing things locally, you could just apply the changes suggested by the CI manually yourself.

**Comment by Taragolis** [comment]
I run hook locally and push changes into the branch: https://github.com/apache/airflow/pull/37750/commits/c0d2041aa663ecd169cc999b1e19e6a147ee6931

**Review by Taragolis — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
