### PR TITLE
[AIRFLOW-3010] added support for date format to postgres_to_gcs_operator

### PR DESCRIPTION
**Pull request by rlkelly**
Make sure you have checked _all_ steps below.

### Jira

- [X ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3010\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3010
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-3010\], code changes always need a Jira issue.

### Description

- [ X ] Here are some details about my PR, including screenshots of any UI changes:

   I just changed it so the Date datatype would be acknowledged in write and read.

### Tests

- [ X ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Currently the schema functionality is largely untested and this would be a larger undertaking if we wanted to create better testing for serialization.

### Commits

- [ X ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ X ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @dgingrich for the PR. Do you think it is possible to test this?

Recently we've moved to Docker for the testing. Therefore we have a Postgres instance available in a linked container.

**Comment by dgingrich** [comment]
@Fokko I didn't submit the PR or the bug, I think you want @rlkelly

**Comment by rlkelly** [comment]
I could improve the test coverage on this if this is something you'd be interested in using

**Comment by SamWildmo** [comment]
I could use this. Any chance this will be in 1.10.1?

**Comment by Fokko** [comment]
Could add a test by adding a `DATE` field? https://github.com/apache/incubator-airflow/blob/master/tests/contrib/operators/test_postgres_to_gcs_operator.py#L47-L54

**Comment by SamWildmo** [comment]
@rlkelly will you add the test?

**Comment by OmerJog** [comment]
@rlkelly any chance to revisit this? I use this fix manually by having a custom operator. I would be nice if this can be in the official airflow release

**Comment by Fokko** [comment]
@OmerJog You can also cherry-pick @rlkelly's work and continue with that.

**Pull request closed without merging**
