### PR TITLE
[AIRFLOW-4162] Support layout blocks in Slack operators

### PR DESCRIPTION
**Pull request by bskim45**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-4162

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adds support for Slack layout blocks in Slack operators: `SlackAPIPostOperator`, `SlackWebhookOperator`
https://api.slack.com/reference/block-kit/blocks

This PR also compatible with slack python sdk v1 which we are using, since slack SDK simply passes kwargs dict to the api client as a payload.
 
### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Updated corresponding operator tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by feluelle** [comment]
Hey @bskim45, I am sorry, but would it be okay for you if we close this PR and add you as an co-author to #6418 ? It does basically the same and we already started to review the other one. :/

cc @mingrammer

**Comment by bskim45** [comment]
No problem @feluelle. I will close this PR.

**Comment by feluelle** [comment]
I know, your PR was opened first.. :/

**Comment by mingrammer** [comment]
@bskim45 I'm sorry.. I didn't check there is already a PR for this issue.

**Pull request closed without merging**
