### PR TITLE
Tests are cancelled if any of faster checks fail

### PR DESCRIPTION
**Pull request by potiuk**
Wheneve the fast checks fail we cancel the whole workflow.
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
this one should significantly speed up our CI builds:

1) We are starting all the tests immediately now
2) But if any of the "fast" checks fails, we cancel the whole workflow

I think that strikes the right balance between the time to wait for CI results (tests do not have to wait for static checks or docs to trigger) and the heavy workload we have because we have repeated tests where only one or two static checks fail (people still do not use pre-commits as often as I would like them to).

This was suggested in last week discussion by @dimberman for static checks but only now I realised that and found out that it is rather easy (and added it for all other checks).

I think that will significantly decrease the load on CI - especially that with the number of jobs we have now even if someone realizes quickly that some static check fails and pushes a fixup, the "cancel" Job from the subsequent run might not even start running as it will be blocked by the jobs in the queue.

**Review by kaxil — COMMENTED** [review]
Does this mean, if there are docs failure and static check failure in CI, it will cancel the workflow as soon as one of them fails? 

That would mean a user fixes that issue and the CI runs again and now fails on static checks?

**Comment by potiuk** [comment]
> Does this mean, if there are docs failure and static check failure in CI, it will cancel the workflow as soon as one of them fails?
> 
> That would mean a user fixes that issue and the CI runs again and now fails on static checks?

No. No. The static checks job will run till completion - i.e. it will verify all static checks. But if any of them (or more than one) fails, it will cancel immediately all "Tests" for that workflow (the long-running ones)

**Review by kaxil — APPROVED** [review]
aah nice

**Comment by potiuk** [comment]
I re-read what you wrote @kaxil (about doc/static). I thought you were talking about two static checks failing but yeah docs/static might cancel each other (and since doc is faster, it will fail static checks always). hmm. That's an interesting one how to solve it. I can remove it from docs. Let me think a bit about it. Going tor a walk now :)

**Comment by potiuk** [comment]
I thought about it and I think it's good. the docs failing after 9 minutes will save a lot of times for others even if static checks also fail later. This is a small price to pay for savings in waiting for others to just re-reun it once after tests fail :).

**Pull request merged**
