### PR TITLE
[AIRFLOW-6539][AIP-21] Move Apache classes to providers.apache package

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

I know that this is a very large PR, but unfortunately, it is not possible to divide it, because these classes are very close together on the lists in `test_core_to_contrib.py` file, documentation and others. 

If we don't do it in bulk, we will constantly fight merge conflicts and AIP-21 will not be finalized in the next six months (100+ integration * 1.5 day =150 days, 150 days / (5 / 7) [exclusion of weekends] = 210 days,  210 days = 6.89 month = 0.57 year). 

In fact, it would probably be a shorter time, but it is still very hard work for one person. That would also be problematic for other people because Travis would be busy.

Best regards,
Kamil

---

Issue link: [AIRFLOW-6539](https://issues.apache.org/jira/browse/AIRFLOW-6539/)

- [X] Description above provides context of the change
- [X] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
We've already agreed this is the way forward with AIP-21 so we have no other choice but to merge such large PRs. I know it's automated, so I have not change every single line of it, it's more the matter of trust and quick scanning. I think it's better to merge it quickly to avoid conflicts.

**Comment by potiuk** [comment]
Is it still [WIP] ? Or should we merge it @mik-laj ?

**Comment by mik-laj** [comment]
Can you check if full compatibility has been maintained?

For example:
```
# pylint: disable=unused-import
from airflow.providers.apache.pinot.hooks.pinot import PinotAdminHook, PinotDbApiHook  # noqa
```
If `airflow.providers.apache.pinot.hooks.pinot` package contains  two classess, then two classes should be imported and two classes should be added in `test_core_to_contrib.py` file. The selection of classes was manual, because I did not want to maintain compatibility with BaseHook or other not important stuff.

It's not WI now. I waited for last Travis's build.

**Comment by mik-laj** [comment]
I found an issue:. We have HDFS sensor in two places:
https://github.com/apache/airflow/blob/master/airflow/contrib/sensors/hdfs_sensor.py
https://github.com/apache/airflow/blob/master/airflow/sensors/hdfs_sensor.py
but in this PR we have sensors from one location, because the file has been overwritten instead of the appended.

You could verify this PR using following commands:
```
diff <(git show apache/master:airflow/contrib/hooks/pinot_hook.py) <(cat airflow/providers/apache/pinot/hooks/pinot.py)
diff <(git show apache/master:tests/contrib/hooks/test_pinot_hook.py) <(cat tests/providers/apache/pinot/hooks/test_pinot.py)
diff <(git show apache/master:airflow/contrib/hooks/spark_jdbc_hook.py) <(cat airflow/providers/apache/spark/hooks/spark_jdbc.py)
diff <(git show apache/master:tests/contrib/hooks/test_spark_jdbc_hook.py) <(cat tests/providers/apache/spark/hooks/test_spark_jdbc.py)
diff <(git show apache/master:airflow/contrib/hooks/spark_jdbc_script.py) <(cat airflow/providers/apache/spark/hooks/spark_jdbc_script.py)
diff <(git show apache/master:airflow/contrib/hooks/spark_sql_hook.py) <(cat airflow/providers/apache/spark/hooks/spark_sql.py)
diff <(git show apache/master:tests/contrib/hooks/test_spark_sql_hook.py) <(cat tests/providers/apache/spark/hooks/test_spark_sql.py)
diff <(git show apache/master:airflow/contrib/hooks/spark_submit_hook.py) <(cat airflow/providers/apache/spark/hooks/spark_submit.py)
diff <(git show apache/master:tests/contrib/hooks/test_spark_submit_hook.py) <(cat tests/providers/apache/spark/hooks/test_spark_submit.py)
diff <(git show apache/master:airflow/contrib/hooks/sqoop_hook.py) <(cat airflow/providers/apache/sqoop/hooks/sqoop.py)
diff <(git show apache/master:tests/contrib/hooks/test_sqoop_hook.py) <(cat tests/providers/apache/sqoop/hooks/test_sqoop.py)
diff <(git show apache/master:airflow/contrib/operators/druid_operator.py) <(cat airflow/providers/apache/druid/operators/druid.py)
diff <(git show apache/master:tests/contrib/operators/test_druid_operator.py) <(cat tests/providers/apache/druid/operators/test_druid.py)
diff <(git show apache/master:airflow/contrib/operators/spark_jdbc_operator.py) <(cat airflow/providers/apache/spark/operators/spark_jdbc.py)
diff <(git show apache/master:tests/contrib/operators/test_spark_jdbc_operator.py) <(cat tests/providers/apache/spark/operators/test_spark_jdbc.py)
diff <(git show apache/master:airflow/contrib/operators/spark_sql_operator.py) <(cat airflow/providers/apache/spark/operators/spark_sql.py)
diff <(git show apache/master:tests/contrib/operators/test_spark_sql_operator.py) <(cat tests/providers/apache/spark/operators/test_spark_sql.py)
diff <(git show apache/master:airflow/contrib/operators/spark_submit_operator.py) <(cat airflow/providers/apache/spark/operators/spark_submit.py)
diff <(git show apache/master:tests/contrib/operators/test_spark_submit_operator.py) <(cat tests/providers/apache/spark/operators/test_spark_submit.py)
diff <(git show apache/master:airflow/contrib/operators/sqoop_operator.py) <(cat airflow/providers/apache/sqoop/operators/sqoop.py)
diff <(git show apache/master:tests/contrib/operators/test_sqoop_operator.py) <(cat tests/providers/apache/sqoop/operators/test_sqoop.py)
diff <(git show apache/master:airflow/contrib/sensors/hdfs_sensor.py) <(cat airflow/providers/apache/hdfs/sensors/hdfs.py)
diff <(git show apache/master:tests/contrib/sensors/test_hdfs_sensor.py) <(cat tests/providers/apache/hdfs/sensors/test_hdfs.py)
diff <(git show apache/master:airflow/hooks/druid_hook.py) <(cat airflow/providers/apache/druid/hooks/druid.py)
diff <(git show apache/master:tests/hooks/test_druid_hook.py) <(cat tests/providers/apache/druid/hooks/test_druid.py)
diff <(git show apache/master:airflow/hooks/hdfs_hook.py) <(cat airflow/providers/apache/hdfs/hooks/hdfs.py)
diff <(git show apache/master:tests/hooks/test_hdfs_hook.py) <(cat tests/providers/apache/hdfs/hooks/test_hdfs.py)
diff <(git show apache/master:airflow/hooks/hive_hooks.py) <(cat airflow/providers/apache/hive/hooks/hive.py)
diff <(git show apache/master:tests/hooks/test_hive_hook.py) <(cat tests/providers/apache/hive/hooks/test_hive.py)
diff <(git show apache/master:airflow/hooks/pig_hook.py) <(cat airflow/providers/apache/pig/hooks/pig.py)
diff <(git show apache/master:tests/hooks/test_pig_hook.py) <(cat tests/providers/apache/pig/hooks/test_pig.py)
diff <(git show apache/master:airflow/hooks/webhdfs_hook.py) <(cat airflow/providers/apache/hdfs/hooks/webhdfs.py)
diff <(git show apache/master:tests/hooks/test_webhdfs_hook.py) <(cat tests/providers/apache/hdfs/hooks/test_webhdfs.py)
diff <(git show apache/master:airflow/operators/druid_check_operator.py) <(cat airflow/providers/apache/druid/operators/druid_check.py)
diff <(git show apache/master:tests/operators/test_druid_check_operator.py) <(cat tests/providers/apache/druid/operators/test_druid_check.py)
diff <(git show apache/master:airflow/operators/hive_operator.py) <(cat airflow/providers/apache/hive/operators/hive.py)
diff <(git show apache/master:tests/operators/test_hive_operator.py) <(cat tests/providers/apache/hive/operators/test_hive.py)
diff <(git show apache/master:airflow/operators/hive_stats_operator.py) <(cat airflow/providers/apache/hive/operators/hive_stats.py)
diff <(git show apache/master:tests/operators/test_hive_stats_operator.py) <(cat tests/providers/apache/hive/operators/test_hive_stats.py)
diff <(git show apache/master:airflow/operators/pig_operator.py) <(cat airflow/providers/apache/pig/operators/pig.py)
diff <(git show apache/master:airflow/sensors/hdfs_sensor.py) <(cat airflow/providers/apache/hdfs/sensors/hdfs.py)
diff <(git show apache/master:tests/sensors/test_hdfs_sensor.py) <(cat tests/providers/apache/hdfs/sensors/test_hdfs.py)
diff <(git show apache/master:airflow/sensors/hive_partition_sensor.py) <(cat airflow/providers/apache/hive/sensors/hive_partition.py)
diff <(git show apache/master:tests/sensors/test_hive_partition_sensor.py) <(cat tests/providers/apache/hive/sensors/test_hive_partition.py)
diff <(git show apache/master:airflow/sensors/metastore_partition_sensor.py) <(cat airflow/providers/apache/hive/sensors/metastore_partition.py)
diff <(git show apache/master:tests/sensors/test_metastore_partition_sensor.py) <(cat tests/providers/apache/hive/sensors/test_metastore_partition.py)
diff <(git show apache/master:airflow/sensors/named_hive_partition_sensor.py) <(cat airflow/providers/apache/hive/sensors/named_hive_partition.py)
diff <(git show apache/master:tests/sensors/test_named_hive_partition_sensor.py) <(cat tests/providers/apache/hive/sensors/test_named_hive_partition.py)
diff <(git show apache/master:airflow/sensors/web_hdfs_sensor.py) <(cat airflow/providers/apache/hdfs/sensors/web_hdfs.py)
diff <(git show apache/master:tests/sensors/test_web_hdfs_sensor.py) <(cat tests/providers/apache/hdfs/sensors/test_web_hdfs.py)
```

**Comment by mik-laj** [comment]
I fixed issues related to HDFS Sensor.

**Comment by potiuk** [comment]
Besides the static check - looks good !

**Comment by potiuk** [comment]
I run those diffs and it's great!

**Pull request merged**
