### PR TITLE
[AIRFLOW-3011][CLI] Add cmd function printing config

### PR DESCRIPTION
**Pull request by vazhuk**
…efined

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3011\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3011
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Example of usage:
Bash command: airflow config` 
Example of printed config is described on a screenshoot below.
image

Output of the same command could be redirected into file and then used for further operations.
image

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by victornoel** [comment]
@dispower  the output (to the file) should not contain the logs of the cli, it defeats the purpose (to get a working config file). Not sure how to handle that though.

**Comment by Fokko** [comment]
Can you give an example when you want to use this? The config is likely to contain secrets, so we should be careful exposing this.

**Comment by victornoel** [comment]
@Fokko my initial use was to:
- create a container that was setup with environment variables (including some in the entrypoint.sh, as in https://github.com/puckel/docker-airflow) and no custom configuration.
- generate the config file to persist it so that when executing commands in the container, airflow CLI would work without having to setup all the environment variables needed

The problem being that the CLI (and I suppose other daemons) needs some of the same environment variables than the running webserver.

My current workaround is to run commands through `entrypoint.sh`, which sets up all the needed environment variables. This works as long as the entrypoint script is not making mutations to the filesystem.

Maybe the original issue wasn't the correct way to tackle this problem though... I will leave that decision to the airflow team :)

**Comment by Fokko** [comment]
Thanks @victornoel 

This won't fix the problem, since the original configuration file will be read, and the environment variables are ignored. Then you should generate a config using the configuration class: https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py

This isn't trivial though since you will need to iterate over all the environment variables, and populate the keys in the conf file, while keeping the order into account (environment variables have priority over the config file).

**Comment by victornoel** [comment]
@Fokko thanks for clarifying this: basically what you just described is the original requirement of the jira issue: https://issues.apache.org/jira/browse/AIRFLOW-3011

So the PR does not solve the opened issue at all @dispower :)

**Pull request closed without merging**
