### PR TITLE
Handle ENTER key correctly in trigger form and allow manual JSON

### PR DESCRIPTION
**Pull request by jscheffl**
Follow-up of #42487

related: #42157

Unfortunately a bit more JavaScript is needed but this enables:
- Handling of press of ENTER in input fields and ensure that JSON form is submitted and correct value is sent
- Handling of manual changes of JSON dict (fix before: was always over-writing JSON)

@dannyl1u - can you confirm from your side?

### CODE REVIEW

**Comment by dannyl1u** [comment]
> Follow-up of #42487
> 
> related: #42157
> 
> Unfortunately a bit more JavaScript is needed but this enables:
> 
> * Handling of press of ENTER in input fields and ensure that JSON form is submitted and correct value is sent
> * Handling of manual changes of JSON dict (fix before: was always over-writing JSON)
> 
> @dannyl1u - can you confirm from your side?

Taking a look

**Comment by dannyl1u** [comment]
@jscheffl tested your branch locally, works good for me. Thank you!

**Review by shahar1 — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]
Thanks for catching that early.

Tested, working as expected. Code looks good. 👍

**Comment by pierrejeambrun** [comment]
Thanks, cherrypick PR is here https://github.com/apache/airflow/pull/42535

**Pull request merged**
