### PR TITLE
Remove schedule downstream tasks after execution (aka "mini scheduler")

### PR DESCRIPTION
**Pull request by ashb**
This has been questionable how much benefit it actually had, but with the move towards task DB isolation in Airflow 3 we won't be able to keep this anymore (as we didn't when AIP-44 DB isolation was enabled), so lets remove it now.

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
Doc needs to be removed too but otherwise lgtm

**Review by potiuk — APPROVED** [review]

**Comment by ashb** [comment]
> Docs portion can also be removed.
> 
> https://github.com/apache/airflow/blob/b89f43ebe1ae020c9808c90b84d0737ab8ac7f5b/docs/apache-airflow/administration-and-deployment/scheduler.rst?plain=1#L386-L389

Thanks - I was grepping based on config option, guess I missed some

**Review by vincbeck — APPROVED** [review]

**Comment by raphaelauv** [comment]
In multiple context of high number of concurrent task ( more than 1000 and around 50 new task by sec ) we had problems and by disabling the mini scheduler things are running way more smoothly,

maybe we could deprecate the option in 2.10.4 and set it to false in 2.11.0 , wdyt ?

**Comment by kaxil** [comment]
> In multiple context of high number of concurrent task ( more than 1000 and around 50 new task by sec ) we had problems and by disabling the mini scheduler things are running way more smoothly,
> 
> maybe we could deprecate the option in 2.10.4 and set it to false in 2.11.0 , wdyt ?

Yeah good point, fancy a PR to 2-10-test?

**Comment by jscheffl** [comment]
> > In multiple context of high number of concurrent task ( more than 1000 and around 50 new task by sec ) we had problems and by disabling the mini scheduler things are running way more smoothly,
> > maybe we could deprecate the option in 2.10.4 and set it to false in 2.11.0 , wdyt ?
> 
> Yeah good point, fancy a PR to 2-10-test?

I think deprecating the option as warning would be good. I also see it needs a re-work as with AIP-72 the function can not be "distributed on worker" as in the past.

Nevertheless when scheduling MANY tasks this was really a performance boost comparing Airflow v1 to Airflow v2 when this was added. Waiting for scheduler loop to schedule the next is really slowing down DAGs... so maybe we need a (future) similar mechanism to schedule next tasks immediately after one has finished to have the same low-latency like in the past... on the backend of course... (like a notification queue where it makes most-sense to schedule next because one task just finished...)

**Pull request merged**
