### PR TITLE
[AIRFLOW-XXX] Fix Docstrings in Hooks, Sensors & Operators

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Fix issues like the below ones:
image

image

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Doc change. Not needed

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by kaxil** [comment]
@Fokko @ashb @r39132    I found https://pypi.org/project/flake8-docstrings/ which we can include it in `.github/PULL_REQUEST_TEMPLATE.md` to enforce that docstrings are included and also in correct format. 

A user should then do the following:

```
git diff upstream/master -u -- "*.py" | flake8 --diff 
```

We only need to add `flake8-docstrings` as dependency.

However, we might want to ignore many rules which we might need to either try it ourselves or find some docs/list and decide.

**Comment by r39132** [comment]
@kaxil Do you have a count before and after your change that shows a reduction in flake8 errors?

**Comment by kaxil** [comment]
@r39132 There is a huge list of issues but some of them are what we don't need like `D401 First line should be in imperative mood`. 

image

We decreased from 7641 to 7634.

**Review by ashb — APPROVED** [review]
This change looks good as is, I suspect we don't want to enable a new flake8 check with warnings, so should create a mass-fixup PR if we are going to enable that plugin.

**Comment by kaxil** [comment]
@ashb Yes, I am going to give that plugin a good review and play-around and then discuss with you guys on the best approach we can take.

**Pull request merged**
