### PR TITLE
[AIRFLOW-6046] Fix Alembic migrations & sync it to 1.10.*

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6046

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
From https://github.com/apache/airflow/pull/6442#issuecomment-557574440

just tried doing an upgrade to 1.10.6 followed by an upgrade to master:

```
git checkout 1.10.6

alembic upgrade heads
git checkout master
alembic upgrade heads
```

Result is

```
ERROR [alembic.util.messaging] Requested revision 74effc47d867 overlaps with other requested 
revisions 004c1210f153
  FAILED: Requested revision 74effc47d867 overlaps with other requested revisions 004c1210f153
```

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by kaxil** [comment]
I have tested it with:

```bash
mkdir airflow_templ
export AIRFLOW_HOME=~/airflow_templ
mkvirtualenv airflow_templ
workon airflow_templ
pip install apache-airflow
workon airflow_templ
which airflow      # Confirm Airflow Version
airflow initdb
pip install -U -e . # Update to Airflow master
which airflow      # Confirm Airflow Version
airflow version
airflow db upgrade
```

Our original report is @mattinbits  . Can you please test the upgrade with this PR @mattinbits too ?

**Comment by mattinbits** [comment]
I can but unfortunately it might take a few days- I was testing this in the office and will be back there Tuesday

**Comment by mattinbits** [comment]
OK, I managed to test it. Using the same approach with running alembic directly. Looks good to me.

**Comment by kaxil** [comment]
> OK, I managed to test it. Using the same approach with running alembic directly. Looks good to me.

Thanks for confirming, have a nice weekend.

**Review by ashb — APPROVED** [review]
LGTM.

**Comment by Fokko** [comment]
Thanks for picking this up @kaxil 👍

**Pull request merged**
