### PR TITLE
Add version to migration prefix

### PR DESCRIPTION
**Pull request by dstandish**
We don't really need the alembic revision id in the filename.  having version instead is much more useful.  having both of them takes up too much space.

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
Do we already check that the version numbers are unique?

I'm thinking of the case where two parallel PRs add, for example. a new `109` migration. How should we handle that in terms of file naming? (It may already be handled TBF)

**Comment by ashb** [comment]
I think two PRs in parallel will conflict on the migrations-ref.rst anyway, so we should have an indicator anyway.

**Comment by dstandish** [comment]
> I think two PRs in parallel will conflict on the migrations-ref.rst anyway, so we should have an indicator anyway.

good point yeah i think we're OK.

**Comment by potiuk** [comment]
Would we have a conflict ? I think we will have two different names for migrations so the conflict will not be there. But if we gree to a numerical prefix, then just checking for duplicate numerical prefix will be enough.

BTW. Are we sure 4 digits is enough 😄  ?  Think 50 years ahead...

**Comment by dstandish** [comment]
> Would we have a conflict ? I think we will have two different names for migrations so the conflict will not be there. But if we agree to a numerical prefix, then just checking for duplicate numerical prefix will be enough.
> 
> BTW. Are we sure 4 digits is enough 😄 ? Think 50 years ahead...

4 digits is 10,000 migrations :)
By that time all bets are off

The conflict should show up in migration ref doc

**Comment by potiuk** [comment]
> The conflict should show up in migration ref doc

Ah yeah I see - because it will be adjacent lines. Indeed. Good enough.

> By that time all bets are off
Well I've just learned (visited them) that "breeze" inspiration for development environment that I implemented in a robotics/ai company I worked before getting to Airflow is still there - alive an kicking even if they grew 10-fold and have different robots and "voyages" as we named them 5 years ago. So you never know ... :D.

Yeah. 10.000 migrations would be kinda time to rewrite it.

**Comment by dstandish** [comment]
doing some testing around the conflict resolution

**Comment by dstandish** [comment]
so i tested the merge conflict experience, and found that the pre-commit hook would fail interminably because it would keep re-ordering the files.  i found that if we merge the heads then that locks the ordering and the hook will then pass.

I also build out the merge heads command for users:

```bash
Update migration ref doc.................................................Failed
- hook id: update-migration-references
- exit code: 1

You have multiple alembic heads; please merge them with the `alembic merge` command and re-run pre-commit.
hint: `alembic merge -m 'merge heads 2468, 9adf' 246895566b3c 9adf8f4beff3`
```

**Comment by dstandish** [comment]
Also part of this, i found that the "insert airflow version" logic (from airflow.version import version) doesn't work correctly when there's an old egg in the directory.  but doing `from setup import version` works correctly in this case.

**Comment by potiuk** [comment]
> I also build out the merge heads command for users:
❤️

**Comment by potiuk** [comment]
Rebase should fix it/

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Should we update any information here https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#metadata-database-updates ?

**Comment by dstandish** [comment]
> Should we update any information here https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#metadata-database-updates ? Maybe not 🤷 but if there are helper points, feel free to add them over there

good idea

**Pull request merged**
