### PR TITLE
Add decorators for external and venv python branching operators

### PR DESCRIPTION
**Pull request by jscheffl**
This PR is a follow-up of PR #33356 to add also python decorators for additional branching tasks for:
- external python
- python virtual environments
To make the feature set complete also for taskflow style DAGs.

How to test?
* See docs and in general CI is green
* Run the example_branch_operator
* Run the example_branch_python_operator_decorator

### CODE REVIEW

**Comment by potiuk** [comment]
Looks really nice. But how about adding Howtos/Examples to https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html folllowing other operators? I think otherwise they will not be easily discoverable

**Comment by jens-scheffler-bosch** [comment]
> Looks really nice. But how about adding Howtos/Examples to https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html folllowing other operators? I think otherwise they will not be easily discoverable

Good idea... should have had the idea myself with examples... DIFF is larger now. I re-worked the existing branching examples and made it all together in one place - let me know if this was the correct idea.
See in "How to test" which DAGs as example are modified now. Also made this for the classic operators for consistency.

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
tests need fixing but It LGTM otherwise.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
All Good. Failed check fixed in main,

**Pull request merged**
