### PR TITLE
[AIRFLOW-6780] Add option to use args instead of command in K8s pod spec

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR adds a config option, `kubernetes.worker_pod_uses_args`, that is passed to `PodGenerator.construct_pod` in order to decide whether or not the Kubernetes `args` field is used instead of `command` in the worker pod specs.

This PR is replacing #7405 (moved to my personal fork).

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by brandonwillard** [comment]
@mik-laj, looks like I can't request reviewers on this one, but did you see [my follow-up to your question](https://github.com/apache/airflow/pull/7405#discussion_r403589325) in the old PR?

**Comment by brandonwillard** [comment]
I'm very confused by [this Travis EOF error](https://travis-ci.org/github/apache/airflow/jobs/671105889#L2531).

**Comment by brandonwillard** [comment]
Also, I've looked into the K8s-related errors (e.g. [this one](https://travis-ci.org/github/apache/airflow/jobs/671105884#L2504)) and I don't see any changes between the `master` deployment spec and [this branch's](https://travis-ci.org/github/apache/airflow/jobs/671105884#L1920) (i.e. no changes in the `command`/`args` values), so I don't know how these changes could be affecting those tests.  

Can someone with more familiarity with these tests take a quick look and point me in the right direction?

**Comment by dimberman** [comment]
Hi @brandonwillard can you give a use-case for this? Also please rebase we had to fix the k8s tests a week or two ago.

**Pull request closed without merging**
