### PR TITLE
Revert "Unquarantine background webserver test (#28249)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 5fad8a4a450de8388e4488523670d5f10f4f35b1.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Hmm. even with the fix, the test is still not stable - for example https://github.com/apache/airflow/actions/runs/3656433350/jobs/6179155045

Reverting

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
Just merged #28252  from @Taragolis and let's see - maybe that will help. I am willing to take some chances on it :)

**Comment by potiuk** [comment]
I rebased on top of #28582 and changed this so let's keep that one ready to merge if we find that the timeout is not enough

**Comment by potiuk** [comment]
Unfortunately - the only way to REALLY check if flaky tests like that are fixed is to run it for a number of PRs that people will raise :(.

**Comment by potiuk** [comment]
Fingers crossed but seems that https://github.com/apache/airflow/pull/28252 fixed the problem. 🤞 

3 full "green" main/canary builds since it was merged - all of them fully green.  Closing. 

Thanks @Taragolis for the fix.

**Pull request closed without merging**
