### PR TITLE
[AIRFLOW-2162] Pass env variables to sudo when impersonating

### PR DESCRIPTION
**Pull request by johnarnold**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2162

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
When impersonating a user other than the user the executor is running as, sudo is pre-pended to the commands.  Without -E arg, the env variables are lost.  This can affect running in docker containers, etc.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Trivial 1-line change already covered in tests.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jgao54** [comment]
My only concern is that it passes *all* environment variables of the user, which may not be ideal... it would be more secure to selectively pass Airflow environment variables only with `env_keep`. thoughts?

**Comment by johnarnold** [comment]
@jgao54   Passing all the env variables is kind of the point.  For some environments, you need things like path, pythonpath, virtualenv stuff, who knows what other env variables are used by the operator.  Credentials/secrets, etc.

I think it's safe enough to assume that a subprocess can have the same environment as the parent process.

**Comment by Fokko** [comment]
Unless you are storing the Airflow Postgres/MySQL database in the env parameters. I've seen this in Airflow Docker deployments.

**Comment by Fokko** [comment]
Ah, this is the process runner. I think it is a different process anyway.

**Comment by johnarnold** [comment]
@Fokko any issues with merging?   Build failure not related to code change.

**Comment by jgao54** [comment]
@johnarnold sorry to get back on this so late. 

Just realized that in the case where there is no impersonation, all the environment variables are _already_ being passed down to the task execution process, which means they are already accessible to all operators. This PR simply extends this behavior when user impersonation is specified. 

That said, I share the same concern as @Fokko, I still believe we have a potential security concern on the whole by passing down all environment variables to the local task execution. This means that it is the responsibility of (1) the airflow admin to not store sensitive data in environment variables in production or (2) the dag repo maintainer to properly audit the dag file and make sure it is not malicious. (1) seems very hard to guarantee (2) seems easier, but not foolproof.

I'm okay with merging this PR since it's just extending existing behavior. Long term I think we should address this issue, so I'll create a [JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2311) for this.

**Comment by Fokko** [comment]
👍

**Pull request merged**
