### PR TITLE
Tests for AWS Athena

### PR DESCRIPTION
**Pull request by Udit107710**
This was created to address one of the files mentioned by #8278.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
This would run the tests against an actual Athena instance, which isn't what we want in our unit tests.

Please look at https://github.com/spulec/moto (already used in other tests, for instance S3) and which supports Athena since 1.3.14 (which are are using)

**Comment by Udit107710** [comment]
> 
> 
> This would run the tests against an actual Athena instance, which isn't what we want in our unit tests.
> 
> Please look at https://github.com/spulec/moto (already used in other tests, for instance S3) and which supports Athena since 1.3.14 (which are are using). moto as of the latest release may not provide _enough_ mocking, so you may have to use just normal unittest.mock to ensure that no network requests are made in this unit test.

10 days ago, support for various functions in Athena, being used by Airflow has been added to moto. I would recommend to bump moto from 1.3.14 to 1.3.15(latest release).

**Comment by potiuk** [comment]
Yep. It would be great to get it mocked :)

**Comment by Udit107710** [comment]
@potiuk The stable release for 1.3.15 is not available. The new features for Athena are still in dev branch. Should I bump the dependency or use mock?

**Pull request closed without merging**
