### PR TITLE
Add support for extra CronJobs in Airflow helm chart

### LINKED ISSUE #34399: Support for custom cronjobs
### Description

https://github.com/apache/airflow/blob/3854264a31ba5c7718c51a034154f12483ad78d3/chart/values.yaml#L2167-L2180

Since airflow helm chart only supports cleanup cronjob, users have to modify templates to add additional maintenance cronjobs

### Use case/motivation

For example, we can create multiple custom cronjobs using <code>values.yaml</code> ​​below

```yaml
cronJobs:
  cleanPods:
    image: apache/airflow
    schedule: "*/15 * * * *"
    command: ~
    args: ["bash", "-c", "exec airflow kubernetes cleanup-pods --namespace={{ .Release.Namespace }}"]
    ...
  cleanDB:
    image: apache/airflow
    schedule: "30 3 1 * *"
    command: ~
    args: ["bash", "-c", "exec airflow db clean"]
    ...
  backupDB:
    image: CUSTOM_IMAGE
    schedule: "0 1 1 * *"
    command: ~
    args: ["bash", "-c", "pg_dump -h HOST -U USER_NAME -Fc DATABASE_NAME | aws s3 cp - s3://<bucket_name>/<database_name>.dump"]
    ...
```

By providing custom cronjobs, we can flexibly respond to additional maintenance tasks as needed.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shohamy7**
---
closes: #34399

This PR aims to add support for custom CronJobs that can be deployed and managed with the official Airflow helm chart.
I am working on tests on this feature right now, but I would like to hear what do you think about the implementation.

- [ ] needs tests

### CODE REVIEW

**Comment by potiuk** [comment]
I am not sure if that is really needed as a feature. That sounds like pretty orthogonal to Airflow "functionality" as application and more of a generic nature.

This looks like a completely independent feature of the chart that does not interact with other components of the chart and I see no particular reason why we should add the whole complexity of those to manage them in our chart. I would rather focus on telling users how they can easily add this and similar kinds of "extensions" to Airflow chart without having to implement it as feature and without having to carry a burden of maintaining those by the Airflow community. 

The problem with such "features" as chart is that people expect that everything will be "configurable" for them as a black box - say you will want to add - for example - anti-affinity to your cronJob to not run at the same machine as your scheduler or things like that - which K8S has plenty of. Surely you can define template in the way that allows you to add any resource option, but when it gets more and more complex and flexible, you either go the route where you literally copy&paste K8S resource definition to your values.yml (which requires you to understand resource definition of K8S as a user) or you introduce a parallel yaml definition of those resources in your values.yaml - so basically your custom "resource" definition. I think K8S resource definition is "good enough" as an abstraction layer and when you manage k8s application - even via chart - you need to understand those and learn it, and be able to write your own definition. For me Helm Chart is not a black box - it's much more of a "gray box" where managing and customizing you helm applications requires you to understand resource definitions.

So (with such a long intro) I think it would be great to explain how you can do similar things and show this as an example but purely as a documentation, not as a feature of the chart.

Not many people are aware but there is a very easy (albeit a bit counter-intuitive) way of extending the charts by making your own chart and adding the chart you want to extend as a sub-chart.

https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

In this particular case you can easily create your own chart, make airflow a sub-chart of it and add such cron job (or many of thsoe) as a resource in your custom chart. This makes it very easy to maintain and it's usually way simpler to do because you would not have to make it generic, you could hard-code your resources and definition of cron-job of yours in a much simpler way, and you could add any kind of labeling, scheme, extra resources etc. etc.  And it has the extra flexibility of being able to do anything else the same way. It's not limiting the users in any way, they can usually do it much faster and easier. 

I believe that If you convert this into a documentation example of how you can extend Airlfow chart and add your own custom functionality (cron job being a good example of this) in https://airflow.apache.org/docs/helm-chart/stable/production-guide.html  - that would be a much better approach to make it possible for Airflow Chart users. They willl get not only an explanation on how can they add cron jobs but also a segway to be able to add  other things they miss.

**Comment by shohamy7** [comment]
Hi @potiuk, thanks for the response!
I see what you're saying. When I started to implement this feature, I thought that this could be just an Airflow DAG instead of cronjob. You will also get the whole Airflow's ecosystem e.g. Webserver, rerun ability, callbacks, etc.
I saw that this is an open issue, so I thought that maybe there is a different reason why we need this feature.
I also not quite sure that an example of extending Airflow chart is necessary cause I don't think that related to the Airflow chart or even the Airflow project as a whole. It seems like a users' issue that they need to deal with, whether by creating dedicated DAG in Airflow or creating a CronJob yaml should be their choice (depending on the use-case off course).
Please, let me know what you think! :)

**Comment by potiuk** [comment]
I think it would be great to give our users some hints and direction there, and - as people work best based on examples - having a real-life useful example of how you can do such extension would be a useful thing to have.

Smart contributing to open-source project is more than just contributing the code. Sometimes contributing the documentation (based on your own code) how users can make their use of the open-source product is far more effective that having our code land in the code of the product. It has all the properties of contribution, and sometimes it has a far wider influence than the code contribution (and also it has far smaller long-term maintenance factor, which is the main point why we are cautious about accepting code contributions). 

So while you are at it, I think it is a great opportunity for you to contribute it, and get much bigger influence and use the opportunity that you already have interest, engagement and code that you might run locally and test while contributing the docs about it. I'd encourage you to do it.

**Comment by shohamy7** [comment]
I will work on example and documentation about how users can extend the official Airflow chart by using Subcharts and global values.
I would be glad if you could take a look at it once I finished :)
Closing this PR for now.

**Pull request closed without merging**
