### PR TITLE
[AIRFLOW-386] limit scope to user email only for github oauth

### PR DESCRIPTION
**Pull request by mylons**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-386](https://issues.apache.org/jira/browse/AIRFLOW-386)

Testing Done:
- tested login on my dev instance

### CODE REVIEW

**Comment by r39132** [comment]
+1

**Comment by bolkedebruin** [comment]
Commit nazi here: please adhere to guidelines next time makes for tidy history ;-)

**Comment by mylons** [comment]
@bolkedebruin sorry -- what did i miss?

**Comment by r39132** [comment]
@bolkedebruin Good catch - I admit that I didn't see it either at first. 

The title in the commit is `limit scope to user email only AIRFLOW-386`, which does not adhere to guidelines, where as the title in the PR follows the correct guidelines : `[AIRFLOW-386] limit scope to user email only for github oauth`

@jlowin I thought the pr tool did some checks on the title, but maybe it's checking the PR title not the commit title? 

screenshot 2016-08-01 20 04 16

**Comment by jlowin** [comment]
@r39132 indeed, it only checks (and will modify, if you let it) the PR title but not commits. Perhaps I can add that as an enhancement.

**Pull request merged**
