### PR TITLE
Add missing test for kubernetes compat converters

### PR DESCRIPTION
**Pull request by yangyulely**
This PR will add unit tests for kubernetes compat converters, and improve the coverage to 100% of `backwards_compat_converters.py`
image
related: #35442

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by yangyulely** [comment]
@romsharon98 , can you review this? I will add more test if that's okay.

**Comment by romsharon98** [comment]
The tests looks good.
One small thing, in my opinion, when you want to test a function that calls a function inside it you will want to mock the inner call and just test the call has been done like you expected (and not really call the inner function).
Let me know what you think.

**Comment by yangyulely** [comment]
> The tests looks good. One small thing, in my opinion, when you want to test a function that calls a function inside it you will want to mock the inner call and just test the call has been done like you expected (and not really call the inner function). Let me know what you think.

Yeah, couldn't agree more with you, as you can see, that's how I got there
```suggestion
@patch("airflow.providers.cncf.kubernetes.backcompat.backwards_compat_converters._convert_kube_model_object")
def test_convert_volume_mount_normal_value(mock_convert_kube_model_object):
    mock_convert_kube_model_object.return_value = k8s.V1VolumeMount(
        name="test_volume_mount", mount_path="/mnt/test"
    )
```

**Comment by romsharon98** [comment]
> > The tests looks good. One small thing, in my opinion, when you want to test a function that calls a function inside it you will want to mock the inner call and just test the call has been done like you expected (and not really call the inner function). Let me know what you think.
> 
> Yeah, couldn't agree more with you, as you can see, that's how I got there
> 
> ```
> @patch("airflow.providers.cncf.kubernetes.backcompat.backwards_compat_converters._convert_kube_model_object")
> def test_convert_volume_mount_normal_value(mock_convert_kube_model_object):
>     mock_convert_kube_model_object.return_value = k8s.V1VolumeMount(
>         name="test_volume_mount", mount_path="/mnt/test"
>     )
> ```

Yes but I think we need to add that we call the Mock function correctly for example in this one we should add:
```python
mock_convert_kube_model_object.assert_called_with(...)
```

**Comment by yangyulely** [comment]
> Yes but I think we need to add that we call the Mock function correctly for example in this one we should add:
> 
> ```python
> mock_convert_kube_model_object.assert_called_with(...)
> ```
> 
> to really verify the logic of the function

@romsharon98, I have updated for that, will appreciate it if you could review again.

**Review by romsharon98 — APPROVED** [review]
Looks good!

**Pull request merged**
