### PR TITLE
[AIRFLOW-1692] Changed test_views filename

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
to support windows

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1692

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
The test_views unit-test used a file which contained colons. Such a file is not supported on windows.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Fokko** [comment]
+1 Let the tests pass on Windows

**Comment by NielsZeilemaker** [comment]
Not really, as the unit-tests don't run on windows. But, it will allow me to do a git checkout on windows.

**Comment by andyxhadji** [comment]
LGTM - Can we merge this? It'll unblock https://github.com/apache/incubator-airflow/pull/2532!

**Comment by NielsZeilemaker** [comment]
@bolkedebruin would it be possible to merge this pull request?

**Comment by bolkedebruin** [comment]
Done sorry for the delay.

**Pull request closed without merging**
