### PR TITLE
[WIP][AIRFLOW-6395] Add an asyncio compatible dask executor [AIP-28]

### PR DESCRIPTION
**Pull request by dazza-codes**
## WIP status

- this is a first sketch that requires a lot more work to evaluate
- this is motivated by [AIP-28](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-28%3A+Add+AsyncExecutor+option)
- see https://gist.github.com/seglberg/0b4487b57b4fd425c56ad72aba9971be
  - consider the subclass `AsyncioExecutor(concurrent.futures.Executor)`
  - this is added/modified and tested; it works but one of the problems of the design is that it's not thread-safe because it spawns a thread to run the asyncio loop forever; there may be better ways to do this on a single thread

### PR checklist

TODO:

- [ ] Description above provides context of the change
- [ ] Commit message contains [\[AIRFLOW-XXXX\]](https://issues.apache.org/jira/browse/AIRFLOW-XXXX) or `[AIRFLOW-XXXX]` for document-only changes
- [ ] Unit tests coverage for changes (not needed for documentation changes)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions.
- [ ] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by tooptoop4** [comment]
@dazza-codes seeing as u know dask, can u help with https://issues.apache.org/jira/browse/AIRFLOW-4796 ?

**Comment by dazza-codes** [comment]
I'll come back to this.

**Comment by ashb** [comment]
Hey @dazza-codes, I'm all in favour of async in general, but can I ask a pointed question:

What does this give us? If I'm reading the PR right (and I've just glanced at it) this creates an async (thread) inside the scheduler that makes network requests to Dask?

**Comment by dazza-codes** [comment]
At some point, I hope to circle back to asyncio in Airflow.  For now, I'm working more on the low-level details in another project, https://gitlab.com/dazza-codes/aio-aws, so that I can avoid some complexity of the legacy work in Airflow and any conflicts with the larger community use-cases.  There's a lot of details in the asyncio approach that need to be resolved before I could confidently contribute something to Airflow.

With regard to dask and async executors, dask already has the right backend to support async execution, so this should be low-hanging fruit.  I apologise for neglecting it for a bit.  I did explore some basic elements of an async executor in
- https://gitlab.com/dazza-codes/python-notes/-/blob/master/notes/async_executor.py
- https://gitlab.com/dazza-codes/python-notes/-/blob/master/tests/test_async_executor.py
I'm not entirely convinced that using a thread for the loop and passing coroutines across a thread-safe bridge is the right way to go.  For instance, it's noted in https://docs.python.org/3.6/library/asyncio-dev.html#concurrency-and-multithreading that `Most asyncio objects are not thread safe.`

**Comment by ashb** [comment]
We can probably learn a lot form what Django of done -- they've just landed sync+async via https://github.com/django/asgiref/tree/master/asgiref

**Comment by potiuk** [comment]
@ashb +1 -> for me this looks like 2.1 thing. 

And also I believe rather than doing it on our own - we should rather wait for Celery 5 https://stackoverflow.com/questions/39815771/how-to-combine-celery-with-asyncio -> there likely we could (again) build on top of all the hard-work Celery people put into making us use it in the first place.

**Comment by dazza-codes** [comment]
For various reasons beyond my control, the complexity of Airflow seemed to be a hurdle for various ops and other personnel on a team at work.  In short, I don't have time to follow-through on this in a timely manner, since alternative simpler options have proved to be useful.  See various details in the Apache2 code at
- https://gitlab.com/dazza-codes/aio-aws

+1 for anyone who wants to beg-borrow-or-steal anything to move this along, if it's a worthy direction for Airflow.

**Comment by kaxil** [comment]
Thanks for your work @dazza-codes -- going to close it so that someone else can take it from here in a new PR

**Pull request closed without merging**
