### PR TITLE
[AIRFLOW-1102] Add `python:` prefix for gunicorn config to make it working with gunicorn 19.4+

### PR DESCRIPTION
**Pull request by yyuu**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1102

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Modified gunicorn dependency version and tweaked `webserver` to make it working with gunicorn 19.4+.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by saguziel** [comment]
I'm guessing this isn't backwards compatible?

**Comment by yyuu** [comment]
Unfortunately, yes. Basically, I believe that gunicorn should have avoided to implement this kind of invompatible changes.

The possible approaches to deal with this breaking changes could be,

1. Modify gunicorn to restore original behavior as gunicorn prior to 19.4
    * https://github.com/benoitc/gunicorn/pull/1499
1. Update airflow's dependency gunicorn version and make it working with gunicorn 19.4+

This PR is for the latter. This may become a kind of incompatibility of airflow. Though gunicorn itself already has an incompatibility and I couldn't find possible workarounds other than this.

**Comment by marcusianlevine** [comment]
+1

We'd like to use a more recent version of gunicorn

**Comment by briancharous** [comment]
@bolkedebruin Any chance we can get this in? The old version of gunicorn is a blocker for using gevent workers and Py3.

**Comment by bolkedebruin** [comment]
@briancharous that is a bit hard for 1.9.0 as this has conflicts, isn't backwards compatible. Target 1.9.1?

**Comment by briancharous** [comment]
@bolkedebruin Considering it's only a 1-line change, it shouldn't be a big conflict to resolve, but 1.9.1 is fine.

**Comment by bolkedebruin** [comment]
If it is updated to not conflict and a clean PR @criccomini could consider it for 1.9.0 as a release manager.

**Comment by briancharous** [comment]
@yyuu Do you want to move this along? Otherwise I will open a new PR against a more recent branch so this can get merged.

**Comment by yyuu** [comment]
@briancharous sorry for delay. Actually I'm not very familiar with the code and testing of airflow project. It'd be very nice if you can create more appropriate PR. Thanks for taking care!

**Comment by ashb** [comment]
Closing in favour of the (merged) other PR. Now that we can close PRs \o/

**Pull request closed without merging**
