### PR TITLE
Move Backport Providers docs to our docsite

### PR DESCRIPTION
**Pull request by kaxil**
The Backport Providers guide is more suitable for docsite. I have improved grammatical errors wherever necessary to while moving it. This also makes our README.md a bit lighter.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Nice. I guess we shoudl also cherry-pick it to the v1-10-test branch for 1.10.13. i can do it.

**Review by potiuk — APPROVED** [review]

**Comment by mik-laj** [comment]
It seems to me that we have several products and each product has its own documentation. We therefore should update the index of our documentation - `https://airflow.apache.org/docs/` to show this, so that we can easily update any documentation independently.
I imagine there will be a list of documentation links for each of our products, such as Apache Airflow, Helm Charm for Apache Airflow, Docker Image, Backport packages and others.
Somethings similar to: https://mc-stan.org/users/documentation/  https://cloud.google.com/sql/docs

**Comment by potiuk** [comment]
@mik-laj -> maybe create an issue for it? That's an interesting proposal that seems like a major doc restructuring - impacting all the stages - updating, building, releasing. And one that might finally speed up the documentation building process. Sounds like an interesting candidate for 2.1 :)

**Comment by mik-laj** [comment]
@potiuk will do.

**Comment by kaxil** [comment]
Yea I like the proposal @mik-laj too

**Comment by mik-laj** [comment]
I created an issue: https://github.com/apache/airflow/issues/11152

**Pull request merged**
