### PR TITLE
[AIRFLOW-4208] Replace @abstractproperty by @abstractmethod

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-4208\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4208
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-4208\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

`@abstractproperty` is deprecated since 3.3. Replacing it with `@abstractmethod` + `@property`
https://docs.python.org/3/library/abc.html#abc.abstractproperty

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Did not change any functionality.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
Can you rebase onto master?

**Comment by milton0825** [comment]
Somehow I still see python2.7 usage in the CI.
```
+kubectl logs airflow-8c6c5db65-nrq4w init
+ ./tmp/airflow-test-env-init.sh
+ cd /usr/local/lib/python2.7/dist-packages/airflow
+ airflow initdb
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python2.7/dist-packages/airflow/__init__.py", line 37, in <module>
    from airflow.models import DAG
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator  # noqa: F401
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/baseoperator.py", line 34, in <module>
    from airflow.models.dag import DAG
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/dag.py", line 43, in <module>
    from airflow.dag.base_dag import BaseDag
  File "/usr/local/lib/python2.7/dist-packages/airflow/dag/base_dag.py", line 28
    class BaseDag(metaclass=ABCMeta):
                           ^
SyntaxError: invalid syntax
+'[' 1 = 1 ']'
```

**Comment by milton0825** [comment]
PTAL @Fokko @feng-tao

**Comment by Fokko** [comment]
Python2 is still in the CI: https://github.com/apache/airflow/pull/5090

**Comment by milton0825** [comment]
@Fokko the usage of `@property` + `@abstractmethod` is supported in py2 actually

**Comment by milton0825** [comment]
ping

**Comment by milton0825** [comment]
ping

**Comment by potiuk** [comment]
Can  you please rebase @milton0825?

**Comment by milton0825** [comment]
@potiuk rebased and the build is successful on my CI: https://travis-ci.org/milton0825/airflow/builds/523114911

**Review by potiuk — APPROVED** [review]

**Comment by milton0825** [comment]
Shall we merge this?

**Pull request merged**
