### PR TITLE
Remove `require_authentication` decorator from security.py

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This decorator was added in #34317, but it seems it's not used anywhere. Opening this PR to see if I'm missing something

cc @vincbeck

### CODE REVIEW

**Comment by vincbeck** [comment]
It is used [here](https://github.com/apache/airflow/pull/35340/files#diff-86edd78c9ae6d7bd14be12d16870d2c900014027e53295d67f0f1ab80169825fR48) :) I love the try though

**Comment by ephraimbuddy** [comment]
> It is used [here](https://github.com/apache/airflow/pull/35340/files#diff-86edd78c9ae6d7bd14be12d16870d2c900014027e53295d67f0f1ab80169825fR48) :) I love the try though

What of this: https://github.com/apache/airflow/blob/8c25304f047dd77dde6802155a894ce9a15481a8/airflow/auth/managers/fab/api/auth/backend/basic_auth.py#L58?

**Comment by vincbeck** [comment]
You can specify multiple authentication strategy for the API. See documentation [here](https://airflow.apache.org/docs/apache-airflow/stable/security/api.html). Example: `auth_backends = airflow.api.auth.backend.default, airflow.api.auth.backend.kerberos_auth`. [This code](https://github.com/apache/airflow/pull/35340/files#diff-86edd78c9ae6d7bd14be12d16870d2c900014027e53295d67f0f1ab80169825fR48) loop through all the API auths you specified in your config through `auth_backends` and then call them. So [this one](https://github.com/apache/airflow/blob/8c25304f047dd77dde6802155a894ce9a15481a8/airflow/auth/managers/fab/api/auth/backend/basic_auth.py#L58) is used whenever a user specify in his config `auth_backends = airflow.auth.managers.fab.api.auth.backend.basic_auth`

**Comment by vincbeck** [comment]
Erratum .... Sorry ... I got confused ... I think you're right, it is safe to remove

**Review by vincbeck — APPROVED** [review]

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
