### PR TITLE
Default to 0 if no rows loaded in GCS to BQ operator.

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by criccomini** [comment]
Noticed this while messing with some ELT jobs. If a GCS->BQ load is empty, it was failing trying to cast int(None). Fixed this, and defaulted to 0 now.

**Comment by criccomini** [comment]
@mistercrunch mind merging this?

**Comment by artwr** [comment]
:+1:

**Comment by criccomini** [comment]
@artwr thx!

**Pull request merged**
