### PR TITLE
Bump OPENAPI_GENERATOR_CLI_VER to latest v5 image(5.4.0)

### PR DESCRIPTION
**Pull request by DrFaust92**
Allows generating cleaner golang code

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by DrFaust92** [comment]
[uranusjr](https://github.com/uranusjr) [ephraimbuddy](https://github.com/ephraimbuddy) anything else needed here?

**Comment by DrFaust92** [comment]
[uranusjr](https://github.com/uranusjr) [ephraimbuddy](https://github.com/ephraimbuddy) any updates?

**Comment by ephraimbuddy** [comment]
This skipped my mind, will merge it after we release the current client that we want to release

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Client announced . Merging :)

**Pull request merged**
