### PR TITLE
[AIRFLOW-450] Remove http example operator

### PR DESCRIPTION
**Pull request by gtoonstra**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues
    - https://issues.apache.org/jira/browse/AIRFLOW-1316
    - https://issues.apache.org/jira/browse/AIRFLOW-450

There have been 2 PR attempts to fix this and none got merged:
    - https://github.com/apache/incubator-airflow/pull/1753
    - https://github.com/apache/incubator-airflow/pull/1890

Clearly the example dag operator causes more trouble than its worth its value, so I'm suggesting to have it removed (I was the original author). 

My suggestion is that if this example dag is very much desired, we find a reliable and consistent HTTP source that this can be programmed against first, then work out the implementation.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Are we removing this because it is running on travis or because it is faulty too often with user's deployments? @gtoonstra 

If it is the first, we should just blacklist it on Travis.

**Comment by gtoonstra** [comment]
@bolkedebruin  Two reasons: 

- On python3 installations with example dags deployed, it crashes the system because it imports the sensor module, which imports hdfs, which imports snakebite, which is not compatible with python3, as explained in https://issues.apache.org/jira/browse/AIRFLOW-1316

- The operator itself doesn't have a stable endpoint to test against, so the example dag just fails and isn't useful because of that. I've made a PR to create one as part of airflow www, but that got rejected because we shouldn't have testing endpoints in prod.

**Comment by ghost** [comment]
Not sure if this is the right place for this comment, but I also noticed that using TimeSensor under python3 naturally also doesnt work since it imports the sensor module, hdfs and the other stuff gtoonstra mentions above.

I havent looked at the code but starting a job on time shouldnt have any dependencies on HDFS. :)

It would probably be good to look over the code base and refactor things a bit so snakebite is only imported in the actual hdfs related modules. This would make airflow a lot more compatible with Python3 by default.

**Comment by Valkrysa** [comment]
Run into the issue today that a fresh installation of python3 cannot successfully init the db in airflow as long as this example-http-operator is here.

I solved the issue by manually removing the example-http-operator, however I believe a user following the natural installation procedures should not have to do this as they might not always understand it's okay to just delete the file.

My suggestion is that example-http-operator either needs to be removed from the repo or fixed so that it does not cause the entire init db script to fail.

**Pull request closed without merging**
