### PR TITLE
[AIRFLOW-3703] Support DnsPolicy for KubernetesPodOperator

### PR DESCRIPTION
**Pull request by bbcbruno**
Make sure you have checked _all_ steps below.

### Jira

- [X] https://issues.apache.org/jira/browse/AIRFLOW-3703

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

`KubernetesPodOperator` supports `hostNetwork` but sometimes in some environments it is necessary to set dnsPolicy for some pods because your cluster can use some unusual DNS configurations.

This PR adds an option to set `dnsPolicy` for a pod.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

KubernetesPodOperatorTest.test_pod_dnspolicy

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by kurtqq** [comment]
I like this!

**Review by pgagnon — COMMENTED** [review]
As a general comment, I think your new parameter should be called `dns_policy` instead of `dnspolicy` for consistency with the other parameters available.

**Comment by pgagnon** [comment]
@bbcbruno Also could you please squash your commits?

**Comment by ashb** [comment]
@pgagnon FYI: The github UI lets us (committers) squash the commits so it's not a requirement for the PR author to do it. They are welcome to, but it's not a hard requirement on them.

**Comment by ashb** [comment]
> As a general comment, I think your new parameter should be called `dns_policy` instead of `dnspolicy` for consistency with the other parameters available.

Probably, but that ship might have sailed already with `hostnetwork` and `configmaps`? (Though I do agree)

**Comment by pgagnon** [comment]
> @pgagnon FYI: The github UI lets us (committers) squash the commits so it's not a requirement for the PR author to do it. They are welcome to, but it's not a hard requirement on them.

Ah! Sorry then. The PR template still mentions that requirement. 😅

**Comment by kurtqq** [comment]
> 
> 
> > As a general comment, I think your new parameter should be called `dns_policy` instead of `dnspolicy` for consistency with the other parameters available.
> 
> Probably, but that ship might have sailed already with `hostnetwork` and `configmaps`? (Though I do agree)

It can be changed later for 2.0

What is blocking this PR from being merged?

**Comment by ashb** [comment]
@kurtqq Just the magical MoneyAndTime tree :)

**Pull request merged**
