### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by natasharw**
Fixes three typing errors in README.md, consisting of one incorrect spelling of the word 'released' and two incorrect version notations.

---
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Thanks @natasharw are you looking to contribute further (we'd love that). If yes, you could take a look at "good first issues" (https://github.com/apache/airflow/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by potiuk** [comment]
And to add to what @kaxil said PR #10000  is yours ... A very special number :)

**Comment by natasharw** [comment]
Wow what a ridiculously insignificant change for such a great milestone... But I have to tell you, I was encouraged to start being an active member of the community by Airflow Summit, and this was my first action. So hopefully the meaning is more significant than the change itself. I will definitely be looking to contribute further.

**Comment by kaxil** [comment]
> Wow what a ridiculously insignificant change for such a great milestone... But I have to tell you, I was encouraged to start being an active member of the community by Airflow Summit, and this was my first action. So hopefully the meaning is more significant than the change itself. I will definitely be looking to contribute further.

That is definitely good to hear :) Let us know if you need any help

**Pull request merged**
