### PR TITLE
Fix google cred links

### PR DESCRIPTION
**Pull request by ashb**
Before:

image

After:

image

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by dstandish — APPROVED** [review]
there were a lot more changes a  second ago was  about to ask :)

**Comment by ashb** [comment]
> there were a lot more changes a second ago was about to ask :)

Yeah, that is for upgrading sphinx and sphinx-autoapi (which is how I noticed this -- it caused an warning in more recent versions.)

**Comment by ashb** [comment]
I'll merge this after docs build has passed.

**Comment by ashb** [comment]
Fine, I will roll this in to the sphinx upgrade instead.

**Comment by ashb** [comment]
https://github.com/apache/airflow/pull/20079

**Pull request closed without merging**
