### PR TITLE
Add startup scripts for upstart based systems

### PR DESCRIPTION
**Pull request by d-lee**
This has been tested on Ubuntu 14.04 in AWS

### CODE REVIEW

**Comment by mistercrunch** [comment]
Very nice. Can you add a note with a reference to the README `docs/installation.rst`?

**Comment by d-lee** [comment]
Added note to installation.rst and cleaned up README a little bit

**Comment by mistercrunch** [comment]
Please rebase the branch so that I can merge it!

**Comment by d-lee** [comment]
Not sure what happened here. Looks like after rebasing a lot of unrelated commits spilled into this PR

**Comment by d-lee** [comment]
Not sure why the build is failing. There is nothing in these .conf files that can possibly cause it

**Comment by mistercrunch** [comment]
It looks like transient errors, we've been having travis/coveralls issues lately

**Comment by bolkedebruin** [comment]
@d-lee can you please add Apache license headers to the _new_ files you have added? I will then merge.

**Comment by d-lee** [comment]
I can add it but is license header really mandatory in each and every source file of a project licensed under ASL?

**Comment by d-lee** [comment]
Here you go. Added license headers

**Pull request merged**
