### PR TITLE
Add documentation on load_examples with official Docker and helm

### PR DESCRIPTION
**Pull request by xinbinhuang**
cloeses: #14491  

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you do a rebase? Documentation for Helm Chart has been moved to the new documentation package. See: https://github.com/apache/airflow/pull/14643

**Comment by xinbinhuang** [comment]
@mik-laj  just rebased to master

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Build docs step is failing @xinbinhuang

**Comment by xinbinhuang** [comment]
@kaxil Fixed! Tested locally.

**Pull request merged**
