### PR TITLE
[WIP][AIRFLOW-2625] [AIRFLOW-2616] Implements an API to fetch all DAGs 

### PR DESCRIPTION
**Pull request by verdan**
**This PR is WIP. 
Opened this PR for community approval to use MethodView instead of developing APIs using functional views. It would help in organizing the APIs using modular approach, else our endpoints.py file will eventually grow bigger, and hard to maintain.**

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2625) issues and references them in the PR title.

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
It adds a basic functionality of an API to get all DAGs and the count using the MethodView. I still need to add the searching/filtering and ordering features for this endpoint.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by verdan** [comment]
@Fokko @kaxil can you please take a look?

**Comment by bolkedebruin** [comment]
@verdan can you please test this om your own github repo? Apache Infra asked us to use less of  travis time. Thanks

**Comment by feng-tao** [comment]
hey @verdan , not sure if you are aware, flask appbuilder provides CRUD functionality for all the views(http://flask-appbuilder.readthedocs.io/en/latest/quickhowto.html#url-api) for all the modelviews. IMO, I think we should leverage this functionality which allows cli and UI uses the same endpoint eventually(cc @mistercrunch ).

**Comment by verdan** [comment]
@feng-tao I believe the API of FAB is still in beta and subject to change in future. Also, most of the DAG's functionality in Airflow is custom written and not actually using the ModelView. That means, you'd need to overwrite most of the base functions of ModelView along with the filters and widgets.

**Comment by feng-tao** [comment]
hey @verdan , I am not aware of BETA for FAB API. But it works pretty well for me. And given airflow api is also experimental, I think they are considered equally readiness.

I am wondering how you use the airflow api stuffs(or how does your deployment looks like)? Are you going to deploy two webservers, one serves UI and another serves api? Consolidate the api into modelView(once FAB becomes default UI) will be better imo. In that case UI, cli, api request could all serve by FAB model CRUD instead of two different places.

**Comment by verdan** [comment]
@feng-tao totally agreed that there should be only one source of truth for all UI, CLI and API. I'll explore the FAB CRUD more, and see if we can convert all of our views to ModelView. 
To answer your question about the usage of airflow apis, I am trying to write REST APIs for all features of Airflow, in an effort to port the frontend (Web UI) in ReactJS (or any other framework, that's still an ongoing discussion), so that our javascript code is more manageable and testable. 
ref: https://issues.apache.org/jira/browse/AIRFLOW-2598

In that setup, I see no use of FAB UI and FAB's CRUD, but just to keep the backward compatibility. thoughts?

**Comment by feng-tao** [comment]
hey @verdan , you mean setup discussed in https://issues.apache.org/jira/browse/AIRFLOW-2598?

**Comment by verdan** [comment]
@feng-tao, yes. I mean that if I use ReactJS with RestAPIs, what’d be the need of FAB’s UI and CRUD in that case

**Pull request closed without merging**
