### PR TITLE
[AIRFLOW-51] Docker cpus -> cpu_shares. 

### PR DESCRIPTION
**Pull request by asnir**
Swarm is not well supported by docker_operator, due to this issue: https://github.com/docker/swarm/issues/475

In order to fix it, we will use cpu_shares instead of cpus.
p.s. The default value is None.

### CODE REVIEW

**Comment by r39132** [comment]
Please create a [Jira](https://issues.apache.org/jira/browse/AIRFLOW) and refer to this PR there. 

Afterwards, you will need to create a few accounts : refer to [Migrating to Apache](https://groups.google.com/forum/#!msg/airbnb_airflow/961jUu-yxR8/5c_WzmgEBAAJ)

**Comment by asnir** [comment]
@r39132 I can't create a Jira issue. 

> Error!
Due Date" field is required and you do not have permission to Schedule Issues for this Service Desk.

**Comment by asnir** [comment]
Solves this issue: [AIRFLOW-51](https://issues.apache.org/jira/browse/AIRFLOW-51)

**Comment by criccomini** [comment]
Can you please squash your commit with this message:

AIRFLOW-51 Rename param Docker cpus -> cpu_shares

**Comment by criccomini** [comment]
What happened? Looks like your squash went bad.

**Comment by asnir** [comment]
I don't know.I have created a new branch. Waiting for CI...

**Comment by criccomini** [comment]
K, LMK when it's ready, and I'll merge

**Comment by asnir** [comment]
https://github.com/apache/incubator-airflow/pull/1467

**Comment by asnir** [comment]
@criccomini It seems like some of the tests are not deterministic.
https://travis-ci.org/apache/incubator-airflow/builds/128141748
https://travis-ci.org/asnir/airflow/builds/128134269

**Pull request closed without merging**
