### PR TITLE
Fix incorrect Azure hook parameter name

### LINKED ISSUE #33025: Problem with Microsoft Azure Provider base_azure hook
### Apache Airflow version

2.6.3

### What happened

When using AzureBaseHook from airflow/providers/microsoft/azure/hooks/base_azure.py with SDKClient class, the get_conn() method fails to instanciate the Client class object.   
  
The error message says, `missing parameter credential`   
  
This is because the sdk_client is being instanciated with `credentials=ServicePrincipalCredentials`
  
Notice an extra `s` in credentials key which is not needed.

### What you think should happen instead

The sdk_client should be instanciated with `credential=ServicePrincipalCredential` which will be instanciated correctly 

### How to reproduce

1. Install any Azure client, let's say azure-monitor-query
`pip install azure-monitor-query`

2. Use the Azure connection with Azure client
```
from airflow.providers.microsoft.azure.hooks.base_azure import AzureBaseHook
from azure.monitor.query import LogsQueryClient

# Lets say we have an azure connection with name Azure_Default

conn = AzureBaseHook(sdk_client = LogsQueryClient, conn_id = 'Azure_Default')
client = conn.get_conn()
``` 
  
This will fail - 

### Operating System

Any

### Versions of Apache Airflow Providers

apache-airflo-providers-microsoft-azure   v6.2.1

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by nathadfield**
closes: #33025

### CODE REVIEW

**Review by pankajkoti — COMMENTED** [review]
Looks like few more tests needs correcting that param, they are failing.

**Comment by nathadfield** [comment]
Hmm.  I can't see what the problem might be be.  @feluelle As the original committer, might you be able to shed some light?

**Comment by potiuk** [comment]
> Maybe you know someone in the community who we can ask regarding this? thinking 

The TODO was added by my because I had no-one to ask :) 

I think the idea is to remove them in the PR and see if anything breaks in tests, ideally get it for a spin with Azure with some example/test dag and see if it works. If it does, good, we should merge those.

**Comment by potiuk** [comment]
FYI: @pankajkoti  I think this is a remnant of the distant past where some of the dependencies were limited to the major upper version "just-in-case" - we've since moved from that, right now we generally only limit something when a) we know upcoming major versio will need some effort to convert to (SQLAlchemy for example, FAB etc.) b) we see that it fails our tests in main.

In both cases the rule we have- described in https://github.com/apache/airflow/blob/main/README.md#approach-to-dependencies-of-airflow  says that whenever we upper-bind a dependency - we need to clearly state why in the comment and ideally link to an issue, which keeps track of this condition being solved (so for example when we limit it because of a bug, we should create the issue describing it and when the issue is solved, we should remove the upper-binding).

This one is clearly from before I introduced the rule and simply needs someone who will take it for a spin and a) get our unit tests pass b) run some smoke tests with Azure.

**Comment by potiuk** [comment]
Maybe we should ask Microsoft team to fix it :D

**Comment by pankajkoti** [comment]
cc: @phanikumv ☝🏽

**Comment by pankajkoti** [comment]
I checked internally, we have kept it in our backlog, but at the moment there are quite a few other priority items and unfortunately, we would have to wait for a while before we can pick this up. 

cc: @potiuk

**Pull request closed without merging**
