### PR TITLE
[AIRFLOW-446] Adds Zenly as an airflow user

### PR DESCRIPTION
**Pull request by cerisier**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-446 - Add Zenly as an Airflow user](https://issues.apache.org/jira/browse/AIRFLOW-446)

Testing Done:
- Non Applicable

Signed-off-by: Corentin Kerisit c@42.am

### CODE REVIEW

**Comment by r39132** [comment]
@cerisier Thanks for your contribution.

See my comments on #1731 and how the submitter corrected it on #1733

In addition to a call for references, we also want to acclimate potential future contributors with the apache commit guidelines. This is required before I can merge your change.

**Comment by r39132** [comment]
For example, though your PR starts with [AIRFLOW-XXX], your commit does not and we need the commit subject line to have [AIRFLOW-XXX] as a preface. This simplifies our generation of release notes.

**Comment by cerisier** [comment]
@r39132 Just fixed the commit title

**Comment by r39132** [comment]
Welcome to the Apache Airflow community!

**Pull request closed without merging**
