### PR TITLE
[AIRFLOW-480] Allow for binary file download from Google Cloud Storage

### PR DESCRIPTION
**Pull request by volkale**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:

https://issues.apache.org/jira/browse/AIRFLOW-480
Per Apache guidelines you need to create a Jira issue.

Testing Done:

This bug fix allowed me to download a gzip file from GCS.

### CODE REVIEW

**Comment by waltherg** [comment]
@criccomini This is a more pythonic version of https://github.com/apache/incubator-airflow/pull/1779

**Comment by waltherg** [comment]
@criccomini @r39132 is this PR okay to merge? Unfortunately the landscape code quality check appears to be hanging indefinitely.

**Comment by r39132** [comment]
+1. @jlowin @criccomini any concern? If not, I will merge. 

@al-xv can you run landscape on your fork and paste a link her on the outcome?

**Comment by criccomini** [comment]
LGTM!

**Pull request closed without merging**
