### PR TITLE
Bump CNCF K8S provider dependency version in Google provider

### PR DESCRIPTION
**Pull request by vatsrahul1001**
[PR #37793](https://github.com/apache/airflow/pull/37793/files#diff-e08f6e1a4ea83e85c60acc015ae9cef3e739ead50bddfd1690cf73addcc468aaR312) introduced `KubernetesDeleteJobOperator` in the latest release 
`8.1.0` of the `cncf-kubernetes` provider, which is also a [dependency](https://github.com/apache/airflow/pull/37793/files#diff-95ed7631b172975c14b35fb4eeefebef992f7a1d1631d47a7222587ed94d8a07R36) 
for the latest release of the `google` provider `10.17.0`. 
This PR bumps the `cncf-kubernetes` provider dependency version 
to a minimum of `8.1.0` for the `google` provider.

It appears that `google` provider `10.17.0` won't together with 
`cncf-kubernetes` provider `<8.1.0`. So we would also need to 
discuss what could be done for the released google provider.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vatsrahul1001** [comment]
When GCP 10.17.0 is started with CNCF K8s provider less than 8.1.0
image

**Review by potiuk — APPROVED** [review]

**Review by pankajkoti — DISMISSED** [review]

**Comment by pankajkoti** [comment]
> It appears that google provider 10.17.0 won't together with
cncf-kubernetes provider <8.1.0. So we would also need to
discuss what could be done for the released google provider.

@eladkal looks like 10.17.0 of the Google provider won't work
with cncf-k8s provider <8.1.0. Do we need to take some care
for the released version of Google provider?

**Comment by potiuk** [comment]
> @eladkal looks like 10.17.0 of the Google provider won't work
with cncf-k8s provider <8.1.0. Do we need to take some care
for the released version of Google provider?

@pankajkoti with your question. Now when you are mentioning it - and since it is only one provider -  probably a better approach is to try/catch the specific import error and raise `AirflowOptionalProviderFeatureException` with explanation that you need to use cncf.kubernetes >=8.1.0 for that one. This is likely better way  to handle this than to add whole provider's dependency.

**Review by potiuk — CHANGES_REQUESTED** [review]
As explained in the comment since this is one Operator only - better way is to turn the import error into `OptionalProviderFeature` with explanation that 8.1.0 of cncf.kubernetes is needed for that

**Comment by eladkal** [comment]
> > @eladkal looks like 10.17.0 of the Google provider won't work
> > with cncf-k8s provider <8.1.0. Do we need to take some care
> > for the released version of Google provider?
> 
> @pankajkoti with your question. Now when you are mentioning it - and since it is only one provider - probably a better approach is to try/catch the specific import error and raise `AirflowOptionalProviderFeatureException` with explanation that you need to use cncf.kubernetes >=8.1.0 for that one. This is likely better way to handle this than to add whole provider's dependency.

Yes I also wanted to raise this. We should use `AirflowOptionalProviderFeatureException` here

**Comment by vatsrahul1001** [comment]
closing in favour of https://github.com/apache/airflow/pull/39036

**Pull request closed without merging**
