### PR TITLE
Fix typo docs - dataset guide

### PR DESCRIPTION
**Pull request by TJaniF**
Just a one character docs typo fix :) 

EDIT: and a missing period.

### CODE REVIEW

**Comment by TJaniF** [comment]
Just learned main is Airflow 3 now, will make a new PR for 3 before my gitting becomes even more embarrassing 👀 apologies to those who got pinged!

**Comment by ephraimbuddy** [comment]
> Just learned main is Airflow 3 now, will make a new PR for this before my gitting becomes even more embarrassing 👀 apologies to those who got pinged!

We can still backport fixes to Airflow v2-10-stable. A fix like this one can be backported, so it's not wrong to PR against main

**Comment by TJaniF** [comment]
Oh, thats good to know thank you! I wasn't sure how to not have all the other commits in here so now I branched off v2-10-stable and re-PRed :)

**Comment by TJaniF** [comment]
@jedcunningham The same docs PR against main as requested :)

**Comment by eladkal** [comment]
Seems the same as https://github.com/apache/airflow/pull/41361 ?

**Comment by TJaniF** [comment]
Yes, @eladkal I did not see that @shahar1 had already taken care of it before reopening this, apologies. Will close for good now :)

**Pull request closed without merging**
