### PR TITLE
[AIRFLOW-5792] Straighten out the migrations

### PR DESCRIPTION
**Pull request by Fokko**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-5792\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5792
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by kaxil** [comment]
Will these somehow affect/corrupt upgrades as the users would already have applied these 2 migrations?

**Comment by kaxil** [comment]
ping @Fokko

**Comment by potiuk** [comment]
Not sure what was the last agreement we had @fokko ? was I supposed to do this or did we agree you do it :) ? Just got some busy week last week :)

**Comment by potiuk** [comment]
@Fokko :)?

**Comment by Fokko** [comment]
Sorry for the late response, I'm extremely busy right now.

Right now there are three heads on v1-10-stable:
```
MacBook-Pro-van-Fokko:incubator-airflow fokkodriesprong$ cd airflow/
MacBook-Pro-van-Fokko:airflow fokkodriesprong$ alembic heads
/Users/fokkodriesprong/Desktop/incubator-airflow/airflow/configuration.py:226: FutureWarning: The task_runner setting in [core] has the old default value of 'BashTaskRunner'. This value has been changed to 'StandardTaskRunner' in the running config, but please update your config before Apache Airflow 2.0.
  FutureWarning
/Users/fokkodriesprong/Desktop/incubator-airflow/airflow/configuration.py:612: DeprecationWarning: Specifying airflow_home in the config file is deprecated. As you have left it at the default value you should remove the setting from your airflow.cfg and suffer no change in behaviour.
  category=DeprecationWarning,
/Users/fokkodriesprong/Desktop/incubator-airflow/airflow/config_templates/airflow_local_settings.py:65: DeprecationWarning: The elasticsearch_host option in [elasticsearch] has been renamed to host - the old setting has been used, but please update your config.
  ELASTICSEARCH_HOST = conf.get('elasticsearch', 'HOST')
/Users/fokkodriesprong/Desktop/incubator-airflow/airflow/config_templates/airflow_local_settings.py:67: DeprecationWarning: The elasticsearch_log_id_template option in [elasticsearch] has been renamed to log_id_template - the old setting has been used, but please update your config.
  ELASTICSEARCH_LOG_ID_TEMPLATE = conf.get('elasticsearch', 'LOG_ID_TEMPLATE')
/Users/fokkodriesprong/Desktop/incubator-airflow/airflow/config_templates/airflow_local_settings.py:69: DeprecationWarning: The elasticsearch_end_of_log_mark option in [elasticsearch] has been renamed to end_of_log_mark - the old setting has been used, but please update your config.
  ELASTICSEARCH_END_OF_LOG_MARK = conf.get('elasticsearch', 'END_OF_LOG_MARK')
a56c9515abdc (head)
004c1210f153 (head)
74effc47d867 (head)
```
The easiest way is to just merge them: `alembic merge a56c9515abdc 004c1210f153 74effc47d867`

**Comment by Fokko** [comment]
If we want to do this the clean way, then we have to figure out if the heads are already part of a release. If not, then remove the branches in the migration scripts.

**Comment by kaxil** [comment]
Thanks @Fokko

**Pull request merged**
