### PR TITLE
[AIRFLOW-397] Fix typo in docs: change instances of "instatiated" to "instantiated"

### PR DESCRIPTION
**Pull request by jalessio**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-397](https://issues.apache.org/jira/browse/AIRFLOW-397)

### CODE REVIEW

**Comment by r39132** [comment]
👍

**Comment by r39132** [comment]
@jalessio Even for small PRs such as these, for the purposes of generating nice release notes, we require you to follow the guidelines on https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

**Comment by r39132** [comment]
👍

**Comment by jalessio** [comment]
@r39132 Ah, I was hoping to skirt the formalities for such a small change but I think everything is in place per the contributing guidelines now. Thanks.

**Pull request merged**
