### PR TITLE
[AIRFLOW-926] Fix & Improve JDBC Hook + Update jaydebapi to 1.0.0

### PR DESCRIPTION
**Pull request by r-richmond**
Please accept this PR that addresses the following issues:
https://issues.apache.org/jira/browse/AIRFLOW-926

which are required because of an api change for [jaydebeapi](https://github.com/baztian/jaydebeapi/commit/2640445de036def2169514aa56e5ad9ced246b16#diff-a51683c99849d299a6cb9e6c4bcec328R349)

Testing Done:
Tested on local machine
screenshots of before and after incoming

### CODE REVIEW

**Comment by r-richmond** [comment]
Actually after making a new virtual-env to test; my jdbc connections no longer appear in the adhoc query selector so it appears i've missed something. Although I'm not sure what.

*edit was running airflow from the wrong virtual env... anyways screen shots below.

Note: after the change Teradata still won't run because of the way airflow currently limits sql. It has a generic else clause that uses limit which Teradata doesn't support. A quick glance of the [code](https://github.com/apache/incubator-airflow/blob/master/airflow/www/utils.py#L65) looks like it uses the connection type to edit the limit clause but since i'm using JDBC there isn't a quick fix. Any guidance here on a preferred approached would be very appreciated.
Potential fixes
1) extra connection config keyword that can replace limit with x (sample in teradata's case)
2) check connection id/name for teradata and then replace limit with sample

**Pre Change**
pre-change

**Post Change**
post-change
**Connection Settings**
connection-settings

**Comment by r-richmond** [comment]
Ok so I went through and added what I felt was a fairly generic keyword handler for teradata jdbc connections and in case other jdbc connections have different limit keywords. (for example. if you want to use an oracle jdbc connection you could change this to `where rownum <= ` )

**Comment by r-richmond** [comment]
**Teradata Working**
working
**New JDBC Connection UI**
connection_ui
**Connection UI of an unrelated connection** (mostly to show its unchanged)
connection_ui_mysql

**Comment by r-richmond** [comment]
Not sure why the CI build is falling as it looks like the test that is failing is unrelated to my change.

```
FAIL: test_overwrite_schema (tests.PostgresTest)
```

also i just get a 500 error when trying to view the code-quality

**Comment by bolkedebruin** [comment]
Can you rebase & retrigger the build so we can verify if it is ok?

**Comment by r-richmond** [comment]
@bolkedebruin rebased and build looks to be running now. Let me know if you need anything else.

**Comment by r-richmond** [comment]
So looking at the failure logs I see various errors with google big query nothing that I've made changes to. In fact i think those might be fixed with https://github.com/apache/incubator-airflow/commit/3e9c666e8e5643bb8d38fbc8bdb1ed8dee182ab2

11) FAIL: test_throws_exception_with_incompatible_syntax (tests.contrib.hooks.test_bigquery_hook.TestBigQueryDataframeResults)

12) FAIL: test_throws_exception_with_invalid_query (tests.contrib.hooks.test_bigquery_hook.TestBigQueryDataframeResults)

@bolkedebruin Is there something else you are looking for before merging?

**Pull request closed without merging**
