### PR TITLE
[AIRFLOW-4236] Add num_retries to MySqlToGoogleCloudStorageOperator

### PR DESCRIPTION
**Pull request by ryanyuan**
Add num_retries to MySqlToGoogleCloudStorageOperator

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow-4236](https://issues.apache.org/jira/browse/AIRFLOW-4236) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by OmerJog** [comment]
Thanks for picking this up.
The ticket mentions that this is an issue with other operators as well (though not mention it specifically)
```
CassandraToGoogleCloudStorageOperator
PostgresToGoogleCloudStorageOperator
S3ToGoogleCloudStorageOperator
AdlsToGoogleCloudStorageOperator
```
are also don't allow to set the `num_retries `of the upload method in the `GoogleCloudStorageHook`

Can you you address them as well? If not, it's better to link this PR to a new Jira ticket which will be a sub-task of https://issues.apache.org/jira/browse/AIRFLOW-4236

**Comment by kaxil** [comment]
Better to address similar issues in one PR then to split it across many

**Comment by ryanyuan** [comment]
@OmerJog Cool. I will get it done.

**Comment by mik-laj** [comment]
Other operators have a fixed number of retry attempts. 
https://github.com/apache/airflow/blob/e27950a75ce287c094e550fba07d1c8de5dc4143/airflow/contrib/hooks/gcp_transfer_hook.py#L92
https://github.com/apache/airflow/blob/383ec374ea148d04af94496dc9e3283263d67d5f/airflow/contrib/hooks/gcp_function_hook.py#L29
https://github.com/apache/airflow/blob/993779f93df172f5f774f1ea2634c55e9c1212c4/airflow/contrib/hooks/gcp_compute_hook.py#L28
https://github.com/apache/airflow/blob/49ade3834a46d9a12c0339a017d1807bf021c5e3/airflow/contrib/hooks/gcp_sql_hook.py#L54
https://github.com/apache/airflow/blob/85ea7e8575bb0f9a2fac989f26970809b36640a4/airflow/contrib/hooks/gcp_dataflow_hook.py#L51
I'm afraid it's a good idea to give the user the option to configure this parameter in this way. Too many parameters will make it difficult to use the operator. In my opinion, this value should be configured in the connection settings instead of the specific use, but fixed value is good enough in this case.

I working on similar mechanism for Google Cloud AI operators: https://github.com/PolideaInternal/airflow/pull/85/files 
I want to support retrying in reaction to exceeding the temporary quota. I would like the use of all GCP operators to be similar, so it is important for me to elaborate one variant.

CC: @potiuk

**Comment by ryanyuan** [comment]
@kaxil Any opinions on what @mik-laj suggested above?

**Comment by ashb** [comment]
This parameter is confusingly similar to BaseOperator.retries parameter.

If we were go have this paramater the docs would need to be much clearer about what is "internal" to one task attempt compared to number of attempts, without changing the name on BaseOperator.

**Comment by kaxil** [comment]
I agree with @mik-laj . It would be ideal to have a uniform number across all the operators. We can have a MAX retries in connection, a default value in hooks, and can be overriden in operator. Keep in mind that we also have a retry for all airflow operators as well so that we don't conflict.

**Comment by ashb** [comment]
Another example of "internal" retries https://github.com/apache/airflow/blob/fc3b45a61ac51441c3b9e4d99a20473cd3664056/airflow/contrib/hooks/aws_athena_hook.py#L109

**Comment by OmerJog** [comment]
I think having a default value in connection is a good approach.

**Comment by OmerJog** [comment]
@kaxil your PR has removed the num_retries:
https://github.com/apache/airflow/pull/5054
You specified that the new library handle the multipart by it's own but you didn't mention what will be with the num_retries

**Comment by kaxil** [comment]
@OmerJog Sorry, I should have included it in the Uploading.md

> Upload requests will be automatically retried.

From https://github.com/googleapis/google-cloud-python/blob/master/storage/google/cloud/storage/blob.py#L87 :
```
"`num_retries` has been deprecated and will be removed in a future "
    "release. The default behavior (when `num_retries` is not specified) when "
    "a transient error (e.g. 429 Too Many Requests or 500 Internal Server "
    "Error) occurs will be as follows: upload requests will be automatically "
    "retried. Subsequent retries will be sent after waiting 1, 2, 4, 8, etc. "
    "seconds (exponential backoff) until 10 minutes of wait time have "
    "elapsed. At that point, there will be no more attempts to retry."
```

**Comment by OmerJog** [comment]
@kaxil  thx. So it sounds like this PR is no longer needed. The new fix in your PR solves the problem.

**Comment by ryanyuan** [comment]
@OmerJog Yes, I will close this PR and create another PR to let the user set a default number of request retries in GCP connection.

**Pull request closed without merging**
