### PR TITLE
Fix: re-enable use of parameters in gcs_to_bq which had been disabled

### LINKED ISSUE #27842: GCSToBigQueryOperator no longer uses field_delimiter or time_partitioning
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

google=8.5.0

### Apache Airflow version

2.4.3

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### What happened

The newest version of the google providers no longer provides the `field_delimiter` or `time_partitioning` fields to the bq job configuration for the GCStoBQ transfers. Looking at the code it seems like this behavior was removed during the change to use deferrable operations

### What you think should happen instead

These fields should continue to be provided

### How to reproduce

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by mdering**
closes #27842 
---
Add in some missing configuration options to the gcs to bq transfer operator. the 8.5.0 release broke a number of things with this operator, mainly the methods to specify the file delimiter, and the time partitioning option.

### CODE REVIEW

**Comment by uranusjr** [comment]
CI is failing.

**Comment by mdering** [comment]
@uranusjr I see why, can you approve it to rerun tests?

**Comment by mdering** [comment]
Is there something you need from me to rerun this?

**Comment by eladkal** [comment]
> Is there something you need from me to rerun this?

Can you please add unit test to avoid regression?

**Comment by mdering** [comment]
@eladkal yes, I added some tests, and fixed the existing tests

**Comment by mdering** [comment]
since this passed CI and has unit tests, is there anything else I need to do to get this merged?

**Review by potiuk — APPROVED** [review]
Cool.

**Pull request merged**
