### PR TITLE
Who uses Airflow - Cinimex DataLab

### PR DESCRIPTION
**Pull request by kdubovikov**
@githubhandle

Added our company to the list

### CODE REVIEW

**Comment by feng-tao** [comment]
I think the list is sorted alphabetically. Could you put your company in the correct place? Thanks.

**Comment by r39132** [comment]
Can you rebase and squash your commits? Also, please put it in alphabetic order!

**Comment by Fokko** [comment]
Please remove the other changes, other than the company name. Cheers!

**Comment by r39132** [comment]
I fixed this in https://github.com/apache/incubator-airflow/pull/3198 -- closing this PR

**Comment by r39132** [comment]
Closing this PR!

**Pull request closed without merging**
