### PR TITLE
Update config.yml [logging][celery_stdout_stderr_separation]

### PR DESCRIPTION
**Pull request by apilaskowski**
This setting is part of 2.7.0 milestone.

### CODE REVIEW

**Comment by apilaskowski** [comment]
@potiuk Am I right, that this will be introduced in 2.7.0?

**Comment by apilaskowski** [comment]
@potiuk @mhenc @kosteev 
Should we update it, or will it be updated on it's own with release  of 2.7.0?

**Comment by apilaskowski** [comment]
Should I close this PR, if it will be handled differently, or should I just wait with that? @potiuk

**Review by jedcunningham — APPROVED** [review]

**Comment by apilaskowski** [comment]
Done.

**Pull request closed without merging**
