### PR TITLE
Adding support for Kubernetes package version 31.0.0

### PR DESCRIPTION
**Pull request by dirrao**
Adding support for Kubernetes package version 31.0.0

### CODE REVIEW

**Comment by potiuk** [comment]
Mypy check fixed in main. Merging.

**Review by potiuk — CHANGES_REQUESTED** [review]
Well. Actually - not really. 31.0.0 is the latest version and we do not use any features from it. It's a bit dangerous to bump lower binding of a dependency - especially if what's left is just one current version - because it will force update to that version even if som eone would like to keep previous one (for example for comopatibility reasons or because there is a bug found in the latest version). 

Our constraints are automatically updated to latest version - and `pip` or `uv` will generally use latest available version by default, so any new installations or "reproducible" airflow upgrades using constraints will use the latest version by default but the user will still have a chance of downgrading it in case of a bug or incompatibility.

We currently have "lowest-direct" CI job - it will check if we are using any of the new features when running tests - so it should automatically detect cases when we should bump the "lower-bounded" libraries, and with that, I think we should generally only bump the lower bounds when it fails (or when the developer bumped lower binding because they **know** that they are using some newer features.

**Comment by potiuk** [comment]
So I guess @dirrao we should close this one.

**Comment by dirrao** [comment]
> So I guess @dirrao we should close this one.

The title is mis leading. I have updated it. This PR will add the support for Kubernetes package version 31.0.0 without changing existing min version support.

**Comment by dirrao** [comment]
> Mypy check fixed in main. Merging.

Yah. Checks are braking after PR merge #42539

**Comment by potiuk** [comment]
> > Mypy check fixed in main. Merging.
> 
> Yah. Checks are braking after PR merge #42539

They are actually breaking after new release of microsoft's kioto package few hours ago. but yes - that's it.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> The title is mis leading. I have updated it. This PR will add the support for Kubernetes package version 31.0.0 without changing existing min version support.

Right. Stupid me 🤯 - > but you mislead me with the title so 1:1 😄

**Pull request merged**
