### PR TITLE
fix to inconsistent task instance state log message

### PR DESCRIPTION
**Pull request by mchalek**
Dear Airflow maintainers,

This is a trivial fix to an incorrectly-formatted log message that we have been seeing in our logs.  Please accept it without the usual JIRA + tests + etc due to its triviality.

Kevin

### CODE REVIEW

**Comment by Fokko** [comment]
Hi @mchalek, thank you for your contribution. Would it be possible to change it the other way around. We started moving to the `%s` format recently. Cheers

**Comment by mchalek** [comment]
hi @Fokko  sure, I'll change it now.  But, well not that it's my business, but isn't switching to `%s` kind of taking a step backwards?  The python docs recommend `.format()` for new code: https://docs.python.org/2/library/stdtypes.html#str.format

I suspect the reasoning could be for compatibility with the log formatter that airflow is using?

**Comment by bolkedebruin** [comment]
@mchalek it doesn't say that. It says it is preferred for formatting strings (and thus not logging per se). However, if you want to use lazy logging you need to use `%`


Strike that. @Fokko please reconsider, this is string formatting not logging. .format should be used here imho.

**Comment by mchalek** [comment]
hi @bolkedebruin thanks for clarifying.  It's too bad that the logger class does not support the new-style of formatting.

**Comment by ron819** [comment]
Is this still needed?

**Comment by mchalek** [comment]
@ron819 it looks like someone else fixed it.  i will close this PR.

**Pull request closed without merging**
