### PR TITLE
Do not create redis secrets for kubernetes executors

### LINKED ISSUE #30420: Chart should not create Redis secrets while using the KubernetesExecutor
### Official Helm Chart version

1.8.0 (latest released)

### Apache Airflow version

2.5.1

### Kubernetes Version

1.21.14

### Helm Chart configuration

```yaml
# values.yaml

executor: "KubernetesExecutor"
```

### Docker Image customizations

None.

### What happened

The [redis secrets](https://github.com/apache/airflow/blob/2.5.1/chart/templates/secrets/redis-secrets.yaml) got created

### What you think should happen instead

Given all the resources defined in [./chart/templates/redis](https://github.com/apache/airflow/tree/2.5.1/chart/templates/redis) contain the below condition, it does not seem right to me to get Redis secrets created in the context of the `KubernetesExecutor`. 

```go
{{- if and .Values.redis.enabled (or (eq .Values.executor "CeleryExecutor") (eq .Values.executor "CeleryKubernetesExecutor")) }}
```

Redis secrets might have been missed when this condition was added, because they are located in a different folder?

### How to reproduce

Render helm templates
```sh
helm template test apache-airflow/airflow --version 1.8.0 --values values.yaml > rendered.yaml
```

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
Create the redis secrets only for Celery based executors and not for Kubernetes executor. This is to stay consistent with other redis elements in airflow helm charts.

closes: https://github.com/apache/airflow/issues/30420
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by hussein-awala** [comment]
Could you check [this comment](https://github.com/apache/airflow/pull/30423#issuecomment-1500781210)?

**Comment by amoghrajesh** [comment]
@jedcunningham looping you in for some comment https://github.com/apache/airflow/pull/30423#issuecomment-1500781210. Will these changes be breaking the point that you made in your comment?

**Comment by amoghrajesh** [comment]
@hussein-awala @jedcunningham following up for a review on this PR. See above comments for context

**Comment by jedcunningham** [comment]
Yes, my comment is still valid. I sorta think we should close that issue as "expected".

I think there are ways we could work around this, but simply adding the conditional for the executor type isn't a good path forward.

**Comment by amoghrajesh** [comment]
Thanks Jed, I think it makes sense. I will close this issue as expected behaviour.

**Pull request closed without merging**
