### PR TITLE
[AIRFLOW-6602]: render executor_config before triggering tasks to su…

### PR DESCRIPTION
**Pull request by TomatoEgg**
…pport dynamic parameters for kubernetes executor

For kubernetes executor, it will create a Pod based on executor_config before rendering the
template fields & running the task, therefore it won't work if a custom ioperator defines executor_config
as template field. It also requires the change in airflow to render it before the task is
triggered

---
Issue link: [AIRFLOW-6602](https://issues.apache.org/jira/browse/AIRFLOW-6602)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by turbaszek** [comment]
Travis is sad, can you fix pylint errors?

**Comment by TomatoEgg** [comment]
@nuclearpinguin : sure, but I would need to discuss what I observed in my manual testing of this feature. Who is the best person to talk to? and how do you normally carry out such discussions? (This is my first PR so please bear with me those basic questions)

**Comment by turbaszek** [comment]
> @nuclearpinguin : sure, but I would need to discuss what I observed in my manual testing of this feature. Who is the best person to talk to? and how do you normally carry out such discussions? (This is my first PR so please bear with me those basic questions)

We already have this PR so it is a good place to start a discussion. When there's no PR or the problem requires some more discussion (for example introduction of "fundamental" changes) we can use our devlist or #development on our slack:

> In case of doubts contact the developers at:
Mailing List: dev@airflow.apache.org
Slack: https://apache-airflow-slack.herokuapp.com/

I am not sure what means "this feature" but in case it means Breeze / pre-commits, I summon @potiuk

**Comment by mik-laj** [comment]
I invite you to the channel #airflow-kubernetes on Slack.

**Comment by TomatoEgg** [comment]
@nuclearpinguin : basically I found out in my test that the following happens when I triggered a DAG with executor_config is templated (say {{ ds }} as value for a key):
1. scheduler_job._enqueue_task_instances_with_queued_state is called which invokes
```
self.executor.queue_command(
                simple_task_instance,
                command,
                priority=priority,
                queue=queue)
```
2. base_executor.queue_command() is called
```
self.queued_tasks[simple_task_instance.key] = (command, priority, queue, simple_task_instance)
```

In the above two steps, simple_task_instance is of type SimpleTaskInstance, which means that it doesn't have enough information to render the templates. If it is TaskInstance instead, we could render the executor_config in those places.

What makes this a bit more confusing is that the test case called 'test_enqueue_task_instances_with_queued_state' in test_scheduler_job.py, it is using TaskInstance as test data instead of SimpleTaskInstance.

So my question is
1) What data type is the correct one?
2) is there an integration test case that we could run to see the truth?

**Comment by neverset123** [comment]
what's status of this PR, why this PR is not merged, could anyone explain?

**Comment by mik-laj** [comment]
@neverset123 There was no reviewer who was mobilized to push these changes forward, and the author did not do it hard enough. The maintainers of this project have very little time to deal with each change and are counting on the authors of the changes to be mobilized and will ask for reviews if the change is ready for review.

> Ping @ #development slack, comment @people. Be annoying. Be considerate.

https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow

I also have doubts if this change works correctly with DAG Serialization and if it does not have too much impact on performance, because this code is executed in the main scheduler loop. If this code didn't modify the main loop, it would be a lot easier to merge this change.

**Comment by BayanAzima** [comment]
I'd like to see this feature as I'd like to template out a `sub_path` of a PV I have so that i don't expose other dag run data I store there to other dag runs. see the example below

I notice that this issue is pretty old, was this added in v2 or is there another way I can do this now? 

``` 

KUBERNETES_WORKSPACE_PVC = {
    "pod_override": k8s.V1Pod(
        spec=k8s.V1PodSpec(
            containers=[
                k8s.V1Container(
                    name="base",
                    volume_mounts=[
                        k8s.V1VolumeMount(
                            name=Constants.KUBERNETES_WORKSPACE_PVC,
                            mount_path='/opt/airflow/mnt/workspace', 
                            # sub_path="{{ ti.xcom_pull(key='run_group_id')}}", 
                            read_only=False
                        )
                    ],
                )
            ],
            volumes=[
                k8s.V1Volume(
                    name=Constants.KUBERNETES_WORKSPACE_PVC,
                    persistent_volume_claim=k8s.V1PersistentVolumeClaimVolumeSource(claim_name=Constants.KUBERNETE_WORKSPACE_PVC)
                )
            ],
        )
    ),
}

**Pull request closed without merging**
