### PR TITLE
Adding REA Group to list of users.

### PR DESCRIPTION
**Pull request by wjlow**
We are using Airflow in a few of the data engineering teams.

### CODE REVIEW

**Comment by kaxil** [comment]
@wjlow The list is alphabetically ordered. Can you please amend the commit to that convention?

**Comment by r39132** [comment]
Closing for inactivity. Reopen once fixed.

**Comment by r39132** [comment]
@wjlow I added the company entry in https://github.com/apache/incubator-airflow/commit/7bdf6162fb1f86fcbd970d242800f1d4ae2f1d45 If you'd like to reopen the PR and add your user id to the list, please do so. One of use will merge the change.

**Comment by wjlow** [comment]
@r39132 Thanks for doing that, so sorry for the inactivity before.

**Pull request closed without merging**
