### PR TITLE
Add Slack operators how-to guide

### PR DESCRIPTION
**Pull request by kevin1kevin1k**
- Solve #11919 
- Generate a how-to guide for Slack operators (currently only SlackAPIFileOperator; could add SlackAPIPostOperator later)
- Fix and unify the code sample in API page

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Looks good. Let me close and reopen to rebuild

**Comment by potiuk** [comment]
Would be cool to have 4 PRS merged after the workshops !

**Comment by kevin1kevin1k** [comment]
Thanks again, really enjoyed the sprint today!

**Comment by potiuk** [comment]
Cool - one thing to fix - we are building an inventory of howto guides so you need to add it to ariflow/providers/slack/provider.yaml (see other providers for an example).

**Comment by kevin1kevin1k** [comment]
No problem, hopefully the new commit would fix that :)

**Comment by potiuk** [comment]
Cool @kevin1kevin1k ! Thanks for the participation in the workshop!

**Pull request merged**
