### PR TITLE
[AIRFLOW-4598] Task retries are not exhausted for K8s executor

### PR DESCRIPTION
**Pull request by andy-g14**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [AIRFLOW-4598](https://issues.apache.org/jira/browse/AIRFLOW-4598)
 issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

When using K8s executor, If a task pod terminates with non zero code, the task is marked as failed, even though its retry count is not exhausted. The section of code I am removing is responsible for marking the task as failed. Adding the (task,state) to event_buffer should take care of retrying in the _process_executor_events method in the Scheduler.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by andy-g14** [comment]
@dimberman

**Comment by dimberman** [comment]
I'm a bit confused by this.

It looks like you're taking out the code that marks tasks as failed, but I'm not seeing where the failures are marked if this is taken out.

Also could you please write one or two unit tests for this to prevent this issue in the future?

**Comment by andy-g14** [comment]
@dimberman The section of code I have removed is marking task as failed if there is a "Failed" event from the WatcherJob, without checking eligibility for retries. 
For your question, the tasks would be marked failed here https://github.com/apache/airflow/blob/e8c5c7a3d83e5bf506cd12ee8d0d4eb3e4436025/airflow/jobs/scheduler_job.py#L1256, in the _process_executor_events  method based on whether retries have been exhausted or not, if they are in QUEUED state. And the tasks for which the watcher got a "Failed" event and were in running state would be collected as zombies.

**Comment by dimberman** [comment]
@andy-g14 thank you for adding the tests + the explanation. This looks great. Merging now :).

**Review by dimberman — APPROVED** [review]

**Comment by ashb** [comment]
We should pull this in to 1.10.4 right?

**Pull request merged**
