### PR TITLE
Persist DataprocLink for workflow operators regardless of job status

### LINKED ISSUE #26987: DataprocLink is not available for dataproc workflow operators
### Apache Airflow version

main (development)

### What happened

For DataprocInstantiateInlineWorkflowTemplateOperator and DataprocInstantiateWorkflowTemplateOperator, the dataproc link is available only for the jobs that have succeeded. Incase of Failure, the DataprocLink is not available

### What you think should happen instead

Like other dataproc operators, this should be available for workflow operators as well

### How to reproduce

_No response_

### Operating System

MacOS Monterey

### Versions of Apache Airflow Providers

apache-airflow-providers-google==6.5.0

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by vksunilk**
Fixes https://github.com/apache/airflow/issues/26987

For DataprocInstantiateInlineWorkflowTemplateOperator and DataprocInstantiateWorkflowTemplateOperator, the dataproc link is available only for the jobs that have succeeded. Incase of Failure, the DataprocLink is not available

Also, As we have moved from LOCATION to REGION in dataproc, have renamed the constant in test file to GCP_REGION

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
Would it be possible to add a test for this?

**Comment by vksunilk** [comment]
> Would it be possible to add a test for this?
@uranusjr Sure. Have added tests now

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
statuic checks failing.

**Comment by vksunilk** [comment]
> statuic checks failing.

It has passed now @potiuk

**Comment by potiuk** [comment]
Nope :( .Static checks are failing. I recommend you to install pre-commit . It will correct the errors for you automatically.

**Comment by vksunilk** [comment]
> Nope :( .Static checks are failing. I recommend you to install pre-commit . It will correct the errors for you automatically.

Done now. Precommit helped!

**Comment by potiuk** [comment]
> Done now. Precommit helped!

Let's see. You are a new user, so I still needed to approve the workflow run from you to run tests.

**Comment by potiuk** [comment]
Anyone from GCP team wants to comment @bjankie1 ? others ?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
