### PR TITLE
[AIRFLOW-2615] Remove not used app creation

### PR DESCRIPTION
**Pull request by KevinYang21**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Removing not used app creation, reduce the start up time webserver needed to almost half :)

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Manual test should be enough.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by KevinYang21** [comment]
@jgao54 @saguziel PTAL.

**Comment by Fokko** [comment]
@jgao54 Do you know what the implications are of removing this?

https://github.com/yrqls21/incubator-airflow/commit/05e1861e24de42f9a2c649cd93041c5c744504e1

**Comment by KevinYang21** [comment]
ping :D

**Comment by feng-tao** [comment]
I think we need this line. Especially for DAG ACL(https://github.com/apache/incubator-airflow/pull/3197) to auto resync permissions during webserver startup. cc @jgao54

**Comment by KevinYang21** [comment]
@feng-tao are you referring to [this line](https://github.com/apache/incubator-airflow/pull/3197/files#diff-5aeaca39c3e310ff9883f8ac4d506d1dR141) syncing roles? From my limited understanding of front end stuff, the apps actually serving traffic live in [the gunicron workers](https://github.com/apache/incubator-airflow/blob/master/airflow/bin/cli.py#L882). After the subprocess are created, [cached_app() will be called to create one app per subprocess](https://github.com/apache/incubator-airflow/blob/master/airflow/bin/cli.py#L832). Since security_manager.sync_roles() lives in create_app(), we should be able to resync the roles/perms everytime we restart the subprocess( not the webserver). Meanwhile, [the workers will be restarted every web_server_worker_timeout](https://github.com/apache/incubator-airflow/blob/master/airflow/bin/cli.py#L812), thus we can refresh both DagBag and roles/perms w/o restarting the master webserver process.

If what I stated is just misunderstanding, I would still strongly suggest we find a way to remove this line--either extract only the needed logic or start the subprocess earlier or something like that. The current approach scales very bad and does not make any sense to me( we're waiting for 2 complete app constructions including 2 single process DagBag parsing before the webserver can serve traffic, at least with the current scale of Airbnb means ~28mins to start a webserver--for around 2k DAG files including some complicated framework DAG files).

**Comment by feng-tao** [comment]
hey @yrqls21 , thanks for the info. Let me do some test with your change on my pr and get back to you.

**Comment by feng-tao** [comment]
but @yrqls21 , regarding to your startup time issue, why not increase numbers of dagbag processes config (``#max_threads`` )from default 2 to a larger value if that's dagbag loading is taking long time if I understand your issue correctly? At lyft, we found that it significantly improves the performance for dagbag loading time. I create an entry before in faq(https://github.com/apache/incubator-airflow/blob/master/docs/faq.rst).  And I am curious how do you pinpoint the issue is due to that line causes the startup issue, and how much startup time gets reduced by removing that line at Airbnb.

**Comment by KevinYang21** [comment]
@feng-tao I do not understand why does a scheduler config have to do with webserver start up time. [Webserver load dagbag in a single thread fashion](https://github.com/apache/incubator-airflow/blob/master/airflow/www/views.py#L101) as I stated in my previous comment.

You are perfectly correct that increasing # of dag file processor would help speeding up DAG file parsing. Airbnb recently bumped that up from 64 to 128 and observed improvements. However we have some limitations:

- from experimentation, on the AWS EC2 i3.16xlarge host, 256 DAG file processor would cause `Too many open files` errors( while OS limit is millions, not sure about the root cause, suspecting file handler not closed properly) and it can be limited by the computer power of the scheduler host/container.
- scheduler loop speed would be the bottleneck when we have limited # of DAG file processors, especially when we have large # of DAG files--I'll be sending out several PRs over the next quarter to scale up the scheduler.

**Comment by jgao54** [comment]
I agree with @yrqls21 and think we should be able to remove this line. When I first added RBAC I added the app construction here to follow the same pattern as old UI. But looking at it again now it doesn't seem to serve any purpose. My hypothesis is that this was here for legacy reason since we used to start the app with app.run instead of gunicorn

**Comment by feng-tao** [comment]
thanks @yrqls21  and @jgao54 . I test on my pr which removing the line works fine. Sorry about the false alarm.

**Review by jgao54 — APPROVED** [review]

**Comment by jgao54** [comment]
@feng-tao  @yrqls21  Sorry I was wrong. It looks like gunicorn and FAB aren't cohabiting very well.

I cleared the db in my local airflow with RBAC enabled. When rerunning `airflow webserver`, it is now throwing many IntegrityError while trying to instantiate the appbuilder (FAB eagerly populates missing rows in its rbac-related tables when it is instantiated). My suspicion is that when we had the extra app creation line, app and appbuilder were created once and cached, so when gunicorn spun up each worker it just used the cached object; now that we removed the line, each worker attempts to populate the same set of rows and it's causing a race condition (which resulted in bad rows generated in `ab_permission_view` and `ab_permission_view_role`). 

Let me know if you can replicate this issue.I think the right thing to do is to revert the change, fix the race condition if possible, and then come back to address the double app creation issue.

**Comment by KevinYang21** [comment]
@jgao54 I think we should definitely revert this PR.

Since gunicorn spins up actual unix process, the app and appbuilder objects won't be shared. But I agree with your theory that FAB won't work well when starting two apps at the same time( set gunicorn worker # to 1 would stop the error). The least we can do is to limit the change to only legacy UI. I'll allocate sometime next week or later to dive into the race condition issue.

Apologize for missing the RBAC with fresh db test part and thank you for spotting it.

**Comment by feng-tao** [comment]
Hey @jgao54, I didn't clear my db though. I could do that this weekend and see if I reproduce your issue.

**Comment by jgao54** [comment]
@feng-tao @yrqls21 that makes sense, not much to do with objects getting cached, but db getting populated first from a single app before the workers started. Thanks for verifying @yrqls21, going to revert this for now.

**Comment by KevinYang21** [comment]
@feng-tao @jgao54 Took a quick look and did some basic experiments and it turned out it might not be easy to make the workers work in parallel setting up the db--both `init_views(appbuilder)` and `init_roles(appbuilder)` need to finish. Besides the hack mentioned above that optimize only for legacy UI, we might also do some other hacks to avoid the lengthy start up. For example, parse an empty folder in the parent process :P

Would love to hear what you guys have in mind.

**Comment by bolkedebruin** [comment]
Im not including this 1.10 due to unresolved issues for now

**Comment by verdan** [comment]
@yrqls21 @jgao54 correct, there might not be easy way to make the workers work in parallel with FAB initialization, as the gunicorn workers are actually independent unix process _(not really sure why we are using the cached app mechanism though)_
Apart from the hack that you mentioned i.e., parsing an empty folder, another hack could be to use environment variables to skip the DAG parsing for parent process. thoughts?
something like this: https://github.com/verdan/incubator-airflow/pull/6/files

**Comment by KevinYang21** [comment]
@verdan I think your approach is more appropriate. Thank you very much.

**Comment by cctvzd7** [comment]
@yrqls21 @jgao54 @feng-tao 
I have an idea:
Why not persist the dags' snapshot and dag files' MD5.
When starting up, check the files' MD5, if MD5 changes then parse the dag files, otherwise do not.

**Comment by KevinYang21** [comment]
@cctvzd7 ty for your idea. Persisting DAG is a much bigger problem and would need a more complicated solution( there're a few challenges there e.g. serialize task dependency graph). It would be nice feature tho, since it would enable useful stuff like DAG versioning.

Note that we will still need to parse the DAG file even it has not changed since we cannot share DAG objects across processes, since not all DAGs are pickable which is the root problem. And there should be no need to actually parse DAG if we have centralized DAG parsing/storage. Finally we will still need a major surgery for `models.py` since it is vastly using the actual DAG and task objects.

Cheers.

**Pull request merged**
