### PR TITLE
Added last_dagrun to DAGs list endpoint

### PR DESCRIPTION
**Pull request by ArshiaZr**
This PR enhances the DAGs list endpoint by adding the `last_dagrun` field to the response. The changes allow the frontend to display the last DAG run details without having to request additional fields one by one.

### Changes:
- Added the `last_dagrun` field for each DAG in the list, retrieving the most recent DagRun for each DAG.
- Used `__dict__` for dynamic handling of DagRun fields to avoid manually adding individual fields.
- Maintained the original structure of the DAG response, ensuring that no existing data is altered.

---

### CODE REVIEW

**Comment by potiuk** [comment]
Agree. No new features for Airlfow 2.

**Comment by pierrejeambrun** [comment]
Closing. I thenk @bbovenzi is working on some way to retrive `last_dag_run` information for the new `get_dags` endpoints.

**Comment by bbovenzi** [comment]
Thanks @ArshiaZr but sorry if I confused you in #42730. We're not updating the legacy api at `api_connexion` but the new get dags list over at `api_fastapi`

**Comment by ArshiaZr** [comment]
@bbovenzi No, it's completely alright. So is there any issue with the new api or there's nothing to be done regarding this issue?

**Comment by bbovenzi** [comment]
We need to add last_dagrun to the get /dags request in fastapi. We can filter and sort by last run, but we don't actually have last run on the dag list response

**Comment by ArshiaZr** [comment]
Can I work on it?

**Comment by pierrejeambrun** [comment]
Of course @ArshiaZr, you are welcome to open a PR

Maybe @bbovenzi will have more information on what is needed exactly but I think the idea is:
- For the public endpoint `get_dags` you can add the `latest_dag_run` which is basically a whole serialized dag_run object
- We need a custom `ui` endpoints to `get_dags` that will also return the X latest dag_run of the dag. So basically a `latest_dag_runs` that is a list with serialized dag_run. Maybe that `X` is a query parameter so I can ask for dags with their 10th dagrun like this `?n_dag_runs=10` or somothing similar. But maybe that is not needed the query parameter part. You can just start with an hardcoded value.

**Comment by bbovenzi** [comment]
Yes, let's start with just updating the public get_dags endpoint with a `latest_dagrun: DagRun | None` I updated the description in https://github.com/apache/airflow/issues/42730

**Comment by ArshiaZr** [comment]
@bbovenzi 

I encountered the following issues:

1. I cannot use `DagRun | None` because the `DagRun` class is incompatible with the expected schema for my implementation, resulting in a `PydanticInvalidForJsonSchema` error. Instead, I am using `latest_dagrun: DAGRunResponse | None`.
2. Due to the schema differences, I'm receiving a UI error during the compilation process:

   ```
   SyntaxError: "/Users/arshia/Desktop/w/airflow/airflow/api_fastapi/core_api/openapi/v1-generated.yaml" is not a valid JSON Schema
   ```

As a result, I am unable to commit my changes.

**Comment by ArshiaZr** [comment]
I'm getting these errors from pre-commit tool

**Comment by pierrejeambrun** [comment]
From your error message above it looks like something is trying to read a json from `v1-generated.yaml`. Hard to tell without more context. Normally pre-commits should just work out of the box. Do you mind pasting more error context for us to understand.

Otherwise you can always commit with `-n` (not advised but in some rare cases of pre-commit bug, you can still commit by-passing the precommits)

**Pull request closed without merging**
