### PR TITLE
Adding `SalesforceToS3Operator` to the Amazon Provider

### LINKED ISSUE #16891: Add a SalesforceToS3Operator to push Salesforce data to an S3 bucket
**Description**
Currently an operator exists to copy Salesforce data to Google Cloud Storage (`SalesforceToGcsOperator`) but a similar operator for an S3 destination is absent.  Since S3 is widely used as part of general storage/data lakes within data pipelines as well as Salesforce to manage a slew of marketing, customer, and sales data, this operator seems beneficial.

**Use case / motivation**
Undoubtedly there are use cases to extract Salesforce into an S3 bucket, perhaps augmenting a data warehouse with said data downstream, or ensuring the data is sync'd to a data lake as part of a modern data architecture.  I imagine users are currently building custom operators to do so in Airflow (if not taking advantage of an external service to handle the copy/sync). Ideally this functionality would be included within the AWS provider as well as help provide some feature parity with Google Cloud in Airflow.

**Are you willing to submit a PR?**
Yes 🚀 

**Related Issues**
None that I can find.

### PR DESCRIPTION
**Pull request by josh-fell**
Closes: #16891 

Creating an operator to extract data from Salesforce and upload to S3: `SalesforceToS3Operator`

Items contained in this PR include:
- Operator code: `airflow/providers/amazon/aws/transfers/salesforce_to_s3.py`
- Operator documentation: `docs/apache-airflow-providers-amazon/operators/salesforce_to_s3.rst`
- Operator unit test: `tests/providers/amazon/aws/transfers/test_salesforce_to_s3.py`
- Example DAG: `airflow/providers/amazon/aws/example_dags/example_salesforce_to_s3.py`
- Updated Amazon `provider.yaml`

Please let me know if I am missing any required updates when adding to provider packages.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Can you please rebase to latest main ?

**Comment by potiuk** [comment]
some rebase issue :( we have now 151 files changed

**Comment by josh-fell** [comment]
> some rebase issue :( we have now 151 files changed

Yeah I'm looking into this. Sorry Jarek.

**Comment by potiuk** [comment]
> Yeah I'm looking into this. Sorry Jarek.

No problem. Happens to me often enough to mess up with rebase :)

**Comment by josh-fell** [comment]
@potiuk Would you mind closing this PR? I'll open a new one. Sorry for really mucking this up.

**Comment by potiuk** [comment]
No problem. This happens often too. We  move fast! and sometimes the best thing is to close and apply changes from the scratch

**Pull request closed without merging**
