### PR TITLE
[AIRFLOW-1770] Allow HiveOperator to take in a file

### PR DESCRIPTION
**Pull request by wolfier**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1770

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Clarify and upgrade HiveOperator. Include
description of hql parameter being able to
take in a relative path from the dag file
of a hive script, templated or not. Add
ability to template hiveconf variables. Add
default value to the map reduce job name as
well as add updated hiveconf var for queue.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
added test_hiveconf_jinja_translate in tests/operators/hive_operator.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by wolfier** [comment]
Do you mind taking a look at this @aoen ;D Thanks!

**Comment by Acehaidrey** [comment]
@saguziel think you can review this?

**Comment by bolkedebruin** [comment]
Can you rebase please? Furthermore can you check if your tests are runnin g on travis? I couldnt find the test by a quick search

**Comment by wolfier** [comment]
Going to right now!

**Comment by bolkedebruin** [comment]
Nice. Probably will fail on some flake8 errors judging from the looks of it - so a little work still needed.

**Comment by wolfier** [comment]
@bolkedebruin My test is under the class HivePrestoTest but those test doesn't get ran as far I know. Should I place my test elsewhere or rather how to set AIRFLOW_RUNALL_TESTS to be in  os.environ so it goes into the if statement?

**Comment by bolkedebruin** [comment]
Add a HiveOperatorTest above the os.environ test, and add your test there please.

**Comment by wolfier** [comment]
@bolkedebruin Rebased, test added and passed!

**Comment by Fokko** [comment]
LGTM, we should get rid of the `AIRFLOW_RUNALL_TESTS` in another PR.

**Pull request closed without merging**
