### PR TITLE
DockerOperator TaskFlow - correct arguments in python command

### LINKED ISSUE #39319: Missing termination argument in DockerOperator
### Apache Airflow Provider(s)

docker

### Versions of Apache Airflow Providers

3.10.0

### Apache Airflow version

2.8.3-python3.11

### Operating System

ubuntu

### Deployment

Docker-Compose

### Deployment details

I'm using docker-compose on an EC2 instance

### What happened

While launching the DAG, when a task fails (I mean : the python code of the task), the file /tmp/script.py expect a forth argument that is missing

### What you think should happen instead

The error seems to come from https://github.com/apache/airflow/pull/31747 that adds the termination file as 
`termination_log_path = tmp_dir / "termination.log"`

### How to reproduce

```
from airflow.decorators import dag, task
@dag()
def failing_test():
    @task.docker(image="python:3.11-slim-bookworm", python_command="python3", docker_url="tcp://docker-socket-proxy:2375",)
    def fails():
        raise RuntimeError("This is a test")
    fails()
failing_test()
```

results in
```
...
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_SCRIPT"]);f = open("/tmp/script.py", "wb"); f.write(x);'
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - + python3 -c 'import base64, os;x = base64.b64decode(os.environ["__PYTHON_INPUT"]);f = open("/tmp/script.in", "wb"); f.write(x);'
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - + python3 /tmp/script.py /tmp/script.in /tmp/script.out
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - Traceback (most recent call last):
  File "/tmp/script.py", line 31, in <module>
    res = fails(*arg_dict["args"], **arg_dict["kwargs"])
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/script.py", line 17, in fails
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - raise RuntimeError("This is a test")
RuntimeError: This is a test
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/script.py", line 33, in <module>
[2024-04-29, 23:09:01 UTC] {docker.py:436} INFO - with open(sys.argv[4], "w") as file:
              ~~~~~~~~^^^
IndexError: list index out of range
[2024-04-29, 23:09:02 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
...
```

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by antoinetavant**
Closes #39319 

This PR provide two minor changes :
- Two additional arguments are given to the python command to match the updates of the script interface
   `python3 /tmp/script.py /tmp/script.in /tmp/script.out none /tmp/script.out`
   Indeed, the script used in the DockerOperator in the same as the one in PythonVirtualenvOperator (see [airflow/utils/python_virtualenv_script.jinja2](https://github.com/karunpoudel/airflow/blob/1e75b694848b1eac2fdf3a28a3052501f5470908/airflow/utils/python_virtualenv_script.jinja2) )
- The messages transferred from the docker container to the worker are split line by line to the logger, in order to
   - allow multiline messages such as Trace backs to maintain the indent (useful for [PEP-657](https://peps.python.org/pep-0657/) )
   - Manage buffered messages that should be individually printed but could be differed
   - Sherry on the cake : filtering on the message level and the file display the totality of the multi-line message (instead of only the first line)

## Illustration of the multiline splits

Before :
```
[2024-05-14T12:51:52.701+0000] {docker.py:436} INFO - + python3 /tmp/script.py /tmp/script.in /tmp/script.out none /tmp/script.out
[2024-05-14T12:51:52.741+0000] {docker.py:436} INFO - Traceback (most recent call last):
  File "/tmp/script.py", line 31, in <module>
    res = fails(*arg_dict["args"], **arg_dict["kwargs"])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/script.py", line 17, in fails
    a = 1 / 0
        ~~^~~
ZeroDivisionError: division by zero
[2024-05-14T12:51:52.955+0000] {taskinstance.py:454} INFO - ::group::Post task execution logs
```

Now 

```
[2024-05-14T12:50:17.655+0000] {docker.py:437} INFO - + python3 /tmp/script.py /tmp/script.in /tmp/script.out none /tmp/script.out
[2024-05-14T12:50:17.693+0000] {docker.py:437} INFO - Traceback (most recent call last):
[2024-05-14T12:50:17.694+0000] {docker.py:437} INFO -   File "/tmp/script.py", line 31, in <module>
[2024-05-14T12:50:17.694+0000] {docker.py:437} INFO -     res = fails(*arg_dict["args"], **arg_dict["kwargs"])
[2024-05-14T12:50:17.694+0000] {docker.py:437} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-05-14T12:50:17.695+0000] {docker.py:437} INFO -   File "/tmp/script.py", line 17, in fails
[2024-05-14T12:50:17.695+0000] {docker.py:437} INFO -     a = 1 / 0
[2024-05-14T12:50:17.696+0000] {docker.py:437} INFO -         ~~^~~
[2024-05-14T12:50:17.696+0000] {docker.py:437} INFO - ZeroDivisionError: division by zero
[2024-05-14T12:50:17.876+0000] {taskinstance.py:454} INFO - ::group::Post task execution logs

```

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by dirrao — COMMENTED** [review]
Congratulations on your first MR. Can you add the test case for your change? 
Formatting the traceback with logger prefix message will beautify the logs. However, it is difficult to traceback whether the logs from the same code line or multiple code lines.

**Review by hussein-awala — COMMENTED** [review]
-0.9 Your PR makes the log more beautiful in Airflow webserver, but it also makes it harder to process and analyze via log tools (datadog, cloudwatch, ELK...)

**Comment by antoinetavant** [comment]
> -0.9 Your PR makes the log more beautiful in Airflow webserver, but it also makes it harder to process and analyze via log tools (datadog, cloudwatch, ELK...)

Damn ! I did not expect that. I'm not using such tools...

Do you think there is a way to allow both approaches to work ?

I thought of indenting the multi-line messages with white spaces matching the length of the logging prefix, but unfortunately the buffering of the messages make such that it is not possible to differentiate one multiline message (such as a Trace back) or multiple messages that are sent at the same time.

**Comment by jscheffl** [comment]
> -0.9 Your PR makes the log more beautiful in Airflow webserver, but it also makes it harder to process and analyze via log tools (datadog, cloudwatch, ELK...)

I would be a +0.5 for the log adjustments - nt using ELK but bothered with the output especially in conjunction as also reported in #39686 . My proposal is to make it configurable, maybe as a parameter on the operator?

**Comment by jscheffl** [comment]
Oh, just realized by stale notifications that by accident #40489 of me also addressed the problem 2 proposed here, but lost track of the other PR being existing.

I'm not using the decorator (yet) but can imagine the point 1 in the PR is still valid.

**Comment by antoinetavant** [comment]
Hi @jscheffl , thanks for the notice I think I would have missed it !
I'm glad you fixed this point, I was not confident on the way to address it in a correct way following the different reviews.

I'll remove this part from the PR to only address the first point then !

**Comment by antoinetavant** [comment]
I've updated the PR by adding a regression test and only addressing the first point, as the second has been addressed.

**Comment by jscheffl** [comment]
Looks good, but fails in a single regression with Airflow 2.7... can you check this? Then I think.. LGTM!

**Comment by antoinetavant** [comment]
> Looks good, but fails in a single regression with Airflow 2.7... can you check this? Then I think.. LGTM!

Thanks !
I've looking into it, I think I got the issue, but I struggle to test the regression to airflow 2.7 locally with breeze.

**Comment by potiuk** [comment]
There is quite detailed step-by-step guide how to run provider tests with older versions of airflow locally https://github.com/apache/airflow/blob/main/contributing-docs/testing/unit_tests.rst#running-the-compatibility-tests-locally

**Comment by potiuk** [comment]
In short `breeze shell --use-airflow-version 2.7.3 --mount-sources providers-and-tests` and then you can run `pytest your_tests` to run the tests.

**Comment by antoinetavant** [comment]
Thanks a lot @potiuk ! I misted it in the docs ! It really works like a breeze !
@jscheffl I can confirm that the regression with `airflow==2.7.3` is fixed !

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I renamed the commit slighlty - to reflect that it's only #1 from the original PR.

**Pull request merged**
