### PR TITLE
Use different executors for k8s tests in CI

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This change will allow us to run k8s tests with different executors in the CI

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — COMMENTED** [review]
See the https://github.com/apache/airflow/issues/14301 - I propose to use existing KUBERNETES_MODE for that

**Comment by ephraimbuddy** [comment]
Still experimenting with this...

**Comment by ephraimbuddy** [comment]
Marking as ready for review but not yet ready

**Comment by potiuk** [comment]
This problem you experienced here was more wide-spread and somehow connected to our CI infra. I will test it later today (hopefully - after the current major outage of GitHub Actions is solved https://www.githubstatus.com/incidents/zbpwygxwb3gw)

**Comment by kaxil** [comment]
@ephraimbuddy Please rebase on the latest master, that should fix the Docs Build error caused by spelling mistake

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
Hurray!

**Pull request merged**
