### PR TITLE
Make task ID on legend have enough width and width of line chart to be 100%. 

### PR DESCRIPTION
**Pull request by PengMingHua905001**
Annotation 2021-05-18 171131
On Task Duration/Task Tries/Lading Times, the full name of task ID is cutted and end with '...' if lenght is over that 20 characters. So we make task ID have enough width (max length: 200 characters ) to be displayed and let user can find out matched Task ID  when pressing CTRL+F and inputting long text.
Width of line chart was set to 1200 , it looks not good for big screens, it should be 100% width.
Please compare the before and after screenshot.
**Before:**
before
**After:**
after

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]
Lgtm. but it may be helpful to show a before and after screenshot in the PR.

**Comment by PengMingHua905001** [comment]
Add beforeand after screenshot

**Comment by PengMingHua905001** [comment]
image
It looks good on ipad simulated on chrome.

**Review by ryanahamilton — APPROVED** [review]

**Review by ryanahamilton — CHANGES_REQUESTED** [review]
Looks like some pylint errors need fixing

**Comment by jhtimmins** [comment]
@ryanahamilton can you take a look and confirm whether your requested changes have been addressed?

**Review by ryanahamilton — APPROVED** [review]

**Pull request merged**
