### PR TITLE
Adding always be rebased message for new contributors

### PR DESCRIPTION
**Pull request by amoghrajesh**
More often than not, we see many issues in our slack asking about issues that end up being because they were not rebased. Github shows it in the UI on subsequent commits after the PR is created. But during the point of PR creation, it can be well possible that the commits are not upto date with rebased main if there are no files with **conflicts**. In such cases, such warnings always help :)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by Lee-W — APPROVED** [review]

**Comment by uranusjr** [comment]
Would a checkbox help much? The PR needs to be rebased _consistently_, not just when it’s first sumitted.

**Comment by potiuk** [comment]
Yeah. I am not sure if more info here is going to help but it should be 'future' focused not 'past' if we want to add any call to action here.

**Comment by amoghrajesh** [comment]
> Would a checkbox help much? The PR needs to be rebased _consistently_, not just when it’s first sumitted.

That is correct. But my idea was to make sure that it is rebased when it is submitted. Periodic refresh is a common practice and is done always

**Comment by amoghrajesh** [comment]
> Yeah. I am not sure if more info here is going to help but it should be 'future' focused not 'past' if we want to add any call to action here.

Right. But the intention is in the `present`, neither future nor past. We should tell the users *now* that they should rebase while creating the PR. Sometimes what happens is that Github wont show a warning if there are no conflicting files, but there might not be conflicting files, but code change somewhere can affect other things too.

Just explaining where I am coming from. Open to feedback.

Maybe @potiuk it can be re worded? Any suggestions?

**Comment by potiuk** [comment]
I think we rarely have problem with a PR raised from not-rebased code at the beginning. My observation that very rarely people  start from an old commit. And even if they do, then "rebase" is very wrong wording. They should `switch` to the latest main, not `rebase`. The `rebase` by definition is when you already have a PR and things changed since you created it, not when you create a new PR - that's why I think adding the checkbox with it here will be mostly noise.

We have to be very careful when we add such message we

There are two kinds of people (generally):

1) fresh contributors - they open their first PR. Almost by definition they will start from latest main because they just checked out airflow's code. Most of those people will get "please rebase" as part of their journey for the first PR, but they need the advice on rebasing few days or weeks after they created the PR. Informing them about rebase when they create PR is confusing at best and misleading and might lead to more questions (what does it mean? should I click it? I do not understand what they are asking here?) 

2) 2nd/3rd-time contributors - those who are **possibly** likely to open a PR from an old commit they had some time ago - most of them already know about rebase as they were informed before. For them creating a PR and seeing the checkbox to click every time is mostly a noise.

3) experienced contributors - this is just noise for them


So if anything - I think MAYBE, if we consider improving the experience and inform our contributors better - we should add a message "please keep your PR rebased - and link to the rebase instructions from GitHub in the "first PR" message that is added for users 1) https://github.com/apache/airflow/blob/main/.github/boring-cyborg.yml#L645  -  I don't think Pull request template is the right place.

**Comment by amoghrajesh** [comment]
Awesome explanation. Every point is valid. @potiuk
I will make the changes to inform the new users about this in the cyborg messages.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
