### PR TITLE
Add "all" to list of valid breeze integrations

### PR DESCRIPTION
**Pull request by scrambldchannel**
Hi, I've tried to address https://github.com/apache/airflow/issues/9857. This change allows use of the "all" option.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
You will also need to add "all" to pre_commit_check_integrations.sh and run `pre-commit run update-breeze-file` to update the docs.

**Comment by potiuk** [comment]
Something like that: 

```
if [[ "${AVAILABLE_INTEGRATIONS} all" != "${_BREEZE_ALLOWED_INTEGRATIONS}" ]]; then

```

**Comment by scrambldchannel** [comment]
> Something like that:
> 
> ```
> if [[ "${AVAILABLE_INTEGRATIONS} all" != "${_BREEZE_ALLOWED_INTEGRATIONS}" ]]; then
> ```

Ah ok, missed that. I'll take a look soon and update the PR. Thanks!

**Comment by scrambldchannel** [comment]
OK, I realised I'd nuked my repo and hadn't re-applied the pre-commit hooks, my bad. I also merged rather than rebased. I was going to close this PR and open a newer one to clean it all up but then ran into a weird error with the check_integrations pre commit hook which failed with.

```
./scripts/ci/pre_commit/pre_commit_check_integrations.sh: line 26: AVAILABLE_INTEGRATIONS: unbound variable
```

Maybe _common_values.sh is no longer being read before the test is run? I am a novice when it comes to the pre commit framework but am trying to muddle through it, will raise an issue if I can determine it properly.

**Pull request closed without merging**
