### PR TITLE
Allow disabling the Helm hooks in the helm chart

### PR DESCRIPTION
**Pull request by Mrngilles**
Following #17447, I added a way to disable the Helm hooks so that the jobs are properly created in ArgoCD.

This does not change the default behavior of the helm chart, but makes it more flexible

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM for now (until we get better way to handle upgrades

**Review by jedcunningham — CHANGES_REQUESTED** [review]
Can you also add tests?

**Comment by Mrngilles** [comment]
Sure, I'll get that done. Thanks for the review

**Review by jedcunningham — APPROVED** [review]

**Comment by jedcunningham** [comment]
Thanks for the contribution @Mrngilles! Congrats on your first commit 🎉

**Comment by potiuk** [comment]
Cool!

**Comment by kylegalea** [comment]
this change  should have been added to 1.3.0 but is not there

**Comment by jedcunningham** [comment]
Thanks @kylegalea, I see that it isn't in there, but it should have been. Let me investigate further.

**Comment by jedcunningham** [comment]
@kylegalea, thanks for bringing this up! Sorry I accidentally messed up getting this into 1.3.0. It'll _definitely_ make it into 1.4.0.

**Pull request merged**
