### PR TITLE
Migrate Dataflow system tests

### PR DESCRIPTION
**Pull request by bhirsz**

### CODE REVIEW

**Comment by potiuk** [comment]
docs failing.

**Comment by potiuk** [comment]
docs failing.

**Comment by potiuk** [comment]
Still

**Comment by bhirsz** [comment]
@potiuk Finally all passing! :) Though I used a bit of the ugly workaround - sphinx couldn't give up with my python file in the tests/system/providers/google/cloud/dataflow/resources/ directory. Renaming the file to ".txt" workarounded the problem for now.  This file is only used in the operator so it doesn't really matter.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> @potiuk Finally all passing! :) Though I used a bit of the ugly workaround - sphinx couldn't give up with my python file in the tests/system/providers/google/cloud/dataflow/resources/ directory. Renaming the file to ".txt" workarounded the problem for now. This file is only used in the operator so it doesn't really matter.

Makes sense, we could probably find a solution and exclude the file but this way is also ok as it is very localized.

**Pull request merged**
