### PR TITLE
Update configuration documentation

### PR DESCRIPTION
**Pull request by LiChangNY**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

NA. Just updating docs.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

https://github.com/apache/incubator-airflow/blob/7765278479b81a73244ff44e47973bbc5bf9bcef/airflow/hooks/base_hook.py#L29 shows that the correct prefix of env var for creating a db connection is `AIRFLOW_CONN` as opposed to `AIRFLOW__CORE__`. So update the docs here.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

My PR does not need test.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

NA

### CODE REVIEW

**Comment by r39132** [comment]
+1. 
Please create a tracking Jira and follow the instructions on : https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide under "Submitting PRs"

**Comment by NielsZeilemaker** [comment]
This is actually not true, the documentation refers to how to override an airflow configuration setting. And hence if you wanted to override the global sql_alchemy_connection as defined in the core section of the configuration you need to set an environment variable called `AIRFLOW__CORE__SQL_ALCHEMY_CONN`.

You are referring to being able to define connections using environment variables. That's also a nice feature, but currently not documented (i think).

**Comment by Fokko** [comment]
@NielsZeilemaker is correct. I think it is documented pretty well: http://airflow.readthedocs.io/en/latest/configuration.html

But if there are any suggestions to improve it, please feel free to submit a RP.

**Comment by r39132** [comment]
Agree with @NielsZeilemaker. The `AIRFLOW_CONN` env var prefix is used to set a connection URI via env var as shown below:
`AIRFLOW_CONN_MYSQL_DBCONN=mysql://user@localhost:3333`

To set the connection to the Airflow Metadata DB, the DB used by Airflow itself (not the connections exposed to DAGs via Admin-->connections), you would use `AIRFLOW__CORE__SQL_ALCHEMY_CONN`

**Comment by r39132** [comment]
If you have no further comments, I will close this PR after a couple of days.

**Comment by LiChangNY** [comment]
Ah, that makes sense. Just looked through the documentation again, here does mention setting connections referenced in the DAG. http://airflow.readthedocs.io/en/latest/concepts.html?highlight=environment%20variable#connections, so we're good. Feel free to close this PR. Thank you!

**Comment by r39132** [comment]
Closing!

**Pull request closed without merging**
