### PR TITLE
Add dataset create endpoint

### PR DESCRIPTION
**Pull request by edumuellerFSL**
This PR adds a new feature to create datasets via the API, improving dataset management in Airflow. The feature includes a new POST endpoint for dataset creation w/ necessary tests and API specifications. This addition will improve the Airflow API by allowing programmatic dataset management, giving users more flexibility and automation options in their workflows.

related: #36686
discussion: https://github.com/apache/airflow/discussions/36723

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by RNHTTR** [comment]
This wouldn't provide any functionality until there's a way to update a dataset via API, right?

**Comment by edumuellerFSL** [comment]
> This wouldn't provide any functionality until there's a way to update a dataset via API, right?

Hi @RNHTTR that's right, let me convert this to a draft for the moment.

**Comment by uranusjr** [comment]
Is this useful in any case? A dataset is created in the database when a DAG listens to it (via `schedule=[dataset]`). A dataset created from API is useless because triggering an event of it would do nothing. To make it possible to trigger an event-driven DAG, we need an API to create DatasetEvent entries, not datasets themselves.

**Review by potiuk — CHANGES_REQUESTED** [review]
I think this one should hold before we conclude https://lists.apache.org/thread/q4sd09xymvlskxdgcb1s6gfsqwnvqs2o discussion (so I am doing "Request changes" unti it does - and end up with a VOTE or CONSENSUS).

Whether to create/delete datasets externally is a decision that should be made deliberately, and there are various voices there - some (including myself) think that dataset management should be done internally by Airflow (including possibly reference counting and automatically removing datasets that are not referred by any DAGS) while some others think that there is a value in managing datasets from outside. Until that discussion concludes, I think we should hold on with merging this change.

**Comment by edumuellerFSL** [comment]
> I think this one should hold before we conclude https://lists.apache.org/thread/q4sd09xymvlskxdgcb1s6gfsqwnvqs2o discussion (so I am doing "Request changes" unti it does - and end up with a VOTE or CONSENSUS).
> 
> 
> 
> Whether to create/delete datasets externally is a decision that should be made deliberately, and there are various voices there - some (including myself) think that dataset management should be done internally by Airflow (including possibly reference counting and automatically removing datasets that are not referred by any DAGS) while some others think that there is a value in managing datasets from outside. Until that discussion concludes, I think we should hold on with merging this change.

I agree, that's why I converted it into a Draft. Thanks @potiuk.

**Pull request closed without merging**
