### PR TITLE
Fix system test for Memorystore memcached

### PR DESCRIPTION
**Pull request by moiseenkov**
Fixed system test for Google Memorystore memcached by adding zone to instance nodes specification

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by o-nikolas** [comment]
Hey @moiseenkov! 

There were some static check failures, you'll need to patch those up.
You can enable pre-commit to easily run static checks on your code ([readme](https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst#installing-pre-commit-hooks)).

Do also rebase your branch since some changes were recently merged to standardize quoting in the Airflow codebase.

**Comment by moiseenkov** [comment]
> Hey @moiseenkov!
> 
> There were some static check failures, you'll need to patch those up. You can enable pre-commit to easily run static checks on your code ([readme](https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst#installing-pre-commit-hooks)).
> 
> Do also rebase your branch since some changes were recently merged to standardize quoting in the Airflow codebase.

**Comment by moiseenkov** [comment]
@o-nikolas , hi,

Can we merge this PR please? Your comment has been addressed.

**Comment by o-nikolas** [comment]
> @o-nikolas , hi,
> 
> Can we merge this PR please? Your comment has been addressed.

All good on my end, but unfortunately I am not a committer and cannot merge changes

**Review by o-nikolas — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
