### PR TITLE
Parse JSON template files by default

### PR DESCRIPTION
**Pull request by oyarushe**
For many operators, we are using template extension `.json`, but these files after rendering as string. But I think it will be good to parse JSON files and get a dictionary instead of a string.

Some operators handle it, but I think it will be good to make this behavior by default:
https://github.com/apache/airflow/blob/177dfbd12a42a5c229640c6c830f43f280ea5caa/airflow/providers/amazon/aws/operators/emr_create_job_flow.py#L74-L78

What do you think about it?

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
> Some operators handle it, but I think it will be good to make this behavior by default

But some operators *want* the un-parsed JSON string, so this will only create issues from the other side. So For me, the answer is no, this should be kept as-is and handled by each operator/hook.

**Comment by potiuk** [comment]
Agree with @uranusjr - this is backwards-incompatible change. If anything we might want to make it an optional feature that you can enable if you want, but if we would like to implement this, we should make it a generic, optional feature for a number of file types (,json, ,yml, .csv). 

However, I think it's not needed - As @uranusjr  decision whether to parse a file can be easily taken by each operator independently.

**Comment by potiuk** [comment]
Closing (unless there will be some good argument to re-open it :)

**Comment by oyarushe** [comment]
Thanks for reviewing @uranusjr, @potiuk, I agree with you

**Pull request closed without merging**
