### PR TITLE
fix: Databricks Provider Dependency #23917

### PR DESCRIPTION
**Pull request by vincentkoc**
Patch fix of requirements for Databricks Provider, quick fix for #23917

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by koconder** [comment]
@uranusjr the 1-2 random test failures seem totally unrelated to the provider code, is there some other issue with tests or is this transient?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
The problem is that we currently have some newly released dependencies breaking main (and any of the PRs that change requirements). We will need to fix it first (I am going to take a look at it shortly - but since we have Airflow Summit this week - please a little patience :).

**Comment by eladkal** [comment]
> I am going to take a look at it shortly
main is broken by moto 
they already fixed the issue https://github.com/spulec/moto/pull/5165 but didn't release 3.1.11 yet

**Comment by potiuk** [comment]
And fix for static check failure here: https://github.com/apache/airflow/pull/23941

**Comment by potiuk** [comment]
Rebased it to re-run the build after both fixes are merged :)

**Comment by koconder** [comment]
Thanks @potiuk its now ready to approve and merge

**Comment by potiuk** [comment]
Done :)

**Pull request merged**
