### PR TITLE
feat: K8S 1.32 support

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Comment by raphaelauv** [comment]
I can't reproduce with `pre-commit run --all-files` the error of the CI `Update breeze docs`

**Comment by potiuk** [comment]
Rebase. It's already been fixed in `main` in #45156 - that was instability in sequence of options in click config dictionary in click 8.1.8 which caused random hash calculation.

**Comment by raphaelauv** [comment]
Thanks for your help , I rebased and it still failing, any idea ?

**Comment by potiuk** [comment]
Yeah. You need to run `breeze static-checks --last-commit` and it should fix itself.

**Comment by potiuk** [comment]
(or so I think)

**Comment by raphaelauv** [comment]
yes I tried `breeze static-checks --last-commit` after the rebase , no effect

**Comment by raphaelauv** [comment]
yes I already tried to rebuild my breeze context , no effect

**Comment by potiuk** [comment]
You can also (though it should happen automatically) remove and re-install breeze `uv tool remove airflow_breeze` followed by `uv tool install --editable ./dev/breeze`.  Maybe also you did the rebuild before constraints were updated - then `breeze ci-image build --upgrade-to-newer-dependencies` might help.

**Comment by potiuk** [comment]
I re-run it locally and those hashes were properly calculated - I pushed a fixup.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> `breeze ci-image build --upgrade-to-newer-dependencies` fixed it 👍
> 
> thanks

Ah. I found out the root cause - we should also upgrade minimum version of click in "airflow" so that `breeze ci-image build` will upgrade it as well - I missed that in https://github.com/apache/airflow/pull/45156. 

This should be fixed now for everyone else via: https://github.com/apache/airflow/pull/45177

**Pull request merged**
