### PR TITLE
AIRFLOW-1491 Check celery queue before scheduling commands

### PR DESCRIPTION
**Pull request by gwax**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1491

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
    - This PR introduces a celery introspection check to the celery executor to recover commands from the celery queue.
    - Doing so prevents the rescheduling of identical commands in celery.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
    - Basic tests for the celery executor
    - Tests of reschedule check

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Nice! Do you know what the speed impact is? I understood querying celery would cost about 1s per query. That could by quite a lot in our case.

**Comment by gwax** [comment]
@bolkedebruin it adds about 1-3s to task scheduling.

This is only when scheduling new tasks, not heartbeating. It also applies only to individual DAG schedulers. It's potentially costly if a given DAG has a large number of tasks that need to be scheduled at the same time and the system has a large parallelism limit.

It's a bit of a stopgap for a race condition that we've run into a number of times. Longer term, I'm hoping to do a more thorough rewrite of the executor system but stopgaps solve problems and hopes don't.

**Comment by gwax** [comment]
If there's a performance concern, I could put it behind a configuration variable.

**Comment by saguziel** [comment]
I'm not sure how I feel about this. I'm working on a fix for a race condition in LocalTaskJob. I think then this will be unnecessary and seems strange. Double triggers are guarded against in both cases, especially with the Celery-Redis Visibility Timeout bug

**Comment by saguziel** [comment]
I'm also concerned about performance, when you say adds 1-3s, what does that mean. If it is 1s per query, that is really bad.

**Comment by saguziel** [comment]
Hold tight for my PR, but I think it's a needed fix, and doesn't change any performance (the issue is with was_running in LocalTaskJob, which is a bad hard to take out, but should be doable)

**Comment by saguziel** [comment]
Can you detail the race condition? The other check should catch most cases.

**Comment by bolkedebruin** [comment]
@gwax you are recovering the asyncresult, but this is recorded. Why is this required? After a scheduler restart? Isn't it better to this at instantiation time then so we recover all state?

**Comment by bolkedebruin** [comment]
Also would 'CELERY_TRACK_STARTED=True' with a properly configured result backend help here?

**Comment by saguziel** [comment]
CELERY_TRACK_STARTED seems like it may be helpful. I think we would need to do 3 things to fix all the issues I've noticed.

1) Fix the was_running race condition (see 1493)
2) Reload the task table into memory on scheduler restart
3) Requeue tasks that are not started by some interval ( or check that it is still queued). This is a concern because of a celery bug with prefetching can delay a task arbitrarily long.

**Comment by bolkedebruin** [comment]
@saguziel can you specify/link to 3?

**Comment by saguziel** [comment]
https://github.com/celery/celery/issues/1933

There is a few more tickets of a similar thing.

We noticed in prod some tasks would get delayed for a long time. What was happening was the task would get prefetched, so it might get stuck behind tasks that run for very long (or even tasks that run forever). Because we want to meet an SLA, this behavior is bad.

**Comment by bolkedebruin** [comment]
@saguziel so you need to set 'task_acks_late = True', per documentation if you don't want this behavior (standard prefetch is 1 + 1, 1 unacknowledged + acknowledged). It is not considered a bu by celery it seems.

**Comment by saguziel** [comment]
@bolkedebruin , The standard option is to do that is `-o fair`, which we have set in bin/cli.py, so it is unintended, as is said by the people in that issue too

**Comment by bolkedebruin** [comment]
No it isn't, although the docs are a bit ambiguous:

"You're probably mistaking the pool child process pipe buffer with the broker prefetch limits. Disabling the latter would mean the worker slurps in as many messages as it can without limit."

You are setting two different things with these options.

**Comment by saguziel** [comment]
We do have ACKS_LATE set, and it still does not disable prefetching (we didn't change anything about celery_executor in our internal repo)

**Comment by gwax** [comment]
@saguziel gets to the heart of our problem when he suggests the solution:

> 2. Reload the task table into memory on scheduler restart

@bolkedebruin the `AsyncResult` is recorded in a dictionary within the executor instance. When the scheduler restarts, the executor state is created anew and the new executor instance does not have any knowledge of previously scheduled tasks that may be waiting in the queue.

The race condition that we've run into boils down to:

1. pool_A has 5 slots and 20 tasks available to schedule
1. scheduler schedules tasks 1-5, and waits on 6-20
1. scheduler restarts
1. scheduler schedules tasks 1-5
1. now the queue is [1,2,3,4,5,1,2,3,4,5]

If task execution is slow, this can snowball. Prior to putting a few other ameliorations in place, we were regularly seeing many dozens of duplicated tasks during high load periods, which was massively decreasing throughput.

This is meant as a short term fix but I can see how it might be undesirable, even as such.

When (if?) I can find time, I can look into a more complete and robust solution but I am also happy to defer to @saguziel, if there are solutions inbound.

**Comment by bolkedebruin** [comment]
@saguziel if that is the case, having all options set, then I would open a new issue with Celery cause that is not what the other issues are about. 

@gwax afaik and understood from the docs, app.control.inspect queries the workers. This is why it takes so long. So this allows you to infer state and do it an executor start up isn't it? If you populate tasks[] from that we solved @saguziel no 2?

**Comment by saguziel** [comment]
The latest issue does mention that but it seems it got closed anyway. I'm pretty sure I've seen another, although someone asserts it is fixed in 4, so I will try it out and bump setup.py version if that is the case.

**Comment by saguziel** [comment]
I think besides re-loading the jobs table, we also need to enforce heartbeats on queued tasks, or at least verify on scheduler restart that the tasks in queued state are actually queued in celery (this can be done with 1 celery inspect query)

**Comment by saguziel** [comment]
I think we also need to add the celery state to tell when a task has started.

**Comment by saguziel** [comment]
I am working on 1, and maybe 3, but I won't be able to have the time to work on 2 anytime soon. I think we get by without scheduler restarts now (what blocked us was reserved tasks getting lost delaying execution, but if we can fix 3, and assume truly lost messages are rare (celery is supposed to fix this for tasks < 1hr ), then it isn't as much an issue)

**Comment by saguziel** [comment]
Here is the relevant open issue: https://github.com/celery/celery/issues/3765

**Comment by gwax** [comment]
This is also closely related to not being able to run multiple schedulers at the same time. Making it possible to run two schedulers concurrently would be great for eliminating single points of failure.

**Comment by saguziel** [comment]
Yes. It would be nice to have the scheduler be able to only operate on certain files assigned to it. This would also make a sharded/HA setup easier in the future with something like Helix.

**Comment by bolkedebruin** [comment]
We have been experimenting with an active/active setup (posted on medium about this). The situation isn't that bad. If two schedulers are active you won't get tasks scheduled multiple times (at least not more than now). Scheduler restarts bring some ambiguity but indeed should be resolved by no 2.

**Comment by saguziel** [comment]
Yeah, active/active works well for HA. Sharded would just be good to scale and have HA, especially since Helix since easy enough to use.

Right now, we don't use scheduler restarts in prod btw, but we re-queue tasks to celery.

**Pull request closed without merging**
