### PR TITLE
Fix `ComputeEngineInsertInstanceOperator` doesn't respect jinja-templated instance name when given in body argument

### LINKED ISSUE #34170: ComputeEngineInsertInstanceOperator doesn't respect jinja-templated instance name when given in body argument
### Apache Airflow version

2.7.0

### What happened

when initializing the operator with a `body` that has a jinja-templated `name` field and without a `resource_id`, the creation fails due to the fact that the instance name doesn't fit the name format - but that is because it doesnt go realization/jinja-parsing.

### What you think should happen instead

full error log:
```
[2023-09-06, 09:22:41 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/compute.py", line 210, in execute
    existing_instance = hook.get_instance(
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 468, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/compute.py", line 350, in get_instance
    instance = client.get(
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/google/cloud/compute_v1/services/instances/client.py", line 2812, in get
    response = rpc(
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/sigal/.local/share/virtualenvs/ingest-airflow-rHPaIjXZ/lib/python3.8/site-packages/google/cloud/compute_v1/services/instances/transports/rest.py", line 2485, in __call__
    raise core_exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://compute.googleapis.com/compute/v1/projects/ai2-israel/zones/us-west1-b/instances/%7B%7B%20params.get('dataset')%20%7D%7D: Invalid value for field 'instance': '{{ params.get('dataset') }}'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'
```

### How to reproduce

```python
with DAG(
    dag_id="blob",
    schedule_interval=None,
    start_date=datetime(2023, 1, 1),
    catchup=False,
    params={
        "dataset": Param(default="test"),
    },
    render_template_as_native_obj=True,
) as dag:
        dataset = "{{ params.get('dataset') }}"
        create_vm_instance = CustomComputeEngineInsertInstanceOperator(
                task_id="create_vm_instance",
                project_id=OUR_PROJECT_ID,
                zone=OUR_LOCATION,
                body={
                "name": dataset,
                "machine_type": f"zones/{OUR_LOCATION}/machineTypes/n1-standard-96",
                "source_machine_image": f"global/machineImages/{OUR_IMAGE}",
                "disks": [
                    {
                        "boot": True,
                        "device_name": dataset,
                        "initialize_params": {"disk_size_gb": "10", "disk_type": f"zones/{OUR_LOCATION}/diskTypes/pd-ssd"},
                    }
                ],
                "network_interfaces": [
                    {
                        "access_configs": [{"name": "External NAT", "network_tier": "PREMIUM"}],
                        "stack_type": "IPV4_ONLY",
                        "subnetwork": f"regions/{OUR_REGION}/subnetworks/default",
                    }
                ],
            }
        )
```

### Operating System

Ubuntu 20.04.6 LTS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by aryehgigi**
Fixes #34170

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
You need to fix tests, I am afraid.

**Comment by aryehgigi** [comment]
hey @potiuk ,
i dont mind trying to fix the tests, but i wondered what do you think of the code changes, looks right?
we can alternatively add the `resource_id` to the jinja-template list - this will resolve the problem with no other changes required - but would it cause other problems that im not aware of?
wdyt?

**Comment by eladkal** [comment]
Can you add unit test to cover this change?

**Comment by aryehgigi** [comment]
added tests, and covered also other machine instantiations

**Comment by potiuk** [comment]
Hmm. We usually use `@cached_property` for similar cases - which is much cleaner and  more straightforward. Maybe you should also consider it ?

**Comment by aryehgigi** [comment]
@potiuk 
mmm I dont see how would that solve anything?
to which method do you think we should add it? init? execute?

if you are looking for simpler alternatives,  i suggested above that adding `resource_id` to the `template_fields` filed would solve the issue with no other change required. i was just not sure if it would have other unintended/unwanted side-effects..

wdyt?

**Comment by potiuk** [comment]
That works as well and is way better. No there should be no negative side effects.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
