### PR TITLE
Upgrade to Pydantic v2

### PR DESCRIPTION
**Pull request by sinwoobang**
This PR removes deprecated features from Pydantic v1 in preparation for the upcoming major release. The focus is on eliminating elements that are no longer supported in v2 or later, as outlined in [the migration guide](https://docs.pydantic.dev/2.0/migration/).

- [x] Use `ConfigDict` instead of `Config`
- [x] Drop compatibility for v1

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
NOTE! We only want to remove it when we know some important packages that are used by Airflow have already moved to Pydantic v2 . See this comment https://github.com/apache/airflow/pull/34081#issuecomment-1725005980  where we had to bring Pydantic 1 back after removing it (becasue Great Expections had not supported Pydantic v2)

@sinwoobang : Can you please take on the task on reviewing Great Expectations and possibly finding out the state of Pydantic  v2 among important data engineering libraries? I am pretty sure someone somewhere did such a research - and maybe keeps the list updated - or maybe it can be asked in Pydantic discussion list.

**Comment by sinwoobang** [comment]
@potiuk Thank you for the review. I looked around Great Expectations as per your request. Pydantic V2 has been supported on Great Expectations since 8th Sep according to this commit https://github.com/great-expectations/great_expectations/commit/091fc1dd472ef17a39b41bd0f9b8486869d695c7,  whereas the PR - bringing back Pydantic V1 compatibility - was created on 5th Sep.

Facts
- Great Expectations has supported Pydantic V2 from [the release 0.17.15](https://github.com/great-expectations/great_expectations/releases/tag/0.17.15) published on 8th Sep.
- However, Great Expectations still supports Pydantic from v1.10.8
  - `requirements.txt` says that [v1.9.2](https://github.com/great-expectations/great_expectations/blob/091fc1dd472ef17a39b41bd0f9b8486869d695c7/requirements.txt#L23) is the min version, which is NOT true.
  - A maintainer confirms that [v1.10.8](https://github.com/great-expectations/great_expectations/pull/8604/commits/4d80172511f53247e6599565f3f719eaae51d40e) is the actual min version.

**Comment by potiuk** [comment]
I think it's about to time to resurrect that one. We are nearing 2.8.0 releease and I think it's good idea to move to Pydanticv2 only. Will you work on it @sinwoobang ?

**Comment by sinwoobang** [comment]
@potiuk I would be glad to do it. I will let you know after I take a look around the code again. Would you have any cautions or things I need to know?

**Comment by potiuk** [comment]
Nope. You've already checked great expectations and 5 months passed and Pydantic is already at 2.5 - there is no particular reason to stick to v1 any more.

**Comment by potiuk** [comment]
But let me know If I can help in any way.

**Review by potiuk — APPROVED** [review]

**Comment by sinwoobang** [comment]
@potiuk I bumped the Pydantic version to v2.3.0, referring to the previous PRs (https://github.com/apache/airflow/pull/34081/files, https://github.com/apache/airflow/pull/33956/files).

**Comment by potiuk** [comment]
Looks good :)

**Pull request merged**
