### PR TITLE
Fix: `emr_conn_id` should be optional in `EmrCreateJobFlowOperator`

### LINKED ISSUE #24318: `EmrCreateJobFlowOperator` does not work if  emr_conn_id param contain credential
### Apache Airflow Provider(s)

amazon

### Versions of Apache Airflow Providers

_No response_

### Apache Airflow version

2.3.2 (latest released)

### Operating System

os

### Deployment

Other

### Deployment details

_No response_

### What happened

EmrCreateJobFlowOperator currently have two params for connection `emr_conn_id` and `aws_conn_id`. So it works only when I set `aws_conn_id` containing credentials and  an empty `emr_conn_id` and it does not work in the below case
- when I set both aws_conn_id and emr_conn_id in the operator and both connection contains credentials i.e it has aws_access_key_id and other params in airflow connection extra 
```
Unknown parameter in input: "aws_access_key_id", must be one of: Name, LogUri, LogEncryptionKmsKeyId, AdditionalInfo, AmiVersion, ReleaseLabel, Instances, Steps, BootstrapActions, SupportedProducts, NewSupportedProducts, Applications, Configurations, VisibleToAllUsers, JobFlowRole, ServiceRole, Tags, SecurityConfiguration, AutoScalingRole, ScaleDownBehavior, CustomAmiId, EbsRootVolumeSize, RepoUpgradeOnBoot, KerberosAttributes, StepConcurrencyLevel, ManagedScalingPolicy, PlacementGroupConfigs, AutoTerminationPolicy, OSReleaseLabel
```
- when I set both aws_conn_id and emr_conn_id in the operator and only emr_conn_id connection contains credentials i.e it has aws_access_key_id and other params in airflow connection extra
```
[2022-06-07, 20:49:19 UTC] {taskinstance.py:1826} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/airflow/providers/amazon/aws/operators/emr.py", line 324, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/opt/airflow/airflow/providers/amazon/aws/hooks/emr.py", line 87, in create_job_flow
    response = self.get_conn().run_job_flow(**job_flow_overrides)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 895, in _make_api_call
    operation_model, request_dict, request_context
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 917, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 195, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 134, in create_request
    operation_name=operation_model.name,
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 103, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 187, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 405, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
``` 
- When I set only aws_conn_id  in the operator and it contains credentials
```
Traceback (most recent call last):
  File "/opt/airflow/airflow/providers/amazon/aws/operators/emr.py", line 324, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/opt/airflow/airflow/providers/amazon/aws/hooks/emr.py", line 90, in create_job_flow
    emr_conn = self.get_connection(self.emr_conn_id)
  File "/opt/airflow/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/opt/airflow/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
```
- When I set only emr_conn_id  in the operator and it contains credentials
```
[2022-06-07, 20:49:19 UTC] {taskinstance.py:1826} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/airflow/providers/amazon/aws/operators/emr.py", line 324, in execute
    response = emr.create_job_flow(job_flow_overrides)
  File "/opt/airflow/airflow/providers/amazon/aws/hooks/emr.py", line 87, in create_job_flow
    response = self.get_conn().run_job_flow(**job_flow_overrides)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 895, in _make_api_call
    operation_model, request_dict, request_context
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 917, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 195, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 134, in create_request
    operation_name=operation_model.name,
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 103, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 187, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 405, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
- When I set aws_conn_id having credential and  emr_conn_id having no credential i.e empty extra field in airflow connection then it work

### What you think should happen instead

It should work with even one connection id i.e with aws_conn_id  or emr_conn_id and should not fail even emr_conn_id has credentials

### How to reproduce

- Create EmrCreateJobFlowOperator and pass both aws_conn_id and emr_conn_id or
- Create EmrCreateJobFlowOperator and pass aws_conn_id or emr_conn_id

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pankajastro**
#Closes: #24318

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @pankajastro - I am about to release RC2 for providers for May and would like to include that one - would it be possibe to fix the failing tests quickly?

**Comment by pankajastro** [comment]
> Hey @pankajastro - I am about to release RC2 for providers for May and would like to include that one - would it be possibe to fix the failing tests quickly?

Fixed it, the test passing on local. let's see how it goes in CI.

**Comment by pankajastro** [comment]
@potiuk static check failing in this PR as well in other with error 
```
Run pydocstyle.........................................................................Failed
- hook id: pydocstyle
- exit code: 1
airflow/www/security.py:627 in private method `_sync_dag_view_permissions`:
        D202: No blank lines allowed after function docstring (found 1)
```

**Comment by potiuk** [comment]
Ah indeed - it looks like some cross-merged commits without rebase ....

**Comment by eladkal** [comment]
Fix: https://github.com/apache/airflow/pull/24322

**Comment by potiuk** [comment]
> Is it actually an error? Possibly due to lack of documentation of this connection type

I believe there were quite a lot of refactorings to AwsBaseHook since and I guess this is result of it - looks legit for me actually.

**Review by potiuk — APPROVED** [review]
@pankajastro  - if you could comment on @Taragolis 's comment too - anyway I am happy to merge it soon and RC2 tests might be good for it.

**Comment by pankajastro** [comment]
> Is it actually an error? Possibly due to lack of documentation of this connection type
> 
> As far as I remember since Airflow 1.10 (and probably earlier) Amazon Elastic Map Reduce connection stored only kwargs for [run_job_flow](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.run_job_flow) and `aws_conn_id` uses for actual `boto3` emr client connection

emr_conn_id is used in only EmrCreateJobFlowOperator and I feel it expecting that emr_conn_id extra filed should contain JSON request body for run_job_flow API. But keeping the boto3 API request body in DAG looks more convenient to me than storing it in connection and if I'm passing job_flow_overrides param in the task in that case then emr_conn_id should not be mandatory. Here, I'm doing 
- check if aws_conn_id is available, use it for AWS credential
- if aws_conn_id is not available assume that credential is in emr_conn_id
- if emr_conn_id conn extra is containing request body override with job_flow_overrides request body
- if emr_conn_id does not exist or contain AWS credentials then use job_flow_overrides as the request body
After this change, if emr_conn_id is not available then it will use aws_conn_id for auth and job_flow_overrides for the request body earlier it was failing by error `conn_id` not found

**Comment by Taragolis** [comment]
> I believe there were quite a lot of refactorings to AwsBaseHook since and I guess this is result of it - looks legit for me actually.

I've just check in 1.10.4 (I used to work with this version for about 1 year) and looks like it have the same behaviour https://github.com/apache/airflow/blob/1.10.4/airflow/contrib/hooks/emr_hook.py

If user stored some parameters in EMR Connection which not accepted by `run_job_flow` it would receive an error. 

However after this changes:
- If user will store `aws_access_key_id ` the error not happen (breaking changes?)
https://github.com/apache/airflow/blob/287fc4bdeb107fc81653d3a6721f9f5b87b90529/airflow/providers/amazon/aws/hooks/emr.py#L101 
- If user store other extra arguments from AWS Connection such as `region_name`, `profile_name`, `config_kwargs`, `session_kwargs`, and etc the error will raised

I'm never been happy with behaviour that I need provide emr connection in cases when I do not required it.

**Comment by pankajastro** [comment]
> * If user will store `aws_access_key_id ` the error not happen (breaking changes?)
>   https://github.com/apache/airflow/blob/287fc4bdeb107fc81653d3a6721f9f5b87b90529/airflow/providers/amazon/aws/hooks/emr.py#L101



> 

If the user will store aws_access_key_id in emr_conn_id extra then I'm assuming that intention to use this connection as authentication rather than using it in building request body. If you want to throw an error like the earlier case I can do that but in current case you can store the AWS JSON in emr_conn_id extra then you do not need to pass aws_conn_id pram in task

**Comment by Taragolis** [comment]
> emr_conn_id is used in only EmrCreateJobFlowOperator and I feel it expecting that emr_conn_id extra filed should contain JSON request body for run_job_flow API. But keeping the boto3 API request body in DAG looks more convenient to me than storing it in connection and if I'm passing job_flow_overrides param in the task in that case then emr_conn_id should not be mandatory.

If only case case make `emr_conn_id` non mandatory than probably better just change receiving config

```python
config = {}
if self.emr_conn_id:
    emr_conn = self.get_connection(self.emr_conn_id)
    config = emr_conn.extra_dejson.copy()
```

Assume that user provide AWS Connection rather than EMR Connection personally for me it is not good point.
I could pass `aws_conn_id=None` and assume that Airflow will use Instance Profile / Task Role

> If the user will store aws_access_key_id in emr_conn_id extra then I'm assuming that intention to use this connection as authentication rather than using it in building request body.

If user deploy Airflow in AWS Cloud and follow AWS Best Practices he/she won't use `aws_access_key_id` and most probably use Instance Profile / Task Role

Examples:
 - User use `role_arn` in EMR Connection and expected that he/she switch to this role, however error raise
 - User use `region_name` in EMR Connection and expected that region changed, however error raise

For me it is not clear why we only need to check `aws_access_key_id` ?

**Comment by pankajastro** [comment]
> For me it is not clear why we only need to check `aws_access_key_id` ?

I'm checking this since I do not want a user to use emr_conn_id to authenticate and `aws_access_key_id` is required if you want to keep the AWS auth param in conn. In case they have kept the auth param in emr_conn_id then ignore it. But I'm ok to remove that if block check if you want.

**Comment by Taragolis** [comment]
I'm just worry that docstring told that this argument for EMR Connection, but we assume that it could be AWS Connection

https://github.com/apache/airflow/blob/01a52ccb53bc805308bd085dc51ae4674dd5eb4a/airflow/providers/amazon/aws/operators/emr.py#L288-L289

I think if we want keep it simpler, allow user to skip set `emr_conn_id` and do not allow use other connection type by mistake we could simply do this

```python
config = {}
if self.emr_conn_id:
    emr_conn = self.get_connection(self.emr_conn_id)
    if emr_conn.conn_type != 'emr':
        raise AirflowError(
            f"Expected 'emr' connection type for `emr_conn_id`={self.emr_conn_id} but got {emr_conn.conn_type!r}"
        )
    config = emr_conn.extra_dejson.copy()
```

WDYT @potiuk @eladkal @pankajastro

**Comment by pankajastro** [comment]
> * `emr_conn_id` not exists - raise an error (same as current implementation)

If you want to keep this behaviour then some users will have to create emr connection having no data, which I don't want. Basically, emr_conn_id should not mandatory.

**Comment by Taragolis** [comment]
> Basically, emr_conn_id should not mandatory.

I mean if user set `emr_conn_id="this_connection_not_exists"` this connection not exists and should raise an error rather than set to empty extras. And `emr_conn_id=None` - is not mandatory.


I think it also required make changes in operator
https://github.com/apache/airflow/blob/287fc4bdeb107fc81653d3a6721f9f5b87b90529/airflow/providers/amazon/aws/operators/emr.py#L304-L305

**Comment by eladkal** [comment]
@vincbeck @ferruzzi @o-nikolas any thoughts on this one?

**Comment by Taragolis** [comment]
> We can't keep aws_conn_id and emr_conn_id default values None because if the user do pass aws_conn_id then we accuse that the value is aws_default across the operator/sensor.

BTW, `AwsBaseHook` handle case if `aws_conn_id=None` and use default boto3 behaviour 
https://github.com/apache/airflow/blob/01a52ccb53bc805308bd085dc51ae4674dd5eb4a/airflow/providers/amazon/aws/hooks/base_aws.py#L418-L422

So it doesn't raise any error now - only static checks warning in IDE
```
AIRFLOW_CTX_DAG_ID=example_emr_job_flow_manual_steps
AIRFLOW_CTX_TASK_ID=create_job_flow
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T10:28:15.046932+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-07T10:28:15.046932+00:00
[2022-06-08, 15:10:55 UTC] {emr.py:300} INFO - Creating JobFlow using aws-conn-id: None, emr-conn-id: emr_default
[2022-06-08, 15:10:55 UTC] {base.py:68} INFO - Using connection ID 'emr_default' for task execution.
[2022-06-08, 15:10:55 UTC] {credentials.py:1180} INFO - Found credentials in environment variables.
[2022-06-08, 15:10:56 UTC] {emr.py:314} INFO - JobFlow with id j-1Y1LXW4LWC1Y1 created
```

**Comment by pankajastro** [comment]
> BTW, AwsBaseHook handle case if aws_conn_id=None and use default boto3 behaviour

Yes, we can also set it here. but that too will be breaking change for someone not passing aws_conn_id in this operator param and have created a connection with the name `aws_default` https://github.com/apache/airflow/blob/287fc4bdeb107fc81653d3a6721f9f5b87b90529/airflow/providers/amazon/aws/operators/emr.py#L304

**Comment by pankajastro** [comment]
> You could use `aws_conn_id: Optional[str] = 'aws_default'` and it won't break anything
> 
> >

Then the default value won't be None it will be aws_default, right?

**Comment by pankajastro** [comment]
> 
> yep

So, if I'll change the [__init__](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/emr.py#L301) method of the operator to 
```
def __init__(
        self,
        *,
        aws_conn_id: str = 'aws_default',
        emr_conn_id: Optional[str] = 'emr_default',
        job_flow_overrides: Optional[Union[str, Dict[str, Any]]] = None,
        region_name: Optional[str] = None,
        **kwargs,
    ):
```
Then from the code execution point of view, this is effectively no change 
and if I'll do 
```
def __init__(
        self,
        *,
        aws_conn_id: str = 'aws_default',
        emr_conn_id: Optional[str] = None,
        job_flow_overrides: Optional[Union[str, Dict[str, Any]]] = None,
        region_name: Optional[str] = None,
        **kwargs,
    ):
```
Then this will be a breaking change if someone has created emr_conn_id with the name emr_default and not passing emr_conn_id param in operator, isn't it?

**Comment by Taragolis** [comment]
> Then this will be a breaking change if someone has created emr_conn_id with the name emr_default and not passing emr_conn_id param in operator, isn't it?

Yeah, you right, for example EMR example DAG doesn't set `emr_conn_id`, it probably won't hurt if it uses empty connection. But if user previously stored some values in `emr_conn_id` it will

https://github.com/apache/airflow/blob/047a6162b0b4cbf07fe2fd978e335839a7d3900b/airflow/providers/amazon/aws/example_dags/example_emr.py#L77-L80

So it would be nice update docstring about behaviour of  `emr_conn_id` as well as for `aws_conn_id` (it could be grabbed from AwsBaseHook)

https://github.com/apache/airflow/blob/047a6162b0b4cbf07fe2fd978e335839a7d3900b/airflow/providers/amazon/aws/hooks/base_aws.py#L378-L383

**Comment by pankajastro** [comment]
Updated docstring here 140a26d224863ad4be9c0baa0cb4af7b88487e9b

**Comment by pankajastro** [comment]
Hey guys, just wanted to check if I need to address anything more here?

**Comment by dacort** [comment]
I was also OOO, but looks like this is already taken care of. Feel free to ping me in the future for any EMR-related questions.

**Pull request merged**
