### PR TITLE
[Draft] Implement Dag SLAs

### LINKED ISSUE #32816: AIP-57 - Implement DAG SLAs
### Description

Implement DAG SLAs as outlined in [AIP-57](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-57+Refactor+SLA+Feature)

This will require the addition of 2 new DAG attributes, and 1 new Dagrun attribute:
[DAG.sla](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L388): None | timedelta
[DAG.on_sla_miss_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L388): None | DagStateChangeCallback | list[DagStateChangeCallback]
[Dagrun.sla_missed](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L118): None | bool

In addition, [Dagrun.update_state](https://github.com/apache/airflow/blob/main/airflow/models/dagrun.py#L522) and [Dag.handle_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L1315) functions must be updated to handle SLA evaluation and SLA miss callbacks.

We will also mark the existing [DAG.sla_miss_callback](https://github.com/apache/airflow/blob/main/airflow/models/dag.py#L407) for deprecation.

### Use case/motivation

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by sungwy**
closes #32816

### Summary

This PR introduces Dag SLAs as a part of **AIP-57 Refactor SLA Feature**.

After many discussions, the community has voted to introduce new SLA features aimed at replacing the existing SLA feature which has caused a lot of confusion and dissatisfaction in the user base over the years. The proposal introduces SLAs that are measured and contained within the lifetime of a Dag Run, and within the lifetime of a Task Instance which cost significantly less for the Airflow Infrastructure to compute than the existing concept of SLAs. The proposed SLA callback functions will also accept the TI context as the argument, which is a parameter that is used by other callback types (on_success_callback, on_failure_callback, on_execute_callback) to honor a consistent interface.

#### Added 
        sla: timedelta | None = None
        on_sla_miss_callback: None | DagStateChangeCallback | list[DagStateChangeCallback] = None

#### Marked for Deprecation
        sla_miss_callback: None | SLAMissCallback | list[SLAMissCallback] = None

#### Added 
        sla_missed = Column(Boolean, default=False)

#### Added
        sla_miss: bool | None = False
        dagrun_state: DagRunState
#### Removed
        is_failure_callback: bool | None = True

### Dag SLA Measurement Semantics 
SLA tracking logic is evaluated when the active Dag Run is checked for updates using DagRun.update_state which is executed in the main scheduling loop. Dag SLA is tracked for all run types except for DagRunType.BACKFILL_JOB if **sla** parameter is provided in the Dag definition. 

If **sla_missed** attribute of the Dag Run is already set to True, the scheduler loop will skip the SLA check for that dag run. This condition ensures that the SLA miss callback is generated only once when a scheduler loop has detected that the dag run has just missed its SLA and has been made the corresponding Dag Run record update in the DB.

SLA is measured against the time between the Dag Run start_date (time) and the current time. If SLA is less than the time between the current time and the Dag Run start_date, SLA has been missed for the active Dag Run. Using the start_date (instead of the scheduled start time according to the time table) allows us to keep a consistent measuring pattern across MANUAL and SCHEDULED run types, and keep the SLA evaluation logic simple for the initial version of this feature.

SLA callback is indicated by the sla_miss boolean flag on DagCallbackRequest. The State of the DagRun corresponding to the DagCallbackRequest is propagated through the dagrun_state parameter, which is also used to deduce whether a on_success_callback or a on_failure_callback must be executed along with the request. It is now possible for a DagCallbackRequest to be issued without a finished DagRun State (SUCCESS or FAILED); it is upto dagrun.handle_callback function to parse the parameters and execute the appropriate callback related to the given DagRun State or sla_miss flag.

### Question:
Do we need to consider the impact of removing is_failure_callback from DagCallbackRequest and replacing it with dagrun_state? If DbCallbackRequest is enabled and unexecuted DagCallbackRequests are stored in the DB at the time of DB upgrade, would it lead to some callbacks not being executed?
EDIT: I've added an alembic migration step that unpacks the json callback_data and programmatically updates the json payload with the logical mapping of is_failure_callback <-> dagrun_state for DagCallbackRequest callback_types of DbCallbackRequest records. I wanted to get others' thoughts on whether this suggestion improves the reliability of the migration or makes it more risky.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by syun64** [comment]
While I wait for feedback on the PR - I'm trying to fix the breaking test **tests/jobs/test_backfill_job.py::TestBackfillJob::test_mapped_dag_unexpandable**, and I'm quite perplexed at how it's failing non-deterministically on the CI. 

In the previous CI run before I merged the main into this branch, the test succeeded on [Postgres11,Py3.8: Core Providers[-amazon,google] Other Providers[amazon] WWW API Always CLI Providers[google]](https://github.com/apache/airflow/actions/runs/5913993194/job/16038904393?pr=33532#logs), but failed on the most recent run: [Postgres11,Py3.8: Core Providers[-amazon,google] Other Providers[amazon] WWW API Always CLI Providers[google]](https://github.com/apache/airflow/actions/runs/5914162025/job/16039246990?pr=33532#logs). Now it's succeeding on Tests that failed on the previous CI run like on [LatestBotoPostgres11, Py3.8: Core Providers[-amazon,google] Other Providers[amazon] WWW API Always CLI Providers[google]](https://github.com/apache/airflow/actions/runs/5914162025/job/16039247433?pr=33532#logs).

I'm unable to reproduce this issue on my local breeze setup - the test passes with flying colors after I've added the new parameters into the factory function in airflow.models.dag. Does anyone have any pointers regarding where I should be looking to debug this issue?

**Comment by uranusjr** [comment]
Looks like it’s a separate bug triggered by an unrelated change. I’m guessing there might be a set or something unordered involved that changes behaviour depending on some external factors. I’ll look into it separately.

**Comment by syun64** [comment]
> Looks like it’s a separate bug triggered by an unrelated change. I’m guessing there might be a set or something unordered involved that changes behaviour depending on some external factors. I’ll look into it separately.

Thank you very much for letting me know @uranusjr 👍

**Comment by syun64** [comment]
This PR requires the patch from https://github.com/apache/airflow/pull/35256

**Comment by syun64** [comment]
This PR was based on an old branch, and got into a messy state after many iterations of rebasing. Closed in favor of https://github.com/apache/airflow/pull/36024

**Pull request closed without merging**
