### PR TITLE
Use typed Context EVERYWHERE

### PR DESCRIPTION
**Pull request by potiuk**
Part of #19891

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Looks like the global Context replace worked flawlessly :) . All tests are geting green :)

**Comment by potiuk** [comment]
Just 214 files :)

**Comment by potiuk** [comment]
It's - surprisingly - indeed green :)

**Review by jedcunningham — APPROVED** [review]
Looked through all the diffs (phew).

**Pull request merged**
