### PR TITLE
[AIRFLOW-722] Add Celery queue sensor

### PR DESCRIPTION
**Pull request by duffn**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- *https://issues.apache.org/jira/browse/AIRFLOW-722*

Testing Done:
- Unsure how to properly test this and am open to suggestions.

### CODE REVIEW

**Comment by jhsenjaliya** [comment]
should this go under airflow/contrib/sensors ?

**Comment by duffn** [comment]
Yes, I believe you are correct. I have moved the sensor to contrib.

**Comment by jhsenjaliya** [comment]
+1 LGTM

**Comment by duffn** [comment]
I'm unfamiliar with landscape.io. How did the check fail despite the fact that none of the files in question were in my commit?

**Comment by jhsenjaliya** [comment]
@r39132 , can you please take a look here? is landscape doing code quality check on entire code base rather than just for the diff ?

**Comment by duffn** [comment]
The file in question that was causing the landscape.io errors (https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/operators/gcs_to_bq.py) has been corrected in a separate commit by another contributor. 

I have rebased and the checks now pass.

**Comment by bolkedebruin** [comment]
@duffn Looks good, but can you please add unit tests.

**Comment by duffn** [comment]
@mschmo join in on the fun.

**Comment by ron819** [comment]
@duffn are you still working on this?

**Comment by duffn** [comment]
I have not worked on this in awhile, though I do know it is still in production at my former company.

**Comment by ron819** [comment]
@bolkedebruin is there something else needed here?

**Comment by feng-tao** [comment]
I think this pr is useful. Let me finish up this pr given the original pr owner doesn't have time to finish it.

**Pull request closed without merging**
