### PR TITLE
Added Xcom to work with DockerSwarmOperator

### PR DESCRIPTION
**Pull request by foxlooo**
This works exactly the same as how DockerOperator currently uses it

---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by foxlooo** [comment]
I didn't write any unit tests for this but could you confirm whether I need to do it for this?
The reason why was because this is almost exactly the same as the DockerOperator function (which is the super of this class).

**Comment by mik-laj** [comment]
@foxlooo  We should write a test to prevent regression. We now know that XCOM works, but that may change in the future.

**Comment by foxlooo** [comment]
Are the tests that you mention run through CI/CD? Could you also direct me to which folder the tests are located? 
Sorry this is my first time working on an open source project, thanks for all your help!

**Comment by mik-laj** [comment]
Yes. We use CI/CD for running unit/integration tests. 
You can find all tests for this module here:
https://github.com/apache/airflow/blob/master/tests/providers/docker/operators/test_docker_swarm.py

If you are interested in testing, we also have documentation that describes our setup:
https://github.com/apache/airflow/blob/master/TESTING.rst

> Sorry this is my first time working on an open source project, thanks for all your help!

I hope you'll enjoy contributing to OOS and it won't be your last contribution. 🐅

**Comment by foxlooo** [comment]
Sorry, I didn't realize it before but if I do a commit, it does a retest on your system, should I close this pull request until I finish the unit tests?

**Comment by mik-laj** [comment]
@foxlooo You do not need. Just when you finish work, call the reviewer.

**Pull request closed without merging**
