### PR TITLE
[AIRFLOW-2900] Show code for packaged DAGs

### PR DESCRIPTION
**Pull request by jakebiesinger**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2900
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Packaged DAGs currently fail on the `Code` page with the error `[Errno 20] Not a directory: ...`

screenshot 2018-08-14 at 11 22 46 am

This PR fixes the screen:

screenshot 2018-08-14 at 11 21 22 am

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

  - Tests added for open_maybe_zip
  - Manual testing of the Code screen

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Great, please add the rbac view changed as well. `www` will disappear soon.

**Comment by jakebiesinger** [comment]
Done. Travis whined about python3 so I updated to use `io.open` and tested again manually.

Is there a way to force the www_rbac code path in a local `airflow webserver`? I'm a n00b here and had no idea that path even existed.

**Comment by jakebiesinger** [comment]
Travis passes w/the exception of flake8, which is not passing due to monkey-patching that pep8 doesn't like https://github.com/apache/incubator-airflow/blob/master/airflow/www_rbac/utils.py#L21

Not sure what you want me to do there... if you monkey-patch that way, pep8 will yell that the subsequent imports aren't at the top of the file.
screenshot 2018-08-14 at 4 41 16 pm

**Comment by ashb** [comment]
> Is there a way to force the www_rbac code path in a local airflow 

Check out UPDATING.md for 1.10 - I think it's `rbac = True` in the `webserver` section, plus you'll need to create a user.

**Comment by ashb** [comment]
To fix the flake8 error change line 21 to:

```
standard_library.install_aliases()  # noqa: E402
```

**Comment by jakebiesinger** [comment]
flake8 errors fixed in latest version of the last commit.

**Comment by jakebiesinger** [comment]
I've also successfully tested using the rbac UI.

screenshot 2018-08-15 at 9 03 29 am

**Comment by jakebiesinger** [comment]
Friendly ping!

**Comment by kaxil** [comment]
@jakebiesinger Can you please resolve the conflicts and it should be ready for merge :) ? 

Thank you for fixing this

**Comment by jakebiesinger** [comment]
Done.

**Comment by kaxil** [comment]
@jakebiesinger Can you please squash your commits?

**Comment by jakebiesinger** [comment]
@kaxil merged and squashed into a single commit.

**Comment by bolkedebruin** [comment]
All ci builds failed, you check what is going on? It would be great to have this in

**Comment by kaxil** [comment]
@jakebiesinger Follow is the error:
```
======================================================================
29) ERROR: test_open_maybe_zipped_archive (tests.www.test_utils.UtilsTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_mysql/lib/python2.7/site-packages/mock/mock.py line 1305 in patched
      return func(*args, **keywargs)
    tests/www/test_utils.py line 218 in test_open_maybe_zipped_archive
      mocked_open.assert_called_once()
   NameError: global name 'mocked_open' is not defined
```

**Comment by jakebiesinger** [comment]
Thanks, @kaxil. Looks like I had a bad merge when I squashed my commit.  Should be working now.

**Comment by kaxil** [comment]
Awesome, Great work.

**Review by kaxil — APPROVED** [review]
LGTM

**Pull request merged**
