### PR TITLE
Enforce js linting for current ui in pre-commit

### LINKED ISSUE #14154: Add/enforce ESLint (JavaScript linting) in pre-commit hooks
There is already an existing ESLint configuration and supporting `yarn lint` commands, it just needs to be integrated into pre-commit.

This will prevent errors and ensure consistent style/syntax is utilized throughout the codebase.

I made a previous attempt at resolving it several months ago in #11699. While I had it working locally, I was unable to get it executing properly in our CI environment.

**Related Issues**

We're working on migrating our inline JavaScript to external files (#14115). I'm not sure that is a pre-requisite for this issue, but the order of execution will certainly affect the scope.

### PR DESCRIPTION
**Pull request by bbovenzi**
Add a new pre-commit hook to lint javascript in `airflow/www/static/js/` using ESLint.

To get linting to pass this PR also fixes all linting errors (there are still warnings, but they don't cause the hook to fail). Also, the rule `no-param-reassign` was changed to a warning instead of error because it would require major refactoring of all d3 implementations

Closes #14154

Since there are so many changes, we probably do not want this to be part of 2.1.0

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
How much did you test all the JS after changing it?

(I'm wondering about not merging this until after 2.1 is branched.)

Oh lol -- you said that too. Yeah, lets hold off until 2.1 is out.

**Comment by potiuk** [comment]
Nice one. Agree we should wait :)

**Comment by ashb** [comment]
@bbovenzi Could you rebase please?

**Comment by bbovenzi** [comment]
@ashb rebased. Do you want to restart the CI?

**Comment by bbovenzi** [comment]
@ashb looks like it's all passing again

**Review by ashb — APPROVED** [review]

**Pull request merged**
