### PR TITLE
Add td_format function and apply to Views duration column for better human readability

### PR DESCRIPTION
**Pull request by Acehaidrey**
This PR came out of the review for: https://github.com/apache/airflow/pull/19921. There was a review for adding an updated view for displaying the duration column in a more readable way.

To be determined if the same application to the TI views are desired as this PR has done so. Otherwise this is just to be a tool to translate some timedelta, or float/int, into the smallest grouped unit of measure to declare how long the duration has been running.

One open question is, is it preferred to make it optionable to apply this change to display the duration as this readable way vs the original timedelta way.

image

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).
Screen Shot 2021-12-09 at 2 30 15 PM

### CODE REVIEW

**Comment by uranusjr** [comment]
Need to fix many errors in linters and tests

**Comment by Acehaidrey** [comment]
@uranusjr sorry I didn't realize it created PR already. Working on it now!

**Comment by Acehaidrey** [comment]
@uranusjr - I don't know what is going on with my build but these import failures of Union I don't have locally. I've tried a few things but can't get this happening on mine. Mind verifying if you apply this change do you see same thing?

**Comment by uranusjr** [comment]
Your local code is different from the code in the PR. The error is pretty straightforward; `Union` is not imported in `timezone.py`, so Python errors.

**Comment by Acehaidrey** [comment]
@uranusjr oh my God, I am sorry, yes locally I have it imported. But I also merged the code. Let me pull it down. Something is off in my local -

**Comment by Acehaidrey** [comment]
@bbovenzi mind looking?

**Review by bbovenzi — COMMENTED** [review]
Looking good. I'm wondering if we should do a `01:00:02` format instead. It would be more compact. In the react tree view we even add a day count like `5d01:00:02`. That seems readable to me but I'm open to suggestions.

**Comment by Acehaidrey** [comment]
@bbovenzi when you recommend that format, `01:00:02` that is what it currently is. That is how the timedeltas look right now if I'm not mistaken. Unless you are looking for something that goes 5d:4h:32m:45s is that what you're recommending?

I'd like to get this in as soon as possible this week so if you don't mind quickly iterating with me to complete the ask.

**Comment by kaxil** [comment]
> @bbovenzi when you recommend that format, `01:00:02` that is what it currently is. That is how the timedeltas look right now if I'm not mistaken. Unless you are looking for something that goes 5d:4h:32m:45s is that what you're recommending?
> 
> I'd like to get this in as soon as possible this week so if you don't mind quickly iterating with me to complete the ask.

`01:00:02` vs '1 hour, 2 seconds' (this is what the PR does currently, no?). I think that is what Brent is suggesting.

I am fine with either, I don't have a strong opinion on it.

**Review by kaxil — APPROVED** [review]
Logic wise looks good to me. I defer to @bbovenzi on the exact format

**Comment by kaxil** [comment]
>One open question is, is it preferred to make it optionable to apply this change to display the duration as this readable way vs the original timedelta way.

hmm, maybe a config or a profile setting -- not sure @bbovenzi @ryanahamilton thoughts?

**Comment by Acehaidrey** [comment]
Thanks for the discussion. I've just made some updates here, waiting for tests to pass then will burden you with review :)

**Pull request merged**
