### PR TITLE
Bump sphinx-autoapi to >=1.5

### PR DESCRIPTION
**Pull request by uranusjr**
We need at least 1.5.0 for `typing.overload` support, but I’m relaxing to include all future 1.x because why not. See #20011.

### CODE REVIEW

**Comment by ashb** [comment]
```
  apache-airflow                                               Traceback (most recent call last):
  apache-airflow                                                 File "/opt/airflow/docs/exts/docs_build/run_patched_sphinx.py", line 23, in <module>
  apache-airflow                                                   from autoapi.extension import (
  apache-airflow                                               ImportError: cannot import name 'default_backend_mapping' from 'autoapi.extension' 
  (/usr/local/lib/python3.7/site-packages/autoapi/extension.py)
```

Now that we're upgradaing autoapi we can entirely avoid run_patched_sphinx.py s the work-around we are applying is included.

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
cc @mik-laj

**Comment by potiuk** [comment]
Just one watchout - I am afraid many more changes are needed for that. As far as I remember there was a problem with Sphinx-autoapi support related to namespace packages (but I remember it vaguely) and there are some workarounds and sphinx patching https://github.com/apache/airflow/blob/main/docs/exts/docs_build/run_patched_sphinx.py to make it works. So upgrading autoapi might turn into much bigger task than you think (but I believe  it is a long overdue one so maybe worth doing it).

**Comment by potiuk** [comment]
AH I see @ashb already commented about it.

**Comment by mik-laj** [comment]
In the past, I worked on upgrade for sphinx-autoapi. https://github.com/apache/airflow/pull/15206/files. but I didn't have enough power to finish it.

**Comment by uranusjr** [comment]
Ugh, I give up. Let’s just hide the overloaded definitions from autoapi. (Why are we using autoapi in the first place?)

**Comment by potiuk** [comment]
> Ugh, I give up. Let’s just hide the overloaded definitions from autoapi. (Why are we using autoapi in the first place?)

Now there are 4 of us that gave up after trying. Do I see a pattern here? (and yeah @mik-laj  - why do we use autoapi ?)

**Comment by mik-laj** [comment]
It was the only tool I found at the moment that generated files for each class without having to manually create the files. We too were constrained by RTD.

**Comment by uranusjr** [comment]
There’s a new effort in #20079.

**Pull request closed without merging**
