### PR TITLE
control task group concurrency: use allow list for mapping index [another way]

### PR DESCRIPTION
**Pull request by mis98zb**
Another way for #32122.
Filter out TIs by group concurrent limitation in scheduling stage, not int queuing stage.

### CODE REVIEW

**Comment by mis98zb** [comment]
have a test on our test environment with nest groups, expanding on outter group.
DAG can be run correctly.
However, in the web GUI, the inner group cannot show expand items.
image

**Comment by uranusjr** [comment]
I haven’t checked the logic in detail, but from a quick glance this does seem to be cleaner and more straightforward than #32122.

Is the inner group not showing expanded items a UI only issue? (Put in another way, is this due to we not provide enough information on the task groups in `views.py`, or is the frontend code not handling the information correctly?)

**Comment by mis98zb** [comment]
Seems it's only UI issue.
The DAG can be run successfully, and in the logging folder, the map index is correctly recorded.

For example:
image
`market_process_group.aggregate.waitScopeJob` is shown without map index in web UI, however, the log file record map index correctly.

**Comment by uranusjr** [comment]
Awesome, that should not be too difficult to fix

**Pull request closed without merging**
