### PR TITLE
[AIRFLOW-XXX] Split extra packages table in multiple

### PR DESCRIPTION
**Pull request by mik-laj**
The current table is too large and is very difficult to use. I divided it into several smaller tables that allow you to find the right packages faster.

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
Not sure I completely agree. It is easier to search in a single table that is alphabetically sorted.

Also if we make this change it would be I wouldn't have a separate `Apache software` and `software` separately.

**Comment by mik-laj** [comment]
As an Apache foundation project, we should promote other projects that are that foundation.  This allows you to build a strong community.

This layout will be uniform with the layout that is in Operators and Hooks Reference: https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#asf-apache-software-foundation
In my opinion, this layout allows you to find faster, because the most used things are in a separate table - foundament. Very often, when you want to install something, you try to look for a specific type of integration. If you have resources, you are looking for software. If you have limited resources, you try to find a service that can do it for you. This is a very clear division in my opinion.

**Comment by feluelle** [comment]
Agree with @mik-laj 
I am also in favor of pointing out Apache projects.

**Comment by kaxil** [comment]
> As an Apache foundation project, we should promote other projects that are that foundation. This allows you to build a strong community.
> 
> This layout will be uniform with the layout that is in Operators and Hooks Reference: https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#asf-apache-software-foundation
> In my opinion, this layout allows you to find faster, because the most used things are in a separate table - foundament. Very often, when you want to install something, you try to look for a specific type of integration. If you have resources, you are looking for software. If you have limited resources, you try to find a service that can do it for you. This is a very clear division in my opinion.

Makes Sense

**Pull request merged**
