### PR TITLE
New provider for Magento open  source

### PR DESCRIPTION
**Pull request by sivajik34**
This pull request introduces a new Magento provider for Apache Airflow. This provider includes basic operators and hooks to facilitate interaction with Magento's API, allowing users to efficiently fetch and process Magento orders and other related data.

Features Implemented:

GetOrdersOperator:

Fetches sales orders from Magento based on the specified status.
Integrates with Magento's REST API to retrieve order details.

Key Components:

MagentoHook: A hook to connect and interact with Magento's API using OAuth authentication.
GetOrdersOperator: Custom operator to retrieve sales orders from Magento.

Configuration:

Magento Connection: Configure the Magento connection (magento_default) in Airflow to provide OAuth API credentials.

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Please check the [accepting new community providers documentation](https://github.com/apache/airflow/blob/main/PROVIDERS.rst#accepting-new-community-providers) and follow the steps.

**Comment by potiuk** [comment]
And to add to what @hussein-awala wrote - it's not very likely we will accept magento as managed by the community - we need to be able to support providers in the community and I guess magento is something rather niche that is likely better to host and release as your own provider @sivajik34 - there is no particular reason we should accept every single e-commerce provider as something that Airflow community will manage - it's much better to be managed by somoene who uses and cares about magento (i.e. you or magento community in general).

Just to set expectations - taking over support for such providers be the community is a liability not an asset and we are not going to take it over unless

a) community is convinced it is very popular and its' good to be managed in the Airflow communiyt
b) community is convinced that there is a reputable entitty that wil make sure all integration is working there 

See system test dashboards https://airflow.apache.org/ecosystem/#airflow-provider-system-test-dashboards

**Comment by kodurusivakumar34** [comment]
@potiuk

Thank you for your feedback on the pull request for the Magento provider. I understand the concerns raised and would like to address them with two proposed solutions:

**Option 1: Separate Repository for Third-Party Providers**

I propose creating a dedicated repository for third-party providers that are less central to the core Airflow functionality. This repository would serve as a central location where users can find and review all available third-party providers. It would also simplify the process for contributors to add new providers and for users to discover them. 

**Pros:**
- Keeps the main Airflow repository focused on core providers.
- Provides a single location for all third-party providers.
- Simplifies contribution and discovery of third-party providers.

**Cons:**
- Users would need to check a separate repository for third-party providers.
- Requires additional effort to maintain and coordinate updates across repositories.

**Option 2: Separate Folder with Flag in `provider.yaml`**

Alternatively, we could maintain third-party providers within a designated folder in the main repository and use a flag in the `provider.yaml` file to distinguish between core and third-party providers. This approach would keep everything within the main repository while clearly indicating the status and type of each provider.

**Pros:**
- Keeps all providers within a single repository for easier access.
- Allows clear differentiation between core and third-party providers.
- Immediate awareness of third-party providers through the `provider.yaml` flag.

**Cons:**
- Potential for increased clutter within the main repository.
- Requires additional management for the flag system in `provider.yaml`.

I am open to discussing these options further or considering any other recommendations the community may have. My goal is to contribute to Airflow in a way that aligns with best practices and meets the needs of the community.

Thank you for your consideration.

**Comment by raphaelauv** [comment]
@sivajik34 what is magento ?

is this project https://github.com/magento/magento2 ?

**Comment by kodurusivakumar34** [comment]
@raphaelauv Yes. It is an ecommerce framework.

Adobe commerce is an enterprise product.
Magento is Open source product.
Magento open source+ extra features= Adobe commerce.

**Comment by potiuk** [comment]
@kodurusivakumar34 -> Those options are not really feasible. Apache Airflow is a project belonging to the Apache Software Foundation and whatever we keep and release - formally - as an "Apache Software Foundation software" has to be released formaly and legally using the ASF processess and governance - that includes responsibilty for managing the releases, security fixes, and more - PMC members have to approve and review every such release and we cannot endores or promote 3rd-party managed software to be released without the overhead incurred: review process, PMC and committers approval, licence compliance, security process and policies clear maintenance rules etc. etc.

Anything that is released or hosted in "apache" repositories, has to have the ASF "stamp of approval" so to speak.

You can start reading here if you are interested https://www.apache.org/legal/release-policy.html  - but there are more links to follow when you read it. This is legal, compliance and governance issue, not a technical issue which prevents the ASF to be legally responsible for 3rd-party software that it does not have any control over, once the software gets contributed to the ASF it becomes "The ASF" software - with all the requirements and expectations that come with it.

But there is nothing to prevent any other entities to build such a repository of 3rd-party providers or index them. For example there is https://registry.astronomer.io/ where you can browse various airflow providers. And you - or anyone else - can release magento provider on their own and submit it to such registries.

**Comment by potiuk** [comment]
BTW. This is where https://airflow.apache.org/ecosystem/ page exist. If you look at the top:

> These resources and services are not maintained, nor endorsed by the Apache Airflow® Community and Apache Airflow project (maintained by the Committers and the Airflow PMC). Use them at your sole discretion. The community does not verify the licences nor validity of those tools, so it’s your responsibility to verify them.

> If you would you like to be included on this page, please reach out to the [Apache Airflow dev or user mailing list](https://airflow.apache.org/community/) and let us know or simply open a Pull Request to that page.

We simply cannot - according to the ASF rules - mix "community" and "3rd-party" software - and such "ecosystem" page with clear indication that this is 3rd-party is the way we "clearly separate" these.

**Comment by potiuk** [comment]
BTW. I see you already have https://github.com/sivajik34/magento-airflow I see you already host your provider. So the easiest way to make it discoverable is to add link to it to the "ecosystem" page.

**Comment by sivajik34** [comment]
Thank you for your feedback. I  will maintain as separate repo.
https://pypi.org/project/apache-airflow-provider-magento
https://github.com/sivajik34/magento-airflow/tree/main

**Comment by potiuk** [comment]
> Thank you for your feedback. I will maintain as separate repo. https://pypi.org/project/apache-airflow-provider-magento https://github.com/sivajik34/magento-airflow/tree/main

One thing though. We do not want to enforce it - and cannot prevent people from creating such name, but generally I think you should not use "apache-airlfow-providers-magento" as provider name - it suggests it is an "apache" provider where it is not, so I would kindly ask you to change the PyPI name and handle the ownership of that name in PyPI to the "Apache Airlfow" pypi organization. You can add me as an owner (`@potiuk`) and I can transfer it there.

**Comment by potiuk** [comment]
That's not very strong request just request to make a clear distinction - again - we probably won't foirce any action there - even if we could (Apache Airflow is now registered trademark in the US), it's more of a kind request - since it is up 25 minutes, it's likely way easier to change it now rather than some time in the future.

**Comment by sivajik34** [comment]
Sure .Yesterday I published, I will try to change the name. Thank you

**Comment by potiuk** [comment]
> Sure .Yesterday I published, I will try to change the name. Thank you

Thanks for being responsive - really appreciate!

**Pull request closed without merging**
