### PR TITLE
BugFix: Fix writing & deleting Dag Code for Serialized DAGs

### PR DESCRIPTION
**Pull request by kaxil**
With `store_dag_code` enabled scheduler throws the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line
297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py",
line 158, in _run_file_processor
    pickle_dags)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py",
line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py",
line 1582, in process_file
    dag.sync_to_db()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py",
line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py",
line 1519, in sync_to_db
    DagCode.bulk_sync_to_db([dag.fileloc for dag in orm_dag])
TypeError: 'DagModel' object is not iterable
```

This is a blocker for 1.10.10 and the bug was found in 1.10.10rc2 by Kostya Esmukov 

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by kaxil** [comment]
Tests have passed, failing tests is for Generating requirements.txt and is unrelated

**Comment by KostyaEsmukov** [comment]
@kaxil Thank you for the patch! I've applied it on my installation, and the `dag_code` table filled with rows.

However, new errors appeared in scheduler:

```
Process DagFileProcessor35-Process:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 158, in _run_file_processor
    pickle_dags)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1582, in process_file
    dag.sync_to_db()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py", line 1519, in sync_to_db
    DagCode.bulk_sync_to_db([orm_dag.fileloc], session=session)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 131, in bulk_sync_to_db
    orm_dag_code.last_updated = timezone.utcnow()
UnboundLocalError: local variable 'orm_dag_code' referenced before assignment
```

and

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/dag_processing.py", line 624, in _run_processor_manager
    processor_manager.start()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/dag_processing.py", line 856, in start
    self._refresh_dag_dir()
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/dag_processing.py", line 928, in _refresh_dag_dir
    DagCode.remove_deleted_code(self._file_paths)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 151, in remove_deleted_code
    cls.fileloc.notin_(alive_dag_filelocs))).delete())
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3789, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1696, in exec_
    self._do_pre_synchronize()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1778, in _do_pre_synchronize
    from_=err,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Could not evaluate current criteria in Python: "Cannot evaluate clauselist with operator <function comma_op at 0x7f14acf61440>".
 Specify 'fetch' or False for the synchronize_session parameter.
```

Do these look like related bugs?

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
> Tests have passed, failing tests is for Generating requirements.txt and is unrelated

Yep. Rebase should help with that.

**Comment by kaxil** [comment]
@KostyaEsmukov Can you please check now with the patch in this PR. 🤞 All problems should be solved

**Comment by KostyaEsmukov** [comment]
@kaxil Thanks for the fix! The scheduler errors are gone, but on a stateless webserver the code is still not rendered, because, apparently, `DagCode` instance always tries to read the code from a local file during initialization:

```
>>> DagCode(dag_orm.fileloc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 59, in __init__
    self.source_code = DagCode._read_code(self.fileloc)
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 63, in _read_code
    with open_maybe_zipped(fileloc, 'r') as source:
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/file.py", line 102, in open_maybe_zipped
    return io.open(fileloc, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '<...my_dag...>'
```

Notice the `_read_code` line.

**Comment by kaxil** [comment]
> @kaxil Thanks for the fix! The scheduler errors are gone, but on a stateless webserver the code is still not rendered, because, apparently, `DagCode` instance always tries to read the code from a local file during initialization:
> 
> ```
> >>> DagCode(dag_orm.fileloc)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<string>", line 4, in __init__
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
>     manager.dispatch.init_failure(self, args, kwargs)
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
>     exc_value, with_traceback=exc_tb,
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
>     raise exception
>   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
>     return manager.original_init(*mixed[1:], **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 59, in __init__
>     self.source_code = DagCode._read_code(self.fileloc)
>   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagcode.py", line 63, in _read_code
>     with open_maybe_zipped(fileloc, 'r') as source:
>   File "/usr/local/lib/python3.7/site-packages/airflow/utils/file.py", line 102, in open_maybe_zipped
>     return io.open(fileloc, mode=mode)
> FileNotFoundError: [Errno 2] No such file or directory: '<...my_dag...>'
> ```
> 
> Notice the `_read_code` line.

Are you on Airflow Slack (https://apache-airflow-slack.herokuapp.com/), would you mind signing up if you are not so that we can check this together :)

**Pull request merged**
