### PR TITLE
[AIRFLOW-1516] Fix error handling getting fernet

### PR DESCRIPTION
**Pull request by edgarRd**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1516

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

There were unhandled cases for exceptions when importing fernet in
`airflow/models.py`. This seems to be a remanent of a previous refactor,
replacing logic that would depend on the definition of a global variable
for Fernet if it was imported correctly.

Generally catching all exceptions from get_fernet function, given that
other functions are already handling it that way and the only
error handling case here is to not use encryption.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This change does not affect any the desired logic on failure condition, ultimately avoiding use of encryption if we can't encrypt.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by edgarRd** [comment]
@saguziel @aoen @bolkedebruin

**Comment by saguziel** [comment]
Seems sketchy, especially since we aren't logging the exception

**Comment by edgarRd** [comment]
We could log the error, but usually the handling through the code is the same - fallback to non encrypted values when fernet fails to load.

**Comment by saguziel** [comment]
lgtm

**Pull request closed without merging**
