### PR TITLE
[#38284] Update Confirmation Logic for Config Changes on Sensitive Environments Like Production

### LINKED ISSUE #38284: Dag trigger confirmation popup for Production Environment
### Description

My team and I are currently working with Airflow, and we manage multiple environments: Development, Staging, and Production. Occasionally, we need to access the Production Airflow to read logs for data analysis. However, we've encountered an issue three times where a team member accidentally triggered a DAG in the Production environment.

I'm wondering if there is an existing solution to prevent this?

If not, I'd like to suggest a feature where if the environment is set to Production, Airflow would display a confirmation popup before triggering a DAG. This would ask the user to confirm if they indeed wish to proceed with the trigger.

### Use case/motivation

To prevent accidental triggering of DAGs in the Production environment by adding an additional layer of confirmation for user actions.

### What would you like to happen?
 I'd like Airflow to display a confirmation popup asking for user confirmation before allowing a DAG to be triggered in the Production environment.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
   - https://github.com/apache/airflow/pull/38299

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by maycuatroi1**
# Description

I've added a configuration option `require_confirmation_dag_change` to both the `config.yml` and the Flask App. Its default value is `False`. However, when a user sets this configuration to `True`, the Dag screen (`Dag.html`) will enforce a logic that requires users to confirm before they can Trigger a DAG or Pause/UnPause a Dag. 

This feature is particularly effective for teams working across multiple environments, including sensitive ones like Production. 
Note: The confirmation is similar to the confirmation box displayed when deleting a Dag.

# Related issue:
- Resolve: #38284

# Test Screen
image

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
It looks good.
[Here](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst) is the static checks doc you need to fix the failed tests.

**Comment by maycuatroi** [comment]
@hussein-awala I've fixed the static check issue. Thank you for your advice.

**Review by potiuk — APPROVED** [review]

**Comment by maycuatroi** [comment]
@potiuk  sorry for taking your time. I'm fixed the ruff check. Please approve trigger the workflow to run test. 🙆‍♂️

**Review by hussein-awala — APPROVED** [review]

**Comment by hussein-awala** [comment]
Congrats on your first commit 🎉

**Comment by xjchew** [comment]
May I suggest that this be added to `dags.html` as well?

**Comment by maycuatroi** [comment]
> May I suggest that this be added to `dags.html` as well?

`dags.html` is the Dags list screen. I believe this change is necessary, and I'll create a PR to update it.

**Pull request merged**
