### PR TITLE
Add CodeQL security scanning on pull requests.

### PR DESCRIPTION
**Pull request by potiuk**
Apparently we only run codeql on main, but we could run it on PRs as well. That's a good idea to test how it can look like.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
This seems to work well.

**Review by amoghrajesh — COMMENTED** [review]
LGTM +1
Should we just mark 2-10* specifically?

**Comment by potiuk** [comment]
> LGTM +1 Should we just mark 2-10* specifically?

We have the same pattern elsewhere - and we are going to have 2.11 in the future, so better to keep it this way I think.

**Comment by potiuk** [comment]
And in the future we will have 3_0, 3_1 etc. ....

**Review by amoghrajesh — APPROVED** [review]

**Review by gopidesupavan — APPROVED** [review]

**Pull request merged**
