### PR TITLE
Task names should be consistent with variable names (drop vs create) in example dags

### PR DESCRIPTION
**Pull request by vinooganesh**
The task names in the MySqlOperator docs currently are not consistent with the actual operations. This PR fixes that.

### CODE REVIEW

**Comment by vinooganesh** [comment]
@ashb - I see that you have reviewed similar changes from other folks. Could I please ask you to quickly look this over?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Rebased it as it seems that the errors were only "flaky".

**Review by uranusjr — APPROVED** [review]

**Comment by uranusjr** [comment]
Need to fix static checks.

**Comment by vinooganesh** [comment]
@uranusjr @potiuk just fixed the static tests, had to force-push because I had some weirdness on my branch. Hope that's okay. If not, I can re-make the PR

**Pull request merged**
