### PR TITLE
Do not remove 'full-tests-needed' when approval missing

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @TobKed

**Comment by potiuk** [comment]
Hey @ashb - we have a chance to first time make a "proper" review with action updated via submodule's update

**Review by TobKed — APPROVED** [review]

**Comment by potiuk** [comment]
Hey @ashb - really small removal of the label :)

**Comment by potiuk** [comment]
@ashb ?

**Review by ashb — APPROVED** [review]

**Pull request merged**
