### PR TITLE
[AIRFLOW-3867] Rename GCP's subpackage

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3867
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

The names for packages for Azure and AWS have been standarized. Google Cloud Platform should follow this trend.

Idea reported by @ashb during the discussion under PR: #4524 

This PR passed an internal review at [Polidea](https://www.polidea.com/): https://github.com/PolideaInternal/airflow/pull/59 

CC: @kaxil, @jmcarp @potiuk It is simple, but it affects all users of GCP operators, so I'm asking for feedback. I feel obliged to inform you about this change.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
I think we need to think about backward compatibility. Mostly because it is used everywhere in blogs: https://cloud.google.com/blog/products/gcp/how-to-aggregate-data-for-bigquery-using-apache-airflow

Maybe keep `gcp_api` for now? And add a deprecation warning.

**Comment by mik-laj** [comment]
@Fokko There is no technical possibility to add a deprecation warning. You can only keep the two variants for a few versions, but it will always be a surprise for people. It may be now or it may be later.

**Comment by kaxil** [comment]
+1 for the change. However, let's support both the versions until 2.0 and maybe even till 2.1 and then remove `gcp_api` eventually. But let's make it clear on the docs that "use apache-airflow[gcp] as apache-airflow[gcp_api] is marked for deprecation".

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
+1 on that

**Review by kaxil — APPROVED** [review]
LGTM. @Fokko Any more thoughts?

**Comment by Fokko** [comment]
Thanks it, thanks @mik-laj et al

**Review by Fokko — APPROVED** [review]

**Pull request merged**
