### PR TITLE
Add EndOfLife instructions to release procedure

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
End Of Life is very well indexed and contains mostly updated data.

I just made PR to it https://github.com/endoflife-date/endoflife.date/pull/1508  and hopefull they approve it quickly, then we will get this:

image

**Comment by potiuk** [comment]
Ah sorting is messed up :)

**Comment by usta** [comment]
PR means Pull Request and when you write PR Request it became Pull Request Request
so i suggest write it long and add PR in parantases (PR)

**Comment by usta** [comment]
`with release date, latest version and updated changelog link.`
we use changelogthemplate for generally generating related new version's url so if changelogthemplate's link
is not different than it should be we are adding link tag.
Also release date and latestrelease date are different each cycle's release date is its .0 version
so for example if the product is 2.1.4 its release date is 2.1.0's date and its latestreleasedate is its 2.1.4's date

**Comment by potiuk** [comment]
> `with release date, latest version and updated changelog link.` we use changelogthemplate for generally generating related new version's url so if changelogthemplate's link is not different than it should be we are adding link tag. Also release date and latestrelease date are different each cycle's release date is its .0 version so for example if the product is 2.1.4 its release date is 2.1.0's date and its latestreleasedate is its 2.1.4's date

Right PR Request :facepalm:  ... I would love to use the template but similarly as you I had a problem with getting it working (despite following the docs). If you can help with it, I'd love to change it to template :)

**Comment by potiuk** [comment]
BTW. updated (bettter sorting) preview is here https://deploy-preview-1508--endoflife-date.netlify.app/apache-airflow

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
And it's LIVE : https://endoflife.date/apache-airflow  @jedcunningham @ephraimbuddy :)

**Comment by usta** [comment]
@potiuk if you add auto: tag in your product ( i mean Airflow) with related git repo address and suitable regex you dont need to prepare PR for each of new releases of your product (every monday our bot will check and updates date link and related parts automatically )

**Comment by potiuk** [comment]
Yep. I  know :). I am just not sure if such regexp can be added now. 

One of my favourite quotes "You have problem - add regexp, now you have two problems". 

We already have pre-commits that generate updates in our docs appropriately: https://github.com/apache/airflow/blob/main/scripts/ci/pre_commit/pre_commit_supported_versions.py so we will eventually automate it but the usual approach we take is that we run a thing like that manually for couple of releases until we automate it (but with every release things get more and more automated so that one will be automated as well).

**Comment by usta** [comment]
@potiuk you misunderstand me, i didnt mean to do anything in yourside i  mean in endoflife.date's side

**Comment by usta** [comment]
or just mention me with each release i will done that change faster than our bots :D

**Comment by potiuk** [comment]
Ah yeah. That is cool - we might try it as next step. I think there are a few things that make it difficult though (for example Airflow 2 follows a different scheme that 1 as we switched to semver when we released 2 so we basically have one real "line" of Airflow 2 and we will mostly update ". And mostly we will update latest release and latest release date only. I am not sure if that pattern will work ?

**Comment by potiuk** [comment]
And we are perfectly fine with opening a PR for that - this is a very smal effort for us really, might be even faster than pinging you. We are opening and handling tens of PRs a day anyway - one more does not make a big difference.

**Pull request merged**
