### PR TITLE
Can't configure Kubernetes and Celery workers in Helm Chart

### LINKED ISSUE #28880: Can't configure Kubernetes and Celery workers in Helm Chart
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.3

### Kubernetes Version

1.25

### Helm Chart configuration

_No response_

### Docker Image customizations

_No response_

### What happened

Current Helm chart uses the "workers" section to configure Kubernetes or Celery workers parameters (resources, affinity, etc.).
However, when using CeleryKubernetesExecutor, the "workers" section is used to configure the Celery ones, making Kubernetes workers settings available only via podTemplateFile, which can be difficult to manage.

I suggest splitting "workers" into "kubernetesWorkers" (used in pod_template_file) and "celeryWorkers" (used by the celery ones)

### What you think should happen instead

Helm Chart should allow to configure both kind of workers in an easy way

### How to reproduce

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
The "workers" section in the values.yaml is only used to configure the celery executor and celerykubernetes executors. We should split the common section of the workers section into celery vs kubernetes so that configuration is easier.

closes: #28880 
Fixes #28880

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by hussein-awala** [comment]
I think this is not necessary, because the Kubernetes workers are not created by the helm chart, it just creates and configures the celery workers.

For the K8S workers, they are created by the schedulers (a worker for each task), and you can configure them by providing a pod template in [the configuration](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#pod-template-file) or override the [pod_template](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#pod-override) for a single task.

**Review by hussein-awala — COMMENTED** [review]
I think this is not necessary, because the Kubernetes workers are not created by the helm chart, it just creates and configures the celery workers.

For the K8S workers, they are created by the schedulers (a worker for each task), and you can configure them by providing a pod template in [the configuration](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#pod-template-file) or override the [pod_template](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html#pod-override) for a single task.

**Comment by amoghrajesh** [comment]
Thanks for explaining that @hussein-awala
Made the changes in sync with what was asked in the issue description: #28880. Maybe I understood the issue wrong. Could you go through that issue and explain to me where I went wrong?

**Comment by potiuk** [comment]
I think the idea in the #28800 was to be able to specify some parameters in the Helm Chart Values in a similar way for K8S as it si for celery. What it would likely mean - is merging the parameters specified in the values.yaml into the pod_template_file (providing defaults) and making it possible to run K8S executor even without a pod template file.

The pod-template file is nice and super flexible, but as I imagine this one - it would be a nice way to configure most of the POD parameters in a very similar way for Celery and K8S pods, which seems to me like a good idea. It is kind of strange (byt justified in most complex cases) to have the parameters specified in pod_template_file. but having a static values (defaults?) specified in  Helm chart would make it much easier to configure the installation for simple cases where pod template file flexibility is not really needed. 

@jedcunningham @dimberman @dstandish - WDYT about such a feature?

This was - I think the original idea behind this feature (at least this is how I understood it). A

**Comment by hussein-awala** [comment]
@amoghrajesh or @potiuk can you please update the description and link the PR to the issue?

I think we can add a new value `k8s_pod_template` and use it when the executor is `CeleryKubernetesExecutor`:
- if the executor is `CeleryExecutor`: load conf from `.Values.workers`
- if the executor is `CeleryKubernetesExecutor`: load celery worker conf from `.Values.workers` and pod template conf from `.Values.k8s_pod_template` if it exists, and if not we load them from `.Values.workers` or `.Values` as we do for now
- if the executor is `KubernetesExecutor`: we load pod template conf from `.Values.k8s_pod_template` if exists, and if not we load them from `.Values.workers`  or `.Values`

I believe some of the `CeleryKubernetesExecutor` users use the same configuration for celery and k8s, if we separate the configurations in two sections, they will need to duplicate them. With my suggestion, they can keep them identical, or override them/some of them in the section k8s_pod_template

**Comment by potiuk** [comment]
> I believe some of the `CeleryKubernetesExecutor` users use the same configuration for celery and k8s, if we separate the configurations in two sections, they will need to duplicate them. With my suggestion, they can keep them identical, or override them/some of them in the section k8s_pod_template

Hmm. I think the whole reason to have CeleryK8S executor was to make them "different" - I think characteristics (memory, CPU etc. ) of "always running" celery worker Pod - which usually has N Python interpreter started (celery parallelism) is pretty much always different than K8S Pod (which always runs 1 task). I think it would be rather counter-productive to commonalize those settings

**Comment by potiuk** [comment]
(BTW. @amoghrajesh - adding `Closes #PR` inside comment does not work :)

**Comment by amoghrajesh** [comment]
Thanks, my bad. Pulled it out of the comment @potiuk

**Comment by amoghrajesh** [comment]
@hussein-awala @potiuk I kinda like the idea of separating the differences between CeleryK8sExecutor and CeleryExecutor. @hussein-awala's idea seems reasonable but requires a fair bit of work to be done while installing if you need to specify the properties. What consensus should we arrive at?

**Comment by potiuk** [comment]
I think... Let's try what @hussein-awala proposes :)

**Pull request closed without merging**
