### PR TITLE
Add missing logos for integrations

### LINKED ISSUE #13110: Add missing logos for integrations
Hello,

@ecerulm [added](https://github.com/apache/airflow/pull/13073) a logo `field` for `integration` object defined in `provider.yaml`
https://github.com/apache/airflow/blob/ccaca0af3933306c7ca0aa3d78fa2237ff3bfb19/airflow/provider.yaml.schema.json#L45-L48

We then use these logos to promote the integrations on our website.
Screenshot 2020-12-16 at 14 59 59

It would be fantastic if we could add the missing logos to make each integration equally fantastic.

Here is an integration list that does not have a logo. If you are interested, you can integrate only to a few integrations and we will still be happy.
```
$ find . -name provider.yaml | xargs -n 1 yq r --tojson | jq '.integrations | map(select(.logo == null))[] | .["integration-name"]' -r | sort
jq: error (at <stdin>:11): Cannot iterate over null (null)
AWS DataSync
AWS Step Functions
Amazon CloudFormation
Amazon DataSync
Amazon ECS
Amazon ElastiCache
Amazon Glacier
Amazon SecretsManager
Amazon Simple Email Service (SES)
Amazon Web Services
Apache Kylin
Apache Livy
Atlassian Jira
Celery
Databricks
Datadog
Dingding
Discord
Docker
Docker Swarm
Elasticsearch
Exasol
Facebook Ads
File Transfer Protocol (FTP)
Google
Google API Python Client
Google Ads
Google Analytics360
Google BigQuery Data Transfer Service
Google Campaign Manager
Google Cloud
Google Cloud Data Loss Prevention (DLP)
Google Cloud Firestore
Google Cloud Life Sciences
Google Cloud OS Login
Google Cloud Secret Manager
Google Cloud Stackdriver
Google Data Catalog
Google Data Fusion
Google Data Proc
Google Dataprep
Google Deployment Manager
Google Discovery API
Google Display&Video 360
Google Drive
Google Search Ads 360
Google Spreadsheet
Hashicorp Vault
Hypertext Transfer Protocol (HTTP)
IBM Cloudant
Internet Message Access Protocol (IMAP)
Java Database Connectivity (JDBC)
Jenkins
Kubernetes
Microsoft Azure
Microsoft Azure Batch
Microsoft Azure Data Explorer
Microsoft Azure FileShare
Microsoft SQL Server (MSSQL)
MongoDB
MySQL
ODBC
OpenFaaS
Opsgenie
Oracle
Pagerduty
Papermill
Plexus
PostgreSQL
Presto
Qubole
Redis
SQLite
SSH File Transfer Protocol (SFTP)
Salesforce
Samba
Secure Shell (SSH)
Segment
Singularity
Slack
Snowflake
Spark on Kubernetes
Telegram
Vertica
Windows Remote Management (WinRM)
Yandex.Cloud
Yandex.Cloud Dataproc
Zendesk
gRPC
```

CC: @ecerulm

### PR DESCRIPTION
**Pull request by griffincosgrove**
Added missing logos .png images and updated provider.yaml file to point to the path for the logo image. Currently, there are many logos on the Apache Site that do not have logo images. Closes #13110

### CODE REVIEW

**Comment by griffincosgrove** [comment]
@mik-laj think please help me with the review... again 😄

**Comment by mik-laj** [comment]
One integration still has a checkerboard pattern.
Screenshot 2021-01-18 at 13 29 40

Can you also add a logo for singularity?
https://sylabs.io/guides/3.7/user-guide/_static/logo.png

**Comment by griffincosgrove** [comment]
yes @mik-laj, I will do that right now 😄 sorry about that.

**Comment by griffincosgrove** [comment]
@mik-laj please check again 😃

**Comment by mik-laj** [comment]
One more chessboard left, but this time it was slightly less visible.
Screenshot 2021-01-19 at 17 17 01

**Comment by griffincosgrove** [comment]
@mik-laj replaced the azure file share logo.

**Comment by mik-laj** [comment]
Perfect!
Screenshot 2021-01-21 at 01 20 47

**Review by mik-laj — APPROVED** [review]

**Comment by potiuk** [comment]
Cool. I might even try to incorporate that into the Provider Readme's :)

**Comment by griffincosgrove** [comment]
Let me know if I can help @potiuk 

thanks for the help lads! Cheers

**Pull request merged**
