### PR TITLE
[AIRFLOW-1929] Pass execution_date in TriggerDagRunOperator

### PR DESCRIPTION
**Pull request by ghost**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Enhancements for the TriggerDagRunOperator to accept execution_date as a parameter.
It reuses the trigger_dag function available in the api.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I have added the following test cases to cover the new code path
test_trigger_dagrun_with_execution_date in tests/core.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ghost** [comment]
ping @sekikn @Fokko @ashb @bolkedebruin

**Comment by sekikn** [comment]
LGTM. I also confirmed that the problem reported on [AIRFLOW-1674](https://issues.apache.org/jira/browse/AIRFLOW-1674) was fixed.
Just wait for committer's review :)

**Comment by bolkedebruin** [comment]
I wonder what we need to do with the `microseconds` here. The Rest API cuts off microseconds and we do this for backwards compatibility reasons. With this change we also cut it off from ones that are triggered from DAGs. 

While I am in favor of moving it to the common framework it needs to be checked if this works correctly for the cases that we currently support. Most likely I think the cut off needs to be moved from the common layer and move the cutoff to the frontend.

cc @Fokko

**Comment by ghost** [comment]
@bolkedebruin One case that will be broken due to rounding off is If the same DAG gets triggered within the same second. 

For keeping everything in the common framework I have put the microsecond_replace feature behind a boolean flag. Let me know about your thoughts.

**Comment by Fokko** [comment]
@sreenathkamath Due to the version bump, master is broken: https://github.com/apache/incubator-airflow/pull/3260. Will be merged soon

**Comment by sreenathkamath** [comment]
@Fokko @bolkedebruin can you take a look at this PR. I have addressed the comments raised

**Comment by ghost** [comment]
@bolkedebruin @Fokko Can you please take a look at the PR. I have addressed the comments mentioned in the first review

**Comment by ghost** [comment]
@Fokko can you please take a look at this

**Review by Fokko — APPROVED** [review]
Thanks @sreenathkamath, I like the change. It also uses the API instead of interacting with the db directly.

**Comment by ena1106** [comment]
I am new to Airflow so please correct me if I am wrong.
It seems to me a weird choice to give the triggered dag a dag_id that is dependent on now instead of the passed execution_date. And I suspect this causes troubles with backfills. 

Suppose I have a daily dag_1 that starts at midnight and when it's done it triggers a dag_2. 
Suppose that execution date of dag_1 is 2018-06-11 and that the same date is passed to dag_2.
dag_1 will have a run_id like "scheduled__2018-06-18T00:00:00"
I would expect dag_2 to have a dag_id like: "trig__2018-06-18T00:00:00"

If the dag_2 run_id is computed using now the name of dag_2 run_id could be very different (if dag_2 takes hours to complete or if we are doing a backfill of dag_1).

Thanks for reading this and please tell me if I am making wrong assumptions here.

**Comment by ena1106** [comment]
Antoher doubt: how can i pass the execution date of the first dag to the triggered dag? The datetime parameter of the dag run operator is not a template field.

I thought to do something like:
```
trigger_dag_task = TriggerDagRunOperator(task_id='trigger_dag_task',
                                         trigger_dag_id="triggered_dag_v1",
                                         execution_date='{{execution_date}}',
                                         dag=dag)
```

**Pull request closed without merging**
