### PR TITLE
[AIRFLOW-3830] Remove DagBag from /dag_details

### PR DESCRIPTION
**Pull request by ffinfo**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3830

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ffinfo** [comment]
Failing tests are also failing on master

**Comment by Fokko** [comment]
Please rebase as soon as master turns green again :-)

**Comment by Fokko** [comment]
So if I understand the PR correctly, this will fetch just the single dag, instead of loading the whole dagbag, but it will still use the Python file according to the TODO.

**Comment by ffinfo** [comment]
Yes indeed, this makes the webserver stateless because it does not depend on a periodical scan of the DagBag anymore.

We going to collect all database changes in 1 PR to limit the number of migration steps to add. After this the single parse of the python file can be removed.

**Review by Fokko — APPROVED** [review]
LGTM, please try to keep the size of the PR within proportions, we can merge the database migrations later on as well as long they are within the same release.

**Pull request merged**
