### PR TITLE
Fix Cloud Worflows system test

### PR DESCRIPTION
**Pull request by VladaZakharova**
- fix path in the link to Cloud Worklow

- change type casting for Worflow execution start_time argument: there was an error when calling old type cast on DatetimeWithNanoseconds object.

- fix system test to use correctly configured Workflow body with correct link.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
recommend `pre-comit install` and `breeze static-checks --only-my-changes`

**Comment by potiuk** [comment]
Still needs a a fix - looks like mypy does not like the way timestamp is used (and likely is right?)

**Comment by moiseenkov** [comment]
> timestamp

Yes, it expects a `Timestamp` object, but the `DatetimeWithNanoseconds` is being used here. I'm investigating it currently.

**Comment by moiseenkov** [comment]
It turned out that `proto-plus` dynamically converts `Timestamp` to `DatetimeWithNanoseconds` which inherits from `datetime.datetime`. So, this dynamic conversion causes static check failure.
That's why I slightly updated the operator's code and added the `# type: ignore` directive to pass this static check.

@potiuk , is there any cleaner way to overcome the static check failure or is my workaround enough?    

- proto-plus docs: https://proto-plus-python.readthedocs.io/en/latest/marshal.html
- the guilty line of code that converts value: https://github.com/googleapis/proto-plus-python/blob/main/proto/marshal/rules/dates.py#L39

**Review by potiuk — APPROVED** [review]

**Pull request merged**
