### PR TITLE
[AIRFLOW-1889] Add sensors in sensors.py to operators package

### PR DESCRIPTION
**Pull request by andyxhadji**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1889

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- Adds sensors from sensors.py to the operators package, removing the
sensors.py file altogether. Maintains old import style (to be removed in
2.0).

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- Already exists

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by andyxhadji** [comment]
@Fokko Would love to get your feedback on this, here are some of my thoughts:

I placed the sensors under `from airflow.operators.[sensor] import [Sensor]`, in order to avoid working with the deprecated AirflowImporter and avoid duplicating code. I maintained the deprecated version, `from airflow.operators import [Sensor]`.

Alternatively, I can create a separate package, outside of `operators/`, called `sensors/`, and leave `sensors.py` in `operators/` with a deprecation warning, while dispersing the classes in `sensors.py` into separate files in the `sensors/` package. The result would be imports that look like from `airflow.sensors.[sensor] import [Sensor]` and maintaining the deprecated `from airflow.operators import [Sensor]`. 

The difference is whether we want to treat sensors as a feature separate from operators, regardless that they inherit from an operator. Additionally, code would be duplicated in both `sensors.py` and the class files, until 2.0.

**Comment by Fokko** [comment]
Hi @andyxhadji 

I also started on the PR, but I'm fine if you want to pick this up. I've created a PR to easily see the changes: https://github.com/apache/incubator-airflow/pull/2875

I strongly feel that we should refactor it a bit more by creating a `airflow.sensors`, like we have with `airflow.contrib.sensors`:
https://github.com/apache/incubator-airflow/tree/master/airflow/contrib/sensors

This also means that the tests should be split from the big `sensors.py`:
https://github.com/apache/incubator-airflow/blob/master/tests/operators/sensors.py
The same accounts for the `tests/core.py` which also contains a couple of tests for the sensors. This would also be beneficial for the code quality since this file is around 2k5 lines.

What do you think? Cheers

**Comment by bolkedebruin** [comment]
I suggest _not_ putting sensors in airflow.sensors but rather airflow.operators.sensors. Better for the logging framework :). Or make sure logging stays functional for airflow.sensors.

Although as they derive from BaseOperator they should be fine, but it gets a bit fuzzy if we do so.

**Comment by andyxhadji** [comment]
Looks like you've made more progress than I have, so I closed mine. I'm
happy to help with any part, lots of grunt work here (especially all the
linting for the touched files, e.g. tests/core.py). Just let me know a
portion I can run with!

I was struggling with operators.sensors vs. just .sensors as well - because
sensors inherit from a base operator (and operate as one), keeping them
nested makes sense as well. Agree that whatever structure is chosen,
though, should be consistent with contrib/.

Not sure how feasible it is, however, to maintain deprecated import
structure if we create a sensors package inside operators/ (can we
simultaneously support `from airflow.operators.sensors import [Sensor]` and
`from airflow.operators.sensors.[sensor] import [Sensor]`)?

**Comment by Fokko** [comment]
Hi @andyxhadji, My PR is more or less done: https://github.com/apache/incubator-airflow/pull/2875 Please take a look if you agree with the changes.

The deprecated import structure needs to stay until Airflow 2.0, I don't like it either, but we have to keep some backward compatibility until then.

**Pull request closed without merging**
