### PR TITLE
[AIRFLOW-4731] Broken get_bucket kwarg in GCS hook

### PR DESCRIPTION
**Pull request by chronitis**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following https://issues.apache.org/jira/browse/AIRFLOW-4731

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

google-storage-client 1.16 introduced a breaking change where the
signature of client.get_bucket changed from (bucket_name) to
(bucket_or_name). Calls with named arguments to this method now fail.
This commit makes all calls positional to work around this.

Upstream change at https://github.com/googleapis/google-cloud-python/pull/7856

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Updated one test in test_gcs_hook

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
Ugh thanks Google.

Could you include a note about this change in our UPDATING.md please (some people may be using the package directly.)

**Comment by ashb** [comment]
Oh - could we safely make the calls positional (as you've done) but leave the version constraint as it is? Then we would reduce the chance of this breaking other code.

Or do you think it's better to force the update of the dep?

**Comment by chronitis** [comment]
The dependency version doesn't _need_ to be forced, if you'd prefer it not be.

The tradeoff is tricky - the existing `~= 1.14` will mean new installs will use `1.16` or later, so upgrading the requirement forces this upgrade at the same time as we're notifying of this bug, rather than it being encountered at some arbitrary later time. But it does force an upgrade which is not technically necessary - the changes will quite happily work with 1.14.

**Comment by potiuk** [comment]
I think it's quite OK with bumping up the dependency. I don't see any downside of it, and this is indeed valid point with ~ installing 1.16.

**Pull request merged**
