### PR TITLE
Add HipChat Operator

### PR DESCRIPTION
**Pull request by jgao54**
Added a base HipChatAPIOperator class and a HipChatAPISendRoomNotificationOperator which sends a customized notification to a HipChat room. This uses HipChat's REST API (they currently do not have an official python client).

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@jgao54 Thanks for the contribution. Can you please add some unit tests and some documentation? Then I'll merge

**Comment by bolkedebruin** [comment]
Almost there... Please have a look at the landscape issues that were introduced by this change. I'll merge after fix.

**Comment by jgao54** [comment]
@bolkedebruin  done. landscape is catching some other changes elsewhere.

**Comment by bolkedebruin** [comment]
Can you add a Apache License header (see others) to your operator? CI is failing because of it. Then I can merge.

**Comment by r39132** [comment]
:+1:  @jgao54

**Pull request merged**
