### PR TITLE
Move TaskInstanceKey to a separate file to fix circular import from kubernetes_helper_functions.py

### LINKED ISSUE #30988: DB migration job fails with circular import
### Apache Airflow version

2.6.0

### What happened

I upgraded my Airflow 2.5.3 to 2.6.0 using the official Helm chart 1.9.0 installation on a Kubernetes cluster. The DB migration job fails with a circular import of "TaskInstanceKey". The image I'm using is `apache/airflow:2.6.0-python3.10`. I'm using CeleryKubernetesExecutor in my configuration.

Here is the stacktrace:
```
Traceback (most recent call last):
File "/home/airflow/.local/bin/airflow", line 8, in <module>
sys.exit(main())
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/__main__.py", line 48, in main
args.func(args)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 51, in command
return func(*args, **kwargs)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 112, in wrapper
return f(*args, **kwargs)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/db_command.py", line 84, in upgradedb
db.upgradedb(
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
return func(*args, session=session, **kwargs)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/db.py", line 1544, in upgradedb
import_all_models()
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/__init__.py", line 60, in import_all_models
__getattr__(name)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/__init__.py", line 78, in __getattr__
val = import_string(f"{path}.{name}")
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 36, in import_string
module = import_module(module_path)
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dag.py", line 82, in <module>
from airflow.models.dagrun import DagRun
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagrun.py", line 57, in <module>
from airflow.models.taskinstance import TaskInstance as TI
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 99, in <module>
from airflow.sentry import Sentry
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sentry.py", line 195, in <module>
Sentry = ConfiguredSentry()
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/sentry.py", line 92, in __init__
executor_class, _ = ExecutorLoader.import_default_executor_cls()
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/executors/executor_loader.py", line 158, in import_default_executor_cls
executor, source = cls.import_executor_cls(executor_name)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/executors/executor_loader.py", line 134, in import_executor_cls
return _import_and_validate(cls.executors[executor_name]), ConnectorSource.CORE
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/executors/executor_loader.py", line 129, in _import_and_validate
executor = import_string(path)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/module_loading.py", line 36, in import_string
module = import_module(module_path)
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/executors/celery_kubernetes_executor.py", line 26, in <module>
from airflow.executors.kubernetes_executor import KubernetesExecutor
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/executors/kubernetes_executor.py", line 44, in <module>
from airflow.kubernetes import pod_generator
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/kubernetes/pod_generator.py", line 46, in <module>
from airflow.kubernetes.kubernetes_helper_functions import add_pod_suffix, rand_str
File "/home/airflow/.local/lib/python3.10/site-packages/airflow/kubernetes/kubernetes_helper_functions.py", line 26, in <module>
from airflow.models.taskinstance import TaskInstanceKey
ImportError: cannot import name 'TaskInstanceKey' from partially initialized module 'airflow.models.taskinstance' (most likely due to a circular import) (/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py)
```

### What you think should happen instead

The DB migration job will start without an error on circular import.

### How to reproduce

I have a complex automation pipeline with many configurations, so, for now, I will not put my details configurations here. Please let me know if you need specific details.

I installed Airflow on my Kubernetes cluster using the official Helm chart 1.9.0. My database is Postgres. The DB migration job starts, but it fails with the error above.

### Operating System

Linux, AWS EKS-based Kubernetes

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

My full configuration is large and contains sensitive data. Please let me know if you need specific details.

I installed Airflow on my Kubernetes cluster using the official Helm chart 1.9.0. My database is Postgres. The DB migration job starts, but it fails with the error above.

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by LipuFei**
Fixes #30988

Fixes a circular import of `DagRun -> TaskInstance -> Sentry -> KubernetesExexcutor -> kubernetes_helper_functions.py (*) -> TaskInstanceKey.`

Moving `TaskInstanceKey` out to a separate file will break the cycle from `kubernetes_helper_functions.py -> taskinstances.py`

### CODE REVIEW

**Comment by potiuk** [comment]
Nice. I like it - this is a simple solution and I think It is also generally a practice we are implementing more and more - splitting modules in order to get rid unnecessary coupling - especially with introducing more type hinting, some of the implicit couplings have been made explicit - like this one. 

One thing to add though: https://github.com/apache/airflow/blob/main/docs/conf.py#L248 should also include taskinstancekey and it should also be added in https://github.com/apache/airflow/blob/main/docs/apache-airflow/public-airflow-interface.rst nest to taskinstance package as they are part of the public Airflow interface. 

I also think it is backwards-compatible since TaskInstanceKey is imported in taskinstance.py (so if someone imports it from there, it will continue to work).

I would love another maintainer opinion, but it looks good to me.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Another  problem with that is that it causes import errors when collecting tests - it has to be fixed.

**Comment by potiuk** [comment]
And you will have to rebase to latest main @LipuFei in order to make some changes I pointed out (fixes to docs were merged yesterday).

**Comment by uranusjr** [comment]
You need a `from __future__ import annotation` line in the file to make CI work.

**Comment by LipuFei** [comment]
I have done a rebase. Hope it works. :) Thanks @potiuk

**Comment by LipuFei** [comment]
> You need a `from __future__ import annotation` line in the file to make CI work. (Edit: And a license blob. See contribution guide for help setting up pre-commit to check that locally.)

Done:
 - Added the LICENSE blob
 - Added `from __future__ import annotation`

**Comment by LipuFei** [comment]
> One thing to add though: https://github.com/apache/airflow/blob/main/docs/conf.py#L248 should also include taskinstancekey and it should also be added in https://github.com/apache/airflow/blob/main/docs/apache-airflow/public-airflow-interface.rst nest to taskinstance package as they are part of the public Airflow interface.

I just added `taskinstancekey` to docs that you have mentioned @potiuk :
 - https://github.com/apache/airflow/blob/main/docs/conf.py#L248
 - https://github.com/apache/airflow/blob/main/docs/apache-airflow/public-airflow-interface.rst

**Review by uranusjr — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by o-nikolas — APPROVED** [review]
Note: This will conflict with some changes I have had in PR for a couple weeks now #30727, last to merge will have to resolve it

**Comment by potiuk** [comment]
> Note: This will conflict with some changes I have had in PR for a couple weeks now #30727, last to merge will have to resolve it

BTW. One of my first responses to this one (I did not send it) started with: 

> This looks cool, but @o-nikolas might get a bit angry if we merge this one before #30727 is merged.

I am looking at #30727 now.

**Comment by potiuk** [comment]
General comment here.

Honestly I think we should merge that one first - because it is very likely we are going to cherry-pick this one to 2.6.1 while #30727 is much more risky to cherry-pick to bugfix branch. This one should cherry-pick cleanly if we merge it first, whereas if we merge it after #30727 it will require manually applying the same fix to 2.6.1 branch. 

This is also why I hesitated a bit with #30727 refactoring and where my comment about possibly splitting it even further  came from @o-nikolas. This is a nice example how such refactorings are impacting our bug-fixing  releases.

Somethign to consider when we decide to merge #30727 (also something for @ephraimbuddy and @pierrejeambrun to take a look I guess) - for me the kind of more complex refactors in "core" parts of Airflow are better done closer to the end of cherry-picking cycle  when we are preparing to cut-off a new minor branch (this is one of the reasons why the base_job refactor of mine was done when it was done  - after the last cherry-pickign round for 2.5.*)

**Pull request merged**
