### PR TITLE
[WIP] Add dms raw

### PR DESCRIPTION
**Pull request by jzucker2**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2334
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @jzucker2. Can you take a look at:

- The commit guidelines?
- Add the operators and sensors to the docs
- Writing some example documentation how to use the operators/sensors

Cheers

**Comment by jzucker2** [comment]
@Fokko thanks for the response. Yes I am totally aware of the commit guidelines. Put this together to for the GitHub diff UI while I work on tests. Will draft up a cleaner PR when I get the tests written.

**Comment by jzucker2** [comment]
Also working on adding DMS support to moto so this can be properly unit tested before merge

https://github.com/spulec/moto/pull/1590

**Comment by Fokko** [comment]
Awesome work, thanks @jzucker2 for the update

**Comment by r39132** [comment]
@jzucker2 please rebase

**Comment by tooptoop4** [comment]
@jzucker2 do u have any updates?

**Comment by balexander** [comment]
@jzucker2 @tooptoop4 I found this PR after writing a bunch of similar code. Since this appears to be abandoned I'll get my stuff organized and open a new PR.

**Pull request closed without merging**
