### PR TITLE
Skip "." path when preparing reproducible packages

### LINKED ISSUE #37399: Airflow Helm chart fails to deploy with ArgoCD
### Official Helm Chart version

1.12.0 (latest released)

### Apache Airflow version

latest

### Kubernetes Version

1.29

### Helm Chart configuration

No parameters with the simple ArgoCD deployment (5.51.x).

### Docker Image customizations

no

### What happened

ArgoCD fails to deploy with `Unable to create application: application spec for airflow-test is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = illegal filepath in archive: /tmp/d629b287-bcfd-4ca1-b827-33aa871dae80`

### What you think should happen instead

ArgoCD should be able to create application

### How to reproduce

1. Deploy ArgoCD
2. Create a simple ArgoCD application from UI
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'airflow-test'
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    targetRevision: 1.12.0
    helm:
      releaseName: airflow-test
      version: v3
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

### Anything else

Issue in ArgoCD https://github.com/argoproj/argo-cd/issues/17182

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
The packages should not contain the "." folder.

Fixes #37399

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Comment by potiuk** [comment]
cc: @jedcunningham -> I guess this one should be added manually to changelog as it will be skipped in Chart changelog.

**Comment by finaldie** [comment]
May I ask when the helm chart 1.12.1 will be released? it's currently blocked the argoCD deployment. Thanks a lot.

**Comment by potiuk** [comment]
Airflow 2.8.2 has been just released so I believe soon. Please make sure to subscribe to devllst when the release candidate for you to test (https://airflow.apache.org/community/ to see how) . 

If you are after speeding up the release - this is THE way you and anyone else waiting for it, can help in speeding up the release/

Can we count on you to get it to a spin and confirm that it works as expected when RC is out @finaldie ?

**Comment by potiuk** [comment]
BTW. I will be quite disappointed not seeing your "I've tested it, it works" or "Here are the problems I found" of yours when we ask for it.

**Comment by finaldie** [comment]
Thanks team, verified for the helm chart 1.13.0 with argocd in GCP, it works now.

**Pull request merged**
