### PR TITLE
[AIRFLOW-2557] Remove paged test for s3

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2557
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Paged tests for s3 are taking over 120 seconds. The
functionality testes is part of the standard boto suite
and part of its own tests.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

tests removed.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

cc @Fokko @NielsZeilemaker

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
You could reduce the number from 5000 to 1001, as a single call will return at most 1000 results.

**Comment by bolkedebruin** [comment]
@NielsZeilemaker I know, but I looked at the code and I don’t think that makes sense. We are not testing anything inside airflow by it and the tests together would still take around 20seconds.

**Comment by Fokko** [comment]
Well, it verifies this logic: https://github.com/apache/incubator-airflow/blob/master/airflow/hooks/S3_hook.py#L98-L102

**Comment by bolkedebruin** [comment]
No it doesn’t, that part will always be tested as you can see in the test coverage as well. There will be always one page if you have results.

**Comment by Fokko** [comment]
It looks like the branch is still being hit: https://codecov.io/gh/apache/incubator-airflow/pull/3455/src/airflow/hooks/S3_hook.py#L98...102 

🤔

**Comment by NielsZeilemaker** [comment]
It will, as you always have a single page, but testing to see if multiple pages work would have my preference, as I actually encountered this bug while using the hook. Maybe there is a quicker method to add the files?

**Comment by bolkedebruin** [comment]
Can you lower the page size somehow?

**Comment by bolkedebruin** [comment]
@NielsZeilemaker @Fokko updated. Page size is a supported setting

Note: @Fokko lets not accept PRs anymore that go over 2s in tests.

**Review by Fokko — APPROVED** [review]
Thanks @bolkedebruin, looking good. Codecov tells me that the branch is still being hit.

I agree that normal tests should run within 2seconds, maybe drop a line on the dev mailinglist?

**Pull request closed without merging**
