### PR TITLE
Revert "Introducing flags to skip example dags and default connection…

### PR DESCRIPTION
**Pull request by kaxil**
…s (#11099)"

This reverts commit 0edc3dd57953da5c66a4b45d49c1426cc0295f9e.

The master is failing because:

```
========================================================================================================================== FAILURES ==========================================================================================================================
_____________________________________________________________________________________________________________ TestConf.test_conf_as_dict_source ______________________________________________________________________________________________________________

self = <tests.test_configuration.TestConf testMethod=test_conf_as_dict_source>

    def test_conf_as_dict_source(self):
        # test display_source
        cfg_dict = conf.as_dict(display_source=True)
        self.assertEqual(
>           cfg_dict['core']['load_examples'][1], 'airflow.cfg')
E       AssertionError: 'env var' != 'airflow.cfg'
E       - env var
E       + airflow.cfg

tests/test_configuration.py:119: AssertionError
```

The configurations are overriding Airflow test configs

cc @francescomucio 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Hmm. Interesting why it passed the tests before. There are subtle differences between master and PR runs, but that one is stange

**Comment by potiuk** [comment]
OK. I know. the tests did not pass. I apparently merged it when things were green but the tests were not yet started @francescomucio  ->  I think I know why this happened (the variables should not be set in CI), 

I think eventually this is yet another stronger case to move "--start-airflow" flag to "start-airflow" command and make those flags re-applied then only for that command. 

BTW. I think we need to be rather careful when merging changes with the "green" button but the number of checks are not as expected @kaxil @dimberman @ash @turbaszek @mik-laj :  Sometimes the button gets green when some tests are still not queued. I raised the github support issue https://github.community/t/merge-button-green-with-jobs-not-started-in-github-actions/132604/5 and after some ping-pong they confirmed the issue, so I raised an official ticket to fix that. Let's see.

**Comment by ash** [comment]
Guys it is so annoying to get notification from your project at least once a week. Please type @ashb, not @ash. You are the only project on github who repeatedly do that mistake.

**Comment by potiuk** [comment]
Sorry. Really sorry. unfortunatley I am afraid we are the only project that has @ashb with @ash nickname on our Slack. I guess that might explain why this is happening, but I am not sure if there is a way to avoid this kind of mistake, it's just built in the situation no matter how many times you will tell people not to do it, It will continue to happen. 

Maybe someone has an idea what to do I think this will not work for maintainers? https://github.blog/2016-04-04-organizations-can-now-block-abusive-users/  . @ashb - any change you can change the slack's nickname to ashb as well?

**Pull request merged**
