### PR TITLE
Resolve 404s when trying to click through to the task instances view

### PR DESCRIPTION
**Pull request by woodlee**
This should resolve the 404s that @james-woods was mentioning in https://github.com/airbnb/airflow/issues/73 (and that I was also experiencing).

### CODE REVIEW

**Comment by mistercrunch** [comment]
img

**Comment by tkaymak** [comment]
:+1:  :)

**Comment by mistercrunch** [comment]
And now with better 404 coming up in the next version:
https://github.com/airbnb/airflow/commit/39531d24b08af3b2abae2701637c01d0bf56a536

**Comment by woodlee** [comment]
Excellent!

**Pull request merged**
