### PR TITLE
Remove search scope from LDAP query to make it work with ActiveDirect…

### PR DESCRIPTION
**Pull request by criccomini**
…ory.

### CODE REVIEW

**Comment by criccomini** [comment]
I ran Airflow against a real ActiveDirectory install, and it didn't work. Our settings were:

```
uri = ldap://<ip>:<port>
user_filter = objectClass=*
user_name_attr = sAMAccountName
bind_user = <user>@<foo.com>
bind_password = ******
basedn = dc=foo,dc=bar
```

This failed with a `KeyError['dn'] not found` exception. Removing the search_scope=LEVEL fixed this. We are now able to log in with LDAP using this patch.

cc @bolkedebruin

**Comment by NeilHanlon** [comment]
The search scope actually just needs to be changed to SUBTREE instead of LEVEL -- and it's not really AD that's the issue, it's that you're not specifying an OU to match against, and therefore the search_scope must be different.

However this is probably more than just removing some code.

In my opinion, there should probably be a setting in airflow.cfg to set the search scope.

**Comment by bolkedebruin** [comment]
Agreed. I'm using FreeIPA that uses a flat structure so no OUs. You can of course set the ou to match against by setting user_filter. SUBTREE can have performance implications if you don't need it.

**Comment by NeilHanlon** [comment]
Yeah... In /most/ setups (even with OUs), this shouldn't be an issue, since in most scenarios the users you'd be trying to grant access would be in the same OU (delegated OU, or something), or at the very least, inside a base OU. However in cases like mine, someone who didn't properly know how to design an AD structure for users designed it, so our users are all over the place, with group membership being the deciding factor for most things.

For very large orgs, subtree will probably kill the box it's running on. I've maxed out CPU on a 12 core Xeon trying to parse a subtree on a huge directory.

**Comment by criccomini** [comment]
Closing this PR in favor of @NeilHanlon's

**Pull request closed without merging**
