### PR TITLE
[AIRFLOW-1716] Fix multiple __init__ def in SimpleDag.

### PR DESCRIPTION
**Pull request by snjypl**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1716

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

 SimpleDag was left with multiple __init__ definition possibly as a result of incorrect merge conflict resolution. 
removed the older __init__ definition and fixed the doc string  

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by snjypl** [comment]
the issue was because of this commit :   @saguziel
https://github.com/apache/incubator-airflow/commit/cfc2f73c445074e1e09d6ef6a056cd2b33a945da

**Comment by snjypl** [comment]
wondering why travis-ci build was not trigged for this pull request?

**Comment by bolkedebruin** [comment]
Please adhere to the commit guidlines (commit title should reference jira, use imperative)

**Comment by snjypl** [comment]
@bolkedebruin  done.

**Comment by bolkedebruin** [comment]
@MortalViews your fix is not correct, the other signature was used in code. tests havent run for some reason. Please open a new PR with correct fix and make sure tests run

**Comment by snjypl** [comment]
@bolkedebruin  the previous definition was not used anywhere in the application. even if it was being used..it would have been overridden by the second __init__. 
anyway, am going to create another pull request and hope the CI is trigged.  

edit: didn't see the CI build failure. will look into it.

edit: i went through the code, looks like SimpleDag is created only at two places. and it is using the updated def. 

https://github.com/apache/incubator-airflow/blob/master/airflow/jobs.py#L1768
https://github.com/apache/incubator-airflow/blob/master/tests/jobs.py#L936

**Pull request closed without merging**
