### PR TITLE
Add autodetect arg to external table creation in GCS-to-BQ operator

### PR DESCRIPTION
**Pull request by shahkshitij15**
Added autodetect in external table creation for GCS to BQ operator
Now one can create the external table without passing any schema

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
Tests are failing @shahkshitij15

**Comment by shahkshitij15** [comment]
Hey! I have updated the test cases. Now it should work @potiuk

**Review by eladkal — APPROVED** [review]

**Comment by shahkshitij15** [comment]
Hey! With reference to issue #22063, how shall I test the proper working of my code?

**Comment by potiuk** [comment]
Here you can find some helpful guidelines:  https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PROVIDER_PACKAGES.md#verify-by-contributors

**Comment by potiuk** [comment]
Improved instructions added in PR https://github.com/apache/airflow/pull/22087

**Pull request merged**
