### PR TITLE
AIRFLOW-6062 Watch worker pods from all namespaces

### PR DESCRIPTION
**Pull request by mppetkov**
The scheduler currently monitors pods only from the Kubernetes namespace provided in the configuration. The initial fix has been implemented in this PR - https://github.com/apache/airflow/pull/7123 but it looks like it was not actually a complete fix.
I am extending the previous fix with additional change in the `KubernetesJobWatcher` to watch all namespaces in the Kubernetes cluster.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by dimberman — APPROVED** [review]

**Comment by dimberman** [comment]
Thank you for adding this @mppetkov!

**Comment by hcheng4** [comment]
[Not a contribution]

Hi folks,

This PR is going to break some Airflow deployments that do not have cluster-scoped RBAC to list all pods in all namespaces.

Are there any active discussions around how to handle this better, or are we going to expect all Airflow KubernetesExecutor-based deployments to have cluster-scoped roles to list across all namespaces? This is a change to our security model and will probably prevent us from being able to pick up 1.10.11.

**Comment by dimberman** [comment]
@hcheng4 that's a really good point I noticed that in the tests. We need to have a larger discussion (maybe make this a "multi-namespace" mode)

**Comment by hcheng4** [comment]
[Not a contribution]

@dimberman a multi-namespace mode sounds like a great idea. Is there a discussion already ongoing? If there's agreement design-wise, I can see if there's appetite and bandwidth here for a patch contribution.

It may be the case that longer-term the restrictions of an in-namespace Kubernetes deployment are too much and it's undesirable to support that going forward, but that doesn't feel like the type of compatibility-breaking change that's appropriate for a patch release IMHO.

**Comment by mppetkov** [comment]
One more vote for the generic multi-namespace approach, it would be amazing if we have functionality like that. Actually, that's why I have contributed the fix. In my company we need to run each worker Pod into a specific namespace based on a condition.

From what I understand, Airflow needs to provide the following options in the **airflow.cfg** to make this approach generic.

**- allowed_namespaces: ['\*']**
  Airflow can create a worker Pod in all namespaces (probably the whitelist property should have * as a value)

**- allowed_namespaces: ['namespace1', 'namespace2', 'namespace3']**
  Airflow can create a worker Pod in any namespace that is part of the **allowed_namespaces** property.

**- denied_namespaces: ['namespace1', 'namespace2', 'namespace3']**
Airflow cannot create a worker Pod in any namespace that is part of the **denied_namespaces** property.

**Pull request merged**
