### PR TITLE
[AIRFLOW-2279] Clear tasks across DAGs if marked by ExternalTaskMarker

### PR DESCRIPTION
**Pull request by yuqian90**
This change was already merged into master in https://github.com/apache/airflow/pull/6633. 
I'm creating this PR to help committers merge into v1-10-test.

---
Issue link: [AIRFLOW-2279](https://issues.apache.org/jira/browse/AIRFLOW-2279)

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by yuqian90** [comment]
@kaxil, this is the same change that you already merged. Since it's a bit of work to merge against v1-10-test, I put up this PR to do that. (e.g. www vs www_rbac are two separate packages, and there's a test which counts the number of example DAGs that need to be updated).

However, I noticed some tests time out. It doesn't look related to my change, e.g. test_cli.py timesout. test_external_task_sensors.py times out in one of the test profiles (Tests sqlite python 3.5), again I don't think it's due to my change. Is there some known issue with the tests in v1-10-test? The same tests in master seem to work just fine.

**Comment by yuqian90** [comment]
> @kaxil, this is the same change that you already merged. Since it's a bit of work to merge against v1-10-test, I put up this PR to do that. (e.g. www vs www_rbac are two separate packages, and there's a test which counts the number of example DAGs that need to be updated).
> 
> However, I noticed some tests time out. It doesn't look related to my change, e.g. test_cli.py timesout. test_external_task_sensors.py times out in one of the test profiles (Tests sqlite python 3.5), again I don't think it's due to my change. Is there some known issue with the tests in v1-10-test? The same tests in master seem to work just fine.

Okay I found the problem with `test_external_task_sensors.py`. I need to set the `ExternalTaskSensor` to `mode="reschedule"` in order to pass the Travis test for sqlite. I did that and the test is now happy. It's interesting the same test passes without issue in master branch.

For `test_cli.py`, I have double checked it is unrelated to my PR. I tried running the same test using clean `upstream/v1-10-test`, it fails too. So it's likely some other issue that should be addressed in a separate PR by someone else.

@kaxil  pls take a look if you have a chance.

**Comment by yuqian90** [comment]
Some new test failures appeared after I git rebased onto `upstream/v1-10-test`. None of them look related to my change.

@potiuk  might have better ideas regarding those failures since I see he's committing changes to fix some of them.

**Comment by kaxil** [comment]
The tests are unstable on v1-10-test branch. We are fixing it, will keep you updated. 

Thanks for this backport PR @yuqian90 🎉 , really appreciate it

**Comment by kaxil** [comment]
Merged to v1-10-test in 14111b4bd

**Comment by yuqian90** [comment]
> Merged to v1-10-test in [14111b4](https://github.com/apache/airflow/commit/14111b4bddbaa7c7085a25cdfe923f88219e1582)

Thanks!

**Pull request closed without merging**
