### PR TITLE
Revert "Make current working directory as templated field in BashOper…

### PR DESCRIPTION
**Pull request by potiuk**
…ator (#37928)"

This reverts commit db07eb1957a729f333c14ce3c26b5a819736295b.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by vincbeck** [comment]
Thanks! I was going to do it!

**Comment by potiuk** [comment]
cc: @Taragolis -> the https://github.com/apache/airflow/pull/37928 shoud be re-done and `full tests needed` addded - as it adds a number  of `cwd` added in serialization tests and other places.

**Comment by Taragolis** [comment]
Re-revert with fixes 😉 I guess it also might be a good idea add bash operator as full-test selective checks since changes in it might affect other tests

**Comment by potiuk** [comment]
>  I guess it also might be a good idea add bash operator as full-test triggerer in selective checks since changes in BashOperator might affect other tests

Yeah. looks like. We can add a rule for that - maybe not full tests but contributing `Core` and `Serialization` test cases. Let me take a look.

**Pull request merged**
