### PR TITLE
[AIRFLOW-XXX] Correct typos in UPDATING.md

### PR DESCRIPTION
**Pull request by dlamblin**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses fixing a typo in the documentation and so prepends commit with \[AIRFLOW-XXX\].

### Description

Applies to v1-10-stable; another pull will apply to master.

- Started with "habe", "serever" and "certificiate" needing to be:  
  "have", "server", and "certificate".
- Ran a check, ignoring British and US accepted spellings.
- Kept jargon. EG admin, aync, auth, backend, config, dag, s3, utils, etc.
- Took exception to:
  - "num of dag run" meaning "number of dag runs",
  - "upness" is normally for quarks,
  - "url" being lower-case, and
  - sftp example having an excess file ending.
- Python documentation writes "builtin" hyphenated, cases "PYTHONPATH".
- Gave up on mixed use of "dag" and "DAG" as well as long line lengths.

### Tests

- [x] My PR does not need testing for this extremely good reason: It is scoped to documentation.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] Updates only existing documentation.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]
thanks. lgtm

**Comment by dlamblin** [comment]
Welcome; not sure how you mange the diffs from the master and stable branch to this doc.
See also https://github.com/apache/incubator-airflow/pull/4242

**Comment by feng-tao** [comment]
just found out that you are updating the v10 branch. cc @ashb , I am not sure if we still update the release branch though.

**Comment by dlamblin** [comment]
I saw on the JIRA it's possible to mark fixed in 1.10.2, so that's why I make this pull request.
You merged 4242, but I wasn't sure if someone would manually reapply that edit into the v1-10-stable branch.

That `test_get_conn (tests.contrib.hooks.test_redis_hook.TestRedisHook) ... FAILED` is pretty consistent for this PR. Is that some known flakey test?

**Comment by feng-tao** [comment]
thanks @dlamblin , I don't think we need to worry about that unit test fails for this pr given it just changes the doc.

**Review by kaxil — APPROVED** [review]

**Comment by feng-tao** [comment]
@kaxil , so this won't go into pypi unless we manually push so, right? So what is the purpose of merging this change into both master branch and v10 branch? And have we had consensus on whether we are going to maintain/ update all the release branch? And what pr should go to both release branch and master branch?

**Comment by kaxil** [comment]
@feng-tao You are right, I had merged it in the morning and didn't release it pointed to 1.10 branch and then **dropped** that commit as I saw it went to 1.10 branch :) 

We would not want anything to change our stable branches.

**Comment by feng-tao** [comment]
thanks @kaxil

**Comment by ashb** [comment]
And yes, PyPI releases are entirely a manual process.

**Comment by Fokko** [comment]
Thanks @dlamblin

**Pull request merged**
