### PR TITLE
Rename AzureDataLakeStorage to ADLS

### PR DESCRIPTION
**Pull request by eladkal**
Followup of https://github.com/apache/airflow/pull/18168

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add a note in `CHANGELOG.rst` file?

**Comment by eladkal** [comment]
> Can you add a note in `CHANGELOG.rst` file?

@potiuk creates them automatically :)

**Comment by mik-laj** [comment]
@eladkal for provider packages, this file has two roles - changelog and update guide. @potiuk updates the changelog, but we keep the update guide manually.


We have a similar ccase in.  We have  a changelog, but we also have a note in nu

**Comment by mik-laj** [comment]
We also have a similar guide for backport providers. https://pypi.org/project/apache-airflow-backport-providers-google/ But we also have a changelog separately.

**Comment by eladkal** [comment]
@mik-laj yeah we used to have there but it was removed in https://github.com/apache/airflow/pull/13767

Do you want me to create an `UPDATEING.md` in Azure provider? (Similar to https://github.com/eladkal/airflow/blob/1d722d84ef3c1f5d2cee2f4be72320b47fc9640b/airflow/providers/amazon/aws/ADDITIONAL_INFO.md ) ?

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
