### PR TITLE
Revert "Send context using in venv operator (#41039)"

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This reverts commit da553935d248f22695124c40777d3ea29e04d57f.

The two tests added here are failing both in the main and 2.10 release branch

### CODE REVIEW

**Comment by ephraimbuddy** [comment]
cc [phi-friday](https://github.com/apache/airflow/commits?author=phi-friday)

**Review by eladkal — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
On main: https://github.com/apache/airflow/actions/runs/10317957180/job/28563448609?pr=41348#step:7:16218

V2-10: https://github.com/apache/airflow/actions/runs/10317331885/job/28569089548?pr=41280#step:7:14514

**Review by shahar1 — APPROVED** [review]

**Comment by eladkal** [comment]
@phi-friday please open a new PR and we will run full tests on it to see what is the problem
cc @shahar1

**Review by jedcunningham — APPROVED** [review]

**Comment by phi-friday** [comment]
@eladkal I created a new PR. #41363

**Pull request merged**
