### PR TITLE
Helm Docker image sources are now included in the Airlfow codebase

### PR DESCRIPTION
**Pull request by potiuk**
We can now build all the images from Airlfow sources in
a reproducible fashion and our users can use the helm chart
based on the images build from official images + code in
Airflow Codebase.

We also have consistent versioning scheme based on
calver version of releasing the images coupled with
the version of the original package.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @dimberman @schnie - I'd love your review on that - see the email!

**Comment by potiuk** [comment]
@kaxil @dimberman @schnie -> I rebased the change where I made all the images used by Helm part of our sources. They are green - and all the sources are easy to rebuild. 

I hope this will be ok for all of you finally.

I basically re-created the images without copying the original sources, and all the builds scripts and labelling scheme is consistent.

Do you still have any reservation against this? If so - can we talk about it and resolve it ?

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Apologies on not seeing this one earlier. I see no problem with this one, approved

**Comment by potiuk** [comment]
Coool! Thanks @kaxil ! Much appreciated! I think this is an important step to release the helm charts! I am going to add some contributions soon.

**Pull request merged**
