### PR TITLE
Adding connections for sql operator unit tests so they pass

### PR DESCRIPTION
**Pull request by tronlightracer**
2 of the unit tests in airflow/tests/operators/test_sql.py were failing for postgres and mysql so I fixed them so no connection has to be made before running the tests

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
If you introduce side effect to the database in tests, you must clean it up afterwards. Consider using Pytest fixtures to do this.

**Comment by tronlightracer** [comment]
@uranusjr I'm unfamiliar with pytests fixtures why would you use a fixture over just write code to delete the connection.

I just commited the code I would use however I'm running into issues deleting connections on the mysql unit test. Would you be able to guide me on how I might fix that?

**Comment by uranusjr** [comment]
A pytest fixture can be implemented and used like this:

```python
@pytest.fixture(scope="session")
def ensure_connection(request):
    def _ensure_session(conn_id: str, conn_type: str, ...):
        session = settings.Session()
        try:
            Connection.get_connection_from_secrets(conn_id)
        except AirflowNotFoundException:
            conn = session.add(Connection(conn_id=conn_id, conn_type=conn_type, ...))
            session.commit()

            def _delete_session():
                session.delete(conn)
                session.commit()

            request.addfinalizer(_delete_session)

    return _ensure_session


@mock.patch("airflow.operators.sql.BaseSQLOperator.get_db_hook")
def test_branch_single_value_with_dag_run(self, mock_get_db_hook, ensure_connection):
    ensure_connection("mysql_default")  # Only need to add this line at the beginning.
```

The fixture implementation should be relatively straightforward, except for some magic like `request` and `scope`, but you don’t need to worry about them if you are not interested. (If you are interested, however, [the official documentation](https://docs.pytest.org/en/stable/explanation/fixtures.html) should have answers for all your questions.

**Comment by uranusjr** [comment]
Please also run pre-commit locally to fix the errors.

**Comment by tronlightracer** [comment]
Hey @potiuk I apology for the late reply I've been dealing with some difficult life circumstances.

What I was trying to fix with this PR is that for the method `test_sql_branch_operator_postgres(self)` and `test_branch_single_value_with_dag_run(self)` the connection ID isn't defined so it can't run the test properly. 

I was able to add the connection successfully for `test_branch_single_value_with_dag_run()` for postgres but I'm unable to figure out how to add a connection for the `test_branch_single_value_with_dag_run(self)` method that used mysql.

How would you approach adding a connection for the `test_branch_single_value_with_dag_run(self)` method?

**Comment by potiuk** [comment]
Whatever you do - you cannot make side effects. You should mock/add connections. The only recommendation for me is to look how other tests do it, analyse and propose maybe even better approach.

**Pull request closed without merging**
