### PR TITLE
Logging and returning info about query execution SnowflakeHook

### PR DESCRIPTION
**Pull request by JavierLopezT**
This modification will log useful info about the execution. Some examples are:

```
Statement execution info - {'status': 'Statement executed successfully.'}
Statement execution info - {'status': 'Table STG_GOOGLE_ADS_HOURLY_CAMPAIGN successfully created.'}
Statement execution info - {'status': 'Copy executed with 0 files processed.'}
Statement execution info - {'number of rows deleted': 0}
Statement execution info - {'number of rows inserted': 0}
```

Also, these values are returned so that we can further implement behavior modifications in the Operators. For instance, in S3ToSnowflakeOperator, if the status is `Copy executed with 0 files processed we could raise an error`

I think new tests are not necessary since it just logs more info and returns a value

### CODE REVIEW

**Comment by potiuk** [comment]
I guess we can also add it as value returned by SnowflakeOperator's execute method ? It's backwards compatible, and with do_xcom_push = True (default) it will automatically create XCom with the output. Might be really useful.

**Comment by JavierLopezT** [comment]
> I guess we can also add it as value returned by SnowflakeOperator's execute method ? It's backwards compatible, and with do_xcom_push = True (default) it will automatically create XCom with the output. Might be really useful.

Done :)

**Comment by uranusjr** [comment]
It means the value you want to push cannot be serialised into JSON. What is the value that caused the failure?

**Comment by potiuk** [comment]
Seems that execution_info are "rows" returned by Cursor which is not json-serializable. 

This PyMSQL shows an example how you can do it: https://programmersought.com/article/12771376188/

**Comment by JavierLopezT** [comment]
> Seems that execution_info are "rows" returned by Cursor which is not json-serializable.
> 
> This PyMSQL shows an example how you can do it: https://programmersought.com/article/12771376188/

I made a workaround eventually. The real output is a list of dicts, so it is serializable with real data. The error was due to the mocking I think. 

Everything green now, I hope it can be merged soon

**Comment by potiuk** [comment]
> > Seems that execution_info are "rows" returned by Cursor which is not json-serializable.
> > This PyMSQL shows an example how you can do it: https://programmersought.com/article/12771376188/
> 
> I made a workaround eventually. The real output is a list of dicts, so it is serializable with real data. The error was due to the mocking I think.

I see. Yeah . Plausible.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
