### PR TITLE
Add index on end_date for task_instance

### PR DESCRIPTION
**Pull request by dstandish**
This is ~commonly~ sometimes used in API list task instances queries

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
After reading the email-thread - sounds reasonable to me to add this index. Also if slight overhead but if commonly used, then LGTM!

**Review by potiuk — APPROVED** [review]

**Review by Taragolis — CHANGES_REQUESTED** [review]
I would like to see any beneficial of add this index, with overall impacts of system performance, and not just one part.

Still not sure that this index would be use in general usage.

At lest would like to see performance impact in general before change and after.

Otherwise it could consider as a speculation that this index improve anything

**Comment by Taragolis** [comment]
And I'm not sure that this should be include into the patch release.

**Comment by dstandish** [comment]
Yeah the thing is with this is that it will help with probability 100%... _when_ it helps.

But not all customers will query in such a way that it will help.

For sufficiently large table, this will help a query with narrow band of end_date -- and I think we can all see that.

But then perhaps if you add a list of dags to the query, or list of task_ids, then it may not be able to use the index.

So what do we do about that?

This PR is, in part, a test case to illustrate the issue raised on the dev list.

**Pull request closed without merging**
