### PR TITLE
[AIRFLOW-3069] Log all output of the S3 file transform script

### PR DESCRIPTION
**Pull request by sjednac**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - [https://jira.apache.org/jira/browse/AIRFLOW-3069](https://jira.apache.org/jira/browse/AIRFLOW-3069)

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The output of the process spawned by `S3FileTransformOperator` is not properly decoded, which makes reading logs rather difficult. Additionally, the `stderr` stream is only shown when process exit code is not equal to `0`.

I would like to propose the following changes to `S3FileTransformOperator`:

- Send both output streams (stdout & stderr) to the logger, regardless of the outcome (if any data is present)
- Decode the output, so that new lines can be displayed correctly.
- Include process exit code in the exception message, if the process fails.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

I've added a separate case for testing `transform_script` with output present. Since logging is essential in this case, the test checks if a valid message was passed to the logging module. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @sbilinski , possibly attaching some screenshots or sample logs (before/after this commit, how the log looks like) may help folks estimate the impact/benefit this commit brings?

**Comment by sjednac** [comment]
Thanks for the suggestion @XD-DENG. Here's how it looks: 

#### Before 
airflow_s3_log_before

#### After
airflow_s3_log_after

Relevant `transform_script` code: 

```
def main(argv):
    ...

    print("Copying {0} to {1}.".format(src, dst))
    shutil.copyfile(src, dst)
    print("Done.")

    sys.stderr.write("I will fail on purpose\nExpected exit code is 42\n")
    sys.exit(42)
```

**Comment by sjednac** [comment]
It was suggested to me on Slack, that this might be considered a bug rather than a new feature (i.e. could potentially go to current `1.x` version rather than `2.x`).

**Comment by Fokko** [comment]
Thanks @sbilinski 

In the past we had some issues with separate stdout and stderr. What happend is that when the stderr buffer would fill up, and it wasn't being consumed, because it was still reading the stdout as long as the process lives, it would freeze in the end because of the full stderr buffer. This is a known bug which we've fixed in the bash_operator by piping stderr to stdout: https://github.com/apache/incubator-airflow/blob/master/airflow/operators/bash_operator.py#L112

**Comment by sjednac** [comment]
Thanks for pointing it out @Fokko. I'm going to adjust this and get back to you. 

For reference: [a blog post](https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/) describing the issue in detail.

**Comment by Fokko** [comment]
Thanks @sbilinski for the reference, I was looking for it, but couldn't find it in time. Let me know when you've updated the PR.

**Comment by sjednac** [comment]
@Fokko I've applied some changes and rebased against `master` - please take another look.

**Comment by Fokko** [comment]
Thanks @sbilinski 

Very nice PR which also makes the code more readable. LGTM merging to master.

**Pull request merged**
