### PR TITLE
[AIRFLOW-2328] Fix empty GCS blob in S3ToGoogleCloudStorageOperator

### PR DESCRIPTION
**Pull request by wileeam**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2328\] Fix empty GCS blob in S3ToGoogleCloudStorageOperator"
    - https://issues.apache.org/jira/browse/AIRFLOW-2328

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
    - Fixes a non-covered case when the destination GCS path for syncing with S3 only consists of the GCS bucket, that is, the GCS blob path is empty.

### Tests
- [x] My PR does not need testing for this extremely good reason:
    - Prior tests still apply: `tests/contrib/operators/test_s3_to_gcs_operator.py`

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
So, what's the difference. Also with a root directory you can still add a trailing `/`, right?

**Comment by wileeam** [comment]
Yes.

I missed testing such case where the pair (`bucket`,`blob`), as returned by `_parse_gcs_url` in `contrib/hooks/gcs_hook.py` would have an empty `blob`, and given that i made the requirement of a trailing `/` for such blob... this would always fail. See below:
```
>>> _parse_gcs_url("gs://")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "airflow/contrib/hooks/gcs_hook.py", line 457, in _parse_gcs_url
    raise AirflowException('Please provide a bucket name')
airflow.exceptions.AirflowException: Please provide a bucket name
>>> _parse_gcs_url("gs:///")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "airflow/contrib/hooks/gcs_hook.py", line 457, in _parse_gcs_url
    raise AirflowException('Please provide a bucket name')
airflow.exceptions.AirflowException: Please provide a bucket name
>>> _parse_gcs_url("gs://pong")
('pong', '')
>>> _parse_gcs_url("gs://pong/")
('pong', '')
>>> _parse_gcs_url("gs://pong///")
('pong', '')
>>> _parse_gcs_url("gs://pong/ping")
('pong', 'ping')
>>> _parse_gcs_url("gs://pong/ping/")
('pong', 'ping/')
>>> _parse_gcs_url("gs://pong/ /")
('pong', ' /')
```
Note how `_parse_gcs_url` removes any trailing `/` after the bucket name as this is done by the functionality given in `urlparse`.

So the requirement of a trailing `/` in the operator still applies, but it should allow root directory as blob, which is the same as empty `blob`.
Allowing for no trailing `/` would complicate the logic of the operator when comparing the contents of the S3 bucket/keys and GCS bucket/objects for syncing. I think that the normal behaviour is to sync contents in 'directories' hence the semantics of a trailing '/' make it clearer and easier to understand.

**Comment by wileeam** [comment]
@Fokko Did you have a look at my reply...?

**Review by Fokko — APPROVED** [review]
Yes, it makes sense. Thanks @wileeam

**Pull request closed without merging**
