### PR TITLE
Add Changelog updates for 2.1.1

### PR DESCRIPTION
**Pull request by jhtimmins**

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
🎉

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
Will need to fix/ignore some of the spellings.

**Review by potiuk — COMMENTED** [review]
Just a comment  - for Provider packages, I automatically add double-reversed-quotes around all commit messages via the scripts that prepare changelogs. I'd probably go mad if I did not :)

**Comment by ashb** [comment]
>   Error: fatal: unable to access 'https://github.com/apache/airflow/': The requested URL returned error: 500

Amazing timing :grin:

**Comment by potiuk** [comment]
> Amazing timing 😁
Yeah. few other people's PRs suffering from similar issues. The https://www.githubstatus.com/ does not show anything yet but it's inevitable.

**Comment by potiuk** [comment]
It's ALWAYS the worst possible time.

**Comment by ashb** [comment]
Docs build has passed. Lets merge this.

**Pull request merged**
