### PR TITLE
[AIRFLOW-840] Make ticket renewer python3 compatible

### PR DESCRIPTION
**Pull request by abij**
The return from the subprocess is in bytes when the universal
 newlines is set to False (default). This will fail in Py3 and
 works fine in Py2.

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-840

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Let us discuss this when I'm back. You probably need to add an extra User. I think it is a permission problem

**Comment by bolkedebruin** [comment]
Looks good in general. Are all changes required to setup_kdc.sh? Please also squash your commits into one.

**Comment by abij** [comment]
Squeezed into single commit and removed some unnecessary bash commands in setup_kdc.sh

**Comment by bolkedebruin** [comment]
Lgtm!

**Pull request closed without merging**
