### PR TITLE
Revert "Add support for creating multiple replicated clusters in Bigt…

### PR DESCRIPTION
**Pull request by potiuk**
…able hook and operator (#10475)"

This reverts commit b0598b5351d2d027286e2333231b6c0c0704dba2.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
It  think the #10475 broke the mater. It looks like the tests passed before they were merged, but the build was running before the fx #10472  was merged that was mixing local/image sources or it could be a manifestation of #10471. I will take a look where it came from and whether we need to implement the workaround I described in #10471.  For now - let's revert it - and I will ask the author to resubmit it.

**Comment by olchas** [comment]
I think the reason for broken master is the combination of @derrickqin's https://github.com/apache/airflow/pull/10475 and my change https://github.com/apache/airflow/pull/10052. @derrickqin's PR added two tests of `BigtableCreateInstanceOperator` that I have not covered in my PR after rebasing. I apologize for that. Here is the fix: https://github.com/apache/airflow/pull/10521.

**Comment by potiuk** [comment]
Cool. Thanks @olchas ! Nothing to worry about -- this is the rare case where two overlapping changes tested in isolation do not work when they are both merged :). No-one's fault, just a consequence of us not doing the full cycle of rebase + wait for build after anything is merged (that would be very costly, so we accept that things break in such cases very rarely).

**Comment by potiuk** [comment]
@derrickqin -> alarm called off :)

**Pull request closed without merging**
