### PR TITLE
[AIRFLOW-626] HTML Content does not show up when sending email with attachment

### PR DESCRIPTION
**Pull request by illop**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-626

Per Apache guidelines you need to create a [Jira issue](https://issues.apache.org/jira/browse/AIRFLOW/).

Testing Done:
- Unittests are required, if you do not include new unit tests please
specify why you think this is not required. We like to improve our
coverage so a non existing test is even a better reason to include one.

Reminders for contributors (REQUIRED!):
* Your PR's title must reference an issue on 
[Airflow's JIRA](https://issues.apache.org/jira/browse/AIRFLOW/). 
For example, a PR called "[AIRFLOW-1] My Amazing PR" would close JIRA 
issue #1. Please open a new issue if required!

* For all PRs with UI changes, you must provide screenshots. If the UI changes are not obvious, either annotate the images or provide before/after screenshots.

* Please squash your commits when possible and follow the [How to write a good git commit message](http://chris.beams.io/posts/git-commit/). 
Summarized as follows:
  1. Separate subject from body with a blank line
  2. Limit the subject line to 50 characters
  3. Do not end the subject line with a period
  4. Use the imperative mood in the subject line (add, not adding)
  5. Wrap the body at 72 characters
  6. Use the body to explain what and why vs. how

### CODE REVIEW

**Comment by criccomini** [comment]
LGTM but let's let the tests run

**Comment by criccomini** [comment]
Note: this is slightly backwards incompatible because it changes the default from alternative to mixed, but IMO it's actually the right default, and allows those who care to keep it the old way if they want.

**Comment by criccomini** [comment]
@illop one other thought: should we update the EmailOperator to allow us to set this?

**Comment by illop** [comment]
ah, can do

**Comment by r39132** [comment]
@criccomini @illop 
This is breaking the email test and hence master. I will need to revert. Please consider resubmitting this with the tests fixed. I'm not clear how you were able to submit with broken tests.

https://travis-ci.org/apache/incubator-airflow/jobs/175858834

```
======================================================================
FAIL: test_custom_backend (tests.EmailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/apache/incubator-airflow/tests/core.py", line 1927, in test_custom_backend
    send_email_test.assert_called_with('to', 'subject', 'content', files=None, dryrun=False, cc=None, bcc=None)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: mock('to', 'subject', 'content', bcc=None, cc=None, dryrun=False, files=None)
Actual call: mock('to', 'subject', 'content', bcc=None, cc=None, dryrun=False, files=None, mime_subtype=u'mixed')

```

**Pull request closed without merging**
