### PR TITLE
[AIRFLOW-3751] Ignore malformed ldap schema option

### PR DESCRIPTION
**Pull request by colin-streicher**
### Jira

This PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-3751/) issues and references them in the PR title.

### Description

This change includes a configuration option to allow ldap authentication to use ldap services that may not return schemas or return invalid ones. To allow malformed schemas, the configuration value of ignore_malformed_schema is added as a boolean. The default is the current behaviour.

### Tests

- The changes introduced by this PR are covered by existing unit tests.

### Code Quality

Passes `flake8`

### CODE REVIEW

**Comment by colin-streicher** [comment]
I do not believe the failing tests are a result of my changes. 

Edit: Rebasing fixed the issues, tests pass now.

**Comment by seelmann** [comment]
Two thoughts:
1. Is it possible to set `set_info=NONE` when creating the `Server` object? This option seems to prevent that the schema is fetched at all. Looking at the code it seems the schema is not required. See https://ldap3.readthedocs.io/server.html?highlight=get_info#server-object)
2. With removal of the old Web UI in master and usage of FAB based UI this class is no longer used, tests are actually already skipped. So it may only make sense to apply those changes on 1.10.3.

**Comment by iamsaso** [comment]
:pray:

**Comment by ashb** [comment]
@seelmann I'm not familiar with the LDAP path, but is this fix good enough to go in for 1.10.3 given it's already deleted/disabled on master?

**Comment by seelmann** [comment]
@ashb Yes, it's fine to apply this patch for 1.10.3. :+1:

**Comment by colin-streicher** [comment]
@seelmann I completely missed the notification for this comment, and it even though it is already merged, it is worth responding to I think. 

My initial thought was to use the set_info setting, this would have the added benefit of being able to set the level of requested information from the server to several different levels. However, I decided against this because the upstream ldap library was using this set_info setting as default. Since I do not understand why this is the case, I decided that setting the malformed schema option was safer in that the name of the option implies that schema checking is being turned off. 

Regardless, the result of both end up being the same, so I would have been ok with either. I had few more changes that allowed more options, but with the move to FAB, it doesn't seem like they would be used.

**Pull request merged**
