### PR TITLE
[AIRFLOW-3622] Add ability to pass hive_conf to HiveToMysqlTransfer

### PR DESCRIPTION
**Pull request by aliceabe**
### Jira

- [x] My PR addresses the following Airflow Jira issues and references them in the PR title. 
  - https://issues.apache.org/jira/browse/AIRFLOW-3622

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Right now we cannot overwrite Hive Yarn queue because `hive_conf` is not passed to `HiveToMySqlTransfer`

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### Reviewers

@KevinYang21 @feluelle @feng-tao

### CODE REVIEW

**Review by feng-tao — COMMENTED** [review]
the change makes sense. Could you add a test on the new code? thanks.

**Comment by aliceabe** [comment]
Thanks @feng-tao Added a test

**Comment by feluelle** [comment]
Lgtm :)

**Comment by feng-tao** [comment]
thanks. lgtm

**Comment by kaxil** [comment]
Can you please resolve an error that was in the PR but because of broken Travis it wasn't detected:

```
======================================================================
33) FAIL: test_execute (tests.operators.test_hive_to_mysql.TestHiveToMySqlTransfer)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 1305 in patched
      return func(*args, **keywargs)
    tests/operators/test_hive_to_mysql.py line 46 in test_execute
      mock_hive_hook.return_value.get_records.assert_called_once_with(self.kwargs['sql'])
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 948 in assert_called_once_with
      return self.assert_called_with(*args, **kwargs)
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 937 in assert_called_with
      six.raise_from(AssertionError(_error_message(cause)), cause)
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/six.py line 737 in raise_from
      raise value
   AssertionError: Expected call: get_records('sql')
   Actual call: get_records('sql', hive_conf={})
   -------------------- >> begin captured logging << --------------------
   airflow.task.operators: INFO: Extracting data from Hive: sql
   airflow.task.operators: INFO: Inserting rows into MySQL
   airflow.task.operators: INFO: Done.
   --------------------- >> end captured logging << ---------------------
```
Please fix it in the new PR.

**Pull request merged**
