### PR TITLE
[AIRFLOW-937] Improve performance of task_stats

### PR DESCRIPTION
**Pull request by saguziel**
Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-937

Testing Done:
- Shouldn't change functionality significantly, should pass existing tests (if they exist)

This leads to slightly different results, but it reduced the time of this endpoint from 90s to 9s on our data, and the existing logic for task_ids was already incorrect (task_ids may not be distinct across dags)

@bolkedebruin @aoen @zodiac @plypaul

### CODE REVIEW

**Comment by saguziel** [comment]
There's a lot of n+1 and long queries that I have on my list

**Comment by aoen** [comment]
LGTM

**Comment by bolkedebruin** [comment]
@aoen closing/merging these is going a bit fast imho - tests have not run and the commit message is unclean (just a copy of the PR message). Can we take it a little bit slower?

**Comment by aoen** [comment]
My bad on the tests, need to unlearn my habit of assuming tests have been run if something is mergeable :). Commit message I cleaned up a bit (e.g. it had [AIRFLOW-XXX] and I removed the reviewers), are there other things that should be changed?

**Comment by bolkedebruin** [comment]
The commit message now reads

```
Please accept this PR that addresses the following
issues:
-
https://issues.apache.org/jira/browse/AIRFLOW-937

Testing Done:
- Shouldn't change functionality significantly,
should pass existing tests (if they exist)

This leads to slightly different results, but it
reduced the time of this endpoint from 90s to 9s
on our data, and the existing logic for task_ids
was already incorrect (task_ids may not be
distinct across dags)
```

It doesn't specify why and what, i.e. it is unclear why something is wrong (need to follow link) and what is fixed. `Please accept this PR` doesn't really add value to the message.

I understand the need and want to get fixes in quickly, but being able to go through an understandable history is just as important :).

**Comment by aoen** [comment]
Makes sense, I'll augment the template to reduce the need to mess around with user commit messages so much.

**Comment by bolkedebruin** [comment]
I normally use the user commit message and ask them / educate them to provide a good one themselves. Makes our lives easier in the end. Do you use the PR message on purpose with the airflow-pr tool?

**Comment by bolkedebruin** [comment]
@aoen @saguziel this fails on Postgres see https://travis-ci.org/bolkedebruin/airflow/jobs/207421220

Just to help you out. It seems to have to do how booleans are tested (did not confirm, just read the error message). See also https://github.com/apache/incubator-airflow/pull/2022 for an example how this worked for ms sql.

Can you please fix this?

**Comment by plypaul** [comment]
@aoen @saguziel - is this still broken on Postgres?

**Comment by saguziel** [comment]
@plypaul  no, see https://github.com/apache/incubator-airflow/pull/2123

**Pull request closed without merging**
