### PR TITLE
[AIRFLOW-4843] Allow orchestration via Docker Swarm aka SwarmOperator 

### PR DESCRIPTION
**Pull request by akki**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [AIRFLOW-4843](https://issues.apache.org/jira/browse/AIRFLOW-4843/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-4843
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
       Added in issue - https://issues.apache.org/jira/browse/AIRFLOW-4843

### Tests

- [x] My PR adds the following unit tests:
    `SwarmOperatorTestCase`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by akki** [comment]
The check that has failed is [`Check license header`](https://travis-ci.org/apache/airflow/jobs/550739577) and the error doesn't seem to be related to this PR: `Our attempt to download rat locally to /tmp/lib/apache-rat-0.12.jar failed.`.

I see the [same error](https://travis-ci.org/apache/airflow/jobs/550526211) with [another recent PR](https://github.com/apache/airflow/pull/5481) so I am guessing there's some problem with the Travis build? Is there any such known issue?

**Comment by ashb** [comment]
Please target the master branch for PRs.

**Comment by akki** [comment]
@ashb I was planning to work on the `master` branch earlier but soon realised that there are a lot of breaking changes between that and the current version that gets installed with `pip` i.e. `1.10.3`.

Would you still suggest me to port this code as per `master`? How would these changes get integrated into `1.10.3` in that case because that is what we are currently using in my company (and have other scripts which break if run against master)?

**Comment by akki** [comment]
Created another PR against `master`, just in case it is possible to add this feature to `v1.10` as well - https://github.com/apache/airflow/pull/5489.

**Comment by akki** [comment]
This branch has diverged a lot from the actual branch, so closing this (at least for now).
Current PR - https://github.com/apache/airflow/pull/5489.

**Pull request closed without merging**
