### PR TITLE
[AIRFLOW-4401] Reliable SynchronizedQueue used instead of multiprocessing.Queue

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4401
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

It solves unreliable behaviour of multiprocessing.Queue.empty() - sometimes returning True when the queue is not really empty.

### Tests

- [x] My PR does not need testing for this extremely good reason:
We already have LocalExecutor and other tests that will just become less flaky.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by milton0825 — APPROVED** [review]
Good change 👍  I am curious about how you find out the cause

**Comment by BasPH** [comment]
Awesome work @potiuk! I find it hard to believe a SynchronizedQueue is not part of the multiprocessing package. You could also submit a PR to the Python stdlib 😄?

Anyways, the test_execution_limited_parallelism test consistently succeeds now. Great work! I believe my commit permissions still have to propagate, but LGTM.

**Comment by feng-tao** [comment]
@potiuk , nice work :) 👍 I wonder what is your approach to root cause the issue is due to multiprocessing.Queue.empty()?

**Comment by feng-tao** [comment]
In-depth discussion in https://github.com/apache/airflow/pull/5159

**Comment by potiuk** [comment]
I put all details in https://issues.apache.org/jira/browse/AIRFLOW-4401 :)

**Comment by potiuk** [comment]
@basph yeah. I might consider that. I will put that on my TODO list. But most of the work was done by https://github.com/vterron in https://github.com/vterron/lemon/commit/9ca6b4b1212228dbd4f69b88aaf88b12952d7d6f  . I merely found out the reason, reviewed the code, pulled in, updated for python3.5+ (like in "Standing on the shoulders of giants").

**Comment by potiuk** [comment]
Since @BasPH reviewed it (even if he has no github permission yet) I allowed myself to merge it to get other make use of the more reliable tests :)

**Comment by potiuk** [comment]
It's already merged, but as (rightfully) pointed out by @ashb this change might have potential side effects. I will take closer look to be sure that it will have no unforeseen consequences.

**Pull request merged**
