### PR TITLE
[AIRFLOW-8472]: `PATCH` for Databricks hook `_do_api_call`

### PR DESCRIPTION
**Pull request by dimonchik-suvorov**
Support of `PATCH` for Databricks hook `_do_api_call` function

### CODE REVIEW

**Comment by houqp** [comment]
For context, databricks has a beta API that uses PATCH method. Having this change in upstream makes easier for us to implement support for that. Once the API is out of beta, we will contribute that to the databricks hook as well.

**Review by potiuk — COMMENTED** [review]
Can you please add a test for it?

**Comment by dimonchik-suvorov** [comment]
> Can you please add a test for it?

There wasn't initial test for methods check, but yes, I can do that

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Great ! thanks @dimonchik-suvorov !

**Pull request merged**
