### PR TITLE
[AIRFLOW-343]: Fixed schema plumbing in HiveServer2Hook

### PR DESCRIPTION
**Pull request by gr8routdoors**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- HiveServer2Hook does not propagate the schema setting correctly.  With this fix users can now set/override the schema in an operator using a Hive Server 2 connection.
- I don't see an issue for this in Airflow's JIRA yet:  https://issues.apache.org/jira/browse/AIRFLOW-230?jql=project%20%3D%20AIRFLOW%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22hive%22%20ORDER%20BY%20priority%20DESC%2C%20key%20DESC

Testing Done:

Reminders for contributors:
- Your PR's title must reference an issue on [Airflow's JIRA](https://issues.apache.org/jira/browse/AIRFLOW/). For example, a PR called "[AIRFLOW-1] My Amazing PR" would close JIRA issue #1. Please open a new issue if required!
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules).

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@devonberry Thanks for the contribution. If a Jira does not exist yet you will need to create one yourself. This is by Apache requirements. In addition as this is a core hook, please provide updated tests to cover this scenario. Hive is available on travis.

Thanks!

**Comment by gr8routdoors** [comment]
I've created the jira ticket and added tests.  I didn't see any assertions on the existing test suite:  https://github.com/apache/incubator-airflow/blob/master/tests/operators/hive_operator.py#L40-L69

so I went ahead and took a mockist approach. Will resolve conflicts in my next update.

**Comment by gr8routdoors** [comment]
Conflicts merged and the CI failure looks due to `tox` failing to archive:
`The command "tox -e $TOX_ENV" exited with 1.`

Should be good to go.

**Comment by gr8routdoors** [comment]
New PR with clean commit history based of current master:  https://github.com/apache/incubator-airflow/pull/1743

**Pull request closed without merging**
