### PR TITLE
Recognize more ways to import DAG in ChainBetweenDAGAndOperatorNotAllowedRule

### PR DESCRIPTION
**Pull request by Seltsamsel**
This solves the second issue mentioned in #13287 . The problem basically is, that currently only `from airflow.models import DAG` is recognized, but it's not unlikely, that e.g. `from airflow import models` followed by `models.DAG(...)` is used.
This PR recognizes all ways of importing / using the DAG class, as long as it is not renamed (e.g. `from airflow.models import DAG as AirflowDAG`).

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
re-triggering ci.

**Comment by mcepok** [comment]
@ashb anything left to do?

**Comment by ashb** [comment]
Hmmm, why are tests not running. Lets try this once more.

**Comment by mcepok** [comment]
So the fails for the 2.7 images are because `from unittest.mock import patch` seems to not exists for python 2.7 . However, that PR is already merged (#14913). The fix is trivial, I can include it here or create another PR. What do you prefer @ashb ?

The other fails are related to docker
`pull access denied for prestosql/presto, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`
:shrug:

**Pull request closed without merging**
