### PR TITLE
[AIRFLOW-1540] Add proxies to Slack Operator

### PR DESCRIPTION
**Pull request by ghost**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1540
      "Airflow 1.8.1 - Add proxies to slack operator"

### Description
- Airflow Slack Operator is not working as expected for servers using proxies to connect to open internet. This PR will help to use proxies in connection and resolve existing issue of connection timed out.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [AIRFLOW-1540] Add proxies to Slack Operator

### CODE REVIEW

**Comment by ghost** [comment]
@saguziel @bolkedebruin please look into this pr and let me know your feedback.

**Comment by ghost** [comment]
@aoen or @criccomini can you please look into this pr and let me know your feedback, thanks.

**Comment by bolkedebruin** [comment]
Why not use the system wide proxy? (Http_proxy)?

**Comment by ashb** [comment]
This should just be cone by setting the `http_proxy` or `https_proxy` environment variables.

**Pull request closed without merging**
