### PR TITLE
Added DataReply to the list of Airflow Users

### PR DESCRIPTION
**Pull request by kaxil**
Added myself & my Company (DataReply) to the list of Airflow users.

Make sure you have checked _all_ steps below.

### JIRA
- [n/a] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [n/a] Here are some details about my PR, including screenshots of any UI changes:
Added me & my Company (DataReply) to the list of Airflow users.

### Tests
- [n/a] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Just an addition to my company and myself to the list of airflow users. No code changes

### Commits
- [n/a] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [n/a] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
@criccomini Can you please take care of this one as well if it's possible?

**Comment by criccomini** [comment]
LGTM

**Comment by criccomini** [comment]
Merged.

**Comment by criccomini** [comment]
Failure is due to random failure on one of the travis builds.

**Pull request closed without merging**
