### PR TITLE
Updating TESTING.rst with minor grammatical corrections

### PR DESCRIPTION
**Pull request by yajna-pandith**
Updating TESTING.rst with minor grammatical corrections

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @yajna-pandith !

**Comment by kaxil** [comment]
@yajna-pandith Can you add more descriptive PR title please for other PRs? This title/commit message would appear in CHANGELOG and it isn't super clear from "Updating README.MD" on what actually was updated

**Comment by yajna-pandith** [comment]
@kaxil Thankyou for letting me know. I have changed the title. 
Since I have done lot of changes in one PR the title looks very big.
Should I make only one change per PR with respect to documentation changes in the future?

**Comment by kaxil** [comment]
`Updating TESTING.rst with minor grammatical corrections` - Your PR description can be your title :)

**Comment by yajna-pandith** [comment]
Corrected :)

**Pull request merged**
