### PR TITLE
Remove deprecated stuff from Amazon provider package

### PR DESCRIPTION
**Pull request by vincbeck**
A new major version will be released in the Amazon provider package (see breaking change in #42218). As such, it is a good time to do some clean up.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vincbeck** [comment]
Tests are expected to fail. I'll resolve them

**Comment by vincbeck** [comment]
> We need change log entry explaining what we broke (list of items)

Here we just remove deprecated stuff, do I need to list them all? I will also do it for #42218 (sorry I missed that). BTW, where should I write this changelog?

**Review by o-nikolas — APPROVED** [review]
I did a few spot checks, it's a large PR, but what I looked at seems good and the tests passing.

**Comment by vincbeck** [comment]
@eladkal Could you check the changelog looks good to you?

**Review by eladkal — APPROVED** [review]

**Pull request merged**
