### PR TITLE
Add custom metadata to Tasks in Graph View

### LINKED ISSUE #27795: Add custom metadata to Tasks in Graph View
### Description

This feature would enable the user to add custom metadata that would be viewable within the tooltip upon hovering on a Task in Graph View.

Currently when the user hovers on a Task in Graph View, they can see the following:

**There is a DAG run**
image

**There is no DAG run**
image

TaskGroups allow the user to add custom information to the tooltip by providing it in the `tooltip` field on instantiation:

image

The information in the tooltip could be fully customizable, or scoped to a specific use case - for example, adding just the Dataset associated with a task.

#### General information about a task

TaskGroups allow the user to provide custom metadata about a task. This would be similarly useful for Tasks.

#### Sources and Targets

Tasks often have information like source and target. Airflow 2.4 introduced the concept of Datasets. In Dataset view, the user can see which tasks influence datasets. This information would also be useful in Graph View - on hover, the user could see the Dataset(s) specified to the Operator.

### Related issues

[AIP-34](https://github.com/apache/airflow/pull/10153) added TaskGroup. Users can customize the information in a TaskGroup's tooltip.

AIP-34 implemented [Issue #8078](https://github.com/apache/airflow/issues/8078).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
closes: #27795

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by amoghrajesh** [comment]
@uranusjr decided to try my hand again at this PR. 
I think I am missing ends here. Wanted to know where the UI rendering happens for the base operator too.

**Comment by uranusjr** [comment]
The rendering part is in `airflow/www/views.py`, and the graph view specifically is rendered in a function called `graph`. You can probably find the tasks in `dag.tasks` (there’s already a loop serialising them). And then you need to change the frontend to use those values.

**Comment by bbovenzi** [comment]
You just need to update this line of the UI code and make sure that the new tooltip variable is passed all the way: https://github.com/apache/airflow/blob/main/airflow/www/static/js/dag/InstanceTooltip.tsx#L68

**Comment by amoghrajesh** [comment]
@bbovenzi how can I find out if it uses the same `.tooltip` as the task group? Interested in exploring this issue a bit more

**Comment by bbovenzi** [comment]
@amoghrajesh if you're still interested, [here](https://github.com/apache/airflow/blob/main/airflow/utils/task_group.py#L75) is where we define tooltips for a task_group.

I think we would just need to change a check inside of grid_data or graph_data.

**Pull request closed without merging**
