### PR TITLE
[AIRFLOW-5803] Update S3Hook import paths [AIP-21]

### PR DESCRIPTION
**Pull request by mingrammer**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5803
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Why did you add the AWS prefix? This is not in line with GCP operator naming guidelines. We have no general rules, so we can use the GCP if they make sense.  

Maybe you would like to help with creating a document describing the general principles of naming operators. I will gladly add my comments. A spreadsheet with planned changes would also be helpful. I have these for GCP changes.

CC: @BasPH @potiuk 

https://docs.google.com/document/d/1_rTdJSLCt0eyrAylmmgYc3yZr-_h51fVlnvMmWqhCkY/edit?ts=5bb72dfd#

**Comment by mingrammer** [comment]
As I mentioned here https://github.com/apache/airflow/pull/6455#issuecomment-547451363, I just followed the current class naming conventions for other AWS operators/hooks.

So I'm a bit confused about which conventions I should follow.

**Comment by mik-laj** [comment]
I am not sure of the correct solution. Can you write about this problem on mailing list?  I don't think there has been an official discussion yet about ordering class names for AWS. The only document that describes it is AIP-21

> Case #6 Other isolated cases
> There are other random cases of inconsistencies in the naming of classes. It is necessary to review the list of all classes and prepare a plan of change. Support from major cloud service providers will be useful.

My team has support from Google, so we have a plan that was presented in the integration guide.

**Comment by mingrammer** [comment]
I sent a new thread on the mailing list about it!

https://lists.apache.org/thread.html/5ed0ce4dfd77640d7464dc57d4fafc75e8aac44e016f87ca1be3a4a3@%3Cdev.airflow.apache.org%3E

**Comment by mingrammer** [comment]
According to some threads on the above mail (all the conventions were proposed by @BasPH), I think we should keep the name `S3Hook` as is.

So I'll fix the `AWSS3Hook` back to `S3Hook`, and will update all its import paths.

**Comment by mingrammer** [comment]
Done.

**Comment by mingrammer** [comment]
By the final voting result, It seems to have to move `S3Hook` into `/providers/amazon/aws`.

Should I update it with an another PR?

> https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths#AIP-21:Changesinimportpaths-Votingresults(seevotingbelow)

**Comment by potiuk** [comment]
Ah. My bad @mingrammer. I was too fast. Can you please make another one to move to amazon.aws ?

**Comment by potiuk** [comment]
I actually had to revert it as it was failing without rebase. Can you please rebase/reopen and add amazon package?

**Comment by mingrammer** [comment]
Sure, I'll do!

**Comment by dazza-codes** [comment]
Related PR in https://github.com/apache/airflow/pull/6764 for batch operator, so I need to follow all this API-21 stuff in a few places (although I'd prefer to just merge it and have the subsequent API-21 stuff applied in one larger PR, but looks like it's already piecemeal).

**Comment by ashb** [comment]
> Related PR in #6764 for batch operator, so I need to follow all this API-21 stuff in a few places (although I'd prefer to just merge it and have the subsequent API-21 stuff applied in one larger PR, but looks like it's already piecemeal).

If you want to do one large rename PR I'm all for it - ping me if you want a reviewer on it :)

**Pull request merged**
