### PR TITLE
Fix location on cloud build operators

### PR DESCRIPTION
**Pull request by tnk-ysk**
Fixed an issue where cloud build operators did not work for private pools or a non-global default pools.
In this case the CloudBuildClient must set the location with api_endpoint.

[Document](https://github.com/googleapis/python-cloudbuild/blob/9cf4f4269b55213c1f84206923d3cdc0308ecf57/samples/snippets/quickstart.py#L35-L43)
```
    # If you're using Private Pools or a non-global default pool, add a regional
    # `api_endpoint` to `CloudBuildClient()`
    # For example, '<YOUR_POOL_REGION>-cloudbuild.googleapis.com'
    #
    # from google.api_core import client_options
    # client_options = client_options.ClientOptions(
    #     api_endpoint="us-central1-cloudbuild.googleapis.com"
    # )
    # client = cloudbuild_v1.services.cloud_build.CloudBuildClient(client_options=client_options)
```

Related https://github.com/apache/airflow/pull/29689

Target operators
- CloudBuildCancelBuildOperator
- CloudBuildGetBuildOperator
- CloudBuildListBuildsOperator
- CloudBuildRetryBuildOperator
- CloudBuildListBuildTriggersOperator
- CloudBuildCreateBuildOperator
- CloudBuildCreateBuildTriggerOperator
- CloudBuildDeleteBuildTriggerOperator
- CloudBuildGetBuildTriggerOperator
- CloudBuildRunBuildTriggerOperator
- CloudBuildUpdateBuildTriggerOperator
- CloudBuildDeleteBuildTriggerOperator

## Reference
- https://cloud.google.com/build/docs/private-pools/private-pools-overview

### CODE REVIEW

**Comment by potiuk** [comment]
LGTM. @VladaZakharova - WDYT?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
tests needs fixing though

**Comment by tnk-ysk** [comment]
@potiuk
> tests needs fixing though 

I fixed it.
https://github.com/apache/airflow/pull/29937/commits/23cd526d1eb6e802ac6baf970ec893e8c8e435f8

**Comment by VladaZakharova** [comment]
Hi!
Did you check if, for example, BigQuery service is working okay with this changes without providing location to the operator?

**Comment by tnk-ysk** [comment]
@VladaZakharova 
I checked and fixed some issues.
1. Fixed some bugs.
2. CloudBuildTriggerOperator had a similar issue, fixed.
3. Fixed CloudBuild links.

Test dag
```
from __future__ import print_function

import datetime
import os

from airflow import models
from airflow.providers.google.cloud.operators import cloud_build
from airflow.providers.google.cloud.utils import credentials_provider

PROJECT_ID = "xxxxxxx"
REPO_NAME = "sample"

gcp_conn = credentials_provider.build_gcp_conn(
    "/files/key.json",
    ["https://www.googleapis.com/auth/cloud-platform"],
    PROJECT_ID,
)
os.environ["AIRFLOW_CONN_GOOGLE_CLOUD_DEFAULT"] = gcp_conn

default_dag_args = {
    'start_date': datetime.datetime(2022, 9, 28),
}

with models.DAG(
    'CloudBuildTest',
    schedule_interval=None,
    default_args=default_dag_args,
    catchup=False
) as dag:
    build = {
        "steps": [{
            "name": "alpine",
            "script": "sleep 10 && echo hello",
        }],
    }
    trigger = {
        "name": "trigger",
        "trigger_template": {
            "repo_name": REPO_NAME,
            "branch_name": "main",
        },
        "filename": "cloudbuild.yaml",
    }

    # global
    create_build_global = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_global",
        project_id=PROJECT_ID,
        build=build,
    )
    create_build_global_deferrable = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_global_deferrable",
        project_id=PROJECT_ID,
        build=build,
        deferrable=True,
    )
    list_build_global = cloud_build.CloudBuildListBuildsOperator(
        task_id="list_build_global",
        project_id=PROJECT_ID,
        page_size=1,
    )
    retry_build_global = cloud_build.CloudBuildRetryBuildOperator(
        task_id="retry_build_global",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="create_build_global", key="id") }}',
    )
    get_build_global = cloud_build.CloudBuildGetBuildOperator(
        task_id="get_build_global",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="retry_build_global", key="id") }}',
    )
    list_build_triggers_global = cloud_build.CloudBuildListBuildTriggersOperator(
        task_id="list_build_triggers_global",
        project_id=PROJECT_ID,
    )
    create_build_global_for_cancel = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_global_for_cancel",
        project_id=PROJECT_ID,
        build=build,
        wait=False,
    )
    cancel_build_global = cloud_build.CloudBuildCancelBuildOperator(
        task_id="cancel_build_global",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="create_build_global_for_cancel", key="id") }}',
    )
    create_build_trigger_global = cloud_build.CloudBuildCreateBuildTriggerOperator(
        task_id="create_build_trigger_global",
        project_id=PROJECT_ID,
        trigger=trigger,
    )
    get_build_trigger_global = cloud_build.CloudBuildGetBuildTriggerOperator(
        task_id="get_build_trigger_global",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_global", key="id") }}',
    )
    update_build_trigger_global = cloud_build.CloudBuildUpdateBuildTriggerOperator(
        task_id="update_build_trigger_global",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_global", key="id") }}',
        trigger=trigger,
    )
    run_build_trigger_global = cloud_build.CloudBuildRunBuildTriggerOperator(
        task_id="run_build_trigger_global",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_global", key="id") }}',
        source={
            "branch_name": "main"
        }
    )
    delete_build_trigger_global = cloud_build.CloudBuildDeleteBuildTriggerOperator(
        task_id="delete_build_trigger_global",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_global", key="id") }}',
    )

    # us-centrarl
    create_build_us_central1 = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_us_central1",
        project_id=PROJECT_ID,
        build=build,
        location="us-central1",
    )
    create_build_us_central1_deferrable = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_us_central1_deferrable",
        project_id=PROJECT_ID,
        build=build,
        deferrable=True,
        location="us-central1",
    )
    list_build_us_central1 = cloud_build.CloudBuildListBuildsOperator(
        task_id="list_build_us_central1",
        project_id=PROJECT_ID,
        page_size=1,
        location="us-central1",
    )
    retry_build_us_central1 = cloud_build.CloudBuildRetryBuildOperator(
        task_id="retry_build_us_central1",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="create_build_us_central1", key="id") }}',
        location="us-central1",
    )
    get_build_us_central1 = cloud_build.CloudBuildGetBuildOperator(
        task_id="get_build_us_central1",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="retry_build_us_central1", key="id") }}',
        location="us-central1",
    )
    list_build_triggers_us_central1 = cloud_build.CloudBuildListBuildTriggersOperator(
        task_id="list_build_triggers_us_central1",
        project_id=PROJECT_ID,
        location="us-central1",
    )
    create_build_us_central1_for_cancel = cloud_build.CloudBuildCreateBuildOperator(
        task_id="create_build_us_central1_for_cancel",
        project_id=PROJECT_ID,
        build=build,
        wait=False,
        location="us-central1",
    )
    cancel_build_us_central1 = cloud_build.CloudBuildCancelBuildOperator(
        task_id="cancel_build_us_central1",
        project_id=PROJECT_ID,
        id_='{{ ti.xcom_pull(task_ids="create_build_us_central1_for_cancel", key="id") }}',
        location="us-central1",
    )
    create_build_trigger_us_central1 = cloud_build.CloudBuildCreateBuildTriggerOperator(
        task_id="create_build_trigger_us_central1",
        project_id=PROJECT_ID,
        trigger=trigger,
        location="us-central1",
    )
    get_build_trigger_us_central1 = cloud_build.CloudBuildGetBuildTriggerOperator(
        task_id="get_build_trigger_us_central1",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_us_central1", key="id") }}',
        location="us-central1",
    )
    update_build_trigger_us_central1 = cloud_build.CloudBuildUpdateBuildTriggerOperator(
        task_id="update_build_trigger_us_central1",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_us_central1", key="id") }}',
        trigger=trigger,
        location="us-central1",
    )
    run_build_trigger_us_central1 = cloud_build.CloudBuildRunBuildTriggerOperator(
        task_id="run_build_trigger_us_central1",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_us_central1", key="id") }}',
        source={
            "branch_name": "main"
        },
        location="us-central1",
    )
    delete_build_trigger_us_central1 = cloud_build.CloudBuildDeleteBuildTriggerOperator(
        task_id="delete_build_trigger_us_central1",
        project_id=PROJECT_ID,
        trigger_id='{{ ti.xcom_pull(task_ids="create_build_trigger_us_central1", key="id") }}',
        location="us-central1",
    )


[
        # global
        create_build_global >> retry_build_global >> get_build_global,
        create_build_global_deferrable,
        list_build_global >> list_build_triggers_global,
        create_build_global_for_cancel >> cancel_build_global,
        create_build_trigger_global >> get_build_trigger_global >> update_build_trigger_global
        >> run_build_trigger_global >> delete_build_trigger_global,

        # us-central1
        create_build_us_central1 >> retry_build_us_central1 >> get_build_us_central1,
        create_build_us_central1_deferrable,
        list_build_us_central1 >> list_build_triggers_us_central1,
        create_build_us_central1_for_cancel >> cancel_build_us_central1,
        create_build_trigger_us_central1 >> get_build_trigger_us_central1 >> update_build_trigger_us_central1
        >> run_build_trigger_us_central1 >> delete_build_trigger_us_central1,
    ]
```

**Comment by potiuk** [comment]
And @tnk-ysk of course :)

**Pull request merged**
