### PR TITLE
[AIRFLOW-6269] Add show config command in CLI

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6269
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
Love it! I think what could be helpful as well if we see from which file (or files) the configuration have been loaded.

**Comment by mik-laj** [comment]
This would have to be a separate command because this command returns a valid `airflow.cfg` file. You can write `airflow config > second config.cfg` to save current configuration. It was not the scope of this PR to add additional commands that allow debugging path configurations. These paths should also not be displayed in the same command, because they will cause it to not be a valid INI file and can cause confusion among users because this file has long output, so finding path information in long output can be problematic.  Can you add an independent PR that will add your new command? I agree that your command would be very helpful.

**Comment by potiuk** [comment]
Sure. That's a valid point. I think we do not need separate command for that -> simply displaying at info level where airflow loads configuration from should be enough.

**Review by potiuk — APPROVED** [review]

**Comment by mik-laj** [comment]
It's already happening
Screenshot 2019-12-18 at 18 42 36

**Comment by potiuk** [comment]
Not everywhere, there might more than one place you read configuration from:

    def load_test_config(self):
        """
        Load the unit test configuration.

        Note: this is not reversible.
        """
        # override any custom settings with defaults
        self.read_string(parameterized_config(DEFAULT_CONFIG))
        # then read test config
        self.read_string(parameterized_config(TEST_CONFIG))
        # then read any "custom" test settings
        self.read(TEST_CONFIG_FILE)

**Comment by potiuk** [comment]
And then:

```
if conf.getboolean('core', 'unit_test_mode'):
    conf.load_test_config()
```

**Pull request merged**
