### PR TITLE
[AIRFLOW-5443] Use alpine image in Kubernetes's sidecar

### PR DESCRIPTION
**Pull request by mik-laj**
The change will reduce the consumption of resources - disk, memory, processor, network. :-D 

A small comparison:
The docker image - 27.3 MB vs. 2.65 MB - 90%
The memory consumption - 4.609MiB vs.  492KiB - 90%

---

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5443
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by dimberman — APPROVED** [review]
LGTM. Will merge when tests pass.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
One watchout here @dimberman @mik-laj : I read recently an article advising against using alpine engine in production https://pythonspeed.com/articles/official-docker-best-practices/ . While it is much smaller, it uses non-standard glibc implementation. It is quite vague advice so might not be worth it, but maybe we should at least give the user an option to choose one of the standard debian images as a base.

**Comment by mik-laj** [comment]
Kubernetes is very difficult to configure right now. I think we should wait for someone to report the problem and then solve it. Otherwise we will only introduce additional confusion. It is very unlikely that a problem would arise in such a simple script.

**Comment by dimberman** [comment]
@potiuk I'm with @mik-laj here. If this starts becoming a problem we can address it, but I'd rather not add more branching logic to our k8s code.

**Comment by potiuk** [comment]
Sure. No problem for me in this case. It's a sidecar image only running one python command so no worries at all in fact.

**Pull request merged**
