### PR TITLE
Add k8s recommended labels

### LINKED ISSUE #34048: Use Kubernetes-recommended labels for airflow helm chart
### Description

Kubernetes offers a [list of recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) for grouping resource objects. The prefix <code>app.kubernetes.io</code> differentiates these recommended labels from custom labels.

Why is it needed?
Enhancing readability and maintainability

References
https://helm.sh/docs/chart_best_practices/labels/#standard-labels
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

### Use case/motivation

https://github.com/apache/airflow/blob/913eff6759bf89d635ef1df1a0db23c157e48c4b/chart/templates/webserver/webserver-deployment.yaml#L36-L40

The above labels would be changed as follows:

```yaml
app.kubernetes.io/part-of: airflow
app.kubernetes.io/component: webserver
app.kubernetes.io/instance: {{ .Release.Name }}
helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
```

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Owen-CH-Leung**
fixes #34048 

As per the discussion, this PR modifes all existing yaml files inside airflow helm chart to include the recommended k8s labels. See [this](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) for more details 

A lot of files are being affected but in short
- a new definition `kubernetes_recommended_labels` is added into `_helpers.yaml`
- Apply this new definition to each yaml file, and if applicable, add a new label `app.kubernetes.io/component` (with the value being the same as `component` if the resource was originally labeled with `component`
- Modify a few helm tests as a result of this change

### CODE REVIEW

**Comment by kimminw00** [comment]
I think it is necessary to differentiate <code>app.kubernetes.io/name</code> of each object.

**Comment by Owen-CH-Leung** [comment]
> I think it is necessary to differentiate `app.kubernetes.io/name` of each object.

How about we name each resource like `airflow-{name of the component}-{type of the resource}` ? 

e.g. `airflow-webserver-deployment`, `airflow-webserver-ingress`

**Comment by kimminw00** [comment]
I think it would be helpful to refer to the prometheus helm chart.

https://github.com/prometheus-community/helm-charts/blob/f57ff6651817b23c21daa7d5cd087649add5836e/charts/prometheus-druid-exporter/templates/_helpers.tpl#L9-L25

https://github.com/search?q=repo%3Aprometheus-community%2Fhelm-charts%20app.kubernetes.io%2Fname&type=code

**Comment by Owen-CH-Leung** [comment]
@kimminw00 Thanks. I've examined the 6 k8s recommended labels in the prometheus chart and I find that there's a difference for the labels `app.kubernetes.io/name` and `app.kubernetes.io/part-of`. 

In prometheus chart, these 2 labels are set as default `Chart.Name`, and can be overriden by `nameOverride` in the `values.yaml` file. In airflow chart, this field also exists so I think we can implement the same logic as well.

For the other 4 labels (`app.kubernetes.io/version`, `helm.sh/chart`,  `app.kubernetes.io/managed-by` and `app.kubernetes.io/instance`), I think my current logic is the same as the prometheus chart. Feel free to let me know if I'm wrong or I miss anything.

**Comment by kimminw00** [comment]
And please take a close look at how each object(secret, pv, ingress etc.) is labeled in prometheus helm chart.

**Comment by kimminw00** [comment]
Prometheus and alertmanager are different apps. So they have different <code>app.kubernetes.io/name</code>

https://github.com/prometheus-community/helm-charts/blob/f57ff6651817b23c21daa7d5cd087649add5836e/charts/kube-prometheus-stack/templates/alertmanager/serviceaccount.yaml#L9

https://github.com/prometheus-community/helm-charts/blob/f57ff6651817b23c21daa7d5cd087649add5836e/charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml#L9C1-L9C85

Ariflow, pgbouncer, redis, and statsd(may be there is more apps!) need to have different <code>app.kubernetes.io/name</code> in the same way.
(But I'm not sure that webserver, scheduler, dag processor, triggerer, etc., are different apps as they run in the same container image)

And you have to tests if app name is not longer than 63 chars.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

**Comment by Owen-CH-Leung** [comment]
Thanks @kimminw00. Yes it makes sense to me. Different apps should have different names for differentiation. I've customized the yaml files to have different `app.kubernetes.io/name` instead of a single definition for all (i.e. differernt resource will have `app.kubernetes.io/name` like `airflow-flower`, `airflow-redis`, `airflow-statsd` and so on).

I also put webserver, scheduler, dag processor, triggerer, worker to have similar app name (i.e. `airflow-webserver`, `airflow-scheduler` etc) even though they use the same image since they are seperate sub-applications. But for jobs like `create-user-job`, `run-airflow-migration` etc, I didn't put this label for now. 

Let me know your thought on this.

**Comment by kimminw00** [comment]
If <code>airflow.fullname</code> is longer than 63 chars, then <code>app.kubernetes.io/name</code> is longer than 63 chars. 
(For example, <code>{{ include "airflow.fullname" . }}-dag-processor</code> should not longer than 63 chars.)
You have to check https://github.com/prometheus-community/helm-charts/blob/1a8f84ae3621937cf43cfb0e97956c4690d9d96b/charts/kube-prometheus-stack/templates/_helpers.tpl#L7-L25.

I think it is better to open another PR which fixes <code>{{ include "airflow.fullname" . }}</code> first. And

**Comment by Owen-CH-Leung** [comment]
I've applied the fix here to truncate `airflow.fullname` to return at most 40 chars.

**Comment by Owen-CH-Leung** [comment]
@jedcunningham @hussein-awala Can I seek your feedback for this PR also ? Thanks

**Comment by kimminw00** [comment]
I think you should also have to consider <code>Label selectors</code>.

**Comment by Owen-CH-Leung** [comment]
> I think you should also have to consider `Label selectors`.

You mean add the newly created labels inside `label selector` ? I think `label selector` should continue to work as long as I didn't remove the existing labels. We don't need to select all labels that are newly created.

**Comment by kimminw00** [comment]
> I think you should also have to consider <code>Label selectors</code>.  

This means replacing the previous labels with the K8S recommended labels in <code>label selector</code>s.
There may be problems due to replacement, so I think it would be good idea to leave it as is.
I'd like to hear what others think!

Please add recommemded labels to the <code>chart/files/pod-template-file.kubernetes-helm-yaml</code> file as well!

**Comment by Owen-CH-Leung** [comment]
> > I think you should also have to consider `Label selectors`.
> 
> This means replacing the previous labels with the K8S recommended labels in `label selector`s. There may be problems due to replacement, so I think it would be good idea to leave it as is. (I think we can replace labels when the chart major version is bumped) I'd like to hear what others think!
> 
> Please add recommemded labels to the `chart/files/pod-template-file.kubernetes-helm-yaml` file as well!
> 
> Thank you for going above and beyond!

No problem =). Added recommended labels to `chart/files/pod-template-file.kubernetes-helm-yaml`

**Pull request closed without merging**
