### PR TITLE
Enable specifying dictionary paths in `template_fields_renderers`

### LINKED ISSUE #17032: Improved SQL rendering within BigQueryInsertJobOperator
**Description**

`BigQueryInsertJobOperator` requires the submission of a `configuration` parameter in the form of a dict.  Unfortunately, if this contains a large SQL query - especially one that is formatted with new lines - then this cannot currently be rendered very nicely in the UI.

Screenshot 2021-07-15 at 15 39 33

**Use case / motivation**

The issue with this is that it's impossible to copy and paste the rendered query out of the Airflow UI, into a BigQuery browser and run it without lots of manual edits which is time wasted when troubleshooting problems.

**Are you willing to submit a PR?**

Yes.  My current thought process around this would be to add an optional SQL parameter to the operator which, if provided, would be added into the configuration and could therefore have its own template field and SQL renderer.

e.g.

Screenshot 2021-07-14 at 14 18 09

### PR DESCRIPTION
**Pull request by nathadfield**
Closes: #17032 
Related to: #17239 
*Recreated from #17252 

`BigQueryInsertJobOperator` requires the specification of a configuration dict but, at present, this results in poor SQL rendering; especially if the queries are big or complex.

### Current Example

127119136-3d6f1f57-c941-4b06-b3f3-c6094b31f821

This PR attempts to implement the capability for specific elements of a dictionary provided to an operator to be rendered individually with the appropriate renderer.

For example, when the following configuration is submitted to `BigQueryInsertJobOperator` then, in addition to the JSON rendering of `configuration` the provided SQL should be separately rendered.

```
sql = '''
INSERT INTO `target_project.target_dataset.target_table`
(col1, col2, col3, col4)
SELECT col1, col2, col3, col4
FROM `source_project.source_dataset.source_table`
'''

test = BigQueryInsertJobOperator(
    task_id='test',
    gcp_conn_id='my_gcp_connection',
    configuration={"query": {"query": sql,
                             "destinationTable": {"projectId": 'my_project',
                                                  "datasetId": 'my_dataset',
                                                  "tableId": 'my_table'},
                             "writeDisposition": 'WRITE_TRUNCATE',
                             "useLegacySql": False}
                   }
)
```

To achieve it, this PR enables any operator to receive a dot-separated path from `template_field_renderers` along with the renderer type.  In this case we want `BigQueryInsertJobOperator` to extract the value from `configuration` dict where the key path is `query.query`.  This is fully represented as follows:

 `template_fields_renderers = {"configuration": "json", "configuration.query.query": "sql"}`

When building the rendered page, we check if the content is a dict - e.g. `configuration` - then, if so, return a generator object that yields every possible path of keys (`get_key_paths`) in the form `key1.key2.key3...keyX`. 

Using this we can then check to see if any of these paths match with what we have in `template_field_renderers` and, if so, what the renderer is.  If it is a valid renderer then we can use that path to retrieve the value from the configuration (`get_value_from_path`).

```
if isinstance(content, dict):
    for dict_keys in get_key_paths(content):
        template_path = '.'.join((template_field, dict_keys))
        renderer = task.template_fields_renderers.get(template_path, template_path)
        if renderer in renderers:
            content_value = get_value_from_path(dict_keys, content)
            html_dict[template_path] = renderers[renderer](content_value)
```

The result of this is a rendered page which looks like the following:

Screenshot 2021-07-26 at 14 51 48

In addition, when decorated tasks or Python operators are used, `op_kwargs` is parsed and each individual element is extracted and rendered.  Such that:

127146694-eb6334b6-be41-4099-9f14-4b1a5093db7b

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by nathadfield** [comment]
The failing Sqlite Py3.6 test seems to be unrelated to the changes.

**Comment by mehmax** [comment]
Hi @nathadfield, checking and rendering op_kwargs individually would totally solve the Issue I faced.
Looks good to me now!

**Review by potiuk — APPROVED** [review]
❤️  IT

**Comment by potiuk** [comment]
Can you please rebase @nathadfield ? We have fixed some failures in main , and it would be great to re-run that one through all tests?

**Comment by nathadfield** [comment]
@potiuk Rebased and all tests have ran successfully!

**Comment by potiuk** [comment]
Yeah. Seems that thanks to some fixes by @ephraimbuddy we are gone a bit closer to the "green one" on the PRS.

**Comment by potiuk** [comment]
One more small request - Could you please alse explain this new feature in https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html?highlight=custom#templating - there template_rendering is mentioned, but it would be nice to add an explanation and example there as well.

**Comment by nathadfield** [comment]
@potiuk Ah, yeah!  I sure can!

**Comment by potiuk** [comment]
at the same time - the list of lexers got longer, so would be nice to refresh it :)

**Comment by nathadfield** [comment]
@potiuk Done!  Happy with the explanation?

**Review by potiuk — APPROVED** [review]
Perfect!

**Comment by potiuk** [comment]
Some errors with doc building though :). 

`./breeze build-docs -- --package filter apache-airlfow`  

Should allow you to build it quickly locally

**Comment by nathadfield** [comment]
Ah!  My bad.  Should be ready once everything runs through again.

**Comment by nathadfield** [comment]
@potiuk Well, that's annoying.  Unrelated test failures again.

**Comment by potiuk** [comment]
No worries. we can merge it anyway :)

**Comment by nathadfield** [comment]
Awesome!  Thanks very much and for your help!

**Comment by potiuk** [comment]
Good job on that :)

**Comment by nathadfield** [comment]
@potiuk Might we expect the core Airflow aspect of this to appear in 2.2?  I guess there would also need to be a Google provider version release afterwards too.

**Comment by potiuk** [comment]
> @potiuk Might we expect the core Airflow aspect of this to appear in 2.2? I guess there would also need to be a Google provider version release afterwards too.

Yeah. We have not yet cut 2.2 branch, so everything merged in main is "in".

BTW. That made me realise  that we should make sure that that if we specify the new "nested" renderers in the in a provider, theold airflow will still work with them (and not break the UI or anything). Maybe what you should do really - is to add those new field renderers now - so that we can release ithem  without airflow yet supporting them (and we make sure that they work without problems in current airflow) ? 

Could you please add such a change to e provider and check it maybe ? (just reverting your change in main should show how old airlfow will behave in this case.

**Comment by nathadfield** [comment]
@potiuk Good point!  Let me take a look at that.

**Comment by nathadfield** [comment]
@potiuk There doesn't appear to be any UI issues if you specify a key path in a provider but the version of core Airflow doesn't have this capability yet.

The existing code in [views.py](https://github.com/apache/airflow/blob/2.1.2/airflow/www/views.py#L970) looks up values from `template_field_renderers` against the operator class but these key paths will never match with anything.

**Comment by potiuk** [comment]
Great ! thanks @nathadfield - would you make some pr to add some example operators with useful paths so that we can release it in the new batch of providers (I plan to cut them shortly - maybe early next week), and then they will be ready when we release 2.2 :)

**Comment by nathadfield** [comment]
@potiuk I'm more than happy to I'm not sure what you had in mind exactly or where to put it.  At the moment, the only operator that has a path which can be rendered is BigQueryInsertJobOperator.

**Comment by potiuk** [comment]
> @potiuk I'm more than happy to I'm not sure what you had in mind exactly or where to put it. At the moment, the only operator that has a path which can be rendered is BigQueryInsertJobOperator.

That's enough :)

**Pull request merged**
