### PR TITLE
[AIRFLOW-488] AirflowException("Failed to create remote temp file")

### PR DESCRIPTION
**Pull request by forevernull**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- _https://issues.apache.org/jira/browse/AIRFLOW-488_

Testing Done:
- It can pass all the test, travis included.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks. Please squash your commits and provide a proper commit message per the guidelines (jira reference, title, what/why description)

**Comment by msumit** [comment]
@forevernull please follow the 50/72 rules for commit messages. https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

**Comment by forevernull** [comment]
@msumit  I have mended. Can It merge or How can I do something?

**Comment by msumit** [comment]
lgtm

**Comment by StonesGitHub** [comment]
I still get this error after make revison on 'mktemp', and I am using Linux platform.
Has it been tested on Linux before?

**Pull request closed without merging**
