### PR TITLE
Updating postgresql distribution

### PR DESCRIPTION
**Pull request by rchojn**
Bitnami is much more stable than existing one. Better documentation and integration in cluster with limited security rights

### CODE REVIEW

**Review by XD-DENG — CHANGES_REQUESTED** [review]
Seems you raised two different PRs with the same changes (https://github.com/apache/airflow/pull/10600).

I think more detailed clarification would be required to justify your changes. Meanwhile, please ensure your changes reflect the subject/scope.

**Comment by gardnerdev** [comment]
@XD-DENG not sure, how to get rid off this PR

**Comment by XD-DENG** [comment]
-1 from me for now, as discussed in PR #10600. Would like to have comments from other committers as well.

**Comment by potiuk** [comment]
I am closing this one in favour of #10600.

**Pull request closed without merging**
