### PR TITLE
[AIRFLOW-2391] Fix to Flask 0.12.2

### PR DESCRIPTION
**Pull request by Fokko**
Flask 0.12.3 has issues with Airflow and needs to be fixed. Therefore lock the version to 0.12.2 so the master is green again: http://flask.pocoo.org/docs/0.12/changelog/

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jornh** [comment]
Apparently due to a packaging mishap with Flask `0.12.3`. According to  https://github.com/pallets/flask/issues/2728#issuecomment-384982064 a fixed `0.12.4` should come out soon.

Sadly, until that happens it also leaves https://dist.apache.org/repos/dist/dev/incubator/airflow/1.10.0beta1/ in a state where you need to manually pin Flask to 0.12.2 as in https://github.com/apache/incubator-airflow/pull/3277/commits/e1bfb684027a627fe7ffc6279adaafc45a6e3e39.

I'll point to this warning from the dev mailing list as well - to maybe save the trouble for someone else.

@Fokko thank you for applying the fix so fast to both `master` and `v1-10-test`. It saved me a few cycles!

**Comment by Fokko** [comment]
Thanks @jornh for the background information. Really appreciate it. Are there any specific from Flask 1.12.{3,4} features that you want to be in there?

For now pinning it onto the specific version is the best solution. We had some issues with upgrades of dependencies that broke the Airflow install earlier.

**Comment by davidism** [comment]
I released 0.12.4 to fix this.

**Comment by Fokko** [comment]
I've reverted the pinned version: https://github.com/apache/incubator-airflow/commit/e561ea64ccbcf54a5200fff322829fcfdccd1bf7 https://github.com/apache/incubator-airflow/commit/0ff434a9b7510fb9cb1e74a60c5ac02b61f087d5

I've did some tests and it looks fine again, thanks @davidism for the quick fix!

**Pull request closed without merging**
