### PR TITLE
[AIRFLOW-1952] Add the navigation bar color parameter

### PR DESCRIPTION
**Pull request by Licht-T**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1952

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Added the navigation bar color parameter.
We operate multiple Airflow's (eg. Production, Staging, etc.), so we cannot distinguish which Airflow is. This feature enables us to discern the Airflow by the color of navigation bar.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This is only UI change.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by gwax — COMMENTED** [review]
Could we provide an option for custom stylesheets instead of creating a new config parameter for a single style change?

**Comment by Licht-T** [comment]
@gwax I think there is no needs for changing the style of other UI elements. And, I am afraid of becoming complicated when UI debuging (the priority of CSS, etc.).
Is there any needs for changing the style of another UI element?

**Comment by gwax** [comment]
I'm wary of the idea that the navbar color is the _only_ element anyone is ever going to want to customize.

For me it's a matter of people can modify the style or they can't; to call out specific elements for modification feels a little overly-specific.

**Comment by pdambrauskas** [comment]
I agree with @gwax. It makes sense to have an option to change whole stylesheet. For example, there is a feature request to make Airflow GUI usable for colorblind people. If we had interchangeable stylesheets that would be possible

**Comment by bolkedebruin** [comment]
Agree with @gwax please closr this or update the PR.

**Comment by r39132** [comment]
This looks like a case where a useful light-weight feature addition is killed by a request for a more complicated feature. Personally, I like the concept of altering an accent color to make it more obvious which environment someone is on. I have definitely been bitten by doing something on the wrong env -- and I'm pretty sure the submitter was also bitten by such an example. So, until interchangeable style sheets become a reality, perhaps we can be more open to this change. 

@Licht-T Please consider rebasing this.

**Comment by Licht-T** [comment]
This totally slipped my mind!
Thanks @r39132, this is what I wanted to say. This is now rebased!

Since easy configurable, this change makes sense for someone who ONLY WANT to distinguishes which envs.
Also note that interchangeable style sheets will make bugs and un-debugginess. Airflow has and had much UI problems. IMO, this should not be any more complicated.

And, there are some softwares which transform colors of display for colorblind people. Is this really the matter of covered by Airflow?
https://www.ryobi-sol.co.jp/visolve/en/

**Comment by r39132** [comment]
Any additional comments/concerns @gwax @bolkedebruin @Fokko ?

**Comment by bolkedebruin** [comment]
I dont like it but i mentioned that. If you ate adament about it is it applies to both web servers?

**Comment by Fokko** [comment]
I agree with @r39132. Having a different color for each environment can be very beneficial.

**Comment by bolkedebruin** [comment]
@r39132 this has created technical debt unfortunately :-( , the change did not apply to the rBAC webserver.

**Pull request closed without merging**
