### PR TITLE
Make app creation session- or class-wide when possible to make tests faster

### PR DESCRIPTION
**Pull request by uranusjr**
More free-ish speedup.

Can this `app` fixture be merged with the one in #14875? They have very slightly different configs (this one does not have `init_appbuilder_views`). That would be able to further save some more time.

### CODE REVIEW

**Comment by ashb** [comment]
We possibly could merge them, yes. The reason to not call linit_appbuilder_views is that it is slow, but if we can reduce the total number of times we initialize the app it will be faster overall _if_ we run these tests in the same "batch".

We don't run `pytests tests/` but we run some in batches -tests/www, tests/api, etc.

But with a change like this maybe it doesn't make as much sense to split these apart anymore.

**Comment by uranusjr** [comment]
Cool. In that case it’s probably easier for me to rebase against #14875 and include the merge here. I’ll also look around for more similar `create_app()` calls in the mean time.

**Comment by uranusjr** [comment]
I’ve rebased this against #14875, so this now includes changes from that PR. If that gets merged first I’ll rebase/merge again.

I’ve located several more app creation code and change them to be session or class scoped. I think there are some more possibile optimisations, especially several of the apps are simply bare `create_app(testing=True)` without decorators. I think they can be merged into a session-scoped fixture in the top-level `tests/conftest.py`. What would be a good name for the fixture? `app` sounds wrong to me, maybe

```python
@pytest.fixture(scope="session")
def testing_app():
    return application.create_app(testing=True)
```

?

**Comment by uranusjr** [comment]
I’m going with `app` for now.

**Comment by ashb** [comment]
Closing and re-opening to trigger full CI rebuild.

**Comment by ashb** [comment]
@uranusjr Changes look okay -- do you have before and after numbers?

**Comment by ashb** [comment]
Don't know if we want to do it in this PR, but tests.cli.commands.test_role_command and test_user_command are slow and wuold likely benefit massively from fixtures too.

**Comment by ashb** [comment]
Ran some tests, this PR as it stands made tests/cli/commands go from 4m30 down to 2m12.

Nice!

**Review by ashb — APPROVED** [review]

**Comment by uranusjr** [comment]
I actually compared numbers for each change in the PR and made sure all of them go down, but threw them away once I finished 😞 

> tests.cli.commands.test_role_command and test_user_command are slow and wuold likely benefit massively from fixtures too

Those look like straightforward gains! I’ll do them in a separate PR (based on this one).

**Comment by ashb** [comment]
> Edit: Actually I think those are already included in this one?

Whoops, so they are!

**Pull request merged**
