### PR TITLE
Port isort config from pre-commit to setup.cfg

### PR DESCRIPTION
**Pull request by kaxil**
Based on https://github.com/apache/airflow/pull/10543#issuecomment-680231216

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
cc @sztamas

**Review by potiuk — APPROVED** [review]
That's fine as well. Though I'd keep the one in pre-commit as it then will not even trigger if you change any of those files.

**Comment by kaxil** [comment]
> That's fine as well. Though I'd keep the one in pre-commit as it then will not even trigger if you change any of those files.

I agree on that one, it was mostly for this comment (https://github.com/apache/airflow/pull/10543#issuecomment-680231216) , it broke isort's tests

**Comment by sztamas** [comment]
Thanks for fixing this so quickly!

Tamas

**Pull request merged**
