### PR TITLE
Recognize quotes when parsing urls in logs

### PR DESCRIPTION
**Pull request by smlee729**
---

Currently, the log UI doesn't recognize single or double quotes when a url is parsed as a hyperlink, so when you click on it, you're taken to the wrong url, which is quite an inconvenient experience. I've created a PR to fix this.

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Nice!

**Comment by potiuk** [comment]
The regexp is a bit magic, but it does the job :)

**Comment by potiuk** [comment]
Need static checks fix though (recommend installing pre-commit)

**Comment by smlee729** [comment]
Thanks @potiuk . I found the failing test was successful : 

```
> pre-commit run --hook-stage manual trailing-whitespace --all-files --verbose
Remove trailing whitespace at end of line................................Passed
- hook id: trailing-whitespace
- duration: 0.37s
```

And pushed a commit. Could you guide me how to re-trigger static-check?

**Comment by potiuk** [comment]
As this is your first contribution, maintainer has to approve and run your workflow (I just did)

**Review by hussein-awala — APPROVED** [review]

**Comment by potiuk** [comment]
Still some checks are failing. Installing pre-commit and running `git commit - -amend` should fix all the static checks

**Comment by smlee729** [comment]
I tried to run `pre-commit run --all-files` command, but stuck with this phase : 
```
Run mypy for providers.............................................................Failed
- hook id: mypy-providers
- exit code: 2

Using 'uv' to install Airflow


Using airflow version from current sources


Leaving default pydantic v2


Using 'uv' to install Airflow

airflow/providers/fab/auth_manager/cli_commands/user_command.py:215: error:
f-string expression part cannot include a backslash  [syntax]
            print(f"Created the following users:\n\t{'\\n\\t'.join(users_c...
                   ^
Found 1 error in 1 file (errors prevented further checking)
Error 2 returned
If you see strange stacktraces above, and can't reproduce it, please run this command and try again:

breeze ci-image build --python 3.8

You can also run `breeze down --cleanup-mypy-cache` to clean up the cache used.
```

But since the change is not related to my change, I'm not sure how I can fix this issue..
Could you help me how to fix this?
Other than that, I removed unused variable on my test since it complaints with ESLint.

**Comment by smlee729** [comment]
Finally passed :) Yay~

**Comment by potiuk** [comment]
:tada:

**Pull request merged**
