### PR TITLE
Fixing tests that leave traces (users)

### PR DESCRIPTION
**Pull request by khalidmammadov**
There are loads of test that leave traces e.g. don't delete users for example once their tests are complete.
This PR adds a new function and makes use of them in the test suite. 

If PR accepted, I will file some more similar PR's to fix remaining test cases. This is deliberately scoped to keep changes to minimum. 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by khalidmammadov** [comment]
@potiuk can you please take a look?

**Comment by potiuk** [comment]
Very good idea - it needs somet static check fixes after rebase, but I think it is a step in the right direction to get rid of the side-effects between tests. 

Can you please rebase and fix the tests @khalidmammadov ?

**Comment by khalidmammadov** [comment]
Thanks @potiuk, will do rebase and fixes.
Also, I had a bit of thought, now thinking to change it a bit, so create_user_scope inside a Class. Then it will allow us to instantiate it and call this func so it's yield also scoped. This will allow parallel runs of this suite. What do you think?

**Comment by khalidmammadov** [comment]
Closing as it brought other changes after rebase...

**Pull request closed without merging**
