### PR TITLE
Pin pandas-gbq to <0.15.0

### LINKED ISSUE #15113: ImportError: cannot import name '_check_google_client_version' from 'pandas_gbq.gbq'
**What happened**:

`pandas-gbq` released version [0.15.0](https://github.com/pydata/pandas-gbq/releases/tag/0.15.0) which broke `apache-airflow-backport-providers-google==2020.11.23`

```
../lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:49: in <module>
    from pandas_gbq.gbq import (
E   ImportError: cannot import name '_check_google_client_version' from 'pandas_gbq.gbq' (/usr/local/lib/python3.7/site-packages/pandas_gbq/gbq.py)
```

The fix is to pin `pandas-gpq==0.14.1`.

### PR DESCRIPTION
**Pull request by darwinyip**
closes: #15113 

Pretty straightforward. Pins `pandas-gbq<0.15.0`.

### CODE REVIEW

**Comment by uranusjr** [comment]
Since the upstream actually removed this outright and no longer performs this check, IMO a better fix would be to remove this test from Airflow as well (maybe only when the function fails to import).

**Comment by uranusjr** [comment]
Reading the source, `_check_google_client_version` was actually a part of `_test_google_api_imports`, so Airflow really doesn’t need to call it separately. I think the call can simply be removed.

**Comment by kaxil** [comment]
Agree with @uranusjr  here, looks like it was just there to do some additional validation :) 

cc @mik-laj @turbaszek who might know more, but feel free to remove this.

**Review by kaxil — APPROVED** [review]
Looks like pandas-gbq>=0.15 also dropped support for Python 3.6 which Airflow still supports so I am going to approve this

https://github.com/pydata/pandas-gbq/releases/tag/0.15.0 (https://github.com/pydata/pandas-gbq/issues/337)

**Comment by potiuk** [comment]
One comment for the future @darwinyip @kaxil :).

Not a big issue, but worth keeping in mind to always describe in the commit and comment in `setup.py` why we are adding such limits.

Why?  

It makes it much easier to understand when to lift the limits and when to leave them in case of further changes. I am going to provide proper fix for few other packages dropping Python 3.6 binary pypi wheels in their recent release (PR is coming) but having a comment in setup.py for the pandas-gbq could be helpful for me to understand what was going on rather than guess it (It was by accident I found my changes coincided with this one).

It could have saved me a few builds to find out that I should not remove this one. I thought it was added because of transitive pandas -> numpy dependencies (which dropped support for 3.6 pypi binary releases and it's easiest in our case to limit them for <3.7 rather than build them in our image (this ain't easy). It would be a bit easier if we had it in `setup.py` as comment. or the commit message (and best if it is in both). It was a bit of luck that I looked at the PR comments to find out why this was added.

I will add comment in my upcoming PR explaining why we have that `<0.15.0` thingie.

**Pull request merged**
