### PR TITLE
[AIRFLOW-2040] Fix  task instance logs link by escaping special chars in execution_date

### PR DESCRIPTION
**Pull request by cinhil**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2040

### Description
- This PR fix the missing log file in Web UI for Task Instances when using timezone.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Would it be possible to test this?

**Comment by cinhil** [comment]
Good question. I am new to airflow, even more to your testing framework.
the "+" symbol is lost by flask request when the URL is not encoded.
We could add a TestLogView in test_views.py with a non day truncated datetime, but we are already behind the issue, so it will not bring more testing coverage.
After some research, the truth is that we should not have used the + symbol in the URL because '+' is expected to replace spaces (https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1). 
If you have any idea where I could add a test, I will be happy to help.

**Comment by cinhil** [comment]
@Fokko Hello, I did add a unit test. Tell me if it is ok.

**Comment by Fokko** [comment]
@cinhil It looks ok. My last question is, why didn't this cause issues earlier on?

**Comment by cinhil** [comment]
@Fokko I have two guess:
- before timezone integration, the date format was probably different without '+' char
- even with the '+' if you work on daily basis without timezone, the date is truncated but still equal to itself

**Comment by cinhil** [comment]
@Fokko The complete answer:
```
>>> import datetime
>>> datetime.datetime.now().isoformat()
'2018-02-02T10:22:51.531638'
>>> import pendulum
>>> pendulum.now('Europe/Brussels').isoformat()
'2018-02-02T10:23:35.185398+01:00'
```

**Comment by Fokko** [comment]
Ah, that makes sense. This is due the recent timezone improvements that @bolkedebruin made

**Comment by bolkedebruin** [comment]
Is this the only place where we face this issue?

**Comment by cinhil** [comment]
Hello @bolkedebruin ,
I did not find already another one but I am new on airflow and try to make it works for timezone dependent batches. I am facing another timezone issue described by https://issues.apache.org/jira/browse/AIRFLOW-2060 but I do not thing it is related directly to this one.

**Comment by cinhil** [comment]
I should do the same for mark_success_url in models.py. Probably affected the same way that log_url. In which screen it is used ?
Edit: I found it, it is in the email alert. I will push the fix later today.
Edit: Done

**Comment by cinhil** [comment]
@Fokko @bolkedebruin Hello,
Is something missing for merging ?
Kind regards,

**Comment by Fokko** [comment]
No, could you rebase against master for the last time? Cheers

**Comment by cinhil** [comment]
@Fokko rebase done, test passed. lgtm.

**Comment by Fokko** [comment]
Thanks @cinhil  We had some recent updates with the pendulum library.

Cheers

**Pull request closed without merging**
