### PR TITLE
[AIRFLOW-2479] Improve doc FAQ section

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2479
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
update the faq:
1.  how to improve airflow dag performance.
2. how to reduce airflow UI page load time.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
can you please limit the amount of closing and opening that you do? We have been contacted by Apache Infra explaining to us that we are taking up to 25% of total build time of Travis builds of all Apache projects. Please retry builds on your own account and point to successful builds there if necessary.

**Comment by feng-tao** [comment]
@bolkedebruin  I'll be more mindful, sorry about that. But it will be great if any of the committers could look into why the travis fails recently for all the prs.

**Comment by Fokko** [comment]
@feng-tao We're looking into this, but the committers time is also finite ;)

**Comment by kaxil** [comment]
The CI has been fixed.

@feng-tao Don't worry regarding CI for this specific PR as it is just a doc update. So you don't need to restart the CI.

**Review by Fokko — APPROVED** [review]
Thanks @feng-tao for pointing this out.

**Pull request closed without merging**
