### PR TITLE
Removed unicodecsv dependency for providers with Airflow version 2.8.…

### PR DESCRIPTION
**Pull request by potiuk**
…0 and above (#42765)

(cherry picked from commit 00b8452b7526166b2918976b991aff1124d1a17c)

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Cherry-picking https://github.com/apache/airflow/pull/42765 - unicodecsv is a **really** old dependency that has been removed from few of our providers some time ago and we really should not have it in airflow - but we had to add it for back-compatibility. It's highest time to remove it also in 2.10 branch.

**Comment by potiuk** [comment]
Should be rebased after #42977 backport for looker/kiota has been merged.

**Comment by potiuk** [comment]
Also related discussion #42969

**Review by gopidesupavan — APPROVED** [review]

**Comment by potiuk** [comment]
Ready to be merged in v2-10-test

**Review by kaxil — APPROVED** [review]

**Pull request merged**
