### PR TITLE
[FEATURE] Added oauth support with snowflake sql api operator

### LINKED ISSUE #36621: SnowflakeSqlApiOperator does not support OAuth
### Description

There are 2 methods for Authenticating to Snowflake: `OAUTH` and `KEYPAIR_JWT`

Currently the only supported auth method is `KEYPAIR_JWT`. It would be great to have OAUTH as an option, as well.

https://github.com/apache/airflow/blob/c47dcc59e5a0766d6b390bc8ceafc8ab6b762c88/airflow/providers/snowflake/hooks/snowflake_sql_api.py#L197 

### Use case/motivation

Add more flexibility to Snowflake Authentication

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ighoshsubho**
## Functionality added -

- SnowflakeSqlApiOperator support for OAuth

closes: #36621

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
You need to add tests, it makes little sense to run CI if there are no tests added for it.

**Comment by potiuk** [comment]
Closed by mistake.

**Comment by ighoshsubho** [comment]
> You need to add tests, it makes little sense to run CI if there are no tests added for it.

sure will do it

**Review by dirrao — CHANGES_REQUESTED** [review]
Existing test cases are failing. Can you address them?

**Review by eladkal — CHANGES_REQUESTED** [review]
We also need to update the snowflake docs
I am not sure if this goes in the connection part or in the operator part
https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/connections/snowflake.html

https://airflow.apache.org/docs/apache-airflow-providers-snowflake/stable/operators/index.html

feel free to suggest the best place to set it

**Comment by ighoshsubho** [comment]
> Existing test cases are failing. Can you address them?

please check now

**Comment by eladkal** [comment]
@ighoshsubho it still missing tests and docs.
Can you add it?

**Comment by eladkal** [comment]
Closed in favor of https://github.com/apache/airflow/pull/37922

**Pull request closed without merging**
