### PR TITLE
[AIRFLOW-1364] Add HdfsSensorTime and unittest

### PR DESCRIPTION
**Pull request by wolfier**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1364) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-1364

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR updates adds a new sensor called HdfsSensorTime that will wait until the associated file has been modified in HDFS. This is to verify a non-partitioned table has been updated for the day before running jobs depending on the table.

### Tests
- [x] My PR adds the following unit tests:
    - HdfsSensorTimeTests
       - test_should_have_a_later_time
       - test_should_have_a_later_time_fail
       - test_should_have_bad_formatted_time

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Acehaidrey** [comment]
I also find this sensor to be useful. Specially for the case where you have non-partitioned tables, you can check the hdfs files instead

**Comment by matt-martin** [comment]
We have several use cases where data is overwritten daily in HDFS and this is a helpful way to detect when that happens.  Hopefully others find this useful as well.  We're happy to respond to any feedback folks may provide on this implementation.

**Comment by Acehaidrey** [comment]
@aoen do you mind reviewing this when you get a chance? or know who should ask?

**Comment by aoen** [comment]
For the most part, my current stance on the PRs for a lot of sensors and hooks) is that if one of the committers doesn't depend on the hook/sensor, then there isn't really much official support for them. Currently, a lot of them don't even have tests. I made a JIRA a while back to create a more formal plugin system for Airflow, but for now nothing is stoping users from creating their own github repos for their custom contrib stuff, and just adding their custom hooks/operators to PYTHONPATH so that DAGs can access them (Airbnb does this for some operators internally).

Another option is to become a committer to maintain the hooks you have a vested interest in!

**Comment by Acehaidrey** [comment]
@aoen thanks for that response :). Greatly appreciated, I/we may be interested in becoming a maintainer of hooks have an interest in like you said. Is there a place to get more information about that?

**Comment by aoen** [comment]
There are no hard and fast requirements but I don't think we've had a case of someone putting in the effort and doing a decent job being rejected. In general you want to: have one big commit, maybe 7-8 smaller ones (at least a couple of which touch the core, not hooks/operators), help review PRs, be involved in the mailing list discussions. No hard and fast rules, and the committers need to vote, but I think those are some good rough ones.

**Comment by Acehaidrey** [comment]
Awesome that's really good to know. Thanks @aoen  :)

**Pull request closed without merging**
