### PR TITLE
Remove side-effect of Hybrid executor blocking test

### PR DESCRIPTION
**Pull request by potiuk**
The tests introduced in #39531 introduced side effect of cleaning the dictionary of executors - they started to fail main in tests where bothn DB and NonDB tests were run together.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
Not 100% sure if all side-effects are handled though. Let's see.

**Comment by potiuk** [comment]
Yeah. As I was afraid, it looks like there is another side effect added in the other test.

**Comment by potiuk** [comment]
OK. Now it shoudl be better.

**Comment by potiuk** [comment]
Mrrging. The tests started to pass.

**Comment by o-nikolas** [comment]
Thanks for the fix :+1:

**Pull request merged**
