### PR TITLE
Update black version automatically in pre-commit configuration

### PR DESCRIPTION
**Pull request by potiuk**
Follow up after #28576

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — COMMENTED** [review]
I think it's not just for black.. also rich and possibly others?
I wonder if we can use aliasing the version number https://hackernoon.com/repeating-nodes-with-yaml-aliases-like-a-pro-5jn34yo

**Comment by potiuk** [comment]
> I think it's not just for black.. also rich and possibly others? I wonder if we can use aliasing the version number https://hackernoon.com/repeating-nodes-with-yaml-aliases-like-a-pro-5jn34yo

Feel free to do it for others too :). Should be easy to do follow-up in a similar way.

Yaml aliasing only work on nodes not on sub-strings inside the nodes.

**Comment by potiuk** [comment]
BTW. Rich is a different problem - it is >= limited to force an upgrade for everyone for a buggy version, but we do not want to specifically synchronize it to specific version. 

There is a big difference - rich is just to "print" output to the user (and auto-update of rich is something that happens automatically with `pre-comit auto-update`. And we REALLY WANT to keep it syncrhonized in pre-commits because black reformats our generated code, so we want to make sure the reformatting is not conflicting with regular formatting applied by the pre-commit. If black changes the decision about formatting (happened in the past) this would mean that our pre-commits will be cancelling each-others formatting when a new file is generated (that's why also we want to fix black so that formatting is the same for users.

**Comment by potiuk** [comment]
Here is more info why YAML anchors (I am not even sure if they are supported for pre-commits) would not work for string replacement: https://stackoverflow.com/questions/59721008/embedding-yaml-alias-within-yaml-string

**Review by eladkal — APPROVED** [review]
:+1:

**Comment by potiuk** [comment]
random failure. Merging.

**Comment by kaxil** [comment]
Love it, pre-commit to handle pre-commit

**Comment by potiuk** [comment]
Inception indeed :)

**Pull request merged**
