### PR TITLE
[AIRFLOW-2779] Add license headers to doc files

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-2779

### Description

- [x] This adds ASF license headers to all the .rst and .md files with the
exception of the Pull Request template (as that is included verbatim
when opening a Pull Request on Github which would be messy)
### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
@Fokko @r39132 @kaxil PTAL - last PR before we can start  1.10.1RC1 🎉

**Comment by bolkedebruin** [comment]
@ashb looks good. How did you ensure you covered all docs?

**Review by kaxil — APPROVED** [review]
Awesome 🎉

**Comment by Fokko** [comment]
I see:
```
[WARNING] Files with unapproved licenses:
  lang/csharp/README.md
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/FixedTest.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/SimpleCallback.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/TestRecordWithUnion.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/AllTestRecordPartial.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/TestRecordExtensions.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/AllTestRecord.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/TestError.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/TestRecord.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/AllEnum.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/MailCallback.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/Message.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/Kind.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/MD5.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/Mail.cs
  lang/csharp/src/apache/ipc.test/GeneratedFiles/org/apache/avro/test/Simple.cs
```

Would it be possible to add the license header to the generated file? Possibly you can make this part of the template. In the case of the readme, you can add it as an exception: https://github.com/apache/avro/blob/master/pom.xml#L229

**Comment by ashb** [comment]
> @ashb looks good. How did you ensure you covered all docs?

`find . -iname '*.rst' -or -iname '*.md'` - so not foolproof

**Comment by ashb** [comment]
I'm updating the .rat-excludes to not ignore docs or md files now

**Comment by ashb** [comment]
@Fokko Where is that message from? I have only been checking the licenses against files in git (i.e. in a clean checkout)

**Comment by ashb** [comment]
Tests failed because I applied the diff from 1-10-test to master wrong, so rat didn't run. Take two.

**Comment by ashb** [comment]
@Fokko I've got all the excludes that I needed for passing on Travis, if there are extra ones that we need for local dev we can add those later

**Review by Fokko — APPROVED** [review]
Aweseom @ashb

**Comment by Fokko** [comment]
Who will cherry-pick it onto v1-10-test? :D

**Comment by ashb** [comment]
I'll do that - it'll conflict and I already know how to resolve it.

**Comment by Fokko** [comment]
Thanks! 👍

**Pull request merged**
