### PR TITLE
[AIRFLOW-1159] upgrading to docker >2.0

### PR DESCRIPTION
**Pull request by elipapa**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. 
    - https://issues.apache.org/jira/browse/AIRFLOW-1159
    - https://issues.apache.org/jira/browse/AIRFLOW-944

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

`docker-py` has been renamed to `docker` and introduced a few breaking changes http://docker-py.readthedocs.io/en/stable/change-log.html

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

the functionality is not altered/improved and no new test is required. 

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by saguziel** [comment]
@elipapa pls fix tests

**Comment by elipapa** [comment]
tests seem to fail b/c of a pre-existing cache. how can one clear the cache
on travis?

**Comment by r39132** [comment]
@elipapa please rebase. I will take a look after.

**Comment by Fokko** [comment]
We already switched a couple of times between `docker` and `docker-py`, but I can't recall the nuances. @benjaminsims ?

**Comment by elipapa** [comment]
@Fokko actually there are no differences: it's the same official docker python SDK package, but it has been renamed after v2.0. 
The official documentation (https://docker-py.readthedocs.io/en/stable/) now dictates the install to be `pip install docker` instead of `pip install docker-py`

**Comment by Fokko** [comment]
Ack, thanks. It looks like 3.3.0 is the current version. Maybe bump it to 3+ right away?

https://pypi.org/project/docker/

**Comment by elipapa** [comment]
That's what's already happening. 
`pip` will by default use the most recent stable version (which is 3.3.0 at the moment). I have only placed the requirements that it is `>=2.0` but not fixed it at that. 

You can see it in the travis log:
image

**Comment by ron819** [comment]
@elipapa any progress with this?

**Comment by ashb** [comment]
Fixed by #4049 or #3407

**Pull request closed without merging**
