### PR TITLE
[AIRFLOW-5556]Add dag file processor timeout

### PR DESCRIPTION
**Pull request by pingzh**
to timeout DagFileProcessor

As of right now, it uses dagbag_import_timeout to control time out of
DagFileProcessor, which is intended to control the timeout of loading
python file.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5556
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
As of right now, it uses `dagbag_import_timeout` to control time out of
DagFileProcessor, which is intended to control the timeout of loading
python file.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Config change

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

@KevinYang21

### CODE REVIEW

**Comment by ashb** [comment]
Other than a confusing name why do we need a new config setting? Is the other setting actually used anywhere else?

**Comment by pingzh** [comment]
> Other than a confusing name why do we need a new config setting? Is the other setting actually used anywhere else?

The `dagbag_import_timeout` is used to control the timeout of `load_source` of python file. Now, it is also used to control the timeout of `DagFileProcessor`, which definitely takes longer than `load_source`, as it not only `load_source` but also does `process_dags`, update db states, etc.

**Comment by ashb** [comment]
```
$ git grep dagbag_import_timeout
airflow/config_templates/default_airflow.cfg:dagbag_import_timeout = 30
airflow/jobs/scheduler_job.py:        processor_timeout_seconds = conf.getint('core', 'dagbag_import_timeout')
```

**Comment by pingzh** [comment]
> ```
> $ git grep dagbag_import_timeout
> airflow/config_templates/default_airflow.cfg:dagbag_import_timeout = 30
> airflow/jobs/scheduler_job.py:        processor_timeout_seconds = conf.getint('core', 'dagbag_import_timeout')
> ```
```
$ ag dagbag_import_timeout
airflow/config_templates/default_airflow.cfg
163:dagbag_import_timeout = 30

airflow/models/dagbag.py
75:    DAGBAG_IMPORT_TIMEOUT = conf.getint('core', 'DAGBAG_IMPORT_TIMEOUT')
200:            with timeout(self.DAGBAG_IMPORT_TIMEOUT):

airflow/jobs/scheduler_job.py
1299:        processor_timeout_seconds = conf.getint('core', 'dagbag_import_timeout')
```

**Comment by ashb** [comment]
D'oh case sensitive. That'd be why I was confused.

**Review by ashb — APPROVED** [review]

**Comment by pingzh** [comment]
> D'oh case sensitive. That'd be why I was confused.

sorry about the confusion, i should have mentioned it before.

**Pull request merged**
