### PR TITLE
Fix failing get_logs on AzureContainerInstanceHook

### PR DESCRIPTION
**Pull request by Pverheijen**
Tried to fetch ContainerInstanceManagementClient.container but it's not a valid attribute, .containers is

---
Make sure to mark the boxes below before creating PR: [x]

- [ ] Description above provides context of the change
- [ ] Unit tests coverage for changes (not needed for documentation changes)
- [ ] Target Github ISSUE in description if exists
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions.
- [ ] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by feluelle** [comment]
hmm but the test fails: https://github.com/apache/airflow/pull/9737/checks?check_run_id=853862794#step:6:803

also in azure sdk it is also like this: https://github.com/Azure/azure-sdk-for-python/blob/88ceae1025573de32739c12c7b8a9ad5b9b343a1/sdk/containerinstance/azure-mgmt-containerinstance/tests/test_mgmt_containerinstance.py#L133

**Comment by Pverheijen** [comment]
I'll get back to this next week, need to check setup settings but this might be a specific version issue. Changing it to containers made it work for me.

**Comment by Pverheijen** [comment]
Hey there,

I'm using:

Puckel's airflow image
# VERSION 1.10.9 
# SOURCE: https://github.com/puckel/docker-airflow

Which features AIRFLOW_VERSION=1.10.9
and python:3.7-slim-buster

And it gave me the following error, the proposed change makes it work for me.

```
AttributeError: 'ContainerInstanceManagementClient' object has no attribute 'container'
```

It seems that a certain version of the Azure SDK uses container and another containerS

Not sure what the best way to proceed is.

**Comment by feluelle** [comment]
Yes, I figured it out @Pverheijen 

Airflow 1.10.9 (setup.py): `azure-mgmt-containerinstance>=1.5.0` means it will install latest which is `2.0.0`

See: https://github.com/apache/airflow/blob/1.10.9/setup.py#L162
And: https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-containerinstance_2.0.0/sdk/containerinstance/azure-mgmt-containerinstance/tests/test_mgmt_containerinstance.py#L133

Airflow 1.10.11 and above (setup.py): `azure-mgmt-containerinstance>=1.5.0,<2` means it will install `1.5.0`

See: https://github.com/apache/airflow/blob/1.10.11/setup.py#L192
And: https://github.com/Azure/azure-sdk-for-python/blob/azure-mgmt-containerinstance_1.5.0/sdk/containerinstance/azure-mgmt-containerinstance/tests/test_mgmt_containerinstance.py#L133

**Comment by feluelle** [comment]
Which means if you want to change from `container` to `containers` you would have to change setup.py to `azure-mgmt-containerinstance>2`

**Pull request closed without merging**
