### PR TITLE
[AIRFLOW-2056] Refactor: Integrate all GCS operators into 1 file

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2056

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- Integrated all the GCS*Operators into single file
- Changed corresponding tests
- Changed corresponding documentation in docs

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Commit aims to refactor and adds no new code

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by criccomini** [comment]
Won't this break all existing DAGs, as their imports will point to the old files?

**Comment by kaxil** [comment]
Thank you for your response @criccomini . This would break the existing DAGs but this commit can be included in 2.0. I have added documentation in `updating.md`, `integration.rst` and `code.rst` regarding the update. There were only 2 operators in `Airflow 1.9` namely: `GoogleCloudStorageDownloadOperator` and `GoogleCloudStorageToBigQueryOperator` but there has an addition of 3 more operators, hence I feel this will keep it organized and allow to add further GCS operators. Let me know your thoughts.

Also this is replicating the current implementation of `DataProc{*}Operators`, hence keeping consistency.

**Comment by fenglu-db** [comment]
+1, thanks @kaxill, LGTM for 2.0.

**Comment by criccomini** [comment]
Need to think through how to manage this. We don't have a 2.0 branch so far. Merging into master would put this on track for 1.10, which we don't want due to compatibility issues. I'm going to leave this open for the time being. If we cut 1.10 soon, then we can merge it in, else we might have to create a 2.0 branch and have you change the PR to point to the 2.0 branch rather than master.

**Comment by kaxil** [comment]
@criccomini Sure we can do that. Or else we can keep the files as they are but also create an integrated file and then we can delete all the single GCS files in Airflow 2.0. But yes I am happy to do it either way.

**Comment by Fokko** [comment]
Let's wait for what comes out of the discussion: https://lists.apache.org/thread.html/4e648d9421c792d4537f5ac66f1a16dce468f816fc5221a9f9db9433@%3Cdev.airflow.apache.org%3E

Closing this for now

**Pull request closed without merging**
