### PR TITLE
[AIRFLOW-1192] Some enhancements to qubole_operator

### PR DESCRIPTION
**Pull request by msumit**
Dear Airflow maintainers,

Please accept this PR. 

### JIRA
    https://issues.apache.org/jira/browse/AIRFLOW-1192

### Description
1. Upgrade qds_sdk version to latest
2. Add support to run Zeppelin Notebooks
3. Move out initialization of QuboleHook from init()

### Tests
- No major addition or functionality change. Just adding couple of entries in templatable fields and bit of refactoring.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you please add tests and correct the typo in your commit message?

**Comment by msumit** [comment]
Hi @bolkedebruin, have correct the commit message and added specs. but somehow Travis is failing and having some setup issues? Can you suggest how I can fix it, in case you've seen the issue before?

**Comment by msumit** [comment]
@bolkedebruin there was some issue with Travis, I reran the tests and they got passed -> https://travis-ci.org/msumit/airflow

**Comment by bolkedebruin** [comment]
please retrigger the build by an empty commit.

**Comment by msumit** [comment]
@bolkedebruin done

**Pull request closed without merging**
