### PR TITLE
[AIRFLOW-2029] Fix AttributeError in BigQueryPandasConnector

### PR DESCRIPTION
**Pull request by fenglu-db**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2029

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
When BigQueryPandasConnector encounters a BQ job insertion error, the exception will be assigned to connector.http_error, which is defined in parent connector GbqConnector but uninitialized. Hence an AttributeError exception will be thrown and the exception handling routine is never exercised. 

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by fenglu-db** [comment]
@criccomini PTAL and thanks.

**Comment by criccomini** [comment]
Curious, did Pandas make a backwards incompatible change to their API? If so, should we force Airflow's Pandas version to be upgraded to the compatible API version, so older Airflow installs won't have the older Pandas class?

**Comment by fenglu-db** [comment]
I could be wrong but don't think this is a Pandas issue. The root cause for this specific bug is that the parent object (i.e., GbqConnector) is not initialized.

**Comment by criccomini** [comment]
Hmm, so this was never working?

TBH, I don't think we use it, so could be possible.

**Comment by fenglu-db** [comment]
The bug is only triggered on the unhappy path (e.g., a bq job insertion error).

**Comment by criccomini** [comment]
Gotcha

**Comment by criccomini** [comment]
LGTM! merged

**Comment by cbandy** [comment]
@fenglu-g What version of `pandas-gbq` are you running?

**Comment by cbandy** [comment]
> When BigQueryPandasConnector encounters a BQ job insertion error, the exception will be assigned to connector.http_error, which is defined in parent connector GbqConnector but uninitialized.

This attribute was added in [`pandas-gbq == 0.3.0`](https://github.com/pydata/pandas-gbq/blob/0.3.0/pandas_gbq/gbq.py#L176).

> Curious, did Pandas make a backwards incompatible change to their API?

For what we're doing, `pandas-gbq` changed dramatically. We override the constructor to set `self.service` ourselves, but that attribute no longer exists:

https://github.com/pydata/pandas-gbq/blob/0.2.1/pandas_gbq/gbq.py#L213
https://github.com/pydata/pandas-gbq/blob/0.3.0/pandas_gbq/gbq.py#L185

When I pinned my local install to 0.2.1, I got the [following error](https://github.com/pydata/pandas-gbq/blob/0.2.1/pandas_gbq/gbq.py#L27-L38):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/airflow/contrib/hooks/bigquery_hook.py", line 93, in get_pandas_df
    connector = BigQueryPandasConnector(project, service, dialect=dialect)
  File "/usr/local/lib/python3.5/dist-packages/airflow/contrib/hooks/bigquery_hook.py", line 142, in __init__
    gbq_check_google_client_version()
  File "/usr/local/lib/python3.5/dist-packages/pandas_gbq/gbq.py", line 38, in _check_google_client_version
    _GOOGLE_API_CLIENT_VERSION))
ImportError: pandas requires google-api-python-client >= 1.6.0 for Google BigQuery support, current version 1.5.5
```

There's a deeper compatibility issue here.
https://github.com/apache/incubator-airflow/blob/d760d63e1a141a43a4a43daee9abd54cf11c894b/setup.py#L129-L136

**Pull request closed without merging**
