### PR TITLE
Password auth

### PR DESCRIPTION
**Pull request by neovintage**
Added a password auth mechanism for users. This is the last bit needed for locking down Airflow for use on Heroku.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Should there be some hash salting based on the app's secret key?

**Comment by neovintage** [comment]
@mistercrunch im hashing with bcrypt. the salt is built-in. no need to worry about it.

**Comment by neovintage** [comment]
python3 support took longer than expected. This should be good for a review now.

**Comment by mistercrunch** [comment]
Looks nice, mergin'!

**Pull request merged**
