### PR TITLE
[FEATURE] update K8S-KIND to 0.13.0

### PR DESCRIPTION
**Pull request by raphaelauv**
https://github.com/kubernetes-sigs/kind/releases/tag/v0.13.0

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @raphaelauv  - can you also please update the `src/airflow_breeze/global_constants.py` ?

We are in the process of migrating the "kind" commands to the new breeze and for a while we want to keep the versions updated in both.

**Comment by raphaelauv** [comment]
@potiuk the current commit already update `dev/breeze/src/airflow_breeze/global_constants.py`

**Comment by potiuk** [comment]
🤦

**Comment by potiuk** [comment]
I also fixed the doc-generation failure in #23640 :). Merging.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
