### PR TITLE
[AIRFLOW-3864] Recognize lists as JSON in variables --import

### PR DESCRIPTION
**Pull request by samdfonseca**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3864
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
  - When settings a variable via import, sets `serialize_json=True` if its value is a list

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - There doesn't seem to be support currently for cli tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
LGTM

**Comment by samdfonseca** [comment]
@zhongjiajie thanks for the review. Anything you need from me to get this merged?

**Comment by OmerJog** [comment]
Is this related to https://issues.apache.org/jira/browse/AIRFLOW-2141 ?

**Comment by zhongjiajie** [comment]
@samdfonseca Sorry, I not a committer, you could at some committer to review and merge your PR, like @Fokko @ashb PTAL thanks.
BTY, welcome to Apache Airflow

**Comment by zhongjiajie** [comment]
@OmerJog Yes, I think is related to that jira ticket, do you think we should use
```python
if not isinstance(v, str):
    Variable.set(k, v, serialize_json=True)
```

**Comment by ashb** [comment]
Could you please add some tests to this - there is a case already in tests/core.py - CliTest.test_variables. You'll probably just have to extend the file it imports and add a new assertion or two

**Review by ashb — CHANGES_REQUESTED** [review]
Please add unit tests

**Comment by ashb** [comment]
Please target against AIRFLOW-2141 instead.

**Comment by kaxil** [comment]
Closed in favor of https://github.com/apache/airflow/pull/4991

**Pull request closed without merging**
