### PR TITLE
starting triggerer for system-tests

### LINKED ISSUE #31826: Add a command line option to start a triggerer process with breeze
### Description

As discussed in https://lists.apache.org/thread/ss0605b561bcrrlogydgww1pzo97691j
It would be helpful to be able to start a triggerer process from the same command line that starts breeze, using an option like `--run-triggerer=True` or `--with-triggerer`.

### Use case/motivation

This option would be used when running system tests that contain deferrable operators, and thus need a triggerer to run to completion.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Bowrna**
closes: #31826
related: #31826 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by o-nikolas** [comment]
> Can you explain to me how you run the system tests? I do this by setting the env var `RUN_SYSTEM_TESTS` and then run the command `breeze testing tests --test-type` with providers or other options. I want to confirm if I doing it correctly.

We use something like:
`breeze testing tests <test name> --system amazon`
 
> Can you tell me an example system test that I can find that depends on triggerer so that I can run that example and check if it works?

There is no such test currently, since triggerer wasn't supported (kind of a chicken and egg problem). You'll have to take an existing test and update it to be deferrable. It shouldn't be too hard, you'll just have to pass a deferrable flag through to an operator. @syedahsn any suggestions or corrections?

Lastly, I'm not sure how well the DebugExecutor will handle the deferring though, that will be interesting to see.

**Comment by syedahsn** [comment]
Most of the system tests can be run in deferrable mode by taking one of the supported operators/sensors and passing `deferrable=True`. Some good examples are the RDS system test, the redshift system test, or the EKS system tests. Keep in mind that some of these tests take a while to finish because they are actually provisioning resources on your AWS account.

**Comment by Bowrna** [comment]
ah this will involve setting up the third party system config to run the test right.. I completely forgot about that part and I don't have an account personally to up and run these tests. Is there any other way for me to do it? Can I push this code and will that be run as part of the Github actions CI pipeline test? @potiuk @o-nikolas @syedahsn

**Comment by o-nikolas** [comment]
> ah this will involve setting up the third party system config to run the test right.. I completely forgot about that part and I don't have an account personally to up and run these tests. Is there any other way for me to do it? Can I push this code and will that be run as part of the Github actions CI pipeline test? @potiuk @o-nikolas @syedahsn

The code will run as Airflow CI, but the system tests wont be executed. Since Airflow as a community can't be on the hook for those infrastructure costs.

As a single user doing some testing, I think it shouldn't be too hard to find a system test that would be well within the AWS free tier and not cost you any money at all to run. But if the task is getting too overwhelming from the perspective, feel free to put what you have in a PR now and we can take it over when we find the time.

**Comment by potiuk** [comment]
Yeah. you can even test some simple tests using free tier of AWS.

**Comment by Bowrna** [comment]
i will reopen the issue after adding simple test with free tier of AWS.

**Comment by Bowrna** [comment]
@o-nikolas @syedahsn @potiuk any idea how i can reopen this PR.

**Comment by potiuk** [comment]
reopened.

**Comment by vincbeck** [comment]
Closing this once since #39176 has resolved it

**Pull request closed without merging**
