### PR TITLE
Switch to Debian 11 (bullseye) as base for our dockerfiles (#21378)

### LINKED ISSUE #18190: Docker image - Migrate to 3.x-slim-bullseye from 3.x-slim-buster
### Description

Currently docker images are produced based on top of 3.x-slim-buster python and as a result output inherits related debian vulnerabilities. 

### Use case/motivation

Migrate to the latest debian release (bullseye was released around a month ago) for docker images.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
Debian 11 Bullseye have been released some time ago as the new
LTS Debian release and already all our dependencies (including
MySQL and MSSQL ODBC drivers) caught up with it so we can finally
migrate to it.

This change switches base images to bullsey for our Dockerfiles
as well as for Redis image we are using in CI.

The relevant packages have been updated to include that
and documentation have been updated.

Examples of ours also are updated to use "bullseye" rather than
buster.

Closes: #18190
Closes: #18279

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
Seems that yesterday building in Seatle  was broken :). let's see if it fixed, and if not I will raise an issue with Microsoft :)

**Comment by potiuk** [comment]
Seems better. Looks like the mirroring system of MS got fixed since yesterday :rofl: 

I just got the random (I hope) K8S failure, but - learning from experience - I re-run it again to get it finally green.

**Comment by potiuk** [comment]
I see one more flaky test (unrelated - I will fix it separately) but I want to see if it's Bullseye or maybe it was truly random

**Comment by potiuk** [comment]
All green :).

**Pull request merged**
