### PR TITLE
Add borderWidthRight to grid for Firefox scrollbar

### LINKED ISSUE #35074: Grid UI Scrollbar / Cell Click Issue
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

This is in 2.5.2, we're in the midst of upgrading to to 2.7 but haven't tested thoroughly if this happens there as we don't have the volume of historic runs. 

On the DAG main landing page, if you have a long DAG with multiple sub-groups, and a number of runs recorded, the UI in it's default listing of `25` previous runs, causes the scrollbar for the grid to overlay the right-most column, making it impossible to click on the cells for the right-most DAG run.

image

This is specifically in Firefox.

It's not world-ending, just a bit annoying at times.

### What you think should happen instead

The Grid area should have enough pad to the right of the rightmost column to clear the scrollbar area.

You can get around this by altering the number of runs down to 5 in the dropdown above the grid, this seems to fix the issue in order access the cells.

### How to reproduce

This seems to be the scenario it happens under:

- DAG with long list of tasks, including sub-groups, and moderately long labels
- Show 25 runs on the dag screen

image

### Operating System

Ubuntu 22.04 / macOS

### Versions of Apache Airflow Providers

N/A

### Deployment

Other

### Deployment details

Custom deployment.

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by vchiapaikeo**
closes: https://github.com/apache/airflow/issues/35074

Before:

https://github.com/apache/airflow/assets/9200263/ac816549-c3fa-4ca4-813c-cdd0b9abcb60

After:

https://github.com/apache/airflow/assets/9200263/fcd5fe25-6cbd-48fd-858e-f07907d33dcd

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vchiapaikeo** [comment]
@pierrejeambrun , wdyt? I tried other options like manipulating scrollbar-gutter, adding extra padding, and margin but none seemed to work.

**Comment by bbovenzi** [comment]
> @pierrejeambrun , wdyt? I tried other options like manipulating scrollbar-gutter, adding extra padding, and margin but none seemed to work.

We have a padding right `pr={4}` in the parent `<Box>` component. Increasing that didn't work?

**Comment by vchiapaikeo** [comment]
@bbovenzi , this seems to work from Chrome but doesn't work for Firefox :-(

https://github.com/apache/airflow/assets/9200263/a61fe5f6-157f-4546-81d7-cd8a430e2f7f

**Review by bbovenzi — APPROVED** [review]
if it works in chrome and firefox then this is good.

**Comment by vchiapaikeo** [comment]
@eladkal , wdyt? Okay to merge here?

**Review by eladkal — APPROVED** [review]

**Pull request merged**
