### PR TITLE
[AIRFLOW-4201][AIP-3-subtask-5] Replace unicode strings by normal strings

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4201

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
Can you rebase onto master?

**Comment by zhongjiajie** [comment]
@Fokko CI green, PTAL, thanks.

**Comment by Fokko** [comment]
Maybe we can get rid of the `six.PY3` here as well: https://github.com/apache/airflow/blob/4b2fdb89b6e7fe4365c9512aca08476b1af86f34/tests/core.py#L967-L971

**Comment by zhongjiajie** [comment]
@Fokko we have a AIP-3 subtask https://issues.apache.org/jira/browse/AIRFLOW-4199 to remove check if     python version is py3. so I think we should remove on that. Related PR https://github.com/apache/airflow/pull/5019
WDYT?

**Comment by kaxil** [comment]
Can you please rebase on master

**Comment by zhongjiajie** [comment]
@kaxil Thanks, had rebase on master and waiting for CI.

**Comment by zhongjiajie** [comment]
@kaxil  FYI, CI green

**Review by Fokko — APPROVED** [review]
Thanks @zhongjiajie  LGTM

**Comment by zhongjiajie** [comment]
Thanks @Fokko @kaxil

**Pull request merged**
