### PR TITLE
[AIRFLOW-150]  setup.py classifiers dict should be list

### PR DESCRIPTION
**Pull request by aoen**
Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-150

setup.py classifiers dict should be list (this broke releasing with pypi)

@bolkedebruin @mistercrunch

### CODE REVIEW

**Comment by r39132** [comment]
meh...
This might not be incidental - someone treating this as a set to avoid dupes while getting list compatibility. I've fine with the change, given that this classifier list won't grow to the point of having dupes, but I'm also fine with leaving it as is. 

> > > {1,1,2,3}
> > > set([1, 2, 3])
> > > [1,2,3]
> > > [1, 2, 3]

**Comment by criccomini** [comment]
Noticed the same thing as @r39132. What about:

```
list({'a', 'b', 'c'})
```

**Comment by mistercrunch** [comment]
LGTM, definitely no need for de-duping here and is required as the lib chokes on a set (@aoen had to debug this yesterday as it was getting in the way of running the commands to push the release to pypi)

**Comment by r39132** [comment]
Didn't notice it broke pypi.. geez... more stuff we need to test for in the future. 
+1

**Comment by r39132** [comment]
@mistercrunch @aoen Can one of you request INFRA treat this as a release. I notice https://github.com/apache/incubator-airflow/releases does not show it.

**Comment by aoen** [comment]
Makes sense ,will file a ticket.

**Comment by aoen** [comment]
Filed https://issues.apache.org/jira/browse/INFRA-11947

**Pull request merged**
