### PR TITLE
Hide logical date and run id in trigger UI form

### LINKED ISSUE #34726: Hiding Run Id and Logical date from trigger DAG UI
### Description

With the new more user friendly Trigger UI (`/dags/mydag/trigger`), one can direct more users to using Airflow UI directly.

However, the first two questions a user has to answer is **Logical date** and **Run ID**, which are very confusing and in most cases make no sense to override, even for administrators these values should be rare edge cases to override.

image

**Is it possible to?**
* Make these inputs opt-in on a per DAG level?
* Global config to hide them from all DAGs?
* Hide under "advanced and optional" section?

Airflow version 2.7.1

### Use case/motivation

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jscheffl**
This PR is an improvement based on the feedback raised in issue #34726 and optimizes the layout of the trigger UI form.

This PR changes:
- Run ID and Logic date are now in the folded section of generated JSON config - why? Because most users don't know what this is and (most probably) only advanced users know what to enter. Still for these advanced users it is needed and therefore in the collapsed section
- Both fields nevertheless are added to the legacy form as well if `AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True` is set
- The DAG documentation is now always expanded in the UI allowing to show instructions to the users.
- Update screenshot in the docs to new layout

How to test?
- Launch the UI and and trigger the DAG `example_params_ui_tutorial` and check the form
- Launch webserver with ENV `AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True` and trigger the DAG `example_python_operator`with config
- Check the Github old/new screenshow if you want to have a "sneak preview".

UI Before: 
image

UI After:
image

DAG Options when un-folded lower section:
image

closes: #34726

### CODE REVIEW

**Comment by potiuk** [comment]
I like it. No good knowledge to comment on the code, but the ideas here are good.

**Review by eladkal — APPROVED** [review]
Nice!

**Comment by hterik** [comment]
Nice. Thanks @jscheffl  :+1:

**Comment by potiuk** [comment]
Congraulations on your first (!?) merged PR as committer @jscheffl :D

**Pull request merged**
