### PR TITLE
[AIRFLOW-2509] Separate config docs into how-to guides

### PR DESCRIPTION
**Pull request by tswast**
Also moves how-to style instructions for logging from "integration" page
to a "Writing Logs" how-to.

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2509

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Splits Configuration documentation into separate how-to guides, much as the Django documentation does.

image

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No tests. Docs-only change.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

Docs-only change.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by tswast** [comment]
Travis failure appears to be unrelated to this change (permissions error on installing a package).

**Review by Fokko — APPROVED** [review]
I think this is a good improvement. +1

**Review by kaxil — APPROVED** [review]
LGTM

**Comment by kaxil** [comment]
Thank you @tswast for this PR. The documentation changes are always very important. Appreciate that.

**Comment by kaxil** [comment]
@tswast Can you update the documentation [here](http://airflow.readthedocs.io/en/latest/howto/create-connection.html) to say that you can also create connections using the Airflow Web UI which is much easy and intuitive as compared to environment variables method and also point to the specific link of creating connection (see [here](http://airflow.readthedocs.io/en/latest/concepts.html#connections) ) instead of linking it to the concepts section?

Or instead of 2 separate pages i.e 1) **Securing connections**, and 2) **Creating connections**: I think a single page **Creating and Securing connections** would make more sense.

What do you think about it @tswast?

**Comment by tswast** [comment]
@kaxil Yes, updating the connection page is the next thing I want to work on. Web UI instructions are a good idea.

I actually would like to have space to talk about all the specific connection types on the creating a connection page. The PostgreSQL example you link to would be a good one to add. Selfishly, I'd also like to document how to create a GCP connection soon, too.

It could make sense to combine the creating and securing pages, but securing them felt like a very different task from creating one, which is why I split them up.

**Pull request closed without merging**
