### PR TITLE
[AIRFLOW-4452] Webserver and Scheduler keep crashing because of slack…

### PR DESCRIPTION
**Pull request by feng-tao**
…client update

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4452
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @XD-DENG @ashb @potiuk  @KevinYang21

**Review by KevinYang21 — APPROVED** [review]

**Comment by KevinYang21** [comment]
Will merge after CI passed.

**Comment by feng-tao** [comment]
@KevinYang21 , CI green now :) Could you help to merge the pr?

**Comment by KevinYang21** [comment]
Aaah I didn't finish my dinner fast enough :D

**Comment by feng-tao** [comment]
thanks @KevinYang21 . Welcome aboard :)

**Comment by KevinYang21** [comment]
Actually, we only need a +1 right? Author can merge as long as another committer gave a +1?

**Comment by feng-tao** [comment]
@KevinYang21 that's correct. Not sure if you have merged any pr yet, but I just let you merge it and see if you have anything setup correctly. Of course I could merge it myself :)

**Comment by KevinYang21** [comment]
I see I see :D I just set it up this afternoon and guess it is all good now :D This is actually the first PR I merged 🎉

**Comment by XD-DENG** [comment]
Welcome @KevinYang21 !

**Comment by ashb** [comment]
Since commit subjects are what we put in to the CHANGELOG, when making a change like this in the future can you make it clearer what the change is - for example in this case "[AIRFLOW-4452] Pin slackclient dependency to 1.x" would be more useful I feel

**Comment by KevinYang21** [comment]
Thank you @XD-DENG :D

**Pull request merged**
