### PR TITLE
Added get_extra_dejson method with nested parameter in Connection

### PR DESCRIPTION
**Pull request by dabla**
This new method allows you to specify if you want the nested json as string to be also deserialized.  The already existing extra_dejson property delegates to this method with nested set to False, as this is the default behaviour (nested json strings don't get deserialized by default).  This is a PR in preparation of [#35591](https://github.com/apache/airflow/pull/35591/), as it has become to big, we're going to split it up in smaller ones.  This is one of them.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by dabla** [comment]
> > This new method allows you to specify if you want the nested json as string to be also deserialized.
> 
> I don't think we need to support string-JSON into the native JSON object.
> 
> This one more convenient way to define JSON
> 
> ```json
> {
>     "foo": "bar",
>     "spam": {"egg": 1, "baz": "qux"}
> }
> ```
> 
> Rather this one. Which looks artificial and ugly
> 
> ```json
> {
>     "foo": "bar",
>     "spam": "{\"egg\": 1, \"baz\": \"qux\"}"
> }
> ```

We’ll need it for PR 35591, as there we split the values being put in extra into different textareas for the http connection, leading to those ugly nested json values in the extra field (which will be hidden).

**Comment by Taragolis** [comment]
Maybe we should fix it in the UI side rather than try to create workaround? 
Connection UI itself provided by [FAB](https://flask-appbuilder.readthedocs.io/en/latest/), there is unlikely would be FAB in Airflow 3.0.

**Comment by dabla** [comment]
> Maybe we should fix it in the UI side rather than try to create workaround? Connection UI itself provided by [FAB](https://flask-appbuilder.readthedocs.io/en/latest/), there is unlikely would be FAB in Airflow 3.0.

Indeed, but I don't know if the issue is related to FAB or the CodeMirror widget for the textarea's.  To me this was the "cleanest" approache to solve the issue

**Comment by dabla** [comment]
We could put a TODO remark on that method and state that if the javascript issue would be solved, this one could be simplified.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Let me rebase and rerun tests to see if nothing changed since.

**Pull request merged**
