### PR TITLE
[AIRFLOW-161] New redirect route and extra links

### PR DESCRIPTION
**Pull request by ArgentFalcon**
Second try at #3533, all details the same as before
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
It looks like we have an unhappy test:
```
======================================================================
47) ERROR: test_extra_links_error_raised (tests.www.test_views.TestExtraLinks)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/www/test_views.py line 1633 in setUp
      self.app = application.create_app().test_client()
   AttributeError: 'tuple' object has no attribute 'test_client'
```

**Comment by feng-tao** [comment]
cc @milton0825 , do you want to finish this pr given the pr has been sitting idle for quite sometime? We could change the commit message with you as "co-author" something? WDYT?

**Comment by milton0825** [comment]
@ArgentFalcon do you mind?

**Comment by feng-tao** [comment]
You could take a look at https://help.github.com/en/articles/creating-a-commit-with-multiple-authors (e.g https://github.com/apache/airflow/pull/4788 and https://github.com/apache/airflow/pull/4792). My understanding is that a commit could be authored by multiple people(putting the co-author in commit message).

**Comment by ArgentFalcon** [comment]
Yeah, go ahead

**Pull request closed without merging**
