### PR TITLE
Cancel queued/running builds on second push to PR

### PR DESCRIPTION
**Pull request by ashb**
This uses an action from the marketplace to cancel any running builds
for our main "CI" workflow (the only one we have at the moment)

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
:heart: !

**Comment by ashb** [comment]
I have no idea _if_ this works, but it looks like it should, and was the accepted answer on the Github community, so lets give it a shot, eh?

**Comment by ashb** [comment]
```
{
  eventName: 'push',
  sha: 'dd1bfccf3c09fb1f6cd23dd3fab822d72d339652',
  headSha: 'dd1bfccf3c09fb1f6cd23dd3fab822d72d339652',
  branch: 'master',
  owner: 'apache',
  repo: 'airflow'
}
Found input: 1029499
Found token: yes
Found 492 runs total.
Found 3 runs in progress.
Cancelling another run:  {
  id: 117878496,
  head_sha: '14e241f05c19208090a96744ed5d7d0b5abff365',
  status: 'queued'
}
Status 202
Cancelling another run:  {
  id: 117878144,
  head_sha: '902703da607140c876d4782c01761f3aa21b2956',
  status: 'in_progress'
}
```

Looks like it's cancelled some (queued/pending) builds for master, leaving only the latest one.

**Comment by potiuk** [comment]
Which is great :).

**Pull request merged**
