### PR TITLE
[AIRFLOW-XXX] Add next/prev ds not correct in faq

### PR DESCRIPTION
**Pull request by zhongjiajie**
### Description

Add `[next|prev]_ds[_nodash]` not correct in Faq.md

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I try twice, but CI failed, but docs test pass

**Comment by dstandish** [comment]
also, when manually triggered, prev_ds == next_ds == ds -- i.e. schedule is ignored

**Comment by zhongjiajie** [comment]
@dstandish Good point, will add it into PR, Thanks

**Comment by zhongjiajie** [comment]
@mik-laj Hi Kamil, could you help me for this PR? doc test failed but I can not find some detail error in `faq.rst`

**Comment by mik-laj** [comment]
This is the reason why Travis is sad, but I do not think it's caused by this PR.
```
/home/travis/build/apache/airflow/docs/cli.rst:29: WARNING: Failed to import "get_parser" from "airflow.bin.cli".
```
It can be associated with:
```
flask 1.1.0 has requirement Werkzeug>=0.15, but you'll have werkzeug 0.14.1 which is incompatible.
```
I have launched a new build on the master and there is this problem.
https://travis-ci.org/apache/airflow/jobs/554414028

I think you should wait for the patch to appear on the master and then rebase.

**Comment by zhongjiajie** [comment]
@mik-laj Thanks for clarification and I will wait until your patch merge, but could you referenced your PR to this please?

**Comment by mik-laj** [comment]
I did not make a PR.  I'm on vacation.  I notified other people about the problem.

**Comment by zhongjiajie** [comment]
Got it, hope you have a good time.

**Comment by mik-laj** [comment]
Fix is on master:
https://github.com/apache/airflow/commit/2b366934cdc20e8fb60b4b1e7b6c840a6708b258 
Can you rebase?

**Comment by zhongjiajie** [comment]
@mik-laj Thanks for mention, and doc CI pass in https://travis-ci.org/apache/airflow/builds/554929789?utm_source=github_status&utm_medium=notification

**Comment by zhongjiajie** [comment]
It pass in my personal repo https://travis-ci.org/zhongjiajie/airflow/builds/554929778?utm_medium=notification&utm_source=email
but failed in Apache's https://travis-ci.org/apache/airflow/builds/554929789?utm_source=github_status&utm_medium=notification

So I think it random error

**Comment by mik-laj** [comment]
I restarted failed job.

**Comment by zhongjiajie** [comment]
Still failed, I will try force push

**Comment by zhongjiajie** [comment]
@ash @mik-laj @potiuk PTAL thanks.

**Review by potiuk — CHANGES_REQUESTED** [review]
I think slight modification might be a bit better understandable:

```
Why next_ds or prev_ds might not contain expected values?
---------------------------------------------------------

- When scheduling DAG, the ``next_ds`` ``next_ds_nodash`` ``prev_ds`` ``prev_ds_nodash`` are calculated using
  ``execution_date`` and ``schedule_interval``. If you set ``schedule_interval`` as ``None`` or ``@once``,
    the ``next_ds``, ``next_ds_nodash``, ``prev_ds``, ``prev_ds_nodash`` valueS will be set to ``None``.
- When manually triggering DAG, the schedule will be ignored, and ``prev_ds == next_ds == ds``
```

**Review by potiuk — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks @potiuk

**Comment by potiuk** [comment]
Thank you!

**Comment by houqp** [comment]
@zhongjiajie i noticed commit 52b67c33 got merged into master based based on this PR's merge history and showed up in our internal airflow mirror repo, but subsequently disappeared from the master branch. Looks like it got replaced by 3ee2dcb, do you know what happened?

**Comment by zhongjiajie** [comment]
@houqp  I find that in my github activity too, but I don't know what cause that, I'm don't have write access to this repo, maybe @potiuk could explain that.

But I find out https://github.com/apache/airflow/commit/52b67c33340edd11331eda8cb79e4101709ec247 is not belong to any branch and guess some git command(like `rebase` `merge`) change it commit hash.

**Comment by potiuk** [comment]
Is this a problem @houqp ? I indeed replaced it  with corrected version (it was a doc-only change that caused a doc failure in Travis - indentation problem. I realised quite quickly it was a problem and replaced it (force-pushed) with corrected version. But if that causes a problem - apologies. I had not realised it might cause some problem for you. I will make sure to not do it any more

**Comment by houqp** [comment]
@potiuk, thanks for confirming. No worry, i just wanted to make sure this is expected, not due to some kind of bug :)

Usually I would recommend not doing any kind of force push to master (or to any other permanent public branches) since it will cause conflict to downstream contributors. In our case, it broke our internal git mirroring.

I also recommend setting master to a protected branch on github so it won't get force updated with wrong history accidentally. I have done this in the past and it was not a fun exercise to communicate and revert ;)

**Comment by zhongjiajie** [comment]
@potiuk Sorry it's my bad, I find out incorrect indent in https://github.com/apache/airflow/commit/52b67c33340edd11331eda8cb79e4101709ec247#diff-c6f0a0722c6a2f86277535d7bcec7f8cR220 , I should check the content before commit

**Comment by potiuk** [comment]
Absolutely @houqp -> will not do it any more, knowing other's git mirroring might get broken. It was really me rushing with merge of "doc-only" change. And no worries @zhongjiajie -> I rushed with merging it because of the recent Travis CI queuing problems - having to wait few hours for Travis CI builds to even start running is not fun for 5 lines of docs change 
:(.

**Pull request merged**
