### PR TITLE
[AIRFLOW-2376] Fix no hive section error

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2376
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Fix the issue which airflow cli throws "backports.configparser.NoSectionError: No section: u'hive'" error.
The reason is because when user uses either run or backfill cli command, airflow tries to copy some of the confirguration(https://github.com/apache/incubator-airflow/blob/master/airflow/utils/configuration.py#L34). Currently hive is one of section for copy, but if user's airflow.cfg doesn't have configuration for this section. It will throw the error described in the jira ticket. Since hive section is not required for core, just remove that.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Just curious why it would just copy a few of the sections, couldn't we fix this by copying the whole config?

**Comment by r39132** [comment]
Also, can you provide full steps to reproduce? I commented as much on the referring Jira.

**Comment by feng-tao** [comment]
hey @Fokko @r39132 , I reproduce the reporter's issue by running airflow backfill example_http_operator -s 2018-02-01 -e 2018-02-02  -i over master branch. I am still not very clear on what is the proper way to fix and what is the history on why we copy configuration this way :)

**Comment by Fokko** [comment]
@mistercrunch Do you know why this copy strategy was implemented?

**Comment by jmeickle** [comment]
Ran into this one because v1.10 is also crashing due to the original `hive` issue. (Or in our case, also `smtp`, since we have non-SMTP SES config instead.)

However I'd also like to note that our deployment features custom configuration sections, and may fall back to defaults if they're not present. Definitely also believe we should copy the entire file.

**Comment by feng-tao** [comment]
Hey @Fokko , I change the pr to copy the whole section and catch NoSection exception.

**Review by Fokko — APPROVED** [review]
LGTM, Thanks @feng-tao

**Comment by r39132** [comment]
Thanks all!

**Pull request closed without merging**
