### PR TITLE
Fix breeze command hashes to "Linux" version.

### PR DESCRIPTION
**Pull request by potiuk**
When calculating command hashes, after click 1.8.1 the hash calculated is different for Linux than for Mac.

Until we fix it, setting it to Linux hashes is good for CI to not fail

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
(or at least it looks like - it also might be that there is other factor that makes it flip-flop).

**Review by gopidesupavan — APPROVED** [review]

**Comment by gopidesupavan** [comment]
I got it i think its the ubuntu upgrade that github release recently ? ubuntu-24.04. might it is default now in our repo

**Comment by gopidesupavan** [comment]
Our CI using now the latest version ubuntu-24.04, https://github.com/apache/airflow/actions/runs/12454695812/job/34766359224#step:1:4

**Comment by potiuk** [comment]
> I got it i think its the ubuntu upgrade that github release recently ? ubuntu-24.04. might it is default now in our repo

Naa. Something else - I see a very weird behaviour on my Mac - the hash is changing between runs, so that's something different.

**Comment by potiuk** [comment]
It looks like it's just NOT STABLE - but I haven't figured out yet what triggers the unstability.

**Comment by gopidesupavan** [comment]
> > I got it i think its the ubuntu upgrade that github release recently ? ubuntu-24.04. might it is default now in our repo
> 
> Naa. Something else - I see a very weird behaviour on my Mac - the hash is changing between runs, so that's something different.

oh okay..

**Comment by potiuk** [comment]
Yeah... It flip-flops randomly so we will keep on seing it... very interesting :)

**Comment by potiuk** [comment]
Ok. Found it - new click does not keep stable sequence of options:

Screenshot 2024-12-22 at 16 59 21

**Comment by potiuk** [comment]
Fix here: https://github.com/apache/airflow/pull/45156

**Pull request merged**
