### PR TITLE
[AIRFLOW-2915] Add example DAG for GoogleCloudStorageToBigQueryOperator

### PR DESCRIPTION
**Pull request by tswast**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2915

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Docs-only change to add an example DAG and a section for GoogleCloudStorageToBigQueryOperator to the operators how-to guides.

image

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

N/A docs-only.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
If I don't have gcp dependency, what happens when I set load_example_dag to true?

**Comment by Fokko** [comment]
Good point @feng-tao, we need to make sure that the examples can still be loaded without having the GCP the dependencies installed. This can be tested quite easily by installing it using `pip install git+https://...` in a new clean docker container. Then try to run a simple task, for example `airflow test airflow_tutorial_v01 print_world 2017-07-01` from https://blog.godatadriven.com/practical-airflow-tutorial

**Comment by tswast** [comment]
@feng-tao @Fokko Thanks for pointing that out. I've pushed a change to only construct the DAG when the GCP operators are available.

**Comment by feng-tao** [comment]
thanks @tswast, lgtm. we could merge once the CI pass.

**Comment by feng-tao** [comment]
@tswast , it seems the flake8 has failed for the pr. Could you look into it?

**Comment by Fokko** [comment]
```

Running flake8 on the diff in the range 7142ae07..af2c4aa8 (1 commit(s)):
--------------------------------------------------------------------------------
airflow/contrib/example_dags/example_gcs_to_bq_operator.py:40:5: E303 too many blank lines (2)
    create_test_dataset = bash_operator.BashOperator(
    ^
airflow/contrib/example_dags/example_gcs_to_bq_operator.py:46:5: E303 too many blank lines (2)
    # [START howto_operator_gcs_to_bq]
    ^
airflow/contrib/example_dags/example_gcs_to_bq_operator.py:61:5: E303 too many blank lines (2)
    delete_test_dataset = bash_operator.BashOperator(
    ^
airflow/contrib/example_dags/example_gcs_to_bq_operator.py:67:5: E303 too many blank lines (2)
    create_test_dataset >> load_csv >> delete_test_dataset
    ^
```

**Comment by tswast** [comment]
Pushed a fix. Had to remove extra blank lines now that the DAG is not constructed at outer layer in the module definition.

**Comment by feng-tao** [comment]
thanks @tswast .

**Comment by kaxil** [comment]
@feng-tao Please remember to resolve the Jira issue as in the new process it isn't resolved by asf-bot. Even I have missed it a couple of time :-)

**Pull request merged**
