### PR TITLE
Enhance magic methods on XComArg for UX

### PR DESCRIPTION
**Pull request by uranusjr**
See #21853. We can do better.

### CODE REVIEW

**Comment by malthe** [comment]
```python
>>> class A:
...     def __getitem__(self, name): print name; return repr(name)
... 
>>> a = A()
>>> next(iter(a))
0
'0'
```
OK that is surprising. Unexpected Python magic!

**Review by malthe — APPROVED** [review]

**Review by ashb — COMMENTED** [review]
Should we add tests?

**Review by dstandish — APPROVED** [review]

**Comment by potiuk** [comment]
> Should we add tests?

Actually two short tests generating the exceptions would be nice :)

**Comment by uranusjr** [comment]
Tests added

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
random ci failure. Merging

**Pull request merged**
