### PR TITLE
[AIRFLOW-1635]: Allow creating GCP connection without requiring a JSON file

### PR DESCRIPTION
**Pull request by barrywhart**
This is a new version of the already-approved PR, https://github.com/apache/incubator-airflow/pull/2634, created against the correct branch (master).

@criccomini 
@jgao54

### CODE REVIEW

**Comment by criccomini** [comment]
The PNG isn't used right? Should be removed.

**Comment by barrywhart** [comment]
One note about the PR. When I built the airflow library from master and tested it by making a request to GCP, it was sending the Airflow version string to Google, which was rejecting it because it was not a normal-looking version number. In order to get it to work, I temporarily changed the version in version.py to "1.10.0". With this change, it worked fine.

**Comment by criccomini** [comment]
What was sending a Airflow version string?

**Comment by criccomini** [comment]
Travis build failed this time..

**Comment by barrywhart** [comment]
Oh yeah, I added the PNG here so I could reference it as a screenshot for the PR, not for the actual stuff to be merged. Will remove.

About the version string, I didn't look into it that carefully, but I'm guessing it was like a user agent version string or something similar. It wasn't anything in my changes, some sort of pre-existing behavior.

**Comment by barrywhart** [comment]
The [Travis build error](https://travis-ci.org/apache/incubator-airflow/jobs/280597085) mentions a missing file. I think this is unrelated to my changes. See below.

```
      INSTANCE_TYPES = json.load(open(os.path.join(RESOURCES_DIR, 'instance_types.json'), 'r'))
   FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/apache/incubator-airflow/.tox/py34-cdh-airflow_backend_sqlite/lib/python3.4/site-packages/moto/ec2/resources/instance_types.json'
```

**Comment by criccomini** [comment]
Master seems happy as of about 4 hours ago. Wonder if it's a transitory issue.

**Review by jgao54 — APPROVED** [review]

**Comment by barrywhart** [comment]
Looks like the build is okay now, I think? Must've been something else.

**Pull request closed without merging**
