### PR TITLE
Bump minimum version for azure containerinstance.

### PR DESCRIPTION
**Pull request by potiuk**
The #40616 used priority for ContainerGroup and it has only been added in 10.1.0 version of azure-containerinstance library

See https://pypi.org/project/azure-mgmt-containerinstance/10.1.0/

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Detected by canary builds.

**Review by eladkal — APPROVED** [review]
interesting. I thought we are checking also against min versions of the depended libs?
Generally speaking if we would know this during review of the PR I would be favor in adding a check for supported version of the lib

**Comment by potiuk** [comment]
> interesting. I thought we are checking also against min versions of the depended libs?
Generally speaking if we would know this during review of the PR I would be favor in adding a check for supported version of the lib

Yes.I am trying to see if we can do it on all PRs in a selective way here: https://github.com/apache/airflow/pull/40768  - becaue currently "special" tests are not run on most of regular PR (which is good), but the "lowest dependency" tests should also run there, I think in all PRs (though they are considerably slower  than regular tests so there is a trade-off).

**Comment by potiuk** [comment]
Yep #40768 should fix it - I was afraid we will hit the workflow limit when I separate it out, but seems that we are not, so it's good to go.

**Pull request merged**
