### PR TITLE
[AIRFLOW-2215] Update celery task to preserve environment variables

### PR DESCRIPTION
**Pull request by johnarnold**
[AIRFLOW-2215] Update celery task to preserve environment variables and improve logging on exception

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [X ] Here are some details about my PR, including screenshots of any UI changes:

Minor change to the celery executor's task:
- Preserve environment variables from parent process (namely, AIRFLOW_HOME) when launching subprocess
- capture stderror
- log exception traceback and exception output from subprocess

### Tests
- [X ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Covered under existing tests, trivial change.

### Commits
- [X ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @johnarnold. Could you fix the flake8 issues. We're working on improving the code quality using flake8, and at every commit the diff's are checked if there are any violations, could you fix them and amend your commit? Thanks

**Comment by johnarnold** [comment]
@Fokko flake8 fixed.

Not sure on the code coverage here -- it's showing decreases in coverage on files that are not touched in the change... ?

**Comment by Fokko** [comment]
@johnarnold The code coverage is sometimes a bit opaque, since it compares against current master I believe. So if you're behind master, it might not be correct.

**Comment by Fokko** [comment]
Thanks @johnarnold, merging.

**Review by Fokko — APPROVED** [review]
Thanks @johnarnold, merging.

**Pull request closed without merging**
