### PR TITLE
[AIRFLOW-XXX] Change instances "Google cloud storage" to "Google Cloud Storage".

### PR DESCRIPTION
**Pull request by dgorelik**
GCS should be formatted as "Google Cloud Storage", so change instances "Google cloud storage" to "Google Cloud Storage".

Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes: just changing docstring

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
This problem also occurs elsewhere. Can you fix it in the whole project?
```
./airflow/operators/gcs_to_bq.py:    Loads files from Google cloud storage into BigQuery.
./airflow/operators/gcs_to_bq.py:    point the operator to a Google cloud storage object name. The object in
./airflow/operators/gcs_to_bq.py:    Google cloud storage must be a JSON file with the schema fields in it.
./airflow/operators/gcs_to_bq.py:    :param source_objects: List of Google cloud storage URIs to load from. (templated)
./airflow/operators/cassandra_to_gcs.py:data from Cassandra to Google cloud storage in JSON format.
./airflow/operators/cassandra_to_gcs.py:    Copy data from Cassandra to Google cloud storage in JSON format
./airflow/operators/cassandra_to_gcs.py:        to Google cloud storage. A {} should be specified in the filename
./airflow/operators/local_to_gcs.py:        Uploads the file to Google cloud storage
./airflow/operators/mysql_to_gcs.py:    """Copy data from MySQL to Google cloud storage in JSON or CSV format.
./airflow/operators/mysql_to_gcs.py:        JSON/Google cloud storage/BigQuery. Dates are converted to UTC seconds.
./airflow/operators/gcs_to_gcs.py:    :param source_bucket: The source Google cloud storage bucket where the
./airflow/operators/gcs_to_gcs.py:    :param destination_bucket: The destination Google cloud storage bucket
./airflow/operators/gcs_to_gcs.py:        destination Google cloud storage bucket. (templated)
./airflow/operators/sql_to_gcs.py:        Google cloud storage.
./airflow/gcp/sensors/gcs.py:    :param bucket: The Google cloud storage bucket where the object is.
./airflow/gcp/sensors/gcs.py:        connecting to Google cloud storage.
./airflow/gcp/sensors/gcs.py:    :param bucket: The Google cloud storage bucket where the object is.
./airflow/gcp/sensors/gcs.py:        connecting to Google cloud storage.
./airflow/gcp/sensors/gcs.py:    :param bucket: The Google cloud storage bucket where the object is.
./airflow/gcp/sensors/gcs.py:        connecting to Google cloud storage.
./airflow/gcp/sensors/gcs.py:    :param bucket: The Google cloud storage bucket where the objects are.
./airflow/gcp/sensors/gcs.py:        to Google cloud storage.
./airflow/gcp/operators/cloud_storage_transfer_service.py:    :param source_bucket: The source Google cloud storage bucket where the
./airflow/gcp/operators/cloud_storage_transfer_service.py:    :param destination_bucket: The destination Google cloud storage bucket
./airflow/gcp/operators/gcs.py:    :param bucket: The Google cloud storage bucket to find the objects. (templated)
./airflow/gcp/operators/gcs.py:    :param bucket: The Google cloud storage bucket where the object is.
./airflow/gcp/operators/bigquery.py:    point the operator to a Google cloud storage object name. The object in
./airflow/gcp/operators/bigquery.py:    Google cloud storage must be a JSON file with the schema fields in it.
./airflow/gcp/operators/bigquery.py:    point the operator to a Google cloud storage object name. The object in
./airflow/gcp/operators/bigquery.py:    Google cloud storage must be a JSON file with the schema fields in it.
./airflow/gcp/operators/bigquery.py:    :param source_objects: List of Google cloud storage URIs to point
./airflow/gcp/hooks/gcs.py:        :param bucket_name: The Google cloud storage bucket where the object is.
./airflow/gcp/hooks/gcs.py:        :param bucket_name: The Google cloud storage bucket where the object is.
./airflow/gcp/hooks/gcs.py:        :param bucket_name: The Google cloud storage bucket where the blob_name is.
./airflow/gcp/hooks/gcs.py:        :param bucket_name: The Google cloud storage bucket where the blob_name is.
./airflow/gcp/hooks/gcs.py:        :param bucket_name: The Google cloud storage bucket where the blob_name is.
grep: ./logs/scheduler/latest: No such file or directory
grep: ./files/airflow-home/logs/scheduler/latest: No such file or directory
./CHANGELOG.txt:- Don't return error when writing files to Google cloud storage.
```

**Comment by dgorelik** [comment]
@mik-laj Should be done.

**Comment by mik-laj** [comment]
@dgorelik Can you do rebase? Travis is sad, because master branch was broken.

**Comment by mik-laj** [comment]
I did rebase.

**Comment by dgorelik** [comment]
Thansk for wrapping this up!

**Pull request merged**
