### PR TITLE
update git-sync to 4.3.0

### PR DESCRIPTION
**Pull request by JKrehling**
Updating git-sync from 4.1.0 to 4.2.4

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Needs to fix pre-commit

**Comment by potiuk** [comment]
Could you rebase and fix static check @JKrehling ?

**Review by potiuk — APPROVED** [review]

**Review by jedcunningham — CHANGES_REQUESTED** [review]
This needs a newsfragment. Here is an example:

https://github.com/apache/airflow/pull/33748/files#diff-041a58e03ac37cd0e7da8320ff979a1110b8d3347eeb5f1b76aa5c3494c630c9

**Comment by JKrehling** [comment]
4.3.0 released so I will go with that instead and I added the news fragment

**Review by jedcunningham — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by romsharon98 — APPROVED** [review]

**Pull request merged**
