### PR TITLE
Prepare fab ad-hoc release December 2024

### PR DESCRIPTION
**Pull request by eladkal**
Generated with :
`breeze release-management prepare-provider-documentation fab  --base-branch providers-fab/v1-5`

### CODE REVIEW

**Review by hussein-awala — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by shahar1 — APPROVED** [review]

**Review by amoghrajesh — APPROVED** [review]

**Comment by potiuk** [comment]
Do you want me to "forward-port" it to main - or will you do it @eladkal  ?

**Comment by eladkal** [comment]
> Do you want me to "forward-port" it to main - or will you do it @eladkal ?

It's just moving the log entry I can do it but there are troubles with doc build

**Comment by potiuk** [comment]
> It's just moving the log entry I can do it but there are troubles with doc build

There should not be, I think - what troubles?

**Comment by eladkal** [comment]
> > It's just moving the log entry I can do it but there are troubles with doc build
> 
> There should not be, I think - what troubles?

Published traceback on release manager channel.

**Pull request merged**
