### PR TITLE
[AIRFLOW-2899] Hide sensitive data when Exporting Variables

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2899
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Currently, the sensitive variable is hidden from being exposed in the Web UI. However, if the UI is compromised, someone can export variables where all the sensitive variables are exported in plain text format.

image

This will still allow an admin to export all the variables from the CLI. The main intention here would be incase of an exposed Web UI, the sensitive data should still be inaccessible.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @Fokko @feng-tao @bolkedebruin 

https://github.com/apache/incubator-airflow/pull/1530 covered hiding it from the UI but didn't consider variable export.

**Comment by feng-tao** [comment]
@kaxil, it would be good if you could add a test to test the sensitive data export case.

**Comment by kaxil** [comment]
@feng-tao Would you or someone with good Flask experience (e.g. @jgao54 , @Fokko ) be able to help with adding a test for this.

**Comment by Fokko** [comment]
I might even argue that we need to fix this on an API level instead of the view level. In this case the API will just obfuscate the secrets.

**Comment by kaxil** [comment]
@Fokko Fixing this on API level will mean we won't be able to get the variables in plain text through CLI as well.

**Comment by kaxil** [comment]
@ashb Thoughts?

**Comment by ashb** [comment]
Yes. And No?

Yes, because by default it probably shouldn't be possible to get the secrets back out. But the export including sensitive might be useful for backups/provisioning.

The "fuller" solution that would support exporting while keeping then encrypted. That would involve a change of format of export and is probably a bigger chunk of work.

In short: I don't know, sorry.

**Comment by kaxil** [comment]
@ashb No worries. The aim of this PR was to obfuscate sensitive variables from UI export but it would still allow you to download them through the CLI.

**Comment by ron819** [comment]
Why not allow the user to decide per Variable if it's sensitive or not (addition of Boolean column)? Then you won't need to consider the question of what to do... there will be a value defined by the user to simply act accordingly.
Sometimes what you might consider as secret isn't considered as such by the user.

**Comment by kaxil** [comment]
@ron819 Even if a user decides whether a field is sensitive or not, you would still need to add the functionality of obfuscating them in the UI, the scope of this PR is just that. And to your point on letting a user decide whether a given field is secret or not, we are happy for you to implement that functionality and send a PR.

Just for your information, the selection of a Variable to be sensitive was decided in this PR: https://github.com/apache/incubator-airflow/pull/1530

**Comment by ron819** [comment]
@kaxil  No need to get mad it was just a suggestion :)

**Comment by kaxil** [comment]
@ron819 I didn't get mad at all, apologies and sorry if you felt so. I seriously think that it should have been a user's choice to select the sensitive variables.

**Pull request closed without merging**
