### PR TITLE
Replace print by logger.info/error in db util

### PR DESCRIPTION
**Pull request by hussein-awala**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by potiuk** [comment]
I **THINK** the prints here were intentional. The problem is that logs get additional extra metadata and here we wanted to really communicate with the user.

**Comment by potiuk** [comment]
This is inside: `if sys.stdout.isatty() and verb:`

**Comment by hussein-awala** [comment]
> I THINK the prints here were intentional

I'll recheck it

**Comment by hussein-awala** [comment]
@potiuk wdyt of #33862?

**Comment by potiuk** [comment]
> @potiuk wdyt of #33862?

Could be the same :)

**Pull request closed without merging**
