### PR TITLE
AIRFLOW-3014 Increase possible length of passwords in connection table

### PR DESCRIPTION
**Pull request by bravefoot**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3014
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [X ] Here are some details about my PR, including screenshots of any UI changes:
Adds a migration script to increase the size of the password column in the connection table

### Tests

- [X ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I did not see unit tests around migration scripts. If I was mistaken, I'd be happy to add a test.
### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bravefoot** [comment]
Sqlite does not allow the modification of columns, so the build for them will fail. Is there a common workaround for this?

**Comment by ashb** [comment]
It looks like SQLite doesn't actually enforce the max length on the columns:

```
sqlite> insert into connection (password) values('aaaaaaaaaaaaaaaaaaaaaaaaa...a');
sqlite> select id, length(password) from connection;
1|1
2|1900
```

So maybe the fix is to simply not run this migration on sqlite engines? I'm some what surprised that the tests we added in #3516 didn't catch this (as the model already has the length set at 5000 but we were missing a migration to change it. (Which is nothing to do with this PR).

**Comment by jomv1** [comment]
I'm facing same problem. This PR could have solve it.
Shouldn't it be easy to skip the migration from the SQLITE and merge this?

**Comment by ashb** [comment]
@jomv1 A PR would be welcome if this is still a  problem on  latest versions of Airflow

**Pull request closed without merging**
