### PR TITLE
Support pass command as args in k8s executor

### PR DESCRIPTION
**Pull request by pingzh**
The current implementation overrides the image's entrypoint, which is less ideal. Users may want to use their own entrypoint to do additional setup and clean up, before and after the airflow tasks.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by pingzh** [comment]
@dimberman could you please take a look? thanks

**Comment by dimberman** [comment]
Hi ping, going forward we're actually going to be deleting all of the k8sexecutor airflow.cfg configs involved in pod creation. This is because as of 1.10.12 we allow users to generate pod_templates using yaml. Please see the PR here for simplification of k8sexecutor https://github.com/apache/airflow/pull/10393

**Comment by pingzh** [comment]
> Hi ping, going forward we're actually going to be deleting all of the k8sexecutor airflow.cfg configs involved in pod creation. This is because as of 1.10.12 we allow users to generate pod_templates using yaml. Please see the PR here for simplification of k8sexecutor #10393

Thanks, will keep this in mind.

**Comment by dszakallas** [comment]
@dimberman the command and args are dynamic, i.e. they could be different for each run, so the only way to customize this behavior from a pod template is to interpolate these parameters using a jinja template during runtime. I don't know if it is possible currently, but would cover more use cases more cleanly. E.g. a common use case not covered by this when the entrypoint relays the args to `airflow` but sets up some environment variables first, in which case only airflow's arguments should be passed to the script.
If we had a two separate variables for the command (`['airflow']`) and args (`['run', 'tasks', 'abc', '...']`)  interpolated into the pod template, we could support that behavior too, by using a static command in the pod spec, and using the dynamic args.

**Pull request closed without merging**
