### PR TITLE
Fixed Issue #45116

### LINKED ISSUE #45116: Logging out from Web UI still raises Airflow 405 error
### Apache Airflow version

2.10.4

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

I still have the same error as described in #40470 even though i'm running 2.10.4 with apache-airflow-providers-fab             1.4.0. It's probably linked to some package - but i did ran
`pip install "apache-airflow==2.10.4" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.10.4/constraints-3.8.txt"`

### What you think should happen instead?

logout process needs to complete correctly

### How to reproduce

connected as admin and try to logout

### Operating System

Fedora 8.3

### Versions of Apache Airflow Providers

apache-airflow-providers-fab==1.4.0

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Spaarsh**
closes: #45116
related: #40470

The fix adds a "Logout" button to the navbar_menu and uses supporting JavaScript to send a POST request to the ```/logout``` endpoint. Additionally, it also fixes a duplicate text of "login" associated with the login button.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Spaarsh** [comment]
This how the logout button shall look in the GUI:
### GUI with the new Logout button:
<video src="https://github.com/user-attachments/assets/049f129a-dbc1-4abb-96f7-df7810d6962e" width="320" height="240" controls></video>

### GUI after removing additional "login" text:
<video src="https://github.com/user-attachments/assets/1c149afe-c0d3-4630-b30c-842d1d24881a" width="320" height="240" controls></video>

**Comment by Spaarsh** [comment]
The current fix is not a clean one. I did go through the code to make a cleaner fix which would involve including the "logout" in one of the functions in 
[base_auth_manager.py](https://github.com/apache/airflow/blob/7f2b8ef5acf95b7fb8faa38a10caf94c043f5019/airflow/auth/managers/base_auth_manager.py#L398C1-L423C1):
```
    def filter_permitted_menu_items(self, menu_items: list[MenuItem]) -> list[MenuItem]:
        """
        Filter menu items based on user permissions.


        :param menu_items: list of all menu items
        """
        items = filter(
            lambda item: self.security_manager.has_access(ACTION_CAN_ACCESS_MENU, item.name), menu_items
        )
        accessible_items = []
        for menu_item in items:
            menu_item_copy = MenuItem(
                **{
                    **menu_item.__dict__,
                    "childs": [],
                }
            )
            if menu_item.childs:
                accessible_children = []
                for child in menu_item.childs:
                    if self.security_manager.has_access(ACTION_CAN_ACCESS_MENU, child.name):
                        accessible_children.append(child)
                menu_item_copy.childs = accessible_children
            accessible_items.append(menu_item_copy)
        return accessible_items
```
The reason being that this menu list is called in the [```navbar_menu.html```](https://github.com/apache/airflow/blob/7f2b8ef5acf95b7fb8faa38a10caf94c043f5019/airflow/www/templates/appbuilder/navbar_menu.html#L36C1-L60C13)

Enabling these changes further requires changes in the [security_manager.py](https://github.com/apache/airflow/blob/7f2b8ef5acf95b7fb8faa38a10caf94c043f5019/airflow/www/security_manager.py#L119C4-L140C68). Is this the correct approach? I did attempt to implement these but that just lead to the need for more changes.

Also, I think that the version checking condition in the [override.py](https://github.com/apache/airflow/blob/7f2b8ef5acf95b7fb8faa38a10caf94c043f5019/providers/src/airflow/providers/fab/auth_manager/security_manager/override.py#L135C1-L140C24) can now be removed if it had been implemented solely due to the GET request at /logout endpoint.

**Comment by jscheffl** [comment]
From the screencast I see that you have not properly compiled www-assets before running the UI. This has side effects of missing scripts.

What I do not understand is the fix you are attempting to contribute. There IS already a logout menu entry behind the profile:
image
Why do you plan to add another in this PR?

**Review by shahar1 — COMMENTED** [review]
+1 to Jens' comment - I didn't understand from the original issue that you want to add a new button in addition to the existing one (which Jens captured in the screenshot), but to fix a broken functionality in the existing one.
I've implemented the exact same CSRF protection in https://github.com/apache/airflow/pull/40145, so I might need some more background regarding the problems with it (if you could take a video that demonstrates it - it would be great!).
Apologies for misunderstanding.

**Comment by Spaarsh** [comment]
@jscheffl @shahar1 my sincere apologies for this mishap. I have compiled the www-assets (sorry for this mistake). In my previous comment under the issue, I had presumed that the person who opened the issue tried to go to the /logout/ endpoint in the browser to logout. I should have asked them how exactly was the error occurring. The only instance of 405 error I got was when I tried to enter the /logout/ in the browser. Hence my assumption. 

Again, my apologies for this bad PR. I will make a comment under the issue to understand how to recreate the error. Should I close my PR until then?

**Comment by shahar1** [comment]
> @jscheffl @shahar1 my sincere apologies for this mishap. I have compiled the www-assets (sorry for this mistake). In my previous comment under the issue, I had presumed that the person who opened the issue tried to go to the /logout/ endpoint in the browser to logout. I should have asked them how exactly was the error occurring. The only instance of 405 error I got was when I tried to enter the /logout/ in the browser. Hence my assumption. 
> 
> Again, my apologies for this bad PR. I will make a comment under the issue to understand how to recreate the error. Should I close my PR until then?

Try to take it easy. Nothing bad happened :)
You could close this PR for now - try to figure out if you can reproduce the issue. If you can, you may create a new PR to fix it - otherwise, there's plenty of other issues that you could tackle.

**Review by VVRChilukoori — COMMENTED** [review]
Agree with  shahar and Jen

**Pull request closed without merging**
