### PR TITLE
[AIRFLOW-4528] Cancel DataProc task on timeout

### PR DESCRIPTION
**Pull request by AlexisBRENON**
Make sure you have checked all steps below.

### Jira

- [x] My PR addresses the following Airflow Jira issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4528

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
  - My PR factorize code for most DataProcXXXOperator operators and primarily implements the `on_kill` callback to cancel dataproc launched jobs on timeout.

### Tests

- [x] My PR adds the following unit tests **OR** does not need testing for this extremely good reason:
  - My PR adds the `DataProcJobBaseOperatorTest` to test that the `cancel` method of the DataProc hook is called on timeout.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "How to write a good git commit message":
  i. Subject is separated from body by a blank line
  ii. Subject is limited to 50 characters (not including Jira issue reference)
  iii. Subject does not end with a period
  iv. Subject uses the imperative mood ("add", not "adding")
  v. Body wraps at 72 characters
  vi. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes flake8

### CODE REVIEW

**Comment by OmerJog** [comment]
@AlexisBRENON
There is an error in the test:
```21) ERROR: test_timeout_kills_job 
(tests.contrib.operators.test_dataproc_operator.DataProcJobBaseOperatorTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/contrib/operators/test_dataproc_operator.py line 578 in test_timeout_kills_job
      hook.cancel.assert_called_once()
    /usr/lib/python3.5/unittest/mock.py line 583 in __getattr__
      raise AttributeError(name)
   AttributeError: assert_called_once
```

**Comment by potiuk** [comment]
Yep @AlexisBRENON. @OmerJog is right  - I will take a look after you fix the test :)

**Comment by AlexisBRENON** [comment]
Addressed the error (`assert_called_once` is not available in all Python version, but it is weird as I use the docker image to test locally and it works. Anyway, moved to `assert_called_once_with` which is used in other tests), and clean-up some useless mocks.

**Comment by potiuk** [comment]
@AlexisBRENON  - It's python 3.5 :). It misses assert_called_once https://medium.com/@dirk.avery/python-mockery-across-versions-3a2528b54786 . I will take look later today

**Comment by AlexisBRENON** [comment]
@potiuk Tests passed ! :smiley:

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Nice one!

**Comment by ashb** [comment]
I can't easily pull this PR in to 1.10.4 as it conflicts massively without https://github.com/apache/airflow/pull/5250, but that introduces a breaking change in the parameter naming.

**Comment by kurtqq** [comment]
@ashb May I ask why must we release `1.10.4` and not for example `1.11.0 `?
There has been some other breaking changes that the community can benefit from if released.
If we must wait to 2.0.0 which is scheduled to end of 2019 (?) it means that almost no changes could be release for this operator or any other operator that had breaking change.

**Comment by potiuk** [comment]
Hey @ashb  -> I spent a little time and I think I managed to fix it with a little hack: https://github.com/apache/airflow/commit/652e46062c6df42889bdbdbb3880c4525c98cd15 

I needed it to apply https://github.com/apache/airflow/commit/31c5746798e35dd99a3aa4b03a26f6cfce6c062f on top of it and seems that it works (I will see Travis results)

**Pull request merged**
