### PR TITLE
[AIRFLOW-3034]: Readme updates : Add Slack & Twitter, remove Gitter 

### PR DESCRIPTION
**Pull request by r39132**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3034
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
N/A.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
hey @r39132 , there are some -1 on the vote thread you started. Have we decided the final decision of retiring gitter? If that's the case, the pr lgtm.

**Review by kaxil — APPROVED** [review]
LGTM. @r39132  We might need to have a heruko app or something similar for users to join the Slack Workspace otherwise new users won't be able to join without invitation.

An app like https://github.com/outsideris/slack-invite-automation

**Comment by r39132** [comment]
Hi @feng-tao This PR doesn't retire Gitter, if that is even possible. It just removes it from the Readme. To retire it, we may need Infra support and possibly a second vote. Currently, the slack adoption is 5-10x that of Gitter (`~120 folks on Slack`). 

@kaxil That's a good point. Want to take a stab at it?

**Comment by feng-tao** [comment]
lgtm, thanks @r39132 for the info.

**Comment by kaxil** [comment]
@r39132 : I have deployed the app on Heroku: https://apache-airflow-slack.herokuapp.com/

Can you add this in the Readme? Can you also announce this on mailing-list / twitter?

**Review by tedmiston — COMMENTED** [review]
@r39132 Glad to see this PR.  I was about to send something similar.  Overall I'm in favor.

Given the mailing list response with some resistance to Slack, what if we kept the Gitter link (but not badge) in the readme but marked it as `Chat (alternative)` or (legacy) or something?

Perhaps it's progress towards being all in on Slack.  But there is still some useful info in the Gitter so I can appreciate having the link around for archival purposes.

**Comment by r39132** [comment]
@tedmiston What plan would you recommend for transitioning off Gitter? I can't imagine it would be a good idea to maintain 2 places? Less than one week after creating the slack channel, we have 170+ folks on slack and maybe 10-15 peoples on Gitter. 

Also, this change does not remove gitter.. it just tells newbies to use Slack...existing users of Gitter can continue.

**Comment by ashb** [comment]
Where did you get the 10-15 people on Gitter btw?

screen shot 2018-09-13 at 10 39 16

(I don't know if that is active people, or just people who have ever signed in to Gitter, but Gitter says 2837 people in the airflow channel. There aren't that many active people, certainly)

**Comment by r39132** [comment]
@ashb 3k might be the total. What are the weekly actives? We can keep both channels as long as it makes sense, though I’m always wary of prolonged Roman-riding.

**Comment by ashb** [comment]
Volume is definately dropping off in Gitter (and I'm encouraging/mentioning the slack channel) - I'll stick around in Gitter until it's quiet

**Comment by tedmiston** [comment]
I don't have a specific recommendation for transitioning off Gitter as I'm not very active on Gitter personally.  I like @ashb's suggestion.

**Pull request merged**
