### PR TITLE
[AIRFLOW-2544] Guard against next major release of Celery, Flower

### PR DESCRIPTION
**Pull request by tedmiston**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2544

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR proactively guards against the next major version of Celery (4.2) from being installed automatically until it's been tested.  It is currently in RC but not yet officially released.  I've also added an upper bound on Flower 1.0 similarly.

Related to https://issues.apache.org/jira/browse/AIRFLOW-1967, and created from discussion in https://github.com/apache/incubator-airflow/pull/2806.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

n/a - just a dependency version guard

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

n/a

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by tedmiston** [comment]
@Fokko Here is the PR I proposed yesterday in https://github.com/apache/incubator-airflow/pull/2806#issuecomment-392957311 that covers Celery.  I also added a similar guard for the 1.0 release of Flower as well.  It looks like master was recently changed to `celery>=4.1.1` so I have preserved that.  Let me know if this looks good to you to merge.  Thank you!

**Comment by tedmiston** [comment]
^ Not sure what this Codecov warning is about.  This PR doesn't change code, so I think it's not relevant, but please let me know if action is required.

**Comment by tedmiston** [comment]
Rebased off master to see if it makes a difference.

**Comment by tedmiston** [comment]
@bolkedebruin I noticed you'd done some work around Celery as well.  Do you have any input on this one?

**Comment by Fokko** [comment]
Thanks @tedmiston. Codecov is sometimes a bit off if you're working on an outdated master. Looking good.

**Comment by r39132** [comment]
LGTM

**Pull request closed without merging**
