### PR TITLE
Disallow calling expand with no arguments

### LINKED ISSUE #23435: Empty `expand()` crashes the scheduler
### Apache Airflow version

2.3.0 (latest released)

### What happened

I've found a DAG that will crash the scheduler:

```
@task
    def hello():
        return "hello"

    hello.expand()
```

```
[2022-05-03 03:41:23,779] {scheduler_job.py:753} ERROR - Exception when executing SchedulerJob._run_scheduler_loop                 
Traceback (most recent call last):                                                                                                 
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 736, in _execute                     
    self._run_scheduler_loop()                                                                                                     
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 824, in _run_scheduler_loop          
    num_queued_tis = self._do_scheduling(session)                                                                                  
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 906, in _do_scheduling               
    callback_to_run = self._schedule_dag_run(dag_run, session)                                                                     
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/jobs/scheduler_job.py", line 1148, in _schedule_dag_run           
    schedulable_tis, callback_to_run = dag_run.update_state(session=session, execute_callbacks=False)                              
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper                            
    return func(*args, **kwargs)                                                                                                   
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagrun.py", line 522, in update_state                      
    info = self.task_instance_scheduling_decisions(session)                                                                        
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper                            
    return func(*args, **kwargs)                                                                                                   
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagrun.py", line 661, in task_instance_scheduling_decisions
    session=session,                                                                                                               
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagrun.py", line 714, in _get_ready_tis                    
    expanded_tis, _ = schedulable.task.expand_mapped_task(self.run_id, session=session)                                            
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/mappedoperator.py", line 609, in expand_mapped_task        
    operator.mul, self._resolve_map_lengths(run_id, session=session).values()                                                      
TypeError: reduce() of empty sequence with no initial value                                                                        
```

### What you think should happen instead

A user DAG shouldn't crash the scheduler. This specific case could likely be an ImportError at parse time, but it makes me think we might be missing some exception handling?

### How to reproduce

_No response_

### Operating System

Debian

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by uranusjr**
This makes everything easier.

FIx #23435.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
Looks like we have a problem with this, it produces parse error for the dag below:

```python

from airflow import DAG
from datetime import datetime, timedelta
from airflow.operators.python import PythonOperator


def mynameis(arg):
    print(arg)


with DAG(
    dag_id="my_name_is",
    start_date=datetime(1990, 1, 1),
    schedule_interval=timedelta(days=30 * 365),
) as dag:
    PythonOperator.partial(task_id='myname_is', python_callable=mynameis).expand(op_args=['a', 'b', 'c'])

```

**Comment by jedcunningham** [comment]
Btw, #23434 was merged so the refactor can now be done here.

**Comment by ephraimbuddy** [comment]
My suggestion is to have an initial value for the reduce function. That way, the task with empty expand argument will be assumed to have expanded only 1 time which is the same as one task being run. Here's what I mean:
```diff

diff --git a/airflow/models/mappedoperator.py b/airflow/models/mappedoperator.py
index aa51a7345..f9661d66a 100644
--- a/airflow/models/mappedoperator.py
+++ b/airflow/models/mappedoperator.py
@@ -606,7 +606,7 @@ class MappedOperator(AbstractOperator):
         from airflow.settings import task_instance_mutation_hook
 
         total_length = functools.reduce(
-            operator.mul, self._resolve_map_lengths(run_id, session=session).values()
+            operator.mul, self._resolve_map_lengths(run_id, session=session).values(),1
         )
 
         state: Optional[TaskInstanceState] = None
```

**Comment by ashb** [comment]
@uranusjr Where are we with this PR?

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
