### PR TITLE
[AIRFLOW-1331]Contrib.SparkSubmitOperator should allow --packages parameter

### PR DESCRIPTION
**Pull request by chie8842**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@Fokko can you review?

**Comment by Fokko** [comment]
LGTM

@chie8842 Please squash your commits

**Comment by chie8842** [comment]
@Fokko  Thank you for your review.
I fixed up my commit.
Please check it.

**Comment by Fokko** [comment]
@chie8842 Please review the commit guidelines:

My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "How to write a good git commit message":
- Subject is separated from body by a blank line
- Subject is limited to 50 characters
- Subject does not end with a period
- Subject uses the imperative mood ("add", not "adding")
- Body wraps at 72 characters
- Body explains "what" and "why", not "how"

Your commit should start with `[AIRFLOW-1331]` and it should be a single commit (not two as now).

**Comment by chie8842** [comment]
@Fokko Sorry, I haven't understand your point, cleary 🙇 
I fixed my commit. Please check it again.

**Comment by Fokko** [comment]
Perfect, @bolkedebruin can you merge?

**Pull request closed without merging**
