### PR TITLE
Sync v2-9-stable with v2-9-test to release python client v2.9.3

### PR DESCRIPTION
**Pull request by utkarsharma2**
Cherrypicked missing PRs

### CODE REVIEW

**Review by ephraimbuddy — APPROVED** [review]

**Comment by potiuk** [comment]
Likely https://github.com/apache/airflow/pull/39181 - I think the breeze changes have not been cherry-picked in 2.9 branch for some time but this one should be easily manually applied.

**Comment by utkarsharma2** [comment]
> Likely #39181 - I think the breeze changes have not been cherry-picked in 2.9 branch for some time but this one should be easily manually applied.

Yes, that worked for me. Thanks @potiuk @ephraimbuddy

**Comment by potiuk** [comment]
BTW. The jobs running here will not work - becuase our self-hosted runners stopped working and we have no way to fix it quickly. 

See https://github.com/apache/airflow/issues/40925

I think what you will have to do to fix it is to apply these two that I used to workaround it for now:

* https://github.com/apache/airflow/pull/40913 
* https://github.com/apache/airflow/pull/40921

Not sure if just cherry-picking will work out-of the box but hopefully yes.

**Comment by utkarsharma2** [comment]
> BTW. The jobs running here will not work - becuase our self-hosted runners stopped working and we have no way to fix it quickly.
> 
> See #40925
> 
> I think what you will have to do to fix it is to apply these two that I used to workaround it for now:
> 
>     * [Temporarily switch to public github runners #40913](https://github.com/apache/airflow/pull/40913)
> 
>     * [Temporarily comment-out publishing docs in canary runs #40921](https://github.com/apache/airflow/pull/40921)
> 
> 
> Not sure if just cherry-picking will work out-of the box but hopefully yes.

Thanks @potiuk I'll try cherry-picking, hopefully should work.

**Comment by utkarsharma2** [comment]
@potiuk cerry-picking those change are cause these [test](https://github.com/apache/airflow/actions/runs/10040436757/job/27746540918?pr=40930) to fail are there any other changes that I need to cherry-pick?

**Comment by potiuk** [comment]
No. Likely those are tests that have been changed in the meantime. Basically the change was to force `["ubuntu-22.04"]` where `["self-hosted", "Linux", "X64"]` were before (that was the problem). So simply fixing those tests and replacing "self-hosted" with "ubuntu" will work..

```
ERROR: The key 'runs-on-as-json-default' has unexpected value:
["ubuntu-22.04"]
Expected value:

["self-hosted", "Linux", "X64"]
```

**Comment by potiuk** [comment]
But at least the tests are running now.

**Review by hussein-awala — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
