### PR TITLE
Change table formatting to reduce git diffs in provider READMEs

### PR DESCRIPTION
**Pull request by ashb**
Rather than formatting all the columns, which means that any time a new
longer commit happens _all_ rows in the table get re-formatted, this
keeps things "tight" so that only changed lines are changed.

What do you think @potiuk?

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
(Either way not merging this before beta1)

**Comment by potiuk** [comment]
Those tables are not going to be updated.

Each table is separate from each other (each release has one table per provider) and once we release, each release has its own, separate table with its own length - not impacting other tables. The table might get updated only while you are rebasing the PR before it gets merged (in which case it has no impact whether all rows change or not). Once it is merged, the table is "fixed". 

I personally I prefer the tabulate one as they are easier and nicer to see in text format, I think this is what tabulate nicely solves.

**Comment by ashb** [comment]
Ah if they aren't going to be updated (very often) that's cool.

**Comment by potiuk** [comment]
> Ah if they aren't going to be updated (very often) that's cool.

They won't change once merged :).

**Pull request closed without merging**
