### PR TITLE
[AIRFLOW-2586] Stop getting AIRFLOW_HOME value from config file

### PR DESCRIPTION
**Pull request by KevinYang21**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2586/) issues and references them in the PR title.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Before [this commit](https://github.com/apache/incubator-airflow/commit/a0deb506c070637abc3c426bc7d060e3fe6c854d#diff-30054b6fa334216ba6e66c9f07025cd2R35), subprocess created by bash operator only inherits env vars from the parent process. However, it does not inherit the proper env var from the `airflow worker` process because we had a bug in the [`sudo airflow run --raw` command](https://github.com/apache/incubator-airflow/blob/master/airflow/task/task_runner/base_task_runner.py#L81). The commit was created to address the bug for bash operator. The bug was later on fixed in [this commit](https://github.com/apache/incubator-airflow/commit/354492bc597130f43c76e7bec4bc894fb6deb7fe) and thus bash operator does not need and should not get AIRFLOW_HOME value from the config (otherwise there might be discrepancy between the AIRFLOW_HOME value in the parent process and the child process).

PYTHONPATH on the otherhand, is always passed to the subprocess in the env var maps so we don't need it.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
tests/operators/bash_operators.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by Fokko — CHANGES_REQUESTED** [review]
Ok, I see the issue now. One minor request, would it be possible to extend the test to also cover `AIRFLOW_HOME`? Thanks

**Comment by KevinYang21** [comment]
@Fokko we actually don't export AIRFLOW_HOME value , we get and use its value from [these lines in configurations.py](https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py#L370-L373). That is actually where it make me uncomfortable with the previous behavior--if I have a `~/airflow.cfg` but not exporting AIRFLOW_HOME, and in my `~/airflow.cfg` I accidentally specified `airflow_home` as say `/srv/airflow`, then the subprocess will set AIRFLOW_HOME in configuration.py as `/srv/airflow` and use all the other configs in `/srv/airflow` to set up the Airflow env.

**Comment by jgao54** [comment]
@yrqls21  Good catch on the PR! If I understood correctly, I think what @Fokko meant is if you could simulate the scenario you mentioned above and verify that AIRFLOW_HOME value is propagated from the config file.

**Comment by Fokko** [comment]
Yes, I really appreciatie that you take the time to make this cleaner and simpler :)

**Comment by KevinYang21** [comment]
@jgao54 @Fokko I changed the test var name ti `AIRFLOW_HOME` but I'm still not convinced we should  test the process I mentioned earlier in my comment end to end. How `AIRFLOW_HOME` is set, read and used is actually not the concern of bash operator--testing the process end to end would add dependency on `AIRFLOW_HOME` reading logic in configuration.py to bash operator test( to figure out the precise value to export), which is out of the scope.

**Review by jgao54 — APPROVED** [review]

**Review by Fokko — APPROVED** [review]
LGTM

**Pull request closed without merging**
