### PR TITLE
Allow list item to be rendered instead of showing as JSON

### LINKED ISSUE #13988: List and Dict template fields are rendered as JSON.
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**: Linux

- **Cloud provider or hardware configuration**: amd64
- **OS** (e.g. from /etc/os-release): Centos 7
- **Kernel** (e.g. `uname -a`):
- **Install tools**: pip
- **Others**:

**What happened**:

The field `sql` is rendered as a serialized json `["select 1 from dual", "select 2 from dual"]` instead of a list of syntax-highlighted SQL statements.

image

**What you expected to happen**:

`lists` and `dicts` should be rendered as lists and dicts rather than serialized json unless the `template_field_renderer` is `json`

image

**How to reproduce it**:

```
from airflow import DAG
from airflow.providers.oracle.operators.oracle import OracleOperator

with DAG("demo", default_args={owner='airflow'}, start_date= pendulum.yesterday(), schedule_interval='@daily',) as dag:
    OracleOperator(task_id='single', sql='select 1 from dual')
    OracleOperator(task_id='list', sql=['select 1 from dual', 'select 2 from dual'])
```

**Anything else we need to know**:

Introduced by #11061, .

A quick and dirty work-around:

Edit file [airflow/www/views.py](https://github.com/PolideaInternal/airflow/blob/13ba1ec5494848d4a54b3291bd8db5841bfad72e/airflow/www/views.py#L673)

```
            if renderer in renderers:
-                if isinstance(content, (dict, list)):
+               if isinstance(content, (dict, list)) and renderer is renderers['json']:
                    content = json.dumps(content, sort_keys=True, indent=4)
                html_dict[template_field] = renderers[renderer](content)
```

### PR DESCRIPTION
**Pull request by avkirilishin**
closes: #13988
related: #17321
related: #11177

#17321 broke a list item rendering that was introduced in #14024.
This PR fixes it again and adds some tests to avoid problems in the future.

Impact on operators:
| Operator | Before PR  | After |
| - | ------------- | ------------- |
| VerticaOperator | image| image |
| PythonOperator | image  | image |
| TaskFlow | image  | image |
| SimpleHttpOperator | image  | image |
| BigQueryInsertJobOperator | image  | image |

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
What changed in `BigQueryInsertJobOperator`? The two images look the same to me.

**Comment by avkirilishin** [comment]
> What changed in BigQueryInsertJobOperator? The two images look the same to me.

Yes, they are the same. Nothing changed in BigQueryInsertJobOperator.

**Comment by uranusjr** [comment]
I guess my question is, why are the screenshots attached if nothing changes there?

**Comment by avkirilishin** [comment]
To emphasize that the functionality from #17321 is not broken

**Comment by uranusjr** [comment]
I see, thanks for the clarification.

**Comment by peloyeje** [comment]
Hi, first of all thanks for the fix! What is the expected timeframe to see this one merged?

**Comment by potiuk** [comment]
@peloyeje  I guess it will be there  as soon as the author (@avkirilishin ) rebaases it and fixes the static checks that were failing. Or if the author does not do it, maybe someone (you @peloyeje ) take it over and lead it to completion.

**Comment by peloyeje** [comment]
> @peloyeje I guess it will be there as soon as the author (@avkirilishin ) rebaases it and fixes the static checks that were failing. Or if the author does not do it, maybe someone (you @peloyeje ) take it over and lead it to completion.

All right no problem will do :)

**Comment by peloyeje** [comment]
Hi @potiuk here you go! https://github.com/apache/airflow/pull/22854
Let me know if everything is ok, it's my first time here

**Comment by potiuk** [comment]
Static checks failing - I recommend to rebasem and run pre-commit locally to test it.

**Comment by peloyeje** [comment]
> Static checks failing - I recommend to rebasem and run pre-commit locally to test it.

Hi @potiuk! 
AFAIK I'm not allowed to push into avkirilishin's branch so I opened [this PR](https://github.com/apache/airflow/pull/22854) instead: static tests are supposed to be ok on this (`breeze static-checks --last-commit` pass) + I rebased on latest upstream

**Comment by eladkal** [comment]
Closed in favor of https://github.com/apache/airflow/pull/22854

**Pull request closed without merging**
