### PR TITLE
Apply D105 to the Models Module Partly

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Related Issue 
#37523 
##Checks 
- [x] airflow/models/abstractoperator.py
- [x] airflow/models/baseoperator.py
- [x] airflow/models/connection.py
- [x] airflow/models/dag.py
- [x] airflow/models/dagrun.py
- [x] airflow/models/dagwarning.py
- [x] airflow/models/dataset.py
- [x] airflow/models/expandinput.py
- [x] airflow/models/log.py
- [x] airflow/models/mappedoperator.py

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by dirrao — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by potiuk — CHANGES_REQUESTED** [review]
Actually - I am not sure - do we relly want to keep that rule @Taragolis -to explain all the `dunder` methods ? Is there a way to exclude those from the check? It seems rather unnecessary ?

**Comment by Taragolis** [comment]
> Actually - I am not sure - do we relly want to keep that rule @Taragolis -to explain all the dunder methods ? 

I’m not the correct person who could explain why we select this rule in https://github.com/apache/airflow/issues/10742
Maybe some discussion in dev list exists, or it selected after discussion in slack or just a random selection

I just a person who consolidate this rule in the single task

About my thoughts I add it into another PR: https://github.com/apache/airflow/pull/37602#issuecomment-2001951402 tl;dr In some places it might be useful in the other it useless/redundant and might confuse

**Comment by potiuk** [comment]
I started thread at the devlist.

**Comment by potiuk** [comment]
As discussed in https://github.com/apache/airflow/pull/38452 - we remove the D105 rule from our checks.

**Pull request closed without merging**
