### PR TITLE
[AIRFLOW-214] Fix occasion of detached taskinstance

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- AIRFLOW-214

For some reason occasionely taskinstances could become
detached from the database session. Now it uses a fresh session
to ensure the taskinstances stay attached.

### CODE REVIEW

**Comment by criccomini** [comment]
Is there a JIRA for this?

**Comment by criccomini** [comment]
Assuming this has something to do with parts of process_dags being dropped out of the transaction session?

**Comment by bolkedebruin** [comment]
Yes. Need to create Jira for it.

**Comment by criccomini** [comment]
According to the JIRA, it's unclear why this is happening. Is this PR a guess? :)

**Comment by bolkedebruin** [comment]
The PR works, that is for sure. I do not understand why the task can get detached in the first place. Session should be consistent and it happens _right_ after dagrun.get_task_instances. It does not happen every time but I could replicate it with `example_skip_dag`, but couldnt fix it by keeping the current session.

**Comment by criccomini** [comment]
LGTM

Saw this in the test failures: 

```
======================================================================
FAIL: Test that the scheduler handles queued tasks correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/tests/jobs.py", line 306, in test_scheduler_pooled_tasks
    self.assertEqual(ti.state, State.QUEUED)
AssertionError: u'scheduled' != u'queued'
```

But this is related to a separate PR that @jlowin and I are on, I believe.

**Comment by jlowin** [comment]
+1

**Pull request merged**
