### PR TITLE
[AIRFLOW-4197] Remove Python2 CI jobs

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4197
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Removed the Python 2 CI tasks.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by mik-laj** [comment]
What do you think about adding support for Python 3.6?  I personally have concerns between testing only on one version of Python. This can cause a compatibility problem. 

@potiuk You have extensive experience with incompatibility problems between these two versions. Can you tell us more? 

My comment should not be treated as opposed to this change. The new version of Python can be introduced in a separate PR.

**Comment by Fokko** [comment]
Since Cloud composer is running 3.6 as well, I think it is good to add it here as well. I haven't seen much stuff that runs on 3.5 and doesn't run on 3.6 though.

**Comment by BasPH** [comment]
Agreed. Ideally I would test all supported Python versions (3.5, 3.6, 3.7), but not sure if that's desirable given the fact it takes forever to complete.

**Comment by potiuk** [comment]
In the past I had quite a few things that did not work on 3.5 while they were working on 3.6. But we might be surprised by some incompatibilities. I'd say if we say we support 3.5, 3.6, 3.7 we should run tests on all of them. Maybe we should drop 3.5 compatibility officially ;) ? 

Here are some examples of nasty incompatibilities I encountered while working on Airflow:

* There is different sorting order of dictionary keys (https://stackoverflow.com/a/40007169/516701) (it's an implementation detail in 3.6 but as of 3.7 you can start relying on it. ). I saw code that implicitly relied on maintaining inserting order - which would fail on 3.5, while it would work differently on 3.6 and 3.7. So I think 3.5 is a must. I caught it during code rewiew luckily, and we added unit test for it. 

* 3.7 has new reserved words (async/await) which is all too easy to be used as variable name. It's been a problem in the past in airflow, and might went'= unnoticed if we do not run 3.7 tests.

* I had a code (related to json.decoding() of subprocess command output) that worked on 2.7 AND 3.6 but did not work on 3.5 (!!!!). It was a bit surprising but you can find details in https://github.com/apache/airflow/pull/4254/commits/22bea285c2cace4a60b96fca4ad077cc91124907

**Comment by BasPH** [comment]
Those are great examples and very valid points @potiuk, and I think everybody is in favour of testing on all Python versions (except Travis maybe😅). Let's create a separate PR for adding new test environments, to keep PRs focussed on one single change.

**Comment by potiuk** [comment]
@BasPH  I think hopefully we might switch to runnnig the multi-staging/multi-layeref image after voting (I hope in-favour). See: https://github.com/apache/airflow/pull/4938. I have 2.7/3.5/3.6 configurations already. Not sure if we want to wait with modifying the current Travis configuration - I think the new image PRs are fairly close to being ready.

**Review by Fokko — APPROVED** [review]
Thanks @BasPH for fixing this.

@potiuk I don't see any harm in merging this. If the vote goes well, we can move to the Docker images after the `[VOTE]`.

**Pull request merged**
