### PR TITLE
[AIRFLOW-794] Consistent access to DAGS_FOLDER and SQL_ALCHEMY_CONN

### PR DESCRIPTION
**Pull request by gsakkis**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-794

Testing Done:
- https://travis-ci.org/Avocarrot/incubator-airflow/builds/194228537

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you please fix your commit messages per guidelines (including PR title)? Ie. prepend commit messages with Jira Issue. Thanks!

**Comment by gsakkis** [comment]
Any news on merging this?

**Comment by bolkedebruin** [comment]
Im holding off for 1.8.0, but it is fine for 1.8.1

**Comment by jlowin** [comment]
@bolkedebruin @gsakkis this PR is causing test failures -- #2018 added code to `tests/jobs.py` that depends on the `from airflow import models` line that this PR removes. Now all tests are failing with a "NameError: global name 'models' is not defined" message.

It looks like the local branch unit tests ran fine when the PR was submitted, but then #2018 was merged a few days ago. Not sure why travis didn't run here though it probably wouldn't have caught the issue unless the PR was rebased on to master prior to merge. 

I will submit a PR to fix it asap.

**Comment by bolkedebruin** [comment]
@jlowin thanks!

**Pull request closed without merging**
