### PR TITLE
Add new "with-triggerer" option to Breeze CLI

### PR DESCRIPTION
**Pull request by rohan472000**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
Can you please modify the PR title and amend commit message with a meaning full message the explains the change?

**Comment by potiuk** [comment]
It's quite not what the issue was about.


You do not need to add new "command" - you need to add new "--flags" to existing breeze `--shell` and `--start-airflow` commands.

See for example the change of @utkarsharma2  https://github.com/apache/airflow/pull/31861 and https://github.com/apache/airflow/pull/30644

**Comment by rohan472000** [comment]
> It's quite not what the issue was about.
> 
> You do not need to add new "command" - you need to add new "--flags" to existing breeze `--shell` and `--start-airflow` commands.

can you suggest any as I cant think of any short and suitable PR title?

**Comment by vincbeck** [comment]
> > It's quite not what the issue was about.
> > You do not need to add new "command" - you need to add new "--flags" to existing breeze `--shell` and `--start-airflow` commands.
> 
> can you suggest any as I cant think of any short and suitable PR title?

"Add new "with-triggerer" option to Breeze CLI" would be a better candidate? `Update breeze.py` does not say much about what you are trying to achieve

**Comment by utkarsharma2** [comment]
@rohan472000 Could you please add the link to the ticket in the PR description? It gives us more context for the PR and helps in the review process :)

Also, you can reach out if you have doubts, in the [#development](https://apache-airflow.slack.com/archives/CCPRP7943) channel.

**Comment by rohan472000** [comment]
> @rohan472000 Could you please add the link to the ticket in the PR description? It gives us more context for the PR and helps in the review process :)
> 
> Also, you can reach out if you have doubts, in the [#development](https://apache-airflow.slack.com/archives/CCPRP7943) channel.

I have given in PR description, plz see once.

**Comment by potiuk** [comment]
I thought I already commented on it (but maybe i have not submitted it). I believe this is not the way it should be done. You do not need new command for that. You need a flag (or maybe even that should be the default) that when start-airflow command is run, the triggerer is not started automatically alongside scheduler/webserver. Possibly that should just be `--no-triggerer` flag. I think having a separate triggerer command in breeze does not have a use case. 

But maybe I missed some case here. What do you want to achieve by this PR?

**Comment by rohan472000** [comment]
@potiuk , I understand your point about not needing a separate command for the triggerer. The goal of my code was to provide a way to start a triggerer process from the command line when running system tests with deferrable operators.

However, I see your point about keeping the commands more streamlined. Instead of introducing a new command, I can modify the existing breeze commands (--shell and --start-airflow) by adding a flag, such as --no-triggerer, to control the automatic start of the triggerer alongside the scheduler and webserver.

This way, users can decide whether they want the triggerer to start automatically or not when using the breeze commands. I believe this approach would provide the desired flexibility without adding unnecessary complexity.

Please let me know your thoughts on this approach.

**Comment by potiuk** [comment]
I think starting triggerer in docker makes little sense as "standalone" command. 

What you really want to run Triggerer when you alraedy enter breeze. Yes  "shell" command is fine also "testing". This is what the original issue (https://github.com/apache/airflow/issues/31826) we discussed with @vandonr-amz was about. So I think this is what you want to implement really - we already have a number of flags and they were even nicely groupped recently for those commands - see the screenshot here https://github.com/apache/airflow/pull/31879#issuecomment-1589853973

**Comment by rohan472000** [comment]
To implement this, I will modify the `shell` and `testing` commands in the `breeze` script to include the `--with-triggerer` flag. When this flag is provided, the triggerer process will be started within the context of the respective `breeze` command. This will ensure that the triggerer runs when a user enters the `breeze` environment.

**Comment by rohan472000** [comment]
> @rohan472000 Could you please add the link to the ticket in the PR description? It gives us more context for the PR and helps in the review process :)
> 
> Also, you can reach out if you have doubts, in the [#development](https://apache-airflow.slack.com/archives/CCPRP7943) channel.

@utkarsharma2 , can u send me invitation to join slack, as I'm not able to join through link given in community.

**Comment by potiuk** [comment]
> @utkarsharma2 , can u send me invitation to join slack, as I'm not able to join through link given in community.

Are you saying that https://apache-airflow-slack.herokuapp.com/ - does not work? this is the only way to get you signed up . Did you try with different address/checked spam etc. ? other people have no problem with joining this way so I find it a bit surprising. Please try again with different emeil addresses and make sure you check your spam etc.

**Comment by rohan472000** [comment]
Oh yes..It was in the promotions section of gmail.

**Comment by utkarsharma2** [comment]
@rohan472000 Based on a cursory look at the code, I would approach the issue 
1. We need to add the `--with-triggerer` option for the command `tests` for which the code resides here -
  https://github.com/apache/airflow/blob/df4c8837d022e66921bc0cf33f3249b235de6fdd/dev/breeze/src/airflow_breeze/commands/testing_commands.py#L384
2. Also you would want to add this new option in the config here -
https://github.com/apache/airflow/blob/df4c8837d022e66921bc0cf33f3249b235de6fdd/dev/breeze/src/airflow_breeze/commands/testing_commands_config.py#L60
3. Now that we can get the option from the user, we need to start the trigger based on this parameter. Now if we look at the code of the command, all that is happening is that we are calling the docker-compose and we do pass multiple files which are selected conditionally based on user-passed options and they are listed below - 
https://github.com/apache/airflow/tree/main/scripts/ci/docker-compose
However, I suspect you need to explore this file to start the trigger. In `start-airflow` we do start all the airflow components in the container itself. - https://github.com/apache/airflow/blob/main/scripts/in_container/run_ci_tests.sh

**Comment by potiuk** [comment]
> However, I suspect you need to explore this file to start the trigger. In start-airflow we do start all the airflow components in the container itself. - https://github.com/apache/airflow/blob/main/scripts/in_container/run_ci_tests.sh

The easiest way is to pass WITH_TRIGGERER environment variable and base the decision whether to start triggerer in the `entrypoint_ci.sh` - this is how similar checks are done for other cases (for example when we run tests we pass `TEST_TYPE` as env variable and based on that we decide what to do.

The `entrypoint_ci.sh` is the place where we keep all the logic of deciding what to do when you enter the image (BTW. This could be a nice opportunity to make it more structured - possibly we could extract separate "branches" of the logic as bash functions, and have a single simple "main" section where we could run the logic and decide what to do.

I know it's bash. We could also attempt to rewrite entrypoint_ci.sh in Python if that's too much to ask, but then it would add the overhead of always running an extra Python interpreter when you enter the image.

**Pull request closed without merging**
