### PR TITLE
[AIRFLOW-2691] Makes Airflow's JS code (and dependencies) manageable via npm and web…  …pack

### PR DESCRIPTION
**Pull request by verdan**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2691) issues and references them in the PR title. 

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
In an effort to simplify the JS dependencies of Airflow, it introduces the `npm` and `webpack` for the package management. For now, it only implements this in the www_rbac version of the web server. 
The problem with the frontend (js) code of Airflow is that most of the custom JS is written in the html files, using the Flask's (Jinja) variables in that JS. The next step of this effort would be to extract that custom .js code in separate JS files, and use the dependencies in those files using `require` or `import`. (At the moment, I'm simply using the CopyWebPackPlugin to copy the required dependencies for use)
There are also some dependencies which are directly modified in the codebase. I couldn't found the npm versions of those libraries. (**dagre-d3.js** and **gantt-chart-d3v2.js**). Apparently dagre-d3.js that we are using is one of the gist, while the gantt-chart-d3v2 has been modified according to Airflow's requirements. 

Next Steps: 
- Extract custom JS from html files, and put them in separate JS files. 
- Introduce eslint, and test cases for JS code. 

_NOTE: This webpack/npm setup is pretty much same as Apache's Superset._ 

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@verdan Nice :). But can you please test in your private repo with Travis? We have been asked by Apache Infra to lower the load.

**Comment by verdan** [comment]
Oops! sure thing. Closing this for now, will open the PR again once build passes.

**Comment by r39132** [comment]
I believe this was never merged, except via another PR https://github.com/apache/incubator-airflow/pull/3572

@verdan https://issues.apache.org/jira/browse/AIRFLOW-2691 links to both this and the other PR. Can you please clean up the JIRA to point to the PR that was merged?

**Comment by verdan** [comment]
@r39132 this one was closed in favor of the #3572 
I've fixed the Jira issue and unlink this PR.

**Pull request closed without merging**
