### PR TITLE
[AIRFLOW-4417] Add AWS IAM authenication for PostgresHook

### PR DESCRIPTION
**Pull request by andrewhharmon**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-4417

### Description

- [x] Enhance the existing PostgresHook to allow for IAM authentication for RDS Postgres and Redshift.

### Tests

- [x] My PR adds the following unit tests
  - test_get_conn()
  - test_get_conn_rds_iam_postgres()
  - test_get_conn_rds_iam_redshift

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Nice

**Comment by mik-laj** [comment]
Can you also update the docs file?
https://github.com/apache/airflow/blob/master/docs/howto/connection/postgres.rst

**Comment by andrewhharmon** [comment]
@mik-laj whats the best way to do that? will i just need to create a new PR? Can it reference the same JIRA?

**Comment by mik-laj** [comment]
@mik-laj You do not need to refer to the Jira ticket. Changes to the documentation can be made using `[AIRFLOW-XXX]`. If you want to make a change then you need to create a new PR, because it has already been closed.

**Pull request merged**
