### PR TITLE
[AIRFLOW-4265] Lineage backend did not work normally

### PR DESCRIPTION
**Pull request by bryanyang0528**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4265
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by bryanyang0528** [comment]
import_string will fail if backend = `airflow.lineage.backend.atlas`

```
>>> from airflow.utils.module_loading import import_string
/airflow/airflow/configuration.py:557: DeprecationWarning: Specifying airflow_home in the config file is deprecated. As you have left it at the default value you should remove the setting from your airflow.cfg and suffer no change in behaviour.
  category=DeprecationWarning,
>>> backend = import_string('airflow.lineage.backend.atlas')
Traceback (most recent call last):
  File "/airflow/airflow/utils/module_loading.py", line 36, in import_string
    return getattr(module, class_name)
AttributeError: module 'airflow.lineage.backend' has no attribute 'atlas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/airflow/airflow/utils/module_loading.py", line 39, in import_string
    module_path, class_name)
ImportError: Module "airflow.lineage.backend" does not define a "atlas" attribute/class
>>>
```

if backend = `airflow.lineage.backend.atlas.AtlasBackend`, it passed import_string, but backend is a class, can not call send_message directly.
```
>>> backend = import_string('airflow.lineage.backend.atlas.AtlasBackend')
>>> backend
<class 'airflow.lineage.backend.atlas.AtlasBackend'>
>>> backend.send_lineage(operator='', inlets='', outlets='', context='')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: send_lineage() missing 1 required positional argument: 'self'
>>>
```

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
lgtm

**Comment by bryanyang0528** [comment]
@feng-tao  thx!

**Comment by Fokko** [comment]
@NielsZeilemaker PTAL

**Comment by NielsZeilemaker** [comment]
@Fokko @bryanyang0528 the interface/super class of the AtlasBackend is still defining `send_lineage` as a class method, and not as a static one.

I think it's better to keep it a class method, but to instantiate the backend here:
https://github.com/bryanyang0528/airflow/blob/d87fb873cdc27350324fd814bb97488dba1f126b/airflow/lineage/__init__.py#L77

**Comment by bryanyang0528** [comment]
@NielsZeilemaker  OK. I'll create another PR for this. Thx

**Comment by bryanyang0528** [comment]
@NielsZeilemaker 
Could I initiate the backend in the `_get_backend()` function and return a backend instance?
https://github.com/bryanyang0528/airflow/blob/d87fb873cdc27350324fd814bb97488dba1f126b/airflow/lineage/__init__.py#L45

Or turn the interface/super class of the AtlasBackend in a staticmethod? Because `send_lineage` didn't use `self` as a parameter and refer to any resource in the class.

@feng-tao Do you have any opinion or suggestion?

**Comment by NielsZeilemaker** [comment]
For me either is fine, @bolkedebruin do you have a preference as you initially implemented it?

**Pull request merged**
