### PR TITLE
[AIRFLOW-XXX] Fix existing flake8 errors

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Fix flake8 error from master introduced in https://github.com/apache/airflow/pull/4418/files

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @kaxil

**Comment by feng-tao** [comment]
Flake8 is fixed now. Will merge this pr.

**Comment by yohei1126** [comment]
@feng-tao your build failed. Is this your test? please check https://travis-ci.org/apache/airflow/jobs/476146347#L4902
```
======================================================================
42) FAIL: test_trigger_dag_button (tests.www_rbac.test_views.TestTriggerDag)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/www_rbac/test_views.py line 1476 in test_trigger_dag_button
      self.assertIsNotNone(run)
   AssertionError: unexpectedly None
```

**Comment by feng-tao** [comment]
@yohei1126 , not sure which one you are looking at, but the master CI passes(https://travis-ci.org/apache/airflow/builds/476197675). 

The test failure comes from https://github.com/apache/airflow/pull/4407 which I have discussed in the pr as well as the mailing list.

**Comment by feng-tao** [comment]
@yohei1126 , I think this test is pretty flaky.

**Pull request merged**
