### PR TITLE
Optimize 2.3.0 pre-upgrade check queries

### PR DESCRIPTION
**Pull request by dstandish**
We have to check for rows that are missing either corresponding TI or DR and move them out of table before adding FKs.  We were doing correlation in the JOIN condition but it appears postgres does *not* like this so here we move correlation to WHERE.

The queries in question seek to find rows that are missing either TI or DR.  If a row is returned, it means it should be moved out of the table.  We use the exists logic to do a CTAS for the offending rows.  Then later, if rows are moved out, delete from the object table `using` the `moved` table.

Before query:

```sql
SELECT
    count(*) AS count_1
FROM (
    SELECT
        rendered_task_instance_fields.dag_id AS dag_id,
        rendered_task_instance_fields.task_id AS task_id,
        rendered_task_instance_fields.execution_date AS execution_date,
        rendered_task_instance_fields.rendered_fields AS rendered_fields,
        rendered_task_instance_fields.k8s_pod_yaml AS k8s_pod_yaml
    FROM rendered_task_instance_fields
    WHERE
        NOT (exists(SELECT
                        1
                    FROM task_instance
                    JOIN dag_run ON rendered_task_instance_fields.dag_id = task_instance.dag_id
                                AND dag_run.run_id = task_instance.run_id
                                AND rendered_task_instance_fields.execution_date = dag_run.execution_date
                    WHERE
                        rendered_task_instance_fields.dag_id = task_instance.dag_id
                        AND rendered_task_instance_fields.task_id = task_instance.task_id))
     ) AS anon_1;
```

Fixed: 
```sql
SELECT
    count(*) AS count_1
FROM (
    SELECT
        rendered_task_instance_fields.dag_id AS dag_id,
        rendered_task_instance_fields.task_id AS task_id,
        rendered_task_instance_fields.execution_date AS execution_date,
        rendered_task_instance_fields.rendered_fields AS rendered_fields,
        rendered_task_instance_fields.k8s_pod_yaml AS k8s_pod_yaml
    FROM rendered_task_instance_fields
    WHERE
        NOT (exists(SELECT
                        1
                    FROM task_instance
                    JOIN dag_run
                        ON dag_run.run_id = task_instance.run_id
                                AND dag_run.dag_id = task_instance.dag_id
                    WHERE
                        rendered_task_instance_fields.dag_id = task_instance.dag_id
                        AND rendered_task_instance_fields.task_id = task_instance.task_id
                        AND rendered_task_instance_fields.execution_date = dag_run.execution_date
            ))
     ) AS anon_1
;
```

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Review by ashb — COMMENTED** [review]
What about other DBs? Do we need to only for this for postgres

**Comment by ashb** [comment]
Why do we even need to do such a count query?

**Comment by dstandish** [comment]
> What about other DBs? Do we need to only for this for postgres

i think it's likely that this will be better on all DBs.  we should test but it will take some time.

> Why do we even need to do such a count query?

we use this to determine whether there are rows that need to be moved. if so we do a ctas and move them.

**Comment by uranusjr** [comment]
I’d assume this is at least equally good from the current implementation across all databases. This basically eliminates join that does not need to happen.

**Review by ashb — APPROVED** [review]

**Pull request merged**
