### PR TITLE
Support adding custom TI Deps to help DagRun make more flexible TI scheduling decisions

### PR DESCRIPTION
**Pull request by XD-DENG**
This PR adds the ability to support adding custom TI Deps for more flexible TI scheduling.

It adds one more attributes `TI_SCHEDULE_DECISION` to the class `BaseTIDep`. If a custom TI Dep class is defined with `TI_SCHEDULE_DECISION=True`, this custom TI Dep will be used by the DagRun object to decide if a TI is schedulable (for this purpose, a parameter `ti_schedule_decision` is needed in the `DepContext` class).

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
For visibility this PR is related to dev list discussion[ Idea for Discussion: custom TI dependencies](https://lists.apache.org/thread/0mxyx8kvbl7bvhth099zdrqqcdt0tp25)

@XD-DENG better to add also docs to explain the benefit and how to use this feature (we can also add warnings about performance)

**Comment by XD-DENG** [comment]
Thanks @eladkal . I purposely avoided adding doc for this, per @ashb 's suggestion at the mailing list discussion.

In addition, adding custom Dep class via Plugin (which is already supported earlier) was not documented either. I assume it was by purpose too.

**Comment by ashb** [comment]
From the description though I'm not sure why this is need? Why can't the dep be set directly on the Operator object?

**Comment by XD-DENG** [comment]
@ashb , the use case my team is having in mind is: we would want the DagRun to be scheduled/created as normal, but we would like to add custom logics to control if a TI under this DagRun should start. This is part of our works for "smarter orchestration".

The custom logics can be relevant to resource, job dependency, event dependency, etc.

**Comment by uranusjr** [comment]
A simple example on how this can be used (that cannot be covered otherwise) would be useful.

**Comment by XD-DENG** [comment]
> A simple example on how this can be used (that cannot be covered otherwise) would be useful.

Hi @uranusjr , sure thing, let me try to elaborate a bit more and get your opinions/inputs on this.

In different scenarios, we realize our TIs may have different extra dependencies. For example,
- Scenario 1: The TI may have to use separate hardware resource. It can be external GPU/acceleration hardware, other than CPU/memory resource (this is literally similar to the built-in Dep `PoolSlotsAvailableDep` or `DagTISlotsAvailableDep`).
- Scenario 2: the TI is only supposed to start when an event is identified (this event may be checked via an API, but it's not present as a `Dataset` in Airflow, and adding Operator to describe the dependency here is not desirable)
- Scenario 3: Among all the TIs (they may not belong to the same DAG), we may want them to be executed in certain customized order. By default, Airflow will execute the TIs in a somehow "FIFO" order, OR take the TI `Priority Weight` into consideration. But we are having a bigger idea in mind: based on the TIs' expected duration + the global concurrency we allow + resource availability, we may want to shuffle the execution order of the TIs, in order to achieve the best global efficiency. 

The easiest way to achieve these ideas above, as far as my team can see, is to ensure we can add our custom TI Deps into the DagRun's TI scheduling decision making process. 

I would love to hear how you think of this, or if you have any good alternative solution to share. Many thanks!

**Comment by potiuk** [comment]
Agree with TP that if we were to merge this one, we will need quite a bit more:

* documentation with some examples
* general use cases where it would be available
* some performance considerations (i.e. what those who create the custom deps should be aware of when writing their own deps
* dos and don'ts 
* possibly some way of detecting when someone is doing bad things there (not sure how it should look like).

The big difference vs. what we have now with "built-in" deps, is that scheduler gives control to "user" code in a very, very "hot area" in the code. Unlike most of the other code we allow our users to configure in Airflow, this one wlll have a crucial and very serious impact on the scheduling performance.

**Comment by uranusjr** [comment]
The scenarios do make sense to me (although No. 2 is a bit weak; we should probably instead improve Dataset and Triggerer to cover the use case instead). But in all scenarios we’d likely need a bit more than just user-provided deps, so it’s clear there’s a bigger picture behind the change. I would suggest communicate the end target directly first in a full document (either AIP or somewhere discussions can be gathered), that custom deps are a solution to.

**Pull request closed without merging**
