### PR TITLE
[FEATURE] update K8S-KIND to 0.12.0

### PR DESCRIPTION
**Pull request by raphaelauv**
using the default K8S image versions of the KIND release

https://github.com/kubernetes-sigs/kind/releases/tag/v0.12.0

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
One test failed for K8S. let's see if it was outlier

**Review by kaxil — APPROVED** [review]
Thanks @raphaelauv

**Comment by potiuk** [comment]
For some reason it did not run all tests (rebasing and running tests again).

**Comment by potiuk** [comment]
Right. Seems we will have to do it again:

image

**Comment by potiuk** [comment]
And again :)

**Comment by raphaelauv** [comment]
@potiuk it's all green

**Comment by kaxil** [comment]
Merged, thanks for your contribution @raphaelauv

**Comment by potiuk** [comment]
Cool!

**Pull request merged**
