### PR TITLE
Send custom message with email alerts.

### PR DESCRIPTION
**Pull request by akuhn**
Added an option to send custom email message. This can be used to provide more context to the receivers of these emails, eg by giving them actionable instructions are by linking them to a help center page.

Also, removed unused parameter.

Test plan
- Couldn't get my local changes to run (it would always run the pip-installed airflow instead) tested my changes by copypasting into ipython instead.

### CODE REVIEW

**Comment by mistercrunch** [comment]
`email_message` could use a more clear name like `failure_email_preamble` or something like that, and the field should be documented in BaseOperator's docstring, specifying that it will be added before the body of the classic email and that it support html syntax.

**Comment by mistercrunch** [comment]
Totally useful hook BTW!

**Comment by martingrayson** [comment]
How do you guys use airflow internally? Is all of your alerting email based?

I like the concept of generalising alerts to be less email specific and more just "notifications". That way users could plug in different modules to alert them of job failure/success and trigger external systems/monitoring tools. One such case would be SNS alerting to push job success messages to topic rather than specifically use email.

**Comment by mistercrunch** [comment]
We use PagerDuty to bubble up alerts. PagerDuty can receive an email and broadcasts alerts using intricate rules around who's on call, their preferred method of contact (SMS, email addresses, Slack, PagerDuty phone app...), groups, schedules, ...

We also have StatsD setup on some of the job events (see `airflow/jobs.py`) and something called Datadog that integrates with StatsD and can alert us if the scheduler stops looping, or if no jobs are started or succeed for over a half hour. StatsD / Datadog is also how we monitor the health of the Airflow machines (memory, cpu, disk space, ...).

**Comment by mistercrunch** [comment]
Old, closing for now

**Pull request closed without merging**
