### PR TITLE
[AIRFLOW-3100][AIRFLOW-3101] Improve docker compose local testing

### PR DESCRIPTION
**Pull request by holdenk**
Make sure you have checked _all_ steps below.

### Jira

- [ X ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

Update the contributing guide for folks who want to run docker compose for a single test (e.g. debugging while developing), clarify tox install requirements (including in image bake script for later and for now updating contributing guide until a new image can be rolled), fix path for users who launch docker-compose while not running as a user named airflow.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This is for improved local testing, existing CI tests should catch any breaking changes.

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

Updates contributing docs.

### Code Quality

- [ X ] Passes ` git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by holdenk** [comment]
cc @gerardo since you did the original docker-compose work. I ran into some issues trying to use it locally and I think this could be a fix, but I'm open very much open to suggestions :)

**Comment by Fokko** [comment]
Thanks @holdenk 

The community is working hard to get the tests working with Docker. Thanks for chipping in. Please keep in mind that the Docker CI image is hosted here: https://github.com/apache/incubator-airflow-ci

**Comment by holdenk** [comment]
Yeah, so I'm a little confused with the docker image split between the 2 repos, but I'll make a PR to that one with the changes too. Is there a plan to keep them in sync or is their a difference in intention between these two.

**Comment by odracci** [comment]
@holdenk
`scripts/ci/kubernetes/docker/Dockerfile` is the image used to run airflow on Kubernetes and it should not contain any dev / testing tool IMO.

FYI `pip` is installed in `scripts/ci/run-ci.sh`:
https://github.com/apache/incubator-airflow/blob/19515e816785a6be828ec0191b9a7d83c9648110/scripts/ci/run-ci.sh#L29-L36

One option would be to install `tox` in https://github.com/apache/incubator-airflow-ci

**Comment by holdenk** [comment]
The problem with installing it in the `run-ci.sh` command is if folks want to use docker compose on their own env they're missing some of the components.

**Comment by holdenk** [comment]
cc @Fokko

**Comment by kaxil** [comment]
Thanks @holdenk

**Comment by Fokko** [comment]
Thanks @holdenk, I was on holiday ;)

**Pull request merged**
