### PR TITLE
Use `uv` as packaging tool used in CI builds

### PR DESCRIPTION
**Pull request by potiuk**
The `uv` tool released in Feb 2024 by ruff creators provides a way faster drop-in replacement to `pip` and we are using it now in our CI, when it can bring significant speed improvements (and soon possibly more features).

This PR replaces `pip install` and `pip uninstall` with equivalent `uv pip install` and `uv pip uninstall` commands, controlled by a single `AIRFLOW_USE_UV` ARG. In CI images it is set to "true" so CI images are prepared using UV, but PROD images (which are also used during CI tests) are built using pip. This way we can get both - stability and compliance for user-facing `pip` installation and speed and new features coming from `uv`.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — APPROVED** [review]
Excited 😄

Looks good, I hope the CI will pass

**Comment by potiuk** [comment]
> Looks good, I hope the CI will pass

Not yet (expected) - but it's close :).

**Comment by potiuk** [comment]
And the numbers are REALLY REALLY good - see https://lists.apache.org/thread/t7pd78ktcs2s4b8mv3trwb7bdyjthcpz

**Review by dirrao — APPROVED** [review]
Looks Great.

**Review by enchant3dmango — APPROVED** [review]

**Comment by potiuk** [comment]
I need to close it and re-open it in `apache` repo to test canary runs now

**Comment by potiuk** [comment]
Reopened it as https://github.com/apache/airflow/pull/37692

**Pull request closed without merging**
