### PR TITLE
Fix #14417 : Failing to submit Druid ingestion task

### LINKED ISSUE #14417: DruidOperator failing to submit ingestion tasks : Getting 500 error code from Druid
Issue : When trying to submit an ingestion task using DruidOperator, getting 500 error code in response from Druid. And can see no task submitted in Druid console.
In Airflow 1.10.x, everything is working fine. But when upgraded to 2.0.1, it is failing to submit the task. There is absolutely no change in the code/files except the import statements.

Resolution : I compared DruidOperator code for both Airflow 1.10.x & 2.0.1 and found one line causing the issue.
In Airflow 2.0.x, before submitting the indexing job json string is converted to python object. But it should be json string only.
In Airflow 1.10.x there is no conversion happening and hence it is working fine. (Please see below code snippets.)

I have already tried this change in my setup and re-ran the ingestion tasks. It is all working fine.

~~hook.submit_indexing_job(json.loads(self.json_index_file))~~
**hook.submit_indexing_job(self.json_index_file)**

Airflow 1.10.x - airflow/contrib/operators/druid_operator.py
```
def execute(self, context):
    hook = DruidHook(
        druid_ingest_conn_id=self.conn_id,
        max_ingestion_time=self.max_ingestion_time
    )
    self.log.info("Submitting %s", self.index_spec_str)
    hook.submit_indexing_job(self.index_spec_str)
```

Airflow 2.0.1 - airflow/providers/apache/druid/operators/druid.py
```
def execute(self, context: Dict[Any, Any]) -> None:
    hook = DruidHook(druid_ingest_conn_id=self.conn_id, max_ingestion_time=self.max_ingestion_time)
    self.log.info("Submitting %s", self.json_index_file)
    hook.submit_indexing_job(json.loads(self.json_index_file))
```

**Apache Airflow version**: 2.0.x

**Error Logs**:

```
[2021-02-24 06:42:24,287] {{connectionpool.py:452}} DEBUG - http://druid-master:8081 "POST /druid/indexer/v1/task HTTP/1.1" 500 15714
[2021-02-24 06:42:24,287] {{taskinstance.py:570}} DEBUG - Refreshing TaskInstance <TaskInstance: druid_compact_daily 2021-02-23T01:20:00+00:00 [running]> from DB
[2021-02-24 06:42:24,296] {{taskinstance.py:605}} DEBUG - Refreshed TaskInstance <TaskInstance: druid_compact_daily 2021-02-23T01:20:00+00:00 [running]>
[2021-02-24 06:42:24,298] {{taskinstance.py:1455}} ERROR - Did not get 200 when submitting the Druid job to http://druid-master:8081/druid/indexer/v1/task
```

### PR DESCRIPTION
**Pull request by TheRum**
Fixes - https://github.com/apache/airflow/issues/14417

closes: #14417

### CODE REVIEW

**Comment by xinbinhuang** [comment]
This is caused by #7127. It would be nice if you can also add a test case in [test_druid.py](https://github.com/apache/airflow/blob/master/tests/providers/apache/druid/operators/test_druid.py) to read `inde_spec` from a JSON file. You can do it roughly like this 

```python
def test_read_spec_from_file(self):
        with NamedTemporaryFile("w") as f:
            index_json_str = '''
            {
                "type": "{{ params.index_type }}",
                "datasource": "{{ params.datasource }}",
                "spec": {
                    "dataSchema": {
                        "granularitySpec": {
                            "intervals": ["{{ ds }}/{{ macros.ds_add(ds, 1) }}"]
                        }
                    }
                }
            }
        '''
            f.write(cloud_build_config)
            f.flush()
            operator = DruidOperator(
                task_id='spark_submit_job',
                json_index_file=f.name,
                params={
                    'index_type': 'index_hadoop',
                    'datasource': 'datasource_prd'
                },
                dag=self.dag
            )
            ti = TaskInstance(operator, DEFAULT_DATE)
            ti.render_templates()
            expected = ...
```

**Comment by xinbinhuang** [comment]
Hi @TheRum, just want to check in to see how's the progress. Are you available for adding the tests? Let me know if I can help with anything

**Comment by TheRum** [comment]
@xinbinhuang Yes, I want to add the tests but not sure how to start. I have no idea. Please guide me.

**Comment by TheRum** [comment]
@xinbinhuang Can you please suggest any changes to test case ?
Once task is submitted/run, it should generate a druid task_id and completed.

**Comment by xinbinhuang** [comment]
@TheRum sorry for the late response. You can use the same `expected` and `assert` from the previous test case `test_render_template`. The idea here is to make sure that we can render the same template from both a string and a file path.

I created a PR to your forked branch with the updated test case. https://github.com/TheRum/airflow/pull/1
Let me know if you have any questions

**Comment by xinbinhuang** [comment]
Thanks! The PR looks good to me. @potiuk @kaxil  Do you mind taking a look and merge it if it also looks good to you?

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Thanks @TheRum and @xinbinhuang

**Pull request merged**
