### PR TITLE
Add template field tests to AWS operators part1

### PR DESCRIPTION
**Pull request by gopidesupavan**
Adding template tests to operators, athena, bedrock, 
cloudformation, comprehend, datasync, dms, ec2, eks, emr.

I plan to submit smaller PRs to simplify the review , Separate PRs will be created for sensors and the remaining operators.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by o-nikolas** [comment]
This is basically checking if there are template fields which aren't present as fields on the operator object, right? What breakage happens if you have a template field that isn't present on the operator? Is it a silent failure or does something break catastrophically (e.g. runtime exception?)

**Comment by gopidesupavan** [comment]
> This is basically checking if there are template fields which aren't present as fields on the operator object, right? What breakage happens if you have a template field that isn't present on the operator? Is it a silent failure or does something break catastrophically (e.g. runtime exception?)

Hi @o-nikolas , yes good question :) it fails at pre-task execution, ex: 

here i have given someunknow_variable, in template fields, 

image

image

**Comment by gopidesupavan** [comment]
Recently while working on gluedatabrew changes #41848 , I made a mistake where the field name was provided incorrectly, causing it to fail during system tests. Thanks to @ferruzzi  :) fixing it here #42073.

**Review by o-nikolas — APPROVED** [review]

**Comment by ferruzzi** [comment]
Thanks for doing this, and I'm sorry I missed the PR; it's been a busy week.  Do you think there would be any benefit in expanding this?  For example, it might be suitable for a project-level CI check that runs on every provider as part of the PR checks, then everyone can benefit from it.  

Barring that, I wonder if we could move it into some BaseOperatorTests class that these can all inherit so we don't have to manually add it to every service file like this.

**Comment by gopidesupavan** [comment]
> Thanks for doing this, and I'm sorry I missed the PR; it's been a busy week. Do you think there would be any benefit in expanding this? For example, it might be suitable for a project-level CI check that runs on every provider as part of the PR checks, then everyone can benefit from it.
> 
> Barring that, I wonder if we could move it into some BaseOperatorTests class that these can all inherit so we don't have to manually add it to every service file like this.

Make sense, I can add pre-commit script to check using Python ast lib, I feel not possible for all operators , where some of the template_fields are object references example here: https://github.com/apache/airflow/blob/3bc2d3aef6c348e26775f4711ac593acfac9595e/airflow/providers/cncf/kubernetes/operators/job.py#L85, some of them might have to exclude 

If this sounds Good I can get a pr we can discuss more

**Pull request merged**
