### PR TITLE
Use `next_url` instead of `next`

### PR DESCRIPTION
**Pull request by vincbeck**
Resolves #37224

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by awdavidson — APPROVED** [review]

**Review by dirrao — APPROVED** [review]

**Review by Taragolis — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by csp33** [comment]
@vincbeck 
This PR breaks the fix I implemented in https://github.com/apache/airflow/pull/36833

Behavior when using `next_url`:

https://github.com/apache/airflow/assets/28935464/a48f4bee-711e-4bb9-a564-5e71e756a28f



Behavior when using `next`:

https://github.com/apache/airflow/assets/28935464/b9434c38-8fc2-4a1c-9d05-df23d1397c3d

**Comment by csp33** [comment]
@vincbeck 
This PR breaks the fix I implemented in https://github.com/apache/airflow/pull/36833

Behavior when using `next_url`:

https://github.com/apache/airflow/assets/28935464/a48f4bee-711e-4bb9-a564-5e71e756a28f



Behavior when using `next`:

https://github.com/apache/airflow/assets/28935464/b9434c38-8fc2-4a1c-9d05-df23d1397c3d

Cc: @ephraimbuddy  @abhishekbhakat @potiuk

**Comment by vincbeck** [comment]
I dont think it breaks what you did. It seems there is a bug I agree, but I dont think this PR breaks #36833

**Comment by vincbeck** [comment]
Indeed. The issue is:
- `next` should be used when used with `url_for` function
- `next_url` should be used with the `get_url_login` method

Let me fix that mess, we should always use `next` for both cases. That will simplify the code.

**Comment by vincbeck** [comment]
Fix here: #37904. I could not update the signature of `get_url_login`, that would break backward compatibility. But it is fine, we jsut need to remember to use `next_url` with `get_url_login` and `next` with `url_for`.

@csp33, could you test it please?

**Comment by jamiekt** [comment]
Hello,
We are running airflow 2.8.4 which should contain the fix in https://github.com/apache/airflow/pull/37904 however we're still seeing the same behaviour. We suspect that the reason is that that fix applies to the FAB auth manager whereas we are using some other auth manager. When we login to to our airflow instances we authenticate via Microsoft Entra (aka Azure Active Directory).
If anyone knows where to go to fix this when authenticating via Entra I'd be very grateful if you could let me know. Thanks in advance.

**Pull request merged**
