### PR TITLE
Prevent breaking scheduler on task_instance.priority_weight column has overflow value

### LINKED ISSUE #22781: Error "NumericValueOutOfRange integer out of range" in scheduler, task_insance.priority_weight column overflow
### Apache Airflow version

2.2.3

### What happened

Scheduler fails with following exception in case of priority_weight_total method returning out of integer range value.

"Original exception was: (psycopg2.errors.NumericValueOutOfRange) integer out of range"

### What you think should happen instead

_No response_

### How to reproduce

DAG to reproduce issue.

<pre>
import airflow
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from datetime import timedelta

default_args = {
    'start_date': airflow.utils.dates.days_ago(0),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(
    'monitoring_sched',
    default_args=default_args,
    description='liveness monitoring dag',
    schedule_interval='*/20 * * * *',
    dagrun_timeout=timedelta(minutes=120))

# priority_weight has type int in Airflow DB, uses the maximum.

# priority_weight has type int in Airflow DB, uses the maximum.
t1 = BashOperator(
    task_id='echo',
    bash_command='echo test',
    dag=dag,
    queue='kubernetes',
    depends_on_past=False,
    priority_weight=2**31-1)

# priority_weight has type int in Airflow DB, uses the maximum.
t2 = BashOperator(
    task_id='sleep',
    bash_command='sleep 1900',
    queue='kubernetes',
    dag=dag,
    depends_on_past=False,
    priority_weight=2**31-1)

# priority_weight has type int in Airflow DB, uses the maximum.
t3 = BashOperator(
    task_id='ech2o',
    bash_command='echo done',
    dag=dag,
    queue='kubernetes',
    depends_on_past=False,
    priority_weight=2**31-1)

t1 >> t2 >> t3
</pre>

### Operating System

Composer

### Versions of Apache Airflow Providers

_No response_

### Deployment

Composer

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kosteev**
closes: #22781

### CODE REVIEW

**Comment by uranusjr** [comment]
The fix is specific to Postgres I believe. Every database has different integer ranges so this will need to contain some if-else branches to cover each of them. Although honestly maybe it’s even better to just document this is a database limitation and you just can’t go over the limit.

**Comment by eladkal** [comment]
> The fix is specific to Postgres I believe. Every database has different integer ranges so this will need to contain some if-else branches to cover each of them. Although honestly maybe it’s even better to just document this is a database limitation and you just can’t go over the limit.

I agree but the point of concern is that this cause the scheduler to crash which is not good.
It means that one dag can cause cluster wide problems. I think we need to find a way to locallize the effect so only the problematic dag will be effected.

**Comment by uranusjr** [comment]
Yeah the scheduler should not crash, but perhaps we could catch the exception or something like that. I seem to recall there’s a similar situation for something else a while ago (datetime out of range?)

**Comment by eladkal** [comment]
I recall only https://github.com/apache/airflow/pull/17003 which also caused scheduler crash with DividedByZero

**Comment by ashb** [comment]
Is silently clamping it right, or should this be a parse time DAG import error?

**Comment by uranusjr** [comment]
Ah found it, 2213635178ca9d0ae96f5f68c88da48f7f104bf1

So I guess the better fix here is to do something similar, check for Postgres, and prevent an out-of-bounds value to be assigned for Postgres specifically.

**Comment by kosteev** [comment]
All right, validating it during DAG import and throwing error makes sense.
What about different databases? Should we handle all the databases taking into account different constraints of each?

**Comment by uranusjr** [comment]
Let’s start with adding just a check for Postgres now, we can add more later.

**Pull request closed without merging**
