### PR TITLE
AIRFLOW-2681: Include last dag run of externally triggered DAGs in UI.

### PR DESCRIPTION
**Pull request by dhatch**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

There is currently a bug in airflow 1.9.0 that causes last DAG runs to only be included in the UI for dags with a schedule.  Externally triggered runs are not included.  This makes it difficult for users to monitor DAGs that are exclusively externally triggered.  This small change resolves the issue.

This passes {{include_externally_triggered=True}} to {{get_last_dagrun}}.  It used to be passed in at this commit: 7c94d81c390881643f94d5e3d7d6fb351a445b72.  

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:  Small change that affects a UI page that doesn't have any existing tests.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
Whops, my bad. When I stopped this being a JSON call I didn't know about this parameter.

the new RBAC-based view copied my mistake, so could you make update the `airflow/www_rbac/templates/airflow/dags.html` template too please?

**Comment by dhatch** [comment]
Just updated to correct this in the RBAC UI as well.

**Review by jgao54 — APPROVED** [review]

**Comment by jgao54** [comment]
Thanks @dhatch!

**Comment by dhatch** [comment]
Thanks for the review!  Do I need to take any action to merge this?

Is it possible to cherry-pick to the v1.10-test branch so this is released with 1.10 as well?

**Comment by jgao54** [comment]
Merged.

Looks like we may end up with a beta3 release before the RC voting. If so, the cutoff will be master and this will be automatically included. Otherwise we can cherry-pick this in.

**Pull request closed without merging**
