### PR TITLE
[AIRFLOW-7058] Add support for different DB versions

### PR DESCRIPTION
**Pull request by potiuk**
Please review only the last commit - it is based on #7570 

---
Issue link: [AIRFLOW-7058](https://issues.apache.org/jira/browse/AIRFLOW-7058)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Let's see if it works with MySQL 8 :)

**Comment by ashb** [comment]
Last time I looked at mysql 8 we failed cos of some bulk export type thing we were using

**Comment by potiuk** [comment]
@ashb @kaxil - I've added description to README to make it clear which Python/MySQL/Postgres DB versions are currently tested with Airflow. Several people asked recently as they could not find this information :)

**Comment by potiuk** [comment]
> Last time I looked at mysql 8 we failed cos of some bulk export type thing we were using

I will try both python 3.8 and mysql 8 as separate PRs :)

**Review by turbaszek — APPROVED** [review]

**Pull request merged**
