### PR TITLE
[Proposal] Add the ability to schedule continuous

### PR DESCRIPTION
**Pull request by cheddar**
Dear Airflow Maintainers,

Please forgive the sudden PR, but I felt like it would be easier to describe what i want to do if there was some (pseudo) code to look at to understand the idea.

I'd like to add a "continuous" scheduling option.  A "continuous" schedule is one that will run the DAG unless there is already an instance of the DAG running.  This is primarily useful for DAGs that are started by sensors written under the assumption that you either want the sensor to be active and checking for data or you want the DAG to be running.

I.e. if you have a sensor that watches something like HCat for partition changes, you'd really like to know that either there is a partition change that is being processed or that there is nothing to be processed but you are actively looking and waiting for something to show up.

I haven't run the attached code yet so there's likely some issue with it, but I believe that it expresses what I think is required.  Namely, we add the `"@continuous"` scheduling option as well as a new parameter `max_consecutive_failures` parameter on the DAG.  

`max_consecutive_failures` exists as a protection to an error in the DAG causing infinite restarts of the DAG.  It is a property that only applies to the continuous case (or it could be promoted to apply in any scheduled case as well, if people were interested in that, but I'm intending to keep this proposal self-contained and not affect other things).

The primary downside I see to this implementation is that the DAG `execution_date` is always equal to `start_date` and is "non-deterministic".  I.e. it will be difficult to use the time selector in the DAG view on the UI to view a specific run of the DAG.  You can still track things down through the DAG history views and it could be possible to eventually adjust the UI to jump to like "next" and "previous" runs if this is a significant concern.  For us right now, this is not a significant concern.  Also, given that it only muddies the waters when you choose to use the continuous scheduling, it should only impact people who use this feature.

Is this something that could get accepted into airflow or is this an abomination that you would never be willing to accept?  If it is something that people would be willing to accept, I can work on making it actually work and have tests and all that good stuff.

### CODE REVIEW

**Comment by mistercrunch** [comment]
It sounds reasonable, we have to take a bit of time to think about the implications. 

Effectively it could also be implemented as an externally triggered DAG where the external trigger cares only about not having a current active DagRun. If that's what you need though it's nice to let the scheduler take care of it and not have to write and manage your own external trigger.

I think it's compatible with `depends_on_past=True` on "dealbreaker" task. Where if you want the flow to stop on error you can hook that up using the existing methodology.

It seems like it would be as easy as the code you sketched here.

**Comment by cheddar** [comment]
Cool, wasn't familiar with `depends_on_past` but yeah, I think setting that on the sensor will work for protecting against infinite failed runs.  Thanks.

I agree it could be externally triggered if that is preferable...  I'd probably do it by having my DAG end with a node that fires the DAG again, effectively making it infinitely recursive (assuming it keeps on succeeding).  I believe I can do that on my own without needing to make any changes in core, so if that's the preferred method just let me know.

Actually, that might even be simpler.  The only downside I can see to it is that nothing in the way the job is scheduled would tell someone how it is being triggered.  They'd have to know about my special end-node on the DAG.  That's not the end of the world though.

**Comment by criccomini** [comment]
(hi @cheddar :))

**Comment by cheddar** [comment]
Hey @criccomini, is github the new FB now? :P

@mistercrunch How do you feel about me doing it as an external trigger that is triggered by the final node in my DAG?  That seems to have nice properties, but I'm looking for confirmation that it's how you think airflow should be used (versus adding it as a scheduling option).

**Comment by cheddar** [comment]
I just figured out the reason not to do it as a trailing node in our DAG.  When we restart all of the airflow services, we have to kill all running DAGs as well (otherwise things seem to get into a weird state).  Doing it with a DAG that invokes itself over and over again would require us to restart all of our DAGs manually every time we restart the airflow services, which is annoying.

Having the scheduler do this would mean that we do not have to do that.

**Comment by r39132** [comment]
@cheddar As part of Cold Case PR Clean up, I am reviewing all PRs older than 2 weeks. We have reduced open PRs from >110 to ~30 : https://cwiki.apache.org/confluence/display/AIRFLOW/Cold-Case+PR+Resolution

Is this PR still needed? If so, can you rebase. A lot of your changes have already been submitted in other PRs. Pls respond within the next 5 days, else I will close this PR.

**Pull request closed without merging**
