### PR TITLE
[AIRFLOW-2581] Fix DbApiHook autocommit

### PR DESCRIPTION
**Pull request by imroc**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2581

### Description
- [x] Here are some details about my PR:
DbApiHook.run actually do not commit when I set to autocommit=True
For example: hook.run(sql,autocommit=True)
This commit fixed this problem.

### Tests
- [x] My PR does not need testing for this extremely good reason:
bug fix, no need for tests

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by imroc** [comment]
@bolkedebruin @Fokko  PTAL. this bug was introduced from [here](https://github.com/apache/incubator-airflow/pull/3257/commits/3450f526cec894cc7beceeae18f9d54cb2ae7520) , and there is a fix [here](https://github.com/apache/incubator-airflow/pull/3258/commits/bf244701e35e973c6b7ee2ee41e5524ceafeed30) , which didn't fix it at all, it runs correctly after I fix it in the PR.

**Comment by bolkedebruin** [comment]
@roc I’ll have a look. But can you please stop closing/opening the Pr for the sake trying it? Apache Infra has asked us not to do this.

**Comment by imroc** [comment]
@bolkedebruin  OK, I was trying to retrigger the CI because of the CI failure  😅

**Comment by imroc** [comment]
it seems that the CI failure was not related

**Comment by Fokko** [comment]
@imroc Please run this on your own Travis since Apache is paying for the Travis hours. Please do the retries on your own Travis and link the successful build.

**Comment by feng-tao** [comment]
I think this pr causes couples of unit tests failed which caused current CI is broken. Are you planning to fix it?

**Pull request closed without merging**
