### PR TITLE
[AIRFLOW-6994] SparkSubmitOperator re-launches spark driver even when original driver still running

### PR DESCRIPTION
**Pull request by tooptoop4**
---
Issue link: [AIRFLOW-6994](https://issues.apache.org/jira/browse/AIRFLOW-6994)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by tooptoop4** [comment]
@nuclearpinguin pls merge

**Review by kaxil — COMMENTED** [review]
How difficult is it to add a test to avoid regression for this case using mocks or something?

**Comment by tooptoop4** [comment]
unstale

**Comment by tooptoop4** [comment]
crispy

**Comment by kaxil** [comment]
> it is trivial change tho

I would still prefer **tests**, please. Otherwise, there is no way of knowing if another user in future breaks this functionality.

**Comment by dimberman** [comment]
@tooptoop4 are you able to add a test to this? It just needs to be something that if the user changes the logic we will be notified via test failure.

**Comment by tooptoop4** [comment]
nah'

**Pull request closed without merging**
