### PR TITLE
[AIRFLOW-929] - Fix log url via relative path

### PR DESCRIPTION
**Pull request by arybin93**
Make sure you have checked _all_ steps below.

### Jira
- [x] [AIRFLOW-929](https://issues.apache.org/jira/browse/AIRFLOW-929) 

### Description

- [x] Add relative path `log_relative_url` for log view in admin panel

### Tests

- [x] My PR follow existing unit tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] Changes in docs don't require

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
I don't think this is needed - the original issue as reported can be fixed by setting the `base_url` under `[webserver]`.

Is there another reason you want this change?

**Comment by OmerJog** [comment]
@ashb If the base_url isn't set how does the logs visible in the task log of the UI.
This seems broken to me.
In one place is visible in other it does not.
As I said on the ticket. Airflow knows where the logs are. It's a fact that we see them in task log.
So why the link for "log URL" needs additional setting?
There is no logic in having double settings.
The webserver should reference the correct location whether it's localhost or remote - am I wrong?

**Comment by ashb** [comment]
Other parts of Airflow will have incorrect links/bad URLs if `base_url` is wrong.

Regardless this isn't quite the right fix - it changes the behaviour of `ti.logs_url` to be a relative URL which could break peoples alerts (i.e. a slack alert on failure that includes the URL)

**Comment by arybin93** [comment]
@ashb may be create property `ti.logs_relative_url` in `TaskInstance` and use it for view in UI. Will it better?

**Comment by ashb** [comment]
Closed in favour of #5525

**Pull request closed without merging**
