### PR TITLE
[AIRFLOW-5246] Remove source parameter in BaseHook constructor

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5246

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by potiuk** [comment]
@BasPH @kaxil @BasPH -> I stumbled upon this while adding codecov/licence generation for python files. It's quite "core" part, I believe that source param is not used any more (unless I missed some obscure metaclass-related behaviour).

**Comment by potiuk** [comment]
BTW. There are also related pylint fixes here.

**Review by BasPH — APPROVED** [review]
I tried searching what could possibly be the use case for `source`, turns out it was added with the very first commit. Time to remove it I guess 😄 

@potiuk I'm okay with this PR for now but please try to make separate PRs for unrelated changes, makes it a lot easier to check + track changes in the future.

**Comment by potiuk** [comment]
Sure thing. I will separate the changes on separate commits  - exactly for tracking purpose.

**Comment by potiuk** [comment]
@BasPH -> I split it into two commits and merge them together now :).

**Pull request merged**
