### PR TITLE
[AIRFLOW-2918] Fix Flake8 violations

### PR DESCRIPTION
**Pull request by Fokko**
A lot of small issues that I've fixed to enforce Flake8 globally instead of on the diffs.
- Unused imports
- Wrong import order
- Small identation fixes
- Remove one letter variables
- Fix noqa annotations

There are still a lot of violations. But I would like to use Black, YAPF or autopep8 to enforce style. Then we have a solid codebase again I'd say.

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2918\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2918
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
LGTM. However, can you just resolve the following 3 issues? This would clear out `dags` directory at least.

```
./dags/test_dag.py:10:2: W291 trailing whitespace
./dags/test_dag.py:12:2: W291 trailing whitespace
./dags/test_dag.py:26:91: E501 line too long (96 > 90 characters)
```

**Comment by Fokko** [comment]
Nice spot @kaxil. I've fixed the voilations.

**Comment by feng-tao** [comment]
thanks @Fokko . And sorry as this falls off my radar...

**Comment by kaxil** [comment]
Thanks @Fokko  :)

**Comment by gwax** [comment]
👍 for black and strong support for using `pre-commit` as well

**Pull request merged**
