### PR TITLE
Bump ``uv`` to ``0.4.26``

### PR DESCRIPTION
**Pull request by kaxil**
https://pypi.org/project/uv/0.4.26/

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Strange but prod image verification failed - could be because of some uv problem. I re-run it.

**Comment by kaxil** [comment]
> Strange but prod image verification failed - could be because of some uv problem. I re-run it.

Yeah:

```
=================================== FAILURES ===================================
  ___________ TestPythonPackages.test_required_providers_are_installed ___________
  [gw2] linux -- Python 3.9.20 /tmp/tmplx3z9mmg/.venv/bin/python
  
  self = <docker_tests.test_prod_image.TestPythonPackages object at 0x7f7ce56bbc70>
  default_docker_image = 'ghcr.io/apache/airflow/main/prod/python3.9:b4a37f531cf739f8850e9795bab1473ebef212fd'
  
      def test_required_providers_are_installed(self, default_docker_image):
          if os.environ.get("TEST_SLIM_IMAGE"):
              packages_to_install = set(SLIM_IMAGE_PROVIDERS)
              package_file = "hatch_build.py"
          else:
              packages_to_install = set(REGULAR_IMAGE_PROVIDERS)
              package_file = PROD_IMAGE_PROVIDERS_FILE_PATH
          assert len(packages_to_install) != 0
          output = run_bash_in_docker("airflow providers list --output json", image=default_docker_image)
  >       providers = json.loads(output)
  
  docker_tests/test_prod_image.py:94: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  /opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/__init__.py:346: in loads
      return _default_decoder.decode(s)
  /opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/decoder.py:337: in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <json.decoder.JSONDecoder object at 0x7f7ce715b6d0>
  s = '[2024-10-23T21:52:00.010+0000] {configuration.py:994} WARNING - section/key [core/asset_manager_kwargs] not found in ...kage_name": "apache-airflow-providers-standard", "description": "Airflow Standard Provider", "version": "1.0.0.dev0"}]'
  idx = 0
  
      def raw_decode(self, s, idx=0):
          """Decode a JSON document from ``s`` (a ``str`` beginning with
          a JSON document) and return a 2-tuple of the Python
          representation and the index in ``s`` where the document ended.
      
          This can be used to decode a JSON document from a string that may
          have extraneous data at the end.
      
          """
          try:
  >           obj, end = self.scan_once(s, idx)
  E           json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 6 (char 5)
  
  /opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/json/decoder.py:353: JSONDecodeError
  =========================== short test summary info ============================
  FAILED docker_tests/test_prod_image.py::TestPythonPackages::test_required_providers_are_installed - json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 6 (char 5)
```

**Comment by kaxil** [comment]
> Strange but prod image verification failed - could be because of some uv problem. I re-run it.

Oh actually, looks like something is broken on main too: https://github.com/apache/airflow/actions/runs/11486815718/job/31971045626 (same error)

**Comment by kaxil** [comment]
aah I know what it might be

**Comment by kaxil** [comment]
> > Strange but prod image verification failed - could be because of some uv problem. I re-run it.
> 
> Oh actually, looks like something is broken on main too: https://github.com/apache/airflow/actions/runs/11486815718/job/31971045626 (same error)

Ok, I know now. PR incoming

**Comment by potiuk** [comment]
> Ok, I know now. PR incoming

Yep:

` WARNING - section/key [core/asset_manager_kwargs] not found in ...kage_name"`

**Comment by kaxil** [comment]
@potiuk Fix here: https://github.com/apache/airflow/pull/43334

**Comment by kaxil** [comment]
> @potiuk Fix here: #43334

Proper fix at https://github.com/apache/airflow/pull/43335

**Comment by kaxil** [comment]
@potiuk Could I get a review on this :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
