### PR TITLE
[AIRFLOW-2731] Raise psutil restriction to <6.0.0

### PR DESCRIPTION
**Pull request by gwax**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2731

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
  - Allow Airflow to be co-installed with psutil >=5.0.0
  - Airflow's usage of psutil does not depend on features changed/removed between psutil 4.x and psutil 5.x so the prohibition is overly strict

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - Library bounds changed on library whose interface has not change w.r.t. Airflow

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
LGTM

**Comment by jrans** [comment]
This PR has broken airflow for me, old limitation of <5 seems like it was for a reason..

I reckon its worth finding out why in [this commit](https://github.com/apache/airflow/commit/fdb7e949140b735b8554ae5b22ad752e86f6ebaf) the version was given an upper limit before making changes like this in future. 

Details:

OS: osx 10.14.3
Python Version: 3.6.1

psutil  4.4.2 works, psutil 5.6.1 fails with this error:

`ValueError: Cannot resolve 'airflow.utils.log.file_processor_handler.FileProcessorHandler': dlopen(/miniconda3/envs/mvp/lib/python3.6/site-packages/psutil/_psutil_osx.cpython-36m-darwin.so, 2): Symbol not found: _kIOMasterPortDefault`
 
image

**Comment by ashb** [comment]
The nature of that error implies it is a bug/conflicting installation of psutil. It looks almost like you have some new and some old files there.

The "Cannot resolve 'airflow.utils.log.file_processor_handler.FileProcessorHandler" part of the error message is just Airflow saying while trying to FileProcessorHandler we got this other error.

You should see the exact same error form running `pyton -c "import psutil"` which would entirely remove Airflow from the equation.

**Comment by jrans** [comment]
Thanks for getting back to me. Yes definitely not an airflow issue but highlighting the change in range in the airflow upgrade `1.10.2` revealing this and hopefully will help someone else suffering.

I can confirm `psutil` @  `5.6.1` and latest `5.6.2` not working for me but pinning to `5.6.0` produces no error.. will raise with them.

**Comment by kaxil** [comment]
But that is the reason why "This PR has broken airflow for me, old limitation of <5 seems like it was for a reason.." is incorrect 😉 .

**Comment by jrans** [comment]
Yep sorry for that should have debugged one step further before making conclusion but regardless important to document somewhere as [not only one](https://stackoverflow.com/questions/54340226/airflow-errorattributeerror-module-airflow-utils-log-has-no-attribute-file) with issue. 
Just unfortunate that at time of my airflow upgrade `psutil` latest was in a bad state and only became a problem once recreating my environment because of the change of upper version limit.

**Pull request closed without merging**
