### PR TITLE
[AIRFLOW 16730] Added docs & doc ref's for AWS transfer operators between SFTP & S3

### LINKED ISSUE #16730: SFTPToS3Operator is not mentioned in the apache-airflow-providers-amazon > operators documentation
**Apache Airflow version**:  2.2.0  , apache-airflow-providers-amazon == 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

I would expect to find the documentation for
`airflow.providers.amazon.aws.transfers.sftp_to_s3.SFTPToS3Operator`
in one these locations 
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/index.html
or
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/transfer/index.html

**How to reproduce it**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by pyerbiz**
…tp #16730 (#1)

* created files
* added s3tosftp and examples
* vault var removed
* updated s3_to_sftp example and doc
* fixed directives
* ref error fixed

closes: #16730 
related:

Added docs and example dags for SFTPToS3Operator and S3ToSFTPOperator. Added ref in s3_to_sftp.py and sftp_to_s3.py

Add meaningful description above

Test:
./breeze build-docs -- --package-filter apache-airflow-providers-amazon

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Can you please @pyerbiz :
1) rebase to latest main (there were an error in main fixed in #16971 
2) fix static checks (the easiest way is to install pre-commit as suggested in the error message - it will then auto-correct everything for you.

Having `pre-commit` installed for airflow contribution is HEARTILY recommended . It saves a lot of time on iterations and a lot of CI build time if you run the checks locally :)

**Comment by pyerbiz** [comment]
Converting to draft to prevent mistakenly triggering CI/CD

**Comment by pyerbiz** [comment]
> Can you please @pyerbiz :
> 
> 1. rebase to latest main (there were an error in main fixed in [Fixes typo in the name of file for Breeze docker compose env #16971](https://github.com/apache/airflow/pull/16971)
 -- rebased local branch

> 2. fix static checks (the easiest way is to install pre-commit as suggested in the error message - it will then auto-correct everything for you.
 -- fixed static check
> Having `pre-commit` installed for airflow contribution is HEARTILY recommended . It saves a lot of time on iterations and a lot of CI build time if you run the checks locally :)
-- installed and passed pre-commit static check all files. Ran through breeze.

**Comment by pyerbiz** [comment]
its failing static check on `hook id: provider-yamls` for providers.yaml file. I did not edit that file, which means I have to add something to it? I did come across a doc I think that talked about `providers.yaml` file -- but right now I couldn't find it.

**Comment by potiuk** [comment]
You just need to add the new guides to https://github.com/apache/airflow/blob/main/airflow/providers/amazon/provider.yaml (look at other .rst files there and do it in the same fashion (and yeah @mik-laj maybe worth to improve the error message in this case ;) )

**Comment by potiuk** [comment]
```
Validate providers.yaml files............................................................Failed
- hook id: provider-yamls
- exit code: 1

Checking integration duplicates
Checking completeness of list of {sensors, hooks, operators}
Checking for duplicates in list of {sensors, hooks, operators}
Checking completeness of list of transfers
Checking for duplicates in list of transfers
Checking connection classes belong to package
Checking doc files
```
Above is cool ^^

Below does not tell too much vv 
```
Items in the first set but not the second:
'/docs/apache-airflow-providers-amazon/operators/transfer/s3_to_sftp.rst'
'/docs/apache-airflow-providers-amazon/operators/transfer/sftp_to_s3.rst'
```

**Comment by potiuk** [comment]
Wooho! all good. Merging.

**Pull request merged**
