### PR TITLE
[Airflow 16934] fix delete task_instance also deleted dag_run too when sla

### PR DESCRIPTION
**Pull request by penggongkui**
delete(ti) will also delete the dag_run(do by the sqla relationship)

#16934 

It's not sla check duty to delete the missed task_instance

### CODE REVIEW

**Comment by uranusjr** [comment]
> delete(ti) will also delete the dag_run(do by the sqla relationship)

Where is this relationship defined? The relationship between DagRun and TaskInstance is defined here:

https://github.com/apache/airflow/blob/v2-1-stable/airflow/models/dagrun.py#L100-L105

But I don’t see any cascading options set (the default is to not cascade IIRC).

If this is really the cause, we can’t just not delete those TaskInstances so some other clean up would be needed.

**Comment by penggongkui** [comment]
@uranusjr accoding the sqla document, default behavior is setting their foreign key reference to NULL.

https://docs.sqlalchemy.org/en/14/orm/cascades.html#unitofwork-cascades

image

also I have do a unit_test  do session.delete(ti), it will set the dag_run's dag_id && execution_date to null(just like deleted the dag_run)

anyway, I have use a another way to delete the taskinstance(it's a little ugly)

**Comment by uranusjr** [comment]
> it will set the dag_run's dag_id && execution_date to null (just like deleted the dag_run)

Ah I see, that makes perfect sense. So both the original issue and this PR is using “delete” in an inaccurate sense; the dag run is not actually deleted, but incorrectly modified and becomes unavailable.

I’m far from a SQLAlchemy expert, so I want to summon a fellow maintainer on this topic, but I feel the current relationship setup between DagRun and TaskInstance is backwards.

Currently we have this on `DagRun`:

https://github.com/apache/airflow/blob/c46e841519ef2df7dc40ff2596dd49c010514d87/airflow/models/dagrun.py#L92-L97

and this on `TaskInstance`:

https://github.com/apache/airflow/blob/c46e841519ef2df7dc40ff2596dd49c010514d87/airflow/models/taskinstance.py#L2147

But if I’m understaing SQLAlchemy correctly (a big if), this makes `DagRun` a child of `TaskInstance`, thus deleting a `TaskInstance` triggers cascading on its associated `DagRun`, setting the foreign key columns to NULL. But the hierarchy is the other way around: a `TaskInstance` only makes sense when there is an associated `DagRun`, so deleting a `DagRun` should cascade to its `TaskInstance` children, but deleting `TaskInstance` shouldn’t affect a `DagRun`. So we should set the backref at the other side (on `TaskInstance.dag_run`) instead…?

**Comment by potiuk** [comment]
Merging. The error was due to  #16971

**Comment by penggongkui** [comment]
agree with you

the best solution is make relationship correct, but this is out of my knowledge with airflow whole project, maybe something else use the ti.dag_run

> So we should set the backref at the other side (on TaskInstance.dag_run) instead…?

the sqla doc https://docs.sqlalchemy.org/en/14/orm/backref.html says backref is a alias with reletionship with back_populates both side, the right relationship is change backref to back_populates in DagRun

https://github.com/apache/airflow/blob/c46e841519ef2df7dc40ff2596dd49c010514d87/airflow/models/taskinstance.py#L2147

and this line just for pylint to know dag_run field in taskinstance (know from the comment: https://github.com/apache/airflow/blob/2.0.0/airflow/models/taskinstance.py#L2066)

I just read the sqla document, also not familiar with it

the right relationship also will fix another issue #16896

**Comment by ashb** [comment]
Yeah, the code in https://github.com/apache/airflow/blob/ab5f770bfcd8c690cbe4d0825896325aca0beeca/airflow/models/taskinstance.py#L2063-L2073 is never run by python -- it's only picked up by code analysers.

This was  my bad -- I added the relationship in the first place, and I wasn't aware that the side where the relationship is defined matter.


But yes, changing the relationship sounds like the better fix.

@penggongkui Please also target all PRs directly to the `main` branch, and then once it's merged then we (committers/release managers) will cherry-pick it in to the release branch.

**Comment by penggongkui** [comment]
how about assign this issue to someone who familiar with the SQLAlchemy and the whole airflow project, I may cannot do it with the big change

**Pull request closed without merging**
