### PR TITLE
[AIRFLOW-1870] Enable flake8 tests

### PR DESCRIPTION
**Pull request by bolkedebruin**
Flake8 tests now run for diffs

### JIRA
- [XXX] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1870

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

flake8

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@Fokko

**Comment by Fokko** [comment]
Very nice @bolkedebruin, maybe also enable a nice landscaping tool. For example https://landscape.io/, https://codeclimate.com/ or https://www.codacy.com/? I don't have a lot of experience with Python tooling, but I'm willing to invest some time to make a comparison.

**Comment by bolkedebruin** [comment]
(imho out of scope of this PR): Landscape we tried, but was very flaky with uptime and reports are kind of unclear. Flake8 reports a lot of these errors as well. But anyways be my guest. Please note activating requires Apache INFRA support and site wide write access is not allowed.

**Comment by Fokko** [comment]
Good point, LGTM. Thanks for adding Flake8 to the build again. Cheers

**Pull request closed without merging**
