### PR TITLE
[AIRFLOW-1798] Include Celery SSL in default config

### PR DESCRIPTION
**Pull request by dhuang**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1798

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Include settings for Celery SSL to default config template.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by gwax — APPROVED** [review]
LGTM.

Test seems due to unrelated flakiness.

**Comment by Fokko** [comment]
Could you rebase against master? I'm a bit confused since I also provided this patch a while ago:
https://github.com/apache/incubator-airflow/pull/2806/files#diff-bbf16e7665ac448883f2ceeb40db35cdR326

**Comment by Fokko** [comment]
Ah, my patch never made it to master. Please rebase, and then I'll merge. Cheers

**Comment by dhuang** [comment]
Sorry for the delay, rebased.

**Review by bolkedebruin — CHANGES_REQUESTED** [review]
Please check the config options. They are defined twice now (although one is in the wrong spot). In addition we moved away from prepending “celery_”. 

I think given the above it warrants a small test

**Comment by dhuang** [comment]
Already addressed by https://github.com/apache/incubator-airflow/pull/2806.

**Pull request closed without merging**
