### PR TITLE
[AIRFLOW-6708] Set unique logger names

### PR DESCRIPTION
**Pull request by mik-laj**
LoggingMixin is intended for configuring the logger for classes. If it is used incorrectly then all loggers are configured with one name - `airflow.utils.log.logging_mixin.LoggingMixin`

Before:
```
$ AIRFLOW__LOGGING__COLORED_LOG_FORMAT='%(name)s: %(message)s'  python -c 'from airflow.logging_config import configure_logging; from airflow.executors.celery_executor import execute_command; configure_logging(); execute_command(["bash", "-c", "echo 1"]);'
airflow.utils.log.logging_mixin.LoggingMixin: Executing command in Celery: ['bash', '-c', 'echo 1']
1
```
After: 
```
23:33 $ AIRFLOW__LOGGING__COLORED_LOG_FORMAT='%(name)s: %(message)s'  python -c 'from airflow.logging_config import configure_logging; from airflow.executors.celery_executor import execute_command; configure_logging(); execute_command(["bash", "-c", "echo 1"]);'
airflow.executors.celery_executor: Executing command in Celery: ['bash', '-c', 'echo 1']
1
```

---
Issue link: [AIRFLOW-6708](https://issues.apache.org/jira/browse/AIRFLOW-6708)

Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Review by ashb — APPROVED** [review]
Good work, this was one of those things that bugged me but that I'd just not got around to fixing

**Review by potiuk — CHANGES_REQUESTED** [review]
Really nice. But needs rebase and also I think we should prevent it from happening in the future. I think simple pygrep pre-commit hook checking for LoggingMixin() should do the job.

Can you please add it while rebasing?

**Comment by mik-laj** [comment]
@potiuk done.

**Review by potiuk — APPROVED** [review]
Perfect! Thanks!

**Pull request merged**
