### PR TITLE
Remove unused query and codes in dag.py module

### PR DESCRIPTION
**Pull request by ephraimbuddy**
I don't think this query is used anywhere. Can't find the usage. Raising a PR to discuss it

### CODE REVIEW

**Comment by ephraimbuddy** [comment]
@tquazi , this seems to come from your change in https://github.com/apache/airflow/pull/30478. Was the query not used, or am I missing something?

**Comment by tquazi** [comment]
@ephraimbuddy The query is used to lock the related dag runs to prevent from possible dead lock.

**Comment by uranusjr** [comment]
Judging from the variable name, there’s probably supposed to be a `with_row_lock` somewhere. Maybe it got removed accidentally at some point?

**Comment by uranusjr** [comment]
Ah I missed the `with_for_update` call, so yeah that should be changed to use `with_row_locks` to make the intention clearer (and more portable across databases).

**Comment by ephraimbuddy** [comment]
> Ah I missed the `with_for_update` call, so yeah that should be changed to use `with_row_locks` to make the intention clearer (and more portable across databases).

Yeah. Didn't see that too

**Pull request closed without merging**
