### PR TITLE
[AIRFLOW-6040] ReadTimeoutError should not raise exception

### PR DESCRIPTION
**Pull request by dimberman**
---
Issue link: [AIRFLOW-6040](https://issues.apache.org/jira/browse/AIRFLOW-6040)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by dimberman** [comment]
continuation of https://github.com/apache/airflow/pull/6643

**Comment by dimberman** [comment]
cc: @pvcnt @sbrandtb

**Review by ashb — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by sbrandtb** [comment]
@dimberman I do not fully agree with making this a warning. Warnings often confuse people and this read timeout is totally expected. I would even demote it to debug because we would only look into this if something is fishy anyways.

**Comment by maxirus** [comment]
I don't think this is the right approach for fixing AIRFLOW-6040. The Watcher isn't being ran in its own thread so it must timeout so it's not blocking further execution. Therefor it's not an error or a warning as this is the expected behavior you're looking for.

**Comment by sbrandtb** [comment]
@maxirus While I agree with this being the wrong approach to fix the issue, I beg to differ: Yes, it is not run in a separate thread. But it is run in a separate process.

**Pull request merged**
