### PR TITLE
Request to add United to the Airflow community

### PR DESCRIPTION
**Pull request by ilopezfr**

### CODE REVIEW

**Comment by r39132** [comment]
@ilopezfr Your commit does not contain any changes. Please resubmit with a change to the readme.md file.

**Comment by r39132** [comment]
@ilopezfr You don't need an enterprise account to make this change yourself using your own github account. 

Follow https://github.com/apache/incubator-airflow/pull/2331 as an example. Also, please try to follow https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

Be sure to squash your commits as well.

**Comment by r39132** [comment]
@ilopezfr : https://github.com/apache/incubator-airflow/pull/2332/commits/fbe4fb7a92ba2f788b70d4bb9482d509c2fe41a4

I went ahead and made the change. Please follow this in the future.

**Comment by ashb** [comment]
@r39132 This can be closed now can't it?

**Comment by r39132** [comment]
Closing!

**Pull request closed without merging**
