### PR TITLE
Static check failure in CI

### PR DESCRIPTION
**Pull request by uranusjr**
Current failed output:

https://github.com/apache/airflow/actions/runs/5063774978/jobs/9090811506?pr=31414

Still investigating.

### CODE REVIEW

**Comment by pankajkoti** [comment]
Adding a comment here to get notifications of the work here :) 
With reference to: https://github.com/apache/airflow/pull/31201#issuecomment-1559977621

**Comment by uranusjr** [comment]
This is passing in main now. Probably a cache issue?

**Comment by uranusjr** [comment]
Still happening…

**Comment by uranusjr** [comment]
Continuing in a new PR.

**Pull request closed without merging**
