### PR TITLE
[AIRFLOW-1353] Standardizing string type in comments

### PR DESCRIPTION
**Pull request by Derrreks**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1353

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
Within comments, str and string were being used to describe the same type. This PR changes all of those instance to be str to follow Python types. In addition a few functions were missing a `:param` or `:type` here and there, so those have been added.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
No need for testing, comment changes only.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Derrreks** [comment]
@msumit @mistercrunch

**Comment by msumit** [comment]
@Derrreks this must be an arduous task to do :). 

The diff lgtm, but I'll let a couple of more folks to review it. cc - @bolkedebruin @criccomini @r39132

**Comment by derekschuster-optimizely** [comment]
@bolkedebruin @criccomini @r39132 can this get a second look?

**Comment by seelmann** [comment]
Was fixed in https://github.com/apache/incubator-airflow/pull/3857, so this can be closed.

**Comment by Fokko** [comment]
Indeed, thanks

**Pull request closed without merging**
