### PR TITLE
Use urljoin to join endpoint to base URL

### PR DESCRIPTION
**Pull request by jbrownlucid**
Dear Airflow Maintainers,

Please accept the following PR that adds robustness against various combinations of trailing and leading slashes.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks fo rthe contribution. Can you check the travis error please?

**Comment by bolkedebruin** [comment]
ping @jbrownlucid

**Comment by jbrownlucid** [comment]
This somewhat confusing. I see the error, it's in the code from this PR:

```
======================================================================
ERROR: test_sensor (tests.HttpOpSensorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/airbnb/airflow/.tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/airbnb/airflow/tests/core.py", line 1212, in test_sensor
    sensor.run(start_date=DEFAULT_DATE, end_date=DEFAULT_DATE, force=True)
  File "/home/travis/build/airbnb/airflow/airflow/models.py", line 2139, in run
    force=force,)
  File "/home/travis/build/airbnb/airflow/airflow/utils/db.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/airbnb/airflow/airflow/models.py", line 1225, in run
    result = task_copy.execute(context=context)
  File "/home/travis/build/airbnb/airflow/airflow/operators/sensors.py", line 56, in execute
    while not self.poke(context):
  File "/home/travis/build/airbnb/airflow/airflow/operators/sensors.py", line 511, in poke
    extra_options=self.extra_options)
  File "/home/travis/build/airbnb/airflow/airflow/hooks/http_hook.py", line 65, in run
    url = urljoin(self.base_url, endpoint)
  File "/home/travis/build/airbnb/airflow/.tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
    base, url, _coerce_result = _coerce_args(base, url)
  File "/home/travis/build/airbnb/airflow/.tox/py27-cdh-airflow_backend_mysql/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

But when I run `./run_unit_tests.sh tests.core:HttpOpSensorTest.test_sensor -s --logging-level=DEBUG` on my local airflow, I get success. This is with python2.7 and python3.5.

**Comment by artwr** [comment]
The change LGTM. @jbrownlucid, if you can create a JIRA issue, we can get this across the "merge" line.

**Comment by r39132** [comment]
Out of sync and no response from submitter. Closing.

**Pull request closed without merging**
