### PR TITLE
Add in animation for running dags.

### PR DESCRIPTION
**Pull request by bo01ean**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA

No Jira issue.

### Description

This PR animates the active DAG's to denote activity in the DAG:
https://giphy.com/embed/3og0IxE2fmLvwucEne

### Tests

Visual tests to indicate activity are not necessary.

### Commits

1 commit only.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Sorry Jira issue is required. Please read the commit guidelines in the PR template. Tests are required.

**Comment by bo01ean** [comment]
This is a CSS modification, no test coverage on CSS.

I will create a Jira issue.

**Comment by bo01ean** [comment]
Also, @bolkedebruin codecov says there was a modification to airflow/models.py, but there was none such modification.

**Comment by saguziel** [comment]
I'm -1 on this since it adds no new information and just adds visual clutter.

**Comment by bo01ean** [comment]
I am having difficulties logging into the ASF Jira.

**Comment by bo01ean** [comment]
image


It is pretty hard to tell lime from green in larger DAGs.

@saguziel Any idea how I can get into Airflow JIRA to make an issue?

**Comment by saguziel** [comment]
You have to make an account first

**Comment by feluelle** [comment]
I only would use this animation when an auto refresh happens after the task changes its state so you always are up to date in what is happening.

I think the animation with sth like auto refresh on changed state should be an option in the airflow.cfg you can turn on/off

**Comment by dlamblin** [comment]
Because the commit message in the PR should start with [AIRFLOW-0123456789] referencing the [jira ticket](https://issues.apache.org/jira/projects/AIRFLOW/issues), you'll need to drop the branch and recommit the change with the updated message on a branch without this commit, before opening the PR.

**Comment by dimberman** [comment]
Hello @bo01ean, I'm going to close this PR since it's been unchanged for a pretty long time, but would be glad to re-open it if you are still interested in contributing this!

**Pull request closed without merging**
