### PR TITLE
Bump upper bound version of jsonschema to 5.0

### PR DESCRIPTION
**Pull request by ephraimbuddy**
The upper bound is necessary because of connexion upper bound on jsonshema

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
Why are versions between 3.2.0 and 4.4.0 no longer compatible?

**Comment by ephraimbuddy** [comment]
> Why are versions between 3.2.0 and 4.4.0 no longer compatible?

This below:
```
jsonschema.__version__, jsonschema.validators.validators, jsonschema.validators.meta_schemas and jsonschema.RefResolver.in_scope have been deprecated, as has passing a second-argument schema to Validator.iter_errors and Validator.is_valid.
```
Airflow was not directly affected though but I think connexion prevented us from using 4.4.0 until they upgraded jsonschema few days ago

**Comment by ephraimbuddy** [comment]
Do you suggest we have it as >3.2.0, <5.0?

**Comment by uranusjr** [comment]
Yes, I was wondering why we need to raise the lower bound.

**Review by uranusjr — APPROVED** [review]

**Pull request merged**
