### PR TITLE
Add tags inside try block.

### PR DESCRIPTION
**Pull request by jhtimmins**
Forces the Sentry customization to occur in the scope in which tags are called.

### CODE REVIEW

**Comment by ashb** [comment]
Do we need to/can we add tests for this to prevent regression?

**Comment by masterlittle** [comment]
Any idea in which release this is gonna be merged?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Do we need to/can we add tests for this to prevent regression?

I tihnk it's not worth to find a clever way to test it ? (But @jhtimmins maybe you can find one?)

**Comment by potiuk** [comment]
> Any idea in which release this is gonna be merged?

We are just voting on 2.2.5 so  most likely in 2.3.0

**Comment by mikharkiv** [comment]
Do we have any updates about when this fix will be merged?

**Comment by potiuk** [comment]
Seems it's been forgotten.

**Pull request merged**
