### PR TITLE
Reset stats logger in daemon context to reinitialize in child process

### PR DESCRIPTION
**Pull request by pavansharma36**
related: #33897 

Clear stats logger instance to reinitialize in child process.

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Could you try to reproduce the error in a new test and pass it with this change?

**Comment by pavansharma36** [comment]
@hussein-awala  Actually I am not aware of writing test with daemon context.

And this issue requires statsd metrics enabled and creating connection with actual host

**Comment by potiuk** [comment]
Can you please rebase.? It's indeed hard to test it.

**Comment by uranusjr** [comment]
This seems a bit messy to me. Perhaps we should create a wrapper to `DaemonContext` to replace its direct usages, and do the resetting in that wrapper instead.

**Comment by potiuk** [comment]
I think it's bette to redo this fix after #34945 - that one seems almost ready and I think fixing the problem you mentioned will be a bit different once it is merged.

**Comment by uranusjr** [comment]
Also please set up pre-commit locally and correct the coding style issues. See the contribution guide for details.

**Comment by pavansharma36** [comment]
Will raise new PR

**Pull request closed without merging**
