### PR TITLE
[AIRFLOW-5565] Add boto extraArgs to S3Hook load_bytes and load_file_obj

### PR DESCRIPTION
**Pull request by maxcountryman**
This patch allows callers to specify their own `ExtraArgs` dictionary.

### CODE REVIEW

**Comment by OmerJog** [comment]
Please open a Jira ticket (any code change require Jira ticket for tracking) also it needs to be something that people will understand from change log something like:
"Add extraArgs dict to S3Hook".

edit your commit message with : 
[AIRFLOW -$JIRANUMBER] Add extraArgs dict to S3Hook

And please add tests to the added functionality

**Comment by maxcountryman** [comment]
@OmerJog please review the change: it should not require additional tests if this module is already tested since it’s just passing down to boto3 and I certainly hope Airflow is not attempting to test boto itself...

If you create the Jira ticket I can update the commit accordingly.

**Comment by OmerJog** [comment]
@feluelle can take a look?

**Comment by feluelle** [comment]
Hey @maxcountryman, I created a [Jira Ticket](https://issues.apache.org/jira/browse/AIRFLOW-5565) for you.

We currently do not test for the `extra_args` according to coverage of [load_bytes](https://codecov.io/gh/apache/airflow/src/master/airflow/hooks/S3_hook.py#L498) and [load_file_obj](https://codecov.io/gh/apache/airflow/src/master/airflow/hooks/S3_hook.py#L536) but I would greatly appreciate it if we do. Because otherwise your change is not guaranteed to work as you expect it to be in the future. :)

Please update the commit message after you've added tests to include the Ticket Id. Thanks.

**Comment by OmerJog** [comment]
@maxcountryman  ping

**Pull request closed without merging**
