### PR TITLE
Print the key name when max_length is exceeded

### PR DESCRIPTION
**Pull request by jabbera**
We had the ambiguous error show up in our logs: airflow.exceptions.AirflowException: The key has to be less than 250 characters. We had a task_id >= 250 characters and it was because of long task group names and some nesting. The log message was not helpful in pointing out where the error was. Adding the key value to the exception was super helpful diagnosing where the issue was.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @o-nikolas re our discussions with long task_id and MySQL.

**Comment by potiuk** [comment]
Can you please fix the unit test @jabbera ?

**Comment by jabbera** [comment]
> Can you please fix the unit test @jabbera ?

Should be all set.

**Comment by o-nikolas** [comment]
> cc: @o-nikolas re our discussions with long task_id and MySQL.

Thanks @potiuk! Looking :eyes:

**Review by potiuk — APPROVED** [review]

**Pull request merged**
