### PR TITLE
[AIRFLOW-1275] Fix `airflow pool` command exception

### PR DESCRIPTION
**Pull request by skudriashev**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following
    - [AIRFLOW-1275](https://issues.apache.org/jira/browse/AIRFLOW-1275) Fix `airflow pool` command exception

### Description
- [x] Here are some details about my PR:
According to request from @bolkedebruin moved pool cli code into experimental API.

```
$ airflow pool
╒════════╤═════════╤═══════════════╕
│ Pool   │ Slots   │ Description   │
╞════════╪═════════╪═══════════════╡
╘════════╧═════════╧═══════════════╛
$ airflow pool -s foo 1 test
╒════════╤═════════╤═══════════════╕
│ Pool   │   Slots │ Description   │
╞════════╪═════════╪═══════════════╡
│ foo    │       1 │ test          │
╘════════╧═════════╧═══════════════╛
$ airflow pool -g foo
╒════════╤═════════╤═══════════════╕
│ Pool   │   Slots │ Description   │
╞════════╪═════════╪═══════════════╡
│ foo    │       1 │ test          │
╘════════╧═════════╧═══════════════╛
$ airflow pool
╒════════╤═════════╤═══════════════╕
│ Pool   │   Slots │ Description   │
╞════════╪═════════╪═══════════════╡
│ foo    │       1 │ test          │
╘════════╧═════════╧═══════════════╛
$ airflow pool -x foo
Pool 'foo' deleted
```

### Tests
- [x] Added the following tests:
    - tests.core:CliTests.test_pool_create
    - tests.core:CliTests.test_pool_get
    - tests.core:CliTests.test_pool_delete
    - tests.core:CliTests.test_pool_no_args
    - tests.api.client.test_local_client:TestLocalClient.test_get_pool
    - tests.api.client.test_local_client:TestLocalClient.test_get_pools
    - tests.api.client.test_local_client:TestLocalClient.test_create_pool
    - tests.api.client.test_local_client:TestLocalClient.test_delete_pool
    - tests.api.common.experimental.test_pool
    - tests.www.api.experimental.test_endpoints:TestPoolApiExperimental

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Overall ok, but I would have liked it to be moved to the API instead of a reimplementation in the cli?

**Comment by skudriashev** [comment]
@bolkedebruin, can we maybe merge this for now and move to API in separate PR? Because my intention was to fix the exception and to maybe it more line connections now. If you want to move I think it is better to do in separate PR.

**Comment by bolkedebruin** [comment]
That would be next generation legacy then, which I am not too enthusiastic about. It isn't too big of a deal to move it, I think?

**Comment by skudriashev** [comment]
@bolkedebruin, so what you propose?

**Comment by bolkedebruin** [comment]
Please move actual code to api/common/experimental/pools.py and expose it in api/client/*_client.py then update cli.py to use the api.

**Comment by skudriashev** [comment]
@bolkedebruin, ok, thanks for the explanation, will try to do :+1:

**Comment by bolkedebruin** [comment]
Nice. LGTM. Can you rebase please so I can merge?

**Comment by skudriashev** [comment]
@bolkedebruin, sure. One moment.

**Comment by skudriashev** [comment]
@bolkedebruin, done.

**Pull request closed without merging**
