### PR TITLE
[AIRFLOW-606] Add requirements.txt for airflow-pr

### PR DESCRIPTION
**Pull request by ldct**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-606](https://issues.apache.org/jira/browse/AIRFLOW-606)

Testing Done:
- Ran `sudo pip install -r requirements.txt`

### CODE REVIEW

**Comment by r39132** [comment]
+1

**Comment by r39132** [comment]
@zodiac Please pin all (2) of the dependencies in this file. When specifying dependencies, we need to be more strict about version compatibilities, otherwise we risk finding ourselves in a similar situation with the main setup.py. Specifying a range of versions is fine, but currently, no versions are provided.

**Comment by r39132** [comment]
@zodiac Please update this within the next 2 days, else I will close for inactivity.

**Comment by ldct** [comment]
updated with version ranges

**Comment by r39132** [comment]
+1

**Pull request closed without merging**
