### PR TITLE
Do not break the build when coveralls flaps in the wind

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by criccomini** [comment]
+1 Though, curious, what exactly is the point of coveralls.

**Comment by mistercrunch** [comment]
Coveralls keeps track of unit test code coverage. At each PR / commit we get a report to see whether coverage is going up/down and what lines aren't covered.

**Comment by criccomini** [comment]
No, I meant more, is anyone paying attention to it? If we're disabling it for PRs because it's failing constantly. Kind of feels like those non-deterministic tests that people end up disabling and ignoring. Why not just delete it? I guess it provides some value since we can check periodically, but, seems pretty limited.

**Comment by bolkedebruin** [comment]
Why dont we switch to https://codecov.io? It seems more stable and provides the same kind of service. Unfortunately I cannot do it as I need to be able to add the airflow repo to it.

**Comment by jlowin** [comment]
@mistercrunch deep irony but:
https://travis-ci.org/airbnb/airflow/jobs/120799766

```
py27-cdh-airflow_backend_postgres runtests: commands[8] | bash -c coveralls || exit 0
WARNING:test command found but not installed in testenv
  cmd: /bin/bash
  env: /home/travis/build/airbnb/airflow/.tox/py27-cdh-airflow_backend_postgres
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
'url'
ERROR: InvocationError: '/bin/bash -c coveralls || exit 0'
___________________________________ summary ____________________________________
ERROR:   py27-cdh-airflow_backend_postgres: commands failed
```

**Comment by artwr** [comment]
@mistercrunch Pretty sure we can close this no?

**Pull request closed without merging**
