### PR TITLE
Expose device_requests to DockerOperator - Enable GPU support

### LINKED ISSUE #9492: DockerOperator support for Nvidia-Docker
**Description**

Offer support for [Nvidia-Docker](https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)). I'm not sure how feasible this is b/c it seems like docker's python package doesn't support the gpus flag ([related issue w/ docker's python package](https://github.com/docker/docker-py/issues/2395)). Although it does appear to be on their radar ([this PR](https://github.com/docker/docker-py/pull/2471))

**Use case / motivation**
Support running GPU accelerated docker operators. This would also be useful to folks looking to run tasks in parallel on separate GPUs.

### PR DESCRIPTION
**Pull request by TediPapajorgji**
This PR adds the ability to pass `device_requests` to the DockerOperator during initialization. This is useful for enabling GPU support in the DockerOperator.

This also opens the door to exposing all other host resources to the docker container.

As an example, with this change, here is how one could expose all GPU's on the host machine to the docker container:
```
train = DockerOperator(
        task_id='<your-id>',
        image='<your-image>',
        api_version='auto',
        auto_remove=True,
        command='<your-command'>,
        device_requests=[
                docker.types.DeviceRequest(count=-1, capabilities=[['gpu']]) # Add all gpu's to the container
            ]
    )
```

closes: https://github.com/apache/airflow/issues/9492

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by TediPapajorgji** [comment]
just fixed tests, my apologies

**Comment by uranusjr** [comment]
Please fix the static check failures.

**Comment by potiuk** [comment]
Yep. I recommend to install pre-commit.

**Comment by TediPapajorgji** [comment]
> Yep. I recommend to install pre-commit.

Hey guys i'll do this today.

**Comment by eladkal** [comment]
@TediPapajorgji  you will need also to rebase and resolve conflicts

**Comment by TediPapajorgji** [comment]
@eladkal done!

**Comment by potiuk** [comment]
Also  - the updates to Changelog are not needed (and a bit harmful). The decision of version bump and changelog are generated (semi-automatically) by the release manager when the provider is released so please remove it from this change.

**Comment by wcwt** [comment]
Hi Team, How can I update this version of docker? 
I saw the [update_list](https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/commits.html) is still version `2.5.1`
Should it be `2.5.2` after this function is ok?

**Comment by eladkal** [comment]
@wcwt this PR wasn't merged it.

@TediPapajorgji can you revert changes to `CHANGELOG.rst` and `provider.yml`?

**Comment by TediPapajorgji** [comment]
> @wcwt this PR wasn't merged it.
> 
> @TediPapajorgji can you revert changes to `CHANGELOG.rst` and `provider.yml`? 

Yep I'll do it today.

**Comment by eladkal** [comment]
Also if possible to add a unit test / add coverage for this change in an existed test.
Mayve https://github.com/apache/airflow/blob/76d6089887919765c1d431c07e53a33f2c16de01/tests/providers/docker/operators/test_docker.py#L73 can coverage this change too?

**Comment by eladkal** [comment]
@TediPapajorgji would love to merge this PR.
can you address it?

**Comment by eladkal** [comment]
@danycohensa you can checkout @TediPapajorgji branch and re PR the fix (thus it will still give credit to the original author).

**Comment by eladkal** [comment]
Closing in favor of https://github.com/apache/airflow/pull/23554

**Comment by happyhooter** [comment]
@eladkal when the next release with updated DockerOperator is planned?

**Pull request closed without merging**
