### PR TITLE
Bump sshtunnel to current release

### LINKED ISSUE #16699: ssh provider limits to an old version of sshtunnel
ssh provider has limit to sshtunnel  < 0.2
https://github.com/apache/airflow/blob/9d6ae609b60449bd274c2f96e72486d73ad2b8f9/setup.py#L451

I don't know why? sshtunnel  already released 0.4
I didn't open PR because I don't know this provider i just tried to install it and couldn't due to conflicts with other requirements in my system so eventually i used vitrual env to solve my problem but logging this issue so that someone who knows this code can handle it.

### PR DESCRIPTION
**Pull request by dash-stefan-petrescu**
Bump sshtunnel from 0.2 to 0.4 (current release).

Fixes #16699

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Some unit tests are failing, so either the tests or the code (or both) need to be fixed

**Comment by uranusjr** [comment]
Seems like sshtunnel changed something about auth (not sure what)

**Comment by eladkal** [comment]
@dash-stefan-petrescu can you fix the failing tests?

**Comment by dash-stefan-petrescu** [comment]
@potiuk All looks good now

**Comment by potiuk** [comment]
Not really - there is one intermittent error with scheduler job, but SSH tests are still failing:

https://github.com/apache/airflow/pull/16858/checks?check_run_id=3231953118#step:6:13691

**Pull request closed without merging**
