### PR TITLE
[AIRFLOW-891] Make webserver clock include date

### PR DESCRIPTION
**Pull request by sekikn**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-891

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Currently the webserver clock has only hour and minute.
We change the clock format to "yyyy-MM-dd HH:mm:ss",
because date information is helpful for user and
this format is universal.

I updated jqClock.min.js with the latest version for now
(https://github.com/JohnRDOrazio/jQuery-Clock-Plugin/tree/v2.3.0).
screen shot 2017-06-26 at 1 38 16

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Added no test. Instead, I ran webserver manually and confirmed the clock was displayed expectedly. Also, I confirmed all unit tests passed.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by msumit** [comment]
+1

**Comment by sekikn** [comment]
Thanks for the review @msumit! Could you merge this PR?

**Comment by msumit** [comment]
@sekikn done.

**Comment by sekikn** [comment]
@msumit Thanks!

**Pull request closed without merging**
