### PR TITLE
[AIRFLOW-4412] PodLauncher drops log lines printed by the pod

### PR DESCRIPTION
**Pull request by smrt28**
### Jira

https://issues.apache.org/jira/browse/AIRFLOW-4412

### Description

- tails entire log instead of just last 10 lines
- right-trims all the log lines read from kubernetes to remove annoying '\n' character

### CODE REVIEW

**Comment by dimberman** [comment]
@smrt28 could you rebase/fix failures? otherwise I'm good to merge this.

**Comment by ashb** [comment]
```
======================================================================
1) FAIL: test_logging (tests.minikube.test_kubernetes_pod_operator.KubernetesPodOperatorTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/minikube/test_kubernetes_pod_operator.py line 269 in test_logging
      mock_logger.info.assert_any_call(b"+ echo 10")
    /usr/local/lib/python3.6/unittest/mock.py line 876 in assert_any_call
      ) from cause
   AssertionError: info(b'+ echo 10') call not found
======================================================================
2) FAIL: test_volume_mount (tests.minikube.test_kubernetes_pod_operator.KubernetesPodOperatorTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/minikube/test_kubernetes_pod_operator.py line 314 in test_volume_mount
      mock_logger.info.assert_any_call(b"retrieved from mount")
    /usr/local/lib/python3.6/unittest/mock.py line 876 in assert_any_call
      ) from cause
   AssertionError: info(b'retrieved from mount') call not found
```

**Comment by mik-laj** [comment]
Hi. Could you do rebase? I also planned to deal with this problem. https://github.com/PolideaInternal/airflow/issues/268

**Comment by smrt28** [comment]
@mik-laj I spent a hour fixing those broken tests. I realized it would be too big effort for me to investigate how all those tests work and how to fix them. Please, feel free to take the ticket and finish it. The project which uses airflow in my company was postponed and I have no time and even the environment for fixing this. Sorry.

**Comment by mik-laj** [comment]
No problem. I will do it. Thanks you.

**Comment by mik-laj** [comment]
can you say why the project was postponed?  is it due to implementation problems? What problems have arisen?

**Comment by smrt28** [comment]
it was just a corporate decision, nothing to do with airflow. I got a task to find a propper job scheduler for our purpose and af was the one of those I discovered. I just found those issues during the investigation. FYI it remains the favorite one ;-)

**Pull request closed without merging**
