### PR TITLE
[AIRFLOW-5066] allow k8s fieldref substitution

### PR DESCRIPTION
**Pull request by jsurloppe**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5066

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
That PR change the order of setting env vars in kubernetes definition to allow substitution with pod metadata.

### Tests

- [x]  does not need testing for this extremely good reason:
Airflow behavior doesn't change, it's just a matter kubernetes API call.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by potiuk** [comment]
@jsurloppe - Would it be possible to add test for this ? I think it should be rather easy one. If we do not have tests, then it might be a lottery to cherry-pick it to the 1.10.x branch even if it works in master.

**Comment by dimberman** [comment]
@jsurloppe I agree with @potiuk. Besides that I'm good to merge this.

**Comment by jsurloppe** [comment]
You're both right, it was faster than expected, test added. :)

**Review by dimberman — APPROVED** [review]
LGTM. @potiuk anything left on your end?

**Comment by mik-laj** [comment]
@jsurloppe  Can you do rebase? I would like to merge these changes 

@potiuk ping

**Comment by mik-laj** [comment]
@jsurloppe  1624 commits. Too much 😿

**Comment by jsurloppe** [comment]
@mik-laj a little yes, didn't expect that much when i switched the target tranch, shouldn't have done it before the rebase.

Anyway, i don't do that PR on master anymore, it needs testing but from what i see, i think the refactor will work without that patch as it doesn't seem to enforce order of creation of env var.

So this is only needed for current stable airflow (with kubernetes in `contrib`)

**Comment by mik-laj** [comment]
@jsurloppe Travis is sad. Can you fix it?

**Comment by jsurloppe** [comment]
correct me if i'm wrong, but it's seems that the errors are related to the current state of the `v1-10-stable` branch, the code and tests introduced in that PR passes.

**Comment by OmerJog** [comment]
@jsurloppe could be. I see failures due to some imports.
Can you rebase to re trigger tests the issues may have been already fixed.

**Comment by jsurloppe** [comment]
@OmerJog done, travis seems happy now :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
