### PR TITLE
AIP-47 - Migrate Airbyte DAGs to new design

### PR DESCRIPTION
**Pull request by chethanuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Static checks failing.

**Comment by chethanuk-plutoflume** [comment]
I have no idea how to fix this conflicts. It says:

```bash
All ok. The docs/apache-airflow-providers-apache-sqoop/index.rst does not contain system tests.

Checking docs/apache-airflow-providers-airbyte/index.rst
The docs/apache-airflow-providers-airbyte/index.rst does not contain System Tests TOC.

Make sure to add those lines to docs/apache-airflow-providers-airbyte/index.rst:


.. toctree::
    :hidden:
    :caption: System tests

    System Tests <_api/tests/system/providers/airbyte/index>

Checking docs/apache-airflow-providers-singularity/index.rst
All ok. The docs/apache-airflow-providers-singularity/index.rst contains hidden index.
```

**Comment by potiuk** [comment]
Just copying the exact instructions:

```
Make sure to add those lines to docs/apache-airflow-providers-airbyte/index.rst:


.. toctree::
    :hidden:
    :caption: System tests

    System Tests <_api/tests/system/providers/airbyte/index>
```

**Comment by potiuk** [comment]
@chethanuk-plutoflume - I am not sure what the problem is - but the instructions are pretty self-explanatory. Am I missing something?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
