### PR TITLE
Airflow 2.7.2 has been released

### PR DESCRIPTION
**Pull request by ephraimbuddy**

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
I'm not sure why the build images workflow is getting cancelled. Any ideas?
cc @potiuk

**Comment by potiuk** [comment]
Still traveling, but this should fix it: https://github.com/apache/airflow/pull/34918

**Comment by potiuk** [comment]
(at least CI image `pip` backtracting).

**Comment by ephraimbuddy** [comment]
> Still traveling, but this should fix it: #34918

Thanks!

**Pull request merged**
