### PR TITLE
[AIRFLOW-2563] Fix PigCliHook Python 3 string/bytes use

### PR DESCRIPTION
**Pull request by jakahn**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. F
    - https://issues.apache.org/jira/browse/AIRFLOW-2563

### Description
- [X] This PR fixes PigCliHook's Python 2-style use of strings where Python 3 requires (or returns) a bytes-like object. It also introduces unit tests for PigCliHook, which were missing.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
   - `tests/hooks/test_pig_hook.py`

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] No new non-test files or new functionality.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jakahn** [comment]
The failing test appears to have been a flake (Travis reports a 10 minute period of no output on an unrelated test; all tests pass on my fork).

**Comment by Fokko** [comment]
Please link to your fork instead of retriggering every time.

**Comment by jakahn** [comment]
Sure, sorry about that!
- Travis: https://travis-ci.org/jakahn/incubator-airflow
- Fork: https://github.com/jakahn/incubator-airflow

**Comment by jakahn** [comment]
Just bumping since it's been ~2 weeks

**Comment by artwr** [comment]
LGTM +1

**Pull request closed without merging**
