### PR TITLE
[AIRFLOW-3648] Default to connection project id in gcp cloud sql.

### PR DESCRIPTION
**Pull request by jmcarp**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3648
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by jmcarp** [comment]
@potiuk I see you're working on this too. I thought I would break this up into several small patches for easier review. WDYT?

**Comment by potiuk** [comment]
Hey @jmcarp. I actually promised to @kaxil that I will do it this week, and I have already done it yesterday :).  Including system testing with real GCP project for all operators we developed for GCP. 

I have a big internal PR opened with 15 separate commits where this is fixed https://github.com/PolideaInternal/airflow/pull/29.  I have started with @kaxil discusion on the best way how it can be split so it can be reviewed fast and quickly and that we can also merge the changes which allow us to run automatically System Tests with real GCP project for all GCP-related operators. 

The cloud SQL one is implemented as separate commit https://github.com/PolideaInternal/airflow/pull/29/commits/097f024e1960ec1ab47e980fef2aba5bdafe3e02 in the (so far big) PR. Please do not comment it just yet, it's very likely it will be split to at least 3 or 4 PRs or maybe more. It includes unit tests changes, it also changes the example dags (allowing to run automated system tests) and shows examples of how you can create the operators in the official documention - showing examples with and without project_id.

My change is done slightly differently: rather than adding project_id=None to hooks I've only changed the operators interface and added a decorator in the hooks that adds project_id from the hook automatically if it is set to None. This is a bit nicer I think because the logic to set the project_id is done in one place only (in the decorator) common for all the operators and you do not have to remember to handle it in all hooks separately. You just need to document that project_id can be none. I could also think about reverting the parameters in hook and having project_id = None as you did, but I thought it's not worth it (but I might reconsider). We have the full automated suite of system tests and automated cloud build that performs the tests on push to our repo (https://storage.googleapis.com/polidea-airflow-builds/56d1ea7c-20c9-4619-8d23-7d0d1c597059/index.html you can see an example success after running System Tests for all GCP operators). And here you can see the documentation generated automatically during that verification build: https://storage.googleapis.com/polidea-airflow-builds/56d1ea7c-20c9-4619-8d23-7d0d1c597059/docs/howto/operator.html#cloudsqlinstancedatabasecreateoperator where you can see that we have now examples with and without project_id.

**Comment by potiuk** [comment]
Also @jmcarp  the decorator you can see added in the gcp_function commit slightly before in the chain: https://github.com/PolideaInternal/airflow/pull/29/commits/7b18693b5fed08c8211eeba7653a3075141d7f4a#diff-aeef6fae3fb1fdb6e4663b68518b0d3aR156  - it's reused for all the GCP operators in the same way.

**Review by potiuk — CHANGES_REQUESTED** [review]
I'd hold on with this one until we decide what to do with https://github.com/PolideaInternal/airflow/pull/29  as it implements the same functionality slightly diiferently and consistently for all the GCP operators.

**Comment by potiuk** [comment]
@jmcarp - one more question - maybe you would like to be involved in polishing and testing out GCP-rwoated environment for Airflow. We have a super easy to run (we think) environment which allows you to easily system test GCP related operator changes - you just need a GCP project id and it will set everything up for you - including this automated Cloud Build that will run a suite of your system tests automatically in container environment and in local IDE and notify you via slack/build you the kind of summary page I linked above. It's rather easy to use and extensively documented : https://github.com/PolideaInternal/airflow-breeze ? What do you think ?

**Comment by jmcarp** [comment]
Thanks for taking care of this @potiuk!

**Pull request closed without merging**
