### PR TITLE
Remove duplicated py37 in dev/breeze/pyproject.toml

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by uranusjr** [comment]
Need to fix the static checks job

**Comment by potiuk** [comment]
> Need to fix the static checks job

Ah. Still do not know why this happens - seems that breeze is installed but then it cannot find the breeze's metadata in "basic-static-checks" - it puzzles me quite a bit :)

**Comment by potiuk** [comment]
Ah ... I know. .. Github Checkout action that is fetching the parent commit remvoves .egg-info 🤦

**Comment by potiuk** [comment]
The bad thing about it is that we will not test it in this PR - because ... After modifying the ci.yml it does not run only basic static chacks any more :).

**Pull request merged**
