### PR TITLE
[AIRFLOW-71] Instantiating Docker Client at constructor, permitting the use of thi…

### PR DESCRIPTION
**Pull request by felipetancredo**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-71
- Instantiating Docker Client at constructor, permitting the use of this one before the execute method.
  e.g.:
  d = DockerOperator(
      task_id='example_task_id',
      image='image_name',
      force_pull=True,
      owner='felipetancredo',
      command="example.py {{ execution_date }} {{ execution_date }}"
  )
  if d.cli:
      d.cli.login(username='usr', password='pwd', registry='https://example.registry.com', reauth=True)
- the change will allow login as required by private registries (like AWS ECR)

### CODE REVIEW

**Comment by asnir** [comment]
https://github.com/apache/incubator-airflow/pull/1806

**Comment by jlowin** [comment]
Is this a duplicate of #1806?

**Comment by asnir** [comment]
@felipetancredo, first of all, you are right. Your solution will solve the open issue. Personally i prefer that the operator will handle it.
@jlowin, https://github.com/apache/incubator-airflow/pull/1806 solves couple of issues, including this [one](https://issues.apache.org/jira/browse/AIRFLOW-71).

**Comment by jlowin** [comment]
@felipetancredo Will #1806 work for you? I think as a matter of style we prefer to have all logic encapsulated inside the operator. It's true that you can always interact with any operator from the DAGfile, as you demonstrate in your example, but it's harder to document/example/test.

**Comment by felipetancredo** [comment]
It's OK for me @jlowin...
Tks
Regards
Felipe

On Fri, Nov 4, 2016, 12:59 AM Jeremiah Lowin notifications@github.com
wrote:

@felipetancredo https://github.com/felipetancredo Will #1806
https://github.com/apache/incubator-airflow/pull/1806 work for you? I
think as a matter of style we prefer to have all logic encapsulated inside
the operator. It's true that you can always interact with any operator from
the DAGfile, as you demonstrate in your example, but it's harder to
document/example/test.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/apache/incubator-airflow/pull/1854#issuecomment-258333470,
or mute the thread

**Comment by jlowin** [comment]
@felipetancredo I think this should be closed in favor of #1877 which seems to have replaced #1806.

**Comment by russellpierce** [comment]
Given that this issue is marked as [resolved on JIRA](https://issues.apache.org/jira/browse/AIRFLOW-71) may we close this corresponding PR?

**Comment by felipetancredo** [comment]
It's ok for me...

**Comment by artwr** [comment]
Unfortunately on the new infra we cannot close PR ourselves. @felipetancredo, you can do it on your side if that's ok :)

**Comment by felipetancredo** [comment]
Done 😄

**Pull request closed without merging**
