### PR TITLE
[AIRFLOW-2186] Change the way logging is carried out in few ops

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2186

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- Changed the way logging is implemented in `PostgresToGoogleCloudStorageOperator` and `HiveToDynamoDBTransferOperator`.  Changed `logging.info` to `self.log.info`

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Minor change. Doesn't require testing

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @Fokko PTAL. The Travis CI fails as `apache-beam[gcp]` is not available for Python 3.

**Comment by Fokko** [comment]
@kaxil The `apache-beam` issue has been fixed in master.

**Comment by kaxil** [comment]
@Fokko haha yes, I fixed that in a PR  😉  💃 . Thanks for merging this.

**Comment by Fokko** [comment]
@kaxil Didn't had my coffee yet ;) Thanks!

**Pull request closed without merging**
