### PR TITLE
[AIRFLOW-2400] Add Ability to set Environment Variables for K8s

### PR DESCRIPTION
**Pull request by jkao**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2400\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2400
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
This allows a user to add environmnent variables to the Pod from the invoker of the KubernetesPodOperator.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This adds an additional parameter, similar to https://github.com/apache/incubator-airflow/commit/72f15a108e5556970229cb68d3b0968ee18db46e.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by wileeam** [comment]
Awesome! Was missing this while I have been reviewing the K8s executor.
You may want to squash your commits :)

**Review by Fokko — APPROVED** [review]
@jkao I'll squash them for you. Thanks!

cc @dimberman

**Comment by dimberman** [comment]
@Fokko thanks for the cc

@jkao ahh good catch! Definitely an important aspect of launching custom pods :).

**Comment by Fokko** [comment]
To master!

**Pull request closed without merging**
