### PR TITLE
Create GKEStartJobOperator and KubernetesJobOperator

### PR DESCRIPTION
**Pull request by MaksYermak**
In this PR I have created operators for starting Kubernetes Job in clusters(ordinary and GKE).

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Could you merge/rebase main?

**Comment by eladkal** [comment]
There was a discussion about this capability in https://github.com/apache/airflow/issues/17490

**Comment by MaksYermak** [comment]
> Could you merge/rebase main?

Sure, I have rebased the branch.

**Comment by raphaelauv** [comment]
:+1: 

would be great to also add some doc there -> https://github.com/apache/airflow/pull/36847

like KPO vs KOJ ...

**Comment by dirrao** [comment]
> 👍
> 
> would be great to also add some doc there -> #36847
> 
> like KPO vs KOJ ...

Yes. It would be great to document when to prefer KJO over KPO.

**Comment by MaksYermak** [comment]
@dirrao @raphaelauv @hussein-awala I have updated documentation for `KubernetesJobOperator`. Could you review my PR one more time?

**Comment by VladaZakharova** [comment]
Hi @eladkal !
Could you please take a look on these changes? Thanks!

**Comment by MaksYermak** [comment]
> Hey @VladaZakharova @MaksYermak - can you rebase please? Conflicts got in the way after I merged #37072

Hi, I have rebased the branch.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
