### PR TITLE
[AIRFLOW-248] Add Apache license header to all files

### PR DESCRIPTION
**Pull request by ajayyadava**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-248

Testing Done:
- No new tests were added

Reminders for contributors:
- Your PR's title must reference an issue on [Airflow's JIRA](https://issues.apache.org/jira/browse/AIRFLOW/). For example, a PR called "[AIRFLOW-1] My Amazing PR" would close JIRA issue #1. Please open a new issue if required!
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules).

Added Apache license header for files with extension (.service, .in, .mako, .properties, .ini, .sh, .ldif, .coveragerc, .cfg, .yml, .conf, .sql, .css, .js, .html, .xml.
Added/Replaced shebang on all .sh files with portable version - #!/usr/bin/env bash.
Skipped third party css and js files. Skipped all minified js files as well.

### CODE REVIEW

**Comment by ajayyadava** [comment]
@bolkedebruin The failures are only in certain environments and not consistent. I suspect it is not because of my changes. Can you please confirm? Thanks!

**Comment by criccomini** [comment]
Failed test is:

```
[2016-06-16 10:40:07,091] {sequential_executor.py:40} INFO - Executing command: airflow run test_depends_on_past test_dop_task 2016-01-06T00:00:00 -I --local -sd DAGS_FOLDER/test_issue_1225.py 
[2016-06-16 10:40:07,662] {__init__.py:50} INFO - Using executor SequentialExecutor
Logging into: /home/travis/airflow/logs/test_depends_on_past/test_dop_task/2016-01-06T00:00:00
[2016-06-16 10:40:11,787] {__init__.py:50} INFO - Using executor SequentialExecutor
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/bin/airflow", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/travis/build/apache/incubator-airflow/airflow/bin/airflow", line 15, in <module>
    args.func(args)
  File "/home/travis/build/apache/incubator-airflow/airflow/bin/cli.py", line 247, in run
    run_job.run()
  File "/home/travis/build/apache/incubator-airflow/airflow/jobs.py", line 174, in run
    self._execute()
  File "/home/travis/build/apache/incubator-airflow/airflow/jobs.py", line 1112, in _execute
    self.heartbeat()
  File "/home/travis/build/apache/incubator-airflow/airflow/jobs.py", line 156, in heartbeat
    session.commit()
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 706, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/travis/build/apache/incubator-airflow/.tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE job SET latest_heartbeat=? WHERE job.id = ?'] [parameters: ('2016-06-16 10:40:13.210089', 3)]
[2016-06-16 10:40:18,329] {sequential_executor.py:47} ERROR - Failed to execute task Command 'airflow run test_depends_on_past test_dop_task 2016-01-06T00:00:00 -I --local -sd DAGS_FOLDER/test_issue_1225.py ' returned non-zero exit status 1:
[2016-06-16 10:40:19,365] {jobs.py:968} ERROR - Task instance ('test_depends_on_past', 'test_dop_task', datetime.datetime(2016, 1, 6, 0, 0)) failed
[2016-06-16 10:40:19,365] {jobs.py:1041} INFO - [backfill progress] | waiting: 0 | succeeded: 0 | kicked_off: 1 | failed: 1 | skipped: 0 | deadlocked: 0
[2016-06-16 10:40:19,366] {base_executor.py:92} DEBUG - 0 running task instances
```

Indeed, this has nothing to do with you. Are you rebased to head right now?

I'm going to send an email to dev@ to notify of this, since it will break a ton of PRs due to silly merge conflicts. I will give 1d, and circle back tomorrow to merge this in.

**Comment by ajayyadava** [comment]
@criccomini Thanks for looking into it. I just tested applying the commit on latest master and it applies without any errors.

**Comment by criccomini** [comment]
Oops, looks like merge conflicts. Likely after @jlowin's AIRFLOW-31 changes.

**Comment by jlowin** [comment]
Whoops I apologize I didn't think about the license overlap. Appreciate all the work @ajayyadava -- let's merge all the others!

**Comment by ajayyadava** [comment]
No worries @jlowin @criccomini I have rebased the pull request with master and there are no conflicts now, verified that there are no code/import changes after rebase.

**Comment by jlowin** [comment]
Looking good. I think @criccomini will merge after notifying folks.

**Comment by ajayyadava** [comment]
Hi @criccomini @jlowin, it seems that the branch again went out of sync because of recently committed changes. 😞  I will rebase the branch again, if you could prioritise this pr, it will be immensely helpful.

**Comment by ajayyadava** [comment]
I have rebased the pull request. The test failure seems to be an arbitrary failure.

**Comment by criccomini** [comment]
Argh @ajayyadava, I'm so sorry that this keeps falling out of sync! Can you msg me on Gitter when it's ready to be mergd?

**Comment by criccomini** [comment]
(and to any of the other committers: feel free to merge if you see that it doesn't have any conflicts)

**Comment by bolkedebruin** [comment]
One thing I wonder with the html templates if the license will now occur multiple times in the generated html? I think that would be undesirable? Also the commit message itself should refer to the Jira.

Thanks btw @ajayyadava !.

**Comment by ajayyadava** [comment]
@bolkedebruin Thank you for the keen review. Both of your observations are spot-on and thanks for catching them. I will fix the commit message. As for the license appearing multiple times in generated html we can not avoid putting license headers in child/derived templates, so I think we should change syntax from html comment to jinja comment. Let me know if you have something better in mind.

**Comment by ajayyadava** [comment]
@bolkedebruin While debugging, I noticed that the pr tool does prefix the jira to the commit message as it picks the commit message from the PR description and not the commit message. Though I still agree with you that the commit message should also contain the JIRA id (will help committers if they choose to apply manually)

Also, if you don't select the squash option while using the PR tool, it not only messes the commit message (puts message as "Merge pull request #.... from ..."), it also doesn't retain the original author of the commit. I will raise a JIRA and send a PR for this.

CC @criccomini

**Comment by ajayyadava** [comment]
@bolkedebruin I have fixed the commit message and also fixed the issue of multiple license header in the generated html. I verified the license in generated HTML by viewing page source of a page in each of the tabs of the ui. 

Please review and let me know.

**Comment by criccomini** [comment]
LGTM merged!

**Comment by jlowin** [comment]
Thanks @ajayyadava!

**Pull request closed without merging**
