### PR TITLE
[#20815] DAG.default_args.catchup is not working... 

### PR DESCRIPTION
**Pull request by seunggabi**
what is different?
default_args vs !default_args

I think, default_args support all of DAG fields

---

Thank you for contributing! Please make sure that your code changes
are covered with tests. And in case of new features or big changes
remember to adjust the documentation.

Feel free to ping committers for the review!

In case of an existing issue, reference it using one of the following:

closes: #28015
related: #28015

How to write a good git commit message:
http://chris.beams.io/posts/git-commit/

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by seunggabi** [comment]
### please check pr
- I made `test_catchup`
- Can I make every test cast arg by arg?

**Comment by potiuk** [comment]
Could you please update the description and title of the PR (and commit) if you want to get it reviewed? As it is now, I had no idea what should be reviewed because neither title nor description says anything useful, so I have completely no idea what your intention was.

**Comment by uranusjr** [comment]
I don’t think we want to implement this. DAG arguments and default args are different things and this introduces complexity that is unnecessary at best.

**Comment by seunggabi** [comment]
@potiuk @uranusjr 
Thanks for attention.

```python
        if "params" in self.default_args:
            params.update(self.default_args["params"])
            del self.default_args["params"]
```

`params` is hybrid property (default_args or !default_args).
I think it's the beginning of a misunderstanding.

So, I suggest this PR. (about extend default_args)

**Comment by potiuk** [comment]
Please describe what you want to achieve in full sentences and describe the context. I have completely no idea what you want to achieve and why. 

Closing until intentions are clear and explained in understandable way.

**Comment by seunggabi** [comment]
I'm sorry about poor information.

Let me explain detail.

Actually, I focused `default_arg`, for common code.
We want to reuse `DAG` by `DAG`.
```
DEFAULT_ARGS = {
    "_slack_channel": DefaultVariable.get("slack")["channel"],

    "catchup": False,

    "owner": "",
    "depends_on_past": False,
    "email": [],
    "email_on_failure": True,
    "email_on_retry": True,
    "is_paused_upon_creation": False,
    "retries": 1,
    "max_active_runs": 1,
    "retry_delay": timedelta(minutes=1),
}
```

So, I made `DefaultAirflowDAG`. (DAG.default_args.catchup is not working... #28015)

```python
from datetime import datetime, timedelta

import pendulum
from airflow import DAG

from batch.core.default_variable import DefaultVariable
from batch.utils.log_utils import LogUtils
from batch.utils.slack_utils import SlackUtils

DEFAULT_ARGS = {
    "_slack_channel": DefaultVariable.get("slack")["channel"],

    "catchup": False,

    "owner": "",
    "depends_on_past": False,
    "email": [],
    "email_on_failure": True,
    "email_on_retry": True,
    "is_paused_upon_creation": False,
    "retries": 1,
    "max_active_runs": 1,
    "retry_delay": timedelta(minutes=1),
}


def extends(default_args):
    for k in DEFAULT_ARGS:
        if k in default_args:
            continue

        default_args[k] = DEFAULT_ARGS[k]

    return default_args


class DefaultAirflowDAG(DAG):
    LOG = LogUtils.log()
    ZFILL = 4

    def __init__(
            self,
            dag_id,
            schedule_interval=None,
            description=None,
            default_args=None,
            history=None,
            start_date_args=None,
            **kwargs,
    ):
        default_args = default_args or {}

        if "start_date" not in default_args:
            start_date_args = start_date_args or [2022, 1, 1]

            default_args["start_date"] = datetime(
                *start_date_args, tzinfo=pendulum.timezone("Asia/Seoul")
            )

        kwargs["default_args"] = extends(default_args)
        kwargs["catchup"] = kwargs["default_args"]["catchup"]

        slack = SlackUtils(kwargs["default_args"]["_slack_channel"], kwargs["default_args"]["owner"])
        kwargs["on_failure_callback"] = slack.on_failure_callback

        super().__init__(dag_id=dag_id, schedule_interval=schedule_interval, **kwargs)

        self.doc_md = __doc__
        self.doc_md = DefaultAirflowDAG.make_doc_md(
            dag_id, description, schedule_interval, history
        )

    @staticmethod
    def make_doc_md(dag_id, description, schedule_interval, history):
        doc_md = f"""
=================================================================================================<br>
ID: {dag_id}<br>
-------------------------------------------------------------------------------------------------<br>
DESCRIPTION: {description}<br>
-------------------------------------------------------------------------------------------------<br>
SCHEDULE: {schedule_interval}<br>
-------------------------------------------------------------------------------------------------<br>
"""
        if history is not None:
            doc_md += """
NO | DATE | AUTH | COMMENT<br>
"""
            for i, o in enumerate(history):
                doc_md += f"""
-------------------------------------------------------------------------------------------------<br>
{str(i).zfill(DefaultAirflowDAG.ZFILL)} | {o.date} | {o.author} | {o.comment}<br>
"""
        doc_md += """
=================================================================================================<br>
"""
        return doc_md


class DagHistory:
    def __init__(self, date, author, comment):
        self.date = date
        self.author = author
        self.comment = comment

```

this is just idea.
But, I want to suggest to add this code in DAG.
That's why, making PR.

---

If we use default_args to reduce the common code of DAGs,
I think we can make a simpler DAG.

I know you're busy, but I ask for a positive review.
Thank you always.
Happy New Year~

**Pull request closed without merging**
