### PR TITLE
[AIRFLOW-6254] obscure conn extra in logs

### PR DESCRIPTION
**Pull request by dstandish**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-6254)
  - https://issues.apache.org/jira/browse/AIRFLOW-6254

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

When BaseHook.get_connection is called, it calls conn.log_info() on the returned conn object.

This is prints to log the full contents of conn.extra.

This is problematic because there can be sensitive information in conn.extra.

The present change resolves this by adding method conn.log_info which obscures extra, and calling that in get_connection instead of debug_info.

The debug_info method itself is left unchanged.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Insignificant change, no new functionality

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
I wonder if we could reasonably filter only certain fields in extra? There's a lot of non password stuff in there for most uses.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Ah. I haven't seen your comment @ashb and merged it first. I think it's dangerous to try to find the fields inside. Each connection has its own private schema and for the sake of security I think it's better to obfuscate it all. There is low risk with not showing it - user can always check connection table or variable if you are not sure if all is ok.

**Comment by dstandish** [comment]
@potiuk @ashb i suppose we could iterate `extra_dejson` and just obscure the values?  i.e. so at least keys would be displayed...  not sure it adds worthwhile benefit if the values are obscured anyway.  

i.e. `{k: 'XXXXXX' for k, _ in extra_dejson.items()}`

**Comment by potiuk** [comment]
@dstandish -> I think it's a bit too risky

**Pull request merged**
