### PR TITLE
Fix multiNamespaceMode not working with executor KubernetesExecutor

### PR DESCRIPTION
**Pull request by joshuayeung**
Currently, multiNamespaceMode is not working with executor KubernetesExecutor.
Even though we set the pod override in the executor config, the pod is still generated in the airflow namespace.
It is suggested to change the order of this pod list to make it work.

See more details:
https://github.com/apache/airflow/discussions/31990

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Could you add a new test which simulates the issue you have with the current implementation? (in [this module](https://github.com/apache/airflow/blob/48930bc0b4c159180cc55c8bd079cdfec9cedb21/tests/providers/cncf/kubernetes/test_pod_generator.py))

**Comment by joshuayeung** [comment]
> Could you add a new test which simulates the issue you have with the current implementation? (in [this module](https://github.com/apache/airflow/blob/48930bc0b4c159180cc55c8bd079cdfec9cedb21/tests/providers/cncf/kubernetes/test_pod_generator.py))

Hi @hussein-awala , I have added a test case to test this scenario

**Review by hussein-awala — APPROVED** [review]
Looks good!

**Comment by andreyolv** [comment]
Thank you very much guys for this fix 🙏

**Review by Lee-W — APPROVED** [review]

**Comment by eladkal** [comment]
helm chart tests are failing

**Pull request closed without merging**
