### PR TITLE
Use airflow user for build segment of docker image

### PR DESCRIPTION
**Pull request by potiuk**
PIP produces a warning when root user is used to run pip install.
This is done for a good reason - because installing PIP this way
clashes with a number of distro-managed python packages.

The warning cannot be disabled even if our use case is legitimate
as has been extensively discussed in
pypa/pip#10556.

The advice given by the warning is a bit misleading - it suggests
to use virtualenv, but since this is considered a bad practice
for container building and because we need to create virtualenvs
dynamically inside the image, using virtualenv is a bad solution
for us. It's been attempted in #19189 and failed.

Instead we create an airflow user and use PIP_USER="true" which
installs all dependencies in build segment to ~/.local folder
from where we can copy it to the main image.

That get rids of the warning and at the same time allows us to
keep the best practices of building the images.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
This is another smaller change separated out from the #20238

**Comment by potiuk** [comment]
cc: @ashb @uranusjr  -> even easier to review that way. I will continue adding other changes separated from #20238

**Comment by potiuk** [comment]
Looks green :)

**Comment by potiuk** [comment]
REbased to latest main. Would love re-review.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
