### PR TITLE
Switching to Ubuntu 20.04 as Github Actions runner.

### PR DESCRIPTION
**Pull request by potiuk**
Ubuntu 20.04 will soon become the default runner for GA.

See: https://github.com/actions/virtual-environments/issues/1816

This PR tests if this is working fine.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Are we planning on leaving it as `ubuntu-latest` or not?

**Comment by kaxil** [comment]
I think we should keep it as latest

**Comment by potiuk** [comment]
Yeah. Latest is fine I think. The only problem now is that we have those annoying warnings which might hide something important. So at least until migration I think we can merge it and switch back to latest when it finishes.

**Comment by potiuk** [comment]
I like to follow "no-broken-window" policy :). Here a a lot of windows are broken:

Screenshot from 2020-11-17 16-12-26

**Comment by potiuk** [comment]
Looks like all works. I'd merge it now and set a reminder to change back to latest in December

**Pull request merged**
