### PR TITLE
[AIRFLOW-964] Allow Airflow to live in a subpath

### PR DESCRIPTION
**Pull request by thomasruiz**
This commit allows Airflow to live in a subpath
under the domain. This is useful in case the application
is served by a proxy (e.g https://tools.example.com/airflow).

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-964

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
It adds a new configuration option to set the root path where the application lives. As stated 

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ghost** [comment]
Would be very useful for us as well!

**Comment by gwax** [comment]
Does adding a suffix to the `base_url` configuration property not work?

**Comment by thomasruiz** [comment]
@gwax no, to my knowledge, `base_url` is used only for email links. Maybe it could be used for this instead of adding a new configuration variable, but that would probably introduce breaking changes or unexpected behaviour for some existing installations.

**Comment by bolkedebruin** [comment]
Why is `app.config["APPLICATION_ROOT"]` not used? Per https://stackoverflow.com/questions/34849257/define-url-root-with-flask and https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes .

In addition I think this can be added to base_url and then use the path from that to set the application_root. This would then automatically apply to emails. Furthermore, please add a test.

**Pull request closed without merging**
