### PR TITLE
[AIRFLOW-6315] Create .airflow_db_initialised always in tests dir

### PR DESCRIPTION
**Pull request by turbaszek**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6315

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

I observed that directory where `. airflow_db_initialised` file is created depends on where is the test we run. The file is used by `breeze_test_helper` to keep information that db has been initialised. 
This change will keep the file always in root directory fo tests. 

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
After reboot breeze, shouldn't the database be initialized again? I think so because we have a ephemeral environment. All data except the source code and files directory is lost after reboot.

**Comment by turbaszek** [comment]
Good catch @mik-laj ! Fixed.

**Comment by potiuk** [comment]
I think it's more to that. We should not create it in the test folder because it is shared between host and container. So rather than removing it in the "entrypoint" I'd crate it in ${AIRFLOW_HOME} (fallback to ${HOME}/airflow if AIRFLOW_HOME is not defined. This is easy to create and has the benefit that if you exit the container, it will be gone. Also you can run several containers in parallel this way with independently initialized database. 

Also this way, if you ran tests in the HOST it will initialise database independently from the container.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Finally ! Good to go. Do the honors @nuclearpinguin :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
