### PR TITLE
Apply PROVIDE_PROJECT_ID mypy workaround across Google provider

### PR DESCRIPTION
**Pull request by potiuk**
There is a simple workaround implemented several years ago for Google provider `project_id` default value being PROVIDE_PROJECT_ID that satisfy mypy checks for project_id being set. They way how `fallback_to_default_project_id` works is that across all the providers the project_id is actually set, even if technically it's default value is set to None.

This is similar typing workaround as we use for NEW_SESSION in the core of Airflow.

The workaround has not been applied consistently across all the google provider code and occasionally it causes MyPy complaining when newer version of a google library introduces more strict type checking and expects the provider_id to be set.

This PR applies the workaround across all the Google provider code.

This is - generally speaking a no-op operation. Nothing changes, except MyPy being aware that the project_id is actually going to be set even if it is technically set to None.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @VladaZakharova

**Comment by potiuk** [comment]
cc: @moiseenkov

**Review by moiseenkov — APPROVED** [review]

**Comment by potiuk** [comment]
Rerunning with upgrade + full tests needed just in case.

**Review by pankajkoti — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Comment by potiuk** [comment]
Random /flaky failure . Merging. All looks good. In the future (providing we keep the approach) it should not cause unexpected mypy  issues.

**Pull request merged**
