### PR TITLE
Breeze was slightly too chatty when there was no dirs created

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
Can we wrap this under the verbosity flag that breeze has?

Can aid in debugging when needed bu otherwise LGTM

**Comment by potiuk** [comment]
> Can we wrap this under the verbosity flag that breeze has?

Actually not :( . Those dirs are created way before --verbose flag is parsed :). But I think it's really not a big problem. Usually in this kind of cases you want to set `VERBOSE_COMMANDS="true"` variable which runs `set -x` and you see all commands as they are run (and it is run as one of the very first things in "script_start()"

**Comment by potiuk** [comment]
The `--verbose` flag is mainly about showing the actual `docker/helm/kubectl/kind` commands being executed under the hood - so that you can easily copy&paste them and run manually if you want to debug stuff.

```
****************************************************************************************************
 Increase verbosity of the scripts

-v, --verbose
        Show verbose information about executed commands (enabled by default for running test).
        Note that you can further increase verbosity and see all the commands executed by breeze
        by running 'export VERBOSE_COMMANDS="true"' before running breeze.

****************************************************************************************************
```

**Comment by potiuk** [comment]
@kaxil  https://github.com/apache/airflow/pull/10348 -> i updated the description to be more informative :)

**Comment by kaxil** [comment]
Cool yeah 👍

**Review by mik-laj — APPROVED** [review]

**Comment by potiuk** [comment]
cc: @jaketf

**Pull request merged**
