### PR TITLE
Bugfix for get_parsing_context() when ran with LocalExecutor

### LINKED ISSUE #39997: get_parsing_context().dag_id always returns None for LocalExecutor
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.90

### What happened?

In trying to optimize dynamic DAG generation, I tried to employ the method described [here](https://airflow.apache.org/docs/apache-airflow/stable/howto/dynamic-dag-generation.html#optimizing-dag-parsing-delays-during-execution), I applied the docs code while running Airflow with a LocalExecutor

```
from airflow.models.dag import DAG
from airflow.utils.dag_parsing_context import get_parsing_context

current_dag_id = get_parsing_context().dag_id

for thing in list_of_things:
    dag_id = f"generated_dag_{thing}"
    if current_dag_id is not None and current_dag_id != dag_id:
        continue  # skip generation of non-selected DAG

    with DAG(dag_id=dag_id, ...):
        ...
```

in all cases current_dag_id was None even during execution.
Not sure if this is a bug or a feature since while using LocalExecutor the scheduler process runs the tasks. 

I switched to CeleryExecutor in the same environment and the same code worked.

### What you think should happen instead?

`get_parsing_context().dag_id` should return the dag_id during execution time.

### How to reproduce

Run the code with the LocalExecutor on a test dag. Trigger the dag yourself and log current_dag_id. It will be None even though this was during dag execution.

### Operating System

ubuntu 22.04

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ErandM50**
his PR resolves #39997
When running with local executor, get_parsing_context would return None regardless of the parsing context. This leads to longer loading times when a lot of dynamic DAGs are generated from a single dagfile. Changed local_executor.py to execute the task with the _airflow_parsing_context_manager.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
Makes sense to me since this matches the code in CeleryExecutor. Needs eyes with better knowledge on this.

**Review by potiuk — COMMENTED** [review]
LGTM. Just the static check needs to be fixed. Ideally maybe a unit test would be good ?

**Review by o-nikolas — COMMENTED** [review]
I think this is missing on SequentialExecutor as well, not sure if it's worth fixing that here or not. Most executors use the standard task runner (and actually in that case only the running by fork path is covered, running by subprocess doesn't use this context.

**Comment by potiuk** [comment]
> I think this is missing on SequentialExecutor as well, not sure if it's worth fixing that here or not. Most executors use the standard task runner (and actually in that case only the running by fork path is covered, running by subprocess doesn't use this context.

Since there are static checks - might be worth adding it.

**Comment by potiuk** [comment]
@ErandM50 ?

**Comment by adrianrego** [comment]
We're seeing this issue using the KubernetesExecutor.

**Comment by potiuk** [comment]
> We're seeing this issue using the KubernetesExecutor.

K8S executor uses LocalExecutor under-the-hood, so likely this one will fix it too. I went aheaad and fixed static-checks and rebased it and will merge for 2.10

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> I think this is missing on SequentialExecutor as well, not sure if it's worth fixing that here or not. Most executors use the standard task runner (and actually in that case only the running by fork path is covered, running by subprocess doesn't use this context.

Separate PR maybe ?

**Review by o-nikolas — APPROVED** [review]

**Pull request merged**
