### PR TITLE
Remove support for FAB `APP_THEME`

### LINKED ISSUE #13158: UI Doesn't use all of Bootstrap theme css, Airflow 2.0
**Apache Airflow version**: 2.0.0

**Environment**: Ubuntu

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Picked Cyborg.css in web_server config but background is still default
image

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by ryanahamilton**
Resolves #13158.

As the UI has evolved, it has needed to diverge from the constraints of the aged, secondary Bootstrap dependency (by way of FAB). The alternative Bootstrap themes provided by FAB are no longer working properly, resulting in a sub-par user experience for anyone who might opt to use one. Supporting these themes would require substantial ongoing maintenance overhead. 

The alternative themes don't provide a better user experience than the (newly refreshed) UI theme. I could see differentiation between multiple Airflow deployments as the goal for utilizing this feature. In that case, we have the option to set a different nav bar color by setting a color value in the `navbar_color` config.

While this PR doesn't stop a user (who knows the inner workings of FAB) from configuring an alternative theme, it does ensure that the airflow theme is always loaded. There is no documentation of this feature in the Airflow docs, but this PR also removes comments suggesting usage of it and pointing to the FAB docs.

I've also updated the theme CSS file naming to remove "default" so it doesn't suggest that it is something changeable.

### CODE REVIEW

**Review by bbovenzi — APPROVED** [review]
Good idea. I'm all in favor of removing unneeded bits.

**Comment by ryanahamilton** [comment]
This feature removal needs to wait for 3.0

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
I think this one needs rebase

**Review by potiuk — APPROVED** [review]

**Comment by jedcunningham** [comment]
So this was marked for 3.0, but has been merged to main. We need to either decide it isn't a breaking change and remark it for 2.4, or revert it in main and leave it around for 3.0.

**Comment by bbovenzi** [comment]
Yeah, we should revert this. And probably avoid accidental merging by not reopening this PR or leaving it in draft.

**Comment by jedcunningham** [comment]
Opened #25652 to revert it.

**Pull request merged**
