### PR TITLE
Mask Password in Log table when using the CLI

### PR DESCRIPTION
**Pull request by kaxil**
**Before**:

image

**After**:

image

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
It's also possible to do `--password=foobar` (but not `-p=foobar`) which this PR won't catch.

**Comment by kaxil** [comment]
> It's also possible to do `--password=foobar` (but not `-p=foobar`) which this PR won't catch.

Fixed in https://github.com/apache/airflow/pull/11468/commits/40b1c0438857926bf7c1b32c70dba73a806edf24

**Comment by ashb** [comment]
Should we add `--conn-password` to this list?

And for bonus points the password part of the URI style?

**Review by ashb — APPROVED** [review]

**Comment by kaxil** [comment]
> Should we add --conn-password to this list?
> And for bonus points the password part of the URI style?

Added `--conn-password`, will address URI style later in a separate PR as we can do some cleanup of other parts where we mask Password in Conn URI too


> _technically_ this is a password of `=test` I think, (or it's not actually accepted by argparse) and it would have to be given as `-p test`.
> 
> But I think as an edge case this is okay if we don't worry about it

Looks like it works fine though 
```python
In [1]: from airflow.cli.cli_parser import get_parser
In [2]: parser = get_parser()
In [8]: parser.parse_args(["users", "create","-e" ,"airflow" , "-p=10", "-r", "Admin", "-f", "as", "-l", "asd", "-u", "as"])
Out[8]: Namespace(email='airflow', firstname='as', func=<function lazy_load_command.<locals>.command at 0x7fd196603dd0>, lastname='asd', password='10', role='Admin', subcommand='create', use_random_password=False, username='as')
```

**Pull request merged**
