### PR TITLE
Ignore deprecations in gcp automl, translate

### PR DESCRIPTION
**Pull request by gopidesupavan**
https://github.com/apache/airflow/actions/runs/12441141635/job/34737776458

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by gopidesupavan** [comment]
Do we really need to ignore these deprecations? or we should remove those deprecated classes? it looks like they have date mentioned target around sept 2025.

**Review by potiuk — APPROVED** [review]

**Review by potiuk — COMMENTED** [review]
Let's take a closer look before merging

**Comment by potiuk** [comment]
It's ok - it's September 2025 - so they are fine. My question is more why in the original PR the tests did not fail. I am looking into it.

**Comment by gopidesupavan** [comment]
> It's ok - it's September 2025 - so they are fine. My question is more why in the original PR the tests did not fail. I am looking into it.

ah i see it looks like providers tests not triggered in original pr https://github.com/apache/airflow/actions/runs/12431426634/job/34709142003

**Comment by gopidesupavan** [comment]
looks like selective checks ignoring some of the file checks conditions. trying to look more..

**Comment by potiuk** [comment]
Fix here #45131

**Comment by potiuk** [comment]
It was a very subtle combination of two bugs - and it's mostly a by-product of having several different folders where provider files come from. Will be simplified in the future when we implement [#44511](https://github.com/apache/airflow/issues/44511) (I am working on it already - first PRs are coming shortly on that one).

**Pull request merged**
