### PR TITLE
Add conditional to ingress apiVersion for compatibility

### PR DESCRIPTION
**Pull request by junnplus**
Add conditional to ingress apiVersion for compatibility.

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
The `networking.k8s.io/v1beta1` apiVersion has existed since 1.14 -- what version are you trying to use it wiht?

**Comment by mik-laj** [comment]
Here is information about supported Kubernetes versions.
> Kubernetes 1.12+ cluster

https://github.com/apache/airflow/tree/master/chart#prerequisites

All files are also verified against the Kubernetes specification.
https://github.com/apache/airflow/blob/3341d210cd265b51175d8f575e2ee73aa247f28b/chart/tests/helm_template_generator.py#L32

**Comment by Junnplus** [comment]
@ashb thanks you for review, I used 1.11.5 on production, 
I think 12.9+ should be compatible with `extensions/v1beta1` https://github.com/instrumenta/kubernetes-json-schema/blob/master/v1.12.9/ingress-extensions-v1beta1.json#L11

**Comment by ashb** [comment]
Even kube 1.12 is now _really_ old, 1.11 even more so. We should probably stop (officially) supporting that.

**Comment by mik-laj** [comment]
Here we discussed to change that and support Kubernetes 1.14+
https://github.com/apache/airflow/pull/12619/files

**Comment by Junnplus** [comment]
@mik-laj https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/  see this blog of official
```
The v1.22 release will stop serving the following deprecated API versions in favor of newer and more stable API versions:

Ingress in the extensions/v1beta1 API version will no longer be served
Migrate to use the networking.k8s.io/v1beta1 API version, available since v1.14. Existing persisted data can be retrieved/updated via the new version.
```
1.14+ should also be compatibled.

**Comment by mik-laj** [comment]
As for me, we can only support Kubernetes 1.14+, but I'm wondering if we should make additional changes. This change changes a little more code.
https://github.com/apache/airflow/pull/12619/files
I do not currently have time to look carefully and review these changes. Could you please help me with this?

**Comment by ashb** [comment]
I've merged #12619 which changes the minimum requirement to Kube 1.14 so I think we close this issue now. Sorry -- 1.11 is too old for us to support.

**Pull request closed without merging**
