### PR TITLE
Netezza  Hook

### PR DESCRIPTION
**Pull request by sanjay-rendu**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
Please read all the materials and consider seriously releasing the provider on your own. If you think there are good reasons for the provider to be added to the community, please start a thread at the devlist explaining why.

**Comment by sanjay-rendu** [comment]
Sounds good. I've published this hook as a package here - https://github.com/sanjay-rendu/apache-airflow-providers-nz/tree/main

**Comment by potiuk** [comment]
Cool. Feel free to make PR To https://airflow.apache.org/ecosystem/ or submit to registry :)

**Comment by potiuk** [comment]
Creating PR in ecosystem is a easy as clicking "suggest a change on this page" button

**Comment by sanjay-rendu** [comment]
Done. Thank you!

**Pull request closed without merging**
