### PR TITLE
Support annotations for the flower service in the chart

### PR DESCRIPTION
**Pull request by FloChehab**
Hello,

This is simple PR that adds the ability to add annotations
to the flower service in the chart.

Docs and tests updated accordingly.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by FloChehab** [comment]
Hello @mik-laj , this PR is good start towards what you were describing in https://github.com/apache/airflow/pull/12010#issuecomment-757344368 .

**Comment by mik-laj** [comment]
I wonder if we should review all objects and standardize support for annotations. As you can see this annotation support is being added in several PRs for different objects, and I guess it won't be hard to do this for all objects. Are you interested in this?

**Comment by FloChehab** [comment]
> I wonder if we should review all objects and standardize support for annotations. As you can see this annotation support is being added in several PRs for different objects, and I guess it won't be hard to do this for all objects. Are you interested in this?

Yeah I can look into that. Maybe we should create an issue for this so that we agree on the how (terminology, objects, location in the values.yaml) before starting the dev? Wdyt ?

**Comment by mik-laj** [comment]
@FloChehab  the idea sounds good to me. the new issue allows us to discuss freely.

**Comment by FloChehab** [comment]
Closing in favor of https://github.com/apache/airflow/issues/13643.

**Pull request closed without merging**
