### PR TITLE
Update faq.rst

### PR DESCRIPTION
**Pull request by zigius**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@zigus would you be so kind and rebase it wth the latest master please? I've just merged #12038 - we had a bug that disabled docs building in case of doc-only changed. So no docs were built in your PR, but when you rebase, they should be built!

**Comment by zigus** [comment]
> @zigus would you be so kind and rebase it on top of the latest master please? I've just merged #12038 - we had a bug that disabled docs building in case of doc-only changed. So no docs were built in your PR, but when you rebase, they should be built!

Hi @potiuk I think you wanted to mention @zigius not me :)

**Comment by potiuk** [comment]
> Hi @potiuk I think you wanted to mention @zigius not me :)

Ah yeah. Sorry :)

**Comment by zigius** [comment]
done. thanks @zigus

**Review by potiuk — APPROVED** [review]
And everything works as expected including docs build now :)

**Pull request merged**
