### PR TITLE
[AIRFLOW-2933] Enable Codecov on Docker-CI Build

### PR DESCRIPTION
**Pull request by Fokko**
Add missing variables and use codecov instead of coveralls. The issue why it wasn't working was because missing environment variables. The codecov library heavily depends on the environment variables in the CI to determine how to push the reports to codecov.

I've removed the explicit passing of the variables in the `tox.ini` since we also do it at the `docker-compose.yml`, having to maintain this at two places makes it brittle.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2933\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-2933\], code changes always need a Jira issue.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
Does this mean no more coverals-io comments in github?

**Comment by Fokko** [comment]
@ashb I was also confused by this, but the comment is by Codecov, right?

An example:
image

**Comment by ashb** [comment]
Definitely looks like it!

**Comment by Fokko** [comment]
Lets add `coveralls` as well :)

**Comment by Fokko** [comment]
Hmm, I'm not exactly sure what triggers the notification. I've requested the Codecov Github app installation at the Apache INFRA team.

**Comment by Fokko** [comment]
So the coverage report gets uploaded: https://codecov.io/gh/apache/incubator-airflow/commit/c1566951dcecb91a2a739700e2b84f3dcee02c6b

not sure why the notification is not posted to Github. Apart from that, I would like to see to get this merged so we get the reporting back on master.

**Review by kaxil — APPROVED** [review]

**Pull request merged**
