### PR TITLE
Add Helm Chart linting

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @jaketf @mik-laj

**Comment by kaxil** [comment]
hmm the CI is stuck

**Comment by potiuk** [comment]
Seems like we do experience some smaller job queue or smth like that. I might have to speed up my "selective tests work".

**Comment by potiuk** [comment]
Looks awfully like some of the Travis problems we had.

**Comment by kaxil** [comment]
> Looks awfully like some of the Travis problems we had.

:( yeah

**Comment by turbaszek** [comment]
This looks like a flaky / side effect?
```
______________________ TestConf.test_conf_as_dict_source _______________________
1164

1165
self = <tests.test_configuration.TestConf testMethod=test_conf_as_dict_source>
1166

1167
    def test_conf_as_dict_source(self):
1168
        # test display_source
1169
        cfg_dict = conf.as_dict(display_source=True)
1170
>       self.assertEqual(
1171
            cfg_dict['core']['load_examples'][1], 'airflow.cfg')
1172
E       AssertionError: 'env var' != 'airflow.cfg'
1173
E       - env var
1174
E       + airflow.cfg
```

**Comment by kaxil** [comment]
> This looks like a flaky / side effect?
> 
> ```
> ______________________ TestConf.test_conf_as_dict_source _______________________
> 1164
> 
> 1165
> self = <tests.test_configuration.TestConf testMethod=test_conf_as_dict_source>
> 1166
> 
> 1167
>     def test_conf_as_dict_source(self):
> 1168
>         # test display_source
> 1169
>         cfg_dict = conf.as_dict(display_source=True)
> 1170
> >       self.assertEqual(
> 1171
>             cfg_dict['core']['load_examples'][1], 'airflow.cfg')
> 1172
> E       AssertionError: 'env var' != 'airflow.cfg'
> 1173
> E       - env var
> 1174
> E       + airflow.cfg
> ```

This is fixed in master

**Review by kaxil — APPROVED** [review]

**Pull request merged**
