### PR TITLE
feat: allow customizing podManagementPolicy

### PR DESCRIPTION
**Pull request by EvertonSA**
---
I as a user of StatefulSets in Airflow, would like to preserving workload uniqueness and identity guarantees, but allow scalling up and down without waiting for termination grace period.

This is useful when termination grace period is very high. In such cases, scaling up and down gets fully stuck while waiting for long running tasks.

### CODE REVIEW

**Review by edumueller — APPROVED** [review]

**Comment by EvertonSA** [comment]
thank you so much for the help here @eladkal, at my organization, we recently pushed celery to production and at the moment we are having issues on scaling due to high termination grace period.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
cc: @jedcunningham for cross-check

**Review by romsharon98 — APPROVED** [review]

**Comment by romsharon98** [comment]
Already merged but it will be nice if you add a UT for this 🙂

**Comment by EvertonSA** [comment]
hi @romsharon98 , I beg your pardon, what is a UT? I will add it

**Comment by romsharon98** [comment]
> hi @romsharon98 , I beg your pardon, what is a UT? I will add it

in UT I ment unit tests.
we have a unit tests documentation about the helm chart [here](https://github.com/apache/airflow/blob/main/contributing-docs/testing/helm_unit_tests.rst).
the test should check if the worker deployment is statefulset and has podManagementPolicy, we added it to the yaml.

**Pull request merged**
