### PR TITLE
Contrib cleanup

### PR DESCRIPTION
**Pull request by ipeluffo**
Close last files pending to be deprecated from contrib: https://github.com/apache/airflow/issues/9382
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Some wekday tests are failing :(

**Comment by potiuk** [comment]
Looks good. I think it's ready to merge :)

**Comment by potiuk** [comment]
Can you un-draft it please :)

**Comment by ipeluffo** [comment]
Ready for review. Thanks

**Review by turbaszek — APPROVED** [review]

**Comment by mik-laj** [comment]
One more file has not been merged.
https://github.com/ipeluffo/airflow/blob/1aa053c8b6303d4fd7cd776a625e74e3e085ba86/airflow/contrib/utils/sendgrid.py
It is also worth adding tests to prevent regression.  People can add files to this package by accident.
https://github.com/apache/airflow/blob/master/tests/test_project_structure.py#L56

**Pull request merged**
