### PR TITLE
Update deferring.rst

### PR DESCRIPTION
**Pull request by 9uzman7**
It took me a long time to figure out that context: Context should also be in the method_name signature. I vaguely updated the docs, but it would be nice to add somewhere that context should be part of method_name signature

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
It's in all the examples above and below so I think just explicitly mentioning it is ok.

**Comment by uranusjr** [comment]
I think the `context` argument was taken for granted because it is also given to `execute`, and only `event` is “added” to subsequent methods. Maybe we should mention `execute` here to make it more explicit.

**Review by dirrao — APPROVED** [review]

**Comment by 9uzman7** [comment]
> I think the `context` argument was taken for granted because it is also given to `execute`, and only `event` is “added” to subsequent methods. Maybe we should mention `execute` here to make it more explicit.

that was what took to me to think that context was in the example, because the example is execute_complete which execute takes context, so it made sense to keep using context 🙃

**Review by pankajastro — APPROVED** [review]

**Comment by 9uzman7** [comment]
@dirrao @pankajastro thanks for the approvals! not sure who can merge this in

**Pull request merged**
