### PR TITLE
[AIRFLOW-2429] Add BaseExecutor import back

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2429
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
  I remove BaseExecutor import from airflow.executors.__init__ as flake8 complain. It turns out that it is refered in tests.__init__. This causes travis to fails. Add back the import line.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @kaxil  @Fokko . Hey Kaxil, Fokko, I checked the travis failure and it turned out that my previous pr(https://github.com/apache/incubator-airflow/pull/3398) has one line incorrect which remove `BaseExecutor` import. Add it back in this pr. Sorry about not that.

**Comment by mistercrunch** [comment]
LGTM

**Comment by feng-tao** [comment]
I believe the travis error is unrelated :)

**Comment by Fokko** [comment]
Thanks @feng-tao for picking this up so quickly.

**Pull request closed without merging**
