### PR TITLE
[AIRFLOW-2956] added kubernetes tolerations to kubernetes pod operator

### PR DESCRIPTION
**Pull request by justinholmes**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2956\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2956
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-2956\], code changes always need a Jira issue.

### Description
 Adds ability to specify kubernetes tolerations for dags using kubernetes pod operator

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @justinholmes, we had some issues with the boto3 dependency. Could you rebase onto latest master?

**Comment by justinholmes** [comment]
Sure.

**Comment by justinholmes** [comment]
Will try to add a few example tests as well.

**Comment by jpds** [comment]
Please also add an example to the example DAG definitions.

**Comment by bolkedebruin** [comment]
Docs please?

**Comment by Fokko** [comment]
@justinholmes can you resolve the merge conflicts?

**Comment by lsowen** [comment]
@justinholmes anything I can do to help with this PR?  Definitely would love to get this merged.

**Comment by ThiagoVieira** [comment]
@justinholmes same as Isowen, would be great to get this PR merged

**Comment by justinholmes** [comment]
I just need to merge master back in and squash commits.

**Comment by justinholmes** [comment]
Merged and Squashed

**Comment by justinholmes** [comment]
@Fokko Are you happy to merge?

**Comment by EamonKeane** [comment]
+1 for getting this merged... will simplify autoscaling of airflow in a dedicated node-pool.

**Comment by Fokko** [comment]
Thanks @justinholmes, merging to master! 👍

**Pull request merged**
