### PR TITLE
Bump ```alembic``` minimum version

### PR DESCRIPTION
**Pull request by aa3pankaj**
related to https://github.com/apache/airflow/discussions/27394#discussioncomment-4015380

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
Why is 1.6.3 specifically chosen as the new lower bound?

**Comment by aa3pankaj** [comment]
> Why is 1.6.3 specifically chosen as the new lower bound?

with alembic<1.6.0 - airflow db upgrade is failing with error mentioned here: https://github.com/apache/airflow/discussions/27394

with alembic>=1.6.0 and <1.6.3 , airflow db upgrade is hanging with below logs:
```
[2022-11-12 22:25:50,993] {db.py:1398} DEBUG - running check function check_conn_id_duplicates
[2022-11-12 22:25:51,083] {db.py:1398} DEBUG - running check function check_conn_type_null
[2022-11-12 22:25:51,085] {db.py:1398} DEBUG - running check function check_run_id_null
[2022-11-12 22:25:51,103] {db.py:1398} DEBUG - running check function check_bad_references
[2022-11-12 22:25:51,146] {db.py:1342} DEBUG - checking model task_instance
[2022-11-12 22:25:51,146] {db.py:1342} DEBUG - checking model task_reschedule
[2022-11-12 22:25:51,146] {db.py:1342} DEBUG - checking model rendered_task_instance_fields
[2022-11-12 22:25:51,147] {db.py:1371} DEBUG - moving data for table rendered_task_instance_fields
[2022-11-12 22:25:51,147] {db.py:1134} DEBUG - running CTAS for table _airflow_moved__2_3__dangling__rendered_task_instance_fields
[2022-11-12 22:25:51,177] {db.py:1145} DEBUG - checking whether rows were moved for table _airflow_moved__2_3__dangling__rendered_task_instance_fields
[2022-11-12 22:25:51,178] {db.py:1151} DEBUG - no rows moved; dropping _airflow_moved__2_3__dangling__rendered_task_instance_fields
[2022-11-12 22:25:51,181] {db.py:1170} DEBUG - exiting move function
[2022-11-12 22:25:51,182] {db.py:1342} DEBUG - checking model task_fail
[2022-11-12 22:25:51,182] {db.py:1371} DEBUG - moving data for table task_fail
[2022-11-12 22:25:51,183] {db.py:1134} DEBUG - running CTAS for table _airflow_moved__2_3__dangling__task_fail
[2022-11-12 22:25:51,215] {db.py:1145} DEBUG - checking whether rows were moved for table _airflow_moved__2_3__dangling__task_fail
[2022-11-12 22:25:51,216] {db.py:1151} DEBUG - no rows moved; dropping _airflow_moved__2_3__dangling__task_fail
[2022-11-12 22:25:51,221] {db.py:1170} DEBUG - exiting move function
[2022-11-12 22:25:51,221] {db.py:1342} DEBUG - checking model xcom
[2022-11-12 22:25:51,221] {db.py:1371} DEBUG - moving data for table xcom
[2022-11-12 22:25:51,222] {db.py:1134} DEBUG - running CTAS for table _airflow_moved__2_3__dangling__xcom
[2022-11-12 22:25:51,255] {db.py:1145} DEBUG - checking whether rows were moved for table _airflow_moved__2_3__dangling__xcom
[2022-11-12 22:25:51,256] {db.py:1151} DEBUG - no rows moved; dropping _airflow_moved__2_3__dangling__xcom
[2022-11-12 22:25:51,260] {db.py:1170} DEBUG - exiting move function
[2022-11-12 22:25:51,261] {migration.py:164} INFO - Context impl MySQLImpl.
[2022-11-12 22:25:51,261] {migration.py:171} INFO - Will assume non-transactional DDL.
[2022-11-12 22:25:51,264] {db.py:1533} INFO - Creating tables
[2022-11-12 22:25:51,264] {settings.py:407} DEBUG - Disposing DB connection pool (PID 78750)
[2022-11-12 22:25:51,265] {settings.py:266} DEBUG - Setting up DB connection pool (PID 78750)
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
```

**Comment by aa3pankaj** [comment]
cc: @potiuk

**Comment by uranusjr** [comment]
Thank you, this additional context may be important if we need to debug similar issues in the future. 1.6.4 only fixes one bug:

https://alembic.sqlalchemy.org/en/latest/changelog.html#change-1.6.4

It doesn’t seem very related, to be honest (I would expect migrations to crash instead of hang for this), but it’s likely not worthwhile to debug to deep into this. We can always review and revise the version range if issues come up.

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
> It’s likely not worthwhile to debug to deep into this, so I think this is good enough. We can always review and revise the version range if issues come up.

Correct - we have a number of "lower bounds" and unlike "upper bounds" - we have no  to explain the lower bounds reasons in detail or evan dig-deeply into the reasons, as long as the "lower-bound" version is "old enough". It might be interesting to know but it has mostly academic value to know it as with every day the reason for that lower-bound is farhter in the past and becomes less and less relevant(as opposed to upper-bound - every day we keep it, it becomes more and more relevant and annoying).

**Comment by potiuk** [comment]
Thanks @aa3pankaj for figuring that one out :).

**Review by potiuk — APPROVED** [review]

**Pull request merged**
