### PR TITLE
Focus upstream / downstream task dependencies on mouseover

### PR DESCRIPTION
**Pull request by dstandish**
**Summary**

We currently support focusing on upstream / downstream task dependencies in a mild way, namely by changing the color.

When you have a big messy dag, though, more aggressive focusing is desirable.

In this PR we enhance the focus on the upstream / downstream tasks by setting opacity of all _other_ tasks and edges to 0.2.

This is the same approach that is already implemented in graph view when you mouseover task state, _and_ when you use the search function to filter tasks.

Below are screenshots when the mouse is over dummy 3.

Before:
image

After:
image

**Also**

In this PR I also apply highlightStrokeWidth to focused tasks.  If this one is merged, then #9297 is obsolete and can be closed.

---

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
Can you also include a before screenshot for comparison?

**Comment by dstandish** [comment]
> Can you also include a before screenshot for comparison?

done

**Comment by dstandish** [comment]
@ashb i updated it to remove one line that did not need to be there
also, i fixed the colors in the screenshot.  unrelated to this change i had the upstream downstream colors changed locally and that could have caused confusion (and probably did).

thanks

**Review by feluelle — APPROVED** [review]

**Comment by dstandish** [comment]
@feluelle what do you think about expanding this a bit, so that we highlight not just immediate upstream / downstream, but everything in the chain.  

so, highlight the immediate upstream tasks, but also the upstream of those upstream tasks. and same with downstream.

i think this might be better, so that for any task, you can see everything it depends on, and everything that depends on it.  and then everything else is de-focused.

**Comment by dstandish** [comment]
thanks @feluelle

**Pull request merged**
