### PR TITLE
AIRFLOW-3573 - Remove DagStat table

### PR DESCRIPTION
**Pull request by ffinfo**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3573

### Description

The table DagStat can be removed after AIRFLOW-3561

### Tests

No need, only removing code

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

No need, just removing unused code.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
LGTM Thanks @ffinfo

**Comment by kaxil** [comment]
Can you please resolve an error that was in the PR but because of broken Travis it wasn't detected:

```
======================================================================
3) FAIL: test_delete_dag_dag_still_in_dagbag (tests.api.common.experimental.test_delete_dag.TestDeleteDAGCatchError)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/api/common/experimental/test_delete_dag.py line 61 in test_delete_dag_dag_still_in_dagbag
      delete_dag(self.dag_id)
   AssertionError: DagFileExists not raised
```

Please fix it in the new PR.

**Comment by Fokko** [comment]
@ffinfo PTAL

**Comment by ffinfo** [comment]
@Fokko I think meanwhile this is already fixed on master

**Pull request merged**
