### PR TITLE
[AIRFLOW-3793] Decommission configuration items for Flask-Admin web UI & related codes

### PR DESCRIPTION
**Pull request by XD-DENG**
### Jira

  - https://issues.apache.org/jira/browse/AIRFLOW-3793

### Description

`authenticate`, `filter_by_owner` and `owner_mode` are only applicable for the Flask-Admin based UI, which is already deprecated in master branch.

### CODE REVIEW

**Comment by XD-DENG** [comment]
@ashb @feng-tao PTAL.

This is to follow up on what we discussed in https://github.com/apache/airflow/pull/4612 (item 1 listed in https://github.com/apache/airflow/pull/4612#issuecomment-459350812)

**Comment by feng-tao** [comment]
will take a look next week. But I think we need to update the UPDATE.md to mention about the config removal?

**Comment by XD-DENG** [comment]
@feng-tao , agree and sorry for having missed it. Let me add that part later.

Happy CNY btw ;-)

**Comment by feng-tao** [comment]
@XD-DENG , happy CNY~

**Comment by XD-DENG** [comment]
Hi @ashb @feng-tao please advise if it’s ok to merge this? Or further change is required?

After this I’ll go ahead to clean the contrib/auth codes.

Thanks.

**Comment by feng-tao** [comment]
I am not very familiar with the code. But I do some grab and found still some references with the config. E.g. https://github.com/apache/airflow/blob/master/tests/core.py#L1964

I would be more comfortable if @bolkedebruin, @mistercrunch and @ashb could take a look.

**Comment by ashb** [comment]
In-fact that whole test can go - here are the tests that we are just always skipping and we should now delete 

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L1960-L1961

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2384-L2385

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2052-L2053

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2406-L2407

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2450-L2451

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2518-L2519

https://github.com/apache/airflow/blob/ba66fa7e774458c8f2fc14fb742847f63508700a/tests/core.py#L2606-L2607

Other files to look at: airflow/config_templates/default_test.cfg

**Comment by XD-DENG** [comment]
Thank you @feng-tao and @ashb for helping check. On holiday now so responding a bit slowely.

Regarding the lines in `tests/core.py` you pointed out, it was a conscious decision to leave them since some of them are relating to the `contrib/auth` modules. As discussed in 
https://github.com/apache/airflow/pull/4612, it's preferable to split the works into multiple PRs, and these tests are always skipped currently anyway. But after double-thinking, I think it may make more sense to delete these tests here in this PR, to avoid confusion. I have already updated the commits.

Regarding `airflow/config_templates/default_test.cfg`, I had a check and no change is needed to me (the a few config items we delete in this PR don't appear in `airflow/config_templates/default_test.cfg`). Please let me know if I missed anything.

Thanks!

**Comment by XD-DENG** [comment]
@ashb @feng-tao do you think we can close this or any further work is needed?

After this PR is closed, I'll resume on the `contrib/auth` modules cleaning.

Thanks!

**Comment by XD-DENG** [comment]
Hi @feng-tao  @ashb , a gentle ping. Please advise.

**Comment by XD-DENG** [comment]
Hi @ashb @feng-tao, a gentle ping in case you missed this. Sorry for keeping bothering ;-)

**Comment by ashb** [comment]
Sorry - been swamped recently. Where did we end up with the various API auth discussions?

**Comment by ashb** [comment]
I vote for removing the currently skipped tests that depend upon config settings we are removing. If we need them back for future PR work we can look in the git history.

**Comment by XD-DENG** [comment]
> Sorry - been swamped recently. Where did we end up with the various API auth discussions?

Hi @ashb , please refer to https://lists.apache.org/thread.html/dea9f1c4c61a9aa33caef1ed51835e24e75de0aa9bac1f0eefae97de@%3Cdev.airflow.apache.org%3E

I would agree with Bolke: given we still have Kerberos (`airflow.api.auth.backend.kerberos_auth`, not `airflow.contrib.auth.backends.kerberos_auth`), we can remove `airflow/contrib/auth/backends/password_auth.py`, as well as other contrib auth backends.

I would suggest to merge this PR first if it looks good to you, then I will resume on the `contrib/auth` modules cleaning. This helps us avoid having a too big PR/change at one time.

**Comment by XD-DENG** [comment]
> I vote for removing the currently skipped tests that depend upon config settings we are removing. If we need them back for future PR work we can look in the git history.

Yep, they were already removed in the 4th commit of this PR ;-)

**Comment by astahlman** [comment]
LGTM, for what it's worth

**Comment by XD-DENG** [comment]
Rebased to resolve conflict.

A gentle ping @ashb @feng-tao .

**Comment by Fokko** [comment]
Restarted the failing tests

**Comment by XD-DENG** [comment]
Hi @Fokko may you restart them again? Two tests failed but they still seem flaky/transient error to me, since CI passed in the CI of my own fork.

If they fail again, I will dive in.

Thanks!

**Comment by XD-DENG** [comment]
Hi @ashb , @feng-tao , @Fokko , a gentle ping on this.

Have rebased earlier today to ensure no conflict.

**Comment by ashb** [comment]
Sorry it took like 9 million months!

**Comment by XD-DENG** [comment]
> Sorry it took like 9 million months!

LOL. Thanks @ashb

**Comment by icyfox-bupt** [comment]
> ### Jira
> * https://issues.apache.org/jira/browse/AIRFLOW-3793
> 
> ### Description
> `authenticate`, `filter_by_owner` and `owner_mode` are only applicable for the Flask-Admin based UI, which is already deprecated in master branch.

Hi, 
I tried your code in master branch but found an error.
Flask App builder looks like is using **python-ldap**, while in 1.10.3, default web ui use **ldap3**
So I failed to start airflow if I don't downgrade to python-ldap.
I think there should have a change, downgrade ldap or upgrade ldap in FAB frame.

Thanks

**Comment by XD-DENG** [comment]
Hi @icyfox-bupt if I'm not mistaken, Airflow's FAB UI doesn't support LDAP authentication in an out-of-box way yet.

**Comment by ashb** [comment]
I haven't used it but there's https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap

**Comment by XD-DENG** [comment]
Thanks a lot @ashb for sharing.

**Comment by icyfox-bupt** [comment]
> Hi @icyfox-bupt if I'm not mistaken, Airflow's FAB UI doesn't support LDAP authentication in an out-of-box way yet.

FAB support it but airflow not. Looks like I should change something here to make LDAP work with FAB and commit here.
Thanks everyone.

**Pull request merged**
