### PR TITLE
Split contributor's quick start into separate guides.

### LINKED ISSUE #23174: Some links in contributor's quickstart table of contents are broken
### What do you see as an issue?

In `CONTRIBUTORS_QUICK_START.rst`, the links in the table of contents that direct users to parts of the guide that are hidden by the drop down don't work if the drop down isn't expanded. For example, clicking "[Setup Airflow with Breeze](https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#setup-airflow-with-breeze)" does nothing until you open the appropriate drop down `Setup and develop using <PyCharm, Visual Studio Code, Gitpod>`

### Solving the problem

Instead of having the entire documentation blocks under `Setup and develop using {method}` dropdowns, there could be drop downs under each section so that the guide remains concise without sacrificing the functionality of the table of contents.

### Anything else

I'm happy to submit a PR eventually, but I might not be able to get around to it for a bit if anyone else wants to handle it real quick.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
The foldable parts were not good. They made links not to work as
well as they were not too discoverable.

Fixes: #23174

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Refactored quick-start contributor's guide to separate docs before the upcoming summit workshop.

**Comment by RNHTTR** [comment]
A few thoughts:
1. I think it'd make sense to mention Breeze in [CONTRIBUTORS_QUICK_START.rst](https://github.com/apache/airflow/blob/bc6ad899adce71fd39ee01206c169312fe86fe4c/CONTRIBUTORS_QUICK_START.rst). Maybe just a high level overview and a link to [BREEZE.rst](https://github.com/apache/airflow/blob/bc6ad899adce71fd39ee01206c169312fe86fe4c/BREEZE.rst). Perhaps in the "Note to Starters" or "Local machine development" sections?
2. My concern would be how maintainable will these guides be? If something common to each of the guides changes, they're not very DRY, and the update will have to be made in each sub-guide. Maybe common parts like "Forking and cloning Project", "Setting up Breeze", "Installing airflow in the local virtual environment airflow-env with breeze.", "Using Breeze", "Testing", etc could be included in the "main" [CONTRIBUTORS_QUICK_START.rst](https://github.com/apache/airflow/blob/bc6ad899adce71fd39ee01206c169312fe86fe4c/CONTRIBUTORS_QUICK_START.rst). Perhaps there could be a link at the end of each sub-guide that returns to `CONTRIBUTORS_QUICK_START.rst` to finish the guide with these sections.
3. Nitpick, but in [CONTRIBUTORS_QUICK_START.rst](https://github.com/apache/airflow/blob/bc6ad899adce71fd39ee01206c169312fe86fe4c/CONTRIBUTORS_QUICK_START.rst), maybe it should say "Contributor's Quick Start" or "Contributor's Quick Start Guide" instead of "Contributor's Quick Guide".
4. Another nitpick: IMO [CONTRIBUTORS_QUICK_START_VSC.rst](https://github.com/apache/airflow/blob/bc6ad899adce71fd39ee01206c169312fe86fe4c/CONTRIBUTORS_QUICK_START_VSC.rst) should be named `CONTRIBUTORS_QUICK_START_VSCODE.rst`.
5. Yet another nitpick: Each of the sub-guides starts with "Setup Airflow with Breeze" and "Forking and cloning Project" as a header. Maybe these headers should be removed; I'm not sure there should be a header for Breeze here because it's explained later in the guides, and there's no alternative to Breeze given. Does that make sense? Similarly, maybe the "Forking and cloning Project" header should be removed because it's described in step 1 and there's no alternative.

Overall I think this is much better! Let me know what you think.

**Comment by potiuk** [comment]
It should be WAY better now.

**Comment by potiuk** [comment]
As we are preparing for the next week's workshop - do let me know (or maybe even add fixup).

CC: @Bowrna @edithturn  @Melodie97  -> would be great  to hear your comments/suggestions here too.

**Comment by potiuk** [comment]
Direct link here: https://github.com/potiuk/airflow/blob/split-contributors-quick-start/CONTRIBUTORS_QUICK_START.rst

**Comment by Bowrna** [comment]
@potiuk Testing in VS Code follows older breeze commands https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#id11
while testing in PyCharm follows the new breeze commands
https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst#testing

**Comment by potiuk** [comment]
> Testing in VS Code and GitPod follows older breeze commands

Ah goood one. We already removed the duplication in the "split" version  - this was one of the artifacts of the "doc duplication" that we had. Now there is only one section about it ....  but it uses the legacy way 🤦

**Comment by potiuk** [comment]
Fixed! Thanks @Bowrna @edithturn @RNHTTR . I think we can merge it :).

**Comment by potiuk** [comment]
Any commmiter review - most welcome here :).

**Review by eladkal — APPROVED** [review]
I think our main tree is starting to grow large..
maybe we should have all the contributors guides under dedicated folder? (also with all testing / static checks guides etc..)

**Pull request merged**
