### PR TITLE
[AIRFLOW-2146] Resolve issues with BQ using DbApiHook methods

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2146

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- Resolves issues with using methods like `get_records()` from `BigQueryHook` which is extended from `DbApiHook`.
- Reverting one changed file from https://github.com/apache/incubator-airflow/pull/3031 to use BigQuery Hook again instead of `GoogleCloudBaseHook`
- Fix `conn_type` of `bigquery_default` connection

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
No major change

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @Fokko

**Comment by Fokko** [comment]
@kaxil CI is failing:
```
======================================================================
1) FAIL: test_cli_connections_list (tests.CliTests)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/core.py line 1042 in test_cli_connections_list
      self.assertIn(['bigquery_default', 'bigquery'], conns)
   AssertionError: ['bigquery_default', 'bigquery'] not found in [[u'airflow_db', u'mysql'], [u'airflow_ci', u'mysql'], [u'beeline_default', u'beeline'], [u'bigquery_default', u'google_cloud_platform'], [u'local_mysql', u'mysql'], [u'presto_default', u'presto'], [u'google_cloud_default', u'google_cloud_platform'], [u'hive_cli_default', u'hive_cli'], [u'hiveserver2_default', u'hiveserver2'], [u'metastore_default', u'hive_metastore'], [u'mysql_default', u'mysql'], [u'postgres_default', u'postgres'], [u'sqlite_default', u'sqlite'], [u'http_default', u'http'], [u'mssql_default', u'mssql'], [u'vertica_default', u'vertica'], [u'wasb_default', u'wasb'], [u'webhdfs_default', u'hdfs'], [u'ssh_default', u'ssh'], [u'fs_default', u'fs'], [u'aws_default', u'aws'], [u'spark_default', u'spark'], [u'druid_ingest_default', u'druid'], [u'redis_default', u'redis'], [u'sqoop_default', u'sqoop'], [u'emr_default', u'emr'], [u'databricks_default', u'databricks'], [u'qubole_default', u'qubole']]
```

**Comment by kaxil** [comment]
@Fokko it has been resolved now. It ahould pass now.

**Comment by kaxil** [comment]
@Fokko I am looking into it. Will update you once I resolve it

**Comment by kaxil** [comment]
@Fokko I had first changed the failed test (`test_cli_connections_list `) to below:
```python
self.assertIn(['bigquery_default', 'google_cloud_platform'], conns)
```
The CI failed this for `backed_sqlite` & `backend_postgres`, however it passed for the rest which you can see [here](https://travis-ci.org/apache/incubator-airflow/builds/345754806). 

This was because of the way the test (`test_cli_connections_list`) is written. The test grabs the content from the command line and uses regex to extract the required information.
```python
    def test_cli_connections_list(self):
        with mock.patch('sys.stdout',
                        new_callable=six.StringIO) as mock_stdout:
            cli.connections(self.parser.parse_args(['connections', '--list']))
            stdout = mock_stdout.getvalue()
        conns = [[x.strip("'") for x in re.findall("'\w+'", line)[:2]]
                 for ii, line in enumerate(stdout.split('\n'))
                 if ii % 2 == 1]
        conns = [conn for conn in conns if len(conn) > 0]
```

Now the command line strips longer names and presents it as `...`, so instead of `google_cloud_platform` it may show `google...platform...` and instead of `druid_ingest_default` it would end of showing `druid_..._default` (Screenshot 2). Hence the regex won't be able to match it when the space in cli is low and it displays `...` instead of correct names.

**Screenshot 1:** 
Travis CI report ([link](https://travis-ci.org/kaxil/incubator-airflow/jobs/345754777#L5102)) showing that because of the dots, the connection list obtained using regex only contain `[u'bigquery_default']` instead of `[u'bigquery_default', u'google_cloud_platform']` and similar with `druid`
image

**Screenshot 2:** 
The screengrab obtained from command line when the connections are listed. You can check using `airflow connections -l`
image

Hence, I have removed the below line from the test as the main purpose of this test was to assert that some of the connections present in the output are as expected which is already done where the connection name and connection types have short string length.

```python
self.assertIn(['bigquery_default', 'google_cloud_platform'], conns)
```

The Travis CI has now passed..

**Pull request closed without merging**
