### PR TITLE
Remove old test dag that is out of place

### PR DESCRIPTION
**Pull request by ashb**
This dag hasn't been used in tests since about 2017, and is the last file in the top level `dags/` folder -- it's high time we removed it.

From what I can see this isn't used in the tests anymore.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by ashb** [comment]
I'll wait for the tests on this one, in case my grep failed to turn up something.

**Review by kaxil — APPROVED** [review]

**Review by kaxil — CHANGES_REQUESTED** [review]
oh wait this is used here: https://github.com/apache/airflow/blob/c863044a0e02918a7853e352aadbbc937483d958/tests/models/test_serialized_dag.py#L53-L55

**Review by kaxil — COMMENTED** [review]
Should be. moved though at the very least under `/tests`

**Comment by ashb** [comment]
I'll just use one of the other example files if that's the only use case

**Comment by ashb** [comment]
Actually: that is just a string -- it doesn't read the file, so that's fine.

**Review by kaxil — APPROVED** [review]

**Pull request merged**
