### PR TITLE
[AIRFLOW-3139] include parameters into log.info in SQL operators, if any

### PR DESCRIPTION
**Pull request by XD-DENG**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3139
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

For all SQL-operators based on `DbApiHook`, sql command itself is printed into `log.info`. But if parameters are used for the sql command, the parameters would not be included in the printing. This makes the log less useful.

This commit ensures that the parameters are also printed into the `log.info`, if any.

**Before this commit**
screen shot 2018-10-02 at 3 24 21 pm

**After this commit**
(if no parameters is given for the sql command, there will be no change)
screen shot 2018-10-02 at 3 40 44 pm

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @ashb , may you take a look? Thanks.

**Comment by krithin** [comment]
Hi @XD-DENG ! This PR's great! But I see it wasn't included in the 1.10.2 airflow release for some reason. Are there plans to make that happen in some future release?

**Comment by XD-DENG** [comment]
Hi @krithin , yes we can propose to include this commit into the next release.

Hi @ashb FYI.

**Comment by osule** [comment]
Hi @XD-DENG any chance that sensitive parameters are masked?

**Comment by XD-DENG** [comment]
Hi @osule , good point. But unfortunately it’s not supported to mask parameters at this moment

**Pull request merged**
