### PR TITLE
[AIRFLOW-3697] Vendorize nvd3 and slugify

### PR DESCRIPTION
**Pull request by bolkedebruin**
nvd3 has a dependency on python-slugify which pulls in a
GPL dependency by default.

@kaxil 

cc: @Fokko @ashb

### CODE REVIEW

**Comment by kaxil** [comment]
I would suggest if this needs more work and probably more time we can include it in the next release. We can have a patch release 1.10.3 after fixing this issue. Let me know your thoughts on this if you agree I will cut RCs for 1.10.2.

CI fails with similar errors as below:

```
======================================================================
1) ERROR: test_backfill (tests.CliTests)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/core.py line 1073 in setUp
      self.app, self.appbuilder = application.create_app(session=Session, testing=True)
    airflow/www_rbac/app.py line 163 in create_app
      init_views(appbuilder)
    airflow/www_rbac/app.py line 91 in init_views
      from airflow.www_rbac import views
    airflow/www_rbac/views.py line 65 in <module>
      from airflow._vendor import nvd3
    airflow/_vendor/nvd3/__init__.py line 19 in <module>
      from .lineChart import lineChart
    airflow/_vendor/nvd3/lineChart.py line 12 in <module>
      from .NVD3Chart import NVD3Chart, TemplateMixin
    airflow/_vendor/nvd3/NVD3Chart.py line 26 in <module>
      pl = PackageLoader('nvd3', 'templates')
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/jinja2/loaders.py line 224 in __init__
      provider = get_provider(package_name)
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/pkg_resources/__init__.py line 359 in get_provider
      __import__(moduleOrReq)
   ImportError: No module named nvd3

======================================================================
2) ERROR: test_cli_connections_add_delete (tests.CliTests)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/core.py line 1073 in setUp
      self.app, self.appbuilder = application.create_app(session=Session, testing=True)
    airflow/www_rbac/app.py line 163 in create_app
      init_views(appbuilder)
    airflow/www_rbac/app.py line 91 in init_views
      from airflow.www_rbac import views
    airflow/www_rbac/views.py line 65 in <module>
      from airflow._vendor import nvd3
    airflow/_vendor/nvd3/__init__.py line 19 in <module>
      from .lineChart import lineChart
    airflow/_vendor/nvd3/lineChart.py line 12 in <module>
      from .NVD3Chart import NVD3Chart, TemplateMixin
    airflow/_vendor/nvd3/NVD3Chart.py line 26 in <module>
      pl = PackageLoader('nvd3', 'templates')
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/jinja2/loaders.py line 224 in __init__
      provider = get_provider(package_name)
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/pkg_resources/__init__.py line 359 in get_provider
      __import__(moduleOrReq)
   ImportError: No module named nvd3
```

**Comment by ashb** [comment]
I would like to see this as two _non-squashed_ commits:
- The first commit vendorising the modules and using them,
- The second commit that makes any local changes.

This will make any future maintenance or upgrading of these vendored modules easier. (This will mean that we can't merge via the GitHub button, but that's okay.)

I'm happy to do this change if you don't have time (I will on Wednesday)

**Comment by BasPH** [comment]
Out of interest: how does vendorizing a 3rd party lib result in removal of the GPL dependency?

**Comment by bolkedebruin** [comment]
@BasPH cause one of the vendorized packages was pulling in a GPL dependency. There is a package that provides the same API but we can't force the dependency on that one

**Comment by bolkedebruin** [comment]
@ashb like this?

**Comment by ashb** [comment]
Yes, thanks.

Though with Slugify 2.0 and #4506 do we still need to vendor this?

**Comment by bolkedebruin** [comment]
Yes as it doesn’t work. It’s a setuptools issue

**Comment by bolkedebruin** [comment]
@kaxil as you included #4506 in the betas this needs to go in too otherwise we would get the gpl dep.

**Comment by kaxil** [comment]
@bolkedebruin I removed #4506 (revert the commit & rebased) so won't be an issue. Do you think it 
 would take long to solve this?

**Comment by bolkedebruin** [comment]
Haha who knows ✌🏾  Only two left two fix... or hopefully they pass then you can include both again @kaxil

**Comment by ashb** [comment]
Ohh. _if_ the non-GPL module is already installed when do `pip install python-slugify` it would use that, otherwise it will pick up the GPL one. Right. :(

**Comment by kaxil** [comment]
I will cut RCs tomorrow without this PR as this PR even if completed would just work for rbac FAB UI as we have removed the old UI.

**Comment by bolkedebruin** [comment]
@Fokko @dimberman @ashb I need a bit of help: I don't understand why this fails on the kubernetes tests

**Comment by dimberman** [comment]
@bolkedebruin looking

**Comment by bolkedebruin** [comment]
Thanks @dimberman

**Comment by ashb** [comment]
Our CI doesn't display errors from the webserver container. Running it locally (with _much_ hacking) I think I finally got to the bottom of it:

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 32, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/airflow/bin/cli.py", line 848, in webserver
    app = cached_app(conf)
  File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 207, in cached_app
    app, _ = create_app(config, session, testing)
  File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 164, in create_app
    init_views(appbuilder)
  File "/usr/local/lib/python2.7/dist-packages/airflow/www/app.py", line 92, in init_views
    from airflow.www import views
  File "/usr/local/lib/python2.7/dist-packages/airflow/www/views.py", line 65, in <module>
    from airflow._vendor import nvd3
  File "/usr/local/lib/python2.7/dist-packages/airflow/_vendor/nvd3/__init__.py", line 19, in <module>
    from .lineChart import lineChart
  File "/usr/local/lib/python2.7/dist-packages/airflow/_vendor/nvd3/lineChart.py", line 12, in <module>
    from .NVD3Chart import NVD3Chart, TemplateMixin
  File "/usr/local/lib/python2.7/dist-packages/airflow/_vendor/nvd3/NVD3Chart.py", line 29, in <module>
    template_content = jinja2_env.get_template(CONTENT_FILENAME)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./content.html
```

We need to adjust MANIFEST.in so that the template files get included in the built dists.

**Comment by ashb** [comment]
The error _was_ in the log it turns out, just not where we are trained to look. 

(Anyway I spent most of the day tweaking the kube tests to make the output more readable.) Fingers crossed this build should pass now - I added the missing line to the MANIFEST.in  https://github.com/apache/airflow/pull/4513/commits/9a7fdea76c97ce88720e4ceb3a393f819f102257#diff-97c91a104c431d0c365565d3ac03ac13

**Comment by ashb** [comment]
Closed by (a manual merge)  commit 281e1ace94e07118b4b3f7c7ec15dafe616ec40f

**Pull request closed without merging**
