### PR TITLE
Making SFTPHook's constructor consistent with its superclass SSHHook

### PR DESCRIPTION
**Pull request by saveriogzz**
This is just a first dummy solution that probably scores low for elegance since I'm making both the parameters Optional.  
What do you guys think? I will adjust according to your suggestions :)

related issue: #20144 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I think adding a test for that would be nice too.

**Comment by potiuk** [comment]
(and fixing static checks - I heartily recommend installing pre-commit. It helps with the iterations a LOT.

**Comment by potiuk** [comment]
Looks good. I thin what it needs is a bit more docstring description on which parameter is preferred but looks good otherwise.

**Comment by potiuk** [comment]
You can also take a look at examples and see which connection is used there (and align with the preferred one)

**Comment by saveriogzz** [comment]
I am writing some tests and I will send a complete PR as soon as I'm done!
  
  

> You can also take a look at examples and see which connection is used there (and align with the preferred one)

Do you mean example dags?

**Comment by saveriogzz** [comment]
I am writing some tests and I will send a complete PR as soon as I'm done!
  
  

> You can also take a look at examples and see which connection is used there (and align with the preferred one)

Do you mean example dags?

**Comment by potiuk** [comment]
> Do you mean example dags?

Yep.

**Comment by saveriogzz** [comment]
I didn't find any example dag including the `SftpHook` or `Operator`!

**Comment by potiuk** [comment]
> I didn't find any example dag including the `SftpHook` or `Operator`!

:scream: How about adding one ?

**Review by potiuk — APPROVED** [review]
Ah.. I think example for that one can be added later :)

**Comment by saveriogzz** [comment]
> :scream: How about adding one ?
> 
> 

Will do!

**Comment by saveriogzz** [comment]
This should be fixed by #20756

**Comment by potiuk** [comment]
Yeah. I yanked the 2.4.0 release and 2.4.1rc1 with the fix included is up for voting. We will release it likely on Wednesday

**Comment by saveriogzz** [comment]
> Yeah. I yanked the 2.4.0 release and 2.4.1rc1 with the fix included is up for voting. We will release it likely on Wednesday

Thanks Jarek! Sorry for the mistake in my PR

**Comment by potiuk** [comment]
> Thanks Jarek! Sorry for the mistake in my PR

No worries :) Happens. That's why we have so flexible mechanims and split the release to separate providers that we can easily handle those kind of situations :).

**Pull request merged**
