### PR TITLE
[AUTH] Add kerberos and ldap authentication backends for the webserver

### PR DESCRIPTION
**Pull request by bolkedebruin**
Note: I am opening this PR to have some discussion. It is still work in progress, although functional.

This PR allows to specify the authentication backend in airflow.cfg instead of using the PYTHON_PATH. The old behavior is still available, but marked deprecated. However, if authenticate is True and the authentication backend fails to import the web server will fail to start. This is a behavioral change in order to make sure you do not run an inconsistent setup.

New config can be used adding the following (for example) the the [webserver] section of airflow.cfg

```
authenticate = True
auth_backend = airflow.contrib.auth.backend.ldap_auth
```

As an example I have included and ldap authentication module (that should work against FreeIPA and AD as well as normal LDAP servers) and a kerberos authentication module. I am not entirely sure of I got all flask-isms right, so I wouldn't mind some pointers.

Couple of questions / ideas
- I saw some talk of using Flask App Builder. Flask App Builder has a more extensive framework for authentication (roles etc). Am I doing work here that is going to be outdated soon? :-)
- Logout is not part of the standard templating where to put it (ie. this is my lack of Flask knowledge)?
- Is the change in behavior acceptable?
- ... anything I am forgetting?

### CODE REVIEW

**Comment by bolkedebruin** [comment]
I see the commits are not too clean. For merging I will clean them up.

**Comment by mistercrunch** [comment]
Thanks for the PR, I'm hoping to have some time to dig into it over the next few days

**Comment by mistercrunch** [comment]
Would mind rebasing and writing a few unit test to cover this? I should be able to see the PR in travis after that!

**Comment by bolkedebruin** [comment]
Of course. Will do tomorrow.

**Comment by bolkedebruin** [comment]
@mistercrunch unit testing the authentication mechanisms requires (I think!) to refactor app.py so it creates the app in a function, eg see http://flask.pocoo.org/snippets/20/ , to be able to pass a different configuration to the app per test. 

This looks like a good idea but also as a major undertaking. If you have a better idea how to unit test the functionality please advice. If refactoring is unavoidable (and it seems more future proof anyway), I will need some help.

**Comment by mistercrunch** [comment]
That sounds kind of brutal. Maybe something like: 

```
# assuming this import in tests/core.py
from airflow.www import app 

# inside your unit tests
# change os.environ['AIRFLOW_CONFIG'] and find some way to reload the configuration, ten
reload(app)
```

**Comment by bolkedebruin** [comment]
Ah good idea. I thought about doing the reload but I couldn't get the config to apply. I didn't try the os.environ yet though. Still the refactoring might be nice for the roadmap as it makes the unit testing much cleaner and probably some other stuff too.

**Comment by bolkedebruin** [comment]
@mistercrunch the tests work locally, but not on travis due to an importerror of the backend. I am not able to reproduce it. If you have an idea that would be appreciated.

**Comment by mistercrunch** [comment]
Is it a circular import issue?

**Comment by bolkedebruin** [comment]
Not obviously right away. The login code is not dependent on core.py or app.py . There is of course a reference to flask (login etc). But it doesn't explain why the tests work locally (./run_unit_tests.sh) and for in practice. I'll continue searching...

**Comment by bolkedebruin** [comment]
Grmbl, was missing the ldap dependency but exception got swallowed. Needs a bit more fixing, but I think I'll get there.

**Comment by bolkedebruin** [comment]
@mistercrunch this is giving me headaches :). Due to the reloading if have to put the tests last otherwise it interferes with the other tests or - I just though of it - I could do the reloading again in a teardown. Still the decorators do not seem to kick into action so I am wondering is this path is as tough as reworking app.py and as that seems more flexible towards the future it might be more opportune. 

I will see if a can do some work on that. Please let me know if you won't accept such a patch.

**Comment by mistercrunch** [comment]
Having a function that returns an app seems reasonable.

**Comment by bolkedebruin** [comment]
closing for now, as it needs more fixing.

**Pull request closed without merging**
