### PR TITLE
[AIRFLOW-2397] Support affinity policies for Kubernetes executor/operator

### PR DESCRIPTION
**Pull request by imroc**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2397
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
KubernetesPodOperator now accept a dict type parameter called "affinity", which represents a group of affinity scheduling rules (nodeAffinity, podAffinity, podAntiAffinity). API reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#affinity-v1-core

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - the example code in docs/kubernetes.rst was updated

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by imroc** [comment]
Travis test failures are unrelated.

**Comment by imroc** [comment]
@bolkedebruin @Fokko  PTAL. KubernetesPodOperator accept a new parameter called "affinity", which represents affinity policies in kubernetes, it could solve complex problems. see API : https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#affinity-v1-core

**Comment by Fokko** [comment]
Hi @imroc, thanks for the contribution. I'm aware of the affinity settings, and I think it would be a great addition to the Kubernetes executor/operator. I'll go through your PR later today. I'm working on fixing some flaky tests: https://github.com/apache/incubator-airflow/pull/3371

**Comment by imroc** [comment]
@Fokko  ok

**Review by Fokko — APPROVED** [review]
Thanks @imroc, this is a very welcome feature to the Kubernetes operator/executor!

**Pull request closed without merging**
