### PR TITLE
[AIRFLOW-1466] fix to match domain and hostname

### PR DESCRIPTION
**Pull request by l1990790120**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
https://issues.apache.org/jira/browse/AIRFLOW-1466

### Description
As on JIRA bug report

### Tests
Should not change any test, it's only to resolve cases when domain and hostname does not match (on ec2 specifically)

### CODE REVIEW

**Review by gwax — APPROVED** [review]
SGTM

**Comment by idlecool** [comment]
@l1990790120 @gwax I am running my pipeline on EMR and any task longer than 1 hour fails because of this. Any reason why this was not merged into master?

**Comment by gwax** [comment]
@idlecool I am not an Airflow committer. I help review in the hopes of reducing the burden on official committers in the hopes of getting more PRs through the process.

There is a moderate backlog at this point. You might be better off maintaining your own fork with cherry-picked commits for the hot fixes you need.

**Comment by idlecool** [comment]
Ok. Thanks @gwax 

Posting a screenshot just as a proof that this issues still exists.

banners_and_alerts_and_1__ubuntu_ip-10-10-1-106_____ssh__and_incubator-airflow_jobs_py_at_master_ _apache_incubator-airflow

**Comment by l1990790120** [comment]
@idlecool As another workaround, I couldn't remember the specifics but we were able to get around with EMR settings as well.

**Comment by idlecool** [comment]
@l1990790120 actually look back into my airflow log, the issue is still now resolved. would be curious to know what was your fix.

**Comment by r39132** [comment]
@l1990790120 can you update this to remove the conflicts. I can have another look once you do so.

**Comment by l1990790120** [comment]
ok i'll take a look the in next few

**Comment by idlecool** [comment]
@l1990790120 patch in the current PR doesn't work anymore.

Following code worked for me:

        fqdn = socket.gethostname()
        same_hostname = ti.hostname.startswith(fqdn)

But I think there will be edge cases.

**Comment by idlecool** [comment]
I have created a PR which works fine on my server - https://github.com/apache/incubator-airflow/pull/2997

**Comment by jgao54** [comment]
@idlecool  @l1990790120 

There was a [fix](https://github.com/apache/incubator-airflow/commit/181d37321ad08e3b87df2a1f87e16b8b74a24454) made a while back to change from hostname to fqdn, which makes sense since hostname alone isn't always sufficient to uniquely identify a host. So i don't think we'd want to change back to using hostname (if we do, it has to be made all across the codebase)

That said, it's very odd to me that the inconsistency occurred. ti.hostname is stored using socket.fqdn(), but in your screenshot it appears to be only the hostname part.  I suppose this could be possible if (1) the machine the celery worker is on is using a different (older) version of airflow or (2) there are some EMR setting oddity.

**Comment by l1990790120** [comment]
@jgao54 Definitely there's some settings in the AWS (not EMR but route 53). Think it breaks if we enable private dns in aws vpc (which was actually ideal) so we disabled it (with celery or not). I am not sure whether @idlecool's PR is the best way to handle this but think it's a real case.

**Comment by idlecool** [comment]
@jgao54 the workers and scheduler are running on the same machine and using the same python packages.

But I have a feeling that we are fixing the symptom and not the cause. Let me retake a look at this and find out why the values are different. As I am new to the code base, can you tell me where these values are coming from, or is there a data flow documentation?

cc. @l1990790120

**Comment by idlecool** [comment]
For starters, I don't think using socket.getfqdn() is the right thing to do. Instead, we should store IP addresses.

According to the documentation: https://docs.python.org/2/library/socket.html#socket.getfqdn

> Return a fully qualified domain name for name. If name is omitted or empty, it is interpreted as the local host. To find the fully qualified name, the hostname returned by `gethostbyaddr()` is checked, followed by aliases for the host, if available. The first name which includes a period is selected. In case no fully qualified domain name is available, the hostname as returned by `gethostname()` is returned.

We cannot rely on the consistency of `getfqdn()`'s output and should use IP address instead.

@jgao54 Any reason why we chose to use the hostname instead of IP address?

**Comment by idlecool** [comment]
@jgao54 @l1990790120 

Please check the screenshot:

`getfqdn()`'s output is not consistent.

**Comment by idlecool** [comment]
more proof:





raw text if you want to copy:

```
1517533576153
ip-10-10-1-106
1517534009048
ip-10-10-1-106
1517534359281
ip-10-10-1-106
1517534824432
ip-10-10-1-106
1517535699895
ip-10-10-1-106
```

**Comment by jgao54** [comment]
@idlecool Thanks for investigating this! Given the results above, it looks like every once a while fqdn can't be resolved so it defaulted to the hostname instead. 

Not familiar with why we started with using hostname... I guess that it was easier to read and easier to implement, since for IP a host can have multiple network interfaces with multiple IPs so we'd want to make sure the right one is selected. In terms of using IP instead of fqdn,  it sounds reasonable... as long as backward compatibility is addressed.

Given that getfqdn will return hostname if it fails to resolve... I'm inclined towards your PR #2997 as a simpler solution

**Comment by jgao54** [comment]
Resolved by #3036, this can be closed, thanks!

**Comment by abdullahodibat** [comment]
Hello, i installed airflow locally and i am trying to integrate with AWS batch however i keep getting this error, and then airflow kills the batch task:
`The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname IT-Administrators-MacBook-Pro-4.local`

im using airflow 1.10.6

**Comment by MemphisMeng** [comment]
> Hello, i installed airflow locally and i am trying to integrate with AWS batch however i keep getting this error, and then airflow kills the batch task: `The recorded hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa does not match this instance's hostname IT-Administrators-MacBook-Pro-4.local`
> 
> im using airflow 1.10.6

@abdullahodibat Have you resolved this issue? I encountered this when I was using airflow 2.6.

**Comment by ramykl** [comment]
I'm getting this with airflow 2.9.2

**Pull request closed without merging**
