### PR TITLE
Restrict "build images" workflow to certain branches

### PR DESCRIPTION
**Pull request by kaxil**
Currently, since we don't restrict it, on forks this runs the build step on all branches

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
And I believe it should. Otherwise images will not build for any PRs that someone runs on their own branch. Is there any problem with that?

**Comment by kaxil** [comment]
> And I believe it should. Otherwise images will not build for any PRs that someone runs on their own branch. Is there any problem with that?

Updated in https://github.com/apache/airflow/pull/12599/commits/ef121f84497c0bf4b523df7b45c40227267583d2 to only run it on pull_request.

The problem currently is that this build is trying to run on all branches where we don't expect users to create PRs too

**Comment by potiuk** [comment]
> Updated in [ef121f8](https://github.com/apache/airflow/commit/ef121f84497c0bf4b523df7b45c40227267583d2) to only run it on pull_request.
> 
> The problem currently is that this build is trying to run on all branches where we don't expect users to create PRs too and it is running on `pushes` on branch too

Not good either - the workflow run is also used to build images for direct pushes to master/v1-10-test/v1-10-stable. 

I think it should be "if" check on (event_type=="push" and "branch" not in ("master". "v1-10-test'" , "v1-10-stable')) so that we can continue testing pushes in our forks for the same branches as in apache/airflow

**Comment by kaxil** [comment]
> I think it should be "if" check on (event_type=="push" and "branch" not in ("master". "v1-10-test'" , "v1-10-stable')) so that we can continue testing pushes in our forks for the same branches as in apache/airflow

You mean "if" check on (event_type=="push" and "branch" ~not~ in ("master". "v1-10-test'" , "v1-10-stable'))

right? I pushed https://github.com/apache/airflow/pull/12599/commits/ec5219b05c3d15be5920b79799c1b02970bb2dd3 ,  can you verify if that is what you meant?

**Comment by potiuk** [comment]
Sorry - been distracted yesterday. 

I look up the specification https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run and I think it should be simply limited via "branches" not based on event type relly. The "worklfow_run" can be triggered by:

1) push
2) pull 
3) schedule 

From the docs, it seems that this can be achieved by simply adding  "branches" without specifying the event that triggers it. We are already limited to those three triggering events because the depending "workflow" only runs on PR/Push/Schedule:: 

```
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
      - requested

```

But I think it should be tested. The best way (and thje way I tested it ) was to push it to my own fork and test it there.

**Comment by potiuk** [comment]
What I usually test it with: 

1) schedule
2) PR from own repo
3) PR from fork of your fork
4) direct push to "master"/"v1-10-test"

**Comment by kaxil** [comment]
> What I usually test it with:
> 
> 1. schedule
> 2. PR from own repo
> 3. PR from fork of your fork
> 4. direct push to "master"/"v1-10-test"

Yeah I tested the 1st commit: https://github.com/apache/airflow/pull/12599/commits/364544ca788797c626fa716737ebdf6d92f2edb2 with direct pushes to different branches and master/v1-10-test but will further test with PRs on those branches

**Pull request closed without merging**
