### PR TITLE
[AIRFLOW-2665] Use shlex to split args and remove shell true

### PR DESCRIPTION
**Pull request by barrachri**
Make sure you have checked _all_ steps below.

### Jira

- [x] Jira ticket: https://issues.apache.org/jira/browse/AIRFLOW-2665

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Currently airflow doesn't support running commands without a `bash` available, there are not UI changes.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This part was already covered by tests.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by barrachri** [comment]
I have a small doubt, what is the proper format of a `command`?:

```
    def execute_work(self, key, command):
        """
        Executes command received and stores result state in queue.
        :param key: the key to identify the TI
        :type key: Tuple(dag_id, task_id, execution_date)
        :param command: the command to execute
        :type command: string
        """
```
because looking at the code seems should be a string...but looks like a small lie, because tests were passing a`list` (this is why I added the `isinstance` check).

**Comment by Fokko** [comment]
@bolkedebruin PTAL

**Comment by ron819** [comment]
Is there update for this?

**Comment by ashb** [comment]
I don't think this change is needed anymore - since #3740 was merged the command is always a list, so no need to split it.

**Pull request closed without merging**
