### PR TITLE
Add devcontainer\Codespace with Breeze

### PR DESCRIPTION
**Pull request by sgromme**
- new style devcontainer.json

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — COMMENTED** [review]
Could you please elaborate and in case you are fixing/updating codespaces/devcontainers support could you:

* update https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START_CODESPACES.rst
* and see what is to be done with https://github.com/apache/airflow/tree/main/.devcontainer 

We have guidelines for running Airflow development env in codespaces. It might or might not work as we do not check it regularly, but if we are to get some "devcontainer" changes - the docs need to be updated and in case the new .devcontainer replaces the old one, you need to elaborate on that a bit.

**Comment by sgromme** [comment]
- Added the new Breeze devcontainer(Codespace) for Breeze support   - integration and testing ( like Gitpod.io)
- CONTRIBUTORS_QUICK_START_CODESPACES.rst  will be updated next
- /.devcontainer  devcontainer.json files (qty 3) will be updated.

**Comment by sgromme** [comment]
Github Codespaces has around ~50 hours free for each month vs Gitpods around ~ 5 hours.

**Comment by potiuk** [comment]
>  Github Codespaces has around ~50 hours free for each month vs Gitpods around ~ 5 hours.

You completely missed the point. I linked you the "codespaces" support not Github - you seem to be adding what we already have (might be broken, but fixing if it is, is the right way, not adding another devcontainer.json when we already have one that starts breeze in codespaces.

**Comment by sgromme** [comment]
Instead of adding new code will fix the devcontainers.

**Pull request closed without merging**
