### PR TITLE
[AIRFLOW-2326] Remove duplicate GCS to GCS operator

### PR DESCRIPTION
**Pull request by berislavlopac**
Addresses [AIRFLOW-2326](https://issues.apache.org/jira/browse/AIRFLOW-2326) "Duplicate GCS copy operator".

### Description
This patch removes one of the two operators with the same functionality. Out of the two, I have removed the `gcs_copy_operator` for two reasons:

1. The other one, `gcs_to_gcs.GoogleCloudStorageToGoogleCloudStorageOperator` follows the naming structure of other operators that move data (e.g. `gcs_to_bq.GoogleCloudStorageToBigQueryOperator`).
2. `GoogleCloudStorageToGoogleCloudStorageOperator` has a bit more functionality, allowing for moving files (i.e. deleting the originals). This pattern can be used for extending the moving functionality to e.g. `rewrite`, as I propose in [AIRFLOW-2222](https://issues.apache.org/jira/browse/AIRFLOW-2222).

### CODE REVIEW

**Comment by Fokko** [comment]
Ai caramba, this is awkward. I agree that the [GoogleCloudStorageToGoogleCloudStorageOperator](https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/operators/gcs_to_gcs.py) has a bit more functionality (for example, moving instead of copying), compared to the [GoogleCloudStorageCopyOperator](https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/operators/gcs_copy_operator.py).

I've checked, and both of them aren't in Airflow 1.9, so we're safe of deleting either one of them. @kaxil Any thoughts?

**Comment by kaxil** [comment]
@Fokko I agree and LGTM. `GoogleCloudStorageToGoogleCloudStorageOperator` provides more functionality as compared to `gcs_copy_operator`. I had that in mind when I was reviewing `GoogleCloudStorageToGoogleCloudStorageOperator` to remove the other one but it slipped out of my mind. Thanks @berislavlopac for this PR.

**Comment by kaxil** [comment]
Can you however fix the comments in integration.rst for `GoogleCloudStorageToGoogleCloudStorageOperator` ?

The one that says:
```
- :ref:`GoogleCloudStorageToGoogleCloudStorageOperator` : Copies a single object from a bucket to another, with renaming if requested.
```

**Comment by berislavlopac** [comment]
@kaxil You're welcome! :)

Fix the comments in what way?

On a related note, I have just discovered a problem with `GoogleCloudStorageToGoogleCloudStorageOperator` when using wildcard, I'll create a separate issue and fix for that (it appends a prefix even if it is not given).

**Comment by kaxil** [comment]
When using wildcard it has to append a prefix. The GCS Rest API doesn't have wildcards in it. You can, however, simulate wildcard by using Prefix and/or Delimiter.

Regarding fixing comment:
Currently, it says:
"Copies a single object from a bucket to another, with renaming if requested."

Change it something like:
"Copies/movies objects from a bucket to another. Renaming is also supported for a single object"

**Comment by berislavlopac** [comment]
Thanks, I didn't catch that in the docs, will fix.

Re the prefix, it currently does this:
```
    hook.copy(self.source_bucket, source_object,
              self.destination_bucket, "{}/{}".format(self.destination_object,
                                                      source_object))
```
If destination is `None` (the default) the file will land in `None/{source_object}`, and if it's an empty string it goes to `/{source_object}`. Basically, it should not prepend `destination_object` if it's empty.

**Comment by kaxil** [comment]
@berislavlopac True. You are right. There needs to be an if condition added.

Can you also remove "source_object" from Line 105:
https://github.com/apache/incubator-airflow/blob/3f1bfd38cd5a1c9c58045004390a6a766bec5e8d/airflow/contrib/operators/gcs_to_gcs.py#L105 . I think the 5th parameter is useless.

@Fokko @berislavlopac : Let's first resolve the issue with `GoogleCloudStorageToGoogleCloudStorageOperator` with a different PR and then come back to this PR. Until then let's not merge this one as I have tried and tested `GoogleCloudStorageCopyOperator` multiple times. Once the issues are resolved we can merge this PR and if possible please add some unit tests.

@berislavlopac Can you please fix the issue with `GoogleCloudStorageToGoogleCloudStorageOperator`? Thanks.

**Comment by berislavlopac** [comment]
@kaxil Sure, I'll make the changes in a new PR, and will open a new ticket in Jira for that.

**Comment by berislavlopac** [comment]
The other PR was created at #3233

**Comment by berislavlopac** [comment]
@kaxil The #3233 has been merged, I guess we can look into this one now?

**Comment by kaxil** [comment]
Surely.

Can you however fix the comments in integration.rst for `GoogleCloudStorageToGoogleCloudStorageOperator` ?

The one that says:
```
- :ref:`GoogleCloudStorageToGoogleCloudStorageOperator` : Copies a single object from a bucket to another, with renaming if requested.
```

**Comment by berislavlopac** [comment]
Ah yes, I missed that when doing the other PR. Updated now.

**Comment by Fokko** [comment]
@kaxil Any final thoughts?

**Comment by kaxil** [comment]
@Fokko . This LGTM now.

**Review by Fokko — APPROVED** [review]
Thanks @berislavlopac and @kaxil for the feedback

**Pull request closed without merging**
