### PR TITLE
Increasing typing coverage for Docker

### PR DESCRIPTION
**Pull request by OmairK**
This PR would increase typing coverage for docker provider #9708 
---
Make sure to mark the boxes below before creating PR: [x]
- [ ] Description above provides context of the change
- [ ] Unit tests coverage for changes (not needed for documentation changes)
- [ ] Target Github ISSUE in description if exists
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions.
- [ ] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
Some static checks are sad. Can you fix it?

**Comment by OmairK** [comment]
> Some static checks are sad. Can you fix it?

@mik-laj @potiuk I guess mypy is getting lost in types here. I have been using docker py's documentation for return type annotations but it's still throwing errors. How should I proceed?

**Comment by potiuk** [comment]
I've added a fixup: there were two problems -> Iterable is "read only" - so it has no "append" method - so the type should be List explicitly. And clie is set to None initially, and it **should** be initialized, but adding explicit flow to handle the case where it is None, helps mypy to understand that it cannot be None.

**Comment by potiuk** [comment]
I've also added a comment to "decode" method. I remember (it was discussed in one of the bug fixes long time ago) that we can get byte sequence rather than string in some cases from the Kubernetes API, so this "if "decode"" is there to handle this case. Somehow after the other fixes mypy "understood" that the "decode" attribute is checked one line above and it stopped complaining.

**Comment by OmairK** [comment]
> I've added a fixup: there were two problems -> Iterable is "read only" - so it has no "append" method - so the type should be List explicitly. And clie is set to None initially, and it **should** be initialized, but adding explicit flow to handle the case where it is None, helps mypy to understand that it cannot be None.

Oh I was totally missing the **explicit flow** part and was looking at the code subjectively. Thank you very much :smile:

**Comment by potiuk** [comment]
Still there are some indentation problems and example should use keyword parameters in the operator (that's why backport packages are failing) :)

**Comment by potiuk** [comment]
But you can take it from here :)

**Comment by mik-laj** [comment]
@OmairK Can you do a rebase?

**Comment by OmairK** [comment]
> @OmairK Can you do a rebase?

Done

**Review by potiuk — APPROVED** [review]

**Pull request merged**
