### PR TITLE
feat:  list of syntax-highlighted SQL statements

### LINKED ISSUE #13988: List and Dict template fields are rendered as JSON.
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): n/a

**Environment**: Linux

- **Cloud provider or hardware configuration**: amd64
- **OS** (e.g. from /etc/os-release): Centos 7
- **Kernel** (e.g. `uname -a`):
- **Install tools**: pip
- **Others**:

**What happened**:

The field `sql` is rendered as a serialized json `["select 1 from dual", "select 2 from dual"]` instead of a list of syntax-highlighted SQL statements.

image

**What you expected to happen**:

`lists` and `dicts` should be rendered as lists and dicts rather than serialized json unless the `template_field_renderer` is `json`

image

**How to reproduce it**:

```
from airflow import DAG
from airflow.providers.oracle.operators.oracle import OracleOperator

with DAG("demo", default_args={owner='airflow'}, start_date= pendulum.yesterday(), schedule_interval='@daily',) as dag:
    OracleOperator(task_id='single', sql='select 1 from dual')
    OracleOperator(task_id='list', sql=['select 1 from dual', 'select 2 from dual'])
```

**Anything else we need to know**:

Introduced by #11061, .

A quick and dirty work-around:

Edit file [airflow/www/views.py](https://github.com/PolideaInternal/airflow/blob/13ba1ec5494848d4a54b3291bd8db5841bfad72e/airflow/www/views.py#L673)

```
            if renderer in renderers:
-                if isinstance(content, (dict, list)):
+               if isinstance(content, (dict, list)) and renderer is renderers['json']:
                    content = json.dumps(content, sort_keys=True, indent=4)
                html_dict[template_field] = renderers[renderer](content)
```

### PR DESCRIPTION
**Pull request by anushkrishnav**
---
Fixed #13988 

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Please review this @turbaszek

**Comment by turbaszek** [comment]
@anushkrishnav it seems that this issues was already fixed in https://github.com/apache/airflow/pull/14024

**Comment by jhtimmins** [comment]
@turbaszek @anushkrishnav can we close this as it appears to have been fixed elsewhere?

**Comment by turbaszek** [comment]
@anushkrishnav please reopen if you think the issue wasn't fixed properly

**Comment by anushkrishnav** [comment]
I think it has been fixed

**Pull request closed without merging**
