### PR TITLE
Add version check for k8s setup venv command

### PR DESCRIPTION
**Pull request by potiuk**
This command install airflow in k8s venv and in case version of Python is not yet supported by Airflow, it might fail.

We do not have check it lower-bound because breeze supports the same minimum version of Airflow as Airflow itself.

The command prints instructions on how to reinstall breeze with different Python version in such case.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
It will print instructions like this (but with 3.12 not 3.8)

Screenshot 2024-01-08 at 22 34 18

It will automatically adjust when Python 3.12 is supported.

**Comment by potiuk** [comment]
cc: @V0lantis

**Review by hussein-awala — APPROVED** [review]
LGTM, I wonder if we need to add a check for the versions smaller than the lower_python_version

**Comment by potiuk** [comment]
Nope. See the commit message :)

> We do not have check it lower-bound because breeze supports the same minimum version of Airflow as Airflow itself.

**Pull request merged**
