### PR TITLE
Pin moto to <2

### PR DESCRIPTION
**Pull request by kaxil**
https://pypi.org/project/moto/#history -- moto 2.0.0 was released yesterday and is causing CI failures.

Example Failure: https://github.com/apache/airflow/pull/14406/checks?check_run_id=1973102416#step:6:3130

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — APPROVED** [review]
LGTM

**Comment by potiuk** [comment]
Not sure how moto release could break it. For regular PRs constraints should limit the version installed. Upgrading to latest constraints should only happen if someone modified setup.py in the PR

**Comment by kaxil** [comment]
> Not sure how moto release could break it. For regular PRs constraints should limit the version installed. Upgrading to latest constraints should only happen if someone modified setup.py in the PR

Check: https://github.com/apache/airflow/runs/1973021580?check_suite_focus=true#step:9:3215

**Comment by potiuk** [comment]
#14437  should fix this for the future..

**Comment by potiuk** [comment]
You can see it here: https://github.com/apache/airflow/runs/1973019420?check_suite_focus=true#step:6:444

  **Full tests requested by label on PR. Running everything** _<-- This is what triggered it_
  needs-api-tests=true
  needs-api-codegen=true
  needs-helm-tests=true
  needs-javascript-scans=true
  needs-python-scans=true
  run-tests=true
  run-kubernetes-tests=true
  test-types=Always Core Other API CLI Providers WWW Integration Heisentests
  basic-checks-only=false
  docs-build=true
  image-build=true
  **upgrade-to-newer-dependencies=64407e5bdc12ee945966fa9218cc57bc724e67ae** _<--- this caused the upgrade_
  
  Finished the script selective_ci_checks.sh
  Elapsed time spent in the script: 0 seconds
  Exit code 0

**Pull request merged**
