### PR TITLE
[AIRFLOW-994] Add MiNODES to the official airflow user list

### PR DESCRIPTION
**Pull request by dice89**
Please accept this PR that adds MiNODES to the official airflow user list.

### CODE REVIEW

**Comment by jlowin** [comment]
@dice89 please place yourself in the list alphabetically

**Comment by jlowin** [comment]
You'll also need to create a JIRA issue (I know it seems disproportionate but it is Apache development policy)

**Comment by dice89** [comment]
@jlowin Done, didn't realise that the list is ordered alphabetically (kind of stupid from my side). 

Here is the link to the [issue](https://issues.apache.org/jira/browse/AIRFLOW-994)

**Comment by jlowin** [comment]
Thanks! +1

**Pull request closed without merging**
