### PR TITLE
Add more type hints to the code base

### PR DESCRIPTION
**Pull request by uranusjr**
This is mainly driven by eliminating `session=None` usages. And since using `NEW_SESSION` makes many previously untyped functions become typed and checked by Mypy, a cascade of minor type hinting issues are surfaced and fixed in this PR.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
That's really useful. This will make some of my refactorings for AIP-44 show a bit more things that need fixing, but I was actually counting on those to complete the AIP-44, and that would be great if those are merged before.

**Comment by potiuk** [comment]
(pending fixing the static checks/tests of course).

**Comment by uranusjr** [comment]
Some test failures in views. Converting to draft for now since I don’t have time to investigate at the moment.

**Comment by potiuk** [comment]
> Some test failures in views. Converting to draft for now since I don’t have time to investigate at the moment.

I can take a look and fix those if needs be.

**Comment by uranusjr** [comment]
OK seems fixed…

**Review by potiuk — APPROVED** [review]

**Pull request merged**
