### PR TITLE
Add Azure Data Factory example DAG

### PR DESCRIPTION
**Pull request by flvndh**
Target #14758

### CODE REVIEW

**Comment by flvndh** [comment]
@turbaszek @ephraimbuddy Could you have a look at it please?

**Comment by ephraimbuddy** [comment]
@flvndh can you also add a system test to verify this example dag?

**Comment by flvndh** [comment]
@ephraimbuddy what do you mean by that ?

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy what do you mean by that ?

Hi @flvndh, here is an example system test https://github.com/apache/airflow/blob/master/tests/providers/microsoft/azure/transfers/test_file_to_wasb_system.py
It helps ensure that the example dag works fine.
Here's how you can run it:
```
pytest tests/providers/microsoft/azure/transfers/test_file_to_wasb_system.py --system azure -s
```

**Pull request closed without merging**
