### PR TITLE
Fix DAG-level permissions disappearance on DAG sync

### LINKED ISSUE #32839: DAG-level permissions set in Web UI disappear from roles on DAG sync
### Apache Airflow version

2.6.3

### What happened

Versions: 2.6.2, 2.6.3, main

PR [#30340](https://github.com/apache/airflow/pull/30340) introduced a bug that happens whenever a DAG gets updated or a new DAG is added

**Potential fix:** Adding the code that was removed in PR [#30340](https://github.com/apache/airflow/pull/30340) back to `airflow/models/dagbag.py` fixes the issue. I've tried it on the current main branch using Breeze.

### What you think should happen instead

Permissions set in Web UI stay whenever a DAG sync happens

### How to reproduce

1. Download `docker-compose.yaml`:
```bash
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.6.2/docker-compose.yaml'
```
2. Create dirs and set the right Airflow user:
```bash
mkdir -p ./dags ./logs ./plugins ./config && \
echo -e "AIRFLOW_UID=$(id -u)" > .env
```
4. Add `test_dag.py` to ./dags:
```python
import datetime

import pendulum

from airflow import DAG
from airflow.operators.bash import BashOperator

with DAG(
    dag_id="test",
    schedule="0 0 * * *",
    start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
    catchup=False,
    dagrun_timeout=datetime.timedelta(minutes=60),
) as dag:
    test = BashOperator(
        task_id="test",
        bash_command="echo 1",
    )
if __name__ == "__main__":
    dag.test()
```
5. Run docker compose: `docker compose up`
6. Create role in Web UI: Security > List Roles > Add a new record:
	Name: test
	Permissions: `can read on DAG:test`
7. Update `test_dag.py`: change `bash_command="echo 1"` to `bash_command="echo 2"`
8. Check test role's permissions: `can read on DAG:test` will be removed

Another option is to add a new dag instead of changing the existing one:
6. Add another dag to ./dags, code doesn't matter
7. Restart scheduler: `docker restart [scheduler container name]`
9. Check test role's permissions: `can read on DAG:test` will be removed

### Operating System

Ubuntu 22.04.1 LTS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

Docker 24.0.2

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by TruthIsNear**
Closes: #32839 

Adds back the code that was removed in #30340 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
How does this affect the issue #30340 is supposed to solve?

Also cc @huymq1710

**Comment by TruthIsNear** [comment]
> How does this affect the issue #30340 is supposed to solve?

Seems like this PR does introduce that issue back

**Comment by potiuk** [comment]
I rebased it and marked is as 2.7.0. Indeed the #30340 removed syncing where it was still needed and reverting the change seems to solve the problem. 

I think this is a blocker for people who use it and want to migrate so having it fixed in 2.7.0 would be great.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I am not sure however if that one is just a band-aid.

Can someone - who knows how the logic of dag permissions syncing was supposed to work? I would like to understand it, because it seems that almost no-one knows how it should work and it is certainly not documented.  A slimple logical description of what should happen here might be very useful. I am hppy to take a closer look and try to do it properly. but I need some guidance. I've never touched this part of code and it's a bit of mistery for me on how it **should** work - but I ema willing to learn @kaxil @jedcunningham @uranusjr. Maybe a birds eye view on that one ??

I think we dropped a ball on that one for 2.6.2 and mostly because we had too little expert knowledge there.

**Comment by potiuk** [comment]
I thin @SamWheating #33632 solution is a better solution. Closing this one in favour of it.

**Comment by potiuk** [comment]
Closing in favour of just merged https://github.com/apache/airflow/pull/33632

**Pull request closed without merging**
