### PR TITLE
Fix the deprecated parameter in hvac client

### LINKED ISSUE #31347: Deprecation warning for hvac `read_secret_version` parameter in Hashicorp Vault client
### Apache Airflow version

2.6.1

### What happened

If you're using the Hashicorp Vault as your secrets backend, any calls to the functions in `vault_client.py` results in warnings like below in logs:

```
/data/apps/.pyenv/versions/3.10.4/envs/airflow-py310/lib/python3.10/site-packages/airflow/providers/hashicorp/_internal_client/vault_client.py:357 DeprecationWarning: The raise_on_delete
d parameter will change its default value to False in hvac v3.0.0. The current default of True will presere previous behavior. To use the old behavior with no warning, explicitly set this value to True. See https://github.com/hvac/h
vac/pull/907
```

This is because of a breaking change in the vault client `hvac` package, specifically in the `read_secret_version` function. A previously optional parameter `raise_on_deleted_version`, is now defaults to False, and should be explicitly set to True for keeping the previous behavior.

### What you think should happen instead

There shouldn't be any deprecation warnings, parameter needs to be set explicitly.

### How to reproduce

Setup hashicorp vault as the secrets backend
Run any airflow command that needs to access the secrets backend

### Operating System

RHEL 8.5

### Versions of Apache Airflow Providers

```
apache-airflow-providers-celery==3.1.0
apache-airflow-providers-common-sql==1.4.0
apache-airflow-providers-ftp==3.3.1
apache-airflow-providers-hashicorp==3.3.1
apache-airflow-providers-http==4.3.0
apache-airflow-providers-imap==3.1.1
apache-airflow-providers-microsoft-mssql==3.3.2
apache-airflow-providers-mysql==5.0.0
apache-airflow-providers-odbc==3.2.1
apache-airflow-providers-sftp==4.2.4
apache-airflow-providers-sqlite==3.3.2
apache-airflow-providers-ssh==3.6.0
```

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by emredjan**
Adds an explicit parameter to fix deprecation warnings in `hvac` client, as described in https://github.com/hvac/hvac/pull/907

closes: #31347 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — CHANGES_REQUESTED** [review]
The `raise_on_deleted_version` parameter was introduced in hvac 1.1.0. Using it with an older version will result in an exception because the read_secret_version method does not accept additional kwargs:
https://github.com/briantist/hvac/blob/669ddfc935014f37273655d6b4b9f7e44661ddf0/hvac/api/secrets_engines/kv_v2.py#L104-L110

If we want to provide a value for the `raise_on_deleted_version` argument, we need to check the hvac version and add it only for versions >= 1.1.0. We can remove this check when we increase the minimum required hvac version to 1.1.0 ([here](https://github.com/apache/airflow/blob/7ebda3898db2eee72d043a9565a674dea72cd8fa/airflow/providers/hashicorp/provider.yaml#L46-L46)).

**Review by hussein-awala — CHANGES_REQUESTED** [review]
The `raise_on_deleted_version` parameter was introduced in hvac 1.1.0. Using it with an older version will result in an exception because the read_secret_version method does not accept additional kwargs:
https://github.com/briantist/hvac/blob/669ddfc935014f37273655d6b4b9f7e44661ddf0/hvac/api/secrets_engines/kv_v2.py#L104-L110

If we want to provide a value for the `raise_on_deleted_version` argument, we need to check the hvac version and add it only for versions >= 1.1.0. We can remove this check when we increase the minimum required hvac version to 1.1.0 ([here](https://github.com/apache/airflow/blob/7ebda3898db2eee72d043a9565a674dea72cd8fa/airflow/providers/hashicorp/provider.yaml#L46-L46)).

**Comment by hussein-awala** [comment]
> Would it be acceptable to implement this via the importlib, or would that be unnecessary overhead?

If I am not mistaken, this method is not available in Python 3.7 (it was introduced in Python 3.8), and since #30963 has not been merged yet, we cannot use it.

**Comment by emredjan** [comment]
> > Would it be acceptable to implement this via the importlib, or would that be unnecessary overhead?
> 
> If I am not mistaken, this method is not available in Python 3.7 (it was introduced in Python 3.8), and since #30963 has not been merged yet, we cannot use it.

Yes, I just saw that. It's available in 3.8+. 3.7 support will end on 2023-06-27, but until then, do you have another suggestion to check the library version?

**Comment by hussein-awala** [comment]
Can you try this?
```python
import sys
if sys.version_info < (3, 8):
    from importlib_metadata import version
else:
    from importlib.metadata import version
hvac_version = version("hvac")
```

**Comment by emredjan** [comment]
Unfortunately I don't have enough knowledge about how to update the tests to take the new function signatures into account 😞. Can someone else pick that part up?

**Comment by potiuk** [comment]
> Unfortunately I don't have enough knowledge about how to update the tests to take the new function signatures into account 😞. Can someone else pick that part up?

It's a great opportunity to learn.

**Review by hussein-awala — COMMENTED** [review]
Could you add a new test which patch `version` and test with 2 different versions, one older than 1.1.0 and another >= 1.1.0?

**Comment by eladkal** [comment]
@emredjan are you still working on this PR?

**Comment by potiuk** [comment]
We've not done that before for PRS - but marked it as "good first issue" for someone to pick up

**Comment by eladkal** [comment]
We have an open issue for this one so added the label there and I guess we can close this one as stale.
hopefully someone will pick it up

**Comment by eladkal** [comment]
closing as stale.
we have open issue to track this task. If someone is interested in completing this please open a new PR

**Pull request closed without merging**
