### PR TITLE
[AIRFLOW-1368] Automatically remove the container when it exits

### PR DESCRIPTION
**Pull request by nathanielvarona**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [AIRFLOW-1368](https://issues.apache.org/jira/browse/AIRFLOW-1368) issues and references them in the PR title.

### Description
- [x] Here are some details about my PR, including an addition to a docker dag argument:
```
from airflow.operators.docker_operator import DockerOperator

task  = DockerOperator(
    ...
    auto_remove=True
    ...
```

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Tested locally and mock ready

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by adambabik** [comment]
+1 

Really, no one is interested in this feature? This PR has just a few lines changed and is easy to review.

**Comment by seancron** [comment]
@criccomini Any chance we can get this in 1.9? I can help test it if needed, but looks like a pretty straightforward PR.

**Comment by criccomini** [comment]
+1 LGTM

**Comment by bolkedebruin** [comment]
@criccomini @nathanielvarona this build wasn't tested and it does not pass tests. Can this be fixed or reverted please?

**Comment by criccomini** [comment]
Woah, I saw the green thingy. How did it not run tests. Weird.

**Comment by criccomini** [comment]
Reverting

**Comment by criccomini** [comment]
Done.

**Comment by criccomini** [comment]
@seancron if you want to re-open and fix test, go for it.

**Comment by dalupus** [comment]
looks like this didn't get reverted or something.   All tests are failing now.

**Comment by criccomini** [comment]
Derp, sorry. I think @bolkedebruin stepped in and fixed it. I forgot to push the revert. 😞

**Pull request closed without merging**
