### PR TITLE
[AIRFLOW-XXX] Upgrade support to python 3.5 and disable dask

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by mrocklin** [comment]
Checking in here.  Was there anything in particular on the Dask side that was troublesome?

**Comment by bolkedebruin** [comment]
If you have a look at some past builds on Travis many of them failed with errors in “distributed” and “tornado” ioloop. Sometimes with connection timeouts but often also other errors. It affected random tests and only disabling Dask tests resolved it (I tried some other strategies first). 

@mrocklin

**Comment by mrocklin** [comment]
I spot checked a couple travis error reports at https://travis-ci.org/apache/incubator-airflow/builds and didn't see anything, although this is likely just because I'm less familiar with reading Airflow's test output.  Can I trouble you to point me to a specific case with a traceback?  In the future, error reports like this would be quite welcome.

**Comment by tooptoop4** [comment]
Can tests be reenabled?

**Pull request merged**
