### PR TITLE
Resume yandex provider

### PR DESCRIPTION
**Pull request by s0neq**
Yandex Provider was suspended in https://github.com/apache/airflow/pull/30667 
This PR is for resuming Yandex Provider in Airflow releases

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
> Oh. Welcome back `yandex provider` ... Indeed I see that protobuf dependency has been bumped. Let's see where it gets us :)

Breeze tests needs to be updated as well.

**Comment by Piatachock** [comment]
GLTM from Yandex

**Comment by s0neq** [comment]
hi, Jarek, hi Peter!

there are some strange problems in tests, should I close and reopen the Pull Request?

from [Helm: CeleryExecutor - true - v1.24.15 v1.25.11 v1.26.6 v1.27.3](https://github.com/apache/airflow/actions/runs/5924333348/job/16063483717?pr=33574#logs)

We are extremely sorry but you've hit the rare case that the credentials you got from GitHub Actions to run are expired, and we cannot do much.
¯\_(ツ)_/¯

You have the following options now:

  * Close and reopen the Pull Request of yours
  * Rebase or amend your commit and push your branch again
  * Ask in the PR to re-run the failed job

**Comment by potiuk** [comment]
1). There is a "build-docs" failure to fix (the links to `changelog` and `security` pages were moved and yandex doc is still pointing to the old location

2) there is another issue with `pip` backtracking but I will take a look at it after the 1) is fixed

The other issues are just "rebuild" needed - but when you fix the docs and push, the build will re-run for all of them

**Comment by s0neq** [comment]
@potiuk build-docs is fixed, please take a look at the second issue

**Comment by potiuk** [comment]
> @potiuk build-docs is fixed, please take a look at the second issue

Interesting one. It actually revealed an interesting bug/edge case/optimization possibility. 

And it motivated me to implement https://github.com/apache/airflow/pull/33603 - optimization that I wanted to do for some time.

What happened in this case - the job that failed was run as part of provider check and in this check we do two things:

1) we simulate preparation of provider decumentation - as if release manager run the documentation generation (helps us to check if the tooling still works)
2) then we build provider packages
 
The point 1) modified provider.yaml files for all the providers that were updated since last release (including yandex)

Then, when 2) was attempted, breeze detected that provider.yaml files changed and attempted to rebuild the CI image  - normally it is a "no-op" because we just built the image with the constraints. But yandex provider has no constraints generated, so `pip` attempted to build the image without constraints, and apparently some of the constraints of yandes are not compatible with the current set of constraints so building the image faild.

The optimization in  #33603 will solve it in a bit indirect way - when provider.yaml are updated by documentation preparation, breeze will first attempt to regenerate "generated/provider_dependencies.json" and only this file change it will attempt to rebuild the image. 

Result - slightly faster and more accurate "check providers" job in CI, less frequent prompts for rebuilding the image for regular developers in breeze, the "generated/provider_dependencies.json" will be generated as needed when you just run breeze, without the need to have pre-commit installed.

Once #33603 gets merged. you should rebase and I believe the job will succeed.

**Comment by potiuk** [comment]
OK. Merged my change. Now rebased to see if it helps

**Comment by potiuk** [comment]
The ARM image failure is irrelevant. Merging.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
AAAND merged !

**Comment by s0neq** [comment]
> AAAND merged !

yayy thanks!

**Comment by potiuk** [comment]
Question to @eladkal but we usually release providers every 2-3 weeks. We also would likely want to release providers before 2.7.1 is out (~ week or so). So generally speaking sooner rather than later

**Comment by eladkal** [comment]
I'll do my best to get to it soon

**Pull request merged**
