### PR TITLE
CI - OpenID Connect authorication to AWS

### PR DESCRIPTION
**Pull request by TobKed**
Hardening security by using OIDC to authorize access to AWS.

Requires setting up `DOCS_AWS_ROLE_TO_ASSUME` in GA secrets
(in case of using instructions listed below this value is available under `ROLE_ARN` variable),
`DOCS_AWS_ACCESS_KEY_ID` and `DOCS_AWS_SECRET_ACCESS_KEY` secrets will not be necessary anymore and could be deleted.

## TODO:

- [x] - trust and policy json files
- [x] - instructions to setup OIDC on AWS

## Trust policy for role

`aws_role_for_ga.json` in the instructions listed below.

`<AWS_ACCOUNT_ID>` should be replaced with proper value. It could be obtained with command
`aws sts get-caller-identity --query "Account" --output text`

I am not sure is such strict policy necessary (redundant to job conditions).

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "RoleForGitHubActions",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/token.actions.githubusercontent.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "token.actions.githubusercontent.com:aud": "sts.amazonaws.com",
          "token.actions.githubusercontent.com:sub": "repo:apache/airflow:ref:refs/heads/main",
          "token.actions.githubusercontent.com:event_name": "push"
        }
      }
    }
  ]
}
```

## Policy for S3 bucket

`aws_bucket_policy.json` in the instructions listed below.

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:ListAllMyBuckets",
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListBucket",
        "s3:GetBucketLocation"
      ],
      "Resource": "arn:aws:s3:::apache-airflow-docs"
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:PutObjectAcl",
        "s3:GetObject",
        "s3:GetObjectAcl",
        "s3:DeleteObject"
      ],
      "Resource": "arn:aws:s3:::apache-airflow-docs/*"
    }
  ]
}
```

## Instructions

1. Prerequisites:

   - installed and configured [`aws cli`](https://aws.amazon.com/cli/)
   - installed  openssl

1. Exports

   ```sh
   export REGION=eu-central-1
   export ROLE_NAME=RoleForGitHubActions

   export ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)

   aws configure set region "${REGION}"
   ```

1. OpenID Connect Identity Provider [IdP] thumbprint:

   ```sh
   export OIDC_IDP_THUMBPRINT=$(
     echo 1 | \
     openssl s_client -servername token.actions.githubusercontent.com -showcerts -connect token.actions.githubusercontent.com:443 2>/dev/null \
     | sed -n '/BEGIN\ CERTIFICATE/,/END\ CERTIFICATE/ p' \
     | sed -n '/END CERTIFICATE/,$ p' \
     | tail -n +2 \
     | openssl x509 -fingerprint -noout \
     | sed -e 's/^SHA1\ Fingerprint=//' | \
     sed -e 's/://g'
   )
   ```

   Based on [AWS - Obtaining the thumbprint for an OpenID Connect Identity Provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html)

1. IAM OIDC Identity Provider:

   ```sh
   aws iam create-open-id-connect-provider \
     --url "https://token.actions.githubusercontent.com" \
     --client-id-list "sts.amazonaws.com" \
     --thumbprint-list "${OIDC_IDP_THUMBPRINT}"
   ```

1. IAM Role and Policy:

   ```sh
   export POLICY_ARN=$(aws iam create-policy --policy-name S3Access --policy-document file://aws_bucket_policy.json --query "Policy.Arn" --output text)
   export ROLE_ARN=$(aws iam create-role --role-name "${ROLE_NAME}" --assume-role-policy-document file://aws_role_for_ga.json --query "Role.Arn" --output text)
   aws iam attach-role-policy --role-name "${ROLE_NAME}" --policy-arn "${POLICY_ARN}"
   ```

1. Value for `DOCS_AWS_ROLE_TO_ASSUME` secret:

   ```sh
   echo $ROLE_ARN
   ```

### Links

Instructions based on : https://github.com/TobKed/github_actions_oidc/

More information about  GItHub Actions and OIDC:

 - [The GitHub Blog: GitHub Actions: Secure cloud deployments with OpenID Connect](https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect/)
 - [GitHub Docs - About security hardening with OpenID Connect](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect)
 - [GitHub Docs - Configuring OpenID Connect in Amazon Web Services](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)
 - [AWS - Creating OpenID Connect (OIDC) identity providers](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
 - [AWS - Creating a role for web identity or OpenID connect federation (console) ](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-idp_oidc.html)
 - [AWS - Obtaining the thumbprint for an OpenID Connect Identity Provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Really nice @ashb - we can get rid of the AWS secrets this way :)

**Comment by ashb** [comment]
Oh yeah, I saw something about this the other week, then forgot it entirely.

**Comment by ashb** [comment]
We'll need to configure our AWS account to trust this too right?

**Comment by potiuk** [comment]
> We'll need to configure our AWS account to trust this too right?

Yep. @TobKed provided instructions

**Comment by TobKed** [comment]
I've just updated instructions.

**Comment by mik-laj** [comment]
Thanks for doing this task I thought for a long time to do it, but I couldn't find the time to do it. If you want it, I can call you over the weekend and set up an AWS account to check it out.

**Comment by TobKed** [comment]
With @mik-laj we tested OIDC in other project and [`permissions`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idpermissions) should be tested before merging. I will do it in incoming week.

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
I updated the ARN so now I'm merging to test it.

**Comment by potiuk** [comment]
Cool

**Comment by ashb** [comment]
This hasn't worked https://github.com/apache/airflow/runs/4472124262?check_suite_focus=true -- and I've added `sts:AssumeRole` to the instance profile permission, but even after 15 minutes (more than enough time for IAM to propagate changes) I can't even get `aws sts assume-role` to work form one of the AWS self-hosted runners.

Hmmmm

**Comment by ashb** [comment]
Corection, the instance profile _doesn't_ have the perms on the S3 bucket.

**Pull request merged**
