### PR TITLE
Rename DAG concurrency settings for easier understanding

### PR DESCRIPTION
**Pull request by kaxil**
``dag_concurrency `` ->  ``max_active_tasks_per_dag``

**ToDo**:

- [x] Add an example scenario where these settings will be useful: 
`max_active_tasks_per_dag `: "To stop a new dag with an early start date from stealing all the executor slots in a cluster?"
- [x] Rename `DAG.concurrency`
- [x] Add note in UPDATING.md
- [ ] Rename `BaseOperator.task_concurrency` settings too. (**Will do this as a separate PR as the change is becoming quite BIG**)

Some of Airflow's concurrency settings have been a source of confusion for a lot of users (including me), for example:

- https://stackoverflow.com/questions/56370720/how-to-control-the-parallelism-or-concurrency-of-an-airflow-installation
- https://stackoverflow.com/questions/38200666/airflow-parallelism

This PR is an attempt to make the settings easier to understand

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by ryanahamilton — APPROVED** [review]
I appreciate how I very clearly know what this means by just reading the name.

**Review by ephraimbuddy — APPROVED** [review]
This makes a lot of sense now! Thanks Kaxil! 

Just some REST API test fix. LGTM

**Comment by jbmeerkat** [comment]
Very clear name `max_active_tasks_per_dag` became obscured `max_active_tis_per_dag` somehow. How did it happen? This "tis" is not clear at all 😞

**Comment by potiuk** [comment]
> Very clear name `max_active_tasks_per_dag` became obscured `max_active_tis_per_dag` somehow. How did it happen? This "tis" is not clear at all disappointed

Your praised very simple `max_active_tasks_per_dag` was simply wrong name. There is a difference between task and task instance. The `tis` is often used all over the code for `task_instance` and this is right. `max_activet_tasks_instances_per_dag` would be simply too long. 

It's all perfectly logical and accurate. As opposed to previous name which was wrong and illogical.

**Comment by jbmeerkat** [comment]
> Your praised very simple `max_active_tasks_per_dag` was simply wrong name. There is a difference between task and task instance. The `tis` is often used all over the code for `task_instance` and this is right. `max_activet_tasks_instances_per_dag` would be simply too long.
> 
> It's all perfectly logical and accurate. As opposed to previous name which was wrong and illogical.

Jarec thank you very much for clarification. Now I see why that changed! 

To be more clear I'm looking not from an Airflow developer perspective but from an Airflow user perspective, so I don't know how it's named in the code. I just updated my Airflow instance and started to see a deprecation warnings about this "tis" 😄 

I'm not trying to dispute that name, just telling about my experience.

**Comment by potiuk** [comment]
> I'm not trying to dispute that name, just telling about my experience.

And I am just answering your question - very precisely and accurately "How did it happen".

**Comment by jbmeerkat** [comment]
> > I'm not trying to dispute that name, just telling about my experience.
> 
> And I am just answering your question - very precisely and accurately - "How did it happen?".

Thank you for that!

**Pull request merged**
