### PR TITLE
Fix license headers

### PR DESCRIPTION
**Pull request by bolkedebruin**
cc: @Fokko 

Enjoy :-)

### CODE REVIEW

**Comment by cbockman** [comment]
A nit, but, unless this is how the original Apache is, can we fix spacing?

+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license **agreements.See** the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the **License.You** may obtain a copy of the License at

--> 

+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements. See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License. You may obtain a copy of the License at

**Comment by bolkedebruin** [comment]
Thanks for checking. Probably a copy paste error on my side. Fortunately I can just rerun the script that generates this. Thanks for reviewing!

**Comment by Fokko** [comment]
I still have some files with the old header:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ grep -R "# you may not use this file except in compliance with the License." .
./docs/Makefile:# you may not use this file except in compliance with the License.
./airflow/bin/airflow:# you may not use this file except in compliance with the License.
./airflow/utils/log/wasb_task_handler.py:# you may not use this file except in compliance with the License.
./scripts/systemd/airflow:# you may not use this file except in compliance with the License.
```

**Comment by bolkedebruin** [comment]
@Fokko except was_task_handler (encoding issue probbaly) the rest was picked up when I ran it manually. Im pushing a new version in a few minutes

**Comment by Fokko** [comment]
@bolkedebruin Conflicts :(

**Comment by artwr** [comment]
Should we mark files we reviewed, or will that be too many notifications :)

**Comment by jgao54** [comment]
@bolkedebruin  thanks for taking this on!

did some spot checking and looks like [flake8_diff.sh](https://github.com/apache/incubator-airflow/blob/master/scripts/ci/flake8_diff.sh) got left out.  I'm assuming it's intentional since it's a different license, but not sure if we need to add the apache one on top

also nit-pick a bit:  some files in `scripts/` dir have a slightly different format (i.e. load_data.sh), the content looks identical though

**Comment by bolkedebruin** [comment]
@jgao54 thanks for checking! `flake8_diff.sh` has a different license (BSD-3). I'm not rewriting licenses (because I shouldn't) in case they are different (but compatible with ASL2) or contain a copyright notice (because its not ours).

In this case its both :-).

**Review by Fokko — APPROVED** [review]
LGTM:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ grep -R "# you may not use this file except in compliance with the License." .
Binary file ./docs/_build/doctrees/environment.pickle matches
grep: ./airflow/www/static/docs: No such file or directory
grep: ./airflow/www_rbac/static/docs: No such file or directory
```

Thanks @bolkedebruin

**Pull request closed without merging**
