### PR TITLE
Revert "Deprecation of AutoML services: Add deprecation warnings and raise exceptions for already deprecated ones"

### PR DESCRIPTION
**Pull request by Taragolis**
Reverts apache/airflow#38673

This PR constains explicit change filter warnings in `AutoMLTablesUpdateDatasetOperator` and `AutoMLDeployModelOperator` by provide `action="error"` into the decorator which looks like an worst practice, because it can't be controlled by the end users.

If this functional still exists and users could use it we should not raise an error here, user might want to control it by provide `-W` flag to the interpreter or `PYTHONWARNINGS` env var: see [Warning control](https://docs.python.org/3/library/warnings.html#the-warnings-filter)

If this functional not exists we could:
- Just raise a warning, so we would warn end users that this functional not exists
- Explicitly raise `AirflowException` (we do not have appropriate exception, even if we add it it will available in Airflow 2.10+) in constructor (`__init__`) method

There is difference `deprecated and `removed`. Deprecated mean this functional still available (even if limited) but removed mean that this functional not available anymore. We should not use deprecated meaning in case when functional removed.

There is an option to change by the separate PR instead of this revert.
 cc: @VladaZakharova @molcay @shahar1

### CODE REVIEW

**Comment by molcay** [comment]
Hi @Taragolis,
 I think reverting to PR is not a good idea. We change a lot of things and the services all ready in the sunset stage. Reverting is not a solution here. If the main problem is only related to `action="error"` we can ditch the `deprecated` decorator and use `AirflowException`.

As you suggested, we can raise the `AirflowException` 
> we are already raising this for other operators with the help of the method: `_raise_exception_for_deprecated_operator`)  

for the following classes: `AutoMLTablesUpdateDatasetOperator` and `AutoMLDeployModelOperator` .

If this is OK, I will try to prepare a new PR which include this change

**Comment by shahar1** [comment]
@Taragolis Thanks for pointing it out; I wasn't aware of this matter while reviewing previous PR.
@molcay I'd be happy to review your fix :)

**Comment by molcay** [comment]
Hi @Taragolis,

We realized that we can do this change within a PR (#39752) that is already created for the community. 

@e-galan will be sending the changes accordingly for #39752 and we can merge that PR to fix all of the `action="error"` misuse (2 operators from this PR: `AutoMLTablesUpdateDatasetOperator`, `AutoMLDeployModelOperator` and 2 operators from #39752).

@shahar1 you can review #39752

@eladkal if you can follow the #39752 for releasing the next provider version for `apache-airflow-providers-google`.

**Comment by eladkal** [comment]
Now that https://github.com/apache/airflow/pull/39752 is merged. Can we close this PR?

**Comment by molcay** [comment]
@eladkal Yes, we can close this PR.

**Pull request closed without merging**
