### PR TITLE
[AIRFLOW-5745] Breeze complete has licence nown

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5745

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Are there any other missing ones that RAT isn't checking?

**Comment by kaxil** [comment]
I am curious why RAT was not checking this? Was it because it had no file extension ?

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
@kaxil Jarek told me that it was part of the `.dockerignore`. So the file was not inside of the Docker image that ran the RAT checker.

**Comment by Fokko** [comment]
Pushed onto `v1-10-test` as well :-)

**Comment by potiuk** [comment]
Yep. That was the thing. It was excluded via .dockerignore. I will make a small modification to the scripts to mount all source files in CI (even those .dockerignored) specifically for RAT checker. 
It will make it different that local checks - mounting all sources on Mac  make the checks a loooot slower (combined node_modules and slow osxfs). 

There is only one question why it was not detected by insert-license pre-commit hook (it was configured to include that file as well and should be detected and added automatically but for some reason it was not). I am looking into it.

**Comment by potiuk** [comment]
OK. It was because breeze-complete was non-executable and [shell] type specified in pre-commit checks also for executable flag. Removed the [shell] type (left .sh only) in #6425

**Pull request merged**
