### PR TITLE
[AIRFLOW-1787] Fix task instance batch clear and set state bugs

### PR DESCRIPTION
**Pull request by KevinYang21**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1787

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Batch clear in Task Instances view is not working for task instances in RUNNING state and all batch operations in Task instances view cannot work when manually triggered task instances are selected because they have a different execution date format.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Added test_parse_execution_date() in tests/utils/test_dates.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by KevinYang21** [comment]
@aoen PTAL
Thank you

**Comment by aoen** [comment]
LGTM

**Comment by bolkedebruin** [comment]
@aoen should this be included in 1.9.0 RC2 maybe? cc @criccomini

**Comment by criccomini** [comment]
Seems like we would want this in 1.9.0. I'm fine with an RC2 to address it.

**Comment by aoen** [comment]
Definitely makes sense if the yrqls21's PR that added batch clearing to the CRUD was included in the RC, otherwise I think we could skip this one (and might have merge conflicts if we try to include it).

**Comment by criccomini** [comment]
I'm going to skip this one for 1.9.0 due to merge conflict, as @aoen called out.

**Pull request closed without merging**
