### PR TITLE
[AIRFLOW-2510] Introduce new macros: prev_ds and next_ds

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2510
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Introduce two new macros:
{{ prev_ds }}: the previous execution date as {{ YYYY-MM-DD }}
{{ next_ds }}: the next execution date as {{ YYYY-MM-DD }}

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
hey Chao-han, please rebase the master :)

**Comment by milton0825** [comment]
@feng-tao Already rebased the master...

**Comment by milton0825** [comment]
PTAL @kaxil @Fokko

**Comment by Fokko** [comment]
@milton0825 this looks good. Maybe a small elaboration in the docs with an example? Since the difference between `yesterday_ds` and `prev_ds` is quite subtile in some situations.

**Comment by milton0825** [comment]
@Fokko updated!

**Comment by feng-tao** [comment]
You could also close and reopen the pr to retrigger the travis to run. Sometimes it is due to transient issue from travis CI side.

**Comment by artwr** [comment]
@feng-tao, let's not and have @milton0825 setup Travis on his own fork and point to the successful result. Apache Infra has reached out to us to explain we are consuming to much compute time on Travis...

**Comment by Fokko** [comment]
@artwr Has a very good point here. The way of developing is always on your own Travis, or local using a Docker container.

**Comment by milton0825** [comment]
Looks like the failing tests on CI are not transient. I will close the PR and fix it

**Pull request closed without merging**
