### PR TITLE
[AIRFLOW-6508] Update the version of cattrs from 0.9 to 1.0

### PR DESCRIPTION
**Pull request by sarutak**
cattrs 0.9 with Python 3.8 causes following error.
```
$ airflow
Traceback (most recent call last):
  File "/Users/sarutak/airflow-env/bin/airflow", line 27, in <module>
    from airflow.bin.cli import CLIFactory
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/airflow/__init__.py", line 40, in <module>
    from airflow.models.dag import DAG
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/airflow/models/__init__.py", line 21, in <module>
    from airflow.models.baseoperator import BaseOperator, BaseOperatorLink  # noqa: F401
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 41, in <module>
    from airflow.lineage import apply_lineage, prepare_lineage
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/airflow/lineage/__init__.py", line 28, in <module>
    from cattr import structure, unstructure
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/cattr/converters.py", line 3, in <module>
    from ._compat import (
  File "/Users/sarutak/airflow-env/lib/python3.8/site-packages/cattr/_compat.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/opt/python/3.8.0/lib/python3.8/typing.py) 
```
This issue is resolved in cattrs 1.0.
https://github.com/Tinche/cattrs/pull/73

So let's update it.

---
Issue link: [AIRFLOW-6508](https://issues.apache.org/jira/browse/AIRFLOW-6508/)

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by feluelle — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by danieltahara** [comment]
Can you issue a patch version bump? This was merged Jan 8 but I still can't use it :(

**Comment by danieltahara** [comment]
How is this still not in 1.10rcs? @potiuk @feluelle

**Comment by potiuk** [comment]
@kaxil -> could we merge this in rc5 as well? This is also a requirement-only change as per rc5 sqlalchemy ? I think it is pretty safe.

**Comment by potiuk** [comment]
On the other hand... If this is only for python 3.8 compatibility, then maybe better to do it in 1.10.1.-> then we could add support to python 3.8 in master and test it in 1.10.11 as well. This is a major version change for cattrs, so there is a risk some obscure problems might occur.


@danieltahara -> we have not yet officially got Python 3.8 compatibility yet not even in master: https://github.com/apache/airflow/blob/master/README.md#master-version-200dev , and there is high chance other things will break with python 3.8 so I think It's better to wait for it until we officially add (and run all tests) for python 3.8. In the meantime 3.6 and 3.7 are also very good choices.

**Comment by kaxil** [comment]
Yes, we don't support Python 3.8 at the moment. Last I check cattrs was still buggy for 1.0.0 & Py3.8

So it will definitely have to wait for next release.

**Comment by danieltahara** [comment]
Hi all,

Thanks for the responses. I think I'm finding it confusing that a commit would get merged into master and not used. If it doesn't break 3.6 and 3.7 tests (which it doesn't, since it got merged), and 3.8 is build your own adventure anyway (b/c it's not officially supported), then I don't see the harm in including it in the release.

I understand you have a very specific release branch flow, but the idea a commit can sit for 4 months on master seems like overhead for y'all (cherrypicking, mental overhead of remembering NOT to include the commit) and confusion for the public.

That said, I completely respect that outcome and really appreciate the work you do maintaining the project. Thanks!

**Comment by potiuk** [comment]
Jut to explain - The flow is only because we are now in a process of working on  backwards incompatible 2.0 release but in the meantime we release bugfixes and even some features in 1.10 line. It is an overhead indeed but we have to be mindful to our users who want to still have bugs solved and some minor features added and 2.0 version is going to be a bit more difficult to upgrade for them (and it can take months or years because of corporate limitations). 

And we do not have to remember of not cherry-picking BTW - we only cherry-pick what we think is worth it. Most of the changes from master branch are not cherry-picked to 1.10.

Surprisingly - it works quite well so far.

**Comment by kaxil** [comment]
To add to what Jarek said, we support Python 2 on Airflow 1.10.* branches, while we don't in Master so, makes cherry-picking process a bit harder for now but provides a good balance between development with new versions will backporting imp features.

**Pull request merged**
