### PR TITLE
Workarounds docker-compose-v2 environment passing

### PR DESCRIPTION
**Pull request by potiuk**
The docker-compose v2 parsing of env file bug detected
in #16949 and eventual disabling of docker-compose-v2 in #16989
found another workaround after discussing with docker-compose
maintainers in https://github.com/docker/compose-cli/issues/1917

The VAR=${VAR} pattern seems to work for all cases for Airflow
because we never rely on the fact if variable is set or not -
we always take into account value of the variable (that is by
design and strictly followed everywhere). Therefore we are
sure this workaround is going to work for us.

However we should remove that workaround once the bug is fixed in
Docker-Compose V2.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@oyarushe  - so it turned out to be more complex but we seem to have a temporary workaround that seems to works for both docker and docker-compose (see https://github.com/docker/compose-cli/issues/1917)

**Comment by oyarushe** [comment]
> @oyarushe - so it turned out to be more complex but we seem to have a temporary workaround that seems to works for both docker and docker-compose (see [docker/compose-cli#1917](https://github.com/docker/compose-cli/issues/1917))

yeah, I monitored all things regarding it. Nice work @potiuk!
and thanks for fixing my fix :)

**Comment by potiuk** [comment]
ACH And found a problem there with PACKAGE_FORMAT variable :)

**Comment by potiuk** [comment]
closing as this does not really work for docker.

**Pull request closed without merging**
