### PR TITLE
Sftp Sensor Newer Than Parameter

### PR DESCRIPTION
**Pull request by AdamPaslawski**
Add a parameter newer_than to the sftp sensor to allow for specifying a datetime for which the file in the SFTP site should be newer than.

Related PR: #21811

I closed it because I ruined the commit history.

### CODE REVIEW

**Comment by AdamPaslawski** [comment]
Hello @potiuk , I made the change to convert all dates to UTC as discussed in #21811.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Static checks are failing

**Comment by AdamPaslawski** [comment]
> Static checks are failing

Hi @potiuk ,

They are failing because I am providing a default value of None to the newer_than parameter which is not of type DateTime. I think it makes sense to allow for a default of None.

I checked for inspiration in areas of the project like in airflow.providers.amazon.aws.sensors.s3.S3KeySensor where defaults are set as None in the same way for parameters with specific datatypes.

Is there another design pattern I can use to pass the static checks but still allow for a default of None?

**Comment by potiuk** [comment]
Just see all the other cases. We are following "strict-optional" which means that when you set something to None, it should be Optional[x] - I guesss? But if it does not work, just look at the rest of the code and try to find similar problems and solutions.

**Comment by potiuk** [comment]
Note the LOCATION of the error. It is NOT in definition of the field type, but definition of the constructor (from what I see S3KeySensor has the Optional[x] type in constructor and you don't - so that's the mistake you overlooked I guess.

**Comment by AdamPaslawski** [comment]
@potiuk That makes perfect sense, I really appreciate the help! 

Tests and static checks are passing in breeze now.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
