### PR TITLE
Add an example on pool usage in the documentation

### PR DESCRIPTION
**Pull request by ledsusop**
initial pull request and doc change

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Hi lusop. Thanks for the contribution! Please follow these http://chris.beams.io/posts/git-commit/ guidelines for your commit message. It helps creating changelogs and release notes in the future. Thanks!

**Comment by ledsusop** [comment]
alright @bolkedebruin , do you need me to reissue a pull request?

**Comment by bolkedebruin** [comment]
Just update your commit message. Git commit --amend , git push --force

**Comment by ledsusop** [comment]
done

**Pull request merged**
