### PR TITLE
[AIRFLOW-6232] Add link to XCom section in concepts.rst

### PR DESCRIPTION
**Pull request by pradeepbhadani**
Add link to `XCom` section in cocepts.rst

### CODE REVIEW

**Comment by dimberman** [comment]
@pradeepbhadani please create a JIRA and add to the title of this PR

**Comment by mik-laj** [comment]
@dimberman This is just a change in the documentation. Does this require a ticket?

**Comment by pradeepbhadani** [comment]
@dimberman Created https://issues.apache.org/jira/browse/AIRFLOW-6232 and updated title PR.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Yeah. I merged it changing the prefix to AIRFLOW-XXX as this was doc only change. @pradeepbhadani  -> thanks for that ! JIRA was not really needed, so sorry for the hassle. But we are looking forward also to code contribution that will require JIRA, now you know how to do it ;).

**Comment by dimberman** [comment]
sorry about that @pradeepbhadani :)

**Comment by pradeepbhadani** [comment]
No worries :)
@mik-laj  @dimberman @potiuk  - thanks for reviewing my PR.

**Pull request merged**
