### PR TITLE
Refactor DAG tabs navigation

### LINKED ISSUE #34489: Counterintuitive functionality when viewing mapped TIs from Grid View
### Apache Airflow version

2.7.1

### What happened

When a user clicks on a mapped TI, the "[] Mapped Tasks" button is replaced by a "Logs" button, and returning to the "Mapped task summary" moves to the side of the view:

image

___
___

image

### What you think should happen instead

Instead, I think the "[] Mapped Tasks" button should remain in the same place, and instead, a "Logs [0]" tab/button should be added just next to the "[] Mapped Tasks" button. In this example, "[0]" represents  that 0th mapped TI has been clicked into:

image

### How to reproduce

Open the UI in 2.7 for a mapped task

### Operating System

n/a

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
We got rid of all of the old DAG pages and their buttons. But in the grid view, the tabs displayed depended on the task+run selection. It was then confusing as to where views disappeared to. Instead, let's show the DAG level, Run level and Task level  tabs. Therefore the more general tabs are always accessible on the page.

Also, moved the "full screen" expand button outside of Graph+Logs and it can be accessed at all times.

Fixes: https://github.com/apache/airflow/issues/34489

Screenshot 2024-03-28 at 3 37 53 PM
Screenshot 2024-03-28 at 3 37 41 PM
Screenshot 2024-03-28 at 3 37 33 PM

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jedcunningham** [comment]
I pulled this up and experimented with it for a few minutes. I like it. It's intuitive and easy to use.

**Review by eladkal — APPROVED** [review]
I love it!

I asked in Slack but will also post it here...
I think Log view is much more needed than task details view. I think it's better to allow less click to get to the logs

**Review by hussein-awala — APPROVED** [review]
Looks good, LGTM!

**Comment by jscheffl** [comment]
My Feedback:

1. @ephraimbuddy even if a late arrival, can we get this into 2.9?
2. The DAG/Run/Task Details are the most common and standard informations. I'd propose to put them first in the order of tabs on the rows. image
3. On the other hand the "Breadcrumbs" are just for information but have no active function. Could we also "use" them and make them clickable like a tab and use this instead of the DAG/Run/Task details? So in the example above if you click on "sum_it" you actually get the task details panel below and we don't need the screen space for a "Task detail" tab? And make this display per default. This would also pay-in the comment of @eladkal "but as a general comment have to say it's getting really crowded and overloaded."
4. As like in the past I need a lot of clicks to navigate between logs of different mapped tasks. As also @eladkal mentioned most often we take a look to logs. In our case most often between mapped as well. Woult it be possible to make the break crumb element of the task being a drop-down so that I can switch to another task log/xcom/details with a selection change? Might be worth to have all tasks - mapped and unmapped listed in dropdown directly.
image
5. The "More Details" and "Rendered Template" links are actually the last leftovers form the previous FAB based UI. Can we have them as tabs as well in the Grid? :-) Would also like to contribute to get rid of this, but don't know if I have capacity during the weekend... being on easter vacation image

Besides these comments and ideas - I LOVE this! It would be a realy cool cleanup of the navigation and makes it cleaner and much easier to understand how to navigate for users!

When finalized a global update of screenshots in the docs should follow! I'd raise my hand to clean behind to contribute to this cool rework!

**Review by phanikumv — APPROVED** [review]

**Comment by vatsrahul1001** [comment]
Love it! I agree with the changes proposed by @jscheffl. I noticed a few issues while checking the logs for the mapped task:

1. The vertical scroll bar in the grid view doesn't work properly.
2. I noticed some log duplications when grouping and was unable to scroll to the bottom to view logs when expanding the grouping.
3. The options for logs download and wrapping to the next line are missing.

https://github.com/apache/airflow/assets/43964496/5d1da51f-40af-45a9-a338-196ee1ff0331

**Comment by bbovenzi** [comment]
Closing in favor of a different approach.

**Comment by jscheffl** [comment]
@bbovenzi Meaning closing in (1) favor _not_ blocking 2.9 release and make the rework in 2.10 or (2) another PR that you open (soon)?

**Pull request closed without merging**
