### PR TITLE
Add template fields renderers to Biguery and Dataproc operators

### PR DESCRIPTION
**Pull request by turbaszek**
Related to #11177 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by RosterIn** [comment]
Airflow has come to a very weird place where providers shows code lines that can never be used due to key functionality is missing in official airflow releases.
In that example this renders behavior was added to BaseOperator but was never released.
https://github.com/apache/airflow/pull/11061

This resulting in us users saying "wow this is cool! lets try this" only to eventually see that we can't because the core feature wasn't release in any official version.

For me it looks like a case where the extension pack of a game is released before the game.

**Comment by turbaszek** [comment]
> For me it looks like a case where the extension pack of a game is released before the game.

@RosterIn this will be part of Airflow 2.0. We do not cherrypick every change to 1.10 line, so this change is not unique :)

**Comment by turbaszek** [comment]
> > For me it looks like a case where the extension pack of a game is released before the game.
> 
> @RosterIn this will be part of Airflow 2.0. We do not cherrypick every change to 1.10 line, so this change is not unique :) But I understand your disappointment. We need providers to ease migration but we also needs to move on with new features. What would you suggest to do?

**Review by potiuk — APPROVED** [review]

**Comment by kaxil** [comment]
Tried rebasing but missing permissions:

```
❯  git push github-desktop-turbaszek HEAD:template-renderes-bq-dataproc -f
remote: Permission to PolideaInternal/airflow.git denied to kaxil.
fatal: unable to access 'https://github.com/PolideaInternal/airflow.git/': The requested URL returned error: 403
```

Can you please rebase on latest master please

**Comment by turbaszek** [comment]
> Tried rebasing but missing permissions:
> 
> ```
> ❯  git push github-desktop-turbaszek HEAD:template-renderes-bq-dataproc -f
> remote: Permission to PolideaInternal/airflow.git denied to kaxil.
> fatal: unable to access 'https://github.com/PolideaInternal/airflow.git/': The requested URL returned error: 403
> ```
> 
> Can you please rebase on latest master please

@kaxil check this tool: https://github.com/ldez/prm kudos to @mik-laj

**Comment by kaxil** [comment]
> @kaxil check this tool: https://github.com/ldez/prm kudos to @mik-laj

That looks good, thanks @turbaszek and @mik-laj

**Pull request merged**
