### PR TITLE
[AIRFLOW-1023] reconnect to S3 bucket location

### PR DESCRIPTION
**Pull request by adrpar**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title:

   https://issues.apache.org/jira/browse/AIRFLOW-1023

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR provides a work around in the S3 hook to a boto issue that results in `Connection reset by peer` errors when uploading files to S3 buckets that are located in non standard US locations (e.g. eu-west-1).

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No unit test is provided, since the S3 related functionality in `S3_hook.py` is not covered with unit tests and this is inherent to S3 and will be hard (if not impossible) to mock.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Great addition but the absence of unit tests does not exempt you from adding them. Please do, thx.

**Comment by adrpar** [comment]
@bolkedebruin I would be happy to provide unit tests for this fix if you could point me to the facility on where this can be done. This fix requires calls to a AWS S3 bucket that resides in a non US location. Do you provide such a bucket that can be called? And further more, this is more of an integration test, rather than a unit test, how are you dealing with those?

I have been looking at `test/operators/s3_to_hive_operator.py` but the actual talking to S3 is mocked away. Any thoughs on how I can achieve this?

**Comment by adrpar** [comment]
What I can offer though is to cover the code with moto. It does not cover the regression, but might be better than nothing.

**Comment by bolkedebruin** [comment]
Seems reasonable

**Comment by adrpar** [comment]
I have covered my change with a unit tests. Why is travis flaky on uploading to coveralls? I cannot get it pass and it always fails for different sub-jobs.

**Comment by adrpar** [comment]
travis passed... anything more for me to do here?

**Comment by bolkedebruin** [comment]
Please rebase and put the tests in their own respective location (not in core, but mirroring the file location). Then I will merge if tests run and pass.

**Comment by adrpar** [comment]
done. I also took the liberty to move the already existing S3Hook test from core to the new file.

**Comment by adrpar** [comment]
I rebased this again. Had to version pin the moto library, since newest 1.0 version does not support boto anymore. Only boto3 support is continued.

**Comment by ashb** [comment]
I think this doesn't apply anymore with the change to use boto3 for the S3 hook.

If I'm wrong please re-open this issue.

**Pull request closed without merging**
