### PR TITLE
[AIRFLOW-5796] Fix case when slot_pool relation is missing

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5796

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by ashb** [comment]
Not a huge fan of doing it this way, especially as there are other ways DAGs can throw errors that show up during migrations.

**Comment by potiuk** [comment]
I looked into it - it's really only in the "slot_pool" related coode and I am also checking for "slot_pool" in the exception message (and re-raise the exception if it is not found) so I think it is pretty safe. I can extend the message even more (i.e. 'relation "slot_pool" does not exist') as expected message if it makes you more comfortable :).

**Comment by ashb** [comment]
If I put this in my dag:

```

with dag:
    if Variable.get('x'):
        PythonOperator(task_id='noop', provide_context=True, python_callable=print_exec_date_tz)

```

(which is a trick I have seen used to disable tasks in certain envs) then I get an error thrown too.

**Comment by potiuk** [comment]
I guess this is a different error then ?

BTW. I realised now - Isn't that really a bad practice to access the DB in the init() of the operator (or in the DAG). That makes extra DB connection/query to be created/used during parsing of the DAG and it's rather disturbing (so maybe we should actually correct the SubDagOperator to not make the pool query in the init() ? There were some discussions recently about a number of DB connections opened needlessly and that might be one of the culprits actually.

**Comment by ashb** [comment]
Not checking the DB in `__init__` would be a better fix, yes!

**Comment by ashb** [comment]
I guess the reason it was validated there is so that the error is reported at a DAG parse time though.

**Comment by Fokko** [comment]
I don't like to swallow the exception. We should move this query out of the `__init__` method as Ash suggested.

**Comment by ashb** [comment]
See also https://github.com/apache/airflow/pull/6379. That will add the same sort of feature to _every_ Operator. It makes sense from a user point of view to error quickly.

Hmmm!

**Comment by feluelle** [comment]
+1 for moving it out of `__init__`.

**Pull request closed without merging**
