### PR TITLE
Increase Health Check parameters for mssql integration

### PR DESCRIPTION
**Pull request by potiuk**
The values for mssql integration were too low, particularly the timeout of 3s was far too low. Per documentation:
https://github.com/docker/cli/blob/5bf86c198488c7f78f2ffd05a8a2441f719d3b98/docs/reference/builder.md#healthcheck

Increasing the values shoudl bring stability back.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
CC: @shahar1

**Comment by potiuk** [comment]
Currently it randomly fails - for example https://github.com/apache/airflow/actions/runs/9256599429/job/25463195510?pr=39851

**Review by vincbeck — APPROVED** [review]

**Comment by potiuk** [comment]
BTW. Those values are pure guesses :), so it might not help either (but they are high enough it should if this is really a problem with slow startup time for mssql

**Comment by shahar1** [comment]
Thanks!
Now that I think of it, when I implemented the test - I noticed that there were times that the health check failed randomly on start when loading it with breeze. I assume that adding time would work

Some related reading materials that I found:
https://stackoverflow.com/questions/60539114/how-to-wait-for-mssql-in-docker-compose

**Comment by shahar1** [comment]
https://github.com/apache/airflow/actions/runs/9256982108/job/25464448138

It's still not happy, maybe we could somehow inject [this script](https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh) to  as the healthcheck entrypoint? (wasn't sure how to do it though)

**Comment by potiuk** [comment]
Next attempt - let's see. In the logs you can enable showing timestamp and I saw a few successful tests where it took ~18 s for the mssql container to start - dangerously close to 20s we had.

**Pull request merged**
