### PR TITLE
[AIRFLOW-3617] Kubernetes gpu support

### PR DESCRIPTION
**Pull request by CatarinaSilva**
# Jira

- [x] My PR addresses the following [AIRFLOW-3617](https://issues.apache.org/jira/browse/AIRFLOW-3617/) issue and references it in the PR title. 
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR:
This PR does not break any behavior, but adds the possibility of passingn GPU limits (which are automatically copied to requests, as per official documentation - https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/ .

### Tests

- [x] My PR changes the following unit tests:
  - TestKubernetesRequestFactory (`/airflow/tests/kubernetes/kubernetes_request_factory/test_kubernetes_request_factory.py`)
  - TestPodRequestFactory (`airflow/tests/kubernetes/kubernetes_request_factory/test_kubernetes_request_factory.py`)

### Commits
- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. 

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by CatarinaSilva** [comment]
not sure who to tag for review, but fyi @ashb @mik-laj (I saw you are reviewers in several other PRs)

**Comment by pgagnon** [comment]
@dimberman

**Comment by potiuk** [comment]
@CatarinaSilva -> please rebase and push so that Travis can build it. Travis had a problem whole day yesterday.

**Comment by CatarinaSilva** [comment]
Hi @potiuk I did that, I just noticed one test is failing, but one where i did not change anything, and it is failing due to a pod taking a long time to be created. Is it possible to restart those tests only?

Example:

https://travis-ci.org/apache/airflow/jobs/562997485

`test_pod_resources (tests.minikube.test_kubernetes_pod_operator.KubernetesPodOperatorTest) ... ERROR`

`Pod Launching failed: Pod took too long to start`

**Comment by CatarinaSilva** [comment]
@potiuk @pgagnon @ashb not sure if you can help, but I just tried to run the pipeline twice. The first time I got the error mentioned in the comment above. 

After I merged master into it a new test starts failing (without any other change) and I can not find the error in the CI logs. Maybe you have some pointers to more easily understand what is happening.

**Review by dimberman — APPROVED** [review]
LGTM. Once tests pass let's merge.

**Comment by CatarinaSilva** [comment]
Can we merge @dimberman @potiuk @pgagnon @ashb can somebody merge?

Btw, when this is merged, how do I know to which release it will be attached to?

**Comment by CatarinaSilva** [comment]
@dimberman since the master branch had changes to the kubernetes files, I updated with conflicts solved and it passed the tests again

**Comment by CatarinaSilva** [comment]
Hi @dimberman @potiuk @pgagnon @ashb friendly reminder that this PR is approved, passing tests and waiting for merge :)

**Comment by aaaaahaaaaa** [comment]
@CatarinaSilva Is there a reason why this PR only allows to specify `limits` but not `requests` for GPUs?

**Comment by mik-laj** [comment]
Because request must be equals to limits if you define GPU resources.

**Comment by mik-laj** [comment]
> You can specify GPU in both limits and requests but these two values must be equal.

https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Pull request merged**
