### PR TITLE
Summarize test failures at the end of CI run

### PR DESCRIPTION
**Pull request by ashb**
This prints the names of the failed tests, and their error/failure
messages which makes it easier to see the errors, rather than having to
expand all the cases, scroll down to find the error many times.

Example output from running locally with a force error.:

image

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
NICE!

**Review by potiuk — APPROVED** [review]

**Comment by ashb** [comment]
I tested this on main by merging a PR that broke everything. *ahem*

image

**Comment by potiuk** [comment]
Really nice !

**Comment by ashb** [comment]
I'm unreasonably happy with this -- it makes finding what cases failed _so much quicker_.

**Pull request merged**
