### PR TITLE
Update documentation to add rebase is optional for Github commit

### PR DESCRIPTION
**Pull request by Srabasti**
Updating documentation to include notes to show rebase is optional for committing change to Github.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Lee-W** [comment]
I'm not sure whether we would like to include it. Even though rebasing is optional, it's highly recommended.

**Comment by potiuk** [comment]
Same thought

**Comment by Srabasti** [comment]
> I'm not sure whether we would like to include it. Even though rebasing is optional, it's highly recommended.



> Same thought

Can we all agree to update comments educating code contributors the advantages of Rebasing? Currently, one can commit without rebasing. If we are encouraging users to rebase, even though they can avoid it, better to mention as good standard coding practice to follow.

Suggestion is to at least add a one-liner as follows below.
Rebasing is highly recommended as a good software practice. Suggested reading to understand advantages of rebasing: https://softwareengineering.stackexchange.com/questions/218801/why-do-so-many-projects-prefer-git-rebase-over-git-merge

Please feel free to suggest anything else you would like to add. 
Thanks in advance!

**Comment by potiuk** [comment]
> Please feel free to suggest anything else you would like to add.

Sure - feel free to rebase (!) and propose a new, update version.

**Review by Srabasti — COMMENTED** [review]
Removed optional to recommended for rebasing.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
It's better now

**Pull request merged**
