### PR TITLE
Remove extra 'of'

### PR DESCRIPTION
**Pull request by zmac12**
Just a double 'of', removes the second one.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
I feel it makes more sense to remove the _of_ in the link instead.

**Comment by zmac12** [comment]
Sure, will update to reflect that change. Thanks

**Comment by zmac12** [comment]
@uranusjr fixed that, let me know if you need me to change anything else. Thanks!

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
The failing static check is unrelated

**Pull request merged**
