### PR TITLE
[AIRFLOW-1319] Fix misleading SparkSubmitOperator and SparkSubmitHook docstring

### PR DESCRIPTION
**Pull request by chrissng**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following:
    - https://issues.apache.org/jira/browse/AIRFLOW-1319

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
    - Re-worded docstrings in spark submit hook and operator for better clarity.

### Tests
- [x] My PR does not need testing as it is a change in documentation.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please correct your commit message per guidelines.

**Comment by chrissng** [comment]
Corrected commit message by including the JIRA issue id in the commit's subject. Unable to include the title of the issue as it will exceed 50 character limit. Included details in the commit message body.

**Comment by chrissng** [comment]
Commit message corrected.

**Comment by Fokko** [comment]
Good point, still `--files` is not only for serialised objects, but also configuration:
https://stackoverflow.com/questions/41263670/spark-hive-reporting-pyspark-sql-utils-analysisexception-utable-not-found-xxx/41263846#41263846

**Comment by Fokko** [comment]
@bolkedebruin This one can be merged

**Pull request closed without merging**
