### PR TITLE
[AIRFLOW-3910] Raise exception explicitly in Connection.get_hook()

### PR DESCRIPTION
**Pull request by XD-DENG**
### Jira

  - https://issues.apache.org/jira/browse/AIRFLOW-3910

### Description

Currently in `Connection.get_hook()`, a `try-except` clause is used for creating hook based on `conn_id` and `conn_type`. If something goes wrong, it pass silently and return None.

But this may cause trouble. Let’s say I’m getting hook from a postgres connection, while package `psycopg2` is not installed. Then getting hook will fail. But it will pass silently, and `None` will be returned as the hook.
 
I found this issue when I’m using `SqlSensor` for PostgresSQL. I keep getting error 
“**AttributeError: 'NoneType' object has no attribute 'get_records’**", but it was very hard to get a clue what caused this error. Similar issues may happen in other cases when `Connection.get_hook()` is invoked.
 
So here we should raise exception explicitly when anything goes wrong in `Connection.get_hook()`, instead of passing silently.

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
I like this, fail fast if you're trying to fetch something that doesn't exists.

**Comment by XD-DENG** [comment]
Thanks @Fokko

**Comment by ashb** [comment]
So an interesting possible side effect of this: I think  it is causing an exception on the "ad-hoc query" pages in 1.10.

Once the run completes https://travis-ci.org/ashb/airflow/jobs/509535397 I'll  be able to see what's going on. But it might be a problem with all the example connections we create.

May not  be worth cherry-picking this on to 1.10.3

**Comment by ashb** [comment]
Yup:

```
    airflow/www/views.py line 2188 in query
      ((db.conn_id, db.conn_id) for db in dbs if db.get_hook()))
    airflow/www/views.py line 2188 in <genexpr>
      ((db.conn_id, db.conn_id) for db in dbs if db.get_hook()))
    airflow/models/connection.py line 230 in get_hook
      return AzureDataLakeHook(azure_data_lake_conn_id=self.conn_id)
    airflow/contrib/hooks/azure_data_lake_hook.py line 39 in __init__
      self.connection = self.get_conn()
    airflow/contrib/hooks/azure_data_lake_hook.py line 49 in get_conn
      client_id=conn.login)
    .tox/py27-backend_sqlite-env_docker/lib/python2.7/site-packages/azure/datalake/store/lib.py line 110 in auth
      raise ValueError("tenant_id and client_id must be supplied for authentication")
   ValueError: tenant_id and client_id must be supplied for authentication
```

Trying to think if this will cause any other problems on master code that we haven't though of  with  the sample connections.

**Pull request merged**
