### PR TITLE
Update ObjectStoragePath for universal_pathlib>=v0.2.2

### PR DESCRIPTION
**Pull request by bolkedebruin**
This updates ObjectStoragePath to be compatible with universal_pathlib >= 0.2.2 which in turn makes it compatible with Python 3.12+.
 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cool.

**Comment by bolkedebruin** [comment]
@potiuk can we green light this?

**Review by eladkal — APPROVED** [review]
LGTM

**Comment by potiuk** [comment]
WOW ! Fantastic!. Let me try Python 3.12 build now :)

**Pull request merged**
