### PR TITLE
[AIRFLOW-869] Web UI Mark Success Upstream Option Bug

### PR DESCRIPTION
**Pull request by toddychen**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- *(https://issues.apache.org/jira/browse/AIRFLOW-869)*

Testing Done:
- No new functionality. Just a bug fix.

### CODE REVIEW

**Comment by toddychen** [comment]
@bolkedebruin Shall we include this fix in v1.8 release?

**Comment by bolkedebruin** [comment]
@toddychen it will be included in 1.8.1 , please note that this might to arrive as is. The issue with the code (not yours per se) is that the tests do not pick up this issue and we might need to refactor some.

**Comment by toddychen** [comment]
@bolkedebruin I see. I agree that the tests did not pick up this issue. We have to check more details in the web UI tests. Please consider another PR https://github.com/apache/incubator-airflow/pull/2075, I think the NULL value in filter is one of the cause.

**Comment by r39132** [comment]
@toddychen testing this now

**Comment by r39132** [comment]
This is not working for me either. 

In this example, I've picked `put_op`, which has both upstream and downsteam tasks in the `none` state. If I mark downstream tasks as success, I get

screenshot 2017-02-13 14 15 12

If I mark upstream tasks as success, I get

screenshot 2017-02-13 14 12 50

**Comment by bolkedebruin** [comment]
@toddychen can you please close this?

**Pull request closed without merging**
