### PR TITLE
[AIRFLOW-5500] Fix the trigger_dag api in the case of nested subdags

### PR DESCRIPTION
**Pull request by cBournhonesque**
Like the jira issue states (https://issues.apache.org/jira/browse/AIRFLOW-5500), the experimental api is broken when one tries to trigger a dag that contains nested subdags.

The reason for this is that calling `dag.subdags` returns a list of ALL the subdags for the dag (even the nested ones), instead of the direct child subdags.
(here: https://github.com/apache/airflow/blob/master/airflow/models/dag.py#L756)

My fix directly changes the trigger_dag.py, but a better solution is probably to make `dag.subdags` return only the child subdags. I didn't know if the current behaviour was chosen for a specific reason so I decided to just change the experimental api.

---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by Devarajegowda** [comment]
@cBournhonesque Wanted to understand why all nested subdags are stored in dag.subdags level,
Ex: dag1-> subdag_dag1 -> subdag_subdag_dag1
dag.subdags contain both subdag_dag1 , subdag_subdag_dag1, I was wondering if it make sense to store 1st level of subdags inside dag.subdags.

**Comment by cBournhonesque** [comment]
@Devarajegowda I think it would make sense to only have dags.subdags have the 1st level of subdags; but I thought that maybe this choice was made for a specific reason?
Personally, on the airflow instance I am using, I modified the dags.subdags code to only return the 1st level subdags, and everything seems to be working, so it might make more sense to just modify the code there?

**Comment by Devarajegowda** [comment]
> @Devarajegowda I think it would make sense to only have dags.subdags have the 1st level of subdags; but I thought that maybe this choice was made for a specific reason?
> Personally, on the airflow instance I am using, I modified the dags.subdags code to only return the 1st level subdags, and everything seems to be working, so it might make more sense to just modify the code there?

Yes even I believe so, if we make those changes change in this commit may not be needed at all. 
Appreciate if others can give us some more idea on why all nested subdags are stored under dag.subdags.

**Comment by cBournhonesque** [comment]
It seems like one side-effect is that clicking on 'clear tasks recursive' on the UI only clears the tasks of the direct subdags, not all nested subdags.

**Comment by samdjstephens** [comment]
I've run into this issue too.. Looking at places `DAG.subdags` is called:
- set_is_paused
- DagBag

Clearly DAG.subdags was intended to return all subdags and nested subdags, so I think fixing trigger_dag to respect that behaviour is the right way to go

**Comment by cBournhonesque** [comment]
Actually, I think so too. Changing dag.subdags directly also change the behaviour of clearing a dag recursively in the UI.

**Comment by kylegao91** [comment]
Really hope this can be merged into 1.10.11, very important for our tasks.

**Comment by potiuk** [comment]
I think that one neds some better understanding about consequences of subdag triggering - it looks legit for me (and I marked it for 1.10.11) but maybe others @kaxil? @milton0825 can have a look and see if there is no problem with it. It's rather small change.

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Can you rebase on latest master please @cBournhonesque

**Comment by cBournhonesque** [comment]
@kaxil Thanks, I just did.

**Pull request merged**
