### PR TITLE
Adding documentation explaining "strange" URI required when using AWS…

### PR DESCRIPTION
**Pull request by kubatyszko**
… Secrets Manager and likely other secrets backends

In some cases, URI's you will need stored in Secrets Manager may not be intuitive, for example when using HTTP / HTTPS or SPARK, you may need URI's that will look like this:

http://https%3A%2F%2Fexample.com

spark://spark%3A%2F%2Fspark-master-0.spark-master.spark.svc.cluster.local:7077

This is a known situation, where schema and protocol parts of the URI are indepentent and in some cases, need to be specified explicitely.

See https://github.com/apache/airflow/pull/10256 and https://github.com/apache/airflow/issues/10913 for more detailed discussion that led to this documentation update. This may get resolved in the future.

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Spelling problem :(. Add the: 

```
..spelling:

   Fspark
```
I guess

**Comment by kubatyszko** [comment]
> Spelling problem :(. Add the:
> 
> ```
> ..spelling:
> 
>    Fspark
> ```
> 
> I guess

That is correct and intentional, in both URI's, the %3A%2F%2F portion resolves to :// 
The last F is what you thought belongs to "spark" yielding "Fspark" while it belongs to the %2F representing slash (/)

**Comment by potiuk** [comment]
> That is correct and intentional, in both URI's, the %3A%2F%2F portion resolves to ://

Yep. I understand. But the spell-checker does not and thinks it is a misspelled word. By adding ..spelling: directive you let the spellchecker know that this is not a typo :)

**Comment by kubatyszko** [comment]
@potiuk the checks finally passed :D

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Happy New Year @kubatyszko !

**Comment by kubatyszko** [comment]
Thanks. Happy New Year @potiuk

**Comment by mik-laj** [comment]
> Yep. I understand. But the spell-checker does not and thinks it is a misspelled word. By adding ..spelling: directive you let the spellchecker know that this is not a typo :)

If it were marked as a code snippet or as a block literal, it would not be spell check. I'll correct it in a moment to make it look better.

**Pull request merged**
