### PR TITLE
Add `log_id` field to log lines on ES handler

### LINKED ISSUE #10406: log_id field is missing from log lines (ES remote logging)
**Apache Airflow version**:
apache/airflow:1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
v1.16.11-gke.5

**Environment**:
GKE

**What happened**:
Webserver doesn't fetch logs for tasks from elasticsearch

**What you expected to happen**:
task logs will be displayed in the webserver UI

It seems like the webserver is trying to query task logs by the `log_id` field:
https://github.com/apache/airflow/blob/1.10.11/airflow/utils/log/es_task_handler.py#L175

this field is missing from all log lines (which are written to stdout) using the KubernetesExecutor. Example log line:
`{"asctime": null, "filename": "standard_task_runner.py", "lineno": 77, "levelname": "INFO", "message": "Running: ['airflow', 'run', 'hello_world', 'hello_task_3', '2020-08-19T14:26:07.226064+00:00', '--job_id', '158', '--pool', 'default_pool', '--raw', '-sd', '/opt/airflow/dags/repo/dags/hello_world.py', '--cfg_path', '/tmp/tmpt7lafkaf']", "dag_id": "hello_world", "task_id": "hello_task_3", "execution_date": "2020_08_19T14_26_07_226064", "try_number": "1"}`

**How to reproduce it**:
this is the relevant configuration we have, scheduler and webserver running separately and tasks run using KubernetsExecutor (all in the same cluster/namespace):
```
AIRFLOW__CORE__LOGGING_LEVEL: INFO
AIRFLOW__CORE__REMOTE_LOGGING: "True"
AIRFLOW__ELASTICSEARCH__HOST: http://elasticsearch.logging:9200
AIRFLOW__ELASTICSEARCH__JSON_FORMAT: "True"
AIRFLOW__ELASTICSEARCH__WRITE_STDOUT: "True"
```

we are using fluentd (https://github.com/fluent/fluentd-kubernetes-daemonset) to forward log lines to elasticsearch, all task logs are written to stdout + elasticsearch as expected.

### PR DESCRIPTION
**Pull request by eyalzek**
closes: #10406 
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
cc @andriisoldatenko @schnie

**Comment by eyalzek** [comment]
I just realized that settings `log_id` might be a breaking change for people who manipulate log lines to add it manually

**Comment by potiuk** [comment]
> I just realized that setting `log_id` might be a breaking change for people who manipulate log lines to add it manually

@eyalzek -> I think that's fine if you make a note about it in UPDATING.md file

**Review by potiuk — CHANGES_REQUESTED** [review]
LGTM - just make a note about it in UPDATING.md :) .

**Comment by eyalzek** [comment]
@potiuk after fighting with fluentd and airflow all day to get the webserver to display my task logs, I think it make sense to also include the `offset` field in this PR, otherwise it doesn't really solve anything. I'll put some work into it over the next few days and will try to update the documentation to reflect this as well.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I think there is just a statc check to fix. We've just added black formatting so you need to rebase/rerun pre-commits and submit it again

**Comment by eyalzek** [comment]
done

**Comment by potiuk** [comment]
Can you please rebase @eyalzek ?  then it will be included in backport packages 2nd wave

**Comment by eyalzek** [comment]
> Can you please rebase @eyalzek ? then it will be included in backport packages 2nd wave

rebased

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks! What's next !

**Pull request merged**
