### PR TITLE
Amazon SES Hook

### PR DESCRIPTION
**Pull request by ipeluffo**
This PR adds a new hook for Amazon Simple Email Service (SES).

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ipeluffo** [comment]
It seems that `CI Build / Backport packages` is still failing with this error:
```
ERROR: There were some import errors

----------------------------------------
Traceback (most recent call last):
  File "/import_all_provider_classes.py", line 61, in import_all_provider_classes
    _module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/ses.py", line 24, in <module>
    from airflow.utils.email import build_mime_message
ImportError: cannot import name 'build_mime_message'

----------------------------------------
```

I'm not sure what I'm missing here 🤔

**Comment by mik-laj** [comment]
I'll take a look at it.

**Comment by mik-laj** [comment]
Okay. I already know what happened. Backport packages are tested with Airflow 1.10.10, so you cannot use Airflow 2.0 function in backport packages unless you also provide an alternative for Airflow 1.10. You can do this by vendoring this method/module to your package. You can do automatically using bowler when creating the package;
Here's some code that does a similar transform for another module.
https://github.com/apache/airflow/blob/master/backport_packages/refactor_backport_packages.py#L641-L649

**Comment by mik-laj** [comment]
I push a patch on your branch We will check if CI will be happy.

**Comment by ipeluffo** [comment]
CI looks good now, thanks for the patch @mik-laj

**Comment by mik-laj** [comment]
@feluelle Can you look at it?

**Review by feluelle — APPROVED** [review]

**Comment by feluelle** [comment]
LGTM, I am merging it.

**Pull request merged**
