### PR TITLE
Add basic test cases for providers cli command

### PR DESCRIPTION
**Pull request by pankajastro**
At the moment the tests are missing for cli providers group. This PR aim to add some basic test, mostly happy path for the providers group command. This will help us to ensure that providers group of command remain healthy.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Just FYI (it's a good idea to add those BTW)  - the reason why there are no tests for provider's CLI is that they have higher level - say "integration" - tests running in CI: 
 https://github.com/apache/airflow/blob/ced56ea5a783a2846094996503d84fc21a33d6ae/scripts/in_container/verify_providers.py#L811 - they don't test too much - they merely run all the cli commands for providers and see that they are not failing. This happens after all the providers have been build in main and installed on top of Airflow. 

But yes. it is great to have Pytest tests to test them too.

And BTW. By checking it, I have found that the above tests have been accidentally excluded in recent refactor - accidentally. Fix to it is coming: https://github.com/apache/airflow/pull/30986

**Comment by potiuk** [comment]
And an FYI @pankajastro  -> the small problem with tests run as "regular" Pytest tests in this case is that providers in CI version of Airflow are not installed the way they are installed in "production". 

When you look at provider's manager, we have separate code path to discover and read provider information when Airflow is installed in CI from sources (providers are discovered from being available in the sources rather from package metadata - because when we run tests in CI, provider metadata is discovered by reading provider.yaml files in "airflow/sources". 

This the main reason why we are building airflow + provider packages in Airflow CI in the separate job , and then removing sources of airflow, and installing both airflow and providers as packages. So the "integration" tests in CI of airflow are testing  the "package" versrion of discovery, which is not possible in the Pytest tests.

**Comment by pankajastro** [comment]
Thanks for pointing out.

I was not aware of the fact that `run_provider_discovery` providers command.  https://github.com/apache/airflow/blob/ced56ea5a783a2846094996503d84fc21a33d6ae/scripts/in_container/verify_providers.py#L811

**Comment by pankajastro** [comment]
> Yep. And after the fix it is even run (back) , so you can actually see the output in the CI https://github.com/apache/airflow/actions/runs/4852143254/jobs/8646855138#step:11:1731

thanks for explaining it, I'll close this for now and add the trigger command also `run_provider_discovery`  in the a separate PR https://github.com/apache/airflow/pull/30999

**Pull request closed without merging**
