### PR TITLE
[AIRFLOW-2168] Remote logging for Azure Blob Storage

### PR DESCRIPTION
**Pull request by marcusrehm**
### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2168) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2168

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
        This PR creates the wasb_task_handler for remote logging using Azure Blob Storage. Besides that, it improves wasb_hook adding capabilities to download and read files from Azure Blob Storage.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
        adds new tests to airflow.contrib.hooks.wasb_hook.py.
        for the airflow.utils.log.wasb_task_handler.py unfortunately I would need a true Azure account in order to create tests.  

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@NielsZeilemaker PTAL

**Comment by NielsZeilemaker** [comment]
LGTM

**Comment by marcusrehm** [comment]
@NielsZeilemaker and @Fokko I think this PR can close this issue too: [AIRFLOW-1775 - Remote file handler for logging](https://issues.apache.org/jira/browse/AIRFLOW-1775)

**Comment by NielsZeilemaker** [comment]
I don't agree, an azure fileshare is something different than a blob store

**Comment by marcusrehm** [comment]
Hi @NielsZeilemaker indeed. I was thinking about a workaround (using the blob store and not the azure fileshare), but reading it again I think you're right. Sorry.

**Review by Fokko — APPROVED** [review]
Thanks @marcusrehm for contributing

**Comment by marcusrehm** [comment]
Hi @Fokko , thank you guys for the awesome work!

**Pull request closed without merging**
