### PR TITLE
Add executor option to breeze shell command

### PR DESCRIPTION
**Pull request by utkarsharma2**
Introduced --executor flag for command `breeze shell` which accepts `CeleryExecutor`, and `LocalExecutor`.

related: https://github.com/apache/airflow/issues/28412

### CODE REVIEW

**Comment by utkarsharma2** [comment]
cc: @uranusjr

**Review by vincbeck — APPROVED** [review]

**Review by potiuk — APPROVED** [review]
Missing piece :)

**Review by potiuk — CHANGES_REQUESTED** [review]
Hmm . I think --executor Celery should automatically also enable celery integration.

**Review by potiuk — APPROVED** [review]
Ah.... It does.... just run it with sqlite and

**Pull request merged**
