### PR TITLE
[AIRFLOW-629] stop pinning lxml

### PR DESCRIPTION
**Pull request by azban**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
https://issues.apache.org/jira/browse/AIRFLOW-629

Testing Done:
- existing tests should cover changes

### CODE REVIEW

**Comment by r39132** [comment]
@jedipi  You'll need to place an upper bound! As presented, it's a timebomb!

**Comment by azban** [comment]
oops!

**Comment by r39132** [comment]
Looks good. Master is currently broken. I need to revert a change before I can test yours. After I fix master, please rebase so that you can kick off travis again.

**Comment by r39132** [comment]
ok.. rebase

**Comment by r39132** [comment]
+1 works locally. merging.

**Pull request closed without merging**
