### PR TITLE
[AIRFLOW-3303] Deprecate old UI in favor of FAB

### PR DESCRIPTION
**Pull request by verdan**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-3303) issues and references them in the PR title. 

### Description

- [x] We are using two different versions of UI in Apache Airflow. Idea is to deprecate and remove the older version of UI and use the new Flask App Builder (RBAC) version as the default UI from now on. (most probably in release 2.0.x)
This PR removes the old UI and renames the references of `www_rbac` to `www`. 

### Tests

- [x] Skipped some of the test case classes as these were purely using the older version of application and configurations. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

**All the help with manual testing would be highly appreciated 🙂**

### CODE REVIEW

**Comment by verdan** [comment]
@Fokko @ashb could you guys please help me with two of the failing tests: `tests/operators/test_latest_only_operator.py`
https://travis-ci.org/apache/incubator-airflow/jobs/451904446#L4518
https://travis-ci.org/apache/incubator-airflow/jobs/451904446#L4596

Both of them are passing in my local environment, but failing on travis. Any idea, if/what I'm missing here?

**Comment by ron819** [comment]
If I read this right  
dag_id = 'SchedulerJobTest.test_execute_task_instances_limit'
https://github.com/apache/incubator-airflow/blob/5ea0d97b494674a52c0e91e6a04d201cbecd8f86/tests/test_jobs.py#L1907

dag_id = 'SchedulerJobTest.test_execute_task_instances_limit'

https://github.com/apache/incubator-airflow/blob/5ea0d97b494674a52c0e91e6a04d201cbecd8f86/tests/test_jobs.py#L1907

should be changed to:
dag_id = 'test_execute_task_instances_limit'
dag_id = 'test_execute_task_instances_is_paused_wont_execute'

**Comment by ron819** [comment]
@verdan  The successful tests are called as:
`tests.test_jobs.SchedulerJobTest.testname`

example:
`tests.test_jobs.SchedulerJobTest.test_scheduler_start_date
`

The failing tests are called as:
`SchedulerJobTest.testname`

example:
`SchedulerJobTest.test_execute_task_instances_limit
`

**Comment by verdan** [comment]
@ron819 can you please double check if what you are saying is the correct reference of the failing tests ?

**Comment by bolkedebruin** [comment]
Can you rebase @verdan so we can take this further?

**Comment by verdan** [comment]
will re-open this after fixing test cases on my repo.

**Comment by verdan** [comment]
Opened another PR here: https://github.com/apache/incubator-airflow/pull/4339

**Pull request closed without merging**
