### PR TITLE
Adding a timeout Context object and using it when importing dags

### PR DESCRIPTION
**Pull request by mistercrunch**

### CODE REVIEW

**Comment by mistercrunch** [comment]
Your bad dag can't take the scheduler down no mo'

**Comment by mistercrunch** [comment]
Tested by adding a sleep(1000) statement in a dag, this is the output:
```
~/Airflow (timeout_imports)*$ airflow list_dags
ERROR:root:Process timed out
ERROR:root:Failed to import: /mnt/home/maxime_beauchemin/Airflow/airflow/example_dags/tutorial.py
ERROR:root:
Traceback (most recent call last):
  File "/mnt/home/maxime_beauchemin/Airflow/airflow/models.py", line 160, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/mnt/home/maxime_beauchemin/Airflow/airflow/example_dags/tutorial.py", line 62, in <module>
    time.sleep(10)
  File "/mnt/home/maxime_beauchemin/Airflow/airflow/utils.py", line 427, in handle_timeout
    raise TimeoutError(self.error_message)
TimeoutError: Timeout
example_bash_operator
example_python_operator
```
It raises within a `try` block so it moves along skipping the hanging DAG file

**Comment by krishnap** [comment]
:+1:

**Comment by artwr** [comment]
Sweet!

**Pull request merged**
