### PR TITLE
Make dag_run join as lazyload by default in TaskInstance

### PR DESCRIPTION
**Pull request by haoch**
**General problem**: `joinedload` on `TaskInstance.dag_run` is generally not needed except for UI/API (list all task instances and related fields at once), but the unnecessary `JOIN` is a killer of Airflow scheduling performance especially when there are thousands of task instances in single DagRun.

**The real problem in some large scale Airflow clusters**: 
We manage thousands of airflow executors (nodes) in production, and each DagRun may have 10k task instances. 

* In Scheduler side , the impact is very obvious as after making it lazy, we do see 3+ times scheduling performance improvement. 

* In Executor side, when tasks are queued and preparing to execute, it will check if dependencies meet with all finished task instances, a large amount of concurrent JOIN SQL will slow database performance. Especially when the config content size of some DagRun is large (1MB), thousands of concurrent executors will pull the same large DagRun at same time and it will also cause huge network throughput (~1 GB/second) from database and make the centralized database and the whole airflow cluster unhealthy. 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
(Housekeeping notes) As the pull request template mentions, please put the description _above_ the line, not below, to improve readability. I have modified the description for you.

**Comment by haoch** [comment]
Thanks @uranusjr

**Comment by o-nikolas** [comment]
There are static code failures ([see here](https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst) for how to run those locally to catch and fix them before the PR) as well as many test failures because a new unexpected arg is being passed.

**Comment by haoch** [comment]
Sure, @o-nikolas will fix all the failures firstly.

**Pull request closed without merging**
