### PR TITLE
add recursive lookup for list of dirs

### PR DESCRIPTION
**Pull request by hg1112**
We have been intending to use the AzureFileShareToGCSOperator to transfer files from azure file share to gcs. 
Problem being we to transfer whole bucket and this operator does not support recursive transfer. 

So we added a boolean option for recursive traversal to AzureFileShareHook so that we can get the list of files through recursive tree if enabled. This will help transfer the files without deviating much with the original flow. 
By default it is set to False, imitating the existing the behavior

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by dirrao — CHANGES_REQUESTED** [review]
Can you add the test case for this enhancement?

**Comment by Taragolis** [comment]
[Static code checks](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst) and [Test(s)](https://github.com/apache/airflow/actions/runs/8953480968/job/24598706387?pr=39410) should be fixed

**Comment by hg1112** [comment]
Understood, I will add tests and fix the build. 
thank you @dirrao @Taragolis

**Comment by bolkedebruin** [comment]
@hg1112 not opposing your fix at all, but did you consider using ObjectStoragePath instead of this operator?

**Comment by hg1112** [comment]
Thank you for all the suggestions. Been a bit . 
I will try to incorporate ur suggestions

**Comment by hg1112** [comment]
closing this PR , because used merge strategy instead of rebase to update latest code from main

**Pull request closed without merging**
