### PR TITLE
[AIRFLOW-3710] Fix Google Cloud Base Hook warnings

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3710

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Fixes IDE warnings in Google Cloud Build Base Hook.

screenshot 2019-01-15 at 21 54 39
screenshot 2019-01-15 at 21 54 34
screenshot 2019-01-15 at 21 54 29
screenshot 2019-01-15 at 21 54 24
screenshot 2019-01-15 at 21 54 14

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
 
There are enough tests already to test it :)

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

No documentation needed.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by kaxil** [comment]
Please follow commit guidelines. Also add screenshots

**Comment by potiuk** [comment]
Sure @kaxil. Sorry for that hastiness :). Screenshots attached.

**Comment by potiuk** [comment]
I realised that there are many unit tests failing now as there was unused "source" parameter for Base Hook.. I will review it and double check everything now, so please hold on with the reviews.

**Comment by potiuk** [comment]
OK I looked at it and I think this is the safest way of solving all problems with setting source=None as default in Base Hook and removing it from all other params.

I do not know the history - but there was the unused source parameter in Base Hook. for whatever reason it was used before, it seems it's not used any more. 

But since it is a BaseHook, I can imagine there are a number of Operators (maybe even not in the apache sources) that still use the constructor with source parameter. 

I found a few in the airflow's code and removed them. But then I think it might also make sense to leave the source parameter and set default value to None so that it will work also for older code/hooks which are distributed as plugins (but removing it from all internal ones makes sense).

**Comment by potiuk** [comment]
Possibly we should also change the description/JIRA content for that change and even split it into two changes.

**Comment by potiuk** [comment]
OK. That one seems good to go (I might change the description though as it got a bit more than just fixing the warning). Unless you also think that we could remove 'source' altogether.

**Comment by feng-tao** [comment]
I think the pr / commit title needs to have [AIFLOW-XXX] which XXX is the ticket number.

**Comment by potiuk** [comment]
@feng-tao -> yeah. I forgot it initially in the commit so it was not in the PR name as well. Changed. Sorry.

**Pull request closed without merging**
