### PR TITLE
[AIRFLOW-2401] Add syntax to use variables from Jinja template

### PR DESCRIPTION
**Pull request by moe-nadal-ck**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA 2401](https://issues.apache.org/jira/browse/AIRFLOW-2401) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2401

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by moe-nadal-ck** [comment]
Simple change in the documentation for the Variable usage from jinja template

**Comment by r39132** [comment]
Please still add a JIRA so that we can generate clean-looking release notes. Follow the contributor guidelines.

**Comment by moe-nadal-ck** [comment]
@r39132 Done!

**Comment by r39132** [comment]
+1 thx

**Comment by r39132** [comment]
FYI.. you should not make the JIRA resolved yourself -- it's automatically marked Resolved when committers/maintainers merge your fix.

**Pull request closed without merging**
