### PR TITLE
[AIRFLOW-2273] Add Discord webhook operator/hook

### PR DESCRIPTION
**Pull request by TJBIII**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2273) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2273

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Add the Discord webhook operator and hook pair. This allows for the posting of messages to a Discord channel using incoming webhooks.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- tests/contrib/operators/test_discord_webhook_operator.py
- tests/contrib/hooks/test_discord_webhook_hook.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by jgao54** [comment]
Please do the following to fix CI failure:
- pep8 error specified [here](https://travis-ci.org/apache/incubator-airflow/jobs/360680857)
- rebase on top of master

For documentation, please add the hook/operator to docs/code.rst

Thanks!

**Comment by TJBIII** [comment]
@jgao54 I made the requested changes. Thanks for looking this over!

**Comment by jgao54** [comment]
lgtm

**Comment by Fokko** [comment]
@zeebonk Next release of Apache Airflow will have Discord integration 👍

**Pull request merged**
