### PR TITLE
[AIRFLOW-2476] allow tabulate up to 0.8.2

### PR DESCRIPTION
**Pull request by Tagar**
Make sure you have checked _all_ steps below.

### JIRA
- [X] 
    - https://issues.apache.org/jira/browse/AIRFLOW-2476

### Description
- [X] As discussed on the dev list, tabulate==0.8.2 is good to go with Airflow

### Tests
- [X] tested manually

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by r39132** [comment]
@Tagar why do you have 2 commits? Why is the second one adding a dependency? Pls squash your commits. Also, provide a little more context on this upgrade in the JIRA.

**Comment by kaxil** [comment]
@Tagar Can you please squash commits? and as Sid requested can you please provide a little more details on this upgrade in the JIRA?

**Comment by r39132** [comment]
@Tagar kindly rebase

**Comment by Tagar** [comment]
@r39132 sorry for the delay. I've moved to some other projects and don't have airflow handy to fix this. if somebody can take over this PR, this will be totally fine with me. Thanks!

**Comment by kaxil** [comment]
No worries @Tagar, thanks anyways . Closed in favor of https://github.com/apache/incubator-airflow/pull/3835

**Pull request closed without merging**
