### PR TITLE
[AIRFLOW-5690] Change log level local_task_job.py

### PR DESCRIPTION
**Pull request by chicochico**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-5690\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5690
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-5690\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes: Reduce log level to prevent over logging

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Already tested

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by Fokko — APPROVED** [review]

**Comment by feluelle** [comment]
Thanks @chicochico LGTM :)

**Comment by adityav** [comment]
can it be a level lower than info? it is simply a successful heartbeating message afterall

**Comment by Fokko** [comment]
@adityav It is actually a bit more than that. What it implies is that the heart beating is being throttled because of the high heart rate.

**Comment by adityav** [comment]
Can the log message be more detailed on how to prevent this high heart rate?
I run airflow on Kubernetes executor and this logline shows up consistently every 10 seconds interspersed with my tasks' output. 10 secs is the heartrate I set. I have no idea how to address it.

**Comment by jj-ookla** [comment]
> adityav It is actually a bit more than that. What it implies is that the heart beating is being throttled because of the high heart rate.

@Fokko 
Is "high heart rate" referring to `job_heartbeat_sec` or `scheduler_heartbeat_sec`?

**Comment by yhlee-tw** [comment]
@Fokko I have a similar question - the logging seems excessively and not very helpful.

Looking at
https://github.com/apache/airflow/blob/master/airflow/jobs/local_task_job.py#L102-L107
https://github.com/apache/airflow/blob/master/airflow/jobs/base_job.py#L190

The BaseJob.heartbeat() will sleep (using configured heartbeat rate), update latest_heartbeat and commit it.
So in a successful heartbeat in BaseJob still triggers log print in LocalTaskJob, which I am not sure if it's intentional for AIRFLOW-4956 (#5589)

**Comment by yuqian90** [comment]
> @adityav It is actually a bit more than that. What it implies is that the heart beating is being throttled because of the high heart rate.

I'm trying to read the code to understand how to silence this line. This line is called in the loop whenever `time_since_last_heartbeat` is smaller than `self.heartrate`. But since the code only sleeps for `self.heartrate - time_since_last_heartbeat`, and then the loop goes to the next iteration. So if the worker is fast enough, there's bound to be a small variation when `time_since_last_heartbeat` is computed again. It is most likely going to be smaller than `self.heartrate`. So this line keeps spamming. There seems to be no way to stop this. And this line is also not useful because it basically says the task is still heartbeating. 

```
                    self.log.warning("Time since last heartbeat(%.2f s) < heartrate(%s s)"
                                     ", sleeping for %s s", time_since_last_heartbeat,
                                     self.heartrate, sleep_for)
```

How about changing it to self.log.trace() or remove it completely?

**Comment by jj-ookla** [comment]
> I'm trying to read the code to understand how to silence this line. This line is called in the loop whenever `time_since_last_heartbeat` is smaller than `self.heartrate`. But since the code only sleeps for `self.heartrate - time_since_last_heartbeat`, and then the loop goes to the next iteration. So if the worker is fast enough, there's bound to be a small variation when `time_since_last_heartbeat` is computed again. It is most likely going to be smaller than `self.heartrate`. So this line keeps spamming. There seems to be no way to stop this. And this line is also not useful because it basically says the task is still heartbeating.
> 
> ```
>                     self.log.warning("Time since last heartbeat(%.2f s) < heartrate(%s s)"
>                                      ", sleeping for %s s", time_since_last_heartbeat,
>                                      self.heartrate, sleep_for)
> ```
> 
> How about changing it to self.log.trace() or remove it completely?

@yuqian90 
The logging level was set to `debug` in https://github.com/apache/airflow/pull/6716

**Comment by yuqian90** [comment]
> > I'm trying to read the code to understand how to silence this line. This line is called in the loop whenever `time_since_last_heartbeat` is smaller than `self.heartrate`. But since the code only sleeps for `self.heartrate - time_since_last_heartbeat`, and then the loop goes to the next iteration. So if the worker is fast enough, there's bound to be a small variation when `time_since_last_heartbeat` is computed again. It is most likely going to be smaller than `self.heartrate`. So this line keeps spamming. There seems to be no way to stop this. And this line is also not useful because it basically says the task is still heartbeating.
> > ```
> >                     self.log.warning("Time since last heartbeat(%.2f s) < heartrate(%s s)"
> >                                      ", sleeping for %s s", time_since_last_heartbeat,
> >                                      self.heartrate, sleep_for)
> > ```
> > 
> > 
> > How about changing it to self.log.trace() or remove it completely?
> 
> @yuqian90
> The logging level was set to `debug` in #6716

I see. Thank you!

**Pull request merged**
