### PR TITLE
Add option of sending DAG parser logs to stdout.

### PR DESCRIPTION
**Pull request by jhtimmins**
This is a continuation of https://github.com/apache/airflow/pull/25528, with the addition of tests.

There were issues getting #25528 to run locally, so I duplicated the PR.

### CODE REVIEW

**Comment by jhtimmins** [comment]
@kaxil this includes the tests you requested for the linked PR

@uranusjr can you take another look at this PR? It's the same as the linked one, with the addition of tests.

**Review by uranusjr — APPROVED** [review]
LGTM, except the linter error needs to be fixed.

**Comment by jhtimmins** [comment]
@ashb @uranusjr looks like An unrelated file in the same test directory keeps failing on MSSQL2017. Is it well known that this is a problematic test environment? Unsure if I should disregard.

https://github.com/apache/airflow/runs/7892800524?check_suite_focus=true

**Comment by potiuk** [comment]
Restarting is easiest way to try @jhtimmins. I did it now, but you should be able to do it when things fail as well.

**Review by uranusjr — APPROVED** [review]

**Comment by uranusjr** [comment]
Test failures not related, it’s introduced into main by another PR.

**Comment by jhtimmins** [comment]
@uranusjr are you referring to this error? https://github.com/apache/airflow/runs/8220641637?check_suite_focus=true#step:13:3875

**Comment by ashb** [comment]
> @uranusjr are you referring to this error? https://github.com/apache/airflow/runs/8220641637?check_suite_focus=true#step:13:3875

No that is something else (but likely not this PR) https://github.com/apache/airflow/runs/8215672242?check_suite_focus=true#step:9:12013 is the error he's talking about I think

**Pull request merged**
