### PR TITLE
[AIRFLOW-3340] Placeholder support in connections form

### PR DESCRIPTION
**Pull request by msumit**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues
  - https://issues.apache.org/jira/browse/AIRFLOW-3340

### Description

- [x] Placeholder are very useful when setting up new connections. Adding the capability to provide custom placeholders in Connections form.

placeholder

### Tests

- [x] Small UI change, which I've tested manually 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] NA

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ron819** [comment]
The airflow/www/static/connection_form.js will be removed when https://github.com/apache/incubator-airflow/pull/4142/ is merged.

**Comment by msumit** [comment]
@ron819 thanks for the heads-up. BTW do you know how connections will be customized in RBAC world?

**Review by kaxil — APPROVED** [review]

**Comment by jgao54** [comment]
@msumit 
It should work the same way. Please see `airflow/www_rbac/static/js/connection_form.js`, I think you could make the same change there.

**Comment by msumit** [comment]
Thanks for the info @jgao54, will do the changes there as well.

**Comment by msumit** [comment]
@jgao54 @kaxil plz see if any of you can merge this PR?

**Comment by kaxil** [comment]
Thanks @msumit

**Pull request merged**
