### PR TITLE
Add update mask to stable REST API patch dag endpoint

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This PR adds an update mask to patch dag endpoint. 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
Cool. I still think that it is worth adding a description of the update_mask parameter in the API introduction. Would you like to take care of it?

**Comment by ephraimbuddy** [comment]
> Cool. I still think that it is worth adding a description of the update_mask parameter in the API introduction. Would you like to take care of it?

Ok. I will create a PR on it tonight :)

**Comment by mik-laj** [comment]
@ephraimbuddy  I added introduction to API, so your change will be much easier now.

**Comment by ephraimbuddy** [comment]
That's awesome. Currently resolving a lot of conflicts in the other PR about unifying API errors but I have pushed the update mask change, haven't created the PR yet. Will create it this night

**Pull request merged**
