### PR TITLE
Restrict looker-sdk version 24.18.0 and microsoft-kiota-http 1.3.4 (#…

### PR DESCRIPTION
**Pull request by potiuk**
…42954)

* restrict looker version 24.18.0

* update microsoft provider deps with microsoft-kiota-http

* update gh issue ids to provider yaml files

* ignore type in applfowhook

* ignore type in applfowhook

* ignore type in applfowhook

(cherry picked from commit 7d8ea68bdaae3258bd391b8f6ae0277258a7c437)

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Backport of #42954  in order to make v2-10-test build without errors.

**Comment by gopidesupavan** [comment]
> Backport of #42954 in order to make v2-10-test build without errors.

ah sorry my bad..

**Review by gopidesupavan — APPROVED** [review]

**Review by ephraimbuddy — APPROVED** [review]

**Comment by gopidesupavan** [comment]
@potiuk should we back port the recent prs related flaky and some k8s test updates?

**Comment by potiuk** [comment]
> @potiuk should we back port the recent prs related flaky and some k8s test updates?

Yes. Might be a good idea.

**Comment by potiuk** [comment]
> Yes. Might be a good idea.

That is a VERY good idea - I see a huge difference in the stability now main vs. 2-10-test after all the fixes you and others came up with for the stability!

**Comment by gopidesupavan** [comment]
> > Yes. Might be a good idea.
> 
> That is a VERY good idea - I see a huge difference in the stability now main vs. 2-10-test after all the fixes you and others came up with for the stability!

Sure will create those prs :)

**Review by eladkal — APPROVED** [review]

**Pull request merged**
