### PR TITLE
Shorten max line length to 90 chars

### PR DESCRIPTION
**Pull request by dstandish**
Shorten max line length to 90 chars for better readability.

I know this one is a long shot, but I actually think it's better readability at 90.  The main difference here is that ruff will be more likely to wrap 

Example OLD:
```python
@dags_router.get("/{dag_id}/details", responses=create_openapi_http_exception_doc([400, 401, 403, 404, 422]))
async def get_dag_details(
    dag_id: str, session: Annotated[Session, Depends(get_session)], request: Request
) -> DAGDetailsResponse:
```

Example NEW:
```python
@dags_router.get(
    "/{dag_id}/details",
    responses=create_openapi_http_exception_doc([400, 401, 403, 404, 422]),
)
async def get_dag_details(
    dag_id: str, session: Annotated[Session, Depends(get_session)], request: Request
) -> DAGDetailsResponse:
```

I think it becomes even better when we specify the args here:
```python
@dags_router.get(
    path="/{dag_id}/details",
    responses=create_openapi_http_exception_doc([400, 401, 403, 404, 422]),
)
async def get_dag_details(
    dag_id: str, session: Annotated[Session, Depends(get_session)], request: Request
) -> DAGDetailsResponse:
```

### CODE REVIEW

**Comment by kaxil** [comment]
Nooo, please don't do this --- not right now

**Comment by dstandish** [comment]
> Nooo, please don't do this --- not right now 😆

so you are saying.... do it after AIP-72????

**Comment by dstandish** [comment]
Ok closing for now
image

**Comment by mobuchowski** [comment]
Please, not something less than 100...

**Pull request closed without merging**
