### PR TITLE
Fix parsing KubernetesPodOperator multiline logs

### LINKED ISSUE #34388: Kubernetes provider - Error parsing timestamp in logs
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We are experiencing issue with error log message being shown in every task that is KubernetesPodOperator. We get 

```
{pod_manager.py:558} ERROR - Error parsing timestamp (no timestamp in message ''). Will continue execution but won't update timestamp
```

after execution is finished in every task.

### What you think should happen instead

No such error should be shown

### How to reproduce

```python
'''doc'''
from kubernetes.client import models as k8s
from airflow.providers.cncf.kubernetes.operators.pod import KubernetesPodOperator
from airflow.models import DAG
import pendulum
import datetime

DAG_ID = 'test-dag'

default_args = {
	'owner': 'owner',
	'depends_on_past': False,
	'start_date': datetime.datetime(2023, 9, 15),
	'sla': datetime.timedelta(hours = 1),
	'execution_timeout': datetime.timedelta(hours = 1, minutes = 30),
	'email_on_failure': False,
	'email_on_retry': False,
	'retries': 3,
	'retry_delay': datetime.timedelta(minutes = 1),
	'retry_exponential_backoff': True,
	'max_retry_delay': datetime.timedelta(minutes = 10),
	'max_active_tis_per_dag': 8,
	'pool': 'SomePool',
	'get_logs': True,
}

dag = DAG(
	dag_id = DAG_ID,
	doc_md = __doc__,
	tags = ['tag'],
	schedule = AfterWorkdayTimetable(pendulum.Time(2, 0)),
	default_args = default_args,
	catchup = True,
	dagrun_timeout = datetime.timedelta(hours = 6),
	max_active_runs = 5
)

task = KubernetesPodOperator(
	affinity = {
		'nodeAffinity': {
			'requiredDuringSchedulingIgnoredDuringExecution': {
				'nodeSelectorTerms': [
					{'matchExpressions': [{'key': 'dataDriveSizeClass', 'operator': 'In', 'values': ['large', 'medium']}]}
				]
			}
		}
	},
	priority_class_name = 'l3',
	namespace = 'some--namespace',
	in_cluster = True,
	image_pull_policy = 'IfNotPresent',
	container_resources = k8s.V1ResourceRequirements(
		requests = {'memory': '150Mi', 'cpu': '1m'},
		limits = {'memory': '512Mi', 'cpu': '500m'},
	),
	cmds = [
		'sleep',
		'10'
	],
	dag = dag,
	task_id = 'kubernetes_task',
	labels = {
		'runner': 'airflow',
	},
	annotations = {'version': '1.0.0'},
	image = 'ubuntu',
	env_vars = [k8s.V1EnvVar(name = name, value = value) for name, value in {'name':'value'}.items()]
)

task
```

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==8.4.0
apache-airflow-providers-cncf-kubernetes==7.5.1
apache-airflow-providers-common-sql==1.6.1
apache-airflow-providers-ftp==3.4.2
apache-airflow-providers-http==4.5.0
apache-airflow-providers-imap==3.2.2
apache-airflow-providers-postgres==5.6.0
apache-airflow-providers-slack==7.3.2
apache-airflow-providers-sqlite==3.4.3
```

### Deployment

Other Docker-based deployment

### Deployment details

Kubernetes 1.26.5
airflow 2.6.3
python 3.10.12
LocalExecutor
Database: Postgres 14.6

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by hussein-awala**
closes: #34388
related: #21605

This PR combines the multi-line log messages read from KubernetesPodOperator pod before logging them by the task.

Why removing the logged error messages is not enough?

In case of any interruption, we retry the method, so if we are in the middle of a multi-line message, we could have a duplication in the log because all the lines after the first one do not have a timestamp, but by combining them in the same message before logging them, we ensure in case of any interruption that we will retry combining and logging the whole message because we didn't do that in the first retry.

### CODE REVIEW

**Comment by hussein-awala** [comment]
I will add some tests before marking it as ready for review

**Review by eladkal — APPROVED** [review]

**Comment by eladkal** [comment]
@hussein-awala can you fix conflicts and rebase?

**Comment by hussein-awala** [comment]
> @hussein-awala can you fix conflicts and rebase?

I was working on it, it should be fine now

**Comment by donPain** [comment]
When will this fix be available in helm stable?

**Comment by dstandish** [comment]
@hussein-awala i was trying to understand this a bit more. but i was unable to actually produce multiline logs in KPO.  can you tell me how i can reproduce the multiline log behavior?

**Pull request merged**
