### PR TITLE
Fix an error that occur when Admin accesses to `Your Profile`.

### PR DESCRIPTION
**Pull request by tiokim**
The `users/userinfo` interface for `Your Profile` may need [`userinfoedit`](https://github.com/dpgaspar/Flask-AppBuilder/blob/4062f1ebd2e9bafe0c30f8b8890fe53011691742/flask_appbuilder/security/views.py#L358) data. 
However when Admin visits `Show record`, it pops the data from dict. 
This commit doesn't delete it, and only shows `Reset Password` button 
since `Edit User` and `Reset my password` buttons are related to Admin, not the selected user.

## How to reproduce the error
This was tested with `Breeze`.
1. Log in to Admin
2. Go to `Security` > `List Users` > `Show record` (or visit `http://localhost:28080/users/show/1` with your web browser)
3. Go to `Your Profile` (or visit `http://localhost:28080/users/userinfo/` with your web browser)

### CODE REVIEW

**Comment by t25kim** [comment]
@ryanahamilton @ashb @bbovenzi Please take a look at my PR! 🙏

**Review by bbovenzi — COMMENTED** [review]
Looks right to me.

@jhtimmins, I think you're more familiar with fab security.

**Comment by uranusjr** [comment]
I think (some of) the code change should go into `_show` instead.

**Comment by ephraimbuddy** [comment]
It seems this is no longer reproducible and I can't find `security > list users > show record` in the UI.

Sorry @tiokim as this seemed to not have received the needed attention, do you think it's still an issue?

**Pull request closed without merging**
