### PR TITLE
statuses column on /admin shows only active or most recent dag_runs

### PR DESCRIPTION
**Pull request by jtschoonhoven**
https://github.com/airbnb/airflow/issues/974

### CODE REVIEW

**Comment by mistercrunch** [comment]
Can you please rename `Status` to `Recent Statuses` here:
https://github.com/airbnb/airflow/blob/master/airflow/www/templates/airflow/dags.html#L23

Ideally also add an info tooltip that fully details what is shown in an info bubble right after that:

```
<span class="glyphicon glyphicon-info-sign" aria-hidden="true" title="Insert verbose description here"></span>
```

then call `.tooltip()` in javascript to get the nice looking bootstrap tooltip.

**Comment by jtschoonhoven** [comment]
@mistercrunch done. What's up with the tests?

**Comment by mistercrunch** [comment]
We get random failures on travis sometimes, I re-triggered it

**Comment by mistercrunch** [comment]
Can you add a test that hits that endpoint in here?
https://github.com/airbnb/airflow/blob/master/tests/core.py#L725

**Comment by jtschoonhoven** [comment]
@mistercrunch will revisit this in a week or so when I have time.

**Comment by bolkedebruin** [comment]
@jtschoonhoven Ping. Are you able to update this. Would be  great to have this in.

**Comment by mistercrunch** [comment]
Oh yes, please rebase and I'll merge!

**Comment by jtschoonhoven** [comment]
@mistercrunch done

**Pull request merged**
