### PR TITLE
Breeze / KinD  - support earlier k8s versions, fix recreate and kubectl versioning

### PR DESCRIPTION
**Pull request by bbenzikry**
This PR covers several small issues; 

* Locking breeze to v1.18 seems like a mistake as it;
  1. Prevents testing k8s oriented operators that rely on CRDs such as the spark-on-k8s operator
             which is an issue for many projects in 1.18 due to kubernetes/kubernetes#88076 
             A few reference issues: 
             https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/921
             https://github.com/operator-framework/operator-sdk/issues/3235
             https://github.com/kubernetes-sigs/controller-tools/issues/444 
  2. Prevents testing workloads on earlier, in-use versions ( EKS, for example, just got to 1.17 this month )

I've added the latest versions from kind ( v1.17.5, v1.16.9 ) and updated the default version to v1.18.6

* ``breeze kind-cluster recreate`` did not seem to work even though it's mentioned in the breeze docs. 
Currently throws: 
```
ERROR: Unknown Kind Kubernetes cluster operation: 'recreate'
Should be one of:
start stop restart status deploy test shell
```

*  ```breeze kind-cluster deploy``` had a typo in perform_kind_cluster_operation

* kind-cluster kubectl version ignored KUBERNETES_VERSION ( typo )

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Great! Thanks!

**Review by potiuk — CHANGES_REQUESTED** [review]
What we also probably want is to run the tests on those different versions of kubernetes. Would you mind also extending matrix of the kubernetes versions in .github/workflows/ci.yml for Kubernetes tests?

**Comment by bbenzikry** [comment]
Hi @potiuk, added the changes yesterday, let me know if there's anything else missing

**Comment by potiuk** [comment]
Fantastic! Thanks @bbenzikry

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
cc: @kaxil  @dimberman - we have now three versions of Kubernetes tested. I am cherry-picking all the changes to 1.10 now.

**Pull request merged**
