### PR TITLE
feat(trigger): reload trigger if file changes

### PR DESCRIPTION
**Pull request by Lee-W**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Lee-W** [comment]
Hi @uranusjr, I recall you mentioning that reloading is generally not a good idea. However, @pauloventurab faced a syncing issue with the triggerer on https://github.com/apache/airflow/issues/31743. I'm not sure if there're other better solutions than reloading the triggerer. I have drafted an idea of reloading only when necessary in this draft PR. I would appreciate your feedback on it. Thank you.

**Comment by uranusjr** [comment]
I am very against this as well. This seems to solve the immediate problem, but will very likely to cause other issues down the road.

Why not just restart the triggerer process? The process is designed to be robust, and reloading it entirely is a fully supported operation.

**Comment by Lee-W** [comment]
> I am very against this as well. This seems to solve the immediate problem, but will very likely to cause other issues down the road.

Yep, I guess that would be the case as well. That's why I'd like to have some feedback before investing more time crafting it 🙂 Thanks for the prompt feedback.
 
> Why not just restart the triggerer process? The process is designed to be robust, and reloading it entirely is a fully supported operation.

If that's the case, should we comment on this solution on https://github.com/apache/airflow/issues/31743, mark the issue as `won't fix`, and close it?

**Comment by uranusjr** [comment]
I’m thinking maybe (not sure) we can still do something to reduce the confusion. Let’s continue in the issue thread instead.

**Comment by Lee-W** [comment]
Got it. Sounds good 👍 I'll check what can be done to reduce such confusion. Thanks!

**Pull request closed without merging**
