### PR TITLE
Update wasb.rst

### PR DESCRIPTION
**Pull request by rab170**
typo. should be WASB not WASP

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Nice 🐝

**Comment by rab170** [comment]
thanks :)

**Comment by rab170** [comment]
I noticed that a test failed (doubtfully related to my change).... do i need to do anything to ensure that the change gets integrated downstream?

**Comment by rab170** [comment]
i.e., not lost :)

**Comment by eladkal** [comment]
> thanks :) certainly a small contribution! haha
> 
> next one is guaranteed to be be strictly greater than or equal in size :D

All contributions are important :)


> do i need to do anything to ensure that the change gets integrated downstream?

Its OK. No further action required.

**Pull request merged**
