### PR TITLE
fix task_instance_mutation_hook

### LINKED ISSUE #9902: task_instance_mutation_hook not using my custom implementation
**Apache Airflow version**: v1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NO

**Environment**: airflow 1.10.11 running on ubuntu 18.04 (used pip for installation) 

- **Cloud provider or hardware configuration**: bare metal 
- **OS** (e.g. from /etc/os-release): ubuntu 18.04
- **Kernel** (e.g. `uname -a`): Linux dev1 4.15.0-108-generic 109-Ubuntu SMP Fri Jun 19 11:33:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: pip
- **Others**:

**What happened**:
I'm not able to get task_instance_mutation_hook (https://github.com/apache/airflow/pull/8852) to load my custom implementation from `$AIRFLOW_HOME/config/airflow_local_settings.py`.

**What you expected to happen**: Airflow to use task_instance_mutation_hook provided in `$AIRFLOW_HOME/config/airflow_local_settings.py`.

**How to reproduce it**: make sure your running v1.10.11 and create a custom `$AIRFLOW_HOME/config/airflow_local_settings.py` where you define a dummy `task_instance_mutation_hook` as next
```python
def task_instance_mutation_hook(ti):
   # every new or up to retry task will be added to non existent queue, so no task will pass through
   if ti.state in [State.NONE, State.UP_FOR_RETRY]:
      ti.queue = 'dummy-queue'
```
if any of the airflow example dags run successfully then, the previous hook didn't work.

**Anything else we need to know**: task_instance_mutation_hook is a new feature introduced in v1.10.11

### PR DESCRIPTION
**Pull request by waleedsamy**
Fixes #9902.
Importing task_instance_mutation_hook will keep the default impl. To fix this I updated Dagrun model to import settings and then later call `settings.task_instance_mutation_hook`; The [same](https://github.com/apache/airflow/blob/c8c52e69c8d9cc1f26f63d95aecc0a6498d40b6f/airflow/models/dagbag.py#L364) way used while calling `policy` function.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by waleedsamy** [comment]
cc @milton0825 @ashb

**Comment by milton0825** [comment]
Looks like static check is failing:
```
+from airflow import settings
 from airflow.exceptions import AirflowException
 from airflow.models.base import ID_LEN, Base
 from airflow.models.taskinstance import TaskInstance as TI
-from airflow import settings
 from airflow.stats import Stats
 from airflow.ti_deps.dep_context import DepContext
 from airflow.ti_deps.dependencies_states import SCHEDULEABLE_STATES
```

**Comment by kaxil** [comment]
that is odd, I don't think it makes any difference. The module is always fully imported into the sys.modules mapping

**Comment by waleedsamy** [comment]
@kaxil In `dagrun.py`, having 
```python
# airflow/__init__.py > airflow/models/__init__.py > airflow/models/dagrun.py
from airflow.settings import task_instance_mutation_hook
```
will load `task_instance_mutation_hook` with the default implementation inside `settings.py` which will **later updated** (when [settings.initialize()](https://github.com/apache/airflow/blob/d23fa2f8896c5e31745131e6917f1970b4aa590f/airflow/__init__.py#L48) called, and [airflow_local_settings](https://github.com/apache/airflow/blob/d23fa2f8896c5e31745131e6917f1970b4aa590f/airflow/settings.py#L400) provided). The import of `task_instance_mutation_hook` will result in caching the old implementation and the change in this PR will drop this caching so calling `settings.task_instance_mutation_hook` will get you the fresh implementation of  `task_instance_mutation_hook`( after _settings.initialize_ load the _airflow_local_settings_).

**Comment by milton0825** [comment]
This is good finding! Do you mind look into the test failures? I assume they are related to the change.

**Comment by waleedsamy** [comment]
@milton0825 I'm checking them now (Static checks is passing now)

**Comment by kaxil** [comment]
> @kaxil In `dagrun.py`, having
> 
> ```python
> # airflow/__init__.py > airflow/models/__init__.py > airflow/models/dagrun.py
> from airflow.settings import task_instance_mutation_hook
> ```
> 
> will load `task_instance_mutation_hook` with the default implementation inside `settings.py` which will **later updated** (when [settings.initialize()](https://github.com/apache/airflow/blob/d23fa2f8896c5e31745131e6917f1970b4aa590f/airflow/__init__.py#L48) called, and [airflow_local_settings](https://github.com/apache/airflow/blob/d23fa2f8896c5e31745131e6917f1970b4aa590f/airflow/settings.py#L400) provided). The import of `task_instance_mutation_hook` will result in caching the old implementation and the change in this PR will drop this caching so calling `settings.task_instance_mutation_hook` will get you the fresh implementation of `task_instance_mutation_hook`( after _settings.initialize_ load the _airflow_local_settings_).

when you run `airflow scheduler` or `airflow webserver` it loads ` from airflow import settings` that already initializes the settings

https://github.com/apache/airflow/blob/4eddce22a3e0eb605f5661204a005262bbaa54cd/airflow/cli/commands/scheduler_command.py#L24
https://github.com/apache/airflow/blob/4eddce22a3e0eb605f5661204a005262bbaa54cd/airflow/settings.py

**Review by kaxil — CHANGES_REQUESTED** [review]
Running any `airflow` cli command calls https://github.com/apache/airflow/blob/4eddce22a3e0eb605f5661204a005262bbaa54cd/airflow/__init__.py#L41

so I don't see the change in this PR making it any different.

**Comment by waleedsamy** [comment]
This issue is happening with **1.10.11** - not related to master branch.
Looking into [v1.10-stable](https://github.com/apache/airflow/blob/d23fa2f8896c5e31745131e6917f1970b4aa590f/airflow/__init__.py#L48) airflow/\_\_init\_\_.py#L48

```py
from airflow import utils
from airflow import settings
from airflow.configuration import conf
from airflow.models import DAG
from flask_admin import BaseView
from importlib import import_module
from airflow.exceptions import AirflowException

settings.initialize()
```

it will do a bunch of imports before calling initialize. These import will reach `dagrun.py` and `from airflow.settings import task_instance_mutation_hook` will cache `task_instance_mutation_hook` so even when calling `settings.initialize()` it won't affect the `task_instance_mutation_hook` in `dagrun.py` anymore.

**Comment by milton0825** [comment]
Should we target the change with `v1-10-test` branch then?

**Comment by waleedsamy** [comment]
Ok, I'll create a new PR for v1-10-test.

**Comment by kaxil** [comment]
> v1.10-stable

That is a very good point, in that case the correct solution for v1-10-test would be to move the `from airflow.models import DAG` after settings.initialize or have it similar to master as this will fix other things too (i.e other airflow_local_settings functions that would used old cached functions)

**Comment by milton0825** [comment]
+1

**Comment by waleedsamy** [comment]
@kaxil Ok, I'll move `from airflow.models import DAG` after `settings.initialize`.

**Comment by kaxil** [comment]
> @kaxil Ok, I'll move `from airflow.models import DAG` after `settings.initialize`.

Thanks, really appreciate the fix. Can you also please add a comment in that file on why the import line is below `settings.initialize`? 

Also pylint or isort might complain, so you might have to add some `#pylint: disable` and/or `#noqa` after the comments to disable the checks

**Comment by waleedsamy** [comment]
>  Can you also please add a comment in that file on why the import line is below settings.initialize?
I'll, thanks guys :)

**Review by kaxil — APPROVED** [review]

**Review by milton0825 — APPROVED** [review]

**Pull request merged**
