### PR TITLE
Add how-to Guide for WinRM operators

### PR DESCRIPTION
**Pull request by Melodie97**
solves issue: #11914
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM!

**Comment by potiuk** [comment]
You will also need to update "provider.yaml" - with link to the new document (static check fails) https://github.com/apache/airflow/blob/main/airflow/providers/microsoft/winrm/provider.yaml - see for example here: https://github.com/apache/airflow/blob/7dbd9e4e0276c508854cceac35315762a0549d51/airflow/providers/microsoft/mssql/provider.yaml#L38

**Comment by Melodie97** [comment]
@potiuk I've pushed the changes
However, I don't know why static checks are failing even after using pre-commit locally.
The issue seems to be- hook id: markdownlint

**Comment by potiuk** [comment]
> @potiuk I've pushed the changes However, I don't know why static checks are failing even after using pre-commit locally. The issue seems to be- hook id: markdownlint

That's not your error. I added a fix here: https://github.com/apache/airflow/pull/21347

**Comment by potiuk** [comment]
The "docker-compose" error is a flaky test. merging.

**Pull request merged**
