### PR TITLE
[AIRFLOW-XXX] Fix typos in tests/gcp_authenticator.py

### PR DESCRIPTION
**Pull request by pradeepbhadani**
Update comment description for a python function.

This is my first contribution to this project and I am not sure if JIRA ticket is required for these kind of changes. Let me know if JIRA ticket is must and I can create one.

### CODE REVIEW

**Comment by mik-laj** [comment]
Travis error is unrelated.

**Comment by mik-laj** [comment]
Thank you warmly for your contributions and I look forward to further PRs 😸  We need more people like you.

**Comment by marengaz** [comment]
> Travis error is unrelated

yes it is @mik-laj !
there's a trailing space on line 139

**Comment by pradeepbhadani** [comment]
Thanks @mik-laj

**Pull request merged**
