### PR TITLE
[AIRFLOW-448] Adding Apigee as an official user of Airflow

### PR DESCRIPTION
**Pull request by btallman**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-448] https://issues.apache.org/jira/browse/AIRFLOW-448

### CODE REVIEW

**Comment by r39132** [comment]
@btallman Thanks for your contribution.

See my comments on #1731 and how the submitter corrected it on #1733

In addition to a call for references, we also want to acclimate potential future contributors with the apache commit guidelines. This is required before I can merge your change.

You commits and PRs need to be prefixed by `[AIRFLOW-XXX]` to make it easy to generate release notes. Please fix and ping me when ready

**Comment by btallman** [comment]
Fixed. Sorry, once you sent that, the format clicked...

Thanks,
Ben

## 

Ben Tallman - 503.680.5709

**Comment by r39132** [comment]
No worries. You also need to modify your commit message, because that's what will be used in the release note ultimately, but I can fix it for now when I merge - one of the cool features of @jlowin merge tools is fixing issues like this, but we want contributors to still follow the convention in case the safety net fails. Please make sure to edit and push future commits with the correct format rules.

**Comment by r39132** [comment]
And welcome to the Apache Airflow community [officially]! Looking forward to your talk at the next meetup

**Pull request closed without merging**
