### PR TITLE
add attachments support to slack operator

### PR DESCRIPTION
**Pull request by abridgett**
This allows richer slack notifications as per: https://api.slack.com/docs/attachments

### CODE REVIEW

**Comment by mistercrunch** [comment]
:+1:

**Comment by pkexcellent** [comment]
it seems like attachment is not working well in library 'slackclient', no attachment will be sent...

**Comment by abridgett** [comment]
Hi @pkexcellent, what version of the slack client are you using out of interest. Also is it possible to see the exact attachment you are sending (just in case there's a problem with the content of the attachment)?

**Comment by pkexcellent** [comment]
Hi @abridgett , I found it's my fault. I post a attachment with wrong formatted content... 
Very sorry to bother you.

**Comment by abridgett** [comment]
ah, cool, no worries - glad you got it fixed :-)

**Pull request merged**
