### PR TITLE
[AIRFLOW-1930] Convert func.now() to timezone.utcnow()

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1930

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

func.now() defaults to the timezone of the database,
we assume that everything is in UTC which might not be
the case if func.now() is used.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

* Current tests 

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by gwax** [comment]
If your columns are timezone aware it doesn't matter what timezone the server uses. That is why we are using timezone aware columns.

Changing this potentially causes exactly the problem you are trying to avoid: suppose I am in -7:00 timezone and my server is set to UTC; now I create a new timezone aware datetime at 15:00-7:00 but I calculate now using utcnow, what ends up being created is 24:00-7:00, which gets stored as 7:00UTC the next day.

If columns are timezone aware, feed them timezone aware, then the columns and datetime objects will take care of all of this for you.

This is NOT a bug; this is working as intended.

Reasonably, one might want to use `server_default=func.now()` so that the server does the calculations and we don't worry about network latency but that's a different issue

**Comment by bolkedebruin** [comment]
As mentioned on the JIRA, @gwax your analyses is not entirely correct. 

It is actually a bug. The transition is handled by Airflow, all dates should be stored in UTC regardless of what time zone database server thinks it is in. Note that for many databases the current time zone is dependent on the connection (MySQL) or connection and server setting (Postgres) or no support at all (SQLite). In addition none of these databases are really time zone aware as they don’t store the time zone itself (only Oracle does afaik). This means that transitions are not handled correctly if left to the database.

This means that func.now created an arbitrary date that we cannot rely on across workers/scheduler and it circumvented the check we do to only store UTC date times as it was executed at the database level. 

DAGS store the information on time zones and with pendulum (and not pytz) we manage transitions across time zones and dst.

You could argue that converting the D.B. fields to time zone aware fields was redundant, however I think it is an improvement across the board.

So the mantra is:

1. Everything in the database is required to be UTC
2. Airflow uses UTC internally
3. DAGs maintain time zone information
4. Only at next/previous schedule for Cron schedules we convert back the DAG time zone.
5. User interface (web) can therefore function time zone independent (not implemented)

This keeps things sane and is according to best practices.

**Comment by gwax** [comment]
Followed up in JIRA, pasting a subset snippet here for reference. Could we consider:

```python
# Added to airflow/util/timezone.py

class sql_utcnow(expression.FunctionElement):
    """UTCNOW() expression for multiple dialects."""
    type = sa_utc.UtcDateTime()


@compiles(sql_utcnow)
def default_sql_utcnow(element, compiler, **kw):
    """Assume, by default, time zones work correctly.

    Note:
        This is a valid assumption for PostgreSQL and Oracle.
    """
    return 'CURRENT_TIMESTAMP'


@compiles(sql_utcnow, 'mysql')
def mysql_sql_utcnow(element, compiler, **kw):
    """MySQL returns now as localtime, so we convert to UTC.

    Warning:
        This must be executed and cannot be used as a
        column server_default value.
    """
    return "CONVERT_TZ(CURRENT_TIMESTAMP,@@session.time_zone,'+00:00')"


@compiles(sql_utcnow, 'sqlite')
def sqlite_sql_utcnow(element, compiler, **kw):
    return "DATETIME('NOW')"


@compiles(sql_utcnow, 'mssql')
def mssql_sql_utcnow(element, compiler, **kw):
    """MS SQL provides a function for the UTC datetime."""
    return 'GETUTCDATE()'
```

Usage then goes from:

```python
created_dttm = Column(UtcDateTime, default=func.now())
```

to

```python
created_dttm = Column(UtcDateTime, default=timezone.sql_utcnow())
```

**Comment by bolkedebruin** [comment]
As mentioned on JIRA I am not convinced we should move to SQL UTC. Let’s continue the discussion there, but I would also like to continue with this change for consistency reasons. The change proposed by @gwax requires a lot more work to be comprehensive and should be done in a separate PR if at all.

**Comment by bolkedebruin** [comment]
@Fokko PTAL

**Comment by Fokko** [comment]
I have to take a look into this. I'm not a timezone expert and I'm not really sure what the convention is. For me it makes most sense to store everything as UTC, but what is most important is that we don't reinvent the wheel here and that we use the mechanism that is most common in Python-land.

**Comment by bolkedebruin** [comment]
There is no “python-land” in this case. The convention in airflow is to store everything in UTC and use UTC internally everywhere and only expose timezone information where it matters (scheduling, ui eventually). This change brings this part in line with the convention.

**Comment by gwax** [comment]
Not only is there not a "most common" approach, there are conflicting approaches in "Python-land", specifically because Python-sqlite-land has one way to do this that is diametrically opposed to the Python-PostgreSQL-land way to do this and rather different from the Python-MySQL-land way to do this.

Often times, we get to _just_ let SQLAlchemy worry about this sort of thing but, unfortunately, in this case SQLAlchemy doesn't have a standard way to do this. The best SQLAlchemy provides is using this problem as a [compiler example](http://docs.sqlalchemy.org/en/latest/core/compiler.html#utc-timestamp-function).

The discussion, essentially boils down to: 1) Should we calculate timestamps on the SQL server or should we calculate timestamps in Python on the individual workers, scheduler, and webservers; and 2) if we calculate timestamps on the SQL server, what should that code look like.

My assertion is that we should calculate the timestamps on the SQL server so that we can have a single, consistent clock for all timestamps.

**Comment by bolkedebruin** [comment]
@gwax I want to get this to a consistent state first. That means moving to the internal version as your change would require a lot more touches to current code. 

I am open to change to the sql version, but it might have more complex issues as seen in the other PR. If you are willing to pick that up, please do! I would advise to have some discussion on the mailing list as well then.

Will merge in next two days @Fokko @jgao54

**Comment by gwax** [comment]
Sounds reasonable @bolkedebruin. Would you mind cutting a new ticket or putting some TODOs in the code so this doesn't get dropped forever.

**Comment by bolkedebruin** [comment]
Done: https://issues.apache.org/jira/browse/AIRFLOW-1990

**Comment by bcb** [comment]
I think the `default` value should be a callable, not a datetime.

If you pass a datetime, every record gets the exact same timestamp.

Affects my PR [here](https://github.com/apache/incubator-airflow/pull/2902).

**Comment by bolkedebruin** [comment]
Good point. I’ll have a look

**Pull request closed without merging**
