### PR TITLE
feat(providers/microsoft): add DefaultAzureCredential support to cosmos

### PR DESCRIPTION
**Pull request by Lee-W**
* add DefaultAzureCredential support to cosmos
    *  use CosmosDBManagementClient to authenticate cosmos client through DefaultAzureCredential

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Lee-W** [comment]
I notice the constrains keep failing. Is there anything I need to change for it?

**Comment by potiuk** [comment]
> I notice the constrains keep failing. Is there anything I need to change for it?

Fix for it in https://github.com/apache/airflow/pull/33774 -> they also fail in main and the reason is that we already relaxed the limit for hive provider for 3.11 but we have not released the matching version of hive provider yet in PyPI (we just made it possible back for the hive provider to work on 3.11 but it needs releasing a new provider version due to dependency changes required for 3.11). 

The #33774 will skip over hive provider for 3.11 temporarily and we will remove it when we have the new hive provider

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
We can merge it now even with failing constrainst (they also fail in main).

**Comment by Lee-W** [comment]
> > I notice the constrains keep failing. Is there anything I need to change for it?
> 
> Fix for it in #33774 -> they also fail in main and the reason is that we already relaxed the limit for hive provider for 3.11 but we have not released the matching version of hive provider yet in PyPI (we just made it possible back for the hive provider to work on 3.11 but it needs releasing a new provider version due to dependency changes required for 3.11).
> 
> The #33774 will skip over hive provider for 3.11 temporarily and we will remove it when we have the new hive provider

Thanks for the detail explaining 🙂

**Pull request merged**
