### PR TITLE
Replace `principle` by `principal` in kerberos-related code

### PR DESCRIPTION
**Pull request by brouberol**
Kerberos has the notion of a [principal](https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-user/What-is-a-Kerberos-Principal_003f.html). "principle" seemed to be a typo.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — DISMISSED** [review]
Even if it's a typo fix, it crosses airflow/providers boundaries - which means that you would have to implement compatibilty layer in both airflow and providers:

1) so that new airflow supports old providers
2) so that old airflow (2.8+ currently) supports new providers

I think the hassle is not worth the typo fix

**Comment by eladkal** [comment]
> I think the hassle is not worth the typo fix

We can just have a function with the correct name and deprecate the old one
given that we are going to remove all deprecations before 2.11 I think it's good chance to do it

**Comment by potiuk** [comment]
> Still I think we can do it with Airflow 3 and backport to 2.10.. this is pretty minor and easy to do.

If @brouberol wishes to do the back-compatiblity code for both issues, we can do it, yes.

**Comment by eladkal** [comment]
OK lets take it by steps:
1. changes to `airflow/security/kerberos.py` should be in a separated PR. Add new function `get_kerberos_principal` with the logic and deprecate `get_kerberos_principle` once this PR is merged to main branch, we can cherry pick it to v2.10-test branch.
2. once (1) is completed we can handle the provider changes

**Comment by brouberol** [comment]
I can give it a go, but I'll be a bit tied up in the coming days. Feel free to proceed with 1) if you want. If not, I'll try to address your comment when I have the time. Thanks again!

**Comment by eladkal** [comment]
Cool but actually we need (2) ready before (1)

All you need to do here is to remove the changes to `airflow/security/kerberos.py` and `tests/security/test_kerberos.py`.

Keep the changes you have in providers but change the imports to:

```
try:
    from airflow.security.kerberos import get_kerberos_principal
except ModuleNotFoundError:
    from airflow.security.kerberos import get_kerberos_principle
```

Once you do that provider is compatible with both name and I can do the change to airflow core.

**Comment by brouberol** [comment]
I've reworked this patch to only rename the affected function, and have opened https://github.com/apache/airflow/pull/44150 that attempts to import the fixed function and falls back to the typoed one, as suggested in https://github.com/apache/airflow/pull/43679#issuecomment-2460343939

**Comment by eladkal** [comment]
Lets add `43679.significant.rst` in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).
Just need to say in the file that we renamed the function due to misspelling. This will be used to generate the release notes.

**Review by eladkal — APPROVED** [review]

**Pull request merged**
