### PR TITLE
[AIRFLOW-3742] Respect the `fallback` arg in airflow.configuration.get

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-3742

### Description

- [x] This `fallback` argument is part of the API from our parent class, but we didn't
support it because of the various steps we perform in `get()` - this
makes it behave more like the parent class, and can simplify a few
instances in our code (I've only included one that I found here)

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: few small tests added

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
Ping @Fokko @feng-tao @kaxil Anyone got time to review this? I've got some fixes I'd like to do around RBAC webserver config/AIRFLOW_HOME that I'd like to use this for

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
LGTM @ashb

**Comment by feng-tao** [comment]
LGTM

**Comment by ashb** [comment]
Fixed up by #4674

**Pull request merged**
