### PR TITLE
AIP-44 Migrate MetastoreBackend to Internal API

### LINKED ISSUE #30242: AIP-44 Migrate MetastoreBackend to Internal API
Used by Variable/Connection.

https://github.com/apache/airflow/blob/894741e311ffd642e036b80d3b1b5d53c3747cad/airflow/secrets/metastore.py#L32

### PR DESCRIPTION
**Pull request by mhenc**
Migrate MetastoreBackend 's get_connections and get_variables to Internal API.

This change requires adding Connection to serializable types. 

closes: #30242

### CODE REVIEW

**Comment by mhenc** [comment]
Made on top of https://github.com/apache/airflow/pull/30282 so please review only the last commit.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Needs conflict resolving :(

**Comment by mhenc** [comment]
Thank you. Right, there were some significant merge conflicts. It should be fine now.

**Comment by potiuk** [comment]
Hmmm. Tests failing?

**Comment by mhenc** [comment]
Tests fixed

**Pull request closed without merging**
