### PR TITLE
Add an optional `on_error` kwargs for `S3ToSnowflakeOperator`

### PR DESCRIPTION
**Pull request by nlecoy**
Adds an optional kwargs `on_error` that specifies the action Snowflake has to perform when an error is encountered while loading data from a file.

### CODE REVIEW

**Comment by potiuk** [comment]
Woudl you mind adding a test ? I think the operator is pretty well covered by unit tests and adding "on_error" tests should be easy.

**Comment by potiuk** [comment]
Also Ideally - this PR shoudl be split into two as those two changes are independent, and it is much better if they are separated (for history/changelog/cherry-picks/reverts)

**Comment by nlecoy** [comment]
Hi @potiuk, sure ! I just updated this PR adding some testing and removing the template_fields. I also opened a new PR to add this template_field to S3ToSnowflake, available here https://github.com/apache/airflow/pull/15926

Have a nice day

**Review by potiuk — APPROVED** [review]

**Comment by eladkal** [comment]
@nlecoy can you fix the failing test?

**Pull request closed without merging**
