### PR TITLE
Fetching databricks host from connection if not supplied in extras.

### PR DESCRIPTION
**Pull request by joshi95**
Fix for the issue #10726 . Have supported the previous functionality of fetching the host from extras if specified else it is getting fetched from the databricks connection which makes more sense.

### CODE REVIEW

**Review by mik-laj — COMMENTED** [review]
Can you add tests to avoid regression?

**Comment by joshi95** [comment]
> Can you add tests to avoid regression?

Sure will add that. :)

**Comment by joshi95** [comment]
> > Can you add tests to avoid regression?
> 
> Sure will add that. :)

Hi I have added the tests. Not sure why CI/CD test were cancelled.

**Comment by potiuk** [comment]
Caused by the transient issue when building image in the "BuildImage" run: https://github.com/apache/airflow/runs/1075245858?check_suite_focus=true

**Comment by potiuk** [comment]
Re-runed both.

**Comment by joshi95** [comment]
> Re-runed both.

Thank you :)

**Comment by potiuk** [comment]
Ah no - you nee to rebase to latest master. The build of yours is based on rather old version of the Docker file that uses  removed requirements, so you need rebase and it should work fine.

**Comment by joshi95** [comment]
I will start a new PR closing this.

**Pull request closed without merging**
