### PR TITLE
Update min-sqlalchemy version to account for latest features used

### PR DESCRIPTION
**Pull request by potiuk**
Some of the recent sqlalchemy changes are not working with minimum version of sqlalchemy of ours - for example `where` syntax does not allow moe than one clause and we are already passing more in _do_delete_old_records (added in #33527). This syntax however was added in SQL Alchemy 1.4.28 and our minimum version was 1.4.27.

This change bumps the minimum SQLAlchemy version to 1.4.28 but it also adds a special test job that only runs on Postgres that downgrades the SQLAlchemy to the minimum supported version (retrieved from setup.cfg). This way, we will be able to detect such incompatible changes at the PR time. This is a new flag `--downgrade-sqlalchemy` on test command that works similar to earlier `--upgrade-boto`.

We also enable the `--upgrade-boto` and `--downgrade-sqlalchemy` flags to be used for `breeze shell` command - thanks to that we can easily test both flags with `breeze shell` command.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I am not sure if this test will pass here - we might have other functionality used from even later versions of sqlalchemy - but once this PR gets merged we should be protected against making similar accidental SQLAlchemy new features used without bumping the min version. 

SQLAlchemy - unfortunately - does not follow SEMVER and they are adding features in patchlevel versions, so we might accidentally use features (like it was in this case) added at any release. This one should protect us.

**Comment by potiuk** [comment]
I am also thinking about having a separate test where we downgrade EVERYTHING possible to the lowest possible versions and run tests for it. But this one wil likely require reconciliation and revisiting MANY min-versions we have and some smart way of figuring what should be min-versions for some of our dependencies.

https://github.com/apache/airflow/issues/34296

**Comment by Taragolis** [comment]
With every step we are getting closer to pin to 1.4.49 😩

**Review by Taragolis — APPROVED** [review]

**Comment by uranusjr** [comment]
I think eventually we want to allow the entire 2.x series anyway, at which point disallowing everything under 1.4.49 would not be a big problem.

**Pull request merged**
