### PR TITLE
Sync v2-10-stable with v2-10-test to release python client v2.10.0

### PR DESCRIPTION
**Pull request by utkarsharma2**

### CODE REVIEW

**Comment by pierrejeambrun** [comment]
I am not sure here, can't we just use the `2.10.0` tag  that was just released to base our python client release off of it ?

So the client and the airflow API are in sync ?

Here this sync PR potentially add extra commits that fix / update the API while those are not part of the 2.10.0 airflow release.

Maybe I misunderstood something.

**Comment by potiuk** [comment]
@pierrejeambrun  Agree, ti's a bit broken now - It's a consequence of the change we agreed that we back-port them to v2-10-test -as we merge PRs to main - previously we only marked them as "to-be-cherry-picked" - but now the situation changed. Previously only **some** changes would have to be cherry-picked for the client release (changing version / changelog of the client mainly https://github.com/astronomer/airflow/commit/3ea764f802fddf16f4a12f39212f067e1abcbbf5  - and potentially some dependencies https://github.com/astronomer/airflow/commit/e76dba61b92eadcee9e3193640ab8db6a9466528 also the watchtower limit few moment ago that broke stable) and it happened before any other cherry-picks were done and merged to stable. 

Maybe the idea of backporting needs soem refinement in the process - like release python client as part of releasing Airflow.

**Comment by utkarsharma2** [comment]
> I am not sure here, can't we just use the `2.10.0` tag that was just released to base our python client release off of it ?
> 
> So the client and the airflow API are in sync ?
> 
> Here this sync PR potentially add extra commits that fix / update the API while those are not part of the 2.10.0 airflow release.
> 
> Maybe I misunderstood something.

We can do that as well. I'm trying to follow the [release process](https://github.com/apache/airflow/blob/main/dev/README_RELEASE_PYTHON_CLIENT.md) as much as possible. Also, I don't see it as much of an issue here, since there aren't any changes that could affect the Python client release, other than what we intend(clients/python/CHANGELOG.md  and clients/python/version.txt) to add. I might have missed some, please point out any commits you are concerned about?

**Comment by pierrejeambrun** [comment]
> might have missed some, please point out any commits you are concerned about?

I didn't take a look in the details at the commits that are being sync to stable. That was just a general observation that this way of doing it 'could' potentially cause trouble.

I'm wondering how we would actually handle the case where one of those backport commit do modify the openapi spec. (for instance fix a parameter type).

**Comment by potiuk** [comment]
> I'm wondering how we would actually handle the case where one of those backport commit do modify the openapi spec (for instance fix a parameter type) between the time when airflow core is released, and we have not yet released the related client version.

I tihnk the issue can be solved by timing of releases. If we generate and client changelog / make decision whether we release API and decision on the version of the client at the sama time when we release Airflow, this would be a non-issue. 
In this case several days passed since and circumstances and environment changed (new dependencies released that required some actions, PRs were merged to v2-10-test)

@ephraimbuddy @utkarsharma2 @jedcunningham -> WDYT.

**Comment by utkarsharma2** [comment]
> > I'm wondering how we would actually handle the case where one of those backport commit do modify the openapi spec (for instance fix a parameter type) between the time when airflow core is released, and we have not yet released the related client version.
> 
> I tihnk the issue can be solved by timing of releases. If we generate and client changelog / make decision whether we release API and decision on the version of the client at the sama time when we release Airflow, this would be a non-issue. In this case several days passed since and circumstances and environment changed (new dependencies released that required some actions, PRs were merged to v2-10-test)
> 
> @ephraimbuddy @utkarsharma2 @jedcunningham -> WDYT.

Yes, we can decide and move forward with the client release quickly. However, there's a caveat based on my limited experience with Airflow releases: they can become quite hectic. Handling two releases back-to-back could be taxing for the release manager. I would prefer if we could decouple the release processes.

The way I see it, we need to update the changelog and make the necessary version changes in both the 2-10-stable and 2-10-test branches. This can be done by submitting separate PRs for each branch, allowing us to continue the release from the 2-10-stable without any unexpected changes and not being concerned about what's added in the 2-10-test.

**Comment by pierrejeambrun** [comment]
I can confirm that sometimes the release process can become a bit painful and having to chain that with other release process can represent a significant effort. That would be more confortable for the release manager if we can figure something out that is a bit more flexible on the schedule as suggested by @utkarsharma2.

> The way I see it, we need to update the changelog and make the necessary version changes in both the 2-10-stable and 2-10-test branches. This can be done by submitting separate PRs for each branch, allowing us to continue the release from the 2-10-stable without any unexpected changes and not being concerned about what's added in the 2-10-test.

I like that

**Comment by potiuk** [comment]
> This can be done by submitting separate PRs for each branch, allowing us to continue the release from the 2-10-stable without any unexpected changes and not being concerned about what's added in the 2-10-test.

Yes. That would be another good approach.

**Comment by potiuk** [comment]
BTW, This one will not work still - we also need to enable PRs for v2-10-stable which are not enabled.

**Comment by potiuk** [comment]
Hey @utkarsharma2 -> I believe we are getting very close :). There is this one flaky test with mapping and I **think** it shoudl be fixed by cherry-picking https://github.com/apache/airflow/pull/41414 - this is the only "test" change for database isolation mode that did not make it to v2-10-test branch as far as I can see (cc: @jscheffl - can you maybe take a look as well to double check?)

**Comment by potiuk** [comment]
Correction:

https://github.com/apache/airflow/pull/41344 and https://github.com/apache/airflow/pull/41414

**Comment by potiuk** [comment]
Also this one: https://github.com/apache/airflow/pull/41626  should fix "latest boto" tests when merged.

**Comment by jscheffl** [comment]
> Hey @utkarsharma2 -> I believe we are getting very close :). There is this one flaky test with mapping and I **think** it shoudl be fixed by cherry-picking #41414 - this is the only "test" change for database isolation mode that did not make it to v2-10-test branch as far as I can see (cc: @jscheffl - can you maybe take a look as well to double check?)

For the PRs I mentioned I am not sure - they are okay to get to v2-10-test (shall I make PRs for this, lost track about the vast amount of patches we made for isolation mode) but in the last build I only see two problems left caused by boto?

**Comment by utkarsharma2** [comment]
> Hey @utkarsharma2 -> I believe we are getting very close :). There is this one flaky test with mapping and I **think** it shoudl be fixed by cherry-picking #41414 - this is the only "test" change for database isolation mode that did not make it to v2-10-test branch as far as I can see (cc: @jscheffl - can you maybe take a look as well to double check?)

Yes, we are! Thanks for looking into this @potiuk :)


> Correction:
> https://github.com/apache/airflow/pull/41344 and https://github.com/apache/airflow/pull/41414

https://github.com/apache/airflow/pull/41344 is already part of the branch. I have cherry-picked https://github.com/apache/airflow/pull/41414

I'm waiting for us to merge https://github.com/apache/airflow/pull/41626 to the main so I can cherry-pick this as well.

**Comment by potiuk** [comment]
> I'm waiting for us to merge https://github.com/apache/airflow/pull/41626 to the main so I can cherry-pick this as well.

Merged

**Comment by potiuk** [comment]
Hmm. We still have the flaky D tests/models/test_taskinstance.py::TestTaskInstance::test_check_task_dependencies_for_mapped - and I do recall having it (and fixing) in main...  Let me try to dig deeper and find what we are missing here.

**Comment by potiuk** [comment]
cc: @jscheffl -> maybe that one rings a bell for you ?

**Comment by potiuk** [comment]
Anh I know. @utkarsharma2 - this should be fixed by cherry-picking #41389

**Comment by potiuk** [comment]
And #41741 should also make "Database Isolation tests" stable.

**Comment by potiuk** [comment]
Yeah I think the last two @utkarsharma2 #41389 and #41471 should bring the stability back (those are test-only changes).

**Comment by utkarsharma2** [comment]
> Yeah I think the last two @utkarsharma2 #41389 and #41471 should bring the stability back (those are test-only changes).

Thanks @potiuk I have cherry-picked them.

**Comment by potiuk** [comment]
OK. I think the remaining ones are the "regular" flakes - that we have no good solution for now - so just re-running them after tests complete should help

**Comment by jscheffl** [comment]
> OK. I think the remaining ones are the "regular" flakes - that we have no good solution for now - so just re-running them after tests complete should help

I double-checked the list of PRs we had for making DB isolation tests working, don't know if implicitly contained but https://github.com/apache/airflow/pull/41450 was also merged on main and seems to be missing in v2-10-test.

**Comment by potiuk** [comment]
Green ! :)

**Review by phanikumv — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by ephraimbuddy — APPROVED** [review]

**Pull request merged**
