### PR TITLE
removing the regexpattern

### LINKED ISSUE #32360: Consider changing API to not use regexp pattern
### Body

Our public REST API specification has the possibility of using regexp pattern (dag_id_pattern). This is potentially dangerous as free regexp patterns might have potentially some  problems (like infinite recursion or non-linear performance of some patterns) and regexp parsing libraries might have unknown bugs, We should consider making a backwards-incompatible release of the API with the pattern feature removed.

This wouls be a breaking change, and breaking the promise we made to keep our Stable REST API the most stable part of the [Public Airflow Interface](https://airflow.apache.org/docs/apache-airflow/stable/public-airflow-interface.html) that we promised our users to rely on, so should carefully consider if removing it is worth breaking the promise. It would also require strong justification and unsolvable security/performance issue to make such change without bumping the REST API version to new MAJOR version and it would disconnect Airflow MAJOR version from the API MAJOR version, so likely the only good time we can do it, is when we release Airflow 3.

 

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by Bowrna**
closes: #32360 

This PR contains fix that removes the regex pattern in the API and is a breakable change.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — COMMENTED** [review]
Is there a reason for commenting out instead of simply removing the unwanted code ?

Also, some of the endpoints modified are marked with `@mark_fastapi_migration_done` meaning that those endpoints have been duplicated and migrated over to the `new` FastAPI API. This means that those changes need to also be reflected there because this will be the remaining API in Airflow 3.

Depending if we want release that bugfix in the 2.10.x next patch version or not, it means that we need to split the change in two. (The current change that can be cherry picked safely to `v2-10-test`, and the change updating `api_fastapi` that cannot be cherry picked to `v2-10-test`).

**Comment by Bowrna** [comment]
@pierrejeambrun https://github.com/apache/airflow/issues/32360#issuecomment-2410314978

Based on your comment here, do you think these PR changes are not relevant as we are not doing direct regex pattern matching here?

**Comment by pierrejeambrun** [comment]
Yes, I am not sure those change are relevant anymore, but let's hear others first and see what they think :)

**Comment by potiuk** [comment]
Yeah. @pierrejeambrun was right... Let's close that one. Sorry @Bowrna - I should have be more dilligent when I created the issue.

**Comment by Bowrna** [comment]
@potiuk I will explore other issues to solve. I have been inactive for sometime here. I hope to become more active in the coming weeks and solving more issues :)

**Pull request closed without merging**
