### PR TITLE
Add support for .jinja2 extensions

### LINKED ISSUE #8603: Consider supporting .jinja2 extensions across the project
**Description**

At the moment, various operators support reading templates from given filenames (for example, [bash_command](https://airflow.apache.org/docs/stable/_api/airflow/operators/bash_operator/index.html#airflow.operators.bash_operator.BashOperator) of `BashOperator`). However, all of these operators specify extensions such as `.sh`, .`json` etc., so it means users need to write Jinja2 templates inside `.sh`, `.json` files. A better way to do it would be supporting the `.jinja2` extension.

**Use case / motivation**

The motivation is threefold:
1. `.jinja2` extension is a widespread convention which is supported by various editors, including Github itself, PyCharm and [VSCode](https://marketplace.visualstudio.com/items?itemName=samuelcolvin.jinjahtml).
1. Putting templates inside `.jinja2` can help distinguish between regular files and template files just by looking at the directory contents
1. Working with tools that recognize `.jinja2` templates can help reduce errors while authoring templates.

**Related Issues**

https://github.com/apache/airflow/pull/8572#discussion_r416473395

### PR DESCRIPTION
**Pull request by oripwk**
This PR closes #8603, which seeks adding support for `.jinja2` for file templates across the project.

It defines a new property for `BaseOperator` which is a list containing `.jinja2` (and possibly other extensions if someone wants to add in the future), and whenever `template_ext` is not empty, the list is combined with it to produce a definite list of extensions, which is used throughout the class.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by oripwk** [comment]
@mik-laj this is the proposed solution.
The only remaining issue is how we update the docs, since there are dozens of operators whose docs we need to update with "also supports `.jinja2` extensions". Also people creating new operators should not forget adding this.

Do you know of any good way of doing it?

**Comment by mik-laj** [comment]
@oripwk I think you just need to add this information in the base class and check that the documentation in the * .rst files is up-to-date.

**Comment by potiuk** [comment]
Agree with @mik-laj  I think this should be implemented as common feature - so it should be just explained in the same place where we already explain the general jinija templates stuff.

**Comment by oripwk** [comment]
I agree, although there's a minor issue with the docs of the individual fields i.e. in `BashOperator` the `bash_command` doc says:

> "_The command, set of commands or reference to a bash script (must be ‘.sh’) to be executed. (templated)_"

So it will stay as is. The question is if it's fine.

**Comment by potiuk** [comment]
I think we might use the opportunity to improve the docs slightly (and globally). If we go with my proposed rule (.sh and .sh.jinja2) for example in Bash), the we could automate generation of such comment. The extensions supported will remain as they are in the operator definitions, and we could write a small plugin to generate the documentation and list supported extensions and remove manually entered documentation for that. We've done things like that before.

**Comment by ashb** [comment]
As discussed on the dev list, thist might be an opportunity to have, `.sh`. _not_ be templated, but `.sh.jinja2` be templated.

Right now it's not possible to have the script/command etc. live in an external file but not be templated. And that is occasionally annoying.

**Comment by oripwk** [comment]
@ashb 

Do we want to do a separate solution for v1.10 and v2.0? (in v.1.10 just render all `*.sh` _and_ `*.sh.jinja2` but in v.2.0 render only `*.sh.jinja2` _but not_ `*.sh`)?

Or to implement only the v2.0 solution?

**Pull request closed without merging**
