### PR TITLE
[AIRFLOW-3353] Upgrade redis client.

### PR DESCRIPTION
**Pull request by jmcarp**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3353
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Upgrade redis client to latest and rename `StrictRedis` to `Redis`.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Covered by existing tests.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
I need to revert this - right now this version of Redis breaks Celery.

**Comment by ashb** [comment]
Once https://github.com/celery/kombu/pull/948 or something like that is fixed in combo we can bring this change back

**Comment by r39132** [comment]
@ashb Sorry for this.. it looked like a good change and tests were passing. Our tests didn't catch this?

**Comment by jmcarp** [comment]
Sorry! I had the same question about tests. Would it be worthwhile to add an integration test to make sure the celery executor works?

**Comment by ashb** [comment]
Yup, it's the fix for our hook.

Reduced integration tests (i.e. not the full suite, just a few dag tests like we do for kube) hitting celery+redis would be amazing to add!

**Pull request merged**
