### PR TITLE
Remove unused recurse_tasks function

### PR DESCRIPTION
**Pull request by kaxil**
I can't see this function used anywhere and it returns nothing so I don't see why someone would use it

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by mik-laj** [comment]
This function return data by arguments (2,3,4k not by value.

**Comment by kaxil** [comment]
> This function return data by arguments (2,3,4k not by value.

Yup, you are right, Would you like me to keep this function or just leave a note in UPDATING.md

**Comment by mik-laj** [comment]
I'm on the phone.  I have no opinion now.  I need to check it when I'm on the computer.

**Review by potiuk — APPROVED** [review]

**Comment by kaxil** [comment]
FYI: This function was added in https://github.com/apache/airflow/commit/91900c995fa8fc373d88974a97cf931a14d7527e but was made redundant by https://github.com/apache/airflow/commit/28cfd2c541c12468b3e4f634545dfa31a77b0091

**Pull request merged**
