### PR TITLE
Add unit tests for EksCreateClusterTrigger and EksDeleteClusterTrigger

### PR DESCRIPTION
**Pull request by mateuslatrova**
Related: https://github.com/apache/airflow/issues/35442

This PR adds unit tests for the EksCreateClusterTrigger trigger from the Airflow AWS provider package.

### CODE REVIEW

**Comment by Taragolis** [comment]
You need to remove this line:

https://github.com/apache/airflow/blob/c434c6b98911d71f27910d7d30cf966462157612/tests/always/test_project_structure.py#L75

**Review by vincbeck — APPROVED** [review]
Other than @Taragolis comment, LGTM

**Review by dirrao — APPROVED** [review]
LGTM

**Comment by eladkal** [comment]
@mateuslatrova can you handle the above comment?

**Review by syedahsn — APPROVED** [review]

**Comment by mateuslatrova** [comment]
> @mateuslatrova can you handle the above comment?

Sorry I'm late! Just pushed the asked change.

**Comment by mateuslatrova** [comment]
I made a mistake because I thought this branch was already merged, so I had to reopen the PR. Here it is: https://github.com/apache/airflow/pull/39508

Now, it also has unit tests for the EksDeleteClusterTrigger class.

**Pull request closed without merging**
