### PR TITLE
[WIP][AIRFLOW-5307] Move BaseOperator to airflow.operators.base_operator

### PR DESCRIPTION
**Pull request by BasPH**
**WIP: working out a bug in the docs.**

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5307
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The BaseOperator currently resides in /airflow/models but has never been a database model, i.e. it is not stored in a database table. I suggest to move it to its logical place, the operators package.

To preserve backwards compatibility I import the BaseOperator in /airflow/models/\_\_init\_\_.py and raise a DeprecationWarning when imported from there. All references to airflow.models.BaseOperator have been removed and I suggest to remove backward compatibility in Airflow 2.0.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No test logic altered, only moved package names.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by kaxil** [comment]
Agree, this should be moved to operator. Can you rebase to the latest master?

**Comment by BasPH** [comment]
@kaxil i have some time this weekend, will check it out

**Comment by BasPH** [comment]
@kaxil given we now have the BashOperator in airflow.operators.bash, and the PythonOperator in airflow.operators.python, I'd like to place this in airflow.operators.base, while we're at it. What do you think?

**Comment by potiuk** [comment]
Hey @BasPH -> I think it's a good idea but you have to be aware that we are moving a lot of stuff out of models/__init__.py in #7596 and also lazy-loading it in models/__init__.py, so possibly it's better to rebase after that one is merged. We need to make sure backwards compatibility so we need too keep the old from models import BaseOperator and with lazy loading / PEP-562 we can get this  working.

**Comment by BasPH** [comment]
Okay, I'll wait for #7596 to be merged first.

**Comment by dimberman** [comment]
@BasPH I'm going to close this but please feel free to re-open if you feel this is still relevant.

**Pull request closed without merging**
