### PR TITLE
Update example_trigger_target_dag.py

### PR DESCRIPTION
**Pull request by brunolucatto**
[fix] Add provide_context=True in order to make kwargs receive the passed message

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by kaxil** [comment]
This has been intentionally removed by some awesome work from @Fokko https://github.com/apache/airflow/pull/5990

**Comment by brunolucatto** [comment]
I understand it was intentionally removed, but without it, the example is not working on my airflow. I was really confused since two weeks ago it worked, so I went to the git page and saw these changes. Then, I tried adding it again and it solved the case.

I don't know if this works in other circumstances, but it should definitely be double-checked.

**Comment by kaxil** [comment]
Are you installing Airflow from master? Or just using DAGs?

**Comment by brunolucatto** [comment]
I did not install airflow, I have been using it as a tool at work, making DAGs. Actually, I was looking at these examples because I am a beginner, so it really gave me a hard time to figure out what was wrong.

**Comment by kaxil** [comment]
I understand the confusion. You should be checking the example DAGs of the version of Airflow you have installed. For example if you have Airflow 1.10.5 installed, you should look at https://github.com/apache/airflow/tree/1.10.5/airflow/example_dags

**Pull request closed without merging**
