### PR TITLE
[AIRFLOW-4891] Extend list of pylint good-names

### PR DESCRIPTION
**Pull request by turbaszek**
I would like to propose further extension of pylint good-names:
- `v` used when iterating :`for k, v in dictionary.items():`
- `ds` and `ts` used in templates (https://airflow.apache.org/macros.html)

### CODE REVIEW

**Comment by turbaszek** [comment]
@mik-laj @potiuk @ashb what are your thoughts?

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
Are there any others do you think? Should we wait/keep this Jira open for a while?

**Comment by turbaszek** [comment]
Here is a list of top 10 invalid names with number of occurrences:
```
  12  Variable name "t2" doesn't conform to snake_case naming style (invalid-name)
  13  Variable name "ts" doesn't conform to snake_case naming style (invalid-name)
  15  Variable name "df" doesn't conform to snake_case naming style (invalid-name)
  17  Variable name "v" doesn't conform to snake_case naming style (invalid-name)
  19  Variable name "p" doesn't conform to snake_case naming style (invalid-name)
  22  Variable name "b" doesn't conform to snake_case naming style (invalid-name)
  23  Variable name "m" doesn't conform to snake_case naming style (invalid-name)
  24  Variable name "c" doesn't conform to snake_case naming style (invalid-name)
  26  Variable name "s" doesn't conform to snake_case naming style (invalid-name)
  39  Variable name "d" doesn't conform to snake_case naming style (invalid-name)
 107  Variable name "t" doesn't conform to snake_case naming style (invalid-name)
```

So I would suggest also `df` as it's popular name for `pd.DataFrame`.

**Comment by ashb** [comment]
Yes to `df`. `ts` = timestamp?

What are the uses of `t`? That's probably `task` isn't it? It may actually be clearer to use `task` instead of `t`. Not sure why I feel different about that var name... :D

**Comment by turbaszek** [comment]
From macro documentation:

> {{ ts }} | same as execution_date.isoformat(). Example: 2018-01-01T00:00:00+00:00

You are right that `t` is often used in tests for task / sensor / operator. But there are also other usages like `t = MySQLdb.constants.FIELD_TYPE` so I would consider `t` too ambiguous.

**Review by potiuk — COMMENTED** [review]
OK. Also I think df is the only from the list that should be OK

**Pull request merged**
