### PR TITLE
[AIRFLOW-6129] Fix pylint errors

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

There ia failure in CRON job https://travis-ci.org/apache/airflow/jobs/618832806?utm_medium=notification&utm_source=email where from-the-scratch build failed with "no-member". It's not clear why it did not happen in the main build (but likely due to some dependencies updated in from-the-scratch build. It's easy to fix so let's fix it.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6129

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Review by feluelle — APPROVED** [review]

**Comment by XD-DENG** [comment]
Hi @potiuk @kaxil @feluelle 
The error `Instance of '' has no 'Object' member (no-member)` in `tests/hooks/test_s3_hook.py` seems back again. This is the the CI build failure of the latest commit in master branch at this moment: https://travis-ci.org/apache/airflow/jobs/619940069?utm_medium=notification&utm_source=github_status

Meaning the fix introduced in this PR may not be working?

**Comment by potiuk** [comment]
It's interesting it appeared in the latest CRON job but does not happen in master build nor in PRs @XD-DENG . Let's see if it happens tonight in the CRON job as well and see if we can reproduce it. Might be still caused by some from-the-scratch dependencies on CRON job.

**Comment by potiuk** [comment]
Interestingly enough. The CRON build has failed again: https://travis-ci.org/apache/airflow/jobs/620450717?utm_medium=notification&utm_source=email 

It must be due to refreshed pylint (or some pylint deps) plugin. I will take a look and see what's different in CRON build vs. master /PR. 

BTW. It's good to have such an early warning system it seems where we rebuild/rerun everything from the scratch. We have time to react before it hits everyone.

**Comment by potiuk** [comment]
Surprisingly it stopped happening :).

**Pull request merged**
