### PR TITLE
Improve modules import in Airflow providers by some of them into a type-checking block

### PR DESCRIPTION
**Pull request by hussein-awala**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I wish we had other mechanism for that :)

**Comment by potiuk** [comment]
BTW. This calls for automation and pre-commit. I think we should ba able to have an AST pre-commit to verify if an import is only used in Type Hints (and ask to move them to `if TYPE_CHECKING`) - and the other way round - we could check if anything that is in `TYPE_CHECKING` is actually only used for type hints (cc: @uranusjr ).

**Comment by hussein-awala** [comment]
I will add some pre-commits after merging the different PRs. I already prepared some of them including this one.

**Comment by potiuk** [comment]
> I will add some pre-commits after merging the different PRs. I already prepared some of them including this one.

I figured you are not doing it manually :)

**Comment by hussein-awala** [comment]
I will try to split it in smaller PRs starting with the bigger providers (k8S, AWS, GCP, ...).

**Comment by hussein-awala** [comment]
I created:
- https://github.com/apache/airflow/pull/33780 for amazon provider
- https://github.com/apache/airflow/pull/33781 for kubernetes provider
- https://github.com/apache/airflow/pull/33783 for google provider

and I kept this one for the rest.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Providers are safe to merge since we do not cherry-pick them.

**Pull request merged**
