### PR TITLE
Use unittest.mock instead of backported mock library

### PR DESCRIPTION
**Pull request by kaxil**
mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.

https://docs.python.org/3/library/unittest.mock.html

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
~Remove it from setup.py too?~

Turns out we removed it from setup.py in 2019! #5292

I wonder how it was even getting pulled in? I guess an indirect dependency from something else.

**Comment by ashb** [comment]
```
>       assert 'pidfile' in mock_celery_worker.call_args.kwargs
E       AssertionError: assert 'pidfile' in kwargs
E        +  where kwargs = call(autoscale=None, concurrency=16, hostname=None, loglevel='INFO', optimization='fair', pidfile='test_pid_file', pool='prefork', queues='default').kwargs
E        +    where call(autoscale=None, concurrency=16, hostname=None, loglevel='INFO', optimization='fair', pidfile='test_pid_file', pool='prefork', queues='default') = <MagicMock name='Worker' id='140524089964136'>.call_args
```

Looks like a slight API change in mock vs unittest.mock that we'll need to fix in our tests.

**Review by dimberman — APPROVED** [review]
This PR makes my head hurt. Thank you for what I hope wasn't too painful of a process

**Comment by kaxil** [comment]
> ```
> >       assert 'pidfile' in mock_celery_worker.call_args.kwargs
> E       AssertionError: assert 'pidfile' in kwargs
> E        +  where kwargs = call(autoscale=None, concurrency=16, hostname=None, loglevel='INFO', optimization='fair', pidfile='test_pid_file', pool='prefork', queues='default').kwargs
> E        +    where call(autoscale=None, concurrency=16, hostname=None, loglevel='INFO', optimization='fair', pidfile='test_pid_file', pool='prefork', queues='default') = <MagicMock name='Worker' id='140524089964136'>.call_args
> ```
> 
> Looks like a slight API change in mock vs unittest.mock that we'll need to fix in our tests.

Updated

**Pull request merged**
