### PR TITLE
[AIRFLOW-5448] Handle istio-proxy for Kubernetes Executor

### PR DESCRIPTION
**Pull request by sjmiller609**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-5448) issues and references them in the PR title.

### Description

- [x] Here are some details about my PR:

Istio service mesh is not compatible by default with Kubernetes Jobs. The normal behavior is that a Job will be started, get an istio-proxy sidecar attached to it via the istio mutating webhook, run until completion, then the 'main' container in the pod stops, but istio-proxy hangs around indefinitely. This applies to the Kubernetes Executor.

Very recently, Istio implemented an endpoint that can be called to cleanly exit the proxy, specifically designed for this use case.

explanation: https://github.com/istio/istio/issues/15041
istio PR implementing it: https://github.com/istio/istio/pull/15406
Astronomer will make a contribution to handle cleanly exit the istio-proxy by default. This will help Astronomer and other Airflow users making use of the Kubernetes Executor in combination with Istio.

Here a PR I am closing in favor of contributing to upstream: https://github.com/astronomer/airflow/pull/47

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

 - [x] All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by mik-laj** [comment]
Hello,

I created a GKE instance with Istio using following command:
```bash
gcloud beta container \
--project "polidea-airflow" clusters create "test-kamil-istio" \
--zone "us-central1-a" \
--no-enable-basic-auth \
--machine-type "g1-small" \
--num-nodes "1" \
--addons HorizontalPodAutoscaling,HttpLoadBalancing,Istio \
--istio-config auth=MTLS_PERMISSIVE
```
In next step, I created a DAG with following task:
```python
    pod_task = GKEPodOperator(
        task_id="pod_task",
        project_id=GCP_PROJECT_ID,
        location=GCP_LOCATION,
        cluster_name=CLUSTER_NAME,
        namespace="default",
        image="perl",
        name="test-pod",
    )

    pod_task_xcom = GKEPodOperator(
        task_id="pod_task_xcom",
        project_id=GCP_PROJECT_ID,
        location=GCP_LOCATION,
        cluster_name=CLUSTER_NAME,
        do_xcom_push=True,
        namespace="default",
        image="alpine",
        cmds=["sh", "-c", 'mkdir -p /airflow/xcom/;echo \'[1,2,3,4]\' > /airflow/xcom/return.json'],
        name="test-pod-xcom",
    )
```
```log
[2019-09-10 06:32:54,415] {pod_launcher.py:125} INFO - Event: test-pod-f2017f38 had an event of type Pending
[2019-09-10 06:32:55,688] {pod_launcher.py:125} INFO - Event: test-pod-f2017f38 had an event of type Pending
[2019-09-10 06:32:56,839] {pod_launcher.py:125} INFO - Event: test-pod-f2017f38 had an event of type Running
[2019-09-10 06:32:57,069] {pod_launcher.py:108} INFO - b'\n'
[2019-09-10 06:32:57,071] {pod_launcher.py:108} INFO - b'Loading DB routines from perl5db.pl version 1.55\n'
[2019-09-10 06:32:57,072] {pod_launcher.py:108} INFO - b'Editor support available.\n'
[2019-09-10 06:32:57,073] {pod_launcher.py:108} INFO - b'\n'
[2019-09-10 06:32:57,074] {pod_launcher.py:108} INFO - b"Enter h or 'h h' for help, or 'man perldebug' for more help.\n"
[2019-09-10 06:32:57,074] {pod_launcher.py:108} INFO - b'\n'
[2019-09-10 06:32:57,075] {pod_launcher.py:108} INFO - b'main::(-e:1):\t0\n'
[2019-09-10 06:32:57,078] {pod_launcher.py:108} INFO - b'  DB<1> '
[2019-09-10 06:32:57,245] {pod_launcher.py:125} INFO - Event: test-pod-f2017f38 had an event of type Succeeded
[2019-09-10 06:32:57,245] {pod_launcher.py:215} INFO - Event with job id test-pod-f2017f38 Succeeded
[2019-09-10 06:32:57,387] {pod_launcher.py:125} INFO - Event: test-pod-f2017f38 had an event of type Succeeded
[2019-09-10 06:32:57,387] {pod_launcher.py:215} INFO - Event with job id test-pod-f2017f38 Succeeded
```
```log
[2019-09-10 06:33:19,577] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Pending
[2019-09-10 06:33:20,724] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Pending
[2019-09-10 06:33:21,870] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Running
[2019-09-10 06:33:22,049] {pod_launcher.py:108} INFO - b''
[2019-09-10 06:33:22,841] {pod_launcher.py:197} INFO - Running command... cat /airflow/xcom/return.json

[2019-09-10 06:33:22,973] {pod_launcher.py:197} INFO - Running command... kill -s SIGINT 1

[2019-09-10 06:33:23,165] {pod_launcher.py:115} INFO - [1,2,3,4]

[2019-09-10 06:33:23,281] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Running
[2019-09-10 06:33:23,281] {pod_launcher.py:118} INFO - Pod test-pod-xcom-b0184129 has state running
[2019-09-10 06:33:25,441] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Succeeded
[2019-09-10 06:33:25,442] {pod_launcher.py:215} INFO - Event with job id test-pod-xcom-b0184129 Succeeded
[2019-09-10 06:33:25,580] {pod_launcher.py:125} INFO - Event: test-pod-xcom-b0184129 had an event of type Succeeded
[2019-09-10 06:33:25,580] {pod_launcher.py:215} INFO - Event with job id test-pod-xcom-b0184129 Succeeded
```
My tasks are done correctly. Could you provide more information that will allow me to repeat this problem? I would like to prepare system tests to prevent regression.

**Comment by sjmiller609** [comment]
@mik-laj Thank you so much for your continued help on this contribution. Can you help me disambiguate something? The intention of this PR is to handle istio for any operator when running using KubernetesExecutor, and the executor is running in a cluster with Istio. Astronomer has discovered that the current behavior is that the task's pods will not be cleaned up.

That being said, I think Istio ought to be handled for all similar situations, for example any Kubernetes pod operator, including the ones you have shown in your example. I am willing to contribute those modifications in addition to this modification, and any advice you give is greatly appreciated.

My plan going forward is the following:
- back port this change to Airflow 1.10.4 to meet an immediate business need on Astronomer's end
- contribute to all pod operators to handle Istio on airflow 2

**Comment by mik-laj** [comment]
Oh. So I'll try to test this PR with Kubernetes Executor. However, I do not understand why this problem does not occur when I use KubernetesPodOperator. Logic of  KubernetesExecutor and KubernetesPodOperator is shared in airflow/kubernetes/pod_launcher.py file. In my opinion, this should not make a difference.

**Comment by mik-laj** [comment]
I would like to add that there is only one difference between KubernetesPodOperator and GKEPodOperator. GKEPodOperator provides authorization for the cluster and then shares all logic with KubernetesPodOperator.

**Comment by sjmiller609** [comment]
> I would like to add that there is only one difference between KubernetesPodOperator and GKEPodOperator. GKEPodOperator provides authorization for the cluster and then shares all logic with KubernetesPodOperator.

Oh perfect, I did not realize that. Also, I now understand that you are attempting to reproduce the original problem in order to make regression tests. I am interested to know where you would put these tests, so that I might contribute such tests in the future if I do something like this.

To check if the problem is occurring in a current version of Airflow, you should look from the kubernetes' perspective. I diagnose it by using airflow on kubernetes with the kubernetes executor. Then I make a DAG using the bash operator, and set the dag to run. I watch the task begin / the pod for the task being created with the command ```kubectl get pods --all-namespaces``` I can see the task come up, and kubernetes will show the pod at 1 more container than usual (in my case, two  containers - the task container and istio-proxy). The task will complete, then the container goes down. The issue is that the pod is not cleaned up because the other container, istio-proxy does not stop. That can be witnessed with another ```kubectl get pods --all-namespaces```, where you will see the task pod at 1/2 containers (because the task stopped but istio-proxy was not cleaned up)

**Comment by mik-laj** [comment]
@sjmiller609 
GKE system test: 
https://github.com/apache/airflow/blob/master/tests/gcp/operators/test_kubernetes_engine_system.py
It run the example DAG. This is available here: 
https://github.com/apache/airflow/blob/master/airflow/gcp/example_dags/example_kubernetes_engine.py

I already have a cluster from Istio, so I will try to reproduce this problem in a moment.  Is your cluster in on-premise or in the cloud?

**Comment by sjmiller609** [comment]
I am running both on GKE and locally on my laptop using docker-kubernetes for mac

**Comment by sjmiller609** [comment]
I'm working on system testing this. I have noticed that the kube executor calls run_pod_async on the PodLauncher class, which means that _monitor_pod is not used.. which means that this code is not executed. I'm going to fix these issues, then re-open.

**Pull request closed without merging**
