### PR TITLE
Sync `v2-1-stable` and `v2-1-test` to release `2.1.4`

### PR DESCRIPTION
**Pull request by kaxil**
Just need an approval, so that I can push to `v2-1-stable` which is a protected branch

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by eladkal** [comment]
I think https://github.com/apache/airflow/pull/17269 was missed from releases

**Comment by potiuk** [comment]
> I think #17269 was missed from releases

Why do you think it should be there @eladkal :)?  We do not cherry-pick all bugfixes to "patchlevel" releases, it's always risky - I think 2.1.4 is mostly about stabilising 2.1.3 (which had a number of stability issues) + some doc-only changes that are mostly clarifications, guiding our users better, improvements in communication (generally 0 or low-risk changes).  The #17269 is also some new behaviour rather than bugfix IMHO so it should go to 2.2

**Comment by eladkal** [comment]
> Why do you think it should be there @eladkal :)? We do not cherry-pick all bugfixes to "patchlevel" releases, it's always risky - I think 2.1.4 is mostly about stabilising 2.1.3 (which had a number of stability issues) + some doc-only changes that are mostly clarifications, guiding our users better, improvements in communication (generally 0 or low-risk changes). The #17269 is also some new behaviour rather than bugfix IMHO so it should go to 2.2

mostly as this seem to be a bug fix for https://github.com/apache/airflow/issues/18102 but I'm OK with it waiting for 2.2 as it should follow shortly

**Comment by potiuk** [comment]
Woohoo!

**Pull request merged**
