### PR TITLE
[AIRFLOW-6751] Pin Werkzeug < 1.0.0 release - 1.0.0 is not compatible

### PR DESCRIPTION
**Pull request by potiuk**
---
Issue link: [AIRFLOW-6751](https://issues.apache.org/jira/browse/AIRFLOW-6751)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
I'd like to try upgrading rather then pinning first. (I'll make the pr now)

**Comment by potiuk** [comment]
Might be solved differently https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1581028413361000

**Comment by ashb** [comment]
For the 1-10 release branch at least we can't upgrade: Flask-Admin hasn't yet published the fix https://github.com/flask-admin/flask-admin/issues/1951

**Comment by ashb** [comment]
Lets merge this one and push it out, then I'll look at unpinning/upgrading all the deps as needed on master to update it

**Comment by potiuk** [comment]
> For the 1-10 release branch at least we can't upgrade: Flask-Admin hasn't yet published the fix [flask-admin/flask-admin#1951](https://github.com/flask-admin/flask-admin/issues/1951)

I think no matter what, it's safer to downgrade werkzeug for 1.10.x rather than upgrade flask.

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Oh FAB is broken too because of it's dep on `flask-babel<1`

**Comment by tooptoop4** [comment]
just missed 1.10.8 release :(

**Comment by ddelange** [comment]
ref https://github.com/pallets/flask/pull/3489

```
$ pipgrip --tree -vvv flask_admin

flask-admin (1.5.4)
├── flask>=0.7 (1.1.1)
│   ├── click>=5.1 (7.0)
│   ├── itsdangerous>=0.24 (1.1.0)
│   ├── jinja2>=2.10.1 (2.11.1)
│   │   └── markupsafe>=0.23 (1.1.1)
│   └── werkzeug>=0.15 (1.0.0)
└── wtforms (2.2.1)
```

**Comment by davidism** [comment]
We're planning to add some imports back compatibility. Sorry for the issue and thanks for your patience.

If you have any insight into which dependencies are raising deprecation warnings with werkzeug 0.16.1, that would be really helpful.

**Pull request merged**
