### PR TITLE
[AIRFLOW-2686] Fix Default Variables not base on default_timezone

### PR DESCRIPTION
**Pull request by lxneng**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2686

### Description
- [x] I have updated airflow.cfg `default_timezone`, but default variable is still base UTC timezone,
    update func:`TaskInstance.get_template_context` in model.py, convert datetime variables to default timezone

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by lxneng** [comment]
@Fokko can u pls take a look this PR. 

 I think this is a bug, when I change `default_timezone` to `Asia/Shanghai`,  tasks will run at correct time, but the template default variables still base on `UTC` timezone.  i think expectation is base on `default_time`, so i've made this change.

**Comment by Fokko** [comment]
I would expect that the `self.execution_date` already has a timezone. @bolkedebruin any thoughts?

**Comment by bolkedebruin** [comment]
execution_date is timezone aware, but is in UTC. However I dont think this is the right change: users should convert an execution_date themselves to a specific timezone. So an jinja2 filter / function is a better option. This way we make sure the user always knows if he is working in UTC or Local Time.

**Comment by lxneng** [comment]
Agree with @Fokko , That would be mush better.

**Pull request closed without merging**
