### PR TITLE
Rename dataset as asset in UI

### PR DESCRIPTION
**Pull request by Lee-W**
As part of https://github.com/apache/airflow/issues/42307

---

Rename ``DagRunTriggeredByType.DATASET`` as ``DagRunTriggeredByType.ASSET`` and all the name ``dataset`` in all the UI components to ``asset``.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by bbovenzi — CHANGES_REQUESTED** [review]
We're missing `.next-dataset-triggered` in `main.css` and `appbuilder.add_link(name="Datasets", href="Airflow.datasets")` in `init_appbuilder_links.py`

**Review by bbovenzi — APPROVED** [review]

**Review by jscheffl — COMMENTED** [review]
Mhm, I am not good with this PR. We will "throw away" the old UI once we have the New ready. Until then we need to maintain old and new UI.

If we now mass-rename the legacy UI parts for Dataset->Asset... the legacy UI wiull diverge a lot from the 2.x line. This means any patch/contribution would need to be adjusted not to "by accident" convert Dataset to Asset in the 2.x line.

Could we leave the legacy UI un-touched and rename just the new UI? because:
1) Maintenance on the legacy will be harder if the legacy diverges
2) Is is a un-needed change if the UI anyway will be removed (soon)

**Comment by Lee-W** [comment]
> Mhm, I am not good with this PR. We will "throw away" the old UI once we have the New ready. Until then we need to maintain old and new UI.
> 
> If we now mass-rename the legacy UI parts for Dataset->Asset... the legacy UI wiull diverge a lot from the 2.x line. This means any patch/contribution would need to be adjusted not to "by accident" convert Dataset to Asset in the 2.x line.
> 
> Could we leave the legacy UI un-touched and rename just the new UI? because:
> 
>     1. Maintenance on the legacy will be harder if the legacy diverges
> 
>     2. Is is a un-needed change if the UI anyway will be removed (soon)

I'm unsure 🤔 The concept of datasets no longer exists in the main branch, so keeping these dataset things in the main branch seems odd. I'm uncertain whether we anticipate many changes to the UI side in version 2.x, but even if so, those changes could probably go to the 2.x branch. But I'm not heavily contributing to the UI end of Airflow, so I would love to know what @bbovenzi thinks.

**Comment by Lee-W** [comment]
> Would the backend not also have issues with backporting changes to 2.10/11?

Yep, whenever I need to do that kind of change, I just did them in separate branch instead of just backporting the merged commit.

> I do agree that much of this work isn't necessary because we will be removing the `/api_connexion`, and `/www` directories. It wasn't just confusing to mix "asset" and "datasets" in the codebase, it did introduce a few bugs. So I am ok with swapping everything over for consistency's sake.

Thanks for confirming. If it actually introduced bugs, I think it's better to just change it in main. I'll go ahead and merge it

**Pull request merged**
