### PR TITLE
TimeSensor should consider the default_timezone config

### LINKED ISSUE #9609: TimeSensor triggers immediately when used over midnight (UTC)
**Apache Airflow version**: 1.10.10 (issue exists in current master as well)

**Environment**: does not seem relevant

**What happened**:

The TimeSensor does trigger if the current time is later than the defined trigger time. Looking at the [source code](https://github.com/apache/airflow/blob/master/airflow/sensors/time_sensor.py), the trigger rule is defined as
```
return timezone.utcnow().time() > self.target_time
```
This leads to problems when the DAG runs over midnight UTC. For example, suppose the following DAG:

```
with DAG('foo', 
    default_args={'start_date': datetime(2020, 7, 1, tzinfo=pendulum.timezone("Europe/Berlin"))}, 
    schedule_interval="0 0 * * *") as dag:

    # in summer, Europe/Berlin is two hours after UTC, hence: 
    time_04h00_local = TimeSensor(task_id="time_01h30", target_time=time(hour=2, minute=00))
```

This DAG will be triggered at 22:00 UTC. Then, according to the trigger rule:
```
22:00 UTC > 2:00 UTC
```
Hence, the TimeSensor will be triggered immediately. 

**What you expected to happen**:

The TimeSensor should trigger at the following day if `target_time < next_execution_date.time()`

**Possible workarounds**:

One can always use the TimeDeltaSensor to archive similar effects. This does result in code that is not as readable, though.

### PR DESCRIPTION
**Pull request by 22quinn**
Fixes #9609

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by kaxil — APPROVED** [review]
Can you please rebase on the master branch to remove conflicts?

**Comment by zikun** [comment]
> Can you please rebase on the master branch to remove conflicts?

Done. Thanks for the review.

Do you mind also taking a look at #9697? It offers idempotence for `target_time`.

**Comment by freget** [comment]
Cool, thank you!

**Comment by wangze999999** [comment]
i see



---Original---

**Comment by JeffryMAC** [comment]
I have two questions:
1. When this is released?
2. If someone is writing timezone aware dag. it might be very confusing when the TimeSensor works with default setting that can't be change. I think to make this change complete maybe it should take first the Timezone from Dag if given otherwise the default from the airflow settings.

**Comment by zikun** [comment]
>
>     2. If someone is writing timezone aware dag. it might be very confusing when the TimeSensor works with default setting that can't be change. I think to make this change complete maybe it should take first the Timezone from Dag if given otherwise the default from the airflow settings.

Good point. I was not aware of the existence of timezone-aware dags. Just created another PR to achieve this: #9882

**Pull request merged**
