### PR TITLE
Consolidate environment variable calculation in ShellParams in Breeze

### PR DESCRIPTION
**Pull request by potiuk**
Historically (when moved from Bash) the environment variables set for docker or docker-compose commands were set in a few places - some were set directly in the code, some were retrieved from shell params and eventually some were set from default values or hardcoded constants. This all happened in various models and it was scattered around the code and it was difficult to grasp what was going on.

This PR consolidates it so that all variables are set in ShellParams object.

* the attributes have been reviewed and None/"" default values were set where needed
* the attributes were sorted
* calculation of dynamic properties was moved to ShellParams
* missing properties were added to ShellParams, so that all variables have corresponding properties
* the get_env_variables_for_docker_commands is now a method in ShellParams object, mapping is done explicitly from self.ATTRIBUTE and default values if not set are set in this single place if not set in case the variables are are retrieved from elsewhere
* we use ShellParams in all places where we execute docker commands (we used BuildCiParams) sometimes needlessly
* tests are added to cover the "attribute" + "incoming env var" to the env vars passed to Docker Compose/Docker

Most importantly the docker and docker-compose env files are now automatically generated and git-ignored so that we only need to maintain the list of variables to pass in a single plase - in ShellParams `env_variables_for_docker_commands` method.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
This is a small follow-up after #35768 - this time not about --build-arg generation by breeze but about env variables passed to docker-compose/docker. The way it was done was quite a bit complex  - and coming from the previous Bash implementation. This is I think the last remnant of the old Bash approach in Breeze's Python code :). We still have a few scripts in the container, but I think that one was the last thing that resembled the Bash version of Breeze.

cc: @Bowrna @edithturn :D

**Comment by potiuk** [comment]
BTW, I am going to separate out small part of it - fixes to pre-commit attempting to upgrade itself in a few pre-commits (which slowed them down and made it impossible to run them in the plain without network)

**Comment by potiuk** [comment]
BTW. This one will make it SO MUCH EASIER to understand and add new variables if we need to :)

**Review by hussein-awala — APPROVED** [review]
Looks good

**Review by vincbeck — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Review by amoghrajesh — APPROVED** [review]
LGTM

**Review by Taragolis — APPROVED** [review]

**Comment by potiuk** [comment]
Actually - I made it even better (see the latest version). I also figured how to do it so that we do not have to keep the separate lists of variables to pass in neither docker-compose base.yaml nor in docker.env - we are now generating the files with the list of variables for both docker and docker-compose.

After this change there is only one place where you need to add env variable to pass to docker (ShellParamss `env_variables_for_docker_commamds` - which will make it very straightforward on how to extend the functionality of breeze passing variable to container.

**Review by utkarsharma2 — APPROVED** [review]
It looks good to me. 👍

**Pull request merged**
