### PR TITLE
[AIRFLOW-3618] - Fix models.connection.Connection get_hook function

### PR DESCRIPTION
**Pull request by griff122**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-3618

### Description

- [x] The airflow.models.connection.Connection class function get_hook did not work as expected. The `conn_type` was not guaranteed to be lower case, and the get_hook function expected all lowercase type names. By updating the code so that the conditionals used `self.conn_type.lower()` instead of just `self.conn_type`, we can now make sure that the conditionals match the expected. 

For example:
```
>>> import airflow
>>> from airflow.hooks.base_hook import BaseHook
>>> airflow.__version__
'1.10.1'
>>> conn = BaseHook.get_connection('test_local_mysql')
[2019-01-02 11:36:15,530] {base_hook.py:83} INFO - Using connection to: localhost
>>> conn.conn_type
'MySQL'
>>> type(conn.get_hook())
<class 'NoneType'>
>>> conn.conn_type = conn.conn_type.lower()
>>> conn.conn_type
'mysql'
>>> type(conn.get_hook())
<class 'airflow.hooks.mysql_hook.MySqlHook'>
```

### Tests

- [x] Does not need tests as it is updating existing functionality which should already have test associated.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] No new documentation is needed as the change is a bug fix which does not change the expected functionality of the function `Connection.get_hook`.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by jgao54** [comment]
All the conn type are defined [here](https://github.com/apache/incubator-airflow/blob/master/airflow/models/connection.py#L53-L92) and they are all lower case consistently. We don't use .lower() because these conn types are hard-coded into the connection.py module.

I noticed that in your JIRA it shows `MySQL` instead, perhaps it's a custom created connection type?

**Comment by griff122** [comment]
@jgao54  - Ahhh, you are correct! I add the airflow connections from the command line during setup:
```
airflow connections --add --conn_id test_local_mysql --conn_type "MySQL" ...
```
I was matching the name that was found on the UI. 

After updating the connection add command to use `--conn_type "mysql"`, it now works as expected:
```
>>> from airflow.hooks.base_hook import BaseHook
>>> conn = BaseHook.get_connection('test_local_mysql')
[2019-01-03 14:38:37,639] {base_hook.py:83} INFO - Using connection to: localhost
>>> conn.conn_type
'mysql'
>>> type(conn.get_hook())
<class 'airflow.hooks.mysql_hook.MySqlHook'>
```

Thanks for that! I was wondering why no one else was seeing this issue.

**Comment by jgao54** [comment]
great! it does look like we are short of an input validation check for CLI that could have made this a bit easier to detect. contributions welcome :)

**Comment by griff122** [comment]
Absolutely, that is a great idea!

**Pull request closed without merging**
