### PR TITLE
[AIRFLOW-6402] fix ssh_operator default value

### PR DESCRIPTION
**Pull request by ohadmata**
[AIRFLOW-6402] https://issues.apache.org/jira/browse/AIRFLOW-6402

Fix for ssh operator default value.
Right now I am getting Nonetype Exception (1.10.7)

### CODE REVIEW

**Comment by kaxil** [comment]
Can you also add a test for it so this can be avoided in future, please?

Test for this operator are at: https://github.com/apache/airflow/blob/master/tests/contrib/operators/test_ssh_operator.py

**Comment by dstandish** [comment]
this operator raises exception if no command is provided:
https://github.com/apache/airflow/blob/49845787feda26681456a56bf3fa11d3a1cb5cdf/airflow/contrib/operators/ssh_operator.py#L108-L109

does it make sense to just pass empty string `super().__init__(command='')` when subclassing?

seems like it would make sense to make `command` not optional i.e. remove the default value of `None`

**Comment by kaxil** [comment]
> this operator raises exception if no command is provided:
> https://github.com/apache/airflow/blob/49845787feda26681456a56bf3fa11d3a1cb5cdf/airflow/contrib/operators/ssh_operator.py#L108-L109
> 
> does it make sense to just pass empty string `super().__init__(command='')` when subclassing?
> 
> seems like it would make sense to make `command` not optional i.e. remove the default value of `None`

Yes, I don't see why someone would use SSHOperator without a "command".

**Comment by CRX-DS** [comment]
Should this TASK work now:
t1 = SSHOperator(
 task_id='t1',
 bash_command='echo t1_finished >> /usr/local/airflow/t1.log',
 ssh_conn_id='myconnection1',
 dag=dag
)

**Pull request closed without merging**
