### PR TITLE
Fix image cache optimizations - speeding up the build (#38442)

### PR DESCRIPTION
**Pull request by potiuk**
The recent refactors in workflows broke the way how cache had been used in the CI builds. This PR brings back the optimizations by using the cache and rebuilding it.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Second attempt on cache optimization restoring

**Comment by potiuk** [comment]
The reason it failed before in https://github.com/apache/airflow/pull/38468 was tht "build-images"  worfkflow used "self-hosted" runners to build images, but we should switch to "public" runner. This has been fixed in #38463

**Comment by potiuk** [comment]
Back green - this time with the **right** runner.

**Comment by potiuk** [comment]
Already approved before in #38442 - but this time with the righ `runs-on` in `build-image` workflow :) . Would love to get it in finally, to make it quite a bit faster to get the build runs.

**Comment by potiuk** [comment]
Already approved before in #38442 - but this time with the righ `runs-on` in `build-image` workflow :) . Would love to get it in finally, to make it quite a bit faster to get the build runs.

**Review by aritra24 — APPROVED** [review]

**Review by amoghrajesh — APPROVED** [review]

**Pull request merged**
