### PR TITLE
Fix incorrect cloudwatch and wasb taskhandler path in config template

### PR DESCRIPTION
**Pull request by ephraimbuddy**
CloudwatchTaskHandler and WasbTaskHandler were moved to their respective provider packages but their references at airflow_local_settings were not updated. This PR updates it

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
Hi @mik-laj, any ideas why this is failing on query count? What should I do to fix it?

**Comment by mik-laj** [comment]
I restarted the build. Let's check if the problem is transistent.

**Comment by potiuk** [comment]
Hey @ephraimbuddy - can you please rebase now? I believe it should work now

**Comment by potiuk** [comment]
trying it on my fork and I think I know how to fix it

**Comment by potiuk** [comment]
I pushed some fixes so it should work now. But it was rather strange (see the CC:)

**Comment by ephraimbuddy** [comment]
> I pushed some fixes so it should work now. But it was rather strange (see the CC:)

I got a merge conflict in a file you didn't edit which might help in understanding this issue:
```
Auto-merging scripts/ci/selective_tests.sh
CONFLICT (content): Merge conflict in scripts/ci/selective_tests.sh
```

**Comment by ephraimbuddy** [comment]
I want to close this and make a new pull request. I have messed up my local branch.

**Comment by mik-laj** [comment]
```
git reset --soft apache/master
git add -p airflow/config_templates/airflow_local_settings.py
git commit -m "Fix incorrect cloudwatch and wasb taskhandler path in config template"
git restore .
```
This should solve your problems.

**Pull request closed without merging**
