### PR TITLE
Fix git-sync-init resources indent

### LINKED ISSUE #35815: git-sync-init resources is too indented
### Official Helm Chart version

1.10.0

### Apache Airflow version

2.6.3

### Kubernetes Version

1.27.7

### Helm Chart configuration

values.yaml

```yaml
  # Git sync
  dags:
    gitSync:
      enabled: true

      repo: git@git/path/to/dag.git
      branch: main
      depth: 1
      # subpath within the repo where dags are located
      subPath: "dags"

      # the number of consecutive failures allowed before aborting
      maxFailures: 3

      # credentialsSecret: airflow-github-credentials
      sshKeySecret: airflow-ssh-secret

      knownHosts: |
        my-known-host
      # interval between git sync attempts in seconds
      # high values are more likely to cause DAGs to become out of sync between different components
      # low values cause more traffic to the remote git repository
      wait: 60
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 100Mi
```

### Docker Image customizations

_No response_

### What happened

Resources get too much indented. This is due to this line https://github.com/apache/airflow/blob/a794e0d020f70aca4a0d81b953402a92a430635e/chart/templates/_helpers.yaml#L253

### What you think should happen instead

A simple change should be made to indent one level up the tree

```yaml
resources: {{ toYaml .Values.dags.gitSync.resources | nindent 4 }} # not 6 
```

### How to reproduce

Inflate helm chart with given values.yaml and notice the extra indent everywhere gitsync is templated (e.g. scheduler)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  template:
    spec:
      initContainers:
        - name: git-sync-init
          resources: 
              limits:
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 100Mi
```

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by romsharon98**
Fixes: https://github.com/apache/airflow/issues/35815

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Could you add a test that reproduces the problem you have?

**Review by jscheffl — APPROVED** [review]
Change looks OK for me.
Tests on this are actually hard, because tests are made by parsing YAML and doing logic tests. This is "just cosmetic" and adjusts the indent. It removed un-needed spacing.
For me good to be merged.

**Review by eladkal — APPROVED** [review]
I agree with @jscheffl 
Wrong indent can be on every line its not so simple to cover.

WDYT @hussein-awala ?

**Comment by hussein-awala** [comment]
> I agree with @jscheffl 
> 
> Wrong indent can be on every line its not so simple to cover.
> 
> 
> 
> WDYT @hussein-awala ?

Okay, I will try to add a test later.

**Review by hussein-awala — APPROVED** [review]

**Pull request merged**
