### PR TITLE
Fix docker compose version to be the latest below 3, depends_on condition now works fine.

### PR DESCRIPTION
**Pull request by gabrielvieira37**
Fix docker compose version to handle ```depends_on``` feature called ```condition```. 
Versions above or equal 3 does not support this feature, it did not port healthcheck dependencies. 
Change version to to 2.4, the latest version below 3 that support that feature.

### CODE REVIEW

**Comment by potiuk** [comment]
According to  #15509   This feature is not documented in docker docs, but it works.

**Comment by potiuk** [comment]
@gabrielvieira37 - did you actually have any problems with this option or is just something you noticed/detected by some static checks?

**Comment by gabrielvieira37** [comment]
I had a problem when i tried to run the docker-compose.yml that the documentation links. When i tried to run it some errors showed up.
 The one that i have mentioned here is that the docker-compose at version 3 or above needs an array on ```depends_on``` command.
 Instead in airflow compose file it has a ```condition``` command  inside of ```depends_on``` to check its health which can only be performed on versions below 3.
The other problem was about the extension fields ```x-``` . It also needs to be version 3.7+ or 2.4+ .
So to solve all of those problems i changed the version to 2.4 and it worked fine :)

**Comment by potiuk** [comment]
cc: @mik-laj

**Comment by mik-laj** [comment]
What version of Docker compose do you have? Do you use `docker compose` or `docker-conpose` command?

We check the compliance of this file with the official Compose specification, which the version field marked as deprecated. Have you tried to delete this field?

**Comment by gabrielvieira37** [comment]
docker-compose version 1.25.0. I use ```docker-compose```.
The changes between 1.29.2 (current) and 1.25.0 did not handle those errors. 
I followed the airflow tutorial to use that docker-compose file. But it was not running at all.
When I read about it a little bit more I found out the issues that I am talking here.
Have you tried to run that docker-compose there ?

**Comment by mik-laj** [comment]
Docker-compose v1.29.1 is required now, becuase we use `depends_on` with `condition` field set to `service_completed_successfully` . See: https://github.com/apache/airflow/pull/16180

> Have you tried to run that docker-compose file there ?

I'm testing this file on my CI and I didn't notice any problem.
https://github.com/mik-laj/airflow-docker-compose-examples

**Comment by potiuk** [comment]
Hey @gabrielvieira37  - have you tested with 1.29.* ? Do you still see the problem? I am closing the issue now unless you come back and tell us that it did not work with 1.29 (I also tested with 1.29 and it works just fine).

**Pull request closed without merging**
