### PR TITLE
[AIRFLOW-2211] Rename hdfs_sensors.py to hdfs_sensor.py for consistency

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2211

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
       Rename hdfs_sensors.py to hdfs_sensor.py for consistency.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  no. The change is trivial.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@feng-tao Can you take a look at the flake8 violations? Cheers

**Comment by feng-tao** [comment]
thanks @Fokko . Will check today :)

**Comment by feng-tao** [comment]
hey @Fokko , I fix the flake8 error :). Would you mind taking a look?

**Review by Fokko — APPROVED** [review]
@feng-tao Thanks for pinging me. Merging right away. Cheers

**Comment by sekikn** [comment]
@feng-tao @Fokko This is incompatible change, so should we add an entry to UPDATING.md just like #3141?

**Comment by Fokko** [comment]
@feng-tao Good point, but this isn't necessary. Splitting the sensors files has been done after 1.8.2 and no release has been done since then, so this will only affect people which are building from master, but I guess they might expect some breaking changes now and then ;)

**Comment by sekikn** [comment]
@Fokko Sorry if I misunderstand, but airflow/contrib/sensors/hdfs_sensors.py seems to have been shipped with 1.8.0. So I thought this change is backward incompatible since its users from 1.8.0+ have to rewrite import statements in their code. Is this right?

**Comment by Fokko** [comment]
@sekikn Oops, I missed that. In that case this should be mentioned in the UPDATING.md.

**Comment by feng-tao** [comment]
@Fokko  and @sekikn , let me submit a pr today to add that info in the doc. Thanks for pointing out.

**Comment by sekikn** [comment]
@feng-tao @Fokko Thanks! :)

**Pull request closed without merging**
