### PR TITLE
[AIRFLOW-4828] Remove parameter python_version

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4828

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Part of AIP-3 Drop support for Python 2

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by OmerJog** [comment]
Shouldnt you target https://issues.apache.org/jira/browse/AIRFLOW-4828 ?

**Comment by zhongjiajie** [comment]
@OmerJog Oh, my bad. Thanks for you help

**Comment by kurtqq** [comment]
I don't think we should remove `python_version `parameter. 
If I run Airflow on Python 3.5 and want to run a task with Python 3.7 I need the `python_version `parameter. 
 Moreover in the future Python 4 will be released. Airflow will likely support both for a while....

I think the `python_version `needs to stay it's not unique to Python 2.7

I also think that if someone wants to run something with Python 2.7 with the `PythonVirtualenvOperator `he is more than welcome. There is no need to prevent the user from doing so.  Airflow can just remove the test for this so if something is not working it's the user problem.

**Comment by XD-DENG** [comment]
Agree with @kurtqq .

- To my understanding, [AIP-3 drop support Python 2] is to drop Py2 support to Airflow itself only.
- Minor version ("x" in "3.x") matters.

**Comment by zhongjiajie** [comment]
Will close it, thanks for the clarification @kurtqq @XD-DENG

**Comment by XD-DENG** [comment]
Thanks @zhongjiajie

**Pull request closed without merging**
