### PR TITLE
[AIRFLOW-4883] Add missing code lost during rebase of original commit

### PR DESCRIPTION
**Pull request by aoen**
Fix broken rebase in https://github.com/apache/airflow/pull/5605 and add unit tests to cover future breakages.

### CODE REVIEW

**Comment by msumit** [comment]
@aoen travis is red

**Comment by mik-laj** [comment]
Travis is broken on all build. We working on migration to other CI. 😿

**Comment by potiuk** [comment]
@aoen please rebase and push so that Travis can build it. Travis had a problem whole day yesterday.

**Comment by ashb** [comment]
Whoops I was a bit eager in merging this. I thought I saw a green from Travis but clearly not -- it's causing failures:

```
======================================================================
76) ERROR: test_kill_timed_out_processors_kill (tests.utils.test_dag_processing.TestDagFileProcessorManager)
----------------------------------------------------------------------
   Traceback (most recent call last):
    /usr/local/lib/python3.5/unittest/mock.py line 1159 in patched
      return func(*args, **keywargs)
    tests/utils/test_dag_processing.py line 195 in test_kill_timed_out_processors_kill
      mock_kill.assert_called()
    /usr/local/lib/python3.5/unittest/mock.py line 585 in __getattr__
      raise AttributeError(name)
   AttributeError: assert_called
```

I'll revert this to fix master builds.

**Comment by ashb** [comment]
Ah the problem is that `assert_called` is new in Py 3.6, and we still run against 3.5. I'll fix that

**Comment by tooptoop4** [comment]
@aoen can u look at https://stackoverflow.com/questions/57713394/airflow-scheduler-stuck ?

**Comment by aoen** [comment]
> @aoen can u look at https://stackoverflow.com/questions/57713394/airflow-scheduler-stuck ?

@tooptoop4 are you sure the failure is related to this PR? There is already a timeout inside of the DAG-parsing processes themselves, so I don't think this PR should cause issues unless there were cases before where the subprocesses to parse DAGs took a significant amount of time. If you can reproduce the issue and create a failing integration test that shows the problem is with this diff I can take a look.

**Pull request merged**
