### PR TITLE
Add Markdown linting to pre-commit 

### PR DESCRIPTION
**Pull request by jbampton**
- Add a basic config file
- Lint Markdown

https://www.npmjs.com/package/markdownlint-cli

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by turbaszek** [comment]
@jbampton can you please check if it would be possible to add this tool to pre-commit config? In this way, files will be linted before commit and this speeds up the feedback loop.

**Comment by potiuk** [comment]
Seems that this is even added in the original markdown lint repo - so should be super easy to add ot our .pre-commit-config.yml 

https://github.com/markdownlint/markdownlint/blob/master/.pre-commit-hooks.yaml

**Comment by potiuk** [comment]
Any news about pre-commit version of the markdown lint @jbampton ?

**Comment by mik-laj** [comment]
@jbampton do you need any help?

**Comment by jbampton** [comment]
Hey @turbaszek @potiuk @mik-laj this PR is ready for review 👍

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
Awesome! Can you create an issue about the remaining rules (similar to https://github.com/apache/airflow/issues/10742) ?

**Pull request merged**
