### PR TITLE
[AIRFLOW-2611] Fix wrong dag volume mount path for kubernetes executor

### PR DESCRIPTION
**Pull request by imroc**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2611

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
There are two way of syncing dags, pvc and git-sync, if set both
(dags_volume_claim and git_subpath), I won't get the mountPath what I
want. I think the priority of pvc should higher than git-sync, so I
think when dags_volume_claim is been set, the mountPath shuold not join the git_subpath.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by imroc** [comment]
@Fokko @bolkedebruin @kaxil  PTAL. If I set both *dags_volume_claim* and *git_subpath*, well, I won't get the volume mount path that I want ([see code](https://github.com/apache/incubator-airflow/blob/0f4d681f6f6e15acd1399dede146e75cb688d536/airflow/contrib/kubernetes/worker_configuration.py#L139)):
``` python
volume_mounts = [{
 'name': dags_volume_name,
 'mountPath': os.path.join(
 self.worker_airflow_dags,
 self.kube_config.git_subpath
 ),
 'readOnly': True
}, {
 'name': logs_volume_name,
 'mountPath': self.worker_airflow_logs
}]
```
There are two way of syncing dags, *pvc* and *git-sync*, I think if set both, the priority of *pvc* should higher than *git-sync*, because some beginers use the template config file at the beginning ([like this](https://github.com/apache/incubator-airflow/blob/0f4d681f6f6e15acd1399dede146e75cb688d536/scripts/ci/kubernetes/kube/configmaps.yaml#L184)), when they want to use pvc to mount dags, they may don't know they should remove the  *git_subpath* config. So I think when *dags_volume_claim* is set, the *mountPath*  shuold not join the *git_subpath*

**Comment by Fokko** [comment]
@dimberman PTAL

**Comment by dimberman** [comment]
@Fokko @imroc This LGTM. Perhaps we can also set an error if neither is set (if it's not handled somewhere else)? Thank you for finding this @imroc!

**Comment by kaxil** [comment]
Thanks, @imroc for your contribution and @dimberman  for reviewing it.

**Pull request closed without merging**
