### PR TITLE
Docs: Add templating info to TaskFlow tutorial

### PR DESCRIPTION
**Pull request by infused-kim**
Hi everyone,

I had some trouble with templating while I was transitioning from the old operator workflow to the Task Flow API.

So, I decided to write up what I learned in the documentation to make life a little easier for others.

Please let me know if you'd like any changes and I will be happy to rewrite it.

### CODE REVIEW

**Review by shahar1 — APPROVED** [review]

**Comment by shahar1** [comment]
Looks good, thanks!

**Comment by infused-kim** [comment]
Awesome. Thank you so much for reviewing it so quickly.

**Comment by potiuk** [comment]
Can you please cherry-pick it (with -x) to v2-10-test and make a "backport" PR @infused-kim ? This one looks like a good candidate to include in 2.10.3

**Comment by infused-kim** [comment]
@potiuk sure thing, I just did it here:
https://github.com/apache/airflow/pull/42992

**Pull request merged**
