### PR TITLE
Lift off upper bound for MarkupSafe

### LINKED ISSUE #19761: removing upper bound for markupsafe
### Description

Per discussion and guidance from #19753, opening this issue and PR https://github.com/apache/airflow/pull/19760 for review. Based on if all the tests pass, this could be reviewed further.

### Use case/motivation

Currently Jinja2 upper bound is jinja2>=2.10.1,<4 at https://github.com/apache/airflow/blob/main/setup.cfg#L121 as part of #16595

Jinja2 seems to require MarkupSafe>=2.0 at https://github.com/pallets/jinja/blob/main/setup.py#L6 as part of pallets/jinja@e2f673e

Based on this, is it feasible to consider updating upper bound in airflow for markupsafe>=1.1.1, <2.0 to allow 2.0 at https://github.com/apache/airflow/blob/main/setup.cfg#L126 ?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tsingh2k15**
Per discussion and guidance from #19753, opening this PR for review. Based on if all the tests pass, this could be reviewed further. Resolves #19761.

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
Everything seems to work well!

**Comment by tsingh2k15** [comment]
> Everything seems to work well!

Thank you for the review @uranusjr 
When this is merged, could I use a constraint file(likely an auto generated file) to start using this change in my installation scripts? I am curious to know when the constraint file could be available. Do I need to wait for a release?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Hey @tsingh2k15 - all looks good. In the "Build Images" job you can find that this build actually used 2.0.1 version:

https://github.com/apache/airflow/runs/4448089223?check_suite_focus=true#step:8:713

```
    Downloading MarkupSafe-2.0.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (31 kB)
```
I merged it.

> When this PR is merged to main, where could I find a constraint file to start using this change in my installation scripts? I am curious to understand when the constraint file would be available or how I can start using this change. Do I need to wait for a release?

When the PR is merged, the constraints will be automatically updated in the "constraint-main" branch of our repo - but ONLY if all tests pass (we have now WAY more stable build so this is likely to happen tonight). Also if there are many subsequent merges one after another, the build might get cancelled due to "concurrency" so sometimes it will take some time for the "green" build to push such new constraints. 

You can see the history of those constraint changes here: https://github.com/apache/airflow/commits/constraints-main

Once there you will be able to use it as described in https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html but use "constraints-main" rather than "constaints-2.2.2" as version.

But if you want to check it yourself it's very easy to download image from your PR build (we have all the images we used for CI in our registry) and run it locally with Breeze. The below should pull your image and start airlfow (loading default connections and example dags for easier testing). It should bring you a running airflow instance with webserver available at http://locahost:28080 (admin/admin):

```
./breeze start-airflow --github-image-id 13b0af1a2211f3e905d23bc5e1808307d577183d --load-example-dags --load-default-connections
```

(The image id you can find in logs of your build)

**Comment by potiuk** [comment]
But if you want to start using it for your own builds, you will need to wait for new release unfortunately as this is released airlfow package dependency (`MarkupSafe < 2.0.0`) and PIP will refuse to install this version with released airflow. Potentially, you could  install the package with ignoring the deps I think, but I do not think it is a good idea.

I marked both PRs to be integrated in 2.2.3 so it should be soon-ish (before/around Xmas I hope),

**Comment by tsingh2k15** [comment]
@potiuk This makes sense, thank you for the clarification. I may wait for the 2.2.3 release. 

I have tried the below instruction step, but it errored.
```Once there you will be able to use it as described in https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html but use "constraints-main" rather than "constraints-2.2.2" as version.```

Error:

```
ERROR: Cannot install apache-airflow==2.2.0 because these package versions have conflicting dependencies.
The conflict is caused by:
apache-airflow 2.2.0 depends on markupsafe<2.0 and >=1.1.1
 The user requested (constraint) markupsafe==2.0.1
```

I think it expects that the constraints file need to match with the release?

**Comment by tsingh2k15** [comment]
> 

This makes sense, thanks for the clarification!

**Comment by potiuk** [comment]
Oh yeah - as predicted : https://github.com/apache/airflow/commit/bb48bc35e5b16903a98beab1a299c7b242adba8f

**Comment by jedcunningham** [comment]
(Kicking this back to the 2.2.3 milestone as that's when this landed in a release)

**Pull request merged**
