### PR TITLE
[AIRFLOW-291] Add index for state in TI table

### PR DESCRIPTION
**Pull request by aoen**
Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-291

Testing Done:
- Existing unit tests should cover this
- Performance testing done on the Airbnb production DB

@jlowin @bolkedebruin @plypaul @mistercrunch

### CODE REVIEW

**Comment by plypaul** [comment]
LGTM - this has made a huge impact on our DB load.

**Comment by mistercrunch** [comment]
Migration script? If you haven't crafted one before I can show you tomorrow.

**Comment by bolkedebruin** [comment]
Migration script with a named index please (otherwise it will be impossible to change them afterwards)
- See also https://issues.apache.org/jira/browse/AIRFLOW-18

**Comment by aoen** [comment]
Good point, addressed.

**Comment by bolkedebruin** [comment]
In general LGTM, but a manual naming is not recommended, see https://media.readthedocs.org/pdf/alembic/latest/alembic.pdf chapter 5. So we might want to 'upgrade' our standard here to make it more future proof. For your consideration, I'm fine with merging it now.

**Comment by aoen** [comment]
That makes sense to me, we should move all of our indexes.

**Pull request closed without merging**
