### PR TITLE
[AIRFLOW-170] Add missing @apply_defaults

### PR DESCRIPTION
**Pull request by Firehed**
Adds missing `@apply_defaults` decorator, ensuring default config values flow through to the operator.

### CODE REVIEW

**Comment by artwr** [comment]
LGTM

**Comment by artwr** [comment]
Not sure about removing os, is it not needed? This seems like an unrelated change.

**Comment by Firehed** [comment]
@artwr Yeah, that shouldn't have been in the original commit. Bad copy-paste from a work-in-progress file elsewhere.

**Comment by criccomini** [comment]
LGTM as well

**Pull request merged**
