### PR TITLE
Resolve GlueJobTrigger serialization bug causing verbose to always be True

### PR DESCRIPTION
**Pull request by jimwbaldwin**
related: https://github.com/apache/airflow/issues/43620

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jimwbaldwin** [comment]
It doesn't test the functionality of what I wanted to test as it does not defer and thats where the bug is. Trying to figure out how to test something that has been deferred and then resumed.

**Review by vincbeck — APPROVED** [review]

**Comment by vincbeck** [comment]
Some static check failures, please [fix them](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst)

**Comment by jimwbaldwin** [comment]
Okay, I figured out how to find the bug we suspected and confirm it with a test. Please see the new `test_serialization` test in this PR.

> Some static check failures, please [fix them](https://github.com/apache/airflow/blob/main/contributing-docs/08_static_code_checks.rst)

I'll take a look at these soon.

**Comment by jimwbaldwin** [comment]
Static type checking looks fine after rebase.
image

**Review by gopidesupavan — APPROVED** [review]

**Comment by gopidesupavan** [comment]
LGTM :)

**Comment by gopidesupavan** [comment]
@jimwbaldwin Nice one, BTW congrats on your first contribution :)

**Comment by jimwbaldwin** [comment]
Still has static file checks issues. I'll check.

**Pull request merged**
