### PR TITLE
[AIRFLOW-6122] Rename CloudKMS service classes

### PR DESCRIPTION
**Pull request by michalslowikowski00**
Rename GoogleCloudKMSHook to CloudKMSHook

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6122
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by dimberman** [comment]
So... what benefit is there to changing this name? KMS is a GCP only feature, no?

**Comment by mik-laj** [comment]
We want to introduce naming conventions of operator names for GCP.  This was voted in AIP-21 / case #6. All rules is available in [GCP Service Airflow Integration Guide](https://docs.google.com/document/d/1_rTdJSLCt0eyrAylmmgYc3yZr-_h51fVlnvMmWqhCkY/edit?ts=5bb72dfd#heading=h.d8ueq9nksq0c) in `Naming conventions` chapter.

We have a plan that introduces conventions for all GCP integrations. Our main goal is to provide a uniform experience when using any GCP operator. It is worth adding that this name is unique because there are several KMS services, but only the service from Google is called "**Cloud**KMS". This change is backward compatible and people who use the old name could still use it without problems. We have tests that verify that the operator is working from an old and new path. If the old path is used, a deprecation warning is also checked.

If you have further questions, I will be happy to answer.

**Comment by ashb** [comment]
> So... what benefit is there to changing this name? KMS is a GCP only feature, no?

(FYI: AWS have a service called KMS too.)

**Review by ashb — APPROVED** [review]

**Comment by michalslowikowski00** [comment]
Thx @ashb :)

**Comment by michalslowikowski00** [comment]
Thx @mik-laj :D

**Pull request merged**
