### PR TITLE
Revert: Need some approval to add name in companies list. 

### PR DESCRIPTION
**Pull request by chandulal**
### Description

Need approval to add name in companies list.

### CODE REVIEW

**Comment by Fokko** [comment]
@chandulal The changes are empty, please open a new PR with the reverted commit.

**Comment by chandulal** [comment]
@Fokko There is only one change in README.md. Just removed "Grab" from company list. Because we need to take permission from the legal team. These changes are there.

**Comment by chandulal** [comment]
@Fokko Could you please merge with master. Thanks in advance.

**Comment by Fokko** [comment]
@chandulal The PR is empty: https://github.com/apache/incubator-airflow/pull/4046/files

Regardless of the PR, I've reverted the changes: https://github.com/apache/incubator-airflow/commit/6999f344cb62d73b820fdb3d80d5b47ed26f6e22

Let me know when you have the approval :)

**Pull request closed without merging**
