### PR TITLE
Upgrade FAB to 4.3.1

### LINKED ISSUE #31156: Searching task instances by state doesn't work
### Apache Airflow version

2.6.0

### What happened

After specifying a state such as "Equal to" "failed", the search doesn't return anything but resetting the whole page (the specified filter is gone)

https://github.com/apache/airflow/assets/14293802/5fb7f550-c09f-4040-963f-76dc0a2c1a53

### What you think should happen instead

_No response_

### How to reproduce

Go to "Browse" tab -> click "Task Instances" -> "Add Filter" -> "State" -> "Use anything (equal to, contains, etc)" -> Click "Search"

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by VVildVVolf**
Flask-ApplicationBuilder v4.3.0 has a bug with usage `Select2` control. It is fixed in v4.3.1. The description is mentioned in issue https://github.com/apache/airflow/issues/31156

> please make sure that you review the classes and models in
    # `airflow/www/fab_security` with their upstream counterparts. In particular, make sure any breaking changes

 [v4.3.0 vs v4.3.1](https://github.com/dpgaspar/Flask-AppBuilder/compare/v4.3.0..v4.3.1) looks pretty minor, but includes the change we need. [flask_appbuilder/security](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/security) was not touched.

---

### CODE REVIEW

**Comment by potiuk** [comment]
Did you check if there are no changes in security manager folowing this comment?

```
    # We are tightly coupled with FAB version because we vendored in part of FAB code related to security manager
    # This is done as part of preparation to removing FAB as dependency, but we are not ready for it yet
    # Every time we update FAB version here, please make sure that you review the classes and models in
    # `airflow/www/fab_security` with their upstream counterparts. In particular, make sure any breaking changes,
````

**Comment by potiuk** [comment]
You can see example changes that needed to be implemented in past PRs that were upgrading FAB BTW.

**Comment by VVildVVolf** [comment]
@potiuk ,

> You can see example changes that needed to be ported in past PRs that were upgrading FAB BTW.

Yes, I am already using https://github.com/apache/airflow/pull/29766/files as a reference, thanks!

> Did you check if there are no changes in security classes folowing this comment?

Mostly I was focused on checking if upgrade of FAB does help or not with the issue https://github.com/apache/airflow/issues/31156 . Good news that upgrading to 4.3.1 helps (but hard to be covered by Unit test, investigating if it is possible). The review of `airflow/www/fab_security` is in progress - I need to find out some details. 

P.S. Just for history maybe it will help someone: to update FAB locally helped:

- some manipulations with [docker's ARGs like AIRFLOW_SOURCES_FROM](https://github.com/apache/airflow/blob/main/Dockerfile)
- `breeze ci-image build --upgrade-to-newer-dependencies
`

**Comment by potiuk** [comment]
> Mostly I was focused on checking if upgrade of FAB does help or not with the issue https://github.com/apache/airflow/issues/31156 . Good news that upgrading to 4.3.1 helps (but hard to be covered by Unit test, investigating if it is possible). The review of airflow/www/fab_security is in progress - I need to find out some details.

From what I understand (I have not done it originally) the security manager was ported "partially" (that is what makes it difficult) - some parts of security manager is completely not used by us, but some other (authentication types) are - and only those should be ported.

**Comment by VVildVVolf** [comment]
It looks like the difference [v4.3.0 vs v4.3.1](https://github.com/dpgaspar/Flask-AppBuilder/compare/v4.3.0..v4.3.1) looks pretty minor, but includes the change we need. [flask_appbuilder/security](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/security) was not touched.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks!

**Pull request merged**
