### PR TITLE
Add triggerer to `docker-compose.yaml` file

### PR DESCRIPTION
**Pull request by kaxil**
Adds triggerer component added in #15389 (AIP-40) to the `docker-compose.yaml` file for quick start

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]

**Review by potiuk — CHANGES_REQUESTED** [review]
I am afraid this is going to fail if someone tries to run it with Airflow < 2.2. We should add some if's here as the docker-compose for quite some time will be used also for older versions of airflow.

**Comment by kaxil** [comment]
> I am afraid this is going to fail if someone tries to run it with Airflow < 2.2. We should add some if's here as the docker-compose for quite some time will be used also for older versions of airflow.

Why would someone use this 

> I am afraid this is going to fail if someone tries to run it with Airflow < 2.2. We should add some if's here as the docker-compose for quite some time will be used also for older versions of airflow.

Docker-compose does not support conditionals for spinning up services. The only workaround is exiting with `exit 0` in which case you lose health-check benefits. Plus docker-compose files are versioned with Airflow, users can use docker-compose file for that version .

The command to get docker-compose is https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html:

```
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.1.2/docker-compose.yaml'
```

The same reason why a user shouldn't be using older version of Airflow and looking into new docs should apply here. 

Plus this is for local testing only, our Helm Chart already have this conditionals.

**Comment by kaxil** [comment]
Update the file to need a minimum of 2.2.0 to run this version. If there is another solution in mind, we can follow-up with a PR but until then this will help current testers to directly use this file or Helm chart to quickly and easily test out triggerer

**Comment by potiuk** [comment]
> 
> The command to get docker-compose is https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html:
> 
> ```
> curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.1.2/docker-compose.yaml'
> ```

I've been helping users with ~30 issues over the last few weeks. Some of them jus took the latest docker-compose and changed the version and run it. The problem is that you get to the "quick-start" page and download the file from there. And then they look at it, change the version to 2.0.2 ("why? Because this is the version that is installed in my production, I wanted to use the same"). They will not switch to earlier version of airlfow in the docs, they will not use the right command for the version. They just don't.

The file itself has no indication which version it supports, it's not named docker-compose-2.1.2 or anything like that, just docker compose. I simply do not want any more to close people's issues beginning with "I used your official docker compose and it does not work". In this case the error will be cryptic ant the user will not know what to do "the triggerrer command  will fail". The "quick-start" should be really "quick" and should give the users maximum guidance on how they should fix the problems, Almost by definition, the users of "quick-start" docker compose know nothing about airflow, and when they will see an error - which they won't understand, they will ... open an issue. I do not want this. I am currently on a spree of making sure we optimise our issue opening/handling experience. The best way to deal with issues is to make sure they will not get opened in the first place.

This is why few lines down I've added explicit "fail if the version is < 2.1.0 and tell them to use only newer version. Either we make this docker compose 2.2.0+ (and change the min version below so that user will get explicit "please upgrade message in case they use < 2.2.0) - which is fine, for me as the message will be clear. Or we introduce some kind of backwards compatibility. Either this or that, but "triggerer could not be started" instead of "You should upgrade airflow to 2.2.0" is a very bad message for first-time users.

**Comment by potiuk** [comment]
> Update the file to need a minimum of 2.2.0 to run this version. If there is another solution in mind, we can follow-up with a PR but until then this will help current testers to directly use this file or Helm chart to quickly and easily test out triggerer

Yep. I am fine with that :) - see my reasoning above :)

**Review by potiuk — APPROVED** [review]
LGTM

**Pull request merged**
