### PR TITLE
[AIRFLOW-4111] Auto config airflow_db to database in initdb

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make `airflow initdb` auto configure `airflow_db`
by reading and parsing alchemy url in `airflow.cfg`
section `[core]` param `sql_alchemy_conn`

`airflow_db` work on UI `Data profiling/Ad Hoc Query`
and `Data profiling/Known Events` but using default
constant values which not user friendly, specially
`Data profiling/Known Events` use conn_id
`airflow_db` as example

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-4111\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR:

Make `airflow initdb` auto configure `airflow_db`
by reading and parsing alchemy url in `airflow.cfg`
section `[core]` param `sql_alchemy_conn`

`airflow_db` work on UI `Data profiling/Ad Hoc Query`
and `Data profiling/Known Events` but using default
constant values which not user friendly, specially
`Data profiling/Known Events` use conn_id
`airflow_db` as example

### Tests

- [x] My PR adds the following unit tests:

Add test in `airflow/test/utils/test_db`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by XD-DENG** [comment]
- `Data profiling/Ad Hoc Query` are no longer applicable in master branch (it's deprecated in the new UI).

- DB table for `Known Events` was also removed in master branch.

**Comment by zhongjiajie** [comment]
@XD-DENG Sorry XD, I do not kuow that. I just test in release branch. But we still use `airflow_db` as Airflow backend default, and it connection information already configure in `airflow.cfg` file. Do you think we should accept this change?

**Comment by XD-DENG** [comment]
No worries @zhongjiajie .

I haven't checked your change yet. My comments above were mainly to address your PR description.

Allow me a bit more time to check/assess your change, or maybe another committer will have a look later.

**Comment by zhongjiajie** [comment]
@XD-DENG thanks.

**Comment by XD-DENG** [comment]
Hi @zhongjiajie I have had a quick check.

I think it's changing the behaviour, and may cause concern (in my person opinion): Users have been used to the behaviour that all the default connections are somehow "fake" and they know that they need to go there configure explicitly.

Another example: I may be using a `read+write` DB account for `sql_alchemy_conn` (`write` permission must be provided), while I will use a `read_only` DB account for `airflow_db`. But your change will use the `read+write` DB account info in `sql_alchemy_conn` to configure `airflow_db`, which should not happen by default.

IMO, the concerns this PR brings > the pros it brings (also given that `Data profiling/Ad Hoc Query/Known Events` are all deprecated). Personally I would not merge it.

Hope this clarifies.

**Comment by XD-DENG** [comment]
@zhongjiajie may you consider closing this?

**Comment by zhongjiajie** [comment]
@XD-DENG Sorry XD, I don't know you comment at two days ago.
You are right, I don't figure out that all of the connection create by `initdb` are fake. And this change may cause some security issue.

**Comment by XD-DENG** [comment]
No worries. Thanks @zhongjiajie

**Comment by zhongjiajie** [comment]
@XD-DENG Thanks for you review, BTW, I close jira ticket with information that your comment above.

**Comment by XD-DENG** [comment]
That helps. Thanks :)

**Pull request closed without merging**
