### PR TITLE
Stop loading Extra Operator links in Scheduler

### LINKED ISSUE #13099: Unable to start scheduler after stopped
**Apache Airflow version**: 2.0.0rc3

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: Linux
- **OS** (e.g. from /etc/os-release): Ubuntu
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:

After shutting down the scheduler, while tasks were in running state, trying to restart the scheduler results in pk violations..

```[2020-12-15 22:43:29,673] {scheduler_job.py:1293} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/home/jcoder/git/airflow_2.0/pyenv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/jcoder/git/airflow_2.0/pyenv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_run_dag_id_run_id_key"
DETAIL:  Key (dag_id, run_id)=(example_task_group, scheduled__2020-12-14T04:31:00+00:00) already exists.
```

**What you expected to happen**:

Scheduler restarts and picks up where it left off.

**How to reproduce it**:

Set example dag ( I used task_group) to schedule_interval `* * * * *` and start the scheduler and let it run for a few minutes. 
Shut down the scheduler
Attempt to restart the scheduler

**Anything else we need to know**:
I came across this doing testing using the LocalExecutor in a virtual env. If no else is able to reproduce it, I'll try again in a clean virtual env.

### PR DESCRIPTION
**Pull request by kaxil**
closes #13099

Mutually exclusive with https://github.com/apache/airflow/pull/13931

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
This works but feels ugly and prone to error — i.e if someone adds another `self.dagbag.get `somewhere and misses the `load_op_links` flag — then op link will be loaded again.

https://github.com/apache/airflow/pull/13931 looks much cleaner in my opinion -- however we manage some sort of global state -- but we remove the env var before we exist `_do_scheduling`

cc @ashb -- I will add tests once we decide on the approach

**Comment by kaxil** [comment]
@ephraimbuddy @jhtimmins Can you take a look and review too please

**Review by jhtimmins — COMMENTED** [review]
I prefer this approach to the global state of environment variables. Is it necessary to pass `load_op_links` to DagBag's constructor though?

I'm not super familiar with the how this is used, so it might not make sense, but could it be passed directly to `deserialize_operator` as an argument?

**Comment by kaxil** [comment]
> I prefer this approach to the global state of environment variables. Is it necessary to pass `load_op_links` to DagBag's constructor though?
> 
> I'm not super familiar with the how this is used, so it might not make sense, but could it be passed directly to `deserialize_operator` as an argument?

Mainly to reduce the places we need to pass the flag otherwise -- https://github.com/apache/airflow/pull/13932/commits/dab163e80bb62d7d8fb43b4adb7654c5b6c3e3ba is my first commit where I tried something similar but its too ugly -- I passed it all the over the place

**Review by potiuk — APPROVED** [review]

**Pull request merged**
