### PR TITLE
Add retryer to SFTP hook connection

### PR DESCRIPTION
**Pull request by TobKed**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by TobKed** [comment]
WDYT @mik-laj ? It is good approach to avoid connection timeouts which occurs during testing https://github.com/apache/airflow/pull/11284 ?

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
@TobKed LGTM. Is it ready for review?

**Comment by TobKed** [comment]
@mik-laj rebased on the latest master, ready to merge

**Comment by TobKed** [comment]
@mik-laj what do you think about merging it?

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
