### PR TITLE
Make execute and on_kill as abstractmethod in baseoperator

### PR DESCRIPTION
**Pull request by zhongjiajie**
Each subclass of baseoperator should implement on_kill function
to avoid make failed/success in dag UI or task instance up_for_retry
status but process still running

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Today in my production environment worker full CPU and found out in `airflow-1.10.0` `SSHOperator` without `on_kill` function. So when a task block or take long times, worker process will keep running whether task up_for_retry or failed. The running ghost processes cause resource and the new task(retry task) running without enough  resource until task instance timeout reach. this repeat one by one until all resource used.

The most direct way to fix it is add `on_kill` function to `SSHOperator` but I check codebase and find some other Operator without `on_kill` So I create this PR force all class implement `BaseOperator` should implement `on_kill` function

**Comment by zhongjiajie** [comment]
Create a draft PR to hear opinions, If agree with that I will continue, WDYT, @potiuk @kaxil @ashb @mik-laj @turbaszek

**Comment by ashb** [comment]
How many don't have an on_kill?

Could the default on_kill be to kill any child processes?

**Comment by mik-laj** [comment]
In the case of Google, only operators for Dataflow and BigQuery have the on_kill method. I think this is an important problem, but first we must create a good example to be able to enforce such a rule.

**Comment by mik-laj** [comment]
All child processes for tasks should be killed by a task runner (`airflow.task.task_runner.standard_task_runner.StandardTaskRunner.terminate`).

**Comment by zhongjiajie** [comment]
> How many don't have an on_kill?

Almost a half? I guess

> All child processes for tasks should be killed by a task runner (airflow.task.task_runner.standard_task_runner.StandardTaskRunner.terminate).

I really odd, I try in master code before I submit PR, I delete function `on_kill` in `BashOperator`, add task `t4=BashOperator(command='python -m http.server')`. When I mark faild/success or let task execution timeout, the child processes `python -m http.server` still running. I don't know whether I make some mistake in my test, will try to re-test tomorrow

**Comment by RosterIn** [comment]
The problem is also where you need to kill a process on remote machine.
https://issues.apache.org/jira/browse/AIRFLOW-3750 

This is also not that simple as some operators are not stand alone but a part of series of operators.
Think of `CreateMachineOperator` -> 1 or more `RunOperator` -> `TerminateOperator` (Like EMR for example)
What functionally will `on_kill()` have in any of them? shall it be just:
```
def on_kill():
   pass
```

**Comment by zhongjiajie** [comment]
> This is also not that simple as some operators are not stand alone but a part of series of operators.

But if we add on_kill function to all operator, they could kill process if not success, whether task instance failed or up_for_retry, the next task will not run, and I think that could be work. Did I missing some situation here?

**Comment by zhongjiajie** [comment]
No stale, sorry about that, I got some health problem recently, will continue after recover from illness.

**Comment by turbaszek** [comment]
From docs https://docs.python.org/3/library/abc.html :
>Using this decorator requires that the class’s metaclass is ABCMeta or is derived from it. A class that has a metaclass derived from ABCMeta cannot be instantiated unless all of its abstract methods and properties are overridden.

That's what I'm proposing in https://github.com/apache/airflow/pull/8805

**Comment by ashb** [comment]
`on_kill` shouldn't be abstract -- a default approach of on_kill being a no-op is okay.

**Comment by ashb** [comment]
> But if we add on_kill function to all operator, they could kill process if not success

The task runner will handle killing processes already, so on_kill is only needed for specialized handling, such as canceling an API request.

**Comment by turbaszek** [comment]
@zhongjiajie would you mind rebasing? We are not using travis anymore and in the meantime we introduced `BaseOperatorMeta` so the abstract method should work as expected

**Comment by mik-laj** [comment]
@turbaszek I think we first need to consider whether we want to process it further.

**Comment by turbaszek** [comment]
> @turbaszek I think we first need to consider whether we want to process it further.

I think the discussion is still ongoing

**Comment by zhongjiajie** [comment]
I will rebase and continue to finish this  PR, thx

**Comment by zhongjiajie** [comment]
I use fast push to test which sub operator missing `on_kill` function.

**Pull request closed without merging**
