### PR TITLE
Add templates and constructor parameters to list-integrations

### LINKED ISSUE #8893: Displaying field templates and constructor parameters in scripts/list-integration.py
Hello,

We have script that allows us to display class names.
https://github.com/apache/airflow/blob/master/scripts/list-integrations.py
It would be nice if it were possible to display template fields and constructor parameters.  This should be available when you run this script with an additional option. The output should be available as CSV or JSON or JSONL. Constructor parameters from BaseOperator or BaseSensor should be ignored.
This tool is needed to review all operators to eliminate missing template fields in existing operators.

Related PR:
https://github.com/apache/airflow/pull/8870
https://github.com/apache/airflow/pull/8840
https://github.com/apache/airflow/pull/7198
https://github.com/apache/airflow/pull/7127
https://github.com/apache/airflow/pull/6656
https://github.com/apache/airflow/pull/5718
https://github.com/apache/airflow/pull/5490
https://github.com/apache/airflow/pull/5248
https://github.com/apache/airflow/pull/5097
https://github.com/apache/airflow/pull/4920
https://github.com/apache/airflow/pull/4691
https://github.com/apache/airflow/pull/3305
https://github.com/apache/airflow/pull/2981
https://github.com/apache/airflow/pull/2549
https://github.com/apache/airflow/pull/2480
https://github.com/apache/airflow/pull/2235
https://github.com/apache/airflow/pull/1808
https://github.com/apache/airflow/pull/996
and more

### PR DESCRIPTION
**Pull request by edithturn**
Add templates and constructor parameters.

* class_name
* template_fields
* init_params

**Format**: class_name; template_fields; init_params

Close: #8893

### CODE REVIEW

**Comment by edithturn** [comment]
@mik-laj could you guide me on how to test this pull request. I am getting this on my local machine.
is there an operator to get complete information with this template?
Screenshot from 2022-05-11 20-40-28

**Comment by potiuk** [comment]
I thin there is no such operator. The tool (was) mostly used for manual scan of the operators but I think the idea was to - eventually - convert the output into  some kind of "todo" list - i.e. to see how many init constructors parameter of those operators are good candidates to be templated.

For that I think we need to add some heuristics to determine the potentially good candidates and mark them as "not good" somehow. Was that the idea @mik-laj ?

**Comment by josh-fell** [comment]
Seems like this might be a duplicate of #21560 which has a slightly different implementation.

**Comment by potiuk** [comment]
Any preference to one or another @josh-fell @mik-laj :) ?

**Pull request closed without merging**
