### PR TITLE
[AIRFLOW-3392] Add index on dag_id in sla_miss table

### PR DESCRIPTION
**Pull request by KevinYang21**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-3392) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3392

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
The [select queries on sla_miss table](https://github.com/apache/incubator-airflow/blob/master/airflow/jobs.py#L669-L674) produce a great % of DB traffic and thus made the DB CPU usage unnecessarily high. It would be a low hanging fruit to add an index and reduce the load. After all such queries that are issued by the DagFileProcessor should be optimized as much as possible.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Tested within Airbnb's setup. In Airbnb's setup, the # of rows scanned by this query is ~80% of all row scanned. Add such index reduced ~30% of the DB CPU usage and the cluster has been running healthy for 1 month +. Below is the CPU usage metrics.

cpu_diff 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
```
flake8 runtests: commands[0] | flake8
./airflow/migrations/versions/03bc53e68815_add_sm_dag_index.py:9:2: W291 trailing whitespace
./airflow/migrations/versions/03bc53e68815_add_sm_dag_index.py:11:2: W291 trailing whitespace
./airflow/migrations/versions/03bc53e68815_add_sm_dag_index.py:33:1: E402 module level import not at top of file
```

**Comment by KevinYang21** [comment]
@Fokko Ty for taking a look! Was retrying the CI and not look into the actually failures as it has been pretty flaky in the past two days. Updated the style and will later on put a proper description( with performance improvement measurement) and remove the WIP in the title.

**Comment by KevinYang21** [comment]
@Fokko @ashb @feng-tao @XD-DENG @kaxil @saguziel @aoen @YingboWang PTAL

**Comment by feng-tao** [comment]
lgtm. thanks @KevinYang21

**Pull request merged**
