### PR TITLE
[AIRFLOW-486] Daemonize webserver process, not gunicorn

### PR DESCRIPTION
**Pull request by ldct**
@bolkedebruin 

Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-486](https://issues.apache.org/jira/browse/AIRFLOW-486)
### Testing done
- [x] webserver detaches with -D
- [ ] webserver still refreshes

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Earlier, before the rolling restarts, we used the daemonize gunicorn in order to make sure the processes it launches are terminated properly. Have you tested whether children of the main process are correctly terminated when the main process terminates?

**Comment by ldct** [comment]
@bolkedebruin how did you terminate gunicorn?

**Comment by bolkedebruin** [comment]
kill -TERM `pid` . The way gunicorn used to be started is that "airflow webserver" does not leave itself running. Ie. after forking gunicorn, the airflow process itself exits immediately.

**Comment by ldct** [comment]
@bolkedebruin will look into that - `pid` is the one passed to gunicorn via `-p` right?

**Comment by ldct** [comment]
@bolkedebruin @aoen I'm looking at the pre-PR code (https://github.com/apache/incubator-airflow/blob/62768bc087e95bf4506a8ec24d4291d7dfa7abaf/airflow/bin/cli.py) and it seems like the values `AIRFLOW_HOME/airflow-webserver.err`, `AIRFLOW_HOME/airflow-webserver.out` and `AIRFLOW_HOME/airflow-webserver.log` are calculated and then ignored, is that expected?

**Comment by aoen** [comment]
@zodiac Which lines are you referring to?

**Comment by ldct** [comment]
@aoen they are computed in the call to`setup_locations` here https://github.com/apache/incubator-airflow/blob/62768bc087e95bf4506a8ec24d4291d7dfa7abaf/airflow/bin/cli.py#L519

**Comment by aoen** [comment]
Ah yes, looks like they are unused, I'll let Bolke comment since it looks like they are part of his PR.
https://github.com/apache/incubator-airflow/commit/e8c1144bb86e9a1f8b0195375185e9418f23f0c5

From what I can see the webserver should follow a similar pattern to the other services, e.g.:

```
stdout = open(stdout, 'w+')
         stderr = open(stderr, 'w+')

         ctx = daemon.DaemonContext(
             pidfile=TimeoutPIDLockFile(pid, -1),
             files_preserve=[handle],
             stdout=stdout,
             stderr=stderr,
         )
```

**Comment by bolkedebruin** [comment]
I agree with @aoen on the pattern . I think not setting the paths correctly is oversight on my behalf.

**Comment by r39132** [comment]
@zodiac Please rebase this commit and let me know your intention on whether you plan to get this across the line. I will wait 5 days to hear back on next steps.

**Comment by ldct** [comment]
@r39132 working on it

**Comment by r39132** [comment]
Do you have an ETA? If not, i can close and you can reopen at a later date when ready for a review, test, and merge.

**Comment by r39132** [comment]
Closed for inactivity. Please re-open when ready for review, test, and merge.

**Pull request closed without merging**
