### PR TITLE
[AIRFLOW-2638] dbapi_hook: add support for replace into instead of insert into

### PR DESCRIPTION
**Pull request by flokli**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2638

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
No UI changes.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
`test_dbapi_hook.test_insert_rows_replace`

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Nice one @flokli.

Like it a lot

**Comment by flokli** [comment]
Thanks for merging! :-)

**Comment by JacobHayes** [comment]
I think `REPLACE INTO` is a mysql syntax extension, would this be more fitting as an override in `mysql_hook.insert_rows` or a new `replace_rows` method (similar to the `bulk_load`/`bulk_dump` extensions)?

**Comment by flokli** [comment]
@JacobHayes You're right!
It seems that the 'REPLACE INTO' syntax is supported for [MySQL](https://dev.mysql.com/doc/refman/8.0/en/replace.html) and [SQLite](http://www.sqlitetutorial.net/sqlite-replace-statement/), but looks slightly different for other engines.

I'm a bit unhappy about introducing the `replace=` parameter just for `mysql_hook.insert_rows`, as this seems to be a useful feature for all engines, and in doing it just for one engine, we would also copy over a lot of generic code from `dbapi_hook` to the mysql-specific implementation (with the possibly happening as for other implementations as well as soon we start supporting that feature for these). Similar applies to a separate `replace_rows` method.

After some deeper look into the code, one way to solve that would be splitting out the sql string generation process into two separate methods (one for insert and one for replace, with the latter raising `NotImplementedError` in `dbapi_hook`), and overiding those in the engine specific classes. I'll file a PR later, please have a look then :-)

**Comment by flokli** [comment]
Actually, `dbapi.run` and `dbapi.insert_rows` already share a lot of code, with the only part missing being the `commit_every` feature. So it would make much more sense to abstract that :-)

**Pull request closed without merging**
