### PR TITLE
[AIRFLOW-3731] Constrain mysqlclient to <1.4

### PR DESCRIPTION
**Pull request by Fokko**
To maintain Python2 compatibility: https://pypi.org/project/mysqlclient/#history

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3731\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3731
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-3731\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
@kaxil PTAL

**Comment by Fokko** [comment]
@potiuk, In my opinion, this stuff needs to be fixed first before we move to a multi-layer image of Airflow. In this case, the image would still be working, but the master would be broken when using Python2 and MySQL 😢

**Comment by kaxil** [comment]
Aren't they just dropping python 3.4 support?

**Comment by Fokko** [comment]
They changed the public interface of the `Connection`, I've opened up an issue: https://github.com/PyMySQL/mysqlclient-python/issues/325

**Comment by TylerBrock** [comment]
I think we need to move forward. Is there a way to install both and use <1.4 for python2 and  >=1.4 for python3? I'm not sure if @kaxil is correct but if they are only removing support for python 3.4 then there shouldn't be an issue here.

I would be happy to take a stab at refactoring airflow's MySqlHook for 1.4 if nobody else is working on it.

**Comment by potiuk** [comment]
Yes. It's possible. In setup.py of v1-10-test we have: 
```
    'sphinx>=2.1.2;python_version>="3.0"',
    'sphinx==1.8.5;python_version<"3.0"',
```

**Comment by OmerJog** [comment]
@TylerBrock  an attempt has be done here https://github.com/apache/airflow/pull/5430 but wan't completed.

**Comment by methane** [comment]
I removed `__exit__` from mysqlclient because it was not many people expects, including Airflow.

https://github.com/apache/airflow/blob/7bebe8ddbc69ed5a1b316d31a2aa542f6bc60432/tests/operators/test_operators.py#L354-L363

https://github.com/apache/airflow/blob/7bebe8ddbc69ed5a1b316d31a2aa542f6bc60432/tests/operators/test_operators.py#L370-L371

The Airflow expect `__exit__` close the connection.  But it didn't.  It did commit or rollback.
So there are connection leaks in your code.

Since this interface is different from many people expects, I am changing it:

1. deprecate it.
2. remove it.  (now)
3. add `__exit__` which closes the connection.  (in near future).

**Pull request merged**
