### PR TITLE
Migrate all packages to use PEP 517

### PR DESCRIPTION
**Pull request by uranusjr**
The main Airflow and all provider packages are now using `pyproject.toml`'s `[build-system]` to specify build-time requirements, and use https://github.com/pypa/build to build sdist and wheel.

TBH I kind of lost track half way of what I should change in the build system. I don't have much confidence of some changes I've made.

cc @potiuk 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
The tests will show. All the build commands (including building providers) are executed in CI :)

**Comment by uranusjr** [comment]
Things seem to work...?

**Comment by uranusjr** [comment]
Since `compile_assets` is now called inside the PEP 517 hook, we can now move it from setup.py into `scripts/pep517/backend.py`, but would some people still want to call `setup.py compile_assets`?

**Comment by uranusjr** [comment]
This seems to break editable install. Need more investigation.

**Pull request closed without merging**
