### PR TITLE
Removed deprectaed extras dict from hatch build

### PR DESCRIPTION
**Pull request by dirrao**
Removed deprectaed extras dict from hatch build

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by vincbeck** [comment]
Do we need a newsfragment?

**Comment by potiuk** [comment]
> Do we need a newsfragment?

Yeah. Good point.

**Review by potiuk — CHANGES_REQUESTED** [review]
newsfragment missing.

**Review by eladkal — APPROVED** [review]

**Comment by dirrao** [comment]
> newsfragment missing.

Done.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
