### PR TITLE
Add task logs across tries

### PR DESCRIPTION
**Pull request by bbovenzi**
First part of https://github.com/apache/airflow/issues/44663 to see task logs across tries

More advanced filtering and formatting will be added later

Screenshot 2024-12-18 at 2 09 07 PM

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
Looks good as a skeleton! Log refresh is not working, correct? ATM I need to hit F5 in all dialogs to get updates, correct?

**Comment by jscheffl** [comment]
I assume unrelated to this PR but on the task there is a `NaN` displayed for duration when it is still running:
image

**Comment by bbovenzi** [comment]
Yes I can add autorefresh and fix the duration in other PRs

**Comment by tirkarthi** [comment]
@bbovenzi @jscheffl   I have a PR open to handle NaN across API calls and in UI for running dagruns and task instance. Happy to know your thoughts. https://github.com/apache/airflow/pull/44989

**Pull request merged**
