### PR TITLE
Improves documentation regarding providers and custom connections 2

### PR DESCRIPTION
**Pull request by soltanianalytics**
See https://github.com/apache/airflow/pull/13375 for the first part

The slack discussion went on and I added some more information that might be helpful for others as well. I also fixed a formatting bug that I introduced in the first part.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Good one! 

Can you please rebase to latest master + solve conflicts ? 

Happy New Year!

**Comment by soltanianalytics** [comment]
Done, thanks!

Happy new year to you, too!

**Comment by potiuk** [comment]
Some spelling errors unfortunately :(

**Comment by soltanianalytics** [comment]
Made some updates - let me know if there is any part you'd like me to go over again :)

**Comment by potiuk** [comment]
Looks great! Merging! Thanks again ! What's next :)?

**Comment by soltanianalytics** [comment]
> Looks great! Merging! Thanks again ! What's next :)?

Thanks! This is next: https://github.com/apache/airflow/pull/13408 ^^

**Pull request merged**
