### PR TITLE
[AIRFLOW-2181] Convert password_auth and test_password_endpoints from DOS to UNIX

### PR DESCRIPTION
**Pull request by dan-sf**
### JIRA
- [x] My PR addresses the following Airflow JIRA
    - https://issues.apache.org/jira/browse/AIRFLOW-2181

### Description
- This PR contains no actual changes to the code. It only contains file format changes to password_auth and test_password_endpoints converting from DOS to UNIX.

### Tests
- I have re-run the unittests and confirmed the password_auth backend still works with this change (using the patch here: https://github.com/apache/incubator-airflow/pull/3048). Travis build/tests pass successfully.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@dan-sf Please fix your line endings. Now the full file is marked as a diff. Cheers

**Comment by dan-sf** [comment]
@Fokko I'm not sure I understand, the files are currently in DOS format in master and this change updates them to UNIX format. Since every line changes git marks the full file diffs, is there a way to force git to only diff line endings?

**Comment by Fokko** [comment]
I just looked in the file:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ hexdump -C airflow/contrib/auth/backends/password_auth.py
00000000  23 20 2d 2a 2d 20 63 6f  64 69 6e 67 3a 20 75 74  |# -*- coding: ut|
00000010  66 2d 38 20 2d 2a 2d 0d  0a 23 0d 0a 23 20 4c 69  |f-8 -*-..#..# Li|
```
Currently it is `0D 0A`, which is Carriage return and a newline. I think this is caused by @NielsZeilemaker his Windows environment. So currently it is `DOS\Windows` and we want to move to `UNIX` style.

**Comment by Fokko** [comment]
Thanks @dan-sf

**Pull request closed without merging**
