### PR TITLE
[AIRFLOW-4810] Bump supported mysqlclient to <1.5

### PR DESCRIPTION
**Pull request by RosterIn**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4810
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by RosterIn** [comment]
Not really sure why 1 test failed... I don't see any related error in the log

**Comment by ashb** [comment]
If you view the raw log for the failed test and search for " FAIL:" you see this

```
74) FAIL: test_database_schema_and_sqlalchemy_model_are_in_sync (tests.utils.test_db.DbTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/utils/test_db.py line 98 in test_database_schema_and_sqlalchemy_model_are_in_sync
      'Database schema and SQLAlchemy model are not in sync: ' + str(diff)
   AssertionError: [('remove_table', Table('test_airflow', MetaData(bind=None), Column('dummy', VARCHAR(length=50), table=<test_airflow>), schema=None)), ('remove_table', Table('test_mysql_to_mysql', MetaData(bind=None), Column('TABLE_CATALOG', VARCHAR(length=512), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565d68>, for_update=False)), Column('TABLE_SCHEMA', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b00>, for_update=False)), Column('TABLE_NAME', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5651d0>, for_update=False)), Column('TABLE_TYPE', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b38>, for_update=False)), Column('ENGINE', VARCHAR(length=64), table=<test_mysql_to_mysql>), Column('VERSION', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('ROW_FORMAT', VARCHAR(length=10), table=<test_mysql_to_mysql>), Column('TABLE_ROWS', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AVG_ROW_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('MAX_DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('INDEX_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_FREE', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AUTO_INCREMENT', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('UPDATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('CHECK_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('TABLE_COLLATION', VARCHAR(length=32), table=<test_mysql_to_mysql>), Column('CHECKSUM', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_OPTIONS', VARCHAR(length=255), table=<test_mysql_to_mysql>), Column('TABLE_COMMENT', VARCHAR(length=2048), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5655c0>, for_update=False)), schema=None))] is not false : Database schema and SQLAlchemy model are not in sync: [('remove_table', Table('test_airflow', MetaData(bind=None), Column('dummy', VARCHAR(length=50), table=<test_airflow>), schema=None)), ('remove_table', Table('test_mysql_to_mysql', MetaData(bind=None), Column('TABLE_CATALOG', VARCHAR(length=512), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565d68>, for_update=False)), Column('TABLE_SCHEMA', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b00>, for_update=False)), Column('TABLE_NAME', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5651d0>, for_update=False)), Column('TABLE_TYPE', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b38>, for_update=False)), Column('ENGINE', VARCHAR(length=64), table=<test_mysql_to_mysql>), Column('VERSION', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('ROW_FORMAT', VARCHAR(length=10), table=<test_mysql_to_mysql>), Column('TABLE_ROWS', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AVG_ROW_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('MAX_DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('INDEX_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_FREE', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AUTO_INCREMENT', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('UPDATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('CHECK_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('TABLE_COLLATION', VARCHAR(length=32), table=<test_mysql_to_mysql>), Column('CHECKSUM', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_OPTIONS', VARCHAR(length=255), table=<test_mysql_to_mysql>), Column('TABLE_COMMENT', VARCHAR(length=2048), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5655c0>, for_update=False)), schema=None))]
```

So this implies something about the mysql client behaviour has changed.

Formatted a bit nicer:

```
[
  ('remove_table', Table('test_airflow', MetaData(bind=None), Column('dummy', VARCHAR(length=50), table=<test_airflow>), schema=None)),
  ('remove_table', Table('test_mysql_to_mysql', MetaData(bind=None), Column('TABLE_CATALOG', VARCHAR(length=512), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565d68>, for_update=False)), Column('TABLE_SCHEMA', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b00>, for_update=False)), Column('TABLE_NAME', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5651d0>, for_update=False)), Column('TABLE_TYPE', VARCHAR(length=64), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff565b38>, for_update=False)), Column('ENGINE', VARCHAR(length=64), table=<test_mysql_to_mysql>), Column('VERSION', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('ROW_FORMAT', VARCHAR(length=10), table=<test_mysql_to_mysql>), Column('TABLE_ROWS', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AVG_ROW_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('MAX_DATA_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('INDEX_LENGTH', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('DATA_FREE', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('AUTO_INCREMENT', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('UPDATE_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('CHECK_TIME', DATETIME(), table=<test_mysql_to_mysql>), Column('TABLE_COLLATION', VARCHAR(length=32), table=<test_mysql_to_mysql>), Column('CHECKSUM', BIGINT(display_width=21, unsigned=True), table=<test_mysql_to_mysql>), Column('CREATE_OPTIONS', VARCHAR(length=255), table=<test_mysql_to_mysql>), Column('TABLE_COMMENT', VARCHAR(length=2048), table=<test_mysql_to_mysql>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x7f0aff5655c0>, for_update=False)), schema=None))
l] 
```

Thise is showing that there are two test tables created in other tests that for some reason aren't getting dropped.

**Comment by RosterIn** [comment]
@ashb It doesn't make sense to me.
There is nothing relevant in the change log of PyMySQL https://github.com/PyMySQL/mysqlclient-python/blob/master/HISTORY.rst
in fact the only reason they bumped version is because they dropped support for Python 3.4 

Moreover, the issue with `test_database_schema_and_sqlalchemy_model_are_in_sync`  is a compare issue.
Note that the other tests regarding `CREATE TABLE`, `DROP TABLE` of MySQL passed successfully. 
So, if there is a problem with the DB and it  has more/less tables than the model I would expect that `test_mysql_to_mysql `: https://github.com/apache/airflow/blob/577f8936727454eb4ff54588cd525c5244ef6d52/tests/operators/test_operators.py#L145 or the `teardown `https://github.com/apache/airflow/blob/577f8936727454eb4ff54588cd525c5244ef6d52/tests/operators/test_operators.py#L47
 would fail to.

I would love to fix whatever needed but I don't have a clue about what is the problem.  Maybe you can give me a better indication or try to rerun the test to see if it was flaky?

**Comment by RosterIn** [comment]
Can someone assist me to solve the problem here?

**Comment by RosterIn** [comment]
Closing for now. If someone will give pointers I'll reopen and address them.

**Pull request closed without merging**
