### PR TITLE
[AIRFLOW-6617] Add tests to PYTHONPATH in breeze

### PR DESCRIPTION
**Pull request by turbaszek**
Adding tests directory to PYTHONPATH helps during development :)

---
Issue link: [AIRFLOW-6617](https://issues.apache.org/jira/browse/AIRFLOW-6617)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Just wondering how it helps ? Not that I am against it but like to see a reason for it and maybe add it for others to the docs how it can be helpful

**Comment by turbaszek** [comment]
> Just wondering how it helps ? Not that I am against it but like to see a reason for it and maybe add it for others to the docs how it can be helpful

It has already happened a few times that I had to set up it manually.

**Comment by potiuk** [comment]
Yeah. But I wonder when it is needed. I.e. it should not be needed, unless someone (for example) somewhere in our code imports tests not from where it should i.e. `import kubernetes` instead of `import tests.kubernetes` -> I'd rather fix those place in the code where those bad imports are used than add tests folder to PYTHONPATH to hide the problem.

**Comment by turbaszek** [comment]
My problem was not bad imports but running `python tests/some/path`, mostly used here https://github.com/apache/airflow/pull/6761 to use cli for tests.

**Pull request closed without merging**
