### PR TITLE
Change log level from ERROR to INFO

### LINKED ISSUE #32862: Change log level of message for event loop block
### Description

Currently, when the event loop is blocked for more than 0.2 seconds, an error message is logged to the Triggerer notifying the user that the async thread was blocked, likely due to a badly written trigger. 
The issue with this message is that there currently no support for async DB reads. So whenever a DB read is performed (for getting connection information etc.) the event loop is blocked for a short while (~0.3 - 0.8 seconds). This usually only happens once during a Trigger execution, and is not an issue at all in terms of performance.
Based on our internal user testing, I noticed that this error message causes confusion for a lot of users who are new to Deferrable operators. As such, I am proposing that we change the log level of that message to `INFO` so that the message is retained, but does not cause confusion. Until a method is available that would allow us to read from the database asynchronously, there is nothing that can be done about the message. 

### Use case/motivation

image
I'd like the user to see this message as an INFO rather than an ERROR, because there it is not something that can be addressed at the moment, and it does not cause any noticeable impact to the user.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rohan472000**
---
closes: #32862 
related: #32862

### CODE REVIEW

**Comment by rohan472000** [comment]
@ferruzzi why static checks are getting cancelled?

**Comment by ferruzzi** [comment]
No idea, I tried to bump them and it happened again.  It's green now though.  May have just been a hiccup on Github's side yesterday.

**Review by ferruzzi — APPROVED** [review]

**Review by amoghrajesh — APPROVED** [review]
Looks good +1

**Comment by rohan472000** [comment]
@kaxil @ashb @XD-DENG review plz.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
