### PR TITLE
[AIRFLOW-1812] Update logging example

### PR DESCRIPTION
**Pull request by Fokko**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

The logging has changed, therefore we should also update the updating.md guide

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1812

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by gwax — APPROVED** [review]
Aside from the merge conflicts, LGTM

**Comment by Fokko** [comment]
I believe @bolkedebruin still had some comments.

**Comment by r39132** [comment]
Hi @Fokko Any updates on this one? If not, do you mind rebasing?

**Comment by r39132** [comment]
@Fokko Kindly instruct your intentions on this PR.

**Comment by r39132** [comment]
@Fokko kindly rebase

**Comment by Fokko** [comment]
Done @r39132, I'll do another pass over the PR this week.

**Pull request closed without merging**
