### PR TITLE
chore: bump OL provider dependencies versions

### PR DESCRIPTION
**Pull request by kacpermuda**
Just a regular bump of the OpenLineage libraries to take advantage of latest features.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I am afraid latest openlineage release broke main - see here https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-72+Task+Execution+Interface+aka+Task+SDK

**Comment by potiuk** [comment]
cc: @kacpermuda @mobuchowski

**Comment by topherinternational** [comment]
> I am afraid latest openlineage release broke main - see here https://github.com/apache/airflow/actions/runs/10734311195/job/29769445166

I saw the same failures in a branch I'm working on, I think #42054's change to the Dataset `extra` field is the problem? A bunch of tests that expect the default val to be `None` are failing bc the default is now `{}`.

**Comment by kacpermuda** [comment]
Yes, i don't think the OL is to blame here 😄

**Comment by potiuk** [comment]
> Yes, i don't think the OL is to blame here 😄

Ups

**Review by mobuchowski — APPROVED** [review]

**Pull request merged**
