### PR TITLE
[AIRFLOW-370] Create AirflowConfigException in exceptions.py

### PR DESCRIPTION
**Pull request by jlowin**
All exceptions should be created in `exceptions.py`.

https://issues.apache.org/jira/browse/AIRFLOW-370

### CODE REVIEW

**Comment by criccomini** [comment]
Is anything using AirflowConfigException? Could this change break imports?

**Comment by jlowin** [comment]
Fair question. The configuration object itself does, especially when validating, and it looks like a few authentication modules do as well: github enterprise; ldap; the general authentication load in **init**.py. Not much, but a few places.

I doubt imports would break because there is still an `AirflowConfigException` in airflow.configuration, it just isn't created there anymore.

**Comment by jlowin** [comment]
Also, I have absolutely no idea why this is causing only the Py2.7 sqlite travis build to fail. I thought it was random, but it fails every time.

**Comment by gwax** [comment]
+1

**Comment by msumit** [comment]
+1

**Pull request closed without merging**
