### PR TITLE
Fix file permission issue when running git-sync in the KubernetesExecutor mode

### PR DESCRIPTION
**Pull request by highfly22**
…tor mode.

---
When using git-sync in the Kubernetes, dag folder is empty because the ssh key file cannot be accessed by git-sync user.
This commit try to fix this by add securityContext.fsGroup parameter in the pod template.

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by highfly22** [comment]
> Would you mind adding a test case for it @highfly22 ? We have this new, fantastic pytest-based test framework for helm chart and it is super easy to add new tests there! look at `chart/tests`

I have added a test in the test_pod_template_file.py.

**Comment by highfly22** [comment]
@potiuk I have no idea on the following failed case. Could you give any clue?

```
self = <kubernetes_tests.test_kubernetes_pod_operator_backcompat.TestKubernetesPodOperatorSystem testMethod=test_xcom_push>

    def test_xcom_push(self):
        return_value = '{"foo": "bar"\n, "buzz": 2}'
        args = [f'echo \'{return_value}\' > /airflow/xcom/return.json']
        k = KubernetesPodOperator(
            namespace='default',
            image="ubuntu:16.04",
            cmds=["bash", "-cx"],
            arguments=args,
            labels={"foo": "bar"},
            name="test",
            task_id="task",
            in_cluster=False,
            do_xcom_push=True,
        )
        context = create_context(k)
        self.assertEqual(k.execute(context), json.loads(return_value))
        actual_pod = self.api_client.sanitize_for_serialization(k.pod)
        volume = self.api_client.sanitize_for_serialization(PodDefaults.VOLUME)
        volume_mount = self.api_client.sanitize_for_serialization(PodDefaults.VOLUME_MOUNT)
        container = self.api_client.sanitize_for_serialization(PodDefaults.SIDECAR_CONTAINER)
        self.expected_pod['spec']['containers'][0]['args'] = args
        self.expected_pod['spec']['containers'][0]['volumeMounts'].insert(0, volume_mount)  # noqa
        self.expected_pod['spec']['volumes'].insert(0, volume)
        self.expected_pod['spec']['containers'].append(container)
>       self.assertEqual(self.expected_pod, actual_pod)
E       AssertionError: {'api[40 chars]': {'namespace': 'default', 'name': <ANY>, 'an[998 chars]'}]}} != {'api[40 chars]': {'annotations': {}, 'labels': {'foo': 'bar'[1012 chars]'}]}}
E         {'apiVersion': 'v1',
E          'kind': 'Pod',
E          'metadata': {'annotations': {},
E                       'labels': {'airflow_version': '2.0.0b3',
E                                  'dag_id': 'dag',
E                                  'execution_date': '2016-01-01T0100000100-a2f50a31f',
E                                  'foo': 'bar',
E                                  'kubernetes_pod_operator': 'True',
E                                  'task_id': 'task',
E                                  'try_number': '1'},
E       -               'name': <ANY>,
E       +               'name': 'test-6c6eea1bc6974613815ef7ad04989ce8',
E                       'namespace': 'default'},
E          'spec': {'affinity': {},
E                   'containers': [{'args': ['echo \'{"foo": "bar"\n'
E                                            ', "buzz": 2}\' > '
E                                            '/airflow/xcom/return.json'],
E                                   'command': ['bash', '-cx'],
E                                   'env': [],
E                                   'envFrom': [],
E                                   'image': 'ubuntu:16.04',
E                                   'name': 'base',
E                                   'ports': [],
E                                   'resources': {},
E                                   'volumeMounts': [{'mountPath': '/airflow/xcom',
E                                                     'name': 'xcom'}]},
E                                  {'command': ['sh',
E                                               '-c',
E                                               'trap "exit 0" INT; while true; do sleep '
E                                               '30; done;'],
E                                   'image': 'alpine',
E                                   'name': 'airflow-xcom-sidecar',
E                                   'resources': {'requests': {'cpu': '1m'}},
E                                   'volumeMounts': [{'mountPath': '/airflow/xcom',
E                                                     'name': 'xcom'}]}],
E                   'hostNetwork': False,
E                   'imagePullSecrets': [],
E                   'initContainers': [],
E       -           'nodeSelector': {},
E                   'restartPolicy': 'Never',
E                   'securityContext': {},
E                   'serviceAccountName': 'default',
E                   'tolerations': [],
E                   'volumes': [{'emptyDir': {}, 'name': 'xcom'}]}}

kubernetes_tests/test_kubernetes_pod_operator_backcompat.py:484: AssertionError
```

**Comment by ashb** [comment]
@highfly22 Try rebasing -- that should have been fixed latest master.

**Comment by highfly22** [comment]
> @highfly22 Try rebasing -- that should have been fixed latest master.

Rebasing fixed that error. All test are passed.

**Comment by gmontanola** [comment]
Thanks for this fix @highfly22! I was trying to understand why setting up a private repo with SSH keys resulted in failure. I could not even get logs from the webserver, not sure why a 403 was issued, but applying your fix solved it too.

`HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:airflow:airflow-webserver\\" cannot list resource \\"pods/log\\" in API group \\"\\" in the namespace \\"airflow\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'`

@potiuk is there anything left in order to merge this PR? Let me know if I can help  :)

**Comment by mik-laj** [comment]
> `HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:airflow:airflow-webserver\\" cannot list resource \\"pods/log\\" in API group \\"\\" in the namespace \\"airflow\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'`

https://github.com/apache/airflow/pull/12598 looks related.

**Review by ianstanton — APPROVED** [review]

**Comment by ianstanton** [comment]
@potiuk Can you give this another look? Do you think this is good to merge?

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
