### PR TITLE
[AIRFLOW-2549] Fix DataProcOperation error-check

### PR DESCRIPTION
**Pull request by mchalek**
GCP DataProc Workflow Template operators should report errors when jobs
fail, even though the errors are not propagated up to the 'error'
field of the DataProcOperation API response object.

This commit checks the outcomes of the individual jobs for errors, and
raises an Exception if any are detected.

This behavior is consistent in spirit with the documentation for
DataProc Workflow templates, which states "A failure in any node in a
workflow will cause the workflow to fail."  See:
https://cloud.google.com/dataproc/docs/concepts/workflows/overview

Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2549) issues and references them in the PR title. 

### Description
- [ X ] Here are some details about my PR, including screenshots of any UI changes:
There are no UI changes.  The only change is that DataProcWorkflowTemplate-based operators will report failures when any of their component jobs/nodes fail, whereas previously those operators would report successes.

### Tests
- [X] My PR adds unit tests to make sure that the _DataProcOperator class responds properly to both successful and failed workflow template operations.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    N/A

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by mchalek** [comment]
cc: @fenglu-g @DanSedov

**Comment by Fokko** [comment]
@kaxil

**Comment by kaxil** [comment]
@mchalek 

Please resolve the below errors for Py3:

```
======================================================================
18) ERROR: test_failed_operation_detector (tests.contrib.hooks.test_gcp_dataproc_hook.DataProcHookTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/contrib/hooks/test_gcp_dataproc_hook.py line 144 in test_failed_operation_detector
      self.assertTrue(context.exception.message.startswith(
   AttributeError: 'Exception' object has no attribute 'message'
```

**Comment by mchalek** [comment]
Sorry about that, @kaxil , I think it should be fixed by my last commit.  I can rebase/force-push that back into the original commit if/when you decide this is ready to merge.

In the comments on the [Jira](https://issues.apache.org/jira/browse/AIRFLOW-2549), @DanSedov pointed out that this commit addresses an issue they would like to fix in DataProc (by surfacing errors at the top level of the API response).  So it may not be necessary to merge this into Airflow.

I think it would be useful to identify the failed job in the Airflow error message, which is something that this commit accomplishes (we have already found it useful in our deployments at Etsy).  For this to work without this airflow commit, it will be necessary for the DataProc error message to indicate the failed jobs.  @DanSedov can you provide guidance on whether the specific job failures will be surfaced in the top-level API `error` field once your fix is in place?

**Comment by kaxil** [comment]
@mchalek I guess we should then wait for the next release which should be in a week. If we would be now receiving the error message in the response itself, do you think we need this PR anymore?

**Comment by mchalek** [comment]
hi @kaxil , I heard from @DanSedov privately that he expected the DataProc new release to contain a high-level error message in the top level of the response, but that the failure information for individual jobs will likely remain in the metadata.  In this case, a small change to my PR would allow us to propagate job-specific failure messages into the Airflow task logs, which I think would be useful (the original PR already does this, but only when the top-level error field is not filled).  What do you guys think about this?

**Comment by kaxil** [comment]
I definitely think that the job-specific message would be useful. Is the new release out for Dataproc? If not, lets wait for it and then update the PR accordingly.

**Comment by DanSedov** [comment]
Hi @mchalek and @kaxil,
In the next few weeks Dataproc will begin to report shorter error messages for failed jobs. This will be of the form "Job step foo (jobId) failed". This replaces the current message "Job failed, see this log file gs:/...". User can always fetch the workflow (via gcloud command) to see all errors; and also fetch the job by id which is now captured in the message.

I feel strongly that Airflow should not _rewrite_ Dataproc error messages as this can only lead to confusion. I have no opinion or objection to collecting and _logging_ job errors, if that is useful.

**Comment by kaxil** [comment]
@fenglu-g Any thoughts on this?

**Pull request closed without merging**
