### PR TITLE
Auto-apply apply_default decorator

### PR DESCRIPTION
**Pull request by ashb**
Continuation of, and closes https://github.com/apache/airflow/pull/15044

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
As discussed on slack. We cannot do that, because we continue releasing providers from master, so the failure of that tests is precisely what should happen. 

We have the following options: 

1) Wait with merging it to just before we cut the branch for 2.1 release (i.e. before we release 2.1rc) - with ~2 weeks release timeline
2) Have a separate branch for providers-only release where we could cherry-pick provider's changes
3) Refactor code automatically for provider release process.

I think option 1) sounds like easiest to do (and it has very little drawbacks, the PR will simply have to be rebased periodically + removal of a new @apply_defaults.

**Comment by ashb** [comment]
That's _why_ I'm picking that this now, as it's what we are days away 2.1 release, and I was thinking that the small window of not being able to release providers was okay.

**Comment by potiuk** [comment]
Yeah. If it's 'days' then we can do option 2) cut the branch where we can cherry-pick any provider changes where we could relase providers from by cherry-picking if needed - just before merging this one, and yeah, in this case we can disable the "2.0" build and enable it back pointing to 2.1.0 right after the rc1  for 2.1.0 gets released. We'd then have to add `>=2.1.0rc1` for all priovider ->  airflow dependencies.

**Comment by ashb** [comment]
@potiuk Happy to merge this now?

**Comment by potiuk** [comment]
Absolutely. I will branch-off any changes in providers in case we need to release them with 2.0 compatibility.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
