### PR TITLE
[AIRFLOW-1527] Refactor celery config

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1527

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

The celery config is currently part of the celery executor definition.
This is really inflexible for users wanting to change it. In addition
Celery 4 is moving to lowercase.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Tests in other PR.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

cc: @saguziel @aoen

### CODE REVIEW

**Comment by saguziel** [comment]
lgtm

**Comment by Acehaidrey** [comment]
Question about this. To add extra configs to the celery executor, it seems I will still have to change the source code? Add them in to the default celery configs. Is that the intention?

**Comment by saguziel** [comment]
The intention is you would have your own python file as config

**Comment by saguziel** [comment]
I believe this is strictly a refactor

**Comment by saguziel** [comment]
You may be able to use PYTHONPATH to put your own but maybe that requires a config change as well

**Comment by Acehaidrey** [comment]
Thanks for the response @saguziel. That's fair, I think I  may have just assumed incorrectly. I thought there would be an option to drop our own configs by adding a file to the airflow.cfg or something like that.

**Comment by ashb** [comment]
I think that #2558 is a more generic version of this PR as it exposes a ('celery', 'celery_config_module') setting that lets the config in use be changed. This one simply refactors things, but doesn't present any way for the operator to change the celery config

**Comment by bolkedebruin** [comment]
cc @criccomini please hold off on merging. I like to update it to get rid of the extra config template.

**Comment by criccomini** [comment]
Test failed :(

**Comment by bolkedebruin** [comment]
@criccomini Test failures are unrelated (Docker?) now. Good news integration tests for Celery have now been added (using rabbitmq)

**Comment by criccomini** [comment]
+1 LGTM

**Pull request closed without merging**
