### PR TITLE
Documenting dag doc_md feature

### PR DESCRIPTION
**Pull request by dud225**
Dear Airflow Maintainers,

I added a note about DAG documentation.

Regards
dud

### CODE REVIEW

**Comment by mistercrunch** [comment]
Nice, thanks for the PR.
 +1

**Comment by bolkedebruin** [comment]
@dud225 in order to be able to merge can you connect it to a jira issue (create a new one if required)? This is for tracking and required by Apache. Thanks!

**Comment by dud225** [comment]
Sure. Just wanting for Jira being unlocked.

**Comment by dud225** [comment]
Here you are : https://issues.apache.org/jira/browse/AIRFLOW-121

**Comment by criccomini** [comment]
@dud225 sorry to be a pain about this--we don't have admin access to this repo--can you change the PR title and commit to:

```
[AIRFLOW-121] Documenting dag doc_md feature
```

**Comment by dud225** [comment]
Thanks.

**Pull request merged**
