### PR TITLE
Kubernetes tests are also run against the released airflow version

### PR DESCRIPTION
**Pull request by potiuk**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
CC: @aneesh-joseph

**Comment by dimberman** [comment]
@potiuk would this run on every master PR? Seems like it might make sense on pushes to 1-10-test but not on master.

**Comment by potiuk** [comment]
> @potiuk would this run on every master PR? Seems like it might make sense on pushes to 1-10-test but not on master.

It also makes sense on master.  I think we are going to release a chart from master that also works for latest released 1.10 version.. Ideally we should be able to release the helm chart from master (say with calver 2020.10.05 version that works nicely also for 1.10.11 image :).

**Comment by potiuk** [comment]
We already rin similar tests for backport packages for example - we take the latest released airflow and we test if all the 'latest'  backport packages can be installed with it.

**Comment by dimberman** [comment]
Ahh ok I see where you're coming from. Since this isn't taking in any code changes and is instead just running against the most recent release... Though that raises the question: Are there any situations that would work for the NEXT release but not the current one? Though I guess that's a bridge we can cross if we get there.

**Comment by potiuk** [comment]
> Ahh ok I see where you're coming from. Since this isn't taking in any code changes and is instead just running against the most recent release... Though that raises the question: Are there any situations that would work for the NEXT release but not the current one? Though I guess that's a bridge we can cross if we get there.

I think it should never be the case. We have the rule (which I think we even written down in README) that whenever we introduce a breaking change in what we release, we do deprecation first and make it backwards compatible as a rule.

**Pull request closed without merging**
