### PR TITLE
Add listeners for Dag import errors

### PR DESCRIPTION
**Pull request by pushpendu91**
---
This PR expands listeners API to be notified about DAG Import error when updating the import_errors table.

At present to identify DAG import errors, user have to refresh the UI or use Importerror REST API to get the import error details. And as there is no definite timeline( by next dag_parsing_interval) when the DAG will be parsed and import errors will be raised users need to keep on refreshing the UI or hit the API. 

With this PR Airflow itself will notify the listener about the addition of import error or existing import errors. And using the below events user can take action accordingly.

a. on_new_dag_import_error
b. on_existing_dag_import_error

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by amoghrajesh — COMMENTED** [review]
I would like to see some unit tests for this change as it is a change in behaviour.

Also, some expert in scheduler area to review it @uranusjr at the very least

**Comment by amoghrajesh** [comment]
Approved the workflow run also, watch out for CI results

**Comment by pushpendu91** [comment]
@amoghrajesh Thank you for reviewing the PR. I was trying to add test cases, but was not able to find an way how to pass a broken DAG . If someone can guide me on the same, that will be helpful.

**Comment by pushpendu91** [comment]
@amoghrajesh @uranusjr I have added the unit tests for the change and below is the test result from my local machine.
I kindly request you to review the change.

```
root@e316901b91ee:/opt/airflow# pytest tests/listeners/test_dag_import_error_listener.py
====================================================== test session starts ======================================================
platform linux -- Python 3.8.19, pytest-8.2.1, pluggy-1.5.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /opt/airflow
configfile: pyproject.toml
plugins: cov-5.0.0, rerunfailures-14.0, mock-3.14.0, custom-exit-code-0.3.0, timeouts-1.2.1, requests-mock-1.12.1, icdiff-0.9, time-machine-2.14.1, xdist-3.6.1, instafail-0.5.0, anyio-4.3.0, asyncio-0.23.7
asyncio: mode=strict
setup timeout: 0.0s, execution timeout: 0.0s, teardown timeout: 0.0s
collected 2 items                                                                                                               

tests/listeners/test_dag_import_error_listener.py::TestDagFileProcessor::test_newly_added_import_error PASSED             [ 50%]
tests/listeners/test_dag_import_error_listener.py::TestDagFileProcessor::test_already_existing_import_error PASSED        [100%]
============================================= Warning summary. Total: 1, Unique: 1 ==============================================
tests: total 1, unique 1
  runtest: total 1, unique 1
Warnings saved into /opt/airflow/tests/warnings.txt file.

======================================================= 2 passed in 2.79s =======================================================
root@e316901b91ee:/opt/airflow# 

```

**Comment by uranusjr** [comment]
Implementation looks OK to me at first glance.

**Review by amoghrajesh — COMMENTED** [review]
Looks good to me. @uranusjr WDYT?

**Comment by eladkal** [comment]
@pushpendu91 can you fix static checks?

**Comment by pushpendu91** [comment]
@amoghrajesh @eladkal Request you to please start the workflow, so that  static checks can be validated. I ran in my local using pre-commit but I was not getting any error.

**Comment by pushpendu91** [comment]
@amoghrajesh request you to please check the workflow. As it is not giving error in my local I am relying on the actual workflow here in github.

**Review by uranusjr — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by eladkal — CHANGES_REQUESTED** [review]
Can you also add the needed doc entry in https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/listeners.html

**Comment by pushpendu91** [comment]
@eladkal I have added the required documentation. Thank you.

**Review by eladkal — APPROVED** [review]

**Pull request merged**
