### PR TITLE
Warn on Webserver when using ``SQLite`` or ``SequentialExecutor``

### PR DESCRIPTION
**Pull request by kaxil**
image

Context: https://lists.apache.org/thread.html/r07e83f2462f08c4a52f6428b771a07e067ce9272b6256dca470a87fc%40%3Cdev.airflow.apache.org%3E
Note: Red flashes are for errors, we shouldn't use that.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
Is there a way to disable these and maybe set it in breeze? It’d be a bit annoying to see it show up when I’m absolutely just testing things…

**Comment by kaxil** [comment]
> Is there a way to disable these and maybe set it in breeze? It’d be a bit annoying to see it show up when I’m absolutely just testing things…

I can make it so that you don't see these error if unit_test mode is on: https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#unit-test-mode (`AIRFLOW__CORE__UNIT_TEST_MODE=True`) -- Will that suffice?

**Comment by uranusjr** [comment]
Sounds good to me

**Review by potiuk — APPROVED** [review]
❤️

**Comment by potiuk** [comment]
Love it! and the Unit-test exclusion as well :)

**Comment by potiuk** [comment]
One small thing though. I just double-checked that  `UNIT_TEST_MODE` is not set in Breeze by default. So when you run `start-airflow` the message will show up.

The UNIT_TEST_MODE is only set when we run tests (it's done using pytest  automated fixture). It used to be set long time ago but it's been removed when we switched to pytest.

The best way to check if you are in Breeze is to check BREEZE environment variable (set to "true").

**Comment by potiuk** [comment]
Maybe we could also check if airflow is installed in "editable" mode. Seems it is possible https://stackoverflow.com/questions/40530000/check-if-my-application-runs-in-development-editable-mode (@uranusjr - how reliable it might be  :) ?

**Comment by leahecole** [comment]
YAY. Love that you link to helpful documentation.

**Comment by potiuk** [comment]
> YAY. Love that you link to helpful documentation.

oh yeah. I noticed that and extra +1 from me on that one as well :)

**Pull request merged**
