### PR TITLE
[AIRFLOW-656] Add dag/task/date index to xcom table

### PR DESCRIPTION
**Pull request by criccomini**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-656

Per Apache guidelines you need to create a [Jira issue](https://issues.apache.org/jira/browse/AIRFLOW/).

Testing Done:
- Ran upgrade db locally:

```
INFO  [alembic.runtime.migration] Running upgrade 4addfa1236f1 -> 8504051e801b, xcom dag task indices
Done.
```

### CODE REVIEW

**Comment by mistercrunch** [comment]
You probably want to add the index definition to the model as well. Example here:
https://github.com/apache/incubator-airflow/blob/master/airflow/models.py#L737

**Comment by criccomini** [comment]
@mistercrunch please have a second look

**Comment by bolkedebruin** [comment]
+1

**Comment by bolkedebruin** [comment]
This is why we need a correct foreignkey for dag runs

**Pull request closed without merging**
