### PR TITLE
[AIRFLOW-6722] Solved bug related to being unable to blank out variables

### PR DESCRIPTION
**Pull request by andrewldesousa**
Previously, users were unable to blank out the value to an existing variable. Now, I have fixed this bug which should now allow users to blank out variable values.

---
Issue link: [AIRFLOW-6722](https://issues.apache.org/jira/browse/AIRFLOW-6722)

Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
I think it's nice but It likely needs some mention in https://airflow.readthedocs.io/en/latest/concepts.html#variables

**Comment by andrewldesousa** [comment]
@potiuk To be honest, I am not too sure what kind of mention you'd be referring to

**Comment by potiuk** [comment]
I mean that in the docs it should be mentioned that setting variable to '' is equivalent to not setting the variable at all (i.e. getValue will return None rather than '').

**Comment by andrewldesousa** [comment]
@potiuk Ok I've mentioned it in the docs. Let me know if there is anything else you think I should change

**Comment by andrewldesousa** [comment]
Aside from that, I am having trouble with both setting up my breeze environment and running from a venv.

I have followed all the steps but my problem with breeze is that when I run './breeze,' after having pulled the image, I get this: 

image

My problem with venv is when I follow the for authentication provided by https://airflow.apache.org/docs/stable/security.html, I get an error saying airflow.models has no attribute user. 

image

Maybe the authentication documentation needs to be addressed? Let me know.

**Comment by potiuk** [comment]
> Aside from that, I am having trouble with both setting up my breeze environment and running from a venv.
> 
> I have followed all the steps but my problem with breeze is that when I run './breeze,' after having pulled the image, I get this:
> 
> image
> 
Can you please run `./breeze --verbose` and send me the output (could be on slack for example).

> My problem with venv is when I follow the for authentication provided by https://airflow.apache.org/docs/stable/security.html, I get an error saying airflow.models has no attribute user.
> 
> image
> 
> Maybe the authentication documentation needs to be addressed? Let me know.

The Users table has been deleted in 2.0 - you should see the "latest" version of the docs which iss available here https://airflow.readthedocs.io/en/latest/security.html. This page is built from master sources and that's where the master "documentation". See README.md file :).

**Comment by potiuk** [comment]
Hy @andrewldesousa  -> I see I dropped the ball on this one - sorry - too many things at the same time. Do you want to still work on this/rebase to the latest master? We have many improvements in Breeze since then and hopefully, the problem you experienced then is sorted out now.

**Pull request closed without merging**
