### PR TITLE
removed unnecessary specifity and complication in contrib quickstart

### PR DESCRIPTION
**Pull request by yiannis-had**
Hey, I was setting up my environment to start contributing to airflow when I noticed that the CONTRIBUTORS_QUICK_START.rst document has outdated and over-complicated steps.

The pyenv project has a much better guide for installing it and we could instead use that one

### CODE REVIEW

**Comment by potiuk** [comment]
This is not only Pyenv, it's also many "system" dependencies that are needed to install airflow so this change is not good.

**Comment by yiannis-had** [comment]
You are mentioning the prerequisites which are literally the first sentence of what I linked in the commit

https://github.com/pyenv/pyenv/blob/master/README.md#prerequisites

**Comment by potiuk** [comment]
Ah I see i did not realise part of the prerequisites are there, However you missed the part whcih still needs to be there as it is not part of pyenv prerequisites:

```
openssl \
       sqlite default-libmysqlclient-dev libmysqlclient-dev postgresql
```

**Review by potiuk — CHANGES_REQUESTED** [review]
There are other pre-requisites than pyenv only and they should remain.

**Comment by yiannis-had** [comment]
Okay done

**Comment by potiuk** [comment]
Static checks are failing. I heartily recommend installing `pre-commit`

**Review by potiuk — APPROVED** [review]

**Pull request merged**
