### PR TITLE
Update mypy-boto3-appflow dependency 

### PR DESCRIPTION
**Pull request by potiuk**
After https://github.com/youtype/mypy_boto3_builder/issues/209
has been fixed and mypy-boto3-appflow released, we can now
remove the limit and intrduce lower-bound limit for it.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Just testing if post1 fixes the problem

**Review by o-nikolas — APPROVED** [review]

**Comment by o-nikolas** [comment]
Changes look good to me, but there are tests failing. I'm going to re-trigger those now, I suspect the failures are spurious.

**Comment by uranusjr** [comment]
The 3.11 failures seem to be consistent.

**Comment by potiuk** [comment]
> The 3.11 failures seem to be consistent.

Yeah. It also happened in main. This was caused by some dependency in 3.11 not pulling `future` library and one of our examples using import from `future` for urllib/urlsplit. Fixed in #33137 

Rebasing to apply it to this PR.

**Pull request merged**
