### PR TITLE
[AIRFLOW-870] Airflow Web UI "Mark Success" action not working properly

### PR DESCRIPTION
**Pull request by toddychen**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- *(https://issues.apache.org/jira/browse/AIRFLOW-870)*

Testing Done:
- Unittests]

### CODE REVIEW

**Comment by r39132** [comment]
@toddychen I'm testing this now

**Comment by r39132** [comment]
This doesn't work for me.

Given a graph as shown here :
screenshot 2017-02-13 13 55 31

In the tree view, If I mark success at the last task in the dag run and select `upstream` & `downstream`, it will set that task as success and ignore all upstream tasks as shown below.

screenshot 2017-02-13 14 01 26

If I then repeat that process by move upstream one task at a time for that dag run, marking each task success with `upstream` & `downstream`, then it will again only mark that single tasks success as shown in these 2 screen shots.

screenshot 2017-02-13 14 02 16

screenshot 2017-02-13 14 02 35

However, if mark post_op and its downstream as success as shown here as success:
screenshot 2017-02-13 14 05 21


I get the following error. This suggests that downstream success marking is not working for this PR.

screenshot 2017-02-13 13 50 12





Using an existing test dag :

**Comment by r39132** [comment]
If this PR dependent on #2074 ? If so, consider submitting them together. I can only test one at a time.

**Comment by toddychen** [comment]
@r39132 Hi, thanks for testing. I have mentioned the detail in https://issues.apache.org/jira/browse/AIRFLOW-870. There are two parts of the fix. This PR right now only solves No.1. So it can find the task. What you have right now is the "KeyError", that's No.2 due to the un-sync'ed behavior and implementation of "Recursive" option. So far, just always choose the option "Recursive" along with either "Upstream" or "Downstream". It will work okay.

**Comment by toddychen** [comment]
@r39132 The other PR just fix the bug that the code always does a "Downstream" for either "Upstream" or "Downstream" option clicked. (That is really bad.) With that PR, down is down, up is up. So here, with simply this PR, the following usage should work well:
1) select a single task, mark it success without any additional option selected.
2) select a task, mark it success with both "Downstream" and "Recursive" options selected. This will mark all downstream tasks.
3) If you also merge the other PR, then the same usage except changing "Downstream" to "Upstream" should work properly.

After all, this is just a temp fix, Bolke knows this issue and is planning a better fix and improvement in testing in v1.8.1.

**Comment by r39132** [comment]
I see. Thx. We may just wait for a holistic fix at this point. I'll keep these PRs for reference however.

**Comment by bolkedebruin** [comment]
@toddychen can you please close this issue?

**Comment by toddychen** [comment]
@bolkedebruin Sure. Thanks for the fix.

**Pull request closed without merging**
