### PR TITLE
Fix hot loop with a burst of log messages (#28778)

### LINKED ISSUE #28778: Script "clean-logs.sh" has an unexpected burst behavior
### Apache Airflow version

2.5.0

### What happened

I've noticed that my Airflow Scheduler logs are full of the following message:

    Trimming airflow logs to 15 days.
    Trimming airflow logs to 15 days.
    ...

My deployment uses the Helm chart, so it's probably specific to the Docker related assets.
This script has a loop where every 900 seconds it will delete old log files. However, on every activation, the part where it prints the 
log message and deletes the file is burst a few hundred times in less than a second. The cycle repeats.

### What you think should happen instead

It should only print one log message (and delete files once) on every cycle.

### How to reproduce

Just comment out the lines regarding the actual file deletion and run it in any bash shell. It should get triggered after 15 minutes.

### Operating System

openSUSE Tumbleweed

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ivarec**
closes: #28778

Fixes a very small issue where a hot loop in the clean-logs.sh script could cause a burst of a few hundred log messages without need.

### CODE REVIEW

**Comment by ivarec** [comment]
Hmm about the failed test: I probably missed a step where this Dockerfile gets created from the modified script. Can someone more knowledgeable help with this? First time contributor here :)

**Comment by ivarec** [comment]
@potiuk sorry for mentioning you if this is not correct, but you are my sole contact so far :smile_cat:

**Comment by uranusjr** [comment]
Please fix the pre-commit issues.

**Comment by ashb** [comment]
@ivarec `pip install pre-commit && pre-commit run` should do it hopefully.

There are more detailed instructions on https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst#id3

**Review by uranusjr — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by smktpd** [comment]
AirFlow 2.10.2: it still prints the message more than once (well, twice) every time it trims logs:
```
2025-10-09T13:30:00.551115120+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
2025-10-09T13:30:01.565594720+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
2025-10-09T13:45:00.581744198+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
2025-10-09T13:45:01.595607729+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
2025-10-09T14:00:00.612044052+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
2025-10-09T14:00:01.625865589+03:00 dag-processor-log-groomer Trimming airflow logs to 15 days.
```

**Pull request merged**
