### PR TITLE
[AIRFLOW-2037] Add methods to get Hash values of a GCS object

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2037

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Added `get_md5hash` and `get_crc32c` in `gcs_hook` to aid in Data integrity validations.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
GCS does not have unit tests

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @criccomini

**Review by jgao54 — APPROVED** [review]
lgtm

**Comment by kaxil** [comment]
cc @Fokko

**Comment by Fokko** [comment]
Please rebase against master to trigger a new build. The CI should be fixed.

**Comment by kaxil** [comment]
@Fokko Getting the same build error:
```
PermissionError: [Errno 13] Permission denied: '/home/travis/.wheelhouse/Flask_Admin-1.5.0-py3-none-any.whl'
ERROR: InvocationError: '/home/travis/build/apache/incubator-airflow/.tox/py35-backend_mysql/bin/pip wheel -w /home/travis/.wheelhouse -f /home/travis/.wheelhouse -r scripts/ci/requirements.txt'
___________________________________ summary ____________________________________
ERROR:   py35-backend_mysql: commands failed
```

**Comment by Fokko** [comment]
I cheered too early. It should be fixed now 👍

**Comment by kaxil** [comment]
@Fokko  No Problem 👍 . This Passed the Travis CI test and looks ready to be merged.

**Comment by Fokko** [comment]
Sure @kaxil thanks for your patience and contribution!

**Pull request closed without merging**
