### PR TITLE
Remove conn.close() ignores

### PR DESCRIPTION
**Pull request by uranusjr**
Continuation of #28995

### CODE REVIEW

**Comment by uranusjr** [comment]
Uh… this works?

**Review by ephraimbuddy — APPROVED** [review]

**Comment by potiuk** [comment]
This worked accidentally. I believe you broke all people's PRs this way. Constraints were not yet refreshed when you merged and you used old version of mysql-connector-python in this PR.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/pull/29010 reverts it for now. 

Some more context:

The thing with constraints is that they require a successful main build to get refreshed. This can take anything between 30 minutes up to several hours (depending on subsequent merges - if you merge several commits one after another, they will cancel running "main" builds and it might take multiple hours undil the main "green" build refresh the constraints.

Until then all regular PRs (like this one) which do not change setup.py or provider.yaml are using old constraitns.

**Comment by potiuk** [comment]
The status of constraints refresh can be tracked here @uranusjr: https://github.com/apache/airflow/commits/constraints-main and once it gets refresh you will be able to re-attempt to fix the exclusions :)

**Comment by potiuk** [comment]
This could be retried now: https://github.com/apache/airflow/commit/5ec488f2d03773ebf4c238033d87e5f43e8ad4ac as constraints got updated (and mysql-connector-python is updated).

**Pull request merged**
