### PR TITLE
[AIRFLOW-2636] Fix Nonetype error for task failure instance duration

### PR DESCRIPTION
**Pull request by tssujt**
### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-2636

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by tssujt** [comment]
Rebased @feng-tao

**Comment by OmerJog** [comment]
There is a pending previous PR https://github.com/apache/airflow/pull/4032  and @ashb requested unit tests before the PR can be merged.

**Comment by OmerJog** [comment]
@tssujt did you have time to work on this?

**Comment by tssujt** [comment]
I found it was fixed in #5178

**Comment by OmerJog** [comment]
@tssujt This probably will need a fix to the old UI as well as https://github.com/apache/airflow/pull/5178 only fix it in the RABC UI. Maybe you can convert this PR to target the v10 test branch? Better ask @kaxil  what he thinks.

**Comment by tssujt** [comment]
@OmerJog The v1-10-test branch has already fixed this.

**Comment by kaxil** [comment]
We don't need this anymore as it was already resolved by https://github.com/apache/airflow/pull/5178/files.

Can you please close the PR and the related JIRA Issue? @tssujt

**Comment by tssujt** [comment]
OK

**Comment by tssujt** [comment]
@kaxil The JIRA issue is not opened by me.

**Comment by kaxil** [comment]
I have closed that. Thanks @tssujt

**Comment by OmerJog** [comment]
@kaxil  need also to close https://github.com/apache/airflow/pull/4032

**Pull request closed without merging**
