### PR TITLE
[AIRFLOW-2860] DruidHook: time variable is not updated correctly when…

### PR DESCRIPTION
**Pull request by awelsh93**
… checking for timeout

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
        I ran `nosetests /tests/hooks/test_druid_hook.py`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Good catch @awelsh93 Thanks

**Comment by awelsh93** [comment]
Hey @Fokko, thanks for your quick response. I've noticed some of the Travis jobs have failed - specifically for test_submit_timeout in `tests.hooks.test_druid_hook.TestDruidHook`. It seems like a timeout of 0 means this change gets stuck in a loop where `sec` gets incremented by 0 and hence will never be greater than `max_ingestion_time`.

What course of action do you recommend?

**Comment by Fokko** [comment]
@awelsh93 Thanks for the quick response. Maybe add an assert that the `timeout` has to be positive. Feel free to change the test as well.

**Comment by Fokko** [comment]
@awelsh93 I've reverted the commit for now since it fails the build. Could you create a new PR with the fixed test?

**Comment by awelsh93** [comment]
@Fokko Thanks for your comments, I've created a new pull request (#3710)

**Pull request merged**
