### PR TITLE
Update CONTRIBUTORS_QUICK_START.rst in terms of Docker Engine

### PR DESCRIPTION
**Pull request by tiokim**
It would be nice if the docker installation guide is updated according to the latest  [official instruction](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository).

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by XD-DENG — COMMENTED** [review]
Hi @t25kim , seems to me the main change here is the remove the usage of Docker Compose here?

May you clarify a bit more what you meant by "updated according to the latest official instruction"?

**Comment by potiuk** [comment]
> May you clarify a bit more what you meant by "updated according to the latest official instruction"?

These are instrunctions: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository - and it looks cool

**Comment by t25kim** [comment]
> Hi @t25kim , seems to me the main change here is the remove the usage of Docker Compose here?
> 
> May you clarify a bit more what you meant by "updated according to the latest official instruction"?

Hi @XD-DENG and @potiuk, Thank you very much for the comments!
I opened this PR to resolve the warnings caused by the out of date docker installation instruction. Docker compose also has been updated.
Please refer to the warning logs below.

```sh
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
Repository: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable'
Description:
Archive for codename: jammy components: stable
More info: https://download.docker.com/linux/ubuntu
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-https_download_docker_com_linux_ubuntu-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-https_download_docker_com_linux_ubuntu-jammy.list
Ign:1 cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy InRelease
Hit:2 cdrom://Ubuntu 22.04.1 LTS _Jammy Jellyfish_ - Release amd64 (20220809.1) jammy Release
Get:4 https://download.docker.com/linux/ubuntu jammy InRelease [48.9 kB]                                                    
Get:5 https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages [9,481 B]                                        
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease                          
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Fetched 58.3 kB in 1s (66.3 kB/s)
Reading package lists... Done
W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
```

**Comment by t25kim** [comment]
I don't remove the Compose standalone installation instruction since many source files use `docker-compose`.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
