### PR TITLE
feat: support rendering ObjectStoragePath value

### LINKED ISSUE #40361: ObjectStoragePath should be template-able
### Description

`ObjectStoragePath` should be able to handle Jinja Templates

### Use case/motivation

If I have an operator, that has an ObjectStoragePath argument
```
class MyOperator(BaseOperator):
  template_fields = ('path',)

  def __init__(path, **kwargs):
    self.path = path
    super().__init__(**kwargs)
```
and am using it in a DAG, with templating
```
MyOperator(
  ...,
  path=ObjectStoragePath(
    "s3://my_bucket/foo/{{ ds_nodash }}/file.csv",
    conn_id="s3"
  )
)
```
Templating didn't seem to work 

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by gyli**
Closes: https://github.com/apache/airflow/issues/40361

Support jinja variable to be rendered in ObjectStoragePath as an operator argument.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Could you please add a unit test covering it?

**Comment by gyli** [comment]
@potiuk Test added. Please review again.

**Comment by gyli** [comment]
Hi @eladkal could you plz review?

**Review by potiuk — APPROVED** [review]

**Comment by fritz-astronomer** [comment]
Awesome! Thanks @gyli ! Excited for this

**Pull request merged**
