### PR TITLE
[AIRFLOW-3695] Replace Flake8 by Pylint

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3695
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Following the [dev mailing list about AIP-6](https://lists.apache.org/thread.html/90c3f38fbda49eca772b32cb55a6274ff2c536e6ecdcaf706ea87826@%3Cdev.airflow.apache.org%3E), I replaced Flake8 by Pylint. I choose Pylint because it's a widely used tool, very configurable and is already used here and there [in Airflow itself](https://github.com/apache/airflow/search?q=pylint&unscoped_q=pylint).

On top of the default Pylint configuration (see .pylintrc), I set some sensible defaults:
```
disable=comprehension-escape,
        pointless-statement,
        invalid-name,
        duplicate-code,
        abstract-method,
        bad-continuation

ignored-argument-names=_.*|^ignored_|^unused_|args|kwargs (added args & kwargs)

max-args=15

min-public-methods=1
```

Pylint is much stricter than Flake8 and I'm sure it will lead to some discussion about the configuration in the beginning. However I'm convinced in the long run it will lead to much more consistent code. This PR adds and applies Pylint only on changed lines compared to master with the help of [diff-cover](https://github.com/Bachmann1234/diff-cover). I see it as an intermediate solution, until the entire Airflow codebase is Pylint-compliant and we can simply run Pylint on complete changed files.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `Pylint`

### CODE REVIEW

**Comment by feluelle** [comment]
Hey @BasPH, I like your proposal  to use pylint to have cleaner code because like you said pylint has more strict rules by default but I actually would be even more strict in that sense that we would add it instead of replacing it and use both flake8 + pylint because flake8 has some checks that even pylint does not have I believe. At work we use both for our custom airflow plugins and it is working great.

**Comment by BasPH** [comment]
Whoops Pylint made the sensible choice to drop Python2 support with Pylint2 which I'm installing and now the tests are failing. Will check tonight.

**Comment by BasPH** [comment]
@feluelle I thought Flake8 checks only PEP8 + logic, and PyLint does that too + code smells + more. Will investigate more how they overlap tonight.

**Comment by feluelle** [comment]
@BasPH Thank you. Maybe I am wrong and we only need pylint. That would be great to know :)

**Comment by feng-tao** [comment]
I think we should send out an email with a title [VOTE] to get three binding votes to close the loop for this AIP.  But I am +1 on having this.

**Comment by diraol** [comment]
Just adding here that it would be good to check [Prospector](https://github.com/PyCQA/prospector) too.

It seems to "replace" both pylint and flake8 and also add some other features. Actually it is more an integration testing tool than a replacement, but still worth looking. =)

**Comment by max-sixty** [comment]
I haven't been involved as an airflow developer, but saw this on the mailing list and thought it would be helpful to comment given my experience with code formatters on half-a-dozen python projects:

I've generally had negative experiences with pylint, and I'm not aware of projects having much success with it, relative to flake8 or increasingly black (which is a larger change, and [doesn't operate on diffs](https://github.com/ambv/black/issues/134)). 

Are there _any_ large python projects using pylint? 
Projects successfully using flake8 include pandas, sqlalchemy, xarray, django

**Comment by BasPH** [comment]
Closed issue in favour of https://github.com/apache/airflow/pull/5238. We will apply both Flake8 and Pylint in the near future.

**Comment by potiuk** [comment]
Yep. Good idea to keep both..  Both have slightly different scope and can be configured to work in parallel.

**Pull request closed without merging**
