### PR TITLE
Add release management command to retreive provider version metadata

### PR DESCRIPTION
**Pull request by potiuk**
This new command will refresh and store generated provider version metadata - including the time when provider has been released and which airflow version it has been associated with.

This information will eventually be used in generating provider's changelogs, and it will be used to generate provider-specific dependencies (we need to know which airflow version provider specific dependencies should be compared with).

This is the next step in publishing SBOM information, but it will also be accompanied by updating more information for past releases of the providers.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey Everyone - this is the next step in building more information about our packages (including SBOM information) - getting historical information about providers which can be easily updated and refrehsed. 

We will need this one in the next steps, when we will use the information to generate SBOM information for providers, but also to improve provider's CHANGELOG in the future.

**Comment by potiuk** [comment]
(see https://github.com/apache/airflow/pull/32119/files#diff-546c8884e1520ba1e582bd392f6280d1c15037bd6705efbfbc6fd339de794ec7 - it will show the results that we get from running it).

**Comment by potiuk** [comment]
cc: @eladkal - I will plug it in the release preparation process as one of the next steps. I just want to add one thing at a time.

**Review by utkarsharma2 — APPROVED** [review]

**Review by pankajastro — APPROVED** [review]
LGTM

**Pull request merged**
