### PR TITLE
Fix visible DagRun doesn't point to the same dag run id

### LINKED ISSUE #35946: Visible DAG RUN doesn't point to the same dag run id
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Hi,
I was checking out airflow 2.7.2 and I've noticed that the dag run (which is visible above the graph) doesn't corresponds with logical date being passed down to the sensor/operator nor to the dag run id visible in the details view.
It looks like the data_interval_end is what being shown.
This will cause confusion among the users!

I've noticed that manually triggered dag run behave like expected(like previous releases)

The file which I included shows the problem.

Screenshot 2023-11-28 at 9 38 57

### What you think should happen instead

I think you should go back to the previous way of showing the active dag run.
Meaning that the visible dag run id will correspond with the logical date and not with data_interval_end

### How to reproduce

1. Create a dag with at least one sensor/operator
2. let it be trigger by the scheduler
3. View the visible run , dag run id, and the grid 

### Operating System

amazon-linux:2023

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==7.6.0
apache-airflow-providers-databricks==4.5.0
apache-airflow-providers-docker==3.7.5 

### Deployment

Amazon (AWS) MWAA

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by lotrias17**
As stated by @nivdror, displaying a DAG RUN date different from the dag run id may cause confusion to users. I fixed this by changing the default displayed date to the Interval Start Date instead of Interval End Date.

closes: #35946

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
For me this looks good but I am only 90% certain if this is "right". @bbovenzi Can you double check before merge?

**Comment by jedcunningham** [comment]
Gentle bump @bbovenzi. I do wonder if both places should use logical_date instead though.

**Comment by bbovenzi** [comment]
Let's go for logical date then

**Review by Taragolis — APPROVED** [review]

**Comment by lotrias17** [comment]
Is there anything I could contribute to help merge this Pull Request?

**Pull request merged**
