### PR TITLE
Use sqlalchemy engine with pandas in MsSqlHook (apache#28969)

### LINKED ISSUE #28969: "UserWarning: pandas only supports SQLAlchemy connectable" when calling MsSqlHook pandas methods
### Apache Airflow Provider(s)

microsoft-mssql

### Versions of Apache Airflow Providers

apache-airflow-providers-microsoft-mssql==3.3.2
pymssql==2.2.7

### Apache Airflow version

2.5.0

### Operating System

Ubuntu 20.04.5

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

1.- Init a local MSSQL server database:

docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=********' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest

```
create database TEST;
use TEST;
create table test (
   id int not null,
   description varchar(50) not null);
insert into test values (1, 'test 1'), (2, 'test 2');
```

2.- Create an example DAG:

```
from airflow import DAG
from airflow.utils.dates import days_ago
from airflow.operators.python import PythonOperator
from airflow.providers.microsoft.mssql.hooks.mssql import MsSqlHook

default_args = {
    'owner': 'Axesor',
    'start_date': days_ago(1)
}


def show_the_warning():
    sql_hook = MsSqlHook(mssql_conn_id="localhost_test")
    print(sql_hook.get_pandas_df("select * from test"))


with DAG(
    'example',
    schedule_interval=None,
    default_args=default_args
) as dag:
    the_task = PythonOperator(
        task_id = "show_the_warning",
        python_callable = show_the_warning
    )

```

### What happened

When using MsSqlHook with Pandas we receive the following warning:

```console

[2023-01-16, 10:39:09 UTC] {logging_mixin.py:137} WARNING - ...***/providers/common/sql/hooks/sql.py:191 **UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy**.
```

### What you think should happen instead

Warning should not be appearing.

### How to reproduce

Just execute the example DAG and look at the task log.

### Anything else

This is not blocking right now but it can raise future deprecation issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rkarish**
Closes: apache#28969

### CODE REVIEW

**Comment by potiuk** [comment]
Oh. That's a MUCH better fix :)

**Comment by potiuk** [comment]
Can you please add a test for that one ? It's always very suspicious to see that a change in behaviour does not require any tests to fix - indicating that we miss some tests most likely.

**Comment by Taragolis** [comment]
Hmmm... Seems like it only fixes MS SQL now but not other providers which still directly provide incompatible connection

**Comment by potiuk** [comment]
> Hmmm... Seems like it only fixes MS SQL now but not other providers which still directly provide incompatible connection

I guess there should be PR for all of them separately then. And maybe the second time we do it, we generalize that (if possible). This is the usual approach I take (let's make things usable first in order to make them re-usable :D).

**Comment by rkarish** [comment]
At first I went for the attempt of changing it to use sqlalchemy engine in the `DbApiHook` but it breaks a *lot* of tests, but all of the majority of the tests follow the same pattern, so not a super big deal. For a second last night I was thinking maybe it was isolated to `MsSqlHook` but apparently it's not. I would like to fix it for everything by making change in `DbApiHook` but I cannot find a good way to fix a ton a failing tests due to using sqlalchemy engine breaking the mocking. SQLite was the only one easy to test. Even for this small PR I don't know what approach to take for testing, I've tried several so far no avail, except for testing SQLite, that was easy and didn't require any mocking. If anyone could weight in on how to test this code successfully for `MsSqlHook` specifically, then I think I can start fresh, *again* 😆, and go for the initial approach and use the same pattern to fix all of the failing tests for provides that test `get_pandas_df()` (pinot, bigquery, drill, elastic search etc...).

I do think that that this should be addressed, but I think UserWarning is less serious than FutureWarning in pandas, and if it works it works, although not tested on pandas side. I use pandas a lot at work and SQL Server is one of the databases we use. I stayed away from this method naturally, I knew it was there and never felt like it benefited me to use, and I just use the hook to get the engine with the airflow connection and use `pd.read_sql()` instead.

Do this we should try to fix the warning though, I'm just lost with how to mock out `self.get_sqlalchemy_engine()` method call that is inside of the method being tested. If someone could help figure out a testing approach, I will go with the fix everything approach, and use the same pattern to updating all of the tests.

**Comment by Taragolis** [comment]
Well the problem in SQL provider, so I think we need to fix it SQL Provider, rather then adopt fix to single Provider.
We need to adopt only on cases when SQLAlchemy not effectively return data for data frame, or it is better approach exists. Ideally `get_uri` (BTW why not `get_sqlalchtmy_uri` ?) should return not implemented in DBApiHook but I think we can't do that

Issue No 1:

SQL Provider expect than Airflow Connection URI always provide valid SQLAlchemy URI
https://github.com/apache/airflow/blob/a1ffb26e5bcf4547e3b9e494cf7ccd24af30c2e6/airflow/providers/common/sql/hooks/sql.py#L162-L170

But I don't think it is valid case for most of Providers, see:
1. MySQL not implemented but Hook itself could use two different drivers
2. Postgres implement `get_uri` method, AFAIK we use in some arguments internally which is not SQLAlchemy compatible and if user provide them then `get_sqlalchemy_engine` wouldn't work
3. ODBC potentially should work
4. Oracle, would return incorrect SQLAlchemy URI
5. MS SQL potentially return correct SQLAlchemy URI
6. AWS Redshift potentially return correct SQLAlchemy URI
7. Presto/Trino I don't think it would work
8. Snowflake - should work
9. Exasol - I don't think it work
10. Impala - Due to implementation I guess not work
11. PinotDb - It implements something strange
12. Vertica - Due to implementation I guess not work

Issue 2:

Incorrect implementation for `pandas.read_sql`

https://github.com/apache/airflow/blob/a1ffb26e5bcf4547e3b9e494cf7ccd24af30c2e6/airflow/providers/common/sql/hooks/sql.py#L183-L222

**Comment by Taragolis** [comment]
For particular this issue it is should work #29095. And I think we could apply in case if we test it.
But this solution shouldn't be a generic approach for all other cases

**Pull request closed without merging**
