### PR TITLE
Check Logging Handlers and Secret Backends for recursion

### PR DESCRIPTION
**Pull request by potiuk**
Logging Handlers and secret backends have the potential of triggering Import/Attribute error due to circular imports. This check will attempt to import all those classes from our providers via airflow_local_settings, which should detect the case where such circular import condition is generated.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
This should prevent any future errors where any of the logging handlers or secrets backend might trigger circular imports via airflows settings:

This is how it will look like:

Screenshot 2023-05-18 at 14 45 18


Are there any other ways we can trigger the circular import besides logging and secret backends ?

**Review by ashb — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Comment by ashb** [comment]
We can't merge this until #31379 or something like it is fixed right?

**Comment by potiuk** [comment]
> We can't merge this until #31379 or something like it is fixed right?

Right. It should fail.

**Review by vincbeck — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by dstandish — APPROVED** [review]

**Comment by potiuk** [comment]
Rebased after https://github.com/apache/airflow/pull/31379

**Comment by potiuk** [comment]
Ok. It seems to work !

**Pull request merged**
