### PR TITLE
[AIRFLOW-2737] Restore original license header

### PR DESCRIPTION
**Pull request by seelmann**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2737

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
    - The original license header in airflow/api/auth/backend/kerberos_auth.py was replaced with the ASF one. This PR restores the original license header.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
Ooops good spot.

@bolkedebruin This should possibly go into 1.10 - 1.9 has the correct license.

**Comment by bolkedebruin** [comment]
Mmm maybe. It is not equal to the original though, but maybe close enough

**Comment by feng-tao** [comment]
I wonder why this file should have a different license header?

**Comment by seelmann** [comment]
@feng-tao The file was developed by a third-party: https://github.com/mkomitee/flask-kerberos/blob/master/flask_kerberos.py. According to https://www.apache.org/legal/src-headers.html#3party it must not contain the standard ASF header then. There would have been the option to remove the license header completely because the license is also in licenses/LICENSE-flask-kerberos.txt, but with the header is more explicit.

**Comment by feng-tao** [comment]
thanks @seelmann for the info. Make sense.

**Comment by ashb** [comment]
@seelmann Sorry we somehow missed this from a number of the point releases. It's been right in master but not in the 1.10.x published releases 🤦‍♂ - 1.10.4 will _finally_ include this.

**Pull request closed without merging**
