### PR TITLE
Order bug report fields by importance

### PR DESCRIPTION
**Pull request by BasPH**
I felt the bug report form was confusing to read, because you start with some issue in mind, and first have to work through "what version", "what deployment", etc. before getting to actually reporting the bug.

This PR places "What happened", "What you expected to happen", "How to reproduce" at the top (and makes "What happened" a required field), which to me feels like a better order.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
I like it. I wonder what others think?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I like it a lot actually :)

**Comment by jedcunningham** [comment]
I think I'd rather see the Airflow version still at the top, otherwise I like it as well.

**Comment by potiuk** [comment]
Good for me with Airflow version too.

**Comment by BasPH** [comment]
Moved the version dropdown to the top:
image

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Looks Great to me :)

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
