### PR TITLE
added a hive -> vertica operator

### PR DESCRIPTION
**Pull request by ezvz**
Modeled on the hive -> mysql operator. 

One thing I noticed was that the test_hive_to_mysql function is in the HivePrestoTest class. I put my test_hive_to_vertica function in the TransferTests class, as that seemed more appropriate.

### CODE REVIEW

**Comment by mistercrunch** [comment]
@varantz thanks for your contribution! 

After thinking a bit through this it doesn't make sense to insert one row at a time in Vertica (since it's a column store) and the hook's `insert_rows` should probably overridden while using this:
https://pyvertica.readthedocs.org/en/latest/#pyvertica.batch.VerticaBatch.insert_list

@griffinqiu, are you interested in this operator?

**Comment by ezvz** [comment]
Ah, good call on using a batch insert. However, I think we would want to use the insert_lists (plural), as opposed to the insert_list function you linked. The function is not documented in https://pyvertica.readthedocs.org/en/latest/ because it looks like that's pointing to v1.5.2, and insert_lists was introduced in 1.5.3.

But if you looks here: https://pypi.python.org/pypi/pyvertica under the 1.5.3 summary it says: "add insert_lists method to VerticaBatch. This method takes multiple lists, converts them to rows, and invokes a single insert rather than one insert per row." So it looks like this is what we want?

I don't know why /latest/ points to 1.5.2, looks like the project is past 1.6, so I think the method should be stable.

**Comment by mistercrunch** [comment]
Sounds right. Don't feel obligated but `insert_lists` would be the way to go.

**Comment by patrickleotardif** [comment]
Closing for now. We can add more Vertica support by referencing this if needed later.

**Pull request closed without merging**
