### PR TITLE
Convert example_ecs_fargate.py to an AIP-47 system test

### PR DESCRIPTION
**Pull request by ferruzzi**
Follows the template set forward in https://github.com/apache/airflow/pull/24643

Also cleans up and makes some required changes within the SystemTestContextBuilder to account for occasionally needing to split the imported variables such as a list of Subnets in this test.

### CODE REVIEW

**Comment by ferruzzi** [comment]
Huh.  Where did those come from.... :eyes:

**Comment by potiuk** [comment]
> Huh. Where did those come from.... 👀
> 
> Looks like the same tests are failing in main, so it's something that was changed in the last couple of days. I'm heading out for a mini roadtrip with the family, I'll try to figure this out on Monday if it's still a problem.

have a great trip - nope. it looks like error when importing the tests :). But it can easily wait - no problem whatsoever :)

**Comment by ferruzzi** [comment]
> nope. it looks like error when importing the tests :).

Yeah, what I meant by that is when I rebase and check out main, those tests still fail.  So we know:

1) The cause is not something in this PR since it's also failing locally on the main branch.
2) They were all passing when they were merged or we'd have seen this before.  
3) They were all passing locally before I rebased, which means whatever changed and broke them was early last week between my last two rebases. 

Anyway, I'm home and I'll poke it today and see what I can find.  :+1:

**Comment by ferruzzi** [comment]
Closing while I sort this out.

**Pull request closed without merging**
