### PR TITLE
Allow disabling periodic committing when inserting rows with DbApiHook

### PR DESCRIPTION
**Pull request by underyx**
``` python
>>> i = 1
>>> commit_every = 0
>>> bool(i % commit_every == 0)  # previously
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
>>> bool(commit_every and i % commit_every == 0)  # with this change
False
```

### CODE REVIEW

**Comment by mistercrunch** [comment]
It would be nice if you added a definition of the parameters in the docstring, their expected types and special cases (like handling of `0`) you just added. There are examples in the codebase as to what the param should be for the auto-docs to format it nicely. Are you up for it?

**Comment by underyx** [comment]
Yeah, why not, @mistercrunch. I'll do it later today, hopefully.

**Comment by underyx** [comment]
@mistercrunch well I guess I didn't do it 'later that day' in the end. PR might be ready to merge now, though!

**Comment by r39132** [comment]
@underyx Please squash commits and ping me on gitter when ready to merge again

**Pull request merged**
