### PR TITLE
[AIRFLOW-3819] - Allow the configuration of a global default for work…

### PR DESCRIPTION
**Pull request by atrbgithub**
…imits and requests

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3819

### Description
Currently the kubernetes executor allows you to specify pod resources requests and limits (cpu and memory). For example:
```
# Limit resources on this operator/task with node affinity & tolerations
three_task = PythonOperator(
    task_id="three_task", python_callable=print_stuff, dag=dag,
    executor_config={
        "KubernetesExecutor": {"request_memory": "128Mi",
                               "limit_memory": "128Mi",
                               "tolerations": tolerations,
                               "affinity": affinity}}
)
```
These values are used by kubernetes when making scaling decisions. This PR allows you to specify a global default for these values, to ensure that each pod airflow creates has a value specified for these properties.
You are still able to modify these values on a dag by dag basis. 

### Tests

There are currently no tests around configuring resources limits/request values as used in the example above, and these would be non-trivial to add due to the integration with kube_client. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.

`default_airflow.cfg` has been updated with the new settings with a descriptive comment and a link to the Kubernetes documentation. 

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by XD-DENG** [comment]
Personally I don't think it's necessary to add them into the Airflow configuration file. Users should specify them explicitly or specify global defaults from K8S side. The `.cfg` file is already quite "big" on the other hand.

**Comment by PaulW** [comment]
Setting this directly from within k8s (in my case through helm) does indeed work, for example:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: worker-pod-limit
spec:
  limits:
  - default:
      memory: 1000Mi
      cpu: 1
    defaultRequest:
      memory: 500Mi
      cpu: 0.5
    type: Container
```

Has this effect within the yaml config for the pod:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.202.6.197/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      base; cpu, memory limit for container base'
...
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
```

**Comment by PaulW** [comment]
Setting this directly from within k8s (in my case through helm) does indeed work, for example:

```
apiVersion: v1
kind: LimitRange
metadata:
  name: worker-pod-limit
spec:
  limits:
  - default:
      memory: 1000Mi
      cpu: 1
    defaultRequest:
      memory: 500Mi
      cpu: 0.5
    type: Container
```

Has this effect within the yaml config for the pod:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: x.x.x.x/32
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      base; cpu, memory limit for container base'
...
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
```

**Comment by atrbgithub** [comment]
Going to close this. We tested with the above ( defaults set at the namespace level) which solves the problem outside of airflow.

**Comment by danieltahara** [comment]
I actually don't think this is a problem best solved at the Kubernetes level. Since LimitRanges are applied as a namespace default, the more tenants you have the less useful those ranges are going to be (because they'll have to be uselessly wide). There isn't a good reason that Airflow should be creating pods without memory limits or not providing that configuration option out of the box. It makes binpacking and cluster autoscaling much harder, since the pods will schedule effectively anywhere.

Is there any chance of re-opening this?

**Comment by fritzdavenport** [comment]
Agreed w/ @danieltahara - creating pods with no resource requests or limits, and relying on a user having namespace defaults is definitely not good practice. 
This seems like a fundamentally basic feature for any pod - and that anything launching pods should account for

**Comment by lihan** [comment]
Same problem here, pretty surprised this has to solved with Kubernetes. 
Can we add the features to Airflow? Also, this same functionality exists in Mesos Configuration within Airflow.  
@atrbgithub

**Comment by tylux** [comment]
Can this get revisited? This goes against Kubernetes best practices to rely on a different mechanism i.e dag code to set the resource limits instead of standard pod limits.

**Pull request closed without merging**
