### PR TITLE
[AIRFLOW-2607] Fix failing TestLocalClient

### PR DESCRIPTION
**Pull request by verdan**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2607/) issues and references them in the PR title.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
This fixes a test case that is failing. Tested it using docker environment

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Any idea why this would not fail on Travis?

**Comment by verdan** [comment]
@Fokko, not entirely sure, but I believe the DAG id i.e., `test_start_date_scheduling` is used in other places, and because of that it remains in the system when you run this as a whole suite. But when you run the api tests (`tests/api`) separately, it fails.
for example: `tests/dags/test_scheduler_dags.py`

**Review by Fokko — CHANGES_REQUESTED** [review]
This is both for the `test_start_date_scheduling ` and `example_bash_operator `:
https://github.com/apache/incubator-airflow/search?q=example_bash_operator&unscoped_q=example_bash_operator
https://github.com/apache/incubator-airflow/search?q=test_start_date_scheduling&unscoped_q=test_start_date_scheduling

Maybe we can give it an unique name? Also maybe refactor the code a bit. Instead of having four strings in the code, maybe assign the `dag_id` to a variable with a sensible name.

**Comment by verdan** [comment]
Assigned the `dag_id` to a variable name. 
Still used `example_bash_operator` as the DAG ID, as I am including the example DAGs in this test file. `models.DagBag(include_examples=True)` 
So, it would run separately just fine.

**Review by Fokko — APPROVED** [review]
LGTM, thanks @verdan 

Looking forward to your work ;)

**Pull request closed without merging**
