### PR TITLE
[doc] Fix copy path in S3 to redshift

### PR DESCRIPTION
**Pull request by zhongjiajie**
Correct S3 copy path in S3 to redshift operator in amazon providers

### CODE REVIEW

**Comment by zhongjiajie** [comment]
According to https://github.com/apache/airflow/blob/602abe8394fafe7de54df7e73af56de848cdf617/airflow/providers/amazon/aws/transfers/s3_to_redshift.py#L120 we know that the path transfer operator using is `s3://{bucket}/{key}`

**Review by ferruzzi — APPROVED** [review]
Nice catch.

**Comment by zhongjiajie** [comment]
ping @mik-laj @potiuk @kaxil again

**Review by potiuk — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks

**Pull request merged**
