### PR TITLE
[19458] Added column duration to DAG runs view

### LINKED ISSUE #19458: DAG Run Views showing information of DAG duration
### Description

In Airflow UI. If we go to Browse --> DAG Runs, then DAG Runs view will be displayed.

Table contains a lot of insightful values likes DAG execution date, Start date, end date, Dag config etc

Request to add DAG duration column in the same table.
DAG Duration i.e. DAG end_date timestamp  - DAG start_date timestamp

### Use case/motivation

Analytics purpose of knowing DAG duration at all DAGs level. So that I can easily find out which DAG  have least and max duration.

### Related issues

Checked open issues. There aren't any

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by subkanthi**
Added column duration(derived) to DAG runs view
closes: #19458 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by subkanthi** [comment]
> Could you add the screenshot you posted in the issue here in the PR? We should also make sure the duration formats in /dagrun and /taskinstance are consistent (/taskinstance below):
> 
> Screen Shot 2021-11-08 at 3 06 28 PM

Sure here it i
Screen Shot 2021-11-08 at 3 53 12 PM
s

**Review by bbovenzi — APPROVED** [review]
nice work!

**Comment by alexInhert** [comment]
Should it have tooltip that explains that the metric is in seconds?

**Comment by ashb** [comment]
Or we could use the existing `convertSecsToHumanReadable` function in JS the front end to make it nicer?

**Comment by subkanthi** [comment]
> Or we could use the existing `convertSecsToHumanReadable` function in JS the front end to make it nicer, or an equivalent behaviour on the backend for display?
Please see attached, changed the default to 0.0 and the same format as the duration in taskInstance(d:m:s)
Screen Shot 2021-11-10 at 1 37 58 PM

**Comment by uranusjr** [comment]
LGTM, I just wonder if it’s worthwhile to display the time this precisely. A couple of decimal points is more than enough IMO. (Same applies to the task instance table.)

**Comment by subkanthi** [comment]
> LGTM, I just wonder if it’s worthwhile to display the time this precisely. A couple of decimal points is more than enough IMO. (Same applies to the task instance table.)

Hi @uranusjr , should I be starting a separate discussion for this, can this PR be merged in the meantime?

**Pull request merged**
