### PR TITLE
Move ElasticsearchTaskHandler to the provider package

### PR DESCRIPTION
**Pull request by ephraimbuddy**
---
This PR fixes one of the issues listed in #9386

The `ElasticsearchTaskHandler` class from `airflow.utils.log.es_task_handler` was moved to
`airflow.providers.elasticsearch.log.es_task_handler`.

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Comment by turbaszek** [comment]
@ephraimbuddy can you please take a look at the CI errors?

**Comment by ephraimbuddy** [comment]
Hi @turbaszek , what could be the cause of the backport packages CI build error? I can't seem to figure it out

**Comment by potiuk** [comment]
Look at the logs @ephraimbuddy -> the "ExternalLoggingMixin" is a bit strange as I cannot see it in the logging_mixin. Where is it from?

----------------------------------------
Traceback (most recent call last):
  File "/import_all_provider_classes.py", line 61, in import_all_provider_classes
    _module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/airflow/providers/elasticsearch/log/es_task_handler.py", line 34, in <module>
    from airflow.utils.log.logging_mixin import ExternalLoggingMixin, LoggingMixin
ImportError: cannot import name 'ExternalLoggingMixin'

----------------------------------------
  ERROR ENCOUNTERED!

**Comment by potiuk** [comment]
We can't use ExtenralLoggingMixin in Airflow 1.10 providers because it only appeared .... TODAY in master

**Comment by potiuk** [comment]
If we want to support ExternalLoggingMixin we should also bacport it to 1.10 but this might be a bit more complex - using Bowler refactoring (@turbaszek WDYT?)

**Comment by ephraimbuddy** [comment]
@potiuk Thanks!

**Comment by mik-laj** [comment]
@potiuk  This will cherry-pick changes to the Javascript code. If you are willing, we can do it. For now, we should delete references to this class in backport packages. This will allow these classes to be used without this one new feature.

**Comment by ephraimbuddy** [comment]
These changes have been move to #9604

**Pull request closed without merging**
