### PR TITLE
[AIRFLOW-3381] Allow use of secretKeyRef or configMapKeyRef in env_vars

### PR DESCRIPTION
**Pull request by abrenaut**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3381

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Updated the KubernetesRequestFactory.extract_env_and_secrets() static method to support `valueFrom` for environment variables.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
The CI is sad:
```
======================================================================
44) FAIL: test_scheduler_sla_miss_callback_exception (tests.test_jobs.SchedulerJobTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/test_jobs.py line 2851 in test_scheduler_sla_miss_callback_exception
      sla_callback.assert_called()
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 906 in assert_called
      raise AssertionError(msg)
   AssertionError: Expected 'None' to have been called.
   -------------------- >> begin captured stdout << ---------------------
   [2018-11-22 00:37:12,065] {test_task_view_type_check.py:47} INFO - class_instance type: <class 'unusual_prefix_61c0ab525b75d060ea41c0aa11a98c88efc72c26_test_task_view_type_check.CallableClass'>
   
   --------------------- >> end captured stdout << ----------------------
   -------------------- >> begin captured logging << --------------------
   root: INFO: class_instance type: <class 'unusual_prefix_61c0ab525b75d060ea41c0aa11a98c88efc72c26_test_task_view_type_check.CallableClass'>
   --------------------- >> end captured logging << ---------------------
======================================================================
45) FAIL: test_scheduler_sla_miss_email_exception (tests.test_jobs.SchedulerJobTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 1305 in patched
      return func(*args, **keywargs)
    tests/test_jobs.py line 2895 in test_scheduler_sla_miss_email_exception
      'test_sla_miss')
    .tox/py27-backend_mysql-env_docker/lib/python2.7/site-packages/mock/mock.py line 925 in assert_called_with
      raise AssertionError('Expected call: %s\nNot called' % (expected,))
   AssertionError: Expected call: exception(u'Could not send SLA Miss email notification for DAG %s', u'test_sla_miss')
   Not called
```

**Comment by OmerJog** [comment]
@abrenaut You still have errors:

```
======================================================================
4) ERROR: Failure: SyntaxError (invalid syntax (kubernetes_request_factory.py, line 140))
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite-env_docker/lib/python2.7/site-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    .tox/py27-backend_sqlite-env_docker/lib/python2.7/site-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    .tox/py27-backend_sqlite-env_docker/lib/python2.7/site-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    tests/contrib/executors/test_kubernetes_executor.py line 26 in <module>
      from airflow.contrib.executors.kubernetes_executor import AirflowKubernetesScheduler
    airflow/contrib/executors/kubernetes_executor.py line 27 in <module>
      from airflow.contrib.kubernetes.pod_launcher import PodLauncher
    airflow/contrib/kubernetes/pod_launcher.py line 23 in <module>
      from airflow.contrib.kubernetes.kubernetes_request_factory import \
    airflow/contrib/kubernetes/kubernetes_request_factory/pod_request_factory.py line 19 in <module>
      from airflow.contrib.kubernetes.kubernetes_request_factory.kubernetes_request_factory \
   SyntaxError: invalid syntax (kubernetes_request_factory.py, line 140)
```

**Comment by OmerJog** [comment]
@abrenaut You still have errors in the code:

```
   Traceback (most recent call last):
    .tox/py27-backend_postgres-env_docker/lib/python2.7/site-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    .tox/py27-backend_postgres-env_docker/lib/python2.7/site-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    .tox/py27-backend_postgres-env_docker/lib/python2.7/site-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    tests/contrib/executors/test_kubernetes_executor.py line 33 in <module>
      from airflow.contrib.executors.kubernetes_executor import AirflowKubernetesScheduler
    airflow/contrib/executors/kubernetes_executor.py line 28 in <module>
      from airflow.contrib.kubernetes.pod_launcher import PodLauncher
    airflow/contrib/kubernetes/pod_launcher.py line 24 in <module>
      from airflow.contrib.kubernetes.kubernetes_request_factory import \
    airflow/contrib/kubernetes/kubernetes_request_factory/pod_request_factory.py line 20 in <module>
      from airflow.contrib.kubernetes.kubernetes_request_factory.kubernetes_request_factory \
   SyntaxError: invalid syntax (kubernetes_request_factory.py, line 140)
```

**Review by galuszkak — COMMENTED** [review]
There should be documentation of this behaviour on KubernetesPodOperator env_vars param, so it's clear what type of dictionaries You can pass there. For now this API change won't be visible to users. Probably is also good idea to have unittest for this behaviour, as for now this isn't in coverage.

**Comment by OmerJog** [comment]
@abrenaut any progress with this (docs/tests)?

**Comment by AnumSheraz** [comment]
Why this change never got merged ???

**Pull request closed without merging**
