### PR TITLE
Make sure finalizers are not skipped during exception handling

### LINKED ISSUE #22404: tempfile.TemporaryDirectory does not get deleted after task failure
### Discussed in https://github.com/apache/airflow/discussions/22403

<div type='discussions-op-text'>

<sup>Originally posted by **m1racoli** March 18, 2022</sup>
### Apache Airflow version

2.2.4 (latest released)

### What happened

When creating a temporary directory with `tempfile.TemporaryDirectory()` and then failing a task, the corresponding directory does not get deleted.

This happens in Airflow on Astronomer as well as locally in for `astro dev` setups for LocalExecutor and CeleryExecutor.

### What you think should happen instead

As in normal Python environments, the directory should get cleaned up, even in the case of a raised exception.

### How to reproduce

Running this DAG will leave a temporary directory in the corresponding location:

```python
import os
import tempfile

from airflow.decorators import dag, task
from airflow.utils.dates import days_ago


class MyException(Exception):
    pass


@task
def run():
    tmpdir = tempfile.TemporaryDirectory()
    print(f"directory {tmpdir.name} created")
    assert os.path.exists(tmpdir.name)

    raise MyException("error!")


@dag(start_date=days_ago(1))
def tempfile_test():
    run()


_ = tempfile_test()
```

### Operating System

Debian (Astronomer Airflow Docker image)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==1!3.0.0
apache-airflow-providers-cncf-kubernetes==1!3.0.2
apache-airflow-providers-elasticsearch==1!2.2.0
apache-airflow-providers-ftp==1!2.0.1
apache-airflow-providers-google==1!6.4.0
apache-airflow-providers-http==1!2.0.3
apache-airflow-providers-imap==1!2.2.0
apache-airflow-providers-microsoft-azure==1!3.6.0
apache-airflow-providers-mysql==1!2.2.0
apache-airflow-providers-postgres==1!3.0.0
apache-airflow-providers-redis==1!2.0.1
apache-airflow-providers-slack==1!4.2.0
apache-airflow-providers-sqlite==1!2.1.0
apache-airflow-providers-ssh==1!2.4.0
```

### Deployment

Astronomer

### Deployment details

GKE, vanilla `astro dev`, LocalExecutor and CeleryExecutor.

### Anything else

Always

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

### PR DESCRIPTION
**Pull request by potiuk**
There was a bug in our fork handling that prevented finalizer
for objects kept in frame of unhandled excepion. Previously,
the os._exit() was called in finally clause, and if there was
an unhandled exception raised, the exception was still kept in
memory while finally clause was processed together with the
objects in the same stack frame as the thrown exception that
could lead to those objects not being finalized.

This is mitigated by moving the os._exit() outside of the finally
clause.

Fixes: #22404

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
All looks good.

**Comment by uranusjr** [comment]
While moving `os._exit()` out of the `finally` block is (I believe) the correct fix, I don’t think those changes to `BaseException` are needed. IMO at least the first one should be reverted.

**Comment by potiuk** [comment]
> While moving `os._exit()` out of the `finally` block is (I believe) the correct fix, I don’t think those changes to `BaseException` are needed. IMO at least the first one should be reverted.

I think it's quite important actually:

Here is the inheritance graph of exceptions: 

https://docs.python.org/3/library/exceptions.html#exception-hierarchy

After moving the os._exit() out of `finally`, If any of "GeneratorExit" "KeyboardException", "SystemExit" are raised in the fork, then `os_exit` will not be called in the fork. While it is likely not a big issue (those exceptions will be raised further and *probably* not caught and lead to fork process exit, this is not the intention here. I believe the intention of the fork here is that the fork should never, ever leave the scope of the `_start_by_fork` function. The whole idea about os._exit() in fork is to exit immediately not giving a chance of any other code to be executed in the fork. This is to emulate Popen() in the place where fork is called. 

If we allow code exceution in the fork to go up the stack in here, this is potentially very distrupting. This will mean that fork process **might** potentially start executing a code that was never supposed to be executed in fork - only in the parent process.

For example if the parent process does:

```python
def run_task():
   process = _start_by_fork()
   wait_process(x) 

def do_something():
   run_task()

try:
   do_something()
except BaseException:
   do_some_cleanup()
```

If we just do "try/except Exception" and BaseException happens,  then `do_some_cleanup()` will be executed in BOTH - parent process and fork process - which is certainly not intended.

I think in such "low-level" code we should catch ALL POSSIBLE exceptions.

**Comment by malthe** [comment]
@potiuk but isn't using `tempfile.TemporaryDirectory` without entering the context manager simply a mistake? I don't think one should rely on the finalizer behavior in order to close such resources.

That said, this is much better (exiting outside of the try/finally block) – but why are we even having a try/finally-block at all.

The exception clause catches everything.

**Comment by potiuk** [comment]
> @potiuk but isn't using `tempfile.TemporaryDirectory` without entering the context manager simply a mistake? I don't think one should rely on the finalizer behavior in order to close such resources.

Technically speaking it **should** work: 

https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

> This function securely creates a temporary directory using the same rules as [mkdtemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp). The resulting object can be used as a context manager (see [Examples](https://docs.python.org/3/library/tempfile.html#tempfile-examples)). On completion of the context or destruction of the temporary directory object, the newly created temporary directory and all its contents are removed from the filesystem.

And I read a lot about it - while traditionally relying on finalizers was not really good idea in Python 2, and early Python versions. It started to work much more reliable, and unless there is a very good reason (like kill -9) it **should** work in all cases. Of course blindly relying that finalizer will **always** be called is not a good idea, expecting that thy will be called in all "normal" situation is quite reaasonable. Just the fact that our user expected it and it did not work is a statemet on it's own.

And there might be many other cases like that. For example I know for a fact that open-telemetry also registers some finalizers (and we are going to add it soon  - we have an AIP for it cooking) and while deleting TemporaryDirectory is not a big issue, not calling open-telemetry finalizers is. If we prevent finalizers from being called, then we also prevent open-telemetry from sending the cachesd  information about the last failure which caused an application crash. This is precisely this kind of problem that we want to avoid (and when it comes to open telemetry - this is precisely the case that open-telemetry is there to help our users with). 

So yeah. I think preventing finalizer from being called when it **should** be called and there are no "system evnts" that prevent it, is actually a BIG deal and we **must** fix it.

> That said, this is much better (exiting outside of the try/finally block) – but why are we even having a try/finally-block at all.
> The exception clause catches everything.

Not really. Finally clause is also executed when there is no exception at all.

**Comment by malthe** [comment]
Oooh of course yes. Very nice then :-)

**Review by malthe — APPROVED** [review]

**Comment by potiuk** [comment]
@uranusjr -> are you ok with the BaseException explanation :) ? (@ashb - your input would also be useful - I want to make sure I did not miss anything - as this is very 'delicate' part of the system.

**Comment by m1racoli** [comment]
> @potiuk but isn't using `tempfile.TemporaryDirectory` without entering the context manager simply a mistake? I don't think one should rely on the finalizer behavior in order to close such resources.

(my opinionated view)

I would disagree. I see the context manager more as an extra and getting deleted upon "destruction of the temporary directory object" is a core feature of `tempfile.TemporaryDirectory`.

Furthermore using a context manager is not alway practical. In particular, we use it in a factory for task specific tmp dirs:

```python
def tmpdir() -> TemporaryDirectory:
    """
    Provides a task instance specific instance of a temporary directory.
    On first invocation a new directory will be created and the holding object will be
    stored in the task instance's context. Successive calls return the already allocated object.
    """
    ctx = python.get_current_context()
    d = ctx.get("tmpdir")

    if d is None:
        d = TemporaryDirectory(prefix=f"{ctx['task_instance_key_str']}.")
        logging.info(f"Temporary directory {d.name} created")
        ctx["tmpdir"] = d

    return d
```

It is of course debatable if this is a good thing to do (and the implementation might only be half-baked).

In regards to the general PR, the TemporaryDirectory issue can be considered as a symptom of a more fundamental problem which extends beyond just this case (as mentioned by @potiuk in regards to open-telemetry which I highly anticipate :) ).

**Comment by uranusjr** [comment]
I’m still skeptical, there’s no information I could find on what happens if an exception is bubbled uncaught in a forked child, but I’d be surprised if `except BaseException` is needed but nobody is telling people to do it. The difference between catching BaseException or not is not whether `os._exit()` will be called, but whether additional cleanups _not_ done by `os._exit()` will happen if we leave BaseException uncaught. I suspect that’s not the case, but do not have proof for either case.

I guess technically it does no harm to always catch BaseException and do `os._exit()` manually (instead of letting the BaseException bubble and the interpreter to quit naturally), so if you feel strongly about this I am not going to stop you.

**Comment by uranusjr** [comment]
Yes that’s why we catch `Exception`, but `BaseException` is reserved for fairly rare cases that generally imply something very terribly wants to stop things, and I’m not sure swallowing it is better than having things crash terribly.

**Comment by potiuk** [comment]
Actually the discussion above made me aware that we should add a bit more cases:

* when SystemExit is called - we should take return_code from it
* whan any of the BaseExceptions (including SystemExit) is caught we should avoid logging them. There is no point in doing it (same as usual when you catch Exception)
 
However I still firmly believe we need to catch the BaseException and run sys._exit() outside of the try/except/finally clause in case of fork, otherwiuse cleanup handlers, flushing other buffers than those we explicitly do in finally (sentry + logging).

**Review by ashb — APPROVED** [review]

**Pull request merged**
