### PR TITLE
Disable flaky mssql based integration tests

### PR DESCRIPTION
**Pull request by gopidesupavan**
Currently in CI these tests are failing with `pymssql.exceptions.OperationalError: ` .  as discussed in slack ci-cd group , disabling these tests.

https://github.com/apache/airflow/actions/runs/11210718014/job/31158453211#step:6:2844

tests/integration/providers/microsoft/mssql/hooks/test_mssql.py::TestMsSqlHook
tests/integration/providers/apache/hive/transfers/test_mssql_to_hive.py::TestMsSqlToHiveTransfer
tests/integration/providers/google/cloud/transfers/test_bigquery_to_mssql.py::TestBigQueryToMsSqlOperator
tests/integration/providers/google/cloud/transfers/test_mssql_to_gcs.py::TestMsSqlToGoogleCloudStorageOperator

hope `@pytest.mark.quarantined` works? 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Actualyt now, when I think of it - quarantining is not enough /not needed - what we really need is to not have mssql integration running in CI. 

If you look at selective checks -> they produce the list of "testable_integrations" : https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/utils/selective_checks.py#L1298

Defined here:

https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/global_constants.py#L57

This list is produced by selective checks here:

https://github.com/apache/airflow/actions/runs/11226083287/job/31205948119?pr=42811#step:8:824


And used in the workflow that runs integration tests to produce matrix of jobs:

https://github.com/apache/airflow/blob/main/.github/workflows/integration-tests.yml#L67

So all we need to do is to remove mssql from the list.

This is actually cool - because this way you can still run the tests locally:

```
breeze tessting integration-tests --integration mssql 
```

but they will not run in CI.

**Comment by gopidesupavan** [comment]
> Actualyt now, when I think of it - quarantining is not enough /not needed - what we really need is to not have mssql integration running in CI.
> 
> If you look at selective checks -> they produce the list of "testable_integrations" : https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/utils/selective_checks.py#L1298
> 
> Defined here:
> 
> https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/global_constants.py#L57
> 
> This list is produced by selective checks here:
> 
> https://github.com/apache/airflow/actions/runs/11226083287/job/31205948119?pr=42811#step:8:824
> 
> And used in the workflow that runs integration tests to produce matrix of jobs:
> 
> https://github.com/apache/airflow/blob/main/.github/workflows/integration-tests.yml#L67
> 
> So all we need to do is to remove mssql from the list.
> 
> This is actually cool - because this way you can still run the tests locally:
> 
> ```
> breeze tessting integration-tests --integration mssql 
> ```
> 
> but they will not run in CI.

yeah, your correct. that was great suggestion, let me check and update. thank you

**Comment by gopidesupavan** [comment]
@potiuk if i remove mssql from TESTABLE_INTEGRATIONS and running breeze command in local, its failing , because the command validation failing at `BetterChoice`. 

`option_integration = click.option(
    "--integration",
    help="Integration(s) to enable when running (can be more than one).",
    type=BetterChoice(AUTOCOMPLETE_INTEGRATIONS),
    multiple=True,
)`

So i have added new constant to disable not required integrations. hope that is fine?

image

**Review by shahar1 — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
@gopidesupavan -> maybe we can cherry-pick that on  to v2-10-test as well.

**Comment by gopidesupavan** [comment]
> @gopidesupavan -> maybe we can cherry-pick that on to v2-10-test as well.

Sure i will get these.

**Pull request merged**
