### PR TITLE
[AIRFLOW-1782] Allow HttpSensor to support xcom

### PR DESCRIPTION
**Pull request by wolfier**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1782

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Using xcom, HttpSensor can communicate with other
tasks.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
added test_xcom in tests/operators/sensors.py
updated test_head_method in tests/operators/sensors.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks for your contribution. Please fix the test:
```
======================================================================
12) ERROR: test_head_method (tests.HttpSensorTests)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-cdh-airflow_backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 1305 in patched
      return func(*args, **keywargs)
    tests/operators/sensors.py line 150 in test_head_method
      task.execute(None)
    airflow/operators/sensors.py line 79 in execute
      while not self.poke(context):
    airflow/operators/sensors.py line 702 in poke
      self.xcom_push(context=context, key=XCOM_RETURN_KEY, value=response.text)
    airflow/models.py line 2703 in xcom_push
      context['ti'].xcom_push(
   TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by wolfier** [comment]
I have updated test_head_method! @Fokko

**Comment by ron819** [comment]
@wolfier are you still working on this PR?

**Comment by mik-laj** [comment]
Related PR: https://github.com/apache/airflow/pull/4345

**Comment by marengaz** [comment]
yes, this pr should be closed. #2753 implemented a global flag with this function on BaseOperator

**Comment by kaxil** [comment]
Implemented in #4345

**Pull request closed without merging**
