### PR TITLE
Revert "check whether AUTH_ROLE_PUBLIC is set in check_authentication…

### PR DESCRIPTION
**Pull request by potiuk**
… (#38924)"

This reverts commit 7b608250468740954c6b0af7a5f7f23dfa52b473.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @Lee-W - this PR has a side effect on failing a number of tests in 

```
tests/providers/fab/auth_manager/api_endpoints/test_role_and_permission_endpoint.py
```

By  a quick look, change from 401 -> 403 impacts all the cases where unauthanticated user is used, which I think is not an intended behaviour (the original isssue mentions only AUTH_ROLE_PUBLIC case). So rather than fixing all 401 in 403 - I think it's better to revert it now and fix it "properly" (which also means that `full tests needed` should be set as label for the new PR). I will also add FAB provider tests to be triggered in selective checks when "api" tests are run - because this is the reason why it did not fail in your PR originally.

**Review by Taragolis — APPROVED** [review]

**Comment by potiuk** [comment]
The PR to run FAB tests together with API changes is merged now @Lee-W -> so you should be able to redo the PR and see the tess failing in your PR. The "too selective" case should be now nicely covered.

**Comment by Lee-W** [comment]
Sure. I just addressed the issue, created a new PR https://github.com/apache/airflow/pull/39012, and added the required label. Thanks for reminding me!

**Comment by potiuk** [comment]
> Sure. I just addressed the issue, created a new PR #39012, and added the required label. Thanks for reminding me!

Sorry for the troubles  with selective checs :( . But should be fixed from now on.

**Comment by Lee-W** [comment]
> > Sure. I just addressed the issue, created a new PR #39012, and added the required label. Thanks for reminding me!
> 
> Sorry for the troubles with selective checs :( . But should be fixed from now on.

Not at all. Thanks for the fix 🙂

**Pull request merged**
