### PR TITLE
Disable health check for mssql integration

### PR DESCRIPTION
**Pull request by potiuk**
We already perform environment check inside Airlfow entrypoint_ci.sh so there is no need to run health-check in docker compose, the script will wait until mssql is available anyway.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @shahar1  -> Let's simply disable the health check in docker compose. We already run environment check inside the container entrypoint. possibly it should be enough.

**Comment by potiuk** [comment]
This is the check we do in entrypoint_ci.sh (via environment_check.sh)

```shell
if [[ ${INTEGRATION_MSSQL} == "true" ]]; then
    check_service "mssql" "run_nc mssql 1433" 50
fi
```

**Comment by shahar1** [comment]
I guess that we could live with it :)

**Comment by potiuk** [comment]
> I guess that we could live with it :)

Sometimes low-level/simple solutions are better than trying to be "correct".

**Comment by shahar1** [comment]
> > I guess that we could live with it :)
> 
> Sometimes low-level/simple solutions are better than trying to be "correct".

I like the idea of the healt check testing at the "inter-container" level provided by Docker Compose.
But yeah, probably there's no need to struggle with it - I'm also having issues implementing a similar healthcheck for `drill`, so I'll give it up for now.

**Review by vincbeck — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
🤞

**Pull request merged**
