### PR TITLE
[AIRFLOW-6002] Drop support for python 3.5

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6002
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Drop python 3.5 support per mailinglist.

### CODE REVIEW

**Comment by potiuk** [comment]
We need a bit more than that. There are a number of bash scripts with PYTHON_VERSION set to 3.5. I might do a commit with that on top of yours shortly.

**Review by Fokko — APPROVED** [review]

**Comment by bolkedebruin** [comment]
> We need a bit more than that. There are a number of bash scripts with PYTHON_VERSION set to 3.5. 

I will remove those, I think that to be bad practice.

> I might do a commit with that on top of yours shortly.

Please do not do that.

**Comment by potiuk** [comment]
There is one more python 3.5 in breeze-complete @bolkedebruin

**Comment by bolkedebruin** [comment]
> There is one more python 3.5 in breeze-complete

Why were those harcoded everywhere @potiuk ?

**Comment by potiuk** [comment]
> > There is one more python 3.5 in breeze-complete
> 
> Why were those harcoded everywhere @potiuk ?

Sorry for that. That was unfortunate indeed. 

I have a refactor (WIP) for the whole set of bash scripts to make them way simpler (#6500) - currently we are at 8/12 PRs (https://issues.apache.org/jira/projects/AIRFLOW/issues/AIRFLOW-5606) done for the production image change that simplified the scripts (and I will make a DEFAULT_PYTHON_VERSION there in common utils script that we will use).

Unfortunately this is not always super-easy for the bash scripts - especially that so far we had a separate build script for Dockerhub (hooks/build) - this is where the whole build logic was implemented. We called this script from within other scripts (and separately in Dockerhub), and it got far too complex.

I reverted the logic in (#6500) so that we have common utils used everywhere and then it will be possible to make it defined in one place and have one constant for it (in bash scripts).

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
And one more thing here @bolkedebruin  - for some of those scripts (static checks) we wanted to force always 3.5 version - no matter what you had setup as your current python version (simply because we wanted to run static checks consistently for all static checks. That's why in those scripts we "hard-coded" 3.5 before any of the common scripts were loaded, to make sure that PYTHON_VERSION is set before any of the initialisation happens. I will have to add a common script to force PYTHON_VERSION but I think it's a bit easier to write:
```
PYTHON_VERSION=3.6 
```
rather than

```
source ${ARIFLOW_SOURCES}/common/_force_python_version.sh
```
I am reviewing the scripts now in my PR and will try to find some good and readable solution.

**Comment by mingrammer** [comment]
The badge for python versions should be updated as well. (remove `3.5` part)

https://img.shields.io/pypi/pyversions/apache-airflow.svg

**Comment by potiuk** [comment]
and 2.7 :)

**Comment by potiuk** [comment]
One small problem with it -  this is for the "released" version and is taken directly from the PyPI. Latest released version supports 2.7, 3.5, 3.6, 3.7 so it is still correct.

**Pull request merged**
