### PR TITLE
[AIRFLOW-XXX] Add newline docstring for doc generation

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
cc @nritholtz
Thanks for reminding me at https://github.com/apache/airflow/pull/4903#issuecomment-480317443

**Comment by zhongjiajie** [comment]
@ashb PTAL, Thanks.

**Comment by zhongjiajie** [comment]
@XD-DENG Thanks for merging.

**Comment by XD-DENG** [comment]
@zhongjiajie welcome ;-)

**Pull request merged**
