### PR TITLE
Merge datasets and dag dependencies graphs

### LINKED ISSUE #29857: Migrate DAG Dependencies view to the dataset dependencies graph
These two graphs have a lot of overlap and can be quite redundant. We should make the datasets view take over for the DAG Dependencies graph.

- [ ] show other DAG dependencies in the datasets graph, and allow a user to filter the graph by dependency type
- [ ] redirect links to datasets view and delete the DAG Dependencies view

### PR DESCRIPTION
**Pull request by bbovenzi**
The Dag Dependencies and Datasets views had a lot of overlap codewise and functionality wise. We should just merge them.

So now the datasets page includes trigger and sensors and the old dag dependencies view is deleted.

I changed the url and the header name. But very much open to suggestions.

Screenshot 2023-08-01 at 11 06 40 PM

Closes https://github.com/apache/airflow/issues/29857

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jedcunningham** [comment]
Brent and I had a chat about this, and I'm just not sure on the naming when combining these 2 pretty distinct conceptual views, even if they share a common component. I also think with the timing around 2.7, we'd be better waiting a bit to make sure we get it right.

**Comment by eladkal** [comment]
> Brent and I had a chat about this, and I'm just not sure on the naming when combining these 2 pretty distinct conceptual views,

What about lineage view?

**Comment by RNHTTR** [comment]
> > Brent and I had a chat about this, and I'm just not sure on the naming when combining these 2 pretty distinct conceptual views,
> 
> What about lineage view?

IMO "lineage" is maybe a bit overloaded, but maybe being a bit more specific, like "DAG Lineage" could be good.

**Comment by bbovenzi** [comment]
@jedcunningham let's chat about this again for 2.8?

**Pull request closed without merging**
