### PR TITLE
remove upper bound for MarkupSafe

### LINKED ISSUE #19761: removing upper bound for markupsafe
### Description

Per discussion and guidance from #19753, opening this issue and PR https://github.com/apache/airflow/pull/19760 for review. Based on if all the tests pass, this could be reviewed further.

### Use case/motivation

Currently Jinja2 upper bound is jinja2>=2.10.1,<4 at https://github.com/apache/airflow/blob/main/setup.cfg#L121 as part of #16595

Jinja2 seems to require MarkupSafe>=2.0 at https://github.com/pallets/jinja/blob/main/setup.py#L6 as part of pallets/jinja@e2f673e

Based on this, is it feasible to consider updating upper bound in airflow for markupsafe>=1.1.1, <2.0 to allow 2.0 at https://github.com/apache/airflow/blob/main/setup.cfg#L126 ?

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tsingh2k15**
Per discussion and guidance from https://github.com/apache/airflow/discussions/19753, opening this PR for review. Based on if all the tests pass, this could be reviewed further. Resolves https://github.com/apache/airflow/issues/19761

### CODE REVIEW

**Comment by uranusjr** [comment]
Let’s see first if the test suite like this

**Comment by uranusjr** [comment]
Hmm, the answer seems to be no...?

**Comment by potiuk** [comment]
> Hmm, the answer seems to be no...?

We have a repeating problems with `test_manager.py` causing OOM in public runner as a few days. I am looking at it now.

**Comment by tsingh2k15** [comment]
> > Hmm, the answer seems to be no...?
> 
> We have a repeating problems with `test_manager.py` causing OOM in public runners as of a few days. I am looking at it now.

Thanks for clarification! It would be helpful to learn more if there are risks and/or compatibility issues with this change. We can wait till all tests run.

**Comment by potiuk** [comment]
Rebase to latest `main` please - all the "serious" test failures shoud be fixed.

**Comment by tsingh2k15** [comment]
> Rebase to latest `main` please - all the "serious" test failures shoud be fixed.

Rebased to latest `main`. Thanks! I will monitor the tests as the workflow proceeds further.

**Comment by tsingh2k15** [comment]
> > Rebase to latest `main` please - all the "serious" test failures shoud be fixed.
> 
> Rebased to latest `main`. Thanks! I will monitor the tests as the workflow proceeds further.

@potiuk It looks like the tests are failing while validating constraints. Trying to understand the failures. It seems like tests are comparing the dependencies with https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-source-providers-3.7.txt. Your input here would be helpful. Thanks! Below is the snippet from one of the test failures.

```
***********************************************************************************************
***********************************************************************************************
*
* In case you see unrelated test failures, it can be due to newer dependencies released.
* This is either because it is 'main' branch or because this PR modifies dependencies (setup.* files).
* Therefore 'eager-upgrade' is used to build the image, This means that this build can have newer dependencies than the 'tested' set of constraints,
*
* The tested constraints for that build are available at: https://raw.githubusercontent.com/apache/airflow/constraints-main/constraints-source-providers-3.7.txt 
*
* Please double check if the same failure is in other tests and in 'main' branch and check if the dependency differences causes the problem.
* In case you identify the dependency, either fix the root cause or limit the dependency if it is too difficult to fix.
*
* The diff between fixed constraints and those used in this build is below.
*
***********************************************************************************************

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  9958  100  9958    0     0  81622      0 --:--:-- --:--:-- --:--:-- 81622
19c19
< Jinja2==2.11.3
---
> Jinja2==3.0.3
22c22
< MarkupSafe==1.1.1
---
> MarkupSafe==2.0.1
107c107
< charset-normalizer==2.0.7
---
> charset-normalizer==2.0.8
242c242
< keyring==23.2.1
---
> keyring==23.3.0
```

**Comment by eladkal** [comment]
@potiuk isn't that the same case we had with sshtunnel and azure cosmos ?

**Comment by potiuk** [comment]
Nope. That was another issue fixed in main (pickle error in PythonVirtualenv). 
Please rebase: @tsingh2k15 : 

> This branch is 36 commits ahead, 30 commits behind apache:main.

**Comment by potiuk** [comment]
(sorry I missed the comment - the `main` was only recently brought to "greeen" status.

**Comment by tsingh2k15** [comment]
> (sorry I missed the comment - the `main` was only recently brought to "greeen" status.

Will open a new PR with latest from upstream

**Pull request closed without merging**
