### PR TITLE
add extraContainers for migrateDatabaseJob

### PR DESCRIPTION
**Pull request by mirobertod**
Hello,
I'd like to add `extraContainers` for `migrateDatabaseJob`, likewise what has been done for the other pods.

One use case might be to use a sidecar container as a proxy for the database, for instance [`cloudsql-proxy`](https://github.com/GoogleCloudPlatform/cloudsql-proxy)

Thanks

### CODE REVIEW

**Comment by potiuk** [comment]
Could you please add unit tests for those ?

**Comment by mirobertod** [comment]
> Could you please add unit tests for those ?

Sure, test added

**Review by potiuk — APPROVED** [review]
LGTM

**Comment by potiuk** [comment]
Some static checks failing

**Comment by mirobertod** [comment]
> Some static checks failing

Should be fixed now

**Comment by mirobertod** [comment]
The test failed says `Process completed with exit code 137.` Usually exit code 137 is about out of memory error.
Can we try to run the test again?
Thanks

**Comment by potiuk** [comment]
For the future - Just rebase and push the change - there is no way in GH to rebuild single test. And yeah 139 is intermittent out of memor so we can merge that one without doing it as all the other tests passed.

**Review by potiuk — APPROVED** [review]

**Comment by omarsmak** [comment]
Hey @mirobertod , I came across this PR and it seems you are trying to do like what I do, to lunch cloud-sql sidecar in the airflow migration database jobs. However, how did you manage to terminate the cloud-sql proxy when the `run-airflow-migrations` has been terminated?

**Comment by mirobertod** [comment]
> Hey @mirobertod , I came across this PR and it seems you are trying to do like what I do, to lunch cloud-sql sidecar in the airflow migration database jobs. However, how did you manage to terminate the cloud-sql proxy when the `run-airflow-migrations` has been terminated?

Hi @omarsmak , I don't exactly remember if I got stuck with the same problem, but my current solution is to use the cloud SQL proxy as a service instead of sidecar.

**Pull request merged**
