### PR TITLE
[AIRFLOW-4509] SubDagOperator using scheduler instead of backfill

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4059

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

tl;dr Make `SubDagOperator` use normal scheduler instead of backfill scheduler to run subtasks.

Currently `SubDagOperator` uses backfill scheduler to schedule tasks in the subdags and there are a few drawbacks:
- Relying on backfill scheduler to schedule tasks in normal `DagRun`.
- `parallelism` is not respected in backfill.
- Tasks in the subdag continues to run even when the DAG is paused.
- You need to specify an executor.

Summary of implementation:
- `SubDagOperator` creates a `DagRun` for the subdag and will wait until the `DagRun` finish. It will occupy a slot (same behavior as we run backfill in `SubDagOperator`) but we can probably introduce `reschedule` concept like `BaseSensorOperator` to release the slots.
- Scheduler will pick up the `DagRun` and schedule the tasks.
- Yet to be implemented: backfill `SubDagOperator`.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by milton0825** [comment]
@ashb @potiuk @feng-tao 
Would be great if I can have some early feedback from you guys about the approach I took here.

**Comment by potiuk** [comment]
I am now focusing more back on the Docker/dev tools area and Ash is on vacation so maybe others could take a look ? It looks like a nice one but I would have to dive a bit deeper in that part to understand all consequences.

**Comment by milton0825** [comment]
No worries @potiuk. Can't wait for the breeze.

**Comment by ashb** [comment]
This may improve things - but my initial idea was that the tasks from subdags are "bubbled" up to the parent dag, so that they become a purely visual/DAG drafting construct.

Which is a bigger change than you've done here. This may be a useful first step though.

**Comment by milton0825** [comment]
@ashb correct me if I am wrong. I think that implies that only parent DAGs can have `DagRun` and subdag is just used as an abstraction for visualization only.

I would imagine that we still need to track the progress of subdag somewhere and `DagRun` would be a a good place since it is the abstraction built for this purpose. Of course the downside of maintaining multiple `DagRun` 's can complicate the codebase and can be hard to keep all `DagRun` s consistent. I would like to hear more about your thoughts on this.

But I agree with you that this PR can be the first step as it does not involve too many changes...

**Pull request closed without merging**
