### PR TITLE
Fix INTEGRATIONS[*]: unbound variable error in breeze

### PR DESCRIPTION
**Pull request by turbaszek**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by feluelle** [comment]
The issue still persists: `./breeze: line 382: INTEGRATIONS[*]: unbound variable`

**Comment by turbaszek** [comment]
@feluelle what command do you run? I had problem when running:
```
./breeze --python 3.6 --backend mysql --db-reset  restart
```

**Comment by feluelle** [comment]
just `./breeze`

**Comment by potiuk** [comment]
I will fix it

**Comment by potiuk** [comment]
I have to add some checks for that :(

**Comment by potiuk** [comment]
It turned out that those problematic parts are not needed any more . I forgot to remove it in the "move kubernetes to host" PR. We do not ever need any KUBERNETES related stuff when we enter CI image. That removes it completely

Here it is:  https://github.com/apache/airflow/pull/9138

**Pull request merged**
