### PR TITLE
provider fab auth manager deprecated methods removed

### PR DESCRIPTION
**Pull request by dirrao**
provider fab auth manager deprecated methods removed
1. get_readable_dags
2. get_editable_dags
3. get_accessible_dags
4. get_accessible_dag_ids
5. get_readable_dag_ids
6. init_role
7. prefixed_dag_id

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
Static checks are failing, else good to merge.

**Comment by dirrao** [comment]
> Static checks are failing, else good to merge.

It's resolved.

**Review by vincbeck — APPROVED** [review]

**Comment by eladkal** [comment]
This one is not handled properly... It mixes core and provider. It also force us to cut fab provider 2.0.0 is that something we want to do now? (We can but I am not sure we should). Initially  I wanted to handle all providers deprecations together as bulk for 2.11

**Comment by potiuk** [comment]
Yesl This one should be reverted.

**Comment by potiuk** [comment]
Revert PR here 
https://github.com/apache/airflow/pull/41960

**Pull request merged**
