### PR TITLE
[AIRFLOW-1040] Fix some small typos in comments and docstrings

### PR DESCRIPTION
**Pull request by mschmo**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] Addresses issue [1040](https://issues.apache.org/jira/browse/AIRFLOW-1040)

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes: 
No UI changes. No actual code changes, just comments and docstrings.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Does not need testing since it doesn't change any actual code.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    Just the one commit

### CODE REVIEW

**Comment by jlowin** [comment]
😳  Thanks @mschmo, LGTM!

**Comment by jlowin** [comment]
Oh... actually, I hate to say this but you'll need to open a JIRA issue even for such a minor change.

**Comment by mschmo** [comment]
Yeah sure, not a problem. I can open an issue for this and reference it here.

**Comment by mschmo** [comment]
Ok @jlowin I opened an issue for this. Let me know if there are any problems.

**Comment by jlowin** [comment]
Thanks!

**Pull request closed without merging**
