### PR TITLE
Change terminal mode to cbreak in `execute_interactive` and handle `SIGINT`

### LINKED ISSUE #26186: Bad terminal handling of `airflow db shell` command with Postgres DB
### Apache Airflow version

main (development)

### What happened

This happens in both iTerm 2 and the built-in Terminal.app in macOS when running ~breeze start-airflow~. `airflow db shell` when using postgres as a backend.

Within `psql` (run via `airflow db shell`):

* Scrollback editing (eg: hitting up arrow to edit a previous query) is messed up for multi-line queries. I don't have a better description. I recorded a video of what happens.
* Some things require an additional keypress (eg: quitting the pager)
  - Some things, like ctrl+P to scrollback needing an additional keypress happen in a normal Docker environment. This is different and distinct from that.
* SIGINT isn't registered when trying to cancel editing a query and reset the SQL prompt

I suspect that there's a lot of interaction happening between iTerm/Terminal.app, ZSH, Python/Breeze, Bash, Docker, tmux, Python/Airflow CLI, and psql, and some keypresses are being filtered or queued along the way. So there are multiple fun rabbit holes to chase down to solve this.

### What you think should happen instead

* Scrollback editing should work. Your text cursor should be in the correct place and the text should be rendered correctly.
* An additional keypress to exit the pager should not be necessary
* SIGINT should cancel editing the query and reset the edit line (eg: it should return to an empty SQL prompt: `airflow=#` instead of `airflow-#`)

### How to reproduce

* Scrollback editing is messed up - indentation and text wrapping are off/wrong
  - This happens even when I don't adjust the tmux pane sizes at all
  - Example:
    + Run `breeze start-airflow` in a terminal 
    + Run `docker exec -it $CONTAINER_ID /bin/bash` with the breeze container that is running
    + Run `airflow db shell` within the container
    + Then this happens (note the up arrow keypresses aren't called out visually):

      https://user-images.githubusercontent.com/597113/188750191-2b3e8ef3-ee89-4b2e-872d-1451807bdbc7.mov

* Some things require an additional keypress
  Example:
  - Run a SQL query:
      ```
      airflow=# SELECT * FROM dag_schedule_dataset_reference
      ```
  - it displays in the pager
      ```
       dataset_id |        dag_id         |          created_at           |          updated_at
      ------------+-----------------------+-------------------------------+-------------------------------
                3 | consumer_dag_2        | 2022-09-06 20:49:23.719275+00 | 2022-09-06 20:49:23.719295+00
                2 | consumer_dag_2        | 2022-09-06 20:49:23.7193+00   | 2022-09-06 20:49:23.719302+00
                4 | taskflow_consumer_dag | 2022-09-06 20:49:23.719305+00 | 2022-09-06 20:49:23.719308+00
                5 | taskflow_consumer_dag | 2022-09-06 20:49:23.719311+00 | 2022-09-06 20:49:23.719313+00
                6 | taskflow_consumer_dag | 2022-09-06 20:49:23.719316+00 | 2022-09-06 20:49:23.719319+00
                1 | consumer_dag_1        | 2022-09-06 20:49:23.719322+00 | 2022-09-06 20:49:23.719324+00
      (6 rows)
      
      (END)
      ```
  - Usually you just hit `q` and it exits immediately, but the pager sticks around:
      ```
       dataset_id |        dag_id         |          created_at           |          updated_at
      ------------+-----------------------+-------------------------------+-------------------------------
                3 | consumer_dag_2        | 2022-09-06 20:49:23.719275+00 | 2022-09-06 20:49:23.719295+00
                2 | consumer_dag_2        | 2022-09-06 20:49:23.7193+00   | 2022-09-06 20:49:23.719302+00
                4 | taskflow_consumer_dag | 2022-09-06 20:49:23.719305+00 | 2022-09-06 20:49:23.719308+00
                5 | taskflow_consumer_dag | 2022-09-06 20:49:23.719311+00 | 2022-09-06 20:49:23.719313+00
                6 | taskflow_consumer_dag | 2022-09-06 20:49:23.719316+00 | 2022-09-06 20:49:23.719319+00
                1 | consumer_dag_1        | 2022-09-06 20:49:23.719322+00 | 2022-09-06 20:49:23.719324+00
      (6 rows)
      
      (END)
      ```
  - The `q` keypress is registered upon your next keypress, whatever that is (in this case, `6`). And the second keypress is echoed in the SQL editor:
      ```
      airflow=# SELECT * FROM dag_schedule_dataset_reference;
      airflow=# 6
      ```
* SIGINT isn't registered to cancel editing a query
  Example:
  - Write a query:
      ```
      airflow=# SELECT * FROM dag_messedupspelling
      ```
  - Then try to cancel/reset it with Ctrl+C:
      ```
      airflow=# SELECT * FROM dag_messedupspelling
      airflow-#
      ```
      (nothing happens)
      In normal psql this will reset the query editor (you can tell because the `airflow-#` prompt changes back to `airflow=#`).

### Operating System

macOS 11.6.8 Big Sur

### Versions of Apache Airflow Providers

N/A

### Deployment

Other Docker-based deployment

### Deployment details

Breeze

### Anything else

This happens every time.

Apologies if this isn't the place to report Breeze issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by renzepost**
Related: #26186 

Because the terminal mode was set to raw mode, `Ctrl-C` was not being interpreted as a `SIGINT` signal. Changing to cbreak mode will maintain most of the features of raw mode, except that keystrokes like `Ctrl-C` will be interpreted by the terminal and will interrupt.
Besides that, a handler for `SIGINT` is added so that the signal is simply passed to the subprocess (instead of causing a KeyboardInterrupt.)
This at least partially fixes #26186, because now hitting Ctrl-C will cause psql (and mysql) to interrupt any partial input.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Nice. Looks pretty resonable. World of low-level terminal interfaces is pretty intriguing

It's an interesting though why you need to send the signal to proc? It think we should simply ignore the signal rather than send it to the spawned process.

From what I understand how the Ctrl-C works is that it sends the signal to process group rather than to the main process. 

When we create the child process (despite a comment - see below) it does not look like the process is created with a "create new process group" flag - so Ctrl-C should also be sent to the child process. 

Of course we still do not want KeyboardInterupt Exception as you noticed, so I'd say we could likely ignore the signal rather than send it to the new process - otherwise the process will receive two signals one after the other.

Re the comment: we have this comment there:

```
        # use os.setsid() make it run in a new process group, or bash job control will not be enabled
```

So it looks like at least at some point of time there was a new process group created when spawning the process, but you cannot see it anywhere in the code. So maybe we shoudl also remove the comment while we are at it.

So I'd say just ignoring the signal would be a better approach.

**Comment by potiuk** [comment]
Also one more comment here - when we set the signal to a new handler (or ignore which is equivalent), we should - at least in theory, save the previous handler and restore it in the finally clause. It does not matter likely in this case - because we are going to exit the `db shell` command in a moment. but  purely thorethically, if anything happens between the `finally` and actual exit, then we will not be able to Ctrl-C it as usual without the handler restored.

**Comment by renzepost** [comment]
Hi Jarek,

You were absolutely right! The subprocess has the same PGID, so I made some changes. Now the calling process simply ignores the SIGINT. I tested this with `psql` and `mysql`, and Ctrl-C works fine without the whole process shutting down with a KeyboardInterrupt.
Also, as you suggested, I restore the old SIGINT handler in the `finally` clause.

**Review by potiuk — APPROVED** [review]
This is cool ! Thanks for being responsive here :)! 

LGTM

**Pull request merged**
