### PR TITLE
Custom providers documentation

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
Looks good but doc build fails:

```
The documentation has errors.
#################### Packages errors summary ####################
Package name                Count of doc build errors    Count of spelling errors
------------------------  ---------------------------  --------------------------
apache-airflow                                      7                           1
apache-airflow-providers                            4                           3
##################################################
```

**Comment by potiuk** [comment]
> Looks good but doc build fails:
> 
> ```
> The documentation has errors.
> #################### Packages errors summary ####################
> Package name                Count of doc build errors    Count of spelling errors
> ------------------------  ---------------------------  --------------------------
> apache-airflow                                      7                           1
> apache-airflow-providers                            4                           3
> ##################################################
> ```

Expected that :) , Pushed fixes

**Comment by kaxil** [comment]
:( failed again

**Comment by potiuk** [comment]
Finally! Ready  to merge!

**Review by kaxil — APPROVED** [review]

**Pull request merged**
