### PR TITLE
[AIRFLOW-4310] Fix incorrect link on DagModel list page

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-4310
  
### Description

- [x] This part of the UI isn't often used, but it was in-operable. (To get to it click on the Edit icon (first column) from dags screen, then select List. It would blow up.

  That column formatter is used in a few places (Dag, DagRun, TI) so it needs to cope with differing input types.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: tested manually. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] None

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by XD-DENG** [comment]
On mobile so can’t check in details now. But should similar change be made to **www_rbac** as well? Given you’re raising this against 1-10-stable in which we still have two sets of UI.

**Comment by ashb** [comment]
Oh yes good point, this is probably a problem there too. Let me check

**Comment by ashb** [comment]
@XD-DENG Turns out RBAC is already doing the right thing, so we just need a fix for the classic UI.

**Review by XD-DENG — APPROVED** [review]

**Comment by XD-DENG** [comment]
Restarted one failing test to confirm if it's transient error.

**Comment by XD-DENG** [comment]
@ashb , I marked "resolved" in JIRA with fix version 1.10.4

**Pull request merged**
