### PR TITLE
[AIRFLOW-1669] fix docker import fix

### PR DESCRIPTION
**Pull request by ahvigil**
There seems to have been some confusion around a revert to the docker dependency and import. https://github.com/apache/incubator-airflow/commit/fa1dc1eb20bd453687c21bb3e75ce8924105377d reverted an update to the newer `docker` package, going back to the older `docker-py` package. https://github.com/apache/incubator-airflow/pull/2653 attempted to fix some imports but accidentally broke the DockerOperator. Here I attempt to sort things out with proper imports :)

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1669

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Correct imports for `docker-py` are
```
 from docker import Client, tls
```
fixed these in the docker operator and unit tests

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

tested on command line

```
$ virtualenv docker-py && . docker-py/bin/activate && pip install "docker-py>=1.6.0"
[...]
Successfully installed docker-py-1.10.6

$ python -c "import docker; print docker.__version__"
1.10.6

$ python -c "from docker import APIClient as Client, tls"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name APIClient

$ python -c "from docker import Client, tls"
```

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ahvigil** [comment]
@Fokko I suspect these unit tests are broken because of cached wheels. `docker-py` and `docker` both inhabit the `docker` package in python so the change in requirements is probably not enough to clear things out. The imports as they are in this PR are correct, but Travis is still using `docker` syntax. Quick check:
```
virtualenv docker && . docker-py/bin/activate && pip install docker
[...]
Successfully installed docker-2.5.1
$ python -c "from docker import APIClient as Client, tls"
$ python -c "from docker import Client, tls"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name Client
```

Can someone go into Travis and manually invalidate the cache? I've done so [on my org travis build](https://travis-ci.org/Twistbioscience/incubator-airflow/builds/284499114) and hopefully those should pass having done that.

**Comment by ahvigil** [comment]
hmmm its slightly more complicated then I thought. `docker-py` gets downloaded as expected:
```
Collecting docker-py (from -r scripts/ci/requirements.txt (line 31))
  Downloading docker_py-1.10.6-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 9.8MB/s 
  Saved /home/travis/.wheelhouse/docker_py-1.10.6-py2.py3-none-any.whl
```

Then some number of lines down `docker` is loaded as a dependency of `moto`
```
Collecting docker>=2.5.1 (from moto->-r scripts/ci/requirements.txt (line 56))
  Downloading docker-2.5.1-py2.py3-none-any.whl (111kB)
    100% |█████████████████████████���██████| 112kB 9.2MB/s 
  Saved /home/travis/.wheelhouse/docker-2.5.1-py2.py3-none-any.whl
```

When we finally do the installation we end up getting the wrong version (the version to satisfy `moto` masks the earlier requirement.)

I guess we can check the version and adjust the import accordingly...

**Comment by moertel** [comment]
Just stumbled upon the same problem. The change in the `moto` package occurred [here](https://github.com/spulec/moto/pull/1048). I've [(hopefully) fixed](https://travis-ci.org/apache/incubator-airflow/builds/285437501) this by pinning the version to `1.1.19` which doesn't include the `docker` dependency. See https://github.com/apache/incubator-airflow/pull/2628/files

**Comment by ahvigil** [comment]
this PR is superseded by the fix in #2628 so closing

**Pull request closed without merging**
