### PR TITLE
Adding corresponding labels to pods created by jobs

### LINKED ISSUE #18103: Helm Chart Jobs (apache-airflow-test-run-airflow-migrations) does not Pass Labels to Pod
### Official Helm Chart version

1.1.0 (latest released)

### Apache Airflow version

2.1.3 (latest released)

### Kubernetes Version

1.18

### Helm Chart configuration

Any configuration should replicate this. Here is a simple example:

```
statsd:
  enabled: false 
redis:
  enabled: false
postgresql:
  enabled: false
dags:
  persistence:
    enabled: true
labels:
  sidecar.istio.iok/inject: "false"
```

### Docker Image customisations

Base image that comes with helm

### What happened

When I installed istio (/w istio proxy etc) on my namespace I noticed that the "apache-airflow-test-run-airflow-migrations" job would never fully complete. I was investigating and it seemed like the issue was with Istio so I tried creating a label in my values.yaml (as seen above) to disable to the istio inject - 
```
labels:
  sidecar.istio.iok/inject: "false"
```

The job picked up this label but when the job created the pod, the pod did not have this label.  It appears there's a mismatch between the job's and the pods' labels that it creates.

### What you expected to happen

I was thinking that any labels associated to job (from values.yaml) would be inherited in the corresponding pods created

### How to reproduce

1. Install istio on your cluster
2. Create a namespace and add this label to the namespace- `istio-injection: enabled`
3. Add this in your values.yaml `sidecar.istio.iok/inject: "false"` and deploy your helm chart
4. Ensure that your apache-airflow-test-run-airflow-migrations job has the istio inject label, but the corresponding apache-airflow-test-run-airflow-migrations-... pod does **not**

### Anything else

I have a fix for this issue in my forked repo [here](https://github.com/jlouk/airflow/commit/c4400493da8b774c59214078eed5cf7d328844ea)

I've tested this on my cluster and have ensured this removes the mismatch of labels between job and pod. The helm install continues without error. Let me know if there are any other tests you'd like me to run.

Thanks,
John

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jlouk**
Ensuring that we get the same labels specified in values.yaml for the jobs as we do with the created pods (from the jobs).

fixes: #18103

### CODE REVIEW

**Comment by potiuk** [comment]
Cool. I think you will need to fix some tests.  I run the workflow for you, let's see.

**Comment by jlouk** [comment]
Looks like the error is "Cannot kill container: 8be9d2c03192d171a4292fef3bc098bee2b69a6fa5abd73893e128c045cba9f9: Container 8be9d2c03192d171a4292fef3bc098bee2b69a6fa5abd73893e128c045cba9f9 is not running"

Before I do this deep dive I just wanted to check if this has ever happened before because I don't think the labels should affect this.

**Comment by potiuk** [comment]
> Looks like the error is "Cannot kill container: 8be9d2c03192d171a4292fef3bc098bee2b69a6fa5abd73893e128c045cba9f9: Container 8be9d2c03192d171a4292fef3bc098bee2b69a6fa5abd73893e128c045cba9f9 is not running"
> 
> Before I do this deep dive I just wanted to check if this has ever happened before because I don't think the labels should affect this.

Not really. It's an intermittent error.

But I think it would be great if you uppdate some tests to the chart/tests to validate that the labels are there.

**Comment by gmsantos** [comment]
@jlouk @potiuk I was planning to submit the same PR for these labels. Let me know if you want some help with the tests.

**Comment by gmsantos** [comment]
Implemented the tests as part of #18403.

**Comment by potiuk** [comment]
Closing this one as it was implemented in #18403

**Pull request closed without merging**
