### PR TITLE
[AIRFLOW-4422] Pool utilization stats

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4422
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Add metrics to record open slots and used slots in each pool (including our new `default_pool`)

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Updated `test_pool.py`.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
if we have open_slot stat(or pool starvation), is there any reason we still need occupy slot stat?

**Comment by milton0825** [comment]
With both  `open_slots` and `occupied_slots` gives you an idea of the pool utilization rate.

**Comment by milton0825** [comment]
The error seems to not related to my PR and it passed on my local build: https://travis-ci.org/milton0825/airflow/builds/548870421

**Comment by milton0825** [comment]
nvm CI is green now.

**Comment by milton0825** [comment]
PTAL @ashb @feng-tao @kaxil

**Comment by astahlman** [comment]
LGTM

**Comment by milton0825** [comment]
Some more context around why we need this two metrics:
With `pool.starving_tasks.<pool_name>` we are measuring the number of tasks that are not able to get a pool slot when the pool is full. It gives us an idea about how many more slots we should add to the pool to accommodate all the tasks if the pool is over utilized. However, when the pool size is too large while there are very few tasks, `pool.starving_tasks.<pool_name>` won't give us much insight about how "under-utilized" a pool is and here is where `pool.open_slots.<pool_name>` and `pool.used_slots.<pool_name>` come in to play. 

The reason we need both `pool.open_slots.<pool_name>` and `pool.used_slots.<pool_name>` is that it is easier to tell the utilization rate if we have both metrics on the same graph without the need to go to the Airflow UI to check the pool size.

We have very similar metrics on the executor side (https://github.com/apache/airflow/blob/master/airflow/executors/base_executor.py#L125-L127).

**Comment by milton0825** [comment]
Screen Shot 2019-06-25 at 4 11 44 PM

We will have a chart for each pool similar to above

**Pull request merged**
