### PR TITLE
Add OracleToGCS Transfer

### PR DESCRIPTION
**Pull request by tuanchris**
This PR add the OracleToGCS transfer to airflow.providers.google.cloud.transfers. This is my first PR, please let me know if any aspect could be improved.

Thank you!

Tuan

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
First quick view looks good. The tests will have to be fixed (both static checks - I heartily recommend to install pre-commit loclly and run it  see https://github.com/apache/airflow/blob/master/STATIC_CODE_CHECKS.rst) as well as the tests. What could be really useful as well is adding an example_dag and HowTo Guide for the operator. You can see plenty of examples in Google Provider, the nice thing is that you can use pieces of the example dag in the HowToGuide. 

Finally (though this is not a requirement) the example dag can be turned into a "system test" https://github.com/apache/airflow/blob/master/TESTING.rst#airflow-system-tests - we have not yet automated them, but soon we will. The example dag could be simply made into a runnable example that could perform end-2-end test of the operator. This would require connection to the actual Oracle DB though (credentials might be stored in environment variable).

**Comment by tuanchris** [comment]
Hi @potiuk, thank you for the guidance. I have been able to: 

- fix the unit test
- add howto doc
- add and example dag

I'm still struggling to get the static test to pass, though. Running pre-commit test locally is taking too long for me (stuck on pylint). Any tips on how to speed up the tests locally?

**Comment by potiuk** [comment]
It will take a while but you can run pre-commit for all files. 

By default when you install pre-commit with pre-commit install, it will only run the tests on staged files. But if you already have the commit you can run it only on the files changed in last commit by running  `pre-commit run --from-ref HEAD^ --to-ref HEAD`

This will limit the checks to only files that were modified in the last commit (yours) .

**Review by potiuk — APPROVED** [review]
Fantastic change !

**Comment by tuanchris** [comment]
@potiuk Thank you for your help! Do let me know if there's any issue/feature I can help with!

**Comment by potiuk** [comment]
Cool @tuanchris ! Glad you liked it :)

You can look at the [good-first-issue](https://github.com/apache/airflow/labels/good%20first%20issue) label - but also you can take a look at the "Airflow 2.0" cleanup [milestone](https://github.com/apache/airflow/milestones/Airflow%202.0%20clean-up) - those are things we always wanted to do and are important but not urgent (and most of them require some but not very deep knowledge of Airflow). Happy to help with any of those !.

**Pull request merged**
