### PR TITLE
[AIRFLOW-6322] Add pytest.mark.slow marker

### PR DESCRIPTION
**Pull request by dazza-codes**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6322

### Description

- [x] This adds a pytest marker for slow tests
  - related to https://github.com/apache/airflow/pull/6811#discussion_r360658365

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - this PR needs to be accepted before the marker can be used in tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - none required for this PR

### CODE REVIEW

**Comment by turbaszek** [comment]
What is the purpose of the marker? Currently we are not using any markers and introduction of this feature is [still discussed](https://lists.apache.org/list.html?dev@airflow.apache.org:lte=1M:markers). What we would like to work out is a set of markers that would allow us optimise time of CI without. @mik-laj @potiuk

**Comment by dazza-codes** [comment]
During some dev-test cycles, it can be useful to use `pytest -m 'not slow'` to skip some slow tests that are working OK but just get in the way of getting test results for other tests.
- http://doc.pytest.org/en/latest/example/markers.html

If additions to markers need to wait until discussions conclude, that's OK by me, just add this request/PR to the list of markers that could be useful.

**Comment by potiuk** [comment]
I think we'd have to decide what slow/fast means. Also we have more marks to add - especially the integration tests. What I encourage you to do is to take part in the discussion yourself and propose the slow marker and explain what you think it would mean to be classified as "slow" test. I think it's crucial to get common understanding. I am going to comment in that thread soon as I have some ideas how to start with the markers - but it's great if more voices are heard !

**Review by ashb — COMMENTED** [review]
Is there anything tagged with this?

**Comment by dazza-codes** [comment]
I want to tag something and did so in another PR, but I first need this PR to be accepted due to review concerns on the other PR and I don't want the other PR to be held up by this issue.

The question of what is `slow` is relative, of course.  When most tests on a module all complete in < 1 sec, but one of them takes up to 30 sec (and it's out of our control), the 30 sec test can be marked with `@pytest.mark.slow` and that helps to skip it so that all the other tests can run quickly and the dev-test cycle is so much faster.

**Comment by turbaszek** [comment]
In my opinion we do not need this mark, as @potiuk mentioned, it's too ambiguous. Our top 5 slowest tests:
```
========================== slowest 100 test durations ==========================
51.87s call     tests/cli/commands/test_task_command.py::TestCliTaskBackfill::test_run_ignores_all_dependencies
42.27s call     tests/providers/amazon/aws/hooks/test_lambda_function.py::TestAwsLambdaHook::test_invoke_lambda_function
38.90s call     tests/test_impersonation.py::TestImpersonation::test_impersonation_subdag
29.33s call     tests/cli/commands/test_dag_command.py::TestCliDags::test_next_execution
25.06s call     tests/executors/test_celery_executor.py::TestCeleryExecutor::test_celery_integration_1_redis_redis_6379_0
```

**Comment by potiuk** [comment]
Hey @dazza-codes @nuclearpinguin  -> just to be clear - I am not agains slow/fast/ etc. markers. quite the opposite - I think they might make quite some sense.  I am just not sure if we know what we name 'slow' and what is 'not slow' - so it would be great to discuss it and agree before we introduce such marker. Maybe we want to make "very-slow". "slow", "slowish" or something :). 

I saw projects using different strategies and naming (for example t-shirt sizes S, M, L, XL, XXL) or "big", "medium", "small". 

What I am here for is to clearly define what such markers are and what exactly we want to achieve by having them rather than introduce them first and think about how to use them later. For me introducing a term without explaining what's the context, how we are going to use it and what we want to achieve is adding noise rather than solving problem.

For example I'd say we want to have a goal "all fast tests together  should run under 2 minutes" (this is just an example) or "we want to have all the tests marked as slow if they run > 2 seconds".  And the timing summary presented by pytest might be useful to make some predictions and intelligent guesses for those values.

@dazza-codes : Just as example you can take a look at the proposal I made in the discussion at the devlist where I explained not only what markers i propose, but also how they fit in the current development environment we have, how I think we use the markers and what I want to achieve by adding those markers.  

https://lists.apache.org/thread.html/4538437c96f599766005ba7829d0bee1511debb4f53599e0d300a56f%40%3Cdev.airflow.apache.org%3E

Since we are an Apache Project all such discussions should happen in the devlist when they are affecting all community - so I encourage you to add proposal, context and explanation there - so that others can at least have a chance to see it and comment. I think discussing it in PR is not enough - as it affects all contributors. We are talking about something potentially everyone will use.

Feel free to continue it in this discussion or start your own thread! Even if you have no concrete vision yet, you can start discussing it there and maybe others will have and join your discussion.

**Comment by dazza-codes** [comment]
The marker definitions will be decided and defined outside of this PR - closing this in deference to something else.

**Pull request closed without merging**
