### PR TITLE
[AIRFLOW-3004] Add config disabling scheduler cron

### PR DESCRIPTION
**Pull request by xales**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3004
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This adds an option that allows for the disabling of the scheduler's automatic creation of jobs by their `schedule`. It will continue to schedule `TaskInstance`s that are created manually, such as via the UI or `trigger_dag`.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Adding config option

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

Added documentation to default/example config, will look for other places to refer to this option if needed.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
I wonder what is the use case to disable it?

**Comment by harikak84** [comment]
This can be used as your QA environment with no dags on schedule

**Comment by harikak84** [comment]
We were planning on building something similar...to just check if our dags executes end to end with no errors in it. If it is successful with manual triggers, then we will push it to for schedule

**Comment by xales** [comment]
> This can be used as your QA environment with no dags on schedule
That's the planned use case for it, as well as if, for whatever reason, production jobs need to be stopped - the scheduler can be restarted with the config updated and the queue will drain without anything new entering, unless manually triggered.

**Comment by feng-tao** [comment]
LGTM. The use case makes sense.

**Pull request merged**
