### PR TITLE
Fix oversized width of DAGs table with hide/reveal of "links"

### LINKED ISSUE #11795: links wrapping on standard-width browser
on my macbook pro w/ chrome full width…

Screen Shot 2020-10-23 at 3 01 04 PM

if i bump down to 90%...

Screen Shot 2020-10-23 at 3 02 08 PM

so i wonder if we should:

A) reduce font size, or 
B) roll the links up under a gear-icon-dropdown (which would allow us to put words next to the icons, which isn't all bad)

### PR DESCRIPTION
**Pull request by ryanahamilton**
Resolves #11795

This update improves the presentation of the DAGs (home) view by making better use of the horizontal space. This was accomplished through a handful of changes:

- Fixed the broken tooltip on the "i" icon in the leftmost column heading by adding missing `js-tooltip` class.
- Moves the tags beneath the DAG ID. By not having left and right aligned elements within the same column, the contents of the cell flow better with the variation of screen widths, and there is less visual distraction with a single alignment point.
- Changes the tag background from green to blue. Green typically communicates a positive status, but in this context the tag has no relation to the DAG's status. The blue is a better neutral color. 
- Changed the column order to a more logical organization. Going left-to-right the order now displays broader-to-detailed properties of the DAG. It also seemed to make more sense to have "schedule" and "last run" adjacent to each other given the former determines the latter.
- Moved the existing CSS only used for this view out of the shared (`main.css`) file to a dedicated `dags.css` file only loaded for this view. The new CSS added in this PR was added to this file as well.
- With the "links" taking up a great deal of space and not providing any actual detail of the DAGs, I've moved them to a hidden menu in the last column of the table. The menu is revealed upon hover of the "•••". In addition to saving space, this alleviates a lot of the visual clutter of having so many icons grouped  throughout the page. Additionally, this allows text to be displayed beside the link icons—providing much better information to the user. I've reversed the prior order of the links in order to reduce the mouse travel to the most popular (tree, graph).

Screen Recording 2020-10-28 at 11 24 31 AM

- Doc screenshot of this view has been updated accordingly.

## Screenshots of overall updates

**Full width - Before**

Image 2020-10-26 at 5 22 18 PM

**Full width - After**

Image 2020-10-26 at 5 23 16 PM

___

**Narrow width - Before**

Image 2020-10-26 at 5 21 33 PM

**Narrow width - After**

Image 2020-10-26 at 5 11 22 PM

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
Interesting approach.

One thing to bear in mind: the links are used more than the actions are -- at least the tree view and graph view links are.

**Comment by ryanahamilton** [comment]
@ashb in the context of the view/table's role as a bird's-eye-view across DAGs, neither the "links" or "actions" are really supporting that purpose, so they seemed most obvious to truncate. Given the sheer quantity of the links and the visual clutter they add, they appeared to be the best candidate. I suppose the actions could be moved within the "more" menu as well if that was desired?

**Comment by ashb** [comment]
More saying in terms of which is clicked not often - some links are much more commonly used then others, and those are used more often them actions.

It's too late for me to come to a conclusion of that thought

**Comment by ryw** [comment]
Yes I agree - I click tree/graph view the most - and it's easy for me to forget what clicking the DAG name will take me too.

One way to consider this change is that if @ryanahamilton was proposing to do the opposite (change from his proposal to our current reality) we'd surely shoot it down :)

I'm +1 to merge this and keep iterating, as it's a UX improvement.

**Comment by ryw** [comment]
@mistercrunch what do you think of this one?

**Comment by mistercrunch** [comment]
Neat!

Side note, the status circles have gotten numerous, there's certainly a better way to visualize this information.

**Comment by ryanahamilton** [comment]
Appreciate the feedback on this everyone. It seems that everyone is agreement that the density of this view has grown out-of-control. I think I'll be able to offer some additional follow-up adjustments to keep refining it.

I did just push one update to reverse the order of the links—this will reduce the mouse travel distance for the more popular links (tree, graph). (see updated GIF in PR description)

**Comment by ryw** [comment]
Yeah I like the reversal

**Review by ryw — APPROVED** [review]

**Review by ashb — APPROVED** [review]
Let's go for it, and see what people think of it -- we can always change something back or pull tree and graph view out if needed

**Pull request merged**
