### PR TITLE
Mount ${HOME}/.aws in breeze environemnt if --forward-credentials

### PR DESCRIPTION
**Pull request by xinbinhuang**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by xinbinhuang** [comment]
Seems Travis is upset about some UI tests, but it is not relevant to this PR?

**Comment by zhongjiajie** [comment]
Restart the failing test

**Review by zhongjiajie — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Merge even if Travis unhappy, unrelated and today in other PR.

**Comment by zhongjiajie** [comment]
@xinbinhuang Thanks.

**Comment by xinbinhuang** [comment]
@zhongjiajie @potiuk @mik-laj  Thanks for reviewing and merging!

**Pull request merged**
