### PR TITLE
Fix wrong logs depupe in UI

### PR DESCRIPTION
**Pull request by artemSSSS**
related: #41225

In this PR, a bug with removing duplicate lines in a single log has been fixed.

### CODE REVIEW

**Comment by eladkal** [comment]
Can you fix the static checks?

**Comment by artemSSSS** [comment]
All checks have passed

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
Should this be considered a bugfix and backported to 2.10?

**Comment by potiuk** [comment]
> Should this be considered a bugfix and backported to 2.10?

I'd say so. @artemSSSS - can you please back-port it and make a PR to `v2-10-test` branch ?

**Pull request merged**
