### PR TITLE
[AIRFLOW-442] SFTPHook

### PR DESCRIPTION
**Pull request by sdiazb**
Dear Airflow maintainers,

Please accept this PR. 

### JIRA
- [x] My PR addresses the jira issue [AIRFLOW-442](https://issues.apache.org/jira/browse/AIRFLOW-442) 

### Description
- [x] SFTP Hook.

### Tests
- [x] My PR adds the following unit tests (interacting with the Travis OpenSSH Server): https://github.com/sdiazb/airflow/blob/sftp_hook/tests/contrib/hooks/test_sftp_hook.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)".

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you squash your commits please?

**Comment by sdiazb** [comment]
Hi @bolkedebruin. I think if we squash the commits here, we'll lose the ownership of the original code as more than one developer participated in this PR. Is there a problem in having two different commits? If so, is there a way to squash the commits while preserving who modified each line? Thanks in advance.

**Comment by sdiazb** [comment]
Hi @bolkedebruin. Hope you are doing great. I am sure you are pretty busy over there but I just wanted to reach out to see if you are ok with maintaining the two commits separated to keep the ownership of the work done in each one of them by different developers. Many thanks again!

EDIT: tagging @mistercrunch, @artwr and @skudriashev as suggested by the bot.

**Comment by sdiazb** [comment]
Hi guys @bolkedebruin @mistercrunch @artwr @skudriashev !

Just checking on this again as I've recently received some emails from people that are finding this feature useful to be merged. Do you think we can progress with it any time soon? If you have the time to review this, it can be interesting to review [this PR with sensor](https://github.com/apache/incubator-airflow/pull/2522) as well.

Thanks in advance!

**Comment by Fokko** [comment]
@sdiazb Please squash your commits and rebase onto master, there are some merge conflicts which need to be resolved before we can merge this.

**Comment by sdiazb** [comment]
@Fokko thanks for the suggestion, I've address them. Please, let me know if we need to change something else to get it merged. Thanks in advance.

**Comment by Fokko** [comment]
Thanks @sdiazb I'll merge it, it looks wel tested. Cheers

**Comment by tuckdruck** [comment]
Hi all, when will this hook be included in a release?

**Comment by artwr** [comment]
@avitaldrucker I believe this commit is included in the 1.10 beta which we are currently testing.

**Pull request closed without merging**
