### PR TITLE
Fix `breeze --backend mssql`

### PR DESCRIPTION
**Pull request by ephraimbuddy**
`breeze --backend mssql` is not working and this fixes it

### CODE REVIEW

**Comment by ephraimbuddy** [comment]
Another option would be to have `breeze --backend mssql` use `backend-mssql-bullseye.yml` as the file is the same as this `backend-mssql.yml`

**Comment by jedcunningham** [comment]
Should we symlink it then instead?

**Comment by potiuk** [comment]
They actually were different - let me fix it really quickly.

**Comment by potiuk** [comment]
Better fix here: https://github.com/apache/airflow/pull/23368

**Comment by potiuk** [comment]
The problem was that we neede to differentiate between buster and bullseye MSSQL clients as they have slightly different support for SSL and I had to be creative and introduce different compose files for those two.

The change in #23368 adds back the capability to choose different compose for mssql based on the debian version used.

**Comment by jedcunningham** [comment]
Closing this as #23368 has been merged.

**Pull request closed without merging**
