### PR TITLE
Extend --from-job and --from-pr to PROD images as well

### PR DESCRIPTION
**Pull request by potiuk**
Building on top of #45287 we also add the same capability for PROD images. Additionally:

* the token is required so it is passed as obligatory --github-token option (with GITHUB_TOKEN env var as source of it). Help contains link to generate the token so that it can be easily generated.

* error messages contain message text on top of error code

* the --github-repository is used to determine the right github repo to use when calling the API.

* PROD image platform escaping used `-` instead of `-` which make it impossible to find the artifact when looking for it. This has been fixed.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I tried to get PROD image and realized it was not implemented :). So I added it, found a typo in PROD load/save and improved a bit github_token/  github_repository behaviour : @gopidesupavan :D

**Comment by potiuk** [comment]
BTW. Side effect of the #45266 that PR workflow sshould not work almost as well (minus caching speed from registry) for PRs internaly done in a different repository - without having to setup GitHub registry - which was huge limitation of the "pull_retquest_target" workflow. This means that it should be entirely possible for anyone to test their PR locally using their own github runners - in their own repository in-repo PR and it should **just work** - including storing the image artifacts - that's why it is important to use `--github-repository` flag whenever possible :)

**Review by gopidesupavan — APPROVED** [review]
cool :) ah prod is there , Thanks for the update

**Comment by gopidesupavan** [comment]
> I tried to get PROD image and realized it was not implemented :). So I added it, found a typo in PROD load/save and improved a bit github_token/ github_repository behaviour : @gopidesupavan :D

Yeah good catch :) thank you

**Pull request merged**
