### PR TITLE
Revert "Add tests to PythonOperator (#30362)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit b4f3efd36a0566ef9d34baf071d935c0655a02ef.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
The #30362 after merging started to fail main - it looks like it was 14 commits behind when merged and some of the earlier commits made it fail it needs to be re-created and failing tests fixed cc: @vincbeck

**Comment by potiuk** [comment]
Or maybe there is a different reason. Looking for it.

**Comment by potiuk** [comment]
Yes. Looks like it's this one - at least reverting it fixes the problem it seems. We should merge it quickly to prevent other tests from failing.

**Review by eladkal — APPROVED** [review]
cc @vincbeck we'll need to redo the PR

**Comment by potiuk** [comment]
Also @vincbeck - where you are back at it, it's a rather weird one. It definitely helped when I reverted it, but I could not reproduce it on my Mac. My current suspect is the new Python version released by Python maintainers 2 days ago caused it
When you will re-open it, we will see if things are still the same, :)

**Comment by vincbeck** [comment]
Sounds good! I'll take a look at it today

**Comment by vincbeck** [comment]
See #30583

**Pull request merged**
