### PR TITLE
[AIRFLOW-5862] Fix failing build on kubernetes

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5862

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by potiuk** [comment]
It worked in the PR but did not work after merging to master because of the optimisations of Travis build scripts - > common dir was missing in the new Docker and it was needed in the new Kubernetes scripts but the Kubernetes scripts have not changed so we have a weakness in the optimisation scripts.

**Comment by potiuk** [comment]
I made the tests a bit more "smart"  - they will also run kubernetes/unit tests also whenever any of the scripts/ci files change. That should prevent this happening in the future.

Please take a look asap - for now we have master failing.

**Review by feluelle — APPROVED** [review]
LGTM

**Comment by feluelle** [comment]
But shellcheck hook is complaining:

```
Check Shell scripts syntax correctness...................................Failed

hookid: shellcheck

Unable to find image 'koalaman/shellcheck:stable' locally

stable: Pulling from koalaman/shellcheck

Status: Downloaded newer image for koalaman/shellcheck:stable

Unable to find image 'koalaman/shellcheck:stable' locally

stable: Pulling from koalaman/shellcheck

Status: Downloaded newer image for koalaman/shellcheck:stable

In scripts/ci/ci_run_airflow_testing.sh line 73:

if [[ ${START_KUBERNETES_CLUSTER} == "true" ]]; then

                                                ^-- SC1009: The mentioned syntax error was in this then clause.

In scripts/ci/ci_run_airflow_testing.sh line 80:

    # shellcheck: disable=SC2016

    ^-- SC1073: Couldn't parse this shellcheck directive. Fix to allow more checks.

                ^-- SC1072:  Fix any mentioned problems and try again.

For more information:

  https://www.shellcheck.net/wiki/SC1072 --  Fix any mentioned problems and t...

  https://www.shellcheck.net/wiki/SC1073 -- Couldn't parse this shellcheck di...

  https://www.shellcheck.net/wiki/SC1009 -- The mentioned syntax error was in...
```

**Comment by feluelle** [comment]
@potiuk 

```
======================================================================

1) FAIL: test_integration_run_dag (tests.integration.kubernetes.test_kubernetes_executor.TestKubernetesExecutor)

----------------------------------------------------------------------

   Traceback (most recent call last):

    tests/integration/kubernetes/test_kubernetes_executor.py line 198 in test_integration_run_dag

      expected_final_state='success', timeout=100)

    tests/integration/kubernetes/test_kubernetes_executor.py line 105 in monitor_task

      self.assertEqual(state, expected_final_state)

   AssertionError: 'queued' != 'success'

   - queued

   + success

   

   -------------------- >> begin captured stdout << ---------------------

   Found the job with execution date 2019-11-07T11:47:40+00:00

   Attempt 0: Current state of operator is queued

   Attempt 1: Current state of operator is queued

   Attempt 2: Current state of operator is queued

   Attempt 3: Current state of operator is queued

   Attempt 4: Current state of operator is queued

   Attempt 5: Current state of operator is queued

   Attempt 6: Current state of operator is queued

   Attempt 7: Current state of operator is queued

   Attempt 8: Current state of operator is queued

   Attempt 9: Current state of operator is queued

   Attempt 10: Current state of operator is queued

   Attempt 11: Current state of operator is queued

   Attempt 12: Current state of operator is queued

   Attempt 13: Current state of operator is queued

   Attempt 14: Current state of operator is queued

   Attempt 15: Current state of operator is queued

   Attempt 16: Current state of operator is queued

   Attempt 17: Current state of operator is queued

   Attempt 18: Current state of operator is queued

   Attempt 19: Current state of operator is queued

   

   --------------------- >> end captured stdout << ----------------------

   -------------------- >> begin captured logging << --------------------

   airflow.utils.log.logging_mixin.LoggingMixin: INFO: Reading the config from /root/airflow/airflow.cfg

   airflow.settings: INFO: Configured default timezone <Timezone [UTC]>

   --------------------- >> end captured logging << ---------------------

======================================================================

2) FAIL: test_integration_run_dag_with_scheduler_failure (tests.integration.kubernetes.test_kubernetes_executor.TestKubernetesExecutor)

----------------------------------------------------------------------

   Traceback (most recent call last):

    tests/integration/kubernetes/test_kubernetes_executor.py line 225 in test_integration_run_dag_with_scheduler_failure

      expected_final_state='success', timeout=120)

    tests/integration/kubernetes/test_kubernetes_executor.py line 105 in monitor_task

      self.assertEqual(state, expected_final_state)

   AssertionError: 'queued' != 'success'

   - queued

   + success

   

   -------------------- >> begin captured stdout << ---------------------

   Found the job with execution date 2019-11-07T11:49:23+00:00

   Attempt 0: Current state of operator is queued

   Attempt 1: Current state of operator is queued

   Attempt 2: Current state of operator is queued

   Attempt 3: Current state of operator is queued

   Attempt 4: Current state of operator is queued

   Attempt 5: Current state of operator is queued

   Attempt 6: Current state of operator is queued

   Attempt 7: Current state of operator is queued

   Attempt 8: Current state of operator is queued

   Attempt 9: Current state of operator is queued

   Attempt 10: Current state of operator is queued

   Attempt 11: Current state of operator is queued

   Attempt 12: Current state of operator is queued

   Attempt 13: Current state of operator is queued

   Attempt 14: Current state of operator is queued

   Attempt 15: Current state of operator is queued

   Attempt 16: Current state of operator is queued

   Attempt 17: Current state of operator is queued

   Attempt 18: Current state of operator is queued

   Attempt 19: Current state of operator is queued

   Attempt 20: Current state of operator is queued

   Attempt 21: Current state of operator is queued

   Attempt 22: Current state of operator is queued

   Attempt 23: Current state of operator is queued

   

   --------------------- >> end captured stdout << ----------------------
```

**Comment by potiuk** [comment]
I reverted the original #6496 as i need to fix those problems first. So I close this one and will merge it into final version of kind improvement.

**Pull request closed without merging**
