### PR TITLE
[AIRFLOW-4822] Fix issue when clearing task instance of subdag, irrelevant task with…

### PR DESCRIPTION
**Pull request by djFFFFF**
…in parent dag might be cleared as well.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4822
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
When clearing a parent dag, a regex which matches the parent's dag's dag_id exactly should be passed as task_regex.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
No unit tests added.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by djFFFFF** [comment]
We're using airflow version 1.10.1 and we found this problem. It's not critical but is rather annoying. As for 2019-06-20, it is not fixed on the master branch yet. I uploaded dag file and screenshots on the corresponding Jira issue.

**Comment by feng-tao** [comment]
cc @milton0825

**Review by ashb — CHANGES_REQUESTED** [review]
Could you add a unit test please?

**Comment by djFFFFF** [comment]
Sure ^.^

**Comment by djFFFFF** [comment]
@ashb Updated existing unit test: BackfillJobTest.test_subdag_clear_parentdag_downstream_clear to cover scenarios related to this bug. Added a specific testing dag for this unit test.

Also the original unit test did not fullfill its purpose: even if the subdag is not cleared, the status of task instance `some-other-task` and the subdag's downstream tasks would still be ```State.NONE```, because only the subdag was executed at the very first place.

**Comment by djFFFFF** [comment]
@ashb ready for review. The 'changes requested' status somehow cannot be changed

**Review by ashb — APPROVED** [review]

**Pull request merged**
