### PR TITLE
Added test for get_blobs_list method

### PR DESCRIPTION
**Pull request by jayrumi**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by turbaszek** [comment]
Hi @jayrumi I think this commit should be part of this PR: https://github.com/apache/airflow/pull/9950

**Comment by jayrumi** [comment]
@turbaszek I need your help again :) How should I correct it? Do I need to merge patch-1 and patch-2?

**Comment by turbaszek** [comment]
You can perform the merge but it's better to cherry-pick this commit to your `patch-1` branch:
https://devconnected.com/how-to-cherry-pick-git-commits/

```
git checkout patch-2
git log --oneline
# copy hash of the last commit "Added test for get_blobs_list method"
git checkout patch-1
git cherry-pick <hash>
```

**Comment by jayrumi** [comment]
@turbaszek thanks again! :) I cherry-picked

**Comment by turbaszek** [comment]
Nice! Closing because of #9950

**Pull request closed without merging**
