### PR TITLE
Fix "Invalid JSON configuration, must be a dict"

### PR DESCRIPTION
**Pull request by janarthanandev**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by janarthanandev** [comment]
hi @kaxil @uranusjr @msumit , These issue was fixed in 2.1.2 but doesn't backported to 2.1.2, so creating pr 
invalid_json

**Comment by jedcunningham** [comment]
@janarthanandev, it looks to me like this change was actually cherry-picked to 2.1.2. Your `v2-1-stable` branch is behind. I also see `v2.1.1` in the footer of your screenshot.

Some links -
The cherry-pick commit: https://github.com/apache/airflow/commit/4c1abfbe0966969929f32a2adc57e9835bac9312
`2.1.2` tag: https://github.com/apache/airflow/blob/2.1.2/airflow/www/views.py#L1513
HEAD of `v2-1-stable`: https://github.com/apache/airflow/blob/2b80c1edec85fb2b0312b6ae7f415c6f744e322e/airflow/www/views.py#L1514

**Comment by janarthanandev** [comment]
> @janarthanandev, it looks to me like this change was actually cherry-picked to 2.1.2. Your `v2-1-stable` branch is behind. I also see `v2.1.1` in the footer of your screenshot.
> 
> Some links -
> The cherry-pick commit: [4c1abfb](https://github.com/apache/airflow/commit/4c1abfbe0966969929f32a2adc57e9835bac9312)
> `2.1.2` tag: https://github.com/apache/airflow/blob/2.1.2/airflow/www/views.py#L1513
> HEAD of `v2-1-stable`:
> 
> https://github.com/apache/airflow/blob/2b80c1edec85fb2b0312b6ae7f415c6f744e322e/airflow/www/views.py#L1514

hi @jedcunningham Yes, it's true we are recently migrated 2.1.1 version and it's tough to migrate again 2.1.2. so only we are requesting for fix in 2.1.1

**Comment by uranusjr** [comment]
I don’t understand. 2.1.1 is already out so we can’t just change the code. We need to release a new version, and that is 2.1.2.

**Pull request closed without merging**
