### PR TITLE
[AIRFLOW-4199][AIP-3-step3] Remove all sys version info

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4199
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Restart CI test after CI test remove python2 job.

Remove all sys.version_info[0] == 3 except setup.py due to Jira have other sub task https://jira.apache.org/jira/browse/AIRFLOW-4202

**Comment by Fokko** [comment]
Can you rebase onto master?

**Comment by zhongjiajie** [comment]
Same Issue as https://github.com/apache/airflow/pull/5020, I submit a PR https://github.com/apache/airflow/pull/5090 to fix this

raise error in CI process

```py
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python2.7/dist-packages/airflow/__init__.py", line 36, in <module>
    from airflow import settings, configuration as conf
  File "/usr/local/lib/python2.7/dist-packages/airflow/settings.py", line 35, in <module>
    from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
  File "/usr/local/lib/python2.7/dist-packages/airflow/configuration.py", line 108, in <module>
    DEFAULT_CONFIG = _read_default_config_file('default_airflow.cfg')
  File "/usr/local/lib/python2.7/dist-packages/airflow/configuration.py", line 104, in _read_default_config_file
    with open(file_path, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```

because python2 have not keyword in `open` function

**Comment by zhongjiajie** [comment]
CI green, PTAL @Fokko @potiuk @XD-DENG thanks.

**Comment by potiuk** [comment]
Can you please rebase @zhongjiajie  (again :( , sorry) - quite a number of conflicts due to parallell py3 merges.

**Comment by zhongjiajie** [comment]
@potiuk Don't be sorry, I rebase and squash commit into one commit. Waiting for CI.

**Comment by zhongjiajie** [comment]
@potiuk  FYI, CI green.

**Review by kaxil — APPROVED** [review]

**Comment by zhongjiajie** [comment]
@kaxil Thanks for merging.

**Comment by feng-tao** [comment]
@kaxil, @potiuk , @ashb, @bolkedebruin  are we supposed to change the vendor files? I thought files under vendor dir are meant for copy paste from upstream without any change? Or I understand incorrectly?

**Comment by feng-tao** [comment]
cc @milton0825

**Comment by potiuk** [comment]
Maybe I am missing something but here is my understanding (from looking at the logs at least): 

Those files in _vendor dir have been modified already in the past - they were modified so that we do not have to pull-in the GPL dependency - we cannot have it from pypi so we brought it in with original version: e36bdef0b34c16def20ecbb8248950070eb5fa33 and later modified those to remove the GPL dependency: 59a7a79c7dc446b723185b346b6fc2f6ffef82dc. And I think we already think about replacing the nvd3 library soon-ish (I saw that we are looking for nvd3 replacement for example) - which in turn will remove the need for slugify.

I don't really think there is harm in modifying the files - there is a very slim chance we are going to upgrade to a later version, but even if we do - we should be able to re-apply our own changes anyway. We try to make it in separate commits (https://github.com/apache/airflow/pull/5168) so that we can later cherry-pick those changes in case we want to upgrade to newer version of the library. 

I think this current change here was a bit unfortunate because the slugify change was not separated out to separate commit, but it's so small change that it will be no problem to re-apply it in case we upgrade.

I guess there are also no licensing limitations that would prevent us from doing so - both libs are MIT licence that allows us to modify this code.

**Comment by feng-tao** [comment]
thanks @potiuk for the explanation:) Make sense. My initial concern is more on whether we are allowed to modify the source code directly.

**Comment by ashb** [comment]
We can modify the source  - I personally wouldn't have bothered so that the vendored libraries are as close as possible to stock just so that seeing our _important_ changes is as easy as possible.

**Pull request merged**
