### PR TITLE
Add `on_kill` to Databricks Workflow Operator

### PR DESCRIPTION
**Pull request by R7L208**
The Databricks Provider did not implement `on_kill` to cancel tasks generated by `_CreateDatabricksWorkflowOperator`. This led to data quality issues, where Airflow would report a cancellation due to timeout; however, the corresponding workflow task would continue to run on Databricks.

This PR implements `on_kill` for `_CreateDatabricksWorkflowOperator`.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by R7L208** [comment]
hey @pankajkoti - Any ETA on when you'd be able to review this PR? 🙏

**Review by pankajkoti — COMMENTED** [review]
hi @R7L208 Apologies, I missed reviewing it so far.

I am happy to review the changes for `databricks_workflow.py` but not so comfortable yet reviewing the changes in `databricks_sql.py` (operators & hooks) as I do not have enough expertise on the changes made there. Would you please to separate out the two changes(move out databricks_sql.py related changes to another PR) and then we can invite some expert to review the other PR?

**Comment by R7L208** [comment]
Opened #42668 

@pankajkoti @eladkal - can you please assign someone to review?

**Review by pankajkoti — APPROVED** [review]

**Comment by pankajkoti** [comment]
@R7L208 Can you please update the PR description based on the altered scope of this PR?

**Comment by pankajkoti** [comment]
> @pankajkoti - it's been updated

it's not. It mentions about DatabricksSqlHook queries ("SQL queries submitted by DatabricksSqlHook") & using threading ("uses threading to cancel SQL queries submitted by DatabricksSqlHook.run()") which we no longer have in this PR. Could you please re-read the description and update to what's limited to the scope of this PR.

Also, _CreateDatabricksWorkflowOperator does not rely on DatabricksSqlHook, but leverages DatabricksHook just in case you missed checking that :)

**Comment by R7L208** [comment]
@pankajkoti - Apologies! I read PR title instead of PR description 🤦 

PR description is now updated

**Review by Lee-W — APPROVED** [review]

**Pull request merged**
