### PR TITLE
[AIRFLOW-1968] STS Role Assumption Credential Strategies

### PR DESCRIPTION
**Pull request by CannibalVox**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

In PR2532 (AIRFLOW-1520), the AWS credential code was refactored into a general
 AWS hook.  When that change was made, the existing assume role code was
 removed, leaving only ID/Secret credentials as an option.  Our dags rely on
 role assumption to access external S3 buckets, so this code re-adds role
 assumption via STS.

Additionally, in order to make this a bit easier, I changed _get_credentials to
 return a functioning boto3 session which is used by the public methods to
 initialize clients/resources/whatever.  This seemed a better route than
 adding another returnval in an already long list.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@Fokko can you review this?

**Comment by Fokko** [comment]
@CannibalVox Can you rebase?

@bolkedebruin I'm currently working on the Google Cloud, perhaps @NielsZeilemaker can take a look at it :)

**Comment by CannibalVox** [comment]
@Fokko I think we're good

**Comment by CannibalVox** [comment]
@NielsZeilemaker Is there anything you need me to look into?

**Comment by NielsZeilemaker** [comment]
So the _get_credentials method is basically a pretty bad attempt from me to make the boto2 stuff working with boto3. Any improvements should help as there weren't any unit tests for it at the time I made the changes. So it looks pretty OK by me

**Comment by CannibalVox** [comment]
@bolkedebruin Any thoughts?

**Pull request closed without merging**
