### PR TITLE
Fix typos, older versions, and deprecated operators with AI platform example DAG

### PR DESCRIPTION
**Pull request by vuppalli**
The AI platform example DAG had typos, was using older versions, and had deprecated operators. This PR is an attempt to fix these problems and corresponds to [this Github issue](https://github.com/apache/airflow/issues/9418). The relevant documentation will be updated soon (most likely next week), which corresponds to [this Github issue](https://github.com/apache/airflow/issues/8207). I will address any comments next Monday (07/06) since we have US holidays for the rest of the week. I look forward to getting feedback!

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by vuppalli** [comment]
@mik-laj You mentioned that this DAG does not have accompanying tests. How should I go about addressing the Unit tests coverage bullet above? Additionally, should I make this a draft PR while I work on the corresponding documentation?

**Comment by mik-laj** [comment]
@vuppalli  We don't need unit tests for DAG. We use them in the documentation and in system tests. System tests are sufficient in this case.  Have the files that are needed to run the tests changed? 

It is better if the contribution is small because then it is much easier to review and merge in the project. In this case, I would prefer you to create a new PR that will only contain documentation. If you need any changes that are included in this PR then you can copy the changes from this PR and add annotations in the PR title `[depends on XXXX]`.  Additionally, you can add a note in the description, but not everyone reads the description of the changes.
Example:
```
Add guide for MLEngine [depends on #9618]
```

In order for this change to be merged, you must fix static check errors in this change.
```
airflow/providers/google/cloud/example_dags/example_mlengine.py:29:89: W291 trailing whitespace
airflow/providers/google/cloud/example_dags/example_mlengine.py:30:80: W291 trailing whitespace
```
+ isort
For more information: 
https://github.com/apache/airflow/blob/master/STATIC_CODE_CHECKS.rst#id1

How do you like an internship at Google? Do you have any concerns about contributing to Open Source? The community of this project is very open to new contributors and interns. We currently have two active interns who contribute to the project. If you would like to get more involved in this project, we'll be happy to help. Apache Airflow is the core of the Cloud Composer service, so contributions to this project will be appreciated by your company.

**Comment by vuppalli** [comment]
@mik-laj Thanks so much for your response. I am not sure which files are needed to run the tests so I do not know if they have changed. The only file I have contributed to is the example DAG. Also, I have fixed the trailing whitespace issues and will create a new PR for the guide sometime this week. 

I am really enjoying my internship at Google and this contribution is quite relevant the work I am doing! Since I am working with Cloud Composer and AI Platform, I am grateful to have helped with this contribution as I learned a lot about both products. I would love to get more involved with Open Source and appreciate the help!

**Comment by mik-laj** [comment]
@vuppalli Are you available on our official Airflow Slack channel? https://apache-airflow-slack.herokuapp.com/ If you plan to contribute more to Airflow, we can coordinate my team and your work. My team looks after all Google integrations, so we'll have a lot of contacts.

**Comment by vuppalli** [comment]
@mik-laj Yes, thank you!

**Comment by mik-laj** [comment]
I sent DM to you. ;-)

**Pull request closed without merging**
