### PR TITLE
reduce eyestrain in dark mode with reduced contrast and saturation

### PR DESCRIPTION
**Pull request by codecae**
While the new dark mode is very appreciated, the inversion and 180 degree hue rotation creates a harsh contrast that some people find a bit extreme and uncomfortable.  This change simply lowers the saturation and contrast to soften the overall appearance, potentially reducing eyestrain for people with eyes that are sensitive to such high contrast.

Adjusting the contrast also emphasizes the styling between alternating rows in the DAG list. 

Open to suggestions to better tweak it for a broader audience.  

Before:
airflowbefore
airflowbefore

After:
image
airflowafter

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jscheffl** [comment]
Can you add a screenshot to the description to before and after for the reviewers?

Note that actually the UI is currently re-workers and gets a totally different dark-mode in Airflow 3.0. In Airflow 2 we actually only want to make bug fixes. No new features. So we woul dneed to classify this as bug fix? @bbovenzi WDYT?

**Comment by codecae** [comment]
> Can you (please) add a screenshot to the description to before and after for the reviewers?
> 
> Note that actually the UI is currently re-workerd and gets a totally different dark-mode in Airflow 3.0. In Airflow 2 we actually only want to make bug fixes. No new features. So we would need to classify this as bug fix? @bbovenzi WDYT?

Understand that this is considered an experimental feature and likely will be be deprecated up the next major release.  Until then, I figured that there might be some teams out there that would appreciate this subtle, yet effective styling update.

I've added screenshots to the description.

**Review by bbovenzi — APPROVED** [review]
if we do another patch release, then I'm happy to include this as a bug fix.

**Comment by codecae** [comment]
Thanks for the approval @bbovenzi !

Speaking of 3.0 UI updates -- Does anyone know if #35301 will be addressed in 3.0?

**Review by pierrejeambrun — APPROVED** [review]

**Comment by potiuk** [comment]
Nice. That was also bothering me.

**Pull request merged**
