### PR TITLE
[Backport] Deprecate implicit default DAG schedule

### PR DESCRIPTION
**Pull request by uranusjr**
This backports #41321 to 2.10.

### CODE REVIEW

**Comment by potiuk** [comment]
I think you need to rebase it now @uranusjr to trigger tests after #41476 has been cherry-picked to v2-10-test

**Comment by potiuk** [comment]
Yeah. Some small fixes are still needed as expected #41478 and  #41480 - likely some cache speedup will be needed as well

**Comment by potiuk** [comment]
Ok. Try to rebase and see if it will work now @uranusjr

**Review by kaxil — APPROVED** [review]
Should we add a newsfragment ?? so maybe we can have a deprecated section in 2.10.1 or 2.11 docs

**Review by vincbeck — APPROVED** [review]

**Pull request merged**
