### PR TITLE
Add fk between xcom and task instance

### PR DESCRIPTION
**Pull request by uranusjr**
As discussed previously.

Also improved the dag_run relationship to use the dag_run_id field directly because why not?

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Comment by uranusjr** [comment]
Forgot to mention, we can do this directly because the prior `select` in the migration already filtered out all `xcom` rows without a matching `dag_run` row, and since `task_instance` already has a foreign key to `dag_run`, it is not possible to have dangling `xcom` rows when we add the fk constraint in the migration.

**Comment by uranusjr** [comment]
Eh, need to fix tests now though, we are currently doing a lot of dangling inserts.

**Comment by uranusjr** [comment]
Alright hopefully this fixes everything. Mostly changing the test code, but I also needed to change how `airflow task test` works conceptually to make this foreign key work (see the commit referencing this command). Currently `airflow task test` would create a “fake” DAG run in-memory to run just that task, but this does not work well with database-level foreign key. So instead I make this command always create a “real” DAG run in the database, and delete it (with everything the run generates because `ON DELETE CASCADE`) after the task is run. Personally I think this is better because now this command is no longer a weird outlier on database integrity, but not sure if this is an acceptable semantic change.

**Comment by ashb** [comment]
Some good to me

**Pull request merged**
