### PR TITLE
[AIRFLOW-1821] Enhance default logging config by removing extra loggers

### PR DESCRIPTION
**Pull request by jgao54**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1821

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- The default_logging_config file has 5 loggers: root, airflow, airflow.task, airflow.task_runner, airflow.processor. This could be simplified to root, airflow.task, and airflow.processor given python logging inheritance. (Noe that this requires a directory structure change from airflow/task_runner/ → airflow/task/task_runner/)

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

cc @bolkedebruin @Fokko @allisonwang @criccomini 

I think there are still room for simplifying the logging setup further, but which may require a bigger discussion. This PR focuses on preventing folks from making the mistakes that we did, by removing some surface area for logger configuration that could otherwise lead to confusion.

### CODE REVIEW

**Comment by Fokko** [comment]
Good morning @jgao54,

Thanks for your commit. Personally I'm always in favor of making this simpler. This allows us to focus on the more complex things ;)

Have you tested this in your local environment? There is a lot happening in the logging lately.

Some tests are still failing:
```
======================================================================
13) FAIL: test_default_task_logging_setup (tests.utils.test_log_handlers.TestFileTaskLogHandler)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/utils/test_log_handlers.py line 46 in test_default_task_logging_setup
      self.assertEqual(handler.name, FILE_TASK_HANDLER)
   AssertionError: 'task' != 'file.task'
======================================================================
14) FAIL: test_file_task_handler (tests.utils.test_log_handlers.TestFileTaskLogHandler)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/utils/test_log_handlers.py line 56 in test_file_task_handler
      self.assertIsNotNone(file_handler)
   AssertionError: unexpectedly None
======================================================================
15) ERROR: test_get_file_task_log (tests.www.test_views.TestLogView)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/www/test_views.py line 330 in setUp
      os.path.join(current_dir, 'test_logs'))
   KeyError: 'file.task'
```

Cheers, Fokko

**Comment by jgao54** [comment]
@Fokko  Thanks for the feedback! And my bad, just corrected the tests.

I've run this default logging config in my local environment, and log files look consistent to me as before the change. I'll run it on gcs as well just in case, but we don't use s3 here so it would be great if someone could test that one :)

**Comment by bolkedebruin** [comment]
@jgao54 Ok, this seems a good first step towards simplification. However is the setting for other locations (s3, gcs) also not quite simple to arrange, e.g. (pseudo code):

```
s3_config = {'task' : bla-bla}

if conf.get("core", "use_s3"):
   DEFAULT_LOGGING.CONFIG['handlers'].update(s3_config)

```

**Comment by jgao54** [comment]
@bolkedebruin updated!

**Comment by bolkedebruin** [comment]
lgtm, can you squash the commit please?

**Comment by jgao54** [comment]
done

**Comment by bolkedebruin** [comment]
@jgao54 can you rebase please? Sorry :)

**Comment by jgao54** [comment]
@bolkedebruin rebased,  built failed on a single instance with transient error

**Pull request closed without merging**
