### PR TITLE
[AIRFLOW-2259] Dataflow Hook Index out of range

### PR DESCRIPTION
**Pull request by Fokko**
Index out of range exception when receiving no lines:

```
[2018-03-27 20:08:49,337] {models.py:1657} ERROR - list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/airflow/models.py", line 1554, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/site-packages/airflow/contrib/operators/dataflow_operator.py", line 140, in execute
    self.jar, self.job_class)
  File "/usr/local/lib/python2.7/site-packages/airflow/contrib/hooks/gcp_dataflow_hook.py", line 176, in start_java_dataflow
    command_prefix, label_formatter)
  File "/usr/local/lib/python2.7/site-packages/airflow/contrib/hooks/gcp_dataflow_hook.py", line 158, in _start_dataflow
    _Dataflow(cmd).wait_for_done()
  File "/usr/local/lib/python2.7/site-packages/airflow/contrib/hooks/gcp_dataflow_hook.py", line 129, in wait_for_done
    line = self._line(fd)
  File "/usr/local/lib/python2.7/site-packages/airflow/contrib/hooks/gcp_dataflow_hook.py", line 110, in _line
    line = lines[-1][:-1]
```

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by criccomini** [comment]
LGTM

**Comment by Fokko** [comment]
WIP, still debugging some stuff. I have the suspicion something in the logic is wrong.

**Comment by Fokko** [comment]
Ok, I found some errors when using the [`dataflow.projects.jobs.list`](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/list) api call. This call, even when setting the location explicitly `europe-west1`, will always return the jobs on the location `us-central1`. I've did some tests with the API [`dataflow.projects.locations.jobs.list`](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/list) and this call will return a list from `europe-west1` that contains the job that we're looking for.

**Comment by Fokko** [comment]
@kaxil @fenglu-g Any thoughts? ^

**Comment by kaxil** [comment]
@Fokko  LGTM . 

I am not really sure on the reason why there is an issue with the `Dataflow Projects` api as opposed to `Dataflow Projects location`. Looks like a bug in the `Dataflow Projects` api itself which is defaulting it to `us-central`..

**Comment by Fokko** [comment]
@kaxil Exactly my thoughts, do you know where I should report this?

**Comment by kaxil** [comment]
@Fokko I reported this issue by emailing them (Dataflow team) and they are looking into it..

**Comment by fenglu-db** [comment]
Thank you @Fokko and @kaxil for the quick fix.

Talked to our internal dataflow contact, the [dataflow.projects.jobs.list ](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/list) was the pre-localization URL when dataflow was only available in us-central1. Given that dataflow now supports multiple locations, one could either use [dataflow.projects.locations.jobs.list](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.locations.jobs/list) with a specific location or projects.jobs.aggregated which lists jobs in all locations. To make things easier, we should probably use the latter.

**Comment by Fokko** [comment]
Thanks for the feedback @feng-tao, this is in line with my findings. The optional location parameter that you can supply to the `dataflow.projects.jobs.list` call makes it confusing. Lets keep it like this until the call has been fixed. Cheers

**Comment by jgao54** [comment]
Thank you for fixing this @Fokko! I was hitting the same issue today before catching up to the latest master with your commit :)

**Comment by ckchow** [comment]
does anyone have a temporary workaround for this that doesn't involve pulling master or 1.10 ? the version of airflow on google's composer cloud service (which just provides kubernetes-ized airflow clusters) exhibits this bug. :(

thanks for this fix regardless!

**Comment by kaxil** [comment]
@ckchow Create a plugin using the code from the master.

**Pull request closed without merging**
