### PR TITLE
Fix revoke Dag stale permission on airflow < 2.10

### LINKED ISSUE #42743: Revoking stale permissions breaks DAG import
### Apache Airflow Provider(s)

fab

### Versions of Apache Airflow Providers

apache-airflow-providers-fab==1.4.0

### Apache Airflow version

2.9.3

### Operating System

Oracle Linux Server 8.10

### Deployment

Virtualenv installation

### Deployment details

_No response_

### What happened

In DAG I use the "old" format of the access_control parameter. "DAG Import Errors" appears in the web interface when revoking stale permissions
```
Traceback(most recent call last):
  File "/opt/venv/lib64/python3.11/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1128, in sync_perm_for_dag
    self._sync_dag_view_permissions(dag_id, access_control.copy())
  File "/opt/venv/lib64/python3.11/site-packages/airflow/providers/fab/auth_manager/security_manager/override.py", line 1175, in _sync_dag_view_permissions
    target_perms_for_role = access_control.get(role.name, {}).get(resource_name, set())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'get'
```

### What you think should happen instead

According to the [provider's documentation](https://airflow.apache.org/docs/apache-airflow-providers-fab/stable/auth-manager/access-control.html#order-of-precedence-for-dag-level-permissions), it supports the old format, I think its support should be added

### How to reproduce

In DAG use the "old" format of the access_control parameter:
`with DAG(
        ...
        access_control={'BASIC_ROLE': {'can_read', 'can_edit', 'can_delete'}, 'BASIC_ROLE_VIEW': {'can_read'}},
        ...
)`

Wait until all permissions are added. Then remove `can_delete` permission, then when revoking obsolete permissions fab crashes and `DAG Import Errors` message appears in web interface

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by joaopamaral**
closes: #42743

This reported issue was happening on airflow < 2.10 using the old access_control format `dict[str, set]` and it was captured by the test `tests/providers/fab/auth_manager/test_security.py` when run the airflow 2.9.3 with fab 1.4.0:

```
FAILED tests/providers/fab/auth_manager/test_security.py::test_access_control_stale_perms_are_revoked - AttributeError: 'set' object has no attribute 'get'
```

After this fix the same test pass:

```
tests/providers/fab/auth_manager/test_security.py::test_access_control_stale_perms_are_revoked PASSED
```

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by joaopamaral** [comment]
Tested with airflow 2.9.3:

- Added a dag with the following access control:
```python
    access_control={
        "Viewer": {'can_read', 'can_edit', 'can_delete'}
    }
```
- The UI shows all the new permissions:
image

- Removed the `can_delete` permission:
```python
    access_control={
        "Viewer": {'can_read', 'can_edit'}
    }
```

- The permission is updated without any error:
image

**Review by vincbeck — APPROVED** [review]
Static checks are failing but otherwise, LGTM

**Comment by potiuk** [comment]
Yeah. And it needs to be rebased after providers have been moved to top level.

**Comment by potiuk** [comment]
Would also be nice if there is a unit test for it.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
