### PR TITLE
[AIRFLOW-1486] Unexpected S3 writing log error

### PR DESCRIPTION
**Pull request by skudriashev**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [AIRFLOW-1486](https://issues.apache.org/jira/browse/AIRFLOW-1486) issue and references them in the PR title.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

**Current:**
```
ERROR:root:Could not read logs from s3://airflow-log/my_dag/task1/2017-08-04T16:03:00/1.log
INFO:root:The key my_dag/task1/2017-08-04T16:03:00/1.log now contains 4648 bytes
```

**Expected:**
```
INFO:root:The key my_dag/task1/2017-08-04T16:03:00/1.log now contains 4648 bytes
```

### Tests
- [x] My PR adds the following unit tests:
    - tests.utils.test_logging.TestS3Log

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by skudriashev** [comment]
@bolkedebruin, @asfgit please have a look. Thanks ;)

**Comment by allisonwang** [comment]
@skudriashev Thanks for writing tests for S3 logs! Using `moto` is a better choice as we don't need to mock the behavior of S3. Could you point out how does this change fix the error?

**Comment by skudriashev** [comment]
@AllisonWang when S3hook writes log first time - it tries to read existing log first and since it doesn't exist - error is printed, but doesn't make sense. So I fixed that behavior.

**Comment by AllisonWang** [comment]
@skudriashev I don't see why when S3 hook writes log first time, it will print error. As here https://github.com/apache/incubator-airflow/blob/master/airflow/utils/logging.py#L207, the read has default `return_error` set to be False, and here https://github.com/apache/incubator-airflow/blob/master/airflow/utils/logging.py#L189 it returns empty string '' if return_error is false. I never see the issue of reading non existing logs from S3 prints this error in production. Could you elaborate more on why error is printed?

**Comment by allisonwang** [comment]
Get it. The log doesn't show up in UI but as a debug message. LGTM. Thanks for fixing the issue. I was trying to test S3 log in PR #2464 but `moto` doesn't work well with current structure. It requires passing mock S3 connection into S3Hook. This test can also be used to test the new S3 log handler.

**Comment by aoen** [comment]
LGTM, mocking is at least better than nothing so I'll merge this for now and we can follow up with better tests later if we desire. Thanks for your contribution!

**Pull request closed without merging**
