### PR TITLE
Optionally not follow logs in KPO pod_manager

### PR DESCRIPTION
**Pull request by dstandish**
When writing an async KPO, you want to be able to read logs up to the current moment and exit (i.e. and not follow the logs).  Additionally you want to be able to resume from a particular moment in time.  That's what this PR enables.

### CODE REVIEW

**Comment by jedcunningham** [comment]
Overall looks good, no test coverage though?

**Comment by dstandish** [comment]
> Overall looks good, no test coverage though?

added some coverage there.

**Review by jedcunningham — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Tests are failing 😞

**Comment by kaxil** [comment]
```
=================================== FAILURES ===================================
  ________________ TestPodManager.test_fetch_container_since_time ________________
  
  self = <tests.providers.cncf.kubernetes.utils.test_pod_manager.TestPodManager object at 0x7f2aeb2d9f10>
  container_running = <MagicMock name='container_is_running' id='139822292685072'>
  mock_now = <MagicMock name='now' id='139822237497808'>
  
      @mock.patch('pendulum.now')
      @mock.patch('airflow.providers.cncf.kubernetes.utils.pod_manager.container_is_running')
      def test_fetch_container_since_time(self, container_running, mock_now):
          """If given since_time, should be used."""
          mock_pod = MagicMock()
          mock_now.return_value = DateTime(2020, 1, 1, 0, 0, 5, tzinfo=Timezone('UTC'))
          container_running.return_value = False
          self.mock_kube_client.read_namespaced_pod_log.return_value = [b'2021-01-01 hi']
          since_time = DateTime(2020, 1, 1, tzinfo=Timezone('UTC'))
          self.pod_manager.fetch_container_logs(pod=mock_pod, container_name='base', since_time=since_time)
          call_kwargs = self.mock_kube_client.read_namespaced_pod_log.call_args_list[0].kwargs
  >       assert call_kwargs['since_seconds'] == 5
  E       TypeError: tuple indices must be integers or slices, not str
  
  tests/providers/cncf/kubernetes/utils/test_pod_manager.py:309: TypeError
  ----------------------------- Captured stderr call -----------------------------
  INFO  [airflow.providers.cncf.kubernetes.utils.pod_manager.PodManager] hi
  ------------------------------ Captured log call -------------------------------
  INFO     airflow.providers.cncf.kubernetes.utils.pod_manager.PodManager:pod_manager.py:216 hi
```

**Comment by dstandish** [comment]
thanks, will fix

**Comment by dstandish** [comment]
> call_kwargs = self.mock_kube_client.read_namespaced_pod_log.call_args_list[0].kwargs
>   >       assert call_kwargs['since_seconds'] == 5
>   E       TypeError: tuple indices must be integers or slices, not str

@kaxil 
yeah locally i use 3.8 so sometimes i get bitten by changes to mock call arg handling between 3.7 and 3.8 ... and that's what happened here.

**Pull request merged**
