### PR TITLE
[AIRFLOW-5590] Add run_id to trigger DAG run API response

### PR DESCRIPTION
**Pull request by aKumpan**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-5590/) issues and references it in the PR title. 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

I suggest to utilize 'run_id' instead of 'execution_date' as '/dag_runs' unique identifier for Rest APIs:
[Proposal](https://issues.apache.org/jira/browse/AIRFLOW-5593). 
As a pre-condition for this story - I am adding return of **'run_id'** as a separate parameter in a
POST '/dag_runs' json response.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Updated existing tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by XD-DENG — APPROVED** [review]
Not sure if I like your proposal to "utilize 'run_id' instead of 'execution_date' as '/dag_runs' unique identifier for Rest APIs", but this PR itself LGTM

**Comment by aKumpan** [comment]
Hi @XD-DENG, could you please provide more details why you do not like the [AIRFLOW-5593 proposal](https://issues.apache.org/jira/browse/AIRFLOW-5593)? So I will have better understanding if it is worth implementing.

The only concern I have - there will be API breaking changes in the implementation. But since API is experimental - better to do it now, then never.

**Comment by aKumpan** [comment]
@XD-DENG hi, could you please merge this?

**Comment by OmerJog** [comment]
@aKumpan can you fix the conflicts?

**Comment by aKumpan** [comment]
@OmerJog, @XD-DENG 
Conflicts resolved, please check again

**Comment by aKumpan** [comment]
@OmerJog, @XD-DENG could you please merge it?

**Comment by aKumpan** [comment]
UP
@OmerJog , @XD-DENG
Conflicts resolved, please check again

**Review by ashb — APPROVED** [review]

**Pull request merged**
