### PR TITLE
[AIRFLOW-4204] Update super() calls to PY3

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4204

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Replace super(_class, self) by super().

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by milton0825** [comment]
PTAL @Fokko @potiuk

**Comment by OmerJog** [comment]
@milton0825  can you add also BaseOperator & LoggingMixin to solve
https://issues.apache.org/jira/browse/AIRFLOW-3407

**Comment by milton0825** [comment]
@OmerJog let's keep this PR single purpose, which is deprecating the PY2 `super` usage.

Created: https://github.com/apache/airflow/pull/5148

**Review by potiuk — CHANGES_REQUESTED** [review]
Whoa. Good job. I hope you used some kind of automation to get this :). I looked it up with regexps and besides a few setupClass() where we cannot really get rid of class i found only one place:

```
diff --git airflow/contrib/operators/gcs_to_gcs.py airflow/contrib/operators/gcs_to_gcs.py
index b694b802..e43a6f4d 100644
--- airflow/contrib/operators/gcs_to_gcs.py
+++ airflow/contrib/operators/gcs_to_gcs.py
@@ -125,8 +125,7 @@ class GoogleCloudStorageToGoogleCloudStorageOperator(BaseOperator):
                  last_modified_time=None,
                  *args,
                  **kwargs):
-        super(GoogleCloudStorageToGoogleCloudStorageOperator,
-              self).__init__(*args, **kwargs)
+        super().__init__(*args, **kwargs)
         self.source_bucket = source_bucket
         self.source_object = source_object
         self.destination_bucket = destination_bucket
```

**Comment by milton0825** [comment]
Yeah I used:
```
find -f tests airflow -type f -name "*.py" -print0 | xargs -0 sed -i .pyc 's/super(.*, self)/super()/g'
autopep8 -r --select E127,E131 --diff airflow tests
```
and I missed the case that `self` is split to another line..

**Comment by milton0825** [comment]
@potiuk added the fix.

**Comment by potiuk** [comment]
I think there is somewhere a real bug - I restarted it and it failed in similar way . Maybe you can take a closer look @milton0825 ?

**Comment by BasPH** [comment]
I don't think changes should be made to anything in the `_vendor` directory. Shouldn't code in there just be a copy-paste of the library as much as possible?

**Comment by milton0825** [comment]
@BasPH I think it is part of the codebase and diverged with the origin since the day we made the copy-paste so we should fix it to drop PY2 support.

**Comment by milton0825** [comment]
And I have seen people making changes to it.

**Comment by potiuk** [comment]
Yeah. @BasPH  - this code was vendorised and I think there were already changes implemented that make it difficult to upgrade to a newer version (which I imagine might be reason why we want to minimise the changes). So I see no big problem in updating the code again - but maybe we should split those changes to separate commits (separate for slugify and python-v3d ) so that in case we upgrade in the future, we can re-apply vendoring by mostly cherry-picking few commits on top of new library.

**Comment by milton0825** [comment]
@potiuk good advice. I have broken the PR into two commits. One fixed nvd3 and one fixed the rest.

**Comment by milton0825** [comment]
And btw there is no usage of `super` in slugify.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
@kaxil @fokko - is it ok to rebase&marge two commits with same JIRA ID? I think it makes sense to separate in this case - but I am not sure if it will work with the automated release scripts you probably use ?

**Comment by kaxil** [comment]
We should have a separate PR for modifying nvd3 stuff - ideally with a new JIRA issue.

It becomes easy to revert if need be.

Or create sub-task under a parent JIRA

**Comment by milton0825** [comment]
Removed the second commit and created a separate PR: https://github.com/apache/airflow/pull/5168

**Pull request merged**
