### PR TITLE
[AIRFLOW-1929] Pass ExecutionDate In TriggerDagRunOperator

### PR DESCRIPTION
**Pull request by ghost**
This change allows passing an execution date
to the trigger dag run operator. This brings parity 
to the operator with the trigger_dag cli utility. 

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-1929] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1929

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
The TriggerDagRunOperator was not configurable to pass the execution_date of the dag being triggered. This change adds another field to the TriggerDagRunOperator and uses the experimental API method trigger_dag used in the cli utility. This can help in avoiding code deduplication. 

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Have modified the existing test cases to encompass the new changes.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by sekikn** [comment]
@sreenathkamath This seems to be the same issue as [AIRFLOW-1674](https://issues.apache.org/jira/browse/AIRFLOW-1674), and I've already submitted a PR as #2678. But I think your solution is better because:

- it leverages common function and improves maintenanceability.
- it's bw-compatible while mine is not.

So I hope your PR will be merged. Would you also fix example_trigger_controller_dag.py to work?

@bolkedebruin do you have any advice?

**Comment by ghost** [comment]
@sekikn I have made the suggested changes.

**Comment by ghost** [comment]
@Fokko  can you please take a look

**Comment by ghost** [comment]
Can someone please take a look at this PR. At least suggest the changes that are required to get it merged?

**Pull request closed without merging**
