### PR TITLE
Disable GitSync + Persistence combo in the Helm Chart

### LINKED ISSUE #27080: Git Sync containers are missing when Dag Processor is enabled
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.3.4

### Kubernetes Version

1.22.6

### Helm Chart configuration

```
...
# Airflow Dag Processor Config
dagProcessor:
  enabled: true
  # Number of airflow dag processors in the deployment
  replicas: 1
...
# Git sync
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim: airflow-dags
    ## optional subpath for dag volume mount
    subPath: ~
  gitSync:
    enabled: true
...
```

### Docker Image customisations

_No response_

### What happened

When Dag Processor is enabled, the Git Sync containers (git-sync-init and git-sync) are missing in airflow-scheduler pod.
They are neither part of the airflow-dag-processor pod.

### What you think should happen instead

Git Sync containers (git-sync-init and git-sync) should be part of one of airflow-scheduler or airflow-dag-processor pods.
Below attaching parts of the helm chart log showing deployment of both airflow-scheduler and airflow-dag-processor pods.
```
################################
## Airflow Dag Processor Deployment
#################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-dag-processor
  labels:
    tier: airflow
    component: dag-processor
    release: airflow
    chart: "airflow-1.7.0"
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: dag-processor
      release: airflow
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        tier: airflow
        component: dag-processor
        release: airflow
      annotations:
        checksum/metadata-secret: 765446a9def21895960ebc0df295399c35d3467cdd84be6ef8bc65c18ca0f7e5
        checksum/pgbouncer-config-secret: da52bd1edfe820f0ddfacdebb20a4cc6407d296ee45bcb500a6407e2261a5ba2
        checksum/airflow-config: a78767ecb4f7423a34e69c0add978a0ff15452ff0a54a6cb08fc93f06aaf5e7e
        checksum/extra-configmaps: 2e44e493035e2f6a255d08f8104087ff10d30aef6f63176f1b18f75f73295598
        checksum/extra-secrets: bb91ef06ddc31c0c5a29973832163d8b0b597812a793ef911d33b622bc9d1655
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      nodeSelector:
        nodepool-type: airflow
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: dag-processor
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
        []
      topologySpreadConstraints:
        []
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
      serviceAccountName: airflow-dag-processor
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      imagePullSecrets:
        - name: ds-registry
      initContainers:
        - name: wait-for-airflow-migrations
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          image: seebodsregistry.azurecr.io/airflow:2.3.4-extended
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
          args:

            - airflow
            - db
            - check-migrations
            - --migration-wait-timeout=60
          envFrom:

            []
          env:

            # Dynamically created environment variables
            # Dynamically created secret envs

            # Extra env
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: '/opt/airflow/all-dags'
            - name: AIRFLOW__CORE__PLUGINS_FOLDER
              value: '/opt/airflow/plugins/repo/deployment/plugins'
            - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
              value: '600'
            - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
              value: '3600'
            - name: AIRFLOW__CORE__PARALLELISM
              value: '128'
            - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
              value: 'True'
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
              value: '15'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP
              value: '100'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE
              value: '100'
            - name: AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD
              value: '1200'
            - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
              value: 'Staging'
            - name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
              value: 'True'


            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-key
                  key: webserver-secret-key
      containers:
        - name: dag-processor
          image: seebodsregistry.azurecr.io/airflow:2.3.4-extended
          imagePullPolicy: IfNotPresent
          args:
            - bash
            - -c
            - exec airflow dag-processor
          resources:

            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:

            - name: logs
              mountPath: "/opt/airflow/logs"
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/config/airflow_local_settings.py"
              subPath: airflow_local_settings.py
              readOnly: true
            - name: dags
              mountPath: /opt/airflow/dags

              readOnly: True
          envFrom:

            []
          env:

            # Dynamically created environment variables
            # Dynamically created secret envs

            # Extra env
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: '/opt/airflow/all-dags'
            - name: AIRFLOW__CORE__PLUGINS_FOLDER
              value: '/opt/airflow/plugins/repo/deployment/plugins'
            - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
              value: '600'
            - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
              value: '3600'
            - name: AIRFLOW__CORE__PARALLELISM
              value: '128'
            - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
              value: 'True'
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
              value: '15'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP
              value: '100'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE
              value: '100'
            - name: AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD
              value: '1200'
            - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
              value: 'Staging'
            - name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
              value: 'True'


            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-key
                  key: webserver-secret-key
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 20
            failureThreshold: 5
            periodSeconds: 120
            exec:
              command:

                  - sh
                  - -c
                  - |
                    CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
                    airflow jobs check --hostname $(hostname)
      volumes:
        - name: config
          configMap:
            name: airflow-airflow-config
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs


################################
## Airflow Scheduler Deployment/StatefulSet
#################################

# Are we using a local executor?
# Is persistence enabled on the _workers_?
# This is important because in $local mode, the scheduler assumes the role of the worker
# If we're using a StatefulSet
# We can skip DAGs mounts on scheduler if dagProcessor is enabled, except with $local mode
# If we're using elasticsearch logging

kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-scheduler
  labels:
    tier: airflow
    component: scheduler
    release: airflow
    chart: "airflow-1.7.0"
    heritage: Helm
    executor: KubernetesExecutor
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: scheduler
      release: airflow
  template:
    metadata:
      labels:
        tier: airflow
        component: scheduler
        release: airflow
      annotations:
        checksum/metadata-secret: 765446a9def21895960ebc0df295399c35d3467cdd84be6ef8bc65c18ca0f7e5
        checksum/result-backend-secret: 74e3e99feee51248d44224665d60fab543dd6b25ba95f04e6fcb0e5758342056
        checksum/pgbouncer-config-secret: da52bd1edfe820f0ddfacdebb20a4cc6407d296ee45bcb500a6407e2261a5ba2
        checksum/airflow-config: a78767ecb4f7423a34e69c0add978a0ff15452ff0a54a6cb08fc93f06aaf5e7e
        checksum/extra-configmaps: 2e44e493035e2f6a255d08f8104087ff10d30aef6f63176f1b18f75f73295598
        checksum/extra-secrets: bb91ef06ddc31c0c5a29973832163d8b0b597812a793ef911d33b622bc9d1655
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      nodeSelector:
        nodepool-type: airflow
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  component: scheduler
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
        []
      topologySpreadConstraints:
        []
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      serviceAccountName: airflow-scheduler
      securityContext:
        runAsUser: 50000
        fsGroup: 0
      imagePullSecrets:
        - name: ds-registry
      initContainers:
        - name: wait-for-airflow-migrations
          resources:
            limits:
              cpu: 8000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 1Gi
          image: seebodsregistry.azurecr.io/airflow:2.3.4-extended
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
          args:
            - airflow
            - db
            - check-migrations
            - --migration-wait-timeout=60
          envFrom:
            []
          env:
            # Dynamically created environment variables
            # Dynamically created secret envs

            # Extra env
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: '/opt/airflow/all-dags'
            - name: AIRFLOW__CORE__PLUGINS_FOLDER
              value: '/opt/airflow/plugins/repo/deployment/plugins'
            - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
              value: '600'
            - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
              value: '3600'
            - name: AIRFLOW__CORE__PARALLELISM
              value: '128'
            - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
              value: 'True'
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
              value: '15'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP
              value: '100'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE
              value: '100'
            - name: AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD
              value: '1200'
            - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
              value: 'Staging'
            - name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
              value: 'True'

            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-key
                  key: webserver-secret-key
      containers:
        # Always run the main scheduler container.
        - name: scheduler
          image: seebodsregistry.azurecr.io/airflow:2.3.4-extended
          imagePullPolicy: IfNotPresent
          args:
            - bash
            - -c
            - exec airflow scheduler
          envFrom:
            []
          env:
            # Dynamically created environment variables
            # Dynamically created secret envs

            # Extra env
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: '/opt/airflow/all-dags'
            - name: AIRFLOW__CORE__PLUGINS_FOLDER
              value: '/opt/airflow/plugins/repo/deployment/plugins'
            - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
              value: '600'
            - name: AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT
              value: '3600'
            - name: AIRFLOW__CORE__PARALLELISM
              value: '128'
            - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
              value: 'True'
            - name: AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL
              value: '120'
            - name: AIRFLOW__SCHEDULER__PARSING_PROCESSES
              value: '15'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_TO_CREATE_PER_LOOP
              value: '100'
            - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE
              value: '100'
            - name: AIRFLOW__SCHEDULER__SCHEDULER_ZOMBIE_TASK_THRESHOLD
              value: '1200'
            - name: AIRFLOW__WEBSERVER__INSTANCE_NAME
              value: 'Staging'
            - name: AIRFLOW__WEBSERVER__RELOAD_ON_PLUGIN_CHANGE
              value: 'True'

            # Hard Coded Airflow Envs
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-fernet-key
                  key: fernet-key
            # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW_CONN_AIRFLOW_DB
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: connection
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-webserver-key
                  key: webserver-secret-key
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 20
            failureThreshold: 5
            periodSeconds: 60
            exec:
              command:

                  - sh
                  - -c
                  - |
                    CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
                    airflow jobs check --job-type SchedulerJob --hostname $(hostname)
          resources:
            limits:
              cpu: 8000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /opt/airflow/pod_templates/pod_template_file.yaml
              subPath: pod_template_file.yaml
              readOnly: true
            - name: logs
              mountPath: "/opt/airflow/logs"
            - name: config
              mountPath: "/opt/airflow/airflow.cfg"
              subPath: airflow.cfg
              readOnly: true
            - name: config
              mountPath: "/opt/airflow/config/airflow_local_settings.py"
              subPath: airflow_local_settings.py
              readOnly: true
        - name: scheduler-log-groomer
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          image: seebodsregistry.azurecr.io/airflow:2.3.4-extended
          imagePullPolicy: IfNotPresent
          args:
            - bash
            - /clean-logs

          env:
            - name: AIRFLOW__LOG_RETENTION_DAYS
              value: "15"
          volumeMounts:
            - name: logs
              mountPath: "/opt/airflow/logs"
      volumes:
        - name: config
          configMap:
            name: airflow-airflow-config
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs
```

### How to reproduce

Both Git Sync and Dag Processor should be enabled.

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #27476: Volume is missing for sshKeySecret when dag persistence is enabled.
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.3.4

### Kubernetes Version

1.22.6

### Helm Chart configuration

```
# Git sync
dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName:
    accessMode: ReadWriteOnce
    existingClaim: airflow-dags
    subPath: ~
  gitSync:
    enabled: true
    repo: "ssh://git@..."
    branch: "main"
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: ""
    sshKeySecret: airflow-ssh-secret
```

### Docker Image customisations

_No response_

### What happened

This commit: https://github.com/apache/airflow/commit/3fc895b9dfe8e7b77538bd80754fb17ccf92db49 causes the following error because volumeMount is created but the volume is missing:
```upgrade.go:369: [debug] warning: Upgrade "airflow" failed: cannot patch "airflow-scheduler" with kind Deployment: Deployment.apps "airflow-scheduler" is invalid: spec.template.spec.containers[2].volumeMounts[0].name: Not found: "dags"```

### What you think should happen instead

I don't see any relation between dag persistency and git-sync configuration. The fact is that the same configuration works when `credentialsSecret` is defined but stopped working with `sshKeySecret`.

### How to reproduce

Follow commit https://github.com/apache/airflow/commit/3fc895b9dfe8e7b77538bd80754fb17ccf92db49

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #27545: missing volumes for git-sync-ssh-key
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.2

### Kubernetes Version

1.20

### Helm Chart configuration

dags:
  gitSync:
    enabled: true
 persistence:
    enabled: true

### Docker Image customisations

all is office helm-chart images

### What happened

when set gitSync enabled: true and persistence enabled: true for dags, volumes has no name with git-sync-ssh-key, it cause install schedule failed.

### What you think should happen instead

in office document for helm-chart, set both true is enabled, so i think set both true should work good, but it failed.
helm upgrade --install airflow apache-airflow/airflow \
  --set dags.persistence.enabled=true \
  --set dags.gitSync.enabled=true

### How to reproduce

just follow the above question

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
Git Sync and Persistence for DAGs makes very little sense together and is largely misleading our users on what it does.

Git Sync provides atomicity of DAG folder synchronisation via checking out a complete copy of the DAGs folder and swapping symbolic link pointing to it. It does not play well with networked persistence.

It makes it super-easy by users unaware how git-sync and persistence work under-the-hood to walk into several traps:

* git sync on persistent remote volumes such as EFS generate a LOT of extra traffic due to the way how git sync works (it creates second working folder for dags and replaces symbolic link to folders which effectively forces full sync of whole DAG folder for all involved instances with every commit
* due to that sync that gets distributed over multiple clients of persistent volumes it looses the atomicity property of git sync and the above case where there are burst of synchronisation betwween multiple nodes, it is very likely to trigger inconsistent DAG parsing
* the problem amplifies when the network volumes are distributed among multiple nodes and there are some networking limits (for example not provisioned IOPS in EFS). The amount of traffic generated at sync might cause even more inconsistencies - only solvable by paying extra IOPS (where it would not be needed normally)
* users might be tricked into trying to use gitSync and also update DAGs using persistence (so basically combine the development friendly dag distribution over persistent volumes and production-ready git-sync - without being aware that git-sync will override the manually synced DAGS when swapping the symbolic links

On top of it, the current status is that it does not work. There are several issues where volumes are missing when the combo is used in certain situations and better than fixing those is to disable it.

Closes: #27545
Closes: #27476
Closes: #27080

Related: #27124

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by dstandish — APPROVED** [review]
Seems fine, though being technically breaking probably requires major release? Unless you want to think of it as bugfix.....  
@jedcunningham

**Comment by potiuk** [comment]
We had a lot of discussions about it with @jedcunningham in related issues and some time ago I wrote the article describing in detail why git-sync and networked persistence do not play along together (and do not serve any useful use case).

https://medium.com/apache-airflow/shared-volumes-in-airflow-the-good-the-bad-and-the-ugly-22e9f681afca

I think we've accumulated enough of the issues from our users that confirm that they REALLY did not want to use persistence and git-sync, and we had a lot of problems which we could attribute to lack of atomicity that is amplified by git-sync + network persistence.

The last straw for me was this discussion  https://apache-airflow.slack.com/archives/C027H098M1C/p1673333515991549. where the users wanted to use dags.persistence and dags.gitSync to combine development and production workflows in one (which would not work but the user was unaware of that as they did not know that how git-sync works under the hood it would overwrote the manually updated/copied dags).

All-in-all - I think allowing this combo is actively harmful  and we should help our users to make the right decision  (and ourselves by not having similar discussions/getting issues created) by disabling the combo.

**Comment by potiuk** [comment]
I personally think it is a bugfix (because it does not work anyway :) )

**Comment by jedcunningham** [comment]
I think I'd rather warn instead of block (but I'm also a bit worn down on thinking about the combo in our chart, so I certainly won't stand in the way here).

**Comment by potiuk** [comment]
I think this is one of those cases that we really balloon a matrix of tests for very little reason. 

Seems that we alrady have a number of tests - now failing) where both are set - yet we still do not have the combo right. 

After seeing the number of tests failing, though, I have a second thought - because apparently this combo was actually quite thoroughly tested before. 

I wonder (for my own understanding here) - why the (currently failing) tests were added. What was the reasoning behind having a number of `"gitSync": {"enabled": True}, "persistence": {"enabled": True}` in the parameterized tests?
Was there any other thought behind it that we knew or expected this combo to be working or was it just - ok let's test all the combinations without much of a thinking whether this combo is actually useful?

I think answer to that should determine whether it makes sense to remove it completely or maybe just warn the users and try to fix the cases we know for now.

**Comment by potiuk** [comment]
And yes I am just afraid that we **might** break things for some users - so far I understood that https://github.com/apache/airflow/issues/27545 effectively means that it was really difficult to get a prod-ready setting, but After looking closely it's been "freshly" broken by https://github.com/apache/airflow/pull/22913 

Also https://github.com/apache/airflow/pull/22913 is triggered by recently added standalone DAG File processor. So my claims that this is not "breaking" is not as bold as it was.

Let me think for a while about it.

**Comment by jedcunningham** [comment]
Yes, it did work at one point and the tests were intentionally added (but even then this combo really only made sense with a single scheduler).

**Comment by potiuk** [comment]
Still thinking on it :).

**Comment by hussein-awala** [comment]
> And yes I am just afraid that we might break things for some users

@potiuk I think the user who uses the combo and wants to upgrade to the new chart version could still use it by enabling git-sync, disabling dags persistence and adding the dags volume [manually](https://github.com/gmsantos/airflow/blob/main/chart/values.yaml#L246-L250), what do you think?

**Comment by JMLizano** [comment]
Hi, I was about to create a bug report related to this but then I saw this PR, so probably better to include it here.

The issue appears when activating both dags persistence and git-sync. When you have a DAG inside a package, that is importing some other module from the package, like:

```python
from mypackage.lib.mylib import lib_method
```

the import will fail at DAG execution time if both git-sync and dag persistence are enabled. The DAG is still displayed in the Web UI, and airflow list it as correctly imported (i.e. it is displayed in the output of `airflow dags list`).
When you try to execute the DAG, it will fail right away, without any log output since it fails before even starting the execution, but if you check the worker logs you will see a message like this:

```bash
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/repo/dags/mypackage/mydags/mydag.py", line 6, in <module>
    from mypackage.lib.mylib import lib_method
ModuleNotFoundError: No module named 'mypackage'
```

If you disable dags persistence then everything works as expected.

I have created a repository that reproduces the issue: https://github.com/JMLizano/explore-airflow-chart-issue

**Comment by potiuk** [comment]
Closing in favour of https://github.com/apache/airflow/pull/32181

**Pull request closed without merging**
