### PR TITLE
Enhance EmrStepSensor to retrieve all steps if no stepId was provided

### PR DESCRIPTION
**Pull request by pedresnyman**
Currently the EmrStepSensor only looks at one step at a time. Enhancing the EmrStepSensor to retrieve all steps on a specified cluster if no stepId was provided.

### CODE REVIEW

**Comment by baolsen** [comment]
Awesome stuff @pedresnyman . Fingers crossed for the build.

**Comment by mik-laj** [comment]
Is it related? https://github.com/apache/airflow/issues/11877#issuecomment-717062405

**Comment by pedresnyman** [comment]
@mik-laj yes it is

**Comment by eladkal** [comment]
@pedresnyman did you mean to close this PR?

**Pull request closed without merging**
