### PR TITLE
Add missing values entries to Parameters in chart/README.md

### PR DESCRIPTION
**Pull request by kaxil**
This PR Adds missing values entries to Parameters in chart/README.md

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
@dimberman this was missing in https://github.com/apache/airflow/pull/11426

**Comment by dimberman** [comment]
@kaxil I figured we don't add it because a) there are no values for webserver and b) you can't add complex objects via CLI

**Comment by kaxil** [comment]
> @kaxil I figured we don't add it because a) there are no values for webserver and b) you can't add complex objects via CLI

In future we are going to automate generating this doc from `values.schema.json`. It is very useful to users to directly check what is configurable without having to look at values.yaml

**Comment by mik-laj** [comment]
> In future we are going to automate generating this doc from values.schema.json. It is very useful to users to directly check what is configurable without having to look at values.yaml

Related: https://github.com/apache/airflow/issues/11077

**Review by potiuk — APPROVED** [review]

**Pull request merged**
