### PR TITLE
[AIRFLOW-393] Add progress callback for FTP download

### PR DESCRIPTION
**Pull request by jlowin**
Link to issue: https://issues.apache.org/jira/browse/AIRFLOW-393

### CODE REVIEW

**Comment by akosel** [comment]
Out of curiousity, was this closed for a particular reason?

**Comment by jlowin** [comment]
@akosel to be honest I don't recall why.

**Comment by akosel** [comment]
Ah ok! Can we resurrect it? I'd be happy to take the lead if you don't have time.

**Comment by jlowin** [comment]
Please feel free to go ahead! I'm afraid I don't have time right now but hopefully the old code is a viable starting point.

**Comment by akosel** [comment]
Excellent! Thank you!

**Pull request closed without merging**
