### PR TITLE
Custom deprecation proxy implementing __format__

### LINKED ISSUE #19716: [Airflow 2.2.2] execution_date Proxy object - str formatting error
### Apache Airflow version

2.2.2 (latest released)

### Operating System

Ubuntu 18.04.6

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### What happened

The deprecated variable `execution_date` raises an error when used in an f string template with date string formatting.

```python
In [1]: execution_date
DeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'logical_date' or 'data_interval_start' instead.
Out[1]: <Proxy at 0x7fb6f9af81c0 wrapping DateTime(2021, 11, 18, 0, 0, 0, tzinfo=Timezone('UTC')) at 0x7fb6f9aeff90 with factory <function TaskInstance.get_template_context.<locals>.deprecated_proxy.<locals>.deprecated_func at 0x7fb6f98699d0>>

In [2]: f"{execution_date:%Y-%m-%d}"
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
----> 1 f"{execution_date:%Y-%m-%d}"

TypeError: unsupported format string passed to Proxy.__format__
```

### What you expected to happen

Executing `f"{execution_date:%Y-%m-%d}"` should return a string and not raise an error. 

### How to reproduce

```python
from datetime import datetime
from airflow import DAG
from airflow.operators.python import PythonOperator


def test_str_fmt(execution_date: datetime):
    return f"{execution_date:%Y-%m-%d}"


dag = DAG(
    dag_id="Test_Date_String",
    schedule_interval="@daily",
    catchup=False,
    default_args={
        "depends_on_past": False,
        "start_date": datetime(2021, 11, 1),
        "email": None,
        "email_on_failure": False,
        "email_on_retry": False,
        "retries": 0,
    },
)

with dag:
    test_task = PythonOperator(
        task_id="test_task",
        python_callable=test_str_fmt,
    )
```

### Anything else

```python
from datetime import datetime
...
datetime.fromisoformat(next_ds)
TypeError: fromisoformat: argument must be str
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by uranusjr**
Fix #19716.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
Hmm, we need to jump through some hoops serialising this into virtualenv.

**Comment by potiuk** [comment]
Idea @uranusjr  - seems that all those "deprecated" objects are `datetime' objects. Why don't we simply create an "Airflow datateime" which extends directly from datetime? we could override the class instance type to pass all the checks for `isinstance` and `issubclass` (obviously). This is less "generic" than using lazy_proxy, but it should behave much more "backwards-compatible" and serialization problems would be gone.

We do not really use the "lazyness" of the proxy, this is perfectly fine to instantiate those objects at creation time (they will probably take less memory than the proxy anyway).

**Comment by potiuk** [comment]
The only problem is to generate the "warning" at first use, but I bet this could be easily implemented by a custom `get_attr()`  method that could keep a boolean flag whether warning was emited or not from this particular object. Sounds easy.

**Comment by uranusjr** [comment]
That wouldn’t help the serialisation issue though because those custom datetimes are still not unpicklable without Airflow being available in the virtual environment.

**Comment by potiuk** [comment]
> That wouldn’t help the serialisation issue though because those custom datetimes are still not unpicklable without Airflow being available in the virtual environment.

If we serialize it as a plain `datetime` it would actually.

**Comment by uranusjr** [comment]
> If we serialize it as a plain `datetime` it would actually.

How? We can’t just serialise that plain datetime object into the virtual environment, because that’s make it impossible to show the lazy deprecation warning to the user. We must serialise something custom. But doing that would cause deserialisation issues because code inside the virtual environment does not have access to that custom object’s definition.

**Comment by potiuk** [comment]
> How? We can’t just serialise that plain datetime object into the virtual environment, because that’s make it impossible to show the lazy deprecation warning to the user. We must serialise something custom. But doing that would cause deserialisation issues because code inside the virtual environment does not have access to that custom object’s definition.

We don't have to. The warning will be printed while serializing - we do not have to addtionally log the warning while the task executes.

**Comment by uranusjr** [comment]
Serialisation does not know exactly what variables will be used by the user inside the environment. We can’t just log everything because it’d emit a ton of superfulous warnings for all those deprecated variables even if the user never uses them.

**Comment by potiuk** [comment]
> Serialisation does not know exactly what variables will be used by the user inside the environment. We can’t just log everything because it’d emit a ton of superfulous warnings for all those deprecated variables even if the user never uses them.

Oh yeah, indeed. Good point. 

I think the reasonable approach will be then to employ custom serialization and  add a small package (locally created dynamically so that we do not have to add it to PyPI) that will automatically be added while venv is created. I think will have to do the same for the @task.docker decorator as well.

**Comment by ashb** [comment]
Instead of a custom proxy object for some values could we not make a custom context dict class that returns lazily evaluates and returns actual objects instead?

Cos there was also another problem where `previois_executiob_date is None` was _never_ true (because the lazy object proxy can't catch this case) - if there is this there could be more bugs.

**Comment by potiuk** [comment]
> Instead of a custom proxy object for some values could we not make a custom context dict class that returns lazily evaluates and returns actual objects instead?

Yeah. Agree - if we could make it works across seralization in virtualenv/docker cases that woudl be best apprach.

**Comment by uranusjr** [comment]
But that custom context object will still be iterated through too eagerly when being serialised for the virtual environment and wouldn’t solve the actual problem at hand. But maybe a combination of the two approaches would work best: a custom context object that emits deprecation warnings on access but returns plain built-in objects, and a tiny module injected into the virtual environment to support deserialisation of that custom context object.

**Pull request closed without merging**
