### PR TITLE
Generic RDS Operators

### PR DESCRIPTION
**Pull request by Anton-Shutik**
_JUST AN IDEA_

It creates new Generic RDS Base Operator and then we can easily make various `RdsOperators` based on that. I think that approach can be applied to another AWS resources as well.

That PR is not ready for release and might be improved, but works fine in my project.

I'd love to discuss the idea to make sure it's worth invest time on `airflow` framework.

### CODE REVIEW

**Comment by dstandish** [comment]
It's an interesting idea

I wonder if it might be better to just make one operator that can do many things, and control the behavior with an enum.

E.g. `GenericRdsOperator`

and 

```
class RdsAction(str, Enum):
    describe_instances = 'describe_instances'
    ...
```

then

```
op =  GenericRdsOperator(action=RdsAction.describe_instances)
```

all of your subclasses don't do anything except change one parameter, so it seems that subclass may be overkill here

**Comment by Anton-Shutik** [comment]
Yeah, your idea great as well.
Then we can go with more generic `Boto3Operator`:
```python

class Boto3Operator(BaseOperator):

    def __init__(self, *args, aws_conn_id: str = "aws_conn_id", boto3_client: str = None, boto3_callable: str = None, boto3_params: dict | None = None, result_handler:callable | None = None, **kwargs):
        super().__init__(*args, **kwargs)
        self.hook.conn = AwsBaseHook(aws_conn_id=aws_conn_id, client_type=boto3_client)

        assert hasattr(self.hook.conn, boto3_callable), f"{boto3_callable} does not exit on boto3.Client('{boto3_client}')"
        self.boto3_handler = getattr(self.hook.conn, boto3_callable)
        self.boto3_params = boto3_params
        self.result_handler = result_handler or (lambda x: x)

    def execute(self, context: Context) -> Any:
        result = self.result_handler(
            self.boto3_handler(self.boto3_params)
        )
        if not isinstance(result, str):
            return json.dumps(result, default=str)
        return result
```

Then we use it like:

```python
with models.DAG(
    "example_rds",
    start_date=datetime(2021, 1, 1),
    catchup=False,
) as dag:

    find_latest_production_snapshot = Boto3Operator(
        task_id='find_latest_production_snapshot',
        aws_conn_id=AWS_CONNECTION_ID,
        boto3_client="rds",
        boto3_callable="describe_db_snapshots", 
        boto3_params={
            "DBInstanceIdentifier": "production-database-name",
        },
        # filters out latest snapshot, returns its ARN
        result_handler=lambda results: sorted(results["DBSnapshots"], key=lambda x: x["SnapshotCreateTime"], reverse=True)[0]["DBSnapshotArn"]
    )

    restoure_from_snapshot = Boto3Operator(
        task_id='restoure_from_snapshot',
        aws_conn_id=AWS_CONNECTION_ID,
        boto3_client="rds", 
        boto3_callable="restore_db_instance_from_db_snapshot", 
        boto3_params={
            "DBInstanceIdentifier": "rds_instance_identifier",
            "DBSnapshotIdentifier": find_latest_production_snapshot.output,
            ...
        },
        result_handler=lambda x: None
    )
```

Or if users like their own (in case if used frequently ) they do:

```python
class RdsRestoreDbInstanceFromSnapshotOperator(Boto3Operator):
    """
    Restores snapshot into new RDS instance
    """

    def __init__(self, *args, rds_client_kwargs:dict | None = None, **kwargs):
        super().__init__(*args, boto3_client="rds", boto3_callable="restore_db_instance_from_db_snapshot", boto3_params=rds_client_kwargs, **kwargs)
```

**Comment by o-nikolas** [comment]
Very interesting indeed!

Personally, I think the main benefits that operators provide are:
1. Simplification, e.g.:
    - Defaulting SDK params where possible so that API exposed to the caller is simpler
    - Specific error and response handling to clarify results received from the AWS API, which are often obtuse
2. Unification of one or more SDK calls into a single common recipe encapsulated in an Operator.
3. Abstraction, the user doesn't necessarily need to be familiar with the Boto3 SDK (or even what an SDK is) to get some dags up and running (think of non-sde users here).

If we make the abstraction layer as thin and generic as proposed here I think you lose many of these benefits of Operators. If users have to go look at the SDK/API to find the method names and the parameters and also provide their own result handler, etc I think it's actually easier and more straight forward for them to just use TaskFlow or Custom Operators and the Boto3 API directly (retrieved from the base hook if they'd like to have that generate the connection for them, which I'd recommend).

**Comment by shubham22** [comment]
Agree with @o-nikolas here. Providing a generic Boto3 operator provides users with breadcrumbs and leaves all the work regarding figuring out Boto3 API details on the users themselves. TaskFlow and custom operators already do something similar and adding a generic operator would just make it confusing. 

In addition what Niko mentioned as main benefits of operators, I think **observability** is one of the main advantages. With operators, we can provide logs of different services/operations within the Airflow UI, so users don't have to go on a hunt for logs in AWS console/CloudWatch. A generic operator would not be able to provide the same convenience.

**Comment by Anton-Shutik** [comment]
Thanks for comments!
Yep, that was just an _idea_. 
I think _generic_ Boto3Opeator can be useful for those who knows boto3 well and can just _use_ the operator instead of writing their own. 
Also, it can be used as base operator for another, more high level, operator.
I've made another [draft PR](https://github.com/apache/airflow/pull/27656), just to show you how it can work and to share it with others.

Closing this one

**Pull request closed without merging**
