### PR TITLE
Send context using in venv operator

### PR DESCRIPTION
**Pull request by phi-friday**
origin: #41039 
related: #41362 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
something is wrong as it shows 0 files changed

**Comment by phi-friday** [comment]
> ~something is wrong as it shows 0 files changed~ ah you need to wait till the revert PR is merged. otherwise the diff is nothing

I'm not sure what to do as I've never seen this before.
If #41362  is merged, should I just rebase it?

**Comment by phi-friday** [comment]
I don't know if this is allowed.
Modifying the model as follows did not cause the problem,
even if it was `pydantic<2` or `none` (I checked in local).

#### in `airflow.utils.pydantic`

```python
if is_pydantic_2_installed():
    from pydantic import BaseModel, ConfigDict, PlainSerializer, PlainValidator, ValidationInfo
else:

    class BaseModel:  # type: ignore[no-redef]  # noqa: D101
        def __init__(self, *args, **kwargs):
            self.__dict__.update(kwargs)

        @classmethod
        def model_validate(cls, value: object):
            args = {name: getattr(value, name, None) for name in cls.__annotations__}
            return cls(**args)

        def model_dump(self, *args, **kwargs):
            from airflow.serialization.serialized_objects import BaseSerialization

            return {
                name: BaseSerialization.serialize(getattr(self, name, None), use_pydantic_models=True)
                for name in self.__annotations__
            }
```

**Comment by potiuk** [comment]
Ah yes. This is because serialization uses Pydantic currently to serialize DB models that are part of the context and that requires Pydantic v2 to be installed. I'd say we should make this feature only available if Pydantic2 is installed (with approproate documentation and error messages) - and skip the tests if Pydantic 2 is not installed.

**Comment by phi-friday** [comment]
https://github.com/apache/airflow/blob/4e62909ff5fc92eb19676fb3266cd935cd42df55/airflow/serialization/serialized_objects.py#L630

If AIP44 is not enabled, an error is thrown.
So I made it so that an error is thrown if `pydantic<2` or AIP44 is not enabled. 
And I added test cases for each of them.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
