### PR TITLE
Replace all NBSP characters by whitespaces

### PR DESCRIPTION
**Pull request by BasPH**
This PR replaces all NBSP characters by whitespaces. Not visible in GitHub, but e.g. PyCharm displays them:

Greenshot 2022-07-02 08 32 20

NBSP characters can lead to hard to discover issues when copy-pasting.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
Interesting they creped into there in the first place. nice catch.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Some copy&paste from word :)  likely

**Review by eladkal — APPROVED** [review]
Can we add pre commit to avoid future cases?

**Comment by potiuk** [comment]
> Can we add pre commit to avoid future cases?

Good point

**Pull request merged**
