### PR TITLE
[AIRFLOW-6183] Fix flaky GCS hook gzip test

### PR DESCRIPTION
**Pull request by turbaszek**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6183

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:
This PR fixes flaky comparison of two gzipped byte strings. When the difference in time creation of two files was big enough then 5th byte of the later file was different 👀

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Restarted flaky test.

**Review by feluelle — COMMENTED** [review]
Should we also mock the same things in [test_upload_data_str_gzip](https://github.com/apache/airflow/blob/c38e11ec5bdbde113a4897619634f6ada3523f53/tests/gcp/hooks/test_gcs.py#L652) ?

**Comment by potiuk** [comment]
Good catch @feluelle: I think we shoudl @nuclearpinguin. It looks like the same problem might happen there.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
@nuclearpinguin -> will you fix it in the other test as well?

**Comment by turbaszek** [comment]
@potiuk I did it on Friday but forgot to push...

**Comment by potiuk** [comment]
> @potiuk I did it on Friday but forgot to push...

:D

**Comment by feluelle** [comment]
Restarted failed py 3.7 check:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Review by feluelle — APPROVED** [review]

**Pull request merged**
