### PR TITLE
[AIRFLOW-2639] Dagrun of subdags is set to RUNNING immediately

### PR DESCRIPTION
**Pull request by seelmann**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2639

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
    - Forward dagrun conf to subdag directly in SubdagOperator
    - Remove eager creation of subdags when triggering a DAG

### Tests
- [X] My PR adds the following unit tests
    - test_forwards_dag_run_conf

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by seelmann** [comment]
@milton0825 @kaxil Can you please take a look?

**Comment by bolkedebruin** [comment]
This seems to address two issues at once. Please split and make sure to add tests to both. Changing the trigger of a dag requires end to end test. Ie. will the sundag still run when the dag is triggered but its subdag not set to running

**Comment by seelmann** [comment]
I should have written that this PR tries to fix behaviour that was introduced in #3460 just some days ago. Before that the subdag was not eagerly created at all (and hence not set to running), so this PR reverts the changes in `trigger_dag.py`.

Are there e2e tests in airlfow repo? Can you point me to them? I tested manually e2e and deployed this change already to our dev env and will deploy to production tomorrow. And yes, the subdag run is created by the SubdagOperator and runs properly.

But I'm ok with splitting it up this PR. Then I'd suggest to revert #3460 for 1.10, and then create a separate PR for passing conf from the main dag to the subdag.

**Comment by seelmann** [comment]
As https://github.com/apache/incubator-airflow/pull/3460 / https://issues.apache.org/jira/browse/AIRFLOW-2355 now is in 1.10 I suggest to not consider this change because it would change behaviour again. Closing this.

**Pull request closed without merging**
