### PR TITLE
[AIRFLOW-599] Adding spotify to Airflow Users

### PR DESCRIPTION
**Pull request by znichols**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- Adds Spotify to list of Airflow users

### CODE REVIEW

**Comment by r39132** [comment]
Hi @znichols Please add Spotify in alphabetic order to the file. Also, refer to https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide 

Even for trivial commits such as this one, we'd like the community to create a JIRA and reference it in the commit message (e.g. [AIRFLOW-XXX]) as a prefix.

**Comment by znichols** [comment]
@r39132 Updated the PR and added relevant ticket here:
https://issues.apache.org/jira/browse/AIRFLOW-599

Apologies for not taking a closer look at the (pretty nice) guidelines.

**Comment by r39132** [comment]
+1 @znichols Welcome to the community!

**Comment by marctc** [comment]
Spotify uses [his own pipeline tool](https://github.com/spotify/luigi). How can be posible that they also uses Airflow? Any reference on this?

**Comment by bolkedebruin** [comment]
@marctc They actually use multiple(like: https://github.com/spotify/styx). We do as well (more in the proprietary space). Why don't you think that is possible?

**Comment by marctc** [comment]
Dunno. I thought that they standardized his tools and the whole company uses the same one.

**Pull request closed without merging**
