### PR TITLE
Add code snippet formatting in docstrings via Ruff

### PR DESCRIPTION
**Pull request by josh-fell**
This was made available [as part of v0.1.8 of the Ruff Formatter](https://astral.sh/blog/ruff-v0.1.8#formatting-code-snippets-in-docstrings). Adding this config option to the `ruff-format` pre-commit hook.

### CODE REVIEW

**Comment by josh-fell** [comment]
This _might_ also remove the need for `blacken-docs` reading this comment correctly from the [release notes of what this new version of Ruff Formatter supports](https://astral.sh/blog/ruff-v0.1.8#formatting-code-snippets-in-docstrings):

> reStructuredText [code-block and sourcecode directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block). As with Markdown, the language names recognized for Python are python, py, python3, or py3.

**Comment by potiuk** [comment]
> Am I reading that correctly?

You can check it by wrong-formating some of those :)

**Comment by josh-fell** [comment]
> This _might_ also remove the need for `blacken-docs` inferring from this comment from the [release notes of what this new version of Ruff Formatter supports](https://astral.sh/blog/ruff-v0.1.8#formatting-code-snippets-in-docstrings):
> 
> > reStructuredText [code-block and sourcecode directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block). As with Markdown, the language names recognized for Python are python, py, python3, or py3.
> 
> Am I reading that correctly?

Nope just handles those directives in docstrings not in rST files. Maybe one day.

**Review by hussein-awala — APPROVED** [review]
Great one! I was planning to test it once I have some time.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
