### PR TITLE
[AIRFLOW-5512] Add gcp dependencies into devel

### PR DESCRIPTION
**Pull request by haoliang7**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5512

### CODE REVIEW

**Comment by feluelle** [comment]
I don't think this is right. Because it is not a `minimal requirement` for all example dags to run.

**Comment by feluelle** [comment]
If you want to install an integration service like GCP you can install it via `pip install -e ".[devel,gcp]"`

**Review by feluelle — COMMENTED** [review]
I don't think this is right. Because it is not a minimal requirement for all example dags to run.

If you want to install an integration service like GCP you can install it via pip install -e ".[devel,gcp]"

**Comment by haoliang7** [comment]
> If you want to install an integration service like GCP you can install it via `pip install -e ".[devel,gcp]"`

@feluelle LOCAL_VIRTUALENV.rst says run `airflow db init` after `pip install -e ".[devel]"`. But errors occur due to missing gcp dependencies. Should we just ignore the errors?

**Comment by haoliang7** [comment]
> I don't think this is right. Because it is not a minimal requirement for all example dags to run.
> 
> If you want to install an integration service like GCP you can install it via pip install -e ".[devel,gcp]"

I assume by the purpose of devel that we should be able to initialize the database without an error after install devel dependencies.

**Comment by feluelle** [comment]
Maybe we should differentiate between example dags for minimal installation and advanced installation enabling advanced examples?

**Comment by nuclearpinguin** [comment]
@haoliang7 can you share the error?

**Comment by turbaszek** [comment]
> Maybe we should differentiate between example dags for minimal installation and advanced installation enabling advanced examples?

I agree with that, especially that when everything will be moved to core we will need not only gcp but also other dependencies. Maybe we can use `.airflowignore` for that? @feluelle

**Comment by potiuk** [comment]
How about moving the whole set of transfer operators/examples into a separate "transfer" sub-package- following AIP-21 principles. We have not agreed at the time of AIP-21 what we are going to do with transfer operators, but this sounds like one possible approach that could solve this problem ? We talked about it with @mik-laj and I think we both think it's a good idea

What do you thing @feluelle @ashb @haoliang7  and others who might be interested? I might raise the topic at the devlist thread for AIP-21

**Comment by mik-laj** [comment]
I agree. I think, it's a good idea to move transfer operators to separate python package. Currently, this division exists in integration.rst file. We have service operators and transfer operators in separate tables.
https://airflow.readthedocs.io/en/latest/integration.html
I thought also about long distance perspective. Separate package make easier to move operators to separate pip package - library. In this situation, all dependencies in new library should be [peer dependencies](https://nodejs.org/es/blog/npm/peer-dependencies/).

**Comment by feluelle** [comment]
> Maybe we can use `.airflowignore` for that? @feluelle

@nuclearpinguin That's exactly what I thought of, too. 👍 
Depending on the services `gcp`,`azure`, etc. we can ship a pre-defined `.airflowignore` file when installing via `initdb` and example_dags enabled.

> How about moving the whole set of transfer operators/examples into a separate "transfer" sub-package- following AIP-21 principles. We have not agreed at the time of AIP-21 what we are going to do with transfer operators, but this sounds like one possible approach that could solve this problem ? We talked about it with @mik-laj and I think we both think it's a good idea

That sounds also pretty good. @potiuk

**Comment by haoliang7** [comment]
> > Maybe we can use `.airflowignore` for that? @feluelle
> 
> @nuclearpinguin That's exactly what I thought of, too. 👍
> Depending on the services `gcp`,`azure`, etc. we can ship a pre-defined `.airflowignore` file when installing via `initdb` and example_dags enabled.
> 
> > How about moving the whole set of transfer operators/examples into a separate "transfer" sub-package- following AIP-21 principles. We have not agreed at the time of AIP-21 what we are going to do with transfer operators, but this sounds like one possible approach that could solve this problem ? We talked about it with @mik-laj and I think we both think it's a good idea
> 
> That sounds also pretty good. @potiuk

I am not sure how do we automatically edit `.airflowignore` file according to the installed dependencies. For example, when GCP dependencies are installed enbale GCP examples otherwise ignore them. 

Can we just skip the examples that cannot be imported when collecting dags? So that the users would not be confused by the error messages when only devel dependencies are installed. I have put that in my last commit.

**Comment by ashb** [comment]
This PR as it stands now doesn't look right as it significantly changes how/when/which DAG files are actually parsed and would mean no import errors show up in the UI I think.

If the goal is to stop the errors from parsing DAGs showing up in the CLI when running `db init` then the migration that imports the dags `airflow/migrations/versions/cc1e65623dc7_add_max_tries_column_to_task_instance.py` could be altered to either capture/silence the errors, or better might be to make that migration just work from the DB, not the code.

**Pull request closed without merging**
