### PR TITLE
Changes to Contributing to reflect more closely the current state of dev on Airflow

### PR DESCRIPTION
**Pull request by artwr**
@mistercrunch @jlowin @criccomini @bolkedebruin 
Our contributing.md was a little out of date. I also refactored some of the devel dependencies in extras_requires.

### CODE REVIEW

**Comment by artwr** [comment]
Ping anybody? I am not really touching code, so Travis build issues are not related.

**Comment by artwr** [comment]
Rebased.

**Comment by jlowin** [comment]
very helpful, much needed.

**Comment by mistercrunch** [comment]
Let's keep the extras documented and in sync here:
https://github.com/airbnb/airflow/blob/master/docs/installation.rst

**Comment by artwr** [comment]
Done @mistercrunch.

**Comment by mistercrunch** [comment]
LGTM

**Comment by r39132** [comment]
+1 Thx @artwr

**Pull request merged**
