### PR TITLE
Remove internal_api_call from airflow.secrets.metastore

### PR DESCRIPTION
**Pull request by potiuk**
Part of #44436

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by shahar1** [comment]
Tests are 🔴

**Comment by potiuk** [comment]
Ah... Our favorite:  `ImportError: cannot import name 'MetastoreBackend' from partially initialized module 'airflow.secrets.metastore' (most likely due to a circular import) (/opt/airflow/airflow/secrets/metastore.py)`

**Comment by potiuk** [comment]
One of those I want to get rid in airflow 3 by explicit rather than implicit initialization via "airflow.__init__".

**Comment by potiuk** [comment]
Hopefully green now :)

**Review by shahar1 — APPROVED** [review]

**Comment by shahar1** [comment]
> Hopefully green now :)

Not yet 😅 I was too optimistic

**Comment by potiuk** [comment]
Variable too... I hate circular imports

**Comment by potiuk** [comment]
Uff :)

**Pull request merged**
