### PR TITLE
Remove short form of --upgrade-on-failure

### PR DESCRIPTION
**Pull request by gmsantos**
The -u option is defined in --upgrade-to-newer-dependencies option too

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by gmsantos** [comment]
Before:

image

After:

image

**Review by jedcunningham — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
CI failure is unrelated (see #27287). Does `-u` work for `--upgrade-to-newer-dependencies` _before_ this change? Maybe we should remove that as well?

**Comment by gmsantos** [comment]
> Does -u work for --upgrade-to-newer-dependencies before this change?

By git blame, the short form for this option was added 6 months ago on breeze, and `--upgrade-on-failure` was added 2 months back.

**Comment by uranusjr** [comment]
Awesome, so this should be ready when CI passes.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Now-> I resolved conflicts in https://github.com/apache/airflow/pull/27191 after merging it ... Good revires there are welcome so that I can merge it :)

**Pull request merged**
