### PR TITLE
[AIRFLOW-6481] Fix bug in SalesforceHook

### PR DESCRIPTION
**Pull request by teddyhartanto**
---
Issue link: [AIRFLOW-6481](https://issues.apache.org/jira/browse/AIRFLOW-6481)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks  @TeddyHartanto !

**Comment by jeffolsi** [comment]
can this bug fix be released in next version?

**Comment by potiuk** [comment]
We are trying to minimise cherry-picking now. Next week hopefully we are going to release backport operators - so yo will be able to install airflow-backported-salesforce operators and use the operators from the new providers package in the previous 1.10.* airflow (in parallel to the operators from the 1.10. Would that be a better solution @jeffolsi  ?

**Comment by jeffolsi** [comment]
@potiuk I see that other hooks and operators do get released in regular versions.
take a look at these:
https://github.com/apache/airflow/pull/8787
https://github.com/apache/airflow/pull/8642
https://github.com/apache/airflow/pull/8287

Salesforce had number of PR that were not released
https://github.com/apache/airflow/pull/4829
https://github.com/apache/airflow/pull/5717
and this one.

If backport comes sooner than 1.10.11 great but if not can you please consider releasing them?
This will help us considerably.

**Comment by potiuk** [comment]
Hello @jeffolsi. Backport packages will definitely come before 1.10.11. the #8807 PR is about to be merged (a monstrous one as it contains all release notes automatically generated):

You can see the release notes for the snowflake package here: 

https://github.com/PolideaInternal/airflow/tree/automated-backport-release-management/airflow/providers/snowflake

**Comment by jeffolsi** [comment]
@potiuk Thank you!

**Pull request merged**
