### PR TITLE
Consistent formatting in CSS files

### PR DESCRIPTION
**Pull request by ryanahamilton**
Cleans up the CSS formatting across Webserver CSS files (excluding `bootstrap-theme.css`) and a handful of inline styles. I've only modified format—none of the changes should bear any impact on what is rendered. While formatting styles can become rather subjective, I attempted to limit to mostly objective changes, including:

- Consistent CSS indentation (as suggested by the [`.editorconfig` rule](https://github.com/apache/airflow/blob/48e89bd51c356cf0ce92563d10f4aadf6eb3a0ac/.editorconfig#L39-L40))
- Consistent spacing, line-breaks, ending semi-colons
- Short-hand, lowercase hex color values
- Removed units from `0` values
- Updated to newer `::` syntax for pseudo elements
- Removed vendor prefixes for long, widely-supported CSS features

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by mik-laj** [comment]
How will we prevent regression?  Did you think to use an automatic tool and add it to the pre-commit?https://github.com/apache/airflow/blob/master/.pre-commit-config.yaml

**Comment by ashb** [comment]
@mik-laj Yup, just discussing that now.

**Comment by ryanahamilton** [comment]
@mik-laj I'd like to follow-up this PR with another to add a linter (likely [stylelint](https://stylelint.io/)) that we can add to the pre-commit. I'll address remaining violations to get it in a passing state as well. Does that plan work for you?

**Comment by mik-laj** [comment]
@ryanahamilton That sounds fantastic. I'm waiting. Web UI needs a lot of our love

**Comment by kaxil** [comment]
CI failure is unrelated

**Pull request merged**
