### PR TITLE
Add clear task menu on task instance view

### PR DESCRIPTION
**Pull request by zkan**
Related: #16986 

Changes proposed in this PR:

* Add a clear task menu on task instance view to save a few clicks

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by zkan** [comment]
@bbovenzi @potiuk May I have your advice, please? I'm not good at designing a UI and here what I have so far.

Screen Shot 2564-10-16 at 21 47 21

* What should the UI look like?
* When we clear the task, which page should we redirect to? Right now I make it redirect to the tree view.

Thanks in advance.

**Comment by bbovenzi** [comment]
The simplest change would be to set a `max-width` on the `<form>` element. So the clear button stays closer to the actions. I would also recommend adding a title above the action to give context on what it does.

**Comment by arsalanfardi** [comment]
Hi @zkan, are you still working on this? I would be willing to assist - particularly if we want to add more actions in addition to clear task.

**Comment by zkan** [comment]
@arsalanfardi Thanks for asking! Yes, I'm still on it. Let me try this for 1-2 weeks. Will let you know how it goes.

**Comment by zkan** [comment]
Here is my latest version:

Screen Shot 2564-11-27 at 18 18 16

I think it may be easier less clicks to clear or try other actions on each sub tab. For example, when we see the log and want to restart the task, we can click the clear button above.

What do you think?

**Comment by bbovenzi** [comment]
Looking good! I'm just wondering if there is an easy way to reuse the actions code instead of copy-pasting it. But FAB may make that non-trivial...

**Comment by ashb** [comment]
I don't think these actions should be visible on the page by default  (it takes up a lot of vertical space)

Isn't the current modal generated by JS that we could call that again here on this page?

**Review by bbovenzi — CHANGES_REQUESTED** [review]
I'm gonna agree with Ash. Let's just add the button to open the already-existing modal. That would be a lot simpler.

**Comment by zkan** [comment]
@ashb @bbovenzi Thanks for the feedback. Totally agree that adding the already-existing modal will be a lot simpler. 🙇🏼‍♂️

**Comment by zkan** [comment]
@arsalanfardi I plan to continue working on this PR in Jan 2022. In the meantime, if you have time and would like to help, I'd be appreciated. :)

**Pull request closed without merging**
