### PR TITLE
Remove incremental upper-bind limit

### PR DESCRIPTION
**Pull request by potiuk**
The https://github.com/twisted/incremental/issues/106 issue has been addressed in 24.7.2 so we are removing the limit - just in case we also exclude the buggy versions, even if they are yanked.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by hussein-awala** [comment]
> just in case we also exclude the buggy versions, even if they are yanked.

Is there any reason for that? yanking should be safe without the need to exclude the versions if I am not mistaken 🤔

**Comment by potiuk** [comment]
> > just in case we also exclude the buggy versions, even if they are yanked.
> 
> Is there any reason for that? yanking should be safe without the need to exclude the versions if I am not mistaken 🤔

Yeah. It is, but ... well they could be unyanked :D

**Comment by potiuk** [comment]
Would love to merge it :)

**Comment by potiuk** [comment]
Yeah as discussed with the author in https://github.com/twisted/incremental/issues/106#issuecomment-2259315888 they might not want to yank this version - so it's good for us to exclude them

**Review by hussein-awala — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Pull request merged**
