### PR TITLE
[AIRFLOW-2298] Add Kalibrr to who uses Airflow

### PR DESCRIPTION
**Pull request by charlesverdad**
https://issues.apache.org/jira/browse/AIRFLOW-2298 
### Description
Add kalibrr to "Who uses airflow"

### CODE REVIEW

**Comment by r39132** [comment]
Please follow https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

**Review by Fokko — APPROVED** [review]
Thanks @charlesverdad!

**Comment by r39132** [comment]
It's interesting that this PR and another one that I merged show "Closed" instead of "Merged".

**Comment by Fokko** [comment]
It is actually pushed onto apache/incubating-airflow master, you can see `Kalibrr` on the README.md. It is because of the squash operation that will generate a new git-hash.

**Pull request closed without merging**
