### PR TITLE
[AIRFLOW-2818] Handle DAG File with Upper Case Extension

### PR DESCRIPTION
**Pull request by XD-DENG**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2818
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

In current design, when trying to identify and list Python files, case is not considered.
Only DAG files with '.py' will be identified, while files ending with '.PY' or '.Py', or '.pY' will be missed. However, it is allowed to have capital case file extension in all file systems.

The solution is simply applying `.lower()`.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
I'm of two minds on this one: one the one hand this might be annoying.

But on the other hand: this is how python works. If you have a `foo.PY` python will not find it:

```
# cat<<EOF > foo.PY
print("hi upper case")
EOF
# python -m foo
/usr/local/bin/python: No module named foo
# cat<<EOF > foo.py
print("hi lower case")
EOF
# python -m foo
hi lower case
```

**Comment by XD-DENG** [comment]
Hi @ashb , got your point.

But to my understanding, `Airflow` is using Python built-in package `imp` to import DAG files, which would work for uppercase extension python scripts.

Using the examples you provided above.
```
>>> import imp
>>> imp.load_source("test", "foo.PY")
hi upper case
<module 'test' from 'foo.PY'>
```

```
import imp
>>> imp.load_source("test", "foo.py")
hi lower case
<module 'test' from 'foo.py'>
```

or even

```
>>> imp.load_source("test", "foo.Py")
hi mixed case
<module 'test' from 'foo.Py'>
```

So `Airflow` itself can accept & import DAG file with extension containing UPPER cases. However due to the reason I described earlier, `Airflow` ignores and misses them. To users, this issue may be very misleading, because `python foo.PY` (not `python -m foo.PY`) would definitely work.

**Comment by XD-DENG** [comment]
Hi @ashb , on top of my last explanation, I have also done a local testing. Double-confirmed that after making the changes I'm proposing in this PR, DAG files with Uppercase extension (.PY, .pY, or .Py) can be identified and imported properly.

It does fix the issue.

Hope this can address your concern. Thanks.

**Comment by XD-DENG** [comment]
Hi @ashb , may you take another look at this and let me know your thoughts? 
Thanks!

**Pull request closed without merging**
