### PR TITLE
[AIRFLOW-1265] Fix celery executor parsing CELERY_SSL_ACTIVE

### PR DESCRIPTION
**Pull request by jordy25519**
Dear Airflow maintainers,

Fix celery executor config parsing of `celery/celery_ssl_active` key

Changed retrieval of `celery/celery_ssl_active` to use `configuration.getboolean()`

Add correct except block and log warning if `celery/celery_ssl_active` key is left undefined

@orezahc made this PR [pull/2340](https://github.com/apache/incubator-airflow/pull/2340/files) but it doesn't address the exception masking. 
Which causes the celery executor to fail if `celery/celery_ssl_active` is left undefined.

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1265) issues and references them in the PR title. For example, "[AIRFLOW-XXXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1265

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This is a bug fix, i.e. the current behaviour is broken so must be missing tests as is.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please fix your commit according to the guidelines (Jira, subject line etc)

**Comment by jordy25519** [comment]
Fixed PR info and squashed commits

**Comment by ashb** [comment]
Woot. @bolkedebruin Can this be merged please? Master is currently broken for using Celery executor on SQS with the otherwise default config.

**Comment by saguziel** [comment]
Please fix the commit message. There's a typo and the subject line looks too long

**Comment by jordy25519** [comment]
@saguziel done

**Comment by saguziel** [comment]
The commit message should still start with [AIRFLOW-xxxx]

**Comment by saguziel** [comment]
@holygits  can you rebase this

**Pull request closed without merging**
