### PR TITLE
Missing Error Handling for Docker Swarm

### PR DESCRIPTION
**Pull request by shubhamvk03**
This pull request resolves the “Missing Error Handling for Docker Swarm Requirements” issue. It adds error handling mechanisms to various methods to improve the robustness and stability of the code when dealing with Docker Swarm and Kubernetes operations. The lack of error handling previously led to unhandled exceptions and potential system crashes, which this update aims to prevent.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by shubhamvk03** [comment]
@apache Could you please review this PR when you get a chance? Thanks!

**Comment by shubhamvk03** [comment]
@apache Could you please review this PR when you get a chance? Thanks!

**Comment by shubhamvk03** [comment]
@apache/airflow
 Could you please review this PR when you get a chance? Thanks!

**Comment by potiuk** [comment]
Could you please rebase with conflict resolving and add unit test when you have time ?

**Pull request closed without merging**
