### PR TITLE
[AIRFLOW-4359] Add a check for dag_run.start_date

### PR DESCRIPTION
**Pull request by keisuke-kawamura**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4359

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by keisuke-kawamura** [comment]
If like this dag_run data is in airflow database, the toppage would be crush.

```
mysql> select execution_date, start_date from dag_run where dag_id = '_masked__' order by execution_date desc limit 1;

+----------------------------+------------+
| execution_date             | start_date |
+----------------------------+------------+
| 2017-04-03 18:00:00.000000 | NULL       |
+----------------------------+------------+
1 row in set (0.05 sec)
```

When I upgrade airflow to 1.10.2 from 1.8.1, the toppage doesn't work.
It's caused the code in webserver doesn't check start_date.
I think we need to add a check for start_date.

**Review by feluelle — APPROVED** [review]
LGTM 👍

**Comment by feluelle** [comment]
Before- and After-Screenshots would also be nice here :)

**Comment by OmerJog** [comment]
@kkawamura  are you still working on this PR?

**Pull request closed without merging**
