### PR TITLE
Add test case to show issue with deserialization

### PR DESCRIPTION
**Pull request by utkarsharma2**
Add a test case to demonstrate the issue with deserialization. More details on the ticket

related: https://github.com/apache/airflow/issues/30797

cc: @uranusjr

### CODE REVIEW

**Comment by hussein-awala** [comment]
Will you implement a fix for this issue? without a fix, this PR will be never merged, and it's better to add the test in the same PR with the fix.

**Comment by hussein-awala** [comment]
I added the test to #30819 which fixes the issue, I tested the fix on your dag and it seems to work, can you test it?

I close this PR.

**Comment by utkarsharma2** [comment]
@hussein-awala Thanks for fixing this, I just wanted to highlight the issue with this PR. :)

**Comment by utkarsharma2** [comment]
@hussein-awala Sure, I don't have access to my system right now but will check on my dags first thing in the morning.

**Comment by utkarsharma2** [comment]
@hussein-awala It's working for my dag as well. :)

**Pull request closed without merging**
