### PR TITLE
[AIRFLOW-4003] Extract example DAGs to separate pythons files

### PR DESCRIPTION
**Pull request by cixuuz**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4003
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Based on suggestions from @mik-laj in https://github.com/apache/airflow/pull/4805. 
> If we have this file in repo, we should include it instead of copy it's content. It's allow to keep example allways working and fresh.
> See:
> http://www.sphinx-doc.org/en/1.5/markup/code.html#directive-literalinclude
> https://github.com/apache/airflow/blob/master/docs/howto/operator.rst

By extracting example python script, we could have unittest on them and make sure correction easily.
The example dags extracted in following documentations:
1. tutorial
2. concepts
3. scheduler
4. lineage

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by mik-laj** [comment]
I am currently working on a similar PR
https://github.com/PolideaInternal/airflow/pull/77
My proposal differs in the assumptions:
a) I want to Extract all the code fragments, not just a certain group
b) I want to complete automatic tests for examples. 
For the reasons of the tests, I have not finished this PR yet

**Comment by cixuuz** [comment]
> I am currently working on a similar PR
> [PolideaInternal#77](https://github.com/PolideaInternal/airflow/pull/77)
> My proposal differs in the assumptions:
> a) I want to Extract all the code fragments, not just a certain group
> b) I want to complete automatic tests for examples.
> For the reasons of the tests, I have not finished this PR yet

Thanks for sharing the current progress. 
Yes, your proposal is more complete and soundness. 
We maybe split the whole task into subtasks, because too many documentations need to be updated. 
In my PR, I extracted DAG related code for **tutorial, concepts**, scheduler, lineage. I saw you have finished changes on **scheduler and lineage**. I think I could focus on codes on **tutorial and concepts**. 
Thus, in this PR, I will 
1) only extract codes on **tutorial and concepts**.
2) extract all code snippets, not only DAGs. 
Is it good?

As for second step, we could create a new PR to add tests for all those examples. 

Besides, I have some questions:
1. Some code fragments are not a DAG file, such as [Kubernetes Operato](https://github.com/PolideaInternal/airflow/pull/77/files#diff-c63bdbf4e38e4a44b9023b6d79aba6d5), is example_dags a good place for those code?
2. Some code fragments are not complete, such as [dependency description](https://airflow.apache.org/concepts.html#bitshift-composition), is it necessary to extract such code?

Thank you very much!

**Comment by mik-laj** [comment]
I would prefer to make all changes in one PR. Creating new files should be combined with the creation of tests.  Extracting fragments only to store them in another file is unintentional. This will only make it difficult to write documentation. You should extract the fragments and write tests, so that it would have an added value.

I am proposing that you send PR to my PR. I will accept all your changes quickly, and finally I will add you as a co-author of the commit/PR. 

Answering your questions.
1. I made a DAG file out of it and selected the fragment that was needed in the documentation. This gives a real example of use. An example that can be tested.
It is worth noting that I am working on a mechanism that allows us to see the full source code in the documentation. https://github.com/apache/airflow/pull/4894
2. In a perfect world, yes. We should prepare examples that should use the code fragments needed in the documentation. 
It is worth noting that the fragments can also be in the test files.
https://github.com/googleapis/google-cloud-python/blob/51c97cd5ecf17d984be3f01cecd6e5d70ae1b266/bigquery/docs/snippets.py
but the world is not always perfect.

**Comment by mik-laj** [comment]
I added a tests for all non-contrib DAGs in my PR.

**Comment by cixuuz** [comment]
Hi @mik-laj Cool. Sounds good. 

> I am proposing that you send PR to my PR. 

Are you referring to this PR https://github.com/PolideaInternal/airflow/pull/77 ?
Can you guide how to send my PR to that?

Thank you!

**Comment by mik-laj** [comment]
1. Open https://github.com/PolideaInternal/airflow/pulls
1. Select base repository PolideaInternal
1. Select base: `extract-examples`
1. Select head repository: your repository
1. Select compare: your branch

If you do not see all the options then you have to press the link "Compare across forks":
image

**Comment by mik-laj** [comment]
To reduce the number of conflicts, I will regularly move your commit to my branch. After completing our changes, I will create one commit from all commit (squash).

**Comment by cixuuz** [comment]
Neat. Since this PR is unnecessary, I will close it. 
Please refer to this PR later: https://github.com/PolideaInternal/airflow/pull/77

**Pull request closed without merging**
