### PR TITLE
Fetching databricks host from connection if not supplied in extras.

### LINKED ISSUE #10726: databricks host name pulling out from extra json data when token is used
When the token is used in the databricks connection, the host name is being pulled from extra json data

https://github.com/apache/airflow/blob/fdd9b6f65b608c516b8a062b058972d9a45ec9e3/airflow/providers/databricks/hooks/databricks.py#L160

I think the host name should be pulled from databricks_conn directly as the line 164, where basic auth is being used https://github.com/apache/airflow/blob/fdd9b6f65b608c516b8a062b058972d9a45ec9e3/airflow/providers/databricks/hooks/databricks.py#L164

Thanks!

Liusong

### PR DESCRIPTION
**Pull request by joshi95**
Fix for the issue #10726 . Have supported the previous functionality of fetching the host from extras if specified else it is getting fetched from the databricks connection which makes more sense.

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @joshi95 , looks good to me. May you rebase?

**Comment by XD-DENG** [comment]
On the other hand, before I can merge, the test you added doesn't make much sense to me. May you clarify a bit or enhance it further?

**Comment by joshi95** [comment]
> On the other hand, before I can merge, the test you added doesn't make much sense to me. May you clarify a bit or enhance it further?

Hi, In this test I have reused the existing TestDatabricksHookToken test with one less extra argument ie {'token': TOKEN} instead of {'token': TOKEN, 'host': HOST}

**Comment by XD-DENG** [comment]
I see. Thanks for the clarification.

May you rebase? Once ci is green I would be happy to merge.

Thanks.

**Comment by joshi95** [comment]
> I see. Thanks for the clarification.
> 
> May you rebase? Once ci is green I would be happy to merge.
> 
> Thanks.

Yes thanks, Have rebased .

**Comment by joshi95** [comment]
Hi not sure why k8s ci test has failed.

**Comment by XD-DENG** [comment]
Possibly a transient error. I have restarted the CI, let’s see if it will be ok

**Comment by joshi95** [comment]
> Possibly a transient error. I have restarted the CI, let’s see if it will be ok

thanks

**Review by XD-DENG — APPROVED** [review]

**Comment by XD-DENG** [comment]
Thanks @joshi95 😃

**Pull request merged**
