### PR TITLE
[AIRFLOW-1508] Add SKIPPED state to task_states

### PR DESCRIPTION
**Pull request by Acehaidrey**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow 1508](https://issues.apache.org/jira/browse/AIRFLOW-1508) issues regarding of the skipped state missing from the task_states.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
In the `airflow.state` module, `State.task_states` doesn't include the `SKIPPED` state even though the `TaskInstance` object has it. I believe this is a bug and have filed a JIRA for it.
I also did a thorough check for usages of this method and it's only used in [views.py](https://github.com/apache/incubator-airflow/blob/master/airflow/www/views.py#L560) in the `task_stats` function. By making the amend, all that will happen is we add another stat in the payload. The below code from the file does this and appends it.
```
                d = {
                    'state': state,
                    'count': count,
                    'dag_id': dag.dag_id,
                    'color': State.color(state)
                }
```

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
My case doesn't really need any tests because we're simply adding a single line of a new state the the `task_states` object. 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Acehaidrey** [comment]
@

**Comment by Acehaidrey** [comment]
@edgarRd sorry to bother you but was wondering if you could review this or comment on the JIRA (or anyone from your team).

**Comment by Acehaidrey** [comment]
@aoen I was wondering if you could give your two cents on this JIRA? I am trying to figure out if it is a bug or it's intentionally left out (not sure why it would be). @edgarRd also commented on there so can review his thoughts too. That'd be great if you had the time.

**Comment by jmcarp** [comment]
cc @ashb @Fokko. Any reason not to include `SKIPPED` in `State.task_states`, since it's a state that a task can have?

**Comment by ashb** [comment]
Can't think of any reason it shouldn't be in the list given everything else is.

Switching to `enum` (by pulling in https://pypi.org/project/enum34/ for Pythons older than 3.4) would probably make all of that `State` class simpler and less error prone.

**Pull request closed without merging**
