### PR TITLE
Fix Sphinx Issues with Docstrings

### PR DESCRIPTION
**Pull request by sunkickr**
This PR fix some typos and issues were the doctrings do not adhere to sphinx standards in the following modules:
- AWSDataSyncOperator
- S3KeySizeSensor
- DatadogHook
- DatadogSensor
- ComputeEngineSSHHook
- CloudDataCatalogLookupEntryOperator
- GoogleDisplayVideo360UploadLineItemsOperator
- GoogleDisplayVideo360CreateSDFDownloadTaskOperator
- GoogleDisplayVideo360SDFtoGCSOperator
- AzureBatchOperator
- AzureCosmosDocumentSensor
- SingularityOperator
- SlackAPIOperator
- DataprocCreateMapReduceJobOperator
- DataprocCreateSparkJobOperator
- DataprocCreatePysparkJobOperator

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by sunkickr** [comment]
@kaxil is there anything that needs to be done with this PR to merge? Not really sure why the tests are failing. Error message says `ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.`

**Comment by kaxil** [comment]
Looks like an un-related failure

```
  apache-beam 2.28.0 has requirement dill<0.3.2,>=0.3.1.1, but you have dill 0.3.3.
```

**Comment by uranusjr** [comment]
The same conflict seems to be failing CI on other PRs as well.

**Comment by kaxil** [comment]
@potiuk Any ideas on why the Provider packages job is trying to rebuild image, I checked only jobs on 2.0.1 and old commits -- where it didn't

Example that worked: https://github.com/apache/airflow/runs/2124903826#step:6:87

Example that fails: https://github.com/apache/airflow/runs/2188111255#step:6:76

**Comment by potiuk** [comment]
This is super strange. The root cause is that between one step and another looks like the yarn.lock and package.json are changed ! but nothing touches them really between the two (and it always worked fine)

In another PR we see the same:

https://github.com/apache/airflow/pull/14968/checks?check_run_id=2188403270#step:5:125

```
  Updated md5sum file /home/runner/actions-runner/_work/airflow/airflow/.build/master/3.6/CI/package.json.md5sum for /home/runner/actions-runner/_work/airflow/airflow/airflow/www/package.json.
  Updated md5sum file /home/runner/actions-runner/_work/airflow/airflow/.build/master/3.6/CI/yarn.lock.md5sum for /home/runner/actions-runner/_work/airflow/airflow/airflow/www/yarn.lock.
```

And in the next step (same runner, same job):
https://github.com/apache/airflow/pull/14968/checks?check_run_id=2188403270#step:6:86
```
  The md5sum changed for /home/runner/actions-runner/_work/airflow/airflow/airflow/www/package.json
  The md5sum changed for /home/runner/actions-runner/_work/airflow/airflow/airflow/www/yarn.lock
```

**Review by kaxil — APPROVED** [review]

**Pull request merged**
