### PR TITLE
Remove JIRA ticket insert by bot in PR template

### PR DESCRIPTION
**Pull request by zhongjiajie**
---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I think we do not need this line anymore

**Comment by kaxil** [comment]
We intentionally kept that line for now to address old Jira issuee

**Comment by potiuk** [comment]
Yeah. We are going to keep it for a  short while.

**Comment by zhongjiajie** [comment]
OK I got it. should I close PR or pending it

**Review by dimberman — APPROVED** [review]

**Comment by dimberman** [comment]
Now that we've shut off new JIRA tickets I think we can merge this :)

**Comment by zhongjiajie** [comment]
Thanks for merging

**Pull request merged**
