### PR TITLE
[AIRFLOW-2983] Add prev_ds_nodash and next_ds_nodash macro

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2983
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description
Similar to https://github.com/apache/incubator-airflow/pull/3418, but introduce two nodash macros:
{{ prev_ds_nodash }}: the previous execution date as {{ YYYYMMDD }}
{{ next_ds_nodash }}: the next execution date as {{ YYYYMMDD }}

We introduced prev_ds and next_ds in https://github.com/apache/incubator-airflow/pull/3418 which is beneficial for backfill.  By using these two macros, we could override the schedule_internal from daily to certain days(e.g 7 days) in backfill through ```--conf``` option. 

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @Fokko @kaxil

**Comment by r39132** [comment]
@feng-tao can you provide a description for your change to the JIRA? The problem statement should be apparent to anyone in the community.

**Comment by feng-tao** [comment]
Thanks @r39132  for the feedback. I updated the description in the pr and jira and let me know if it looks ok to you.

**Comment by kaxil** [comment]
LGTM. @feng-tao  Can we add a simple test for this?

**Comment by feng-tao** [comment]
@kaxil , thanks for the comment. I added a unit test to check. Will wait for CI to finish.

**Comment by feng-tao** [comment]
Hey @kaxil, @r39132, a test to check template context is added. Merge it now.

**Comment by r39132** [comment]
FYI... don't forget to close JIRA issues when you merge ... for future reference .. I just closed https://issues.apache.org/jira/browse/AIRFLOW-2983

**Comment by feng-tao** [comment]
Thanks @r39132 . Will keep in mind next time.

**Pull request merged**
