### PR TITLE
Fix running parallel k8s tests in "depth-first" mode in CI

### PR DESCRIPTION
**Pull request by potiuk**
The K8S tests when run in parallel for multiple versions require:

a) vast amount of memory to keep all the cluster running
b) extra time to startup for all k8s tests

This caused a problem when tests in CI were split into separate
steps - because we had to create all clusters before we run tests
even if we limited parallelism.

By using "depth-first" mode, we can run complete tests (with
cluster creation and deletion) in parallel with limited parallelism
without having to create all clusters upfront.

We now add the `run-complete-tests` command that does all the
steps in one function - which makes it much nicer to parallelise
without using too much resources.

There had to be a few fixes done to make it happen.

* Failure in CI for K8S jobs produced really long logs that
  were next to impossible to analyse any problems (for example
  problems involved with lack of memory or with overwhelming K8S
  with too many requests when there were multiple clusters.
  When we combined multiple steps in one output it made the logs
  absolutely unusable.

* Verbose moda has been disabled because it was creating too much
  noise (not that bad as resource dumps, but still lots of it).

* The resource dumps from K8S are now dumped to separate files.
  Those resource dumps can be downloaded separately as they are uploaded
  as artifacts in case of failure.

There were also few fixes to kubernetes tests to make them more stable
and debuggable:

* Assertion which was thrown in "setUp" of K8S test base did not give
  too much information about what the problem was so it has been now
  replaced with a much more user-friendly message showing the actual
  reason (could not check health of the webserver) and
  you can see the root cause alongside the error.

* Few tests in itest_kubernetes_pod_poperator were using fixed path for
  local temp file that caused intermittent failures of the tes when run
  in parallell.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I added debugging resources in all places in order to debug K8S tests failure in main. Turned out that it was running out of space in /var/lib/docker filesystem, so I increased the space we allocate for `/var/lib/docker` in our AMI image. Hopefully it will run fine (but the main should be fixed already without merging this one - this one only enables debugging the resources.

**Comment by potiuk** [comment]
It was a bit too small so I got it bumped a little again. 🤞

**Comment by potiuk** [comment]
Hey here - this is something I had to fix before I disconnect for the next 2 weeks.

It looks I managed to solve some of tha main (not all but should be pretty good) stability issues with "K8S tasks". They are now consistently failing in main when run in parallel and I mitigated the problem by:

* decreasing paralllelism (accounting by the fact that Kind cluster + airflow require many more resources than 1 CPU only.
* using `depth-first` approach for running the tests (not all k8s clusters need to be started upfront when run in parallel - they are now created and discarded in parallel as needed and no more than 2 clusters are running in parallel ).
* fixing some parallelism-incompatible bugs
* improving diagnostics to be much more usable in case of failures (already used it to fix some of the bugs).

I tested it with self-hosted and public runners and while could not eliminate every single flakiness (there are still few tests that randomly fail) - it is much closer to way better stability and much easier to diagnose problem and locally reproduce it (@ephraimbuddy - you might be glad to hear it, I think the previous CI logs were next to unusable).

I would love to merge it soon - this will help to keep main `green` (and this is the last one that will keep me from completely disconnecting so I'd appreciate quick turnaround :).

**Comment by potiuk** [comment]
One last rebase to check  with "full tests"

**Comment by potiuk** [comment]
All green. Looking forward to merge this one :)

**Review by dstandish — APPROVED** [review]

**Pull request merged**
