### PR TITLE
[AIRFLOW-1412] Add config to truncate the task log file

### PR DESCRIPTION
**Pull request by zhangela**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1412

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Reasons for doing this:
    1. webserver would hang if you try to view log that is too big
    2. unlimited log size could be bad for disk space

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

I didn't see unit tests for logs in the code base

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Sorry I don't think this is the right approach. Better rotate your logs or make sure you log less.

**Comment by zhangela** [comment]
How would log rotate address this issue? 1 failing task is logging an excessive amount of data, and you won't even be able to see that log at all in the webserver because it just hangs. In that case, you'd have to manually find that log file from the airflow box. 

Log rotating would address the disk space issue, but I think webserver hanging is by far the bigger problem and I don't think that's addressed.

**Comment by allisonwang** [comment]
Hi zhangela indeed excessive logs will make webserver hang for long time. This problem will be addressed later as we change the frontend to lazyly fetch the logs. Truncating logs shouldn't be part of airflow core logic. You can maybe make task logging less verbose or change LOG_LEVEL in airflow config.

**Comment by zhangela** [comment]
I see. Yeah I think as long as the webserver can lazily fetch the logs 1 page at a time, that would solve the main problem here. Any idea when that would be shipped?

**Comment by ashb** [comment]
> Yeah I think as long as the webserver can lazily fetch the logs 1 page at a time, that would solve the main problem here. Any idea when that would be shipped?

In 1.10 it turns out!. Closing this now.

**Pull request closed without merging**
