### PR TITLE
 [AIRFLOW-2575] Make gcs to gcs operator work with large files

### PR DESCRIPTION
**Pull request by torkjel**
### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title:
    - https://issues.apache.org/jira/browse/AIRFLOW-2575

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Use `GoogleCloudStorageHook.rewrite` instead of `copy` so that it
works with files > 5TB

### Tests
- [X] My PR updates existing tests to pass after the change. 

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Code Quality
- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
From https://cloud.google.com/storage/docs/json_api/v1/objects/copy:

>Use the copy method to copy between objects in the same location and storage class. When copying objects across locations or storage classes it's sometimes possible to use the copy method, but we recommend using the rewrite method instead because if the source and destination are in different locations or storage classes the copy method calls the rewrite method exactly once behind the scenes. The larger the object the more likely that multiple rewrite calls will be needed to complete the operation. If the single rewrite call made by copy doesn't complete the operation it will result in a Deadline exceeded error.

I am curious to know the use of `copy` method in presence of `rewrite` method. @fenglu-g  @tswast

**Comment by tswast** [comment]
Rewrite could require multiple API calls for large files. https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite

**Comment by kaxil** [comment]
@tswast But `copy` won't work for largr files over 5 TB I suppose?

**Comment by kaxil** [comment]
@tswast @fenglu-g Based on the thread, I am still unable to figure out the use of `copy` method while `rewrite` method exist. I am sure there must be some reason of having 2 separate methods `copy` and `rewrite`. And what do you think about the change in this PR?

**Comment by tswast** [comment]
`rewrite` is the more general method, yes. The `copy` method is mostly a helper method for those using the API directly, a library such as this one should probably always use `rewrite`.

I see that the hook does loop with `rewrite` until the copy is complete, so this change should work as intended.

https://github.com/apache/incubator-airflow/blob/df05546f8d4676ff3651e6a4c093ad068c7f5bbc/airflow/contrib/hooks/gcs_hook.py#L125-L140

**Review by tswast — APPROVED** [review]

**Comment by kaxil** [comment]
Cool. 👍 understood. Thanks @tswast

**Comment by kaxil** [comment]
LGTM

**Comment by kaxil** [comment]
Thank you @torkjel for your contribution.

**Pull request closed without merging**
