### PR TITLE
[AIRFLOW-2809] Fix security issue regarding Flask SECRET_KEY

### PR DESCRIPTION
**Pull request by XD-DENG**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2809
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

#### Background
Currently there is a configuration item **secret_key** in the configuration .cfg file, with a default value "temporary_key".

#### Issue
**Most admins would ignore it and just use the default value "temporary_key". However, this may be very dangerous. User may modify the cookie if they try the default SECRET_KEY while the admin didn't change it.**

**In Flask documentation, it's suggested to have a SECRET_KEY which is as random as possible (http://flask.pocoo.org/docs/1.0/quickstart/ ). **

#### My Proposal
If Admin explicitly changed the SECRET_KEY in **.cfg** file, we use this SECRET_KEY given by Admin.

If the default SECRET_KEY is not changed in **.cfg** file, randomly generate SECRET_KEY. Meanwhile, print INFO to remind that a randomly generated SECRET_KEY is used.

This solution will not affect user experience at all. 

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@XD-DENG Can you prepend the squash the commits and prepend the message with the Jira ticket `[AIRFLOW-2809] ...`

This looks like a good idea to me, maybe check what the other committers think about this.

cc @kaxil @bolkedebruin @jgao54

**Comment by XD-DENG** [comment]
Thanks @Fokko . Have squashed the commits and prepended the JIRA ticket label as suggested.

**Comment by kaxil** [comment]
Thank you @XD-DENG , @Fokko This makes sense to me as well. LGTM

**Review by Fokko — APPROVED** [review]
LGTM

**Pull request closed without merging**
