### PR TITLE
Move version imports to inside utils standard provider

### PR DESCRIPTION
**Pull request by gopidesupavan**
Version imports causing issues when using from __init__ : https://github.com/apache/airflow/pull/44011
https://github.com/apache/airflow/pull/44011#discussion_r1841786333

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
cc @potiuk

**Comment by potiuk** [comment]
This is strange error

**Comment by potiuk** [comment]
Applying full tests needed should help

**Comment by potiuk** [comment]
The problem is that "sdist" test build new providers and try to install them, and they do it in "chunks" - and only for providers affected in this PR. This is a bit missing piece - this PR  only modifies the standard provider but no common.sql 1.20 that it depends on, so it misses 1.20 version locally built.

We could likely solve it by smarter selection which providers should be built for sdist builds, but for now "full tests needed"  should be enough - also this will go away after we merge this one an release common.sql 1.20 , and applying "full tests needed" should solve the problem as all provider's sdist will be built.

**Comment by eladkal** [comment]
> We could likely solve it by smarter selection which providers should be built for sdist builds, but for now "full tests needed" should be enough - also this will go away after we merge this one an release common.sql 1.20 , and applying "full tests needed" should solve the problem as all provider's sdist will be built.

Yeah the problem should not happen after merging to main.
We can open a followup task in Github issue to get it done when we have the time

**Comment by potiuk** [comment]
> We can open a followup task in Github issue to get it done when we have the time

Yeah. I was adding it as you wrote it :) https://github.com/apache/airflow/issues/44023

**Comment by gopidesupavan** [comment]
> The problem is that "sdist" test build new providers and try to install them, and they do it in "chunks" - and only for providers affected in this PR. This is a bit missing piece - this PR only modifies the standard provider but no common.sql 1.20 that it depends on, so it misses 1.20 version locally built.
> 
> We could likely solve it by smarter selection which providers should be built for sdist builds, but for now "full tests needed" should be enough - also this will go away after we merge this one an release common.sql 1.20 , and applying "full tests needed" should solve the problem as all provider's sdist will be built.

oh i see, good learning bit to know this :)

**Review by eladkal — APPROVED** [review]

**Comment by gopidesupavan** [comment]
tests are failing for openlineage, created this https://github.com/apache/airflow/pull/44025

**Pull request merged**
