### PR TITLE
[AIRFLOW-3685] Move licence header check

### PR DESCRIPTION
**Pull request by ffinfo**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3685

### Description

Moving licence header check to a pre-test stage to prevent useless travis resources

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
+1 this is a good change. Approved. Waiting for the CI to pass.

**Comment by BasPH** [comment]
Wow what a coincidence... I was just about to push the PR button and see this. https://issues.apache.org/jira/browse/AIRFLOW-3686

**Comment by BasPH** [comment]
My branch is a bit more explicit: https://github.com/apache/airflow/compare/master...BasPH:bash-split-license-ci-check. The license check is a separate stage since it's not related to Flake8 IMO:

image

**Comment by ffinfo** [comment]
This is my version, in this case flake8 and check licence can run in parallel.
May this best one win ;)

screenshot 2019-01-12 at 13 49 43

**Review by Fokko — APPROVED** [review]

**Pull request merged**
