### PR TITLE
[AIRFLOW-1487] Added links to all companies currently officially using Airflow

### PR DESCRIPTION
**Pull request by tanmatt**
Added links to all companies currently officially using Airflow

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1487

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Found some missing links to companies using Airflow. Added. 

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Readme file changes. No unit testing required. 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by aoen** [comment]
LGTM, but please create a JIRA (a lot of the processes/tools we use break without this)

**Comment by tanmatt** [comment]
@aoen I don't have access to create a new issue in JIRA https://issues.apache.org/jira/browse/AIRFLOW/

**Comment by saguziel** [comment]
@tanmaythakur  afaik, anyone can create an account

**Comment by tanmatt** [comment]
Created issue https://issues.apache.org/jira/browse/AIRFLOW-1487 and updated the description. Is it good to push?

**Comment by aoen** [comment]
Almost! Just change the PR title/commit message to start with the JIRA ticket [AIRFLOW-1487].

**Comment by tanmatt** [comment]
Made necessary changes.

**Comment by ghost** [comment]
The Jira ticket is still in progress and needs to be resolved: https://issues.apache.org/jira/browse/AIRFLOW-1487

@aoen  is there supposed to be some automation for closing Jira tickets by using the Jira ticket name in the title/commit ?

**Pull request closed without merging**
