### PR TITLE
Add to provider.FTP possibility to use file-like objects.

### LINKED ISSUE #29153: FTP(S)FileTransmitOperator class should allow to use file-like buffer.
### Description

Hi.

It would be great to have possibility to use file-like buffer as local_filepath parameter. An example:
```python3
class FTPFileTransmitOperator(BaseOperator):
    def __init__(
        self,
        *,
        ftp_conn_id: str = "ftp_default",
        local_filepath: str | list[str] | io.TextIOWrapper | list[io.TextIOWrapper],
        remote_filepath: str | list[str],
        operation: str = FTPOperation.PUT,
        create_intermediate_dirs: bool = False,
        **kwargs,
    ) -> None:
        ...
```
My proposition can be found in the following PR: https://github.com/apache/airflow/pull/29156
Please let me know it requires more coding/fixing. I really need this functionality.

### Use case/motivation

Files to be sent to the FTP server can be read by open/smart_open from e.g. S3 or AzureStorage. The current solution forces such a file to be downloaded, which makes the provider very limited. Here, passing the handle returned by smart_open would solve the problem. It should not be hard, because hook (FTPHook) in method store_file can use file_handlers.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Draqun**
Closes: https://github.com/apache/airflow/issues/29153

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Taragolis** [comment]
Could you provide any samples how you intend to use this?
Because you can't easily send file-like objects between tasks.

In general if you need transfer between two sources you need to create Transfer Operator:
see as example:
- [Google Transfer Operators](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/operators/transfer/index.html)
- [Amazon Transfer Operators](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/transfer/index.html#amazon-transfer-operators)

**Comment by Draqun** [comment]
The scenario is as follows:
- a container is started using DockerOperator, where data is prepared for processing in the cloud (AWS and AZURE)
- data after processing in the cloud is saved in S3/Azure Storage as a rather large file
- this file needs to be uploaded to the FTP server - instead of downloading the file, I want to use smart_open and pass the file handle as a parameter to the FTP provider.

The proposed fix solves my problem. Everything works as expected because FTPHook is customised for this type of operation.

**Comment by Taragolis** [comment]
> The proposed fix solves my problem.

And looks like might add problems for others. See [Best Practices -> Top level Python Code](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code):

```text
Specifically you should not run any database access, heavy computations and networking operations.
```

BTW did you try your solution by your own?

---

> this file needs to be uploaded to the FTP server - instead of downloading the file, I want to use smart_open and pass the file handle as a parameter to the FTP provider.

Still no idea how it would work without spawning dozen additional connection.


Just use Hook inside task execution (if it has appropriate method for solve your issue), not a task method.

```python

with DAG(
    dag_id="abstract_dag",
    start_date=pendulum.datetime(2022, 1, 1, tz='UTC'),
    schedule=None,
    catchup=False,
    tags=["abstract"]
):
    @task.docker(image="foo:bar-slim")
    def first_task():
        # Instead of this comment should exist code which produce file to S3/Azure/GCS
        return uri

    @task
    def second_task(uri):
        with smart_open.open(uri) as fp: # BTW how you plan managed connections to S3/Azure/GCS?
            ftp_hook = FTPHook(...)
            ftp_hook.use_appropriate_method(...)

    second_task(first_task())
```

**Comment by potiuk** [comment]
I agree with @Taragolis - that passing file-like objects in FileTransferOperator is not going to work. Each operator when executing will run in its own process/interpreter and there is simply no way to pass the file-like object to it.

Closing, unless there will be some explanation - maybe we are wrong and there is something we both completely miss. @Draqun  - if you can explain it, please do.

The way how you should do what you want is different - you could implement File-lilke objects in Hooks and then use TaskFlow approach as desrribed in my blog post here: https://medium.com/apache-airflow/generic-airflow-transfers-made-easy-5fe8e5e7d2c2

**Pull request closed without merging**
