### PR TITLE
Refactor new UI Nav

### PR DESCRIPTION
**Pull request by bbovenzi**
Redesign the navigation bar in the new UI from the top to the left hand side. A big downside of the legacy UI was too many navs and banners pushing the useful page content halfway down the page.

Dark Mode:
Screenshot 2024-09-04 at 4 08 54 PM

Light Mode:
Screenshot 2024-09-04 at 4 08 58 PM

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
Very nice!

I see you decided to drop the tags and owner from the default view but choose to have description. I think tags and owner are better to display first and description can be opened when clicking on the expand arrow

**Comment by bbovenzi** [comment]
> Very nice!
> 
> I see you decided to drop the tags and owner from the default view but choose to have description. I think tags and owner are better to display first and description can be opened when clicking on the expand arrow

Oh. Ignore the dags table for now. It was a placeholder. It is going to be redesigned. And everything you just said is already in the works.

**Comment by potiuk** [comment]
Nice indeed. And bold. And I love it.

**Comment by eladkal** [comment]
> Oh. Ignore the dags table for now. It was a placeholder. It is going to be redesigned. And everything you just said is already in the works.

Super cool!

**Review by eladkal — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]

**Pull request merged**
