### PR TITLE
[AIRFLOW-1208] Speed-up cli tests

### PR DESCRIPTION
**Pull request by skudriashev**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following
    - [AIRFLOW-1208](https://issues.apache.org/jira/browse/AIRFLOW-1208) Speed-up cli tests

### Description
- [x] No need to do actual reset in unit tests if nothing is really verified in it. So we mock it.

### Tests
- [x] All tests passed.

### CODE REVIEW

**Comment by skudriashev** [comment]
@bolkedebruin, could you please have a look in this? Thanks.

**Comment by bolkedebruin** [comment]
I'm not sure if a I agree with this. While these are not particularly unit tests they are more like integration tests. The speedup will also be quite low I presume.

**Comment by skudriashev** [comment]
@bolkedebruin, but what these tests do? I mean if `resetdb` and `inidb` do not work - we won't have tests even started (since we do this during env. sutup). So I guess it worth just to check that cli command works without actual db reset.

**Comment by skudriashev** [comment]
@bolkedebruin also I know this is a very little speedup, but having many of such speedups we can improve speed significantly. I think it worth to do such changes :smirk:

**Comment by skudriashev** [comment]
@bolkedebruin, what about this one? :)

**Comment by bolkedebruin** [comment]
I don't like that it decreases the coverage. How come?

**Comment by skudriashev** [comment]
@bolkedebruin, because we use mocked interface now, so doesn't perform resetdb now in tests. But it does it for sure before each run.

**Pull request closed without merging**
