### PR TITLE
[AIRFLOW-XXX] Allow setting of keepalives_idle to enable PostgresHook to work with Amazon Redshift

### PR DESCRIPTION
**Pull request by apurvis**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- My PR does not have a JIRA.  I don't have a JIRA account to file the extremely problematic issue we came across when using Airflow with Amazon Redshift, so maybe this won't get merged, but maybe the next guy will find it with google.

### Description
- [x] When running long running queries in Amazon with `PostgresHook`, we had an interesting result.  Any query over 300 seconds would appear to Airflow as "hanging" for exactly 120 minutes, and then the task would fail.  So from the 5 minute mark to the 2 hour mark, stuff would just be stuck.

After a ton of testing and poking and prodding deep with the recesses of [the documentation of the `psycopg2` driver and `libpq-connect`](https://www.postgresql.org/docs/9.3/static/libpq-connect.html), we discovered the `keepalives_idle` setting.  When we set that to less than 300 seconds in the connection string, voila, victory.  We currently use 180 to play nice with redshift.

0, the default set here, means "use the system setting" (according to [the driver docs](https://www.postgresql.org/docs/9.3/static/libpq-connect.html))

### Tests
- [x] This does not require more tests because it is just adding a `libpq` option to the driver.  Cannot think of a way to test this.

### Commits
- [x] My commits do not JIRA issues in their subject lines. 
- [x] You can squash + merge.  I tried to squash into one commit and ended up with several.  oh well.
- [x] In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by saguziel** [comment]
Please fix your branch

**Comment by Fokko** [comment]
Can you squash your commits, rewrite the commit message according to the guidelines and rebase against master. Also the changes to the README needs to be in a separate PR.

**Comment by ghost** [comment]
Hey @apurvis don't be discouraged! This looks like an important change, just today someone had the same problem and was asking about it on Gitter and would really appreciate the PR being made ready for review & merging, so thanks for submitting it 👍 

You can sign up to the Jira without and permission or request. It's open https://issues.apache.org/jira/projects/AIRFLOW

What did you try when squashing gave you more commits? The top 2 answers here show good ways to do this. Using the soft reset method is probably simpler, in your case you want to get your local master up to date with this one,  then soft reset and redo your unstaged changes as a single commit, and then push it to your github fork again.  https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by bolkedebruin** [comment]
Will pick this up as it seems important for interoperability

**Comment by axrdb** [comment]
Running into an issue with PostgresToGoogleCloudStorageOperator that uses PostgresHook ... the issue is postgres_to_gcs_operator does not log anything after executing the sql and task is marked as failed ... here is the last line from the log but the task is marked as failed ...``` [2018-03-31 00:20:11,875] {base_task_runner.py:98} INFO - Subtask: [2018-03-31 00:20:11,875] {postgres_to_gcs_operator.py:118} INFO - SELECT c1, c2, c3 FROM t1 JOIN t2 AS cos ON lists.id = cos.c1 WHERE cos.c2 = TRUE AND c3 IS null ; ```

Here is how I am setting keepalives_idle as part of connection in Extra field ``` {"keepalives_idle":"180"} ```

I can run the same query from python command line using psycopg2 package. The query takes over 600 seconds to execute and returns successfully.

**Comment by ghost** [comment]
@axrdb Your issue doesn't sound related to this PR. This fixes an issue with Amazon Redshift timing out. Redshift is a fork of Postgres so shares the hook. 

Re your error, that SQL looks strange, you are using "lists.id" in a join, "lists" looks like a table alias which is not declared. Or is this an array type column? If so I wouldn't recommend joining to it, hard to index those, might explain why it is long running.

If you want to see more in the logging you can start Airflow with DEBUG level logging. I suggest trying a smaller, shorting running version of the query and checking that the connection to gcs is working. You can also check logs on Postgres. I find the pgadmin tool useful.

**Comment by axrdb** [comment]
@davoscollective the sql does work and data is successfully written on GCS after adding more filters that reduces number of rows returned with the query (since it makes the sql execute within 300 secs). The issue is only when the sql keeps running for more than ~300 secs

**Comment by ghost** [comment]
@axrdb OK so your issue is the `statement_timeout` setting, which can be set either on your Postgres server (not in Airflow) , in your sessions, and possibly with environment variables on the client. There are a few ways to change it.
https://www.postgresql.org/docs/current/static/config-setting.html
First is using postgresql.conf file setting in the data directory on Postgres server. If you don't have server access, or don't want to make a global setting that will affect all queries then don't use this.

You can also set it in your session using something like (in milliseconds)
`set statement_timeout to 100000`
You could add that at the beginning of your SQL query being passed in the `sql` parameter for the `PostgresToGoogleCloudStorageOperator` and see if that works. 

To set it as environment variable on the client:
https://dba.stackexchange.com/a/1376/10866
You could set that permanently on the Airflow server, probably a good option.


There is also an `options` parameter available in the psycopg python package that Airflow uses for connections to Postgres. `options` will pass through any of a range of command line parameters to Postgres. 
The syntax _would_ be something like this:
options='-c statement_timeout=100000'
Unfortunately the PostgresHook doesn't allow for this parameter. The only options are the ones in conn_args, and certain extra ones allowed in the conn.extra field, including keepalives_idle . see:
https://github.com/apache/incubator-airflow/blob/master/airflow/hooks/postgres_hook.py#L41

In the meantime, you could modify the hook to allow for `statement_timeout` in the conn.extra field. You could do it as a plugin for both the hook & operator, or fork, patch and contribute a pull request. I recommend creating a separate Jira ticket and issue for this, as it doesn't relate to this thread.
Allowing options could be useful for other parameters too, but of course your Postgres user would have to have appropriate permission to set them.

To be clear, keepalives_idle has nothing to do with your statement_timeout issue.

**Comment by axrdb** [comment]
Thank you. Let me look into setting it on the client side.

**Comment by prideloki** [comment]
@davoscollective hi, i also faced similar issue. i have a `SELECT` query that takes long to complete.

In my operator, i have these 2 lines.
```
cursor.execute("SET statement_timeout = 0") # turn off the statement_timeout
cursor.execute('SELECT a,b,c FROM foo')
```
but the task still fails after 300 seconds.

also already modify the hook to accept `keepalives_idle` still no luck.

**Comment by ghost** [comment]
As I mentioned in the previous comment, keepalives_idle is not the cause of this issue. The setting you want is statement_timeout its a completely different setting. This thread is not really the right forum for this, it needs a new Jira ticket. I've said that twice now so maybe I should do it.

In the meantime if you want to kludge it up I would try this:
Change your second cursor.execute to "SHOW statement_timeout" to see if the setting actually took effect, perhaps return it from the operator so you can see it in xcom. The cursor should be sharing the same session so using SET to change runtime parameters should be fine across multiple calls to cursor.execute


This SO question mentions it might be a timing thing. One hacky workaround suggested is to add a time.wait in python between the calls. A better solution is to add the option parameter to the psycopg.connect method inside the postgres hook, as I mentioned in the previous comment. Its pretty straight forward for you to copy the hook and operator into plugins and modify them then use them instead of the builtins, if you need that functionality urgently. 


https://stackoverflow.com/questions/32812463/setting-schema-for-all-queries-of-a-connection-in-psycopg2-getting-race-conditi

**Pull request closed without merging**
