### PR TITLE
Only run builds on "push" events for v* test branch

### PR DESCRIPTION
**Pull request by potiuk**
We do not need to run separate build on push and pull request when we are cherry-picking and pushing branch to apache/airflow repo. Those PRs are always made by committers, and they are done as direct push to the apache/airflow repo so they will run build on push (which will be equivalent of canary run). We also do not need to run anything on stable, because stable is the result of merging those changes from test after they get green.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
This one will avoid running two builds (one for push and one for pull_request) when we are working on *test branch.

**Comment by potiuk** [comment]
Another finding from 2.6.2 preparation

**Comment by potiuk** [comment]
This likely led to "permission error" when two builds at teh same time tried to push the same image in v2-6-test branch

**Comment by jedcunningham** [comment]
> We also do not need to run anything on stable, because stable is the result of merging those changes from test after they get green.

Doesn't the run on stable update constraint files though?

**Comment by potiuk** [comment]
> > We also do not need to run anything on stable, because stable is the result of merging those changes from test after they get green.
> 
> Doesn't the run on stable update constraint files though?

Glad you asked :) 

Nope. The "test" one updates constraints immediately if the test build succeeds. We do not need to defer updating constraints - this is only needed for PR  runs.

This is controlled by "canary-run" flag, which is set by "get-workflow-info":

```
    def is_canary_run(self) -> str:
        if (
            self.event_name == "push"
            and self.head_repo == "apache/airflow"
            and self.ref_name
            and (self.ref_name == "main" or TEST_BRANCH_MATCHER.match(self.ref_name))
        ):
            return "true"
        return "false"
````

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
