### PR TITLE
[KubernetesExecutor] Don't skip succeeded status

### LINKED ISSUE #40516: Sensors stuck in queued after being spot interrupted
### Apache Airflow Provider(s)

cncf-kubernetes

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==8.3.2
apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-http==4.12.0
apache-airflow-providers-postgres==5.11.2

### Apache Airflow version

2.9.2

### Operating System

Debian GNU/Linux 12 (bookworm)

### Deployment

Other Docker-based deployment

### Deployment details

We deploy Docker containers based on the official Airflow images (apache/airflow:slim-2.9.2-python3.11) to an AWS EKS kubernetes cluster running Kubernetes 1.29.

### What happened

When a sensor is stopped due to a spot interrupt, it can end up stuck in the `queued` state, never getting into the `running state. In the scheduler logs, this information is reported:

```
~(12 other attempts omitted)~
[2024-07-01 08:49:47,283] {base_executor.py:284} INFO - queued but still running; attempt=13 task=TaskInstanceKey(dag_id='test', task_id='python-sensor-1', run_id='scheduled__2024-06-30T00:00:00+00:00', try_number=1, map_index=-1)
[2024-07-01 08:49:48,316] {base_executor.py:287} ERROR - could not queue task TaskInstanceKey(dag_id='test', task_id='python-sensor-1', run_id='scheduled__2024-06-30T00:00:00+00:00', try_number=1, map_index=-1) (still running after 13 attempts)
```

Restarting the scheduler allows the sensors to recover and get into the `running` state again.

### What you think should happen instead

Sensors should be able to recover from a spot interrupt without needing to restart the scheduler.

I have tested multiple versions of the apache-airflow-providers-cncf-kubernetes provider, and this used to work correctly up until version 8.0.1. Starting from version 8.1.0, this has been broken (I've tested this on 8.1.0, 8.2.0, 8.3.1 and 8.3.2). This seems to be a regression.

### How to reproduce

I've used the following definition to test this behavior.
This will just start a number of Python sensors which will never succeed and keep running until timeout.

```
from airflow import DAG
from airflow.sensors.python import PythonSensor

with DAG(
    "test",
    schedule_interval="@daily",
    max_active_runs=1,
) as dag:
    for i in range(10):
        PythonSensor(
            task_id=f"python-sensor-{i}",
            mode="reschedule",
            timeout=timedelta(hours=6),
            poke_interval=timedelta(seconds=60),
            python_callable=lambda: time.sleep(1200)
        )
```

To trigger the behavior, one needs to spot interrupt the node where a sensor is running, but not the one where the scheduler is running. Restarting the scheduler allows the task to recover, so we want to only spot interrupt the task, while the scheduler stays healthy. You can look for a node matching these two constraints using k9s or kubectl, and then use the AWS console to initiate an interruption on the spot request for that node (can be done from the EC2 service).

### Anything else

By following the reproduction steps as described, I can trigger this issue every time.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### LINKED ISSUE #41436: Airflow scheduler misses success events of worker pods on kubernetes
### Apache Airflow version

2.9.3

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

We had several sensors that failed to be rescheduled by the scheduler because it still thought that the worker tasks were running.

The root cause was that the scheduler missed an update event from worker task because the Kubernetes node, where the Airflow worker pod was running on, got deleted soon after the worker finished successful. This does not follow the assumption in the code that a delete of the worker is only issued by Airflow itself. The wrong code is in `kubernetes_executor_utils.py`:

```
  if (
     event["type"] == "DELETED"
     or POD_EXECUTOR_DONE_KEY in pod.metadata.labels
     or pod.metadata.deletion_timestamp
  ):
    self.log.info(
        "Skipping event for Succeeded pod %s - event for this pod already sent to executor",
         pod_name,
    )
    return
```
In the logs we see only skipping event messages for the worker pods instead of first an event that was processed.
The comment of the if check say the following which is not necessarily true:
```
# We get multiple events once the pod hits a terminal state, and we only want to
# send it along to the scheduler once.
# If our event type is DELETED, we have the POD_EXECUTOR_DONE_KEY, or the pod has
# a deletion timestamp, we've already seen the initial Succeeded event and sent it
# along to the scheduler.
```

Our sensor failed such that it needed to be rescheduled and the task got requeued. 
At that time the scheduler never scheduled the task as it thought there was still one running and logged the following:

`{base_executor.py:284} INFO - queued but still running;`

The only way to fix it was to restart the scheduler as then the internal state of the scheduler was in sync with kubernetes.

### What you think should happen instead?

The fundamental problem is that the watcher for events on kubernetes pods skipped the successful event of the worker.

In order to make sure we process all events there are 2 options:
- remove the skipping of events as it is wrong in certain edge situations. I investigated when it was added and it was not really added for a reason, just as a behind the scene optimisation as far as I can tell. https://github.com/apache/airflow/pull/30872
- if you want to handle this reliably in Kubernetes you should use finalizers for your worker pods. This way you can guarantee that you do not miss any events and can use the finalizer to make sure you only process success events once. 

### How to reproduce

The issue is difficult to reproduce reliably. We do notice it on our huge production from time to time. 
It is however easy to see that the code is wrong in certain edge cases 

### Operating System

kubernetes: apache/airflow:slim-2.9.3-python3.11

### Versions of Apache Airflow Providers

apache-airflow-providers-cncf-kubernetes==8.0.1
apache-airflow-providers-common-io==1.3.2
apache-airflow-providers-common-sql==1.14.2
apache-airflow-providers-fab==1.2.2
apache-airflow-providers-ftp==3.10.0
apache-airflow-providers-http==4.12.0
apache-airflow-providers-imap==3.6.1
apache-airflow-providers-opsgenie==4.0.0
apache-airflow-providers-postgres==5.11.2
apache-airflow-providers-slack==7.3.2
apache-airflow-providers-smtp==1.7.1
apache-airflow-providers-sqlite==3.8.1

### Deployment

Other 3rd-party Helm chart

### Deployment details

Kubernetes deployment

### Anything else?

/

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by vlieven**
This PR implements the fix proposed in #41436 and guards against duplicated success messages by having `_change_state()` in the KubernetesExecutor only emit to the `event_buffer` if the task is in `self.running`,
as proposed by @jedcunningham in #40516.

closes: #40516, closes #41436

### CODE REVIEW

**Review by jedcunningham — COMMENTED** [review]
Thanks @vlieven.

Can you fix (or probably remove) the broken test, and add coverage for the early return?

**Comment by vlieven** [comment]
Sorry about that! I removed the broken test, and added another one to check that no event is emitted when the task key is not present in `running`.

**Review by jedcunningham — APPROVED** [review]

**Comment by RNHTTR** [comment]
@vlieven can you please resolve the merge conflicts?

**Comment by vlieven** [comment]
Hi @RNHTTR, I rebased the changes, should be good again now.
Could you point me to what is expected as backport PR?

**Comment by RNHTTR** [comment]
> Hi @RNHTTR, I rebased the changes, should be good again now. Could you point me to what is expected as backport PR?

I believe you just need to create a new branch against `v2-10-test` (not `main`), run `git cherry-pick <commit>` (you can find the commit ID in the PR where it says “merge commit <commit> into main”), and creating a new PR with thie new branch.

**Comment by RNHTTR** [comment]
> > > Hi @RNHTTR, I rebased the changes, should be good again now. Could you point me to what is expected as backport PR?
> > 
> > 
> > I believe you just need to create a new branch against `v2-10-test` (not `main`), run `git cherry-pick <commit>` (you can find the commit ID in the PR where it says “merge commit into main”), and creating a new PR with thie new branch.
> 
> Why? This is provider only change. PR is against main branch and that is how it should be.

Oh, duh, sorry about that.

**Review by RNHTTR — APPROVED** [review]

**Pull request merged**
