### PR TITLE
Refactor: Directly pass HttpOperator `data` and `json` arguments to requests and aiohttp params

### PR DESCRIPTION
**Pull request by goncalorazevedo**
related: #37291

Both `requests` and `aiohttp` deal with json and data arguments in the same 
manner (https://requests.readthedocs.io/en/latest/api/#requests.post and https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.request), so it would be more transparent to simply pass these arguments 
directly. I believe it is also a good choice to be transparent in this 
direct usage because requests is a very popular HTTP library so most 
people already know how these arguments are expected. 

The `params` argument could also be introduced in the HttpOperator with the same goal.

This PR was meant to address #37291 after seeing the discussion started here https://github.com/apache/airflow/pull/37293#discussion_r1529377720
The PR includes a breaking change.

### CODE REVIEW

**Comment by gazev** [comment]
@potiuk I opened the PR of this discussion https://github.com/apache/airflow/pull/37293#discussion_r1529377720 but hadn't realized you said a breaking change would not be ideal. What should I do with the PR? Thank you!

**Comment by potiuk** [comment]
Does the other PR fixes the same thing? If so - close it. If not - change yours to add new things. Why do you need to ask me :) ? Seems pretty straightforward?

**Comment by gazev** [comment]
> Does the other PR fixes the same thing? If so - close it. If not - change yours to add new things. Why do you need to ask me :) ? Seems pretty straightforward?

I am really sorry for the inconvenience, I hadn't realized the breaking change was implemented in the mentioned PR.

**Comment by potiuk** [comment]
No need to apologise :)

**Pull request closed without merging**
