### PR TITLE
[AIRFLOW-2498] Fix Unexpected argument in SFTP Sensor

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2498
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- The SFTP sensor is using SFTP hook and passing `sftp_conn_id` to `sftp_conn_id` parameter which doesn't exist. The solution would be to remove the parameter name, hence defaulting to first parameter which in this case would be `ftp_conn_id`

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
The failing test is unrelated:
```
======================================================================
18) ERROR: test_celery_integration (tests.executors.test_celery_executor.CeleryExecutorTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/executors/test_celery_executor.py line 34 in test_celery_integration
      with start_worker(app=app, logfile=sys.stdout, loglevel='debug'):
    /opt/python/2.7.14/lib/python2.7/contextlib.py line 17 in __enter__
      return self.gen.next()
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/contrib/testing/worker.py line 76 in start_worker
      **kwargs) as worker:
    /opt/python/2.7.14/lib/python2.7/contextlib.py line 17 in __enter__
      return self.gen.next()
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/contrib/testing/worker.py line 118 in _start_worker_thread
      **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/contrib/testing/worker.py line 33 in __init__
      super(TestWorkController, self).__init__(*args, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/worker/worker.py line 99 in __init__
      self.setup_instance(**self.prepare_args(**kwargs))
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/worker/worker.py line 122 in setup_instance
      self.should_use_eventloop() if use_eventloop is None
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/celery/worker/worker.py line 241 in should_use_eventloop
      self._conninfo.transport.implements.async and
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/kombu/transport/base.py line 125 in __getattr__
      raise AttributeError(key)
   AttributeError: async
```

Maybe rebase onto master?

**Comment by kaxil** [comment]
@Fokko The CI passes for all but one build and failes on an unrelated test

https://travis-ci.org/apache/incubator-airflow/builds/381851680

**Comment by kaxil** [comment]
@Fokko The CI passes all builds & tests here: https://travis-ci.org/kaxil/incubator-airflow/builds/381851640

**Comment by kaxil** [comment]
@Fokko PTAL when you have time. If you approve it I will merge it to the master.

**Review by Fokko — APPROVED** [review]
Yes, good one @kaxil 

For reference:
https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/hooks/sftp_hook.py#L42

**Pull request closed without merging**
