### PR TITLE
[AIRFLOW-6012] - performance improvement to end task result queue when k8 labels do not need scrubbing 

### PR DESCRIPTION
**Pull request by wyndhblb**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

For hundreds of tasks finishing, this is a very long process (lots of DB calls and a large loop).

We can make the loop exit quickly if we don't need to check for the label safety.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by XD-DENG — CHANGES_REQUESTED** [review]
The logic of your change seems incorrect to me.

Let's say the `dag_id`/`task_id` in your `labels` is "randomdag"/"randomtask", surely they will pass the check you added (`_make_safe_label_value("randomdag")` will return `"randomdag"`), and return directly. But this DAG/Task don't necessarily exist in DB.

Correct me if I'm wrong.

**Comment by wyndhblb** [comment]
Yes that is correct, and is the current behavior in the "main release" (1.10.6).

should https://github.com/apache/airflow/blob/master/airflow/executors/kubernetes_executor.py#L781
fail to find the pod/tasks in it's queue, the KeyError will trap it, and simply move on.

We have experienced ~20min speed up in general scheduling with this small change, having hundreds of tasks that complete every 10-15min makes that DB loop prohibitively expensive for every done task.

**Comment by ashb** [comment]
Please give this PR a more descriptive title - they form part of our changelog and this doesn't give enough info to say performance what/where.

> - [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
>   1. Subject is separated from body by a blank line
>   1. Subject is limited to 50 characters (not including Jira issue reference)
>   1. Subject does not end with a period
>   1. Subject uses the imperative mood ("add", not "adding")
>   1. Body wraps at 72 characters
>   1. Body explains "what" and "why", not "how"

**Comment by adityav** [comment]
possible duplicate of https://github.com/apache/airflow/pull/6340

**Comment by ashb** [comment]
Closing this in favour of #6340.

**Pull request closed without merging**
