### PR TITLE
Remove the Experimental tag for Pluggy

### LINKED ISSUE #34147: Update docs to mark Pluggy interface as stable rather than experimental
### What do you see as an issue?

[Pluggy interface has been listed as experimental](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/cluster-policies.html#:~:text=By%20using%20a,experimental%20feature.) since Airflow 2.6.  Requesting it be listed as stable

### Solving the problem

Change the documentation to say it is now stable

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by TheCodyRich**
Removed experimental tag from Pluggy interface. Resolves #34147

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
> I've just wondering should Vote or at least [Lazy Consensus](https://community.apache.org/committers/lazyConsensus.html#stating-lazy-consensus) created in [dev-list](https://airflow.apache.org/community/)?

Yeah. Lazy consensus should be enough.

**Comment by TheCodyRich** [comment]
Sent a Lazy Consensus, will wait for responses

**Comment by eladkal** [comment]
I think we want a newsfragment for this one.
Moving feature from experimental to full support is something that we should mention as headline in the changelog and not just as line in the misc section.

**Comment by eladkal** [comment]
For visibility mailing list thread:
[[LAZY CONSENSUS] - Removing the Experimental tag for Pluggy](https://lists.apache.org/thread/8s5vlmh7khsx88l09jsyq9px77d47mdv)

(Original[ Mailing list thread](https://lists.apache.org/thread/9lc7jy8o7k6xr9x9ss6h5s5w3ym3jhdg) which was renamed due to title)

**Review by Lee-W — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
