### PR TITLE
Adding functionality to shuffle HMS connections to facilitate load balancing

### PR DESCRIPTION
**Pull request by vanka56**
Adding functionality to shuffle HMS connections that way the requests to hms servers are load balanced.

Existing logic picks the first connection out of all connections pertaining to a specific conn_id and uses it for for all requests that is sent via HiveMetastoreHook. This code change shuffles the connections and make sure same HMS connection / server is not used all the time HiveMetastoreHook is instantiated. This is done by shuffling the hms connections

---
Make sure to mark the boxes below before creating PR: [x]

- [ X] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [ X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by vanka56** [comment]
Checked all the boxes

**Comment by ashb** [comment]
This one is I'm afraid a "won't fix", at least for 2.0 because of https://github.com/apache/airflow/issues/8608

If you re-target this to v1-10-stble we could include it in 1.10.11 though.

**Comment by Acehaidrey** [comment]
Think we can close this ticket and just merge in https://github.com/apache/airflow/issues/8608
What do you think @ashb ?

**Comment by ashb** [comment]
Closing in favour of #9280

**Pull request closed without merging**
