### PR TITLE
Add DAG permissions based on DAG tags

### LINKED ISSUE #9342: RBAC access rights filtering by dag tags
**Description**

Is there a way to auto generate permissions based on tags?

e.g.
I want to automatically grant access to user based on his role to a specific list of tags

currently only the can dag read on <dag name> and can dag write on <dag name> is auto populated when there is a new dag

it would be good if i can do something like `can dag read on tag <tag name>` and `can dag write on tag <tag name>`

thanks in advance!

**Use case / motivation**

I have multiple teams using the same airflow server and access rights granting has been very tedious as it is currently done by adding individual dags manually to the access rights of each team

**Related Issues**

https://github.com/apache/airflow/pull/6489#issuecomment-643951458

### PR DESCRIPTION
**Pull request by zacharya19**
Closes #9342, a new feature that allow to add read/write access for dags based on the tags, which will be make it easier to control "group" access.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by zacharya19** [comment]
Going to ignore the tests for now - they passed and all I did was change the commit message and they're failing on something that looks like connection error on the CI, not a real test issues.
Once this PR is approved I'll rebase from master.

**Comment by zacharya19** [comment]
@ashb @kaxil LMK what you guys think, I would love to so it in the next version.

**Comment by ashb** [comment]
cc @jhtimmins Who is working on an overhaul of the permissions modelling/names for the UI in https://github.com/apache/airflow/pull/11362

@zacharya19 I think we might ask you to hold off on this until that PR is merged at least.

**Comment by zacharya19** [comment]
> cc @jhtimmins Who is working on an overhaul of the permissions modelling/names for the UI in #11362
> 
> @zacharya19 I think we might ask you to hold off on this until that PR is merged at least.

@ashb I see this PR got merged, should I start working on building my code on top of it or there is another PR I would wait for?

**Comment by kaxil** [comment]
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

**Comment by zacharya19** [comment]
> Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.
> 
> It will help if your squash your commits into single commit first so that there are less conflicts.

Done, also refactored the code to be compatible with #11362.

**Comment by kaxil** [comment]
@jhtimmins Can you take a look at this please?

**Comment by zhaitin-quotient** [comment]
Fixed the conflicts.
@kaxil @jhtimmins Any thoughts?

**Comment by zacharya19** [comment]
Fixed the conflicts.
@kaxil @jhtimmins Any thoughts?

**Comment by kaxil** [comment]
ping @jhtimmins

**Comment by jhtimmins** [comment]
@zacharya19 @kaxil @ashb 

At a high-level I like the idea of tying permissions to DAG tags, however this presents two issues.

1. This would allow anyone with the User role to give DAG access to anyone else. Currently, you need to be an Admin user to give DAG access to someone else. But with this change, if a user is able to edit a DAG (which the User role permits), they are able to add arbitrary DAG tags. This allows them to give permissions to other users.

2. Dag-level permissions were hacked into the existing permission design, which we attempted to clean up with the `DAG:` prefix. It was a step in the right direction, but was a less than ideal solution. I'm somewhat hesitant to go further down the path of creating special classes of permissions via prefix strings. Creating a more robust permission design to better handle flexible permissions such as this may not be warranted, but I think we should consider the pros/cons of adding to the hack. I'm happy to defer to Ash and Kaxil.

**Comment by zacharya19** [comment]
> @zacharya19 @kaxil @ashb
> 
> At a high-level I like the idea of tying permissions to DAG tags, however this presents two issues.
> 
> 1. This would allow anyone with the User role to give DAG access to anyone else. Currently, you need to be an Admin user to give DAG access to someone else. But with this change, if a user is able to edit a DAG (which the User role permits), they are able to add arbitrary DAG tags. This allows them to give permissions to other users.
> 2. Dag-level permissions were hacked into the existing permission design, which we attempted to clean up with the `DAG:` prefix. It was a step in the right direction, but was a less than ideal solution. I'm somewhat hesitant to go further down the path of creating special classes of permissions via prefix strings. Creating a more robust permission design to better handle flexible permissions such as this may not be warranted, but I think we should consider the pros/cons of adding to the hack. I'm happy to defer to Ash and Kaxil.

1. Maybe I'm missing something, but the only way to add tags to a dag is by editing the code directly which requires access to the machine itself, so even without it the user can simply extract the DB info and edit permissions if they have access to the machine.
2. I get your point, you're probably right but I feel that tags and the ability to add permissions based on them is a must for big companies that want to use Airflow, so IMHO adding this hack and open a task to redesign the permission system would be the right thing to do, I think that doing that redesign now is a big task and can make this feature wait for a few months.

@kaxil @ashb What do you guys think? I'm OK with either way, I can probably take the redesign task on myself.

**Comment by JavierLopezT** [comment]
Any update on this?

**Comment by jhtimmins** [comment]
@zacharya19 Apologies for the delay.

1. This will depend on your deployment setup. If your team uses automated deployments it's very possible that a user could have merge access that will allow a DAG to get added/modified without having access to the DB. Perhaps more importantly, allowing a code-level change to modify permissions is a relatively deep coupling between two separate systems, which presents additional issues. For example, allowing tags to control access means that any time someone does a code review of a DAG change, they'll need to check the associated users with access to the associated tags, then confirm with a manager/admin user that those users are permitted to access that DAG. Now admin-level app management is tied to code deployments.

2. It seems like most of the issues you described can be solved with custom roles. Since users can have multiple roles, could you not create custom roles that have access to edit/read the appropriate DAGs. Then a user that works for the internal tools team, for example, could have the roles `Viewer` and `InternalTools`. Whenever the internal tools team adds a new DAG, it's relatively simple to add that new DAG to the `InternalTools` role. 

@JavierLopezT I'm interested in your thoughts for #2 as well.

**Comment by zacharya19** [comment]
@jhtimmins

1. I get your point, but this is true even without this feature, a user can always write code inside the dag to change permission or access the DB through it.

Anyway, I guess this is not an impl that you guys like, do you have another proposal?

**Comment by Deathblade6** [comment]
@zacharya19 This is actually a great feature that I need, which i honestly thought already existed in Airflow. Just commenting so that this PR turns into a reality.

**Comment by kaxil** [comment]
Temporarily added it to 2.1 Milestone to revisit this at a later time.

Assigning permissions to a group of DAGs is a good future -- I am not yet sure if "Tags" are the best way for it for the reason James already mentioned. Probably better would be some sort of "wildcard" on permissions -- not sure at the moment.

**Comment by kaxil** [comment]
Moving the conversation to the Issue instead of this PR

**Comment by good92** [comment]
May be adding the role in the DAG would be better.

**Pull request closed without merging**
