### PR TITLE
Better behaviour for self-update of Breeze

### PR DESCRIPTION
**Pull request by potiuk**
Breeze self-upgrade behaved somewhat erratically:

1) when executed manually as `self-upgrade` it printed "repaat the
   command" - which made no sense

2) whe triggered as part of an environment check (i.e. when breeze
   version was different or installed from another workspaece) it
   upgraded - and also printed "repeat the command" - which made
   more sense but added a need to repeat the command.

3) It asked the user to make the decision - but since reinstallation
   is not very intrusive (just few seonds delay) it makes little sense
   as reinstalling breeze would usually take less time than making
   decision

This change fixes it for both cases:

1) there is no "repat the command" when you run self-upgrade command
2) when self-upgrade is triggered as part of another command, the
   original command is automatically re-run (with execvl - so
   replacing previous process) after the self-upgrde completed.
3) reinstalling breeze happens automatically in both cases without
   asking the user.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
CC: @blag  - you might be interested, but I think this one will improve the Breeze experience when there are multiple workspaces.  Still upgrading, but it will automatically re-install and re-run Breeze if it is installed from different folder or with older dependencies.

I think that maybe (following some of your earlier comment) we should simple force-reinstall breeze in all those cases? 

I see no big problem with that, especially that this should be a) rather rare case b) rather fast (usually reinstalling breeze takes just couple of seconds).

This will avoid asking qeustion and timeout (which you had complained about before. I'd love to hear what you think.

**Comment by potiuk** [comment]
Yeah. I think that in case of breeze reinstallation, just reinstalling without asking makes much more sense.

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
Comment. I just cherry-picked it to v2-3-test and it works really nice. 

The reinstallation takes usually less than a second or two (once you installed it in the past) and you almost do not experience it and it gets as close as it can to the case which I think we all wanted @blag @o-nikolas (myself including) where you pretty much always run the version of breeze which is tied to the branch and workspace you are in.

It gets reinstalled (so it is kinda against what the old breeze approach was and is something that @blag complained about), but it's almost unnoticeable and you get the same final behavior eventually (every 'serious' breeze operation except --help and autocomplete runs using the "current" version of breeze in the sources), while we also keep the nice property that @uranusjr advocated for with `pipx` nicely handling installation, upgrade, windows environment, click autocomplete working without any venv activated etc..

Due to cherry-picking and some old branch testing I often switch between workspaces and branches and the previous approach was a bit annoying, while the new one is really smooth. 

Seems like a really good `middle-ground` implementation - not very obvious but kinda 'best of all worlds` with the current set of tools we have available now.

**Comment by potiuk** [comment]
cc: @rossturk  -> you might also take a look. We've been discussing about re-recording breeze videos soon, and I think this is a nice `power-user` feature of breeze. It will now work very smoothly and nicely regardless how many workspaces with airflow you have and which branches/versions you have, always the right version of breeze will be used for the version you currently work on :)

**Comment by blag** [comment]
@potiuk I totally missed your at-mentions in this thread until now, apologies!

While I still have my reservations about Breeze, this will make my QOL much better with it, thank you. 😄

**Pull request merged**
