### PR TITLE
Run docker containers

### PR DESCRIPTION
**Pull request by wndhydrnt**
This PR adds support for running docker containers by adding a
`DockerOperator`.

Besides starting a container, the implementation supports pulling
images, limiting resources, mounting volumes, setting the network
mode and authenticating via TLS.

### CODE REVIEW

**Comment by wndhydrnt** [comment]
@bolkedebruin Good idea, I've added the parameter `tmp_dir`.

**Comment by pedrorjbr** [comment]
I made a pull request to execute docker container on ECS AWS:
https://github.com/airbnb/airflow/pull/652

**Comment by wndhydrnt** [comment]
@mistercrunch Seeing #756, I can easily add tests for this. It can be done using `mock` to mock `docker.Client` or testing against a running instance of the Docker daemon. What is the preferred way for airflow?

**Comment by bolkedebruin** [comment]
@wndhydrnt @mistercrunch to chime in on your question: travis does not allow docker-in-docker at the moment so my suggestion would be to use mock. Using travis' VMs (by using sudo: required) would significantly slow down the testing speed for a non core feature.

**Comment by wndhydrnt** [comment]
@mistercrunch @bolkedebruin I've added tests using `mock`. Hope that's fine. PTAL

**Comment by bolkedebruin** [comment]
:+1:

**Comment by bolkedebruin** [comment]
@mistercrunch can this be added? seems like a nice addition?

**Comment by asnir** [comment]
How to transfer data between containers? In order to simplify things, let’s say that we have 2 containers (c1 & c2) operating one after another, while c2 uses c1’s output. 

What do you think should be the best practice at this case? 
The solution might be different if c2 is communicating via rest API and/ or it’s a sealed app.

Couple of possible solutions might be:
•	Using volumes (for example tmp_dir parameter).
•	A new operator based one this one, which will left up the container and execute another basic_operator.

**Comment by asnir** [comment]
How to transfer data between containers? In order to simplify things, let’s say that we have 2 containers (c1 & c2) operating one after another, while c2 uses c1’s output. 

What do you think should be the best practice at this case? 
The solution might be different if c2 is communicating via rest API and/ or it’s a sealed app.

Couple of possible solutions might be:
•	Using volumes (for example tmp_dir parameter).
•	A new operator based one this one, which will run the container and execute another command let’s say basic operator.

**Comment by wndhydrnt** [comment]
@asnir I would go for some kind of storage outside of the Docker container, like HDFS or S3.

**Comment by bolkedebruin** [comment]
This was superseded by #882

**Pull request closed without merging**
