### PR TITLE
fix imports sort

### PR DESCRIPTION
**Pull request by timqsh**
Found wrong imports sorting during isort integrations testing :)

### CODE REVIEW

**Review by ashb — CHANGES_REQUESTED** [review]
Change is good, but if you are making this change can you also enable isort for these files in setup.cfg and .pre-commit-config.yaml please?

**Comment by timqsh** [comment]
It looks like `skip_glob` flag of isort is confusing. It doesn't work with * and ** like real glob, but rather just treats * like .* in regexp.

I made skips in setup.cfg consistent with pre-commit.

**Comment by timqsh** [comment]
rebased on current master

**Comment by kaxil** [comment]
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

**Comment by timqsh** [comment]
I looked into changes in the new master. It looks like this fix is no longer needed 🙂

**Pull request closed without merging**
