### PR TITLE
Helm chart upgrade ci

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@ephraimbuddy - running it here. There are few small things I corrected (let's see if it helps):

* I moved the common functions to _parallel.sh (and prefixed with `parallell::`)
* I renamed the common functions to *_helm_*
* I added the `>"${JOB_LOG}" 2>&1` redirection (that was the actual culprit for the failure you had - the output was simply printed directly to stdout for parallel jobs, rather than redirected to a separate log per parallell job. So when we tried to print the output after all jobs were finished, the JOB_LOG file was missing (and then it failed).

**Comment by ephraimbuddy** [comment]
> @ephraimbuddy - running it here. There are few small things I corrected (let's see if it helps):
> 
> * I moved the common functions to _parallel.sh (and prefixed with `parallell::`)
> * I renamed the common functions to __helm__
> * I added the `>"${JOB_LOG}" 2>&1` redirection (that was the actual culprit for the failure you had - the output was simply printed directly to stdout for parallel jobs, rather than redirected to a separate log per parallell job. So when we tried to print the output after all jobs were finished, the JOB_LOG file was missing (and then it failed).

Cool!

**Comment by potiuk** [comment]
one more fix @ephraimbuddy :) - > the problem was that when we moved the function, scripts relative location changed and I had to change it to make it a "full" script path ( `"${AIRFLOW_SOURCES}/scripts/ci/kubernetes/${single_job_filename}"`). It was `"$(dirname "${BASH_SOURCE[0]}")/${single_job_filename}"`. I also added some better diagnostics in similar situations to make it more obvious what happened.

**Comment by potiuk** [comment]
Ha @ephraimbuddy ! I think I finally got it 🎉

**Comment by potiuk** [comment]
Yep. It works :)

**Comment by ephraimbuddy** [comment]
> Ha @ephraimbuddy ! I think I finally got it 🎉

Wonderful!!!

**Review by ephraimbuddy — APPROVED** [review]

**Pull request merged**
