### PR TITLE
Restructure Docs 

### PR DESCRIPTION
**Pull request by TohnJhomas**
This PR is designed to restructure the overcrowded and confusing sidebar of the Astronomer Documentation. This is intended to allow for further scalability of the airflow docs, and to increase user-friendliness to new users. 

The current docs have 28 top-level pages and two sub-sections of substance: "How-to Guides" and "Concepts."  Here I've attempted to clean up the sidebar and make the structure more clear by both splitting "Concepts" into three new top-level pages ("Core Concepts," "Authoring and Scheduling" and "Administration and Deployment") and folding many of the current top-level pages into these categories. 

The structure of the docs as they currently are is visually here: The left column is representative of the top-level sidebar, with the concepts subsection broken out to the right. How-to guides is another large section, but because it didn't undergo any substantial change I've hidden the sub-pages for ease of understanding.

Screen Shot 2022-10-24 at 1 12 51 PM

The structure of the refactored docs is below, with the same format as above: 

Screen Shot 2022-10-24 at 1 12 41 PM

 ---

### CODE REVIEW

**Comment by TohnJhomas** [comment]
This version has known issues with cross-provider label referencing

**Comment by uranusjr** [comment]
Thanks for taking the time to do this! The new structure makes much more sense to me.

**Comment by potiuk** [comment]
Conflicts to resolve I am avraid :( . Emotions are the same :)

**Comment by potiuk** [comment]
Would be great also if you generate the docs `breeze build-docs` and share some screenshots.

**Comment by BasPH** [comment]
Looking forward to this much-needed change! 👍

**Comment by potiuk** [comment]
> Looking forward to this much-needed change! 👍

Likewise.

**Comment by mik-laj** [comment]
Can you also update [the `redirects.txt` file](https://github.com/apache/airflow/blob/main/docs/apache-airflow/redirects.txt)?  It is essential for Google to be able to find the new page locations and also for users to be properly redirected when they change Apache Airflow versions in the documentation.

**Comment by TohnJhomas** [comment]
Yeah - just pointing all the old locations at their new locations?

**Comment by mik-laj** [comment]
@TohnJhomas  Yes. Exactly.

**Comment by dstandish** [comment]
has conflicts

**Comment by BasPH** [comment]
@TohnJhomas I'd love to see this PR merged, any chance you could resolve the conflicts?

**Comment by potiuk** [comment]
> @TohnJhomas I'd love to see this PR merged, any chance you could resolve the conflicts?

Oh yeah. I would very, very much love that too. Maybe you need some help @TohnJhomas ? I am happy to spend some time on helping to solve issue with docs building (I know it is a very daunting thing to fight with Sphinx. The way the tags etc. are defined are rather non-intuitive and there are many, many traps you can fall in.

**Comment by TohnJhomas** [comment]
@potiuk / @BasPH Honestly - I got a little stuck working on some of the sphynx roles. I'm getting redirects.txt and the merge conflicts fixed today and everything pushed up to date. a few broken links to/from KubernetesPodOperator probably shouldn't hold everything else up

**Comment by potiuk** [comment]
Approved the workflow to see if it works :)

**Comment by potiuk** [comment]
Approved workflow again :)

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

Let me merge it quickly before there are any conflicts


🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Pull request merged**
