### PR TITLE
[AIRFLOW-4995] Fix DB initialisation on MySQL

### PR DESCRIPTION
**Pull request by pemontto**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [AIRFLOW-4995](https://issues.apache.org/jira/projects/AIRFLOW/issues/AIRFLOW-4995) issues and references them in the PR title.

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
Airflow fails to initialise MySQL as a backend due to some check constraints.
```
An expression of non-boolean type specified to a check constraint 'kube_resource_version_one_row_id'
```
This change simply includes mysql along with mssql in the conditional check for support.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: This line is already covered.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
I did some check on that and I think there is a better solution (see JIRA for details). 

Seems that if we have separate  "if mysql" clause and we have "one_row_id<>0" - it should work also for mysql 8.0.16 that introduced support for CHECKs.

**Review by potiuk — CHANGES_REQUESTED** [review]
Accidental approve :(

**Comment by potiuk** [comment]
Hey @ashb. I think this one is important for 1.10.4.

I believe we are going to have another RC for 1.10.4 (I guess?) - then it's worth that this one is merged (possibly after my proposal with <> 0 works for @pemontto and he can double-check this with their MySql DB).

It seems like airflow 1.10.3 and previous ones with Kubernetes will not cleanly install on the latest Mysql 8.0.16 because of this BOOL Check constraint. If we have not yet made decision about 1.10.4 RC - this might be quite important issue to be added to 1.10.4 - so that people will have a stable Airflow version that they can use with latest MySQL. See my comment here: https://issues.apache.org/jira/browse/AIRFLOW-4995?focusedCommentId=16889502&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16889502

**Comment by pemontto** [comment]
@potiuk thanks for the help. Confirming the clause you provided works great 👍

**Review by potiuk — APPROVED** [review]

**Pull request merged**
