### PR TITLE
[AIRFLOW-2140] Don't require kubernetes for the SparkSubmit hook

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2140

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes: Don't require k8s client libs for spark hook.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Tested manually in my install

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you verify other hooks / operators as well?

**Comment by ashb** [comment]
Confirmed, no other occurances in hooks, and airflow/contrib/operators/kubernetes_pod_operator.py loads via `airflow.contrib.kubernetes` already.

Yes, doing via a.c.k8s makes sense actually. Will change over.

**Comment by ashb** [comment]
@bolkedebruin Updated as you suggested

**Comment by bolkedebruin** [comment]
@kaxil @Fokko what do you guys think?

**Review by kaxil — APPROVED** [review]
LGTM. I have restarted the errored test on Travis and it looks to pass all the tests now. 

A personal choice is to rename `has_kubernetes` to `kubernetes_lib_imported`. However, that ss just a personal preference so not that important. 😃

**Review by Fokko — APPROVED** [review]
LGTM, Thanks for picking this up.

I still think we should have a more generic solution for this kubernetes dependency. It is also a problem with the examples, and there hasn't been a very nice solution (yet).

We could also do a local import: https://github.com/ashb/incubator-airflow/blob/809a8a7f11e376cc4f863910e9360868348a9da1/airflow/contrib/hooks/spark_submit_hook.py#L555

Then we don't need the import try/except logic. What are your thoughts on this?

**Comment by ashb** [comment]
I thought about a local import, but thought that getting told about the error as soon as possible would be better, rather than when it delaying it to _just_ when the on_kill handler was run.

**Comment by tooptoop4** [comment]
k8s is once again mandatory for spark submit, raised AIRFLOW-5406

**Pull request merged**
