### PR TITLE
[AIRFLOW-2659] Improve Robustness of Operators in Airflow during Infra Outages

### PR DESCRIPTION
**Pull request by afernandez**
### JIRA
- [x] My PR addresses the following: [AIRFLOW-2659](https://issues.apache.org/jira/browse/AIRFLOW-2659)

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

**Problem:**
If an infrastructure outage occurs on the Hadoop cluster, tasks that rely on those services will fail in Airflow, thereby causing SLA misses and deteriorating user confidence in Airflow (even if the outage was in another system). Only a fraction of tasks and DAGs have retries around certain operators/hooks and the retry attempts are not sufficient during an outage.

**Goal:** Automatically retry failures that occur due to infrastructure issues.

**High-level design:**

- Retry decorator in the Hooks for easy annotation
- Retry logic will be time-based (initial delay, max delay time, retry window, etc.)
- Allow each Hook to determine the root-cause of the error (user, infra outage)
- User-errors will be handled the way they are today.
- Infra-errors will be able to retry for extended periods of time.
- Configurable (optional, configurable per Hook)
- Emit metrics using StatsD

See more detailed design doc in https://issues.apache.org/jira/secure/attachment/12928793/AIRFLOW_2659.pdf

### Tests
- [x] Unit tests passed
screen shot 2018-07-02 at 4 03 40 pm

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
screen shot 2018-06-29 at 5 47 24 pm

### CODE REVIEW

**Comment by afernandez** [comment]
@mistercrunch @bolkedebruin @saguziel @yrqls21 
Would you be able to take a look at this PR?
Thank you

**Comment by Fokko** [comment]
This is also in Airflow itself. If an operator fail, it will be retried within a certain time period (up for retry state). Why not extend this logic instead of writing another wrapper around the operator.

**Comment by afernandez** [comment]
@Fokko My apologies for replying 2 months later (I was working on other high priority projects and now returning to work on Airflow). 
Good question, the primary reason being that the retries in Airflow are mainly meant to handle transient errors where 3-5 retries suffice (or maybe 5 min window). This PR tries to address a larger infrastructure outage that can last several hours.

A user may have a legitimate case for only retrying 3 times (say a particular service is flaky at really high load).  Having shorter retries for transient errors ensures enough robustness for flaky services but not high enough that they completely mask unreliable services.

The solution I'm proposing tries to be more intelligent by applying business logic to the particular hook.
If it's indeed a transient-error, then retry according to the existing Airflow logic, but if it's a complete infrastructure outage, then perhaps retry for 2-4 hours. Luckily, services like Hive, Presto, Spark, etc., can provide enough context to make this determination.

**Comment by Fokko** [comment]
Wouldn't it be preferable to design the operator in such a way, that it will pick it up again automagically. Now we add additional configuration etc, which increases the complexity of Airflow and the specific operators. Would it be possible to integrate this in the operator itself?

**Pull request closed without merging**
