### PR TITLE
Create CustomJob and Datasets operators for Vertex AI service

### PR DESCRIPTION
**Pull request by MaksYermak**
This PR fixes problems with mypy checker which were in this PR https://github.com/apache/airflow/pull/20077 .

Co-authored-by: Wojciech Januszek januszek@google.com
Co-authored-by: Lukasz Wyszomirski wyszomirski@google.com
Co-authored-by: Maksim Yermakou maksimy@google.com

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by jedcunningham** [comment]
@MaksYermak, can you rebase on main? I think the failures you are seeing here have been fixed now.

**Comment by MaksYermak** [comment]
> @MaksYermak, can you rebase on main? I think the failures you are seeing here have been fixed now.

@jedcunningham I have done it

**Comment by lwyszomi** [comment]
@potiuk @jedcunningham Can we merge these operators if all is green?

**Review by potiuk — APPROVED** [review]
It's been already reviewed and merged - this one is just after MyPy fixes. LGTM. Merging

**Pull request merged**
