### PR TITLE
[AIRFLOW-XXX] 1-setup-env.sh should only run in docker

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

`1-setup-env.sh` should only be ran inside the docker container as it override files.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Modified the CI bash script should not need unit test I guess?

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by milton0825** [comment]
@ashb

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
It's really good idea. I've added very similar solution to my WIP PR for multi-staging. The nice thing there is that the image to run CI is part of airflow itself and we already had a few ENV variables defined that we could use.

https://github.com/apache/airflow/pull/4938  (but I added it in all scripts that are run in the container - there are a few places to add it:  https://github.com/apache/airflow/pull/4938/commits/9a9489948a5addb5952549ca5a6beda9e30eb629#diff-9cf9f4241b4e721774c938abb1c6c103R25

**Comment by feng-tao** [comment]
lgtm

**Comment by milton0825** [comment]
tests passed in: https://travis-ci.org/milton0825/airflow/builds/513064124

**Pull request merged**
