### PR TITLE
google: move bigquery openlineage imports inside methods

### LINKED ISSUE #40043: google providers 10.19.0 bigquery operators directly depends on openlineage package
### Apache Airflow Provider(s)

google

### Versions of Apache Airflow Providers

10.19.0

### Apache Airflow version

2.7.0+

### Operating System

linux

### Deployment

Google Cloud Composer

### Deployment details

_No response_

### What happened

[pull/39614](https://github.com/apache/airflow/pull/39614) refactored `_BigQueryOpenLineageMixin` and now `bigquery` operators directly import from `openlineage` package, even when Open Lineage provider is not installed, so importing any BigQuery operator fails with `ImportError`

I can create the PR to fix it

### What you think should happen instead

Imports should happen lazily, only when `get_openlineage_facets_on_complete` is called.

### How to reproduce

Install Google Providers package 10.19.0 without `openlineage` package installed

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ahidalgob**
closes: #40043

In the latest google providers version (10.19.0), importing `bigquery` operators results in importing the `openlineage` package even when the openlineage provider is not installed. 

This refactors the code so all imports to the `openlineage` package happen only inside `get_openlineage_facets_on_*` again.

https://github.com/apache/airflow/pull/39614 moved the mixin to `openlineage/utils.py` and this brings it back to `operators/bigquery.py` to keep the top-level `openlineage` imports in `utils.py`, and even worse because the mixin is now bulkier thank before. Another option would be to move `BigQueryJobRunFacet` and `BigQueryErrorRunFacet` to another file, and move all `openlineage` top-level imports in `utils.py` inside methods. Open to suggestions.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by VladaZakharova — APPROVED** [review]
LGTM
Great job!

**Comment by JDarDagran** [comment]
Would be more feasible to keep the code in the separate module as it is and move OL imports from top-level to local imports?

**Comment by JDarDagran** [comment]
How about having mixin only in, let's say, `airflow/providers/google/cloud/openlineage/mixins.py`, in which all imports are local?
I can attempt to fix it in another PR or leave it up to you in this one.

**Comment by ahidalgob** [comment]
sounds good to me, I will make the changes in this PR

**Review by potiuk — APPROVED** [review]

**Pull request merged**
