### PR TITLE
[AIRFLOW-XXX] Fix Minor issues with Azure Cosmos Operator

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
- Fixed Documentation in integration.rst
- Fixed Incorrect type in docstring of `AzureCosmosInsertDocumentOperator`
- Added the Hook, Sensor and Operator in code.rst
- Updated the name of example DAG and its filename to follow the convention

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
thanks @kaxil, cc @tmiller-msft , btw, I can't close others jira with my current account, do I need to file any specific request to apache for that?

**Comment by kaxil** [comment]
@feng-tao You should have the permission. Can you give it a try on https://issues.apache.org/jira/browse/AIRFLOW-3408 . Click on **Resolve Issue**

**Comment by feng-tao** [comment]
screen shot 2018-12-06 at 12 41 03 pm

This is what I see for a jira filed/assigned by others.

**Comment by kaxil** [comment]
@feng-tao Hmm.. that is strange. Raise a ticket with Apache-Infra to give you permissions to Resolve Issues

**Comment by kaxil** [comment]
@feng-tao Can you review this one - has minor changes :-)

**Comment by feng-tao** [comment]
lgtm

**Pull request merged**
