### PR TITLE
[WIP][AIRFLOW-594] Add dag source plugin hooks

### PR DESCRIPTION
**Pull request by drewsonne**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-594\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-594
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-594\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

  This PR is a precursor to loading DAGs from pip packages. It provides a new plugin structure, `AirflowPluginDagSource` with two methods `collect_dags_from_plugins` and `put_dag_plugins_on_disk` where a Plugin author can:
 -  implement the former and provide logic to inject the `airflow.model.DAG` objects into a provided `airflow.modal.DagBag` object using their own custom logic,
 - or implement the latter and provide logic to write the dag python files to disk in the dag folder where they will be collected by the normal DAG loading setup.

From discussion below, potential use cases could be:
 - to load dags from pip packages
 - to load dags from (for example) S3, GCP Cloud Storage, Azure Blob Storage (using the built in hooks/connections);
 - integration with say, https://github.com/wooga/airconditioner without mixing yaml and python for dag definitions;
 - tighter integration with https://github.com/python-bonobo/bonobo
 - as an intermediary step to handle some automatic lineage injection on DAG load
 - perform some validation or linting of DAGs before loading.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by drewsonne** [comment]
I renamed the branch in my repo, which meant I accidently closed the old PR which was here. https://github.com/apache/airflow/pull/4531

**Comment by KevinYang21** [comment]
This sounds like a great addition to Airflow. Just wondering what's the relationship between this and [AIP-5](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher)?

**Comment by milton0825** [comment]
Can you take a look at [AIP-5](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher)? In short, it defines a remote DAG fetcher that fetches DAGs from remote sources such as `git`, `s3` and cache it locally. I think we probably need to consolidate the fetcher abstraction somehow.

**Comment by drewsonne** [comment]
@KevinYang21 @milton0825 The relationship between AIP-5 and this would be that this PR provides a framework to implement AIP-5 on top of. The intention of this PR is to build plugin hooks to allow users to write pip packaged packages which can provide DAG loading functionality without modifying the airflow core repo.

I'm still actively working on this, but due to the large scale of the Airflow development environment and the long turnaround time in running tests, it's slow going. Any help on this PR is much welcomed.

**Comment by milton0825** [comment]
It seems like we only load DAGs from plugin during start up time while [AIP-5](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher) proposed that the airflow services periodically fetch DAGs from remote sources during runtime.

**Comment by milton0825** [comment]
I feel like we can have a common `BaseDagFetcher` class that fetch DAGs from remote and persist to local filesystem and `put_dag_plugins_on_disk` can use it.

**Comment by ashb** [comment]
Dag fetcher is a whole different issue, but if we do add that I'd rather we tied it in to Airflow more deeply and didn't *need* files on disk at all!

**Comment by milton0825** [comment]
@ashb do you mind taking a look at [AIP-5](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher) and leave your feedback there?

**Comment by KevinYang21** [comment]
Personally I would prefer to put such logic inside core Airflow instead of as a plugin. This doesn't look like a framework that AIP-5 can be implemented on top of. I prefer the way described in AIP-5 that we switch to use the DagFetcher abstraction, which is an independent core Airflow component, right before we parse the DAG or periodically fetch the DAG in an independent process.

**Comment by feng-tao** [comment]
+1 on @KevinYang21  @milton0825 , I felt AIP-5 provides a more generic framework which could be extensible to load DAGbag.

**Comment by drewsonne** [comment]
@KevinYang21 The intention here is to build some hooks that can facilitate loading DAGs from anywhere. When I say building as a plugin, there's nothing contrary to AIP-5. AIP-5 could be in the core, and be built on top of this. The intention would be that any DAG loading method used in the core would use the same hooks as the plugins.

The philosophy here is to use the same code to extend core functionality as used to extend plugin functionality to provide everyone with good solid hooks for performing extensions to Airflow without having to do PR's on the core.

But just to confirm, there is nothing contradictory with AIP-5 and this PR. AIP-5 could use the hooks in this PR and still be distributed with the core airflow.

Side note: Using plugin hooks, means you can have pieces of code which exist in seperate repositories and users can install at their will and if there is a desire within the core community, those repositories can be brought into airflow core through normal PR process. But it reduces the need for actual PR's into the core on whether code is suitable to go in the airflow core.

**Comment by drewsonne** [comment]
Shooting from the hip, but to implement AIP-5, would be something like this on top of these hooks

```import json
import os

from airflow import LoggingMixin
from airflow.configuration import conf
from airflow.plugin import AirflowPluginDagSource
from airflow.plugins_manager import AirflowPlugin

log = LoggingMixin().log


class DagBagFetcher(AirflowPluginDagSource):
    def add_dags_to_dagbag(self):
        pass

    def put_dags_on_disk(self):
        home_dir = conf.get('core', 'airflow_home')
        dag_repo_manifest = os.path.join(home_dir, 'dag_repositories.json')
        if os.path.isfile(dag_repo_manifest):
            log.info('Loading dag_repositories.json')
            with open(dag_repo_manifest, 'r') as fp:
                manifest = json.load(fp)
                for repo in manifest['dag_repositories']:
                    # ... download from s3
                    # ... write to disk
        else:
            log.info('Could not find dag_repositories.json')


class Aip5Plugin(AirflowPlugin):
    dag_sources = [DagBagFetcher]
```

and you could include it in the core, by adding to setup.py

```
    setup(
        # ...
        'entry_points': {
            'airflow.plugin': [
                'dag_repo_loader = airflow.plugin.dag_repo_loader:Aip5Plugin'
            ]
        }
    )

**Comment by KevinYang21** [comment]
@drewsonne Thank you for the detailed explaination. The more I think and dig into the issue the more interesting it becomes. Here's what I think:

It is perfectly fine to implement some hooks for the use of both core Airflow and plugins. But in that way I think the code belongs more to the utils module instead of the plugin module.

On the other hand, writing a hook to be used by both core and plugin is not what we are trying to pursue in this PR. From what I'm understanding, we're trying to make the DAG loading plugable. And I'm 100% supportive for this philosophy. In my imagination, to achieve this we would need roughly two steps, 1. is to extract a layer of abstration on DAG fetching in Airflow core and 2. is to make this layer plugable. I think both of them are within the scope of AIP-5 and seems like you are trying to achieve the latter in this PR.

If what I was describing makes sense, then I think it is better to finish 1. first if we don't do 1. and 2. together. And about the implementation details of 2., to keep stuff consistent, I'd prefer to do it like [how we do plugin executor](https://github.com/apache/airflow/blob/master/airflow/executors/__init__.py#L84-L95), which we kinda need to have 1. in place to start.


@ashb I image we'd still need local files as cache or so, but maybe this is not what you meant _need_.

@milton0825  I'm sorry I didn't look close enough when u start the DISCUSS thread but one thing just came aross my mind is that we may want to make the DagFetcher module plugable, people like @drewsonne, me and more would love to have that( not saying that you didn't plan it, just didn't see it get pointed out loud in the AIP)

@ashb @milton0825 @feng-tao Is above something similar to what you guys have in mind?  I just start to put more thoughts into this and likely you guys got something better :D would love to hear more.

**Comment by milton0825** [comment]
@KevinYang21 
Thanks for the feedback! What I envision about remote DAG fetcher is that we can have multiple DAG repos using different storage options (e.g. git, s3, hdfs) at the same time. We will use a `dag_repositories.json` that records the URI to different repo. DAG fetcher would look at the URI and use different implementation (GitDagFetcher, S3DagFetcher) to fetch the DAGs.

But I think we should also allow people to register their own DAG fetcher plugin through a similar way to https://github.com/apache/airflow/blob/master/airflow/executors/__init__.py#L84-L95 as you point out.

**Comment by milton0825** [comment]
@drewsonne 
I think this PR and AIP-5 should share the same fetcher interface like `AirflowPluginDagSource`  with two methods you proposed but I would probably rename it to `BaseDagFetcher` . AFAIK the only difference is that you propose to load the DAG once during startup (correct me if I am wrong) and AIP-5 propose to fetch from remote periodically.  

Also I would recommend you to write an AIP about what you are proposing so that we all can have a better understanding of your proposal and we can consolidate things.

Cheers

**Comment by drewsonne** [comment]
@KevinYang21 
>On the other hand, writing a hook to be used by both core and plugin is not what we are trying to pursue in this PR.

I would ask why are you not trying to pursue that? In the spirit of DRY, why split the loading into "core" and "not-core" plugins?

**Pull request closed without merging**
