### PR TITLE
Removes AIP-44 from dag processing manager and internal_api_call

### PR DESCRIPTION
**Pull request by potiuk**
This is the last "internal_api_call" change from AIP-44 removal and it not only removes the dag_processsing/manager calls but also the internal_api_call itself.

Part of #44436

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @jason810496

**Review by mobuchowski — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]
Wohoo, house is clean!

**Comment by jscheffl** [comment]
...ah wheres still some cleaning and removal in airflow/serialization/pydantic/** is needed as well?
Will airflow/serialization/** actually also be removed or will this stay? (I assume we don't need this with the old API, correct?)

**Comment by potiuk** [comment]
> 
...ah wheres still some cleaning and removal in airflow/serialization/pydantic/** is needed as well?
Will airflow/serialization/** actually also be removed or will this stay? (I assume we don't need this with the old API, correct?)


Yep. there is one more step in #44436 - remove all `*Pydantic` classes aand that's part of it. One problem there is that `Pydantic` classes are currently used as a way to serialize Context for `PythonVirtualenvOperator` and `ExternalPythonOperator` - so we cannot remove them "as-is" - we have to provide a replacement - which is likely tied to the Task SDK API changes - cc: @ashb @kaxil

**Pull request merged**
