### PR TITLE
Better summary of status of AIP-47

### PR DESCRIPTION
**Pull request by potiuk**
Result is here: https://github.com/apache/airflow/issues/24168

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
image

**Comment by potiuk** [comment]
Hey @eladkal  I saw you closed some of the issues that were completed - but I figured I can automate this check and get really nice way of seeing both the progress and "actionable" issues for AIP-47 (when there are "closed" but actually not completed or "open" but completed we see the list of those issues and can easily close/reopen as needed.

**Review by eladkal — APPROVED** [review]
🆒

**Review by josh-fell — APPROVED** [review]
Very helpful indeed.

**Pull request merged**
