### PR TITLE
By default PIP will install all packages in .local folder

### PR DESCRIPTION
**Pull request by potiuk**
In order to optimize the Docker image, we use the ~/.local
folder copied from build imge (this gives huge optimisations
regarding the docker image size). So far we instructed the users
to add --user flag manually when installing any packages when they
extend the images, however this has proven to be problematic as
users rarely read the whole documentation and simply try what they
know.

This PR attempts to fix it. `PIP_USER` variable is set to `true`
in the final image, which means that the installation by default
will use ~/.local folder as target. This can be disabled by
unsetting the variable or setting it to `false`.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by XD-DENG — COMMENTED** [review]
You mentioned "*So far we instructed the users
to add --user flag manually when installing any packages when they
extend the images*" in your description. Is this anywhere in the doc? If yes this should be updated?

**Comment by potiuk** [comment]
> You mentioned "_So far we instructed the users to add --user flag manually when installing any packages when they extend the images_" in your description. Is this anywhere in the doc? If yes this should be updated?

It was already updated in the PR - > see the "production-deployment.rst" which is part of the change :)

**Comment by XD-DENG** [comment]
> > You mentioned "_So far we instructed the users to add --user flag manually when installing any packages when they extend the images_" in your description. Is this anywhere in the doc? If yes this should be updated?
> 
> It was already updated in the PR - > see the "production-deployment.rst" which is part of the change :)

What I meant was if there is any **existing** paragraph/sentences that instruct users to do that? If yes they should be updated. What I can see in `production-deployment.rst` so far is only new additions.

**Comment by potiuk** [comment]
> What I meant was if there is any **existing** paragraph/sentences that instruct users to do that? If yes they should be updated. What I can see in `production-deployment.rst` so far is only new additions.

It's just above that. Earlier paragraph describes it.

**Review by XD-DENG — APPROVED** [review]

**Review by mik-laj — APPROVED** [review]

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
