### PR TITLE
[AIRFLOW-1559][AIRFLOW-1665] Increase database layer robustness

### PR DESCRIPTION
**Pull request by StephanErb**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-1559
    - https://issues.apache.org/jira/browse/AIRFLOW-1665

### Description
- [x] Here are some details about my PR:

An overloaded or faulty database can easily take down Airflow. This PR addresses two dimensions of this problem: Airflow must be more diligent in gracefully closing unused connections, and it must reconnect if one of its existing connection fails unexpectedly.

For reviewers, I would suggest to read this PR commit by commit rather than whole diff at once. Each commit also comes with a more lengthy description of its intend.

The PR is partially based on #2767  by @vklogin and #2744 by @dhuang with a few improvements and clean-ups on top.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

The database layer is used throughout the entire code base, so this improvement leverages the existing test coverage. The newly added behaviour depends on the interlinked behaviour of the main thread, sub- and child processes, and the database. It is therefore hard to test in isolation.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Fokko** [comment]
Looking good, please let me test this. Cheers

**Comment by dhuang** [comment]
This is good to see! I will test it out today for the SQL warnings I was trying to address in my PR.

**Comment by StephanErb** [comment]
@dhuang did you have a chance to test this? I am happy to iterate on the patch if you are still seeing issues.

**Comment by dhuang** [comment]
Yup, I left it on overnight and didn't see any warnings about connection aborted. LGTM!

**Comment by StephanErb** [comment]
@bolkedebruin thanks a lot for merging!

Do you see a chance to get this into 1.9? Or has the release train already progressed too far? (Which I would also totally understand)

**Comment by bolkedebruin** [comment]
1.9.1 is the target. We are at rc for 1.9.0

**Comment by StephanErb** [comment]
That will do, thanks

**Pull request merged**
