### PR TITLE
Fix impersonate beam condition lower than 2.39.0 always evaluating true

### PR DESCRIPTION
**Pull request by tiranux**
Impersonation of service accounts was added in Apache Beam 2.39.0. In PR #27263 validation was added to fix backwards compatibility, but there is an "or True" condition that causes to always evaluate to true. This is causing environment with Apache Beam 2.39.0 and higher to always raise the exception. Same condition was replicated in PR #31471 when support for deferrable mode was added. 

Removing conflicting "or True" from code:
https://github.com/apache/airflow/blob/b5a4d36383c4143f46e168b8b7a4ba2dc7c54076/airflow/providers/apache/beam/hooks/beam.py#L276
https://github.com/apache/airflow/blob/b5a4d36383c4143f46e168b8b7a4ba2dc7c54076/airflow/providers/apache/beam/hooks/beam.py#L491

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
@VladaZakharova -> do  you know of any reason where `or True` was there?

**Comment by tiranux** [comment]
> @VladaZakharova -> do you know of any reason where `or True` was there?

Maybe @mik-laj can let us know if there was something else there that did not make it into the final commit.

**Comment by VladaZakharova** [comment]
Hi Team!
I was not really suspicious about this condition on Beam version, because for me, even using version 2.46.0 didn't cause any errors at all:
Screenshot 2023-08-11 09 10 54

Please, correct me if i am running the operator not in correct way to reproduce the error:
```
 start_python_pipeline_dataflow_runner = BeamRunPythonPipelineOperator(
        task_id="start_python_pipeline_dataflow_runner",
        runner="DataflowRunner",
        py_file=GCS_PYTHON_SCRIPT,
        pipeline_options={
            "tempLocation": GCS_TMP,
            "stagingLocation": GCS_STAGING,
            "output": GCS_OUTPUT,
        },
        py_options=[],
        py_requirements=["apache-beam[gcp]==2.46.0"],
        py_interpreter="python3",
        py_system_site_packages=False,
        dataflow_config=DataflowConfiguration(
            job_name="{{task.task_id}}", project_id=GCP_PROJECT_ID, location="us-central1"
        ),
        deferrable=True,
    )
```

**Comment by tiranux** [comment]
@VladaZakharova your example is not using impersonate_service_account, so it does not enter into that condition:

https://github.com/apache/airflow/blob/b5a4d36383c4143f46e168b8b7a4ba2dc7c54076/airflow/providers/apache/beam/hooks/beam.py#L274-L279

**Comment by VladaZakharova** [comment]
Sorry, my bad :D
Using this parameter it failed for me as well.
I am not sure about the origin of this additional check in `if` statement, but i think it is also a good idea to remove it.

**Comment by potiuk** [comment]
Looks like left-over debugging :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
