### PR TITLE
Fixes #1223

### LINKED ISSUE #1223: Warning e-mails are sent without the Date header
The warning e-mails don't have the "Date" header.

### PR DESCRIPTION
**Pull request by mtoma**

### CODE REVIEW

**Comment by mistercrunch** [comment]
Please follow the guidelines for commit messages here:
http://chris.beams.io/posts/git-commit/

A good commit history makes it easy  to put the changelog together.

**Comment by mtoma** [comment]
Of course. I tough the code diff was self-explanatory and completely forgot about a changelog.

**Comment by mtoma** [comment]
Did add a clearer commit message. Let me know if you feel it should be improved in any way.

**Comment by bolkedebruin** [comment]
Sorry to nitpick but can you fix the landscape issues? (Trailing white spaces)

**Comment by mtoma** [comment]
Yes, no problem. Needed something to add to highlight the changed lines in the diff.
Will take them out.

**Comment by mtoma** [comment]
Done

**Pull request merged**
