### PR TITLE
[AIRFLOW-XXX] Pin docker requirement version

### PR DESCRIPTION
**Pull request by deagon**
The method "create_container" in APIClient of docker has been incompatible from version 3.0.0.

### CODE REVIEW

**Comment by deagon** [comment]
The reason of failing seems to be time out. How to recheck it?

**Review by ashb — COMMENTED** [review]
Is there a reason to to update to 3, and fix the coffe code?

**Comment by deagon** [comment]
@ashb It passed. ^_^

**Comment by deagon** [comment]
When someone want to pip install the docker plugin on airflow, it could mislead the users to install the latest bags. It's a friendly tip.

**Comment by deagon** [comment]
When someone want to pip install the docker plugin on airflow, it could mislead the users to install the latest bags. It's a friendly tip.

**Comment by Fokko** [comment]
Please create a Jira ticket for this, and mention the incompatibility with the `create_container`

**Comment by deagon** [comment]
Reopened it at #4042

**Pull request closed without merging**
