### PR TITLE
[AIRFLOW-50] Add bulk_insert_rows() to OracleHook for more performant inserts.

### PR DESCRIPTION
**Pull request by geeknam**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- _https://github.com/airbnb/airflow/issues/1463_

This has been tested on 1 million rows.

### CODE REVIEW

**Comment by r39132** [comment]
Refer to my comment in your GitHub issue. You need to link this PR to a Jira issue before we can merge it.

**Comment by geeknam** [comment]
@r39132 JIRA issue create, this process will just discourage everyone from contributing

**Comment by r39132** [comment]
@geeknam it's part of our move to Apache. It's a new set of tooling that is standard across all Apache projects and also in use in many companies (in the Bay Area). It will slow things down during the transition but it will help us scale better. 5 months ago, we were in the realm of a single company & single committer and the project was not able to scale. As part of the move to apache, we have removed both types of SPOFs.

JIRA : [AIRFLOW-50](https://issues.apache.org/jira/browse/AIRFLOW-50)

**Comment by criccomini** [comment]
LGTM

**Pull request merged**
