### PR TITLE
Show dagbag import errors in dag list command

### PR DESCRIPTION
**Pull request by turbaszek**
Previously error were ignored to make the output parsable.

Screenshot 2021-03-30 at 14 09 17

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
I like this idea! It will be helpful for the users.

**Comment by turbaszek** [comment]
> I like this idea! It will be helpful for the users.

Thanks @mik-laj ! I'm just wondering about adding `"ERROR"` as a `dag_id` for dagfiles with errors so it's even easier to spot the problem

**Comment by turbaszek** [comment]
@mik-laj would you mind re-reviewing?

**Review by XD-DENG — COMMENTED** [review]
Worth adding a flag to allow users to decide if they want import errors to be shown here or not?

**Comment by mik-laj** [comment]
I thought about it longer and I think that DAG file loading errors are different than DAG files and should be displayed separately. On this screen, we can add a message that prompts you to use another command.
```
Failed to load all files. For details, run airflow dags list-import-errors.
```
In particular, it will be helpful when we have more types of errors.
https://github.com/apache/airflow/pull/11960

**Comment by turbaszek** [comment]
@mik-laj how this should be represented in yaml/json format?

**Comment by mik-laj** [comment]
@turbaszek This message will be available on stderr, not stdout, so that won't be a problem.

**Comment by turbaszek** [comment]
@mik-laj any additional input on this one?

**Comment by mik-laj** [comment]
I suggest that we should display this information in a separate table/command.  what do you think?

**Comment by uranusjr** [comment]
+1 to separate table (but same command IMO). This makes the table *very* long and reduce readability on small-is screens—not 80-column small, I think even my 13-inch laptop would not be wide enough. The use of space can be a bit inefficient considering most rows would have no errors anyway.

**Pull request closed without merging**
