### PR TITLE
[AIRFLOW-996] Updated version.py to match git tag

### PR DESCRIPTION
**Pull request by UnclaimedPants**
Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-996

Testing Done:
- No unit tests done.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
This will only be done after 1.8 is released and it will contain Apache incubating. 

Please close this PR

**Comment by UnclaimedPants** [comment]
@bolkedebruin `setup.py` fails here due to version not matching tag "1.8.0" from the tag you released 5 hrs ago here:

https://github.com/apache/incubator-airflow/releases/tag/1.8.0

Offending line in `setup.py`:
https://github.com/apache/incubator-airflow/blob/master/setup.py#L86:
`            assert tag == version, (tag, version)`

Caused by line in `version.py`:
`version = '1.8.0rc5+apache.incubating'`

**Comment by bolkedebruin** [comment]
@UnclaimedPants I know, it will be updated once the release is VOTED on by the Apache IPMC and we can rename from 1.8.0rc5 to 1.8.0

**Comment by UnclaimedPants** [comment]
Version has been updated by @bolkedebruin

**Pull request closed without merging**
