### PR TITLE
Further improve image caching for Breeze

### PR DESCRIPTION
**Pull request by potiuk**
In order to allow "big" rebuilds we remove the image tag
before rebuilding, to make sure that the remote and not local image
is used as source of cache. This is consequence of using inlined
cache.

Files are added to the Python Base image image - the base
layers will be shared with other stages but we will make sure
that the script stages are different for different platforms.

Also - when there is no image at all we fail pre-commit. This
should handle the situation when we tried to build the image and
stopped it in-between.

Hadolint released a new version of their checker - with support
for the new Dockerfile buildkit features and native support for
ARM so we are enabling it back.

See https://github.com/hadolint/hadolint/pull/803

Finally we still need some files that we cannot inline, because
they are only needed for source build and they are too long
to inline (yarn.lock for example). In order to keep the cache
working for all umasks we need to bring back group fixing.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
This will nicely handle moving "to" the new cache. The "inline" image cache should always be used from the remote image in `ghcr.io` to make sure latest version is used. Therefore we should remove the local image before the build. This is equivalent to "pull and force" but it has the nice property that buildx uses both caches for building so:

1) If you built the image locally and the cache is "better" -it will be used to quickly rebuild the image
2) But if the image changed significantly, the remote cache will be used

**Comment by potiuk** [comment]
I hope that one will make it finally solved with multi-staging builds. I've learned a TON about it and there are still some weird behaviours.

| There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.

**Comment by potiuk** [comment]
Hello! I would really love that one to merge :). It also includes re-enabling hadolint which also brought ARM support last night (and already supports the new dockerfile:1.4 features that we use.

**Review by mik-laj — APPROVED** [review]

**Comment by potiuk** [comment]
Random failure. Merging :)

**Pull request merged**
