### PR TITLE
[AIRFLOW-4355] removed task should not lead to dagrun success

### PR DESCRIPTION
**Pull request by tooptoop4**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by waleedsamy** [comment]
1+

**Comment by tooptoop4** [comment]
not stale

**Comment by turbaszek** [comment]
@tooptoop4 can you please rebase?

**Comment by tooptoop4** [comment]
crispy

**Comment by turbaszek** [comment]
@tooptoop4 can you rebase? We are not using Travis anymore and CI helps allows us to make sure that nothing was broken

**Comment by tooptoop4** [comment]
@turbaszek rebased

**Comment by kurtqq** [comment]
Why is it left to user to decide if `REMOVED` should be considered as `Success `or as `Running`?
I think REMOVED is just a "background noise" it should be ignored like it doesn't exist. I don't think any logic should be constructed over it.

**Comment by tooptoop4** [comment]
REMOVED is not background noise, dynamic dags can get REMOVED intermittently

**Comment by kurtqq** [comment]
> 
> 
> REMOVED is not background noise, dynamic dags can get REMOVED intermittently

My point was that if in a specific run there is a task which has removed state in this run it should be ignored like it doesn't exist.
So if you have` A-> [B,C] -> D`
and `B` is removed Airflow will consider this to be: `A -> C -> D`
Otherwise you might get into a world of troubles. In this PR you try to address the dag state but there is also a very big issue of how trigger rules to be handled. If trigger rule is `ALL_SKIP `does it means REMOVED is OK for it or not?
What about `all_success`? `all_failed `?
I think it makes much more sense to go simple

**Comment by tooptoop4** [comment]
crispy

**Pull request closed without merging**
