### PR TITLE
Fix `RedshiftCreateClusterOperator` to always specify `PubliclyAccessible`

### PR DESCRIPTION
**Pull request by vincbeck**
`PubliclyAccessible` needs to be always specified because the default value (if not provided) is `True` on `Redshift` service side

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ferruzzi — APPROVED** [review]
I might have added a comment to say why it is different from the rest, but I'll approve it.  Thanks for fixing this.

**Comment by vincbeck** [comment]
> I might have added a comment to say why it is different from the rest, but I'll approve it. Thanks for fixing this.

If `PubliclyAccessible` is not provided to the service, it considers it as `True`. Thus, when passing `False` to `publicly_accessible`, with the current code, it does not set it, which is then considered as `True` for Redshift. Removing the if solves that issue

```
if self.publicly_accessible:
            params["PubliclyAccessible"] = self.publicly_accessible
```

**Comment by ferruzzi** [comment]
I get it, but just looking ta the code it is not clear why that one value isn't wrapped in an `if` like all the others are.   No biggie, I over-comment everything :P

**Comment by vincbeck** [comment]
> I get it, but just looking at the code it is not clear why that one value isn't wrapped in an `if` like all the others are. No biggie, I over-comment everything :P

Oh! Get it :) That's a good point, adding a comment

**Comment by ferruzzi** [comment]
I can just see someone in the future looking at that operator and deciding to clean it up and not even noticing thta one parameter is handled differently; even worse, now that I think of it, the tests would all still pass if they did unintentionally revert that in an effort to standardize or clean up that cascading mess of `if` statements....

**Review by o-nikolas — APPROVED** [review]

**Pull request merged**
