### PR TITLE
Use `redshift-data` operators instead of SQL operators

### PR DESCRIPTION
**Pull request by vincbeck**
Instead of using `SQLExecuteQueryOperator`, use AWS provided operator `RedshiftDataOperator` to run SQL queries in a Redshift cluster.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
> Instead of using `SQLExecuteQueryOperator`, use AWS provided operator `RedshiftDataOperator` to run SQL queries in a Redshift cluster.
> 
> **^ Add meaningful description above** Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information. In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed. In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x). In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

If both options work maybe we should also add doc entry explain the difference?

**Comment by vincbeck** [comment]
> > Instead of using `SQLExecuteQueryOperator`, use AWS provided operator `RedshiftDataOperator` to run SQL queries in a Redshift cluster.
> 
> If both options work maybe we should also add doc entry explain the difference?

The main difference being `SQLExecuteQueryOperator` will execute a SQL query as any other database and will use an Airflow as such, whereas `RedshiftDataOperator` uses `boto3` to communicate with the Redshift cluster. Happy to add that information in the doc, where do you suggest adding such information? [here](https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/operators.html)

**Comment by vincbeck** [comment]
> > Instead of using `SQLExecuteQueryOperator`, use AWS provided operator `RedshiftDataOperator` to run SQL queries in a Redshift cluster.
> 
> If both options work maybe we should also add doc entry explain the difference?

They both work but it seems `RedshiftDataOperator` is more stable, that's why we want to use `RedshiftDataOperator`

**Comment by eladkal** [comment]
Cool. We already have that mentioned in
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/redshift/index.html

**Review by eladkal — APPROVED** [review]

**Pull request merged**
