### PR TITLE
[AIRFLOW-2487] Allow user to set conn type for druid ingestion hook

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2487
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
   1. Allow user to configure the connection type for druid ingestion hook(http, https etc).
   2. Fix flake8 for druid_hook, and test_druid_hook.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
   Add unit test

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
Please rebase with master. The CI has been fixed.

**Comment by feng-tao** [comment]
thanks @kaxil, pr rebased and updated :)

**Comment by kaxil** [comment]
PTAL at below errors

```
======================================================================
19) ERROR: test_submit_gone_wrong (tests.hooks.test_druid_hook.TestDruidHook)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 225 in inner
      return func(*args, **kwargs)
    tests/hooks/test_druid_hook.py line 55 in test_submit_gone_wrong
      hook.submit_indexing_job('Long json file')
    airflow/hooks/druid_hook.py line 67 in submit_indexing_job
      req_index = requests.post(url, data=json_index_spec, headers=self.header)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 112 in post
      return request('post', url, data=data, json=json, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 58 in request
      return session.request(method=method, url=url, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 508 in request
      resp = self.send(prep, **send_kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 106 in _fake_send
      return _original_send(session, request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 618 in send
      r = adapter.send(request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/adapter.py line 233 in send
      raise exceptions.NoMockAddress(request)
   NoMockAddress: No mock address: POST druid://druid-overlord:8081/druid/indexer/v1/task
   -------------------- >> begin captured logging << --------------------
   airflow.utils.log.logging_mixin.LoggingMixin: INFO: Using connection to: druid-overlord
   --------------------- >> end captured logging << ---------------------
======================================================================
20) ERROR: test_submit_ok (tests.hooks.test_druid_hook.TestDruidHook)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 225 in inner
      return func(*args, **kwargs)
    tests/hooks/test_druid_hook.py line 74 in test_submit_ok
      hook.submit_indexing_job('Long json file')
    airflow/hooks/druid_hook.py line 67 in submit_indexing_job
      req_index = requests.post(url, data=json_index_spec, headers=self.header)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 112 in post
      return request('post', url, data=data, json=json, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 58 in request
      return session.request(method=method, url=url, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 508 in request
      resp = self.send(prep, **send_kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 106 in _fake_send
      return _original_send(session, request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 618 in send
      r = adapter.send(request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/adapter.py line 233 in send
      raise exceptions.NoMockAddress(request)
   NoMockAddress: No mock address: POST druid://druid-overlord:8081/druid/indexer/v1/task
   -------------------- >> begin captured logging << --------------------
   airflow.utils.log.logging_mixin.LoggingMixin: INFO: Using connection to: druid-overlord
   --------------------- >> end captured logging << ---------------------
======================================================================
21) ERROR: test_submit_timeout (tests.hooks.test_druid_hook.TestDruidHook)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 225 in inner
      return func(*args, **kwargs)
    tests/hooks/test_druid_hook.py line 119 in test_submit_timeout
      hook.submit_indexing_job('Long json file')
    airflow/hooks/druid_hook.py line 67 in submit_indexing_job
      req_index = requests.post(url, data=json_index_spec, headers=self.header)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 112 in post
      return request('post', url, data=data, json=json, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 58 in request
      return session.request(method=method, url=url, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 508 in request
      resp = self.send(prep, **send_kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 106 in _fake_send
      return _original_send(session, request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 618 in send
      r = adapter.send(request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/adapter.py line 233 in send
      raise exceptions.NoMockAddress(request)
   NoMockAddress: No mock address: POST druid://druid-overlord:8081/druid/indexer/v1/task
   -------------------- >> begin captured logging << --------------------
   airflow.utils.log.logging_mixin.LoggingMixin: INFO: Using connection to: druid-overlord
   --------------------- >> end captured logging << ---------------------
======================================================================
22) ERROR: test_submit_unknown_response (tests.hooks.test_druid_hook.TestDruidHook)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 225 in inner
      return func(*args, **kwargs)
    tests/hooks/test_druid_hook.py line 94 in test_submit_unknown_response
      hook.submit_indexing_job('Long json file')
    airflow/hooks/druid_hook.py line 67 in submit_indexing_job
      req_index = requests.post(url, data=json_index_spec, headers=self.header)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 112 in post
      return request('post', url, data=data, json=json, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/api.py line 58 in request
      return session.request(method=method, url=url, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 508 in request
      resp = self.send(prep, **send_kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/mocker.py line 106 in _fake_send
      return _original_send(session, request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests/sessions.py line 618 in send
      r = adapter.send(request, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/requests_mock/adapter.py line 233 in send
      raise exceptions.NoMockAddress(request)
   NoMockAddress: No mock address: POST druid://druid-overlord:8081/druid/indexer/v1/task
   -------------------- >> begin captured logging << --------------------
   airflow.utils.log.logging_mixin.LoggingMixin: INFO: Using connection to: druid-overlord
   --------------------- >> end captured logging << ---------------------
```

**Comment by feng-tao** [comment]
hey @kaxil , thanks for pointing it out. I have fixed the unit tests. Now let's see if the CI passes :)

**Comment by Fokko** [comment]
Nice one!

**Pull request closed without merging**
