### PR TITLE
[AIRFLOW-1085]  Passing the Spark home, driver memoryu, and Java application class to the SparkSubmitOperator

### PR DESCRIPTION
**Pull request by camshrun**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. 
    - https://issues.apache.org/jira/browse/AIRFLOW-1085

### Description
- [ ] Adds the ability to pass the Spark home, driver memory, and Java main class to the SparkSubmitOperator.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Adds:
- contrib.hooks.spark_submit_hook.TestSparkSubmitHook.test_submit_cmd
Modifies:
- contrib.hooks.spark_submit_hook.TestSparkSubmitHook.test_build_command
- contrib.operators.spark_submit_operator.TestSparkSubmitOperator.test_execute

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@camshrun Thanks for your contribution. Please adhere to the commit guidelines.

@Fokko can you review this? I think the operator should obtain spark_home from the connection and not from the constructor.

**Comment by Fokko** [comment]
@camshrun Thank you for your contribution, looks like a good addition. 

However I have one comment. Personally I would integrate the `SPARK_HOME` variable in the connection string, by extracting this from the piggybacked json, see:
https://github.com/camshrun/incubator-airflow/blob/199948356d6812aab8513eb77dfc85fda332551d/airflow/contrib/hooks/spark_submit_hook.py#L102

Passing the driver memory, and the Java application class is fine to pass it directly to the operator. When something affects all the spark-submit job, I would put it in the connection. If the parameter should be tuned per job, such as the memory or entry class, I would suggest passing it to the hook itself.

**Comment by camshrun** [comment]
@Fokko  Thanks for the feedback.  I will move the spark home into the extra in the connection.

**Comment by Fokko** [comment]
LGTM, nice addition!

**Comment by bolkedebruin** [comment]
Please squash and verify your commit message against the guidelines. Then I'll merge.

**Comment by camshrun** [comment]
@bolkedebruin I have squashed the commit and updated the commit message.

**Comment by bolkedebruin** [comment]
I will merge but your commit message still does not comply, next time please read and adjust

**Comment by camshrun** [comment]
@bolkedebruin Thank you.  Is there any feedback you can give me about the commit message so I can be better contributor to this project?

**Comment by bolkedebruin** [comment]
See under commits iv.

**Comment by camshrun** [comment]
@bolkedebruin Thanks. I see now.

**Comment by bolkedebruin** [comment]
@camshrun also specify the correct lira next time plz.

**Pull request closed without merging**
