### PR TITLE
[AIRFLOW-1239] Fixes base_task_runner logging with unicode values on Py27

### PR DESCRIPTION
**Pull request by deckmon**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### CODE REVIEW

**Comment by skudriashev** [comment]
@deckmon please report a Jira issue describing what is the problem.

**Comment by deckmon** [comment]
@skudriashev Jira issue added

**Comment by allisonwang** [comment]
Please use the standard PR template. This doesn't fix the root issue of having unicode characters in log messages that causes UnicodeDecodeError. A better way is to make the formatter's format string unicode.

**Comment by Acehaidrey** [comment]
Agree with @AllisonWang comments. I am having these same error messages looking like the following: 
```
[2017-07-28 23:03:03,358] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ahaidrey/.virtualenvs/airflow/local/lib/python2.7/site-packages/airflow/task_runner/base_task_runner.py", line 95, in _read_task_logs
    self.logger.info('Subtask: {}'.format(line.rstrip('\n')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 66: ordinal not in range(128)
```
But after adding the line `from __future__ import unicode_literals` (like Allison's suggestion) it goes away and I have something like the following in my worker logs:
```
[2017-07-29 03:57:05,707] {__init__.py:57} INFO - Using executor CeleryExecutor
[2017-07-29 03:57:05,833] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[2017-07-29 03:57:05,879] {driver.py:120} INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
```
I read this [SO post](https://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string) to get that solution.

@deckmon , let me know if you're willing to make that change in this PR so it can get merged (I need it too), otherwise I can create a separate PR.

**Comment by Acehaidrey** [comment]
@aoen this PR can be closed as well. Just letting you know.

**Comment by aoen** [comment]
I can't close it unfortunately @deckmon will need to close it.

**Comment by Acehaidrey** [comment]
Ah got it @aoen. Just was trying to get rid of old PR's for your team. But no problem! @deckmon you can close this ticket and the JIRA ticket for it, AIRFLOW-1239.

**Comment by r39132** [comment]
Closing.... resolved by https://github.com/apache/incubator-airflow/pull/2496

**Pull request closed without merging**
