### PR TITLE
Backport TI updated_at column from 2.5.0

### PR DESCRIPTION
**Pull request by luisglft**
New column name will be useful to query tasks stuck in scheduled state.
https://github.com/apache/airflow/pull/26252

### CODE REVIEW

**Comment by jscheffl** [comment]
Uuups, something went totally wrong in re-basing your PR?

**Review by jscheffl — CHANGES_REQUESTED** [review]
Something is terribly wrong in this PR

**Comment by jedcunningham** [comment]
Pretty sure this wasn't meant for the Apache repo @luisglft, but an (internal) fork? I'm going to close this. But please open another PR if I've interpreted this incorrectly.

**Comment by luisglft** [comment]
> Pretty sure this wasn't meant for the Apache repo @luisglft, but an (internal) fork? I'm going to close this. But please open another PR if I've interpreted this incorrectly.

yes you're right, sorry about that

**Pull request closed without merging**
