### PR TITLE
UX Enhancement: Separate actions from links in DAG navigation

### PR DESCRIPTION
**Pull request by ryanahamilton**
- Separates the "actions" (trigger, refresh, and delete) from the "view navigation" to visually differentiate between these two different logical groupings.
- The action buttons all have tooltips and aria attributes to offset the removal of the text from the buttons.
- Updated the icons used for "Trigger" and "Delete". The non-circled icons have a cleaner appearance in an icon-only button. These icons have also been updated in the "DAGs" index view.
- Swapped the position of the "Tree View" and "Graph View" navigation links given "Tree View" is the default view when clicking from the "DAGs" index view.
- UI screenshots in documentation have been updated to reflect these changes.

**DAG Navigation - Before:**
image

**DAG Navigation - After:**
image

**DAGs Index Icons - Before:**
image

**DAGs Index Icons - After:**
image

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by dimberman — APPROVED** [review]

**Review by mik-laj — COMMENTED** [review]
Fantastic. I started working on it once but never got motivated to finish it.
https://github.com/apache/airflow/pull/4796

**Review by mik-laj — APPROVED** [review]

**Comment by ryanahamilton** [comment]
@mik-laj ah, I hadn't seen that PR. Glad to see we're on the same page!

**Review by ryw — APPROVED** [review]
Nice improvement @ryanahamilton - looks good

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Nice work @ryanahamilton

**Pull request merged**
