### PR TITLE
[AIRFLOW-469] Add MFG Labs as Airflow user

### PR DESCRIPTION
**Pull request by dud225**
Hello.

We'd like to be added as official Airflow users.

Regards

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Welcome! But could you make sure to use the alphabetical order?

**Comment by r39132** [comment]
@dud225 ? As mentioned, please add your company to the list while maintaining alphanumeric ordering.

**Comment by dud225** [comment]
Sorry for that didn't notice it in the first place.

**Comment by r39132** [comment]
@dud225 You need to rebase.. looks like quite a few companies added their names while this was left open.

**Comment by r39132** [comment]
Also, in general, you need to squash your commits, though committers can also do it with the airflow-pr tool, but it's something we also wish contributors to do.

**Comment by r39132** [comment]
I'm going to close this PR. Please reopen when ready.

**Comment by r39132** [comment]
@dud225 just a warning that I will be closing this PR unless there is movement on this.

**Comment by msumit** [comment]
@dud225 plz resolve the conflicts and rebase to squash all your commits in a single commit.

**Comment by dud225** [comment]
Sorry for the late reply. 
Here you are.

**Comment by ldct** [comment]
👍

**Pull request closed without merging**
