### PR TITLE
gitSync from multiple git repository or branch

### PR DESCRIPTION
**Pull request by koustreak**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

Purpose of the PR : Git-Sync from multiple repo and branch ,
change-list:
- in dags.gitSync , now it is possible to have multiple entries
- changes in values.schema.json to amend the new schema for dags.gitSync.repositories
- changes in check-values.yaml to check the below rules
  - to check if duplicate repo and branch combinations are entered
  - containerName should be unique in values.yaml for every entry in dags.gitSync.repositories
- changes in _helpers.yml ( the helper function ) to accommodate multi-repo settings
- changes in deployment yaml to support multirepo setting
- changes in dags folder path so that symlink can be created for all repos
- changes to support known-hosts and sshKey for multiple repos or branchs

**This is a new feature which i have been working , i am ready to co-operate with all test-cases , below are the test cases i have performed**

Test Cases | Expected Behaviour | Result
-- | -- | --
multiple git-repo ( 2 Private and 1 Public ) | gitSync pulling from multiple repo or branch | PASSED
multiple git-repo ( 2 Private with ssh ) | gitSync pulling from multiple repo or branch | PASSED
single git-repo | existing behavior should not be interrupted | PASSED
multiple duplicate entry in repositories section in dags | Should raise error while helm install | PASSED
Known-hosts for all repos | Known-hosts are listed in airflow.cfg for all repos | PASSED

**Change Lists** : 

File Name | Changes
-- | --
templates/NOTES.txt | Notes added for multirepo changes , it is just a Note
templates/check-value.yaml | The Multirepo changes comes with some conditions -  <br>**1**. containerName in dags.gitSync for every repo in repositories list , should be unique  <br>**2**. whether user is providing duplicate input in the dags.gitSync.repolistories list
templates/_helpers.yaml | Below are the changes - <br>**1**. create git-sync-init and git-sync container for every entry in the dags.gitSync.repositories list <br>**2**. create seperate volumeMounts and volumes for the ssh key and repo in dags.gitSync.repositories <br>**3**. create dags folder path for all entries in dags.gitSync.repositories <br>**4**. created a new helper to create symlink for every repo and call this helper in container ( scheduler , worker , triggerer , webserver , ..  ) in their lifecycle
templates/scheduler/scheduler-deployment.yaml | changes to enlist all volumnes for all repos and as well as for sshKey , also in container lifecycle , helper airflow.dags_poststart has been called , so that it can create symlink for every repo , only after the git-sync is finished , to avoid any race-condition,
templates/worker/worker-deployment.yaml | changes to enlist all volumnes for all repos and as well as for sshKey , also in container lifecycle , helper airflow.dags_poststart has been called , so that it can create symlink for every repo , only after the git-sync is finished , to avoid any race-condition,
templates/webserver/webserver-deployment.yaml | changes to enlist all volumnes for all repos and as well as for sshKey , also in container lifecycle , helper airflow.dags_poststart has been called , so that it can create symlink for every repo , only after the git-sync is finished , to avoid any race-condition,
templates/triggerer/triggerer-deployment.yaml | changes to enlist all volumnes for all repos and as well as for sshKey , also in container lifecycle , helper airflow.dags_poststart has been called , so that it can create symlink for every repo , only after the git-sync is finished , to avoid any race-condition,
templates/secrets/git-ssh-key-secrets.yaml | changes in secrets , so that it can have secrets from multiple repos from dags.gitSync.repositories
templates/dag-processor/dag-processor-deployment.yaml | changes to enlist all volumnes for all repos and as well as for sshKey , also in container lifecycle , helper airflow.dags_poststart has been called , so that it can create symlink for every repo , only after the git-sync is finished , to avoid any race-condition,
templates/configmaps/configmap.yaml | changes to facilitate multiple known-hosts from dags.gitSync.repositories
files/pod-template-file.kubernetes-hem-yaml | changes in volumne and container lifecycle to facilitate the multirepo changes
values.yaml | introduced a new list element in dags.gitSync , this new list element named repositories which will have multiple entries of repos or branches
values-schema.json | because a new element has been introduced in dags.gitSync , the schema.json is needed to be changed .

Thanks and Regards,
koushik

### CODE REVIEW

**Comment by potiuk** [comment]
Hello @koustreak  - could you please explain how are you going to provide synchronization between multiple repos?

One of the functionalities of git-sync is that it performs atomic swap when new commits are synced - it keeps the old repository, while it checks-out the new one and then atomically swaps the new folder with the old one via symbolic link.

This is an important feature of git-sync, because it guarantees that DAG parsing across multiple folders inside the repo is consistent - and uses always the same single-consistent version of the DAG files and any related imports.

This is one of the reasons why both git-sync and us are reluctant to manage and sync multiple repositories via "external means" - because you can already do it via "submodules" - and then the consistency and atomic swap is maintained - while you get  a good way of keeping references to all the updated repos and even reverting and backing individual repos to previous versions in the single "umbrella repo" using submodules.

With the approach you propose, not only you have multiple init containers, and running containers with git-sync, but also they have somewhat unpredictible schedule - and it's very easy to imagine that checked out repositories: a and b will be checked in an inconsistent state (say repository a still at previous commit, and repository b at new commit) 

Imagine "common" repository and "dag_team_a" repository - and `dag_team_a` importing `common.util.function` - and comon.util.function adding new mandatory parameter - when you synchronize each repository independently, common.util.function might be already updated, when 'dag_team_a" importing it, still uses the old function without the mandatory parameter. This will fail parsing of dags in `dag_team_a`.

This is perfectly manageable with having a single repository with submodules where you update to the right versions of your
common repos and commit those changes together.

See https://www.youtube.com/watch?v=uA-8Lj1RNgw - the talk by Anum from Jagex explaining how they are doing it.

How are you going to deal with this scenario?

**Comment by koustreak** [comment]
Hi , @potiuk , 

First of all , many thanks for taking a look at my PR . 
lets say you have setup ```common``` and ```dag_team_a``` in the multirepo setup , and as per  wait parameter both will be synced independently , 

So lets say for common repo the value of wait is 60 and for dag_team_a the value of wait is 80 , and they will be synced accordingly , so if ```common.util.function``` introduced a mandatory parameter and the user forgot to change the function call accordingly in dag_team_a , then it will throw an error , the user will change the function call in dag_team_a and wait for 80 seconds . 

The scenario you referred is somewhat depends on end-user error , lets say you combine both dag_team_a and common in a single repo , still if you forgot to mention the mandatory parameter in your function call , you still gonna get the error . 

the helper function **airflow.dags_poststart** makes sure once the scheduler / triggerer / worker / webserver .. container is started , it creates a symlink in /opt/airflow/dags/bags/<container name>   which points to /opt/airflow/dags/repo/container_name ( this is where the git-sync changes will be synced every time . 

Also the dag_folder points to /opt/airflow/dags/bags , ( if dags.path is mentioned in values.yaml ) 

Yes , i agree to your point that the cross-repo sync won't happen , if such scenario with mandatory parameter occur the it will throw and error in dag processing , then the user will change the code in dag_team_a and after 80 seconds it will be synced again and we can run the dag . 

A dag sync hook or dependence can be created , to make sure both repo sync at same time . I agree to your point there will be a problem with sync staleness , but if we keep the wait parameter value is same for both repo  then it will somewhat do the job will less lag .

**Comment by potiuk** [comment]
> A dag sync hook or dependence can be created , to make sure both repo sync at same time . I agree to your point there will be a problem with sync staleness , but if we keep the wait parameter value is same for both repo then it will somewhat do the job will less lag .

But why not promote submodule (which solves the problem - because in submodule, you can also make sure that you have a single commit, syncing both repos. Say you have 

* repo a) commit 1 -> commit 2
* repo b) commit 3 -> commit 4

Having a single "umbrella" subrebo and single git-sync allows you to do this:

repo c) (umbrella over b) and c)

* commit 4: -> links to commit 1 of repo a) and commit 3 of repo b)
* commit 5: -> links to commit 3 or repo a) and commit 4 of repo b)

That allows for atomic sync of repo c) - being umbrella on top of a) and b) where a) and b) repos are always consistent

Is there any problem with that? Would not it be better to explain (and make a PR documenting it) how you can use submodule "umbrella" repo to synchronize multiple repos? Is there any problem with that? Have you looked at the Jagex presentation explaining it and benefits it brings for managing multi-repos?

I am afraid that by adding more than one repo in git-sync we are opening up for a number of problems, and basicaly eventually we would have to develop a "submodule" equivalent, because the syncrhronisation problems between several repos will cause various errors - and submodule approach seem to have a solution for that, so it seems better to just describe how you can use it.

Any problems with that?

**Comment by potiuk** [comment]
BTW. Have you tried to use submodules for your case? What are your experiences?

**Comment by koustreak** [comment]
Submodules are great , but the main purpose i came up with this is something different . 

Lets say you have two branch develop and main , and you want to test your dags and code are ok in develop branch before merge it to main . 

As per the existing airflow setup you need to have two seperate airflow deployment,  one is pointing to main and another is pointing to develop . 

And many small budget projects end up paying extra to manage two different deployments . 

This is the problem i want to solve. Like i said earlier Cross repo sync wont be a blocker in multirepo gitsync, and i m not intending to decouple the submodule approach and put it in a different repo . 

My goal is completely different.

The multirepo gitsync is a way to deal with multiple version of dags in a same environment.

**Comment by koustreak** [comment]
Submodules are great , but the main purpose i came up with this is something different . 

Lets say you have two branch develop and main , and you want to test your dags and code are ok in develop branch before merge it to main . 

As per the existing airflow setup you need to have two seperate airflow deployment,  one is pointing to main and another is pointing to develop . 

And many small budget projects end up paying extra to manage two different deployments . 

This is the problem i want to solve. Like i said earlier Cross repo sync wont be a blocker in multirepo gitsync, and i m not intending to decouple the submodule approach and put it in a different repo . 

My goal is completely different.

The multirepo gitsync is a way to deal with multiple version of dags in a same environment. 

Sorry my bad i should be cleared at the beginning about the usecase . 

But if you think the cross repo sync would be beneficial along with the multirepo setup i can design a pre sync hook to mitigate that .

**Comment by potiuk** [comment]
> The multirepo gitsync is a way to deal with multiple version of dags in a same environment.

I am not sure if I get it. How?

**Comment by potiuk** [comment]
Just to put it in context: in Airflow 2, all the DAGs in DAG folder are in the same "namespace" - they can see each other and import each other. You can potentially bundle things together in a DAG .zip file (and this is the way how you can currently also bundle DAG and it's dependencies so that they are isolated between different DAGs) - but generally speaking when you have a DAG, imports will use the DAG_FOLDER as the part of PYTHONPATH where all imports are made from for your custom code.

I don't see why you would not be able to do what you want to do with submodules to be honest. But maybe I am wrong.

Also in Airflow 3 this is going to change a lot and in a completely different way that your proposal is heading. We have AIP-66 being implemetned: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=294816356 where you will be able to specify different sources for different bundles, and this all will be handled pretty differently - and the community is going to focus their efforts on supporting this - way more forward looking approach, which has much greater flexibility and will be supported. And if you want to spend your efforts on making it happen - I would suggest contributing to those efforts, rather than adding support for multiple git-sync containers. 

Even if you have a good case yourself to have support for multiple git-syncs ratther than submodules I don't think it is something we would like to support here, you could probably fork Airfow's chart and publish your version if you want to expose it to others and support it for others using it, but I think that would be quite a bit of burden for us to support it here in the community, while we already not only defined what is the way forward but are also in the middle of implementing it for airflow 3.

@jedcunningham -> since you are mostly engaged in AIP-66, is my thinking going in the right direction?

**Comment by koustreak** [comment]
Understood , @potiuk , happy to contrubute to the community approach of dag versioning . 
Since the community is going towards a different direction , i would post my work as a fork and continue to use it in my current project as a stopgap . Once airflow 3 dag version is out comepletely i will switch to it .  

Thanks for reviewing my work , will close this PR today .

**Comment by jedcunningham** [comment]
Yep, I share the same opinion/thoughts as Jarek.

@koustreak, I just want to say this is a very good first PR though (sorry it's not something we want merge). Lots of detail, testing documented, etc. Well done. Hope to see future PRs from you :)

**Pull request closed without merging**
