### PR TITLE
Improve verification of images with PIP check

### PR DESCRIPTION
**Pull request by potiuk**
Verification of images with PIP is done in separate jobs and
they provide useful information to committers and contributors
when the pip check fails.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Still draft, buit it should make it easy to handle dep changes in the future

**Comment by potiuk** [comment]
It's ready for review. I thnk it's really nice change that allows to focus on dep changes and explains how to fix it in case it happens..

**Comment by potiuk** [comment]
@turbaszek @kaxil @ashb @mik-laj [@mjpieters ?] -> The PR with improved PIP check is ready -  and you can actually see how things will work when there is a problem with PIP check (we still have the azure problem to fix in the prod image that @ephraimbuddy  is working on):

https://github.com/apache/airflow/pull/12718/checks?check_run_id=1475010204#step:4:562 

I already have a couple of small improvements to add:

* adding RED error message to indicate clearly that the `pip check` output  is an error and GREEN when everything is fine
* few typos

However, I would love to get some comments on the wording and instructions. I based it on my experiences with getting rid of the conflicts and how I was solving them. I think those instructions should be clear enough for the contributors and commiters on what they should do in case their change actually results in conflict so I am happy to hear any comments.

**Comment by potiuk** [comment]
BTW. once I merge this change I will also add an automated "updated to newer dependencies" flag whenever setup.py changes in the PR. With PIP check guarding it, we should be safe to do 'pip upgrade --upgrade-strategy eager for any PR that changes setup.py.

**Comment by potiuk** [comment]
This is what you get now when there is a pip check error:

Screenshot from 2020-11-30 22-47-04

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
