### PR TITLE
Clean up remaining getattr connection DbApiHook

### PR DESCRIPTION
**Pull request by dabla**
This pull request also applies the cleanup done in the DbApiHook throughout all depending hooks regarding the duplicated calls using the getattr on the conn_name_attr.  This was already done within the DbApiHook itself in the fix for [PR 40615](https://github.com/apache/airflow/pull/40615).  The only drawback of this change is that all providers then need to update the min required version of the common.sql provider to be at the latest version.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
The pre-commit needs to be run as suggested in the error message :)

**Comment by dabla** [comment]
Suddenly I get this static check error but don't see any relation with the changes I did, also rebased already:

docs/exts/substitution_extensions.py:94: error: Incompatible return value type
(got "Tuple[List[Any], List[system_message]]", expected
"Tuple[List[Any], List[SystemMessage]]")  [return-value]
        return [node], system_messages

**Comment by potiuk** [comment]
https://github.com/apache/airflow/pull/40727

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> The only drawback of this change is that all providers then need to update the min required version of the common.sql provider to be at the latest version. 

This is absolutely fine (precisely because we intend to keep strict backwards compatibility for all common.sql versions). It's a bit **unfortunate** that 1.14.1 was not 1.15.0 for that one (because it added `get_conn_id()` so it could be classified as new feature) - but this is just a small inconvenience and that ship has sailed :)

**Comment by dabla** [comment]
> > The only drawback of this change is that all providers then need to update the min required version of the common.sql provider to be at the latest version.
> 
> This is absolutely fine (precisely because we intend to keep strict backwards compatibility for all common.sql versions). It's a bit **unfortunate** that 1.14.1 was not 1.15.0 for that one (because it added `get_conn_id()` so it could be classified as new feature) - but this is just a small inconvenience and that ship has sailed :)

Sorry for that, so I should have done a minor bump then for the common sql provider before, good to know as I will need to do that for the next PR also.  This time will try to do it correctly

**Comment by dabla** [comment]
I get follow [error](https://github.com/apache/airflow/actions/runs/9951806929/job/27492131045?pr=40665) stating that I need to regenerate the provider constraints, but when I run the follow command in breeze nothing is changed:

breeze static-checks --type update-providers-dependencies --all-files

Also my branch is up-to-date with gitbuh.

**Comment by potiuk** [comment]
Can you rebase it please @dabla ? I believe a conflicting change was merged soon after you pushed the PR and that's the root cause (currentlly you cannot even rebase it with the UI as it have conflicting changes (on dependencies update).

**Comment by potiuk** [comment]
image

**Review by potiuk — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
