### PR TITLE
Fix mismatch in generated run_id and logical date of DAG run

### PR DESCRIPTION
**Pull request by davidcaron**
When execution_date is `None`, the generated name for the `run_id` contains the a generated `execution_date` in isoformat.
That `execution_date`should be passed to `trigger_dag`, otherwise we have a mismatch between the `execution_date` in `run_id` and the actual `execution_date` of the dag run.

This didn't cause any issues per se, but I thought it should be fixed for consistency.

### CODE REVIEW

**Review by uranusjr — COMMENTED** [review]
LGTM. We should have a test case preventing future regression. I suspect the current test only covers cases where `isinstance(self.execution_date, datetime.datetime)` is True and thus never detect the bug.

**Comment by uranusjr** [comment]
I added a couple of checks to existing tests to ensure the run ID is generated consistently. I also expanded the refactoring a little to strighten up the type of `self.execution_date`.

**Review by uranusjr — APPROVED** [review]

**Comment by eladkal** [comment]
tests seem to fail :(

**Comment by uranusjr** [comment]
I merged main and removed the full-test-needed label, this should help us see where test failures are from.

**Review by jedcunningham — APPROVED** [review]

**Comment by jedcunningham** [comment]
I just merged main and the mssql failures are also happening in main. Still, I'm going to wait on merging this just to be safe.

**Comment by uranusjr** [comment]
Hmm, looks like MSSQL has some issues with datetime values added in this PR.

**Comment by jedcunningham** [comment]
Looks good now!

**Pull request merged**
