### PR TITLE
Shell edits

### PR DESCRIPTION
**Pull request by OyinOlamide**
Hi @potiuk So I tried my hands on the better variable naming issue, I do not think this PR is perfect, I would however like corrections, what I have done wrong and can do so I can make better changes and get the entire issue solved.
Thank you!

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by OyinOlamide** [comment]
Hello @eladkal @ephraimbuddy This is my second PR and first try on the better naming conventions issue.

Please let me know what I may have done wrong or need to improve on so as to make better changes and get the entire issue solved.
Thank you. :)

**Comment by potiuk** [comment]
> Please let me know what I may have done wrong or need to improve on so as to make better changes and get the entire issue solved.

Sorry for missing that one - but you will need to rebase and remove the chagnes from INSTALL/Quick start as they were already updated in the meantime.

**Comment by ephraimbuddy** [comment]
> Hi @potiuk Thanks for your feedback. I'd like to know. I have already submitted the PR link on Outreachy, do I need to delete the entire PR or is there a way I can go about removing the unnecessary commits in the PR?

You can remove the changes in your file, commit them, rebase and push

**Comment by OyinOlamide** [comment]
Thank you @ephraimbuddy I'll do that today and get back to you.

**Comment by potiuk** [comment]
You really need to start from the latest main and resolve conflicts, I am afraid.

**Comment by OyinOlamide** [comment]
> You really need to start from the latest main and resolve conflicts, I am afraid.

Hi @potiuk , I opened a new, clean PR which can be found here, https://github.com/apache/airflow/pull/19577

With your approval, I would like to close this one so the new one can be the focus. Looking to hear from you. :)

**Pull request closed without merging**
