### PR TITLE
AIRFLOW-51 && AIRFLOW-71 && AIRFLOW-516 docker_operator improvements

### PR DESCRIPTION
**Pull request by asnir**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:

[AIRFLOW-51] Improve the integration with swarm
[AIRFLOW-71] docker_operator - pulling from private repositories
[AIRFLOW-516] removing stopped container.

### CODE REVIEW

**Comment by g2010a** [comment]
Please merge! 👀

**Comment by bolkedebruin** [comment]
Please squash commits / rebase and provide proper commit message per Jira.

**Comment by bolkedebruin** [comment]
Marked for 1.8.1. if merge/comment conditions are met.

**Comment by asnir** [comment]
@bolkedebruin , [The last commit](https://github.com/apache/incubator-airflow/pull/1982/commits/c2e543bd43e466738bbc7942b01229fe90f27838) doesn't contain changes (It was a fast-forward merge)  so you can merge it. You will not find it at the commit log.

**Comment by moertel** [comment]
@asnir, it's been a few months but would you be willing to resolve the conflicts and provide the proper commit message @bolkedebruin asked for? Would be much appreciated. Thanks a lot for your work on this!

**Comment by asnir** [comment]
https://github.com/apache/incubator-airflow/pull/2491

**Pull request closed without merging**
