### PR TITLE
[BUGFIX] podMutations are now deployed correctly to airflow_local_settings.py

### PR DESCRIPTION
**Pull request by alikhtag**
There is a BUG in helm chart where, setting anything in `podMutation` in `values.yaml` does not seem to affect anything. Currently these `podMutations` will not apply during deployment to `airflow_local_settings.py`, hence they will not be used by Kubernetes Executor and Pod Operator to correctly set `taints` and `affinities` in pod configuration. 

This PR should fix this, but only if `.Values.scheduler.airflowLocalSettings` were not set but it seems it was by design originally. 

### If you like to reproduce the bug:
* Firstly use `KubernetesExecutor` for the `Airflow` deployment. 
* Simply add desired `toleration` and/or `affinity` in `podMutation`.
* Deploy some dag/task etc. 
* Check that newly created pods do not have either `tolerations` and `affinities` set in their pod configuration.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
@dimberman  - it looks cool, but I want your opinion here as well :)

**Comment by dimberman** [comment]
Why are we not just having podMutation as a string and allowing people to write whatever function they want? I don't want to start prescribing values or we'll maintain it forever.

**Comment by alikhtag** [comment]
> Why are we not just having podMutation as a string and allowing people to write whatever function they want? I don't want to start prescribing values or we'll maintain it forever.

Hmm this yaml configuration of `podMutation` is very useful, since it will transform to json (or python dict), which is harder to write as string in this yaml, in my opinion. But `podMutation` can have a templating string ( using `tpl .values.podMutiation.pythonFunctionStr` ) as value as well. So if one decides to write function themselves they can overwrite it or use the yaml for templating. I will add this idea soon.

**Comment by alikhtag** [comment]
I don't understand why `postgres` and `mysql` CI failed, current changes I would think would've not affected it?

**Comment by potiuk** [comment]
I'd say those were transient errors. I re-run all jobs now to see if it helps

**Comment by alikhtag** [comment]
@dimberman does current implementation satisfy the maintainability requirement?

**Comment by dimberman** [comment]
Hi @alikhtag, would you like to rebase this PR so we can merge it? If not I can take this on and tag you as the author.

**Comment by dimberman** [comment]
Also you're gonna need to make the pod_mutation_hook function compliant with 2.0 :)

**Comment by alikhtag** [comment]
> Also you're gonna need to make the pod_mutation_hook function compliant with 2.0 :)

Hi @dimberman. What do you refer to `2.0`? Helm `2.0`? If yes I can probably do that during this week.

**Comment by ashb** [comment]
@alikhtag Airflow 2.0 -- we changed the format of pod mutation hooks quite a lot -- it now takes the Kube API Model object directly rather than Airflow's own classes. 
See https://github.com/apache/airflow/pull/10393 and https://github.com/apache/airflow/pull/9903 for example

**Comment by dimberman** [comment]
@alikhtag can you please get the tests to pass? Would be glad to merge once they are passing :).

**Comment by dimberman** [comment]
@alikhtag are you interested in finishing this?

**Comment by jedcunningham** [comment]
I'm going to close this since all `podMutation` parameters have been removed from the chart at this point. This functionality can still be achieved with `airflowLocalSettings` without being too cumbersome.

**Pull request closed without merging**
