### PR TITLE
added oracle operator with existing oracle hook

### PR DESCRIPTION
**Pull request by angelgao**
Dear Airflow Maintainers,

Please accept the following PR that
- Added an Oracle operator to execute Oracle SQL queries, using the existing Oracle Hook

### CODE REVIEW

**Comment by r39132** [comment]
@angelgao Please add an apache 2.0 license header to your new files. This is a requirement as we are now an Apache Incubating project. We are enforcing it on new files, which was mentioned on the pull request template. After adding it, please squash your commits into a single one and then I will be happy to merge it.

**Comment by r39132** [comment]
If you have questions, jump on https://gitter.im/airbnb/airflow and ping me

**Comment by angelgao** [comment]
@r39132 I have made the changes, and squashed the commits.

**Comment by angelgao** [comment]
@r39132 is this PR ok to merge?

**Comment by r39132** [comment]
+1 I'm not sure what our test strategy is for testing db hooks/operators for different db backends, but can you look into adding some mock tests in a follow-on PR?

**Comment by bolkedebruin** [comment]
@r39132 I think the file location might be the wrong place. I think this one should go to airflow.contrib, especially as we cannot really test it and oracle is not under APL2.

**Pull request merged**
