### PR TITLE
fix: Fix hardcoded BigQuery to GCS project id

### LINKED ISSUE #32106: GCSToBigQueryOperator and BigQueryToGCSOperator do not respect their project_id arguments
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

We experienced this issue Airflow 2.6.1, but the problem exists in the Google provider rather than core Airflow, and were introduced with [these changes](https://github.com/apache/airflow/pull/30053/files).  We are using version 10.0.0 of the provider.

The [issue](https://github.com/apache/airflow/issues/29958) that resulted in these changes seems to be based on an incorrect understanding of how projects interact in BigQuery -- namely that the project used for storage and the project used for compute can be separate.  The user reporting the issue appears to mistake an error about compute (`User does not have bigquery.jobs.create permission in project {project-A}.` for an error about storage, and this incorrect diagnosis resulted in a fix that inappropriately defaults the compute project to the project named in destination/source (depending on the operator) table.

The change attempts to allow users to override this (imo incorrect) default, but unfortunately this does not currently work because `self.project_id` gets overridden with the named table's project [here](https://github.com/apache/airflow/pull/30053/files#diff-875bf3d1bfbba7067dc754732c0e416b8ebe7a5b722bc9ac428b98934f04a16fR512) and [here](https://github.com/apache/airflow/pull/30053/files#diff-875bf3d1bfbba7067dc754732c0e416b8ebe7a5b722bc9ac428b98934f04a16fR587).

### What you think should happen instead

I think that the easiest fix would be to revert the change, and return to defaulting the compute project to the one specified in the default google cloud connection.  However, since I can understand the desire to override the `project_id`, I think handling it correctly, and clearly distinguishing between the concepts of storage and compute w/r/t projects would also work.

### How to reproduce

Attempt to use any other project for running the job, besides the one named in the source/destination table

### Operating System

debian

### Versions of Apache Airflow Providers

apache-airflow-providers-google==10.0.0

### Deployment

Other 3rd-party Helm chart

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by irvifa**
In the airflow configuration, we defined the self.project_id where we pass the information regarding the project_id where we run the job. There's another configuration that is defined in _prepare_configuration regarding how we define the job id given for the BQ table source.

closes: https://github.com/apache/airflow/issues/32106
related: https://github.com/apache/airflow/issues/32106

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
@Yaro1  -  What do you think about this change ? Your change from hook.project_id from https://github.com/apache/airflow/pull/30053 seems to be now reverting somehow

@irvifa and @Yaro1 -> maybe you can discuss which is the best approach?

**Comment by avinashpandeshwar-sharechat** [comment]
I can confirm that below change to `airflow/providers/google/cloud/transfers/bigquery_to_gcs.py` also works, while keeping @Yaro1 's changes and also respecting the project_id parameter in the operator.

```
        return hook.insert_job(
            configuration=configuration,
            project_id=self.project_id or configuration["extract"]["sourceTable"]["projectId"],
            location=self.location,
            job_id=job_id,
            timeout=self.result_timeout,
            retry=self.result_retry,
            nowait=self.deferrable,
        )
```

**Comment by avinashpandeshwar** [comment]
I can confirm that below change to `airflow/providers/google/cloud/transfers/bigquery_to_gcs.py` also works, while keeping @Yaro1 's changes and also respecting the project_id parameter in the operator.

How this works - For job computation, use project_id parameter if provided, else use the project_id from the table.
```
        return hook.insert_job(
            configuration=configuration,
            project_id=self.project_id or configuration["extract"]["sourceTable"]["projectId"],
            location=self.location,
            job_id=job_id,
            timeout=self.result_timeout,
            retry=self.result_retry,
            nowait=self.deferrable,
        )
```

**Comment by eladkal** [comment]
Closed in favor of https://github.com/apache/airflow/pull/32232

**Pull request closed without merging**
