### PR TITLE
add install/uninstall api to databricks hook

### PR DESCRIPTION
**Pull request by hnaoto**
- adding install Databricks API to databricks hook([api/2.0/libraries/install](https://docs.databricks.com/dev-tools/api/latest/libraries.html#install))
- adding uninstall Databricks API to databricks hook  ([2.0/libraries/uninstall](https://docs.databricks.com/dev-tools/api/latest/libraries.html#uninstall))

### CODE REVIEW

**Review by XD-DENG — COMMENTED** [review]
So far my only comment is on the docstring’s summary line. Would be good to be consistent with the “style” of existing methods, like “Terminates the cluster”/“Starts the cluster”/etc. above

**Comment by XD-DENG** [comment]
> So far my only comment is on the docstring’s summary line. Would be good to be consistent with the “style” of existing methods, like “Terminates the cluster”/“Starts the cluster”/etc. above

To clarify myself a bit: I meant to ADD a summary line in the existing “style”. The current line can be kept and I find them useful

**Comment by hnaoto** [comment]
> > So far my only comment is on the docstring’s summary line. Would be good to be consistent with the “style” of existing methods, like “Terminates the cluster”/“Starts the cluster”/etc. above
> 
> To clarify myself a bit: I meant to ADD a summary line in the existing “style”. The current line can be kept and I find them useful

Thank you! just added a "summary line" in the comment

**Review by houqp — APPROVED** [review]

**Review by XD-DENG — APPROVED** [review]

**Comment by XD-DENG** [comment]
Thanks @hnaoto . Look forward to the next PR from you :)

**Pull request merged**
