### PR TITLE
Summarize all warnings from all builds

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by ashb** [comment]
Nice one, I was about to look at pretty much this :D

**Comment by ashb** [comment]
Something not working right though:

```
cat: './artifacts/warnings*': No such file or directory
```

Despite the previous step saying it downloaded many artifacts.

**Comment by potiuk** [comment]
Yep. looking at it.

**Comment by potiuk** [comment]
There are some outliesrs there:


image


But I think that  `/tmp` ones should be easy to remove (and seems that is a single warning)  and the ones that start with space are just spurious "\n" thrown in the warnings that make it multi-line, and it's quite OK to have them.

Other warnings are also duplicated because they are thrown from inside of the Python libs so they contain python version, but it makes no sense to de-duplicate them I think (especially that there might be - and are - different warning messages from different versions of Python).

**Comment by potiuk** [comment]
I guess also the /tmp* ones might disappear after the #28153

**Review by dstandish — APPROVED** [review]
cool

**Pull request merged**
