### PR TITLE
[AIRFLOW-2905] Fix get job API endpoint

### PR DESCRIPTION
**Pull request by fenglu-db**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2905
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

Switch to a new get job API endpoint to make it work for jobs launched in non-global/default region (e.g., europe-west1).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by TrevorEdwards — APPROVED** [review]
I also notice that templated jobs do not use locations() https://github.com/apache/incubator-airflow/blob/fd3562bcab78e7f649c10334ab4e47a1d6d0e838/airflow/contrib/hooks/gcp_dataflow_hook.py#L286-L289 but that doesn't affect this PR.

**Comment by fenglu-db** [comment]
@kaxil PTAL, thank you.

**Comment by kaxil** [comment]
@fenglu-g Can you modify the associated tests?

Check the failing Travis:
```
======================================================================
16) FAIL: test_dataflow_job_init_with_job_id (tests.contrib.hooks.test_gcp_dataflow_hook.DataFlowJobTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/contrib/hooks/test_gcp_dataflow_hook.py line 274 in test_dataflow_job_init_with_job_id
      mock_jobs.get.assert_called_with(projectId=TEST_PROJECT, jobId=TEST_JOB_ID)
    .tox/py27-backend_mysql/lib/python2.7/site-packages/mock/mock.py line 925 in assert_called_with
      raise AssertionError('Expected call: %s\nNot called' % (expected,))
   AssertionError: Expected call: get(jobId='test-job-id', projectId='test-project')
   Not called
```

**Comment by kaxil** [comment]
Thanks @fenglu-g

**Pull request merged**
