### PR TITLE
Order the release commands properly

### LINKED ISSUE #32877: Wrong version in Dockerfile
### Apache Airflow version

2.6.3

### What happened

I want to use `2.6.3` stable version of `Airflow`. I cloned the project and checkout on the `tags/2.6.3`.

```bash
git checkout tags/2.6.3 -b  my_custom_branch
```
After checkout I check the `Dockerfile` and there is what I see below:

```bash
ARG AIRFLOW_VERSION="2.6.2"
```
Then I just download code as a `zip` [2.6.3 link](https://github.com/apache/airflow/releases/tag/2.6.3) and I see the same under `Dockerfile`.

Does `AIRFLOW_VERSION` have a wrong value ?

Thanks !

### What you think should happen instead

_No response_

### How to reproduce

I need confirmation that, version is definitely wrong under `Dockerfile`.

### Operating System

Ubuntu

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
closes: #32877 

Due to the documentation, updating the version is done after the TAG is set for the release. We should re order it

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Review by uranusjr — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
I don’t think this will have much effect. Git tagging is done as part of the breeze release command earlier than this

**Comment by amoghrajesh** [comment]
Can you point me to it @pierrejeambrun?

I can fix it if thats the case

**Comment by pierrejeambrun** [comment]
It's done by the following command, earlier in the process:
```
breeze release-management start-rc-process ...
```

The source for the command is [here](https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/commands/release_candidate_command.py#L309), the `git_tag` fn.

**Comment by amoghrajesh** [comment]
Thanks Pierre. 

Can you point me to what you think is the issue? I can pick it up

**Comment by pierrejeambrun** [comment]
As I understand the reported issue, an idea would be to update the dockerfile airflow version when we upgrade the airflow version in the test-branch. (update `airflow/__init__.py`, `airflow/api_connexion/openapi/v1.yaml`, just before building the release note and running the `breeze start-rc-process`).

This way the tag will have the appropriate version in the dockerfile.

We already have a line:
```
Updating Dockerfile with the new version.
```

For updating main version, we also need this in the test branch I think.

**Comment by potiuk** [comment]
Yes. @amoghrajesh. Again - as I suggested before - you can try to PERFORM release process by following the guide and then you will see. what is going on and where you need to fix it. If you are attempting to fix it without actually following the release process, you are attempting to fix something theorethical. The ONLY way to improve the release process is to follow it and yourself and find the place where to fix it. This is pretty much an imperative. You really need to experience what's going on if you want to fix it.

You will not be able to push or publish the packages, but all the rest you will be able to do it with your own hands - otherwise you will make changes like the last time where you misunderstood what you need to do.

**Comment by amoghrajesh** [comment]
Thanks for that @potiuk 
I didn't try to experience it this time because it looked like I didn't have rights to create or push packages. 

But from your comment, it looks like I can try out the rest of the stuff at the very least. Will be mindful of it and try it out.

Apologies for the confusion the last time

**Pull request merged**
