### PR TITLE
feat: add OpenLineage support for RedshiftToS3Operator

### PR DESCRIPTION
**Pull request by kacpermuda**
Similar to #41575 , I'm adding OpenLineage support for operator in reverse direction - RedshiftToS3Operator.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by kacpermuda** [comment]
This should wait for #41634.

**Comment by vincbeck** [comment]
#41634 is merged, feel free to rebase

**Comment by kacpermuda** [comment]
Thanks ! I've found out that I still need to add some work here, probably parse the select_query when used to retrieve all the input tables from redshift. Will keep it in draft for now until it's ready :)

**Comment by potiuk** [comment]
Is that related with https://github.com/apache/airflow/pull/42963 @kacpermuda ?

**Review by mobuchowski — APPROVED** [review]

**Pull request merged**
