### PR TITLE
Fix dynamic imports in google ads vendored in library

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Skimmed only (assuming it's automated)

**Comment by potiuk** [comment]
We still need to get confirmation it actually works :) @collinmcnulty

**Comment by collinmcnulty** [comment]
We have not seen this resolve the problem yet. I'm double checking that the patched code is what's running before ringing alarm bells.

**Comment by vanducng** [comment]
Hi @potiuk @collinmcnulty, we are able to test this branch successfully for google ads api. Eager to have this provider published soon.

Test steps:

1. Clone this forked branch
1. Build wheel file
    ```
    breeze release-management prepare-provider-packages --version-suffix-for-pypi dev1 google
    ```
    
    image

1. Update astro image, I need to remove the default google provider first to get it work, then install the wheel
    image

3. Run Airflow task: succeeded!

**Comment by potiuk** [comment]
> Hi @potiuk @collinmcnulty, we are able to test this branch successfully for google ads api. Eager to have this provider published soon.

WOOOOOOHOOOOO!!!!

Let me then rebase the PR to succeed and we might want to release an ad-hoc release of Google Provider @eladkal ! Happy to do it as well if you want.

**Comment by eladkal** [comment]
> Let me then rebase the PR to succeed and we might want to release an ad-hoc release of Google Provider @eladkal ! Happy to do it as well if you want.

I will do it today

**Comment by potiuk** [comment]
I have to close that PR and open a new one to make it from the "apache/airflow" repository - there is a change in "breeze" that will only work when merged to main or when the PR is run from "apache/airflow" repo, so in order to test it, I need to

**Comment by potiuk** [comment]
New PR opened in https://github.com/apache/airflow/pull/30544

**Pull request closed without merging**
