### PR TITLE
[AIRFLOW-1061] Remove BASE_URL from log_url and mark_success_url

### PR DESCRIPTION
**Pull request by jacopofar**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1061) issues and references them in the PR title. For example, "[AIRFLOW-1601] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1061

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
When the server is started with a port which is not 8080 the log visualizer lik still refers to that and the link doesn't work.
With this change the link in the DAG list uses relative paths and have the browser bring to the actual page.

### Tests
- [x] My PR passes the already existing tests and works in the browser

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by walkoss** [comment]
Hi @jacopofar,

How do you handle the log URL in case where you are running some workers and a mail is sent from a worker that doesn't host the webserver ?

**Comment by jacopofar** [comment]
@Walkoss I didn't know such a function existed and used this helper. In this case I think the solution is to continue using the absolute URL and instead fix `configuration.get('webserver', 'BASE_URL')` to return the correct port. Currently if I run it with `airflow webserver -p 8090` the URL still refers to port 8080. If I have time I'll try to look at it and hopefully come with an updated/new PR.

The other links in the interface use Flask's `url_for` and work. From the issue on Jira I think a similar problem happens with the hostname.

**Comment by walkoss** [comment]
@jacopofar It seems airflow doesn't use this method to fecth remote log. See [here](https://github.com/apache/incubator-airflow/blob/a1b2c0feb01f0891331500e94bb3d08fee1947f8/airflow/utils/log/file_task_handler.py#L97) So you're right :)

**Comment by jacopofar** [comment]
Does that mean it can be merged as is?

**Comment by ron819** [comment]
@jacopofar can you rebase?

**Comment by Rotemlofer** [comment]
This effects only the new  experimental UI correct?

**Pull request closed without merging**
