### PR TITLE
Avoid passing `aws_conn_id` as conn_args for `psycopg2.connect`

### PR DESCRIPTION
**Pull request by gabrielsyapse**
* In the postgres hook code, the conn_args was changed from a whitelist to blacklist at some point 
* `aws_conn_id` should be removed from conn_args and not passed to psycopg2.connect
* the psycopg2 fails to create the connection because `aws_conn_id` is  an unknown param to postgres

### CODE REVIEW

**Review by 0ex-d — APPROVED** [review]

**Comment by xinbinhuang** [comment]
@gabrielsyapse Hi thanks for the contribution! The change looks fine to me, but it seems that this's more a problem on the usage than the actual code itself. - `*_conn_id` should never go into the `extra` field in any situation. I wonder what's the use case and problem you have?

**Comment by gabrielsyapse** [comment]
@ xinbinhuang thanks for the reply, line 48-52 of this file documents the usage. also it was working previously in airflow 1.x
```
extras example: ``{"iam":true, "aws_conn_id":"my_aws_conn"}``
```

**Comment by xinbinhuang** [comment]
@gabrielsyapse ah you're right! Would you mind also adding a test case [here](https://github.com/apache/airflow/blob/main/tests/providers/postgres/hooks/test_postgres.py)? This can help us avoid this from happening again in the future.

**Review by xinbinhuang — APPROVED** [review]

**Comment by jhtimmins** [comment]
@gabrielsyapse can you try rebasing and then running the pre-commit checks on this? That should address the failing static check https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst

**Review by 0ex-d — APPROVED** [review]

**Pull request merged**
