### PR TITLE
Support tables in DAG docs

### LINKED ISSUE #10367: Markdown table is not rendered in doc_md attribute for DAG
**Apache Airflow version**: 1.10.11

**Environment**: Python 3.7

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): PRETTY_NAME="Debian GNU/Linux 10 (buster)"
 (from python3.7-slim-buster docker image)
- **Kernel** (e.g. `uname -a`): Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

Using a markdown formatted table does not work.

**What you expected to happen**:

To be able to see a formated table within DAG view

**How to reproduce it**:

Add a tabular formatted code do dag.doc_md.

Example:

> mytable:
> 
> | a | b | c |
> | ------------- | ------------- | ------------- |
> | a | b | c |

[Table not formatted](https://i.imgur.com/l6JXuWe.png)

**Anything else we need to know**: N/A

### PR DESCRIPTION
**Pull request by jyotidhiman0610**
Closes https://github.com/apache/airflow/issues/10367

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add tests to avoid regression?  It's also the easiest way to get reviews faster, as the reviewer won't have to run the change locally.

**Review by mik-laj — APPROVED** [review]

**Review by ryanahamilton — APPROVED** [review]

**Comment by jyotidhiman0610** [comment]
@ryanahamilton @mik-laj I pushed a space to re-run the failing tests/(seemed unrelated) & get a green build on the PR. Post that, I think we can be good to merge.
Do let me know if there is any other way to run failing tests. 
Thanks

**Comment by jyotidhiman0610** [comment]
I re-based to latest master & pushed. Hoping the tests run now!

**Comment by jyotidhiman0610** [comment]
Thanks for closing @mik-laj /sparkle

**Comment by mik-laj** [comment]
Thanks @jyotidhiman0610 for your contribution. What's next? 🐈‍⬛

**Pull request merged**
