### PR TITLE
Fix logic in Airflow scheduler to prevent DAGs from being reloaded on…

### PR DESCRIPTION
**Pull request by criccomini**
I have been observing strange behavior from the Airflow scheduler lately. The behavior manifests itself as having a lot of active DAG runs with very few task instances being executed. Then, every two minutes, or so, a bunch of task instances would get scheduled. They'd then finish up pretty quickly (< 30s), and there would be no activity for 1m30s until more tasks were added.

Upon investigation, it appears that the Airflow scheduler was taking more than 2 minutes to complete a single loop. We put in profiling in the jobs.py _execute method, and it became apparent that this loop was the culprit:

```
            for dag in dags:
                self.logger.debug("Scheduling {}".format(dag.dag_id))
                dag = dagbag.get_dag(dag.dag_id)
                if not dag or (dag.dag_id in paused_dag_ids):
                    continue
                try:
                    self.schedule_dag(dag)
                    self.process_dag(dag, executor)
                    self.manage_slas(dag)
                except Exception as e:
                    self.logger.exception(e)
```

The dagbag.get_dag(dag.dag_id) invocation was taking about 500ms per-DAG. I have 270 DAGs. 270 \* .5 = ~2 minutes.

The get_dag method has an if-statement to determine if the DAG should be refreshed. Every DAG was getting refreshed on every iteration. This was happening because orm_dag.last_expired is None for all DAGs, which resulted in a check of `dag.last_loaded < datetime(2100, 1, 1)`, which it always is.

The fix appears to only check if last_expired is not None. If it's None, the UI hasn't been clicked, and we shouldn't bother checking if it needs to be refreshed (unless it's not in self.dags).

This dropped the scheduler loop from ~2 minutes to 16 seconds. This is still not great, but it's better. Now, each iteration of the for loop takes .05s. Still, .05_270 = 13.5 seconds. Ideally, I'd like this loop to be even lower. 270 DAGs aren't *that_ many.

I think the scheduler's loop might need to be re-thought a bit, but I'll leave that for a different issue.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can I suggest a test against get_dag so we wont introduce it again?

**Comment by criccomini** [comment]
@bolkedebruin I added a test. The test fails with the old code, and passes with the new.

**Comment by jlowin** [comment]
The fix makes sense to me!

**Comment by criccomini** [comment]
Note the CPU is still pretty heavily used. The core running the scheduler is between 40%-50% pegged.

**Comment by r39132** [comment]
What set's the last_expired column? I looked at my production airflow db for distinct values of last_expired and didn't find any empty columns.

```
airflow=# select distinct(last_expired) from dag order by last_expired;
        last_expired        
----------------------------
 2015-07-22 23:30:55.858098
 2015-07-22 23:30:57.16261
 2015-07-22 23:30:58.337368
 2015-07-22 23:30:58.752384
 2015-07-24 18:00:17.85004
 2015-07-24 18:03:52.802488
 2015-08-20 20:41:33.414277
 2015-08-20 20:43:07.417331
 2015-09-03 15:30:10.433952
 2015-11-07 00:16:49.960903
 2015-11-22 19:20:42.915282
 2015-12-30 17:09:42.592368
 2016-01-12 19:01:04.880244
 2016-01-21 01:07:04.726346
 2016-01-29 23:48:00.024172
 2016-02-19 22:43:38.547216
 2016-03-31 05:40:37.888955
 2016-04-15 19:31:44.542237

(19 rows)
```

**Comment by r39132** [comment]
I found the answer to my question (shown below for my dev machine!):
I see this is called by `/refresh` and `/refresh_all` endpoints on the webserver (e.g. [refresh_all](http://localhost:9999/admin/airflow/refresh_all))

Here's the result of executing `refresh_all` in the UI:
screenshot 2016-04-17 17 35 15

Here's the result of executing `refresh` by clicking on the cycle icon next to the dag in the UI:
screenshot 2016-04-17 17 31 23

Executing these changed the last_expired column value as shown below 

**Before Refresh**:

```
airflow=# select distinct(last_expired) from dag where is_active=True;
        last_expired        
----------------------------
 2016-04-17 17:33:07.270549
(1 row)

```

**After Refresh**:

```
airflow=# select distinct(last_expired) from dag where is_active=True;
        last_expired        
----------------------------
 2016-04-17 17:38:45.303884
(1 row)
```

**Comment by r39132** [comment]
👍

**Pull request merged**
