### PR TITLE
Add --link to COPY directives

### PR DESCRIPTION
**Pull request by mik-laj**
To improve our cache, we can use copying without comparing with the previous image.

> If you don’t rely on symlinks in your COPY commands, the recommendation is to always start using --link

https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
This is really cool improvement from buildkit. This was inevitable to hapen - and It might significantly speed up building of our Breeze images.

**Comment by potiuk** [comment]
Unfortunately, I think we can't use it. Latest docker desktop for MacOS contains bundled 0.8.0 version of buildx and I am afraid it does not work there. I'd prefer to stick to whatever is installed by default for MacOS users. I believe the feature is available in buildx 0.9.6 (but might be wrong - I will download and check the desktop when I am back from Berlin today.

In any case we will nedd to perform version check and fail build image if buildx is in old version - otherwise the failures are pretty cryptic.

**Comment by potiuk** [comment]
Yep. Current docker desktop for Mac  (buildx 0.8.0) fails with:

```
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 57: Unknown flag: link
```

we need to wait until at least 0.9.6 will be included in Docker Desktop I am afraid

**Comment by mik-laj** [comment]
> I believe the feature is available in buildx 0.9.6 (but might be wrong - I will download and check the desktop when I am back from Berlin today.

**Comment by mik-laj** [comment]
I suspect that this is independent of the `buildkit` version, but the syntax just wasn't correct. I'll check it out.

**Comment by mik-laj** [comment]
We managed to build images on MacOS / CI. The syntax definition needs to be on the first line.

But...we are blocked by this issue in hadolint.
https://github.com/hadolint/language-docker/issues/81

**Comment by potiuk** [comment]
I guess we can cole it :). The speedups even without --link are fantastic.

**Pull request closed without merging**
