### PR TITLE
Fix openlineage tests

### PR DESCRIPTION
**Pull request by gopidesupavan**
Tests are failing https://github.com/apache/airflow/actions/runs/11837035818/job/32983342904?pr=44018#step:7:4873

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Comment by gopidesupavan** [comment]
Not sure which PR causes this failure trying to fid :)

**Comment by potiuk** [comment]
One of the few latest asset changes. I think we should automatically add providers open-lineage tests after any changes in assets, as their test heavily depend on them.

This will be quite a bit easier I think after https://github.com/apache/airflow/pull/43979 lands.

**Comment by potiuk** [comment]
Issue created : https://github.com/apache/airflow/issues/44026

**Comment by potiuk** [comment]
Yeah it was caused by #41325 - and there the test were green because openlineage tests were skipped by selective checks., so #44026 when implemented might help to avoid such breakages.

**Comment by potiuk** [comment]
(or maybe @mobuchowski @kacpermuda - we could make those open-lineage tests less depending on actual dataset implementation ? Not sure).

**Comment by mobuchowski** [comment]
The uri vs name thing is not purely implementation detail in this case. We actually try to serialize that information - the event output we want to have _is_ depending on actual dataset specification - I'd rather do the opposite and run OL tests with any change to assets/datasets.

**Comment by mobuchowski** [comment]
Oh yeah that's what you actually suggested within the issue :)

**Pull request merged**
