### PR TITLE
Fix AzureBatchOperator false negative status

### LINKED ISSUE #25635: AzureBatchOperator not handling exit code correctly
### Apache Airflow Provider(s)

microsoft-azure

### Versions of Apache Airflow Providers

[apache-airflow-providers-microsoft-azure 3.9.0](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/3.9.0/)

### Apache Airflow version

v2.3.2

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Other 3rd-party Helm chart

### Deployment details

_No response_

### What happened

I have a task in my Airflow DAG that uses AzureBatchOperator. 
As `batch_task_command_line` we pass something like `/bin/bash -c "some-script.sh"`. 
The Azure Batch task correctly executes this command, and runs `some-script.sh`. All good.

When `some-script.sh` exits with a non-zero exit code, the Azure Batch task is correctly marked as failed (in Azure Portal), as is the job containing the task. However, in Airflow, the AzureBatchOperator task _always_ shows up as succeeded, ignoring the underlying Azure Batch job or task status.

It even shows in the Airflow DAG logs. Below are the logs of a run with the shell script returning a non-zero exit code. Airflow still considers the task to be a SUCCESS.

```sh
[2022-08-10, 10:01:27 UTC] {batch.py:362} INFO - Waiting for {hidden} to complete, currently on running state
[2022-08-10, 10:01:42 UTC] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id={hidden}, task_id={hidden}, execution_date=20220809T141257, start_date=20220810T100024, end_date=20220810T100142
[2022-08-10, 10:01:42 UTC] {local_task_job.py:156} INFO - Task exited with return code 0
```

The `some-script.sh` contains the following at the top, so that can't be the issue I think.
```bash
#!/bin/bash
set -euo pipefail
```
I tried passing `set -e` to the `batch_task_command_line`, so `set -e; /bin/bash -c "some-script.sh"` but that doesn't work, it gives me a `CommandProgramNotFound` exception. 

### What you think should happen instead

When using AzureBatchOperator, I want this task in Airflow to fail when the command line that is passed to AzureBatchOperator exits with a non-zero exit code.

### How to reproduce

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pankajastro**
closes: https://github.com/apache/airflow/issues/25635

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ukaaa — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by nicholashendrickx-tomtom** [comment]
@pankajastro I still have issues with the exit code. I'm passing the following command line to `AzureBatchOperator`:
```bash
"/bin/bash -c 'exit 1'"
```
And even though the batch job fails on Azure, Airflow still considers the task to be exiting with code 0.
We are using `apache-airflow-providers-microsoft-azure@4.3.0`

**Comment by pankajastro** [comment]
> @pankajastro I still have issues with the exit code. I'm passing the following command line to `AzureBatchOperator`:
> 
> ```shell
> "/bin/bash -c 'exit 1'"
> ```
> 
> And even though the batch job fails on Azure, Airflow still considers the task to be exiting with code 0. We are using `apache-airflow-providers-microsoft-azure@4.3.0`

that's weird, can you please share your airflow `AzureBatchOperator` task?

**Comment by nicholashendrickx-tomtom** [comment]
> that's weird, can you please share your airflow `AzureBatchOperator` task?

```python
cmd_line = "/bin/bash -c 'exit 1'"

batch_operator = AzureBatchOperator(
        task_id='batch_operator_with_inline_exit_1',
        batch_pool_id='batch_pool_test',
        batch_pool_vm_size='STANDARD_F48S_V2',
        batch_job_id='batch_job_test',
        batch_task_command_line=cmd_line,
        batch_task_id='batch_task_test',
        batch_max_retries=1,
        batch_task_resource_files=resource_files, # var defined elsewhere, irrelevant in this example
        batch_task_user_identity=user_identity, # var defined elsewhere
        target_dedicated_nodes=1,
        azure_batch_conn_id='azure_batch_default',
        vm_publisher='Canonical',
        vm_offer='0001-com-ubuntu-server-focal',
        vm_sku='20_04-lts-gen2',
        vm_node_agent_sku_id='batch.node.ubuntu 20.04',
        timeout=360,
        should_delete_job=False,
        should_delete_pool=False
    )
```

As said the Azure Portal shows me that the batch job failed, and exited with exit code 1

**Comment by nicholashendrickx-tomtom** [comment]
I've pushed changed in https://github.com/apache/airflow/pull/27185

**Pull request merged**
