### PR TITLE
fix datetime reference in DAG.is_fixed_time_schedule

### PR DESCRIPTION
**Pull request by joshowen**
Fixes a bug in is_fixed_time_schedule due to imports

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by dirrao — COMMENTED** [review]
@joshowen
Thanks for the MR. I see this function is marked as deprecated and not being referenced anywhere in the code. Do we need to support this function?

**Comment by joshowen** [comment]
> @joshowen Thanks for the MR. I see this function is marked as deprecated and not being referenced anywhere in the code. Do we need to support this function?

The deprecation warning says it isn't being removed til Airflow3, so I think its reasonable to expect it to continue to exist and work.

**Review by dirrao — APPROVED** [review]
LGTM

**Review by hussein-awala — APPROVED** [review]
LGTM

**Comment by hussein-awala** [comment]
related to https://github.com/apache/airflow/pull/35887

**Comment by hussein-awala** [comment]
> @joshowen Thanks for the MR. I see this function is marked as deprecated and not being referenced anywhere in the code. Do we need to support this function?

When we deprecate a method/feature, we stop adding new features and improvements to it, but we should maintain it and fix its bugs, especially since this method was broken in the last release.

**Comment by hussein-awala** [comment]
Congrats on your first commit 🎉

**Pull request merged**
