### PR TITLE
ProSiebenSat.1 added to INTHEWILD.md

### PR DESCRIPTION
**Pull request by nicolamarangoni**
ProSiebenSat.1 added to INTHEWILD.md

The editor automatically renumbered the list items

### CODE REVIEW

**Comment by potiuk** [comment]
Please remove those renumberings. They are there on purpose - not everyone has editor that will renumber those automatically.

**Review by potiuk — DISMISSED** [review]
No renumberings.

**Comment by potiuk** [comment]
BTW. You can edit the file directly in GitHub (it will open a PR if you edit a file). No editor needed, no renumbering. You really do not need editor to add one line of markdown :)

**Review by ashb — APPROVED** [review]
I fixed it for you.

**Pull request merged**
