### PR TITLE
Add better diagnostics when tests fail

### PR DESCRIPTION
**Pull request by potiuk**
The "post_test" action had not worked as intended when there was a test failure and did not upload dump of the container logs. It turned out that the "if" conditions in the sub-action do not propagate from the parent action, so "failure()" condition was never met.

This PR spplits post-test actions to "success" and "failure" ones, and triggers each action respectively when the tests succeed or fail.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I discovered it while trying to diagnose the flaky "backfill" test. 

With this change - you will be able to download a complete dump of all the stdout logs from all the containers involved in tests when the tests fail.

**Review by pierrejeambrun — APPROVED** [review]

**Review by pierrejeambrun — COMMENTED** [review]
~~Maybe both actions success and failure should be in the same post_tests folder ? Success is, but failure has its own, wondering if there is a reason for it~~

Re-reading description makes me realise that this was intended.

**Comment by potiuk** [comment]
I had to add a linux permission change as well (what I did, worked on Mac, but not on Linux and it turned out I had to add a bit more.

**Review by vincbeck — APPROVED** [review]

**Review by phanikumv — APPROVED** [review]
LGTM

**Pull request merged**
