### PR TITLE
[AIRFLOW-2796] Improve utils helpers code coverage

### PR DESCRIPTION
**Pull request by andscoop**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR adds test to a few simple helper functions

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
PR adds three unit tests for

- is_container
- is_in
- as_tuple

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by artwr** [comment]
LGTM +1

**Comment by andscoop** [comment]
Is standard practice in this case just to force push and pray? I don't know of any other way to re-trigger CI to attempt to resolve a CI timeout issue.

**Comment by artwr** [comment]
@andscoop We are trying to reduce our consumption of Apache Travis resources. Ideally, you would setup Travis on your fork, and just paste the link to a successful build.

**Comment by andscoop** [comment]
@artwr Thanks. I force pushed this time around since setting up CI would have required at least one other force push as well. 

I will be setting up CI for future PRs.

Thanks for the review.

**Comment by andscoop** [comment]
@artwr Are we good to merge?

**Comment by feng-tao** [comment]
lgtm. Thanks for adding the test @andscoop .

**Pull request merged**
