### PR TITLE
Fix slow DAG deletion due to missing dag_id index for job table

### LINKED ISSUE #20249: DAG deletion is slow due to lack of database indexes on dag_id
### Apache Airflow version

2.2.1

### What happened

We have an airflow instance for approximately 6k DAGs. 
- If we delete a DAG from UI, the UI times out
- If we delete a DAG from CLI, it completes but sometimes takes up to a half-hour to finish.

Most of the execution time appears to be consumed in database queries. I know I can just throw more CPU and memory to the db instance and hope it works but I think we can do better during delete operation. Correct me if I am wrong but I think this is the code that gets executed when deleting a DAG from UI or CLI via `delete_dag.py`
```python
    for model in models.base.Base._decl_class_registry.values():
        if hasattr(model, "dag_id"):
            if keep_records_in_log and model.__name__ == 'Log':
                continue
            cond = or_(model.dag_id == dag_id, model.dag_id.like(dag_id + ".%"))
            count += session.query(model).filter(cond).delete(synchronize_session='fetch')
    if dag.is_subdag:
        parent_dag_id, task_id = dag_id.rsplit(".", 1)
        for model in TaskFail, models.TaskInstance:
            count += (
                session.query(model).filter(model.dag_id == parent_dag_id, model.task_id == task_id).delete()
            )
```

I see we are iterating over all the models and doing a `dag_id` match. Some of the tables don't have an index over `dag_id` column like `job` which is making this operation really slow. This could be one easy fix for this issue.

For example, the following query took 20 mins to finish in 16cpu 32gb Postgres instance:
```sql
SELECT job.id AS job_id FROM job WHERE job.dag_id = $1 OR job.dag_id LIKE $2
```
and explain is as follows
```sql
EXPLAIN SELECT job.id AS job_id FROM job WHERE job.dag_id = '';
                                QUERY PLAN
---------------------------------------------------------------------------
 Gather  (cost=1000.00..1799110.10 rows=6351 width=8)
   Workers Planned: 2
   ->  Parallel Seq Scan on job  (cost=0.00..1797475.00 rows=2646 width=8)
         Filter: ((dag_id)::text = ''::text)
(4 rows)
```
This is just one of the many queries that are being executed during the delete operation.

### What you expected to happen

Deletion of DAG should not take this much time.

### How to reproduce

_No response_

### Operating System

nix

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kushsharma**
Fixes https://github.com/apache/airflow/issues/20249

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by kushsharma** [comment]
@uranusjr can you check what version I should use in the migration docs(I am not sure about it)? I am just using 2.3.0 for now as one of the tests requires me to update that file.

**Review by potiuk — APPROVED** [review]
Ah. So it turned out to be just one index missing :). Cool.

**Comment by potiuk** [comment]
Static checks need fixing and I think this change uses an old migration head (some change likely implemented hen you branched off?)

**Comment by uranusjr** [comment]
2.3.0 should work. But yeah you should change the `down_version` and the corresponding column in migration-ref to `786e3737b18f` instead. And fix the static check failure.

**Review by kaxil — APPROVED** [review]
I have rebased on main, resolved the conflicts and updated the down revision

**Review by potiuk — APPROVED** [review]

**Pull request merged**
