### PR TITLE
Switch Breeze/CI to ghcr.io exclusively

### PR DESCRIPTION
**Pull request by potiuk**
Switch Breeze to use Github Container Registry
    
Breeze used traditionally DockerHub to pull images, because
they were public and GitHub Packages were not. With GitHub Container
Regisry however, we can switch fully to using GitHub Container
Registry also for Breeze.

Thanks to moving to Github Container Registry we can remove
a lot of code responsible for maintaining different naming
and different versions of the images in DockerHub and
GitHub Container Registry. Also it streamlines and simplifies
the process of refreshing the images when new python versions
are released - the CI push builds will check if the new Python
image is released in DockerHub and it will rebuild the base
image automatically if needed (and push it as cache)

The CI documentation (including sequence diagrams) has been
refreshed to reflect those changes (and other changes done in
the meantime). The flows are now simplified as DockerHub is
largely moved out of the picture.

The only remaining DockerHub Images now are:

* images used during CI for integrations (airflow-ci)
* officially released Production Airflow images (airflow)

The integration images will be moved to GitHub Container Registry
in a subsequent PR and the only images remaining in DockerHub
will be the officially released Production Airflow images.

Part of #16555

### CODE REVIEW

**Comment by potiuk** [comment]
Also switching breeze to use `ghcr.io` seems to be complete!

**Comment by potiuk** [comment]
With this (and preceeding #16776) we get quite a bit simplification of pull/build image scripts and the workflow (with removed DockerHub from the picture).

**Comment by potiuk** [comment]
Would be great to merge it and test before tomorrow's workshop @turbaszek  :)

**Comment by potiuk** [comment]
Actually..  I think it's better to wait until AFTER the workshop :)

**Comment by potiuk** [comment]
Right. I think it's ready to review after the workshops :)

**Comment by potiuk** [comment]
Anyone :) ?

**Review by kaxil — APPROVED** [review]

**Pull request merged**
