### PR TITLE
Add owner to taskinstance

### LINKED ISSUE #40366: add ower to TaskInstance class
### Description

add task owner information to taskinstance

### Use case/motivation

I am sending an alarm to Slack using the airflow callback(on_success_callback, on_failure_callback) function. 

I create an alarm message using the information of the task instance, and it would be better if the task owner information is included here.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by wornjs**
Description
add task owner information to taskinstance

Use case/motivation
I am sending an alarm to Slack using the airflow callback(on_success_callback, on_failure_callback) function.

I create an alarm message using the information of the task instance, and it would be better if the task owner information is included here.

Closes: https://github.com/apache/airflow/issues/40366

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Could you add a test that tries to access this parameter on runtime?

**Comment by wornjs** [comment]
> Could you add a test that tries to access this parameter on runtime?

@hussein-awala 
This is a very minor change, so it would be better to use the existing tests rather than creating a new one. I have added the task owner check logic to the test_refresh_from_db test.

**Comment by jscheffl** [comment]
I am worried a bit, the task instance table is a very huge table that potentially have millions of rows. Do we need to persist the field into the table or could we also load it from the Python object as task instance?

Note, the extension solely will not work, if really it is accepted to extend the data model, a DB migration is needed to be added.

**Comment by wornjs** [comment]
> I am worried a bit, the task instance table is a very huge table that potentially have millions of rows. Do we need to persist the field into the table or could we also load it from the Python object as task instance?
> 
> Note, the extension solely will not work, if really it is accepted to extend the data model, a DB migration is needed to be added.

you means migrations/versions/xxx.py? 
I didn't know that, but thank you for letting me know. i add migration py
how are revision and down, revision determined? They seem to be commit IDs, but the actual commits do not exist on the main branch.

**Comment by potiuk** [comment]
> > I am worried a bit, the task instance table is a very huge table that potentially have millions of rows. Do we need to persist the field into the table or could we also load it from the Python object as task instance?
> > Note, the extension solely will not work, if really it is accepted to extend the data model, a DB migration is needed to be added.
> 
> @jscheffl you means migrations/versions/xxx.py? I didn't know that, but thank you for letting me know. i add migration py how are revision and down, revision determined? They seem to be commit IDs, but the actual commits do not exist on the main branch.

You should use alembic to generate those -those are not commits. See https://github.com/apache/airflow/blob/main/contributing-docs/13_metadata_database_updates.rst as starting point.

And I absolutely share @jscheffl worries. TaskInstance is a huge table, it can have miliions and millions of rows and it is the crucial part of the process. Modifying the DB structure and making our database less normalized is not a decision that should be taken lightly.

Have you run any performance tests on millons of rows @wornjs ? Do you know what impact it will have on the database size and memory used to store the extra data? Have you tested it on mysql and Postgres and sqlite with those millions of rows?

If the answer to any of the questions above is "no" - that change is absolutely not ready to be merged. And in generall, if the motivation is to avoid traversing from Task Instance to get the owner information in order to send slack alert, I seriously doubt this change has a serious merit.

**Review by potiuk — CHANGES_REQUESTED** [review]
Requesting changes as there is a doubt if that change is good at all.

**Comment by uranusjr** [comment]
I don't think this is a good idea, trying to access the information on the task would be better.

**Pull request closed without merging**
