### PR TITLE
Migrating issue generation to breeze release-management

### PR DESCRIPTION
**Pull request by amoghrajesh**
Offline chat with @eladkal revealed that there is an inconsistency between how issues are generated for providers, helm-charts, and airflow. Initially I had fixed #37891 and realised that a bigger effort is needed to move everything to breeze. This PR moves issue generation from prepare_release_issue.py to breeze release-management and introduces two new commands.

The usage looks like this:
```
breeze release-management generate-issue-content-core --previous-release 1.9.0 --current-release 1.10.0 --verbose
breeze release-management generate-issue-content-helm-chart --previous-release 1.6.0 --current-release 1.8.0 --verbose
```

Tested for helm chart as well as airflow core.

Example output:
```
root@d4e667edbe5e:~/clone/airflow# ./dev/prepare_release_issue.py generate-issue-content --previous-release 1.9.0 --current-release ${VERSION}
Retrieving PR#3701: https://github.com/apache/airflow/pull/3701
Retrieving PR#3720: https://github.com/apache/airflow/pull/3720
Retrieving PR#3708: https://github.com/apache/airflow/pull/3708
Retrieving PR#3700: https://github.com/apache/airflow/pull/3700
Retrieving PR#3703: https://github.com/apache/airflow/pull/3703
Retrieving PR#3660: https://github.com/apache/airflow/pull/3660
Retrieving PR#24: https://github.com/apache/airflow/pull/24
Retrieving 7 PRs  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
We are kindly requesting that contributors to [Apache Airflow RC 1.10.0](https://pypi.org/project/apache-airflow/1.10.0/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Fix run_unit_tests.sh (#24)](https://github.com/apache/airflow/pull/24): @afarbos
- [ ] [[AIRFLOW-2817] Force explicit choice on GPL dependency (#3660)](https://github.com/apache/airflow/pull/3660): @bolkedebruin
- [ ] [[AIRFLOW-2140] Don't require kubernetes for the SparkSubmit hook (#3700)](https://github.com/apache/airflow/pull/3700): @ashb
- [ ] [[AIRFLOW-2856] Pass in SLUGIFY_USES_TEXT_UNIDECODE=yes ENV to docker run (#3701)](https://github.com/apache/airflow/pull/3701): @andscoop
- [ ] [[AIRFLOW-2857] Fix broken RTD env  (#3703)](https://github.com/apache/airflow/pull/3703): @tedmiston
- [ ] [[AIRFLOW-2859] Implement own UtcDateTime (#3708)](https://github.com/apache/airflow/pull/3708): @bolkedebruin
- [ ] [[AIRFLOW-2870] Use abstract TaskInstance for migration (#3720)](https://github.com/apache/airflow/pull/3720): @bolkedebruin


Thanks to all who contributed to the release (probably not a complete list!):
@afarbos @andscoop @tedmiston @ashb @bolkedebruin

```
```
(new-env) ➜  airflow git:(issueContentToBreeze) ✗ breeze release-management generate-issue-content-core --previous-release 1.9.0 --current-release 1.10.0 --verbose
/Users/adesai/.local/pipx/venvs/apache-airflow-breeze/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/adesai/Documents/OSS/airflow/dev/breeze/src/airflow_breeze/commands /Users/adesai/Documents/OSS/airflow
Command to run: 'git log --pretty=format:%H %h %cd %s --date=short 1.9.0...1.10.0 -- .'
Retrieving PR#3701: https://github.com/apache/airflow/pull/3701
Retrieving PR#3720: https://github.com/apache/airflow/pull/3720
Retrieving PR#3708: https://github.com/apache/airflow/pull/3708
Retrieving PR#3700: https://github.com/apache/airflow/pull/3700
Retrieving PR#3703: https://github.com/apache/airflow/pull/3703
Retrieving PR#3660: https://github.com/apache/airflow/pull/3660
Retrieving PR#24: https://github.com/apache/airflow/pull/24
Retrieving 7 PRs  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
We are kindly requesting that contributors to [Apache Airflow RC 1.10.0](https://pypi.org/project/apache-airflow/1.10.0/) help test the RC.

Please let us know by commenting if the issue is addressed in the latest RC.

- [ ] [Fix run_unit_tests.sh (#24)](https://github.com/apache/airflow/pull/24): @afarbos
- [ ] [[AIRFLOW-2817] Force explicit choice on GPL dependency (#3660)](https://github.com/apache/airflow/pull/3660): @bolkedebruin
- [ ] [[AIRFLOW-2140] Don't require kubernetes for the SparkSubmit hook (#3700)](https://github.com/apache/airflow/pull/3700): @ashb
- [ ] [[AIRFLOW-2856] Pass in SLUGIFY_USES_TEXT_UNIDECODE=yes ENV to docker run (#3701)](https://github.com/apache/airflow/pull/3701): @andscoop
- [ ] [[AIRFLOW-2857] Fix broken RTD env  (#3703)](https://github.com/apache/airflow/pull/3703): @tedmiston
- [ ] [[AIRFLOW-2859] Implement own UtcDateTime (#3708)](https://github.com/apache/airflow/pull/3708): @bolkedebruin
- [ ] [[AIRFLOW-2870] Use abstract TaskInstance for migration (#3720)](https://github.com/apache/airflow/pull/3720): @bolkedebruin


Thanks to all who contributed to the release (probably not a complete list!):
@bolkedebruin @afarbos @ashb @tedmiston @andscoop

```

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
NAAAJS.. Few comments:

* we should remove the `dev/*` script in the same PR

We should run the command in CI together right after Airflow Release And Helm Release commands - this way we will be sure that the command works (at least it will not break in the CI).

We already do that in case of providers:

```
      - name: "Test providers issue generation automatically"
        run: >
          breeze release-management generate-issue-content-providers
          --only-available-in-dist --disable-progress
```
In the `prepare-test-provider-packages-wheel`  job.

For Helm it should be added in `tests-helm-release` jon
For Airlfow it should be added `prepare-test-provider-packages-wheel` as this is where we also prepare `airflow` package

```
      - name: "Prepare airflow package: wheel"
        run: breeze release-management prepare-airflow-package --version-suffix-for-pypi dev0
```

This is the main benefit of having the commands nicely packaged as `breeze` commands - because we can run them in CI and we can be reasonably sure they continue working.

Also I guess there will be a follow up PR where we - possibly - do some refactor and extract the common parts of `generate_issue_content_*` methods ?  It looks like there are quite a lot of duplicated lines of code that could by DRY-ed (but I believe it shoudl be a follow-up PR once we get one or two rounds of releases and this will be proven to work - we might avoid some unnecessary coupling issues this way.

**Comment by potiuk** [comment]
(also having it running in CI is ultimate proof that it works - and there is no need for the reviewer to run it locally - they will simply be able to see it in the CI :)

**Comment by amoghrajesh** [comment]
> We already do that in case of providers:
Understood. Will make the changes for this

**Comment by amoghrajesh** [comment]
> we should remove the dev/* script in the same PR

Yeah I wanted to, but wasn't sure whether to keep this in case it doesn't work.

**Comment by amoghrajesh** [comment]
>  Also I guess there will be a follow up PR where we - possibly - do some refactor and extract the common parts of generate_issue_content_* methods ? It looks like there are quite a lot of duplicated lines of code that could by DRY-ed (but I believe it shoudl be a follow-up PR once we get one or two rounds of releases and this will be proven to work - we might avoid some unnecessary coupling issues this way.

Of course, I will be refactoring in a follow up. I know its messy :)

**Comment by amoghrajesh** [comment]
@potiuk @eladkal I added it to CI as well, wasn't so sure what version to use, so I used some random versions. WDYT?

**Comment by potiuk** [comment]
> @potiuk @eladkal I added it to CI as well, wasn't so sure what version to use, so I used some random versions. WDYT?

It will get longer and longer over time. I deally, we should do the same what the release manager does - i.e use latest version. It's rather easy for airflow - you could potentiallly add support for `latest` value and find latest version from Pypi (already used in Breeze):

```python
    response = requests.get("https://pypi.org/pypi/apache-airflow/json")
    response.raise_for_status()
    latest_released_version = response.json()["info"]["version"]
```

For Helm chart it shoud also be somewhat easy to get latest version ?  I leave that exercise to you

**Comment by amoghrajesh** [comment]
Ok understood, I can take it up in a follow up once this is stabilised. Your call, let me know

**Comment by potiuk** [comment]
Sure. Can be done separately :)

**Comment by potiuk** [comment]
Those issues generated look a bit short though :)  (Helm one is empty :( )

image

**Comment by amoghrajesh** [comment]
Helm one has content right? You mean airflow one?

**Comment by potiuk** [comment]
Compare it with the provider ones (And that's only part of it):

image

**Comment by potiuk** [comment]
Helm is currently this:

image

**Comment by potiuk** [comment]
I don't think  tagging is done? I could not find it actually ? Where is it tagged? I believe the previous steps only use existing tags but never tag it ? Or maybe I missed it ?

**Comment by amoghrajesh** [comment]
> I don't think tagging is done? I could not find it actually ? Where is it tagged? I believe the previous steps only use existing tags but never tag it ? Or maybe I missed it ?

Maybe I am slightly mistaken here but I was checking the process logs.
We have this happening in the step "Helm release tarball"
```
Run breeze release-management prepare-helm-chart-tarball --ignore-version-check --override-tag --skip-tag-signing --version 0.0.0 --version-suffix dev0
Airflow version in values.yaml: 2.8.3
Default Airflow Tag in values.yaml: 2.8.3
Airflow version in Chart.yaml: 2.8.3
Version in chart.yaml (1.[14](https://github.com/apache/airflow/actions/runs/8278547604/job/22651378456?pr=38062#step:9:15).0-dev) does not match the version passed as parameter (0.0.0). Updating
Airflow version in chart.yaml matches the airflow version in values.yaml: (2.8.3)

Versions of the chart has been updated

Ignoring the version check. The tarball will be created but it should not be published
Tagging the chart with helm-chart/0.0.0dev0
Creating tarball for Helm Chart helm-chart/0.0.0dev0
Tarball created in /home/runner/actions-runner/_work/airflow/airflow/dist/airflow-chart-0.0.0-source.tar.gz
```


And in this breeze command the following happens
```
    if not skip_tagging:
        get_console().print(f"[info]Tagging the chart with {tag_with_suffix}[/]")
        tag_command = [
            "git",
            "tag",
            tag_with_suffix,
            "-m",
            f"Apache Airflow Helm Chart {version}{version_suffix}",
        ]
        if override_tag:
            tag_command.append("--force")
        if not skip_tag_signing:
            tag_command.append("--sign")
        result = run_command(tag_command, check=False)
        if result.returncode != 0:
            get_console().print(f"[error]Error tagging the chart with {tag_with_suffix}.\n")
            get_console().print(
                "[warning]If you are sure the tag is set correctly, you can add --skip-tagging"
                " flag to the command[/]"
            )
            sys.exit(result.returncode)
    else:
        get_console().print(f"[warning]Skipping tagging the chart with {tag_with_suffix}[/]")
    get_console().print(f"[info]Creating tarball for Helm Chart {tag_with_suffix}[/]")
```

So I think it has a tag now. I will check out what the right one is

**Comment by amoghrajesh** [comment]
@potiuk I ran a `git tag` in CI environment and it does have one tag: `helm-chart/0.0.0dev0`
I have added it for helm chart now, I will unblock it in a followup where i allow it to get the realistic versions and work on that instead.

**Comment by amoghrajesh** [comment]
The job has passed now: https://github.com/apache/airflow/actions/runs/8292193216/job/22693362907?pr=38062

If all is ok, we can send this one in and I will pick up the follow ups asap.

**Comment by amoghrajesh** [comment]
@potiuk can you take a round at this once you have some time? Just rebased onto the new HEAD of main :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
