### PR TITLE
[AIRFLOW-5501] in_cluster default value in KubernetesPodOperator overwrites configuration

### PR DESCRIPTION
**Pull request by qlemaire22**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5501

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Hi!

The default value of the parameter in_cluster of the kube_client.get_kube_client function is in_cluster=conf.getboolean('kubernetes', 'in_cluster'). Therefore, the expected behavior is that when, in_cluster is not set, it takes the value in the configuration file.

However, the default value of in_cluster in KubernetesPodOperator.py is False and in_cluster is passed as a parameter when calling the kube_client.get_kube_client function. Therefore, it changes the expecting behavior by overwritting the default value. When in_cluster is not set when initializing KubernetesPodOperator, the value of in_cluster in kube_client.get_kube_client is False and not the value which is in the configuration file.

It is quite confusing because it can feel like the value in the configuration file is not working properly.

Therefore, I changed the default value of the in_cluster parameter in KubernetesPodOperator so that it takes the value of the configuration file as a default and expected value instead of False as it is now.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by qlemaire22** [comment]
Fix committer.

**Comment by mik-laj** [comment]
Travis is sad. Can you do rebase?

**Comment by qlemaire22** [comment]
I did the rebase, but there are still some errors and Travis is still sad. After some investigation, I realised that my changes were modifying the behavior of some tests.
For example this test in [`tests/minikube/test_kubernetes_pod_operator.py`](https://github.com/apache/airflow/blob/master/tests/minikube/test_kubernetes_pod_operator.py): 
```
def test_working_pod(self):
        k = KubernetesPodOperator(
            namespace='default',
            image="ubuntu:16.04",
            cmds=["bash", "-cx"],
            arguments=["echo 10"],
            labels={"foo": "bar"},
            name="test",
            task_id="task"
        )
        k.execute(None)
        actual_pod = self.api_client.sanitize_for_serialization(k.pod)
        self.assertEqual(self.expected_pod, actual_pod)
```

It does not specify the `in_cluster` argument. Therefore, the old behavior was to use `in_cluster=False` which was the default value. Now, it is using the value defined in the config which is `in_cluster=True` [(link to the config)](https://github.com/apache/airflow/blob/master/scripts/ci/kubernetes/kube/templates/configmaps.template.yaml).

Therefore, the test is now different and it is the case for every failing test.

Shall I modify the failing tests to include the `in_cluster=False` argument to come back to the old behavior or shall I try to solve the `Service host/port is not set` error which seems to be caused by some missing environment variables?

**Comment by qlemaire22** [comment]
The tests are successful now.

**Comment by RosterIn** [comment]
@dimberman @qlemaire22 I think this fix is simple and important.
why not to merge this?

**Comment by ashb** [comment]
@RosterIn because it got forgotten about.

Ive tried resolving the conflicts. Hopefully the test will still pass.

**Comment by RosterIn** [comment]
seems there is an issue @qlemaire22 
`error: Incompatible default for argument "in_cluster" (default has type "None", argument has type "bool"`

To my understanding ``None`` is not compatible with non-optional types by default however it can be overwritten by `--no-strict-optional` setting

**Pull request merged**
