### PR TITLE
Revert "Update backfill tests to use executor loader (#40285)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 3f3bb463aecdf5c1ce41d25b442df24639a115d7.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
The #40285 seems to impact the "all" (special) tests - likely because of some side-effects from other tests @o-nikolas - for now I think it's better to revert it and re-do, apply "full tests needed" and solve it in a new PR (and I will think of getting selective check more agressively enabling "full tests" in case of some "core" changes possibly.

**Comment by potiuk** [comment]
See https://github.com/apache/airflow/actions/runs/9580481028/job/26415461775

**Comment by potiuk** [comment]
Applied "upgrede-to-newer-dependencies" to actually run the "special tests"

**Review by o-nikolas — APPROVED** [review]

**Comment by o-nikolas** [comment]
> The #40285 seems to impact the "all" (special) tests - likely because of some side-effects from other tests @o-nikolas - for now I think it's better to revert it and re-do, apply "full tests needed" and solve it in a new PR (and I will think of getting selective check more agressively enabling "full tests" in case of some "core" changes possibly.

Sounds good to me, feel free to merge this when you can get it green

**Comment by potiuk** [comment]
Merging: Mypy is red - but this is something coming from new dependencies (same in main) and I will address it separately.

**Pull request merged**
