### PR TITLE
Clean microsoft azure provider by deleting the custom prefix from conn extra fields

### LINKED ISSUE #30557: Azure connections extra fields are inconsistent between the doc, tests and the UI connections
### Apache Airflow Provider(s)

microsoft-azure

### Versions of Apache Airflow Providers

_No response_

### Apache Airflow version

2.5.3

### Operating System

Azure connections extra fields are inconsistent between the doc, tests and the UI connections

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### What happened

When creating an Azure connection from the UI, the extra fields are prefixed with `extra__azure__`, which is not used in the unit tests and not mentioned in the provider documentation.

In some of the hook/operators methods, we double read the field with and without `extra__azure__`  to support the connections created from the CLI (or via env vars) and the connections created from the webserver UI, but this double read is missing in some methods (ex #30556).

To fix this, we should fix the UI fields name and deprecate the fields with `extra__azure__` in order to remove them in the future.

### What you think should happen instead

_No response_

### How to reproduce

~

### Anything else

This should be a Task issue but it is reserved for maintainers.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by hussein-awala**
closes: #30557

---
In this PR I fix the UI fields name by removing the custom prefix from Azure conn extra fields, deprecating the used fields with this prefix in order to remove them in the future, clean the documentation, and clean the provider tests.

### CODE REVIEW

**Comment by eladkal** [comment]
We also have entry for Azure in https://github.com/apache/airflow/issues/28790

**Comment by hussein-awala** [comment]
The method `_ensure_prefixes` was added in #27041 by @dstandish:
https://github.com/apache/airflow/blob/058b6ebdd863ff9178007f5750cc4cde4d3c463f/airflow/providers/microsoft/azure/hooks/fileshare.py#L29-L33

I don't think we really need to wait until bumping the provider min airflow version to >= 2.5.0, since we check for the two variables (with and without `extra_...`) in each extra field loading, and with this PR, we will have:
- For the new connections, the extra fields will be created without `extra_` prefix -> this should work without any problem
- For the connection which have fields with `extra_`, when we update them will have a new field without the `extra_` prefix and another one with `extra_` prefix but with the old value, this old value will not be processed as long as the new one is present in the extra.
- For the connection which have fields with `extra_`, without any update, the provider will use the fields with the prefix, and a warning will be logged to prompt the user to update the connection extra fields.

WDYT?

**Comment by potiuk** [comment]
Hmm. I think the problem was that without the "ensure prefixes" providers_manager woudl crash during building the UI fir connections or at least wreak some havoc. I think we would need to build such provder and install it in airflow 2.3 to be sure.

**Comment by hussein-awala** [comment]
@potiuk I tested this PR with 2.4.0 (the current min version) and with main, I can create connections with and without the `extra__azure__` prefix without any issue. What kind of tests should I do before merging it?
And for this commet:

> Hmm. I think the problem was that without the "ensure prefixes" providers_manager woudl crash during building the UI fir connections or at least wreak some havoc. I think we would need to build such provder and install it in airflow 2.3 to be sure.

There is no problems with the UI:
image
image
image
(6.2.3 because I built it with breeze and installed it from source in a clean conda env)

**Comment by potiuk** [comment]
I can't remember exactly (the comment was from more than 3 months ago) but I believe it was based on "providers back-compat tests" failing back then. We moved to 2.4 min version since, so I think this is good to go now - maybe because of back-compat problem going away because of the min-airflow version bump :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
