### PR TITLE
Removed deprecated k8s rendering methods from task instance module

### PR DESCRIPTION
**Pull request by dirrao**
Removed deprecated k8s rendering methods from task instance module

### CODE REVIEW

**Comment by dirrao** [comment]
The test is passing locally but failing in this environment. Can someone assist with troubleshooting this issue?

**Comment by potiuk** [comment]
Tests are failing :(

**Comment by dirrao** [comment]
> Tests are failing :(
This is fixed.

**Comment by dirrao** [comment]
> Tests are failing :(

Done

**Review by potiuk — APPROVED** [review]

**Pull request merged**
