### PR TITLE
[AIRFLOW-7066] Use sphinx syntax in concepts.rst

### PR DESCRIPTION
**Pull request by zhongjiajie**
---
Issue link: [AIRFLOW-7066](https://issues.apache.org/jira/browse/AIRFLOW-7066)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Seem CI failed with unrelated error, https://travis-ci.org/github/apache/airflow/jobs/662646733?utm_medium=notification&utm_source=github_status

**Comment by potiuk** [comment]
Restarted

**Comment by zhongjiajie** [comment]
BTW, I have some question could not understand, in my PR https://github.com/apache/airflow/pull/7709,  raise pylint error three time, but `airflow/www/views.py` is in `pylint_todo.txt`, which mean will not test by pylint, also test folder will not test by pylint. should where the pylint error? (I only change two files)

I test in breeze using `pylint airflow/www/views.py` and `pylint test/www/views.py` only `airflow/www/views.py` have some error hint(but it in pylint_todo.txt)
@exploy

**Comment by potiuk** [comment]
> BTW, I have some question could not understand, in my PR #7709, raise pylint error three time, but `airflow/www/views.py` is in `pylint_todo.txt`, which mean will not test by pylint, also test folder will not test by pylint. should where the pylint error? (I only change two files)
> 
> I test in breeze using `pylint airflow/www/views.py` and `pylint test/www/views.py` only `airflow/www/views.py` have some error hint(but it in pylint_todo.txt)
> @exploy

It is the test/ that is failing. We have two separate pre-commits - pylint and pylint-test . The test  one is failing in the other build and should be fixed there.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @zhongjiajie !

**Comment by zhongjiajie** [comment]
> > BTW, I have some question could not understand, in my PR #7709, raise pylint error three time, but `airflow/www/views.py` is in `pylint_todo.txt`, which mean will not test by pylint, also test folder will not test by pylint. should where the pylint error? (I only change two files)
> > I test in breeze using `pylint airflow/www/views.py` and `pylint test/www/views.py` only `airflow/www/views.py` have some error hint(but it in pylint_todo.txt)
> > @exploy
> 
> It is the test/ that is failing. We have two separate pre-commits - pylint and pylint-test . The test one is failing in the other build and should be fixed there.

Ok, will take a look to the test, BTW, thanks for merging

**Pull request merged**
