### PR TITLE
Support api_host on Datadog provider

### PR DESCRIPTION
**Pull request by pecigonzalo**
Setting the `api_host` is required `[...]/site-packages/datadog/__init__.py` in Datadog to send metrics/events/etc to other tenants like app.datadoghq.eu.

The tests for the provider do not seem to have any testing regarding `api_key` or `app_key`, but in case we leverage these in the future, I've added the to the `setUp`.

### CODE REVIEW

**Comment by potiuk** [comment]
Looks like @pecigonzalo you have some - wrongly configured [pull bot](https://github.com/apps/pull)  that synced @jbampton changes to your fork whihc made the PR marked as merged when I merged https://github.com/apache/airflow/pull/23764  - was it deliberate configuration @pecigonzalo ?

**Comment by potiuk** [comment]
You will have to redo the pr regardless.

**Comment by pecigonzalo** [comment]
The bot is intentionally pulling, but I forgot about it and used `main` in my repo instead of branch. Ill re-do it.

**Comment by pecigonzalo** [comment]
@potiuk Sorry, done in https://github.com/apache/airflow/pull/23784

**Pull request merged**
