### PR TITLE
Add support for role arn for aws creds in storage transfer job operators

### LINKED ISSUE #35271: CloudDataTransferServiceS3ToGCSOperator does not support identify federation
### Description

We are using identity federation to pass access from GCP to AWS. However, it is not possible to use identify federation with `CloudDataTransferServiceS3ToGCSOperator` as `AWS_S3_DATA_SOURCE` is using `ACCESS_KEY_ID` and `SECRET_ACCESS_KEY`. Maybe it should be possible to pass `AWS_S3_DATA_SOURCE`?

### Use case/motivation

To enable using identity federation between GCP and AWS I'd like it to be possible to pass `AWS_S3_DATA_SOURCE` to the operator.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by wlinamchurch**
closes: https://github.com/apache/airflow/issues/35271
related: Attempt to fix tests and checks from https://github.com/apache/airflow/pull/35292

This PR adds support to use role arn's for AWS credentials in storage transfer jobs. All of the substantive code changes were made in https://github.com/apache/airflow/pull/35292.

My additional contributions were to get the tests to pass and pre-commit checks to pass.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by wlinamchurch** [comment]
@Taragolis apologies if this is not the correct way to do this but tagging you since you looked at https://github.com/apache/airflow/pull/35292 previously.

**Comment by wlinamchurch** [comment]
@Taragolis - pinging again following the directions of "be persistent". Again, apologies if this is not the correct procedure.

**Review by ferruzzi — APPROVED** [review]
I don't know google provider very well so there may be something I'm missing, but the code LGTM.  If those unit tests are passing and the CI goes green, I think it's good to merge.

**Comment by wlinamchurch** [comment]
Thanks @ferruzzi!

**Comment by ferruzzi** [comment]
@wlinamchurch  You still need one more approval, perhaps drop a message in the slack #contributors channel asking for another set of eyes.

**Review by Taragolis — APPROVED** [review]

**Comment by wlinamchurch** [comment]
Thanks @Taragolis!

**Comment by ferruzzi** [comment]
Congrats!  Thanks for your contribution and your patience!

**Pull request merged**
