### PR TITLE
Kind Cluster on Breeze

### PR DESCRIPTION
**Pull request by edithturn**
Migrating ./breeze legacy kind-cluster [commands] to breeze.

### CODE REVIEW

**Comment by edithturn** [comment]
@potiuk thank you for your feedback, I was creating the group with click and not with "main" that was my mistake.  This is how it is looking now.

Screenshot from 2022-05-14 23-10-23
Screenshot from 2022-05-14 23-10-15

**Comment by potiuk** [comment]
Yep. That's better - you need to rebase though and re-run pre-commits as some of the images generated do not take into account latest changes in rich.

**Comment by potiuk** [comment]
Some conflicts to solve :(

**Comment by edithturn** [comment]
😥  let me try to solve them, Jarek!

**Comment by edithturn** [comment]
@potiuk I was checking /breeze-legacy kind-cluster start
Let me know if all these steps are correct for "start" for ./breeze

1. Validate Docker Version
2. Starts KinD cluster include:
2.1. Pull the latest version of Apache Airflow for a kind cluster: ghcr.io/apache/airflow/main/ci/python3.7:latest
2.1. Checking resources (Memory, CPUs, and Disk)
2.3. Downloading Kind version v0.14.0
2.4. Downloading Kubectl version v1.24.0
2.5. Downloading Helm version v3.6.3
2.6. Creating a cluster of kind

Some functions are already created like Checking resources, and for the others, I'm thinking of a utils file to add the download, helm, kubectl functions, unless they already exist elsewhere.

**Comment by potiuk** [comment]
Yep. Looks right. And yes we can add utils for those - though those are pretty "localised" and likely there is no need to create separate "utils" for them - they would be better in "kind" command python file. We can always move them to "utils" when we find other use for them.

**Comment by edithturn** [comment]
I keep this draft for a long time. @potiuk is taking it with a different approach. I'm closing this draft. :/

**Pull request closed without merging**
