### PR TITLE
Update AWS system tests to use SystemTestContextBuilder

### PR DESCRIPTION
**Pull request by vincbeck**
### Notes
Update AWS system tests to use SystemTestContextBuilder

### Testing
Ran all system tests in this PR successfully

### CODE REVIEW

**Comment by vincbeck** [comment]
The test `Tests / Build and test provider packages wheel (pull_request)` keeps getting canceled

**Comment by potiuk** [comment]
> The test `Tests / Build and test provider packages wheel (pull_request)` keeps getting canceled

Yeah. looks like we have some `pip` back-tracking issue on 2.2.

**Comment by potiuk** [comment]
I will take a look soon

**Comment by vincbeck** [comment]
All tests are passing now :)

**Comment by vincbeck** [comment]
@potiuk :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
