### PR TITLE
Change alembic logging level to WARN

### LINKED ISSUE #30562: alembic Logging
### Apache Airflow version

2.5.3

### What happened

When I call the airflow initdb function, it outputs these lines to the log

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

### What you think should happen instead

There should be a mechanism to disable these logs, or they should just be set to WARN by default

### How to reproduce

Set up a new postgres connection and call:

from airflow.utils.db import initdb
initdb()

### Operating System

MacOS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by geekykayaker**
closes: https://github.com/apache/airflow/issues/30562

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
Do not use WARN. Use WARNING instead. _If_ we agree to do this.

**Review by hussein-awala — COMMENTED** [review]
Currently the alembic logging configuration are loaded from this file without any possibility to update them:
https://github.com/apache/airflow/blob/73e03131d2003ea0c41d8721fff16ed836eb54aa/airflow/utils/db.py#L728-L728

I think it might be a good feature if we add a new Airflow configuration to provide a custom ini file for alembic, then you can update it as you like in your Airflow server. WDYT?

**Comment by geekykayaker** [comment]
Yeah, I think that's a more complete solution, and would certainly resolve this for me.

**Comment by potiuk** [comment]
> Currently the alembic logging configuration are loaded from this file without any possibility to update them:
> 
> https://github.com/apache/airflow/blob/73e03131d2003ea0c41d8721fff16ed836eb54aa/airflow/utils/db.py#L728-L728
> 
> I think it might be a good feature if we add a new Airflow configuration to provide a custom ini file for alembic, then you can update it as you like in your Airflow server. WDYT?

Agree with @hussein-awala - being able to specify alembic.ini would be much better.

**Comment by hussein-awala** [comment]
the issue was closed by #31415

**Pull request closed without merging**
