### PR TITLE
Add optional from_email parameter to EmailOperator

### LINKED ISSUE #33287: Add from_email parameter to EmailOperator
### Description

I am looking for adding from_email parameter to EmailOperator. Currently, the EmailOperator takes the sender email from Airflow Config. 
Which means the emails going from Airflow will always go from same email. 

But we need a way where The EmailOperator user can define the from_email so that sender email can be changed per DAGs. 

And lets make this parameter optional, meaning if user does not provide any email, it will still use the one defined in config.

### Use case/motivation

When developing different DAGs for different Business units which deliver reports to Business users, we need a way to define sender email. So that when business users respond to the email, it goes to right team. 

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shakeelansari63**
closes: https://github.com/apache/airflow/issues/33287

Add optional from_email parameter to EmailOperator which allows users to provide sender emails in Dags.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by shakeelansari63** [comment]
Related to #33287

**Comment by potiuk** [comment]
also related to #30531 cc: @hussein-awala

**Comment by vijayasarathib** [comment]
Have you considered adding test cases to verify the new behavior?

**Comment by shakeelansari63** [comment]
I have updated the test for verifying new from_email parameter.

**Comment by shakeelansari63** [comment]
@potiuk , would you be able to approve the test workflow for latest commit. Need to re-run the tests as I have email test.

**Review by eladkal — CHANGES_REQUESTED** [review]
I'm setting PR to request changes to avoid merge.
Needs to wait for @hussein-awala review as he is working on refactoring this operator into the smtp provider.

(This is technical step not to worry)

**Comment by Franz1241** [comment]
Will this get merged to main?

**Comment by shakeelansari63** [comment]
@hussein-awala , Can you please review this and check if this PR can be merged?

**Comment by shakeelansari63** [comment]
@hussein-awala , Did you get a chance to review this PR?

**Comment by shakeelansari63** [comment]
Look like the Airflow team isn't interested in this feature. Hence closing this PR.

**Pull request closed without merging**
