### PR TITLE
Update link to match what is in pre-commit

### PR DESCRIPTION
**Pull request by danielhoherd**
[The k8s schema repository that has been used for chart pytest has gone stale with no updates in 14 months](https://github.com/instrumenta/kubernetes-json-schema). There are no new updates beyond 1.18.1, and [PRs for updates are not being merged](https://github.com/instrumenta/kubernetes-json-schema/pulls). Airflow is using a more active fork [in pre-commit](https://github.com/apache/airflow/blob/main/.pre-commit-config.yaml#L571), so this change uses [that updated fork](https://github.com/yannh/kubernetes-json-schema) in chart pytests too. This updated fork's latest schema is 1.21.1, and has had changes within the last month.

### CODE REVIEW

**Comment by danielhoherd** [comment]
If anybody wants, we can update to a non-deprecated version of k8s too. There were breaking changes in 1.16 though, so changing from 1.14 to >= 1.16 may create more work, but it would be valid work.

**Comment by danielhoherd** [comment]
[I have opened an issue in the new fork](https://github.com/yannh/kubernetes-json-schema/issues/4) suggesting that netlify be substituted with gh pages so forks can self publish.

**Review by kaxil — COMMENTED** [review]
Tests are failing with the following error:

```
          if http_error_msg:
  >           raise HTTPError(http_error_msg, response=self)
  E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.14.0/serviceaccount-v1.json
```

Link: https://github.com/apache/airflow/pull/16408/checks?check_run_id=2808914953#step:6:967

**Comment by kaxil** [comment]
Just re-running the test after checking the update on the issue you had opened: https://github.com/yannh/kubernetes-json-schema/issues/4#issuecomment-860030638

🤞

**Comment by danielhoherd** [comment]
I wonder if we could just parse our needed content out of URLs like https://raw.githubusercontent.com/kubernetes/kubernetes/v1.17.0/api/openapi-spec/swagger.json

**Review by kaxil — APPROVED** [review]

**Pull request merged**
