### PR TITLE
Fix name format in the batch requests

### LINKED ISSUE #32069: AioRpcError in DataprocCreateBatchOperator
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow version: 2.3.4 (Composer 2.1.12)

I've been using the DataprocCreateBatchOperator with the deferrable=True option. It worked well for the past few months, but an error started appearing on June 21, 2023, at 16:51 UTC. The error message is as follows:
```
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:74.125.69.95:443 {grpc_message:"Request contains an invalid argument.", grpc_status:3, created_time:"2023-06-21T16:51:22.992951359+00:00"}"
```

### What you think should happen instead

The name argument in the [hook code](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/dataproc.py#L1746) follows the format "projects/PROJECT_ID/regions/DATAPROC_REGION/batches/BATCH_ID". However, according to the [Google Cloud DataProc API Reference](https://cloud.google.com/dataproc-serverless/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.GetBatchRequest), it should be in the format "projects/PROJECT_ID/locations/DATAPROC_REGION/batches/BATCH_ID .

### How to reproduce

just run a dataproc operator like this
```
create_batch = DataprocCreateBatchOperator(
        task_id="create_batch",
        batch_id="batch_test",
        deferrable=True,
)
```

### Operating System

Ubuntu 20.04

### Versions of Apache Airflow Providers

_No response_

### Deployment

Google Cloud Composer

### Deployment details

Composer 2.1.12

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by HaeSe0ng**
closes: #32069

The name argument in the [hook code](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/dataproc.py#L1746) follows the format "projects/PROJECT_ID/regions/DATAPROC_REGION/batches/BATCH_ID". However, according to the [Google Cloud DataProc API Reference](https://cloud.google.com/dataproc-serverless/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.GetBatchRequest), it should be in the format "projects/PROJECT_ID/locations/DATAPROC_REGION/batches/BATCH_ID .

### CODE REVIEW

**Review by Swebask — APPROVED** [review]

**Comment by kristopherkane** [comment]
Also experiencing this problem.

**Comment by kristopherkane** [comment]
@HaeSe0ng For the interim, you might be able to switch to non-deferable as it doesn't do a get_batch request up front and instead waits on the initial job request completion.

**Comment by HaeSe0ng** [comment]
@kristopherkane

After the incident in our dags, I confirmed that the issue only occurs when `deferrable` is set to `True`. Therefore, I set `deferrable` to `False` already. I truly appreciate your kindness. Thank you.

FYI. Even if `deferrable` is False, `get_batch` can be called if `AlreadyExist` (batch with given id already exists) error occurs in `DataprocCreateBatchOperator`

**Comment by kristopherkane** [comment]
Yep, we are tracking that deficiency.  This is just the only route for current production Airflow.  We are in contact with GCP and have been told that the API behavior is being reverted.

**Review by hussein-awala — APPROVED** [review]
Thank you for submitting this PR. It looks good!
Let's wait for the CI to pass before merging it.

**Review by potiuk — APPROVED** [review]
Looks it passed/ Merging.

**Comment by HaeSe0ng** [comment]
Thank you for the reviews. May I know what version would include this PR and when would it be released?

**Comment by potiuk** [comment]
For providers it is always it's 'next' and 'when ready'

**Comment by potiuk** [comment]
Srsly. Watch the announcements, and release notes if you want to know when it is released. In case of providers we determine the version and timing **Just** before releasing them - based on what kind of changes are included. It is impossible to tell when and what version it will be. You need to watch. But it will be included in the "next" version (after we release the versions that we were voting on while this one was merged).

**Comment by HaeSe0ng** [comment]
Oh, I see. I'll keep watching the announcements. Thanks for letting me know.

**Pull request merged**
