### PR TITLE
[AIRFLOW-91] Add SSL config option for the webserver

### PR DESCRIPTION
**Pull request by caseyching**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-91

Testing Done:
- Manual testing with and without SSL and -d. Let me know if there is an easy way to test this.

The CLI options are:

$ airflow webserver --ssl_cert <path> --ssl_key <path>

and the airflow.cfg options are:

web_server_ssl_cert = <path>
web_server_ssl_key = <path>

### CODE REVIEW

**Comment by caseyching** [comment]
Ping. Could someone take a look at this?

**Comment by bolkedebruin** [comment]
LGTM, tests could be with self signed certificates. 

@caseyching could you please update the documentation and create a proper commit message (defining what not how, usage should be in the docs). Then I will merge.

**Comment by caseyching** [comment]
Thanks for looking at this. I'll make the updates and resend tomorrow.

**Comment by caseyching** [comment]
The commit message and docs are updated now.

**Comment by caseyching** [comment]
I'm pretty sure that build failure is unrelated to this change.

**Comment by caseyching** [comment]
@bolkedebruin can you take another look at this? Is there some way I can trigger another test run?

**Comment by bolkedebruin** [comment]
LGTM! Thanks for the work!

**Pull request closed without merging**
