### PR TITLE
[AIRFLOW-XXXX] Small grammar fixes in Best Practices doc

### PR DESCRIPTION
**Pull request by petedejoy**
---
This PR adds some grammatical and structural improvements to the FAQ doc currently available at https://airflow.apache.org/docs/stable/best-practices.html.

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
You still need to update commit title though :(

**Comment by petedejoy** [comment]
My apologies! Jumped the gun on this- was reading through this doc and just clicked the `Suggest a change on this page` link, which pushed me to update the .rst file directly and make a PR in one fell swoop.

I will say, the doc editing flow for someone who isn't deeply familiar with the PR process is a bit odd; I was prompted to make the commit with the default message  _before_ being given the PR checklist that tells me what to do with commit messages. Definitely on me for not brushing up on the entire process beforehand, but for a user reading through docs who just wants to help clean them up, it's a bit challenging.

Regardless, I'll roll it back and make sure the proper commit message is used. I also have some other updates to this doc that I plan on making.

**Comment by potiuk** [comment]
No worries! Thanks for trying to improve things :). It's just our automation around merging makes some rules necessary!

**Comment by petedejoy** [comment]
Totally understand. I'll have the reverted commit with some more updates coming up shortly. Thanks, @potiuk!

**Review by potiuk — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Thanks @petedejoy

**Pull request merged**
