### PR TITLE
[AIRFLOW-5739] Move google cloud platform functions to providers package

### PR DESCRIPTION
**Pull request by chicochico**
…ions

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-5739\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5739
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes: Move google cloud platform functions to providers package

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Already tested

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add backward compatiblity and add deprecation warnings?

**Comment by chicochico** [comment]
@mik-laj I added the warnings and backward compatibility, I also rebased to the current master.

**Comment by mik-laj** [comment]
Travis is sad. We also have warnings in the airflow.contrib package. Can you update them?  Travis is sad. Can you fix it?  Can you add tests in https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py?

**Comment by mik-laj** [comment]
Done. I did it while reorganizing the remaining packages.

**Pull request closed without merging**
