### PR TITLE
[AIRFLOW-XXX] Add Overstock to list of companies

### PR DESCRIPTION
**Pull request by mhousley**
Please add Overstock to the list of companies using Airflow.
best,
Matt

### CODE REVIEW

**Comment by jgao54** [comment]
I created a [JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2057) for your PR. Please modify your commit message with the JIRA name : AIRFLOW-2057 so I can merge your PR. Thanks!

**Comment by mhousley** [comment]
Thanks!

**Comment by bolkedebruin** [comment]
@jgao54 I think for these kind of changes we can accept AIRFLOW-XXX. What do you think?

**Comment by jgao54** [comment]
@bolkedebruin  I'm totally fine with it personally :)

**Pull request closed without merging**
