### PR TITLE
Improve CI test that prepares and test python client

### PR DESCRIPTION
**Pull request by potiuk**
The test for python client require locally installed airflow with some providers prepared from sources. We have been preparing the selected packages and installing them, but sometimes this required to add new package there.

To make it simpler, we can instead prepare and install all the packages - this will be pretty fast with `uv` and we will avoid to manually modify the CI tests every time we add some package that requires installation.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — APPROVED** [review]

**Comment by potiuk** [comment]
Actually - I've hit the same problem that made the breeze ci image necessary - hard to install Airflow with all dependencies in consistent way in CI (uv wants to build kerberos :). I think I will actually change it to run the client  inside breeze - but I will defer it after coming back from Ireland (I am going to be far less available next week).

**Comment by potiuk** [comment]
converted to draft for now

**Comment by potiuk** [comment]
I will create an issue for that maybe @gopidesupavan or others would like to take that :)

**Comment by potiuk** [comment]
I added https://github.com/apache/airflow/issues/44020 describing what needs to be done

**Pull request closed without merging**
