### PR TITLE
Dag tags use set instead of list

### PR DESCRIPTION
**Pull request by zhongjiajie**
Dag tags store in db without duplicate name in each
dag, but list could contain duplicate elements, so
it's better to change tags attr in Dag from list to
set

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
We don't need to do this: Check https://github.com/apache/airflow/pull/6489/files#r347050841

**Comment by BasPH** [comment]
@kaxil I think it might be worth changing this call to a set: https://github.com/apache/airflow/blob/master/airflow/models/dag.py#L1532. It seems currently the DagTags are made unique when fetching from the DB.

Other than that, we can close this pull request IMO.

**Comment by zhongjiajie** [comment]
Sorry for reply late due to have cold. @kaxil @BasPH I change dag tags from list to set due to two main reason:
1. In https://github.com/apache/airflow/blob/6ba672eaab84fd71dc8a6f2dd5791651e5a96c38/airflow/models/dag.py#L1654-L1660 we have unique key on `name and dag_id` but in https://github.com/apache/airflow/blob/6ba672eaab84fd71dc8a6f2dd5791651e5a96c38/airflow/models/dag.py#L234 we define `tags` in list(which may contain duplicate element). Since each dag can not contain duplicate tag, should we define `Dag.tags` without duplicate element and using set would be a solution
2. Users use tag when they define DAG file with set, them may came to their mind `DAG tags is a set and no duplicate element`. I think will be more clear. I know we will drop the duplicate element by code or database constraint, but maybe avoid it by user define side would be better.

WDYT

**Comment by zhongjiajie** [comment]
BTW, I submit this when I review bulk sync to database code in https://github.com/apache/airflow/pull/8231

**Comment by kaxil** [comment]
> Sorry for reply late due to have cold. @kaxil @BasPH I change dag tags from list to set due to two main reason:
> 
> 1. In https://github.com/apache/airflow/blob/6ba672eaab84fd71dc8a6f2dd5791651e5a96c38/airflow/models/dag.py#L1654-L1660
>     we have unique key on `name and dag_id` but in https://github.com/apache/airflow/blob/6ba672eaab84fd71dc8a6f2dd5791651e5a96c38/airflow/models/dag.py#L234
>     we define `tags` in list(which may contain duplicate element). Since each dag can not contain duplicate tag, should we define `Dag.tags` without duplicate element and using set would be a solution
> 2. Users use tag when they define DAG file with set, them may came to their mind `DAG tags is a set and no duplicate element`. I think will be more clear. I know we will drop the duplicate element by code or database constraint, but maybe avoid it by user define side would be better.
> 
> WDYT

I think we can just change the line @BasPH mentioned (https://github.com/apache/airflow/blob/master/airflow/models/dag.py#L1532. ) to a `set`. We can allow user to submit any Iterable (List, Set etc)

**Comment by zhongjiajie** [comment]
Ok, if we just need to change one line, I prefer to do it in https://github.com/apache/airflow/pull/8231 and close this PR

**Pull request closed without merging**
