### PR TITLE
[AIRFLOW-7102] Add try_number to airflow context

### PR DESCRIPTION
**Pull request by cong-zhu**
---
Issue link: [AIRFLOW-7102](https://issues.apache.org/jira/browse/AIRFLOW-7102)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by cong-zhu** [comment]
@KevinYang21 PTAL

**Review by KevinYang21 — APPROVED** [review]
CI looks wired, it seems to have already passed.

**Comment by cong-zhu** [comment]
@KevinYang21 Yes the CI already passed

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
One more small thing. Can you also please add this to https://airflow.readthedocs.io/en/latest/macros-ref.html @cong-zhu ?

**Comment by cong-zhu** [comment]
@potiuk, it seems there's not section for environment variables yet.

**Comment by potiuk** [comment]
Was not that about the context that is then available to templates in Jinja ? Or am I wrong about it ?

**Comment by cong-zhu** [comment]
@potiuk, it's different from that. those are variables exported to the environment.

**Comment by potiuk** [comment]
OK. I looked it up now. No wonder I did not know about it - because it is not documented :). So maybe it's a good time to add it then? 

I am happy to collaborate on that/propose structure etc.

**Comment by cong-zhu** [comment]
I think we need a separate Jira ticket on it as the whole story of environment variables is missing in the document.

**Comment by KevinYang21** [comment]
I feel it can go either way, maybe a bit more clean to put that into a seperate commit. @potiuk would love to hear your opinion on where should this piece of doc lives, and if possible how it should look like.

**Comment by BasPH** [comment]
Slightly off-topic question: I have no idea why we have some context variables as environment variables, and some context variables in the task instance context (dict).

I'd say consistency is key so either have all variables as both env vars + dict, or stick to one single method. Any ideas @KevinYang21 @potiuk?

**Comment by potiuk** [comment]
Yeah. That's all weird. I am ok with approving that one before fixing it but maybe we can agree first how we are going to fix it and one of us do it :). I think once we do that then @KevinYang21  - we can discuss where this piece of documentation should go (I'd say next to macros).

**Comment by cong-zhu** [comment]
@KevinYang21 can we merge this change?

**Pull request closed without merging**
