### PR TITLE
Extract build images to composite actions

### PR DESCRIPTION
**Pull request by potiuk**
Extract Build images to composite actions

Follow-up after #27371 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Only last commit counts

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
We need to get https://github.com/apache/airflow/pull/27371 merged first @eladkal :(

**Comment by potiuk** [comment]
(it is based on that one).

**Comment by eladkal** [comment]
Forgot to click the publish button :)

**Comment by potiuk** [comment]
Running additional tests here: https://github.com/potiuk/airflow/pull/283/checks to see that build image workflows still work for main (run it before but I want to be absolutely sure).

**Review by pierrejeambrun — APPROVED** [review]

**Comment by potiuk** [comment]
Found #27385 during testing, but it's not blocking this one).

**Comment by potiuk** [comment]
Also found #27387 - but that was there before. Merging.

**Pull request merged**
