### PR TITLE
Use Python 3.9 as target version for Ruff & Black rules

### PR DESCRIPTION
**Pull request by kaxil**
Since we dropped support of Python 3.8 (after it reach EOL), we missed changing rules for black & ruff.

For reviewers: easier to just review [first commit](https://github.com/apache/airflow/pull/44298/commits/dfbbde809d5e07870b1e5f07bdc17803ac52c977), second commit is mostly  autogen code

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]
Interesting. How can it be that I over-looked the changes in the first commit when removing Python 3.9 support?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Nice - but seems there are still some troubles with collection changes.

BTW. I would like - before merge and when green re-run it locally and reapply ruff auto-changes - to see if I come up with small set of reviewable changes (aka - reproducibility check :)

**Comment by kaxil** [comment]
> Nice - but seems there are still some troubles with collection changes.
> 
> 
> 
> BTW. I would like - before merge and when green re-run it locally and reapply ruff auto-changes - to see if I come up with small set of reviewable changes (aka - reproducibility check :)
> 
> 

Done, rebased, ran ruff, force pushed locally

**Comment by kaxil** [comment]
> Interesting. How can it be that I over-looked the changes in the first commit when removing Python 3.9 support?

You already had to many changes to handle :)

**Comment by potiuk** [comment]
And one more here @jscheffl ;) https://github.com/apache/airflow/pull/44328

**Comment by kaxil** [comment]
> And one more here @jscheffl ;) #44328

:D

**Comment by kaxil** [comment]
> Interesting. How can it be that I over-looked the changes in the first commit when removing Python 3.9 support?

All good man

**Comment by jscheffl** [comment]
> And one more here @jscheffl ;) #44328

Hope this was the last one... or shall I go hunting again? :-D

**Comment by kaxil** [comment]
> > And one more here @jscheffl ;) #44328
> 
> Hope this was the last one... or shall I go hunting again? :-D

If you wouldn't be missing such things, I would consider you a bot 😄

**Pull request merged**
