### PR TITLE
[AIRFLOW-914] Disable test_backfill_examples on Travis

### PR DESCRIPTION
**Pull request by sekikn**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-914

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

BackfillJobTest.test_backfill_examples takes over 5 minutes to execute
on Travis and it's about 25% of the entire time. Disabling it on Travis
makes more quick feedback for developers possible.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No additional test, since it's modification for test code itself.
I confirmed on Travis that test_backfill_examples was skipped and the running time was significantly reduced. For example, the time for Python 2.7 x MySQL is reduced from 21 min 4 sec to 16 min 50 sec.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by sekikn** [comment]
The CI failure started from [#8079](https://travis-ci.org/apache/incubator-airflow/builds/287784228) and seems to be irrelevant to this fix.

**Comment by Fokko** [comment]
@sekikn Disabling a test on Travis does not sound like a good idea. Before merging code into master, we want to make sure everything behaves as expected. Backfilling is a very important feature of Airflow, that we definitely want to test.

What are you trying to test? And why can't you test locally? This will give you the fastest feedback loop. Personally I use Docker a lot to test (Easy to switch between Python2 and Python3):
```
Fokkos-MBP:Desktop fokkodriesprong$ docker run --rm -t -i  python bash
root@81d6bd3e4a16:/# git clone https://github.com/airflow/airflow.git /airflow/
Cloning into '/airflow'...
remote: Counting objects: 23699, done.
remote: Total 23699 (delta 0), reused 0 (delta 0), pack-reused 23698
Receiving objects: 100% (23699/23699), 12.67 MiB | 199.00 KiB/s, done.
Resolving deltas: 100% (16751/16751), done.
Checking connectivity... done.
root@81d6bd3e4a16:/# cd /airflow/
root@ae1f3e7af284:/airflow# pip install -e .[devel]
root@ae1f3e7af284:/airflow# pip install unicodecsv psycopg2 hive-thrift-py
... Lot of output ...
root@ae1f3e7af284:/airflow# airflow initdb
root@d11ac6a39103:/airflow# nosetests airflow/the/file/that/you/want/to/test.py
```

Instead of cloning, you can also mount a volume of your working directory inside of docker, to have the ability to work with your favorite IDE.

**Comment by sekikn** [comment]
Thanks for the comment @fokko. The original JIRA said as follows and there was no objection on that, so I implemented the latter ("not run at all if on Travis").

> BackfillJobTest.test_backfill_examples takes over 5 minutes to execute on Travis. It should use a whitelist instead or not run at all if on Travis.

But now I also think it was somewhat sloppy, so I'll try the whitelist. :)

**Comment by bolkedebruin** [comment]
@sekikn if you want to disable the tests, make sure that everything is covered by (unit)tests. Ie. this probably means writing other tests. Some work indeed, hence we havent done so yet. It might be  better to split up the tests on Travis so they only run once in the matrix...

**Comment by ron819** [comment]
Is this still needed?

**Comment by ashb** [comment]
We don't want to disable backfill tests entirely. Closing this PR, but one to reduce the number of backfill tests that are run would be welcomed.

**Pull request closed without merging**
