### PR TITLE
[AIRFLOW-766,775,2364] fix issue with jdbc/dbapi autocommit

### PR DESCRIPTION
**Pull request by artwr**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-766
    - https://issues.apache.org/jira/browse/AIRFLOW-775
    - https://issues.apache.org/jira/browse/AIRFLOW-2364

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Some unit tests for dbapi

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by artwr** [comment]
Working on a fix for the tests @bolkedebruin @Fokko. Will ping when ready.

**Comment by bolkedebruin** [comment]
O o o I was too early with merging 😀  thanks @artwr !

**Comment by artwr** [comment]
I should have checked the build on my fork before submitting the PR :) But I appreciate the push for the new version.

**Comment by artwr** [comment]
Issue fixed here https://github.com/apache/incubator-airflow/pull/3258

**Pull request merged**
