### PR TITLE
update celery to 4.4.2

### PR DESCRIPTION
**Pull request by auvipy**
---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by nuclearpinguin** [comment]
Should we wait for response to this question https://github.com/celery/kombu/issues/1063#issuecomment-600434919 ?
>I am reopening, but can you try the latest celery==4.4.2 and reproduce this again?

https://github.com/celery/kombu/issues/1063

**Comment by auvipy** [comment]
> Should we wait for response to your question [celery/kombu#1063 (comment)](https://github.com/celery/kombu/issues/1063#issuecomment-600434919) ?
> 
> > I am reopening, but can you try the latest celery==4.4.2 and reproduce this again?
> 
> [celery/kombu#1063](https://github.com/celery/kombu/issues/1063)

I think we should :) Btw, I would like to be an active airflow contributor. it would be awesome if you can nevigate meto the celery specific codes?

**Comment by nuclearpinguin** [comment]
> I would like to be an active airflow contributor. it would be awesome if you can nevigate meto the celery specific codes?

That would be awesome! One of Airflow executors uses Celery, the code is here:
https://github.com/apache/airflow/blob/master/airflow/executors/celery_executor.py

Here you can find the description of CeleryExecutor architecture done by @mik-laj :
https://airflow.readthedocs.io/en/latest/executor/celery.html

Also together with @dimberman we are working on autoscaling celery workers, here's Daniels blogpost about it:
https://www.astronomer.io/blog/the-keda-autoscaler/

Finally, I encourage you to look at our contributing guidelines that include a lot of useful information
https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst:

**Comment by nuclearpinguin** [comment]
Also there is some ongoing work around celery:
https://github.com/apache/airflow/pull/7542
https://github.com/apache/airflow/pull/6961
https://github.com/apache/airflow/pull/6905

**Comment by potiuk** [comment]
> I think we should :) Btw, I would like to be an active airflow contributor. it would be awesome if you can nevigate meto the celery specific codes?

Fantastic! Celery is our hands-down best deployment method - and now with added auto-scaling capabilities and KEDA even more so.

**Comment by auvipy** [comment]
amazing!! thanks, guys for the kind guidance.

**Comment by kaxil** [comment]
Thanks @auvipy for your contribution. Hope to see more in the coming months :) Let us know if you need any help. 

We also have an active Airflow Slack channel at https://apache-airflow-slack.herokuapp.com/

**Comment by auvipy** [comment]
I want to be a regular contributor to airflow and improve celery upstream :)

**Comment by turbaszek** [comment]
> celery/kombu#1063 (comment)

Does this issue can potentially impact Airflow? @kaxil @auvipy ? I know about this issue because I one of our customers once reported something similar in Airflow.

**Comment by auvipy** [comment]
> > [celery/kombu#1063](https://github.com/celery/kombu/issues/1063) (comment)
> 
> Does this issue can potentially impact Airflow? @kaxil @auvipy ? I know about this issue because one of our customers once reported something similar in Airflow.

if they use Redis and there is really issue in kombu. but that is still unclear that it is kombu issue.

**Comment by auvipy** [comment]
it seems to upgrade to Redis server 5 solved the issue! https://github.com/celery/kombu/issues/1063#issuecomment-607532782

**Pull request merged**
