### PR TITLE
 [AIRFLOW-4075] minikube enviroment lack of init airflow db step

### PR DESCRIPTION
**Pull request by jie8357IOII**
Make sure you have checked _all_ steps below.

### Jira
No jira.

### Description
When use kubenetes/kube/deplopy to deploy airflow on minikube, always failure in init container.
Because lack of 'airflow' database in postgresql, I add init 'airflow' db step in python.

### CODE REVIEW

**Comment by OmerJog** [comment]
@jie8357IOII You have errors to resolve:
```
Traceback (most recent call last):
  File "/app/.tox/py35-backend_sqlite-env_docker/bin/airflow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/app/airflow/bin/airflow", line 32, in <module>
    args.func(args)
  File "/app/airflow/utils/cli.py", line 74, in wrapper
    return f(*args, **kwargs)
  File "/app/airflow/bin/cli.py", line 513, in run
    dag = get_dag(args)
  File "/app/airflow/bin/cli.py", line 150, in get_dag
    'parse.'.format(args.dag_id))
```

Also it requires to open a Jira ticket and put the number of the ticket in the commit message.

**Comment by XD-DENG** [comment]
@jie8357IOII  These scripts are for CI usage only. I don't think you're supposed to deploy airflow on minikube using them.

**Comment by jie8357IOII** [comment]
I see, maybe I should put it in 'kube/deploy.sh' or 'kube/postgres.yaml'.

**Comment by XD-DENG** [comment]
@jie8357IOII  IMO we don't need to make this change in this codebase. Let me know your thought?

**Comment by jie8357IOII** [comment]
@XD-DENG 
We manually create 'airflow' database in postgresql when we start airflow cluster first time on minikube.
Do not need to make it automatic?

**Comment by XD-DENG** [comment]
Hi @jie8357IOII as shared earlier, most (if not all) K8S-related scripts in this codebase are for CI purpose only. DB creation is already handled by the CI process itself. All the K8S-related code in this code base are not supposed to be used for deploying airflow cluster.

**Comment by jie8357IOII** [comment]
Got it! So this feature maybe not suite 'CI'.
Close it.

**Comment by XD-DENG** [comment]
@jie8357IOII Thanks. Look forward to other contributions from you :-)

**Pull request closed without merging**
