### PR TITLE
Handle `AUTH_ROLE_PUBLIC` in FAB auth manager

### PR DESCRIPTION
**Pull request by vincbeck**
`AUTH_ROLE_PUBLIC` is an option of FAB auth manager, it should not be handled in Airflow.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jscheffl — COMMENTED** [review]
We discussed in Airflow 3 Devcall that Provider changes and Core adjustments should not be mixed. Can you please separate the changes?

As it seems dependencies between provider and core are adjusted - are you sure the provider will stay compatible with Airflow 2.9?

**Comment by vincbeck** [comment]
> We discussed in Airflow 3 Devcall that Provider changes and Core adjustments should not be mixed. Can you please separate the changes?
> 
> As it seems dependencies between provider and core are adjusted - are you sure the provider will stay compatible with Airflow 2.9?

Yes, similar to #42042, both changes (providers and core) are interrelated and it is impossible to split them. I am basically moving some features from core to providers so the provider will be compatible with Airflow 2.9. The only incompatibility is Airflow 3 with current or older version of FAB (because the feature is neither in Airflow and providers) but we decided (see [comment](https://github.com/apache/airflow/pull/42042#issuecomment-2333313742)) that Airflow 3 will require last version of Fab

**Review by pierrejeambrun — COMMENTED** [review]
Looking nice. So that means I can safely remove the `TODO` comment in my other PR.

As I understand the backend is now checking automatically the `AUTH_ROLE_PUBLIC` if the user is `None` that's cleaner 👍

**Comment by vincbeck** [comment]
I cannot reproduce and understand why the compat tests are failing. I need to debug directly in the PR. Setting the PR in draft until I figure it out

**Comment by jscheffl** [comment]
> I cannot reproduce and understand why the compat tests are failing. I need to debug directly in the PR. Setting the PR in draft until I figure it out

Have you tried to run the compat tests local? Don't know how powerful your laptop is but for me this is a faster round trip.
```
breeze testing tests --python 3.8 --run-in-parallel --parallel-test-types "Providers[whatever_you_want]" --use-packages-from-dist --package-format wheel --use-airflow-version "2.8.4" --airflow-constraints-reference constraints-2.8.4 --install-airflow-with-constraints --providers-skip-constraints --skip-providers "cloudant fab"
```

**Comment by vincbeck** [comment]
> > I cannot reproduce and understand why the compat tests are failing. I need to debug directly in the PR. Setting the PR in draft until I figure it out
> 
> Have you tried to run the compat tests local? Don't know how powerful your laptop is but for me this is a faster round trip.
> 
> ```
> breeze testing tests --python 3.8 --run-in-parallel --parallel-test-types "Providers[whatever_you_want]" --use-packages-from-dist --package-format wheel --use-airflow-version "2.8.4" --airflow-constraints-reference constraints-2.8.4 --install-airflow-with-constraints --providers-skip-constraints --skip-providers "cloudant fab"
> ```

Yep I did, it complains because the amazon provider package is not installed. I could not figure it out why. But I actually found out the reason why the tests are failing by debugging by pushing things and waiting the CI for feedback :D

**Comment by vincbeck** [comment]
CI is (finally) green!

**Review by jscheffl — APPROVED** [review]

**Pull request merged**
