### PR TITLE
Add `init_command` parameter to `MySqlHook`

### LINKED ISSUE #33300: MySqlHook add support for init_command
### Description

There is currently no way to pass an `init_command` connection argument for a mysql connection when using either the `mysqlclient` or `mysql-connector-python` libraries with the MySql provider's `MySqlHook`.

Documentation for connection arguments for `mysqlclient` library, listing `init_command`:
https://mysqlclient.readthedocs.io/user_guide.html?highlight=init_command#functions-and-attributes

Documentation for connection arguments for `mysql-connector-python` library, listing `init_command`:
https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html

There can be many uses for `init_command`, but also what comes to mind is why do we explicitly provide support to certain connection arguments and not others?

### Use case/motivation

For my own use right now I am currently am subclassing the hook and then altering the connection arguments to pass in `init_command` to set the `time_zone` session variable to UTC at connection time, like so:

```python
conn_config['init_command'] = r"""SET time_zone = '+00:00';"""
```

Note: This is just an example, there can be many other uses for `init_command` besides the example above. Also, I am aware there is a `time_zone` argument for connections via the `mysql-connector-python` library, however that argument is not supported by connections made with `mysqlclient` library. Both libraries do support the `init_command` argument.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by alexbegg**
This allows the addition of `init_command` as a `MySqlHook` parameter.

`init_command` is a connection argument to set an initial command to issue to the MySQL server upon connection. It is available as both a `mysqlclient` connection attribute (https://mysqlclient.readthedocs.io/user_guide.html?highlight=init_command#functions-and-attributes) and a `mysql-connector-python` connection attribute (https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html).

For example, to set the session's `time_zone` to UTC you can set in a `MySqlHook` an `init_command` parameter as shown:
```python
MySqlHook(init_command="SET time_zone = '+00:00';")
```
or in a SQL operator shown using `hook_params` (which should return "+00:00"):
```python
SQLExecuteQueryOperator(
    task_id="check_time_zone",
    conn_id="mysql_default",
    hook_params={"init_command": "SET time_zone = '+00:00';"},
    sql=r"""SELECT @@SESSION.time_zone;""",
    autocommit=True,
    show_return_value_in_logs=True
)
```

closes: #33300 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by alexbegg** [comment]
I have ran the tests and have tested a DAG locally with a MySQL connection created with the extra set to
```json
{
  "init_command": "SET time_zone = '+00:00';"
}
```
and a task to output the `@@SESSION.time_zone` as shown:
```python
SQLExecuteQueryOperator(
    task_id='check_time_zone',
    sql=r"""@@SESSION.time_zone;""",
    autocommit=True,
    show_return_value_in_logs=True
)
```
with the `init_command` set in the connection as shown the task returned `+00:00` as expected, without it the task returned the default time_zone of `SYSTEM`.

**Review by potiuk — CHANGES_REQUESTED** [review]
Main reason we are not adding all the potential options to extras is potential problem with security.

Allowing to execute arbitrary command via "extra" is potential security risk. This gives the user who can edit connections more priviliedges than needed. We had a number of security vulnerabilities, where we had to remove features like that from connection extras.

While we have modified our security model description https://airflow.apache.org/docs/apache-airflow/stable/security/index.html and hopefully informed our users that users who have access to edit connection can have more priviledges, adding a new option for that knowingly is a bad idea.

The "extra" parameters in ideal world should only be limited to declarative parameters, that merrely configure options of the underlying driver. passing arbitrary code to execute is a no-go.

It's quite ok to add an init_command when you initilalize the Hook - and with sql operator you can pass such parameter via hook_params, so that DAG authors could modify it. so if you can chang e it so that init command canot be passed by extra, but by hook parameter, then I'd be perfectly fine with accepting such PR.

**Comment by alexbegg** [comment]
Thank you for the explanation. I see your point and will revise this PR to turn this into a hook parameter.

**Comment by alexbegg** [comment]
Ok, this is changed to a `MySqlHook` param now, and the PR description is updated

**Comment by alexbegg** [comment]
> It's quite ok to add an init_command when you initilalize the Hook - and with sql operator you can pass such parameter via hook_params, so that DAG authors could modify it.

Oh, I didn't even know about the `hook_params` sql operator parameter, that will be exactly what I need, a way to use this in a `SQLExecuteQueryOperator`. Thanks for the heads up!

**Comment by alexbegg** [comment]
Moving to a draft until I rebase the branch and make it ready

**Comment by alexbegg** [comment]
@potiuk this is now ready for review again

**Comment by alexbegg** [comment]
@potiuk it still says "change requested" although I already made the requested change, can you review it again?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Cool. Just got to it now. Please exercise a bit of patience next time. No need to hurry things like that.

**Pull request merged**
