### PR TITLE
Fix py/url-redirection by replacing request.referrer by get_redirect()

### PR DESCRIPTION
**Pull request by hussein-awala**
`redirect(location=request.referrer)` is not safe, and we don't use it in the webserver, instead we use `BaseView.get_redirect()` to get the original the previous url.

Is there any specific reason to use request.referrer in #33932? (I don't think so)

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
Does this also need to call `update_redirect`?

**Comment by potiuk** [comment]
> Does this also need to call `update_redirect`?

Yep. I thinl it should, otherwise back/resubmit button wil skip over  it.

**Review by uranusjr — APPROVED** [review]

**Review by Taragolis — APPROVED** [review]

**Review by pierrejeambrun — APPROVED** [review]

**Comment by pierrejeambrun** [comment]
Changed milestone for 2.7.2, this is security related and be released as bugfix I believe.

**Comment by hussein-awala** [comment]
I used the same milestone as #33932 because the change is not released yet. But it looks like the other PR is a bug-fix too.

**Comment by pierrejeambrun** [comment]
Oh I see, I believe 33932 started as a fix but ended up adding new options and is now more of an ‘improvement’.

Putting back 2.8.0, sorry.

**Pull request merged**
