### PR TITLE
Drop support for k8s 1.23

### PR DESCRIPTION
**Pull request by jedcunningham**
k8s 1.23 has reached EOL.

### CODE REVIEW

**Review by eladkal — APPROVED** [review]
Do we need to add news fragment for next feature release?

**Comment by potiuk** [comment]
Not that I am against it but:

```
We drop support for Python and Kubernetes versions when they reach EOL. **Except for Kubernetes, a version stays supported by Airflow if two major cloud providers still provide support for it.** 
```

**Comment by jedcunningham** [comment]
We haven't in the past when dropping stuff for EOL reasons.

**Comment by potiuk** [comment]
(And yes, I would be happy to drop support immediately after they reach EOL, but it's not what we agreed to, unfortunately).

**Comment by jedcunningham** [comment]
Hmm, I wasn't aware of the k8s exception. Let me have a think on that. Fwiw, as of today 2 support 1.22 still.

**Comment by potiuk** [comment]
> Hmm, I wasn't aware of the k8s exception. Let me have a think on that. Fwiw, as of today 2 support 1.22 still.

Yep. I noticed :)

**Comment by jedcunningham** [comment]
Okay, opened #29884 so it's more visible!

**Pull request closed without merging**
