### PR TITLE
Builds and pushes images in parallel

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
I think this one is last to go for the parallelism

**Comment by ashb** [comment]
Do you have a build run in your own fork where these changed files have been used?

**Comment by potiuk** [comment]
> Do you have a build run in your own fork where these changed files have been used?

Yeah. I am mostly running and adding some fixes in my own fork, once I get it green, I will push it here

**Comment by potiuk** [comment]
Converted to Draft for now.

**Comment by potiuk** [comment]
@ashb the fork build is here: https://github.com/potiuk/airflow/actions/runs/764521494 (build image). I think it should be green now

**Comment by potiuk** [comment]
Closing it. There are at most marginal improvements and multitude of problems when images are build in parallel. Docker build does not cope well with several builds runnning in parallel (apparently creating layers in docker are single threaded) also building three prod images on the same public  Github runner uses far too much space.

**Pull request closed without merging**
