### PR TITLE
[AIRFLOW-2448] Enhance HiveCliHook.load_df to work with datetime

### PR DESCRIPTION
**Pull request by sekikn**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2448
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

HiveCliHook.load_df can not handle DataFrame
which contains datetime for now.
This PR enhances it to work with datetime
and addresses some flake8 issues.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Added tests.hooks.test_hive_hook:TestHiveCliHook.test_load_df_with_data_types.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Buongiorno @gglanzani, 

Can you take a look at this? My knowledge of Apache Hive is futile compared to yours..

Cheers!

**Comment by gglanzani** [comment]
@Fokko It seems good to me, valid use case.

@sekikn Could you close and re-open to re-trigger the Python 3.5 tests, that are failing for some other reason?

**Comment by Fokko** [comment]
Thanks @gglanzani 

The tests seem to fail on Snakebite, which is not Python 3.x compatible:
```
======================================================================
1) ERROR: Failure: SyntaxError (invalid syntax (client.py, line 1473))
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py35-backend_sqlite/lib/python3.5/site-packages/nose/failure.py line 39 in runTest
      raise self.exc_val.with_traceback(self.tb)
    .tox/py35-backend_sqlite/lib/python3.5/site-packages/nose/loader.py line 418 in loadTestsFromName
      addr.filename, addr.module)
    .tox/py35-backend_sqlite/lib/python3.5/site-packages/nose/importer.py line 47 in importFromPath
      return self.importFromDir(dir_path, fqname)
    .tox/py35-backend_sqlite/lib/python3.5/site-packages/nose/importer.py line 94 in importFromDir
      mod = load_module(part_fqname, fh, filename, desc)
    /home/travis/build/apache/incubator-airflow/.tox/py35-backend_sqlite/lib/python3.5/imp.py line 245 in load_module
      return load_package(name, filename)
    /home/travis/build/apache/incubator-airflow/.tox/py35-backend_sqlite/lib/python3.5/imp.py line 217 in load_package
      return _load(spec)
    <frozen importlib._bootstrap> line 693 in _load
      
    <frozen importlib._bootstrap> line 673 in _load_unlocked
      
    <frozen importlib._bootstrap_external> line 697 in exec_module
      
    <frozen importlib._bootstrap> line 222 in _call_with_frames_removed
      
    tests/__init__.py line 27 in <module>
      from .core import *
    tests/core.py line 2317 in <module>
      from airflow.hooks.hdfs_hook import HDFSHook
    airflow/hooks/hdfs_hook.py line 25 in <module>
      from snakebite.client import Client, HAClient, Namenode, AutoConfigClient
   SyntaxError: invalid syntax (client.py, line 1473)
```

Please don't naively retrigger the tests if it is clear that something is wrong. This isn't a flaky test. I've addressed this earlier here: https://github.com/apache/incubator-airflow/pull/3342#issuecomment-389439015

**Comment by gglanzani** [comment]
@Fokko This is failing on `/home/travis/build/apache/incubator-airflow/tests/dags/test_impersonation_custom.py`, what does it have to do with this?

**Comment by Fokko** [comment]
Not much, apparently the Snakebite stuff gets pulled in. But the test isn't executed under 3.5, so we also don't know if these tests pass under 3.5. Restarting the tests will give the same issues, so we first have to fix master.

**Comment by gglanzani** [comment]
@Fokko Clear! I'll leave it up to you then!

**Comment by sekikn** [comment]
Thanks for the review @gglanzani @Fokko! I'll re-trigger the CI once #3365 is merged.

**Comment by kaxil** [comment]
Please rebase with master as https://github.com/apache/incubator-airflow/pull/3365 is merged.

**Comment by sekikn** [comment]
Rebased on master. Let's see if CI succeeds...

**Comment by sekikn** [comment]
The CI failures seem to be caused by an environmental problem. Error messages say that task_instance table doesn't exist.

**Comment by gglanzani** [comment]
@Fokko Seems indeed very unrelated to this code, it fails way before it starts testing this patch

**Comment by kaxil** [comment]
Please rebase with master. The CI has been fixed.

**Comment by sekikn** [comment]
Thanks @Fokko @kaxil, rebased on master.

**Comment by Fokko** [comment]
@kaxil @sekikn Master still looks dark red here: https://travis-ci.org/apache/incubator-airflow/branches

**Comment by sekikn** [comment]
Hmm. According to the CI result, perhaps AIRFLOW-2441 introduced a new bug around string encoding on Python3. I'll investigate it together.

**Comment by sekikn** [comment]
Updated the PR. Fixed around output encoding and confirmed that it worked as expected both for Python2 and 3 with Hive 1.2.1.

**Pull request closed without merging**
