### PR TITLE
Revising flower_url_prefix considering default value

### LINKED ISSUE #27402: #26415 Broke flower dashboard
### Discussed in https://github.com/apache/airflow/discussions/27401

<div type='discussions-op-text'>

<sup>Originally posted by **Flogue** October 25, 2022</sup>
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.4.1

### Kubernetes Version

1.24.6

### Helm Chart configuration

```
flower:
  enabled: true
```

### Docker Image customisations

None

### What happened

Flower dashboard is unreachable.
"Failed to load resource: net::ERR_CONNECTION_RESET" in browser console

### What you think should happen instead

Dashboard should load.

### How to reproduce

Just enable flower: 

```
helm install airflow-rl apache-airflow/airflow --namespace airflow-np --set flower.enables=true
kubectl port-forward svc/airflow-rl-flower 5555:5555 --namespace airflow-np
```

### Anything else

A quick fix for this is:

```
config:
  celery:
    flower_url_prefix: ''
```

Basically, the new default value '/' makes it so the scripts and links read:
`<script src="//static/js/jquery....`
where it should be:
`<script src="/static/js/jquery....`

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)
</div>

### PR DESCRIPTION
**Pull request by amoghrajesh**
closes: https://github.com/apache/airflow/issues/27402

Simple fix as suggested in related PRs that went stale: https://github.com/apache/airflow/pull/27480

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by amoghrajesh** [comment]
@jedcunningham @potiuk I would like to add test coverage for this, but wasn't sure where to. This is because the only usage of this property is in celery_executor.py and we do not test this property as a unit

**Comment by RNHTTR** [comment]
Maybe somewhere in [/tests/charts](https://github.com/apache/airflow/tree/main/tests/charts)?

**Comment by amoghrajesh** [comment]
Yes, let me see where I can send it in

**Comment by amoghrajesh** [comment]
@jedcunningham @potiuk @hussein-awala I added the tests here. Can you take a look when you have some time?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
