### PR TITLE
Remove email provider test module

### PR DESCRIPTION
**Pull request by pankajastro**
Since we have moved the email operator to the core and also tests so we should remove the corresponding test module from the provider tests

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — CHANGES_REQUESTED** [review]
We have not yet moved.
We released provider first as informed decision after what happened with common.sql provider
@hussein-awala is working now on the needed core changes and PR is coming 
Created https://github.com/apache/airflow/issues/30530 for visibility.

**Comment by pankajastro** [comment]
> We have not yet moved. We released provider first as informed decision after what happened with common.sql provider @hussein-awala is working now on the needed core changes and PR is coming Created #30530 for visibility.

Thanks @eladkal for pointing out. The email operator from core will go at [smtp provider](https://github.com/apache/airflow/tree/main/airflow/providers/smtp) and [smtp provider test](https://github.com/apache/airflow/tree/main/tests/providers/smtp) in https://github.com/apache/airflow/issues/30530 or we will be adding back email provider?

**Comment by eladkal** [comment]
core operator will be deprecated and use the provider just like we did for common.sql (and what earlier we did for contrib)

**Comment by eladkal** [comment]
closing this one in favor of the planned PR

**Pull request closed without merging**
