### PR TITLE
Correct question type for prepare-provider-documentation

### PR DESCRIPTION
**Pull request by amoghrajesh**
For the provider doc preparation, the qn that asked to confirm if we have any changes apart from `doc-only` didn't acknowledge `N` option.

```
Does the provider: airbyte have any changes apart from 'doc-only'?
Press y/N/q: N

Define the type of change for `Split providers out of the main "airflow/" tree into a UV workspace project (https://github.com/apache/airflow/pull/42505)` by referring to the above table
Type of change (b)ugfix, (f)eature, (x)breaking change, (m)misc, (s)kip, (q)uit ? ^C

Summary of prepared documentation:
```

Corrected the qn function to fix it.

```
Does the provider: airbyte have any changes apart from 'doc-only'?
Press y/N/q: N
answer is Answer.NO True
Marking last change: 857ca4c06c and all above changes since the last release as doc-only changes!


Summary of prepared documentation:

Docs only: 1

airbyte


Successfully prepared documentation for packages!
```

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I think you should remove those HASH file modifications :)

**Comment by potiuk** [comment]
Looks like they were added by pre-commit while the source for breeze has not been committed :). Making sure that you do not have any modified file and running `pre-commit  run update-breeze-cmd-output --all-files` should fix things.

Just make sure you have no non-added changes in your workspace.

**Review by hussein-awala — APPROVED** [review]

**Comment by amoghrajesh** [comment]
@potiuk I tried it out, it doesn't generate anything:
```
(apache-airflow) ➜  airflow git:(correctWrongAnsType) pre-commit  run update-breeze-cmd-output --all-files
Update breeze docs.......................................................Passed

```

Moreover, also tried force pushing the change only, still running into this

**Comment by potiuk** [comment]
Maybe try to reinstall your pre-commit/breeze - maybe it is still installed with python 3.8 (though it should not change too much) . I cannot push a fixup to your branch, but I have exactly the same hashes as the one that are on the server- somehow the hashes in your version are calcualated differently..

**Comment by amoghrajesh** [comment]
Let me try reinstalling, looks to me that it installed an "older" breeze when I was playing around with some really "old" branch!

**Comment by amoghrajesh** [comment]
CI is green, merging.

**Comment by potiuk** [comment]
> Let me try reinstalling, looks to me that it installed an "older" breeze when I was playing around with some really "old" branch!

That could be - at some point in time i added the change that automatically breeze if an older version is used - without even asking the user - it just reinstalls it, but if you had REALLLY old version of breeze that did not have this mechanism, then yeah - hash calculation changed at some point in time so it could be different.

**Pull request merged**
