### PR TITLE
Disable test code coverage for PRs

### PR DESCRIPTION
**Pull request by potiuk**
The test code coverage took a lot of memory (2-3GB) when core
tests were running (specifically test_kubernetes_executor.py) and
the memory was kept for the duration of whole test.

This caused intermittent memory issues on public GitHub runners.

The change only uses test coverage for `main` builds where we have
a lot of memory available.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @khalidmammadov @o-nikolas

**Comment by potiuk** [comment]
And "regular" user PR here: https://github.com/apache/airflow/pull/19524

**Comment by potiuk** [comment]
I REALLY hope this one will solve the memory errors for contributors now ! :crossed_fingers: 

I reproducibly run the `test_kubermetes.py` followed by `test_backfill_job.py` with/without coverage yielding 2-3 GB vs 700 MB memory used while test_backfill_job was running. So I REALLY hope it's gonna fly this time.

**Review by kaxil — APPROVED** [review]

**Review by o-nikolas — APPROVED** [review]

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
It failed for a different reason in one test - but I do think it's gonna work

**Pull request merged**
