### PR TITLE
[AIRFLOW-42] Adding logging.debug DagBag loading stats

### PR DESCRIPTION
**Pull request by mistercrunch**
```
-------------------------------------------------------------------
DagBag stats for /Users/maxime_beauchemin/code/Airflow/airflow/example_dags
-------------------------------------------------------------------
Number of DAGs: 16
DagBag parsing time: 0.141064
-------------------------------------------------------------------
file                                        | duration | dag_num | dags
--------------------------------------------+----------+---------+------------------------------------------------------------------------------------------------------
/example_twitter_dag.py                     | 0.030106 |       1 | ['example_twitter_dag']
/example_subdag_operator.py                 | 0.021742 |       3 | ['example_subdag_operator', 'example_subdag_operator.section-2', 'example_subdag_operator.section-1']
/example_branch_operator.py                 | 0.014476 |       1 | ['example_branch_operator']
/example_python_operator.py                 | 0.013508 |       1 | ['example_python_operator']
/example_bash_operator.py                   | 0.010692 |       1 | ['example_bash_operator']
/example_http_operator.py                   | 0.009226 |       1 | ['example_http_operator']
/example_skip_dag.py                        | 0.008972 |       1 | ['example_skip_dag']
/example_short_circuit_operator.py          | 0.00873  |       1 | ['example_short_circuit_operator']
/example_trigger_target_dag.py              | 0.00443  |       1 | ['example_trigger_target_dag']
/example_xcom.py                            | 0.004198 |       1 | ['example_xcom']
/example_branch_python_dop_operator_3.py    | 0.003652 |       1 | ['example_branch_dop_operator_v3']
/tutorial.py                                | 0.003636 |       1 | ['tutorial']
/example_trigger_controller_dag.py          | 0.003174 |       1 | ['example_trigger_controller_dag']
/example_passing_params_via_test_command.py | 0.002758 |       1 | ['example_passing_params_via_test_command']
/docker_copy_data.py                        | 0.00051  |       0 | []
/example_docker_operator.py                 | 0.000478 |       0 | []
/subdags/subdag.py                          | 0.00047  |       0 | []
/__init__.py                                | 0.00019  |       0 | []
/subdags/__init__.py                        | 0.000116 |       0 | []

-------------------------------------------------------------------
```

### CODE REVIEW

**Comment by r39132** [comment]
+1 Glad its sorted in decreasing parse time

**Comment by r39132** [comment]
@mistercrunch You need to create a Jira for this - It will be easier to report how many Jiras are closed each month in the board report.

**Comment by artwr** [comment]
LGTM

**Comment by mistercrunch** [comment]
https://issues.apache.org/jira/browse/AIRFLOW-42

**Comment by r39132** [comment]
Awesome..thx

**Pull request merged**
