### PR TITLE
[AIRFLOW-3072] Assign permission get_logs_with_metadata to viewer role

### PR DESCRIPTION
**Pull request by seelmann**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3072

### Description

- [X] Allow non-admin roles to view logs.

### Tests

- [X] My PR adds unit tests

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
Actually if the viewer has DAG level  permission(https://github.com/apache/incubator-airflow/blob/master/airflow/www_rbac/views.py#L502), he should be able to view the log.

**Comment by feng-tao** [comment]
But we could commit it for now and revisit if we should take it out from viewer permission. cc @jgao54

**Comment by seelmann** [comment]
Thanks @feng-tao for approval. This is more a fix for 1.10 which does not include DAG level permission yet. Maybe this can be included in 1.10.1 @ashb ?

**Comment by ashb** [comment]
I'm not sure I like this as a default permisson. On the one hand needing admin to view logs is wrong, but conversely there could be passwords or other sensitive info in the logs, so maybe just "viewer" shouldn't have access to the logs?

Not sure basically.

**Comment by jgao54** [comment]
imho, viewer was originally intended for anything read-only, which would include log-reading, while user had both read and write access to DAGs. So from that perspective viewers should have log-reading access.

**Review by jgao54 — APPROVED** [review]

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
@seelmann The JIRA issue for this PR is marked as 1.10.1, but the diff doesn't apply cleanly there. Would you be able to some up with a patch against the v1-10-test branch please?

**Comment by seelmann** [comment]
@ashb I opened PR https://github.com/apache/incubator-airflow/pull/4175

**Pull request merged**
