### PR TITLE
Refactor `SafeDogStatsdLogger` to use `get_validator` to enable pattern matching

### LINKED ISSUE #39368: Add a pattern-matching support for allow and block list in Datadog metric
### Description

Currently, when exporting metrics to Datadog, we only do plain prefix matches for the allow list and block list.  I am requesting to include regex pattern-matching

### Use case/motivation

We are already supporting this for OTEL #36250. Adding this to Datadog will help to maintain a reduced number of patterns required in the allow/block list

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rawwar**
closes #39368 

By reusing the `get_validators` function, we can incorporate pattern search to include allow/block lists.

### CODE REVIEW

**Review by pankajkoti — COMMENTED** [review]
were you able to test this end to end with Datadog using all the 3 configurations? Allow list, block list and pattern list? Also could you please add tests for all those configurations if they don't exist already?

**Comment by rawwar** [comment]
@pankajkoti, Yes, I have tested them. Allow/Block list without pattern worked perfectly.  However, I noticed the following behaviour when using pattern matching, which I am not sure if it's right.

## With pattern matching enabled:

1. `AIRFLOW__METRICS__METRICS_ALLOW_LIST` =  `.*queued_duration.*` : Worked perfectly


image


2. `AIRFLOW__METRICS__METRICS_ALLOW_LIST` =  `.*get_astronauts.*` : Not sure if this is correct


image



In the 2nd screenshot, I still see several metrics that don't have `get_astronauts` anywhere in their metrics names. Is this correct behaviour? One of them is `airflow.ti.finish`

**Comment by rawwar** [comment]
Block lists seem to be working as intended.

1. `AIRFLOW__METRICS__METRICS_BLOCK_LIST` = `.*duration.*` : works perfectly

image

**Comment by rawwar** [comment]
Env variables set:


AIRFLOW__METRICS__STATSD_DATADOG_ENABLED | true 
-- | -- | --
AIRFLOW__METRICS__STATSD_DATADOG_TAGS | testNo:C2 
DATADOG_API_KEY | ● ● ● ● ● ● ●
AIRFLOW__METRICS__METRICS_USE_PATTERN_MATCH | true
AIRFLOW__METRICS__METRICS_ALLOW_LIST | .*print_astronaut_craft.*

**Review by pankajkoti — APPROVED** [review]

**Review by dirrao — APPROVED** [review]
LGTM

**Review by ferruzzi — APPROVED** [review]
Code change LGTM, but I'm not sure that second allow-list example (the one you seemed unsure about) is working as expected.  Either way, that is not in scope for this PR if that is broken, but you may want to look into that more if you have the time.

**Comment by rawwar** [comment]
> Code change LGTM, but I'm not sure that second allow-list example (the one you seemed unsure about) is working as expected. Either way, that is not in scope for this PR if that is broken, but you may want to look into that more if you have the time.


I will look into it. I will create an issue and post my findings there.

**Pull request merged**
