### PR TITLE
[AIRFLOW-5671] rename DataProcHook to DataprocHook

### PR DESCRIPTION
**Pull request by michalslowikowski00**
Part of AIP-21
--

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5671
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by feluelle — COMMENTED** [review]
IMO this deprecation warning is not necessary if we are targeting AIP 21 for 2.0. It will be a major/breaking release anyway. We should rather add it to the Updating.md instead of adding more code. WDYT? @nuclearpinguin @mik-laj

**Comment by feluelle** [comment]
_I am feeling a bit bad about it_. But maybe if you can provide me a good reason why we should keep it for 2.0 and remove it later (2.1, etc) I am feeling better 😀

**Comment by feluelle** [comment]
I mean ya moving it out of contrib is worth a `DeprecationWarning`, because it is a "bigger" step.

**Comment by mik-laj** [comment]
It is very important to facilitate the migration of users to Airflow 2.0. The release of Airflow 2.0 is the possibility of introducing breaking and major changes, but this is not the reason why we should make these changes in a backwards compatible manner. Migration to Airflow 2.0 is a very big change and we cannot further hinder it by having to change every DAG.

Adoption of AIP-21 took place under one statement "All proposed solutions are backwards compatible.".  It was also a topic of discussion in the community on the mailing list. If the changes are to be incompatible, it is worth avoiding them, but if we can have an apple and eat an apple, i.e. make changes and maintain backward compatibility, we should do it.

**Comment by mik-laj** [comment]
FYI. This change results from an attempt to unify and adapt operators to GCP guidelines (~190 changes in current spreadsheet). This will apply to almost all GCP operators. In the next steps, we will also think about unifying the names of other operators.  Such a change cannot take place in a way that prevents migration. Airflow would suffer a lot if it suddenly broke all compatibility rules. Users could start looking for a different environment that provides more stable work.

**Comment by feluelle** [comment]
Thanks. It totally makes sense now as I am thinking about it again with your points mind.

_I just searched for backwards compatiblity in the AIP before making that review and still somehow missed it._

**Comment by feluelle** [comment]
Should we also move it to the `providers` package since it belongs to the same AIP ? Or do you think this should be part of another PR @michalslowikowski00 ?

**Comment by mik-laj** [comment]
We want to do it in a separate PR. For now, we want to improve the names, which is a very difficult task, because we have 200 resources to change. I prefer changes with small steps, which limits the chances of error.

Note that the tests in the tests/test_core_to_contrib.py file show that very few changes take place in this file.

**Review by feluelle — APPROVED** [review]

**Comment by mik-laj** [comment]
Can you also update a note in UPDATING.md file?
https://github.com/apache/airflow/blob/master/UPDATING.md#changes-to-import-paths-and-names-of-gcp-operators-and-hooks

**Comment by mik-laj** [comment]
@feluelle 
Screenshot 2019-10-25 at 13 52 59
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths
The assumption that backward compatibility is also required is outlined in section "Implementation considerations". We compare different backward compatibility solutions. The lack of backward compatibility was not a solution that was even considered.  The entire AIP is follow up the PR #3000  which was not accepted by the lack of backward compatibility mechanism. Development accelerated when I presented a solution of backward compatibility #4667

**Comment by michalslowikowski00** [comment]
Hi @feluelle, as @mik-laj said for now we want to split this task for the small PRs which can be easily fix. There is a lot of little changes and I would like to avoid making mistakes and I don't want to provide many changes in single PR. I hope it is fine with you. Any suggestions are more than welcome.

**Comment by michalslowikowski00** [comment]
@mik-laj, I added new commit with updated UPDATING.md. Will it be ok?

**Comment by feluelle** [comment]
@michalslowikowski00 I am fine with it.

**Pull request merged**
