### PR TITLE
[AIRFLOW-390] Don't load example dags by default

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-390
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Don't load example dags by default.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
I find this a hard decision. If you are new to Airflow, the examples are nice to look at.

**Comment by bolkedebruin** [comment]
We like a great out of the box experience. This is (a.o. reasons) why we have sqlite support. Having examples gets newbies quickly started. More experienced users know how to disable them.

So im not in favor of this change.

**Comment by feng-tao** [comment]
sure. In this case, could we close the original jira ticket as won't fix? And could we(or committers) do a jira triaging and close those noise tickets? I felt the current airflow jira board is not very up-todate which makes it hard for newcomer to tell which one should be in the roadmap and which one is not.

**Comment by feng-tao** [comment]
close this pr as won't fix.

**Pull request closed without merging**
