### PR TITLE
[AIRFLOW-1313] Add vertica_to_mysql operator

### PR DESCRIPTION
**Pull request by juise**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [AIRFLOW-1313](https://issues.apache.org/jira/browse/AIRFLOW-1313) "Vertica To MySQL operator"

### Description
- [x] Simple contrib operator that can export data from vertica to mysql

### Tests
- [x] Exists

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please add tests, absence of tests is not an excuse to not add them.

**Comment by juise** [comment]
@bolkedebruin done!

**Comment by juise** [comment]
@bolkedebruin up

**Comment by r39132** [comment]
+1 Sorry for the delay.

**Pull request closed without merging**
