### PR TITLE
[AIRFLOW-6319] Add support for AWS Athena workgroups

### PR DESCRIPTION
**Pull request by bhavika**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://jira.apache.org/jira/browse/AIRFLOW-6319

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The AWS Athena hooks ans operators currently do not provide the ability to use workgroups for running queries. More on the feature here - https://docs.aws.amazon.com/athena/latest/ug/workgroups.html & https://docs.aws.amazon.com/athena/latest/ug/user-created-workgroups.html

I propose we add the ability to pass in workgroup names while creating the Athena connection. The default workgroup name in Athena is `default` - so we can make that the parameter default when a workgroup is not passed in by the user. 

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I have not added more tests but modified existing tests to use a `default` workgroup. I would like suggestions on how to add tests that use a non-default workgroup. 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @bhavika!

**Comment by bhavika** [comment]
@potiuk thank *you*! What do you think of adding more tests for non-default workgroups? I suppose the Airflow project has an AWS setup which is useful for testing - could we add a non-default workgroup to that & some tests to go along, or is this PR enough?

**Comment by potiuk** [comment]
If you are referring to system tests - we do not have (yet) an AWS setup that we use for "system" testing. This is something that we are working on as part of AIP-4: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+System+Tests+for+external+systems - but I think it requires a few prerequisites before we vote/approve changes in there. such as moving out of Travis CI (we switched from migrating to GitLab to migrating to Github Actions) and securing some regular credits from AWS/GoogleCloud/Microsoft Azure - so that we can run those tests regularly + pytest markers to distinguish those tests and run them only when we run them "with system tests".  All of these prerequisites are in progress :) 

I think for now its enough - once we have a basic framework for running the system tests (and some credits provided by Google Cloud/AWS/Azure) we might revisit that and add more tests for that.

**Comment by bhavika** [comment]
> If you are referring to system tests - we do not have (yet) an AWS setup that we use for "system" testing. This is something that we are working on as part of AIP-4: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-4+Support+for+System+Tests+for+external+systems - but I think it requires a few prerequisites before we vote/approve changes in there. such as moving out of Travis CI (we switched from migrating to GitLab to migrating to Github Actions) and securing some regular credits from AWS/GoogleCloud/Microsoft Azure - so that we can run those tests regularly + pytest markers to distinguish those tests and run them only when we run them "with system tests". All of these prerequisites are in progress :)
> 
> I think for now its enough - once we have a basic framework for running the system tests (and some credits provided by Google Cloud/AWS/Azure) we might revisit that and add more tests for that.

Ah, that makes sense. I did mean system tests. Thank you for explaining where this is at. I hope y'all secure those credits soon. :)

**Comment by mrshu** [comment]
Hey everyone,

Thanks a ton for implementing this @bhavika!

When we tried these changes today (after update to 1.10.9), however, it turns out they did not really work out for us. There seem to be two reasons:

1. It seems that when you do not create a Workgroup on AWS, the default name is called `primary` rather than `default`. This is what the [AWS Docs say](https://docs.aws.amazon.com/athena/latest/ug/workgroups-procedure.html):

>  default, if you have not created any workgroups, all queries in your account run in the primary workgroup

2. Even after setting the `workgroup` parameter to `primary`, the AWSAthenaOperator did not work for us and failed with the following:

```
Unknown parameter in input: "Workgroup", must be one of: QueryString, ClientRequestToken, QueryExecutionContext, ResultConfiguration, WorkGroup
```
It turns out that the correct parameter to use is actually called `WorkGroup` as opposed to `Workgroup` which the code currently uses (https://github.com/apache/airflow/pull/6871/files#diff-a5011c8e96e573b3c2a951d1450bd9eaR78).

If you think it may make sense, I'll be happy to send a PR that should fix both of these issues. Let me know what you think!

------------------------------------------------

Just for the sake of completeness (and because I assume a few more people may run into this), we now use the following custom `AWSAthenaOperator`:

```python
from airflow.contrib.operators.aws_athena_operator import AWSAthenaOperator
from airflow.contrib.hooks.aws_athena_hook import AWSAthenaHook


class CustomAWSAthenaOperator(AWSAthenaOperator):
    # Monkey patch the workgroup because the default is 'primary' for us, not
    # 'default' as Airflow uses
    # https://github.com/apache/airflow/pull/6871
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.workgroup = 'primary'

    def execute(self, context):
        self.hook = self.get_hook()

        self.query_execution_context['Database'] = self.database
        self.result_configuration['OutputLocation'] = self.output_location

        conn = self.hook.get_conn()

        self.res = conn.start_query_execution(QueryString=self.query, # noqa
                                              ClientRequestToken=self.client_request_token, # noqa
                                              QueryExecutionContext=self.query_execution_context, # noqa
                                              ResultConfiguration=self.result_configuration, # noqa
                                              WorkGroup=self.workgroup) # noqa

        self.query_execution_id = self.res['QueryExecutionId']
        query_status = self.hook.poll_query_status(self.query_execution_id,
                                                   self.max_tries)

        if query_status in AWSAthenaHook.FAILURE_STATES:
            error_message = self.hook.get_state_change_reason(self.query_execution_id) # noqa
            raise Exception(
                'Final state of Athena job is {}, query_execution_id is {}. Error: {}' # noqa
                .format(query_status, self.query_execution_id, error_message))
        elif not query_status or query_status in AWSAthenaHook.INTERMEDIATE_STATES:  # noqa
            raise Exception(
                'Final state of Athena job is {}. '
                'Max tries of poll status exceeded, query_execution_id is {}.'
                .format(query_status, self.query_execution_id))

        return self.query_execution_id
```
------------------------------

> I think for now its enough - once we have a basic framework for running the system tests (and some credits provided by Google Cloud/AWS/Azure) we might revisit that and add more tests for that.

@potiuk I just wanted to second that this framework would be a great addition to the testing pipeline, as issues like the ones we've encountered here might get to surface much earlier. Is there any way I can help with that?

Thanks!

**Comment by bhavika** [comment]
@mrshu thank you so much for your detailed writeup of this issue Marek and I'm sorry you faced this problem. As far as I can see, you're right about the problems with the default workgroup name and the "WorkGroup" parameter. If you'd prefer to submit a fix yourself, go ahead but let me know if you'd like me to do it instead. I think we don't have a test setup for Athena as you can see in my comments above - but I agree that having this would help surface issues sooner.

**Comment by bhavika** [comment]
@mrshu just wanted to flag that someone else already fixed the WorkGroup param name here - https://github.com/apache/airflow/pull/7386

**Comment by mrshu** [comment]
@bhavika Nice -- thanks a lot for the reply!

Please feel free to go ahead and update the `workgroup` default -- it would take me much longer to setup :)

Thanks again!

**Pull request merged**
