### PR TITLE
Add airflow webserver URL into SLA miss email.

### PR DESCRIPTION
**Pull request by abhishekbafna**
---
**^ Add meaningful description above**

This adds the Airflow webserver base URL in the SLA miss notification email. This can be really helpful in cases where multiple airflow clusters are running and it identifies in which cluster it has happened. It also enables users to reach the airflow cluster with a single click from the email itself. 

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — COMMENTED** [review]
Can we see an example screenshot of such an email generated  ?

**Comment by abhishekbafna** [comment]
> Can we see an example screenshot of such an email generated ?

Thank you for the review Jarek. Please find the screenshot of the email below.

PS: I have tested this on Airflow 1.10.4+ which we use internally. It's the same change for both the current master and 1.10.4 version.

Screenshot 2020-12-23 at 10 00 05 AM

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Nice!

**Comment by abhishekbafna** [comment]
Thank you Jarek, I couldn't be happier.

**Pull request merged**
