### PR TITLE
[AIRFLOW-1759] create PostgresTableSensor

### PR DESCRIPTION
**Pull request by Acehaidrey**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow 1759](https://issues.apache.org/jira/browse/AIRFLOW-1759/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-1759

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Create a Postgres Table Sensor to see if table exists before doing any sort of work on it.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Tests added to check if sensor works. Use a postgresoperator to first create the table.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Acehaidrey** [comment]
failures are not due to my tests.. I removed my test file and still the travis jobs fail

**Comment by Acehaidrey** [comment]
@aoen @bolkedebruin  just looking for some feedback.
It's weird test errors, not related to anything I've worked on or touched. I'm not seeing a specific message that's especially helpful.
But more so, I was wondering do you think this is something worthy to add to the airflow project. Other people I feel would need this sort of sensor, but if you don't think it's especially useful then I don't want to waste my time trying to fix the tests etc. and will just close out this ticket.
I can add it for myself as a plugin in either case, but let me know if you think this is valuable for the airflow community! I know we have similar sensors for hive and likely other dbs

**Comment by Acehaidrey** [comment]
@bolkedebruin just want to know if you think there is merit to this PR. @aoen too. If not then I'll close it out

**Comment by bolkedebruin** [comment]
@Acehaidrey can you close this please? Or clean it up? It is triggering a build for every commit to master

**Comment by Acehaidrey** [comment]
Hi sorry about that, yes let me close it. I didn't mean to do that, I was just trying to rebase and work on this PR.

**Pull request closed without merging**
