### PR TITLE
[AIRFLOW-4338] Change k8s pod_request_factory to use yaml safe_load

### PR DESCRIPTION
**Pull request by feluelle**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4338
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR changes k8s pod_request_factory to use yaml safe_load and fixes yaml.load deprecation warning.

Explanation:
Before Python yaml version 5.1 yaml has used the UnsafeLoader that has a potential security vulnerability. From now on there is a FullLoader that will be used by default that fixes these vulnerability. To suppress the warning we can explicitly set the loader or use a shortcut function like **safe_load**

See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation for more details.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feluelle** [comment]
I don't understand why mypy cannot find the attribute `FullLoader`
```
airflow/contrib/kubernetes/kubernetes_request_factory/pod_request_factory.py:45: error: Module has no attribute "FullLoader"
airflow/contrib/kubernetes/kubernetes_request_factory/pod_request_factory.py:113: error: Module has no attribute "FullLoader"
```

`python -c "import yaml; yaml.FullLoader"` runs successfully in the same python env mypy is installed.

**Comment by ashb** [comment]
Unrelated to the mypy warning I think we want to use `SafeLoader` - we only want to restore "plain" objects here anyway.

Which we can do by `yaml.salfe_load` - so that would side-step the mypy issue too.

**Comment by feluelle** [comment]
Yes, the shortcut function would fix it 👍 

I am fine with `SafeLoader` as well. @dimberman what do you think of this?

**Review by dimberman — APPROVED** [review]
@feluelle this all LGTM. Is this good to merge? (It seems that you've already handled the SafeLoader issue but just want to make sure first)

**Comment by feluelle** [comment]
The issue I had was only related to mypy (I still don't get) but has been worked-around by using a shortcut function where mypy don't need to check the Loader classes. - So yes it is fixed.

Just to summarize it for you:

If we use the `FullLoader` / `load_full` we don't change any functionality. It just will fix the deprecation warning.
> Loads the full YAML language. Avoids arbitrary code execution. This is currently (PyYAML 5.1) the default loader called by yaml.load(input) (after issuing the warning).

If we use the `SafeLoader` / `load_safe` we may change functionality - but tests run successfully so it is probably fine.
> Loads a subset of the YAML language, safely. This is recommended for loading untrusted input.

**Comment by dimberman** [comment]
SG. Yeah if the tests are passing we should be fine.

**Pull request merged**
