### PR TITLE
Pin github/codeql-action action

### PR DESCRIPTION
**Pull request by gopidesupavan**
As per ASF, we should pin all the external actions.

https://infra.apache.org/github-actions-policy.html

codeql-action: https://github.com/github/codeql-action/tree/v3.27.9

Slack action need to be updated, I will raise separate change, latest slack action release has introduced breaking changes, need to check. 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]

**Comment by amoghrajesh** [comment]
Some checks failing

**Comment by potiuk** [comment]
We don't have to pin actions prefixed with `github/` 

```
You MAY use all actions internal to the apache/*, github/* and actions/* namespaces without restrictions.
```

**Comment by gopidesupavan** [comment]
> https://infra.apache.org/github-actions-policy.html

oh yeah my bad, missed. will close this one :)

**Comment by gopidesupavan** [comment]
closing this one, as github/* namespace allowed to use without commit sha.

**Comment by gopidesupavan** [comment]
> Some checks failing

sorry closed as it not needed :)

**Pull request closed without merging**
