### PR TITLE
change parquet_writer write a table for each row

### PR DESCRIPTION
**Pull request by akbarnotopb**
**Problems/Issue** 
- The uploaded parquet files in GCS is too big, e.g., ~2000 rows of 77 cols in `csv` ~1MB but in `parquet` will be ~50MB. 

**Suspect** 
- At `line 246-248`, current operator will create a `parquet table` for each row and immediately write it on the file buffer.

**Solution** 
1. Store each rows  in a temporary variable `parquet_datas`
2. Write it down to the file if :  
   - its size exceed `approx_max_file_size_bytes` or,
   -  at the end of the row

### CODE REVIEW

**Comment by eladkal** [comment]
Can you add unit test?

**Comment by akbarnotopb** [comment]
> Can you add unit test?

working on it

**Comment by akbarnotopb** [comment]
> > Can you add unit test?
> 
> working on it

I'm new to the community & this is my first PR ever made to open-source projects.  

I've read the unit test guidelines & existing unit test on `SqlToGTCSOperator` , but still, i just cannot think any idea on what should i add to the test regarding this case. 

Is comparing the filesize between parquet & csv enough? *there  is already a test to make sure the data is valid, cmiiw

It'll be helpful if you could give me rough idea/criteria that needs to be met in the test case? Thanks in advance

**Comment by eladkal** [comment]
> but still, i just cannot think any idea on what should i add to the test regarding this case.

The goal is that if someone will modify these codelines in the future the test will make sure the behavior you want to fix here will not be broken again so we are looking for a way to verify the change is working as expected

**Comment by akbarnotopb** [comment]
> > but still, i just cannot think any idea on what should i add to the test regarding this case.
> 
> The goal is that if someone will modify these codelines in the future the test will make sure the behavior you want to fix here will not be broken again so we are looking for a way to verify the change is working as expected

So in short, i just need to show you that
 - parquet file dumping is working properly
 - data is valid
 since i only move the way operator write to the buffer which affect the filesize?

**Pull request closed without merging**
