### PR TITLE
Fix string encoding in DockerOperator when using xcom / json in xcom.py

### LINKED ISSUE #13535: DockerOperator / XCOM : `TypeError: Object of type bytes is not JSON serializable`
**Apache Airflow version**: 2.0.0

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`): NA

**Environment**: 
* local Ubuntu 18.04 LTS / 
* docker-compose version 1.25.3, build d4d1b42b
* docker  20.10.1, build 831ebea

**What happened**:

when enabling xcom push for a docker operator the following error is thrown after the task finishes succesfully:
`TypeError: Object of type bytes is not JSON serializable`

**What you expected to happen**:

* error is not thrown
* if xcom_all is True: xcom contains all log lines
* if xcom_all is False: xcom contains last log line

**How to reproduce it**:

see docker compose and readme here:
https://github.com/AlessioM/airflow-xcom-issue

### PR DESCRIPTION
**Pull request by AlessioM**
closes: #13535

fixes the xcom issue by decoding the byte array of the log file before submitting it to xcom

replaces pull request #13536

### CODE REVIEW

**Comment by AlessioM** [comment]
this repo allows easy testing of the fix:
https://github.com/AlessioM/airflow-xcom-issue

however:
the repo above has a dockeroperator that prints 10 lines (numbers 0 to 9, using a simple python script)
xcom always contains all 10 lines, regardles if xcom_all is set or not

I suspect that is because the DockerOperator uses docker-py's [client.attach](https://github.com/docker/docker-py/blob/6da140e26c1cbe8e362b328b1c78d9c736f3a1a2/docker/api/container.py#L17) wich does not return the logs separated by lines

**Review by turbaszek — CHANGES_REQUESTED** [review]
I'm not sure about this one. In my opinion the default XCom supports only JSON-serializable types. And bytes are not the type. It's up to an operator to take care of that. If users want to change behaviour of XCom backend they can either use pickle (not recommended for security reasons) or create their own XCom backend:
https://airflow.apache.org/docs/apache-airflow/stable/concepts.html?highlight=z#custom-xcom-backend

**Comment by kaxil** [comment]
> I'm not sure about this one. In my opinion the default XCom supports only JSON-serializable types. And bytes are not the type. It's up to an operator to take care of that. If users want to change behaviour of XCom backend they can either use pickle (not recommended for security reasons) or create their own XCom backend:
> https://airflow.apache.org/docs/apache-airflow/stable/concepts.html?highlight=z#custom-xcom-backend

Agree with @turbaszek , the change in https://github.com/apache/airflow/pull/13536/files is actually what we need

**Comment by AlessioM** [comment]
ok, will close this one in favor of #13536
thanks for the help!

**Pull request closed without merging**
