### PR TITLE
[AIRFLOW-5733] Migrate AWS components to /providers/aws [AIP-21]

### PR DESCRIPTION
**Pull request by BasPH**
This PR moves all AWS components to `/providers/aws`, as described in [AIP-21](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths).

Things to point out:

- All old paths raise DeprecationWarnings
- Components are now grouped by AWS service (`operators/s3.py` became quite long)
- Had to fix test `TestS3ToGoogleCloudStorageOperator.test_execute` which was using the S3Hook from two different locations, which are now the same script. Other than that, no code changes, only moving.
- Excluded full directory `'_api/airflow/providers/aws'` from the docs for now, a number of components are missing docs which should be handled in a different PR.

Would be nice to get this merged quickly. Because of the large code change, it will be lots of work to keep up-to-date with master.

-----------------

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5733
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add the missing tests?
https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py

**Comment by mik-laj** [comment]
I also prefer that PR be smaller, because now it is very difficult to check if the change is correct. In the case of GCP, we made changes in one service in one PR, because it allowed us to check if the change was correct.

**Comment by mik-laj** [comment]
> Excluded full directory '_api/airflow/providers/aws' from the docs for now, a number of components are missing docs which should be handled in a different PR.

I think it is necessary to create a separate PR that will create this package and then make changes to the [https://github.com/apache/airflow/blob/master/docs/autoapi_templates/index.rst](docs/autoapi_templates/index.rst]) file so that the documentation builds correctly.

> Components are now grouped by AWS service (operators/s3.py became quite long)

Can you do it in a separate PR so that it is possible to verify that it was done correctly? One PR can introduce tests, and then another PR can check if the path is still working properly.

**Comment by mik-laj** [comment]
>  rename tests/{contrib/hooks/test_aws_lambda_hook.py => providers/aws/hooks/test_lambda_.py} (93%)
>  rename tests/{contrib/operators/test_dynamodb_to_s3.py => providers/aws/operators/test_dynamodb.py} (97%)
>  rename tests/{operators/test_redshift_to_s3_operator.py => providers/aws/operators/test_redshift.py} (97%)

It doesn't look good, but it's difficult to verify.

**Comment by BasPH** [comment]
I can make PRs per service, will start at A of Athena.

**Comment by mik-laj** [comment]
@BasPH Thank you. We have an integration list, so it's easy to organize work now
https://airflow.readthedocs.io/en/latest/operators-and-hooks-ref.html#id3

**Comment by BasPH** [comment]
Closing in favour of multiple smaller PRs. Related JIRA: https://issues.apache.org/jira/browse/AIRFLOW-5788

**Pull request closed without merging**
