### PR TITLE
Retrieve PR labels from the associated PR

### PR DESCRIPTION
**Pull request by potiuk**
This change is needed to implement optimisation of running only
limited version of the matrix tests for PRs that are not yet
approved by committers.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Works nicely here:

In CI:
https://github.com/potiuk/airflow/pull/134/checks?check_run_id=1301856214#step:2:595
In CI Build:
https://github.com/potiuk/airflow/runs/1301856242?check_suite_focus=true#step:2:88

**Comment by potiuk** [comment]
cc: @TobKed

**Comment by potiuk** [comment]
In order to fully test #11828  I need to merge this one first - to start retrieving labels from PR in master "wokflow_runs". I tested it already in the "limited" version and we have ~ 50% less job time used for those PRs that will be run as "unapproved PRs.

**Comment by potiuk** [comment]
I need to merge this one - it's harmless but otherwise we won't be able to test the "sub-set" of tests with @TobKed

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
