### PR TITLE
Kerberos

### PR DESCRIPTION
**Pull request by bolkedebruin**
This adds initial kerberos support to airflow. Foundation for hooks is available. Please review and let me know if it needs updates.

### CODE REVIEW

**Comment by mistercrunch** [comment]
First thank you for doing this! I created the PR as a placeholder for the discussion.

First I'm not sure what to do with `kt_renewer.py` and `security_util.py`. Is it possible that security_util ins't used anywhere? I couldn't find a reference to it. 

And for `kt_renewer` is forked out of the Hue project right? I guess it's small enough to hold it here (as opposed to having Airflow depend on Hue...). Maybe we need to put it under an `ext` folder and rename it to something more meaningful.

Apart from that everything seems reasonable upon first read.

**Comment by bolkedebruin** [comment]
Thanks! 

`kt_renewer` does exactly what is named being a kerberos ticket renewer ;-). It is indeed forked out of the hue project, but it is also a port, although minor, to make it work in the airflow context. 

`security_util.py` is not used at the moment, it will however help with porting hooks to support kerberized services. I might need to change the example HiveCliHook to use it to get the fqdn from `security_utils.py` instead of getting it from `os.socket` as in multi-homed servers it might not give the correct name.

Instead of putting it into `ext` I would suggest `security` and then rename `security_util.py` to `util.py`. This reason for this is that for example a (future) yarn executor in a secure context will become reliant on having kerberos authentication available. Besides that putting it into `ext` would make it seem a bit slapped on which does not raise confidence with a certain public :-). But of course it is just semantics.

I can update the PR to have things moved. Let me know.

**Comment by mistercrunch** [comment]
Sounds good, what about a security folder with `utils.py` and `kerberos.py`?

**Comment by bolkedebruin** [comment]
@mistercrunch changes are implemented including owner/login support for HiveCliHook with beeline

**Comment by bolkedebruin** [comment]
Is anything else required to get this PR merged?

**Comment by bolkedebruin** [comment]
@mistercrunch I am preparing some additional patches (in contrib though :) ) that rely on this PR. Any chance to get it merged or are additional changes required? Are additional tests required (I think the implications are covered by current tests)?

**Comment by gglanzani** [comment]
Looks like solid work to me. Any chances of getting this merged? What's stopping it?

**Comment by praveev** [comment]
+1 would love to see this merged

**Comment by mistercrunch** [comment]
I'm running the unit tests against it now and merging as soon as it passes

**Comment by mistercrunch** [comment]
Thank you for this major contribution!

**Comment by praveev** [comment]
@bolkedebruin - thanks for this feature!

But when I tried to test with kerberos - I got this:

`File "/usr/local/lib/python2.7/dist-packages/snakebite/channel.py", line 236, in get_connection
    sasl = SaslRpcClient(self)`
`NameError: global name 'SaslRpcClient' is not defined`

I double checked and made sure I built pkg with this feature. I also have rpc_sasl.py where SaslRpcClient is defined. What am I missing?

**Comment by bolkedebruin** [comment]
Hi @praveev this is obviously an issue in snakebite and not per se in airflow. Did you install the cyrus-sasl libraries / kerberos flavor of snakebite (ie. does snakebite work from the command line ?)

**Comment by praveev** [comment]
@bolkedebruin i installed snakebite[kerberos]. not sure how to test kerberos from snakebite command line. specifically how to specify ccache and keytab via command line for snakebite https://github.com/spotify/snakebite/issues/173

**Comment by bolkedebruin** [comment]
You can use 

Kinit -kt path/to/keytab <principal>

And then

snakebite ls /

**Comment by praveev** [comment]
@bolkedebruin  thanks. I get the same error from the command line as well: 
`NameError: global name 'SaslRpcClient' is not defined`

**Comment by bolkedebruin** [comment]
Did you install the Cyrus-Sasl libs? Ie see instructions here: https://pypi.python.org/pypi/sasl

**Comment by praveev** [comment]
Yup that's installed.

**Comment by bolkedebruin** [comment]
Ok. This is an issue with a change that was done in snakebite to do a conditional import.

If you add:
          from snakebite.rpc_sasl import SaslRpcClien
          from snakebite.kerberos import Kerberos

to the top of snakebite/channel.py it should start working

Can you raise this issue with snakebite?

**Comment by praveev** [comment]
sure thanks. @bolkedebruin  https://github.com/spotify/snakebite/issues/174

**Pull request merged**
