### PR TITLE
[AIRFLOW-1617] Fix XSS vulnerability in Variable endpoint

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1617

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

In case a Variable form was accessed by a get request and
the form did not exist as a template, the input was
returned as is to the user.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Test added.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@saguziel @aoen @r39132

**Comment by bolkedebruin** [comment]
Strange, travis seemed to have pulled the old diff.

**Comment by criccomini** [comment]
+1 LGTM

**Comment by aoen** [comment]
LGTM

**Comment by criccomini** [comment]
Merged and cherry picked into 1.9.0

**Pull request closed without merging**
