### PR TITLE
AIP-59 Performance testing framework

### PR DESCRIPTION
**Pull request by bjankie1**
---

Initial version of performance testing framework - AIP-59.

Note: PR created for early review, testing in progress - not ready for merge.

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vincbeck** [comment]
Is there any chance you could split up this PR in multiple PRs? 15k lines of code is really hard to review :)

**Comment by potiuk** [comment]
Agree. Would be nice to separate out piece by piece and review them in smaller increments. Generally review time is at least n^2

**Comment by bjankie1** [comment]
I will make an attempt to divide the code into several PRs.
1.  Framework for building performance DAGs
1.  Framework for collecting instance metrics in kubernetes.
1.  Framework for collecting instance metrics in Cloud Composer.
1.  Glue code - performance tests execution

**Comment by mathiaHT** [comment]
Hello, any update about this ?

**Comment by Asquator** [comment]
Any update?

**Pull request closed without merging**
