### PR TITLE
[AIRFLOW-3074] Add relevant ECS options to ECS operator.

### PR DESCRIPTION
**Pull request by jmcarp**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The ECS operator currently supports only a subset of available options
for running ECS tasks. This patch adds all ECS options that could be
relevant to airflow; options that wouldn't make sense here, like
`count`, were skipped.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Thanks @jmcarp  LGTM

**Comment by smith-m** [comment]
@jmcarp

JIRA marked this issue (Also Airflow-3036? GCP CloudSQL/mysql configuration issues with 1.10) as complete as result of this PR. 

https://issues.apache.org/jira/plugins/servlet/mobile#issue/AIRFLOW-3036

Does this PR address that issue? They don't seem to be related

**Comment by seelmann** [comment]
This is the right Jira: https://issues.apache.org/jira/browse/AIRFLOW-3074

**Comment by smith-m** [comment]
In that case, the airflow-3036 needs to be reopened and 3074 should be closed

**Comment by danmactough** [comment]
@ashb This PR got merged into master back in September 2018, but it never made it into any release. Any idea what happened? How can we get this released?

image

**Comment by ashb** [comment]
@danmactough We cherry-pick commits from master branch in to the release, based on the Fix Version in JIRA tickets. The good news is that I have already cherry-picked it on to the branch for 1.10.3 so it'll be included in the next release - https://github.com/apache/airflow/commit/653a5864d35d29fcecf60f32d993fa2301122c10

**Comment by danmactough** [comment]
Thanks @ashb

**Pull request merged**
