### PR TITLE
Use internal table. Using external was leading to duplicates.

### PR DESCRIPTION
**Pull request by artwr**
@mistercrunch 
We were running into an interesting issue even with an insert overwrite which would not clear previous data. This should fix it.

### CODE REVIEW

**Comment by artwr** [comment]
Oddly enough, this seems to only affect the new cluster and Hive 0.13...

**Comment by mistercrunch** [comment]
Interesting, did you run the unit tests on both versions?

**Comment by artwr** [comment]
@krishnap

**Comment by mistercrunch** [comment]
I ran the tests.

**Pull request merged**
