### PR TITLE
ci(basic-tests): add missing standard provider

### PR DESCRIPTION
**Pull request by Lee-W**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by gopidesupavan** [comment]
Ah ryt I have added this into bash operator there were tests failing in the pr due to standard procedure not installing, the pr is in review.

**Comment by gopidesupavan** [comment]
#42506 this  has changes to provider manager and bash operator changes, in my opinion it breaks k8s tests also as there is import being used in celery executor utils . Because standard provider not getting installing in the container. It would be better to revert the changes ? 
Cc: @romsharon98

**Comment by Lee-W** [comment]
for short term solution, we probably could go with this one. for long term, we will need to add it as fab dep and wait for its release

**Comment by gopidesupavan** [comment]
https://github.com/apache/airflow/blob/0c911a9d36936d2d0ef1937e33560a30907f30ad/airflow/providers/celery/executors/celery_executor_utils.py#L114 here when bash operator gets imported this would fail because bash operator has imports related to hook? It's like dead lock.

**Comment by gopidesupavan** [comment]
> for short term solution, we probably could go with this one. for long term, we will need to add it as fab dep and wait for its release

Agree. API client works with this change , but my hunch is on k8s test might fail.

**Comment by gopidesupavan** [comment]
And docker tests as well... As a workaround I have added skipif here https://github.com/apache/airflow/pull/42252. But don't like skipping these tests not good. It would be better to release the standard provider basic version and installing it default provider lists.

**Comment by gopidesupavan** [comment]
Created revert pr https://github.com/apache/airflow/pull/42659

**Comment by Lee-W** [comment]
Ok, then let's use the revert commit and close this one. Thanks @gopidesupavan !

**Comment by potiuk** [comment]
See the discussion in https://lists.apache.org/thread/1gshy5cjmp9wz5v8dozyh64jj3dyn5s4 - I think we should start releasing ".dev0" standard provider to PyPI manually to overcome some of the chicken-egg problems experienced here and avoiding the neeed for "skip-if"

**Pull request closed without merging**
