### PR TITLE
Streamline image-based pre-commit tests

### PR DESCRIPTION
**Pull request by potiuk**
This PR simplifies and streamlines the pre-commits that require
CI and BATS docker images to run. This is the result of
upcoming CI/Breze rewrite from Bash to Python and recent
improvements in image caching.

The following simplifications and deletion are implemented:

* BATS tests (amd all related code) are completely removed from both
  Host and container we are removing Bash so those won't be needed

* The 'build' test that prepared CI image if needed has been
  removed (see below)

* The 'mypy' and 'flake' images that require CI image, instead of
  attempting to rebuild the image, will run on whatever image they
  have, but they will warn that the image needs to be rebuilt
  at earliest convenience.

* In case the CI image has never been built locally, it will
  be automaticaly pulled from ghcr.io latest image built on CI
  without asking the user

* Documentation is updated

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @bowrna @edithturn -> Another 1000 lines of bash that we can remove now as we are moving to simpler setup.

**Comment by potiuk** [comment]
For those reviewing it. This is what you will get (after this one is merged) when your image is out-dated during pre-commit.

No questions asked, no progress bar, no interaction - just information that it would be wise to rebuild your image soon.

image

**Comment by potiuk** [comment]
(and the double image in the warning is removed in the final version).

**Comment by potiuk** [comment]
And @ashb - your -7000 lines net is still out of reach but this is one step closer :).

**Comment by edithturn** [comment]
wow, there are a lot of lines reduced, Jarek.

**Comment by potiuk** [comment]
Ah yea @edithturn ... @ashb WDYT ?

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
