### PR TITLE
Fix main Branch Test Failures

### PR DESCRIPTION
**Pull request by bugraoz93**
Fix main failures and adjust test names and file names according to changes in dataset -> asset.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]
Sounds promising... but the tests would fail in Airflow 2.10 then?

**Comment by bugraoz93** [comment]
Doesn't it depend on whether these changes have already been backported? #42579

**Comment by bugraoz93** [comment]
I have seen it neither in `v2-10-test` nor `2.10.2`.

**Comment by jscheffl** [comment]
> I have seen it neither in `v2-10-test` nor `2.10.2`. So I assume it should be good if I am not missing somethings 🙂

The renaming Dataset->Asset is a breaking change that is only for Airflow 3 line. All providers (and I assume also pytests of providers) need to be compatible with Airflow 2 and 3 line.

@uranusjr @Lee-W Do you have any idea/guidance? If FAB needs to support "both worlds" would pytests then need to have a "skipif" and carry both back-end implementations?

**Comment by vincbeck** [comment]
These tests are already skipped if Airflow < 3

**Review by vincbeck — APPROVED** [review]

**Comment by Lee-W** [comment]
Thanks @bugraoz93 !  Missed this one 🤦‍♂️

@jscheffl I think we already have the compat code in FAB. the permission side should be fine, but asset endpoints won't exist in <3.0 so they should be skipped for <3.0

**Pull request merged**
