### PR TITLE
Revert "AIP-79 Generate assets for Flask application in FAB provider"

### PR DESCRIPTION
**Pull request by jscheffl**
Reverts apache/airflow#44744

Seems to be the "quickest" way to fix main, will re-open a PR to merge back again with full tests after

FYI @vincbeck 

Broken build: https://github.com/apache/airflow/actions/runs/12399970802/job/34616478712

### CODE REVIEW

**Comment by jscheffl** [comment]
Note: I#ll have another PR as fix in 5min, maybe that saves a reversion...

**Comment by jscheffl** [comment]
I propose to close this in favor of #45058

**Comment by potiuk** [comment]
Yep.

**Comment by jscheffl** [comment]
Other PR as quick fix failed, so I change my opinion and would propose the reversion route. Then we can re-apply and check fully.

**Review by vincbeck — APPROVED** [review]

**Pull request merged**
