### PR TITLE
Fix LDAP error messages when login fails.

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by criccomini** [comment]
cc @bolkedebruin feedback welcome--just tweaking error messages to make fat-fingered usernames a bit more intelligible.

**Comment by bolkedebruin** [comment]
Rest seems fine and I am all good with better messages

**Comment by criccomini** [comment]
What do you mean "positive" dn? With AD, what we see is a result with nothing but a search reference field.

**Comment by bolkedebruin** [comment]
Ah ok I get it. Patch seems fine then.

@mistercrunch

**Comment by mistercrunch** [comment]
:+1:

**Pull request merged**
