### PR TITLE
remove duplicate ports key in webserver-service.yaml

### PR DESCRIPTION
**Pull request by Ahmad-RW**
remove duplicate key in webserver service template

---

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by Taragolis — APPROVED** [review]

**Comment by brokenjacobs** [comment]
Just an FYI these duplicate ports break installation with fluxcd... So you can do a manual helm install but you can't use fluxcd to deploy in the cluster because the yaml is broken. Please please please cut a new helm chart release @potiuk !

**Comment by jedcunningham** [comment]
Let's sit on it for a little bit longer to see if anything else shakes out. I'm happy to start a new release later this week. That said, it'd be great if you all could test the RCs so we can find these accidental regressions before the release is finalized.

**Comment by tsgit** [comment]
apart from the duplicate ports:  the whitespace changes following that in the generated yaml are also odd.
$ helm template airflow apache-airflow/airflow -f values.yaml --namespace=$(NAMESPACE)
gives 
```
    component: webserver
    release: airflow
  ports:
  ports:
  
    -
      name: airflow-ui
      port: 8080
```


in addition I see a duplicate 
`cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` in the airflow-scheduler deployment section of the rendered chart 

likely due to 

https://github.com/apache/airflow/blob/main/chart/templates/scheduler/scheduler-deployment.yaml#L98-L106


when using the kustomize HelmChartInflationGenerator this results in error
```
error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 47: mapping key "cluster-autoscaler.kubernetes.io/safe-to-evict" already defined at line 46
```

I believe the worker-deployment template avoids this via
https://github.com/apache/airflow/blob/main/chart/templates/workers/worker-deployment.yaml#L41-L42

**Comment by brokenjacobs** [comment]
> Let's sit on it for a little bit longer to see if anything else shakes out. I'm happy to start a new release later this week. That said, it'd be great if you all could test the RCs so we can find these accidental regressions before the release is finalized.

Heard. Is there an RC for this one?

**Comment by jabbera** [comment]
I've got a need for this as well. I can't use kustomize without this fix.

**Comment by BalaMuralibi** [comment]
@jedcunningham I ran into same error with ports to install with flux, We can't do manual install. Any ETA when is the chart 1.12.0 is expected to be updated ?

**Comment by potiuk** [comment]
I believe we will do it after we release Airlfow 2.8.2. But I think it realy depends on how much time people like you will spend on testing the RCs when they are out - apparrently you missed the announcement on RC 1.12.0 to catch this earlier. Can we count on you helping testing it when RC is out @BalaMuralibi ? It requires you to subscribe to our devlist https://airflow.apache.org/community/ and when we ask people to test RC - you should respond and confirm that it is fixed.

Can we count on you @BalaMuralibi ? 

Subscribing to devlist is the way when you can find out when RC is out. In the meantime, there is absolutely no problem to use the previous helm chart, I think.

**Comment by potiuk** [comment]
Also @jabbera - you can still use previous version and subscribe to devlist and when we ask you to test RC, we'd expect you test it and confirm it works. You seem to be very interested to get it - so it looks like you would be interested in helping out to test the RC when it is out. That will definitely speed up and improve the release if people like @BalaMuralibi and @jabbera who are early adopters will test the RCs. Can we count on the both of you to help with RCs?

**Comment by potiuk** [comment]
@brokenjacobs -> you as well. Pleases subscribe to our devlist and when RC is out, please verify and test if it works for you and respond to our requests to test the RC when it is out. In the meantime any of you can either use the previous version, or - if you are adventurous, you can also install current main version - you will find README and instructions how to install chart from main after checking out the main version of the repo.

I think doing this kind of preliminary testing and reporting back the status of it is absolutely best way to make such release faster, so if you care about getting new release faster, this is precisely the way you can help with. It works much better than asking for ETA on that.

**Comment by BalaMuralibi** [comment]
> I believe we will do it after we release Airlfow 2.8.2. But I think it realy depends on how much time people like you will spend on testing the RCs when they are out - apparrently you missed the announcement on RC 1.12.0 to catch this earlier. Can we count on you helping testing it when RC is out @BalaMuralibi ? It requires you to subscribe to our devlist https://airflow.apache.org/community/ and when we ask people to test RC - you should respond and confirm that it is fixed.
> 
> Can we count on you @BalaMuralibi ?
> 
> Subscribing to devlist is the way when you can find out when RC is out. In the meantime, there is absolutely no problem to use the previous helm chart, I think.

sure, I can test rc when it is out.

**Comment by jedcunningham** [comment]
> I believe we will do it after we release Airlfow 2.8.2.

Yep, that's exactly my plan.

**Pull request merged**
