### PR TITLE
[AIRFLOW-2908] Allow retries with KubernetesExecutor.

### PR DESCRIPTION
**Pull request by jpds**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2908

### Description

This allows users to retry DAG tasks when using the Kubernetes executor.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

There do not appear to be tests for this view.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue.

@dimberman

### CODE REVIEW

**Comment by dimberman** [comment]
+1!

**Comment by dimberman** [comment]
cc: @bolkedebruin @Fokko

**Review by Fokko — APPROVED** [review]
LGTM

**Comment by Fokko** [comment]
Did you actually ran a job using this code? @jpds

**Comment by jpds** [comment]
@Fokko Yes, I have this happily working on our test Airflow instance.

**Comment by Devarajegowda** [comment]
Can anyone please explain why this operation is limited only for celery or Kubernetes executor.
I tried to remove this check & it seems working fine for LocalExecutor as well, Am I missing something ?

**Comment by ashb** [comment]
@Devarajegowda Probably because it didn't used to work and no one investigated to see that it does _now_ work. If it does now work then please open a PR :)

**Pull request merged**
