### PR TITLE
[BUMP] kind 0.18.0

### PR DESCRIPTION
**Pull request by raphaelauv**
https://github.com/kubernetes-sigs/kind/releases/tag/v0.18.0

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Nice! Thanks @raphaelauv !

**Comment by raphaelauv** [comment]
@potiuk could we merge ? thanks

**Comment by eladkal** [comment]
@potiuk shall we merge?

**Comment by potiuk** [comment]
Static checks will need rerun . Btw yesterday GitHub released a new runner that seems to have a fix for those intermittent node pull errors (it will retry pulling node when they fail). I will deploy it later today

**Pull request merged**
