### PR TITLE
[AIRFLOW-2779] Add project versions to LICENSE

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-2779

### Description

- [x] The Incubator PMC requested that we add version information to the
license declarations to cope with the possibility of projects changing
licenses on us in the future.

Where possible I have worked out the version we are actually using, but
where that hasn't been possible and the project is still on the same
license (they all were) I have taken the latest version as of right now
### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
@bolkedebruin @kaxil @Fokko Could one of you PTAL? I think this is the last thing needed before I can make a v1.10.1 RC1

**Comment by Fokko** [comment]
Few of the Javascript dependencies are minimal versions. How do we deal with more recent versions?

Eg. https://github.com/apache/incubator-airflow/blob/master/airflow/www_rbac/package.json#L59

**Comment by ashb** [comment]
Good question. I've been going off this short post on the incubator mailing list:

> I checked the source tar with the git tag and the License files.  
> We need to specify the third party dependencies version as they may have  
> different License in different version.  
> Please fix it in next around release.

**Review by Fokko — APPROVED** [review]
Thanks @ashb 

I'm fine with merging this one. Maybe drop a follow up question on the mailinglist?

**Review by kaxil — APPROVED** [review]

**Pull request merged**
