### PR TITLE
[AIRFLOW-6555] mushroom cloud error when clicking 'task instance details' from graph view of dag that has never been run yet

### PR DESCRIPTION
**Pull request by tooptoop4**
---
Issue link: [AIRFLOW-6555](https://issues.apache.org/jira/browse/AIRFLOW-6555)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by tooptoop4** [comment]
@kaxil pls merge

**Comment by kaxil** [comment]
@KevinYang21 What do you think of this PR?

**Comment by tooptoop4** [comment]
u there Kev? @KevinYang21

**Comment by ashb** [comment]
@tooptoop4 Could you add a unit test please so we can check this doesn't break again in the future?

**Comment by tooptoop4** [comment]
@ashb are there any similar tests I could 'reuse' as a starting point ?

**Comment by tooptoop4** [comment]
@mik-laj do u know what test I can base off?

**Comment by mik-laj** [comment]
```
    def test_dagrun_id_tooptoop4(self):
        ti = Mock(get_dagrun=Mock(return_value=None))
        self.assertTrue(DagrunIdDep().is_met(ti=ti))

```
File: tests/ti_deps/deps/test_dagrun_id_dep.py

**Comment by tooptoop4** [comment]
covered by https://github.com/apache/airflow/pull/8389

**Pull request closed without merging**
