### PR TITLE
Fix database isolation case for task mapping taskinstance tests

### PR DESCRIPTION
**Pull request by potiuk**
Related: #41067

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Should fix the failing 32 task_instance tests.

**Review by aritra24 — COMMENTED** [review]
I think it looks fine, but I don't fully understand it. So will wait for someone else's review...

**Comment by potiuk** [comment]
> I think it looks fine, but I don't fully understand it. So will wait for someone else's review...

The problem was that task retrieved via get_task_instance wes None (but this is only needed for this test)

**Comment by potiuk** [comment]
Actually it turns out that the tests should be skipped altogether as they are monkeypatching calculate method locally.

**Review by vincbeck — APPROVED** [review]

**Pull request merged**
