### PR TITLE
[AIRFLOW-5142] Fixed flaky cassandra test

### PR DESCRIPTION
**Pull request by potiuk**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5142

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by potiuk** [comment]
@kaxil @BasPH  -> we have a flaky cassandra test in master, so we'd better merge this fix quickly :)

**Review by feluelle — APPROVED** [review]

**Review by kaxil — COMMENTED** [review]
I still don't exactly understand why was that flaky

**Comment by mik-laj** [comment]
The data structure that does not store the order of the elements. Sometimes last element has the value A and other times the value B.

**Comment by mik-laj** [comment]
https://stackoverflow.com/a/39980744/1849502

**Comment by potiuk** [comment]
Yeah. It's all explained in discussion here: https://github.com/apache/airflow/pull/5753 and https://stackoverflow.com/a/39980744/1849502 - we have two method calls and they are sometimes in different order because of race and the test originally checked only last call (that's how assert_called_with works). It seems it was only problem in python 3.5 (not sure why it passed originally ) because there it's not the "last" call but the one which is determined by the dictionary order as pointed by @mik-laj . Now the test correctly tests if the two upload methods were called in any order.

**Comment by turbaszek** [comment]
Interesting case! @potiuk is right, the test should assert two calls and I missed it in https://github.com/apache/airflow/pull/5738 😔

**Comment by BasPH** [comment]
> @kaxil @BasPH -> we have a flaky cassandra test in master, so we'd better merge this fix quickly :)

I was too late, but nice work 😄

**Comment by kaxil** [comment]
Thanks @potiuk & @mik-laj , I now understand that

**Pull request merged**
