### PR TITLE
Bugfix: Return XCom Value in the XCom Endpoint API

### LINKED ISSUE #13676: API Endpoints - /xcomEntries/{xcom_key} - doesn't return value
**Apache Airflow version**: 2.0.0

**What happened**:

Using endpoint `/dags/{dag_id}/dagRuns/{dag_run_id}/taskInstances/{task_id}/xcomEntries/{xcom_key}` I got Response Body but without `value` entry. Like:
```
{
  "dag_id": "string",
  "execution_date": "string",
  "key": "string",
  "task_id": "string",
  "timestamp": "string"
}
```
Instead of:
```
{
  "dag_id": "string",
  "execution_date": "string",
  "key": "string",
  "task_id": "string",
  "timestamp": "string",
  "value": "string"
}
```
The exact value by defined `key` exists.

### PR DESCRIPTION
**Pull request by kaxil**
closes https://github.com/apache/airflow/issues/13676

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
this field could potentially be very large so it does not show up in the list.  You must download a single item to download its contents.

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/blob/master/airflow/api_connexion/endpoints/xcom_endpoint.py#L97
```diff
-    return xcom_collection_item_schema.dump(query_object)
+    return xcom_schema.dump(query_object)
```
That should fix the problem.

**Comment by kaxil** [comment]
> this field could potentially be very large so it does not show up in the list. You must download a single item to download its contents.

We should replicate what we do in the UI -- we ask everyone to not store large values in XCom

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/blob/2fef2ab1bf0f8c727a503940c9c65fd5be208386/airflow/api_connexion/openapi/v1.yaml#L1876
here this behavior is described in the spec. Storing large objects in XCOM is not recommended, but unfortunately some people store larger objects in Xcom and the API should still behave stably.

**Review by mik-laj — APPROVED** [review]

**Review by XD-DENG — APPROVED** [review]

**Pull request merged**
