### PR TITLE
Enable Pydocstyle D200 check

### PR DESCRIPTION
**Pull request by mrwacky42**
Judicious use of Perl:

```
pre-commit run -a pydocstyle 2>&1 |grep module.level |cut -d: -f 1 |xargs perl -pi -e 'undef $/; s@"""\n(.*?)\n"""@"""\1"""@ms'
pre-commit run -a pydocstyle 2>&1 |grep ^airflow |cut -d: -f 1| xargs perl -pi -e 'undef $/; s@"""\n +([^\n]+)\n +"""@"""\1"""@gms'
pre-commit run -a pydocstyle 2>&1 |grep ^airflow |cut -d: -f 1| xargs perl -pi -e 'undef $/; s@"""\n +([^\n]+)\n+ +"""@"""\1"""@gms'
```

Then fix a few things manually here and there.

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Some static checks are sad. Can you fix it?
```
Run pydocstyle....................................................................................................................Failed
- hook id: pydocstyle
- exit code: 1

docs/build_docs.py:42 in public class `DocBuildError`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:68 in public class `SpellingError`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:110 in public function `clean_files`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:121 in public function `display_errors_summary`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:139 in public function `display_spelling_error_summary`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:194 in private nested class `ClassVisitor`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:217 in public function `check_guide_links_in_operator_descriptions`:
        D200: One-line docstring should fit on one line with quotes (found 4)
docs/build_docs.py:330 in public function `check_class_links_in_operators_and_hooks_ref`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:364 in public function `check_guide_links_in_operators_and_hooks_ref`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:409 in public function `check_exampleinclude_for_example_dags`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:426 in public function `check_enforce_code_block`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/build_docs.py:460 in public function `check_google_guides`:
        D200: One-line docstring should fit on one line with quotes (found 4)
docs/build_docs.py:680 in public function `build_sphinx_docs`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/exts/sphinx_script_update.py:38 in private function `_user_cache_dir`:
        D200: One-line docstring should fit on one line with quotes (found 3)
airflow/contrib/hooks/gcp_transfer_hook.py:18 at module level:
        D209: Multi-line docstring closing quotes should be on a separate line
metastore_browser/hive_metastore.py:49 in public class `MetastoreBrowserView`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:57 in public method `index`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:83 in public method `table`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:95 in public method `db`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:107 in public method `partitions`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:138 in public method `objects`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:169 in public method `data`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:183 in public method `ddl`:
        D200: One-line docstring should fit on one line with quotes (found 3)
metastore_browser/hive_metastore.py:201 in public class `MetastoreBrowserPlugin`:
        D200: One-line docstring should fit on one line with quotes (found 3)
docs/exts/exampleinclude.py:45 in public class `ExampleHeader`:
        D200: One-line docstring should fit on one line with quotes (found 3)
```

**Comment by mrwacky42** [comment]
Not sure how that happened, it passed locally. I'll fix it up.

**Comment by mik-laj** [comment]
There was a conflict merge. I tried to solve this problem using Web UI. Hope it works.

**Comment by mik-laj** [comment]
I am working on a rebase for this change.

**Comment by mik-laj** [comment]
Something is broken after rebase. Can you look at it?

**Comment by kaxil** [comment]
Can you please rebase your PR on latest Master since we have applied [Black](https://github.com/apache/airflow/commit/4e8f9cc8d02b29c325b8a5a76b4837671bdf5f68) and [PyUpgrade](https://github.com/apache/airflow/commit/8c42cf1b00c90f0d7f11b8a3a455381de8e003c5) on Master.

It will help if your squash your commits into single commit first so that there are less conflicts.

**Pull request closed without merging**
