### PR TITLE
Upgrade google-ads version

### PR DESCRIPTION
**Pull request by molcay**
This PR is about upgrading the `google-ads` version which is a dependency for `google` providers

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — COMMENTED** [review]
What is the motivation?
V16 is very new and v15 was released last year.
As long as v15 is not EOL I dont think we should change the default

**Review by pedro-klein-desco — APPROVED** [review]
Link new version [Google Ads Doc](https://developers.google.com/google-ads/api/reference/rpc/v16/overview)

**Comment by potiuk** [comment]
Yeah. It's better to preemptively bump Ads version.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
They tend to deprecate stuff faster than everyone else

**Pull request merged**
