### PR TITLE
Remove deprecated param from BranchDayOfWeekOperator

### PR DESCRIPTION
**Pull request by gopidesupavan**
Remove deprication param use_task_execution_day in BranchDayOfWeekOperator

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — CHANGES_REQUESTED** [review]
Temporary block.

We may want to discuss introducing `common.time` provider. This will allow to extract several operators/sensor from core and will not put these breaking changes on Airflow 3

**Comment by romsharon98** [comment]
> Temporary block.
> 
> We may want to discuss introducing `common.time` provider. This will allow to extract several operators/sensor from core and will not put these breaking changes on Airflow 3

I raised thread in mailing list 
https://lists.apache.org/thread/2dmlqkcmyomm4q7rrovygs6bw655zx07

**Comment by gopidesupavan** [comment]
> > Temporary block.
> > We may want to discuss introducing `common.time` provider. This will allow to extract several operators/sensor from core and will not put these breaking changes on Airflow 3
> 
> I raised thread in mailing list https://lists.apache.org/thread/2dmlqkcmyomm4q7rrovygs6bw655zx07

Thank you @romsharon98 😊 I am happy to help on this work. Please let me know if anything.

**Comment by gopidesupavan** [comment]
Closing this pr, as we have moved operators inside standard provider.  #41564

**Pull request closed without merging**
