### PR TITLE
add/community project

### PR DESCRIPTION
**Pull request by AibekYrysbekov**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
What is this?

To other maintainers: **Don’t run CI.** A submodule has been added. Not sure what’s in it.

**Comment by potiuk** [comment]
Good catch. I will convert to draft in the meantime and will take a look.

**Comment by potiuk** [comment]
@AibekYrysbekov - any explanation ? Or are you a bad actor ? If no response given i will flag you to GitHub to ban your account

**Comment by AibekYrysbekov** [comment]
Hello! Sorry for the late reply. I have created a tool that can be run daily or weekly to analyze information about the open source community. It requests information from the API and generates a report on the latest state of the community.

**Comment by potiuk** [comment]
No. Then we are not going to add it.

**Comment by pabloem** [comment]
hi all! no bad actor - this is part of a google summer of code project. We will continue development in a separate fork. Thanks and sorry about the confusion.

**Comment by potiuk** [comment]
> hi all! no bad actor - this is part of a google summer of code project. We will continue development in a separate fork. Thanks and sorry about the confusion.

OK. Sorry to scare away your summer of code intern @pabloem :)

But this was quite a bit unexpected and looked suspicious. Maybe an intro would be nice :)

**Pull request closed without merging**
