### PR TITLE
Fix Connection reset by peer when there is no log for a long time

### PR DESCRIPTION
**Pull request by buxizhizhoum**
Fix Connection reset by peer when there is no log for a long time by catch the related PortalError.
If not, there will be a log like line below:
[2020-06-17 15:04:53,084] {connectionpool.py:750} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', error(104, 'Connection reset by peer'))': /api/v1/namespaces/oflow-test/pods/oflow-kuberbetes-test-24972430/log?container=base&follow=True&tailLines=10

Current unit test could already cover the modification, so no new unittest test is needed.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by mik-laj** [comment]
@mbohlool @roycaihw Can you look at it? I wonder if this is something we should fix on our side, or should we fix it in kubernetes-client/python

**Comment by buxizhizhoum** [comment]
Is there anything more to do? I could pass **CI Build / Quarantined:Pg9.6,Py3.6 (pull_request)** check in forked repository, however it fails here.

**Comment by mik-laj** [comment]
I would be happy if you would create a ticket in the Kubernetes library and add a link in the comment. Connection problems in this case should be handled on the library side. If this is important to you, you can also ask for reviews of other Kubernetes contributors. This is open source, so every review is valuable.

**Comment by buxizhizhoum** [comment]
> I would be happy if you would create a ticket in the Kubernetes library and add a link in the comment. Connection problems in this case should be handled on the library side. If this is important to you, you can also ask for reviews of other Kubernetes contributors. This is open source, so every review is valuable.

It my pleasure to do it, and should I close this issue, since this problem should be handled on the library side?

**Comment by mik-laj** [comment]
Until the library authors fix this problem, we can have this workaround, but this should be marked with a ticket link - inline comment in code.

**Comment by buxizhizhoum** [comment]
> Until the library authors fix this problem, we can have this workaround, but this should be marked with a ticket link - inline comment in code.

I have reported it at here, https://github.com/kubernetes/kubernetes/issues/92298

**Pull request closed without merging**
