### PR TITLE
Add `uri_pattern` query param to Get `/datasets` endpoint

### PR DESCRIPTION
**Pull request by ephraimbuddy**

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]
This looks good. I do wonder if we should also have a `uri` param that checks for full equality. Thoughts? Could be a follow up too.

**Comment by ephraimbuddy** [comment]
> This looks good. I do wonder if we should also have a `uri` param that checks for full equality. Thoughts? Could be a follow up too.

Sounds good since datasets have no name. Would be a good way to find specific dataset.

**Comment by ephraimbuddy** [comment]
> This looks good. I do wonder if we should also have a `uri` param that checks for full equality. Thoughts? Could be a follow up too.

Thinking about this, what do you think should be the behaviour when both uri_pattern and uri is supplied by the user? It seems to me that we could have misleading results that way. If we filter by uri_pattern before filtering by uri we could miss the search. If we ignore one and apply the other, the result will also be misleading and I don't think we should do mutual exclusion for a query param. WDYT

**Comment by jedcunningham** [comment]
I'd think making them mutually exclusive is the most straight forward for everyone involved.

**Pull request merged**
