### PR TITLE
Update dag-run.rst for dead links of cli commands

### PR DESCRIPTION
**Pull request by abhishekbhakat**
The location of cli ref was recently changed. So, the commands linked for `backfill` and `clear` lands on broken page.

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by uranusjr** [comment]
It’s probably a good idea to use `:ref:` instead so Sphinx can check the link automatically in the future.

**Comment by potiuk** [comment]
> It’s probably a good idea to use `:ref:` instead so Sphinx can check the link automatically in the future.

Agree. @abhishekbhakat -> would you like to update it ? There are good examples across other code out there.

**Comment by abhishekbhakat** [comment]
cli ref is generated by `argparse` not to sure how to reference them if not hyperlink to html

**Comment by abhishekbhakat** [comment]
The cli ref is generate by sphinx-argparse dynamically. I'm not sure we can link that as a `:ref:`.

**Comment by abhishekbhakat** [comment]
https://github.com/apache/airflow/blob/f7d5b165fcb8983bd82a852dcc5088b4b7d26a91/docs/apache-airflow/database-erd-ref.rst?plain=1#L33

There may be other references to cli like the one above, mostly it's html link cause it's dynamically generated ?

**Comment by potiuk** [comment]
Yeah. Makes sense.

**Comment by uranusjr** [comment]
We should add this as a feature to sphinx-argparse if it’s not there already

cc @ashb

**Pull request merged**
