### PR TITLE
Upload provider distribution artifacts during CI

### PR DESCRIPTION
**Pull request by malthe**
This adds "./dist/apache_airflow_providers_*.tar.gz" into a build artifact bundle "airflow-providers".

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
a bit of whitespace :(. BTW. Pre-commits are cool

**Comment by malthe** [comment]
@potiuk yeah I had this naïve idea that I would be able to edit a simple file without making whitespace errors but then I realized that there are sections where there are two newlines etc.

**Comment by potiuk** [comment]
> @potiuk yeah I had this naïve idea that I would be able to edit a simple file without making whitespace errors but then I realized that there are sections where there are two newlines etc.

Been there, done tht :)

**Comment by potiuk** [comment]
Nice! merging as the other issues are unrelated (and mostly fixed already via OOM fix)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
