### PR TITLE
add dag parsed time in DAG view

### PR DESCRIPTION
**Pull request by leehuwuj**
At our company, user have to change their dag definition in their own git repository which is going to be pulled by git-sync service into our Airflow instance. Users have to wait a moment then checking the DAG code to see is their updates are refreshed in Airflow.
It'd be easier if we show the last parsed time in DAG view that user can easily compare the parsed time with current time.

This update will add a new label called `Parsed at` next to the `Next Run` tooltip of the DAG UI.

image

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
Nice! I'm just not sure if that's the best place for that info. I think it may be better in the `/detail` page

**Comment by jedcunningham** [comment]
Turns out it's already on the details page. What about if we added it to /code?

**Comment by leehuwuj** [comment]
> Turns out it's already on the details page. What about if we added it to /code?

Good idea @jedcunningham , It'll be more friendly with users who checking their updates in the code without look closer into their code. 
Should I keep the label there then add a condition to show in `/code` page only or put it inside the dag_code block?
I'll keep commit if our decision is simple because i'm not a front-end developer myself.

**Comment by jedcunningham** [comment]
Lets put it in the page body instead, above the code block? That work for you @bbovenzi?

**Comment by bbovenzi** [comment]
> Lets put it in the page body instead, above the code block? That work for you @bbovenzi?

Yeah, let's put it in `code.html` inbetween `subtitle` and `code`

**Comment by leehuwuj** [comment]
> Yeah, let's put it in `code.html` inbetween `subtitle` and `code`  

I'm a bit confused, I think it's `dag_code.html` and it seems that the `code.html` has not be used for a long time!

**Comment by bbovenzi** [comment]
> > Yeah, let's put it in `code.html` inbetween `subtitle` and `code`
> 
> I'm a bit confused, I think it's `dag_code.html` and it seems that the `code.html` has not be used for a long time!

Yes, my bad.

**Comment by leehuwuj** [comment]
Just moved to `dag_code.html`:
image

**Review by bbovenzi — APPROVED** [review]

**Comment by jedcunningham** [comment]
Thanks @leehuwuj! Congrats on your first commit 🎉

**Pull request merged**
