### PR TITLE
[AIRFLOW-3028] Update Text & Images in Readme.md

### PR DESCRIPTION
**Pull request by r39132**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3028
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Updated Readme with new images and added Apache Airflow in a few places.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
N/A

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
@feng-tao @ashb  @kaxil PTAL

**Comment by Fokko** [comment]
Thanks @r39132, looks good.

What happend to the images, they are used in other `.md` files: https://github.com/apache/incubator-airflow/search?q=code.png&unscoped_q=code.png

**Comment by r39132** [comment]
Hi @Fokko 
I replaced the images, so with this commit, we would be able to rebuild & publish the docs site. In your link above, the RST was the only other place referenced. 

Is this PR good to go or was there something else you were looking for?

**Review by Fokko — APPROVED** [review]
Thanks @r39132 LGTM

**Comment by r39132** [comment]
Thx @Fokko. I will merge this now. 

I looked at all of the images under docs/img. There are 3 more that are worth updating: 
* adhoc.png
* chart.png
* chart_form.png

However, I need to get them up and working first on some reasonable data. I'll do those in a follow-up PR.

**Pull request merged**
