### PR TITLE
Do not display github-actions[bot] in RC testing issue content

### PR DESCRIPTION
**Pull request by amoghrajesh**
Noticed in https://github.com/apache/airflow/issues/44811 that we are displaying the github actions bot in the RC testing issues and thanking it too!

image

We shouldn't be doing that, this PR skips that.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
:robot:

**Review by gopidesupavan — APPROVED** [review]
Nice :)

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
You broke integration tests with this change :P - https://github.com/apache/airflow/actions/runs/12262659739/job/34212827799?pr=44823

I veto this change ;)-- jk ofcourse

**Comment by potiuk** [comment]
:scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream: :scream:

**Comment by amoghrajesh** [comment]
Hahah good one! Its been fixed by https://github.com/apache/airflow/pull/44829

**Comment by amoghrajesh** [comment]
Reopening to trigger tests.

**Pull request merged**
