### PR TITLE
add function to check for table existence

### PR DESCRIPTION
**Pull request by askeys**
@mistercrunch adds a "table_exists" function to the metastore hook.

### CODE REVIEW

**Comment by mistercrunch** [comment]
The metastore thrift service has a `tableExists` call but I think this does essentially the same thing.

**Comment by askeys** [comment]
Oh, if there is a function that already exists, that would be cleaner.  I looked through the list and didn't find it.  Let me check again.

**Comment by askeys** [comment]
Still not finding it... maybe you can point me to the docs?

**Comment by mistercrunch** [comment]
[tableExists](https://hive.apache.org/javadocs/r0.13.1/api/metastore/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.html#tableExists%28java.lang.String, java.lang.String%29)

**Pull request merged**
