### PR TITLE
[AIRFLOW-796] Config options for num_runs, processor_poll_interval, log_level

### PR DESCRIPTION
**Pull request by gsakkis**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-796

Note: please ignore the first commit, it is covered by #2013

### CODE REVIEW

**Comment by jhsenjaliya** [comment]
@gsakkis  , you should squash all commits and update commit msg and PR title according to the guidelines. ref other PRs if you need any reference. Thanks

**Comment by gsakkis** [comment]
Commits squashed

**Comment by bolkedebruin** [comment]
Marking this for 1.8.1

**Comment by bolkedebruin** [comment]
@gsakkis can you please rebase?

**Comment by gsakkis** [comment]
@bolkedebruin commit rebased

**Comment by gsakkis** [comment]
@bolkedebruin any update on this?

**Comment by ejconlon** [comment]
Making `processor_poll_interval` configurable would go a long way toward taming scheduler log spew (which is easily 10GB/week for a small instance I'm running).  Can we get this change in?

**Comment by gsakkis** [comment]
Bump

**Comment by ashb** [comment]
Log_level iss now a config setting.

Remove that, rebase, and test that setting the scheduler job interval still works, then ping be and I can merge.

**Comment by ashb** [comment]
(And sorry for leaving the PR for so long. I realise you've already rebased once and nothing happened. Sorry)

**Comment by XD-DENG** [comment]
@gsakkis FYI: `run_duration` is removed since https://github.com/apache/airflow/commit/327860fe4f04934750a80d39d8e1498398eebf69#diff-1c2404a3a60f829127232842250ff406

**Comment by OmerJog** [comment]
num_runs is also planned to be removed  https://issues.apache.org/jira/browse/AIRFLOW-3533

**Pull request closed without merging**
