### PR TITLE
Add Google Cloud Tasks how-to documentation

### LINKED ISSUE #8208: Create guide for Cloud Tasks operators
**Description**

Hello,

A guide that describes how to use Cloud Tasks service operators would be useful.

We have an example DAG for this service, so the guide should not be a big challenge.

If anyone is interested in this task, I am willing to provide all the necessary tips and information.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

Best regards
Kamil

**Use case / motivation**

N/A

**Related Issues**

Missing guide for GCP: https://github.com/apache/airflow/issues/8209

### LINKED ISSUE #8209: Missing guides for GCP operators
**Description**

Hello, 

Some GCP services do not have guides. It would be nice if we created the missing guides. 

We have an example DAGs for GCP services, so the guide should not be a big challenge.

If anyone is interested in this, I am willing to provide all the necessary tips and information.

All example DAGs for GCP are available in the [example_dags](https://github.com/apache/airflow/tree/master/airflow/providers/google/cloud/example_dags) directory. 

Other guides are [available](https://airflow.readthedocs.io/en/latest/howto/operator/index.html)

Are you wondering how to start contributing to this project? Start by reading our [contributor guide](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst)

**Use case / motivation**

New users want to learn how to use an operator should have documentation. The most important thing in this guide is to include an example of the use of operators.

**Related Issues**

BigQuery: https://github.com/apache/airflow/issues/8200
Cloud Data Loss Prevention (DLP): https://github.com/apache/airflow/issues/8201
Dataflow: https://github.com/apache/airflow/issues/8202
Dataproc: https://github.com/apache/airflow/issues/8203
Datastore: https://github.com/apache/airflow/issues/8204
Cloud Key Management Service (KMS): https://github.com/apache/airflow/issues/8205
Kubernetes Engine: https://github.com/apache/airflow/issues/8206
Machine Learning Engine: https://github.com/apache/airflow/issues/8207
Cloud Tasks: https://github.com/apache/airflow/issues/8208

### PR DESCRIPTION
**Pull request by kazanzhy**
closes: #8208
related: #8209

Add how-to documentation for Google Cloud Tasks.
I've built successfully in a local machine and made static checks.

This PR with the #20138 also closes: #8209

### CODE REVIEW

**Comment by dstandish** [comment]
looks like black failed

**Comment by kazanzhy** [comment]
That's strange. 
I've successfully built docs locally and I can't figure out why images build is failing

**Comment by potiuk** [comment]
> That's strange. I've successfully built docs locally and I can't figure out why images build is failing

This is not images - you just should run -pre-commit and format the code with black via pre-commit.

**Comment by kazanzhy** [comment]
Now seems to be ok @dstandish 
The issue was in `mypy`. Some methods` parameters had no types like `response_view: Optional = None`.
I passed `response_view: Optional[Task.View] = None` in according to documentation.

**Review by potiuk — APPROVED** [review]

**Pull request merged**
