### PR TITLE
 [AIRFLOW-1854] Improve Spark Submit operator for standalone cluster mode

### PR DESCRIPTION
**Pull request by ghost**
At the current state, the spark submit operator does not support standalone cluster mode.
When using such a cluster, it leads to Airflow starting too many Spark jobs in parallel as it is mistakenly interprets the spark-submit.sh returncode 0 as a [SUCCESS].
This PR adds a status check to keep track of the Spark driver status on the standalone cluster.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1854) issue.

### Description
- [x] When executing a Spark submit to a standalone cluster using the Spark submit hook, it will get a return code from the Spark submit shell and not the Spark job itself.
This means when a Spark submit is executed and successfully received by the cluster, the Airflow job will automatically consider it to be successful, even when the Spark job is not yet finished or failed.

When your Airflow connection is set to work with a standalone cluster mode, this sumbitted version of the hook will start tracking the driver status. It parses the logs after spark submit is done and retrieves the driver id and polls the driver status every second.

### Tests
- [x] My PR adds the following unit tests in `/tests/contrib/hooks/test_spark_submit_hook.py`:
    - Shell commands created to discover the driver status
    - Correct parsing of the spark logs to retrieve the driver id and
    the driver status
    - Correct parsing of the connection string

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Good point. I've only used Spark in combination with YARN, so the tracking of standalone applications was not taken into account.

**Comment by bolkedebruin** [comment]
Please retrigger the build (empty commit, close/open pr) we had a transient error on Travis.

Make sure your commits are squashed.

**Comment by ghost** [comment]
I also applied the flask8 style guide.

**Comment by ghost** [comment]
@bolkedebruin I have the feeling there is still something going wrong with Travis

**Comment by bolkedebruin** [comment]
Please squash your commits. Thanks.

**Comment by ghost** [comment]
@bolkedebruin Squashed them. Do you also want the commit of merging master into this branch squashed?

**Comment by bolkedebruin** [comment]
There should be only one commit in this pr. So no merges indeed.

**Comment by ghost** [comment]
@bolkedebruin Done

**Comment by Fokko** [comment]
LGTM

**Comment by ghost** [comment]
There is something going wrong with the Travis build. Second time the test just fails while they were passing before.
Ill just retrigger the build as before as that fixed the issue the previous time.

**Pull request closed without merging**
