### PR TITLE
Revert "[AIRFLOW-6596] Enforce description should not be empty (#7211)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit d553813b0c35f212b2fa10a49e6a542d23e5ee83.

After few reviews, I think the description check is counter-productive. There are many commits
that might not require it and it's not obvious how it should be fixed. I prefer to judge manually if
more description is needed. Also we might quickly end up with bogus descriptions such as copying the title to description which is worse than not having the description.

Also - I think what's really important if we want to enforce description - Then we need to make sure that description is OK in the final commit rather than in PR description. 

Note that PR description is not synchronised after PR is created, so if you create PR with an empty description, you have to update both description in the PR and the commit to get the desired result!

---
Issue link: [AIRFLOW-6596](https://issues.apache.org/jira/browse/AIRFLOW-6596)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by kaxil** [comment]
I feel otherwise. I want to know from the PR description on what I am reviewing without diving into the code.

I am fine with people copying the PR title as description for simple PRs.

**Comment by kaxil** [comment]
I can add some docs in the Contribution guide to make it better. But in general, if you check the line "Description above provides context of the change" and if you don't add a description to it, it doesn't make any sense and that checkmark would mean nothing and is more confusing. 

Also, my main intention with that check was to make PR descriptive without having to look at the code. Basically to answer Why this PR? And What it changes? And/or use-case !

Whether or not the description is added to commit is not that important as our Changelog contains PR number which users can directly click and check.

Let me know if you would like me to add some descriptions in Contributing guide or if you have other views :)

**Comment by potiuk** [comment]
As discussed over the phone - it's more about the error message clarity from mergable than anything else - now it's super confusing what's wrong with the PR for an average user (or even experienced committer :))

**Comment by kaxil** [comment]
Going to merge this to avoid confusion for a few hours before I solve it.

**Pull request merged**
