### PR TITLE
fix cosmos hook static checks by making providing partition_key mandatory

### LINKED ISSUE #38196: Resolve mypy violations for `azure-cosmos` >= 4.6.0
### Body

We limited `azure-cosmos` to < 4.6.0 for now in https://github.com/apache/airflow/pull/38175, but we need to update our code / annotations to make mypy happy again.

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by hussein-awala**
closes: #38196

According to https://github.com/Azure/azure-sdk-for-python/pull/34795#issuecomment-2005120823 we cannot create non-partitioned cosmos collections anymore, this is badly handled in the Python SDK but we will receive an API exception if we try to do that.

I update the PR to make the `partition_key` mandatory, with the possibility to define a default one in the connection.

### CODE REVIEW

**Comment by potiuk** [comment]
Nice :). Airflow detecting and spreading fixes to hundreds of libraries :)

**Review by dirrao — CHANGES_REQUESTED** [review]
Cosmos related test cases are failing.

**Comment by hussein-awala** [comment]
> Cosmos related test cases are failing. 

Check the PR description, it depends on another PR that fixes the issue in the microsoft sdk.

**Comment by hussein-awala** [comment]
@eladkal I updated the PR and its description according to azure python SDK maintainers, could you check if we can consider it as a bug fix or if we need a new major release? Do I need to add something to changelog?

**Comment by eladkal** [comment]
> @eladkal I updated the PR and its description according to azure python SDK maintainers, could you check if we can consider it as a bug fix or if we need a new major release? Do I need to add something to changelog?

I don't think it qualify as breaking but the bext release is major due to another PR so we can treat this one as major change in terms of the entry log.

Simply add the needed explnation for users on the 1.10 entry of the change log

**Review by eladkal — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
