### PR TITLE
Enable setting the base url of the website

### LINKED ISSUE #9777: Helm chart webserver pod does not start when setting the webserver base url
**Apache Airflow version**:
1.10.11

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):
1.15.11

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

Utilize a proxy in front of the airflow webserver service which proxies the `/airflow` prefix to the service.

In the values.yaml file, configure the [webserver base url environment variable](https://airflow.apache.org/docs/stable/configurations-ref.html#base-url) through the `env:` field.  For example, like `"AIRFLOW__WEBSERVER__BASE_URL: domain.com/airflow/"`.  Install the helm chart. The webserver pod crashloops.

**What you expected to happen**:

The helm chart tailors the correct endpoint to access in it's probes.

**What do you think went wrong?**

When the webserver picks the baseurl value up, in my example the health endpoint is located at `airflow/health` but the pod healthcheck is trying to access the `/health` endpoint resulting in a 404 error and resulting in the pod being periodically restarted for failing it's healthchecks.

**How to reproduce it**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by vsimon**
Take into account the path of the base url in liveness and readiness
check probes.

This introduces `baseUrl` as a value to use for the chart's health
checks and also to use to set the AIRFLOW__WEBSERVER__BASE_URL
environment variable.

Fixes #9777
---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
LGTM But would love @dimberman  to take a look

**Comment by dimberman** [comment]
Why would the liveness and readiness probes need a base URL? Aren't those directly performed within the pod already?

**Comment by vsimon** [comment]
I think this is in the case where Airflow is run behind a reverse proxy.

https://airflow.readthedocs.io/en/stable/howto/run-behind-proxy.html

As in an example, if the proxy is configured to serve airflow from `/airflow` in it's configuration, then the base_url gives the ability to set the correct endpoint.

What I notice without it is, when `/airflow/home` or `/airflow/graph` is accessed, airflow tries to redirect and fetch `/home` or `/graph` which are both 404s.

**Comment by vsimon** [comment]
I notice without a base_url set, the healthchecks `/health` endpoint returns 200 OK but accessing airflow through the reverse proxy fails.
Then with a base_url set (to say https://domain.com/airflow/), accessing airflow through the reverse proxy works, but the healthchecks fail (`/health` returns 404, `/airflow/health` returns 200 OK)

**Comment by dimberman** [comment]
@vsimon I guess I'm a bit confused here, wouldn't that be testing the reverse proxy instead of airflow? Why would you need to access airflow via the reverse proxy for a health check?

**Comment by mik-laj** [comment]
@dimberman The base_url option adds a prefix to each address (including health check), so this change looks good. This option is implemented as WSGI middleware, so it affects all addresses. This option is not related to reverse proxy, but is often used together. We have a similar option - proxy_fix and it is closely related to the option and has a similar purpose, but a different way of working.
Please look here: 
https://github.com/apache/airflow/blob/master/tests/www/test_app.py

**Comment by aneesh-joseph** [comment]
> @dimberman The base_url option adds a prefix to each address (including health check), so this change looks good. This option is implemented as WSGI middleware, so it affects all addresses. This option is not related to reverse proxy, but is often used together. We have a similar option - proxy_fix and it is closely related to the option and has a similar purpose, but a different way of working.
> Please look here:
> https://github.com/apache/airflow/blob/master/tests/www/test_app.py

If that's the case may be the webserver should be tweaked to make sure that the healthcheck url is excluded from this prefixing? I think it doesn't make sense to  set the probes on the reverse proxy url Probes are a way for kubernetes to check if that specific pod is healthy, the reverse proxied health url doesn't give that information

**Comment by gowtamchandrahasa** [comment]
@vsimon , I'm facing this exact issue currently. Since this PR is not merged, is there some way to handle this issue for now? TIA!

**Comment by vsimon** [comment]
hi @gowtamchandrahasa  The way I handled it was within the helm chart. I happen to be using chart version: 7.16.0.

Assuming I have a dns name (the hostname of the reverse proxy) and a path (the path configured in the reverse proxy to map to the airflow web serevice)

```
$DNS_NAME
$PATH_NAME
```

I set these two fields:

```
      web:
        baseUrl: https://$DNS_NAME/$PATH_NAME

      ingress:
        web:
          livenessPath: /$PATH_NAME/health
```

**Pull request closed without merging**
