### PR TITLE
[AIRFLOW-2233] Update updating.md to include the info of hdfs_sensors…

### PR DESCRIPTION
**Pull request by feng-tao**
… renaming

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
   update updating.md to include hdfs_sensors renaming info.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
trival change.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
@Fokko  @sekikn

**Comment by sekikn** [comment]
I prefer full package name (airflow.contrib.sensors.hdfs_sensor) since airflow.sensors.hdfs_sensor was not changed at all. +1 other than that.

**Comment by feng-tao** [comment]
thanks. Didn't know that we have two files with the same name. Just updated. BTW, should we consolidate these two files into single hdfs_sensor file instead to avoid confusion? @Fokko  @sekikn

**Comment by sekikn** [comment]
Sorry, I'm not sure if there are any rules or criteria to promote contributed stuff to core. @Fokko Any suggestions?

**Comment by Fokko** [comment]
Can you rebase onto master?

**Comment by Fokko** [comment]
The main criteria to promote stuff to core is the test-coverage, if this is high enough, it is ok to move it to core.

**Comment by feng-tao** [comment]
@Fokko , updated :) . the travis ci issues seems to be related something else.

**Comment by Fokko** [comment]
@feng-tao Thanks!

**Pull request closed without merging**
