### PR TITLE
Bring back documentation publishing to Canary builds

### LINKED ISSUE #41931: Bring back Documentation publishing in Canary runs
Currently, documentation publishing in Canary runs is disabled. This caused several problems (that will get worse over time):

* we do not test publishing worklfow - and it might stop working any time and break release process
* the "sphinx inventory" is not published for airlfow and providers which means that docs building will take more time and will lead to potential errors

https://github.com/apache/airflow/blob/7cf54a734e1eefa04ab710cb2eb364d529c6b1b1/.github/workflows/static-checks-mypy-docs.yml#L246

The reason is that public runners default "workspace" disk is too small to fit checked out documentation while being published - and "self-hosted ASF runners" were unstable even if they had bigger disk.

There are few ways we can address it:

* apply the same workaround that @kaxil did for "airflow-site" building : https://github.com/apache/airflow-site/pull/1055
* switch back to "ASF self-hosted runners" https://github.com/apache/airflow/actions/runners?tab=self-hosted
* switch to large or medium "ARC self-hosted runners" after https://github.com/apache/airflow/pull/41728 is completed

It's been disabled in https://github.com/apache/airflow/pull/40921

### PR DESCRIPTION
**Pull request by potiuk**
We are using the same approach as in
https://github.com/apache/airflow-site/pull/1055/ where we utilise /mnt directory to store checked out airflow-site.

Fixes: #41931

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
This seems to be even simpler than https://github.com/apache/airflow-site/pull/1055 as  we only need to really use the /mnt space for the airflow-site separate checkout .

**Comment by potiuk** [comment]
BTW. I want to get it out "quick-ish" because it causes very long  "spellcheck" checks on some PRs because first pass of spell-check does not local build, so if inventories are out-dated, it will try to spellcheck, fail, and then fall-back to rebuilding everything -  and it can take more than hour.

**Comment by potiuk** [comment]
Example here: https://github.com/apache/airflow/actions/runs/11591221918/job/32271148668?pr=43503

**Review by eladkal — APPROVED** [review]

**Review by kaxil — APPROVED** [review]
Thanks @potiuk for taking care of it.

**Comment by potiuk** [comment]
Spellcheck still running in 1h 30 minutes - hopefully last pass of the spellcheck now. Testing this change is a PAIN. I understand @kaxil why it was not high priority :D

BTW. Might want to optimise that one but when we have regular pushes - this will happen way less frequently.

**Comment by potiuk** [comment]
This is really bad thing that is happening -> downloading inventories (old) -> running spellcheck for all providers -> failing some as inventories are outdated and miss some references -> cleaning all -> running build together (failing for some cases - because local inventories were outdated) -> re-running again -> failing a bit less number of those as local inventories were rebuilt -> re-running build again for the remaining ones -> running spellcheck for all of them now with locally rebuilt inventories -> it's a bit madness :D

**Comment by ashb** [comment]
Failing with

```
fatal: could not create work tree dir '/mnt/airflow-site/airflow-site': Permission denied
```

😞

**Comment by potiuk** [comment]
So... Not that easy :)

**Comment by potiuk** [comment]
Right ... Sudo :)

**Comment by potiuk** [comment]
I hope I got this right this-time. It's not only the sudo, but the `df -h` had shown that we did not have this extra space and it was because ASF self-hosted runners we used to use for publishing actually did not have this extra volume mounted.

I switched back publlishing and doc building back to public runners and :crossed_fingers: it will work this time.

We will see in 2 hours

**Comment by potiuk** [comment]
Almost: 

image

**Comment by kaxil** [comment]
🤞

**Comment by potiuk** [comment]
Finally!

**Comment by kaxil** [comment]
Nice

**Comment by potiuk** [comment]
> Nice

Yeah... ❤️  it too :)

**Pull request merged**
