### PR TITLE
[AIRFLOW-4950] Simplify string format

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM

**Comment by ashb** [comment]
I think I'm -0.5 on this -- it is a lot of diff that makes `git blame`/history noisier and what is there is not deprecated or wrong.

**Comment by mik-laj** [comment]
This will help maintain good health of the code. When this change is accepted, it will be possible to automatically verify the code.
https://github.com/asottile/pyupgrade

**Comment by ashb** [comment]
Is the current syntax deprecated by Python?

**Comment by mik-laj** [comment]
No, but it seems to me that when the whole code will be uniform, it will be a more readable code. This tool will allow us to automatically unify the whole code, and in addition we will be ensured that we always use the recommended syntax. I do not care very much about this change.  My main goal is to upgrade the syntax to Python 3.6.If we additionally get a code that will be unified in terms of code style, this is an additional plus.

**Comment by ashb** [comment]
We still need to support Py 3.5 for a while yet, and I'm not in favour of Yet Another Style Checker, and I honestly couldn't care which style of string formatters people use in PRs, my concern here is 1) the current form works and isn't deprecated, it is valid Python 3.8 code. and 2) around git blame/history.

To me the explicit numbers are clearer - I prefer the current version of these two:

```diff
                    "Error occurred when calling the grpc service: {0}, method: {1} \
                    status code: {2}, error details: {3}"
                    "Error occurred when calling the grpc service: {}, method: {} \
                    status code: {}, error details: {}"
```

(that is admittedly the longest one in the diff)

And just so you are aware: if we merge this change it makes a 1.10.5 almost impossible as now there are 62 more files that won't work on Py2. (`super()` was so far the only other major py2 issue and that one is easy enough to catch. This is much trickier.)

**Comment by ashb** [comment]
Thank you, and sorry to be a bit of a pain - I'm coming at this with my "I've just cherry-picked 100s of commits over the last few months" hat on.

**Comment by potiuk** [comment]
Good points @ashb

**Pull request closed without merging**
