### PR TITLE
[FIX] Fixed databricks repair run deferrable

### PR DESCRIPTION
**Pull request by raghvendra-singh1**
`_handle_deferrable_databricks_operator_completion`  is assuming repair_run will always be called in case of repair_run = True however after new_settings change, that decision also include reason match and hence flow exit with execute_complete method. These changes will consider the settings and then run for repair run flow.
@Lee-W 

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by Lee-W — APPROVED** [review]
LGTM

**Comment by Lee-W** [comment]
Will need to get the tests fixed

**Comment by raghvendra-singh1** [comment]
Sure, will look into that

**Review by Lee-W — CHANGES_REQUESTED** [review]
need to fix the CI issue before merging

**Comment by gaurav7261** [comment]
@Lee-W can you please review and merge this bug fix PR

**Comment by Lee-W** [comment]
> @Lee-W can you please review and merge this bug fix PR

Sure, will take a look once the test and CI pass

**Comment by raghvendra-singh1** [comment]
@Lee-W Made some changes. Those failing CI tests should be fixed now. Could you please review?

**Comment by Lee-W** [comment]
rebased from the latest main to see whether the last test passes

**Comment by raghvendra-singh1** [comment]
@Lee-W Passed the CI tests. Could you please review now?

**Review by Lee-W — APPROVED** [review]

**Pull request merged**
