### PR TITLE
introduce dag processor job fix #27140

### LINKED ISSUE #27140: Invalid livenessProbe for Standalone DAG Processor
### Official Helm Chart version

1.7.0 (latest released)

### Apache Airflow version

2.3.4

### Kubernetes Version

1.22.12-gke.1200	

### Helm Chart configuration

```yaml
  dagProcessor:
    enabled: true
```

### Docker Image customisations

```dockerfile
FROM apache/airflow:2.3.4-python3.9

USER root
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update && apt-get install -y google-cloud-cli
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
USER airflow
```

### What happened

Current DAG Processor livenessProbe is the following:
```
CONNECTION_CHECK_MAX_COUNT=0 AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR exec /entrypoint \
    airflow jobs check --hostname $(hostname)
```
This command checks the metadata DB searching for an active job whose hostname is the current pod's one (_airflow-dag-processor-xxxx_). 
However, after running the dag-processor pod for more than 1 hour, there are no jobs with the processor hostname in the jobs table.
image
image

As a consequence, the livenessProbe fails and the pod is constantly restarting.

After investigating the code, I found out that DagFileProcessorManager is not creating jobs in the metadata DB, so the livenessProbe is not valid.

### What you think should happen instead

A new job should be created for the Standalone DAG Processor.
By doing that, the _airflow jobs check --hostname <hostname>_ command would work correctly and the livenessProbe wouldn't fail

### How to reproduce

1. Deploy airflow with a standalone dag-processor.
2. Wait for ~ 5 minutes
3. Check that the livenessProbe has been failing for 5 minutes and the pod has been restarted.

### Anything else

I think this behavior is inherited from the NOT standalone dag-processor mode (the livenessProbe checks for a SchedulerJob, that in fact contains the "DagProcessorJob")

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by farhan0syakir**
fixes: https://github.com/apache/airflow/issues/27140

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by farhan0syakir** [comment]
fix #27140

**Comment by potiuk** [comment]
Looks cool @farhan0syakir. But I have two asks:

1. Did you test it with more than one DagFileProcessor running on two different subdirs - each of them should be a potentially separate job and have separate liveness probe.

2. Could you please add more description in the commit than `fixes: https://github.com/apache/airflow/issues/27140` ? The thing is that commits remain with us - while issues/PR history are kept in GitHub and we need to (as per ASF rules) keep all the context in Git, so we need to have more complete description o fhte contex and the fix in the commit.

**Comment by farhan0syakir** [comment]
Hi @potiuk 
let me answer your question.
1. I didn't. However, when I tried that, I got another question, is it possible to specify subdir in the current helm values.yaml?If not, probably need to raise another issue(?). Also for the liveness I use `airflow jobs check --hostname $(hostname)` which specify hostname so it will check it separately
2.  I agree, I accidentally commited that in another branch, which I deleted now. In here the commit message is introduce dag processor job. Is it okay?

**Comment by potiuk** [comment]
Sorry for the delay::

1. I think it would be good to maka a PR with this change.
2. Yeah. rebase and add it. 

@mhenc - also can yoy please let us know what you think about it?

**Comment by mhenc** [comment]
Thank you for looking int that.
This change looks good for me. 
TBH I haven't tested it with Helm (as we use other way of deploying workloads to K8s).

**Review by potiuk — APPROVED** [review]

**Pull request merged**
