### PR TITLE
Verify enough resources for Docker

### LINKED ISSUE #20251: Breeze: Verify if there are enough resources avaiilable in Breeze
At entry of the Breeze command we verify if there iss enouggh CPU/memory/disk space and print (coloured) information if the resources are not enough.

We should replicate that in Python

### PR DESCRIPTION
**Pull request by edithturn**
This PR is to fix the one that was merged: https://github.com/apache/airflow/pull/20763
Point:
The runners have different filesystems to check the disk available. The one that is mounted should be taken to extract data of the disk available in the runners.

Please keep in mind it is a work in progress this is Work in Progress, and for now, I am printing "df -h" on the runner.

Close: #20251

### CODE REVIEW

**Comment by potiuk** [comment]
I think this is a different change ?

**Comment by edithturn** [comment]
@potiuk I am checking this data in the runner:
Screenshot from 2022-01-19 10-58-14

**Comment by potiuk** [comment]
You won't see it because you are not committer :). I will have to push it

**Comment by potiuk** [comment]
You will be able to see it here: https://github.com/apache/airflow/pull/20959

**Comment by potiuk** [comment]
BTW. @edithturn  When you create a PR you can create it as draft (not very well visible drop-down next to "create Pull Request" button if you want to do something for test - no need to prefix things with [WIP] . You can also convert it to draft and back any time via "convert to draft" link (or "Ready for Review" button). I will convert it to draft now.

**Comment by edithturn** [comment]
ohhh, @potiuk I was wondering how to make it to avoid notifying others, thank you so much! 🙏🏼

**Comment by edithturn** [comment]
@potiuk I fixed it. I am considerign:

`# Disk current available
    partition_usage = psutil.disk_usage('/')
    disk_available = round(get_size(partition_usage.free))`

Also, I am round the value.

**Comment by potiuk** [comment]
FYI @edithturn : I am running it in my PR to check if it will also work for committers: https://github.com/apache/airflow/pull/20959

**Comment by edithturn** [comment]
Thank you so much @potiuk, I also sent the last test, it takes time, especially the one which build the image.

**Comment by edithturn** [comment]
What defines a "committer"?

**Comment by potiuk** [comment]
> What defines a "committer"?

This list: https://github.com/apache/airflow/blob/c13558186c678c15938db5ea3a65f948061af72a/.github/workflows/ci.yml#L96

**Comment by edithturn** [comment]
> > What defines a "committer"?
> 
> This list:
> 
> https://github.com/apache/airflow/blob/c13558186c678c15938db5ea3a65f948061af72a/.github/workflows/ci.yml#L96

I see you have elevated privileges for Github events, right?
Are there things you can see in CI's processes that we can't?

**Comment by potiuk** [comment]
> Are there things you can see in CI's processes that we can't?

Nope. It's just where the builds are run. There is no  difference in what we see.

**Comment by edithturn** [comment]
> I am running it in my PR to check if it will also work for committers: [#](https://github.com/apache/airflow/pull/20959)
Screenshot from 2022-01-20 12-40-54

@potiuk this is the result on your runner. I also checked the one I sent, it finished successfully: https://github.com/apache/airflow/actions/runs/1724358952

let me know what are you thoughts

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Careful :tada: :)

**Comment by potiuk** [comment]
:crossed_fingers:

**Comment by edithturn** [comment]
🤞🏼

**Comment by edithturn** [comment]
I think it worked! https://github.com/apache/airflow/runs/4886367996?check_suite_focus=true 👀

**Pull request merged**
