### PR TITLE
Add new Compute Engine Operators and fix system tests

### PR DESCRIPTION
**Pull request by VladaZakharova**
Added new Compute Engine Operators and updated existing system tests Compute Engine operators. 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Some conflicts :(

**Comment by potiuk** [comment]
conflicts + errors to fix :(

**Comment by potiuk** [comment]
confilcts to be resolved - likely after __future__.annotation change.

**Comment by potiuk** [comment]
Docs failing :(

**Comment by potiuk** [comment]
Some tests are failing.

**Comment by VladaZakharova** [comment]
> Some tests are failing.

Yes, but the problem is that all these tests, that are failing in the CI, I can run locally without any errors for all Python versions. Can you please check what could be the reason of the errors? Thanks!

**Comment by o-nikolas** [comment]
> > Some tests are failing.
> 
> Yes, but the problem is that all these tests, that are failing in the CI, I can run locally without any errors for all Python versions.

How are you running the postgres CI tests?

> Can you please check what could be the reason of the errors? Thanks!

The errors can be seen [here](https://github.com/apache/airflow/actions/runs/3111337410/jobs/5045988834):
```
 ==== Providers postgres: 9 failures ====

tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_delete_instance_group_manager_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_delete_instance_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_delete_template_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_get_instance_group_manager_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_get_instance_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_get_template_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_insert_instance_group_manager_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_insert_instance_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
tests/providers/google/cloud/hooks/test_compute.py::TestGcpComputeHookApiCall::test_insert_template_should_not_throw_ex_when_project_id_none: google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
Error: Process completed with exit code 1.
```

**Comment by VladaZakharova** [comment]
Hi Team, 
I have resolved all the conflicts and errors in the tests but continue getting errors in Helm(https://github.com/apache/airflow/actions/runs/3263824766/jobs/5368266070#logs) and MSSQL(https://github.com/apache/airflow/actions/runs/3263824766/jobs/5366146241). Rebasing from main brach didn't work for me. Also i was trying to restart the build several times but it also didn't work for me. May be someone already faced this kind of problem?

**Comment by lwyszomi** [comment]
https://github.com/apache/airflow/issues/9941

**Comment by potiuk** [comment]
I think configure aws credentials update was not intentional. Please use "git submodule update" to update your version to the latest we have :)

**Comment by lwyszomi** [comment]
@potiuk These changes are open for a long time because we had some problems with build, maybe now when build passed is possibility to review and merge it?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
