### PR TITLE
Refactor: consolidate import time in providers

### PR DESCRIPTION
**Pull request by eumiro**

### CODE REVIEW

**Comment by vincbeck** [comment]
Why doing this change? Why is it better?

**Comment by o-nikolas** [comment]
> Why doing this change? Why is it better?

I agree, I especially don't like PRs with zero description. What is the motivation here? Any links to resources that explain why this is a best practice?

**Comment by Lee-W** [comment]
I guess the motivation is to unify how we import `time` into airflow. I found `import time` is used more frequently than `from time import sleep`.

**Review by Lee-W — APPROVED** [review]

**Review by uranusjr — APPROVED** [review]

**Review by vincbeck — APPROVED** [review]

**Comment by eumiro** [comment]
> Why doing this change? Why is it better?

It was to have the same import of time everywhere in the repo. `import time` and `from time import time` makes it confusing.

**Pull request merged**
