### PR TITLE
Bump cattrs version

### LINKED ISSUE #24421: Airflow pinning old version of attrs: apache-airflow (>=2.3.2,<3.0.0) requires attrs (>=20.0,<21.0)
### Apache Airflow version

2.3.2 (latest released)

### What happened

Hello Airflow is pinning old version of attrs and this is leading to version conflict on our side to use Airflow.

```
And because every version of aws-cdk-lib requires attrs (>=21.2,<22.0) or jsii (>=1.58.0,<2.0.0) (4), every version of aws-cdk-lib requires attrs (>=21.2,<22.0)
      Because no versions of apache-airflow match >2.3.2,<3.0.0
   and apache-airflow (2.3.2) depends on attrs (>=20.0,<21.0), apache-airflow (>=2.3.2,<3.0.0) requires attrs (>=20.0,<21.0).
      Thus, apache-airflow (>=2.3.2,<3.0.0) is incompatible with aws-cdk-lib.
```

### What you think should happen instead

Please upgrade attrs to >=21

### How to reproduce

_No response_

### Operating System

macOS Monterey - 12.3.1

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tomsej**
related: #24421

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ashb — COMMENTED** [review]
Sounds good to me, but haven't checked anything in detail here.

Have you checked the changelog of cattrs to see if anything is likely to break for us?

**Comment by tomsej** [comment]
> Sounds good to me, but haven't checked anything in detail here.
> 
> Have you checked the changelog of cattrs to see if anything is likely to break for us?

Honestly, it is hard to say. Previously, it broke a lineage (#16172), but it should be fixed in https://github.com/python-attrs/cattrs/issues/151. There is also a new validation mode https://cattrs.readthedocs.io/en/latest/validation.html but I do not think it should break anything.

Build is failing but it seems to be unrelated to my changes.

**Comment by ashb** [comment]
> #56 144.0             error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/local/include/python3.10 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -c build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-x86_64-3.10/build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-x86_64-3.10/build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o.d -std=c99" failed with exit status 1

Build error is caused by trying to build numpy on 3.10 (numpy still doesn't have a wheel for 3.10?!)

**Comment by ashb** [comment]
Hmm, recent versions do, but we tried to pull in numpy==1.19.4, but that is not what's in any of the constraint files https://github.com/apache/airflow/blob/constraints-main/constraints-3.10.txt  -- any idea why that might be @potiuk ?

**Comment by potiuk** [comment]
> Build error is caused by trying to build numpy on 3.10 (numpy still doesn't have a wheel for 3.10?!)

Bumping cattrs unblocked numpy to be bumped to 1,23.* (from 1.22.4) which apparently has problem with 3,10. I thin k 1.22.4 also does not support 3.10 fully -  but it did not have a detection of that :shrug: 

numpy is only needed in oracle provider it seems (BTW. we should get rid of it - I believe it is only needed there to do detection

The solution @romsej will be to change in https://github.com/apache/airflow/blob/main/airflow/providers/oracle/provider.yaml

```
dependencies:
   - numpy 
```

to:

```
dependencies:
   - numpy;python_version<"3.10"
   - numpy<1.23;python_version>="3.10"
```

But I will try to get rid of it completely in parallel anyway

**Comment by potiuk** [comment]
Ah noo....  numpy==1.19.4 :...... This is strange.

**Comment by tomsej** [comment]
I do not think that is the case. Seems some other builds are also failing - https://github.com/apache/airflow/runs/7806805101?check_suite_focus=true#step:13:19601. I cannot investigate since I am not by the computer.

**Comment by potiuk** [comment]
Yeah. Lookiung at it

**Comment by potiuk** [comment]
This is a more complex issue - looks like `pip resolver` started to downgrade our pyarrow for 3.10 which triggered downgrading numpy :)

**Comment by tomsej** [comment]
Ohh, thanks a lot! Let me know if I can help...

**Comment by potiuk** [comment]
Fix here https://github.com/apache/airflow/pull/25697 - once it gets green and get merged please rebase @tomsej :)

**Comment by potiuk** [comment]
Ok. I merged the fix and rebased your PR on top @tomsej - let's see :)

**Comment by tomsej** [comment]
@potiuk thanks a lot, I really appreciate it! It failed on binding address for Trino:

``` ERROR: for airflow-integration-postgres_trino_1  Cannot start service trino: driver failed programming external connectivity on endpoint airflow-integration-postgres_trino_1 (50f5ffd5c1adb15ff3699b0b430ad1b8ae39296afe40f7cb5d97eaae97dc58ad): Error starting userland proxy: listen tcp4 0.0.0.0:38080: bind: address already in use```

Do I need to rerun the tests?

**Comment by potiuk** [comment]
I re-run it :)

**Review by potiuk — APPROVED** [review]

**Pull request merged**
