### PR TITLE
Use Sphinx Auto Typehints for docstrings

### PR DESCRIPTION
**Pull request by kaxil**
https://pypi.org/project/sphinx-autodoc-typehints/

This extension allows you to use Python 3 annotations for documenting acceptable argument types and return value types of functions. This allows you to use type hints in a very natural fashion, allowing you to migrate from this:

```
def format_unit(value, unit):
    """
    Formats the given value as a human readable string using the given units.

    :param float|int value: a numeric value
    :param str unit: the unit for the value (kg, m, etc.)
    :rtype: str
    """
    return '{} {}'.format(value, unit)
```

to

```
from typing import Union

def format_unit(value: Union[float, int], unit: str) -> str:
    """
    Formats the given value as a human readable string using the given units.

    :param value: a numeric value
    :param unit: the unit for the value (kg, m, etc.)
    """
    return '{} {}'.format(value, unit)
```

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Is it compatibile with sphinx-autoapi?

**Comment by kaxil** [comment]
> Is it compatibile with sphinx-autoapi?

I think so, have seen few projects use it: https://github.com/asappresearch/flambe/blob/38e92673d00550e5f6292330f7dda899b2bf581c/docs/requirements.txt

**Comment by mik-laj** [comment]
@kaxil I'll check it out. It used to be incompatible, ie sphinx-auto-typehint only worked properly on pages that do not use sphinx-autoapi.

**Comment by mik-laj** [comment]
It still doesn't work.
Before:
Screenshot 2020-10-12 at 13 24 21
After: 
Screenshot 2020-10-12 at 14 24 42

This only adds types on one page - https://airflow.readthedocs.io/en/latest/macros-ref.html#airflow.macros.datetime_diff_for_humans. We use `.. automodule:: `and `.. autofunction:: `, but these functions don't have type hints, so it's not very useful in our project.

**Comment by kaxil** [comment]
> It still doesn't work.
> Before:
> Screenshot 2020-10-12 at 13 24 21
> After:
> Screenshot 2020-10-12 at 14 24 42
> 
> This only adds types on one page - https://airflow.readthedocs.io/en/latest/macros-ref.html#airflow.macros.datetime_diff_for_humans. We use `.. automodule:: `and `.. autofunction:: `, but these functions don't have type hints, so it's not very useful in our project.

gaah :( Sad

**Pull request closed without merging**
