### PR TITLE
Add pre-commits preventing accidental API changes in common.sql

### PR DESCRIPTION
**Pull request by potiuk**
We had recently some mishaps when it comes to changes to the common.sql provider that accidentally changed API of the common.sql providers and they passed both tests and reviews.

Common.sql is pretty special provider because it used by other providers and we have to make sure the API it epxoses is backwards compatible, otherwise upgrading common.sql provider might break those providers.

This had already happened:

* The #26761 refactored common.sql provided and removed some methods that were actually used by Google Provider

* This caused a problem described in #27838 and forced us ot yank common.sql 1.3.0 and release 1.3.1 with the methods added back in #27843

This change introduces tools and process to flag common.sql API changes that are likely backwards compatible.

They will require a deliberate action from the contributor who introduces a breaking API to common.sql, it will also help to flag to reviewer when such a change is made.

The idea is based on how Android OS handles flagging API changes for their public APIs.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @vincbeck @alexott @oliviervg1 @kazanzhy - this is the pre-commit tests that I described in our previous discussions. It should flag any changes to the common.sql API when they happen, so that it is not easy to change the API accidentally and reviewers can also immediately see that the API has been changed.

We are still keeping `_parse_boolean` as part of the public API - even now it is used by google provider.

Examples of errors printed when there are changes in the API:

1) When only new methods are added, the contributor will have to just commit the change:

Screenshot 2022-11-27 at 02 10 29

Screenshot 2022-11-27 at 02 11 59

2) When there is removal, the contributor will have to manually update the `api.txt` file:

Screenshot 2022-11-27 at 02 13 16

Screenshot 2022-11-27 at 02 13 36

3) Similarly- when there is an update, to exisiting API, user will have to manually update the `api.txt` file:

Screenshot 2022-11-27 at 02 15 16

Screenshot 2022-11-27 at 02 18 40

**Comment by potiuk** [comment]
Also the second part:

1) Here is how checking if other providers are only using the public API:

Screenshot 2022-11-27 at 02 26 53

2) And here error returned by pre-commit in case any non-public method is used:

Screenshot 2022-11-27 at 02 29 50

**Comment by potiuk** [comment]
BTW. When we see it works, we should be able to use very similar approach (and reuse the code) for core API s - this should be a prerequisite for splitting providers.

**Comment by potiuk** [comment]
I reviewed and clarified (it's clearere and simpler I hope) the description of the API verification processs in the README_API.md. I've also added the "Possible future work" chapter explaining how results of experimenting with API in the `common.sql` might be eventually converted into much more comprehensive tool for internal `API` verification.

This might be not only for cross-provider dependencies but also for `providers` -> `Airflow core` dependencies eventually. 

We've been discussing it several times before, and from those discussions, I think having such comprehensive API "snapshot" and "verification" tooling is a prerequisite for the future splitting of providers to separate repos (if we decide to do that of course).

Eventually e might give external provider developers a tool to verify if the providers they develop, are API-level compatible with certain versions (+) of the Apache Airflow. With approach similar to what I described, we might not only be able to finally be able to tell "Those are the official Airflow classes/methods you can use and rely on" but also have a mechanism for provider developers to use them - we will be able to test those for our providers (once/if we split them in a separate repository.

**Comment by alexott** [comment]
That's really nice feature!

**Comment by potiuk** [comment]
> That's really nice feature!

Indeed. I found this kind of approach works really well for Android OS (I've been developing custom Android OS and migrating between different API versions). It's quite a bit of more complex beast for Android but it seems we are getting to the point to start implementing something similar as it might prevent some problems that we already started to experience.

**Review by ashb — COMMENTED** [review]
Is this really a "pre-commit" check or should this just be in the unit tests?

(We seem to be adding more and more and more checks over time to pre-commit. Is there any rhyme or reason to what goes where?

**Comment by ashb** [comment]
I love this idea, however I think using https://mypy.readthedocs.io/en/stable/stubgen.html might be a good idea -- it captures (I think) everything we want but we have far less code to maintain as a result.

**Comment by potiuk** [comment]
> Is this really a "pre-commit" check or should this just be in the unit tests?
> 
> (We seem to be adding more and more and more checks over time to pre-commit. Is there any rhyme or reason to what goes where?

I think for me the rule of thumb I see is what we are testing. 

* The "unit tests" should test the "real" airflow functionality. (i..e whether things work as expected even if some of the things they use are mocked).  
* Static checks (i.e. pre-commits) on the other hand check if the "code fullfils certain criteria" (formatting, Type checking, using certain constructs,  etc.).

The tests above check if:

a) the API has not changed accidentally
b) whether the code is only using what is intended 

IMHO, if we need to run AST parsing for Airflow code, this is a clear indication we analyse the code of Airlfow not the functionality of Airflow. So they both seem to fit  in the second camp.

There are other criteria - such as  how fast things are, whether they are feasible to be run in pre-commit - before each commit (if you have pre-commit installed), which also boils down to - whether we can run them super-selectively - only for changed files in some very selected part of the code and be pretty sure about the result - this is what pre-commit gives us.  

In this case - yes - we are running the tests for "common.sql" in the first case and for all providers in the other case - and it will give good results if we only change few files in providers and run the pre-commit - it should fail the same as we run it for all applicable files.  

So yeah - this one very firmly goes into pre-commits.

Side commend. As discussed in the previous discussion with @vincbeck - we could add "regular" unit tests (or rather system tests following the AIP-47) to add similar checks on "whether it works" level https://github.com/apache/airflow/pull/27854#issuecomment-1325325982 - but this seems to be quite an impossible feat because we would have to run tests with literally every released version of the other providers. 

Another side - comment. There is another (upcoming) example which will go into unit tests and it would explain where the difference is. For AIP-44 I plan to run ALL APPLICABLE unit tests of our in a "db-less" backend - i.e. with only internal API server running - and making sure our code will not execute any SQLAlchemy/DB operation. - simply to make sure that Airlfow worker, dag file processor, triggerer are truly - DB-less. And in this case this falls precisely in the other camp - where we want to actually "run" the real airflow code and see that it behaves as expected.

**Comment by potiuk** [comment]
> I love this idea, however I think using https://mypy.readthedocs.io/en/stable/stubgen.html might be a good idea -- it captures (I think) everything we want but we have far less code to maintain as a result.
> 
> Oh: this might not let us capture only _specific_ "private" things we want. Humbug.

Interesting idea. I will see if I can bend the stubgen to our case, I would also prefer not to have our own code doint this AST parsing (I've learned a bit and it's simple, but not having to do it would be a plus). The "diff" part is going to work very similarly and .pyi file seems to fulfill very well the criteria I have for the API definition.  The not-really-privte-even-if -it-shoudl be might be indeed a blocker, but maybe I can bend it to our will a bit. 

Also one difficulty with .pyi file that we would have to parse the file anyway to check if our code is actually using the "exposed" API functions.  I am not sure if we can run any check to tell "Am I only using the stuff from that .pyi file and nothing else"? 

But the idea made me think - maybe we can do something a bit different. Maybe instead of generating the api file we could generate the .pyi files and let the Mypy checks to the verifications for us. I will explore this one.

**Comment by potiuk** [comment]
> But the idea made me think - maybe we can do something a bit different. Maybe instead of generating the api file we could generate the .pyi files and let the Mypy checks to the verifications for us. I will explore this one.

Hmm. The `--include-private` flag does not really work (and it is far too broad). 

 I think we could be able to add some post-processing of the stub files to include the _private stuff that `could be used`. Let me see if I can implement it easily. I think it should be possible to just add some hard-coded replacements. I really like the idea that the "API" specification will be standard `.pyi` files, rather than our proprietary format.

MyPy actually does even better job than our rudimentary check in this case, It actually detected that we also have another case that we should handle (which is enough of a justification for me to really bend it to our will):

image

I just have to make sure to surface the information to the comon.sql contributor that those issues should be treated somehow differently and add smarter generation of the stubs - rather than outright generating, them, we can run them to a separate folder, compare and then decide what to do.

**Comment by ashb** [comment]
Oh nice.

>  rather than outright generating, them, we can generate them to a separate folder, compare and then decide what to do.

Yeah, perhaps we have them generated/stored in the normal location (`airflow/providers/common/sql/hooks/sql.pyi`) and then the test generates those to a temp folder and compares them?

**Comment by ashb** [comment]
> The "unit tests" should test the "real" airflow functionality. (i..e whether things work as expected even if some of the things they use are mocked).

Same criteria but different view: To me ensuring that we maintain back compat of the provider is part of the real functionality.

Ultimately it doesn't matter, so long as it's tested somewhere. (If I was writing it I would have put it in unit tests, but I'm not so it doesn't really matter where it is 😄)

**Comment by potiuk** [comment]
> Same criteria but different view: To me ensuring that we maintain back compat of the provider is part of the real functionality.

But we do not actually "run" those methods - we just statically verify them them that they are correct.

**Comment by potiuk** [comment]
> Yeah, perhaps we have them generated/stored in the normal location (`airflow/providers/common/sql/hooks/sql.pyi`) and then the test generates those to a temp folder and compares them?

Yep. I am sending PR with that shortly

**Comment by potiuk** [comment]
The mypy change is in https://github.com/apache/airflow/pull/27962/ - overall it's even more code eventually (multiple stub files generated, and I also had to handle black formatting of the resulting code as well as nicely handle cases where whole python files would be deleted (or renamed).

I think though it is totally worth - it also because the .pyi files will be part of the provider package and you will not only check it during our pre-commits but also any of the users of common.sql provider who uses mypy will have errors when using internal methods. So ultimately I think this was a great suggestion @ashb

**Comment by potiuk** [comment]
closing in favour of #27962

**Pull request closed without merging**
