### PR TITLE
[AIRFLOW-1656] Tree view dags query changed

### PR DESCRIPTION
**Pull request by djo10**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1656

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Base date and number of runs could not be set, tree view was unusable for None schedule dags (externally triggered). Loading of that page lasted too long when there are many dag runs. This is fixed in this PR.

before:
tree_view_old
after:
tree_view_new

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
No unit tests.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by djo10** [comment]
This is bug from airflow 1.9.0
After i noticed Jira duplicates :
https://issues.apache.org/jira/browse/AIRFLOW-1853.
https://issues.apache.org/jira/browse/AIRFLOW-1656
#3288

**Comment by jgao54** [comment]
Thanks for the fix! Simpler and cleaner.

I believe you can also remove the following two lines in `airflow/www/views.py`
```
dates = dag.date_range(base_date, num=-abs(num_runs))	
min_date = dates[0] if dates else timezone.utc_epoch()
``` 

Also please take a look at the failing unit test  `test_dag_views ` + pep8

**Comment by jgao54** [comment]
ping @djo10  :)

**Comment by Fokko** [comment]
I like the code change, it looks much cleaner.

**Comment by djo10** [comment]
@jgao54 @Fokko Sorry for delay :)

**Review by Fokko — APPROVED** [review]
Thanks @djo10 

Merging to master!

**Pull request closed without merging**
