### PR TITLE
Add deferrable mode to GCPToBigQueryOperator + tests

### PR DESCRIPTION
**Pull request by VladaZakharova**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Needs conflict resolving after string normalization in providers.

**Review by potiuk — APPROVED** [review]

**Comment by quentin-sommer** [comment]
Hi, I tracked an issue I have to this pr:

```
def _check_schema_fields(self, table_resource):
```
(https://github.com/apache/airflow/pull/27052/files#diff-875bf3d1bfbba7067dc754732c0e416b8ebe7a5b722bc9ac428b98934f04a16fR512)

is executed and try to infer a schema on my newline delimited json file. It obviously doesn't work, I end up with column names containing `{"`.

I'm trying to understand why the function is called on all the data types without checking if `source_format` is `'CSV'`. Maybe I'm just using it wrong? Hope you can help

I could provide the `schema_fields` every time to make the operator bypass the check but it was convenient to let bigquery detect the schema.

ping @VladaZakharova and @potiuk

**Comment by VladaZakharova** [comment]
@quentin-sommer 
Hi Team,
I am working on preparing a PR with a fix for this issue and will share all the updates.

**Comment by VladaZakharova** [comment]
@quentin-sommer
Hi Team :)
Please, check the PR that I have created for the fix to this issue:
https://github.com/apache/airflow/pull/28284

Thanks!

**Pull request merged**
