### PR TITLE
[AIRFLOW-2801] Skip test_mark_success_no_kill in PostgreSQL on CI

### PR DESCRIPTION
**Pull request by tedmiston**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2801
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Skips a test that frequently errors out on the CI which has lead to confusing build results.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This change is to a unit test decorator call.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Isnt it beter to fix the issue rather than skip it? Ie. Fix the test?

**Comment by tedmiston** [comment]
Yeah, fixing the test is a better longterm solution.

In the short term, the error-ing out is breaking builds (not consistently but intermittently) for unrelated changes both on master and for PRs leading to confusing results like in https://github.com/apache/incubator-airflow/pull/3641.  My thought process was that skip was a good solution to that problem.  I'm thinking of this as a temporary workaround similar to how we're currently doing the same thing for MySQL as of AIRFLOW-2267 (https://github.com/apache/incubator-airflow/pull/3197#issuecomment-403173210).

As far as I can tell this is the only error on the CI currently.

**Comment by tedmiston** [comment]
FWIW here's the traceback of the exception triggering the error ([link](https://travis-ci.org/apache/incubator-airflow/jobs/407522994#L5668-L5701)):

```
10) ERROR: test_mark_success_no_kill (tests.transplant_class.<locals>.C)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/jobs.py line 1116 in test_mark_success_no_kill
      ti.refresh_from_db()
    airflow/utils/db.py line 74 in wrapper
      return func(*args, **kwargs)
    /opt/python/3.5.5/lib/python3.5/contextlib.py line 66 in __exit__
      next(self.gen)
    airflow/utils/db.py line 45 in create_session
      session.commit()
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/orm/session.py line 927 in commit
      self.transaction.commit()
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/orm/session.py line 471 in commit
      t[1].commit()
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/base.py line 1632 in commit
      self._do_commit()
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/base.py line 1663 in _do_commit
      self.connection._commit_impl()
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/base.py line 723 in _commit_impl
      self._handle_dbapi_exception(e, None, None, None, None)
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/base.py line 1402 in _handle_dbapi_exception
      exc_info
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/util/compat.py line 203 in raise_from_cause
      reraise(type(exception), exception, tb=exc_tb, cause=cause)
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/util/compat.py line 186 in reraise
      raise value.with_traceback(tb)
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/base.py line 721 in _commit_impl
      self.engine.dialect.do_commit(self.connection)
    .tox/py35-backend_postgres/lib/python3.5/site-packages/sqlalchemy/engine/default.py line 443 in do_commit
      dbapi_connection.commit()
   OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
   	This probably means the server terminated abnormally
```

It seems to be erroring out on trying to [commit](http://initd.org/psycopg/docs/connection.html#connection.commit) the pending transaction to the database, possibly because the connection has been closed.  What's weird is that this line is already in a try-except block catching all exceptions, but I think it's somehow not entering the except clause.

https://github.com/apache/incubator-airflow/blob/f3b6b60c4809afdde916e8982a300f942f26109b/airflow/utils/db.py#L36-L50

I'm happy to work on a longer term fix for this too but would love to get this one in so we have clean build results on the CI in the meantime.

**Comment by Fokko** [comment]
Thanks for picking this up @tedmiston 

I think we should merge this now, and work on a long term solution. This is something we definitely need to fix. @tedmiston Can you make a new Jira for fixing this?

**Review by Fokko — APPROVED** [review]

**Comment by tedmiston** [comment]
@Fokko Sure thing, I've spun off an issue for it here - https://issues.apache.org/jira/browse/AIRFLOW-2806.

**Comment by Fokko** [comment]
Thanks!

**Pull request closed without merging**
