### PR TITLE
Movin trigger dag to operations folder

### PR DESCRIPTION
**Pull request by khalidmammadov**
This is to move/graduate trigger dag modue out of experimental folder to a new operations folder. 
New operations directory can host similar modules for internal implementations going forward.

This was discussed and suggested in this PR #18685

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add backward-compatibility with deprecation warning? For example, see: airflow.contrib module.

**Comment by uranusjr** [comment]
There are many more that should be moved, basically everything mentioned in `airflow.www.views` (and probably some more, I didn't check). They don't need to done in this PR, I'm just noting those as easy follow-up contributions 🙂

**Comment by kaxil** [comment]
Let's wait on merging this -- we can include it in 2.1.1

**Comment by uranusjr** [comment]
Do we want to continue this? The file has since be moved out of experimental, but not out of api. Now should be a good time to do this for 2.3, I think. We should also move mark_state together.

**Pull request closed without merging**
