### PR TITLE
 [AIRFLOW-4062] Improve docs on install extra package commands

### PR DESCRIPTION
**Pull request by zhongjiajie**
Some command for installing extra packages like
`pip install apache-airflow[devel]` cause error
in special situation/shell, We should clear them
by add quotation like
`pip install 'apache-airflow[devel]'`

Make sure you have checked _all_ steps below.

  - https://issues.apache.org/jira/browse/AIRFLOW-4062

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
From https://github.com/apache/airflow/pull/4897, sorry for break our CI test in https://github.com/apache/airflow/pull/4897

**Review by ashb — APPROVED** [review]

**Comment by zhongjiajie** [comment]
CI doc check pass, but failed in main test. https://travis-ci.org/apache/airflow/builds/510600306?utm_source=github_status&utm_medium=notification
Maybe I should force push to restart CI?

**Comment by zhongjiajie** [comment]
@ashb CI failed several times, and it's unrelated. This PR just change docs and log so I think it could be merge.

**Comment by zhongjiajie** [comment]
@ashb Thanks.

**Comment by zhongjiajie** [comment]
@ashb I found out you make jira ticket status "RESOLVED", It nessary for me to change jira ticket when PR was merge? Ask that because I found out them will change status auto when related PR be merge.

**Comment by ashb** [comment]
The commiter usually marks the Jira ticket as resolved, but we forget sometimes. If we don't,  yes you can mark your own Jira tickets as resolved. If you do please also set the Fix Version field - to 2.0.0 or 1.10.3 depending on if it's a large/backwards-incompatible change or not.

**Comment by zhongjiajie** [comment]
I got it, thanks @ashb

**Pull request merged**
