### PR TITLE
add "return" statement to "yield" within a while loop in amazon triggers

### PR DESCRIPTION
**Pull request by Lee-W**
We notice some of the amazon triggers are not explicitly exiting a while loop like https://github.com/apache/airflow/blob/952d04a3c10a7b511e4c39528d6f7aca7d729df6/airflow/triggers/external_task.py#L112-L113

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by tirkarthi** [comment]
https://github.com/apache/airflow/pull/31987 has a more general fix.

**Comment by Taragolis** [comment]
> https://github.com/apache/airflow/pull/31987 has a more general fix.

This change not conflicting with that PR. It will work only on specific Airflow, however providers usually support minor versions of Airflow 2 for at least for 1 year. Like now it supports 2.6, 2.7, 2.8.

When/if this PR merged and min supported version to provider will respect the version it might be removed from the provider codebes

**Review by Taragolis — APPROVED** [review]

**Comment by tirkarthi** [comment]
@Taragolis Understood, we have also implemented return statement after trigger event in our internal triggers. My point was more to add a context that the similar changes already present in google related providers were removed in https://github.com/apache/airflow/pull/31703 and then added back in https://github.com/apache/airflow/pull/31985 with discussion pointing out various subtle things in asyncio. It lead to the more general fix to be opened in https://github.com/apache/airflow/pull/31987.

> If your trigger is designed to emit more than one event (not currently supported), then each emitted event must contain a payload that can be used to deduplicate events if the trigger is running in multiple places. If you only fire one event and don’t need to pass information back to the operator, you can just set the payload to None.

Though currently not supported emitting multiple events is noted in this doc section.

**Comment by Taragolis** [comment]
I guess the main problem that how this implemented right now in many triggers.
Instead of
```python
while True:
    "do something"
    if foo == "bar"
        yield ...
        return
    elif spam == "egg"
        yield ...
        return
```

It might be better then it implemented as (or as a decorator/context manager)

```python
event = None
try:
    while not event:
        "do something"
except Exception:
    yield ...  # Error event
else:
   yield event  # Error event
```

But it still required to change the code and make sure that yield not happen inside of while syntax

**Comment by hussein-awala** [comment]
> #31987

We are agreed on accepting coroutines and generators to fix this issue, but we are blocked by MyPy that doesn't support this implementation.

**Review by hussein-awala — APPROVED** [review]

**Pull request merged**
