### PR TITLE
feat: add Hook Level Lineage support for GCSHook

### PR DESCRIPTION
**Pull request by kacpermuda**
Adding hook level lineage support for GCS Hook. Similar PR for S3 Hook: #40819 

Also, Google provider needed some adjustments after Dataset has been renamed to Asset so I've done that as well.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by shahar1** [comment]
Static checks and `LowestDeps` tests currently fail

**Comment by kacpermuda** [comment]
Yes, I'm working on fix and also adding tests to my changes. I'll switch to draft before i push it.

**Review by JDarDagran — APPROVED** [review]

**Review by shahar1 — COMMENTED** [review]
Please ensure that your PR complies with the adjustments that were introduced in #41348

**Comment by kacpermuda** [comment]
@shahar1 It should work well now, adjusted the GCSHook and the whole provider to work with Asset naming instead of Dataset.

**Review by shahar1 — APPROVED** [review]
Looks great! Thank you :)

**Pull request merged**
