### PR TITLE
Fix repair function call

### PR DESCRIPTION
**Pull request by gaurav7261**
Fix repair function calling, only repair_dict need to get passed

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Why? Can you explain? What is source documentation?

Can you please add a unit test to cover this change?

**Comment by gaurav7261** [comment]
Hi @potiuk , it seems like typo in my repair run PR, I have tested on our dev, for deferrable, it is working as expected, but in normal, it is failing, you can find error in screenshot below, thanks 
Screenshot 2024-10-14 at 12 40 25 PM

**Comment by potiuk** [comment]
> Hi @potiuk , it seems like typo in my repair run PR, I have tested on our dev, for deferrable, it is working as expected, but in normal, it is failing, you can find error in screenshot below, thanks

Which PR? 

And I think in either case - if this is "correct fix" - generally speaking we do not accept PRs like that which have no unit test changes - because it means that the "bad" functionality did not have a good unit test. If it did, the test would fail after your change and you would have to correct the test as well) - so adding a unit test here is pretty much mandatory.

**Comment by gaurav7261** [comment]
Hi @potiuk , sure will add a unit test case for the same, in earlier PR, a unit test case was there, but that covered only the deferrable one, as a functionality point  of view, it is same, no worries, I will add a test case for this as well

**Pull request closed without merging**
