### PR TITLE
[AIRFLOW-207] Improve JIRA auth workflow

### PR DESCRIPTION
**Pull request by jlowin**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-207

Improve Jira auth workflow by prompting for username/password instead of crashing if the env var isn't set.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Like!

**Comment by criccomini** [comment]
LGTM

**Comment by jlowin** [comment]
@bolkedebruin @criccomini thanks for the +1's -- I added a commit with a few minor styling/UX updates under AIRFLOW-187. Do you mind taking a quick look at those when you have a moment? Once done I'll merge.

**Comment by criccomini** [comment]
LGTM (again :))

**Comment by jlowin** [comment]
Thanks!

**Pull request merged**
