### PR TITLE
[AIRFLOW-3088] Include slack-compatible emoji image.

### PR DESCRIPTION
**Pull request by sethwoodworth**
Emoji preview:
airflow_64x64_emoji

----
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. 
  - https://issues.apache.org/jira/browse/AIRFLOW-3088

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This adds a 64px by 64px version of your logo, suitable for adding to slack as a custom emoji.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This is a static PNG image and does not require tests.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

I did not document the inclusion of the image.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by r39132 — CHANGES_REQUESTED** [review]
1. Please move the image to docs/img/logos/
2. Can you add a link to the image in the "conversation" so we can view it?

**Comment by r39132** [comment]
@sethwoodworth ^

**Comment by r39132** [comment]
@sethwoodworth ping!

**Comment by sethwoodworth** [comment]
@r39132 Sorry for the delay, I wasn't getting notifications for a little while there.

+ Image moved to /docs/images/logo subfolder
+ Preview image added to PR description
+ Rebased, squashed, & pushed

**Comment by r39132** [comment]
Cool! @sethwoodworth 

 Can you add `transparent` in the image name just to make it more obvious `airflow_64x64_emoji_transparent.png`? We currently have some png that do not have a transparent background.

**Comment by r39132** [comment]
@sethwoodworth any updates?

**Comment by sethwoodworth** [comment]
@r39132 Renamed and rebased

**Pull request merged**
