### PR TITLE
[AIRFLOW-1182] & [AIRFLOW-1184]: Contrib Spark Submit operator should template fields & Contrib Spark Submit Hook does not split argument and argument value

### PR DESCRIPTION
**Pull request by vfoucault**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following
  - [Airflow-1182](https://issues.apache.org/jira/browse/AIRFLOW-1182) Contrib Spark Submit operator should template fields
  - [Airflow-1184](https://issues.apache.org/jira/browse/AIRFLOW-1184) Contrib Spark Submit Hook does not split argument and argument value
### Description
- [ ] Here are some details about my PR, : 
  - added template fields to the SparkSubmitOperator : ```_application_args``` & ```_name``` making them usable with macro. This enable to pass params based on dag execution to the Spark application
  - split spark application options as they should be for Popen in spark_submit_hook. Without, the spark application is complaining about missing & malformed option. See jira issu 1184

### Tests
- [ ] My PR adds the following unit tests :
  - refactored tests for spark_submit_operator & spark_submit_hook.

### CODE REVIEW

**Comment by vfoucault** [comment]
This PR contains #2282 plus additional Jira  1184

**Comment by bolkedebruin** [comment]
Can you please cleanup your commit message (see guidelines) and see if you need to split the patch across two commits that address the jira's separately?

**Comment by vfoucault** [comment]
Is there any way to re trigger the travis build without a new push ?
the error is 
```log
11) FAIL: test_scheduler_run_duration (tests.SchedulerJobTest) (11s vs 5s)
```
and build is ok on my branch : 
https://travis-ci.org/vfoucault/incubator-airflow ->bid 8 for same commit number (e60aab8)

thx.

**Comment by Fokko** [comment]
You could try to do a force push of the same commit, this might trigger a new build.

**Comment by vfoucault** [comment]
No effect.  I'll go with a empty commit then

**Comment by Fokko** [comment]
I think it is not a problem, the committers are aware of the fact that the tests are sometimes a bit flakey.

**Comment by vfoucault** [comment]
I think we're good now, let me know.

kr.

**Comment by bolkedebruin** [comment]
@Fokko tests are not flaky any more. So no we don't accept non passing tests anymore. Exception could be due to changes to underlying dependencies (i.e. a version has changed).

LGTM

**Comment by ashb** [comment]
I think this needs reverting as it _impossible_ to include an argument with an embedded space!

I don't think this is needed:

```
application="com.example.MyClass"
args=[
  "--foo=bar",
 "--qux=foo bar",
]
task = SparkSubmitOperator(
    task_id="spark_csv_parser",
    dag=dag,
    application="com-example-spark.jar",
    application_args=args,
    java_class="com.example.MyClass",
)
```

Previously to this PR this would do the equivalent of:

```py
popen([
  "spark-submit",
  ...,
  "com-example-spark.jar",
  "com.example.MyClass",
  "--foo=bar",
  "--qux=foo bar"
])
```

But after this commit it drastically changes the last argument:

```py
popen([
  "spark-submit",
  ...,
  "com-example-spark.jar",
  "com.example.MyClass",
  "--foo=bar",
  "--qux=foo",
  "bar"
])
```

**Pull request merged**
