### PR TITLE
Revert to isort version 5.11.2 in pre-commit

### PR DESCRIPTION
**Pull request by dstandish**
Hopefully fix broken main

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
🤞

**Comment by dstandish** [comment]
i'm still working on it. 🤞 indeed

**Comment by dstandish** [comment]
when i reference pyproject toml, it doesn't seem to respect `skip` and modifies tests/decorators/test_python.py

**Comment by dstandish** [comment]
same with skip_glob

**Comment by dstandish** [comment]
ok... new tactic... back to 5.11.2

**Pull request merged**
