### PR TITLE
Add Secrets backend for Microsoft Azure Key Vault

### LINKED ISSUE #8258: Implement Azure key vault secrets backend
**Description**

A secrets backend for Azure Key Vault

**Use case / motivation**

In addition to AWS Secrets Manager & SSM, HashiCorp Vault, and GCP Secrets Manager, we could implement a secrets backend for Azure Key Vault.

**Related Issues**

No

### PR DESCRIPTION
**Pull request by kaxil**
Co-authored-by: Elwin Arens <elwinjoeriarens@gmail.com>

closes: #8258

This PR adds secrets backend for Microsoft azure key vault

This work was started at https://github.com/apache/airflow/pull/9639

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
k8s failures are unrelated

**Comment by potiuk** [comment]
> k8s failures are unrelated

Need rebase - that was one of the previous master merges (fixed afterwards) I had the same problem with two other prs and it was fixed after rebase

**Comment by kaxil** [comment]
> > k8s failures are unrelated
> 
> Need rebase - that was one of the previous master merges (fixed afterwards) I had the same problem with two other prs and it was fixed after rebase

rebased

**Review by potiuk — APPROVED** [review]
Nice! one more secret backend!

**Comment by potiuk** [comment]
I think we have a failing pylint in master now because of this one :(

**Comment by potiuk** [comment]
@kaxil ^^

**Comment by kaxil** [comment]
Checking

**Comment by kaxil** [comment]
No, I think the test was cancelled because another PR was merged, I can't see any error

**Comment by potiuk** [comment]
https://github.com/apache/airflow/runs/1108600218?check_suite_focus=true

**Comment by potiuk** [comment]
In another PR

**Comment by potiuk** [comment]
I am running my PR rebased on master now https://github.com/apache/airflow/pull/10912/checks?check_run_id=1108699419

**Comment by potiuk** [comment]
Hmm. It works. It was an interesting race condition that I must have to take a closer look at :)

**Comment by potiuk** [comment]
Allright I know @kaxil . It was manifestation of the #10471 

Currenlty the image is built using the original commit, but the build itself is run using sources after the PR is automatically merged with master. So in the image there was no "azure-identity" and the other package added, but the sources used for pylint check already contained it (because we run static checks using the local sources). 

That makes me think that I might want to try to solve it eventually.

**Comment by elwinarens** [comment]
Thanks for the effort of picking up where i left, everyone!

**Pull request merged**
