### PR TITLE
[AIRFLOW-2042] Fix browser menu appearing over the autocomplete menu

### PR DESCRIPTION
**Pull request by fox**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2042

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Fixes a small but annoying issue in Safari, in which typing in search bar makes both the browser default and bootstrap typeahead menus to appear. To prevent it, we set autocomplete to "off" on input elements.

##### Before:

issue

##### After:

after

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This is a tiny UI change.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
@fox What version of Safari do you see this in? I cannot reproduce the problem on Safari Version 11.1 (13605.1.33.1.2)

**Comment by r39132** [comment]
@fox I tried testing this PR out.. but I still see the problem .. I'm on Safari `Version 11.1 (13605.1.33.1.2)` Can you confirm your fix works for this version of Safari?

**Comment by fox** [comment]
@r39132 I can confirm this works on the same Safari version. You probably need to clear your browser cache first (Develop → Empty Caches). I've tested it again, it's essentially a one-liner change so .. without the change: 

before

With the change:

after  

I would argue this is an issue with Typeahead library, although the latest version (4.0.2) is the one Airflow uses. It's really a small annoyance, affecting only Safari and the workaround here seems to help.

**Comment by r39132** [comment]
Thx +1

**Pull request closed without merging**
