### PR TITLE
Further increase startup time for mssql

### PR DESCRIPTION
**Pull request by potiuk**
Some of the integration tests seem to succeed after ~18s after creating the containers. We have startup period = 20s so increasing it might increase the chance of succeeding.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
@shahar1 -> another attempt

**Review by vincbeck — APPROVED** [review]

**Comment by potiuk** [comment]
looks better THIS TIME

**Comment by potiuk** [comment]
Nope - no dice - seems that the health check for mssql has some persistent issue - regardless of timeout @shahar1

**Comment by potiuk** [comment]
Proposed to disable the docker-compose health check here https://github.com/apache/airflow/pull/39885

**Pull request merged**
