### PR TITLE
Revert "Decouple production executor warning in dags UI (#29609)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 88ed20a813393e642de00ec920593bda7b5471cf.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Not sure why, but I think #https://github.com/apache/airflow/pull/29609 broken pytest collection in main (looks like a circular import). For some reason it did not happen in the original PR.

We should merge it (and find the cause) as both PRs started to fail with:

```
    from airflow.executors import celery_executor, celery_kubernetes_executor
airflow/executors/celery_executor.py:40: in <module>
    from celery import Celery, Task, states as celery_states
E   ImportError: cannot import name 'Celery' from 'celery' (/usr/local/lib/python3.7/site-packages/celery/__init__.py)
```

For example here: https://github.com/apache/airflow/actions/runs/4333507290/jobs/7566768495

**Comment by potiuk** [comment]
@o-nikolas - you will have to redo that one again and we need to carefully look at what was going on with the import.

**Comment by o-nikolas** [comment]
> @o-nikolas - you will have to redo that one again and we need to carefully look at what was going on with the import.

Interesting, I'll have to find the way to replicate the error on my end. Both my local testing and the PR didn't show the issue. I'll look on Monday. And thanks for the revert 👍

**Comment by potiuk** [comment]
Yep. Strange. I need approval to merge it though :)

**Comment by potiuk** [comment]
I also added this one https://github.com/apache/airflow/pull/29923 to clearer show  when things like that happen (there will be separate job doing the test collection) and also allowing the other jobs in CI to continue even if collection fail.

**Comment by potiuk** [comment]
🙏 :) @o-nikolas

**Comment by potiuk** [comment]
I think it is a different thing - side-effect of argcomplete released few moments ago (which drags importlb upgrade with it).

**Comment by potiuk** [comment]
Confirmed. This is a regrression in importlib_metadata that will be fixed in upcoming celerly 5.3. Workaround is coming.

**Comment by potiuk** [comment]
(so no need to take a look @o-nikolas )

**Comment by potiuk** [comment]
the right fix is here https://github.com/apache/airflow/pull/29924

**Comment by o-nikolas** [comment]
Nice, glad this worked out :smiley:  I was unavailable this weekend and only had a few mins to check this PR on my phone!

**Pull request closed without merging**
