### PR TITLE
SFTP file transfer

### PR DESCRIPTION
**Pull request by genomics-geek**
Added SftpHook and SftpOperator which allows put/get methods on a remote server

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Nice! Please create a Jira for this and make sure you describe and squash your commits per guidelines.

**Comment by genomics-geek** [comment]
Sorry about that @bolkedebruin. Should I close this pull request and submit a new one?

**Comment by jhsenjaliya** [comment]
@genomics-geek , I am rebuilding SSH_operator along with ssh_hook using paramiko since i find current one using subprocess is with limited options , do you think we should combine ssh_operator with sftp_operator ?  just a thought.
pls let me know your thought and whether we can collaborate on this.  Thanks

**Comment by genomics-geek** [comment]
@jhsenjaliya Absolutely! I actually thought the same thing.  Please use [this pull request](https://github.com/apache/incubator-airflow/pull/1992) instead.

**Pull request closed without merging**
