### PR TITLE
Impala hook implention

### PR DESCRIPTION
**Pull request by blcksrx**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists  #8916
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Hello @blcksrx -> i will happily review it but I think you need to rebase and fix some of the static checks

**Comment by blcksrx** [comment]
Sure! I will do it

**Comment by blcksrx** [comment]
@potiuk I fixed the static checks! but currently, there are issues related to `pyhive`:
```
      AttributeError: module 'pyhive' has no attribute 'hive'
```

**Comment by potiuk** [comment]
That's an interesting one.

It looks like there is a conflict of dependencies between Impala and Hive (because of incompatible versions of thrift used - the root cause is org.apache.hive.service.rpc.thrift.TCLIService ). Impyla dynamically replaces  TCLIService with an incompatible version.

The issue is described here: https://github.com/cloudera/impyla/issues/277

And there is a fix in impyla for that: https://github.com/cloudera/impyla/commit/0284cc0850a1acf53507ba1366022fc36e6df517

It was merged 12th of June, but the latest release of Impyla was done 2nd May. I've asked what are the plans for Impyla to release a new version.

**Comment by potiuk** [comment]
I guess we will have to wait with the merge unti impyla releases next version I am afraid.

**Comment by potiuk** [comment]
Sorry for that :(

**Comment by blcksrx** [comment]
No Problem. Thanks

**Comment by RosterIn** [comment]
@blcksrx impyla v0.16.3 was released 10 days ago and it includes the commit @potiuk was referring to.
Can this PR revisited due to the new version release?

**Comment by blcksrx** [comment]
> @blcksrx impyla v0.16.3 was released 10 days ago and it includes the commit @potiuk was referring to.
> Can this PR revisited due to the new version release?
Yes of course. Thanks

**Pull request closed without merging**
