### PR TITLE
Remove unused pageSize method.

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Or should we remove the whole function ? @bbovenzi @pierrejeambrun -  from what I see, the whole `page_size` thing is not used any more?

**Review by dirrao — APPROVED** [review]

**Comment by bbovenzi** [comment]
> Or should we remove the whole function ? @bbovenzi @pierrejeambrun - from what I see, the whole `page_size` thing is not used any more?

Yeah, I don't see where we define anything with `#page-size`. Let's try removing it.

**Comment by potiuk** [comment]
> Yeah, I don't see where we define anything with `#page-size`. Let's try removing it.

Removed.

**Comment by potiuk** [comment]
cc: @bbovenzi

**Review by hussein-awala — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by bbovenzi — APPROVED** [review]

**Pull request merged**
