### PR TITLE
Change import so hive_metastore is not a required module for operator tests

### PR DESCRIPTION
**Pull request by krishnabhupatiraju**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-873

Testing Done:
- Ran existing tests in tests/operators/. They were successful

### CODE REVIEW

**Comment by krishnabhupatiraju** [comment]
@jlowin @artwr Could you take a look.

**Comment by jlowin** [comment]
Thanks @krishnabhupatiraju -- I think that while your change will in fact prevent the file from being imported, it will also prevent it from being included in any unit tests. Let's see if Travis picks it up.

**Comment by jlowin** [comment]
Also, I'm in love with this bot. @bolkedebruin is this your doing?

**Comment by gsakkis** [comment]
> I think that while your change will in fact prevent the file from being imported, it will also prevent it from being included in any unit tests. 

@jlowin please see #2078 that addressed this issue for many more dormant tests.

**Comment by krishnabhupatiraju** [comment]
@jlowin #[2078](https://github.com/apache/incubator-airflow/pull/2078) does make the same change as this one. So closing this PR Off.

**Pull request closed without merging**
