### PR TITLE
[WIP][AIRFLOW-2806] test_mark_success_no_kill test breaks intermittently on CI

### PR DESCRIPTION
**Pull request by tedmiston**
https://issues.apache.org/jira/browse/AIRFLOW-2806

Note: Please ignore this PR right now — I'm just trying to reproduce the error.

### CODE REVIEW

**Comment by tedmiston** [comment]
Here's a WIP start to the follow up discussion from https://github.com/apache/incubator-airflow/pull/3642.  I'm starting the longer term solution by seeing if upgrading the relevant dependencies makes a difference.

@Fokko Do you have any advice around how to test this intermittent error on CI?  Basically I'd like to trigger the build ~5–10x times in a row on some combinations of [MySQL, PostgreSQL] x [Python subversions] and see how many (if any) succeed vs error out.

Note: I have an open task to get Travis CI setup on my GitHub account.  I understand Airflow is using significant resources for Apache on Travis, so getting that setup is a priority.

**Comment by ashb** [comment]
It's relatively easy to set up Travis on your personal fork of Airflow - IIRC it's as simple as going to https://travis-ci.org/tedmiston/incubator-airflow and clicking a big button (possibly after signing in via github).

**Comment by tedmiston** [comment]
Thanks @ashb!  Looks like you're right.  On my personal account it "just worked" after I updated my fork and pushed a branch.

On my GitHub org account, it worked after adding our org to Travis CI then specifically granting access to the incubator-airflow repo (even though it's public).  I don't think I ever did that on my personal but I could have forgotten.  In any case, it's working great.

_Note: I had to change .org to .com in the URL to see my builds.  Not sure if this is unique to me or the same for everyone as I setup my personal account on the .com site a few months ago._

**Comment by tedmiston** [comment]
Closing this PR for now as I have more work to do here before it can be merged.

**Pull request closed without merging**
