### PR TITLE
Allow custom Docker production image to be verified by bash script

### PR DESCRIPTION
**Pull request by mik-laj**
I wanted to verify my own image with this script, but I got lost about how to configure the environment variables. For this reason, I would like to split this script into two scripts: one script that is well integrated with our CI environment, and the other that allows us to define our own image and is therefore more user-friendly.

Additionally, I made some other minor changes:
- All tests are always run, but if one check fails, the script fails.
- Rename some functions: check_feature -> check_command, verify_production_image_features -> verify_production_image_python_modules

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
That's useful but it is not good  when CI script calls another non-CI script to do the stuff. This should be done by common functons.

The current convention is that all "common" parts are in libraries. Foilowing this convention - please move the function to a new _veriy_images.sh module in "libraries" folder, the functions should be prefixed with verify_images:: and both scripts should simply call those functions.

**Comment by potiuk** [comment]
Also (at least for now), breeze is the entrypoint for all useful user commands (it is better for discovery rather than having separate scripts), so it would be good to run it as command in breeze. This is not needed in this PR though but I can add it once we have the  shared libraries.

**Comment by mik-laj** [comment]
> Also (at least for now), breeze is the entrypoint for all useful user commands (it is better for discovery rather than having separate scripts), so it would be good to run it as command in breeze. This is not needed in this PR though but I can add it once we have the shared libraries.

Unfortunately, my skills do not allow for contributions to the ./breeze script. Unfortunately, there are too many Bash and too many global variables out there to be comfortable for me. I created a new script `/scripts/ci/tools/verify_docker_image.sh` and I hope it will be a good enough solution for now.

**Comment by potiuk** [comment]
> Unfortunately, my skills do not allow for contributions to the ./breeze script. Unfortunately, there are too many Bash and too many global variables out there to be comfortable for me. I created a new script `/scripts/ci/tools/verify_docker_image.sh` and I hope it will be a good enough solution for now.

It's rather easy following other commands, but this is no problem. I can add it once this one is merged.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Static checks failing

**Pull request merged**
