### PR TITLE
Extend HTTP extra_options to LivyHook and operator

### PR DESCRIPTION
**Pull request by dsynkov**
PR in relation to discussion I initially started here https://github.com/apache/airflow/discussions/12622. In short, the `LivyHook` used by the `LivyOperator` has `extra_options` in its main `run_method` but there's no way to use them from the actual operator itself. 

https://github.com/apache/airflow/blob/956a2053b51d690038f5db6a61ed14f381540240/airflow/providers/apache/livy/hooks/livy.py#L89-L95

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by dsynkov** [comment]
While I was testing this I got the below error:
```
[2021-03-16 01:05:07,136] {logging_mixin.py:104} INFO - Running <TaskInstance: example_livy_operator.pi_java_sensor 2021-03-16T01:05:06.055205+00:00 [running]> on host 0ec62ec2ae59
[2021-03-16 01:05:07,169] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1274, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/opt/airflow/airflow/models/taskinstance.py", line 1776, in render_templates
    self.task.render_template_fields(context)
  File "/opt/airflow/airflow/models/baseoperator.py", line 870, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/opt/airflow/airflow/models/baseoperator.py", line 881, in _do_render_template_fields
    content = getattr(parent, attr_name)
AttributeError: 'LivySensor' object has no attribute 'batch_id'
```
Which looks to be due to `batch_id` in `template_fields` not matching how it's stored in the constructor `self._batch_id` so I fixed this as well.

https://github.com/apache/airflow/blob/956a2053b51d690038f5db6a61ed14f381540240/airflow/providers/apache/livy/sensors/livy.py#L36

https://github.com/apache/airflow/blob/956a2053b51d690038f5db6a61ed14f381540240/airflow/providers/apache/livy/sensors/livy.py#L44

**Comment by marcosmarxm** [comment]
@dsynkov maybe add a new Operator test using the extra_options to guarantee the change?

**Review by kaxil — APPROVED** [review]

**Review by kaxil — COMMENTED** [review]
LGTM. Can you please add a test case for it in https://github.com/apache/airflow/blob/master/tests/providers/apache/livy/operators/test_livy.py

**Comment by dsynkov** [comment]
@marcosmarxm @kaxil Thank you for reviewing. I added a test to run the `post_batch` flow with `extra_options` set.

**Comment by kaxil** [comment]
Thanks @dsynkov 🎉

**Pull request merged**
