### PR TITLE
Support k8s auth method in vault secrets provider

### PR DESCRIPTION
**Pull request by reltuk**
---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by reltuk** [comment]
Not sure about the most recent lint failure...I moved pylint directive comment to the line above the class.

**Comment by potiuk** [comment]
> Not sure about the most recent lint failure...I moved pylint directive comment to the line above the class.

You can see it in the output:

airflow/providers/hashicorp/secrets/vault.py:32:54: E261 at least two spaces before inline comment

**Comment by reltuk** [comment]
But in the most recent code there is no inline comment at `airflow/providers/hashicorp/secrets/vault.py:32`. The comment has been moved to `airflow/providers/hashicorp/secrets/vault.py:31` instead, because of the previous pylint failure...

**Comment by reltuk** [comment]
Pushed an empty commit to try again. Thanks for feedback :).

**Review by kaxil — COMMENTED** [review]
Have you tested this ?

**Comment by reltuk** [comment]
Yes, for the most part. See this gist for an example of an adhoc end-to-end test that works:

https://gist.github.com/reltuk/4ff3ee7edca0848d081a945abb5ad01b

**Comment by reltuk** [comment]
Small white lie from the above testing: in order to make it work, I had to have the following patch applied. Not sure what's going on there...maybe my pip install is wrong or `vault.py` is out of date or something.

```patch
diff --git a/airflow/providers/hashicorp/secrets/vault.py b/airflow/providers/hashicorp/secrets/vault.py
index c0fd23581..27058e9c4 100644
--- a/airflow/providers/hashicorp/secrets/vault.py
+++ b/airflow/providers/hashicorp/secrets/vault.py
@@ -24,7 +24,7 @@ import hvac
 from cached_property import cached_property
 from hvac.exceptions import InvalidPath, VaultError
 
-from airflow import AirflowException
+from airflow.exceptions import AirflowException
 from airflow.secrets import BaseSecretsBackend
 from airflow.utils.log.logging_mixin import LoggingMixin
 
```

Seems unrelated to the k8s support though.

**Comment by kaxil** [comment]
> Small white lie from the above testing: in order to make it work, I had to have the following patch applied. Not sure what's going on there...maybe my pip install is wrong or `vault.py` is out of date or something.
> 
> ```diff
> diff --git a/airflow/providers/hashicorp/secrets/vault.py b/airflow/providers/hashicorp/secrets/vault.py
> index c0fd23581..27058e9c4 100644
> --- a/airflow/providers/hashicorp/secrets/vault.py
> +++ b/airflow/providers/hashicorp/secrets/vault.py
> @@ -24,7 +24,7 @@ import hvac
>  from cached_property import cached_property
>  from hvac.exceptions import InvalidPath, VaultError
>  
> -from airflow import AirflowException
> +from airflow.exceptions import AirflowException
>  from airflow.secrets import BaseSecretsBackend
>  from airflow.utils.log.logging_mixin import LoggingMixin
>  
> ```
> 
> Seems unrelated to the k8s support though.

Happy for you to make that change too. It will avoid cycles.

**Comment by reltuk** [comment]
Ok, added a commit to fix the AirflowException import in `vault.py`.

Also added a commit to make `airflow variables get VAR_NAME` print the value of the retrieved variable. Previously I had to use `airflow variables get hello -d test`, because the variable value was only printed if a default was also provided on the command line.

**Review by kaxil — APPROVED** [review]

**Pull request merged**
