### PR TITLE
Revert "Add Python 3.12 support (#36755)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 76dee0b5867580480d802765bad2dd61e3156bff.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
More than that actually - some stranflge timeouts on databricks and python venv

**Comment by Taragolis** [comment]
AS we discuss in the other PR, this test might have some strange side effect to the other test, maybe we could try to move entire [`tests/core/test_impersonation_tests.py`](https://github.com/Taragolis/airflow/blob/main/tests/core/test_impersonation_tests.py) into the Quarantine and that might "magically" fix other tests

**Comment by Taragolis** [comment]
Yeah, maybe other things. But for that one I think it is worthwhile to move it in quarantined

**Comment by potiuk** [comment]
Running tests in https://github.com/apache/airflow/pull/38025 with new feature added - only running tests for latest versions to limit resources (and with some fixes - let's see).

**Pull request merged**
