### PR TITLE
[providers-fab/v1-5] Invalidate user session on password reset (#45139)

### PR DESCRIPTION
**Pull request by potiuk**
* session expire on pass change

* fix statis checks

* add tests (cherry picked from commit cf401c48bb6d06f1b30fef59d2a07afab22118bc)

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @shubhamraj-git

**Review by shubhamraj-git — APPROVED** [review]
+1 Clean cherry-pick, Looks good!

**Comment by potiuk** [comment]
Re-opened to trigger (hopefully) the build.

**Comment by potiuk** [comment]
Hmmmmmm

**Comment by potiuk** [comment]
Hmm. I think I need to close that PR and open a new one.

**Pull request closed without merging**
