### PR TITLE
Make node color more visible in UI and increase font size

### LINKED ISSUE #34420: Respect node color in the new UI graph
### Body

In Airflow 2.7.0 we removed the old graph and replaced it by the new graph view. However, this new graph doesn't change the node color to the color provided in the operator, it only use this color as a shadow for the task name:
image

It would be better if we change the node color as we had before with the old graph

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by shohamy7**
---

closes: #34420
I added some padding and increased the font size as suggested by @bbovenzi.
The new graph will look like that:
dummy_dag_with_color

### CODE REVIEW

**Comment by bbovenzi** [comment]
Could you a screenshot of how this looks with a dag run selected with task states?

**Comment by shohamy7** [comment]
Hi @bbovenzi
Thanks for your response!
It looks like the padding is getting out from the graph's nodes. I will try to find how to resolve this issue, thanks for noticing :)
Currently it looks like this:
selected_dag_run_color

If you have more use cases you want me to check, please tell me

**Comment by bbovenzi** [comment]
Well, previously it was the background color. Do you want to test that? but maybe we need to fade the color a bit.

**Comment by shohamy7** [comment]
So upon select the background color will be the operator color?
I did try to use "fit-margin" in the height field of the node element by I saw that it look bad when using task groups.
I can try resolve that, or maybe just go with what you suggested - what do you think?

**Comment by bbovenzi** [comment]
Try out your idea and send a screenshot. We're balancing a few things so its going to be trial and error.

**Comment by shohamy7** [comment]
It's fine by me :)
I'll work on both your and my solutions and will send a screenshot of each one

**Pull request closed without merging**
