### PR TITLE
Improve provider verification pre-commit

### PR DESCRIPTION
**Pull request by potiuk**
There were a numer of problems with the provider verification pre-commit scripts:

* It missed verification of "notifications"
* It did not check if the classes or modules specified in provider yaml raised deprecation warnings
* The messages produced by the script when some discrepancies were found were pretty cryptic and it was difficult to guess what kind of action should be taken to fix the problem

This PR fixes all those problems:

* verification of notification is performed
* when importing all the classes and modules, check for the AirflowProviderDeprecationWarnings is done and treated as error
* The messages produced provide clear actionable instructions on what to do and explain what are the discrepancies of expected vs. current list in a clear way

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Note! This PR will fail and it will nicely show all the kinds of problems detected by the script now - I am submitting separate PRs to fix problems found here and when we merge them, this one should become green.

**Comment by potiuk** [comment]
This one will succeed once we merge:
* https://github.com/apache/airflow/pull/33641
* https://github.com/apache/airflow/pull/33642
* https://github.com/apache/airflow/pull/33643

**Comment by potiuk** [comment]
Those are example errors printed now when the script fails:

Screenshot 2023-08-23 at 10 19 27

**Review by eladkal — APPROVED** [review]
Very nice!
Added it as solving an item from https://github.com/apache/airflow/issues/31443

**Comment by potiuk** [comment]
I decided to give up on "undeprecating DataProcLink" for now (too risky) - just added a feature of "Known deprecated classes" instead.

**Comment by potiuk** [comment]
Google team will take care about the DataprocLink some time soon-ish cc: @VladaZakharova :)

**Comment by potiuk** [comment]
flaky test only, Merging.

**Pull request merged**
