### PR TITLE
[AIRFLOW-2585] Fix bugs in CassandraHook and CassandraToGCSOperator

### PR DESCRIPTION
**Pull request by jgao54**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2585

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR fixes:
 (1) issue with UUID type conversion: currently UUID is converted to hex string, but should be converted to base64-encoded as that is the required format in BigQuery for uploading.
 (2) Issue with configuring load balancing policy in CassandraHook: currently the hook only successfully instantiate with the default LB policy, but throw an exception if attempts to pass in a custom LB policy in the extra field.
(3) Issue with connections not closed properly after use: should always shut down the cluster in the operator to close all sessions/connections associated with the cluster instance.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
unit tests added/fixed:
  - tests.contrib.hooks.test_cassandra_hook
  - tests.contrib.operators.test_cassandra_to_gcs_operator

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
Can you please fix the flake8 errors? :

```
Running flake8 on the diff in the range ab81767d..a1182cc2 (1 commit(s)):
--------------------------------------------------------------------------------
airflow/contrib/hooks/cassandra_hook.py:146:91: E501 line too long (98 > 90 characters)
            child_policy_name = policy_args.get('child_load_balancing_policy', 'RoundRobinPolicy')
                                                                                          ^
tests/contrib/hooks/test_cassandra_hook.py:28:5: E128 continuation line under-indented for visual indent
    DCAwareRoundRobinPolicy, WhiteListRoundRobinPolicy)
    ^
tests/contrib/hooks/test_cassandra_hook.py:69:25: E225 missing whitespace around operator
        fake_addr_info =[['family', 'sockettype', 'proto', 'canonname',
                        ^
tests/contrib/hooks/test_cassandra_hook.py:70:25: E128 continuation line under-indented for visual indent
                        ('2606:2800:220:1:248:1893:25c8:1946', 80, 0, 0)]]
                        ^
tests/contrib/hooks/test_cassandra_hook.py:82:91: E501 line too long (92 > 90 characters)
                                       expected_child_policy_type=WhiteListRoundRobinPolicy)
                                                                                          ^
tests/contrib/hooks/test_cassandra_hook.py:101:91: E501 line too long (96 > 90 characters)
                                   {'child_load_balancing_policy': 'WhiteListRoundRobinPolicy'},
                                                                                          ^
tests/contrib/hooks/test_cassandra_hook.py:116:9: E722 do not use bare except'
        except:
        ^
```

**Comment by jgao54** [comment]
CI didn't get triggered, will close/reopen this PR.

**Comment by jgao54** [comment]
New unit test failures seemed to be unrelated

**Comment by kaxil** [comment]
Can you please rebase against the master? The CI should now be fixed.

**Comment by jgao54** [comment]
Ah, thanks for pointing it out @kaxil

**Comment by gerardo** [comment]
@kaxil master still seems to be broken

**Comment by kaxil** [comment]
@gerardo Aah, yes it is annoying. The CI had passed for that PR which was merged. Another PR that basically reverts the original change has been merged to master. The CI should pass this time.

**Comment by Fokko** [comment]
Could be that the PR was on an old master, therefore the rebasing is so important

**Pull request closed without merging**
