### PR TITLE
[FEATURE] KPO add optional K8S hook

### PR DESCRIPTION
**Pull request by raphaelauv**
Add the availability to use the KPO with an airflow kubernetes connection

Screenshot from 2022-03-08 13-42-44

https://github.com/apache/airflow/issues/15219

### CODE REVIEW

**Comment by jedcunningham** [comment]
Hey @raphaelauv, thanks for opening this. We actually have a couples PRs working on getting KPO to use the hook. Once we dug in a bit, we found some interesting edge cases to consider. We are currently looking at getting the changes in for 2.3.0. Could you take a look at them? Thanks!

https://github.com/apache/airflow/pull/20578
(and related) https://github.com/apache/airflow/pull/20759#issuecomment-1030330624

**Comment by raphaelauv** [comment]
@jedcunningham there is no activity on https://github.com/apache/airflow/pull/20578

why not merge this one, it would unlock the usage of the conn_id in the KPO for the users

and in the future ( in another PR ) we could change the default of KPO and add a deprecation

**Comment by dstandish** [comment]
I am currently in progress on it @raphaelauv and raised discussion on dev list about the approach with respect to deprecations.

**Comment by dstandish** [comment]
@potiuk, ideally I'd _like_ to merge this one first, just since @raphaelauv went through the trouble of making it.  The thing that gives me hesitation is backcompat.  If we  release this before https://github.com/apache/airflow/pull/20578, then there when https://github.com/apache/airflow/pull/20578 is released there will be some behavior changes that users would experience.

For one, with this PR, using K8s hook would mean that core k8s settings would not be considered (in https://github.com/apache/airflow/pull/20578 they _are_ in order to make a smooth transition).  And the other is that in this one, TCP keepalive logic is not there, but in https://github.com/apache/airflow/pull/20578 it will be.

If these two PRs would go out in the same release, then that's fine because there's no backcompat concern.  If they won't then probably it's not a good idea.  FWIW I think https://github.com/apache/airflow/pull/20578 is just about ready.  I _just_ got all tests passing.

**Review by potiuk — APPROVED** [review]

**Comment by dstandish** [comment]
> I am fine with merging both together :) Both are approved now.

ok so should we.... let er rip?

**Review by dstandish — APPROVED** [review]

**Pull request merged**
