### PR TITLE
Support list/add connections in the CLI

### PR DESCRIPTION
**Pull request by jgao54**
Dear Airflow Maintainers,

Please accept the following PR that
- Add CLI support for listing/adding connections (I left out deleting/editing connections to keep it simple, but could be added in the future if there's a need for that).

Reminder to contributors:
- You must add an Apache License header to all new files
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please have a look at #1391 I'm not too happy with this kind of functionality directly inside the cli. Yes, this deviates from earlier, but the cli is getting hard to maintain and replicates functionality.

**Comment by jgao54** [comment]
@bolkedebruin cool, all good points and glad to see the API support!  I'll make changes accordingly once #1391 is merged.

**Comment by jgao54** [comment]
Closing for now.

**Comment by r39132** [comment]
@jgao54 @bolkedebruin No need to close this PR. We can always port it to the API model after the fact.

**Comment by bolkedebruin** [comment]
@jgao54 @r39132 I'm not particularly against merging it now, just hoping that @jgao54 indeed ports the functionality to the API once it stabilizes a bit more ;-).

**Comment by jgao54** [comment]
@bolkedebruin most definitely :)

**Pull request closed without merging**
