### PR TITLE
[AIRFLOW-3891] Disable SQL Alchemy tracking

### PR DESCRIPTION
**Pull request by drewsonne**
Make sure you have checked _all_ steps below.

### Jira

https://issues.apache.org/jira/browse/AIRFLOW-3891

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
I've created a new Jira for this as the previous one was already included in 1.10.2

**Review by ashb — APPROVED** [review]

**Comment by Fokko** [comment]
The error was so annoying, but is only the quotes? 😨

**Review by Fokko — APPROVED** [review]
I was looking at the second commit, nvm. LGTM, thanks @drewsonne for picking this up!

**Comment by ashb** [comment]
Yeah - that was me :D Since github lets me edit it right then and there it seemed quicker to do that than make Drew change it.

**Comment by ashb** [comment]
Oh. I got confused about this. We didn't actually need a new Jira for it. The problem as this change somehow got removed in #4401.

Oh well :D

**Comment by drewsonne** [comment]
I created this PR before work, and came back and now I feel like I didn’t take part in most of it, but it’s got my name on it anyway. Good work team! 💪 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
