### PR TITLE
[AIRFLOW-XXX] Added Jeitto as one of happy Airflow users!

### PR DESCRIPTION
**Pull request by brennerpablo**
Added Jeitto as one of happy Airflow users!

[Jeitto](https://www.jeitto.com.br) [[@BrennerPablo](https://github.com/BrennerPablo), [@ds-mauri](https://github.com/ds-mauri)

### CODE REVIEW

**Comment by r39132** [comment]
@BrennerPablo the company names need to be in alphabetic order. Please fix!

**Comment by brennerpablo** [comment]
> @BrennerPablo the company names need to be in alphabetic order. Please fix!

Thanks!

**Comment by r39132** [comment]
@BrennerPablo Awesome.. now one nit.. please prepend `[AIRFLOW-XXX]` to your commit message. We generate release notes from the first lines of commit messages, so this reads better. You don't need to create a JIRA for this trivial change -- you can use the placeholder value (XXX). 

Bonus points if you can squash your commits into 1.

**Comment by r39132** [comment]
Welcome aboard!!! Yours is the 200th official company to list itself on the company list!!!

**Pull request merged**
