### PR TITLE
Change from dynamic date to fixed date in examples

### PR DESCRIPTION
**Pull request by collinmcnulty**
The example dags all use a dynamic start date, but this is not good practice. In my experience, many people new to Airflow continue to use dynamic start dates in their real dags and it causes them problems. For example, they get into the habit of using `days_ago(1)` and that works for daily dags but not for anything less frequent than that.

I assume the example dags use dynamic start date to keep from spawning many dagruns for anyone who chooses to run them. I propose that `catchup=False` be used for that purpose instead.

This PR only covers the core airflow example dags, not all the providers.

### CODE REVIEW

**Comment by collinmcnulty** [comment]
I'm fairly sure the remaining test failures are not due to the code changes in this PR.

**Comment by ashb** [comment]
The test failures _might_ be because of a different number of DagRuns being created in the tests that use the example dags

**Comment by ashb** [comment]
I wonder if it's worth adding another conditional index on queued here like we did in https://github.com/apache/airflow/pull/18061

(Annoyingly for Mysql we'd _like_ only a single (state,dag_id) index, but I'm not sure if we can easily/realistically do that.)

**Comment by collinmcnulty** [comment]
I've limited the changes to avoid needing to touch any of the tests. Should be ready for review on the merits of if this is actually a good idea for the examples or not. 

I've read over the Tutorial, Tutorial on Taskflow, and Concepts sections of the documentation and made sure none of the text needs a dynamic `start_date` in the examples to make sense.

**Comment by ephraimbuddy** [comment]
Hi @collinmcnulty can you explain why days_ago(1) only works for daily dags as you said? Also why do you think that using a dynamic date at DagLevel is a bad practice? I understand that if we use dynamic date at default_args tasks may have different start dates, do you think having a static start_date at default_args is also a bad practice?

**Comment by collinmcnulty** [comment]
If you have a task that runs every week with `days_ago(1)`, then at the time it would kick off the `start_date` will be yesterday morning but the `execution_date` will be a week ago. Therefore the dag will not be started as `start_date > execution_date`.

I think you should use static dates for `start_date` at whatever level you set them. I think that if you're setting `start_date` at the task level, it should be because some tasks actually have different times you want them to start from one another, but that's a much less strongly held opinion.

**Comment by ephraimbuddy** [comment]
> If you have a task that runs every week with `days_ago(1)`, then at the time it would kick off the `start_date` will be yesterday morning but the `execution_date` will be a week ago. Therefore the dag will not be started as `start_date > execution_date`.
> 
> I think you should use static dates for `start_date` at whatever level you set them. I think that if you're setting `start_date` at the task level, it should be because some tasks actually have different times you want them to start from one another, but that's a much less strongly held opinion.

Makes sense!

**Review by ephraimbuddy — APPROVED** [review]

**Comment by collinmcnulty** [comment]
I've run the Core and Other tests in breeze for Postgres 13 and Python 3.7 and all passed.

**Comment by ephraimbuddy** [comment]
I have tried to experiment with what you said @collinmcnulty but unfortunately, I can't wrap my head around it.
For example, this dag when parsed today:

```
dag = DAG("mydag_name",
          start_date=days_ago(1),
          schedule_interval="@weekly")
```
would have execution_date stored as "2021-09-12 00:00:00+00". This is when it should run.
On the execution day, the start_date will still be in the past:  "2021-09-11 00:00:00+00" which is less than the execution_date.

Still finding it hard to understand this.

**Comment by collinmcnulty** [comment]
> would have execution_date stored as "2021-09-12 00:00:00+00". This is when it should run.
On the execution day, the start_date will still be in the past: "2021-09-11 00:00:00+00" which is less than the  execution_date.

@ephraimbuddy The start date will be in earlier than the current time, but later than the execution_date because the execution_date for the dagrun that would run on the 12th is a week earlier "2021-09-*05* 00:00:00+00"

**Comment by ephraimbuddy** [comment]
> > would have execution_date stored as "2021-09-12 00:00:00+00". This is when it should run.
> > On the execution day, the start_date will still be in the past: "2021-09-11 00:00:00+00" which is less than the  execution_date.
> 
> @ephraimbuddy The start date will be earlier than the current time, but later than the execution_date because the execution_date for the dagrun that would run on the 12th is a week earlier "2021-09-_05_ 00:00:00+00"

Interesting, need to read more about this execution_date. Thanks

**Pull request merged**
