### PR TITLE
Change Quick Start IDE image path

### PR DESCRIPTION
**Pull request by brienzb**
Since this [PR](https://github.com/apache/airflow/pull/36969), the quick-start-ide image path has changed and the image is not displayed.
I expect the following effects by modifying the paths of the images.

#### ex) [contributors_quick_start_vscode](https://github.com/apache/airflow/blob/main/contributing-docs/quick-start-ide/contributors_quick_start_vscode.rst)
| AS-IS | TO-BE |
| ---| --- |
| 스크린샷 2024-02-25 오후 2 54 56 | 스크린샷 2024-02-25 오후 2 54 06 |

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Ah... I **just** saw it and fixed it independently earlier today (by just pointing to the right images) without seing it. But it's a good idea to move the images as well - can you please rebase this one ? Happy to merge after rebase.

**Comment by brienzb** [comment]
You've already revised it! 👍 And thank you for thinking of my PR in a good way.
I have rebase it. I would appreciate it if you merge :)

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
AAAAnd merged :)

**Comment by potiuk** [comment]
Thanks for contributing it :). Contributing to contributing docs is really good contribution 😆

**Pull request merged**
