### PR TITLE
[AIRFLOW-2163] Add HBC Digital to users of airflow

### PR DESCRIPTION
**Pull request by tmccartan**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2163

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
+1

**Comment by r39132** [comment]
@ashb Want to try merging this one?

**Comment by r39132** [comment]
@ashb Did you merge using the airflow-pr tool or manually merge? If you use the tool, the commit will say "authored by tmccartan and Ash Berlin-taylor committed...". If you manually, merge, I believe it actually creates a commit in your name, which is what I see in the commit log. Any issues running the tool? I ask as I am currently running into some TLS issue running the tool and wonder if it's broken for others as well.

**Comment by ashb** [comment]
I did merge with the tool, yes. I chose no to squash on this (as it was only one commit).

The Jira issue bit failed because I didn't (at the time) have the Jira python module installed.

**Comment by r39132** [comment]
Hmn.. I usually don't squash either. I wonder what's different. Usually, the "authored.... committed" line is preferable as it doesn't create extraneous merge commits and uses the "rebase and merge" option in github (i believe). The way it seems to have gone for you is not that route, but merge (which looks the same for single-commit PRs as a squash and merge.)

**Comment by Fokko** [comment]
I squash most of the time. By squashing it, it will amend the commit, and generate a new commit hash. Because the hashes don't match up, the PR in Github appears to be closed instead of merged. Apparently the author was reset on the commit. Something went wrong, because I would expect having the commit under the name of the original author.

**Pull request merged**
