### PR TITLE
Separate out additional CI image checks

### PR DESCRIPTION
**Pull request by potiuk**
There are a few checks that are needed by other jobs to
continue (such as generating constraints, mypy and running static checks)
and ones that are "standalone" (such as building ARM CI images or making
sure that release process works or pushing early cache for images) - and
failure of those non-important ones should not block the tests that
are finalizing the CI workflow.

We put the nt ones together and move the standalone ones
to a separate workflow to be able to depend only on the ones that
are needed by other tests to group them nicely in the CI workflow.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by aritra24 — APPROVED** [review]

**Comment by potiuk** [comment]
Still a draft - will need to improve and split it a bit differently, looking at some potential failure scenarios that should not block  tests when some unimportant things fail. I will update that one slightly - while the other "teeting" problems are fixed and merged.

**Comment by potiuk** [comment]
OK. Should be now working within the limits of GH when it comes to workflows.

**Review by dirrao — APPROVED** [review]

**Comment by shahar1** [comment]
I'd like to express my concerns regarding the use of `important`/`non-important` terminology - I'd like to hope that the additional CI image checks are also important. Otherwise, they would have been considered YAGNI and removed from the codebase, right? :)
Maybe `critical` and `non-critical` would do better? I'd be happy if you could consider it.

**Comment by potiuk** [comment]
Yeah the naming is wrong.  I think here the case is more about the distinction "other tests depend on it" vs. are independent.  I will think of a better name when I come back to this one.

**Comment by potiuk** [comment]
OK. I named it explicitly " static + mypy + constraints" group vs "additional CI checks" - should nicely reflect the split now.

**Review by eladkal — APPROVED** [review]

**Pull request merged**
