### PR TITLE
Fix setup.py missing comma (1.10.14rc3)

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
Fix 1.10.14rc3 setup.py

### CODE REVIEW

**Comment by potiuk** [comment]
Oh GAD AGAIN.... @kaxil -> sounds like rc4 :(

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
And I will have to double check the constraints.

**Comment by ashb** [comment]
Since this is only in setup_requires we _may_ be lucky and find this doesn't actually break much of anything.

**Comment by ashb** [comment]
```
clean-airflow-1.10.14 ❯ pip install https://dist.apache.org/repos/dist/dev/airflow/1.10.14rc3/apache-airflow-1.10.14rc3-bin.tar.gz
Collecting https://dist.apache.org/repos/dist/dev/airflow/1.10.14rc3/apache-airflow-1.10.14rc3-bin.tar.gz
  Downloading https://dist.apache.org/repos/dist/dev/airflow/1.10.14rc3/apache-airflow-1.10.14rc3-bin.tar.gz (4.1 MB)
...
Building wheels for collected packages: apache-airflow
  Building wheel for apache-airflow (setup.py) ... done
  Created wheel for apache-airflow: filename=apache_airflow-1.10.14-py2.py3-none-any.whl size=4715270 sha256=021bf424f21d9a2980a0105d0d55b962463e060e90f74d28db45524955bd354b
  Stored in directory: /home/ash/.cache/pip/wheels/9f/a3/1d/37323222afda37226454756a8700a4ce0f19461a7f9303175f
Successfully built apache-airflow
Installing collected packages: sqlalchemy, MarkupSafe, Mako, python-editor, six, python-dateutil, alembic, zipp, importlib-metadata, argcomplete, attrs, cached-property, colorlog, configparser, natsort, croniter, dill, idna, dnspython, email-validator, jinja2, werkzeug, click, itsdangerous, flask, wtforms, flask-admin, flask-caching, flask-login, PyYAML, flask-swagger, flask-wtf, funcsigs, future, graphviz, gunicorn, importlib-resources, iso8601, json-merge-patch, pyrsistent, jsonschema, lazy-object-proxy, markdown, pyparsing, packaging, numpy, pytz, pandas, pytzdata, tzlocal, pendulum, psutil, pygments, docutils, lockfile, python-daemon, text-unidecode, python-slugify, python-nvd3, setproctitle, tabulate, tenacity, thrift, unicodecsv, zope.deprecation, typing-extensions, cattrs, pycparser, cffi, cryptography, chardet, urllib3, certifi, requests, sqlalchemy-jsonfield, sqlalchemy-utils, Flask-SQLAlchemy, Babel, Flask-Babel, marshmallow, prison, PyJWT, Flask-JWT-Extended, apispec, marshmallow-sqlalchemy, defusedxml, python3-openid, Flask-OpenID, colorama, marshmallow-enum, flask-appbuilder, apache-airflow
Successfully installed Babel-2.9.0 Flask-Babel-1.0.0 Flask-JWT-Extended-3.25.0 Flask-OpenID-1.2.5 Flask-SQLAlchemy-2.4.4 Mako-1.1.3 MarkupSafe-1.1.1 PyJWT-1.7.1 PyYAML-5.3.1 alembic-1.4.3 apache-airflow-1.10.14 apispec-1.3.3 argcomplete-1.12.2 attrs-20.3.0 cached-property-1.5.2 cattrs-1.1.2 certifi-2020.12.5 cffi-1.14.4 chardet-3.0.4 click-7.1.2 colorama-0.4.4 colorlog-4.0.2 configparser-3.5.3 croniter-0.3.36 cryptography-3.2.1 defusedxml-0.6.0 dill-0.3.3 dnspython-2.0.0 docutils-0.16 email-validator-1.1.2 flask-1.1.2 flask-admin-1.5.4 flask-appbuilder-2.3.4 flask-caching-1.3.3 flask-login-0.4.1 flask-swagger-0.2.14 flask-wtf-0.14.3 funcsigs-1.0.2 future-0.18.2 graphviz-0.15 gunicorn-20.0.4 idna-2.10 importlib-metadata-2.1.1 importlib-resources-1.5.0 iso8601-0.1.13 itsdangerous-1.1.0 jinja2-2.11.2 json-merge-patch-0.2 jsonschema-3.2.0 lazy-object-proxy-1.4.3 lockfile-0.12.2 markdown-2.6.11 marshmallow-2.21.0 marshmallow-enum-1.5.1 marshmallow-sqlalchemy-0.23.1 natsort-7.1.0 numpy-1.19.4 packaging-20.7 pandas-1.1.4 pendulum-1.4.4 prison-0.1.3 psutil-5.7.3 pycparser-2.20 pygments-2.7.3 pyparsing-2.4.7 pyrsistent-0.17.3 python-daemon-2.2.4 python-dateutil-2.8.1 python-editor-1.0.4 python-nvd3-0.15.0 python-slugify-4.0.1 python3-openid-3.2.0 pytz-2020.4 pytzdata-2020.1 requests-2.23.0 setproctitle-1.2.1 six-1.15.0 sqlalchemy-1.3.20 sqlalchemy-jsonfield-0.9.0 sqlalchemy-utils-0.36.8 tabulate-0.8.7 tenacity-4.12.0 text-unidecode-1.3 thrift-0.13.0 typing-extensions-3.7.4.3 tzlocal-1.5.1 unicodecsv-0.14.1 urllib3-1.25.11 werkzeug-0.16.1 wtforms-2.3.3 zipp-3.4.0 zope.deprecation-4.4.0
WARNING: You are using pip version 20.2.4; however, version 20.3.1 is available.
You should consider upgrading via the '/home/ash/.virtualenvs/clean-airflow-1.10.14/bin/python -m pip install --upgrade pip' command.
pip install   37.21s user 3.42s system 90% cpu 44.937 total
```

Doesn't seem to have actually broken anything for me.

**Comment by potiuk** [comment]
> Doesn't seem to have actually broken anything for me.

ufff!

**Comment by GuillaumeDesforges** [comment]
The package built without the fix, but some other libs that parse the requirements were failing (e.g. using https://github.com/DavHau/mach-nix)

**Comment by kaxil** [comment]
Just talked with Ash, this won't be an issue for Airflow users but we will create rc4 with the fix since this is supposed to be a bridge release and we haven't lost a good amount of time yet after rc3. Creating it now. 

Thanks for reporting and fixing @GuillaumeDesforges

**Comment by potiuk** [comment]
I indeed checked that it has no impact indeed -> all the scenarios works fine with pip 20.2.4: constraint install works, eager upgrade works and produces consistent constraints. 

However looking at comment from @GuillaumeDesforges and  taking into account the recent PIP 20.3 "adventures" and fact that PIP becomes more strict about stuff and "correctness" of PIP packages is now more important than before. It won't delay voting that much, maybe worth to release rc4. @kaxil @ashb  WDYT?

**Comment by potiuk** [comment]
> Just talked with Ash, this won't be an issue for Airflow users but we will create rc4 with the fix since this is supposed to be a bridge release and we haven't lost a good amount of time yet after rc3. Creating it now.
> 
> Thanks for reporting and fixing @GuillaumeDesforges

Cool!

**Comment by potiuk** [comment]
Cn you also merge the breeze PR  with it to stable @kaxil :) ?

**Comment by potiuk** [comment]
BTW. There is the extra space as well in the second place where docutils are mentioned

**Comment by kaxil** [comment]
> Cn you also merge the breeze fix with it to stable @kaxil :) ?

yup will do

**Comment by potiuk** [comment]
And another BTW. I checked and it has no impact on 20.3 bug (in case you asked :D)

**Comment by ashb** [comment]
Just opened a PR to add/enable the pylint option to check for this.

**Pull request merged**
