### PR TITLE
[AIRFLOW-2041] Syntax correction of python examples

### PR DESCRIPTION
**Pull request by 0atman**
### JIRA
Trivial change, no ticket. (happy to make one if needed).

### Description

I parsed the readme with the ol' eyeball compiler. Changes:

 - correct `def` syntax on line 50
 - use literal `dict` on line 67

### Tests
Text only additions. It's not impossible that a clever someone could automate linting the examples in the readme in the future.

### CODE REVIEW

**Review by gwax — APPROVED** [review]
LGTM

**Comment by 0atman** [comment]
Anyone fancy clicking merge?

**Comment by criccomini** [comment]
PR needs a JIRA and proper title formatting

**Comment by 0atman** [comment]
Done! Sorry it took a while :smile:

**Comment by r39132** [comment]
+1

**Pull request closed without merging**
