### PR TITLE
[AIRFLOW-2291] Add optional params to ML Engine Training operator

### PR DESCRIPTION
**Pull request by dlebech**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2291

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

This PR adds three extra optional parameters to the `MLEngineTrainingOperator` as well as a new unit tes for the `MLEngineVersionOperator`

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

- `testSuccessCreateTrainingJobWithOptionalArgs` for the extra parameters
- `testSuccessCreateVersion` for creating a new ML Model Version (no tests existed at all for this operator before)

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

There are a bunch of other errors *unrelated to this PR*

### CODE REVIEW

**Comment by Fokko** [comment]
@kaxil @fenglu-g thoughts?

**Comment by wileeam** [comment]
@dlebech I have a pending PR ([AIRFLOW-2291](https://github.com/apache/incubator-airflow/pull/2746)) that would benefit from this too. A bit of rework and cleanup of the operator as well.
But I didn't address one comment as other operators :) and DAGs came up; although I just commented to the reviewer.
Not sure what is the best approach here @Fokko. My PR could include this PR as I address parameters too (although with a focus on templating) and at the same time I also did some cleanup in the operators.
But I don't want @dlebech to have to fix conflicts nor myself :)

**Comment by dlebech** [comment]
@wileeam It seems to be that my PR contains such as a small change, and it doesn't really interfere with your PR (mine simply adds a few parameters to the traning operator, not the prediction operator), so I don't know what benefit there is to try and merge the two PRs? But anyway, that's not my call, so I'll be happy just to see this change in Airflow no matter what path it takes to get there :-)

**Comment by kaxil** [comment]
LGTM. But can you rebase with the master again to trigger Travis CI and see if it passes? @dlebech

**Review by kaxil — COMMENTED** [review]
LGTM

**Comment by kaxil** [comment]
Can you rebase with the master again to trigger Travis CI and see if it passes? @dlebech

**Comment by Fokko** [comment]
I've merged https://github.com/apache/incubator-airflow/pull/2746, can you rebase onto master? Thanks!

**Comment by dlebech** [comment]
@kaxil @Fokko Thanks, I've rebased and it looks like Travis is happy :-)

**Comment by Fokko** [comment]
Thanks @dlebech, merged to master

**Pull request closed without merging**
