### PR TITLE
Added chunk_size parameter to LocalFilesystemToGCSOperator 

### LINKED ISSUE #38958: add blob size to LocalFilesystemToGCSOperator
### Description

Hi team,

I hope LocalFilesystemToGCSOperator can add blob size in order to allow users to upload large files without timeout issue. the hook.upload has blob size arg.  

### Use case/motivation

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jsjasonseba**
closes: https://github.com/apache/airflow/issues/38958
related: https://github.com/apache/airflow/issues/38958

This PR added a chunk_size parameter to the LocalFilesystemToGCSOperator. This parameter is already implemented in the GCSHook.upload function. This change ensures that the chunk_size is passed to the upload function.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]

**Comment by potiuk** [comment]
Some spell-check issue.

**Comment by jsjasonseba** [comment]
It seems like the spell-check detects 'KiB' as an invalid term, even tough it should be valid. I have removed it.

**Comment by potiuk** [comment]
There is a list of allowed words. KiB is not on it. you can add it there, or you can `KiB` quote the word to avoid spellchecking it.

**Comment by jsjasonseba** [comment]
I wasn't aware of the list of allowed words. Let me add it to the list. Thanks for letting me know.

**Comment by potiuk** [comment]
And merged :)

**Pull request merged**
