### PR TITLE
[AIRFLOW-273] Create an svg version of the airflow logo.

### PR DESCRIPTION
**Pull request by gwax**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-273

Testing Done:
Viewed the generated image file in Chrome.

Reminders for contributors:
- Your PR's title must reference an issue on [Airflow's JIRA](https://issues.apache.org/jira/browse/AIRFLOW/). For example, a PR called "[AIRFLOW-1] My Amazing PR" would close JIRA issue #1. Please open a new issue if required!
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules).

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Cool! I tried it in some viewers bit it didn't show the colors yet. Bit that might be due to the viewers. Please add the Apache 2.0 license header to the file, we can check then properly and merge.

**Comment by gwax** [comment]
License added.

As for proper rendering, I have only tested in chrome and can't really speak to other viewers.

**Comment by bolkedebruin** [comment]
Ok. thanks. Please make sure to include a Jira (this is per apache guidelines) create one if needed, then also include it in your commit message. Sorry for the nit, great work this.

**Comment by bolkedebruin** [comment]
A sorry missed the title, I will merge and update the commit message

**Comment by underyx** [comment]
Awesome, thank you @gwax :heart:

**Pull request closed without merging**
