### PR TITLE
CHANGELOG for 1.8

### PR DESCRIPTION
**Pull request by alexvanboxel**
CHANGELOG for 1.8, please do not merge yet. Because the 1.7 branches are gone it was hard to compare Luckily I had one locally.

### CODE REVIEW

**Comment by igozali** [comment]
Really excited for this! Was wondering if you have an approximate release date for this upcoming version (1.8)?

**Comment by bolkedebruin** [comment]
See Airflow 1.8.0 BETA 1 Thread:

RELEASE PLANNING

Beta 2: 20 Jan
Beta 3: 25 Jan
RC1:  2 Feb


RC1 should be equal to release if all goes as planned (but no guarantees), besides it needs to go through the voting process of the IPMC and they might require some adjustments.

Bolke

**Comment by bolkedebruin** [comment]
Airflow 782 is not in 1.8. I reverted that one for 1.8 but you probably excluded reverts :-)

**Comment by bolkedebruin** [comment]
Please don't tag it rc1 but 1.8.0. The rc can become release right away if we find no blockers.

**Pull request closed without merging**
