### PR TITLE
Fix breeze failing breeze on missing docker config

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by subkanthi — APPROVED** [review]

**Comment by uranusjr** [comment]
Does this skip setting `experiemental` when the config is missing? Should we write `{"experiemental": true}` instead?

**Comment by potiuk** [comment]
> Does this skip setting `experiemental` when the config is missing? Should we write `{"experiemental": true}` instead?

Nope. 

The `{"experiemental": true}` is correct for engine side (`.docker/deamon.json`) but `{"experiemental": "enabled"}` is needed for the client side (`.docker/config.json`) 

https://thenewstack.io/how-to-enable-docker-experimental-features-and-encrypt-your-login-credentials/

¯\_(ツ)_/¯

**Comment by uranusjr** [comment]
Eh. So should we write `{"experiemental": "enabled"}` if `~/.docker/config` is missing? (This PR is not doing that right now.)

**Comment by potiuk** [comment]
> Eh. So should we write `{"experiemental": "enabled"}` if `~/.docker/config` is missing? (This PR is not doing that right now.)

Not really. This is only needed in a specific case in CI where we wait for CI image. But yeah - we could actually only do that In CI too, so I will add it as an exception. The ".docker" missing is only when you start breeze locally, but you never, ever started any docker command before, and this is not the case in CI.

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
> Eh. So should we write `{"experiemental": "enabled"}` if `~/.docker/config` is missing? (This PR is not doing that right now.)

I updated it to only run on CI and added warning in case it cannot be set + some comments. This will make it less magical.

**Comment by potiuk** [comment]
(And I only added "likely" because at some point the manifest command might stop being experimental :D )

**Pull request merged**
