### PR TITLE
Switch to GitHub-rendered Mermaid diagrams

### PR DESCRIPTION
**Pull request by potiuk**
We used mermaid diagrams in a few places and had pre-commit
script to generate images out of them, but since GitHub
introduced rendering of mermaid diagrams in javascript, we can
now switch to markdown files with embedded mermaid markup.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @edithturn -> I extracted some parts of the docs and I got the mermaid diagrams working :)

**Comment by edithturn** [comment]
wow! this is just amazing 🤩💪🏾💪🏾🥳. Wohooo!!!

**Comment by edithturn** [comment]
If you allow me to suggest something, the graph of selective check could be better in this way (Just details) especially in the part of **Enable images**
```mermaid
flowchart TD
A(PR arrives)-->B[Selective Check]
B-->C{Direct push merge?}
C-->|Yes| N[Enable images] 
N-->D(Run Full Test<br />+Quarantined<br />Run full static checks)
C-->|No| E[Retrieve changed files]
E-->F{Environment files changed?}
F-->|Yes| N
F-->|No| G{Docs changed}
G-->|Yes| O[Enable images building]
O-->I{Chart files changed?}
G-->|No| I
I-->|Yes| P[Enable helm tests]
P-->J{API files changed}
I-->|No| J
J-->|Yes| Q[Enable API tests]
Q-->H{Sources changed?}
J-->|No| H
H-->|Yes| R[Enable Pytests]
R-->K[Determine test type]
K-->S{Core files changed}
S-->|Yes| N
S-->|No| M(Run selected test+<br />Heisentest, Integration, Quarantined<br />Full static checks) 
H-->|No| L[Skip running test<br />Run subset of static checks]
```

**Comment by potiuk** [comment]
Of course. Updated. And added you as co-author :)

**Comment by potiuk** [comment]
Anyone? Removing another functionality that GitHub provided us for free.

**Review by kaxil — APPROVED** [review]

**Pull request merged**
