### PR TITLE
[AIRFLOW-1554] Wrong DagFileProcessor method name call

### PR DESCRIPTION
**Pull request by chopkins123**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1554) issues and references them in the PR title. 

### Description
- [x] The DagFileProcessorManager.set_file_paths() function was incorrectly calling processor.stop() instead of processor.terminate(). This would cause an AttributeError to be thrown and the scheduler to hang, not processing any future DAGs.

### Tests
- [x] My PR adds the following unit tests:
\tests\utils\test_dag_processing.py

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by edgarRd** [comment]
LGTM - kudos for the tests.

**Comment by bolkedebruin** [comment]
Can you update your commit message to reference the jira issue, make sure the formatting is correct and remove any spurious edits? Thanks!

**Comment by pdambrauskas** [comment]
Would be nice to get this for 1.9 :).

**Comment by bolkedebruin** [comment]
Can you close this please?

**Pull request closed without merging**
