### PR TITLE
Move triggers to standard provider

### PR DESCRIPTION
**Pull request by gopidesupavan**
Move triggers to standard provider

airflow/triggers/external_task.py
airflow/triggers/file.py
airflow/triggers/temporal.py

to 

providers/src/airflow/providers/standard/triggers/external_task.py
providers/src/airflow/providers/standard/triggers/file.py
providers/src/airflow/providers/standard/triggers/temporal.py

related #43641

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by gopidesupavan** [comment]
These changes also require to support 2.8 and 2.9, will wait for this https://github.com/apache/airflow/pull/43556 and then rebase on top so that will fix if anything fails for 2.8 and 2.9.

Meanwhile working on local and verifying to support these changes on 2.8 and 2.9 :)

**Comment by potiuk** [comment]
> These changes also require to support 2.8 and 2.9, will wait for this #43556 and then rebase on top so that will fix if anything fails for 2.8 and 2.9.
> 
> Meanwhile working on local and verifying to support these changes on 2.8 and 2.9 :)

Yeah ... Some of #43556  take a bit more  than I originally anticipated :D

**Comment by gopidesupavan** [comment]
> > These changes also require to support 2.8 and 2.9, will wait for this #43556 and then rebase on top so that will fix if anything fails for 2.8 and 2.9.
> > Meanwhile working on local and verifying to support these changes on 2.8 and 2.9 :)
> 
> Yeah ... Some of #43556 take a bit more than I originally anticipated :D

Yeah fine no rush ☺️...

**Comment by gopidesupavan** [comment]
This is green now, one test failed not related to this. would anyone have another look on the latest modifications, mostly those are test fixes to support compatibility :)

**Review by romsharon98 — APPROVED** [review]

**Pull request merged**
