### PR TITLE
Prepare FAB provider to set next version as major version

### PR DESCRIPTION
**Pull request by vincbeck**
Prepare the provider to set its next version as major version. I also set the state of the provider as non-ready because we should not release the provider next major version before Airflow 3 release timeframe.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by vincbeck** [comment]
I need to work on the tests since it seems that setting the state of an already installed provider from ready to non-ready is not that trivial

**Comment by eladkal** [comment]
> I need to work on the tests since it seems that setting the state of an already installed provider from ready to non-ready is not that trivial

I dont think this is right approch. We may still release 1.x versions. For example if we find security risk.
Provider should stay in ready state.
Also, we are going to have airflow 3 alpha/beta which might need also alpha/beta of the provider

I can simply skip its release manually if needed.

**Comment by vincbeck** [comment]
The compat tests are failing because Airflow 2.9 and 2.10 tries to install the latest fab provider that is only compatible with Airflow 3. In `hatch_build`, the fab provider constraint is `fab>=1.0.2`. How can we solve that?  Should we, somehow, update this constraint to `fab>=1.0.2<=2.0.0` for Airflow 2.9 and 2.10?

**Comment by vincbeck** [comment]
Or should `uv` figure it out on its own?

**Comment by potiuk** [comment]
> Or should `uv` figure it out on its own?

I think we will have to simply skip fab provider for Airflow 2.9 and 2.10. That should do the job. It will be installing applicable FAB from PyPI then

**Comment by potiuk** [comment]
```
BASE_PROVIDERS_COMPATIBILITY_CHECKS: list[dict[str, str | list[str]]] = [
    {
        "python-version": "3.9",
        "airflow-version": "2.8.4",
        "remove-providers": "cloudant fab edge",
        "run-tests": "true",
    },
    {
        "python-version": "3.9",
        "airflow-version": "2.9.3",
        "remove-providers": "cloudant edge",
        "run-tests": "true",
    },
    {
        "python-version": "3.9",
        "airflow-version": "2.10.3",
        "remove-providers": "cloudant",
        "run-tests": "true",
    },
]
```

**Comment by vincbeck** [comment]
> > Or should `uv` figure it out on its own?
> 
> I think we will have to simply skip fab provider for Airflow 2.9 and 2.10. That should do the job. It will be installing applicable FAB from PyPI then

Makes sense. Thank you!

**Comment by vincbeck** [comment]
All tests are passing!

**Review by eladkal — DISMISSED** [review]
Temporary block to avoid merge

Lets wait with this after we finish current wave of providers. If we merge this PR we wont be able to make rc2.

After provider wave is finished we can dismiss this block and merge

**Comment by vincbeck** [comment]
Providers are now released. Can we proceed with this one?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
