### PR TITLE
[AIRFLOW-3259] Internal Server Error when creating charts because of sort function

### PR DESCRIPTION
**Pull request by elmesaoudee**
Make sure you have checked all steps below.

## Jira ##
Check the following JIRA for more clarifications.
[JIRA issue](https://issues.apache.org/jira/browse/AIRFLOW-3259)

## Description ##
**Problem**
When you try to create a chart and display metrics you get an internal server error.

**Cause**
A dependency issue: the function "sort" was deprecated and is no longer a part of pandas Dataframe and thus it creates a problem when creating charts in airflow.

**Solution**
The sort function needs to replaced by sort_values instead (See code below)
`# Replace this `
`df = df.sort(df.columns[0]) `
`# By this `
`df = df.sort_values(by=df.columns[0])`
In views.py

**Result**
The data is loaded and the chart displayed   

## Tests ##
My PR does not need testing for the simple reason:
My code doesn't change the behavior of the code, but rather modifies a no longer existing function (in pandas) with its new substitute.

## Code quality ##
  Passes `flake8`

### CODE REVIEW

**Comment by elmesaoudee** [comment]
Could you retrigger the build please? Travis timed out on the last job for no apparent reason. I tried building my fork and it passed gracefully. Thank you.

**Comment by zackmeso** [comment]
How is it possible that my changes decreased code cov by 7% ?!!

**Comment by Fokko** [comment]
@zackmeso Would it be possible to test this?

**Comment by elmesaoudee** [comment]
Hello @Fokko I answered you on this new [PR](https://github.com/apache/incubator-airflow/pull/4114)
I created a new PR in order to comply with the contribution guidelines.

**Pull request closed without merging**
