### PR TITLE
Added test-case for callable values in path and query parameters of MSGraphAsyncOperator

### PR DESCRIPTION
**Pull request by dabla**
This PR allow callable values to be passed into the path and query parameters so expensive evaluations (like Variable.get) don't get evaluated during DAG processing time.  I'm aware you can get variables through jinja expressions, but in case of jinja None get's evaluated as an empty string which causes issues when calling the MSGraph end point as key/value parameters with value None aren't taken into account while empty string is causing issues further on.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by raphaelauv** [comment]
all templated fields can already be a callable since airflow 2.10.0

**Comment by dabla** [comment]
> all templated fields can already be a callable since airflow 2.10.0

Ow damn well that makes it easy then we may close this one.

**Comment by dabla** [comment]
Maybe will reopen it and keep the tests but with additional code

**Comment by dabla** [comment]
> all templated fields can already be a callable since airflow 2.10.0

Indeed templated fields are callable, but here I also support callable values of a dict key/value pair which is passed to a templated field, which is not supported by default in templated fields.  So this PR still makes sense.

**Comment by dabla** [comment]
I've removed the code regarding callable evaluation within dict values for templated fields and I've adapted the tests so it uses the already existing behaviour of the callable templated fields in Airflow.

**Comment by raphaelauv** [comment]
I invite you to open a new PR , I don't understand what new feature you propose

**Comment by dabla** [comment]
> I invite you to open a new PR , I don't understand what new feature you propose

I removed the feature, I just updated the tests using the callable as of 2.10.  My proposition was to also allow callables within dict parameters, but I stepped away from it.  I now just use the existing Airflow feature but updated the tests accordingly

**Comment by dabla** [comment]
@raphaelauv just consider this PR as an improvement of the integration tests for the MSGraph operator and sensor in which I now also test the usage of lambdas supported since Airflow 2.10.0

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Nice!

**Pull request merged**
