### PR TITLE
[AIRFLOW-3948] Operator list as templated field issue 

### PR DESCRIPTION
**Pull request by ryanyuan**
Operator list as templated field

This is a global fix for #4770 

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [AIRFLOW-3948](https://issues.apache.org/jira/browse/AIRFLOW-3948) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
I don't think this sort of special case handling should be needed after #4292 (which is in master but not released, will make it in to 1.10.3).

For example https://github.com/VilledeMontreal/incubator-airflow/blob/d8841ea88797f908d988c4121cae59d3fcd82518/tests/models.py#L421-L424

Maybe all the change we need to do here is add more fields to be templated in these operators.

**Comment by ryanyuan** [comment]
@ashb Thank you for looking at my PR.

I looked at the commit you mentioned above. It looks like the issue it's fixed is not for the issue I've raised.

If I pass a Jinja template to a templated field, the type of the content would be string. In that case, it will render the actual value using Jinja template as string.

For example:
```
def push_value(**kwargs):
    kwargs['ti'].xcom_push(key='push_key', value=[1, 2, 3])

def do_nothing(**kwargs):
    return

push_task = PythonOperator(
    task_id='push_task',
    dag=dag,
    python_callable=push_value,
)

pull_task = PythonOperator(
    templates_list='{{ ti.xcom_pull(key="push_key") }}',
    task_id='pull_task',
    dag=dag,
    python_callable=do_nothing,
)

push_task >> pull_task
```

Inside pull_task, the type of templates_list is string instead of list.

My fix is specifcally for passing Jinja templated list to a templated field. And the rendered value should be converted from string to list.

**Comment by ashb** [comment]
Ah okay, similar but not the same issue.

In  the specific case of PythonOperator you can do this:

```python
def push_value(**kwargs):
    kwargs['ti'].xcom_push(key='push_key', value=[1, 2, 3])

def do_nothing(ti, **kwargs):
    mylist = ti.xcom_pull(key='push_key')
    print(repr(mylist))
    return

push_task = PythonOperator(
    task_id='push_task',
    provider_context=True,
    dag=dag,
    python_callable=push_value,
)

pull_task = PythonOperator(
    task_id='pull_task',
    provide_context=True,
    dag=dag,
    python_callable=do_nothing,
)

push_task >> pull_task
```

(I know that only works for python operator, and not a general solution.)

I think https://issues.apache.org/jira/browse/AIRFLOW-3362 is the way to fix this more generally - that one: works with types other than list, and doesn't need each operator to handle it specifically.

**Comment by ryanyuan** [comment]
@ashb Oh awesome! I will have a look at the new Jinja2 library. Cheers!

**Pull request closed without merging**
