### PR TITLE
Proposal for serialized pythonoperator

### PR DESCRIPTION
**Pull request by casassg**
This is just an illustrative PR for discussion on how to handle serialization for generic python operator serialization. The idea is to serialize using `inspect.getsource` this allows us to just send the source code to the worker, which should allow us to avoid having to send the DAG file to the worker for execution.

### CODE REVIEW

**Comment by ashb** [comment]
This is likely going to be a _hard_ pass from me. The issue is that there is so many cases where this doesn't work (imports, closure context, etc) and if we wanted to do this, https://pypi.org/project/cloudpickle/ is a more battle tested solution (it's what pyspark uses) anyway.

So: yes, this would be a cool features, but I am skeptical of this approach. Sorry.

**Comment by casassg** [comment]
yeah, no worries. This was just a simple example of how it could be done. cloudpickle also works, just wanted to test a more vanilla approach to it. The idea though is the same.

**Comment by casassg** [comment]
Okay. Gave it some extra thought. My main worry with CloudPickle is that we would need to have the same version of python on the workers than the one used to serialize. This won't work for the following scenarion:
- Store old version of DAGs in DB and want to re-run them
- Python version from DAG submitter is not the same as the one from the executor

Regarding imports:
- We can inherit imports from current context (should have same imports if we execute DAG file).
- Recommend users to import inside the function (this is how PySpark also recommends to do it)


Not sure what you mean by closure context. How is this worse than executing the function itself?

**Comment by ashb** [comment]
```
def make_op():
    a = 1
    @task
    def my_func():
        return a+1
    return my_func
```

That won't work. Parsing and re-evaluating a string is _very_ error prone and will fail in all sorts of cases.

**Comment by ashb** [comment]
I don't love (cloud) pickle, but there is a reason pyspark uses it.

My understanding was the version of Python doesn't have to match _exactly_. Is that not the case

**Comment by casassg** [comment]
`Cloudpickle can only be used to send objects between the exact same version of Python.`

I tried to find if there's a compilation of compatible versions or how often does it break (aka does it need to be on re-release).

Regarding your code example, it would indeed not work. But you can teach users to make sure to only use scoped variables. So it comes off as flexibility to create complex functions vs compatibility between different environments. I believe each option has its issue. 

My view is that you more often will find yourself wanting to re-execute old DAGs (after upgrading) than want to make complex functions with weird scopes.

The alternative is to allow both options and let user decide what's used underneath.

**Pull request closed without merging**
