### PR TITLE
Better validation of Dataset URI during dag parse

### LINKED ISSUE #26380: UI doesn't handle whitespace/empty dataset URI's well
### Apache Airflow version

main (development)

### What happened

Here are some poor choices for dataset URI's:

```python3
empty = Dataset("")
colons = Dataset("::::::")
whitespace = Dataset("\t\n")
emoji = Dataset("😊")
long = Dataset(5000 * "x")
injection = Dataset("105'; DROP TABLE 'dag")
```

And a dag file which replicates the problems mentioned below: https://gist.github.com/MatrixManAtYrService/a32bba5d382cd9a925da72571772b060 (full tracebacks included as comments)

Here's how they did:
|dataset|behavior|
|:-:|:--|
|empty| dag triggered with no trouble, not selectable in the datasets UI|
|emoji| `airflow dags reserialize`: `UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f60a' in position 0: ordinal not in range(128)`|
|colons| no trouble|
|whitespace| dag triggered with no trouble, selectable in the datasets UI, but shows no history|
|long|sqlalchemy error during serialization|
|injection| no trouble|

Finally, here's a screenshot:

Screen Shot 2022-09-13 at 11 29 02 PM

Notice that there are two empty rows in the datasets list, one for `empty`, the other for `whitespace`.  Only `whitespace` is selectable, both look weird.

### What you think should happen instead

I propose that we add a uri sanity check during serialization and just reject dataset URI's that are:
- only whitespace
- empty
- long enough that they're going to cause a database problem

The `emoji` case failed in a nice way.  Ideally `whitespace`, `long` and `empty` can fail in the same way.  If implemented, this would prevent any of the weird cases above from making it to the UI in the first place.

### How to reproduce

Unpause the above dags

### Operating System

Docker/debian

### Versions of Apache Airflow Providers

n/a

### Deployment

Astronomer

### Deployment details

`astro dev start`

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ashb**
Previously we had the validation on the Dataset model, but we since moved the "dag" facing class to a separate one. This adds validation to the public class, and extends the validation to not allow space-only strings

Closes #26380

### CODE REVIEW

**Comment by norm** [comment]
Might be worth retiring `tests/models/test_dataset.py` as part of this?

**Comment by ashb** [comment]
> Might be worth retiring `tests/models/test_dataset.py` as part of this?

I considered that, but we do still have validation on the model -- should we keep that or not?

**Comment by ashb** [comment]
Oh, those are testing the public dataset class, not the model. Yeah I'll remove those tests!

**Comment by ashb** [comment]
Fail Ash. (New dev env, don't have pre-commit set up there yet)

**Comment by kaxil** [comment]
The failure is due to https://github.com/apache/airflow/pull/26382 I think -- where we forgot to add it to rat_exclude?

**Comment by jedcunningham** [comment]
> The failure is due to #26382 I think -- where we forgot to add it to rat_exclude?

Yep, unrelated to this one.

**Comment by ashb** [comment]
Failure is on main, merging.

**Comment by ashb** [comment]
https://github.com/apache/airflow/pull/26396 to fix main.

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
