### PR TITLE
[AIRFLOW-1642] Use scoped_session in alembic revision cc1e65623dc7

### PR DESCRIPTION
**Pull request by jgao54**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1642

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
The alembic script does not use a [scoped_session](http://docs.sqlalchemy.org/en/latest/orm/contextual.html#sqlalchemy.orm.scoping.scoped_session), which could potentially cause deadlocks (see JIRA for an example scenario of this). Using settings.Session() instead will create a scoped session.
Note: This alembic script is introduced after the current stable release, so *should* be safe to modify. 

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Ran migration script locally for testing. Unit tests not applicable here.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by jgao54** [comment]
Error:

```
INFO  [alembic.runtime.migration] Running upgrade 127d2bf2dfa7 -> cc1e65623dc7, add max tries column to task instance
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/.tox/py34-cdh-airflow_backend_postgres/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/travis/build/apache/incubator-airflow/.tox/py34-cdh-airflow_backend_postgres/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: relation "task_instance" does not exist
LINE 2: FROM task_instance 
             ^
```

Looks like the failure is only happening in postgres. If anyone has encountered a similar case in the past, would love to get some insight, thanks!

**Comment by ashb** [comment]
@jgao54 Could you enable the "Allow edits from maintainers." setting on this branch/PR and then I'll try fixing this up?

**Comment by Fokko** [comment]
I'm also a big fan of the with-comprehension when it comes to database sessions.

**Comment by OmerJog** [comment]
@jgao54 Was this dropped?

**Pull request closed without merging**
