### PR TITLE
Fix broken stat scheduler_loop_duration

### PR DESCRIPTION
**Pull request by 0vj00**
The stat `scheduler_loop_duration` is broken since [this](https://github.com/apache/airflow/commit/0f4884c3ca26c39bc6bd21967c950e718589fcd6#diff-b0491913f69327937706aea8fc77a71efeb979897898e405ade2b162ad862476R1104) change. The nesting of the stats context statement results in it not capturing the full scheduler loop duration. This PR fixes the nesting.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by 0vj00** [comment]
@howardyoo - Would appreciate if you can review as well, since this follows up on your original PR https://github.com/apache/airflow/pull/40802

**Comment by howardyoo** [comment]
Thanks, I’ll take a look!Sent from my iPhoneOn Oct 10, 2024, at 2:09 AM, Venkat VJ ***@***.***> wrote:﻿
@howardyoo - Would appreciate if you can review as well, since this follows up on your original PR #40802

**Comment by potiuk** [comment]
I approved the run - @howardyoo, would be great to get the review. Also - if we could have some unit test for that (can we?) it would be great.

**Comment by howardyoo** [comment]
> I approved the run - @howardyoo, would be great to get the review. Also - if we could have some unit test for that (can we?) it would be great.

I don't think this can be unit-tested..?
The fix seems to be related to some changes that happened outside of Airflow OTEL implementation, but the code change makes sense.

**Review by potiuk — APPROVED** [review]

**Comment by sunchao** [comment]
@potiuk @0vj00 any chance this can be added to Airflow 2.10.3 release? we are seeing the same issue as well

**Comment by potiuk** [comment]
> @potiuk @0vj00 any chance this can be added to Airflow 2.10.3 release? we are seeing the same issue as well

No. Not unless 2.10.3 rc1 is cancelled and we attempt to do 2.10.3rc2 (cc: @utkarsharma2 @ephraimbuddy ) -> I marked it provisionally for 2.10.4 - next time it's a good idea to mention it before we prepare a new release, that things are good candidates and would be great to back-port.

**Comment by sunchao** [comment]
I see, thanks @potiuk

**Comment by potiuk** [comment]
We are going to have rc2 - > backporting that one in #43544

**Pull request merged**
