### PR TITLE
Rewrite the task decorator as a composition

### PR DESCRIPTION
**Pull request by uranusjr**
With more and more things being put into the `@task` decorator, it becomes more difficult to see what names are being used, since the mixin-inheritance structure requires looking at the mixin declarations to know what names each mixin provides. This troubles me while reviewing #20860.

By using a composition-based approach, these names become immediately visible in the same file, making it easier to design and review new name additions.

I also added some more type annotations to make the return type easier to check. This PR does not include any functional changes.

### CODE REVIEW

**Comment by ashb** [comment]
This doesn't work for autocompletion:

image

**Comment by uranusjr** [comment]
Hmm, looks like not all autocompletion systems are smart enough to “look through” `staticmethod`. I changed the implementation to use a metaclass. Does that work better?

**Comment by ashb** [comment]
Nope, still no joy this way.

Though now looking at it, something about the current way is broken too, and it doesn't actually work right now either :(

**Comment by ashb** [comment]
Ah i think my VSCode wasn't using the virtual env where Airflow was installed in :)

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
> Ah i think my VSCode wasn't using the virtual env where Airflow was installed in :)

VScode :)?

**Pull request merged**
