### PR TITLE
Add ability to provide proxy for dbt Cloud connection

### PR DESCRIPTION
**Pull request by b-per**
Adding the ability to define proxy settings when connecting to dbt Cloud. This can be useful for people setting up IP restrictions on dbt Cloud, allowing only some IPs to connect.

This is my first contribution to Airflow, so feel free to let me know if I need to do anything else.

I update the code for the hooks and added some documentation.

I didn't add tests as I am not too sure of how I could do it in that case, but I am happy to do so with a bit of pointers/guidance.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Needs unit tests.

**Comment by b-per** [comment]
Happy to add some, but I am not able run the existing ones. Hence why I was wondering if there was any pointer or guidance.

If I do a `pytest tests/providers/dbt/cloud/` in my hatch env I get a `ModuleNotFoundError: No module named 'sqlalchemy'` but `sqlalchemy` is indeed installed

**Comment by b-per** [comment]
I actually managed to run the tests with `breeze testing tests --test-type "Providers[dbt.cloud]"`.

I have updated them so that they pass again and I have added an extra test with the proxy.

Let me know if instead of creating a new test you prefer if I update all the `pytest.mark.parametrize` to include the connection with a proxy.

My rationale for adding a new test for the proxy rather than as a parameter for all tests is that most people using the providers won't need the proxy.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> If I do a pytest tests/providers/dbt/cloud/ in my hatch env I get a ModuleNotFoundError: No module named 'sqlalchemy' but sqlalchemy is indeed installed

BTW. Re venv - you should be able to run the test in venv created with `pip install -e ".[dbt.cloud,devel-tests]" - that should install all what is needed to run the tests.

**Pull request merged**
