### PR TITLE
[AIRFLOW-823] Allow specifying execution date in task_info API

### PR DESCRIPTION
**Pull request by robin-miller-ow**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-823

Testing Done:
- Unittests added to cover this code change.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@robin-miller-ow I think this is the wrong approach to make the change. A DAG does not have an execution date, but a DagRun does. A Task does not have an execution_date but a TaskInstance does by inheriting it from the DagRun.

So I would expect:
`/dags/<string:dag_id>/<datetime:execution_date>/tasks/<string:task_id>`

to return the information you are looking for.

**Comment by robin-miller-ow** [comment]
@bolkedebruin That seems inconsistent to me. When I added a date into the tigger dag API, you said it should be sent in the data, not the URL, so I presume we'd still want to do that. If this is not the right URL, then based on the trigger dag URL, would:
`/dags/<string:dag_id>/dag_runs/task_instance/<string:task_id>`
be more consistent? Possibly:
`/dags/<string:dag_id>/dag_runs/<datetime:execution_date>/task_instance/<string:task_id>`
but I would then expect the be posting to
`/dags/<string:dag_id>/dag_runs/<datetime:execution_date>`
to create a dag run at a specific time. Thoughts?

**Comment by bolkedebruin** [comment]
@robin-miller-ow that is actually unrelated: GET vs POST. So no that is not more consistent

**Comment by robin-miller-ow** [comment]
@bolkedebruin I think this is now as you would like. Please let me know if there are any further issues.

**Comment by bolkedebruin** [comment]
LGTM

**Pull request closed without merging**
