### PR TITLE
Add pre-commit check to check integrations table.

### PR DESCRIPTION
**Pull request by timonviola**
Add pre-commit check to check if integrations and TESTING documentation are synchronized.
---
The new pre-commit test:
- reads `integration-*.yml` files
- reads the table of integrations in `TESTING.rst`
- compares the two lists and fails if they are not synced.

### CODE REVIEW

**Comment by timonviola** [comment]
@potiuk Could you give some first feedback on this?

Particularly, I am not sure about **auto generating** the table, as the description part is missing. Could the description be pulled from the `yml` files?

**Comment by potiuk** [comment]
> Particularly, I am not sure about auto generating the table, as the description part is missing. Could the description be pulled from the yml files?

Generally looks cool. We do not have descriptions yet. But we can possibly also already improve the `integration-*.yml" files and add description there (and read it from there)

See: https://docs.docker.com/compose/compose-file/compose-file-v3/#reference-and-guidelines - you could add "labels"  and we could standardize to use `breeze.description` label for it (you can also add version as well to all the integration compose files -  I tihnk "3.8" seems to make most sense as it is "19.03.0+" and we are already "24.0.0+".

```yaml
version: "3.8"
services:
  kafka:
    image: ....
    labels:
      breeze.description: "This label will appear on all containers for the web service"
```

As a follow-up we could update "version" and "labels" for other files (for airflow service we only need to set label for "base.yml".

**Comment by timonviola** [comment]
@potiuk Thank's for the feedback, pushed 2 commits, which should cover it.

> As a follow-up we could update "version" and "labels" for other files (for airflow service we only need to set label for "base.yml".

I did not change the base.yml in this PR as it is not part of `integrations-*.yml`

Maybe this is what you meant, but would it make sense to create another PR for standardizing `breeze.description`? 
- Add a hook, which checks whether `breeze.description` exists and 
- add `breeze.description` to other files as well e.g. `base.yml`?

**Review by potiuk — APPROVED** [review]
❤️ it

**Comment by potiuk** [comment]
> Maybe this is what you meant, but would it make sense to create another PR for standardizing breeze.description?

> Add a hook, which checks whether breeze.description exists and
add breeze.description to other files as well e.g. base.yml?

Yep. Absolutely. Separate PR, And having pre-commit to check it is a good idea :)

**Comment by potiuk** [comment]
Some other pre-commits need to be run and fixed :). 

I highly recomment `pre-commit install` - and then you do not have to even think about it

**Comment by potiuk** [comment]
Cool !

**Pull request merged**
