### PR TITLE
Refactor: Simplify code in providers/amazon

### PR DESCRIPTION
**Pull request by eumiro**

### CODE REVIEW

**Review by vincbeck — APPROVED** [review]

**Comment by ferruzzi** [comment]
I got half way through reviewing it last night and was going to finish this afternoon.    Ah well.   :P  Thanks for the cleanup!

**Comment by o-nikolas** [comment]
> I got half way through reviewing it last night and was going to finish this afternoon. Ah well. :P Thanks for the cleanup!

@ferruzzi I think another pass can't hurt, if you find something then we can always fix it in a follow-up PR. I'm not sure the goal of this PR, since there's no description, but there is a large surface area of code/logic changing here, something can easily slip in with those types of PRs!

**Comment by potiuk** [comment]
> @ferruzzi I think another pass can't hurt, if you find something then we can always fix it in a follow-up PR. I'm not sure the goal of this PR, since there's no description, but there is a large surface area of code/logic changing here, something can easily slip in with those types of PRs!

I did a pass too. Could not see anything odd. FYI @o-nikolas -> this is a series of cleanups that @eumiro is apparently on a quest of - he had one huge PR to improve some of our less-than-ideal code snippets and I asked him to break it into series of smaller PRs focused on "common" areas  - this one is the "aws" provider one.

**Comment by vincbeck** [comment]
Sorry If I merged too fast folks, I did not see anything odd and everything made sense to me. I'll be more patient next time :)

**Pull request merged**
