### PR TITLE
Fix case of GitHub

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by potiuk** [comment]
We had a temporary issue with cancelling too many jobs. Can you please rebase to latest master? It should be fixed now.

**Comment by turbaszek** [comment]
@jbampton was this fixed in the whole codebase?

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
@jbampton Looks like `./breeze` needs updating too -- the help comes out of those so is being force to be in sync.

**Comment by jbampton** [comment]
Hey @potiuk this is ready for review 👍

**Comment by potiuk** [comment]
Ah GREEN!

**Review by potiuk — APPROVED** [review]

**Pull request merged**
