### PR TITLE
[AIRFLOW-XXXX] Add pre-commit check for utf-8 file encoding

### PR DESCRIPTION
**Pull request by feluelle**
Note: From Python 3.x onwards the explicit utf-8 header is no longer required. It is utf-8 encoded by default.

---
Issue link: `Document only change, no JIRA issue`

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by feluelle** [comment]
Related to #7338

**Comment by mik-laj** [comment]
I want to do it using pyupgrade: https://github.com/apache/airflow/pull/7343 I don't know if we want to duplicate tools that do the same.

**Comment by potiuk** [comment]
I think we can add it for now and replace with pyupgrade when it's ready. Pyupgrade has more things that it fixes but I see no problem with adding it now especially that it is built-in in one of the repos we have now.

**Comment by potiuk** [comment]
However we should exclude vendor files from this for sure

**Review by potiuk — CHANGES_REQUESTED** [review]
As mentioned - for now it's a good solution especially that encodings were added in few files in the meantime. But _vendor should be excluded - similarly as for the other checks.

**Comment by mik-laj** [comment]
I don't know if adding magic comments with coding is a problem that is worth solving.  It seems to me that if someone adds this comment it does not cause serious problems and we do not need a temporary solution.  Instead of developing a temporary solution for a maximum of 2 weeks, you can make other contributions. I am not against this change. If you decide to finish it, I will gladly accept it. I just wanted to show the wider context of my change. Deleting the magic of comments is only an intermediate step, but it is not my goal.

**Comment by potiuk** [comment]
I think discussing it now took more time than implementing it :). I am all for intermediate solutions if they are super-simple to implement.

**Comment by potiuk** [comment]
I think you need to apply the precommit in the next push @feluelle !

**Comment by feluelle** [comment]
True. 🤦‍♂

**Comment by feluelle** [comment]
That should do it! ..now I think we should get this thing quickly merged as soon as it passes to avoid further rebases :P

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @feluelle !

**Pull request merged**
