### PR TITLE
[AIRFLOW-1892] Modified BQ hook to extract data filtered by column

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1892

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

Added 'selected_fields' parameter to 'get_tabledata()' method in BigQuery hook to extract data for selected columns.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Google doesn't provide local unit test for GCS.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @criccomini @jgao54

**Comment by criccomini** [comment]
Looks like a flake8 failure:

```
airflow/contrib/hooks/bigquery_hook.py:651:91: E501 line too long (97 > 90 characters)
                      max_results=None, selected_fields=None, page_token=None, start_index=None):
                                                                                          ^
ERROR: InvocationError: '/home/travis/build/apache/incubator-airflow/scripts/ci/flake8_diff.sh'
```

Please fix

**Comment by kaxil** [comment]
@criccomini resolved

**Comment by criccomini** [comment]
Thanks! Waiting on clean build, and will merge.

**Comment by kaxil** [comment]
@criccomini Passed all the tests

**Comment by criccomini** [comment]
LGTM merged

**Pull request closed without merging**
