### PR TITLE
Prepare to release a new wave of providers.

### PR DESCRIPTION
**Pull request by potiuk**
For the regular providers, Vast majority is in `1.0.1` version and it is
only documentation update - but this way we will have a consistent set
of documentation (including commit history) as well as when we release
in PyPI, the READMES will be much smaller and link to the documentation.

We have two new providers (version 1.0.0):

* neo4j
* apache.beam

There are few providers with changes:

Breaking changes (2.0.0)

* google
* slack

Feature changes (1.1.0):

* amazon
* exasol
* http
* microsoft.azure
* openfaas
* sftp
* snowflake
* ssh

There were also few providers with 'real' bugfixes (1.0.1):

* apache.hive
* cncf.kubernetes
* docker
* elasticsearch
* exasol
* mysql
* openfaas
* papermill
* presto
* sendgrid
* sqlite

The ''backport packages" documentation is prepared only for those
providers that had actual bugfix/features/breaking changes:

```
amazon apache.hive cncf.kubernetes docker elasticsearch exasol google
http microsoft.azure mysql openfaas papermill presto sendgrid sftp
slack snowflake sqlite ssh
```

Only those will be generated with `2021.2.5` calver version.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @ashb @kaxil  As discussed before, I've used the provider generation scripts to prepare changelogs and generate documentation for the providers - both `regular` ones and the `backport` ones.

For the regular providers, I prepared release for all of them, Vast majority is in `1.0.1` version and it is only documentation update - but this way we will have a consistent set of documentation (including commit history) as well as when we release in PyPI, the READMES will be much smaller and link to the documentation. 

There are few providers with changes: 

Breaking changes (2.0.0): 

* google 
* slack 

Feature changes (1.1.0):

* amazon
* snowflake
* microsoft.azure
* exasol
* openfaas
* ssh
* http

There were also few providers with 'real' bugfixes (1.0.1):

* papermill
* presto
* docker
* mysql
* sqlite
* exasol 
* cncf.kubernetes
* openfaas
* apache.hive
* sendgrid
* elasticsearch

I prepared the ''backport packages" documentation only for those providers that had actual bugfix/features/breaking changes:

slack google amazon snowflake microsoft.azure exasol openfaas ssh http papermill presto docker mysql sqlite exasol cncf.kubernetes openfaas apache.hive sendgrid elasticsearch`

Only those will be generated with `2021.2.5` calver version.

**Review by kaxil — APPROVED** [review]

**Review by turbaszek — APPROVED** [review]

**Comment by potiuk** [comment]
Cool. One more change from @mik-laj completing the last currently possible google API upgrade to 2.0 (#13801), then I will regenerate this one then and release providers RCs finally!

**Comment by potiuk** [comment]
Waiting for https://github.com/potiuk/airflow/actions/runs/535267816 to succeed from my fork and relese the providers :crossed_fingers:

**Comment by potiuk** [comment]
Looks like it passes the docs builds, So i am merging it and prepare the providers  rc

**Pull request merged**
