### PR TITLE
fix changelog of common-io

### PR DESCRIPTION
**Pull request by eladkal**

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
Now it fails because common.io had no tests at all (side effect of our missing test detection being broken as captured in #35442 . Added test in #35457

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
The most difficult one-line-documentation-fix PR ever :D . Required some 3 PRs to pass the tests 

:scream:  :scream_cat:

**Comment by eladkal** [comment]
> The most difficult one-line-documentation-fix PR ever :D . Required some 3 PRs to pass the tests
> 
> 😱 🙀

I have unique skill to find the edge case of the edge case :)

**Comment by potiuk** [comment]
> > The most difficult one-line-documentation-fix PR ever :D . Required some 3 PRs to pass the tests
> > 😱 🙀
> 
> I have unique skill to find the edge case of the edge case :)

But yeah. Thanks to that we have all the edge-cases fixed now. Keep on doing it.

**Pull request merged**
