### PR TITLE
[AIRFLOW-2800] Remove low-hanging linting errors

### PR DESCRIPTION
**Pull request by andscoop**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

I am willing to create a JIRA issue, but this is just a code quality fix PR and that seems excessive

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR reduces `flake8 airflow` from 466 to 266 errors mostly through resolving of 

- E226
- W291

as well as __some__ E501 (line too long) where it did not risk reducing readability

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Only fixes flake8 errors

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

It does not pass as there are other linting errors on some of the files I touched that I was not comfortable changing at this time.

### CODE REVIEW

**Comment by andscoop** [comment]
This is failing due to existing linting errors on files I touched. It still results in a reduction of linting errors by over 40%. (200 resolved errors).

**Comment by Fokko** [comment]
Thanks @andscoop.

Can you adhere to the commit guidelines and create a ticket? I know this feels a bit unnecessary, but it is for keeping track of the changes for the releases. Cheers

**Comment by andscoop** [comment]
@Fokko issue created and commit updated

**Comment by Fokko** [comment]
Thanks @andscoop the test still fails on a few Flake8 violations, mind picking up these as well?

```
Running flake8 on the diff in the range f3b6b60c..aba6120b (1 commit(s)):
--------------------------------------------------------------------------------
airflow/jobs.py:1095:21: E128 continuation line under-indented for visual indent
                    DR.execution_date == TI.execution_date))
                    ^
airflow/jobs.py:1268:30: E711 comparison to None should be 'if cond is None:'
                or_(TI.state == None, TI.state.in_(acceptable_states))
                             ^
airflow/www/validators.py:49:33: E131 continuation line unaligned for hanging indent
                                or self.fieldname,
                                ^
airflow/www/validators.py:49:33: W503 line break before binary operator
                                or self.fieldname,
                                ^
ERROR: InvocationError for command '/home/travis/build/apache/incubator-airflow/scripts/ci/flake8_diff.sh' (exited with code 1)
```

**Comment by r39132** [comment]
@andscoop do you mind rebasing? Thanks for taking this up. Once rebased, I can merge.

**Comment by andscoop** [comment]
@r39132 done - thanks

**Comment by r39132** [comment]
Cool. Running `flake8 airflow | wc -l` on master and this PR branch, I see a decrease from `458` down to `235`!

Thanks for making these changes.

**Pull request merged**
