### PR TITLE
[AIRFLOW-2851] Canonicalize "as _..." etc imports

### PR DESCRIPTION
**Pull request by tedmiston**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2851
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR:

1. Replaces `import foo as _foo` style imports with the more common `import foo` used everywhere else across the codebase.  I dug through history and couldn't find special reasons to maintain the as style imports here (I think it's just old code).  Currently (33dd33c89d4b6454d224ca34bab5ae37fb9812a6), there are just a handful of import lines using `as _...` vs thousands not using it, so the goal here is to improve consistency.

2. It also simplifies `import foo.bar as bar` style imports to equivalent `from foo import bar`.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Coverage by existing tests.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
Thanks @tedmiston  for fixing that. I wonder if @mistercrunch knows the initial reason behind using the original import style.

**Review by Fokko — APPROVED** [review]
I really like this

**Comment by tedmiston** [comment]
Thank you both for the review and initial comments!  It sounds like the next step here is probably to get a quick thought from Max when he has a chance.

**Comment by mistercrunch** [comment]
I'm unclear as to why contributors went around their way to alias imports, but it appears to be 100% unnecessary. `git blame` show @kaxil as one of the people doing this on `_os`.

**Comment by kaxil** [comment]
@mistercrunch 🤔 I might have definitely done it on `gcs_hook`. Sorry about that. Not sure if I ever used `_os`.

**Pull request merged**
