### PR TITLE
Enable specifying dictionary paths in `template_fields_renderers`

### LINKED ISSUE #17032: Improved SQL rendering within BigQueryInsertJobOperator
**Description**

`BigQueryInsertJobOperator` requires the submission of a `configuration` parameter in the form of a dict.  Unfortunately, if this contains a large SQL query - especially one that is formatted with new lines - then this cannot currently be rendered very nicely in the UI.

Screenshot 2021-07-15 at 15 39 33

**Use case / motivation**

The issue with this is that it's impossible to copy and paste the rendered query out of the Airflow UI, into a BigQuery browser and run it without lots of manual edits which is time wasted when troubleshooting problems.

**Are you willing to submit a PR?**

Yes.  My current thought process around this would be to add an optional SQL parameter to the operator which, if provided, would be added into the configuration and could therefore have its own template field and SQL renderer.

e.g.

Screenshot 2021-07-14 at 14 18 09

### PR DESCRIPTION
**Pull request by nathadfield**
Closes: #17032 

`BigQueryInsertJobOperator` requires the specification of a configuration dict but, at present, this results in poor SQL rendering; especially if the queries are big or complex.

### Current Example

125806943-839d57a9-d4a0-492d-b130-06432b095239

This PR attempts to implement the capability for specific elements of a dictionary provided to an operator to be rendered individually with the appropriate renderer.

For example, when the following configuration is submitted to `BigQueryInsertJobOperator` then, in addition to the JSON rendering of `configuration` the provided SQL should be separately rendered.

```
sql = '''
INSERT INTO `target_project.target_dataset.target_table`
(col1, col2, col3, col4)
SELECT col1, col2, col3, col4
FROM `source_project.source_dataset.source_table`
'''

test = BigQueryInsertJobOperator(
    task_id='test',
    gcp_conn_id='my_gcp_connection',
    configuration={"query": {"query": sql,
                             "destinationTable": {"projectId": 'my_project',
                                                  "datasetId": 'my_dataset',
                                                  "tableId": 'my_table'},
                             "writeDisposition": 'WRITE_TRUNCATE',
                             "useLegacySql": False}
                   }
)
```

To achieve it, this PR enables any operator to receive a dot-separated path from `template_field_renderers` along with the renderer type.  In this case we want `BigQueryInsertJobOperator` to extract the value from `configuration` dict where the key path is `query.query`.  This is fully represented as follows:

 `template_fields_renderers = {"configuration": "json", "configuration.query.query": "sql"}`

When building the rendered page, we check if the content is a dict - e.g. `configuration` - then, if so, return a generator object that yields every possible path of keys (`get_key_paths`) in the form `key1.key2.key3...keyX`. 

Using this we can then check to see if any of these paths match with what we have in `template_field_renderers` and, if so, what the renderer is.  If it is a valid renderer then we can use that path to retrieve the value from the configuration (`get_value_from_path`).

```
if isinstance(content, dict):
    for dict_keys in get_key_paths(content):
        template_path = '.'.join((template_field, dict_keys))
        renderer = task.template_fields_renderers.get(template_path, template_path)
        if renderer in renderers:
            content_value = get_value_from_path(dict_keys, content)
            html_dict[template_path] = renderers[renderer](content_value)
```

The result of this is a rendered page which looks like the following:

Screenshot 2021-07-26 at 14 51 48

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
so. Let the competition begin @nathadfield @mehmax :) #17239 :D

**Comment by nathadfield** [comment]
@potiuk Yes.  It seems my PR it is bit more targeted in scope as it focuses on enabling specific elements of a dict to be individually rendered.

**Comment by mehmax** [comment]
@nathadfield I like this a lot. Is there a chance to apply the rendering without specifying `template_field_renderers ` in the Operator Class?

Especially when using decorated tasks or python operators, I like to use the unmodified version of the PythonOperator, where `template_field_renderes` are not specified.

E.g. 
my dag looks like this

```
with DAG('infor_staging_material_v2.0', 
	default_args=default_args,
	schedule_interval='25 6 * * *',
    catchup=False,
    template_searchpath='/airflow/home/airflow/sql'
    ) as dag:

    @task(default_args=default_args, templates_exts=['.sql'])
    def extract(src_odbc_conn_id : str, dest_odbc_conn_id : str, dest_table : str, sql : str, **kwargs):
         src_odbc_hook = OdbcHook(src_odbc_conn_id)
         dest_odbc_hook = OdbcHook(dest_odbc_conn_id)

         df = src_odbc_hook.get_pandas_df(sql)
         df.to_sql(dest_table, con=dest_odbc_hook.get_sqlalchemy_engine())

    t1extract = extract(
        src_odbc_conn_id='SOURCE', 
        dest_odbc_conn_id='DESTINATION', 
        sql='SQLSCRIPT.sql',
        dest_table='material'
        )

```

all of the parameters are collected into op_kwargs, and I would like to prevent specifying
```
op_kwargs.sql
op_kwargs.dest_table
```

as `template_field_renderes` in the _PythonDecoratedOperator class

**Comment by nathadfield** [comment]
@mehmax Yeah, I reckon that would be possible.  Let me have a go.

**Comment by nathadfield** [comment]
@mehmax I can modify `view.py` again to look for a template field  equal to 'op_kwargs' if content is a dict.  We can also look at the keys in `op_kwargs` to see if they match any existing renderers (e.g. `sql`) otherwise we default to `py` (or something else?).

```
if isinstance(content, dict):
    if template_field == 'op_kwargs':
        for key, value in content.items():
            renderer = task.template_fields_renderers.get(key, key)
            if renderer in renderers:
                html_dict[key] = renderers[renderer](value)
            else:
                html_dict[key] = renderers['py'](value)
    else:
        for dict_keys in get_key_paths(content):
            template_path = '.'.join((template_field, dict_keys))
            renderer = task.template_fields_renderers.get(template_path, template_path)
            if renderer in renderers:
                content_value = get_value_from_path(dict_keys, content)
                html_dict[template_path] = renderers[renderer](content_value)
```

Then if specify this in the DAG:

```
@task(default_args=default_args, templates_exts=['.sql'])
def extract(src_odbc_conn_id: str, dest_odbc_conn_id: str, dest_table: str, sql: str, **kwargs):
    src_odbc_hook = OdbcHook(src_odbc_conn_id)
    dest_odbc_hook = OdbcHook(dest_odbc_conn_id)

    df = src_odbc_hook.get_pandas_df(sql)
    df.to_sql(dest_table, con=dest_odbc_hook.get_sqlalchemy_engine())

sql = '''
INSERT INTO `target_project.target_dataset.target_table`
(col1, col2, col3, col4)
SELECT col1, col2, col3, col4
FROM `source_project.source_dataset.source_table
WHERE dt = {{ ds }}`
'''.strip()

t1extract = extract(
    src_odbc_conn_id='SOURCE',
    dest_odbc_conn_id='DESTINATION',
    sql=sql,
    dest_table='material'
)
```

This is how it gets rendered.

Screenshot 2021-07-27 at 12 31 06

Thoughts?

Anything from you @potiuk?

**Comment by nathadfield** [comment]
@potiuk  I noticed the test failures here but they seems unrelated to these changes.  I ran the static checks locally but didn't get the error and I can't quite understand what the Postgres error is.

I've got the above potential addition to commit so everything will run again but can you advise if there's anything that I need to look at with regard to these test failures?

**Comment by nathadfield** [comment]
@mehmax How does this further addition to `views.py` look?  Does it achieve what you would like?

**Comment by mehmax** [comment]
@nathadfield let me look into this today or tomorrow. I am quite busy currently

**Comment by nathadfield** [comment]
@mehmax No problem.  In your own time.

**Comment by nathadfield** [comment]
@mehmax The PR for this is now here #17321

**Pull request closed without merging**
