### PR TITLE
[AIRFLOW-XXX] Add task lifecycle image to documentation

### PR DESCRIPTION
**Pull request by kaverisharma09**
Jarek Potiuk (potiuk@) and Kamil Breguła (mik-laj@) helped me to finalise this and Viktoria Nemkin (nemkin@) helped with using Github.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
Screenshot 2019-12-09 at 14 59 54

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason: Change is only in documentation.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by nemkin — APPROVED** [review]
Great diagram! :)

**Review by potiuk — APPROVED** [review]
Nice !

**Comment by potiuk** [comment]
@KKcorps -> maybe you can take a look as well ? WDYT

**Comment by mik-laj** [comment]
Can you also update the description under the image? We should add information about scheduled state.

**Comment by KKcorps** [comment]
It looks good. A suggestion from my end will be that A state transition diagram should consist of only states. The part such as Scheduler, Executor, and Worker should be indicated either on the connections or not at all.
Also, would it make sense to include what happens when you press Clear?

**Comment by mik-laj** [comment]
@KKcorps This is not a state diagram but lifecycle diagram for the task Information about the components is key. It is also not necessary to add additional states if they do not fall into the standard task life cycle. In any case, you can mark a task as empty, successful or unsuccessful.  This makes it very difficult to understand the diagram.

**Comment by KKcorps** [comment]
Ok then let's leave components as they are for now.
But can we do two things
Add a legend that indicates what blue boxes, white boxes, solid arrows, and dotted arrows imply
Change the name of the file,  there's already a task_lifecycle.png in the img directory.

**Comment by nemkin** [comment]
image

New look.

**Review by mik-laj — APPROVED** [review]

**Comment by KKcorps** [comment]
Looks great!

**Comment by yuqian90** [comment]
Hi @kaverisharma09 and @mik-laj  I'm adding a new state in https://github.com/apache/airflow/pull/16681 and thus need to update this diagram? May I know what tool you used to create the diagram? I guess we may want to keep the style of the diagram consistent so I'm trying use the same tool as you did.

**Comment by mik-laj** [comment]
I'm afraid this was not made by any diagram drawing tool, but a vector editor was used e.g. Corel Draw, Inkscape or other similar.

**Comment by potiuk** [comment]
Possibly you can re-do it - what I use our ASF confluence for that - there you can use the drawing capability available there for free (and online) - see for example: https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-23+Migrate+out+of+Travis+CI - I edit images there and export it as .png files. We also have some automated .mermaid diagrams that are automatically generated from markdown-like description (but it is useful for simple diagrams): https://github.com/apache/airflow/tree/main/images/ci.

**Comment by kaxil** [comment]
> Hi @kaverisharma09 and @mik-laj I'm adding a new state in #16681 and thus need to update this diagram? May I know what tool you used to create the diagram? I guess we may want to keep the style of the diagram consistent so I'm trying use the same tool as you did.

Upload images to https://cwiki.apache.org/confluence/display/AIRFLOW/File+lists if you plan to use Draw.io or Lucid chart.

**Comment by kaverisharma09** [comment]
I created this using sketch <https://www.sketch.com/>.
I can send an updated version if you let me know what the requirements are.
Although it might be best to recreate the diagram using any of the tools
Jarek suggested so that you have an editable diagram for the future.

**Comment by potiuk** [comment]
> Upload images to https://cwiki.apache.org/confluence/display/AIRFLOW/File+lists if you plan to use Draw.io or Lucid chart.

+1. I think the confluence-embedded images are `draw.io` ones.

**Comment by yuqian90** [comment]
@kaxil @potiuk @mik-laj @kaverisharma09 Thank you for your responses. In case you missed my comment, I've updated https://github.com/apache/airflow/pull/16681 with a new graph. I'll upload to https://cwiki.apache.org/confluence/display/AIRFLOW/File+lists once the PR is approved.

**Pull request merged**
