### PR TITLE
[AIRFLOW-XXX] Omit vendor packages from being covered by codecov

### PR DESCRIPTION
**Pull request by feluelle**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The `_vendor` packages contains modules that are not directly part of airflow itself. Because of that I think we don't have to check its code coverage.

For `example_dags` I think there is also no need to add tests to.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by mik-laj** [comment]
I working on tests for example dags
https://github.com/PolideaInternal/airflow/pull/83
https://github.com/PolideaInternal/airflow/pull/77

**Comment by feluelle** [comment]
Oh, I see. So you think we should keep the coverage for example_dags?

BTW the automatic code ingestion in the docs looks awesome 👍

**Review by KevinYang21 — APPROVED** [review]

**Comment by KevinYang21** [comment]
Think it is nice to include exampels if we have 100% coverage there but don't think that is strictly needed.

**Comment by Fokko** [comment]
I know that (at least some) DAGs are used in the tests, but having coverage would be nice here. I'm not really interested in artificially increasing the code coverage, as I strongly believe it is a vanity metric.
I do think we need to exclude `airflow/_vendor/*`.

**Comment by feluelle** [comment]
I think @Fokko is right actually. Moreover @mik-laj did already add tests for the example dags.

I change this PR to only exclude vendor packages.

**Comment by Fokko** [comment]
@feluelle Did you push? I still see the exclusions of the dags folders.

**Comment by feluelle** [comment]
@Fokko I didn't had time. I did now (and rebased onto master).

**Comment by Fokko** [comment]
Thanks @feluelle

**Pull request merged**
