### PR TITLE
Cleanup of build-image scripts

### PR DESCRIPTION
**Pull request by potiuk**
This PR re-arranges tags int GitHub actions to be more explicit in
the pull/build/push steps on which tag of the image is currently
pulled/pushed/built.

Previously the actual configuration of those steps was determined
by combining "top", "job" and "step" variables, but that gave
little insight on what combinations of evn variables was used in
the step eventually. After this change, in all the pull/push/build
steps you can see what environment is used for that build.

Also, since we often build and push and then pull the same image in
the same workflow, the PUSH tag was sometimes used in PULL
variable as input. We change it now by introducing single
`IMAGE_TAG_FOR_THE_BUILD` which will be used as PUSH and PULL
tag as needed.

This one also fixes failure of PROD cache builds which did not
pull the right CI image.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Nice cleanup of actions :)

**Comment by potiuk** [comment]
(Another prerequisite for removing some bash code from old Breeze)

**Review by eladkal — APPROVED** [review]

**Comment by eladkal** [comment]
it has some conflicts

**Comment by potiuk** [comment]
Yep. Needs rebase

**Comment by potiuk** [comment]
Wooho!!!!!

We have finally fully green main build which prepared all the refreshed multi-platform cache for all the images - fully automatically and using ARM hardware instances started and stopped automatically (I observed it when running)

https://github.com/apache/airflow/actions/runs/2089074376 

The 3.9 and 3.10 images have not been refreshed recently due to some ARM instance maintenance script problems. But with that one they got refreshed and looks like the cache works nicely now.

This makes our cache "eventually consistent". 

As long as there will be a "green" main build merged and enought time to run the tests and build images, the cache should efficiently and automatically refresh itself.

I hope this will be self-maintaining in the future.

**Pull request merged**
