### PR TITLE
 gitpodify Apache Airflow - online development workspace

### PR DESCRIPTION
**Pull request by j143**
At present, configuration startups up the ide
with `./breeze -y` for setting up breeze environment.

**How to test?**

Visiting the link
[https://gitpod.io/#https://github.com/`apache/airflow/pull/16498`](https://gitpod.io/#https://github.com/apache/airflow/pull/16498) would fire up the online ready to code workspace.

**Terminals:**

image

**Testing:**

  <details>
  <summary><code> pytest tests/core/test_core.py::TestCore::test_check_operators</code></summary>

```console
root@d143c0ff1e51:/opt/airflow# pytest tests/core/test_core.py::TestCore::test_check_operators
================================= test session starts ==================================
platform linux -- Python 3.6.13, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /opt/airflow, configfile: pytest.ini
plugins: httpx-0.12.0, cov-2.12.0, requests-mock-1.9.3, celery-4.4.7, forked-1.3.0, instafail-0.4.2, xdist-2.2.1, rerunfailures-9.1.1, flaky-3.7.0, timeouts-1.2.1
setup timeout: 0.0s, execution timeout: 0.0s, teardown timeout: 0.0s
collected 1 item                                                                       

tests/core/test_core.py::TestCore::test_check_operators 
PASSED                   [100%]

=================================== warnings summary ===================================
tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/importlib/__init__.py:126: DeprecationWarning: This module is deprecated. Please use `airflow.providers.tableau.hooks.tableau`.
    return _bootstrap._gcd_import(name[level:], package, level)

tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/dns/hash.py:25: DeprecationWarning: dns.hash module will be removed in future versions. Please use hashlib instead.
    DeprecationWarning)

tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/eventlet/green/OpenSSL/__init__.py:6: DeprecationWarning: OpenSSL.tsafe is deprecated and will be removed
    from . import tsafe

tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/alembic/ddl/sqlite.py:44: UserWarning: Skipping unsupported ALTER for creation of implicit constraintPlease refer to the batch mode feature which allows for SQLite migrations using a copy-and-move strategy.
    "Skipping unsupported ALTER for "

tests/core/test_core.py::TestCore::test_check_operators
tests/core/test_core.py::TestCore::test_check_operators
tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/flask_caching/__init__.py:241: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.
    category=DeprecationWarning,

tests/core/test_core.py::TestCore::test_check_operators
tests/core/test_core.py::TestCore::test_check_operators
tests/core/test_core.py::TestCore::test_check_operators
tests/core/test_core.py::TestCore::test_check_operators
  /usr/local/lib/python3.6/site-packages/marshmallow/fields.py:201: RemovedInMarshmallow4Warning: Passing field metadata as a keyword arg is deprecated. Use the explicit `metadata=...` argument instead.
    RemovedInMarshmallow4Warning,

tests/core/test_core.py::TestCore::test_check_operators
  /opt/airflow/tests/core/test_core.py:102: DeprecationWarning: This class is deprecated.
              Please use `airflow.operators.sql.SQLCheckOperator`.
    task_id='check', sql="select count(*) from operator_test_table", conn_id=conn_id, dag=self.dag

tests/core/test_core.py::TestCore::test_check_operators
  /opt/airflow/tests/core/test_core.py:113: DeprecationWarning: This class is deprecated.
              Please use `airflow.operators.sql.SQLValueCheckOperator`.
    dag=self.dag,

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== 1 passed, 15 warnings in 37.48s ============================
```

</details>

**Problems encountered:**

1. "Error response from daemon: driver failed programming external connectivity on endpoint" while running `./breeze --integration mongo`

2. Which ports should be open to public/private ? (suggestions please.)
image

Related: #16480

### CODE REVIEW

**Comment by j143** [comment]
Hi @potiuk - Could you help me, with objectives this feature should address?

**Comment by potiuk** [comment]
Would love to - but next week only. Having some private/family interruptions this week and do bare minimum. Hopefully next week  will be better (looks like)

**Comment by j143** [comment]
cc @potiuk , 😀

- is this the intended feature. 
- there are some errors - are they expected?
- Which ports are to be open?

Thanks, 
Janardhan

**Comment by potiuk** [comment]
Sorry, got some private distractions and was not as available as I would like. I should be able to send my thoughts by next week. Sorry to keep you waiting.

**Comment by j143** [comment]
Hi, Could you have a cursory check for now. Reviewing the screenshot!
 We will go for a deep pass later.

**Pull request closed without merging**
