### PR TITLE
Revert "Upgrade mypy to 0.991 (#28926)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 6ae0a80cbaf1d33343b763c7f82612b4522afc40.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
The #28926 was merged witth failing static checks and it breaks new PRs

**Comment by potiuk** [comment]
(Revert is temporary - we should bring it back likely after fixing the root cause)

**Review by o-nikolas — APPROVED** [review]

**Comment by potiuk** [comment]
Merging/ The "pyarrrow" warning is unrelated and will be handled in a separate PR in a moment (won't affect regular PRs, just main).

**Comment by potiuk** [comment]
cc: @ashb @Taragolis I think the #29468 and this reverted https://github.com/apache/airflow/pull/28926 should be squashed- happy to help to solve the stubgen problem if needed.

**Pull request merged**
