### PR TITLE
add dirrao to committer list

### PR DESCRIPTION
**Pull request by dirrao**
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ephraimbuddy — APPROVED** [review]

**Review by eladkal — DISMISSED** [review]
holding merge to check something

**Review by hussein-awala — CHANGES_REQUESTED** [review]
Committer is not the same as contributor, please check https://community.apache.org/newcommitter.html

**Comment by eladkal** [comment]
> Committer is not the same as contributor, please check https://community.apache.org/newcommitter.html

Yes we actually have it explained in
https://github.com/apache/airflow/blob/main/COMMITTERS.rst#committers-vs-maintainers

**Comment by eladkal** [comment]
Closing as to be added as committer you need to be invited by the PMC. You can find more information about contributor vs committer/maintainer in
https://github.com/apache/airflow/blob/main/COMMITTERS.rst#committers-vs-maintainers

**Comment by dirrao** [comment]
I am reopening this as per the invitation received from @potiuk.

**Review by hussein-awala — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
