### PR TITLE
full screen mode for logs

### PR DESCRIPTION
**Pull request by Abhishek-kumar-ISM**
related: https://github.com/apache/airflow/issues/33012

As asked in above issue, i have done part of showing full screen logs.

I have added a small icon above logs on right side
minised

When one clicks on it, it will maximize log screens as follows
maximised

When one clicks it again, then it will minimize log screen, and show normal screen.

### CODE REVIEW

**Comment by Abhishek-kumar-samsung** [comment]
@Adaverse @potiuk @Taragolis @eladkal @pierrejeambrun @bbovenzi @ryanahamilton @ashb

I have added an icon that can maximize or minimize the logs to full screen.

Please check and review.

**Comment by pierrejeambrun** [comment]
Hello,

Please don't @ directly people unless there is a specific reason to ping someone. Code owners are automatically asked for a review and most maintainers have subscribed to notifications and will be notified on each activity (PR/issue/dicussion/etc.). People will review in time.

Thank you for the PR, looking cool!

**Comment by Abhishek-kumar-samsung** [comment]
> Hello,
> 
> Please don't @ directly people unless there is a specific reason to ping someone. Code owners are automatically asked for a review and most maintainers have subscribed to notifications and will be notified on each activity (PR/issue/dicussion/etc.). People will review in time.
> 
> Thank you for the PR, looking cool!

Okay sorry, i was not aware about that.

**Comment by Adaverse** [comment]
This is same functionality as F11. The issue highlighted the need for bigger view for logs in GRID view. This screen will be removed in coming days. Correct me if I'm mistaken @bbovenzi

**Comment by bbovenzi** [comment]
> This is same functionality as F11. The issue highlighted the need for bigger view for logs in GRID view. This screen will be removed in coming days. Correct me if I'm mistaken @bbovenzi

That's right. I would avoid making changes to this logs page as it will almost certainly be removed in 2.8
But I'm happy to review any improvements to the logs in grid view.

**Comment by Abhishek-kumar-samsung** [comment]
> > This is same functionality as F11. The issue highlighted the need for bigger view for logs in GRID view. This screen will be removed in coming days. Correct me if I'm mistaken @bbovenzi
> 
> That's right. I would avoid making changes to this logs page as it will almost certainly be removed in 2.8 But I'm happy to review any improvements to the logs in grid view.

In grid view, if i add similar thing i.e maximising logs to full screen and minimising, will that be good

**Pull request closed without merging**
