### PR TITLE
Add guide for DataprocInstantiateInlineWorkflowTemplateOperator

### PR DESCRIPTION
**Pull request by NiloFreitas**
Added the example of DataprocInstantiateInlineWorkflowTemplateOperator in the documentation and example DAG

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Failing tests and static checks :(

**Comment by mik-laj** [comment]
Can you add a reference to this section in Python API reference docs?
https://github.com/apache/airflow/blob/fb6b2d1fee6af366a3311a8012eb35b8f665348a/airflow/providers/google/cloud/operators/bigquery.py#L126-L128

**Comment by NiloFreitas** [comment]
The Python API reference docs for the DataprocInstantiateInlineWorkflowTemplateOperator already has a reference (which is broken):

> .. seealso::
>         Please refer to:
>         https://cloud.google.com/dataproc/docs/reference/rest/v1beta2/projects.regions.workflowTemplates/instantiateInline

So you want me to replace it with this

>  .. seealso::
>         For more information on how to use this operator, take a look at the guide:
>         :ref:`howto/operator:DataprocInstantiateInlineWorkflowTemplateOperator`

Or fix the link with this reference?

> .. seealso::
>         Please refer to:
>         https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.workflowTemplates/instantiateInline

**Comment by mik-laj** [comment]
What do you think about fixing a link AND adding a new reference to our guide?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
It needs some fixes in the list of documentation left.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
