### PR TITLE
Resurface S3Log class eaten by rebase/push -f

### PR DESCRIPTION
**Pull request by artwr**
During my refactoring of utils, I rebased several times,
it seems however that the S3Log class was not ported to the new
utils structure. This PR fixes this.

Sorry @jlowin, I thought I had rebased correctly, but your class was eaten by a grue.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you add a test so it doesn't happen again?

**Comment by bolkedebruin** [comment]
:P

**Comment by artwr** [comment]
@bolkedebruin I would but I was waiting for https://github.com/airbnb/airflow/pull/1228 to be merged to copy and paste the GCS one.

**Comment by bolkedebruin** [comment]
Merged :)

**Pull request merged**
