### PR TITLE
Required Param requires None to be explicitly passed as default

### LINKED ISSUE #28940: Required `Param` requires `None` to be explicitly passed as default
### Apache Airflow version

2.5.0

### What happened

I have a dag like

```
import datetime

from airflow.models import Param
from airflow.models.dag import dag


@dag(
    dag_id="foo",
    schedule=None,
    params={'month': Param()},
    start_date=datetime.datetime.now()
)
def foo():
    pass


foo()

```

I am trying to pass this param via CLI. I tried passing it like 
```
airflow dags test foo --conf '{"month": "2022-01"}'
```

gives
```
Traceback (most recent call last):
  File "/Users/adam.amster/venvs/airflow/lib/python3.10/site-packages/airflow/models/dagbag.py", line 437, in _process_modules
    dag.validate()
  File "/Users/adam.amster/venvs/airflow/lib/python3.10/site-packages/airflow/models/dag.py", line 667, in validate
    self.params.validate()
  File "/Users/adam.amster/venvs/airflow/lib/python3.10/site-packages/airflow/models/param.py", line 230, in validate
    raise ParamValidationError(f"Invalid input for param {k}: {ve}") from None
airflow.exceptions.ParamValidationError: Invalid input for param month: No value passed and Param has no default value
```

# Note
Found out that you need to explicitly pass `None` as the default, otherwise it will crash with above.

### What you think should happen instead

`month` should be passed to the dag

### How to reproduce

_No response_

### Operating System

mac osx

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
Fixes: #28940. Tested using the same DAG.
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I think this is more than just a small change - the unit tests have to be updated (and added) to cover all cases and I am not sure yet - without looking-  what exactly was wrong and how it **SHOULD** be fixed, starting from unit tests and understanding them and adding more cases is the way to start working on it. 

@msumit  maybe you can also comment on that? I think you remember best the intentions here and what will be the best way forward.

**Comment by aamster** [comment]
It looks like if the param has no default, then this just sets the default to None. What happens if the param is not passed? In that case it should raise an exception.

**Comment by amoghrajesh** [comment]
@aamster I tried out by providing a default value to the dag too. It does not fail because it will not enter that bit of code which sets the final_val to `None` (https://github.com/apache/airflow/pull/28968/files#diff-b0191ca5420883beb9d9e84666aba91ef89dac76c83ada5a15fe286901e3c04dR94)

**Comment by amoghrajesh** [comment]
@msumit code wise, how do we know if the parameter is required or not?

**Comment by msumit** [comment]
IIRC the first value of the param is a default value (read [this](https://airflow.apache.org/docs/apache-airflow/stable/concepts/params.html)). So a Param with no default value is a required param.

**Comment by amoghrajesh** [comment]
Okay, @msumit.
So, if a param with no default value is a required param and we are trying to raise an exception if no default is provided for the param object. That is exactly the issue raised. Currently, without my change, Param throws an exception whenprovidedlt is provided aka None is not passed. 

Maybe i am not understanding the issue well, if possible could you list a few examples around what we are trying to achieve in the issue? 

Thanks in advance!

**Comment by msumit** [comment]
> Okay, @msumit. So, if a param with no default value is a required param and we are trying to raise an exception if no default is provided for the param object. That is exactly the issue raised. Currently, without my change, Param throws an exception whenprovidedlt is provided aka None is not passed.
> 
> Maybe i am not understanding the issue well, if possible could you list a few examples around what we are trying to achieve in the issue?
> 
> Thanks in advance!

Sorry @amoghrajesh I could not understand what are you trying to convey here and to whom your question is directed. But the issue seems valid while the fix is not.

**Comment by amoghrajesh** [comment]
If possible can someone state a few examples of valid vs invalid cases for more clarity?

**Comment by potiuk** [comment]
@aamster maybe you can provide some examples of what you think should happen here as the original author of the issue?

**Comment by aamster** [comment]
If a `Param` with no default value is given, passing the param in the `--conf` flag should satisfy that parameter. That use case is given in the original issue. Currently if it is passed, an exception is still raised. If the param is left out of `--conf`, the same exception that is currently raised should be raised. 

That is for the case of a simple param. It gets more complicated for a complex `object` type parameter.
For example

```
import datetime

from airflow.models import Param
from airflow.models.dag import dag
from airflow.decorators import task


@dag(
    dag_id="foo",
    schedule=None,
    params={
        'complex': Param(
            type='object',
            parameters={
                'foo': {
                    'type': 'number',
                    'default': 1
                },
                'bar': {
                    'type': 'number'
                }
            }
        )
    },
    start_date=datetime.datetime.now()
)
def foo():
    @task
    def my_task(**context):
        x = context['params']['complex']
        print(x)

    my_task()


foo()
```

In this case, `complex` has no default, but its property `foo` does. However its other property `bar` does not. In my opinion, the user must only pass a value for the property `bar` but not `foo`. I.e. the user can pass `{'complex': {'bar': 1}}` and it should work. Currently it does work, but the default value for `foo` is ignored, so `print(x)` above will print `{'complex': {'bar': 1}}` instead of  `{'complex': {'bar': 1, 'foo': 1}}` Even worse, the user can pass `'complex': {}` and no error is thrown. I know that there is the `required` argument for objects, but this seems redundant and confusing. Shouldn't it be able to figure out what is required by which properties lack a default value?

For the case of an `object` type param with all properties with a default value, no value should need to be passed for this param and it should take on the defaults for all values. 

I understand the above will get complicated with nested objects.

**Comment by amoghrajesh** [comment]
@potiuk @aamster thanks for the clarification. Had a doubt regarding the class structures. 
When we try running commands like:
```
 airflow dags test foo --conf '{"month": "2022-01"}'
```

1. What classes get initialised on adding the dag - is it Param?
2. What classes get initialised on calling the above method - is it `DagParam` with `ParamDict`? 
3. When does the `__setitem__` of ParamDict gets called?

**Comment by amoghrajesh** [comment]
@potiuk @aamster following up on my last comment

**Comment by potiuk** [comment]
> @potiuk @aamster following up on my last comment

I do not know by heart - I would have to go to details, and I think it's a good exercise to do if you want to make sure the fix works.

**Pull request closed without merging**
