### PR TITLE
Proper version is displayed when running prod image via Breeze

### PR DESCRIPTION
**Pull request by potiuk**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by potiuk** [comment]
Note that this is only applicable to production image. --install-airflow-version in CI works slightly differently. In production image it builds a new image. In CI image it installs airflow version in the original "2.0" image (uninstalls airflow 2.0 first). This is much faster and OK for testing. For production image - we really want to build the image in an optimal way so the image is rebuild using the version of airflow provided via --install-airflow-version flag.

**Comment by potiuk** [comment]
Hey @feluelle - can you double check if this works :) ?

**Review by feluelle — APPROVED** [review]
Works. Thanks @potiuk :)

**Comment by feluelle** [comment]
@potiuk That is really weird -> `$AIRFLOW_VERSION` shows `1.10.10` also `airflow version` shows `1.10.10` but endpoint `/version` shows `2.0.0`

1. `./breeze build-image --production-image --install-airflow-version=1.10.10`
2. `./breeze --production-image`
3. `airflow upgradedb`
4. `airflow webserver`
5. http://0.0.0.0:28080/version

**Comment by potiuk** [comment]
it is :). Looking at it

**Comment by potiuk** [comment]
Can you try the same with ``--skip-mounting-local-sources`` switch? I think this might be the reason and we might want to simply not mount "airflow" sources at all (the change I just approved and merged today).

**Comment by feluelle** [comment]
with `--skip-mounting-local-sources` I cannot reach the webserver probably because the compose file (local-prod) won't be used at all.

When I remove all `volumes` in the compose and run normally - it works :) `/version` shows `1.10.10`

**Comment by potiuk** [comment]
YEah. I think the reason was source mapping to inside the container. I left comment in #8228  to remove all the /opt/airflow mounts. This might be super-misleading if we leave them.

**Comment by potiuk** [comment]
Luckily I have not yet merged it so you can still fix it :)

**Comment by feluelle** [comment]
Will do - thanks for helping :)

**Pull request merged**
