### PR TITLE
Move dag's cli method out of DAG.

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
I wonder if it would be better to delete it. This was helpful when it was easy available, but that leads to a lot of problems.  The basic thing is that we have to support running DAGs that have not been loaded by DagBag, so we have to do many things when ``import airflow`` e.g. add new path to sys.path, loading plugins, etc.  If we do not prepare the environment while the airflow import is being done, loading the DAG File may fail.

**Comment by potiuk** [comment]
> I wonder if it would be better to delete it. This was helpful when it was easy available, but that leads to a lot of problems. The basic thing is that we have to support running DAGs that have not been loaded by DagBag, so we have to do many things when `import airflow` e.g. add new path to sys.path, loading plugins, etc. If we do not prepare the environment while the airflow import is being done, loading the DAG File may fail.

Maybe as a next move. For now I want to focus on deps.

**Comment by potiuk** [comment]
But If you want to remove it - feel free :)

**Comment by mik-laj** [comment]
We may think about it later. This change now needs an entry in UPDATING.md anyway.

**Pull request closed without merging**
