### PR TITLE
Rewire www-app to have a function to return an app

### PR DESCRIPTION
**Pull request by bolkedebruin**
@mistercrunch as discussed this is the rewiring of the www-app to support returning an app from a function. This is the first step to have the possibility to test multiple configurations on the web interface. Forms, blueprints, views have been put in their own respective module. I think this creates flexibility towards the future and in some cases it is required to get it functional (views). 

Caveats: 
- Tests pass, but I haven't been able to test the plugin functionality - no tests for it and no examples.
- instead of @app in views it is required to use @current_app registration needs to happen in app.py

Todo (in new PR):
- Rewire the configuration to make it possible to instantiate them
- Make it possible to pass the configuration to the app

Let me know if anything needs to be different!

### CODE REVIEW

**Comment by mistercrunch** [comment]
Ok I'll test this manually in our environment and see confirm that our plugins are working.

**Comment by bolkedebruin** [comment]
Thanks! That is appreciated. The other PR (for more flexible config) is ready when this is in

**Comment by bolkedebruin** [comment]
@mistercrunch did you have a chance to look at this? I have tested it with the metastore browser and it seems to work fine from a first glance.

**Comment by mistercrunch** [comment]
I just tested and it look fully compatible with our plugins

**Comment by bolkedebruin** [comment]
@jlowin you might want to double check if your s3 adjustments landed correctly, I had to port them manually.

**Comment by jlowin** [comment]
Thanks! Will look into it.

**Comment by jlowin** [comment]
@bolkedebruin appears to be there... what did you have to port?

**Pull request merged**
