### PR TITLE
[AIRFLOW-4472] Use json.dumps/loads for templating lineage data

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4472
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

jinja2 cannot use dict/lists as templates hence converting
it to json solves this while keeping complexity down.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Is covered.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
cc: @feng-tao 

This is a pre-requisite for the Papermill operator.

**Review by feng-tao — APPROVED** [review]

**Comment by ssYkse** [comment]
Hi!
This work, however for some reason is not part of the airflow 1.10.10 release (and earlier).
As it is merged into master, I assume it was lost somewhere in other merges.

**Comment by sankroh** [comment]
Can you guys release this please?

**Comment by Minutis** [comment]
Would like to see this one released too.

**Comment by potiuk** [comment]
I believe it was never meant to be released @kaxil @ashb  @bolkedebruin? I am not 100% sure as it has no tests, but I think this one gets rather deeply into the operator/context behaviour and it might have some  undesireable effects (on the other hand maybe it's better to cherry-pick it now because otherwise people might hit similar problems when migrating to 2.0)?

**Comment by bolkedebruin** [comment]
It's meant to be updated significantly. It's about 70% there and I need some time to finish it.

**Pull request merged**
