### PR TITLE
Cherry pick 3 9 support to v2 1

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
It was rather easy to cherry-pick that one - almost no conflicts and the ones that were there were only in elasticsearch (which is ignored in non-main branch) and in breeze/scripts. Since we have ~ 3 months to release 2.2, I think it's worth to merge it now. But if it will cause any problems, I am ok with doing it as part of 2.1.3 as well @jhtimmins @ashb

**Comment by potiuk** [comment]
Closed/reopened to trigger tests for all python versions

**Comment by ashb** [comment]
@potiuk I was trying to keep 2.1.2 as small as possible (to minimize testing and to only fix the regressions from 2.1.0), so my instinct is to wait on merging this until 2.1.2 is out, and then include this in 2.1.3 (due towards the end of this month).

**Comment by ashb** [comment]
That said, this has _no_ changes on core itself, so 👍🏻

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
Ah.  Ut will need to be merged to get 3.9 updated in v2-1-stable to actually run the 3.9 build. I will merge it and in case we find any problem we can revert it. I built it manually so it should be fine.

**Comment by potiuk** [comment]
Just to be fully sure of it before you wake up @jhtimmins  I am running it all in my fork from main: https://github.com/potiuk/airflow/actions/runs/1011392229 and https://github.com/potiuk/airflow/runs/3018362289

**Comment by potiuk** [comment]
Yep. There were some errors (seems that the public GitHub Runners are very unstable) but image building and some Py3.9 tests succeeded , so is should be good to go

**Pull request merged**
