### PR TITLE
[AIRFLOW-3391] Upgrade Pendulum to latest version

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3391
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Existing tests.

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
@bolkedebruin FYI, CI fails.

**Comment by dongli** [comment]
Looking forward this PR!

**Comment by dongli** [comment]
Any news?

**Comment by dongli** [comment]
We really need newer pendulum.

**Comment by feng-tao** [comment]
cc @bolkedebruin

**Comment by ashb** [comment]
@dongli You are welcome to take over the upgrade work and make a new PR that upgrades pendulum.

**Comment by impredicative** [comment]
@dongli To prevent this issue from blocking me, I switched to using [`arrow`](https://pypi.org/project/arrow/) instead for my DAGs as it is a competitive alternative to `pendulum`. Note that `arrow==0.15.2` is compatible with `apache-airflow==1.10.6`; it doesn't conflict with any preexisting requirements.

**Comment by redwanhuq** [comment]
anyone working on this pendulum upgrade?

**Pull request closed without merging**
