### PR TITLE
Fix render_template method name in plugin example

### PR DESCRIPTION
**Pull request by davidcaron**

### CODE REVIEW

**Comment by davidcaron** [comment]
Wow, not sure if it's something I'm doing, but I'm sorry for resquesting all these reviews! I thought it was the `gh` cli tool first...

**Review by kaxil — APPROVED** [review]

**Review by XD-DENG — COMMENTED** [review]
Thanks @davidcaron .

If you don't mind, may we extend the scope of this PR a little bit? I found that the same issue also exist in `tests/plugins/test_plugin.py`. It will be great if we also fix it there

**Comment by davidcaron** [comment]
@XD-DENG I'm... not sure which issue you are referring to (mind pointing me to it?), but while looking for it I found another place where `render` was used.

The confusion seems to comes from:

ok:
`flask_appbuilder.BaseView.render_template`
`flask_admin.BaseView.render`

not ok:
`flask_appbuilder.BaseView.render`

**Comment by XD-DENG** [comment]
Hi @davidcaron ! Sorry I think I made a mistake. I was at branch `v1-10-stable` when I checked the code and raised the question above ([the line I was talking about](https://github.com/apache/airflow/blob/v1-10-stable/tests/plugins/test_plugin.py#L80), if you are interested). It's not applicable in `master` branch. My bad, sorry for it!

**Review by XD-DENG — APPROVED** [review]

**Pull request merged**
