### PR TITLE
Add super user and profiler to ldap

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by bolkedebruin** [comment]
:+1: but I do think it is smart to make the search scope configurable. I don't know what it defaults to but going subtrees is not always deseriable. 

On the super user privilege good call although I would consider it an intermediate solution and Flask Roles are in the end more suitable but that could use this as foundation.

**Comment by mistercrunch** [comment]
Seems like this change could affect people by requiring new conf settings, is that what we want or should we just assume that everyone has all rights if those conf settings don't exist. 

I have no idea how many organizations are using this. Could be just you guys or could be 10...

Requiring new conf settings upon upgrade isn't a big deal though. I'm ok with that too.

**Comment by bolkedebruin** [comment]
@mistercrunch I'm not sure if I agree with you. The super_user functionality is exposed within airflow so this change makes that configurable from ldap. My initial implementation for ldap made everyone superuser which in the end is not something you want I guess.

However, on the whole I like a a role based access better (with flask-principal), instead of piggybacking some authorization on top of the authentication (which in general you should not do). This would allow a more flexible approach, eg. authentication in ldap, authorization in db).

**Comment by criccomini** [comment]
> However, on the whole I like a a role based access better (with flask-principal), instead of piggybacking some authorization on top of the authentication (which in general you should not do). This would allow a more flexible approach, eg. authentication in ldap, authorization in db).

@bolkedebruin I tend to agree with you, however that's a much larger change. How do you feel about using this PR, and revisiting once a real role-based integration has been done for Airflow?

**Comment by criccomini** [comment]
@mistercrunch re: config

> Seems like this change could affect people by requiring new conf settings, is that what we want or should we just assume that everyone has all rights if those conf settings don't exist.

The current change shouldn't require any config settings. If you don't do anything, the code defaults to super user. If, however, you DO configure Airflow to have a superuser_filter/data_profiler_filter filters, then it will enforce them.

**Comment by criccomini** [comment]
Just pinging to see if we can get this merged in. Security is a bit of a show stopper for us right now, and having SOME form of admin/profiler/user ACLs is really helpful.

**Pull request merged**
