### PR TITLE
Restore DaskExecutor tests

### LINKED ISSUE #5803: Support for Dask executor in Apache Airflow
I am creating an issue on behalf of Apache Airflow community and it's about Apache Airflow integration with Dask.

We are working on Apache Airflow 2.0 (still at least 3-4 months to release it) but we are doing various cleanup tasks. One of the things we noticed is that we have a DaskExecutor https://github.com/apache/airflow/blob/master/airflow/executors/dask_executor.py . It uses Dask to run the tasks. The executor is very little used. It's used so little that we even have all the Dask Executor tests failing for months - without anyone noticing. We understand that Dask is important for a number of people, but also in order to keep it in Airflow we need someone who actually uses Dask (and Dask Executor in Airflow) to keep it in a healthy state. We are querying at our devlist and checking if someone is willing to maintain it but we also think it might be a good idea to ask here. 

We are happy as Apache Airflow committers to review and accept all the related code but we would love someone more familiar and using Dask to maintain it :).

Note that the executor is rather simple and the tests https://github.com/apache/airflow/blob/master/tests/executors/test_dask_executor.py are just a few and not very complex.

It's literally 200 lines of code in total. We could fix it ourselves, but maybe having someone who actually uses Dask being just a bit more active in the Apache Airflow community is a good idea :)

### PR DESCRIPTION
**Pull request by TomAugspurger**
Closes https://github.com/dask/dask/issues/5803. See https://github.com/dask/dask/issues/5803#issuecomment-601788441 for context, but the brief version is that the Dask Scheduler and workers were using the default tcp protocol, rather than tls as required by the test..

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

### CODE REVIEW

**Comment by potiuk** [comment]
Fantastic @TomAugspurger ! Thanks a lot for that.

Let's see how the tests work.  Note - we are in a process of changing from JIRA to github issues so the bots might give some unhelpful advices for a while

**Comment by kaxil** [comment]
Awesome, really excited for this, thanks @TomAugspurger

**Comment by potiuk** [comment]
Hello @TomAugspurger -> could you please rebase it on top of the latest master? We had some breakages which were unrelated and they should be fixed now.

**Comment by kaxil** [comment]
Also, the following tests failed:

```
FAILED tests/executors/test_dask_executor.py::TestDaskExecutor::test_backfill_integration
FAILED tests/executors/test_dask_executor.py::TestDaskExecutor::test_dask_executor_functions
FAILED tests/executors/test_dask_executor.py::TestDaskExecutorTLS::test_gauge_executor_metrics
FAILED tests/executors/test_dask_executor.py::TestDaskExecutorTLS::test_tls
```

**Comment by kaxil** [comment]
I think we need to add `dask` in https://github.com/apache/airflow/blob/0974aabd31abc6aeadf4f07c9c310b6750e28e2f/setup.py#L459-L463

**Comment by TomAugspurger** [comment]
The test `TestDaskExecutor.test_backfill_integration` is failing because the executor hasn't been started.

```
    def end(self) -> None:

        if not self.client:

            raise AirflowException(NOT_STARTED_MESSAGE)

        if not self.futures:

>           raise AirflowException(NOT_STARTED_MESSAGE)

E           airflow.exceptions.AirflowException: The executor should be started first!

```

Would it be OK to start the Executor somewhere around https://github.com/apache/airflow/blob/4bde99f1323d72f6c84c1548079d5e98fc0a2a9a/tests/executors/test_dask_executor.py#L117? The other tests do this by calling `self.assert_tasks_on_executor(executor)`. I'm not sure whether or not that's appropriate in this test.

**Comment by TomAugspurger** [comment]
Add a call to `start` in https://github.com/apache/airflow/pull/7786#issuecomment-602568451 doesn't seem to help. I think airflow was doing it internally anyway as part of the backfill job.

I haven't been able to resolve the remaining exceptions. If someone more familiar with Airflow can take a look it'd be appreciated.

**Comment by kaxil** [comment]
https://github.com/apache/airflow/pull/7786/commits/d652062b19f0820a0ba5636ec2c4ff94f8aef9b3 should fix another 2 tests.

```
tests/executors/test_dask_executor.py::TestDaskExecutor::test_backfill_integration FAILED                                                                                                                                                              [ 25%]
tests/executors/test_dask_executor.py::TestDaskExecutor::test_dask_executor_functions PASSED                                                                                                                                                           [ 50%]
tests/executors/test_dask_executor.py::TestDaskExecutorTLS::test_gauge_executor_metrics PASSED                                                                                                                                                         [ 75%]
tests/executors/test_dask_executor.py::TestDaskExecutorTLS::test_tls PASSED                                                                                                                                                                            [100%]
```

I got the following error while running the test related to backfill:

**Error Log:**
```
------------------------------------------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------------------------------------------
distributed.worker - WARNING -  Compute Failed
Function:  airflow_run
args:      ()
kwargs:    {}
Exception: TypeError('expected str, bytes or os.PathLike object, not int',)

distributed.worker - WARNING -  Compute Failed
Function:  airflow_run
args:      ()
kwargs:    {}
Exception: TypeError('expected str, bytes or os.PathLike object, not int',)

distributed.worker - WARNING -  Compute Failed
Function:  airflow_run
args:      ()
kwargs:    {}
Exception: TypeError('expected str, bytes or os.PathLike object, not int',)

distributed.worker - WARNING -  Compute Failed
Function:  airflow_run
args:      ()
kwargs:    {}
Exception: TypeError('expected str, bytes or os.PathLike object, not int',)

--------------------------------------------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------------------------------------------
INFO     airflow.models.dagbag.DagBag:dagbag.py:371 Filling up the DagBag from /opt/airflow/tests/dags
INFO     root:test_task_view_type_check.py:48 class_instance type: <class 'unusual_prefix_5d280a9b385120fec3c40cfe5be04e2f41b6b5e8_test_task_view_type_check.CallableClass'>
INFO     airflow.models.dagbag.DagBag:dagbag.py:269 File /opt/airflow/tests/dags/test_zip.zip assumed to contain no DAGs. Skipping.
INFO     airflow.executors.dask_executor.DaskExecutor:base_executor.py:75 Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2017-01-01T00:00:00+00:00', '--pickle', 1, '--ignore-depends-on-past', '--local', '--pool', 'default_pool']
INFO     airflow.executors.dask_executor.DaskExecutor:base_executor.py:75 Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_1', '2017-01-01T00:00:00+00:00', '--pickle', 1, '--ignore-depends-on-past', '--local', '--pool', 'default_pool']
INFO     airflow.executors.dask_executor.DaskExecutor:base_executor.py:75 Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2017-01-01T00:00:00+00:00', '--pickle', 1, '--ignore-depends-on-past', '--local', '--pool', 'default_pool']
INFO     airflow.executors.dask_executor.DaskExecutor:base_executor.py:75 Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2017-01-01T00:00:00+00:00', '--pickle', 1, '--ignore-depends-on-past', '--local', '--pool', 'default_pool']
INFO     airflow.jobs.backfill_job.BackfillJob:backfill_job.py:379 [backfill progress] | finished run 0 of 1 | tasks waiting: 2 | succeeded: 0 | running: 4 | failed: 0 | skipped: 0 | deadlocked: 0 | not ready: 2
ERROR    airflow.executors.dask_executor.DaskExecutor:dask_executor.py:86 Failed to execute task: TypeError('expected str, bytes or os.PathLike object, not int',)
ERROR    airflow.executors.dask_executor.DaskExecutor:dask_executor.py:86 Failed to execute task: TypeError('expected str, bytes or os.PathLike object, not int',)
ERROR    airflow.executors.dask_executor.DaskExecutor:dask_executor.py:86 Failed to execute task: TypeError('expected str, bytes or os.PathLike object, not int',)
ERROR    airflow.executors.dask_executor.DaskExecutor:dask_executor.py:86 Failed to execute task: TypeError('expected str, bytes or os.PathLike object, not int',)
```

**Comment by TomAugspurger** [comment]
That's in `Dask.Executor.execute_async`. Printing out the `command` that';s passed to `subprocess.call`:

```
['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2017-01-01T00:00:00+00:00', '--pickle', 1, '--ignore-depends-on-past', '--local', '--pool', 'default_pool']
```

The `1` between `'--pickle'` and `'--ignore-depends-on-past'` looks fishy. Do you know where it's coming from?

**Comment by kaxil** [comment]
Added a commit to not pickle if using DaskExecutor

**Comment by kaxil** [comment]
Something is wrong with Travis, but the Build is at https://travis-ci.org/github/apache/airflow/builds/666783056

**Comment by TomAugspurger** [comment]
Thanks @kaxil. CI seems to be passing now :)

**Comment by kaxil** [comment]
Merged, thanks for your help @TomAugspurger

**Comment by TomAugspurger** [comment]
Thank you!

**Comment by potiuk** [comment]
FAntastic! Thanks @TomAugspurger !

**Comment by potiuk** [comment]
And thanks @kaxil !

**Pull request merged**
