### PR TITLE
Fix Ui Carets orientation in Grid view

### LINKED ISSUE #27166: Carets in Grid view are the wrong way around
### Apache Airflow version

main (development)

### What happened

When expanding tasks to see sub-tasks in the Grid UI, the carets to expand the task are pointing the wrong way.

### What you think should happen instead

Can you PLEASE use the accepted Material UI standard for expansion & contraction - https://mui.com/material-ui/react-list/#nested-list

### How to reproduce

_No response_

### Operating System

All

### Versions of Apache Airflow Providers

_No response_

### Deployment

Astronomer

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by shashwata27**
closes: #27166 
------
As the carets were facing the wrong way, I swapped the condition to make the orientation write.

### CODE REVIEW

**Comment by bbovenzi** [comment]
Looks like a bunch of js styling got messed up. Let's make sure we're just changing the icons.

Would you mind fixing the carets in the dag import error too?
CSS file: https://github.com/apache/airflow/blob/main/airflow/www/static/css/flash.css
Icon code lookup: https://fontawesome.com/v5/cheatsheet

**Comment by pierrejeambrun** [comment]
@shashwata27, at the momnet we use ESLint for code formatting. (no prettier etc.).

**Comment by pierrejeambrun** [comment]
We also recommend setting up the pre-commit hooks :)

**Comment by shashwata27** [comment]
@pierrejeambrun @bbovenzi will setup what both of you mentioned.

**Comment by bbovenzi** [comment]
@shashwata27 did you ever get the pre-commit hooks working?

**Comment by eladkal** [comment]
Reaolved in https://github.com/apache/airflow/pull/28624

**Pull request closed without merging**
