### PR TITLE
Fix building documentation broken by upgrade of dnspython

### PR DESCRIPTION
**Pull request by potiuk**
The automated upgrade of dependencies in main broken building of
Airflow documentation in main build.

After a lot of experimentation, It has been narrowed down
to upgrade of dnspython from 1.16.0 to 2.+ which was brought
by upgrading eventlet to 0.32.0.

This PR limits the dnspython library to < 2.0.0. An issue
has been opened:
https://github.com/rthalley/dnspython/issues/681

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
It's DNS @ashb . It's always DNS.

**Comment by potiuk** [comment]
I think it is ready and it should fix failing main when merged - then we will be able to  generate new constraints and refresh images and prepare 2.1.4 release.

**Comment by potiuk** [comment]
Reopened to rebuild.

**Comment by potiuk** [comment]
All Green! We can have green master too.

**Review by mik-laj — APPROVED** [review]

**Pull request merged**
