### PR TITLE
AIRFLOW-3543: Fix deletion of DAG with rescheduled tasks

### PR DESCRIPTION
**Pull request by seelmann**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-3543

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
  - `TaskReschedule` must be deleted before `TaskInstance` because of foreign key constraint

### Tests

- [X] My PR extends the following unit tests
  - `test_delete_dag.py`
  - Also changed tests to use `with create_session() as session`

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
Could this not be fixed with less code by simply adding a `ON DELETE CASCADE` to the DB table?

**Comment by seelmann** [comment]
Good point, I'll try...

**Comment by feng-tao** [comment]
@seelmann , any update?

**Comment by seelmann** [comment]
Was busy last days, I'll try this weekend.

**Comment by feng-tao** [comment]
@seelmann , no worry, thanks.

**Comment by seelmann** [comment]
@feng-tao @ashb I made the change to use `ON DELETE CASCADE`. The DB schema needs to be changed by dropping the existing FK constraint and creating a new one. Additionally I added a migration to merge the existing 3 alembic heads.

In CI one Kubernetes test failed but I think it's not related to this change.

**Comment by Fokko** [comment]
I've restarted the failing test. Let us see.

**Comment by OmerJog** [comment]
@Fokko tests pass

**Comment by Fokko** [comment]
Thanks again @seelmann

**Pull request merged**
