### PR TITLE
Fix order of returned rows in a flaky test_outlets_dataset test

### PR DESCRIPTION
**Pull request by potiuk**
In Postgres especially (but in generaly in all databases, if
there is no order specified in select query, the rows might
come in random order. It depends on many factors.

The test query here retrieved the dags without any order but
expected the list to be in specific order.

This PR adds ordering - it also removes side-effects of the
test by using fixture that clears the datasets before and after
the tests that rely/modify datasets - because othrwise failure of
one of the tests can create side effects that fail the other
tests (this is what happened in this case)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @dstandish - mental note (also to self, been there done that). Order every query :)

**Comment by potiuk** [comment]
Looks green.

**Review by Fokko — APPROVED** [review]
Unordered queries; recipe for a race condition :)

**Review by ephraimbuddy — APPROVED** [review]

**Comment by potiuk** [comment]
> Unordered queries; recipe for a race condition :)

Indeed.

**Comment by dstandish** [comment]
> cc: @dstandish - mental note (also to self, been there done that). Order every query :)

thanks

**Comment by blag** [comment]
LGTM, thanks! 😄

**Comment by potiuk** [comment]
> LGTM, thanks! 😄

Yeah. Flaky tests are the worst and the sooner we kill them the better :)

**Pull request merged**
