### PR TITLE
AIRFLOW-6132 - Allow to pass in tags

### PR DESCRIPTION
**Pull request by jomach**
### Jira

- [x] My PR addresses the following [[AIRFLOW-6132](https://issues.apache.org/jira/browse/AIRFLOW-6132)]

### Description

Small change to allow pass in tags for the azure cloud

### Documentation

added python docs

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
Is it used somewhere? It does not see, to be changed in execute (). Also some test accompanying this change would be great.

**Comment by jomach** [comment]
@potiuk This change I think it does not impact anything else as ContainerGroup object already has the tag field. I just exposed it to the Operator. I added a test now. I hope travis re-builds it.

**Comment by jomach** [comment]
@potiuk can  we merge ?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @jomach !

**Pull request merged**
