### PR TITLE
Prepare docs for July 2023 wave of Providers

### PR DESCRIPTION
**Pull request by eladkal**
Providers wave for July.

open issues:
- [x] can not prepare` common.sql` provider due to https://github.com/apache/airflow/pull/31398#issuecomment-1615600858

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Rebased after Pydantic < 2.0.0 limit merged

**Comment by eladkal** [comment]
> Rebased after Pydantic < 2.0.0 limit merged

Thanks! The release wave is still on hold till we figure out the open issue of `common.sql`

**Comment by potiuk** [comment]
> Thanks! The release wave is still on hold till we figure out the open issue of common.sql

Which one ?

**Comment by eladkal** [comment]
> > Thanks! The release wave is still on hold till we figure out the open issue of common.sql
> 
> Which one ?

The OL extra added to `common.sql`
https://github.com/apache/airflow/pull/31398#issuecomment-1615600858

**Comment by potiuk** [comment]
As explained  in https://github.com/apache/airflow/pull/31398, I think there are fundamentally no problems with releasing the change with openlineage extra. 

Our tests are passing (which also means that there are no imports that will not work becasue of openlineage missing (currently we do not install openlineage provider during tests) - so we have quite a certainty that not having openlineage provider is going to work fine for common.sql

**Comment by eladkal** [comment]
> As explained in #31398, I think there are fundamentally no problems with releasing the change with openlineage extra.
> 
> Our tests are passing (which also means that there are no imports that will not work becasue of openlineage missing (currently we do not install openlineage provider during tests) - so we have quite a certainty that not having openlineage provider is going to work fine for common.sql

I think releasing an extra that you can't install is not like installing a provider with a feature that isn't useable yet and the code tells you that you can't use it (like we did with Notifiers being released in providers before we released it in core) but If others consider it as OK I will proceed with the release

**Comment by potiuk** [comment]
> I think releasing an extra that you can't install is not like installing a provider with a feature that isn't useable yet and the code tells you that you can't use it (like we did with Notifiers being released in providers before we released it in core) but If others consider it as OK I will proceed with the release

I think we won't avoid it at times - sometimes we even deliberately released something that was not usable so that we could refer to it in the future. Not ideal, but this is sometimes inevitable when we have two independent things being developed/released when usage of one will depend on the other. 

But if it bothers you, I can draft a very small PR to exclude it.

**Comment by potiuk** [comment]
PR: here: https://github.com/apache/airflow/pull/32325

You will have to regenerate the docs (specficially common.sql) after merging and rebasing on top of this one @eladkal

**Comment by eladkal** [comment]
After discussing with @potiuk I'll continue the release as is

**Review by potiuk — APPROVED** [review]

**Comment by eladkal** [comment]
Looks like there is issue with MsSQL tests

**Comment by potiuk** [comment]
> Looks like there is issue with MsSQL tests

Likely https://github.com/apache/airflow/pull/32343 should fix main  ( guess it's the sqlalchemy refactor).

**Pull request merged**
