### PR TITLE
Add Github Actions badge to README

### PR DESCRIPTION
**Pull request by turbaszek**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by turbaszek** [comment]
I took a look at docs and I think we should fix them once we fully migrate to GA. This or another way, there will be a little bit confusions in the meantime.

**Comment by turbaszek** [comment]
It seems that we are running all tests even for docs only change :<

**Comment by kaxil** [comment]
Hmm yeah, we don\t want to run all tests if docs only change for sure. Wasn't breeze handling these already ?

**Comment by potiuk** [comment]
> Hmm yeah, we don\t want to run all tests if docs only change for sure. Wasn't breeze handling these already ?

It was likely lost with the emergency move to GA (it was based on the name of Travis job) I will take a look and fix some small things shortly.

**Pull request merged**
