### PR TITLE
Airflow OpenShift cluster 

### PR DESCRIPTION
**Pull request by kavodsky**
### Description

Commit provides capabilities to easy create Airflow cluster in OpenShift, unig OpenShift template file.

### Tests
Tested on OpenShift Dedicated v3.10

### CODE REVIEW

**Comment by XD-DENG** [comment]
I think these contents can be put somewhere else as a separate repo and for sure can benefit people (like https://github.com/puckel/docker-airflow), but not necessary to be committed into this Airflow main codebase.

**Comment by marcusrehm** [comment]
Cool!!!

Maybe it could be on https://github.com/helm/charts/blob/master/stable/airflow/README.md

**Comment by kavodsky** [comment]
Thank you guys. Will propose this changes to puckel.

**Comment by kavodsky** [comment]
Closed.

**Pull request closed without merging**
