### PR TITLE
ldap connection_auto_bind pr

### PR DESCRIPTION
**Pull request by zstan**
hi, i found that out LDAP flexible for tls bindings settings, pls merge it ?
default are the same.
thanks !

### CODE REVIEW

**Comment by zstan** [comment]
more correct, sorry :
-       connection_auto_bind = TLS_BEFORE_BIND # available options: NONE | TLS_AFTER_BIND | TLS_BEFORE_BIND | NO_TLS
-       connection_auto_bind = NONE # available options: NONE | TLS_AFTER_BIND | TLS_BEFORE_BIND | NO_TLS

travis-ci failed cause i can`t found there is default airflow.cfg stored ... plz fix it

**Comment by mistercrunch** [comment]
You also need to add a few lines in `configuration.py` to 1-set a default, and 2-have it documented as part of the auto-generated `airflow.cfg`.

As a comment in the `airflow.cfg`, please document the options that can be used and link to a place that explains what they mean.

**Comment by bolkedebruin** [comment]
Hi @zstan . Thanks for the contribution! After you updated the PR with mistercrunch recommendation please follow these http://chris.beams.io/posts/git-commit/ guidelines for your commit message. It helps creating changelogs and release notes in the future. In this case a more descriptive and imperative title and a description that makes clear what and why your are updating.

**Comment by zstan** [comment]
mistercrunch@ i hope i fix all you told, bolkedebruin@ thanks i would follow this !
don`t know why travis-ci false ...

**Pull request closed without merging**
