### PR TITLE
[core] Closing db connection during execution

### PR DESCRIPTION
**Pull request by mistercrunch**
This should help with the occasional MySQL `Too many connections` we've seen.

### CODE REVIEW

**Comment by max-sixty** [comment]
Have you thought about using a `contextmanager` to handle these? http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it

For example:

``` python
@contextmanager
def session_scope(session_cls):
    """Provide a transactional scope around a series of operations."""
    session = session_cls()
    try:
        yield session
        session.commit()
    except Exception, e:
        logger.exception(e)
        session.rollback()
        raise
    finally:
        session.close()
```

Then in the code:

``` python
with Session() as session:
    # ...
    session.add(Log(State.SUCCESS, self))
    # ...
```

Then when you exit the `with` statement, your session is cleaned up, and the code writing to the DB doesn't need to worry about closing sessions / connections / handling exceptions / etc - it's all abstracted.

Happy to do a PR

**Comment by mistercrunch** [comment]
Good call. That'd be a god addition to `airflow.utils`. 

I'm monitoring the sessions number now and I'm not sure this PR actually did it just yet. I have to look at every level of the stack...

**Comment by max-sixty** [comment]
Great - I can try and have a go this weekend. If you want to use this to solve your immediate issues, don't wait for me

**Comment by mistercrunch** [comment]
It turns out close connections in sqla doesn't actually close them, it releases them to the connection pool when using one. `engine.dispose()` seems like the way to go according to this:
http://docs.sqlalchemy.org/en/latest/core/connections.html#engine-disposal

**Pull request merged**
