### PR TITLE
Add MesosExecutor for airflow

### PR DESCRIPTION
**Pull request by kapil-malik**
MesosExecutor allows you to schedule airflow tasks on a Mesos cluster.
For this to work, you need a running mesos cluster and perform following
steps -
1. Install airflow on a machine where webserver and scheduler will run, let's refer this as Airflow server.
2. On Airflow server, use a database which can be accessed from mesos slave machines, for example mysql, and configure in `airflow.cfg`.
3. Change your `airflow.cfg` to point executor parameter to MesosExecutor and provide related Mesos settings.
4. On all mesos slaves, install airflow. Copy the `airflow.cfg` from Airflow server (so that it uses same sql alchemy connection).
5. On all mesos slaves, run 

```
airflow serve_logs
```

for serving logs.
6. On Airflow server, run 

```
airflow scheduler -p
```

to start processing DAGs and scheduling them on mesos. We need -p parameter to pickle the DAGs. (See https://github.com/airbnb/airflow/pull/394 )

You can now see the airflow framework and corresponding tasks in mesos UI.
The logs for airflow tasks can be seen in airflow UI as usual.

### CODE REVIEW

**Comment by kapil-malik** [comment]
@mistercrunch to use this feature, you need to install mesos python eggs as available on http://open.mesosphere.com/downloads/mesos/
Supported versions are 0.22.1 and later.
However, I am not sure how to specify the same in requirements.txt or setup.py. Any suggestions ?

**Comment by mistercrunch** [comment]
img

**Comment by mistercrunch** [comment]
Quick note to the effect that the core maintainers of Airflow won't be able to test, grow and fix this feature, and we need to highlight this in some way. 

I've seen other projects put community contributed modules under a `contrib` folder to make it clear to the community where the boundaries are.

Would you mind moving the `mesos_executor.py` file under `airflow/contrib/operators/`? Also add a note "(community contributed)", or "contributed by @kapil-malik" in the docs where you think it makes sense.

**Comment by kapil-malik** [comment]
Hi @mistercrunch, sure, would move it to contrib folder and update the docs. Thanks :)

However, can you kindly look at https://github.com/airbnb/airflow/pull/394 ? it is necessary for MesosExecutor.

Further, do you think I should update requirements.txt / setup.py as well ? If so, any suggestions on how to do that for mesos eggs URL as I mentioned in my first comment?

**Comment by kapil-malik** [comment]
@mistercrunch , re-submitted pull request at https://github.com/airbnb/airflow/pull/414 after changes.

**Comment by ghost** [comment]
some questions：
1. how  to select Airflow server machine？its one of mesos slaves？
2. Use mesos executor replace of celery executor？how to install and manager rabbitMQ  or other dependents of airflow.
3. i want run airflow to yarn cluster with docker_container_executor ， can you give me some advise for coding.

**Comment by agrajm** [comment]
Not an expert on either airflow or mesos but my two cents:
1. Airflow server machine can be on any other machine - independent of Mesos slave as well.
2. Yes, MesosExecutor is an alternative for CeleryExecutor.  If you are using this executor, then no need to install RabbitMQ or Redis or anything else that Celery needs.

**Pull request closed without merging**
