### PR TITLE
[AIRFLOW-826] Add Zendesk hook

### PR DESCRIPTION
**Pull request by shreyasjoshis**
Dear Airflow Maintainers,

Please accept this PR that adds a Zendesk hook. [Jira issue](https://issues.apache.org/jira/browse/AIRFLOW-826).

### CODE REVIEW

**Comment by sarfarazsoomro** [comment]
Looks good and I like that one can use the zdesk client plus you have patched the call method to work through pagination. On that, please note that the way Zendesk's APIs multi-page end-points return responses is different for their Core API and Incremental Export API. For Core, they simply set the next_page to null so that you don't make additional calls (and this is well handled in the zdesk client), for incremental export api, the next_page in the last page of the result set is set to a url which you are supposed to save and start getting the results from that point onwards (next time you run your fetch). You can also use the 'count' value to tally up the number of objects you have gathered so far :)

**Comment by criccomini** [comment]
Please add license headers, and make sure tests pass.

**Comment by r39132** [comment]
Also, you have a few errors in Landscape related to your changes. Pls address those.

**Comment by shreyasjoshis** [comment]
@criccomini Added license header. @r39132 I think I've fixed the landscape errors.

**Comment by criccomini** [comment]
Need header for tests/contrib/hooks/zendesk_hook.py too

**Comment by criccomini** [comment]
+1 LGTM

**Comment by bolkedebruin** [comment]
Nice addition, I would have liked more thorough unit tests. These barely scratch the surface and do not cover all functionality and functions.

**Pull request closed without merging**
