### PR TITLE
[AIRFLOW-5824] Added AWS DataSync Hook and Operator

### PR DESCRIPTION
**Pull request by baolsen**
Make sure you have checked _all_ steps below.

### Jira
- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  
### Description
- [x] Here are some details about my PR:

Added AWS DataSync Hook and Operator, along with appropriate tests and documentation.

### Tests
- [x] My PR adds the following unit tests:

Tests added for both new components (DataSync hook + operator).

The tests require the moto Python library, specifically moto_datasync. 
I only recently added moto_datasync to moto, so the Airflow tests for AWS DataSync will be skipped if moto_datasync is not present. 
However all tests pass on my local copy of moto which includes moto_datasync

### Commits
- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by baolsen** [comment]
I split up the monolithic DataSync operator into different operators for Create, Get, Update, Delete and execute. This provides more fine-grained control for dealing with AWS DataSync and will work better for users in read-only scenarios or scenarios where new Tasks _must_ be created every time.

**Review by potiuk — CHANGES_REQUESTED** [review]
Thanks for that @baolsen - According to latest agreements (being finalised now) it should be `providers/amazon/aws' :). I hope we can finalise it tomorrow and get it "final".

**Comment by potiuk** [comment]
This also will be helpful in case we want to back-port those operators to 1.10.* series using the new mechanism we are going to have (backport pip packages).

**Comment by baolsen** [comment]
No problem at all, I'll change it accordingly.

**Comment by dh-racheldean** [comment]
FWIW, I've done the base work for moving into `providers/amazon/aws` already in #6502 - doc paths, etc. If that gets merged first (after the vote on AIP-21 v2 is closed), then your update would be easier...

**Comment by baolsen** [comment]
Sounds good, I wouldn't mind an example of the new conventions :) 

I'll wait for #6502 to be merged and then rebase.

**Comment by baolsen** [comment]
I made some initial changes per review feedback, and dependent on #6502 being merged (my build is failing because it is missing a proper documentation migration).
Once those two are done I'll rebase and update and should be good to go.

**Comment by baolsen** [comment]
Hi @potiuk , 
I saw AIP 21 was updated and activity on #6502 , are those changes now merged so I can rebase?
Thanks for the help!

**Comment by potiuk** [comment]
Yes absolutely @baolsen -> it will be providers/amazon/aws for sure. We are just discussing other packages that should likely end up in providers but for amazon it's quite clear.

**Comment by baolsen** [comment]
Somehow my branch got messed up with all the changes, busy fixing it

**Comment by baolsen** [comment]
Hi @potiuk my changes are done. Ready for review / merge when you are.

**Review by potiuk — APPROVED** [review]
Thanks! Good one.

**Pull request merged**
