### PR TITLE
[AIRFLOW-1095]  ldap_auth memberOf should come from configuration

### PR DESCRIPTION
**Pull request by vfoucault**
if the key ldap/group_member_attr is set in the airflow.cfg, the this value is used
to lookup groups for the user.

### CODE REVIEW

**Review by NeilHanlon — COMMENTED** [review]
lgtm

Not sure if I'm 'allowed' to approve, though.

**Comment by criccomini** [comment]
Should update docs to mention this feature. Somewhere like here maybe:

https://airflow.incubator.apache.org/security.html?highlight=ldap#ldap

Also, might consider updating the default configs to include `group_member_attr = memberOf` just to help people be aware that this exists.

**Comment by criccomini** [comment]
LGTM

**Comment by criccomini** [comment]
In future, please follow template when opening PR.

https://issues.apache.org/jira/browse/AIRFLOW-1095

**Pull request closed without merging**
