### PR TITLE
Move some` FAB related tests to provider

### PR DESCRIPTION
**Pull request by potiuk**
There are still some tests that are really FAB provider Auth Manager tests but they were left in the core (which is kind-of expected remnant of the past. We will eventually find and move all of them but for now let's just move some of them we are aware of.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by amoghrajesh — APPROVED** [review]
Looks like this was what lead to the false positive earlier. Thanks +1

**Review by ephraimbuddy — APPROVED** [review]

**Comment by potiuk** [comment]
> Looks like this was what lead to the false positive earlier. Thanks +1

We still have to update our FAB / WWW test suite - to make the needed test purely AuthManager ones, but that's something for another day (And likely maybe we will need to get some "TestAuthiManager" in those tests maybe (@vincbeck ?) . I think there is a number of FAB-bound tests we still have in tests/www that actually use FAB logic under-the hood, some of them we can move to provider, but likely some of them should test a generic AuthManager features so maybe some day (not today likely) we should have a general cleanup in those tests and separate the "pure" auth manager tests from the "fab" ones.

WDYT @vincbeck ?

**Review by eladkal — APPROVED** [review]

**Comment by vincbeck** [comment]
> > Looks like this was what lead to the false positive earlier. Thanks +1
> 
> We still have to update our FAB / WWW test suite - to make the needed test purely AuthManager ones, but that's something for another day (And likely maybe we will need to get some "TestAuthiManager" in those tests maybe (@vincbeck ?) . I think there is a number of FAB-bound tests we still have in tests/www that actually use FAB logic under-the hood, some of them we can move to provider, but likely some of them should test a generic AuthManager features so maybe some day (not today likely) we should have a general cleanup in those tests and separate the "pure" auth manager tests from the "fab" ones.
> 
> WDYT @vincbeck ?

100% agree. I realized that when I was working on migrating FAB related code from core Airflow to providers. The only reason why I did not do it was the effort required. As mentioned by Jarek, there are many tests in core that use FAB logic, ideally we should make these tests FAB agnostic. But it won happen in one day, let's do it step by step :)

**Comment by potiuk** [comment]
:100:

**Pull request merged**
