### PR TITLE
fix(migration): fix dataset to asset migration typo

### LINKED ISSUE #43226: "breeze start-airflow" failing on main branch
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

"breeze start-airflow" is failing for main branch

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 3a8972ecb8f9 -> 05234396c6fc, Rename dataset as asset.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedObject: constraint "dsdar_dataset_fkey" of relation "dag_schedule_asset_alias_reference" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 8, in <module>
    sys.exit(main())
             ^^^^^^
```

Seems some issue with migrating from datasets to assets

### What you think should happen instead?

This PR could be a possible problem https://github.com/apache/airflow/pull/42023
Reverting this fix is fixing the issue.

### How to reproduce

1. Checkout main branch
2. Run breeze `start-airflow`

### Operating System

MacOS

### Versions of Apache Airflow Providers

_No response_

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Lee-W**
Closes: https://github.com/apache/airflow/issues/43226

# Why

`dsdar_dataset_alias_fkey` was accidentally named as `dsdar_dataset_fkey` in migration files

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
Why is it `dataset_alias` and not `asset_alias`?

**Comment by Lee-W** [comment]
> Why is it `dataset_alias` and not `asset_alias`?

Those are fks from Airflow 2.10 that we need to rename.

> Also running `airflow db migrate` locally, I run into `constraint "dsdar_dag_id_fkey" of relation "dag_schedule_asset_alias_reference" does not exist`. Not sure if it might be related?

Thanks for reminding me. There's yet another issue but somewhat related. Fixed in this PR

**Review by uranusjr — APPROVED** [review]
This should be backported, right?

**Comment by Lee-W** [comment]
> This should be backported, right?

0026 yes, 0040 no

**Comment by Lee-W** [comment]
backport pr https://github.com/apache/airflow/pull/43314

**Pull request merged**
