### PR TITLE
[AIRFLOW-4501] pymysql pendulum fix

### PR DESCRIPTION
**Pull request by nazo**
### Jira

https://issues.apache.org/jira/browse/AIRFLOW-4501

### Description

see
https://github.com/sdispater/pendulum/issues/267
https://github.com/sdispater/pendulum/tree/1.x#limitations

### CODE REVIEW

**Comment by zhongjiajie** [comment]
Please add jira ticket due to you change code. @nazo

**Comment by XD-DENG** [comment]
@nazo it’s a potentially useful change. But as Jiajie suggested above, please create a ticket in JIRA and update your commit/PR here accordingly before we can proceed to review/merge your patch

**Comment by nazo** [comment]
created a ticket. https://issues.apache.org/jira/browse/AIRFLOW-4501

**Comment by OmerJog** [comment]
@nazo you'll need to change the commit message from `[AIRFLOW-XXX]pymysql pendulum fix` to
`[AIRFLOW-4501] pymysql pendulum fix converters datetime bug`

The logs for releases are generated from the commit message so it's important it will be accurate.

**Comment by nazo** [comment]
changed commit message.

**Pull request merged**
