### PR TITLE
Migrating to Bullseye images from Buster 

### PR DESCRIPTION
**Pull request by vmalakhin**
related: #18190
Migration to Bullseye images (latest Debian release) away from Buster

### CODE REVIEW

**Comment by potiuk** [comment]
I am afraid mysql installlation needs fixin - the image does not build :(

**Comment by vmalakhin** [comment]
> I am afraid mysql installlation needs fixin - the image does not build :(

There's an issue with msodbcsql17 and mssql-tools as well under Dockerfile.ci. Microsoft does not support Bullseye yet per https://github.com/MicrosoftDocs/sql-docs/issues/6804. Asked about their plans...

**Comment by potiuk** [comment]
> There's an issue with msodbcsql17 and mssql-tools as well under Dockerfile.ci. Microsoft does not support Bullseye yet per [MicrosoftDocs/sql-docs#6804](https://github.com/MicrosoftDocs/sql-docs/issues/6804). Asked about their plans...

Yeah. Usually our delays in releasing new versions of base image/python versions were delays in dependencies supporting them.

**Comment by vmalakhin** [comment]
> > There's an issue with msodbcsql17 and mssql-tools as well under Dockerfile.ci. Microsoft does not support Bullseye yet per [MicrosoftDocs/sql-docs#6804](https://github.com/MicrosoftDocs/sql-docs/issues/6804). Asked about their plans...
> 
> Yeah. Usually our delays in releasing new versions of base image/python versions were delays in dependencies supporting them.

That's fine - let's wait for their response then.

**Comment by vmalakhin** [comment]
> > > There's an issue with msodbcsql17 and mssql-tools as well under Dockerfile.ci. Microsoft does not support Bullseye yet per [MicrosoftDocs/sql-docs#6804](https://github.com/MicrosoftDocs/sql-docs/issues/6804). Asked about their plans...
> > 
> > 
> > Yeah. Usually our delays in releasing new versions of base image/python versions were delays in dependencies supporting them.
> 
> That's fine - let's wait for their response then.

There's no official ETA from Microsoft I'm afraid. But per their reply https://github.com/MicrosoftDocs/sql-docs/issues/6804 usually next release adds support for recently introduced versions. So most probably Bullseye will be supported by Jan 2022.

**Comment by potiuk** [comment]
> > > > There's an issue with msodbcsql17 and mssql-tools as well under Dockerfile.ci. Microsoft does not support Bullseye yet per [MicrosoftDocs/sql-docs#6804](https://github.com/MicrosoftDocs/sql-docs/issues/6804). Asked about their plans...
> > > 
> > > 
> > > Yeah. Usually our delays in releasing new versions of base image/python versions were delays in dependencies supporting them.
> > 
> > 
> > That's fine - let's wait for their response then.
> 
> There's no official ETA from Microsoft I'm afraid. But per their reply [MicrosoftDocs/sql-docs#6804](https://github.com/MicrosoftDocs/sql-docs/issues/6804) usually next release adds support for recently introduced versions. So most probably Bullseye will be supported by Jan 2022.

I guess we just wait then :(. I think there is not a "HUGE" value - buster's EOL is ~2022-08, so they will continue releasing security fixes - Jan 2022 sounds like safe to migrate.

**Pull request closed without merging**
