### PR TITLE
Add Qubole how to documentation

### LINKED ISSUE #10929: Add how to documentation for Qubole Operator
We are trying to improve our documentation, and I see a guides that explains how to use these operators is missing. Here are guides for other operators: https://airflow.readthedocs.io/en/latest/howto/operator/index.html
Wouldn't you like to write a guide for this operator? In practice, the guide is an example DAG file + description.

_Originally posted by @mik-laj in https://github.com/apache/airflow/issues/9347#issuecomment-691988305_

### PR DESCRIPTION
**Pull request by kazanzhy**
Add draft of Qubole how-to documentation for Qubole Operators and Sensors
I will be very glad to any suggestions, especially from Qubole users.

closes: #10929

### CODE REVIEW

**Comment by potiuk** [comment]
Nice @chattarajoy  waiting for your review to merge :)

**Review by chattarajoy — APPROVED** [review]
Looks good

**Comment by kazanzhy** [comment]
Just fixed some issues with doc build.
Now local doc building works well

**Comment by potiuk** [comment]
some provider.yaml inconsistency :)

**Comment by potiuk** [comment]
BTW @kazanzhy. I STRONGLY recommend `pip install pre-commit`. It saves a TON of time on iterations like that :).
See https://github.com/apache/airflow/blob/main/STATIC_CODE_CHECKS.rst#id3

**Comment by kazanzhy** [comment]
Did it, thanks
Just trying to figure out what's wrong

**Comment by potiuk** [comment]
Hey @kazanzhy - small comment :). Could you please use Github's "Draft" feature instaead of adding Draft: in the subject? 

https://github.blog/2019-02-14-introducing-draft-pull-requests/

The side effect of changing the subject is that if you are subscribed to GitHub notifications via email, the thread gets split.

**Review by potiuk — APPROVED** [review]

**Comment by kazanzhy** [comment]
Copy that. Sorry for the bad habit from Gitlab :)

**Pull request merged**
