### PR TITLE
D205 Support - Root files

### PR DESCRIPTION
**Pull request by ferruzzi**
Part of https://github.com/apache/airflow/issues/10742

D205 asserts that all docstrings must have a one-line summary ending in a period.  If there is more than one sentence then there must be a blank line before the rest of the docstring.  Meeting these requirements could be as simple as adding a newline, or might require some rephrasing.

There are almost a thousand violations in the repo so we're going to have to take this in bites.

### PLEASE NOTE

There should be zero logic changes in this PR, only changes to docstrings and whitespace.  If you see otherwise, please call it out.

### Included in this chunk

The last three "root" level files: `setup.py`, `airflow/exceptions.py`, and `airflow/configuration.py` 

### To test

If you comment out [this line](https://github.com/apache/airflow/blob/main/pyproject.toml#L68) and run pre-commit in main you will get 92 errors.  After these changes, only 73 remain and no files in the list above should be on the list.  After uncommenting that line and rerunning pre-commits, there should be zero regressions.

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by ferruzzi** [comment]
Strange, wonder why the static checks are failing.   It doesn't look related at first glance, but I'll poke at it this afternoon.

**Comment by ferruzzi** [comment]
huh.  Running `breeze build-docs` locally passes in this branch.

image

**Comment by ferruzzi** [comment]
Mypy was grumpy about some missing type hints.  Not sure what in this PR triggered it, but I've fixed the complaints.

**Comment by potiuk** [comment]
> Mypy was grumpy about some missing type hints. Not sure what in this PR triggered it, but I've fixed the complaints.

Mypy is quite often grumpy about unrelated things. The old guy is useful anywwy, so we keep him around anyway

**Review by potiuk — APPROVED** [review]

**Pull request merged**
