### PR TITLE
Add ADDITIONAL_PYTHON_DEPS

### PR DESCRIPTION
**Pull request by wittfabian**
**Description**

Since we have separate "build" segment for the production image, We will need to add any extra dependencies there rather than on top of the base image if someone wants to add those dependencies.

Reference: https://github.com/apache/airflow/issues/8604

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Nice!. I will also add an option to extend Breeze with that option - but that can be done separately.

**Comment by potiuk** [comment]
You can mark it as ready for review to merge it @wittfabian - or you might try to extend Breeze with an option to add --additional-python-deps flag if you are brave enough :)

**Comment by wittfabian** [comment]
I have not yet worked with Breeze, but I would like to see the result ;)
I am already working on https://github.com/apache/airflow/issues/8866.

**Comment by wittfabian** [comment]
@potiuk Must the flag be added here? 
https://github.com/apache/airflow/blob/master/breeze#L770

**Comment by potiuk** [comment]
There are a few places - breeze-complete and breeze are the two scripts. You can just search for another flag and do it similarly, or I can add it later after your PRs are merged and cc: you in the PR.

**Pull request merged**
