### PR TITLE
Fix and enable test_retry_handling_job

### PR DESCRIPTION
**Pull request by Bisk1**
Needed to resync DAG to db as the only DAG so that scheduler schedules it with num_runs=1

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]
If it passes. (The DAGs are cleared after each test in this class so the sync call is fine, albeit not optimal performance-wise.)

**Comment by Bisk1** [comment]
@uranusjr What would be a better approach performance-wise?

**Comment by Taragolis** [comment]
close-open for re-trigger full tests

**Comment by Bisk1** [comment]
@Taragolis it seems that tests passed (not sure but I think the steps for building images fail for other reasons) should I close & reopen it several times more to check if it's not flaky?

**Review by Taragolis — APPROVED** [review]
I think better merge it and check if it flakey or not. Previously it was completely broken

**Pull request merged**
