### PR TITLE
[AIRFLOW-2407] import logging for line 70 of qubole_sensor.py

### PR DESCRIPTION
**Pull request by cclauss**
flake8 testing of https://github.com/apache/incubator-airflow on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./airflow/contrib/sensors/qubole_sensor.py:68:13: F821 undefined name 'logging'
            logging.exception(e)
            ^
```

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
See above.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
This PR fixes flake8 tests that are currently failing.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [X] Passes git diff upstream/master -u -- "*.py" | python3 -m flake8 --diff

### CODE REVIEW

**Comment by Fokko** [comment]
Please don't `import logging`, but use `this.log.`

**Comment by cclauss** [comment]
LOL...  __this__ is an undefined name...

flake8 testing of https://github.com/apache/incubator-airflow on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./airflow/contrib/sensors/qubole_sensor.py:62:9: F821 undefined name 'this'
        this.log.info('Poking: %s', self.data)
        ^
./airflow/contrib/sensors/qubole_sensor.py:68:13: F821 undefined name 'logging'
            logging.exception(e)
            ^
./airflow/contrib/sensors/qubole_sensor.py:71:9: F821 undefined name 'this'
        this.log.info('Status of this Poke: %s', status)
        ^
```
__this__ also conflicts with the standard library module:
$ __python__
    >>> import this

**Comment by kaxil** [comment]
@cclauss Please can you create a single Pull Request for [AIRFLOW-2407] JIRA instead of separate PR as below:
https://github.com/apache/incubator-airflow/pull/3293
https://github.com/apache/incubator-airflow/pull/3294
https://github.com/apache/incubator-airflow/pull/3296
https://github.com/apache/incubator-airflow/pull/3297
https://github.com/apache/incubator-airflow/pull/3298
https://github.com/apache/incubator-airflow/pull/3299
?

**Comment by cclauss** [comment]
https://github.com/apache/incubator-airflow/pull/3294#issuecomment-386159118

**Comment by cclauss** [comment]
Closed in favor of #3307

**Pull request closed without merging**
