### PR TITLE
rename GKEStartPodOperator -> GKEPodOperator

### PR DESCRIPTION
**Pull request by raphaelauv**
KubernetesPodOperator
EksPodOperator
GKEStartPodOperator

we could fix this inconsistency by renaming GKEStartPodOperator -> GKEPodOperator or even GkePodOperator ?

### CODE REVIEW

**Comment by mik-laj** [comment]
We used to have discussions about operator naming and agreed that every operator should have a verb.

**Comment by mik-laj** [comment]
Discussion thread: https://lists.apache.org/thread/6k9jzrd2jzsmz073m68b49zz2zhlzhfv


> I think that the operator should describe the behavior(verb), hook should
> describe a service(noun). These are other parts of speech.
> In my opinion, HiveOperator should be named HiveExecuteQuery. Hook will be
> called Hive. Then there will be no name conflicts.

> But I do like the verb/noun idea. That's a really nice way of thinking about what belongs where.

> I completely agree that the operator names have been a bit muddled,
HiveExecuteQuery sounds better to me.

**Comment by raphaelauv** [comment]
Then GKEStartPodOperator is not doing what it say

cause the GKEStartPodOperator is not only starting a pod , but it's starting , tracking  and waiting for end of the pod (and also re-attach)

**Comment by raphaelauv** [comment]
So a better name could be KubernetesRunPodOperator ? GkeRunPodOperator ...

**Comment by mik-laj** [comment]
KubernetesRunPodOperator sound good to me, but we should discuss it in a wider group, because it is one of the most popular operators. Can you create a thread on mailing list?

**Comment by potiuk** [comment]
Are we sure we want to get here? KPO is such a comnmon name, and such ubiquitous all over the place that I am hesitating quite a bit to renaming it. KRPO sounds already pretty bad. 

In this case I am not sure if consistency is a king any more

**Comment by raphaelauv** [comment]
then only rename

GKEStartPodOperator -> GKEPodOperator 

@potiuk ?

**Comment by potiuk** [comment]
> GKEStartPodOperator -> GKEPodOperator
> 
> @potiuk ?

Sounds much better :) - but I woudl love to hear what others say.

**Comment by potiuk** [comment]
Failures :(

**Review by jedcunningham — COMMENTED** [review]
This sounds good to me. There are some docs/test references that still need changing though.

**Comment by potiuk** [comment]
Still some errors :(

**Pull request closed without merging**
