### PR TITLE
Update to new helm stable repo

### PR DESCRIPTION
**Pull request by ashb**
Switch out deprecated helm repo for new stable repo.

- https://www.cncf.io/blog/2020/11/05/helm-chart-repository-deprecation-update/
- https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by ashb** [comment]
Will merge as soon as the first test that uses helm passes. (We've used this on our own non-Airflow projects so it should be good)

**Review by potiuk — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
Kube tests failed, and but I think that was a transient error. Merging anyway as it is much better if not perfect.

**Comment by potiuk** [comment]
I think we have a "real" problem introduced a day ago or so. I am taking a look at this . This seems to be fully repeatable.

**Comment by mjpieters** [comment]
I still see this on my 1-10-stable pull requests: https://github.com/apache/airflow/runs/1395402772?check_suite_focus=true#step:6:3841

Looks like this needs backporting.

**Pull request merged**
