### PR TITLE
Fix Custom Sensitive Variable fields feature

### PR DESCRIPTION
**Pull request by kaxil**
https://github.com/apache/airflow/pull/9397 added this feature but broke Master

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by ashb — APPROVED** [review]
Tests still not 100% happy though

**Comment by kaxil** [comment]
> Tests still not 100% happy though

```
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
             Checking integration openldap
-----------------------------------------------------------------------------------------------

             Integration openldap OK!

-----------------------------------------------------------------------------------------------

Error: some of the CI environment failed to initialize!

###########################################################################################
                   EXITING /opt/airflow/scripts/ci/in_container/check_environment.sh WITH STATUS CODE 254
###########################################################################################

Error: check_environment returned 254. Exiting.

###########################################################################################
                   EXITING /entrypoint WITH STATUS CODE 254
###########################################################################################
###########################################################################################
                   EXITING WITH STATUS CODE 254
###########################################################################################

Finished the script ci_run_airflow_testing.sh
Elapsed time spent in the script: 139 seconds
Exit code 254
```

Environment related issue in one of the tests

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
still test_can_handle_error_on_decrypt fails consistently :(

**Comment by kaxil** [comment]
> still test_can_handle_error_on_decrypt fails consistently :(

Yup, fixing it too

**Pull request merged**
