### PR TITLE
feat: K8S 1.29 support

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Review by dirrao — COMMENTED** [review]
I have a basic question on the test setup. does our test suite run on all supported Kubernetes versions?

**Comment by potiuk** [comment]
> I have a basic question on the test setup. does our test suite run on all supported Kubernetes versions?

Depending on PR. Full matrix of tests is run in  `Canary` runs and when `full tests needed` label is set.  

You can read more about our CI setup here https://github.com/apache/airflow/blob/main/CI.rst where all the details of the setup is explained. 

Specifically this document https://github.com/apache/airflow/blob/main/dev/breeze/SELECTIVE_CHECKS.md explains how selective checks are applied - i.e. which PRs are running whcih tests.

You can also study the CI (to see how our matrix of tests is run) and breeze code (especially selective checks) to see how PR content and type affects the matrix.

Generally `Canary` builds (`main` builds scheduled 1/day + when things are merged to main) are running complete set of tests with `**everything**` - most of the PRs run only relevant subset of tests that Selective checks determine based on some heuristics (which we continue to tweak if we find any false positives).

**Comment by potiuk** [comment]
In this PR the heuristics determined that "full tests" were needed so it did run full matrix of tests. You can see it when you look at the names of the jobs and job details

image

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Thanks @raphaelauv ! as usual :)

**Pull request merged**
