### PR TITLE
[AIRFLOW-2241] Set pool slot to 0 if the user specified pool doesn't …

### PR DESCRIPTION
**Pull request by feng-tao**
…exist

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2241

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
User could accidentally put a noon-exist pool name into the dag which will cause the scheduler to throw an exception.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
not sure if this needs a test.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
cc @youngyjd

**Comment by Fokko** [comment]
It will not skip the task, but get stuck if I understand correctly, right?

**Comment by feng-tao** [comment]
@Fokko , that's correct.

**Comment by feng-tao** [comment]
@Fokko, actually this should have been fixed by https://github.com/apache/incubator-airflow/commit/e6973b1596914e5d62567e065223e7b169d1c26c. Close the pr for now.

**Pull request closed without merging**
