### PR TITLE
Bump boto min versions

### PR DESCRIPTION
**Pull request by ferruzzi**
aiobotocore's pinned botocore version has restricted us to botocore 1.34.0.   aiobotocore released 2.13.0 a couple weeks ago which relaxes their boto restrictions to `botocore>=1.34.70,<1.34.107`.  I'd love to get support for botocore 1.34.90 or better, so I'm just checking to see how much work is going to be needed to get this bump working.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by ferruzzi** [comment]
Huh, seems to be passing just fine.  I'll open it up for review/approval.

**Review by vincbeck — APPROVED** [review]

**Comment by ferruzzi** [comment]
well... it WAS all green..... LOL

**Comment by ferruzzi** [comment]
I haven't run into trouble on this test yet.  Following the docs, I ran it locally in this branch for just the amazon provider and it appears to be passing fine:

image



Maybe I'll give this a bump tomorrow and give it another chance.

**Comment by ferruzzi** [comment]
seems fine locally.  bumping the failed test

image

**Review by potiuk — APPROVED** [review]

**Pull request merged**
