### PR TITLE
Bump Flask-AppBuilder to ``4.5.2``

### PR DESCRIPTION
**Pull request by kaxil**
https://pypi.org/project/Flask-AppBuilder/4.5.2/ . It fixes WTForms issue mentioned in https://github.com/apache/airflow/pull/43233. Fix was https://github.com/dpgaspar/Flask-AppBuilder/pull/2279

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by ashb** [comment]
This the WTForms fix?

**Comment by kaxil** [comment]
> This the WTForms fix?

Yup

**Comment by kaxil** [comment]
> This the WTForms fix?

Actually I will update the WTForms thing too

**Comment by potiuk** [comment]
That was quick (from Daniel). But you will have to rebase @kaxil as I just merged 4.5.1 as it also had some "security manager" code changes - so we cannot go straight to 4.5.1 -> and now you have conflicts

**Review by potiuk — APPROVED** [review]

**Comment by kaxil** [comment]
> That was quick (from Daniel). But you will have to rebase @kaxil as I just merged 4.5.1 as it also had some "security manager" code changes - so we cannot go straight to 4.5.1 -> and now you have conflicts

Done

**Comment by potiuk** [comment]
Also we will need to backport this one to 2-10-test because of the wtforms limit removal

**Comment by kaxil** [comment]
> Also we will need to backport this one to 2-10-test because of the wtforms limit removal

Yup, will create a backport PR

**Comment by potiuk** [comment]
I think due to our new backport policy, the number of PRs merged in Airflow increased significantly... But I am still increasing the lead @kaxil ;)

**Comment by potiuk** [comment]
> But I am still increasing the lead @kaxil ;)

or NOT

image

**Comment by kaxil** [comment]
> I think due to our new backport policy, the number of PRs merged in Airflow increased significantly... But I am still increasing the lead @kaxil ;)

I need to change git author email and name on your laptop to mine :D

**Comment by kaxil** [comment]
> > But I am still increasing the lead @kaxil ;)
> 
> or NOT
> 
> image

Let me be happy with the weekly ones :D

**Review by jedcunningham — APPROVED** [review]

**Review by shahar1 — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]

**Comment by kaxil** [comment]
Backport PR: https://github.com/apache/airflow/pull/43318

**Pull request merged**
