### PR TITLE
V1 8 stable

### PR DESCRIPTION
**Pull request by uniquerussa**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Fokko** [comment]
Hi @teriusbin, something is going wrong her. If want to contribute please follow the guidelines. Right now you try to merge a branch into Airflow master that doesn't look ok.

**Comment by bolkedebruin** [comment]
Please close this, it takes buikd time away from us on Travis. Thx.

**Comment by yes5144** [comment]
the process **airflow scheduler** are using more and more memory, is this a bug? have you met this ?
At the beginning, the using of memory is very low, but after 20 days later, the using is more the 4G. so i have to restart the process. 
Can you help me ? thanks

1. airflow 1.8.0  
2. executor = CeleryExecutor
3.  the manager tool: supervisor

**Comment by ashb** [comment]
Airflow 1.8.0 is now two point releases (1.8.1 and 1.8.2) and two releases (1.9.0 and 1.10.0) old, so the first thing we would suggest is upgrading.

Additionally github PR comments are not the best place for getting help - either slack (https://apache-airflow-slack.herokuapp.com/) or the https://lists.apache.org/list.html?dev@airflow.apache.org mailinglist are the places to ask for support.

**Pull request closed without merging**
