### PR TITLE
[AIRFLOW-1422] Customize File Handler for logging module via airflow.cfg

### PR DESCRIPTION
**Pull request by ronfung**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1422) issues and references them in the PR title. For example, "[AIRFLOW-1422] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1422

### Description
- [x] # Allow log files generated by the scheduler, webserver and workers be more organized based on time interval, size etc.   Make it easier for analysis, maintenance and cleanup. 
- [x] # Log Handler - it supports all file handlers:  TimedRotatingFileHandler, RotatingFileHandler, WatchedFileHandler, FileHandler or StreamHandler.  
- [x] #Two configuration keys are added: log_handler_class and log_handler_params.  Default is using logging.FileHandler with None. 
e.g. 1
`log_handler_class = logging.handlers.RotatingFileHandler`
`log_handler_params = {"maxBytes":"100000"}`
e.g. 2
`log_handler_class = logging.handlers.TimedRotatingFileHandler`
`log_handler_params = {"backupCount":7,"interval":1,"when":"d"}`
default:
`log_handler_class = logging.FileHandler`
`log_handler_params = None`

### Tests
- [x] ./run_unit_tests.sh python2.7.x and python3.5.x 

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by criccomini** [comment]
@bolkedebruin @aoen thoughts on this?

**Comment by aoen** [comment]
I think we should close this, we are putting together a more detailed proposal for logging here:
https://github.com/apache/incubator-airflow/pull/2422 which will include this functionality

**Comment by bolkedebruin** [comment]
Hi Chris, I agree with @aoen. @AllisonWang is working in getting logging properly fixed which will allow you to this within the config more closely to the Python standards. Maybe you would like to chime in and help her/us getting it proper so we can work from there?

**Comment by bolkedebruin** [comment]
@ronfung can you close this please?

**Pull request closed without merging**
