### PR TITLE
[AIRFLOW-4062] Clear install extra package command

### PR DESCRIPTION
**Pull request by zhongjiajie**
Some command for installing extra packages are
`pip install apache-airflow[devel]` we should
clear install extra package command to
`pip install 'apache-airflow[devel]'`

[ci skip]

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-4062\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Some command for installing extra packages are
`pip install apache-airflow[devel]` we should
clear install extra package command to
`pip install 'apache-airflow[devel]'`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
I create jira ticket becase of change log code in https://github.com/apache/airflow/pull/4897/files#diff-e90ff8ca3f03b5d363736e93748ef634R67

**Comment by mik-laj** [comment]
Why is it important?

**Comment by zhongjiajie** [comment]
PTAL @XD-DENG @feng-tao @Fokko

**Comment by zhongjiajie** [comment]
@mik-laj `pip install apache-airflow[devel]` will get error in ubuntu, but `pip install 'apache-airflow[devel]'` will not

**Comment by XD-DENG** [comment]
Hi @zhongjiajie , I tried to run `pip install apache-airflow[devel]` on Ubuntu, and there was no issue/error.

Python: Python 2.7.15rc1
Pip: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
Ubuntu: Linux **** #34-Ubuntu SMP Thu Jan 17 15:18:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (an AWS instance)

Please double-check from your side.

**Comment by zhongjiajie** [comment]
@XD-DENG In my side, it raise error.
pic

**Comment by zhongjiajie** [comment]
@XD-DENG I get it, It is `zsh`, according to https://stackoverflow.com/a/30539963/7152658. I don't know in this situation I should close PR or not.

**Comment by XD-DENG** [comment]
I would suggest closing it as I don't see it as an issue/bug.

**Comment by zhongjiajie** [comment]
@XD-DENG Think about it for a while, I want to discuss PR once again. I have two points.

* We should compatible our command in many operating system and many type of shell, and this change will not break others and could use in `zsh`
* We have some other `pip install` using `''` between extra package, just like below.

https://github.com/apache/airflow/blame/master/docs/howto/executor/use-celery.rst#L64
https://github.com/apache/airflow/blame/master/CONTRIBUTING.md#L132

**Review by 7yl4r — APPROVED** [review]
Adding single quotes to pip install argument fixes install for `zsh` and doesn't hurt other shells. 
Sure, why not?

**Comment by Fokko** [comment]
I've seen people make this mistake often. I'll would like to get this in. @zhongjiajie. Can you rebase?

**Comment by kaxil** [comment]
I agree with Fokko

**Comment by zhongjiajie** [comment]
@Fokko I rebase on master, PTAL, thanks.

**Comment by ashb** [comment]
@zhongjiajie This causes test failures due to invalid docs. Turns out CI skip was a bad idea on docs, at least in this case :D

We can have this back once the test pass :)

**Comment by zhongjiajie** [comment]
@ashb I am so sorry about that. I will fix that.

**Pull request merged**
