### PR TITLE
[AIRFLOW-2414] Fix RBAC log display

### PR DESCRIPTION
**Pull request by oyamin**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2414

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
 - Fixing exception thrown when trying to view the LOG file in RBAC UI

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - None for now

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Hmm, do you know if this could be covered by a test? This code should be tested. Cheers

**Comment by rsubra13** [comment]
@oyamin 

Hi I had the same issue and had raised this ticket.  https://issues.apache.org/jira/browse/AIRFLOW-2402


I believe the 'read' method of file task handler returns logs and metadatas. 
https://github.com/apache/incubator-airflow/blob/master/airflow/utils/log/file_task_handler.py#L168

But in www_rbac/views.py
https://github.com/apache/incubator-airflow/blob/master/airflow/www_rbac/views.py#L447
I believe by changing like this, things work smooth. 

```
   logs, metadatas = handler.read(ti)
```

**Comment by KevinYang21** [comment]
please checkout my comment in https://issues.apache.org/jira/browse/AIRFLOW-2402

**Comment by Fokko** [comment]
This has been changed in here https://github.com/apache/incubator-airflow/pull/3214/files#diff-948e87b4f8f644b3ad8c7950958df033R765

**Comment by Fokko** [comment]
The problem is that we have two UI's, but only the legacy one has been updated. @yrqls21 can you also add a test to the rbac code? Would be very helpful.

**Comment by KevinYang21** [comment]
Will do.

Fokko Driesprong <notifications@github.com>于2018年5月3日 周四下午11:44写道：

**Comment by r39132** [comment]
Fixed in https://github.com/apache/incubator-airflow/pull/3319 

Closing this one as a dupe.

**Pull request closed without merging**
