### PR TITLE
[AIRFLOW-2515] Add dependency on thrift_sasl to hive extra

### PR DESCRIPTION
**Pull request by sekikn**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2515
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adds a dependency on thrift_sasl to hive extra
so that HiveServer2Hook.get_conn() works.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

tests.hooks.test_hive_hook:TestHiveServer2Hook.test_get_conn

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Ah I see, this only happens when using kerberos: https://github.com/apache/incubator-airflow/blob/1db3073374b6fd033651caf1fcb98e743483fa30/airflow/hooks/hive_hooks.py#L503

@sekikn can you resolve the conflicts?

**Comment by sekikn** [comment]
Thanks for taking a look @Fokko! Rebased the PR.

> this only happens when using kerberos

Not only in that case unfortunately. impyla always requires `thrift_sasl`, even without kerberos.

https://github.com/cloudera/impyla/blob/6980dda32350f0b43d2069978815e515a04283e4/impala/_thrift_api.py#L149

**Review by Fokko — APPROVED** [review]
Thanks @sekikn

**Comment by hani1814** [comment]
Can you please give an example on how to use hivethriftserver2 with kerberos / http transport mode.

I placed the following in extras and it is not working

{ "use_beeline": true, "principal": "hive/_HOST@XX.ADDS", "transportMode": "http", "httpPath: "cliservice", "proxy_user": "login"}

**Comment by Fokko** [comment]
@hani1814 can you provide soms logs?

**Comment by hani1814** [comment]
Please find attached a screenshot of the error. 

12ad8644-2d3c-4320-8d16-f072997713ea

**Comment by Fokko** [comment]
@gglanzani Any experience with this?

**Comment by gglanzani** [comment]
@Fokko this is usually happens when you either can't connect or when the authentication failed for some reason. Unfortunately the degree of information given back by Thrift does not allow a lot of debugging.

@hani1814 Could you let us know what happens when using the client from pure Python?

**Pull request closed without merging**
