### PR TITLE
[AIRFLOW-3766] Add support for kubernetes annotations

### PR DESCRIPTION
**Pull request by stijndehaes**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Adds kubernetes annotation support 

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I need some help with being able to test this

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by iwilltry42** [comment]
Thanks for that! I hope this will be merged soon, as we could really use it to automatically inject sidecar-containers using github.com/tumblr/k8s-sidecar-injector , e.g. for Kerberos.

**Review by iwilltry42 — APPROVED** [review]

**Comment by feng-tao** [comment]
look reasonable to me. @dimberman , what do you think?

**Comment by iwilltry42** [comment]
I tested this change in my fork based on tag 1.10.2 and it works just fine.
Although this only works completely fine in some environments if you put the annotations into the `airflow.cfg`, as many annotations (e.g. for Prometheus or the sidecar-injector) have a `/` in them which is neither allowed as an environment variable in Docker nor as a ConfigMap key in Kubernetes.

**Comment by feng-tao** [comment]
@iwilltry42 will this https://github.com/apache/airflow/pull/4772 help?

**Comment by iwilltry42** [comment]
@feng-tao this is definitely a good thing, but it won't help in that case.
Let me expand on this a little bit:
I am using the [sidecar-injector](https://github.com/tumblr/k8s-sidecar-injector/), which requests an injection config using an annotation on pods like this: `"injector.tumblr.com/request": "sidecar-test"`.
That way, I can inject e.g. a kerberos sidecar into each pod that's being created by the KubernetesExecutor.
So I put this into the `airflow.cfg` under the `[kubernetes_annotations]` section: `injector.tumblr.com/request = sidecar-test`. This works just fine.
Now if I want to define this in an environment variable like all the other config options, then it will fail, as `AIRFLOW__KUBERNETES_ANNOTATIONS__INJECTOR.TUMBLR.COM/REQUEST: sidecar-test` is not a valid environment variable (and also not a valid ConfigMap key) because of the `/` it contains.

The error message for the Kubernetes deployment (using stable/airflow helm chart) when putting it into the ConfigMap: 
> Invalid value: "AIRFLOW__KUBERNETES_ANNOTATIONS__INJECTOR.TUMBLR.COM/REQUEST": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')

And when putting it directly into an env var:
> Invalid value: "AIRFLOW__KUBERNETES_ANNOTATIONS__INJECTOR.TUMBLR.COM/REQUEST": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')

Maybe there's room for a char-sequence substitution? As the `/` in annotations is a very common thing?

**Comment by feng-tao** [comment]
got you @iwilltry42 , thanks for the explaination. lgtm.

**Comment by feng-tao** [comment]
should be in 1.10.3. cc @ashb

**Comment by iwilltry42** [comment]
@feng-tao so what about just having something like `annotation = annotation.replace("_._", "/")` to replace `_._` with a `/` before setting the annotation in the worker_config?
That way the configuration env var would look like this `
AIRFLOW__KUBERNETES_ANNOTATIONS__INJECTOR.TUMBLR.COM_._REQUEST` but end up in the pod annotation as `
AIRFLOW__KUBERNETES_ANNOTATIONS__INJECTOR.TUMBLR.COM/REQUEST`.
I'm pretty sure that `_._` is not a common pattern in annotation keys, but `/` is

**Comment by Lowess** [comment]
Hi there ! 

I am in the same situation as @iwilltry42. 
Looks like the injection of an annotation that contains a `/` is not implemented in this PR. 
@iwilltry42  did you find any work around (except dropping the annotation in `airflow.cfg` directly) ?

**Comment by iwilltry42** [comment]
@lowess yep, I cloned the repo and added a one-liner to replace a `__. __` in annotations with a `/`, since I don't expect that sequence there too often compared with a simple /.
Could be any other char sequence though..

**Comment by andrei-l** [comment]
I believe that should have been addressed differently. The airflow config keys should not be related to annotation keys. There should be just a single airflow config key which would contain all key/value annotation pairs.  In a similar way like annotations are provided in k8s: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Pull request merged**
