### PR TITLE
[AIRFLOW-1189] Fix get a DataFrame using BigQueryHook failing

### PR DESCRIPTION
**Pull request by ghost**
…function; new tests for the behavior included

Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ x ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1189

### Description
- [ x ] Here are some details about my PR, including screenshots of any UI changes:
Fixing missing arguments and class attribute from the `get_pandas_df` function call chain

### Tests
- [ x ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Tests for two different input query syntaxes and function output

### Commits
- [ x ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ghost** [comment]
Ok, so is there a BQ connection for testing purposes? The tests are dysfunctional if there is none available

**Comment by ghost** [comment]
@criccomini @mistercrunch @alexvanboxel so will this be merged or not?

**Comment by criccomini** [comment]
It was.

https://github.com/apache/incubator-airflow/commit/93666f9965b2940c5179c5b6bbfef8cf278c024c

The PR just says closed because our repo is with Apache, not github, so we merge outside of the Github PR.

**Comment by ghost** [comment]
Alright. Just wondering if there going to be a GCP project to run the tests included in this pull request. Otherwise the build with fail.

**Comment by criccomini** [comment]
I modified those tests in a subsequent PR to only run when a specific switch is set.

**Pull request closed without merging**
