### PR TITLE
[AIRFLOW-335] Fix simple style errors/warnings

### PR DESCRIPTION
**Pull request by skudriashev**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-335](https://issues.apache.org/jira/browse/AIRFLOW-335)

Testing Done:
- Unittests passed

### CODE REVIEW

**Comment by bolkedebruin** [comment]
LGTM

**Comment by jlowin** [comment]
@skudriashev since this merge, I'm seeing this error message in the mysql unit tests of a number of PRs:

```
ERROR [airflow.jobs.SchedulerJob] Boolean value of this clause is not defined
Traceback (most recent call last):
  File "/home/travis/build/apache/incubator-airflow/airflow/jobs.py", line 667, in _do_dags
    self.manage_slas(dag)
  File "/home/travis/build/apache/incubator-airflow/airflow/utils/db.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/apache/incubator-airflow/airflow/jobs.py", line 301, in manage_slas
    .all()
  File "/home/travis/build/apache/incubator-airflow/.tox/py34-cdh-airflow_backend_mysql/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 2760, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
```

I can't tell for sure if it's from this PR, but I believe it might be this line:
`.filter(SlaMiss.email_sent.is_(False) or SlaMiss.notification_sent.is_(False))`, which was changed changed from `==` to `is_`. 
https://github.com/apache/incubator-airflow/commit/dc1bdf6222094e908b75056f9d6b0d14419e8777#diff-54a57ccc2c8e73d12c812798bf79ccb2R299

I don't run mysql so I can't test it directly, can you confirm if sqlalchemy is mishandling mysql bool types?

**Comment by skudriashev** [comment]
@jlowin, that should work. It is recommended way actually (http://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.ColumnElement.is_). If this really cause problems, we can revert it.

**Comment by jlowin** [comment]
@skudriashev I agree it's definitely the right way to do it -- I just can't figure out why it isn't working for MySql (but fine for others). Maybe we aren't properly declaring that as a bool field in MySql terms? I'm scratching my head on this one.

**Comment by skudriashev** [comment]
@jlowin, aren't tests fine?

**Comment by jlowin** [comment]
I don't think so -- all of the recent PR's Python 3.4 mysql tests have been failing. What's strange is that the error I pasted above doesn't actually seem to be failing a test -- it prints in the log of successful tests. I'm not sure it's being caught properly -- maybe SLA's are wrapped in a try/except.

**Pull request closed without merging**
