### PR TITLE
[AIRFLOW-4251] Instrument DagRun schedule delay

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW4251

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Instrument DagRun schedule delay - time between expected DagRun start date and the actual DagRun start date.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Tests not required as we did not change any airflow logic

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
correct me if I am wrong, but could you help me understand why we need this stat given it is highly dependent on the DAG's schedule interval?

**Comment by milton0825** [comment]
@feng-tao 
What I am measuring here is the delay between the expected start date and the actual start date of a `DagRun`. Both expected start date and actual start date are dependent on the  `schedule_interval` because that is how Airflow works (scheduled start_date = execution_date + schedule_interval). The `schedule_delay` itself is not dependent on the `schedule_interval` tho.

**Comment by feng-tao** [comment]
yeah, but what is the difference between running this vs running canary monitoring dag? Now you will generate O(#DAG) for this dagrun stats.

**Comment by milton0825** [comment]
I think this metric is useful to track the schedule delay per `DAG`. We can use the metric to tell how behind a `DAG` is to its schedule and can quickly check the historic trend on a dashboard like Grafana.

Canary monitoring serves for the purpose of tracking the delay from DAG schedule to first task execution, which may or may not represents the schedule delay for each DAG.

What do you think?

**Comment by KevinYang21** [comment]
IMO this can be useful when we're analyzing delays, so we know where the delay comes from, scheduler or executor. On the other hand, I think the story would be more comprehensive if we have task instance level metrics--for a DAG with 1k tasks we now get only 1 data point per dag run just like a DAG with 1 task, which make it less representitive. In th end people may be more interested about task instance delays instead of DAG run delay.

About the performance, I think it is not too bad to have it here since we do it in the dag parsing subprocess so it is effectively O(# DAG/# subprocesses). If data points coming from TI level stat are too many maybe we can try some random sampling? Also if it is TI level stat intuitively it would be in the main scheduler loop which performance matters more.

All this reminds me about some old discussion we had earlier. If we do want to start having a story around scheduling performance, we might need to consider the parsing time of DAG files and even kick that out from our metrics--otherwise if I as a user introduce u a large # of large DAG files then ur metrics will spike.

Just some random thoughts around this topic :D

**Review by feng-tao — APPROVED** [review]
I am convinced by you guys :) I guess it is not harm to have more stats. And the cardinality is per DAG run which should be fine.

**Comment by feng-tao** [comment]
thanks @milton0825 @KevinYang21

**Comment by garghima** [comment]
@feng-tao @milton0825 I have a concern regarding the delay we are capturing here.
There will come erroneous delay values in case of backfill as then the current difference logic will not give correct picture.
WDYT?
@vardancse @ramandumcs

**Comment by milton0825** [comment]
@garghima this metrics is only captured when the airflow scheduler create a `DagRun`. `DagRun` created by `airflow backfill` would not be captured here.

**Comment by garghima** [comment]
@milton0825 Thanks, Got you.

**Comment by arbass22** [comment]
I still see this metric in the docs but am not seeing it being emitted, nor can I find any reference to it in the codebase anymore.  @milton0825 Do you know if this was removed either intentionally or unintentionally?

**Comment by milton0825** [comment]
Maybe it was removed accidentally. Can you open an issue for this?

**Comment by arbass22** [comment]
Done https://github.com/apache/airflow/issues/14364

**Pull request merged**
