### PR TITLE
Upload coverage for PRs to main

### PR DESCRIPTION
**Pull request by thomasrockhu**
---
Tom from @codecov here. Right now, coverage isn't uploaded to Codecov except on commits on the `main` branch. This change will also upload coverage on PRs to the `main` branch on `apache/airflow` on PRs (both on the main repository and forks)

**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by mik-laj** [comment]
Related: https://github.com/apache/airflow/pull/19523 CC: @potiuk

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
This is not a good idea for two reasons:

* Gathering coverage during our tests takes a lot of memory - see #19523. Most of our PRs are run in Public GitHub Runners and gathering coverage will cause OOM errors on public runners.

* We are using selective checks in our PRs. We detect what kind of changes are done in the PR and based on that we run subset of tests. That makes  lcoverage information wrong because those PRs show far less coverage.

**Comment by thomasrockhu** [comment]
Ahhh that makes sense @potiuk. Would something like [carryforward flags](https://docs.codecov.com/docs/carryforward-flags) make sense? We built that for teams that don't run their entire test suite on every commit.

**Comment by potiuk** [comment]
That might solve the 2nd problem indeed (good one!). But I am afraid the first problem is more serious.

**Comment by potiuk** [comment]
> I reproducibly run the test_kubermetes.py followed by test_backfill_job.py with/without coverage yielding 2-3 GB vs 700 MB memory used while test_backfill_job was running.

**Comment by potiuk** [comment]
It could be "generated" by some internals of pytest/coverage interaction - but for use stability is much more important than PR coverage and I've already lost quite a lot of time chasing other memory issues, so unless you could help us solving this problem, it is super-low priority for us.

Just in case you'd like to take a look @thomasrockhu,  running tests in reproducible conditions is easy:
1) checkout airflow
2) run `./breeze` command and wait for the environment to bootstrap
3) once you are in the `docker-compose` shell of airlfow test environmet
4) run pytest commands

In this case `pytest /tests/providers/cncf/kubernetes/hooks/test_kubernetes.py ./tests/jobs/test_backfill_job.py` - with/without coverage flag should show you the difference (just monitor memory used while the tests are running).

**Comment by potiuk** [comment]
Try with those args (and use ./breeze as it contains .coveragerc for example:

```
if [[ ${ENABLE_TEST_COVERAGE:="false"} == "true" ]]; then
    EXTRA_PYTEST_ARGS+=(
        "--cov=airflow/"
        "--cov-config=.coveragerc"
        "--cov-report=xml:/files/coverage-${TEST_TYPE}-${BACKEND}.xml"
    )
fi
```

I just repeated that, and results are the same. Steps to reproduce:

Setup:

1) `./breeze stop` (stop all containers)
2) `./breeze --db-reset --backend sqlite` (starts breeze in basic sqlite configuration with reseting the db)
3)  Run `docker stats` in separate terminal
4) Run `pytest ./tests/providers/cncf/kubernetes/hooks/test_kubernetes.py ./tests/jobs/test_backfill_job.py` to "warm the caches" 

Once you do it, it very reproducible:

Test a) - without coverage:

`pytest ./tests/providers/cncf/kubernetes/hooks/test_kubernetes.py ./tests/jobs/test_backfill_job.py`

https://user-images.githubusercontent.com/595491/147656637-6ad880e1-9f2b-4364-915a-cd5c92aa58c0.mp4

Memory tops ~ 156 MB and drops right after the tests fiinish.

Test b) - with coverage:

`pytest ./tests/providers/cncf/kubernetes/hooks/test_kubernetes.py ./tests/jobs/test_backfill_job.py --cov=airflow/ --cov-config=.coveragerc --cov-report=xml:/files/coverage-test.xml`

https://user-images.githubusercontent.com/595491/147656618-c550ae90-521c-40cd-b842-32172a2ab94a.mp4

Durint the test memory usage is very similar - but when the tests are finishing (I guess output report is prepared) the memory used goes quickly up to more than 230 MB  just before dropping (about 0:19 of the video). This effect is non-existing in case coverate is disabled.

This is fully reproducible.

**Comment by potiuk** [comment]
(BTW. This is just a very small subset of the tests. When we run full tests suite, the excess memory used will be much bigger (but this one shows the "spikey" character of this. The problem is that when the test are finished, we have a sudden spike of memory used (and even 80 MB which we see in this case is a lot). This is all before pytest has a chance to free the memory used for all the "legitimate" reasons.  

We have rather limited memory on public runners so every 100 MB counts - the effect compounds when we also have database docker containers running and integration dockers running, We hevily optimized the memory used by our database dockers to make them fit the memory we have in public runners and we have little room left.

**Comment by eladkal** [comment]
hi @thomasrockhu @potiuk it seems like we don't get codecov reports at all https://codecov.io/github/apache/airflow?branch=main
while it's not a good idea to run it on every PR, I think there is a value for update coverage report daily/weekly on main branch only? I'm not sure what is going on there but I think this one is broken since we renamed default branch master -> main ?

**Comment by potiuk** [comment]
I honestly lost any interest in codecov use, I was never able to figure out why some reports are wrong or misconfigured. 

Codecov integration with GitHub is 

codecov.yaml of ours contains already the right branch:

```
codecov:
  branch: mai
```

The yaml file is valid - checked it following: https://docs.codecov.com/docs/codecov-yaml#why-does-my-bot-not-match-the-one-i-inputted-on-my-yaml

Yet codecov still attempts to use master 🤷🤷🤷🤷🤷 

I think I and others attempted to fix multiple problems with codecov reports probably 10 times in the past and I can't remember it working well or giving useful insights.

But if someone would like to continue attempting to fix it - I have no problem with it. But I am not going to loose any sleep/time on it any more to be honest.

**Pull request closed without merging**
