### PR TITLE
Add retrieve output docker swarm operator

### LINKED ISSUE #41445: DockerSwarmOperator retrieve_output XCom not working
### Apache Airflow version

Other Airflow 2 version (please specify below)

### If "Other Airflow 2 version" selected, which one?

2.10.0rc1

### What happened?

Using a `DockerSwarmOperator`, with `retrieve_output=True` and `retrieve_output_path='/path/to/pickle/file'`, the content of the file located at `/path/to/pickle/file` is not set as XCom prior to deletion of the container.

This functionality is described in the `DockerOperator`[documentation](https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/_api/airflow/providers/docker/operators/docker/index.html#airflow.providers.docker.operators.docker.DockerOperator). As `DockerSwarmOperator` inherits from `DockerOperator` (cf. [source](https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/_modules/airflow/providers/docker/operators/docker_swarm.html#DockerSwarmOperator)), I was expecting the `retrieve_output` feature to work using `DockerSwarmOperator`.

### What you think should happen instead?

- The same behavior as when using `DockerOperator`, i.e. the contents of the file located at `/path/to/pickle/file` is set as XCom ("return_value" key) when `retrieve_output=True` and `retrieve_output_path='/path/to/pickle/file'`.

### How to reproduce

Below is an example of how to reproduce the issue.
The `docker_url` argument must be adapted to the deployment context.

The DAG is made up of 2 identical tasks, using either a DockerOperator (`write_xcom_docker`) or a DockerSwarmOperator (`write_xcom_docker_swarm`). In these two tasks :
- A python script writes a dictionary to a Pickle file (`/tmp/variable.pickle`).
- The path to this Pickle file is associated with the `retrieve_output_path argument` in the Docker(Swarm)Operator.

```py
from airflow import DAG
from airflow.utils.dates import days_ago
from datetime import timedelta

from docker import types
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.providers.docker.operators.docker_swarm import DockerSwarmOperator

params = {
    'dag_id': 'test_xcom_docker_docker_swarm',
    'catchup': False,
    'max_active_runs': 1,
    'default_args': {
        'owner': 'airflow',
        'start_date': days_ago(1),
        'retries': 1,
        'retry_delay': timedelta(minutes=5)
    }
}

with DAG(**params) as dag:
    write_xcom_docker = DockerOperator(
        task_id='write_xcom_docker',
        image='python:latest',
        api_version='auto',
        command="""python -c '

import os
import pickle

capitals = {
  "Canada": "Ottawa", 
  "England": "London",
  "France": "Paris",
  "Germany": "Berlin", 
}

file_path = "/tmp/variable.pickle"
with open(file_path, "wb+") as file:
    pickle.dump(capitals, file)

    '
    """,
        retrieve_output=True,
        retrieve_output_path='/tmp/variable.pickle')

    write_xcom_docker_swarm = DockerSwarmOperator(
        task_id='write_xcom_docker_swarm',
        image='python:latest',
        api_version='auto',
        command="""python -c '

import os
import pickle

capitals = {
  "Canada": "Ottawa", 
  "England": "London",
  "France": "Paris",
  "Germany": "Berlin", 
}

file_path = "/tmp/variable.pickle"
with open(file_path, "wb+") as file:
    pickle.dump(capitals, file)

    '
    """,
        retrieve_output=True,
        retrieve_output_path='/tmp/variable.pickle',
        mode=types.ServiceMode(mode="replicated", replicas=2))

write_xcom_docker >> write_xcom_docker_swarm
```

- For the task using a `DockerOperator`, the content of the Pickle file is set as XCom as expected.

image

- For the task using a `DockerSwarmOperator`, nothing is set as XCom.

image

### Operating System

Docker host : Debian GNU/Linux 11 (bullseye)
Container OS : Debian GNU/Linux 12 (bookworm)

### Versions of Apache Airflow Providers

apache-airflow-providers-docker==3.12.3

### Deployment

Other Docker-based deployment

### Deployment details

Airflow was deployed using Docker Swarm, based on Docker version 26.1.4 (build 5650f9b)

### Anything else?

The issue has also been tested in version `2.9.2` (using apache-airflow-providers-docker==3.12.0), with the same result.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by rgriffier**
Closes: https://github.com/apache/airflow/issues/41445

Updates the `DockerSwarmOperator` to include the same `retrieve_output` functionality as the `DockerOperator`: get access of the content of a file as XCom at the end of a task, before the container is destroyed. To take account of possible container replication at deployment time, a `Task` and `Container` retrieval step has been added, in addition to the specific `retrieve_output` functionality.

The modifications were tested with the Dag provided below:

```py
from airflow import DAG
from airflow.utils.dates import days_ago
from datetime import timedelta

from docker import types
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.providers.docker.operators.docker_swarm import DockerSwarmOperator

params = {
    'dag_id': 'test_xcom_docker_docker_swarm',
    'catchup': False,
    'max_active_runs': 1,
    'default_args': {
        'owner': 'airflow',
        'start_date': days_ago(1),
        'retries': 1,
        'retry_delay': timedelta(minutes=5)
    }
}

with DAG(**params) as dag:
    write_xcom_docker = DockerOperator(
        task_id='write_xcom_docker',
        image='python:latest',
        api_version='auto',
        command="""python -c '

import os
import pickle

capitals = {
  "Canada": "Ottawa", 
  "England": "London",
  "France": "Paris",
  "Germany": "Berlin", 
}

file_path = "/tmp/variable.pickle"
with open(file_path, "wb+") as file:
    pickle.dump(capitals, file)

    '
    """,
        retrieve_output=True,
        retrieve_output_path='/tmp/variable.pickle')

    write_xcom_docker_swarm = DockerSwarmOperator(
        task_id='write_xcom_docker_swarm',
        image='python:latest',
        api_version='auto',
        command="""python -c '

import os
import pickle

capitals = {
  "Canada": "Ottawa", 
  "England": "London",
  "France": "Paris",
  "Germany": "Berlin", 
}

file_path = "/tmp/variable.pickle"
with open(file_path, "wb+") as file:
    pickle.dump(capitals, file)

    '
    """,
        retrieve_output=True,
        retrieve_output_path='/tmp/variable.pickle')

    write_xcom_docker_swarm_replicas = DockerSwarmOperator(
        task_id='write_xcom_docker_swarm_replicas',
        image='python:latest',
        api_version='auto',
        command="""python -c '

import os
import pickle

capitals = {
  "Canada": "Ottawa", 
  "England": "London",
  "France": "Paris",
  "Germany": "Berlin", 
}

file_path = "/tmp/variable.pickle"
with open(file_path, "wb+") as file:
    pickle.dump(capitals, file)

    '
    """,
        retrieve_output=True,
        retrieve_output_path='/tmp/variable.pickle',
        mode=types.ServiceMode(mode="replicated", replicas=2))

write_xcom_docker >> write_xcom_docker_swarm >> write_xcom_docker_swarm_replicas
```

Here the results:
- `DockerOperator`:
image
- `DockerSwarmOperator` without replication: 
image
- `DockerSwarmOperator` with `replicas=2`: 
image
As `replicas=2` in the Service configuration inside the DAG, 2 files were loaded inside the `return_value` XCOM.

If needed, I can create a specific PR for the `v2-10-test` branch !

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by rgriffier** [comment]
@potiuk Thank you for validating the PR. Do I need to make a specific one for `2.10` so that the feature is available in the next release 2.XX?

**Comment by potiuk** [comment]
This is provider-only change - it will be released in the next docker provider

Note! Current state of airflow development is that technically there will be no new 2.* releases any more (just 2.11 as a bridge release for Airflow 3) - but users will be able to upgrade providers for 2 for quite some time and we will keep on releasing them.

**Comment by spoutin** [comment]
unless I'm missing something, the docker sdk function to `get_archive` is only available on the the workers that hosted the docker container since it uses the container ID.  If you have a multi node setup how are you able to retrieve the logs if the airflow worker that executed the docker container is not on the same docker swarm worker node?

i also noticed that you're calling the `inspect_container`, this has the same limitation; you can only inspect containers that are on the same worker.

The docker "tasks" APIs are what we should be using to access Docker Services tasks not the "container" APIs.

What's confusing me is that this was tested but I'm not sure how.  Unless I'm confused about the Docker Swarm APIs or there is some form of a Docker API gateway / proxy that is routing the docker APIs to the correct workers I'm not sure how this is working.

**Comment by rgriffier** [comment]
I'll have to check, I did test the code in Swarm mode but I'm not sure whether I was testing with a container deployed on a node other than the manager node... I'll have a look at it this weekend, I'll tell you again (but I'm fairly convinced by @spoutin's arguments, I'm afraid I tested in a configuration far from the reality of use)...

**Comment by rgriffier** [comment]
I've just checked and it doesn't work if the container being deployed is not on the same host as the manager.
My bad, I wasn't on my usual infrastructure and I didn't notice that I only had one node. @spoutin comment was right on the mark. I've seen in your PR that you're proposing to delete what I'd added, which is actually a good idea. I thinks it's impossible to do what I wanted with the Docker API at the moment: Swarm mode does not allow containers deployed on worker nodes to be queried from the manager. Sorry for the bad testing.

**Pull request merged**
