### PR TITLE
[AIRFLOW-2947] Added Helm chart for Kubernetes executor

### PR DESCRIPTION
**Pull request by jpds**
### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2947

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Added Helm chart for Airflow.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This probably should run helm lint, happy to add it if someone can show me how to integrate it into Travis CI.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":

### CODE REVIEW

**Comment by jpds** [comment]
@dimberman @gsemet

**Comment by ashb** [comment]
This is a -1 from me - I don't like Helm's requirement to be run as an all-powerful user in the cluster.

**Comment by jpds** [comment]
@ashb That's not a hard-requirement from Helm, it's completely possible to deploy Tiller in a namespace with only access to that namespace.

**Comment by ashb** [comment]
I'm also not a fan of that model as it's a resource hog ;)

**Comment by dimberman** [comment]
@ashb I agree that helms super-user tiller is a really bad security model
but there are best practices users can take to use it safely. It's also the
lowest barrier to entry and a lot of people in the k8s world have been
asking for a chart.

Also worth mentioning that helm 3 will completely remove the tiller.

https://sweetcode.io/a-first-look-at-the-helm-3-plan/

**Comment by ashb** [comment]
Yeah, I'm waiting quite eagerly for Helm3. I'm not a fan of this right now, but I also don't feel that strongly about it, certainly not enough to veto or anything like that.

**Comment by dimberman** [comment]
I think we're in a similar mind about the current state of helm. I think
this'll be useful for people wanting to test airflow out or build quick
POCs, but hopefully for production they use something like the airflow
operator.

**Comment by gsemet** [comment]
@ashb I do not see what your remark has to do with Airflow, to what I see and use in other charts in this repository, they almost all follow the same structure, and this airflow chart looks like every other. If you want to deploy this chart without Tiller, you can do `helm template` and then `kubectl apply`. Or use Helm in client mode only.

**Comment by dimberman** [comment]
@jpds It looks like you removed the kube/deploy folder but it's not removed from the setup_kubernetes script https://github.com/apache/incubator-airflow/blob/5bd5a7bad638241c01ac1ddd0fe8f8c7a3e95d27/scripts/ci/kubernetes/setup_kubernetes.sh. 

It looks like this PR has screwed up the kubernetes tests and now they're just running the normal airflow tests. 

https://travis-ci.org/apache/incubator-airflow/jobs/419688983

**Comment by dimberman** [comment]
Wait. No. This is on the master branch. Thats... not good. Going to investigate further.

**Comment by dimberman** [comment]
Ok so that was caused by the recent dockerized ci pipeline. I'm addressing the issue here https://github.com/apache/incubator-airflow/pull/3797

**Comment by dimberman** [comment]
Lol so now that the tests have been fixed, let's revisit this :). @jpds could you please rebase?

**Comment by ron819** [comment]
@jpds ping

**Comment by dimberman** [comment]
@jpds could you please rebase this? Would love to start offering this as a simple solution for testing out the k8sExecutor :).

**Comment by gauthiermartin** [comment]
@jpds Still interested in this feature as i might be interested to take over if you dont ?

**Comment by dimberman** [comment]
@gauthiermartin I think it's safe at this point to take over this effort since it's been a few months.

**Comment by dimberman** [comment]
@jpds I'm going to close this PR as stale. Please let me know if you want me to reopen it.

**Pull request closed without merging**
