### PR TITLE
[AIRFLOW-3138] Use current data type for migrations

### PR DESCRIPTION
**Pull request by noronham**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3138

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Migrations need to use not just the current model (with columns) as the current status of the DB but also the correct types. Go back to using basic sqlalchemy types and keep the timestamp as a timestamp without a timezone.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Ran DB migration manually against both sqlite and postgres. Following https://github.com/apache/incubator-airflow/pull/3720.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Comment by ashb** [comment]
@bolkedebruin This looks okay to me - do you have time for a quick check too.

I think this is okay as our UtcDateTime type is the same column type under the hood. But thinking a bit more about it does doing this set the timezones incorrectly on the row. Hmmmmm.

(Turns out there's no way to remove a review approval in github)

**Review by ashb — CHANGES_REQUESTED** [review]
I'm not 100% sure this is right actually - the UtcDateTime isa Datetime under the hood, and without this I'm not sure we'll set the right timezone value on the column.

This is particularly important when the timezone of the server is _not_ UTC.

**Comment by noronham** [comment]
@ashb - the problem I ran into was that (at least for postgres) - the data was being read from a naive timestamp column in the db (pre 0e2a74e0fc9f_add_time_zone_awareness.py and ) and so the python code was converting it to an assumed UTC date. The session.merge of the task instance then fails because (at least in postgres) the timestamp with timezone is passed into the query as a full string and so the key no longer matches the database and you get an error and the migration fails:
**'sqlalchemy.orm.exc.StaleDataError: UPDATE statement on table 'task_instance' expected to update 1 row(s); 0 were matched.'**

I don't think that the migration really needs the date - it just needs the primary key and so while for runtime code/etc - I agree 100% that the UtcDateTime should be used. However, I believe in this case since the database during this migration is storing naive dates AND we are only using the date as a value type - it should be safe  to keep naive in the migration code.

I'll see if I can test with mysql and confirm this doesn't cause any new errors.
  * install airflow 1.8 or 1.9
  * run a task (so task_instance table isn't empty)
  * upgrade to 1.10

**Comment by ashb** [comment]
Oh, I was getting the migrations confused. I thought this was the one where we changed the timezone columns from native to UtcDateTime. But this  is an earlier one right?

In which case yes this makes sense, and thank you for the detailed explanation.

**Comment by noronham** [comment]
I did a little more testing today with mysql, and while the mysql version I'm using doesn't currently set 
explicit_defaults_for_timestamp (so I can't upgrade to current master at the moment) - the migration for this runs fine both with and without my diff.

On an unrelated note since I was testing a bit more using master instead of 1.10.0 - there seems to be two current heads for migrations which makes it a little harder to run upgrades and downgrades (you have to explicitly upgrade to cc1e65623dc7)
9635ae0956e7 -> 0a2a5b66e19d (head), add task_reschedule table
9635ae0956e7 -> dd25f486b8ea (head)

Let me know if there is anything else I should/could do before this can be merged!

**Comment by Fokko** [comment]
@ashb PTAL

**Review by ashb — APPROVED** [review]

**Pull request merged**
