### PR TITLE
[AIRFLOW-1937] Speed up scheduling by committing in batch

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1937

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Newly scheduled task instances (state = None, up for retry)
were committed per task instance instead of all at once.
This isn't required as tasks cannot be picked up by another
process in the mean time. Committing in batch significantly
speeds up task scheduling for dags that have a lot of tasks.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Covered by existing.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
cc @Fokko @ori-moisis

**Comment by bolkedebruin** [comment]
cc @criccomini @jgao54 ping @Fokko

**Review by gwax — APPROVED** [review]
Yes, please!

**Comment by Fokko** [comment]
I went down the tree, and I don't see any problems with the batch commit. Bolke, the RDBMS will thank you! Cheers

**Pull request closed without merging**
