### PR TITLE
Support additional apt dependencies

### PR DESCRIPTION
**Pull request by 22quinn**
Support ADDITONAL_DEV_DEPS and ADDITONAL_RUNTIME_DEPS build arguments in both CI and production Dockerfile.

Related to: #8872

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Fantastic. One more thing that could be useful is to add those additional deps as flags in Breeze. But it can be a separate request.

**Comment by zikun** [comment]
Thanks for reviewing. Not very familiar with Breeze scripts. Let me do some research and make it in another PR.

**Review by feluelle — COMMENTED** [review]
`ADDITONAL_` should be `ADDITIONAL_` @zikun ;)

**Comment by zikun** [comment]
> `ADDITONAL_` should be `ADDITIONAL_` @zikun ;)

Good catch :) I just found another `additonal` in `concepts.rst` and fixed it together because it's not worth a separate PR. Hope this is fine?

**Review by feluelle — APPROVED** [review]

**Pull request merged**
