### PR TITLE
[AIRFLOW-2114] Add AIRFLOW_HOME to PythonVirtualenvOperator

### PR DESCRIPTION
**Pull request by john-bodley**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2114

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR passes the `AIRFLOW_HOME` environment variable to the subprocess which is required in order for the connection information to be available within the subprocess. The logic is derived from the [BashOperator](https://github.com/apache/incubator-airflow/blob/master/airflow/operators/bash_operator.py#L81).

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Existing unit test converage.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by saguziel** [comment]
The env var name should be AIRFLOW_HOME not AIRFLOW_HOME_VAR

**Comment by saguziel** [comment]
I think

**Comment by saguziel** [comment]
Probably unquote. Can you link the BashOperator thing?

**Comment by john-bodley** [comment]
@saguziel I've added the requested link in the description.

**Comment by kaxil** [comment]
Can you please add Jira issue in your commit message?

**Pull request closed without merging**
