### PR TITLE
Use existing cached_property method to skip pylint error.

### PR DESCRIPTION
**Pull request by jhtimmins**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
The #16682 cherry-picking might be faster way :)

**Review by potiuk — APPROVED** [review]

**Review by potiuk — DISMISSED** [review]
I think it's a REAL problem not pylint

**Comment by jhtimmins** [comment]
@potiuk yeah it's trying to import from a file that doesn't exist without your pylint PR. So rather than merge in that PR now, I'm just having it reference the `cached_property` method from before your pylint chAnages.

**Comment by potiuk** [comment]
Yeah. I see - simply so far we usually solved those kind of problems by bringing-in all missing commits (@ashb  even had a magic git command to get the chain of commits needed). But it has some drawbacks (bringing more than needed sometimes. Just for consideration., I think bringing some refactors/tool commts make it more future-proof and easier to cherry-pick subsequent fixes if needed. I don't mind either, but I think final resul is better if we mostly stick to cherry-picking rather than fixing in-place.

**Comment by potiuk** [comment]
BTW. Those are not my pylint changes - the actual reason for that error is the https://github.com/apache/airflow/pull/15969 which introduced the compat shim

**Pull request closed without merging**
