### PR TITLE
[AIRFLOW-1571] Add AWS Lambda Hook

### PR DESCRIPTION
**Pull request by sid88in**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1571

### Description
- [x] Here are some details about my PR, no UI changes

Details of this PR are in the Jira above. 

### Tests
- [x] My PR adds the following unit tests 

1. test_aws_lambda_hook
This unit test uses moto to mock aws lambda. Firstly, we create a lambda function (assuming this function is already created by aws cloudformation template in production). Secondly, we trigger lambda function using invoke function in the hook. Lastly, we parse the response and assert statements.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by andyxhadji** [comment]
@ reviewer - As part of a larger design decision, how should we think about naming hooks extending the AwsHook base class?

e.g. here we name the file "AwsLambda", but elsewhere we call it by the service name without the "Aws" prefix - "S3Hook" instead of "AwsS3Hook". This is also relevant for the RedshiftHook PR (https://github.com/apache/incubator-airflow/pull/2717): "AwsRedshiftHook" vs. "RedshiftHook".

Just want to make sure our naming is consistent!

**Comment by sid88in** [comment]
@andyxhadji I concur with that. For aws related hooks/operators we should have consistent naming convention. For instance, google hooks start with gcp_* filename and GoogleCloudHookname  For the same reason for dynamodb I merged aws_dynamodb_hook and for Kinesis https://github.com/apache/incubator-airflow/pull/2586 its aws_kinesis_hook filenames and AwsHookname.

**Comment by andyxhadji** [comment]
Sounds good to me, I'll make a JIRA issue to address naming inconsistencies with current Aws hook extensions in order to follow that practice.

**Comment by sid88in** [comment]
@bolkedebruin would be great if you could please help review this?

**Comment by bolkedebruin** [comment]
Merged. Another idea is to merge all Aws hooks into one file, it is getting a bit messy now. Operators maybe as well.

**Comment by sid88in** [comment]
yay thanks @bolkedebruin !! Yes I agree that we should combine aws related hooks in 1 file. Will create a new PR to add aws related hooks  (EMR, DynamoDB and Lambda) in aws_hook.py.. once thats done, I am going to decline my PR https://github.com/apache/incubator-airflow/pull/2586 and submit a fresh PR with the hook. Once we start adding more operators we can take similar approach. thanks again

**Comment by andyxhadji** [comment]
Would having them all in one file be too lengthy? It also would be
inconsistent with the importing structure we have now (e.g. from
airflow.....S3_hook import S3Hook). Perhaps it makes sense to put them in
the same package? Is this general file organization something we'd want to
do with gcp as well (there seems to be more hooks for gcp than aws)?

**Comment by sid88in** [comment]
@andyxhadji you raise some good points. I think we should think about restructuring with @bolkedebruin .

**Pull request closed without merging**
