### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — CHANGES_REQUESTED** [review]
Can you double-check if you have some time to fix other spelling errors too -- since we just merged your [other PR](https://github.com/apache/airflow/pull/14472) 50 mins back.

Let's keep this one open for a while and fix all the remaining ones if you have time to save our CI build times -- since it touches core files and so all the tests are run

**Comment by jbampton** [comment]
Hey @kaxil  I have now 53 changed files on my local machine but when I run the pre-commit the `Run pylint for tests` never finishes as seen in the image.   I have tried committing twice.  It has been stuck for a couple of hours now.   There are a lot of files in the `tests` folder that have changed.

Screen Shot 2021-02-27 at 11 29 35 am

**Comment by kaxil** [comment]
@jbampton you can skip pylint by running following:

```
SKIP=pylint git commit
```

**Comment by potiuk** [comment]
@jbampton  Strange that it was stuck with pylint for hours. Could be you simply had some problems with disk space for docker or not enough memory reserved for docker (in case you used Mac). I recommend to check and increase them:  See https://github.com/apache/airflow/blob/master/BREEZE.rst#docker-community-edition 

And yeah - you can use SKIP or you can also run `git commit --no-verify` in case you hit this kind of problem. Pylint is deliberately put at the end for that purpose - to do other checks before, in case it has some problems like that.

**Review by kaxil — APPROVED** [review]

**Pull request merged**
