### PR TITLE
Deprecated kerberos auth removed

### PR DESCRIPTION
**Pull request by dirrao**
The following deprecated kerberos auth removed
1. airflow.auth.managers.fab.api.auth.backend.kerberos_auth
2. airflow.api.auth.backend.kerberos_auth

### CODE REVIEW

**Review by eladkal — DISMISSED** [review]
Breaking change must have news fragment to notify users what was removed and how to mitigate. In this case just alerting about module remove and how to set it up with fab provider

**Comment by dirrao** [comment]
> Breaking change must have news fragment to notify users what was removed and how to mitigate. In this case just alerting about module remove and how to set it up with fab provider

I have already added the news fragment. Am I missing anything?

**Review by potiuk — APPROVED** [review]

**Review by vincbeck — APPROVED** [review]

**Comment by potiuk** [comment]
@eladkal ?

**Comment by jscheffl** [comment]
Sorry, need to be another bad guy here. We said for Airflow 3 dev rules we must separate PRs for providers and stuff for the core. Assume we need to split this here as well. (1) for provider update and (2) for removing/breaking change in core.

(whereas I assume we don't plan to back-port to 2.10 so technically could be one PR?)

**Comment by dirrao** [comment]
> back-port to 2.10

@eladkal 
Let me know if you want me to separate core and providers.

**Comment by dirrao** [comment]
@eladkal / @jscheffl 
Do you want me to create separate PR for provider changes?

**Comment by vincbeck** [comment]
Yep I think it is needed. But we might actually want only core changes, breaking change in providers will result in creating major versions which we might not want yet. I'll let @eladkal confirm

**Comment by vincbeck** [comment]
@dirrao Could you please update this PR (or create another one) to include only changes from core?

**Comment by dirrao** [comment]
@vincbeck / @jscheffl 
Provider changes are dependent on the core. Not sure how to support the backward compatibility. Please take a look at the provider dependency.

**Comment by vincbeck** [comment]
Actually I think your changes are fine. It seems inevitable to force Airflow 3 to use the latest FAB version provider. See comment [here](https://github.com/apache/airflow/pull/42042#issuecomment-2333313742). If that is the case your changes are not breaking for providers. You back ported  `airflow/api/auth/backend/kerberos_auth.py` to `airflow/providers/fab/auth_manager/api/auth/backend/kerberos_auth.py` (am I right?) so FAB provider no longer depend on core Airflow for Kerberos auth (which is good). The only issue would be to use Airflow 3 with current version of FAB provider or earlier but, as mentioned, if this is something that will not be possible, I think these changes are fine. In this sense, these changes are not breaking for FAB provider.

**Review by vincbeck — APPROVED** [review]

**Comment by dirrao** [comment]
> Actually I think your changes are fine. It seems inevitable to force Airflow 3 to use the latest FAB version provider. See comment [here](https://github.com/apache/airflow/pull/42042#issuecomment-2333313742). If that is the case your changes are not breaking for providers. You back ported `airflow/api/auth/backend/kerberos_auth.py` to `airflow/providers/fab/auth_manager/api/auth/backend/kerberos_auth.py` (am I right?) so FAB provider no longer depend on core Airflow for Kerberos auth (which is good). The only issue would be to use Airflow 3 with current version of FAB provider or earlier but, as mentioned, if this is something that will not be possible, I think these changes are fine. In this sense, these changes are not breaking for FAB provider.

Yes, my changes are backward compatible. They will simply start using the FAB provider module instead of the deprecated core auth module.

**Comment by dirrao** [comment]
@potiuk / @eladkal
I'm awaiting final approval to proceed with the merge. Could you please take a look when you get a chance?

**Review by vincbeck — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by eladkal — COMMENTED** [review]
The commit message says removed deprecation but this PR also adds more functionality to the provider. Is the commit message right?

**Comment by vincbeck** [comment]
> The commit message says removed deprecation but this PR also adds more functionality to the provider. Is the commit message right?

The only code added to the provider is code moved from core to provider. There is no new functionality. I think the message is fair

**Comment by dirrao** [comment]
> > The commit message says removed deprecation but this PR also adds more functionality to the provider. Is the commit message right?
> 
> The only code added to the provider is code moved from core to provider. There is no new functionality. I think the message is fair

Yes. No new functionality added.

**Comment by eladkal** [comment]
> The only code added to the provider is code moved from core to provider. There is no new functionality. I think the message is fair

ok then I will modify the provider change log

**Pull request merged**
