### PR TITLE
Pass region name to superclass of AWSGlueJobHook

### LINKED ISSUE #14217: AWS GlueHook does not pass Region name to superclass constructor
https://github.com/apache/airflow/blob/e3bcaa3ba351234effe52ad380345c4e39003fcb/airflow/providers/amazon/aws/hooks/glue.py#L77

### PR DESCRIPTION
**Pull request by yohei1126**
Fix #14217 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by jhtimmins** [comment]
This fix works, but now you're setting `self.region_name` in both the child and the parent. Probably best to remove `self.region_name = region_name` from the child.

Could you also add a test for this? Just a simple test in https://github.com/apache/airflow/blob/master/tests/providers/amazon/aws/hooks/test_glue.py that instantiates the class and makes sure that `glue.region_name == <expected_value>` should be enough.

**Review by jhtimmins — APPROVED** [review]

**Comment by yohei1126** [comment]
There are some errors. 

https://github.com/apache/airflow/runs/1970983265
https://github.com/apache/airflow/runs/1970983080

```
Requirement already satisfied: zipp>=0.5 in /home/runner/.local/lib/python3.6/site-packages (from importlib-metadata->pre-commit) (3.4.0)
./scripts/ci/static_checks/run_static_checks.sh: /home/runner/.local/bin/pre-commit: /opt/hostedtoolcache/Python/3.6.12/x64/bin/python: bad interpreter: No such file or directory
```

**Comment by yohei1126** [comment]
@jhtimmins do you know why this failed?

**Comment by eladkal** [comment]
Thanks @yohei1126 
The issue was fixed in https://github.com/apache/airflow/pull/14251

**Pull request closed without merging**
