### PR TITLE
[AIRFLOW-3823] Exclude BranchPythonOperator choice's downstream tasks from the tasks to skip

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3823
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

An extensive description of this PR is given in https://issues.apache.org/jira/browse/AIRFLOW-3823.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Added 2 tests to test both BranchPythonOperator options in this edge case.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by Fokko — APPROVED** [review]
Looking good @BasPH 

@ashb Do you think we can cherry-pick this into 1.10.3?

**Comment by ashb** [comment]
Probably, yes.

Cherry picked, and #4215 which this change depended on, to the release branch.

**Comment by ashb** [comment]
@BasPH Something about this PR seems to make the tests fail reliably on the v1-10-test branch

https://travis-ci.org/apache/airflow/builds/491746735

The previous commit, of #4215, https://travis-ci.org/apache/airflow/builds/491746787 is passing the failing tests. Do you have any ideas? Have I messed up the cherry-pick, or is there an extra test dependency that I need to cherry-pick in that you know of?a

**Comment by BasPH** [comment]
Odd, at least it's consistently giving the same error:
```
[2019-02-11 17:58:31,425] {plugins_manager.py:149} ERROR - (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'airflow.task_instance' doesn't exist") [SQL: u'DELETE FROM task_instance WHERE task_instance.dag_id = %s'] [parameters: ('unit_tests',)] (Background on this error at: http://sqlalche.me/e/f405)
```

But I'm unsure at the moment what could cause it....?

**Comment by ashb** [comment]
Yeah - I've re-run it a few times too. I also noticed that the backfill test seems to be failing. But never on SQLite

**Comment by BasPH** [comment]
That's probably because the BackfillJobTest is excluded when SQLite is used :) https://github.com/apache/airflow/blob/master/tests/test_jobs.py#L139

**Comment by BasPH** [comment]
Thinking out loud: I remember seeing the exact same test failing while developing. It was on Python 2 only, because I did a string comparison `if isinstance(branch, str):` (https://github.com/apache/airflow/blob/v1-10-test/airflow/operators/python_operator.py#L133), which I then replaced by `if isinstance(branch, six.string_types):`.

Not sure why it's failing right now.

**Comment by Fokko** [comment]
That was a good catch Bas. Good to check:
```
MacBook-Pro-van-Fokko:incubator-airflow fokkodriesprong$ grep -R "isinstance(.*, str)" .
./airflow/contrib/sensors/jira_sensor.py:                    elif isinstance(field_val, str):
./airflow/contrib/hooks/bigquery_hook.py:        if not dataset_id or not isinstance(dataset_id, str):
```

**Comment by ashb** [comment]
I pulled in extra commits and this is passing now, so it'll be in 1.10.3 :)

**Comment by chadwgardner** [comment]
EDIT: Correction. I actually think this is a UI bug. When you click a task, the "Downstream" and "Recursive" options are enabled for the Clear option. But in 10.1.3, these options are (also? only?) tied to the Mark Failed option. So when I try to mark a single task as failed, all downstream tasks are mark as failed. Deselecting the "Downstream" and "Recursive" options then selecting Mark Failed will now only mark as failed the selected task, not all downstream tasks.

IGNORE:
I'm noticing some change in behavior in 1.10.3 that might be related to this. Forgive me if I'm totally off here. In 1.10.2, when you set a task to failed in the UI, all dependent downstream tasks would get skipped. Now, they all insta-fail, and even tasks which have all_done triggers are not running and are marked as failed, whereas in 1.10.2 they would execute. Bug? Feature? Or should I direct my observations elsewhere.
Thanks!

**Comment by ashb** [comment]
There was a UI bug that was fixed in 1.10.4 (or will be, when it's released) that those buttons were ignored/not behaving right.

Might be worth you trying `pip install apache-airflow==1.10.4rc3` and seeing if that behaves better.

**Comment by rika** [comment]
Hello, I started getting this behaviour when I updated my airflow from `1.10.11` to `1.10.12`.
I tested with the example in: https://issues.apache.org/jira/browse/AIRFLOW-3823
And it's skipping the t4 and t5 tasks.

**Pull request merged**
