### PR TITLE
[FEATURE] add 1.22 1.23 K8S support

### PR DESCRIPTION
**Pull request by raphaelauv**
Support of K8S 1.20  ended yesterday -> https://endoflife.date/kubernetes

### CODE REVIEW

**Comment by ashb** [comment]
End of life from Kube project, but still supported in Amazon EKS https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html and https://cloud.google.com/kubernetes-engine/docs/release-schedule

**Comment by potiuk** [comment]
> End of life from Kube project, but still supported in Amazon EKS https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html and https://cloud.google.com/kubernetes-engine/docs/release-schedule

Hmm. Do we care actually ?  Similarly as Python, we agreed to follow K8S EOL not EKS EOL.
I am not talking that we shoul not do it, but if we should possibly we should have a rule describing it . Do we care about EKS? GKS? others?  What would be the reasoning here?

Currently the change is very much in line with our rules: https://github.com/apache/airflow/blob/main/README.md#support-for-python-and-kubernetes-versions

(And I would even say it should be accompanied by addign 1.22 and and 1.23 too.

**Comment by potiuk** [comment]
Added "full tests needed" and closed/reopened to trigger test for more complete matrix combination

**Comment by potiuk** [comment]
Random failure on image building

**Comment by ashb** [comment]
In this case yes, I care a lot more. Updating python version for a single application is a lot easier than upgrading a whole cluster.

By doing this we make it that much harder for users to update.

So -1 to the removal of 1.20 while the big cloud providers still support it.

**Comment by raphaelauv** [comment]
But if you use a EKS or GKE , updating your K8S cluster is easy and fully managed by the cloud provider

**Comment by potiuk** [comment]
> > But if you use a EKS or GKE , updating your K8S cluster is easy and fully managed by the cloud provider
> 
> "Hi Central Infra Team? Yes I'd you you to upgrade our kubernetes cluster so I can update my app". There are plenty of companies where it would not play out well.

Can you raise it at the devlist @ashb  - this is a change to what we agreed to, so I think it should make it into a discussion in the devlist.

**Comment by potiuk** [comment]
Just to make it here - it was agreed here by the lazy consensus: https://lists.apache.org/thread/3m6hfxfhfhvo14kmhc38s2fgz1jfgz0y

**Comment by potiuk** [comment]
And to be perfectly clear. I think indeed it makes sense to keep it a bit longer but we need to propos some rules for it :). For example support by major K8S cluster providers might be a good rule to have.

**Comment by potiuk** [comment]
The Kubernetes Upgrade for all the versions takes more than 80m so you should increase it in the `ci.yml` - it woudl be great to add the rule above to README in the same PR @raphaelauv :)

**Comment by raphaelauv** [comment]
@potiuk I've made the changes

**Review by potiuk — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
