### PR TITLE
[AIRFLOW-223] Make parametrable the IP on which Flower binds to

### PR DESCRIPTION
**Pull request by dud225**
Hello

I'd be glad if Flower could be set to bind to localhost only as could be done for Gunicorn.
dud

### CODE REVIEW

**Comment by criccomini** [comment]
This requires a look from @aoen @mistercrunch @artwr @plypaul

**Comment by aoen** [comment]
LGTM, has this been tested?

**Comment by dud225** [comment]
Yes I'm using this feature. Here are some tests :

```
# CLI test :
$ grep flower_host airflow/airflow.cfg -c
0
$ airflow flower
[...]
[I 160615 12:35:59 command:136] Visit me at http://0.0.0.0:5555

$ airflow flower -hn 127.0.0.1
[...]
[I 160615 12:37:44 command:136] Visit me at http://127.0.0.1:5555

# Configuration file test :
$ grep flower_host airflow/airflow.cfg 
flower_host = 127.0.0.1
$ airflow flower
[...]
[I 160615 12:44:07 command:136] Visit me at http://127.0.0.1:5555
```

**Comment by aoen** [comment]
Thanks! LGTM.

**Pull request merged**
