### PR TITLE
[AIRFLOW-1987] Fix error in query for MS Sql Server

### PR DESCRIPTION
**Pull request by patsak**
MS Sql Server doesn't support boolean field in SQL expression

Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1987

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Can you retrgger the build (close/open or empty commit) to see if it passes the tests?

**Comment by bolkedebruin** [comment]
This seems not be be postgres compatible?

**Comment by Fokko** [comment]
Postgres translates this to an assignment:
```
   ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: boolean = integer
   LINE 3: ...fill_%') AND (dag.dag_id IS NULL OR dag.is_paused = 0) AND t...
                                                                ^
   HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
    [SQL: 'SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance.pid AS task_instance_pid \nFROM task_instance LEFT OUTER JOIN dag_run ON dag_run.dag_id = task_instance.dag_id AND dag_run.execution_date = task_instance.execution_date LEFT OUTER JOIN dag ON dag.dag_id = task_instance.dag_id \nWHERE task_instance.dag_id IN (%(dag_id_1)s, %(dag_id_2)s, %(dag_id_3)s, %(dag_id_4)s, %(dag_id_5)s, %(dag_id_6)s, %(dag_id_7)s, %(dag_id_8)s, %(dag_id_9)s, %(dag_id_10)s, %(dag_id_11)s, %(dag_id_12)s, %(dag_id_13)s, %(dag_id_14)s, %(dag_id_15)s, %(dag_id_16)s, %(dag_id_17)s, %(dag_id_18)s) AND (dag_run.run_id IS NULL OR dag_run.run_id NOT LIKE %(run_id_1)s) AND (dag.dag_id IS NULL OR dag.is_paused = %(is_paused_1)s) AND task_instance.state IN (%(state_1)s)'] [parameters: {'state_1': 'scheduled', 'dag_id_18': 'example_skip_dag', 'dag_id_7': 'example_python_operator', 'dag_id_8': 'test_utils', 'dag_id_15': 'latest_only', 'dag_id_3': 'example_trigger_controller_dag', 'dag_id_12': 'example_http_operator', 'dag_id_14': 'example_short_circuit_operator', 'dag_id_10': 'example_subdag_operator.section-1', 'is_paused_1': 0, 'dag_id_4': 'latest_only_with_trigger', 'dag_id_17': 'example_subdag_operator.section-2', 'dag_id_6': 'example_branch_operator', 'dag_id_1': 'example_subdag_operator', 'dag_id_16': 'example_bash_operator', 'dag_id_9': 'tutorial', 'dag_id_11': 'example_trigger_target_dag', 'run_id_1': 'backfill_%', 'dag_id_13': 'example_branch_dop_operator_v3', 'dag_id_2': 'example_passing_params_via_test_command', 'dag_id_5': 'example_xcom'}]
```
Really weird stuff. For me, the idiomatic sqlalchemy operators,`~` and `not(...)` are easier to read, than the assertions with zero. This feels to me more like a bug in the orm-layer.

**Comment by patsak** [comment]
I agree this problem more likely for the orm layer and try to solve it in application layer it is not a good idea. So this pull request is not actual.

**Comment by Fokko** [comment]
Maybe you can check if this has been solved in a later version of sqlalchemy, and bump the version number.

**Comment by r39132** [comment]
@patsak Kindly look into making a change to sqlalchemy instead of airflow. Closing for now.

**Pull request closed without merging**
