### PR TITLE
[AIRFLOW-5903] Remove serve_logs command from CLI

### PR DESCRIPTION
**Pull request by mik-laj**
I wanna remove the ``serve_logs`` command. This command should be run only by internal application mechanisms and there is no need for it to be accessible from the CLI interface.

---

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by potiuk — COMMENTED** [review]
It seems indeed it is not needed - but maybe there are some uses that we have not thought about. I wonder what others think about it ?

**Comment by mik-laj** [comment]
This command was always run when executing the `` airflow worker`` command.  The option to disable autostart of this server has been introduced recently, so we can assume that everyone who starts worker must have this port free.  These logs should be shared from workers, so no one could technically run it without playing with strict process isolation (linux net namespace) and other tricks.

**Comment by msumit** [comment]
In general, it makes sense as no one would be using it in its standalone form anyway. However, I don't see any valid problem statement behind removing this functionality.

**Comment by potiuk** [comment]
@msumit -> if the "serve logs" command is really not used anywhere, then I think @mik-laj  is right - we should remove it. The valid problem we solve this way is "we have to maintain this code even if it's not used so let's remove it".

Removing unused code is one of the best things an engineer can do to improve the project's quality. It increases test coverage, makes the code more maintainable, smaller, easier to refactor.

Code is usually liability not an asset.

**Review by msumit — APPROVED** [review]

**Comment by potiuk** [comment]
@mik-laj -> one test is failing :)

**Comment by mik-laj** [comment]
I want to delete it because it makes using CLI difficult. Many people read CLI documentation and find commands that they cannot use in any way.

**Review by ashb — APPROVED** [review]

**Comment by aoen** [comment]
Yeah makes sense, thanks!

**Comment by mik-laj** [comment]
This PR has an error. I should also delete serve_logs from the `airflow/bin/cli.py` file

**Pull request merged**
