### PR TITLE
Bust pre-commit cache on v1-10-test branch

### PR DESCRIPTION
**Pull request by ashb**
---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
(I'm not sure at all if this is the right fix or not, but thought I'd try it)

**Comment by ashb** [comment]
https://github.com/apache/airflow/runs/699984569?check_suite_focus=true is the problem I was dealing with

**Comment by potiuk** [comment]
It was deliberately set to 3.5 on 1.10 - because by default the static checks for MyPy and I believe for flake the "compatibility" level is set by default to the version it runs on and w wanted to run py3.5 compatibility check.  

I think the problem looks awfully like a GA cache problem. We are caching the pre-commit environment. and possibly something went wrong with restoring that cache. The tests that failed were not even using the PYTHON_MAJOR_MINOR version because they were running on the host and PYTHON_MAJOR_MINOR_VERSION is only used for the container for CI.

I think that could have been a temporary solution and it should be working now - the same as it is working now for the builds.

**Comment by ashb** [comment]
yeah, I thought this might be deliberate, bit wondered if it was a pre-commit 1 vs 2 problem.

**Comment by ashb** [comment]
Updated to just bust cache.

**Comment by ashb** [comment]
@potiuk Think this is worth merging anyway? Appears to be just a single random failure now.

**Comment by ashb** [comment]
Tests were failing with the same timing issue I'd fixed in #8405 -- so I've just backported that to v1-10-test

**Review by kaxil — APPROVED** [review]

**Pull request merged**
