### PR TITLE
feat(chart): add security context on container levels

### PR DESCRIPTION
**Pull request by anja-istenic**
It is recommended practice to give a resource (pod/container) the least privileges it needs. The Airflow Helm Chart already supports configuring the security context on the pod level. This PR adds the `securityContext` configurations on the container level ([more info on container level securityContext here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)).

This change is fully backwards compatible, as the `securityContext` value configuration is optional and defaults to `{}`

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by anja-istenic** [comment]
@dstandish @jedcunningham would appreciate any feedback on this PR :)

**Comment by anja-istenic** [comment]
@potiuk @jedcunningham @dstandish @kaxil any feedback or review would be much appreciated

**Comment by potiuk** [comment]
This looks good to me, but I woudl love the others to take a look too :)

**Review by potiuk — APPROVED** [review]

**Comment by jedcunningham** [comment]
(I'd argue this is a duplicate of #24588)

**Comment by potiuk** [comment]
> (I'd argue this is a duplicate of https://github.com/apache/airflow/pull/24588)

So I guess we need to suggest some way forward @jedcunningham :) to @ChrisFraun and @anja-istenic - which one should we move forward? Or maybe @ChrisFraun and @anja-istenic  you can review each other's PR and agree between yourselves which one should proceed (either of the two needs rebase to follow).

**Comment by anja-istenic** [comment]
> So I guess we need to suggest some way forward @jedcunningham :) to @ChrisFraun and @anja-istenic - which one should we move forward? Or maybe @ChrisFraun and @anja-istenic you can review each other's PR and agree between yourselves which one should proceed (either of the two needs rebase to follow).

Thanks all for reviewing this. While I was out @ChrisFraun added the extra changes from this PR to https://github.com/apache/airflow/pull/24588, I'm therefore closing this now redundant PR.

**Pull request closed without merging**
