### PR TITLE
Disabled edit button in task instances list view page

### LINKED ISSUE #20655: Edit Task Instance Page does not save updates.
### Apache Airflow version

main (development)

### What happened

On the Task Instances table, one can click on `Edit Record` and be directed to a `Edit Task Instance` page. There, if you try to change the state, it will simply not update nor are there any errors in the browser console.

Screen Shot 2022-01-04 at 10 10 52 AM

### What you expected to happen

Changes to state should actually update the task instance.

### How to reproduce

Try to use the `Edit Task Instance` page

### Operating System

Mac OSx

### Versions of Apache Airflow Providers

_No response_

### Deployment

Virtualenv installation

### Deployment details

_No response_

### Anything else

This page is redundant, as a user can successfully edit task instance states from the table. Instead of wiring up the correct actions, I say we should just remove the `Edit Task Instance` page entirely.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by subkanthi**
closes: #20655 
Screen Shot 2022-01-04 at 5 59 45 PM

Disabled edit button in List Task Instance page, tested all the action buttons.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Review by kaxil — COMMENTED** [review]
Will this change allow clearing the TIs now from the List TIs page?

Can you confirm, please?

**Comment by subkanthi** [comment]
> 



> Will this change allow clearing the TIs now from the List TIs page?
> 
> Can you confirm, please?

Yes it does.
Screen Shot 2022-01-05 at 6 52 05 AM

**Review by bbovenzi — APPROVED** [review]

**Comment by dmishh** [comment]
Code changes in this PR removed all bulk actions for TIs except for Delete. This is a huge mistake https://github.com/apache/airflow/pull/20659/files#diff-917b70d2661fae8322c538a4f60b9d4ba755556036fe0c527eb0411a6ac60f2eL4370

Airflow 2.2.3 - TI's bulk actions in place (https://github.com/apache/airflow/blob/2.2.3/airflow/www/views.py#L4227)
Airflow 2.3.3 - TI's bulk actions are missing (https://github.com/apache/airflow/blob/2.3.3/airflow/www/views.py#L5011)

**Comment by dmishh** [comment]
More than that, the Edit action is available in 2.3.3. So this PR just removed a very useful feature of TI bulk clearing.
cc @kaxil @uranusjr @bbovenzi

**Comment by ashb** [comment]
@dmishh You could ask for this back in a much _much_ nicer way. Please be considerate of the volunteer time of OSS authors

https://xkcd.com/1172/

**Comment by dmishh** [comment]
@ashb I highly appreciate everyone's time and effort, but what's wrong with calling mistake a mistake? The "huge" correlates with the fact that @kaxil directly asked (which is a fantastic call) whether this will break the clearing functionality and the answer was "no, it won't".

**Comment by potiuk** [comment]
> @ashb I highly appreciate everyone's time and effort, but what's wrong with calling mistake a mistake? The "huge" correlates with the fact that @kaxil directly asked (which is a fantastic call) whether this will break the clearing functionality and the answer was "no, it won't".

@dmishh - let me explain what I think @ashb had in mind (or at least how I feel it as it is close to what I feel when I read your comment).  The way you expressed it, looked like the whole change was a huge mistake. I believe (also knowing Ash) he did not complain on naming things a mistake but about your way of communicating and asking for it.

For example If you had started your first comment with "I highly appreciate everyone's time and effort and I see how much this PR improved, but it also mistakenly removed this and that" - that would be much nicer way to say what you possibly wanted to say (looking at your secondd comment you do appreiciate the work but it was not seen from the first comment. 
It's very difficult to express the feelings in a written form when you write a comment in PR and I think learning it is an art.

**Comment by dmishh** [comment]
@potiuk @ashb Folks, I really didn't want to hurt anyone's feelings. Contributing to open source is a pure act of love - giving away your energy for the sake of creating some good stuff. I know what it takes, and I genuinely appreciate everyone's effort in creating free software.

My directness might sound a bit harsh, especially reading the comment without the details below, but I did it with respect and appreciation. I was as precise as possible when describing an issue - in my opinion, all the changes in this PR should be amended: the PR removed an important feature and the main piece of code that was supposed to do what was required is reverted now (in 2.3.3 at least). Also, the way the initial problem was fixed is something like "the wheel doesn't spin - let's remove it instead of lubricating".

**Comment by potiuk** [comment]
It's easy to criticise. Much more difficult to express it in the way that shows respect while doing it. The last comment shows respect. The first did not. That's as simple as that. Try better next time. Contributing is a live-long learning (for me for sure) so you have a chance to show respect next time when you criticise something. No hard feelings.

**Pull request merged**
