### PR TITLE
[AIRFLOW-4524] Improve checkbox logic to restore functionality

### PR DESCRIPTION
**Pull request by jmeickle**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-4524

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by jmeickle** [comment]
@ashb This doesn't completely fix the underlying issue (of reusing variable names within the same form and/or needing to split the form); but we do need this sort of helper function to properly read checkbox state. Is it OK to merge?

**Comment by ashb** [comment]
Looking at this now.

**Comment by ashb** [comment]
I think the issue was I messed up the cherry pick on to 1.10.3 as this only applies to the RBAC tree on v1-10-stable I think. Master just contains a single in put named "ingore_all_deps", as does the non-RBAC tree in 1.10.3.

In `airflow/www_rbac/templates/airflow/dag.html` I somehow added

```
            <input type="hidden" name="ignore_all_deps">
            <input type="hidden" name="ignore_ti_state">
            <input type="hidden" name="ignore_task_deps">
```

which doesn't exist on any other branch or commit. I have _no_ idea where I got that from to commit it.

**Comment by ashb** [comment]
Closing in favour of #5378

**Pull request closed without merging**
