### PR TITLE
[DO NOT MERGE - JUST FOR APPROVAL] Prepare 2.0.3 release

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
@kaxil @ashb  -> this is mainly about dependency update (just generated newest constraints with PIP 21). The rest is mainly scripts sync + https://github.com/apache/airflow/pull/13247  which seems to be critical (and it was cherry-picked before to v2-0-test). My question is do we want even this one or are there any more critical fixes worthy of adding to 2.0.3 ?

**Comment by kaxil** [comment]
Hey, Am on leave this week so won't be able to do a detailed review, will check back on Sat /Sun. 

Just looking at included commit titles from mobile seems GOOD but will let Ash review it in detail

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
looks like getting green this time!

**Comment by potiuk** [comment]
Random failure -: @ashb do you want to take a look? 

Just to be sure I run this `git log --oneline  2.0.2..HEAD -- airflow/` to filter out only `airflow` changes 
```
492f84322 Adds interactivity when generating provider documentation. (#15518)
4423ea7fc Use Pip 21.* to install airflow officially (#15513)
ecff91caa Clarifies installation/runtime options for CI/PROD images. (#15320)
19e41577f Fix critical CeleryKubernetesExecutor bug (#13247)
```

And then `git show --oneline  2.0.2..HEAD -- airflow/` (and filtered out provider changes that were part of some doc fixes) - and those are the changes. 

They are mainly about:

*  "provider.schema" new field (not used in airflow, we have runtime schema in airflow). Part of the PIP 21 change for providers.
*  Remove PIP warning from README
* pylint exclusion fixes to make new version of pylint happy
* the default value for timeout (30.0 -> 30) change was needed to make migration from 1.10 working smooth (the timeout was int in 1.10 and in some tests it failed for our builds. I can revert this default one for 2.0.3 if needed but I think it is very safe). 
* the only real fix - the critical fix to CeleryKubernetesExecutor

```
4423ea7fc Use Pip 21.* to install airflow officially (#15513)
diff --git a/airflow/provider.yaml.schema.json b/airflow/provider.yaml.schema.json
index bdec41dc3..458ee2ef2 100644
--- a/airflow/provider.yaml.schema.json
+++ b/airflow/provider.yaml.schema.json
@@ -191,6 +191,10 @@
       "items": {
         "type": "string"
       }
+    },
+    "additional-extras": {
+      "type": "object",
+      "description": "Additional extras that the provider should have"
     }
   },
   "additionalProperties": false,
diff --git a/airflow/providers/apache/beam/README.md b/airflow/providers/apache/beam/README.md
index 34f2863b5..d9294d2c1 100644
--- a/airflow/providers/apache/beam/README.md
+++ b/airflow/providers/apache/beam/README.md
@@ -41,14 +41,6 @@ are in `airflow.providers.apache.beam` python package.
 
 ## Installation
 
-NOTE!
-
-On November 2020, new version of PIP (20.3) has been released with a new, 2020 resolver. This resolver
-does not yet work with Apache Airflow and might lead to errors in installation - depends on your choice
-of extras. In order to install Airflow you need to either downgrade pip to version 20.2.4
-`pip install --upgrade pip==20.2.4` or, in case you use Pip 20.3, you need to add option
-`--use-deprecated legacy-resolver` to your pip install command.
-
 You can install this package on top of an existing airflow 2.* installation via
 `pip install apache-airflow-providers-apache-beam`
 
diff --git a/airflow/providers/apache/hive/transfers/mssql_to_hive.py b/airflow/providers/apache/hive/transfers/mssql_to_hive.py
index 5e5af8c5d..090a70285 100644
--- a/airflow/providers/apache/hive/transfers/mssql_to_hive.py
+++ b/airflow/providers/apache/hive/transfers/mssql_to_hive.py
@@ -15,7 +15,7 @@
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
-
+# pylint: disable=no-member
 """This module contains operator to move data from MSSQL to Hive."""
 
 from collections import OrderedDict
diff --git a/airflow/providers/microsoft/mssql/hooks/mssql.py b/airflow/providers/microsoft/mssql/hooks/mssql.py
index 4acdb52d1..928d0c45d 100644
--- a/airflow/providers/microsoft/mssql/hooks/mssql.py
+++ b/airflow/providers/microsoft/mssql/hooks/mssql.py
@@ -15,6 +15,7 @@
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
+# pylint: disable=no-member
 """Microsoft SQLServer hook module"""
 
 import pymssql
ecff91caa Clarifies installation/runtime options for CI/PROD images. (#15320)
diff --git a/airflow/config_templates/config.yml b/airflow/config_templates/config.yml
index c92acf8d2..cbb90a6bb 100644
--- a/airflow/config_templates/config.yml
+++ b/airflow/config_templates/config.yml
@@ -242,7 +242,7 @@
       version_added: ~
       type: float
       example: ~
-      default: "30.0"
+      default: "30"
     - name: dagbag_import_error_tracebacks
       description: |
         Should a traceback be shown in the UI for dagbag import errors,
diff --git a/airflow/config_templates/default_airflow.cfg b/airflow/config_templates/default_airflow.cfg
index bc4d54a0b..0b1aa493b 100644
--- a/airflow/config_templates/default_airflow.cfg
+++ b/airflow/config_templates/default_airflow.cfg
@@ -147,7 +147,7 @@ fernet_key = {FERNET_KEY}
 donot_pickle = True
 
 # How long before timing out a python file import
-dagbag_import_timeout = 30.0
+dagbag_import_timeout = 30
 
 # Should a traceback be shown in the UI for dagbag import errors,
 # instead of just the exception message
19e41577f Fix critical CeleryKubernetesExecutor bug (#13247)
diff --git a/airflow/executors/celery_kubernetes_executor.py b/airflow/executors/celery_kubernetes_executor.py
index 721db317b..b5146801a 100644
--- a/airflow/executors/celery_kubernetes_executor.py
+++ b/airflow/executors/celery_kubernetes_executor.py
@@ -38,6 +38,7 @@ class CeleryKubernetesExecutor(LoggingMixin):
 
     def __init__(self, celery_executor, kubernetes_executor):
         super().__init__()
+        self._job_id: Optional[str] = None
         self.celery_executor = celery_executor
         self.kubernetes_executor = kubernetes_executor
 
@@ -54,11 +55,31 @@ class CeleryKubernetesExecutor(LoggingMixin):
         """Return running tasks from celery and kubernetes executor"""
         return self.celery_executor.running.union(self.kubernetes_executor.running)
 
+    @property
+    def job_id(self):
+        """
+        This is a class attribute in BaseExecutor but since this is not really an executor, but a wrapper
+        of executors we implement as property so we can have custom setter.
+        """
+        return self._job_id
+
+    @job_id.setter
+    def job_id(self, value):
+        """job_id is manipulated by SchedulerJob.  We must propagate the job_id to wrapped executors."""
+        self._job_id = value
+        self.kubernetes_executor.job_id = value
+        self.celery_executor.job_id = value
+
     def start(self) -> None:
         """Start celery and kubernetes executor"""
         self.celery_executor.start()
         self.kubernetes_executor.start()
 
+    @property
+    def slots_available(self):
+        """Number of new tasks this executor instance can accept"""
+        return self.celery_executor.slots_available
+
     def queue_command(
         self,
         task_instance: TaskInstance,
```

**Comment by ashb** [comment]
Can you explain the timeout thing? I don't see how changing the default back to an int will change much of anything, given the int value will already exist in user's config files.

**Comment by potiuk** [comment]
> Can you explain the timeout thing? I don't see how changing the default back to an int will change much of anything, given the int value will already exist in user's config files.

Sure. I can't recall the exact scenario right now, but it was more because of errors generated when building/testing the providers. The change is part of the "Fix a problem with building PROD image". As I remember what happens is that when we install Airflow 1.10.* in the CI image prepared for 2.0, the config file was present and the migration was using 1.10 code to read it. However, I am happy to restore the original values in this change and I will see if I can reproduce the problem in master and will fix it there as well differently (just removing the generated airflow config should do the trick).. I see the point where the "30.0" value indicates that you can add fractional values is better than "30". This will anyhow become non-issue very soon when we stop supporting 1.10 entirely.

> There are more commits here than I would have expected -- for instance seem uncnecsarry on first glance:
> 
> [9389e95](https://github.com/apache/airflow/commit/9389e95090e079edc5ac0b3df22c59b31aa9fae3)
> [0963ecd](https://github.com/apache/airflow/commit/0963ecd5b5de99605451297b5db1f04a25190472)
> [492f843](https://github.com/apache/airflow/commit/492f843225f05b5bfbe8e17401da1181473f9621) (we don't build providers from release branch)

This is mainly because some of the files in those changes (like breeze/scripts) are common with other updates which were necessary (mainly because of optimisations of Docker image building  (limiting number of layers) and PIP 21 compliance (changes to some common scripts where we excluded beam etc.). This is FAR easier to cherry-pick all those changes to relevant files rather than trying to only cherry-pick the docker building stuff (it would lead to conflicts and possibly the changes will end-up there anyway but in non-relevant commits).

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
Actually - I will simply remove 1.10 support from masterr breeze altogether. Highest time.

**Comment by potiuk** [comment]
Hey @ashb @kaxil, I also reviewed the 2.0.3 milestone, and noticed quite a few issues that were already marked with 2.0.3. I reviewed them all and applied those that were cleanly cherry-pickable, were simple and had good test coverage. 

I removed the 2.0.3 milestone from  some of the issues that were not easy to cherry pick. Those non-cherry-pickable are mostly UI-related, there are some changes in master branch that make them more difficult to cherry-pick so I left them for 2.1).

**Review by YoutacRSVARs — APPROVED** [review]

**Comment by potiuk** [comment]
BTW. I run './airflow-github compare 2.0.3 <TOKEN> and those are the resutts:

The two "unmerged" ones are actually closed and solved by other issues (but I updated them in the changelog)

Screenshot from 2021-05-09 19-50-02

**Comment by potiuk** [comment]
Closing this one as we decided to release `2.1` instead.

**Pull request closed without merging**
