### PR TITLE
[AIRFLOW-1558] Py3 fix for S3FileTransformOperator

### PR DESCRIPTION
**Pull request by awentzonline**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1558

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

The temporary files created by this operator have `mode == 'w'` but boto returns bytes.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
 * Tests that `execute` works as expected

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by nehiljain — APPROVED** [review]

**Comment by bolkedebruin** [comment]
Add test please thanks!

**Comment by bolkedebruin** [comment]
Can you make sure tests pass and rebase? Then I can merge.

**Comment by awentzonline** [comment]
Turns out there are a few py3 incompatibilities here. I'll update this PR as time allows.

**Comment by ron819** [comment]
@awentzonline  any news on that?

**Pull request closed without merging**
