### PR TITLE
Fix main failing on wrong inheritance hierarchy

### PR DESCRIPTION
**Pull request by potiuk**
Introduced by ##20332

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Failed with 

tests/core/test_core_to_contrib.py::TestMovingCoreToContrib::test_is_subclass_256_airflow_providers_amazon_aws_operators_ecs_ECSOperator: TypeError: Protocols can only inherit from other protocols, got <class 'airflow.providers.amazon.aws.operators.ecs.ECSProtocol'>

tests/core/test_core_to_contrib.py::TestMovingCoreToContrib::test_warning_on_import_256_airflow_providers_amazon_aws_operators_ecs_ECSOperator: TypeError: Protocols can only inherit from other protocols, got <class 'airflow.providers.amazon.aws.operators.ecs.ECSProtocol'>

**Comment by potiuk** [comment]
No-one fault - selective checks did not run the tests as it is "provider-only" change (theorethically).

**Comment by ashb** [comment]
But `ECSProtocol` is a protocol...

**Comment by potiuk** [comment]
> But `ECSProtocol` is a protocol...

I know . But It helped for now. I tihnk there is some problem with the type check. Since it is a deprecated class, I preferred to quickly fix it for now.

**Comment by uranusjr** [comment]
So is `EcsProtocol`. By inheriting from `EcsProtocol`, `ECSProtocol` is already automatically a protocol, and inheriting from `Protocol` is redundant either way.

**Comment by potiuk** [comment]
```
        for base in cls.__bases__:                                                                                                                                                                                                                                                                               
            if not (base in (object, Generic) or                                                                                                                                                                                                                                                                 
                    base.__module__ == 'collections.abc' and                                                                                                                                                                                                                                                     
                    base.__name__ in _PROTO_WHITELIST or                                                                                                                                                                                                                                                         
                    isinstance(base, _ProtocolMeta) and base._is_protocol):                                                                                                                                                                                                                                      
                raise TypeError('Protocols can only inherit from other'                                                                                                                                                                                                                                          
>                               ' protocols, got %r' % base)                                                                                                                                                                                                                                                     
E               TypeError: Protocols can only inherit from other protocols, got <class 'airf
```

**Comment by uranusjr** [comment]
I’m going to close this one since this is only a subset of #20670, and we should choose from either it or #20699 instead.

**Comment by eladkal** [comment]
> No-one fault - selective checks did not run the tests as it was "provider-only" change (theorethically).

yep https://github.com/apache/airflow/pull/20332 had a green build.
We need `test_core_to_contrib` to run also on any change in `providers`.
I think also this file name is a bit misleading.. it has also entries for stuff other than contrib. it's more like a general deprecation check.

**Comment by potiuk** [comment]
> > No-one fault - selective checks did not run the tests as it was "provider-only" change (theorethically).
> 
> yep #20332 had a green build. We need `test_core_to_contrib` to run also on any change in `providers`. I think also this file name is a bit misleading.. it has also entries for stuff other than contrib. it's more like a general deprecation check.

Agree - we even have a special category for that "Always" :)

**Comment by potiuk** [comment]
PR in #20691

**Pull request closed without merging**
