### PR TITLE
[AIRFLOW-4200][AIP-3-subtask-4] Remove all __future__ imports

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4200
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by Fokko** [comment]
Can you rebase onto master?

**Comment by zhongjiajie** [comment]
CI failed because our CI process have py2 envirement, I submit a PR https://github.com/apache/airflow/pull/5090 to remove them. @Fokko

**Comment by Fokko** [comment]
It looks like the K8s tests still use Python 2.7:
```
+ airflow initdb
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python2.7/dist-packages/airflow/__init__.py", line 36, in <module>
    from airflow import settings, configuration as conf
  File "/usr/local/lib/python2.7/dist-packages/airflow/settings.py", line 32, in <module>
    from airflow.utils.sqlalchemy import setup_event_handlers
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils/sqlalchemy.py", line 22, in <module>
    import json
  File "/usr/local/lib/python2.7/dist-packages/airflow/utils/json.py", line 27, in <module>
    class AirflowJsonEncoder(json.JSONEncoder):
AttributeError: 'module' object has no attribute 'JSONEncoder'
```

**Comment by zhongjiajie** [comment]
CI green, PTAL @Fokko @potiuk @XD-DENG thanks.

**Review by potiuk — APPROVED** [review]

**Comment by zhongjiajie** [comment]
Thanks @potiuk

**Pull request merged**
