### PR TITLE
Refactor Breeze to group related methods and classes together

### PR DESCRIPTION
**Pull request by potiuk**
This change refactors Breeze classes to more consistent approach.

* The "commands" package only contains commands
* All Parameters (BuildCi, BuildProd, BuildDoc, Shell) are now
  in "params" package
* Required/Optional Build args are now members of the
  BuildCiParams, BuildProdParams which makes the params
  much more self-contained..
* All utils are in "utils" package

This helps with avoiding circular imports (all utios are now
standalone and do not use any of the commands.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc; @Bowrna @edithturn - FYI. the usual step in development process is that when things grow, we need to take a look at what we have and reshufs hifle/refactor things around to cleanup/standardize/commonalize. 

We got to the point when there were slightly different approaches in a few places and some decisions about structuring the code and package structure have to be revised.

This is that kind of change. I looked from the top and tried to determine which classes/packages/methods are actually coupled and should be put together and which are probably unnecessarily put together because they are decoupled really and only accidentally grouped together with others.

Also what helps in such project that we do not have too many "deep nesting" in packages - especially if different part of the code tree have different "depth". 

This change is the result of such review - it practically only reshuffles code around without changing any functionality - but the resulted structure is way more "intutitive" - usually when you modify a functionality you will have to modify one module or package only and things that are coupled and likely modified together are actually put together (for example you can see that required and optional args became fields of BuildCIParams/BuildProdParams because they are tightly coupled.

You might want to take a look at some of the decisions I made there.

**Comment by potiuk** [comment]
I am also reviewing the result and find a few more functiona that we can/should move (will get some fixups in a moment)

**Comment by Bowrna** [comment]
@potiuk Cool :) I am learning a lot by reading the changes you made.

**Comment by potiuk** [comment]
Few more renames and a bit of shuffling around. I think I am happy with it now.

**Comment by potiuk** [comment]
All seems good :)

**Review by eladkal — APPROVED** [review]

**Pull request merged**
