### PR TITLE
Clean up the pre-commit config file

### PR DESCRIPTION
**Pull request by jbampton**
Standardize YAML file extensions

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
Not worth it, if we have to specify the alternate config file for various tools.

**Comment by jbampton** [comment]
What about all the other fixes ?   Seems you were a bit too quick closing this down.

refs #15681

**Comment by jbampton** [comment]
Hey @potiuk can you please do a proper review ?

**Comment by potiuk** [comment]
Hey @jbampton. I think @ashb was perfectly right -looking at the scope of it and especially commit message. The commit message is "Standardize YAML file extensions" and here I agree with @ashb it is not need/harmless. Can you please open separate PR with just the config file fixes?

**Pull request closed without merging**
