### PR TITLE
99 is using airflow in production environment :)

### PR DESCRIPTION
**Pull request by fbenevides**
adding [99](https://99taxis.com) on company list.

### CODE REVIEW

**Comment by msumit** [comment]
@fbenevides Thanks for the contribution. But the PR and commit message aren't following the standard practises. Plz see the contribution guide [here](c1b78b7972e13c22c997f1f6e499ecce4314eb76), specially the last section.

**Comment by r39132** [comment]
Specifically, a commit message in the active voice that is within the recommended character count for message subject and body. For example, "[AIRFLOW-XXX] Add 99 to the Companies list." Yes, this means that you do need to open a JIRA for this, since we track all PRs via JIRA.

**Comment by fbenevides** [comment]
@msumit @r39132 ok. I got it. Thanks for the reply, I'll change that :)

**Comment by r39132** [comment]
Cool. Though a trivial commit, we want to introduce contributors to our review-for-merge protocol. We generate release notes from the commit subject lines, so adherence to our protocols pays forward.

**Comment by r39132** [comment]
@fbenevides Any updates?

**Comment by r39132** [comment]
This PR looks dead. I will go ahead and correct the issues when I merge it.

**Comment by fbenevides** [comment]
@r39132 sorry for the delay. i'm going to fix it today! ok?

**Comment by r39132** [comment]
No worries -- it's merged, but please be aware of our commit guidelines on future commits. Welcome to the community.
-s

**Pull request closed without merging**
