### PR TITLE
Change Log to DEBUG level for SQL Statement in DBApiHook

### LINKED ISSUE #9638: Airflow Logging Sensitive Information
The Snowflake hook (and more accurately the dbapihook) logs sensitive information that is retrieved from the Airflow connections metadata. This happens by both the logger and the logging that comes with the cursor itself that fires the SQL commands. 
This part of the code I believe is the offender: (dbapi_hook.py/ run function)
```         with closing(conn.cursor()) as cur:
                for s in sql:
                    if sys.version_info[0] < 3:
                        s = s.encode('utf-8')
                    if parameters is not None:
                        self.log.info("{} with parameters {}".format(s, parameters))
                        cur.execute(s, parameters)
                    else:
                        self.log.info(s)
                        cur.execute(s)
```

I posted this issue on the official Slack channel and I was told to bring this issue up here. Would be great if we could mask this kind of information from being printed to the logs.

### PR DESCRIPTION
**Pull request by kaxil**
closes https://github.com/apache/airflow/issues/9638

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by kaxil** [comment]
cc @davido912

**Comment by mik-laj** [comment]
Very large people browse the logs just in search of SQL statement.  Knowledge of the query is crucial to diagnose problems with SQL.  I think we should look for a better solution, e.g. add parameters that will disable logging.

**Comment by davido912** [comment]
@mik-laj an idea from the top of my head could be adding a parameter that could allow for regex pattern removal/hashing of string parts of the sql statement which could then be selectively applied when required

**Comment by kaxil** [comment]
> @mik-laj an idea from the top of my head could be adding a parameter that could allow for regex pattern removal/hashing of string parts of the sql statement which could then be selectively applied when required

That would go back to using the Custom Logging Filter/Formatter which I think would be more elegant solution.

**Comment by kaxil** [comment]
> Very large people browse the logs just in search of SQL statement. Knowledge of the query is crucial to diagnose problems with SQL. I think we should look for a better solution, e.g. add parameters that will disable logging.

Probably not disable logging entirely but maybe just masking log parameters.

**Comment by davido912** [comment]
@kaxil So what would actually be the way to go in this case? Should we attempt to implement a solution on our side or is there anything that you believe would be implemented Airflow side?

**Comment by madison-ookla** [comment]
I agree with @mik-laj on this one, we have one instance where we have 4 dynamic dags that generate hundreds of DAGs with quite varied templated SQL. Viewing these queries in our logs is often necessary for debugging/troubleshooting failures.

**Pull request closed without merging**
