### PR TITLE
Replace foreign key constraints with foreign annotation

### LINKED ISSUE #12448: General Error Deleting DAG run
Using a 2.0.0 beta 2 build...

Untitled

Log from webserver:

```
[2020-11-18 14:58:52,712] {interface.py:713} ERROR - Delete record error: Dependency rule tried to blank-out primary key column 'job.id' on instance '<SchedulerJob at 0x7fc68ba7f990>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/models/sqla/interface.py", line 698, in delete
    self.session.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 538, in execute
    self.dependency_processor.process_deletes(uow, states)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 547, in process_deletes
    state, child, None, True, uowcommit, False
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/dependency.py", line 604, in _synchronize
    sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/sync.py", line 88, in clear
    "column '%s' on instance '%s'" % (r, orm_util.state_str(dest))
AssertionError: Dependency rule tried to blank-out primary key column 'job.id' on instance '<SchedulerJob at 0x7fc68ba7f990>'
172.19.0.1 - - [18/Nov/2020:14:58:52 +0000] "POST /dagrun/delete/147 HTTP/1.1" 302 415 "http://localhost:8080/dagrun/list/?_flt_3_dag_id=airflow_community_data_refresh&_flt_3_state=success" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36"
```

### PR DESCRIPTION
**Pull request by kaxil**
closes https://github.com/apache/airflow/issues/12448

https://github.com/apache/airflow/pull/12586 didn't fully solve the issue. I was getting the following error:

```
    def clear(dest, dest_mapper, synchronize_pairs):
        for l, r in synchronize_pairs:
            if (
                r.primary_key
                and dest_mapper._get_state_attr_by_column(dest, dest.dict, r)
                not in orm_util._none_set
            ):

                raise AssertionError(
                    "Dependency rule tried to blank-out primary key "
>                   "column '%s' on instance '%s'" % (r, orm_util.state_str(dest))
                )
E               AssertionError: Dependency rule tried to blank-out primary key column 'job.id' on instance '<BaseJob at 0x7f42c08ac630>'

/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/sync.py:88: AssertionError
```

This PR also fixes the issues completely for DagRun and fixes it for clearing TaskInstances too from the UI and adds tests for the same

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
I did wonder if the tests in the other pr were actually covering what we needed.

**Comment by kaxil** [comment]
Sqlite test is failing in an unrelated test

**Comment by ashb** [comment]
Have we worked out _why_ this actually makes a difference yet?

**Comment by kaxil** [comment]
> Have we worked out _why_ this actually makes a difference yet?

No -- at least not with 100% confidence but passing values to foreign_key enforces foreign key constraint but using annotation does not

**Review by ashb — APPROVED** [review]

**Pull request merged**
