### PR TITLE
Implement ldap authentication including tests

### PR DESCRIPTION
**Pull request by bolkedebruin**
This PR implements ldap authentication that is python 3 compatible. 

Tests:
- Fully there including testing against a live ldap server on travis.

Caveats:
- In most of the modules the configuration is imported as "from airflow import configuration" in order to make sure different configurations can be unit tested without requiring to re-read a config file. This change creates things like "configuration.conf.get" which does not look too pretty an should be cleaned up later.
- Important: The hack in default_login.py has been removed. There is no required relation between sql-alchemy and flask-login session management. This can make this change incompatible with previous implementations that have overwritten the default_login behavior by supplying "airflow_login" in the PYTHON_PATH. This change was required in order to be able to switch authentication backend on the fly while testing. The hack was interfering.

User changes:
- You can now specify the authentication backend in the config file by setting auth_backend in the web server section. Old behavior is still available but deprecated.

Please have a look and tell me what you think and if things need to be updated.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Any chance for feedback @mistercrunch ?

**Comment by mistercrunch** [comment]
Merge conflict at the moment... 

`configuration.conf` isn't very elegant but it allows to move forward. What about having a shortcut `get` in the configuration namespace to allow for `configuration.get`?

**Comment by bolkedebruin** [comment]
Thanks! Yes. I will fix the conflict that happened after the last commit. And I'll add the shortcuts and do the refactoring for it. Can I ask for a bit of policy on "not importing conf" anymore? I think it will keep out a lot of trouble in the future.

O and something weird I couldn't get my mind around is that I had to set "authenticate" to "false" in the WebUiTests as well despite the tearDown function. If you have an idea on that?

**Comment by mistercrunch** [comment]
I'll do my best to enforce the policy around conf. I'd suggest renaming it to `_conf` but it may break plugins or external operators / hooks and executors.

**Comment by bolkedebruin** [comment]
@mistercrunch issues have been fixed, all modules have been refactored. I'll have a look at making it _conf apart from this PR as it might indeed break other stuff.

**Comment by mistercrunch** [comment]
This is fantastic.

**Pull request merged**
