### PR TITLE
Use timetable to generate planned days for current year

### PR DESCRIPTION
**Pull request by malthe**
This adds a new state "planned" to the calendar view which shows days where it is expected that we'll have a dag run.

The state is rendered as a grey dot to avoid confusion with existing states.

Screenshot 2022-03-07 at 17 19 51

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM. But a UI mind should look at it.

**Comment by BasPH** [comment]
Love this change! However to me the dot is hard to see + not meaningful. What do you think of showing a black checkmark (✓)?

**Comment by malthe** [comment]
@BasPH now that I have defined a `<pattern>` in the SVG output it is actually quite easy to experiment with variations using the developer tools.

It is a balance to strike of course between too subtle and too "in your face".

**Comment by potiuk** [comment]
> It is a balance to strike of course between too subtle and too "in your face".

I think we need @bbovenzi to chime in. Such small UI changes are usually the source of most discussions. Mostly because everyone has an opinion on UI :D

**Comment by bbovenzi** [comment]
I agree that the grey dot is a little too hard to see. Let's at least make its radius 2 and also add it to the legend.

**Comment by malthe** [comment]
@bbovenzi changed to radius 2, same color as table border and added legend now.

Screenshot 2022-03-09 at 07 22 02

**Comment by potiuk** [comment]
Much better :)

**Review by bbovenzi — APPROVED** [review]
Nice work!

**Pull request merged**
