### PR TITLE
Edit variable button on variable list page

### PR DESCRIPTION
**Pull request by shubhamraj-git**
related: https://github.com/apache/airflow/issues/43709

Note:
This needs to rebase on https://github.com/apache/airflow/pull/45238, once that is merged.

image

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by shubhamraj-git** [comment]
@pierrejeambrun 

I can see that the patch variable api have a check 
```
if patch_body.key != variable_key:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST, "Invalid body, key from request body doesn't match uri parameter"
        )
    non_update_fields = {"key"}
```

Is this introduced new that we can't edit the variable key?
I checked in the legacy UI and I was able to edit it.

**Review by jscheffl — APPROVED** [review]
Looks good for me. LGTM!

(we could debate if it makes sense to add a "ManageVariable" subfolder just for the CRUD elements but actually that is rather cosmetic)

**Comment by shubhamraj-git** [comment]
@jscheffl I am open to suggestion on this, if we have something better.
My only take on this was, we will have import vars, export var, delete multiple, action bars. So, it will contain lot of files, so just made the proper CRUD under a folder.

**Comment by jscheffl** [comment]
> @pierrejeambrun @jscheffl @bbovenzi
> 
> I can see that the patch variable api have a check
> 
> ```
> if patch_body.key != variable_key:
>         raise HTTPException(
>             status.HTTP_400_BAD_REQUEST, "Invalid body, key from request body doesn't match uri parameter"
>         )
>     non_update_fields = {"key"}
> ```
> 
> Is this introduced new that we can't edit the variable key? I checked in the legacy UI and I was able to edit it.

I believe that this is an artefact from the migration of public API from Connexion to Fast API, this validation was converted 1:1.
The legacy UI was _not_ using the public API but was directly writing to DB.

So technically we have two options:
1. Restrict changing the key in UI, make the key field read-only when editing
2. Remove the validation in Rest API
3. Add a UI specific API just for this

From UI Perspective dis-allowing to change the key does not make sense. So I'd propose to remove the validation in REST API. For option 1 I see no reason. And Option 3 is too much overhead just because of a cross-validation in API

Any other opinions?

**Comment by shubhamraj-git** [comment]
> @pierrejeambrun @jscheffl @bbovenzi
> 
> I can see that the patch variable api have a check
> 
> ```
> if patch_body.key != variable_key:
>         raise HTTPException(
>             status.HTTP_400_BAD_REQUEST, "Invalid body, key from request body doesn't match uri parameter"
>         )
>     non_update_fields = {"key"}
> ```
> 
> Is this introduced new that we can't edit the variable key? I checked in the legacy UI and I was able to edit it.

Also regrading this issue.

If we plan to implement this.
1. I can have a PR where I will disable the key edit.
2. But if we chose to remove this check from backend, I can have a PR to do that.

**Comment by shubhamraj-git** [comment]
> I believe that this is an artefact from the migration of public API from Connexion to Fast API, this validation was converted 1:1. The legacy UI was _not_ using the public API but was directly writing to DB.
> 
> So technically we have two options:
> 
> 1. Restrict changing the key in UI, make the key field read-only when editing
> 2. Remove the validation in Rest API
> 3. Add a UI specific API just for this
> 
> From UI Perspective dis-allowing to change the key does not make sense. So I'd propose to remove the validation in REST API. For option 1 I see no reason. And Option 3 is too much overhead just because of a cross-validation in API
> 
> Any other opinions?

Regarding option 1)
If we change the key itself, I think we actually created a new variable itself, Isn't this contradicting to edit behaviour? Like users will need to actual change the references too in that case.

I think this can have a decision and can be fixed later, what say?

**Comment by shubhamraj-git** [comment]
@potiuk @pierrejeambrun @jscheffl 
Based upon the discussion, https://apache-airflow.slack.com/archives/C07813CNKA8/p1735405229925579
I have disabled the variable key edit from UI side.

**Pull request merged**
