### PR TITLE
[AIRFLOW-2859] Implement own UtcDateTime

### PR DESCRIPTION
**Pull request by bolkedebruin**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2859
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

The different UtcDateTime implementations all have issues.
Either they replace tzinfo directly without converting
or they do not convert to UTC at all.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Added

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

cc @Fokko @ashb new tests pass locally with equal mysql version to travis. If test fail for mysql I might need some help ;-)

### CODE REVIEW

**Comment by ashb** [comment]
Code looks okay at first glance. Not in front of a laptop today to test further.

**Comment by ashb** [comment]
Can I help?

**Comment by bolkedebruin** [comment]
@ashb I think I finally nailed it. The issue was in my understanding how sqlalchemy was dealing with timezone information inside fields for mysql. If you insert in mysql `2018-08-08 20:40:21.443732+02:00` mysql will ignore the `+02:00` _and_ apply the connection's timezone setting (e.g. `set time_zone='+01:00'`). I thought sqlalchemy would handle this somehow (ie bij separating the timezone and doing something like this [1]. 

So, this creates chaos obviously, although not too much as long as you do not change the connection's timezone. In my tests I was actually doing so hence they didn't pass. Strangely enough if executing them isolated / locally it worked for some reason. probably due to connection re-use. 

Anyways I borrowed you event watcher and now make sure we always connect in UTC with mysql. For postgres it doesn't matter and we can test it doesn't. 

[1] https://stackoverflow.com/questions/7651409/mysql-datetime-insert-a-date-with-timezone-offset

**Comment by ashb** [comment]
AIP-3: Drop support for Mysql :D

**Comment by bolkedebruin** [comment]
I think our google friends use mysql 5.7 for their cloud composer. Probably they won't be happy with us then ;-)

**Review by ashb — APPROVED** [review]

**Comment by feng-tao** [comment]
flake8 fails.

**Pull request merged**
