### PR TITLE
[AIRFLOW-2878] Fix www_rbac display issue

### PR DESCRIPTION
**Pull request by XD-DENG**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2878
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The RBAC UI has some issues about layout/UI display.

The header (`<h2>`) is not shown ("hidden" by the Nav Bar), or tables are not shown completely.

This is addressed by a simple change on `templates/appbuilder/baselayout.html`.

`**Please check the screenshots below**` (beforeFix-1 vs. afterFix-1, beforeFix-2 vs. afterFix-2)

##### beforeFix-1
screen shot 2018-08-09 at 8 11 14 pm

##### beforeFix-2
screen shot 2018-08-09 at 8 10 45 pm

##### beforeFix-3
screen shot 2018-08-09 at 8 10 03 pm

##### beforeFix-4
screen shot 2018-08-09 at 8 11 08 pm

##### afterFix-1
screen shot 2018-08-09 at 8 14 33 pm

##### afterFix-2
screen shot 2018-08-09 at 8 14 45 pm

##### afterFix-3
screen shot 2018-08-09 at 8 14 19 pm

##### afterFix-4
screen shot 2018-08-09 at 8 14 27 pm

##### afterFix-5
screen shot 2018-08-09 at 8 14 39 pm

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
+1

**Comment by verdan** [comment]
@XD-DENG I believe you haven't built the frontend packages yet, causing all these issues. 
We've implemented the `npm` and `webpack` to manage the JS libraries and dependencies [AIRFLOW-2691](https://issues.apache.org/jira/browse/AIRFLOW-2691) . Can you please follow the steps mentioned here to build the frontend packages and see if that fixes everything for you?
https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md#setting-up-the-node--npm-javascript-environment-only-for-www_rbac

**Comment by XD-DENG** [comment]
Hi @verdan, I installed from the ‘tar.gz’ file directly.

Will check the setting-up you introduced later. Thanks.

**Comment by verdan** [comment]
perfect, thanks!
Also, I believe we need to revert this change, as this change would include extra spaces on each page. cc: @r39132 

screen shot 2018-08-10 at 2 02 25 pm

**Comment by XD-DENG** [comment]
Sure. @r39132 may you please revert this commit as @verdan suggested?
Thanks for pointing this out!

**Comment by XD-DENG** [comment]
Hi @verdan , FYI, this commit is already reverted via https://github.com/apache/incubator-airflow/pull/3737 . Thanks.

**Comment by r39132** [comment]
@verdan thx for catching this.. @feng-tao thx for executing the reversion.

@verdan Can we add a test to catch this next time?

**Pull request merged**
