### PR TITLE
[AIRFLOW-65] Support child rows to show extra information for AirflowModelView

### PR DESCRIPTION
**Pull request by yyyyyyuanfei**
Dear Airflow Maintainers,

Please accept the following PR that
- Support child rows to show extra information for AirflowModelView using DataTable

It's an update for #1422 in that it solely uses the existing DataTable plugin and extends the detail row feature to all AirflowModelViews.
### DagRun conf

snip20160427_78
### Connection Extra

snip20160427_80

Reminder to contributors:
- You must add an Apache License header to all new files
- Please squash your commits when possible and follow the [7 rules of good Git commits](http://chris.beams.io/posts/git-commit/#seven-rules)

### CODE REVIEW

**Comment by yyyyyyuanfei** [comment]
@mistercrunch @r39132 I made a new one that solely based on the existing DataTable plugin. Also added support for the DagRun view. How does this one look?

It exposes all the information to the admins as mentioned [here](https://github.com/airbnb/airflow/pull/1422#issuecomment-215192515). I can more permission related logic later.

Thanks!

**Comment by r39132** [comment]
@stranbird  You need to create a JIRA and link it to this before we can merge it.

**Comment by r39132** [comment]
+1 @mistercrunch Can you have a look as well and ensure it's all good for you?

**Comment by mistercrunch** [comment]
I don't understand why the extra has to be shown in the list view as opposed to only in the edit view? I'd rather customize the Flask-Admin templates as little as possible.

**Comment by r39132** [comment]
@mistercrunch Doesn't it make sense to view information without having to click "edit"?
 Similarly for the variable list view... why not show the variable value in the list view? Instead, we must click edit to view the variable value, leaving the possibility for unintended changes.

**Comment by r39132** [comment]
https://issues.apache.org/jira/browse/AIRFLOW-65

**Comment by r39132** [comment]
@stranbird Can you add a conf value to control this feature? For example, the configuration can be `hide_confidential_ui_fields` with a default of False.

**Comment by r39132** [comment]
Also, please edit your PR subject to be prepended with [AIRFLOW-65]

**Comment by yyyyyyuanfei** [comment]
@mistercrunch the idea origins from our use cases that we'd have multiple ad-hoc dag runs triggered externally with different configurations, to show `conf` for the task instances helps us to easily see why the dag is shaped as it is. To show `extra` has been helping us identify the missing configurations like `{ "local_infile": true }` which is required by MySQL bulk load while is easily forgot to add.

@r39132 it's definitely a vital switch, I'll add that.

**Comment by r39132** [comment]
Okie. Update Jira or issue once the configuration has been added. Also, if you haven't done so already, assign the Jira to yourself.

**Comment by r39132** [comment]
@stranbird any updates?

**Comment by mistercrunch** [comment]
My feeling it's that it's too much custom logic (template override, javascript, ...) to not even avoid one click (you still have to click to view the extras), but just to view that field in the context of the list view.

I'd try to stay vanilla as much as possible. Otherwise it's just more code that we have to support for a very marginally useful feature.

**Comment by yyyyyyuanfei** [comment]
@mistercrunch I see, feel free to close this issue. I am glad to continue working on other features.

**Comment by r39132** [comment]
Let's discuss this further on https://issues.apache.org/jira/browse/AIRFLOW-65

**Comment by r39132** [comment]
Closing as there was no movement on this PR.

**Pull request closed without merging**
