### PR TITLE
Limit temporarily `aiohttp` to < 3.11.0

### PR DESCRIPTION
**Pull request by vincbeck**
Because of https://github.com/aio-libs/aiohttp/issues/9866 some tests are failing. This PR can be reverted when https://github.com/pnuckowski/aioresponses/pull/262 is merged and released

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by jscheffl — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
This PR (when you open failing output you can see it) revealed  limitation on parsing development dependencies that should be installed for compatiblity testing.

The fix is here: https://github.com/apache/airflow/pull/43995 - but I think this limit should not be placed in devel-deps. I will take a look in a moment.

**Comment by potiuk** [comment]
This is a better fix https://github.com/apache/airflow/pull/43998 - aiohttp is already a dependency of `adlfs` so we can add it there.

**Review by potiuk — CHANGES_REQUESTED** [review]
better fix in https://github.com/apache/airflow/pull/43998

**Comment by potiuk** [comment]
Even better fix https://github.com/apache/airflow/pull/44006

**Comment by potiuk** [comment]
Closing -> the fix from https://github.com/apache/airflow/pull/44006 is much more "appropriate".

**Pull request closed without merging**
