### PR TITLE
Supporting extraAnnotions at pgbouncer deployment level

### LINKED ISSUE #27246: Pgbouncer doesn't support extraAnnotations for deployment/pod
### Official Helm Chart version

1.6.0

### Apache Airflow version

2

### Kubernetes Version

1.24

### Helm Chart configuration

Pgbouncer doesn't support extraAnnotations for deployment/pod

### Docker Image customisations

_No response_

### What happened

Pgbouncer doesn't support extraAnnotations for deployment/pod

### What you think should happen instead

_No response_

### How to reproduce

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by amoghrajesh**
Adds support for integrating extraAnnotations in the pgbouncer deployment spec when defined in values.yaml during setup

closes: #27246 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by amoghrajesh** [comment]
@jedcunningham can I get a review on this once you have some time?

**Comment by amoghrajesh** [comment]
@potiuk @jedcunningham can I get a review on this PR if you have some free time?

**Comment by jedcunningham** [comment]
How is this different than `pgbouncer.podAnnotations`?

**Comment by amoghrajesh** [comment]
@jedcunningham I was trying to cover up the tech debt due to thseparatePR: https://github.com/apache/airflow/pull/27247
Not sure about the exact intention but looks like an effort to seperate the annotations into `podAnnotations` and `extraAnnotations`

**Comment by jedcunningham** [comment]
I don't see any reason to have 2 ways to set annotations on the pod, and `podAnnotations` is how it's done elsewhere. `extraAnnotations` is just used on our services.

I've marked that issue as closed by #30168. Thanks @amoghrajesh!

**Pull request closed without merging**
