### PR TITLE
Fix depends_on_past work for dynamic tasks

### LINKED ISSUE #29531: Dynamic task mapping does not always create mapped tasks
### Apache Airflow version

2.5.1

### What happened

Same problem as https://github.com/apache/airflow/issues/28296, but seems to happen nondeterministically, and still happens when ignoring `depends_on_past=True`.

I've got a task that retrieves some filenames, which then creates dynamically mapped tasks to move the files, one per task.
I'm using a similar task across multiple DAGs. However, task mapping fails on some DAG runs: it inconsistently happens per DAG run, and some DAGs do not seem to be affected at all. These seem to be the DAGs where no task was ever mapped, so that the mapped task instance ended up in a Skipped state.

What happens is that multiple files will be found, but only a single dynamically mapped task will be created. This task never starts and has map_index of -1. It can be found under the "List instances, all runs" menu, but says "No Data found." under the "Mapped Tasks" tab.

Screenshot 2023-02-14 at 13 29 15

Screenshot 2023-02-14 at 13 29 25

When I press the "Run" button when the mapped task is selected, the following error appears:

```
Could not queue task instance for execution, dependencies not met: Previous Dagrun State: depends_on_past is true for this task's DAG, but the previous task instance has not run yet., Task has been mapped: The task has yet to be mapped!
```

The previous task _has_ run however. No errors appeared in my Airflow logs.

When I try to run the task with **Ignore All Deps** enabled, I get the error:

```
Could not queue task instance for execution, dependencies not met: Previous Dagrun State: depends_on_past is true for this task's DAG, but the previous task instance has not run yet., Task has been mapped: The task has yet to be mapped!
```

This last bit is a contradiction, the task cannot be mapped and not mapped simultaneously.

If the amount of mapped tasks is 0 while in this erroneous state, the mapped tasks will not be marked as skipped as expected.

### What you think should happen instead

The mapped tasks should not get stuck with "no status".

The mapped tasks should be created and ran successfully, or in the case of a 0-length list output of the upstream task they should be skipped.

### How to reproduce

Run the below DAG, if it runs successfully clear several tasks out of order. This may not immediately reproduce the bug, but after some task clearing, for me it always ends up in the faulty state described above.

```
from airflow import DAG
from airflow.decorators import task
import datetime as dt

from airflow.operators.python import PythonOperator
import random


@task
def get_filenames_kwargs():
    return [
        {"file_name": i}
        for i in range(random.randint(0, 2))
    ]

def print_filename(file_name):
    print(file_name)

with DAG(
        dag_id="dtm_test_2",
        start_date=dt.datetime(2023, 2, 10),
        default_args={
            "owner": "airflow",
            "depends_on_past": True,
        },
        schedule="@daily",
) as dag:
    get_filenames_task = get_filenames_kwargs.override(task_id="get_filenames_task")()

    print_filename_task = PythonOperator.partial(
        task_id="print_filename_task",
        python_callable=print_filename,
    ).expand(op_kwargs=get_filenames_task)
```

### Operating System

Amazon Linux v2

### Versions of Apache Airflow Providers

_No response_

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by uranusjr**
This is #30892 with changes applied to fix issues mentioned in reviews.

Fix #29531.

### CODE REVIEW

**Review by eladkal — APPROVED** [review]

**Review by hussein-awala — COMMENTED** [review]
The number of mapped tasks could be too big, in order to avoid fetching all the tasks, I wonder if we could improve the query to something like:
```python
TIs_stats = session.query(
    func.count().label("tasks_count"),
    func.sum(func.case([(Task.state.in_(['success', 'skipping']), 1)], else_=0)).label('succefully_finished_count')
).filter(
    TI.dag_id == dagrun.dag_id, TI.task_id == task_id, TI.run_id == dagrun.run_id
).first()

if not TIs_stats.tasks_count:
   # check for ignore_first_depends_on_past

if tasks_count.succefully_finished_count != TIs_stats.tasks_count:
    # yield failing status # we cannot list the failed tasks
```

For `wait_for_downstream`, we could create a second query which self join the table TI and fetch only the tasks which has a not finished downstream (or better their count), instead of calling the method `are_dependents_done` N times.

However, **I think** there is a bug int the method `are_dependents_done`:
```python
ti = session.query(func.count(TaskInstance.task_id)).filter(
            TaskInstance.dag_id == self.dag_id,
            TaskInstance.task_id.in_(task.downstream_task_ids),
            TaskInstance.run_id == self.run_id,
            TaskInstance.state.in_((TaskInstanceState.SKIPPED, TaskInstanceState.SUCCESS)),
        )
```
1. in your method, when you process a mapped task, you will call this method N times, and it will run the same query and gives the same result because it doesn't use map_index.
2. in case of mapped task group, the mapped tasks don't have the same upstream tasks, but all their upstream tasks have the same TI id, with different map indexes

WDYT?

**Comment by uranusjr** [comment]
Good point. The actual task instances are only used for logging, which we can probably avoid in most cases.

**Comment by uranusjr** [comment]
Oh, we actually do use those task instances to calculate `are_dependents_done`. That function is quite inefficient too though, we should probably just replace it with a direct query.

**Comment by uranusjr** [comment]
Alright, I’ve refactored this to do all the heavy-lifting in the database, and almost no additional information (except the DAG run) is not transfered from the database to Python. I had to quite substantially rewrite the tests as well to properly mock all database calls, but everything should work now.

**Review by eladkal — APPROVED** [review]

**Review by hussein-awala — APPROVED** [review]
Great work! LGTM

**Review by potiuk — APPROVED** [review]
Nice and clear!

**Pull request merged**
