### PR TITLE
Obtain lock for update when scheduling tis

### LINKED ISSUE #19957: Airflow crashes with a psycopg2.errors.DeadlockDetected exception
### Apache Airflow version

2.2.2 (latest released)

### Operating System

Ubuntu 21.04 on a VM

### Versions of Apache Airflow Providers

root@AI-Research:~/learning_sets/airflow# pip freeze | grep apache-airflow-providers
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-http==2.0.1
apache-airflow-providers-imap==2.0.1
apache-airflow-providers-sqlite==2.0.1

### Deployment

Other

### Deployment details

Airflow is at version 2.2.2
psql (PostgreSQL) 13.5 (Ubuntu 13.5-0ubuntu0.21.04.1)

The dag contains thousands of tasks for data download and preprocessing and preparation which is destined to a mongodb database (so, I'm not using the PostgreSQL inside my tasks).

### What happened

[2021-12-01 19:41:57,556] {scheduler_job.py:644} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DeadlockDetected: deadlock detected
DETAIL:  Process 322086 waits for ShareLock on transaction 2391367; blocked by process 340345.
Process 340345 waits for AccessExclusiveLock on tuple (0,26) of relation 19255 of database 19096; blocked by process 340300.
Process 340300 waits for ShareLock on transaction 2391361; blocked by process 322086.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (1335,10) in relation "task_instance"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/scheduler_job.py", line 628, in _execute
    self._run_scheduler_loop()
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/scheduler_job.py", line 709, in _run_scheduler_loop
    num_queued_tis = self._do_scheduling(session)
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/scheduler_job.py", line 792, in _do_scheduling
    callback_to_run = self._schedule_dag_run(dag_run, session)
  File "/usr/local/lib/python3.9/dist-packages/airflow/jobs/scheduler_job.py", line 1049, in _schedule_dag_run
    dag_run.schedule_tis(schedulable_tis, session)
  File "/usr/local/lib/python3.9/dist-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/airflow/models/dagrun.py", line 898, in schedule_tis
    session.query(TI)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 4063, in update
    update_op.exec_()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1895, in _do_exec
    self._execute_stmt(update_stmt)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/orm/query.py", line 3568, in _execute_crud
    return conn.execute(stmt, self._params)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
DETAIL:  Process 322086 waits for ShareLock on transaction 2391367; blocked by process 340345.
Process 340345 waits for AccessExclusiveLock on tuple (0,26) of relation 19255 of database 19096; blocked by process 340300.
Process 340300 waits for ShareLock on transaction 2391361; blocked by process 322086.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (1335,10) in relation "task_instance"

[SQL: UPDATE task_instance SET state=%(state)s WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.run_id = %(run_id_1)s AND task_instance.task_id IN (%(task_id_1)s, %(task_id_2)s, %(task_id_3)s, %(task_id_4)s, %(task_id_5)s, %(task_id_6)s, %(task_id_7)s, %(task_id_8)s, %(task_id_9)s, %(task_id_10)s, %(task_id_11)s, %(task_id_12)s, %(task_id_13)s, %(task_id_14)s, %(task_id_15)s, %(task_id_16)s, %(task_id_17)s, %(task_id_18)s, %(task_id_19)s, %(task_id_20)s)]
[parameters: {'state': <TaskInstanceState.SCHEDULED: 'scheduled'>, 'dag_id_1': 'download_and_preprocess_sets', 'run_id_1': 'manual__2021-12-01T17:31:23.684597+00:00', 'task_id_1': 'download_1379', 'task_id_2': 'download_1438', 'task_id_3': 'download_1363', 'task_id_4': 'download_1368', 'task_id_5': 'download_138', 'task_id_6': 'download_1432', 'task_id_7': 'download_1435', 'task_id_8': 'download_1437', 'task_id_9': 'download_1439', 'task_id_10': 'download_1457', 'task_id_11': 'download_168', 'task_id_12': 'download_203', 'task_id_13': 'download_782', 'task_id_14': 'download_1430', 'task_id_15': 'download_1431', 'task_id_16': 'download_1436', 'task_id_17': 'download_167', 'task_id_18': 'download_174', 'task_id_19': 'download_205', 'task_id_20': 'download_1434'}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-12-01 19:41:57,566] {local_executor.py:388} INFO - Shutting down LocalExecutor; waiting for running tasks to finish.  Signal again if you don't want to wait.
[2021-12-01 19:42:18,013] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 285470
[2021-12-01 19:42:18,105] {process_utils.py:66} INFO - Process psutil.Process(pid=285470, status='terminated', exitcode=0, started='18:56:21') (285470) terminated with exit code 0
[2021-12-01 19:42:18,106] {scheduler_job.py:655} INFO - Exited execute loop

### What you expected to happen

Maybe 24 concurrent processes/tasks are too many?

### How to reproduce

reproducibility is challenging, but maybe the exception provides enough info for a fix

### Anything else

all the time, after some time the dag is being run

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by ephraimbuddy**
Not sure how we get deadlock at this method even with one scheduler
so I'm suggesting we lock it for update

Closes: https://github.com/apache/airflow/issues/19957

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Review by jedcunningham — APPROVED** [review]

**Comment by potiuk** [comment]
I am rather sceptical if it changes anything (unless I missed something).

What thi change effectively does it would attempt to run:

```
UPDATE task_instance SET state=%(state)s WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.run_id = %(run_id_1)s AND task_instance.task_id IN () FOR UPDATE;'
```

Which I think is not happening anyway because it makes no sense. the FOR UPDATE clause only makes sense in select queries.  Row lock happens always when your UPDATE query, so I think sqlalchemy will simply silently ignore the whith_for_updae() clause. 

What I think we really need to fix for this query is fix the OTHER query that causes it (but we need the logs from server to find out what the other query was). From how I understand here this piece of code should be protected by earlier locking of "DAG_RUN" row and there is another query that locks TASK_INSTANCE rows for that DAG_RUN - and it should not.

There are two reasons it could happen:

1) The other query does not lock the DAG_RUN row "deliberately" 
2) We have a commit somewhere that releases the DAG_RUN lock

I suspected initially that it's mini-scheduler, but I think it must be something else (mini-scheduler correctly  locks the DAG_RUN and I could not find any place where it would release it.

One other reason is that it could be an API call or UI action that updates the task_instances.

**Comment by ephraimbuddy** [comment]
What made me try this change was because a similar thing happened with multiple schedulers and #18975 solved it. 
Also, I think locking DAG_RUN will not lock the task instances but we could obtain a lock for the task instance separately since it's a separate table. 
That's what I think but I'm not sure.
The part of the scheduler log that convinced me to try this is:
```
CONTEXT: while updating tuple (1335,10) in relation "task_instance"
```
I'm of the opinion that if `dag_run `lock is the problem, then the log would be around `dagrun` and not `task_instance`

Sadly, #18975 was easily reproducible but this one is not.

**Comment by ephraimbuddy** [comment]
What made me try this change was because a similar thing happened with multiple schedulers and #18975 solved it. 
Also, I think locking DAG_RUN will not lock the task instances but we could obtain a lock for the task instance separately since it's a separate table. 
That's what I think but I'm not sure.
The part of the scheduler log that convinced me to try this is:
```
CONTEXT: while updating tuple (1335,10) in relation "task_instance"
```
I'm of the opinion that if `dag_run `lock is the problem, then the log would be around `dagrun` and not `task_instance`

Sadly, #18975 was easily reproducible but this one is not.

**Comment by potiuk** [comment]
> What made me try this change was because a similar thing happened with multiple schedulers and #18975 solved it.

Yeah - but this is really the difference SELECT vs. UPDATE. The #18975 was SELECT query:

```
tis: List[TI] = session.query(TI).filter(filter_for_tis).options(selectinload('dag_model')).all()
```

Where here we have an UPDATE query:

```
session.query(TI)
.filter(
    TI.dag_id == self.dag_id,
    TI.run_id == self.run_id,
    TI.task_id.in_(schedulable_ti_ids),
)
.update({TI.state: State.SCHEDULED}, synchronize_session=False)
```

UPDATE query obtains lock automatically for all rows accessed (so what happens first in the query it tries to obtain locks on all the rows it accesses and `with_row_lock` has no effect.

> I'm of the opinion that if dag_run lock is the problem, then the log would be around dagrun and not task_instance

The dag_run is not the problem. In theory (that how the DAG_RUN lock was designed), you should not even attempt to get a lock on any TASK_INSTANCE before obtaining DAG_RUN lock first. This is what "with_row_lock" SELECT FROM DAG_RUN SKIP_LOCKED few methods up in the stack should be doing before we get here. 

This is what  `next_dagruns_to_examine` is doing by:

```
       query = (
            session.query(cls)
            .filter(cls.state == state, cls.run_type != DagRunType.BACKFILL_JOB)
            .join(DagModel, DagModel.dag_id == cls.dag_id)
            .filter(DagModel.is_paused == false(), DagModel.is_active == true())
        )
       ....

        return with_row_locks(
            query.limit(max_number), of=cls, session=session, **skip_locked(session=session)
        )
```

@ashb? Is that correct ? 

What happens here - we have the DAG_RUN lock from the few methods up, so we should be safe to update TASK_INSTANCES. but for some reason someone else who did not have the DAG_RUN lock also tries to update those instances.

**Comment by potiuk** [comment]
Yeah. I can confirm that this change has not changed anything, as I suspected @ephraimbuddy . You can test it yourself. This is what I did (latest breeze  + postgres)

```
export  AIRFLOW__CORE__SQL_ALCHEMY_ENGINE_ARGS='{"echo": true}'
```
^^ This enables echo of the queries generated by SQLAlchemy.

```
pytest tests/jobs/test_scheduler_job.py::TestSchedulerJob::test_dagrun_callbacks_are_called -s
```
^^ This is one of the tests that reaches this query.

```
UPDATE task_instance SET start_date=%(start_date)s, end_date=%(end_date)s, duration=%(duration)s, state=%(state)s
WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.run_id = %(run_id_1)s AND task_instance.task_id
IN (%(task_id_1)s)

"{'start_date': datetime.datetime(2022, 1, 23, 18, 1, 14, 880695, tzinfo=Timezone('UTC')),
'end_date': datetime.datetime(2022, 1, 23, 18, 1, 14, 880701, tzinfo=Timezone('UTC')),
'duration': 0, 'state': <TaskInstanceState.SUCCESS: 'success'>,
'dag_id_1': 'test_task_start_date_scheduling',
'run_id_1': 'scheduled__2016-01-01T00:00:00+00:00', 'task_id_1': 'dummy2'}"
```
^^ This was the query generated (as you can see there is no extra lock here). To make it easy to find I just added 'raise Exception` right after the query - this one was the last query printed.

I reverted the commit "Obtain lock for update when scheduling tis" and re-run it:

```
UPDATE task_instance SET start_date=%(start_date)s, end_date=%(end_date)s, duration=%(duration)s, state=%(state)s
WHERE task_instance.dag_id = %(dag_id_1)s AND task_instance.run_id = %(run_id_1)s AND task_instance.task_id 
IN (%(task_id_1)s) 
{'start_date': datetime.datetime(2022, 1, 23, 18, 11, 22, 12081, tzinfo=Timezone('UTC')), 
'end_date': datetime.datetime(2022, 1, 23, 18, 11, 22, 12087, tzinfo=Timezone('UTC')), 
'duration': 0, 'state': <TaskInstanceState.SUCCESS: 'success'>, 
'dag_id_1': 'test_task_start_date_scheduling', 
'run_id_1': 'scheduled__2016-01-01T00:00:00+00:00', 'task_id_1': 'dummy2'}
```
^^ As you can see, we have the very same query generated by SQLAlchemy, no matter if we do the query with/without row lock. Exactly as I suspected. I will re-open the original error, because IMHO, this change has no chance of fixing it, because it does not change anything :(.

**Comment by ephraimbuddy** [comment]
Wow. Not aware of the {"echo": true}. Thanks very much. 
I will look into this again

**Comment by potiuk** [comment]
> Wow. Not aware of the {"echo": true}. Thanks very much. I will look into this again

Pretty handy :) . I just learned about it actually while looking at it.

I thought a bit abou this, and I think this might actually be something not really Airflow-code originated. It really looks like it coudl be caused by someone running some manual UI operations and not committing it . It feels strange that Task Instance rows are locked without the DagRun, so it almost feels like it's either a custom code or manual operations of the users. I spent quite some time looking at a a potential path where the TI rows could be locked, but I could not find anything honestly.

So I'd really insist on the users who see it provide us some more details - particularly what is the "other" query that locks the instances. I think the code that get's the deadlock is "correct" - it's the "other" code that is at fault (but we have no idea what the other code is and whether it is a code or human).

**Comment by stablum** [comment]
Hello,

unfortunately I'm still getting deadlocks: https://github.com/apache/airflow/issues/19957#issuecomment-1079965417

**Comment by potiuk** [comment]
Hey @stablum - did you have a chance to update to some more recent versions of Airlfow? (2.3.2 released on Saturday) - are those deadloics still happening.

**Comment by stablum** [comment]
hi @potiuk with 2.3.0 they were unfortunately still occurring. I will upgrade to 2.3.2 soon...

**Comment by potiuk** [comment]
> hi @potiuk with 2.3.0 they were unfortunately still occurring. I will upgrade to 2.3.2 soon...

Let me know and provide some locks after you do (2.3.2 shoulds solve some other teething problems with 2.3) and I might want to re-take a look (now that Airlfow Summit and 2.3.0/1/2 are out ).

**Pull request merged**
