### PR TITLE
[AIRFLOW-2435] Change ecs_operator.py to be able to pass launch_type

### PR DESCRIPTION
**Pull request by ThomasVdBerge**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/AIRFLOW-2435) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2435
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Added launch_type to ECSOperator. Default value remains EC2

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
If someone can point me in the right direction for this, gladly.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Could you also extend the tests?
```
======================================================================
18) FAIL: test_execute_with_failures (tests.contrib.operators.test_ecs_operator.TestECSOperator)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/contrib/operators/test_ecs_operator.py line 124 in test_execute_with_failures
      taskDefinition='t'
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 948 in assert_called_once_with
      return self.assert_called_with(*args, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 937 in assert_called_with
      six.raise_from(AssertionError(_error_message(cause)), cause)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/six.py line 737 in raise_from
      raise value
   AssertionError: Expected call: run_task(cluster='c', overrides={}, startedBy=<ANY>, taskDefinition='t')
   Actual call: run_task(cluster='c', launchType='EC2', overrides={}, startedBy='airflow', taskDefinition='t')
======================================================================
19) FAIL: test_execute_without_failures (tests.contrib.operators.test_ecs_operator.TestECSOperator)
----------------------------------------------------------------------
   Traceback (most recent call last):
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 1305 in patched
      return func(*args, **keywargs)
    tests/contrib/operators/test_ecs_operator.py line 102 in test_execute_without_failures
      taskDefinition='t'
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 948 in assert_called_once_with
      return self.assert_called_with(*args, **kwargs)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/mock/mock.py line 937 in assert_called_with
      six.raise_from(AssertionError(_error_message(cause)), cause)
    .tox/py27-backend_sqlite/lib/python2.7/site-packages/six.py line 737 in raise_from
      raise value
   AssertionError: Expected call: run_task(cluster='c', overrides={}, startedBy=<ANY>, taskDefinition='t')
   Actual call: run_task(cluster='c', launchType='EC2', overrides={}, startedBy='airflow', taskDefinition='t')
```

**Comment by kaxil** [comment]
@ThomasVdBerge 

Add `launchType='EC2'` to https://github.com/apache/incubator-airflow/blob/7ca45b252bbeeb2de223a835b8fa8b6b6200423c/tests/contrib/operators/test_ecs_operator.py#L120

i.e.

```
client_mock.run_task.assert_called_once_with(
            cluster='c',
            launchType='EC2',
            overrides={},
            startedBy=mock.ANY,  # Can by 'airflow' or 'Airflow'
            taskDefinition='t'
        )
```

Do the same here https://github.com/apache/incubator-airflow/blob/7ca45b252bbeeb2de223a835b8fa8b6b6200423c/tests/contrib/operators/test_ecs_operator.py#L98

This should pass the failing tests.

**Comment by kaxil** [comment]
Can you please squash commits to just have a single commit?

**Comment by kaxil** [comment]
LGTM. Thank you for your contribution. 👍

**Pull request closed without merging**
