### PR TITLE
[AIRFLOW-2886] Secure Flask SECRET_KEY

### PR DESCRIPTION
**Pull request by XD-DENG**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2886
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

In my earlier PRs, https://github.com/apache/incubator-airflow/pull/3651 and https://github.com/apache/incubator-airflow/pull/3729 , I proposed to generate random `SECRET_KEY` for the `webserver` (Flask App).

However, I realise that we may encounter CSRF error `The CSRF session token is missing` when we have multiple workers for the Flask webserver, since the secret_key is not consistent among workers.

On the other hand, it's still very important to have as random SECRET_KEY as possible for security reasons. We can deal with it like how we dealt with `FERNET_KEY` (i.e. generate a random value when the airflow.cfg file is initiated).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by XD-DENG** [comment]
@feng-tao @Fokko PTAL. 

We need to have random SECRET_KEY for Flask App, while it must be consistent among workers. So I propose to deal with it like how we dealt with `FERNET_KEY`.

Thanks.

**Comment by feng-tao** [comment]
hey @XD-DENG , it seems that it will still be an issue if we have a cluster for webservers  based on the comment in https://issues.apache.org/jira/browse/AIRFLOW-2866. What do you think? cc @Fokko , @kaxil  as they comment / approve the original prs.

**Comment by XD-DENG** [comment]
Hi @feng-tao , in cluster mode, given the `.cfg` files are initiated on different nodes, the SECRET_KEY will be different. That's also why Craig mentioned it fixes now on a single webserver instance (single worker or multiple workers), but still having `CSRF` error on a cluster of webservers ([LINK](https://issues.apache.org/jira/browse/AIRFLOW-2866?focusedCommentId=16576717&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16576717)).

I insist in that we should have random SECRET_KEY for the webserver. If we use the previous way, that is to have a default value in the template, it's gonna be risky.

If users want to use a cluster of webservers, they need to either 
- make sure that SECRET_KEYs are consistent across nodes (to manually specify). This is similar to what people need to do for `sql_alchemy_conn` if they're running multiple nodes for webserver.
OR
- apply `ip-hash` strategy for the cluster load-balancing, rather than `round-robin`.

Please let me know your thoughts?

cc: @Fokko @kaxil

**Comment by Fokko** [comment]
Are people using clusters of webservers? I've never seen such a setup to be honest.

**Comment by XD-DENG** [comment]
@Fokko @feng-tao :
If users are running a cluster for `webservers`, we can leave it to users to ensure configuration settings being homogeneous across the cluster (just like how users set `sql_alchemy_conn` or `broker_url`).

In a more common scenario, users have `webserver` on a single node (starting multiple processes as multiple workers), the solution in this PR should be able to improve the security in terms of SECRET_KEY without `CSRF` issue.

**Comment by feng-tao** [comment]
looking at this https://github.com/apache/incubator-airflow/pull/3651 pr, I am wondering whether we could do better than use random function to assign the value to secret_key. I felt the better approach is to have a random key store in an internal key management service(this should be common for company, e.g lyft uses https://github.com/lyft/confidant) and assign it to secret_key in the config file. This will make sure the key is random but uniform across all the webservers.  This won't cause any csrf issues as well.  What do you think @Fokko , @kaxil , @XD-DENG ?

**Comment by feng-tao** [comment]
This pr currently can't address the issue when we have a cluster for webserver. IMO, I would prefer to revert the orignal prs and improve the secret_key config documentation. Let me know what you guys think.

**Comment by Noremac201** [comment]
As far as I can tell, I can't save any passwords in Connections in Airflow webUI from a fresh master and this commit cherry-picked.

I don't know if I could've caused this though.

**Comment by XD-DENG** [comment]
Hi @feng-tao , I agree that PRs #3651  and #3729  must be reverted as they are causing CSRF issues in web UI at this moment(they are also reverts in the commit of this PR).

On the other hand, for Airflow, I don’t think it’s common to run multiple nodes for webserver for a single Airflow instance. Normally people use multiple processes on a single machine as multiple workers for each single Airflow instance. Then the solution in this PR can provide out-of-the-box security improvement.

If you're talking about a cluster of Airflow instances, then Airflow instances do not need to have consistent secret_key, and they should not (different apps should use different secret_keys). 

Please let me know your thoughts. Thanks.

CC @Fokko  @kaxil

**Comment by ashb** [comment]
My vote is to go with this approach (secure by default and easy for the common case) plus a bit of documentation saying that you will want to make sure that this value is the same across multiple machines if you run more than one behind a load balancer etc.

**Comment by ashb** [comment]
To use an external secret store this could be extended to use the (already existing) `_cmd` functionality that exist in airflow for certain config options (sql alchemy connection instance) - we'd just need to add this option to the list that are read from cmds.

**Comment by feng-tao** [comment]
sounds good @ashb . Let's go ahead to merge this pr to unblock master and document the functionality you mentioned later.

**Comment by feng-tao** [comment]
thanks @XD-DENG  for fixing the issue.

**Comment by XD-DENG** [comment]
Thank you @feng-tao @ashb

**Pull request merged**
