### PR TITLE
[AIRFLOW-2883] Not search dag owner if owners are missing

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2883
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
If the owners field are missing for a dag in airflow metadata db table(DAG),  we will encounter "NoneType" object has no attribute 'lower' when we do a search in UI. We should skip that dags in this case.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
no test. Trivial fix.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @kaxil @Fokko

**Comment by r39132** [comment]
Hi @feng-tao!
I was not able to reproduce the problem on master, so I'd like some more detail on the bug you encountered.

I tried 3 things:
1. I created a simple DAG and omitted the owner. When I did this, Airflow defaulted the owner to `Airflow`

2. I created a simple DAg and set the Owner to None. When I did this, the UI crashed, 
```
[2018-08-09 18:04:47,528] ERROR in app: Exception on /admin/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/Flask-0.12.4-py3.6.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/Flask_Admin-1.4.1-py3.6.egg/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Flask_Admin-1.4.1-py3.6.egg/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/Flask_Login-0.2.11-py3.6.egg/flask_login.py", line 755, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/airflow/www/views.py", line 2040, in index
    auto_complete_data.add(dag.owner)
  File "/usr/local/lib/python3.6/site-packages/airflow/models.py", line 3506, in owner
    return ", ".join(list(set([t.owner for t in self.tasks])))
```

3. I set owner to the empty string: ''
This worked fine. The UI was able to support my searching for other owners and my dag was excluded. If clear the search box and execute a search, then I get all DAGs back, including my sample DAG.

What test case am I missing here and what did you run into?

**Comment by feng-tao** [comment]
hey @r39132 ,  the issue is because the owners field for the dag is missing(https://github.com/apache/incubator-airflow/blob/master/airflow/models.py#L3087) .  And when we search certain regex in the search bar, it will hit this line(https://github.com/apache/incubator-airflow/blob/master/airflow/www/views.py#L2131) which will check for all the dags in dag table whether the dag_id or dag.owners match the search term. If the owners is None, it will throw an exception as following.
screen shot 2018-08-09 at 11 13 00 pm

**Comment by feng-tao** [comment]
PTAL @r39132 , any other concern?

**Comment by feng-tao** [comment]
PTAL @mistercrunch , @r39132

**Comment by r39132** [comment]
Hi Feng!
So, a couple things. I have been trying really hard to reproduce this bug. I understand your fix, but am also trying to understand how you were able to reproduce this. 

Here's why. 
If I specify a DAG that is missing an owner, the default_owner in airflow.cfg seems to be getting used. If I remove that configuration and retry, somehow, `Airflow`, is still specified as the owner. If I specify `None`, I get an exception that I showed earlier -- the DAG will not even be imported. If I specify `''` (empty string), the UI works as expected. 

Ignoring the fact that I can't reproduce this, I do wonder about your fix. Your fix won't search for dag_id match if the owner field is missing. That does not feel like the right fix. Why not look for a match against both fields, only ignoring the owner field if the owner field is missing.

**Comment by r39132** [comment]
@feng-tao ^

**Comment by feng-tao** [comment]
@r39132 , let's close this pr for now and revisit once I have time. We did have a dag which the owners field is None in metastore table. This causes our server UI search throws exceptions.

**Comment by r39132** [comment]
@feng-tao I'm ok with the code-guard, but wanted to ensure the fix does what we intend. Please reopen when you would like to revisit.

**Pull request closed without merging**
