### PR TITLE
Add missing imports to app.py

### LINKED ISSUE #10053: Error "Name 'flask' is not defined" when changing the force_log_out_after
**Apache Airflow version**: 1.10

**Kubernetes version (if you are using kubernetes)** (use `kubectl version`):

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release):
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
- **Kernel** (e.g. `uname -a`): 4.14.186-146.268.amzn2.x86_64 (Amazon Linux 2)
- **Install tools**: Pip
- **Others**:

**What happened**:
When setting the **force_log_out_after** variable to a number different from the default 0, the error below is displayed when trying to login.

Other parameters that may be important:
**authenticate** = True
**auth_backend** = airflow.contrib.auth.backends.ldap_auth

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/usr/local/lib/python3.7/site-packages/airflow/www/app.py", line 198, in before_request
    flask.session.permanent = True
NameError: name 'flask' is not defined
```

**What you expected to happen**:
The user session should be forced to log out after the set amount of time.

**How to reproduce it**:
Change the **force_log_out_after** from the default value.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by kunz07**
Add missing imports to app.py to fix exception thrown when force_log_out_after config setting is set to values other than 0

closes: #10053

### CODE REVIEW

**Review by XD-DENG — COMMENTED** [review]
I believe issue #10053 is an accidental issue made during the cherry-picking.

Different approach should be used to fix it. For example, 'flask.session' is actually already imported at line 29 with alias "flask_session". We should use "flask_session" rather than import flask.

I suggest to leave this to release manager (ping @kaxil )

**Comment by XD-DENG** [comment]
Or maybe @kaxil can advise the contributor what's the easiest way for you to merge the PR? So the contributor can address accordingly.

**Review by kaxil — APPROVED** [review]
Thanks for the PR. I agree with @XD-DENG on `flask_session` vs `flask.session` bit but that can happen in a separate PR since it affects Master too: https://github.com/apache/airflow/blob/master/airflow/www/extensions/init_session.py

**Comment by kaxil** [comment]
Re-running the tests since last time it didn't complete for some reason

**Pull request merged**
