### PR TITLE
[AIRFLOW-2138] Google Cloud Storage to Google Cloud Storage Operator to allow wildcards

### PR DESCRIPTION
**Pull request by DannyLee12**
Closes #2138 closes #AIRFLOW-2138

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-2138

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
   - https://issues.apache.org/jira/browse/AIRFLOW-2138
- Add support for wildcards to be provided in source object argument
This allows the user of the Operator to provide a wildcard in the format accepted by the documentation. This message is echoed in the docstring for ease of use, and also because it is only three sentences and adding a link is not required.
- Add an argument move_object (bool) to the operator that, when true runs a mv command  as opposed to a cp command. That is to say, it moves an object instead of copying the object. This is especially useful when this operator is used to move objects in the same bucket, perhaps from folder to folder.
- Add dotmodus and dannylee12 to companies using airflow
We use airflow in almost all of our projects.

### Tests
- [x] Unit tests have been added, they acheive what they set out to acheive. All other elements are tested previously. This PR does not change any functionality of the underlying hooks, but rather extends how they can be used.
### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. 
Not sure how to squash commits? 
In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
Please follow guidelines of commit messages.

**Comment by DannyLee12** [comment]
Updated commit message to follow guidelines.

**Comment by kaxil** [comment]
You need to also include Jira issue in commit message. Check other PR for example.

**Comment by DannyLee12** [comment]
Updated commit header to include Jira issue. As per the other PRs.

**Comment by Fokko** [comment]
Thanks for taking the time to update the `CONTRIBUTING.md`, unfortunately this should be a separate ticket. If you split this into a different ticket, and remove those changes from this PR, I'll merge the PR.

**Comment by DannyLee12** [comment]
@Fokko I've removed the offending files, needed to open and close as travis timed out.

**Comment by Fokko** [comment]
@DannyLee12 Thanks it looks good now. One last question. Would it be possible to add a test to check the `*` execution path?

@kaxil any further remarks?

**Comment by DannyLee12** [comment]
Yeah I can try and include that, I don't think that this operator has any
tests, so I'll see what I can add.

Regards,

Daniel Lee
Senior Software Engineer
0727672055
Daniel@dotmodus.com
<https://mail.google.com/mail/u/1/#inbox>

**Comment by Fokko** [comment]
Thanks @DannyLee12, much appreciated

**Comment by DannyLee12** [comment]
@Fokko I've added 3 tests, not sure what's going on with codecov, please tell me if I've changed those files, else I don't understand how I've affected the coverage in those files?

**Comment by kaxil** [comment]
This LGTM @Fokko

**Comment by DannyLee12** [comment]
@Fokko please take a look when you get a chance?

**Comment by Fokko** [comment]
@DannyLee12 Thanks!

I've removed:
```
+1. [dotmodus](http://dotmodus.com) [@dannylee12](https://github.com/dannylee12)
```
Please open a new PR. This list needs to be alphabetically. Thanks! 👍

**Pull request closed without merging**
