### PR TITLE
Allows to build production images for 1.10.2 and 1.10.1 Airflow

### LINKED ISSUE #10974: GPL dependency error when trying to build image wiith breeze (airflow 1.10.2)
**Apache Airflow version**: 1.10.2

- **OS** (e.g. from /etc/os-release): Mac OS X | 10.15.6

**What happened**: I can't build image through using the following breeze commad

./breeze build-image --production-image --install-airflow-version="1.10.2"

Removing intermediate container f0ac3df80323
 ---> 0ac6851388bc
Step 50/65 : ENV AIRFLOW_INSTALL_VERSION=${AIRFLOW_INSTALL_VERSION}
 ---> Running in 057c99021846
Removing intermediate container 057c99021846
 ---> 55e48234a411
Step 51/65 : WORKDIR /opt/airflow
 ---> Running in 969b54f7df4c
Removing intermediate container 969b54f7df4c
 ---> 3fb9c6b83054
Step 52/65 : RUN pip install --user "${AIRFLOW_INSTALL_SOURCES}[${AIRFLOW_EXTRAS}]${AIRFLOW_INSTALL_VERSION}"     --constraint "${AIRFLOW_CONSTRAINTS_URL}" &&     if [ -n "${ADDITIONAL_PYTHON_DEPS}" ]; then pip install --user ${ADDITIONAL_PYTHON_DEPS}     --constraint "${AIRFLOW_CONSTRAINTS_URL}"; fi &&     find /root/.local/ -name '*.pyc' -print0 | xargs -0 rm -r &&     find /root/.local/ -type d -name '__pycache__' -print0 | xargs -0 rm -r
 ---> Running in 8891a38dcfed
pip install --user 'apache-airflow[async,aws,azure,celery,dask,elasticsearch,gcp,kubernetes,mysql,postgres,redis,slack,ssh,statsd,virtualenv]==1.10.2' --constraint https://raw.githubusercontent.com/apache/airflow/constraints-1.10.2/constraints-3.7.txt
Collecting apache-airflow[async,aws,azure,celery,dask,elasticsearch,gcp,kubernetes,mysql,postgres,redis,slack,ssh,statsd,virtualenv]==1.10.2
  Downloading apache-airflow-1.10.2.tar.gz (5.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f0xtaqnq/apache-airflow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f0xtaqnq/apache-airflow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-64dcdo1n
         cwd: /tmp/pip-install-f0xtaqnq/apache-airflow/
    Complete output (11 lines):
    /tmp/pip-install-f0xtaqnq/apache-airflow/setup.py:23: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f0xtaqnq/apache-airflow/setup.py", line 429, in <module>
        do_setup()
      File "/tmp/pip-install-f0xtaqnq/apache-airflow/setup.py", line 287, in do_setup
        verify_gpl_dependency()
      File "/tmp/pip-install-f0xtaqnq/apache-airflow/setup.py", line 53, in verify_gpl_dependency
        raise RuntimeError("By default one of Airflow's dependencies installs a GPL "
    RuntimeError: By default one of Airflow's dependencies installs a GPL dependency (unidecode). To avoid this dependency set SLUGIFY_USES_TEXT_UNIDECODE=yes in your environment when you install or upgrade Airflow. To force installing the GPL version set AIRFLOW_GPL_UNIDECODE
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/bash -o pipefail -e -u -x -c pip install --user "${AIRFLOW_INSTALL_SOURCES}[${AIRFLOW_EXTRAS}]${AIRFLOW_INSTALL_VERSION}"     --constraint "${AIRFLOW_CONSTRAINTS_URL}" &&     if [ -n "${ADDITIONAL_PYTHON_DEPS}" ]; then pip install --user ${ADDITIONAL_PYTHON_DEPS}     --constraint "${AIRFLOW_CONSTRAINTS_URL}"; fi &&     find /root/.local/ -name '*.pyc' -print0 | xargs -0 rm -r &&     find /root/.local/ -type d -name '__pycache__' -print0 | xargs -0 rm -r' returned a non-zero code: 1

I don't understand this error, I ran the same command with another version of airflow (./breeze build-image --production-image --install-airflow-version="1.10.2") and it worked as well.

I have to use the version 1.10.2 and for me breeze is a good way to build env easily.

Best regards,

### PR DESCRIPTION
**Pull request by potiuk**
Airflow below 1.10.2 required SLUGIFY_USES_TEXT_UNIDECODE env
variable to be set to yes.

Our production Dockerfile and Breeze supports building images
for any version of airflow >= 1.10.1 but it failed on
1.10.2 and 1.10.1 because this variable was not set.

You can now set the variable when building image manually
and Breeze does it automatically if image is 1.10.1 or 1.10.2

Fixes #10974

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @folly3

**Comment by potiuk** [comment]
Hey everyone - this one is in fact green - I am moving the flaky test from  issue #10988 in #10989 but other than it's good to go IMHO.

**Comment by ashb** [comment]
I mean I have no problem with this, other than want to know why you want to build a docker image for such an old 21+ month old version.

**Review by ashb — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
> I mean I have no problem with this, other than want to know why you want to build a docker image for such an old 21+ month old version.

It's not me. It's one of the users who want to do it :).

**Comment by folly3** [comment]
I confirme it's work on my side now.
Thanks a lot guys ! I

Regards

**Comment by potiuk** [comment]
one more happy user :)

**Comment by potiuk** [comment]
But @folly3 -> what @ashb wrote is very true. You will be way better migrating to latest version of Airflow sooner rather than later. There are a  TON of improvements since 1.10.2

**Comment by folly3** [comment]
haha, 21 months... I didn't see the comment of @ashb , I have joined a new company since last monday and they work on this version. They are looking for a plan to upgrade their airflow, we are open to any advice to handle this task (which solutions ? breeze, composer etc)

**Comment by potiuk** [comment]
Well. I think it really depends how big installation /tech savvy you are. It can be self-hosted installation if you can afford running/hosting or (we have helm charts I our repo but they are not yet officially released for one).. you can also choose composer If you want to run it as a 'service' or Astronomer as well. With Astronomer you can also have on-premise version with a.lot of maintenance (such as images/helm etc. taken care of and a cli interface to manage). So plenty of options :)

**Pull request merged**
