### PR TITLE
[AIRFLOW-419] Setting task instance status through UI causes exception

### PR DESCRIPTION
**Pull request by saaratstaples**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
    https://issues.apache.org/jira/browse/AIRFLOW-419

Testing Done:
    Local testing.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
We accept fractional seconds, so removing granularity is not the right approach to solve this issue.

**Comment by saaratstaples** [comment]
@bolkedebruin - Understood. How is this handled in datastores that do not support fractional seconds? Isn't this the main cause of the issue - datastores not supporting the accepted granularity?

**Comment by bolkedebruin** [comment]
We don't support those datastores as a backend for Airflow. 

MySQL 5.6.4+ changed its behavior towards fractional seconds. This means that if you do a comparison with a fractional part, ie. datetime.now(), it wont match against what is stored as MySQL's default is not to store fractional seconds. This has been fixed in master.

Officially we support MySQL and Postgres as a backend. Thus use Postgres or MySQL < 5.6.4 with Airflow 1.7.1.3 or use master with either Postgres and MySQL 5.6.4+.

**Comment by saaratstaples** [comment]
My experience with Airflow 1.7.1.3 / Postgres 9.3.13 or 9.5.4 / SQLAlchemy 1.1.4 and fractional seconds was unstable behavior due to mismatch in the timestamp. I did not experience this with SQLite (default) which doesn't support fractional second granularity. Removing the fractional second granularity from the table definitions resolved this. I recall looking at the SQLAlchemy code but can't find the code section at the moment. It automatically adjusts for DB type precision during comparisons which corrects for comparisons to datetime.now() with higher precision.

**Comment by GregTD42** [comment]
This problem is still showing up in Airflow 1.9.0.  This is the result when I go to Task instance and attempt to set status to Success (get similar when I try to set it to failed).

I really do need a way to stop a running DAG

Traceback (most recent call last):
  File "/apps/dist/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/dist/python/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/dist/python/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/dist/python/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/dist/python/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/apps/dist/python/lib/python2.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/apps/dist/python/lib/python2.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/apps/dist/python/lib/python2.7/site-packages/flask_admin/model/base.py", line 2068, in action_view
    return self.handle_action()
  File "/apps/dist/python/lib/python2.7/site-packages/flask_admin/actions.py", line 113, in handle_action
    response = handler[0](ids)
  File "/apps/dist/python/lib/python2.7/site-packages/airflow/www/views.py", line 2344, in action_set_success
    self.set_task_instance_state(ids, State.SUCCESS)
  File "/apps/dist/python/lib/python2.7/site-packages/airflow/utils/db.py", line 53, in wrapper
    result = func(*args, **kwargs)
  File "/apps/dist/python/lib/python2.7/site-packages/airflow/www/views.py", line 2382, in set_task_instance_state
    raise Exception("Ooops")
Exception: Ooops

**Comment by ron819** [comment]
Also happens to me in 1.9.0
Duplicated ticket: https://issues.apache.org/jira/browse/AIRFLOW-3364

From what I can tell this bug will follow also to the new UI.

**Comment by Rotemlofer** [comment]
Encountered this today.
Will this be fixed?

**Comment by Rotemlofer** [comment]
Is there an update on this?

**Comment by saaratstaples** [comment]
> Is there an update on this?

The approach was rejected by Airflow maintainers. If they are reconsidering this, I can update the branch to resolve conflicts.

**Comment by feng-tao** [comment]
PTAL @bolkedebruin , any other suggestions, we encounter this issue as well.

**Comment by OmerJog** [comment]
Here is a list of all tickets that are possibly linked/related to this bug:

https://issues.apache.org/jira/browse/AIRFLOW-419
https://issues.apache.org/jira/browse/AIRFLOW-1254
https://issues.apache.org/jira/browse/AIRFLOW-1484
https://issues.apache.org/jira/browse/AIRFLOW-1773
https://issues.apache.org/jira/browse/AIRFLOW-3553

**Comment by feng-tao** [comment]
what do you think @ashb ? I am not sure if there are any other way to fix this issue which also handles ms case. But our production system also encountered this bug as well.

**Comment by UltaLior** [comment]
@feng-tao it also happened to us in production. I see this is a known issue for 2 years. Is there intention to resolve this?

**Comment by astahlman** [comment]
Do we actually need to truncate the fractional seconds in the database? The dateutil parser seems to be able to handle timestamps with or without the microseconds field:

```
>>> import dateutil.parser
>>> dateutil.parser.parse('2019-04-01 00:00:00.000000') == dateutil.parser.parse('2019-04-01 00:00:00')
True
```

**Comment by milton0825** [comment]
Looks like this is not an issue anymore in the latest master. I was able to delete a task with execution_date that contains fraction of seconds.

**Comment by ashb** [comment]
Has anyone tested this on 1.10.x with the "classic" UI?

**Comment by dimberman** [comment]
@saaratstaples is this PR still relevant or can we delete this?

**Comment by saaratstaples** [comment]
@dimberman - You can reject this PR. Given all the 'me too' comments, I think this is still an issue since the different RDBMs supported by SqlAlchemy that can be used with Airflow have different default time resolutions.

**Pull request closed without merging**
