### PR TITLE
[AIRFLOW-865] - Configure FTP connection mode

### PR DESCRIPTION
**Pull request by s7anley**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-865

Testing Done:
- Unit test

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks for your contribution. Tests are required. Please use mock for unit tests or add a ftp server to Travis configuration for integration tests

**Comment by s7anley** [comment]
@bolkedebruin, you are right, i should provide unit test, since `ftplib.FTP` is the component which should be tested against actual FTP server. Thanks.

**Comment by bolkedebruin** [comment]
LGTM

**Comment by s7anley** [comment]
Rebased with current master.j

**Comment by s7anley** [comment]
Rebased with current master. Travis is [green](https://travis-ci.org/s7anley/incubator-airflow).

**Comment by s7anley** [comment]
Hi, @bolkedebruin any chance you can look on this PR on more time? Thanks!

**Comment by ron819** [comment]
@s7anley Can you rebase?

**Pull request closed without merging**
