### PR TITLE
Add Snowpark operator and decorator

### LINKED ISSUE #24456: Add Snowpark Operator that allows execution of Snowflake Snowpark code
### Description

A Snowpark operator (similar to the Snowflake Operator) that executes Snowpark for Python Code. Credentials are handled the same way for Snowflake Operator. Code is executed the same ways to the Python Operator.

### Use case/motivation

I would like to be able to to schedule snowflake-snowpark-python code that I have developed.  Instead of having to write lengthy SQL statements, I would prefer to develop in my language of choice.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by sfc-gh-jdu**
---
closes: #24456 

This is the first step of adding Snowpark-related operators and decorators. We will add more in the following PRs (e.g., running snowpark in virtual env). This PR also includes unit tests, system tests and documentation changes. 

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by sfc-gh-jdu** [comment]
Hi @potiuk and @mik-laj, could you please take a look? Thanks!

**Comment by potiuk** [comment]
> Could anyone please take a look? Thanks!

I think there is a problem with dependencies that causes PROD build to fail

**Comment by potiuk** [comment]
Or simply rebase might fix it.

**Comment by sfc-gh-jdu** [comment]
> > Could anyone please take a look? Thanks!
> 
> I think there is a problem with dependencies that causes PROD build to fail

Yeah I checked CI failures last week, it seems unrelated. I rebased once but got some new failures you saw here. @jscheffl Thanks for rebasing it!

**Comment by sfc-gh-jdu** [comment]
> Or simply rebase might fix it.



> Or simply rebase might fix it.

All merge gates are green now. Can you please take a look when you get a chance? Thanks!

**Review by jscheffl — APPROVED** [review]
I have no real expertise with Snowflake/Snowpark, generally the cod elooks OK but can not judge functional correctness. Second eye review requested before merge.

**Review by potiuk — APPROVED** [review]
LGTM as well. Though also - I do not know details of Snowflake integration.

Speaking of which.....

Maybe it is a good idea that Snowflake team implements System Tests and system test dashboard similar to the ones that Amazon, Google. Astronomer and Teradata did (see https://airflow.apache.org/ecosystem/#airflow-provider-system-test-dashboards ) 

We had a talk about it at Airflow Summit (recording will be published soon) where the authors of such dashboard explained what benefit it brings to them and that might be a great way to make sure that the quality of integration with Snowflake is maintained over time. 

See https://airflowsummit.org/sessions/2024/hello-quality-building-cis-to-run-providers-packages-system-tests/  for description of the talk (recordings should be avaoilable at this link soon)

**Comment by sfc-gh-jdu** [comment]
> LGTM as well. Though also - I do not know details of Snowflake integration.
> 
> Speaking of which.....
> 
> Maybe it is a good idea that Snowflake team implements System Tests and system test dashboard similar to the ones that Amazon, Google. Astronomer and Teradata did (see https://airflow.apache.org/ecosystem/#airflow-provider-system-test-dashboards )
> 
> We had a talk about it at Airflow Summit (recording will be published soon) where the authors of such dashboard explained what benefit it brings to them and that might be a great way to make sure that the quality of integration with Snowflake is maintained over time.
> 
> See https://airflowsummit.org/sessions/2024/hello-quality-building-cis-to-run-providers-packages-system-tests/ for description of the talk (recordings should be avaoilable at this link soon)

Yes! @mik-laj already told me that and I'm working on such a dashboard now

**Comment by potiuk** [comment]
> Yes! @mik-laj already told me that and I'm working on such a dashboard now

👀 👀 👀 👀 👀 👀 👀 👀

**Pull request merged**
