### PR TITLE
Support jinja2 native Python types

### PR DESCRIPTION
**Pull request by kaxil**
This is second attempt to https://github.com/apache/airflow/pull/4900

Docs: https://jinja.palletsprojects.com/en/2.11.x/nativetypes/

```python
>>> from jinja2 import nativetypes
>>> ne = nativetypes.NativeEnvironment()
>>> import pendulum
>>> ne.from_string('{{ x }}').render(x=pendulum.now())
<Pendulum [2021-03-04T15:33:17.073343+00:00]>

>>> ne.from_string('{{ x }}').render(x=pendulum.now().isoformat())
'2021-03-04T15:33:29.516540+00:00'
>>> ne.from_string('{{ x }}').render(x="2012-10-10")
'2012-10-10'
```

Current:

```python
>>> environment.Environment().from_string('{{ ["w","x"] }}').render()
"['w', 'x']"
```

Proposed:
```python
>>> nativetypes.NativeEnvironment().from_string('{{ ["w","x"] }}').render()
['w', 'x']
```

The problem with replacing `Environment` as `NativeEnvironment` only is
that `NativeEnvironment` does not raise an error on Undefined templates so it won't respect `DAG.template_undefined`:

https://github.com/pallets/jinja/blob/2.11.3/src/jinja2/nativetypes.py#L70-L94

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
If the approach looks correct I will go ahead and docs for the same.

**Review by ashb — COMMENTED** [review]
Not a huge fan of needing to add a new arg (I understand why we need it though);

Perhaps we could make something like this work:

```python
from airflow.templates import native_template as nt

task = MockOperator(task_id="op1", arg1=nt("{{ foo }}"(, arg2=nt("{{ bar }}") arg3='{{ ds }}' )
```

**Comment by turbaszek** [comment]
I think that flag on DAG level will make things more consistent. The `nt` solution proposed by @ashb is interesting one but it's a bit of additional work - at least to me.

Whatever we will decide - lets extend the docs to cover this feature 👌

**Comment by kaxil** [comment]
Re-thinking this -- I agree with Tomek that keeping it same per DAG makes it more consistent and reason about and remove complexity.

@ashb WDYT? If you agree with current approach, I can add docs to describe this feature

**Comment by ashb** [comment]
Sure, I guess this will work and it's unlikely people will want to mix them in one dag? Not sure.

Docs now please!

**Comment by kaxil** [comment]
> Sure, I guess this will work and it's unlikely people will want to mix them in one dag? Not sure.
> 
> Docs now please!

Done in https://github.com/apache/airflow/pull/14603/commits/4aacd2bef6587e93b1047b05ca57f4790c701282

**Comment by kaxil** [comment]
Tests are green, ping @ashb @turbaszek

**Review by potiuk — APPROVED** [review]
Nice!

**Pull request merged**
