### PR TITLE
Clarify breeze install message re pipx vs `./breeze`

### PR DESCRIPTION
**Pull request by dstandish**
The first sentence, "When you have multiple copies of Airflow" was momentarily confusing.  It wasn't obvious that the context was "to use pipx or ./breeze".  I try to make that a little clearer here.

### CODE REVIEW

**Comment by potiuk** [comment]
Hmmm. That's not really correct. The new `breeze` actually REQUIRES `pipx` . This is the only supported method of installation. The `./breeze` script is merely wrapper around it when you look closely.

Maybe the message should be clearer but it's not either-or. The `./breeze` script is temporary to ease people to migrate but we will remove it eventually.

We thought and tried quite some time about whether to support two ways of running `breeze` but due to autocomplete requiring installing the `airflow-breeze` as package AND having `breeze` on the path - we chose `pipx` as the only way to install the new breeze.

This has been captured in ADR 10 here with the detailed reasoning and invalidating earlier ADR 3 where we did not decide about the way of installation until we learn more: https://github.com/apache/airflow/blob/main/dev/breeze/doc/adr/0010-use-pipx-to-install-breeze.md (includes context and consequences).

If you do not use `pipx`, there are few consequnces. Most notable is that "self-upgrade" command will not work. It assumes breeze is installed with `pipx` and will attempt to use `pipx` to upgrade it to get latest dependencies installed. It even allows you to reinstall `breeze` from a different source tree (because it might be that you have version 2.3 and main where `main` breeze will not work on `2.3` branch. Breeze warns the user if you try to use it from a wrong source tree and offers you to reinstall it. 

This all is strongly rooted with the  assumption that breeze is installed with `pipx`.

**Comment by potiuk** [comment]
(and yeah we MUST update the instructions - they are wrong currently).

**Comment by potiuk** [comment]
I completely missed updatinng those instructions after making this decision :blush:

**Comment by dstandish** [comment]
Ok sounds good, was just making assumptions

Will close

**Comment by potiuk** [comment]
Actuallly - this message should not be there at all :). It's chicken-egg. You won't see it until Breeze is installed, but if you have it installed, you don;t need it any more :) #22923 removes it :)

**Comment by dstandish** [comment]
haha yeah thought it was bit weird but did not give it much thought

**Pull request closed without merging**
