### PR TITLE
[AIRFLOW-2533] Fix path to DAG's on kubernetes executor workers

### PR DESCRIPTION
**Pull request by bnutt**
Make sure you have checked _all_ steps below.

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2533
 
### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
When triggering a DAG using the kubernetes executor, the path to the DAG on the worker node is not properly set due to the modification of the command that is sent to the pod for the worker node to perform.  

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Prior to removing airflow command modification: 

screen shot 2018-05-31 at 4 15 11 pm

After removal of modification:

screen shot 2018-05-31 at 4 15 11 pm

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
LGTM, less is more. Lets see what Jenkins will tell us.

**Comment by bnutt** [comment]
Thanks @Fokko , looks like one of tests failed because of

```
KIP: Failure: SkipTest (Kubernetes integration tests require a minikube cluster;Skipping tests [Errno 2] No such file or directory)
----------------------------------------------------------------------
   No Traceback
   SkipTest: Kubernetes integration tests require a minikube cluster;Skipping tests [Errno 2] No such file or directory
```
Have you seen this before?  Weirdly did not that experience that here https://travis-ci.com/bnutt/incubator-airflow/builds/74708974 with this change https://github.com/bnutt/incubator-airflow/compare/432ac718b14e...3a3227856aa6. 

Edit: Tests are passing after rebase on master

**Comment by imroc** [comment]
👍 This PR fixed my problem, why not been merged yet? we need it !

**Review by Fokko — APPROVED** [review]
Thanks @bnutt

**Pull request closed without merging**
