### PR TITLE
Adding ftp hook

### PR DESCRIPTION
**Pull request by martingrayson**
Really simple ftp hook functionality.

### CODE REVIEW

**Comment by mistercrunch** [comment]
Awesome! It's great to see this. 

Any reason why you are silencing all errors though? I'd rather see the errors come through.

**Comment by martingrayson** [comment]
Whoops, I meant to return the error but ensure the connection had been closed - my excuse is that it was late! I'll fix this shortly.

**Comment by mistercrunch** [comment]
Cool, can we squeeze it in `airflow/contrib/operators/`until we have unit tests? I'll try to see internally if we have an FTP server I could use to run tests.

**Comment by jlowin** [comment]
@martingrayson @mistercrunch did this ever get merged? I was about to write one myself but found it here.

**Pull request closed without merging**
