### PR TITLE
providers/yandex: fix typing

### PR DESCRIPTION
**Pull request by got686-yandex**
Typing changes for yandex-cloud/python-sdk (yandexcloud pypi package) types.
https://github.com/yandex-cloud/python-sdk/issues/106

### CODE REVIEW

**Comment by Piatachock** [comment]
@potiuk hi, Jarek! Here are fixes for typing in both `yandexcloud/python-sdk` and Yandex Airflow provider itself. Hope it allows unlocking our provider version 🙏

**Comment by got686-yandex** [comment]
@potiuk hi, there is fixes for issue https://github.com/yandex-cloud/python-sdk/issues/106

**Comment by Piatachock** [comment]
LGTM from Yandex

**Comment by got686-yandex** [comment]
@potiuk , good day, can you start full checks?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
