### PR TITLE
Upgrade importlib-resources version

### LINKED ISSUE #18155: Upgrade `importlib-resources` version
### Description

The version for `importlib-resources` constraint sets it to be [v1.5.0](https://github.com/python/importlib_resources/tree/v1.5.0) which is over a year old. For compatibility sake (for instance with something like Datapane) I would suggest upgrading it. 

### Use case/motivation

Upgrade a an old dependency to keep code up to date.

### Related issues

Not that I am aware of, maybe somewhat #12120, or #15991.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bmckallagat-os**
Closes #18155

Update `importlib-resources` version as the current selected version is over a year old. Fixes compatibility issues with other packages.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by bmckallagat-os** [comment]
As a note, the following unittests failed which seem to be unrelated to this change:

```
FAILED tests/www/test_security.py::TestSecurity::test_verify_public_role_has_no_permissions - AssertionError: assert [can read on DAG:test_example_bash_operator] == []
FAILED tests/www/views/test_views_base.py::test_resetmypasswordview_edit[pk-admin] - AttributeError: 'NoneType' object has no attribute 'password'
```

I didn't want to patch them due to it being out of scope of this change, but just thought I would point it out.

**Comment by bmckallagat-os** [comment]
Not sure who to ping, but you commented on the ticket so @potiuk!

**Comment by bmckallagat-os** [comment]
Checking the errors and will update accordingly.

**Review by kaxil — APPROVED** [review]

**Comment by uranusjr** [comment]
This broke tests in main, see #18225.

**Pull request merged**
