### PR TITLE
[AIRFLOW-676] Do not allow Pools with 0 slots

### PR DESCRIPTION
**Pull request by r39132**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-676

Testing Done:
Manual testing done. Refer to screen shots below (image uploads don't work, so I've attached links) : 

**Screenshot 1: Disallow creation of 0-slot pool**
https://www.dropbox.com/s/90biqz6br8xgqkq/test_empty_pool_create.png?dl=0

**Screenshot 2: Disallow editing of 0-slot pool - before edit attempt**
https://www.dropbox.com/s/enkohy3k6g0wrvj/test_empty_pool_edit_before.png?dl=0

**Screenshot 3: Disallow editing of 0-slot pool - after edit attempt**
https://www.dropbox.com/s/2misa034wl569gd/test_empty_pool_edit_after.png?dl=0

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Why would this be needed? Sometimes it can be convenient to change a pool to 0 to disallow new tasks to run.

**Comment by r39132** [comment]
I disagree with that approach for a few reasons. 

Firstly, I'd prefer fewer (ideally a single) means to achieve a goal in Airflow, rather than multiple half-measures. If a user wants to pause a DAG, he/she should be provide a single, conspicuous, intuitive means to pause the DAG. The current solution for that is the "Pause DAG" UI control, now found on every DAG-centric UI Page. Setting the slot size to 0 is a hack. Also, it interferes with a lot of best practices around configuration management. Connections, Pools, & Variables are all part of configuration and should ideally be controlled by configuration management tooling (e.g. Ansible, Chef, Puppet, etc...). Manually altering these is hacky. Worse yet, altering them opens the door to forgetting about it and then having to track down why a DAG is not running. 

This happened to us in production. It was not at all obvious why a DAG stopped running and we needed to follow a process of elimination to figure it out.

Secondly, what do you expect to happen when the pool size is set to 0? I'd expect to see queued tasks. In 1.7.1.3, which is what we run in production, this does not happen. Instead, there are no state indicators on the DAG or Tree views. This situation falls in the "why is the DAG not being scheduled" category, which I hope you agree should be minimized. 

I'd rather have an exception surface when a pool does not exist or to see queued tasks, both of which make it easy to diagnose and resolve an issue. A 0-slot pool is currently a silent error. We could submit a fix in the scheduler for this as well, though when I consider my first point, I'd prefer to disallow silly things like an empty resource pool. 

The pain of a 0-slot pool outweighs its value IMO.

**Comment by bolkedebruin** [comment]
I understand your points however I think the behaviour changed in master and some people might actually use it. So maybe it is an idea to discuss this on the mailinglist first. Maybe a warning is better?

**Comment by cademarkegard** [comment]
This makes total sense. I like that the project is moving towards a path where state is more easily determined. I'd like to see some sort of unit test (even basic) to be apart of the PR also.

**Comment by r39132** [comment]
@bolkedebruin I've tested the existing behavior on latest master (without my fix). 

Including other maintainers : @jlowin @criccomini 

Master has a new state `scheduled`, not present in 1.7.1.3. Currently, if the pool size is set to 0, the state indicator on the tree view is a black square for `scheduled` -- `note : the graph view doesn't show any state indicator and tree view is actually missing a legend entry for this new scheduled state.`, so these should have been part of the original PR that added the `scheduled` state.

Having the new `scheduled` state is helpful, but I'd prefer to see tasks `queued` not `scheduled` in this case. There may be other reasons a task is stuck in the `scheduled` state but a `queued` entry is more directly attributable to a pool oversubscription issue. 

Additionally, this does not address my first point : using the Pause DAG controls now  available in the UI, CLI, and possibly API.
Here are some screen shots from master.

**Pool Entry - Slots set to 0**
https://www.dropbox.com/s/8f1j36uoit4m90y/Screenshot%202016-12-31%2009.57.40.png?dl=0

**Tree View - Take Note of Scheduled State for First Task Depending on Pool**
https://www.dropbox.com/s/h06o69ozyf8eojt/Screenshot%202016-12-31%2009.57.07.png?dl=0

**Graph View - Take Note There is no Task State Indicator for this Case**
https://www.dropbox.com/s/diw8dne28oohf1r/Screenshot%202016-12-31%2009.56.54.png?dl=0

**Code View - Notice Task that uses the Pool**
https://www.dropbox.com/s/k0ly4bc1ov6qjf8/Screenshot%202016-12-31%2009.55.46.png?dl=0

**Comment by mistercrunch** [comment]
I think it's a good thing to be able to disable a pool [temporarily], and setting it to 0 is probably the only way to do that currently. Say if you'd have a Redshift pool use across many DAGs, and would like to temporarily disable Redshift (say for some maintenance task), setting that pool to 0 would be easy and more targeted than pausing all the DAGs, which would also stop progress on other tasks which in theory can run.

I agree that we should formalize the `scheduled` state, with a specific, coherent color and representation throughout the UI

**Comment by r39132** [comment]
@mistercrunch You mean.. to disable a pool across multiple DAGs in order to indicate that a resource is down? I can see that use-case. 

However, It's hacky. I propose a different approach :  a UI control called `Enable/Disable Pool` backed by a new boolean column in the pool table and a check in the scheduler for this case.  The problem with setting the value from N to 0 is remembering what N was when you need to reset it.

Additionally, as mentioned, it's already bitten us in production. I prefer stricter aka less ambiguous failure semantics around this.

**Comment by gwax** [comment]
All this does is prohibit setting a pool to 0 in the UI. If the goal is to prevent this, would it be better to constrain the Pool SQLAlchemy model as well?

**Comment by r39132** [comment]
@gwax Right.. makes sense to do it higher up.

**Pull request closed without merging**
