### PR TITLE
Group options in shell and start-airflow commands

### PR DESCRIPTION
**Pull request by potiuk**
The shell and start-airflow commands started to have more options and the "advanced" flags became a bag of everything. This change groups the options in more logical groups at help screen. The option groups are also logically sequenced, they basically reflect things as they are happening:

* first user selects what integration/backends/python to use
* then executor
* then - if options are selected - image gets rebuild with options before shell is entered
* then sources/mypy-volume get mounted
* then - if options are selected - packages are possibly installed inside the image

It should make it easier to understand what's going on and which options to choose.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @utkarsharma2 @pankajkoti @vincbeck 


image

**Comment by potiuk** [comment]
compare it with:

image

**Review by vincbeck — APPROVED** [review]
Nice! More clear indeed!

**Review by utkarsharma2 — APPROVED** [review]
Much more intuitive :)

**Review by uranusjr — APPROVED** [review]

**Review by pankajkoti — COMMENTED** [review]
Looks cooler! 

@potiuk Just for my understanding, could you please let me what is the process you follow to generate those svg files? I see it in quite a few breeze related PRs. So would like to understand how we create those, which software to use? 

In general, I know we can create screenshots on MacOS. So, I would have run `breeze start-airflow -h` and created a screenshot from the iTerm app. But is there as said standard and tools/terminals we need to adopt to here for creating the end output svg files?

**Comment by potiuk** [comment]
Yes - it should happen automatically when you run pre-commits. In vast majority of cases the images should be automatically regenerate for you when you have pre-commit installed and you should not worry about it, just commit the changes when they are generated.

Funny thing that in this case breeze it's own dog food. What happens when you run precommit is .... .... it runs breeze to generate the images of breeze commands :D

There is `breeze setup regenerate-command-images` that you can use to regenerate them 

Screenshot 2023-06-14 at 19 55 31

You can run it manually and generte each command selectively if you want, you can even `--force` it - because when you run the command by default it will only regenerate the images where the commands changed (new flag, description, help etc).  Sometimes you need to regenerate the images with `--force` - for example I needed to do it wihen I grouped the options, because grouping the options is not included in check if "anything changed". That's the only thing that is not checked.

The image for each command should be generated automatically every time any description, flag etc. changes. We know when to regenerate each command because we store hash of each command in https://github.com/apache/airflow/blob/main/images/breeze/output-commands-hash.txt and whenever we (or pre-commit) runs `breeze setup regenerate-commands` it will compare hashes stored in the file with the defiition of command that @click has and it will generate the images (and update the hasj) when it finds they are different.

Technology - it's done thanks to the fact that we use rich, click and rich-click. Rich has the capability of producing screenshots from whatever it displays, click provides commands (and ability to inspect them to see if they changed), rich-cllick binds the two together.

**Comment by pankajkoti** [comment]
Okay, this is a great knowledge add.

Thank you for the hints @utkarsharma2 @vincbeck 🙏🏽

Thanks a lot for @potiuk the deatiled tutoring, very helpful :)

**Comment by potiuk** [comment]
BTW. Small proposal here @pankajkoti -> if you want to get more hands on, actually there should be a way to improve the "group change" case a bit. As mentioned above, when you "just" move things around in "command*_config.py" (i.e. like in this case groupping commands together) the images will not be regenerated automatically - because the `hash` generated  only hashes the "click" information and not the "rich-click" information that contains the groupping information. Extending the hash to also including groups is the small thing that I did not do - but it should be entirely possible.


Maybe a good way to learn how it works  `by doing` (just saying). It will make it slightly easier to not forgot to force generation of the screenshots when we change grouping in the future.

**Comment by potiuk** [comment]
As you see in this PR ^^ - hashes did not change, I had to manually run:

```
breeze setup regenerate-command --force --command start-airflow --command shell
```

to regenerate the images. 

If this behaviour is fixed, hashes in https://github.com/apache/airflow/blob/main/images/breeze/output-commands-hash.txt should change after just grouping changes, and regeneration should happen by pre-commit automatically.

**Comment by pankajkoti** [comment]
yes, definitely would like to work on it. Thank you for the suggestion @potiuk  :) On my to-do list :)

**Pull request merged**
