### PR TITLE
[AIRFLOW-3190] Make flake8 compliant

### PR DESCRIPTION
**Pull request by Fokko**
Enforce Flake8 over the entire project

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-3190\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3190
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-3190\], code changes always need a Jira issue.

### CODE REVIEW

**Comment by Fokko** [comment]
@kaxil The day of Flake8 compliant Airflow has come. I had some spare time in the plane 👍

**Comment by kaxil** [comment]
Awesome @Fokko . Only 2 flake8 errors now:

```
./tests/sensors/test_sql_sensor.py:44:25: E128 continuation line under-indented for visual indent
./tests/sensors/test_sql_sensor.py:55:25: E128 continuation line under-indented for visual indent
```

Can you fix that and then lets merge this?  :) 🎉

**Comment by Fokko** [comment]
@kaxil All green, hit the button!

**Comment by kaxil** [comment]
Awesome... 🎉  Boom

**Pull request merged**
