### PR TITLE
Add imap_attachment_to_s3 example dag and system test

### PR DESCRIPTION
**Pull request by feluelle**
This PR / change adds imap_attachment_to_s3 systems tests by running the newly added example dags.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by feluelle — COMMENTED** [review]
NOTE for reviewers. This PR references the `amazon_system_helpers.py` which is not yet merged into master. PTAL at #8581 first.

**Comment by feluelle** [comment]
I am also wondering why I get this error when testing the backported version.

```
_______________________________________________________ ERROR collecting tests/providers/amazon/aws/operators/test_imap_attachment_to_s3_system.py _______________________________________________________
ImportError while importing test module '/opt/airflow/tests/providers/amazon/aws/operators/test_imap_attachment_to_s3_system.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.6/site-packages/_pytest/python.py:513: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/local/lib/python3.6/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
/usr/local/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:152: in exec_module
    exec(co, module.__dict__)
tests/providers/amazon/aws/operators/test_imap_attachment_to_s3_system.py:20: in <module>
    from airflow.providers.amazon.aws.example_dags.example_imap_attachment_to_s3 import S3_DESTINATION_KEY
E   ModuleNotFoundError: No module named 'airflow.providers'
```

2.0.0 works fine.

I ran the prepare backport script `./scripts/ci/ci_prepare_packages.sh amazon postgres mysql`.

@turbaszek do you have an idea?

**Comment by mik-laj** [comment]
@feluelle You must manually install the prepared package with operators.
```
pip install *.whl
```

**Comment by feluelle** [comment]
Thanks @mik-laj 

I had
```
# install any packages from dist folder if they are available
if [[ ${RUN_AIRFLOW_1_10:=} == "true" ]]; then
  pip install /dist/apache_airflow_providers_{amazon,imap,postgres,mysql}*.whl || true
fi
```
in my `variables.env` but forget to set `RUN_AIRFLOW_1_10=true`

**Review by kaxil — APPROVED** [review]

**Pull request merged**
