### PR TITLE
EdgeModifier refactoring

### LINKED ISSUE #17469: Label in front of TaskGroup breaks task dependencies
**Apache Airflow version**: 2.1.0

**What happened**:

Using a Label infront of a TaskGroup breaks task dependencies, as tasks before the TaskGroup will now point to the last task in the TaskGroup.

**What you expected to happen**:

Task dependencies with or without Labels should be the same (and preferably the Label should be visible outside of the TaskGroup).
Behavior without a Label is as follows:

```python
with TaskGroup("tg1", tooltip="Tasks related to task group") as tg1:
        DummyOperator(task_id="b") >> DummyOperator(task_id="c")

DummyOperator(task_id="a") >> tg1
```
without Taskgroup

**How to reproduce it**:

```python
with TaskGroup("tg1", tooltip="Tasks related to task group") as tg1:
        DummyOperator(task_id="b") >> DummyOperator(task_id="c")

    DummyOperator(task_id="a") >> Label("testlabel") >> tg1
```
with TaskGroup

### PR DESCRIPTION
**Pull request by avkirilishin**
closes: #17469

| Dag | Before | After |
| ------------- | ------------- | ------------- |
| simple_label | image | image |
| simple_label_reversed | image | image |
| complex_label | image | image |

Tested on dags: 
[test_label_refactoring.py.zip](https://github.com/avkirilishin/airflow/files/8018631/test_label_refactoring.py.zip)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
I think this one needs a deeper look @bbovenzi @kaxil - I think you asked for a fix in #17469 and it LOOKS like a good fix. Which (if confirmed) might even qualify for 2.2.4 release @jedcunningham ? (marked it provisionally).

I do not know that well about EdgeModifiers and relations setting but it does look legit from first point of view. And  I think possibly some unit tests here woudl be useful. WDYT?

**Comment by potiuk** [comment]
@avkirilishin - would it be possible to add some unit tests for this one ?

**Comment by avkirilishin** [comment]
> would it be possible to add some unit tests for this one?

I am ready to add some unit tests if the approach is OK.

**Comment by bbovenzi** [comment]
Yeah, I would say we should move forward with this approach.

**Comment by potiuk** [comment]
Also good for me so @avkirilishin -> adding some testswill be great.

**Comment by avkirilishin** [comment]
> Also good for me so @avkirilishin -> adding some testswill be great.

@potiuk Done

**Review by bbovenzi — APPROVED** [review]
lgtm

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
Rebasing to see if issues are fixed (should be by MS).

**Comment by potiuk** [comment]
Jsut a temporary error that needs to be handled separately.

**Pull request merged**
