### PR TITLE
Make pause DAG its own role separate from edit DAG

### LINKED ISSUE #22317: Make pause DAG its own role separate from edit DAG
### Description

As an Airflow administrator I would like to be be able to configure a user account with permissions be able to "clear" and re-run a DAG run but also _not_ be able to pause a DAG.

Currently this doesn't appear to be possible as `Toggle DAG paused status` and `Clear DAG Run` both come from the same `DAGs.can_edit` permission set.

### Use case/motivation

A failure such as an unexpected reboot may require a non-privileged user to restart a run - without needing a huge amount of permissions.

It is **_really easy_** to click and pause a DAG when viewing / browsing in the UI. 

Either cancelling an existing dag run or preventing further runs from proceeding can be an issue.

This happened a few times and has caused issues as the DAG was paused preventing important ETLs from running at their scheduled times.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by herlambang**
Add ability to pause DAGs as separate role from edit.

### Use cases

Giving users ability to running DAGs without having the ability to pause it. Also to prevent users to easily/accidentally suspend DAGs.

### Scopes

- Admin UI
- API

### Changes

- add ACTION_CAN_PAUSE ("can_pause") in security permissions
- set can_pause as part of accessible dag in security manager
- add can_pause dag as part of default USER_PERMISSIONS in security manager
- add function to check if user eligible to pause all/specific dags in security manager
- disable toggle `Pause/Unpause DAG` in home page if user is not eligible for can_pause dag
- disable toggle `Pause/Unpause DAG` in detail dag page if user is not eligible for can_pause dag
- disable toggle `Unpause DAG when triggered` in trigger form if user is not eligible for can_pause dag
- change access permission to `/paused` from ACTION_CAN_EDIT to ACTION_CAN_PAUSE on main view
- change access permission on `patch` `/dags/<dag-id>` and `/dags` from ACTION_CAN_EDIT to ACTION_CAN_PAUSE on API end point
- add can_pause on DAG Level Role access control documentation
- add migration, append can_pause permission to roles that have can_edit dag(s) permission
- add tests

closes: #22317

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by ashb** [comment]
What is edit dag role used for if not pause?

**Comment by herlambang** [comment]
To trigger Dag Run, combine with dag_run can_create

**Comment by potiuk** [comment]
I think it looks good in principle, but if I understand it correctly, it is heavily breaking change and it should have support to migrate existing permission that will work in general case.

If I understand it - someone who currently has "CAN_EDIT" role will suddenly not be able to pause dags.

In other words people who could pause dags, will suddenly loose this capability without a warning? 

If so, then this is a breaking change and we need to make sure that backwards compatibility is maintained. At the minimum level every role that currently has CAN_EDIT role should have CAN_PAUSE assigned during the migration.

We have to remember, that our users could have their roles assigned in arbitrary way so making sure that ADMIN user has all the permissions is not enough, because our users could have different roles defined on their own.

**Comment by herlambang** [comment]
Hi @potiuk , thanks for the feedback. 
I added a migration and adjust the security manager to keep the ability of pausing DAGs with current can_edit permission.
Documentation also added and tests also adjusted.
Looking forward for further review, thanks.

(Sorry for my bad on pushing dirty commit after rebase, added several people as reviewers 🙏 )

**Comment by potiuk** [comment]
I'd need others to take a look if that change makes sense.

**Comment by potiuk** [comment]
Anyone else wants to chime in ? (and @herlambang  -> you will need ot rebase and fix the conflict).

**Comment by herlambang** [comment]
> (and @herlambang -> you will need ot rebase and fix the conflict).

on it!

Changes added in description, probably to make it more appealing to read

**Comment by potiuk** [comment]
Anyone here who is more into permissions? @jhtimmins @ephraimbuddy maybe ? :)

**Comment by aru-trackunit** [comment]
@herlambang I love the work you've done so far. Looking forward to test it!

**Pull request closed without merging**
