### PR TITLE
Fix PodGenerator to handle Kubernetes resources

### PR DESCRIPTION
**Pull request by odracci**
Fix the issue #9812 

In Airflow 1.10.11, `namespaced['resources'] = resources` is missing.
This PR improves the definition of pod resources, `requests` and `limits` are optional.

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
Thanks for the PR :) appreciate it. Let's wait for the CI results

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Just line too long for flake @kaxil :(

**Comment by odracci** [comment]
The build fails with:
`Could not find a version that satisfies the requirement pandas==0.25.3 (from -c https://raw.githubusercontent.com/apache/airflow/v1-10-test/requirements/requirements-python2.7.txt`

Why CI uses requirements from `v1-10-test` instead of `v1-10-stable`?

**Review by dimberman — APPROVED** [review]

**Comment by potiuk** [comment]
I have changed the way of handling requirements now in "master" and I want to cherry-pick it to v1-10-test, but i think it's worth to do it for v1-10-stable. WDYT @kaxil  @dimberman ?

**Comment by potiuk** [comment]
This is much "better way" https://github.com/apache/airflow/pull/9889. @kaxil -I understood so far that v1-10-stable was (from time totime) rebased on top of v1-10-test (is this still the case ? Or do we want stable to be only PRs by people and cherry-picks done separately in v1-10-test? 

If the rebase is in-game, I think I would like to cherry-pick the requirement change to v1-10-test and then once the tests are OK rebase v1-10-stable on top of it. Does it make sense?

**Comment by dimberman** [comment]
@odracci can you please rebase? I have the k8s tests passing

**Comment by kaxil** [comment]
> This is much "better way" #9889. @kaxil -I understood so far that v1-10-stable was (from time totime) rebased on top of v1-10-test (is this still the case ? Or do we want stable to be only PRs by people and cherry-picks done separately in v1-10-test?
> 
> If the rebase is in-game, I think I would like to cherry-pick the requirement change to v1-10-test and then once the tests are OK rebase v1-10-stable on top of it. Does it make sense?

We only rebase v1-10-stable before cutting out a release. But we would rebase v1-10-test on v1-10-stable from time to time since most/all PRs targeting v1.10.* would be against v1-10-stable

**Comment by kaxil** [comment]
I think https://github.com/apache/airflow/pull/10140 and this one address the same problem I think

**Comment by odracci** [comment]
> @odracci can you please rebase? I have the k8s tests passing

done

**Comment by kaxil** [comment]
This is no longer needed correct @dimberman ??

**Comment by dimberman** [comment]
@odracci I'm going to close this issue but please let me know if this issue is still a problem in 1.10.14 and we can re-open/merge it.

**Pull request closed without merging**
