### PR TITLE
Add Mercari to the company list

### PR DESCRIPTION
**Pull request by yu-iskw**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
No JIRA ticket related to this PR.

### Description
Add Mercari to the company list

### Tests
We don't need any test for this PR.

### CODE REVIEW

**Comment by yu-iskw** [comment]
@skudriashev  can you tell me how to execute the travis CI again without commiting anything new.

**Comment by bolkedebruin** [comment]
Please use the alphabetical order. Thanks!

**Comment by skudriashev** [comment]
@yu-iskw you can close and reopen PR to restart tests.

**Comment by skudriashev** [comment]
@yu-iskw but I think this is not required since you change only README.

**Comment by yu-iskw** [comment]
@bolkedebruin  Thank you for the feedback! I have modified it.

**Comment by yu-iskw** [comment]
@skudriashev Thank you for the advice.

**Pull request closed without merging**
