### PR TITLE
Update LICENCE

### PR DESCRIPTION
**Pull request by Aditya-Kapadiya**

### CODE REVIEW

**Review by XD-DENG — CHANGES_REQUESTED** [review]
Hi @Aditya-Kapadiya , by following the official copy of the Apache-2 license (https://www.apache.org/licenses/LICENSE-2.0), I believe we should not make the changes you are proposing here.


Screenshot_2022-10-02_at_9_36_02_AM

**Comment by XD-DENG** [comment]
So for the reason I shared above, I would suggest to close this if you also agree, @Aditya-Kapadiya

**Comment by Aditya-Kapadiya** [comment]
Hello, @XD-DENG I also updated this changes in the below shown repository and they accepted the change. And this changes are made in the URL to make it secure. They doesn't create any conflicts. And still if you cannot accept this PR it would be great if you can guide me through the process of updating that license at (https://www.apache.org/licenses/LICENSE-2.0)

PR-Apache-License

**Comment by XD-DENG** [comment]
The license itself is a legal content, and it's not a small deal to update it, even just a single character, IMO.

The "security concern" should not apply here, given Apache site already automatically redirects visitors to HTTPS, and the page is not for transmitting any sensitive info.

Here I would strongly prefer to be aligned with whatever content Apache Software Foundation is having in their official source (https://www.apache.org/licenses/LICENSE-2.0, or https://www.apache.org/licenses/LICENSE-2.0.txt). I also checked other projects, like Spark and Cassandra, and they didn't touch their license in any way either.

**Comment by XD-DENG** [comment]
Hi @turbaszek , CCing you as the author mentioned another similar PR that you helped review (https://github.com/apache/comdev-site/pull/70). Please find my thoughts above. Thanks.

**Comment by Aditya-Kapadiya** [comment]
@XD-DENG Okay. If it automatically redirect to "https" than its fine. I will close this PR. 
But Apache should update this minor changes in their license so, in future other contributors don't open the PR to change it to "https" in past this link used to open in "http" so, I thought of requesting a change.

Thanks.

**Comment by XD-DENG** [comment]
Hi @Aditya-Kapadiya , this is only because it's the LICENSE file, the legal foundation of the projects. A single-character change to it will need legal attention and effort.

If you notice any usage of HTTP over HTTPS anywhere else (**other than LICENSE**), please do help point out and raise a PR, and we would be more than happy to change accordingly. Thanks.

**Comment by Aditya-Kapadiya** [comment]
@XD-DENG Sure, I will do that if found any such usage.

**Pull request closed without merging**
