### PR TITLE
Fix broken/renamed internal API method

### PR DESCRIPTION
**Pull request by jscheffl**
While rebasing I realized that one mapped method in internal API was renamed and broke the internal API.
This PR fixes back to the correct name.

@potiuk How could this happen if internal API is used in CI tests? I thought this is enabled now? Do we need another safety-net?
To prevent regression I added a pytest to check that method-map can be built, means this will fail if any method is moving-away

### CODE REVIEW

**Comment by potiuk** [comment]
Yeah. I also found it and fixed in https://github.com/apache/airflow/pull/41067 - so yeah. That's exactly what will not happen when we run the tests :D

**Comment by potiuk** [comment]
And yeah. By implementing the test you already implemented [the](https://github.com/apache/airflow/issues/28695)

**Review by potiuk — APPROVED** [review]

**Comment by jscheffl** [comment]
> And yeah. By implementing the test you already implemented [This one](https://github.com/apache/airflow/issues/28695)

I would say the pytest is 50% of it. Still you could add the decorator and miss listing the method in the method-map. Then the test will not fail.

**Comment by potiuk** [comment]
Agreed :)

**Pull request merged**
