### PR TITLE
feat: add read access to pools for viewer role

### PR DESCRIPTION
**Pull request by marekhanus**
Cluster Activity UI shows `FAILED TO FETCH DATA` error in pools section. Users with Viewer role do not have permission to read pools.

airflow k8s notino local_cluster_activity

Checks:

- [x] patch tested locally on Airflow 2.7.2

---

### CODE REVIEW

**Comment by raphaelauv** [comment]
@marekhanus if your PR is ready you could set it in "ready for review"

**Review by vincbeck — APPROVED** [review]

**Comment by marekhanus** [comment]
Rebase done. Conflicts after https://github.com/apache/airflow/commit/ad717ef50d58bfc442f62a7da03e2a77acd636b9 are now resolved.

**Review by raphaelauv — APPROVED** [review]
LGTM

**Comment by raphaelauv** [comment]
@marekhanus could you please rebase on main , to trigger a new CI test run

**Comment by raphaelauv** [comment]
the test `test_get_user_roles_for_anonymous_user` is failing

**Review by pierrejeambrun — APPROVED** [review]
Looking good.

I'll wait for another approval before merging this. I just want to be sure that there is no historical reason for having it this way in the first place.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> I'll wait for another approval before merging this. I just want to be sure that there is no historical reason for having it this way in the first place.

You get it :)

**Review by eladkal — APPROVED** [review]

**Pull request merged**
