### PR TITLE
[AIRFLOW-439] Add Scaleway as an Airflow user.

### PR DESCRIPTION
**Pull request by kdeldycke**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-439 Add Scaleway as an Airflow user](https://issues.apache.org/jira/browse/AIRFLOW-439).

Testing:
- Done: Not Applicable.

Changes made:
- Add Scaleway to `README.rst`. Line 111.

### CODE REVIEW

**Comment by r39132** [comment]
Thanks for your contribution. 

See my comments on https://github.com/apache/incubator-airflow/pull/1731 and how the submitter corrected it on https://github.com/apache/incubator-airflow/pull/1733

In addition to a call for references, we also want to acclimate potential future contributors with the apache commit guidelines. This is required before I can merge your change.

**Comment by kdeldycke** [comment]
Thanks @r39132 for the feedback. Just created and linked to JIRA issue: https://issues.apache.org/jira/browse/AIRFLOW-439

This PR is ready to be merged IMHO.

**Comment by r39132** [comment]
👍

**Comment by kdeldycke** [comment]
Thanks @r39132 fir the merge! :)

**Pull request closed without merging**
