### PR TITLE
Add HTML meta tags. Set the dir attribute to ltr on the opening html tag

### PR DESCRIPTION
**Pull request by jbampton**
The dir attribute specifies the text direction of the element's content.  Set at left to right.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by jbampton** [comment]
Hey @potiuk can you please review 👍

**Comment by potiuk** [comment]
Not a big expert in the frontend part and there some frontend changes there.

**Comment by ryanahamilton** [comment]
@jbampton the function of the `dir` attribute is understood, but why are they necessary for this application and specifically these views?

**Comment by ryanahamilton** [comment]
Closing this PR; there isn't any clear or presented value to this change.

**Pull request closed without merging**
