### PR TITLE
Deprecated raw configuration view has been removed

### PR DESCRIPTION
**Pull request by dirrao**
Deprecated raw configuration view has been removed

### CODE REVIEW

**Comment by dirrao** [comment]
Unrelated tests are failing related backfill.

**Comment by jscheffl** [comment]
I am not sure whether we should "touch" this part, the UI and the whole views.py will be deleted prior Airflow 3.0 I assume.
Otherwise if we want to make the house clean, then you might delete the whole `/configuration` Flash route

**Review by bbovenzi — APPROVED** [review]
We're deleting all of views.py at some point. Doesn't hurt to remove some low-hanging fruit now. 

I'm ambivalent as if its significant. But it doesn't hurt to document the change.

**Comment by vincbeck** [comment]
I would say dont bother, we'll remove `views.py` all together but if you want to do it, we cannot stop you :)

**Pull request closed without merging**
