### PR TITLE
[AIRFLOW-2713] Rename async variable to async_packages in setup.py for Python 3.7.0 compatibility

### PR DESCRIPTION
**Pull request by Perados**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2713

### Description
- [ ] async is a reserved keyword in Python 3.7+

### Tests
- [ ] flake8

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Good point. `async` is a reserved keyword. Could you fix the Flake8 violations?
```
Common ancestor between travis_pr_3561 (7160b932) and origin/master (89c1f530) is 89c1f530:
--------------------------------------------------------------------------------
commit 89c1f530da04088300312ad3cec9fa74c3703176 (origin/master, origin/HEAD, master)
Author: Tim Swast <swast@google.com>
Date:   Fri Jun 29 14:15:16 2018 +0200
    [AIRFLOW-2682] Add how-to guides for bash and python operators
    
    Closes #3552 from tswast/airflow-2682-bash-python-
    how-to
Running flake8 on the diff in the range 89c1f530..7160b932 (1 commit(s)):
--------------------------------------------------------------------------------
setup.py:105:1: E305 expected 2 blank lines after class or function definition, found 1
async_packages = [
^
ERROR: InvocationError for command '/home/travis/build/apache/incubator-airflow/scripts/ci/flake8_diff.sh' (exited with code 1)
```

**Comment by gthank** [comment]
It looks like this flake8 violation is pre-existing? If it's really a blocker, I can just create a new PR, but I'm not sure it should be a blocker for a PR that unbreaks installation under the latest stable Python.

**Comment by Fokko** [comment]
Hi @gthank, that is true. The Flake8 violation is there already. But we're trying to make everything compliant, so for every diff we check for flake8. Would be highly appreciated if you would include a fix in your commit.

**Comment by gthank** [comment]
@Fokko It's not mine, but I'll be happy to submit one if this one stalls for much longer.

**Comment by Fokko** [comment]
Please respect the commit guidelines: https://github.com/apache/incubator-airflow/blob/master/.github/PULL_REQUEST_TEMPLATE.md

You will need to create a JIRA and prepend the commit with the jira issue number, e.g. `[AIRFLOW-1925]`.

**Comment by Perados** [comment]
@Fokko done: https://issues.apache.org/jira/browse/AIRFLOW-2713

**Comment by feluelle** [comment]
There is still an issue with the changes to Python 3.7 in Airflow's 1.10. Release.

bildschirmfoto 2018-08-28 um 11 36 56

Why is this commit https://github.com/apache/incubator-airflow/blob/master/CHANGELOG.txt#L9 included in 1.10 but there is no support for Python 3.7. according to @ashb in this comment https://issues.apache.org/jira/browse/AIRFLOW-2813?focusedCommentId=16561267&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16561267 ?

**Comment by Perados** [comment]
I think there is a problem, I didn't see this commit in the changelog for 1.10 nor in the 1.10 tag : https://github.com/apache/incubator-airflow/blob/master/CHANGELOG.txt and https://github.com/apache/incubator-airflow/commits/1.10.0

**Comment by feluelle** [comment]
You are right, not this one but a similiar one https://github.com/apache/incubator-airflow/pull/3578
It fixes async await for Python 3.7 even if Python 3.7 is not supported for this release.

**Pull request closed without merging**
