### PR TITLE
Add systemd unit files

### PR DESCRIPTION
**Pull request by bolkedebruin**
This PR adds systemd unit files that work on RedHat based systems. The good thing about systemd integration is that it will restart failed daemons.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@mistercrunch travis is complaining about something unrelated.

**Comment by mistercrunch** [comment]
I don't understand how these empty files in the project work along with systemd.

**Comment by bolkedebruin** [comment]
That's a very good question. They should not be empty of course. Weird, I'll fix that.

**Comment by bolkedebruin** [comment]
@mistercrunch done.

**Comment by mistercrunch** [comment]
Nice, we should add a note in the installation docs referencing these files

**Comment by bolkedebruin** [comment]
@mistercrunch documentation has been updated.

**Comment by bolkedebruin** [comment]
@mistercrunch anything left to do?

**Comment by mistercrunch** [comment]
It's good to go!

**Pull request merged**
