### PR TITLE
Add dag_state to cli

### PR DESCRIPTION
**Pull request by wil5for**
Add functionality to pause/unpause a dag from the cli.

Addresses Issue #693

### CODE REVIEW

**Comment by mistercrunch** [comment]
About semantics, `state` can be a little confusing as it is used for DagRun and TaskInstance and usually describes `failed`, `running`, `success`, ...

We might also allow to pause/unpause individual tasks in the future, so having two subcommands `airflow pause` and `airflow unpause` that could be used against DAGs or tasks may look better. Meaning we could evolved pause and unpause to support specifying a task regexp when we get there.

**Comment by wil5for** [comment]
I like that idea, I will turn this into pause/unpause subcommands instead.

**Comment by wil5for** [comment]
I removed the dag_state for now. 

I can add a dag_status (naming?) later that mimics the dag index view in the UI if that is on the CLI roadmap.

**Comment by mistercrunch** [comment]
:+1: 

Could be good to have a generic `desc` or `view` subcommand that would show all the details about a dag, task or task instance object. I use the UI for that but it can be great as you develop.

Sometime I'm thinking all the CLI features should be built on top of a REST interface, but we can get to that later.

**Comment by mistercrunch** [comment]
:+1:

**Pull request merged**
