### PR TITLE
Consolidated fix for volumeClaimTemplates (apiVersion and PVC)

### LINKED ISSUE #41766: Argo Incompatibility Discovered? (Missing apiVersion and kind in volumeClaimTemplates)
### Official Helm Chart version

1.15.0 (latest released)

### Apache Airflow version

2.9.3

### Kubernetes Version

1.25.16 and greater

### Helm Chart configuration

```
images: 
  airflow:
    repository: <redacted>/apache/airflow
    tag: 2.9.3
  statsd:
    repository: <redacted>/quay.io/prometheus/statsd-exporter
    tag: v0.26.1
  redis:
    repository: <redacted>/redis
    # Redis is limited to 7.2-bookworm due to licencing change
    # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
    tag: 7.2-bookworm
# Detailed default security context for airflow deployments
securityContexts:
  pod: 
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 50000
    fsGroup: 0
  containers: 
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 50000
    capabilities:
      drop: ["ALL"]
    allowPrivilegeEscalation: false
statsd:
  securityContexts:
    pod:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 50000
redis:
  persistence:
    size: 10Gi
    storageClassName: aws-gp3
  password: <redacted>
  uid: 50000
  securityContexts:
    pod:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 50000
    containers:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 50000
      capabilities:
        drop: ["ALL"]
      allowPrivilegeEscalation: false
    
#https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart-with-argo-cd-flux-rancher-or-terraform
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync
useStandardNaming: true
webserverSecretKey: <redacted>
fernetKey: <redacted>

keda:
  enabled: true
```

### Docker Image customizations

_No response_

### What happened

When deploying via ArgoCD, the statefulsets for redis, triggerer, and worker were unable to sync due to the below screenshot. In order to get a successful "sync", I had to update redis-statefulset, triggerer-deployment, and worker-deployment template files and include those two lines under volumeClaimTemplates. I don't believe this is an argocd issue, rather a template issue. Should this be required? Is there a better place to make the change? I didn't find it in the values.yaml file.
Capture

### What you think should happen instead

Argo is able to successfully sync.

### How to reproduce

Helm chart deployed with argocd but unable to synchronize successfully.

### Anything else

Behavior occurs unless templates are updated manually

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by darth-drew**
Closes: https://github.com/apache/airflow/issues/41766

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by darth-drew — COMMENTED** [review]
Please see https://github.com/apache/airflow/pull/41768

**Comment by darth-drew** [comment]
@hussein-awala from earlier convo

**Review by hussein-awala — APPROVED** [review]
Looks good, LGTM

We need to wait for the CI.

**Comment by darth-drew** [comment]
Much appreciated!

**Review by romsharon98 — APPROVED** [review]

**Pull request merged**
