### PR TITLE
Remove PATCH /dags/{dag_id}/dagRuns/{dag_run_id} endpoint

### PR DESCRIPTION
**Pull request by OmairK**
Dag Runs are immutable and clear_task_instances can be used to modify the Dag Runs table.

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by jhtimmins** [comment]
This code looks fine. @mik-laj do you know if there was a reason the spec included the ability to update dag runs via PATCH?

**Comment by jhtimmins** [comment]
Looks like this is failing static checks. I recommend running [pre-commit](https://github.com/apache/airflow/blob/master/STATIC_CODE_CHECKS.rst#pre-commit-hooks) checks

**Comment by OmairK** [comment]
> This code looks fine. @mik-laj do you know if there was a reason the spec included the ability to update dag runs via PATCH?

@mik-laj himself suggested to remove this endpoint.

**Comment by mik-laj** [comment]
@jhtimmins  I can't find fields that can be modified.

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
@OmairK  Can you do a rebase? I would like to merge this change.

**Comment by OmairK** [comment]
> @OmairK Can you do a rebase? I would like to merge this change.

@mik-laj I did the rebase.

**Pull request merged**
