### PR TITLE
[GH-9708] Add type annotations to two AWS Athena modules

### PR DESCRIPTION
**Pull request by coopergillan**
Add type annotations to `AthenaSensor` and `AWSAthenaOperator`. Of note on `AWSAthenaOperator` in particular, I removed `hook` as an attribute, which was always defaulting to `None`. I tried to keep it , but continually ran into errors like this:

>airflow/providers/amazon/aws/operators/athena.py:122: error: Item "None" of "Optional[AWSAthenaHook]" has no attribute "stop_query"
>                response = self.hook.stop_query(self.query_execution_id)

Any ideas on how to add typing when an attribute starts as `None` and gets set later? Or is the point of these errors that that is not necessary?

I also intentionally put this into two commits since the `AWSAthenaHook` changes were a little more straightforward. I could pull the operator ones out if need be.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by turbaszek** [comment]
Does it duplicates efforts from https://github.com/apache/airflow/pull/10025 ?

**Comment by coopergillan** [comment]
@turbaszek sure does, yep. That one has an approval also so we should probably close this, right?

**Comment by coopergillan** [comment]
I'll wait until it is merged since there's a merge conflict over there now.

**Comment by coopergillan** [comment]
Closing due to https://github.com/apache/airflow/commit/000287753b478f29e6c25442ac253e3a6c8e8c87 from https://github.com/apache/airflow/pull/10025.

**Pull request closed without merging**
