### PR TITLE
Implement AND logic checkbox for filtering DAGs

### LINKED ISSUE #38147: Add ability to filter DAGs in DAGs View by tags using "AND" instead of default behavior "OR"
### Description

In the DAGs View, we can enter tags in the "Filter DAGs by tag" box by entering one or more tags.  However, this results in an OR-type behavior, where the results show every DAG with any of the entered tags.

With this feature enabled, the list of DAGs returned would be a list only of those DAGs containing **ALL** of the user-entered tags, rather than a list of DAGs containing **ANY** of the user-entered tags.

### Use case/motivation

This feature could be as simple as adding a checkbox next to the "Filter DAGs by tag" box (marked "use AND" or similar).  This will be a great help to filter DAGs when tagging is used extensively and there are hundreds of DAGs on an instance.  For instance, we're migrating legacy ELT procedures that use legacy systems.  We're tagging these DAGs with all the legacy systems they use.  If we could zero in on which DAGs are using legacy system A **and** legacy system B, it would help us to understand the relationships between those systems, and what needs to be done to no longer rely on either.

### Related issues

None I'm aware of.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by TiDeane**
Implements a small checkbox named "Use AND logic" under the "filter DAGs by tag" box, allowing users to toggle between filtering DAGs using AND logic or OR logic. If there are no matching DAGs, it resets the tags and displays a message saying "No matching DAG tags found" (which is the default behaviour). Developed in collaboration with @lotrias17.

Screenshots:

Screenshot 2024-05-11 130229

Screenshot 2024-05-11 130239

Screenshot 2024-05-11 130248

We also implemented a test in [test_views_home.py](https://github.com/apache/airflow/compare/main...TiDeane:airflow:feature-38147-PR?expand=1#diff-81ef48c7266f1690897901984c78693b82eaef73c99d54c738782fc9541202ce).

The checkbox's state is saved in `localStorage`. When filtering the DAGs by tag in [views.py](https://github.com/apache/airflow/blob/main/airflow/www/views.py#L801), it now checks if the checkbox is marked, and if so it filters by AND instead of by OR.

closes: #38147

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by amoghrajesh — COMMENTED** [review]
Logic looks good here, but I am not so sure of how the UX turns up now. It seems to get much more cluttered. @bbovenzi WDYT?

**Comment by Tristan-Zaleski** [comment]
Attempted to mimic this logic in Airflow 2.6.3 standalone, but checkbox is not registering when checked in views.py. Seems like use_and is not being set.

**Comment by TiDeane** [comment]
I already replied in the issue, but figured it might be good to reply here too for consistency:

> @Tristan-Zaleski That's strange, I've just rebased with upstream/main and it seems to be working on my end. Would it work differently with Breeze?

**Comment by bbovenzi** [comment]
UX-wise. I think it would be best to add the AND/OR toggle as a sticky div inside of the tag selection dropdown. Tagged onto the top or the bottom. Sort of like how we keep some timezones stuck to the top of the timezone selection dropdown:

Screenshot 2024-07-30 at 2 07 33 PM

**Pull request closed without merging**
