### PR TITLE
Fix: Typos inside /docs

### PR DESCRIPTION
**Pull request by parikshit-adhikari**
Multiple typos inside /docs directory have been fixed.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by Taragolis** [comment]
@eladkal @ephraimbuddy correct me if I wrong but I think we do not make any changes into the `commits.rst` because it is just git commits messages, so if typo exists in git history then it would be persist here forever (as well as in git itself)

**Comment by potiuk** [comment]
Yes. Commits.rst is regenerated fully every time they are released (it's even explained in the headaers of those files) so corecting typose there has no effect, they will come back.

**Comment by potiuk** [comment]
> it's even explained in the headaers of those files)

Actually it is not, which is strange and possibly something we should add.

**Comment by potiuk** [comment]
https://github.com/apache/airflow/pull/35065 will add the comment in the future generated files.

**Pull request closed without merging**
