### PR TITLE
[AIRFLOW-3051] Change CLI to make users ops similar to connections

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3051

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
The ability to manipulate users from the  command line is a bit clunky.  Currently 'airflow create_user' and 'airflow delete_user' and 'airflow list_users'.  It seems that these ought to be made more like connections, so that it becomes 'airflow users list ...', 'airflow users delete ...' and 'airflow users create ...'

After merging this PR, `airflow users -h` in cli will result in the following:

```
usage: airflow users [-h] [-l] [-c] [-d] [--username USERNAME] [--email EMAIL]
                     [--firstname FIRSTNAME] [--lastname LASTNAME]
                     [--role ROLE] [--password PASSWORD]
                     [--use_random_password]

optional arguments:
  -h, --help            show this help message and exit
  -l, --list            List all users
  -c, --create          Create a user
  -d, --delete          Delete a user
  --username USERNAME   Username of the user, required to create/delete a user
  --email EMAIL         Email of the user, required to create a user
  --firstname FIRSTNAME
                        First name of the user, required to create a user
  --lastname LASTNAME   Last name of the user, required to create a user
  --role ROLE           Role of the user. Existing roles include Admin, User,
                        Op, Viewer, and Public. Required to create a user
  --password PASSWORD   Password of the user, required to create a user
                        without --use_random_password
  --use_random_password
                        Do not prompt for password. Use random string instead.
                        Required to create a user without --password
```

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Manipulated tests

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
+1

**Review by r39132 — COMMENTED** [review]
Approved

**Comment by XD-DENG** [comment]
Hi @kaxil , when is this planned to be released? Since any documentation in which `airflow create_user` command is mentioned should be updated accordingly, which is not considered yet (and maybe they should only be updated when this new `airflow users` command is released officially?).

**Comment by kaxil** [comment]
@XD-DENG  Thanks. I have now added it in https://github.com/apache/incubator-airflow/pull/3971/files

This would be released in Airflow 2.0

**Comment by XD-DENG** [comment]
Cool! Thanks @kaxil

**Pull request merged**
