### PR TITLE
[AIRFLOW-1889] Move sensors to separate package

### PR DESCRIPTION
**Pull request by Fokko**
Hi all,

I'd like to move the core sensors to a separate package. Right now all the sensors are contained in 
`airflow/operators/sensors.py`. But I'd like to split this like in `/contrib/sensors/`:
image

This also includes splitting the tests which are now mostly in `tests/core.py` which is a huge test class which is candidate for refactoring.

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
@bolkedebruin what are your thoughts on this?

Please note that we have two `hdfs_sensor.py`, both in core and contrib :-)

**Comment by Fokko** [comment]
Many changes are related to Flake compliancy, I had to shorten a lot of url's and fix the order of imports.

**Comment by bolkedebruin** [comment]
Can you rebase?

**Comment by Fokko** [comment]
@bolkedebruin done!

**Comment by Fokko** [comment]
Rebased

**Comment by ashb** [comment]
I think sensors.py should still exist, contain a deprecation warning, but still have the sensors available in that package (until 2.0), otherwise DAGs will break with no warning, and it’s easy to maintain back compat in this case

**Comment by yati-sagade** [comment]
LGTM, this change will make maintenance/testing of sensors much easier. I would love for this to be merged before I hack on [AIRFLOW-2001](https://issues.apache.org/jira/browse/AIRFLOW-2001).

**Comment by andyxhadji** [comment]
Looks great, awesome work! I think we should keep sensors.py for now with a deprecation warning - I can add their removal to the scope of [AIRFLOW-1922](https://issues.apache.org/jira/browse/AIRFLOW-1922) for 2.0.

**Comment by Acehaidrey** [comment]
I'm really glad you guys did this!

**Comment by Fokko** [comment]
Follow up fix: https://github.com/apache/incubator-airflow/pull/2961

**Pull request closed without merging**
