### PR TITLE
[AIRFLOW-2240] [dask] Added TLS/SSL support for the dask-distributed scheduler.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
As of 0.17.0 dask distributed has support for TLS/SSL.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
ping @bolkedebruin

**Comment by mrocklin** [comment]
Checking in here.  Is there anything blocking this PR?

**Comment by artwr** [comment]
@mariusvniekerk LGTM, a test would be nice though.
Could you also change your commit to mention the JIRA number associated with it?

**Comment by mariusvniekerk** [comment]
Updated title

**Comment by mrocklin** [comment]
@mariusvniekerk Dask has some testing infrastructure to set up a local cluster with TLS active.  See example here: https://github.com/dask/distributed/blob/master/distributed/tests/test_tls_functional.py#L23

**Comment by artwr** [comment]
We'll wait until CI passes, but looks good to me +1

**Comment by mariusvniekerk** [comment]
@artwr ping

**Comment by artwr** [comment]
LGTM, thank you!

**Pull request closed without merging**
