### PR TITLE
FIX Entrypoint and _CMD config variables (#8705)

### PR DESCRIPTION
**Pull request by NBardelot**
See issue https://github.com/apache/airflow/issues/8705

### CODE REVIEW

**Comment by potiuk** [comment]
Unstale :)

**Comment by potiuk** [comment]
Hey @NBardelot  I see I missed that one. Would you mind rebasing ?

**Comment by potiuk** [comment]
Unstale.

**Comment by potiuk** [comment]
unstale again

**Comment by potiuk** [comment]
@NBardelot - are you going to complete that one?

**Comment by kaxil** [comment]
Created another PR https://github.com/apache/airflow/pull/12411 to target master and will be cherry-picked.

Added the original author as co-author too

**Pull request closed without merging**
