### PR TITLE
Make Google Cloud Storage download operator use a filename, not a fil…

### PR DESCRIPTION
**Pull request by criccomini**
…e descriptor.

### CODE REVIEW

**Comment by criccomini** [comment]
Making this change because the file descriptor wasn't working since it's created in the DAG .py file, but then the operator might or might not even be executed on the same machine.

**Comment by criccomini** [comment]
Pinging here. Would be good to get this in the next release. Relatively small tweak, but the operator is broken without it.

**Comment by mistercrunch** [comment]
I'm happy to merge, it is changing the API though (`file_fd` -> `filename`). We typically try to avoid doing that, but since this is a `contrib` item and there's probably not many people using it I'm ok merging it.

**Comment by criccomini** [comment]
Thanks, ya agreed. TBH, the file_fd never worked to begin with, but I will be mindful re: backwards compatibility. The reason it got committed is because the file_fd was working in `airflow run` mode, but not when a real DAG got triggered. Sorry for the confusion.

**Pull request merged**
