### PR TITLE
Support for sorting DAGs by Last Run Date in the web UI

### LINKED ISSUE #30838: Sort Dag List by Last Run Date
### Description

It would be helpful to me if I could see the most recently ran DAGs and their health in the Airflow UI. Right now many fields are sortable but not last run.

The solution here would likely build off the previous work from this issue: https://github.com/apache/airflow/issues/8459

### Use case/motivation

When my team updates a docker image we want to confirm our DAGs are still running healthy. One way to do that would be to pop open the Airflow UI and look at our teams DAGs (using the label tag) and confirm the most recently ran jobs are still healthy. 

### Related issues

I think it would build off of https://github.com/apache/airflow/issues/8459

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tquazi**
closes: #30838

Based on the closed PR #30935 
Adding fix for MSSQL code

image

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by tquazi** [comment]
Hey @potiuk can you please add "full tests needed" label to this PR. Thanks!

**Comment by potiuk** [comment]
Yep. Closed/reopened to rebuild as well.

**Comment by potiuk** [comment]
Hmm. Did not help as MSSQL is currently skipped for regular PRs even with full tests needed . Will fix it shortly

**Comment by potiuk** [comment]
PR here: https://github.com/apache/airflow/pull/31247 - once it gets merged. I will rebase this onen and the mssql problem should be finally visible here.

**Comment by potiuk** [comment]
Rebased :crossed_fingers:

**Comment by tquazi** [comment]
Hey @potiuk, looks like the Sqlite Py3.10 test is failing due to an unrelated issue. Can you please take a look. Also is it possible to re-trigger just this failed test?

Thanks

**Review by potiuk — APPROVED** [review]

**Pull request merged**
