### PR TITLE
[AIRFLOW-XXXX] create user in quick start

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by milton0825** [comment]
@feng-tao @Fokko

**Comment by r39132** [comment]
@milton0825 Just curious where you see the `airflow users` CLI. When I rebuilt master, I still see the `airflow create_user` CLI.

**Comment by r39132** [comment]
@milton0825 so, this is for 2.0+. Till 2.0+, it seems the `airflow create_user` is the relevant API.

@ashb @Fokko @feng-tao Are we planning to release `airflow users` in any release before 2.0? If so, should he change his API call?

I'm assuming this is not specific to the new RBAC webserver and applies to our current webserver as well?

**Comment by mik-laj** [comment]
I think, you should also update `docs/security.rst` file. The statement is there: 
> By default, all gates are opened.

**Comment by feng-tao** [comment]
@r39132  good point, may be change the note to  something:
```
if you build it with 1.10.2 or 1.10.1 version, use `airflow create_user ...`
If you build it with master, use `airflow user -c` something
```

**Comment by feng-tao** [comment]
depends on whether @ashb cherry-pick that pr.

**Comment by ashb** [comment]
Our docs our versioned (though the linking/signaling of that could do with some work), for example:

https://airflow.readthedocs.io/en/latest/ is from master branch
https://airflow.readthedocs.io/en/1.10.2/
https://airflow.apache.org/ is current release (1.10.2)
https://airflow.apache.org/1.10.1/ is 1.10.1

So we shouldn't have this sort of version comment in the docs.

Also the default on 1.10 is still to use the non RBAC UI so quick start there doesn't need a user created.

**Comment by milton0825** [comment]
PTAL @ashb @feng-tao

**Review by Fokko — APPROVED** [review]
Thanks @milton0825 for putting this in the docs.

**Comment by Fokko** [comment]
Maybe we should make this section clearer?

image

https://airflow.apache.org is the latest release, and the ReadTheDocs is the latest master.

**Pull request merged**
