### PR TITLE
Synchronizes updated changelog after buggfix release

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
One more fix resulting from the later-than-last-minute-fix :(

**Comment by potiuk** [comment]
Shoudl be good to go

**Comment by kaxil** [comment]
Static check is failing

**Comment by potiuk** [comment]
Right. The pre-commit was to "aggressive". removed it

**Review by ephraimbuddy — APPROVED** [review]

**Pull request merged**
