### PR TITLE
Add configure_environment.sh to ./breeze --start-airflow 

### PR DESCRIPTION
**Pull request by francescomucio**
With `./breeze --start-airflow` it was not possible to use the dags stored in `files/dags` in the host machine because the AIRFLOW__CORE__DAGS_FOLDER environment variable was not set. 

This was because `scripts/in_container/configure_environment.sh` was not executed. I have added a call to that script.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by francescomucio** [comment]
@mik-laj @potiuk thanks

**Comment by ashb** [comment]
@potiuk This didn't run CI for some reason -- so it failed on master (tabs was used for indentation). Could you look at why it didn't run please?

**Comment by potiuk** [comment]
It did run it but it took some time. That's my fault really - I should have checked. the GA works in the way that until it starts all the checks, the "rebase&squash" button gets "green". This is also when or two checks succeed but the dependent one did not start yet. 
So if there are many PRs in the queue and there is a delay in running jobs, the PR looks green even if the checks did not start yet.

**Comment by potiuk** [comment]
Created an inssue in Github Support : https://github.community/t/merge-button-green-with-jobs-not-started-in-github-actions/132604. Some likes are welcome :)

**Comment by ashb** [comment]
> It did run it but it took some time. That's my fault really - I should have checked. the GA works in the way that until it starts all the checks, the "rebase&squash" button gets "green". This is also when or two checks succeed but the dependent one did not start yet. 
> So if there are many PRs in the queue and there is a delay in running jobs, the PR looks green even if the checks did not start yet.

Oh lovely. Makes sense how it happened now, thanks

**Comment by francescomucio** [comment]
I can create a new PR to fix the formatting, will that be ok?

**Comment by potiuk** [comment]
Fixed already by Ash and Kaxil

**Comment by francescomucio** [comment]
Oh, great, I didn't notice it. Thanks for fixing my error.

**Pull request merged**
