### PR TITLE
fix(providers/azure): remove json.dumps when querying AzureCosmosDBHook

### PR DESCRIPTION
**Pull request by Lee-W**
`json.dumps` leads to `azure.cosmos.exceptions.CosmosHttpResponseError: (BadRequest) Message: {"Errors":["Invalid query. Specified parameterized query JSON is malformed."]}`

https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/database_management.py#L41C36-L46

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
The ignore comments you have to put in suggest something is wrong, but I’m not sure if it’s the code or the Azure lib.

**Comment by Lee-W** [comment]
> The ignore comments you have to put in suggest something is wrong, but I’m not sure if it’s the code or the Azure lib.

I think it's the error from Azure lib. The annotation [here](
https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py#L392) and the code example [here](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/cosmos/azure-cosmos/samples/database_management.py#L41C36-L46) does not match

**Comment by Lee-W** [comment]
Where is the best place for me to put such comments? Around all the ignores?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Where is the best place for me to put such comments? Around all the ignores?

Maybe it woudl be worthwile to add a comment ("The ignore below is due to typing bug in azure lib x.y.z" . I also usually try to find if there is an issue open for that and if not i open it mysefl and post a link to the issue.  This way anyone might check in the future if the issue has been solved and remove those unnecessary ignores when we upgrade.

**Comment by Lee-W** [comment]
There was not. But I created one. Just added comments to the ignore

**Review by potiuk — APPROVED** [review]

**Pull request merged**
