### PR TITLE
Feature: Added event_handler parameter in MSGraphAsyncOperator

### PR DESCRIPTION
**Pull request by dabla**
Added an event_handler parameter in MSGraphAsyncOperator which allows you to override the default implementation when needed.  This can be handy when you want to handle certain failed event types returned by the triggerer.  Also added a unit test for this new feature and updated docstring.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by dabla** [comment]
Dunno why following tests keeps failing, it succeeds locally:

```
FAILED tests/providers/microsoft/azure/operators/test_data_factory.py::TestAzureDataFactoryRunPipelineOperator::test_execute_wait_for_termination[Canceling-timeout] - AssertionError: assert 2 == 4
 +  where 2 = <MagicMock name='get_pipeline_run' id='139745815447776'>.call_count
=========== 1 failed, 6661 passed, 60 skipped in 1235.68s (0:20:35) ============
/usr/local/lib/python3.8/site-packages/pytest_asyncio/plugin.py:208: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
```

**Comment by potiuk** [comment]
Did you try reproducing it with upgraded boto:

If you unfold the failed output you will see this:

```bash
  Upgrading boto3, botocore to latest version to run Amazon tests with them
  
  Uninstalled 4 packages in 395ms
   - aiobotocore==2.15.1
   - opensearch-py==2.7.1
   - s3fs==2024.9.0
   - yandexcloud==0.320.0
  + uv pip install --python /usr/local/bin/python --upgrade boto3 botocore 'oss2>=2.14.0' 'cryptography<43.0.0' 'requests!=2.32.*,<3.0.0,>=2.24.0'
  Resolved 19 packages in 2.87s
  Prepared 3 packages in 438ms
  Uninstalled 3 packages in 882ms
  Installed 3 packages in 139ms
   - boto3==1.35.23
   + boto3==1.35.34
   - botocore==1.35.23
   + botocore==1.35.34
   - requests==2.32.3
   + requests==2.31.0
```

Which can be locally reproduced with:

```
breeze shell --upgrade-botot
```


And then rerunning the tests.

**Comment by potiuk** [comment]
(It might also be transitive / accidental side effect)

**Comment by dabla** [comment]
> (It might also be transitive / accidental side effect)

Apparently it was, it failed for days even after updates now it passes :)

**Comment by potiuk** [comment]
It looks that there were some changes in looker/kiota packages recently. Can you please rebase again and resolve conflicts and see where it is and ping me if you still see errors ?

**Comment by dabla** [comment]
> It looks that there were some changes in looker/kiota packages recently. Can you please rebase again and resolve conflicts and see where it is and ping me if you still see errors ?

Resolved conflicts, will see how the build behaves.

**Comment by dabla** [comment]
> It looks that there were some changes in looker/kiota packages recently. Can you please rebase again and resolve conflicts and see where it is and ping me if you still see errors ?

Everything is fine now after update and conflict resolution

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Woooohooo!

**Pull request merged**
