### PR TITLE
[AIRFLOW-6] Removing dependency on Highcharts in favor of NVD3

### PR DESCRIPTION
**Pull request by mistercrunch**
https://issues.apache.org/jira/browse/AIRFLOW-6

We're moving to Apache, and the Highcharts license is not compatible with ours.

This rips out the dependency on Highcharts in favor of NVD3, and attempts to keep the charting application working where possible. Some chart types that were supported before aren't supported anymore (heatmaps, parallel coordinates) and some may behave slightly differently.

Since the small charting application located under "Data Profiling -> Chart" is peripheral to Airflow, this change is not meant to be fully compatible. For better charting and long term support, check out Airbnb's Caravel.
https://github.com/airbnb/caravel

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Will update the PR to be compatible with current master and then merge.

**Comment by r39132** [comment]
@mistercrunch please rebase, create a referring Jira, squash commits, prefix commit and PR titles with JIRA issue id, and let me know once done. If no changes occur in the next 5 days, I will close for inactivity! If you intend to work on this in the next 2 weeks, I can keep it open.

**Comment by r39132** [comment]
@mistercrunch @bolkedebruin wasn't this done in a different commit?

**Comment by r39132** [comment]
Was this merged as part of https://github.com/apache/incubator-airflow/pull/1611?

**Comment by mistercrunch** [comment]
This has been merged by other means, closin'

**Pull request closed without merging**
