### PR TITLE
[AIRFLOW-3353] Upgrade redis client

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

https://issues.apache.org/jira/browse/AIRFLOW-3353

### Description

Now that Celery/Kombu have updated and work with RedisPy 3.x (they in
fact force us to use 3.2) we should re-introduce this change.

This re-introduces the change from #4203 (with the addition of a note in UPDATING.md. The tests have been changed since so don't need updating anymore) that was reverted in #4205 

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
@Fokko @feng-tao PTAL - tests are failing until this is merged :(

**Comment by ashb** [comment]
Note to whoever merges this - please remove the `(#4203)` from the commit message (it snuck in when I took the author information from the previous PR.

**Comment by feng-tao** [comment]
lgtm, I am afk, and I think @ashb  you could merge it on your own if you are by your computer.

**Comment by Fokko** [comment]
Thanks @ashb for picking this up so quickly

**Comment by ashb** [comment]
> lgtm, I am afk, and I think @ashb you could merge it on your own if you are by your computer.

@feng-tao I generally try to get other committers to to merge my PRs still.

**Comment by feng-tao** [comment]
@ashb , I assume once other committers give +1, it should be fine. Besides we currently have a limited set of active committers.

**Pull request merged**
