### PR TITLE
[AIRFLOW-1842] Add gcs to gcs copy operator with renaming if required

### PR DESCRIPTION
**Pull request by unlitdev**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1842

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
New GoogleCloudStorageToGoogleCloudStorageOperator operator copies an object from a Google Cloud Storage bucket to another Google Cloud Storage bucket, with renaming if required.

### Tests
- [x] My PR does not need testing for this extremely good reason:
Google doesn't provide local stubs for testing google cloud storage api

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Review by fenglu-db — APPROVED** [review]

**Comment by fenglu-db** [comment]
LGTM

**Review by jgao54 — APPROVED** [review]
+1

Code lgtm!

Would be nice to expose the option for allowing/disallowing the overwriting of an object that already exists at the destination bucket. 

I am aware that the GCS Hook currently only expose `copy` but not `rewrite`, but it may be worth the effort to add `rewrite`, for the following reason described in the [doc](https://cloud.google.com/storage/docs/json_api/v1/objects/copy):

```Use the copy method to copy between objects in the same location and storage class. When copying objects across locations or storage classes it's sometimes possible to use the copy method, but we recommend using the rewrite method instead because if the source and destination are in different locations or storage classes the copy method calls the rewrite method exactly once behind the scenes. The larger the object the more likely that multiple rewrite calls will be needed to complete the operation. If the single rewrite call made by copy doesn't complete the operation it will result in a Deadline exceeded error.```

**Comment by unlitdev** [comment]
oh ok. Well, I only started expanding GCP stuff. I need more operators and sensors for my GCP projects.

**Comment by jgao54** [comment]
@litdeviant gotcha, thanks for your contribution! That's why I approved the PR as well :) Would love to see more commits to enhance the GCP operators, including things mentioned above.

cc @criccomini

**Pull request closed without merging**
