### PR TITLE
Trigger DAG re-serialization after upgrade

### LINKED ISSUE #19533: Always re-serialise DAGs after an upgrade
### Description

https://github.com/apache/airflow/issues/19519#issuecomment-965621090

> Also I think we have a new "dags reserialize" coming - #19471 - which is really good idea because the "serialized" form of DAGs is pretty safe to delete and recreate.

> I just wonder if this is not something that we should always do after/during upgrade "just in case". It might slow-down initial dag refresh, but at least we can be sure that everything in serialized dags is "correct".

Recording this in a new issue so it doesn’t get forgotten.

### Use case/motivation

_No response_

### Related issues

A way to manually trigger DAG reserialisation:
#19471

If a previous-serialised DAG is not being compatible with new semantics, a bug can be raised at a confusing location:
#19519

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by uranusjr**
Fix #19533.

### CODE REVIEW

**Review by kaxil — CHANGES_REQUESTED** [review]
I am not in favour of doing this **_always_**.

For users that have 1000s of dags, this will be SLOW !!

**Comment by msumit** [comment]
+1 to re-serialize again, as upgrades are not happening every day.

**Comment by potiuk** [comment]
I am also +1 on doing it always. 

I prefer even 10 minutes of resync (which is I guess highly unrealistic to take that long on pretty much any upgrade) for every user at upgrade time than handling all the issues that people will have in case of any future incompatibilities/migration from older versions.

**Review by potiuk — APPROVED** [review]

**Comment by kaxil** [comment]
> I am also +1 on doing it always.


Agree when we have incompatibilities -- and we can resync during that version is what I feel.

> 
> I prefer even 10 minutes of resync (which is I guess highly unrealistic to take that long on pretty much any upgrade) for every user at upgrade time than handling all the issues that people will have in case of any future incompatibilities/migration from older versions.

It compounds to 30 mins -- when you account for other DB migrations. The larger the number of DAGs, larger the TIs, more time for other migrations and more time for re-serialization.

**Comment by kaxil** [comment]
Alternative --  how about a flag to `airflow db upgrade --clear-serialized-table` or something like that .. 

`--clear-serialized-table` -- Couldn't find a better name unfortunately

**Review by ashb — CHANGES_REQUESTED** [review]
-1 to this. It will make upgrades a lot more painful.

We should instead make the deserialization upgrade in place, which we already do for most cases.

**Comment by potiuk** [comment]
> It compounds to 30 mins -- when you account for other DB migrations. The larger the number of DAGs, larger the TIs, more time for other migrations and more time for re-serialization

But isn't that the case that just "clearing" the serialized dags is equivalent to emptying the cache? I do not think just **cleaning** the serialized fields will take a lot of time in any sizeable database - it's just marking the fields as empty which is mostly almost no-op. It's the compound time of re-serializing that will take some time.

Not sure if that's the case and what are all consequences of such an approach.

I believe when upgrade is happening, when we end the migration with "cleaning" the serialized dags, Dag File processor  will simply start processing and serializing dags pretty much almost "as usual" - initially a bit slower but this will be almost unnoticeable except that the dags that are not serialized yet, the tasks will not show in the UI. 
And for those DAGs that are already processed the tasks will start to re-appear in the UI.

Am I correct? Or are there any other side effects?

Another approach here is to simply mark those all serialized dags as invalid - so that they stay present in the DB for the UI and dag file processor will reserialize them all while parsing - then even the "disappearing UI Dags". This is equivalent to "cache invalidation" rather than cleaning and maybe that's the right solution.

> We should instead make the deserialization upgrade in place, which we already do for most cases.

IMHO marking all dags as "invalid" at each upgrade  is far more "resilent" approach than reserialization looking also at the cases we had. We've introduced "accidental" incompatibilities in serialisation and there is no guarantee (and we have no protection/tests preventing it from it happening again, so "reserialize all at upgrade" for me is an easy solution that helps us dealing with accidental mistakes we can (and will) make.

**Comment by kaxil** [comment]
>But isn't that the case that just "clearing" the serialized dags is equivalent to emptying the cache? I do not think just cleaning the serialized fields will take a lot of time in any sizeable database - it's just marking the fields as empty which is mostly almost no-op. It's the compound time of re-serializing that will take some time.

Yeah, I am talking about the time between starting the upgrade to be able to run the DAG - "downtime time" -- Imagine 1000 files that are serialized incrementally as they were added/modified. Now you need to serialize them again as we cleared it. So we need to wait until all of these files are re-serialized to allow running the DAGs in those files. 

>IMHO marking all dags as "invalid" at each upgrade is far more "resilent" approach than reserialization looking also at the cases we had. We've introduced "accidental" incompatibilities in serialisation and there is no guarantee it won't happen again (and we have no protection/tests preventing it from it happening again), so "reserialize all at upgrade" for me is an easy solution that helps us dealing with accidental mistakes we can (and will) make.

We need to take greater care for those "accidental" incompatibilities. If we don't have tests, we should add tests for it and not the other way around. 

>IMHO marking all dags as "invalid" at each upgrade is far more "resilent" approach than reserialization looking also at the cases we had. 

It means a larger unnecessary downtime for most of the users when they are just upgrading patch versions. This feels like a bad idea. I shouldn't have to wait for all my DAGs to get parsed again when I am just upgrading from 2.2.1 to 2.2.2 for example.

**Comment by kaxil** [comment]
>I prefer even 10 minutes of resync (which is I guess highly unrealistic to take that long on pretty much any upgrade) for every

2.2.0 had a migration that took 30 mins for some users -- so definitely "realistic". With the AIPs that are coming through the number of DB migrations will just keep on growing that touch TIs, so let's not add additional overhead.


@uranusjr I suggest, we add a flag like I suggested in https://github.com/apache/airflow/pull/19637#issuecomment-971786164 for users who wants to clear serialized DAGs while upgrade but "-1" for forcing it.

**Comment by potiuk** [comment]
> We need to take greater care for those "accidental" incompatibilities. If we don't have tests, we should add tests for it and not the other way around.


I am all for this. If we have that, I am happy without this "invalciation". The only problem is HOW to write the tests to account for all the migration paths. 

We will have people upgrading from 2.0.0 straight to 2.3.0 even if a breaking change was introduced in 2.2.0. Hell we will make changes in 2.3.5 and people will upgrade from 2.0.0 straight to 2.5.0. Do we have an idea how we test this scenario? This is quite unfeasible to test, especially that code from 2.0.0 is already long gone from the "main" branch.

I have another idea how to make everyone happy.

Why don't we explicitly add such cleanup only when we know that we have a breaking change in-between?

Say we have a user migrating from 2.0.0 to 2.3.0 and we KNOW that 2.1.0 introduced breaking change - let's force the migration then.

```
last_breaking_serialization_versions= '2.1.0' 

if original_airflow_version < last_breaking_serialization_version:
   clean()
```

WDYT?

**Comment by kaxil** [comment]
>I am all for this. If we have that, I am happy without this "invalidaation". The only problem is HOW to write the tests to account for all the migration paths.

This goes hand in hand with my suggestion on making sure that correct tests are added. Whenever something touches serialization -- we should add a test in https://github.com/apache/airflow/blob/main/tests/serialization/test_dag_serialization.py - We also already test serialization and deserialization of example_dags. The simplest of test in a container is to get older stable released version, run `airflow db upgrade` and run a sample DAG and verify that it succeeds. 


>Why don't we explicitly add such cleanup only when we know that we have a breaking change in-between?
> Say we have a user migrating from 2.0.0 to 2.3.0 and we KNOW that 2.1.0 introduced breaking change - let's force the migration then.

I mean -- I don't think the "migration" / "cleanup" is needed then. If it was an oversight in 2.1.0 and we broke serialization, we will fix the deserialization part in 2.1.1 . Until now we didn't have to change the serialization format without breaking compatibility. When it comes to it, we can add a DB migration to fix those and do smart "migration" where only affected records are cleaned up.

I would still suggest of a separate CLI command like https://github.com/apache/airflow/pull/19471 or run `airflow db upgrade` with a flag (`--with-reserialize-migrations` or similar) to have a switch in case things go wrong.

**Comment by potiuk** [comment]
> I would still suggest of a separate CLI command like #19471 or run `airflow db upgrade` with a flag (`--with-reserialize-migrations` or similar) to have a switch in case things go wrong.

One thing that I really do not like here is that it forces the admin users to "know" about the serialization, be able to diagnose problems connected with it and map it mentally to the switch or command line.

This should be totally transparent to them - this is an implementation detail of airflow which is important to us but it should be totally invisible to the users. I can't even imagine a good "admin description" on WHEN the user should use such a flag? What is the criteria they should be using to decide when to use it?

**Comment by kaxil** [comment]
>One thing that I really do not like here is that it forces the admin users to "know" about the serialization, be able to diagnose problems connected with it and map it mentally to the switch or command line.

It won't be one size fits all. This is an escape hatch, they don't need to run it but if they face an issue then they can run and mitigate the issue and there is already a precedence for it with `sync-perm`.

I can write a good enough description for it :) but I don't have a strong opinion if we should have that flag or not.

However, I have a strong opinion that we should not force re-serialize during Airflow Upgrade !

**Comment by potiuk** [comment]
Hmm. Maybe I am a little overcautious here, but it comes from the experience of responding and trying to help many of our users. I think it really boils down to what we want to optimize for.

My current optimisation "goal" is to decrease the number of problems our users even approach us with. So if there is a problem we can anticipate and solve for our users without them even knowing it, I am all for that. Adding more and more escape hatches like that is going quite against that "optimisation" goal, because we admit that there is a problem and we try to "throw the problems at our users to solve" - and this (from the experience) will hit us back. 

This was the case with the warning for "removed" task instance entries. I know why we added it but IMHO it exposed an internal detail of airlfow to our users, and this kinda 'undermines' the feeling that airlfow is "reliable" and "safe to upgrade" - users who just want to install airflow without knowing how it works intenrnally should be first-class citizens as well, and those kind of "escape hatches" just leaks the "airlfow" abstraction. I think sometimes we tend to forget that our Ops (even admins) are not "developers" or even no "sql admins" should not eventually even know that there is a database behind.  This is really an implementation detail for many.

But If I am the only one to be worried, I am ok with the flag (I just hope in the next few months we will not have to handle a floo od of issues upgrading from say 2.0.2).

**Comment by kaxil** [comment]
> Hmm. Maybe I am a little overcautious here, but it comes from the experience of responding and trying to help many of our users. I think it really boils down to what we want to optimize for.
> 
> My current optimisation "goal" is to decrease the number of problems our users even approach us with. So if there is a problem we can anticipate and solve for our users without them even knowing it, I am all for that. Adding more and more escape hatches like that is going quite against that "optimisation" goal, because we admit that there is a problem and we try to "throw the problems at our users to solve" - and this (from the experience) will hit us back.
> 
> This was the case with the warning for "removed" task instance entries. I know why we added it but IMHO it exposed an internal detail of airlfow to our users, and this kinda 'undermines' the feeling that airlfow is "reliable" and "safe to upgrade" - users who just want to install airflow without knowing how it works intenrnally should be first-class citizens as well, and those kind of "escape hatches" just leaks the "airlfow" abstraction. I think sometimes we tend to forget that our Ops (even admins) are not "developers" or even no "sql admins" should not eventually even know that there is a database behind. This is really an implementation detail for many.
> 
> But If I am the only one to be worried, I am ok with the flag (I just hope in the next few months we will not have to handle a floo od of issues upgrading from say 2.0.2).

I am "-1" for the same reasons that I don't want our users to be to have to "unnecessarily" wait and instead of actually making sure that we don't break serialization we are cleaning the serialized_dags. And this comes from years of experience and helping users and companies as well.

>Adding more and more escape hatches like that is going quite against that "optimisation" goal, because we admit that there is a problem and we try to "throw the problems at our users to solve" - and this (from the experience) will hit us back.

That's exactly why we should not just clean the table and can still achieve what we need without comprising the cost of reserializing the table. And it is not "throw the problems at our users to solve" , it is if we goof up for whatever reason we have a "backup" that helps users without compromising it for the versions that don't have it. It is a different way of looking at the coin !!

> This was the case with the warning for "removed" task instance entries. I know why we added it but IMHO it exposed an internal detail of airlfow to our users, and this kinda 'undermines' the feeling that airlfow is "reliable" and "safe to upgrade"

That is the reason we adopted the solution I suggested to move things to a temporary table then ask them to cleanup dangling TIs where they didn't even know what they need to run. And it is not "one size fits all" problem -- there are users who don't care about those but there are corporate, banks and others who have policies to retain data for a certain period, so they can decide if they want that data or not.

>and this kinda 'undermines' the feeling that airlfow is "reliable" and "safe to upgrade" - users who just want to install airflow without knowing how it works intenrnally should be first-class citizens as well, and those kind of "escape hatches" just leaks the "airlfow" abstraction

Again, there are two kinds of users and it is not one size fits all. For "new users" / "new installs" neither is the problem -- nor the TI issue or the dag serialization issue. It is for the users during the "upgrade" -- the main benefit of open source is transparency (and this is my view). To debug why a DAG is not working, you _might_ need to look at parsing logs and the serialized representation of the DAG -- so it is not leak of abstration but understanding of a core process.

>I think sometimes we tend to forget that our Ops (even admins) are not "developers" or even no "sql admins" should not eventually even know that there is a database behind. This is really an implementation detail for many.

And we should not forget that we in trying to optimize for new users we don't forget the users and companies running Airflow for years who want to optimize it and they need tools from us. I would love to make it as easy to upgrade but without compromising, the solution you mentions only achieves one thing which is why I am trying to find the best of both worlds as we have both type of users.

>But If I am the only one to be worried, I am ok with the flag

I will be very happy to hear other solutions that fixes it for both type of users and I have no strong opinion on the flag, I have proposed a separate sub-command solution to similar to https://github.com/apache/airflow/pull/19471 . 

> (I just hope in the next few months we will not have to handle a flood of issues upgrading from say 2.0.2).

Do you think of all the issues that we are flooded with, this one issue will have more?

I understand what you want to solve and why and I do appreciate it but I think we should not take this shortcut. However this is my personal opinion only :)

**Comment by uranusjr** [comment]
> I suggest, we add a flag like I suggested in [#19637 (comment)](https://github.com/apache/airflow/pull/19637#issuecomment-971786164) for users who wants to clear serialized DAGs while upgrade but "-1" for forcing it.

If we add a flag, I want it the other ways around, i.e. you need to explicitly request Airflow to _not_ bust serialisation cache. An opt-in flag is meaningless since we can just tell the user to run `airflow dags reserialize` manually after `airflow db upgrade`.

**Comment by potiuk** [comment]
Side comment. I think this is a great discussion and we should have more of those as it lets us hear and cosnsider different perspectives.

@uranusjr - I quite agree the swich makes no sense in it's current proposed form - since we can have the command to reserialize after migration.

@kaxil  - I hear you. And I understand your perspective of the "power users". And while I agree maybe reserializing everything is a "bulk and heavy" solution but maybe let's try indeed to find a better solution that will be good for all kinds of users - not only the "power" users. We have to remember about one thing as well. Even the "power users" have teams of "ops" people which rotates and changes. For those "experienced" teams, a lot of knowledge and experience in their heads leaves the team when they leave it. So if we are helping the "new" users to deal with problems, we are also helping "new members" of such "power ops teams". That's why I think ALSO focusing on the needs of those inexperienced users actually helps everyone. 

What I am **really** after is that we think of those users when we deal with problems and if we know of some class of problems we should - ideally make a self-healing solution, or if we can't - we should make sure that we give the user good and **reassuring** message of problem and guidance how they can deall with it. This is something we do very, very poorly I think. What we are doing right now is we give the user a meaningless messaage that - if they are inexperienced - scares them more than helps them. I think we should be super empathetic towards those people. 

What is really the problem I want to solve (and maybe indeed we can find a good solution for everyone) is that what happened in the past (and I guess it will happen even now if the user has serialization problem).  The screenshots below are from yesterday's slack conversation in `trobleshooting`: https://apache-airflow.slack.com/archives/CCQ7EGB1P/p1637144816451900. They are about pickling and different python version, but they illustrate the problem very well as this is pretty much the same "kind of issue" that is self-healable and repeats often enough that we should really consider it "common problem" and find a good "automated" solution for it.

The message that the user had was something like that:

image (1)
image (2)

What do you expect user will do in this case - either experienced or not? 

Yeah. The user will actually create an issue. 

None of us (including the user) does not want this to happen - yet we "trick" the user into creating an issue which takes both user and maintainer time completely needlessly. I want either:

a) (best!) airflow self-healing itself and the message reassuringly saying "This is known issue and we are fixing it automatically. Please try in 5 minutes it will get solved"

b) (a little worse but acceptable!) the user gets clear message on what to do - instructions providing context of the problem and enough information that the user can make decision on their own without involving maintainers. This is what was missing originally in the "moved_task_instance" case and what I added [here[(https://airflow.apache.org/docs/apache-airflow/stable/installation/upgrading.html#post-upgrade-warnings) - and the "warning" message links to it. 

This is a well known and often occuring situation. Seeing a cryptic error  - rather than reassuring message and helpful instuctions - creates the impression that Airlfow is enterprise-grade software. Those kind of errors are very bad - because there are only two options when you see it: either "I screwed up" or "they screwed up". Both thoughts have bad consequences.

So what I am really after is answer to simple question.

Can we make sure that in case of serialization errors (and maybe we do the same with pickling errors while we are at it) - the messages the user sees are reassuring, and the system either self-heals or the user gets clear instructions what they should do - including context why and ability to make the decision on their own what to do without involving maintainers?

If the answer to this is "yes" and we implement it - then I think we do not neeed this automated reserialization.

**Comment by kaxil** [comment]
> > I suggest, we add a flag like I suggested in [#19637 (comment)](https://github.com/apache/airflow/pull/19637#issuecomment-971786164) for users who wants to clear serialized DAGs while upgrade but "-1" for forcing it.
> 
> If we add a flag, I want it the other ways around, i.e. you need to explicitly _opt out_ of auto reserialisation. An opt-in flag is meaningless since we can just tell the user to run `airflow dags reserialize` manually after `airflow db upgrade`.

@uranusjr I suggested one of the two not both. Check https://github.com/apache/airflow/pull/19637#issuecomment-971897110 where I say "_I would still suggest of a separate CLI command like #19471 or run airflow db upgrade with a flag (--with-reserialize-migrations or similar) to have a switch in case things go wrong._"

**Comment by kaxil** [comment]
> Deserialization problems seems to be a well known and often occuring situation. Seeing a cryptic error - rather than reassuring message and helpful instuctions - creates the impression that Airlfow is not an enterprise-grade software. Those kind of errors are very bad - because there are only two options when you see it: either "I screwed up" or "they screwed up". Both thoughts have bad consequences.

Can you give some examples of this please except for the 2.2.0 issue

**Comment by kaxil** [comment]
>the messages the user sees are reassuring, and the system either self-heals or the user gets clear instructions what they should do

I agree with this to add that instruction to run a deserialize command with "https://github.com/apache/airflow/blob/e25446a8b19197e55989174f210e1c94ae5ff65f/airflow/serialization/serialized_objects.py#L333"

And where we know we can take care of incompatibilities we can take care of them in migrations as suggested in https://github.com/apache/airflow/pull/19637#issuecomment-971897110

_I mean -- I don't think the "migration" / "cleanup" is needed then. If it was an oversight in 2.1.0 and we broke serialization, we will fix the deserialization part in 2.1.1 . Until now we didn't have to change the serialization format without breaking compatibility. When it comes to it, we can add a DB migration to fix those and do smart "migration" where only affected records are cleaned up._

**Comment by potiuk** [comment]
> Can you give some examples of this please except for the 2.2.0 issue where just reserializing would have helped

Yep. It all started with this: https://github.com/apache/airflow/issues/19519 for example. 

We still do not know what the root cause was. It was "solved" by the user by starting the DB from the scratch.
I can try to find more similar issues (and there were similar slack conversations which might be more difficult to find).

But he fact that we do not know what was the reason, tells me that we will have more cases like that.

Also we can ask the orignal author of the https://github.com/apache/airflow/issues/19432 @collinmcnulty - maybe you can provide more cases (when/why you needed to run reserialization - and maybe some logs from the past would be helpful).

**Comment by kaxil** [comment]
> > Can you give some examples of this please except for the 2.2.0 issue where just reserializing would have helped
> 
> Yep. It all started with this: #19519 for example.
> 
> We still do not know what the root cause was. It was "solved" by the user by recreating the DB from the scratch. I can try to find more similar issues (and there were similar slack conversations which might be more difficult to find).
> 
> But he fact that we do not know what was the reason, tells me that we will have more cases like that.
> 
> Also we can ask the orignal author of the #19432 @collinmcnulty - maybe you can provide more cases (when/why you needed to run reserialization - and maybe some logs from the past would be helpful).

Collin works with us :) We were both debugging the same issue after 2.2.0 -- but that's what I think that is it just one isolated  issue in 2 years with 2.2.0.

>We still do not know what the root cause was. It was "solved" by the user by recreating the DB from the scratch.
I can try to find more similar issues (and there were similar slack conversations which might be more difficult to find).

The root cause was we missed accounting for deserialization of Params.

**Comment by collinmcnulty** [comment]
I unfortunately do not have logs. I have encountered three kinds of scenarios where clearing the serialized dag representations was required, but the latter two seem to be fixed in 2.2:

- Incompatibilities related to the 2.2 upgrade, as has been thoroughly discussed
- When DAG authors have made changes to working DAGs such that they no longer parse correctly. The effect of this has been lessened significantly by surfacing the DAG import error on the individual DAG view. 
- For dynamically generated DAGs, some authors I've worked with wanted only the currently existing DAGs to show up in the UI, but dags that were previously generated and serialized still showed up. This could be dozens of DAGs

Having thought about it more, I'm no longer in favor of reserializing on upgrade as I don't want to have to start caveating advising people to upgrade (needing maintenance downtime windows, etc.) I'll update my original Issue to reflect my evolution in opinion.

**Comment by potiuk** [comment]
> Collin works with us :) We were both debugging the same issue after 2.2.0 -- but that's what I think that is it just one isolated issue in 2 years that happened with 2.2.0.

Hmmm. Who does not work with Astronomer then :)? 

I recalll other cases when dag serialisation was more `persistent` problem and painful (and ending up cleaning the DB). But maybe I am overcautious here indeed and it is not as bad as I thought. 

However if we are confident that the 2.2 upgrde was an isolated case, and that we have good diagnostic of similar issues and good message for users, I am OK with closing this one and leaving only the "reserialize" command to fix stuff.

**Comment by dstandish** [comment]
Shall we close this?

**Comment by potiuk** [comment]
Yep. Fine for me (also the #19533) in this case I guess.

**Pull request closed without merging**
