### PR TITLE
Fixing small issue with qbol operator and hook

### PR DESCRIPTION
**Pull request by msumit**

### CODE REVIEW

**Comment by mistercrunch** [comment]
:+1:

**Comment by artwr** [comment]
This might not work if the Qubole client is not picklable, right?

**Comment by msumit** [comment]
Sorry for n00b question, but Qubole client should be picklable, as its just a python object?

**Comment by artwr** [comment]
Usually, objects that encapsulate credentials tend to mark these fields as not picklable. It's the case for the boto client for AWS for instance. I do not know how the Qubole client works here so I am assuming you have tested it.

**Comment by msumit** [comment]
Thanks for the info Arthur, I'll test it out.

**Pull request merged**
