### PR TITLE
Revert "Switch to GitHub Container Registry by default (#16586)"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit f7aebeb8a1fb634ca7369a4455c7324f67a9deda.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
Can you explain a bit more on why we need to revert ?

**Comment by ashb** [comment]
May not be needed -- if other PRs "Wait for Image" steps are passing then this is not needed.

**Comment by potiuk** [comment]
Yeah. I just created it "in-case" we need it.

**Comment by potiuk** [comment]
This seems to be a likely permission issue with ghcr.io when I tested it this afternoon - it worked on "main" in my fork, and it still works after I merged the change but i seems to not work from PRs. I will need to investigate it more.

**Comment by potiuk** [comment]
At least here the "wait for CI image" is green now, so it does look we might not need it.

**Comment by potiuk** [comment]
Yep. Confirmed it in unrelated PR. We are back in business. Closing this one and I will test the GHCR.IO switch tomorrow.

**Pull request closed without merging**
