### PR TITLE
[AIRFLOW-3152] Kubernetes Pod Operator should support init containers.

### PR DESCRIPTION
**Pull request by marinajpereira**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - [AIRFLOW-3152] Kubernetes Pod Operator should support init containers. 
     https://issues.apache.org/jira/browse/AIRFLOW-3152

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
This PR introduces init-containers in the kubernetes pod operator. An `InitContainer` (K8SModel) resource is added to ease the configuration of the init-container in the dag file. For now, InitContainer allows for configuration of the following: `name`, `image`, `init_environment`, `volume_mounts`, `cmds`, `args`. The configuration options we selected to support in this PR is based on our current usecase. We decided against supporting more to keep the scope of this PR small.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  - tests/kubernetes/test_init_container.py that contains 2 unit tests for InitContainer
  - tests/minikube/test_kubernetes_pod_operator.py - Already existed.  Added an additional test for init-container

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by davlum** [comment]
I would suggest instead of implementing a custom object (`InitContainer`) that you allow users to pass the the`kubernetes.client.models.V1Container` object directly. Your `InitContainer` only implements a small portion of the full `kubernetes.client.models.V1Container`and requires additional code to convert to the appropriate object. This should lower the complexity and increase the functionality of this PR significantly. The old Airflow Kubernetes objects are only there for backwards compatibility API reasons.

**Comment by marinajpereira** [comment]
> I would suggest instead of implementing a custom object (`InitContainer`) that you allow users to pass the the`kubernetes.client.models.V1Container` object directly. Your `InitContainer` only implements a small portion of the full `kubernetes.client.models.V1Container`and requires additional code to convert to the appropriate object. This should lower the complexity and increase the functionality of this PR significantly. The old Airflow Kubernetes objects are only there for backwards compatibility API reasons.

@davlum Thanks for your review on this PR. I would like some clarification on your comment. 
1. When you say old Airflow Kubernetes objects, do you mean the custom objects such as: `Secret`, `VolumeMount`, `Volume`,..?
2. Are you suggesting that I allow users to define the container using the model `kubernetes.client.models.V1Container` and then pass it as `List[k8s.V1Container]` to `init_containers` in (`KubernetesPodOperator`) object?

**Comment by davlum** [comment]
1. Yeah, I'm referring to those custom objects. Each of them duplicates code that is available in `kubernetes.client.models`
2. Exactly. Users pass `List[k8s.V1Contiainer]`. No need to then convert the `InitContainer` object to the `k8s.V1Container` object.

**Comment by marinajpereira** [comment]
> 1. Yeah, I'm referring to those custom objects. Each of them duplicates code that is available in `kubernetes.client.models`
> 2. Exactly. Users pass `List[k8s.V1Contiainer]`. No need to then convert the `InitContainer` object to the `k8s.V1Container` object.

@davlum Thank you for suggesting this approach. I've made the code updates and it looks much cleaner with less complexity.

**Comment by OmerJog** [comment]
cc @dimberman

**Comment by dimberman** [comment]
Hi @marinajpereira, apologies I hadn't seen this PR. Could you rebase? Would be glad to PR an merge after that :).

**Comment by marinajpereira** [comment]
> Hi @marinajpereira, apologies I hadn't seen this PR. Could you rebase? Would be glad to PR an merge after that :).

Sure, will do! I will update you when it is ready :)

**Comment by marinajpereira** [comment]
> Hi @marinajpereira, apologies I hadn't seen this PR. Could you rebase? Would be glad to PR an merge after that :).

Hi @dimberman, I've rebased and the PR is ready for review.

**Review by dimberman — COMMENTED** [review]
LGTM. Thank you @marinajpereira!

**Comment by OmerJog** [comment]
@dimberman @potiuk release planed to 1.10.7 or 2.0 ?

**Comment by sdanbury** [comment]
What version of Airflow will this be included in please?

**Comment by potiuk** [comment]
Not planned yet for 1.10.11 - but @dimberman  -> it looks like this one should be easy to cherry-pick to 1.10.11?

**Comment by dimberman** [comment]
@potiuk should be possible :). I'm actually hoping to merge in the ability to launch arbitrary yaml files by 1.10.11 as well (I've merged in a lot of the infrastructure PR's over the past two weeks)

**Comment by sdanbury** [comment]
@dimberman sounds great, interested to see the new capabilities. I shall wait for 1.10.11 then and provided it isn't forgotten, it should be in 1.10.11?

**Comment by dimberman** [comment]
@sdanbury yes it's added to the milestone so it should be included.

**Comment by prithvisathiya** [comment]
Will this also work when setting the `init_containers` via the `pod_mutation_hook` function described here? https://airflow.apache.org/docs/stable/kubernetes.html#pod-mutation-hook

Example:
```python
def pod_mutation_hook(pod: Pod):
    init_container = k8s.V1Container(
      name="init-container",
      image="ubuntu:16.04",
      command=["bash", "-cx"],
      args=["echo 10"]
    )
    pod.init_containers = [init_container]
```

**Comment by prithvisathiya** [comment]
Actually, I was able to test it out. The code snippet I referenced above seems to work even _without_ the changes included in this PR

**Pull request merged**
