### PR TITLE
AIRFLOW-437: Send TI context in kill zombies

### PR DESCRIPTION
**Pull request by msumit**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- _https://issues.apache.org/jira/browse/AIRFLOW-437_

Thanks,
Sumit

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Please correct commit message (prefix and description) and add unit tests.

**Comment by r39132** [comment]
@msumit 

Remember to prefix your commit and PR with '[AIRFLOW-XXX]' as per https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

When we create release notes, we extract the commit title, so it's important to adhere to this convention and to require contributors to as well. 

Also, can you add some tests here?

**Comment by bolkedebruin** [comment]
Thanks for the rephrase @r39132 ;-)

**Comment by msumit** [comment]
Sure, will update it.

**Comment by r39132** [comment]
@bolkedebruin I think we both updated this page within a couple of minutes ;-) Are you checking airflow from a beach or something similarly wonderful?

**Comment by bolkedebruin** [comment]
Just got back. Still a Jet lag to recover from!

**Comment by bolkedebruin** [comment]
Copacabana is great though!

**Comment by msumit** [comment]
opened a new PR as I've messed up all commit history.. plz review new PR here https://github.com/apache/incubator-airflow/pull/1796

**Pull request closed without merging**
