### PR TITLE
feat: support K8S 1.28

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Comment by potiuk** [comment]
Cool. I guess 1.24 removal should bein October when GCP's end of life for 1.24 is :)

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Looks like "rolling window" and alternating between 4 and 5 supported version of K8S will be our target setup.

**Review by uranusjr — APPROVED** [review]
Waiting for CI.

**Comment by potiuk** [comment]
All tests (including K8S ones) passed :)

**Pull request merged**
