### PR TITLE
[AIRFLOW-2419] Use default view for subdag operator

### PR DESCRIPTION
**Pull request by milanvdm**
### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2419) issue

### Description
- [x] When you click on Zoom Into SubDag, you will be redirected to the SubDag on the default view. The default setting comes from airflow.config.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x]

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by milanvdm** [comment]
@Fokko @ashb Could you guys have a look?

**Comment by Fokko** [comment]
I'm not super familiar with the GUI/view's. @bolkedebruin do you have an opinion?

**Comment by milanvdm** [comment]
@bolkedebruin Could you have a look please?

**Comment by mistercrunch** [comment]
LGTM

**Comment by mistercrunch** [comment]
You might want to confirm that things are ok in  the upcoming new UI under `www_rbac`

**Comment by bolkedebruin** [comment]
Woooooooo @mistercrunch is doing a commit! Hear hear! @Fokko 👍

**Comment by bolkedebruin** [comment]
Awesome

**Pull request closed without merging**
