### PR TITLE
Azure storage 0.37.0 is not installable any more

### PR DESCRIPTION
**Pull request by potiuk**
2020.05.12 release of the azure-storage is not installable any more
(it is deprecated). For now we should switch to latest working
version

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
CI failed, section flask8, but I think we ignore scripts and dev folder
```
scripts/ci/pre_commit_yaml_to_cfg.py:96:42: F541 f-string is missing placeholders
scripts/ci/pre_commit_yaml_to_cfg.py:111:46: F541 f-string is missing placeholders
airflow/providers/google/cloud/example_dags/example_presto_to_gcs.py:50:12: F541 f-string is missing placeholders
tests/executors/test_executor_loader.py:74:35: F541 f-string is missing placeholders
airflow/jobs/scheduler_job.py:564:17: E131 continuation line unaligned for hanging indent
tests/models/test_serialized_dag.py:123:17: F541 f-string is missing placeholders
tests/models/test_serialized_dag.py:123:32: F541 f-string is missing placeholders
tests/models/test_serialized_dag.py:123:47: F541 f-string is missing placeholders
dev/send_email.py:41:12: F541 f-string is missing placeholders
dev/send_email.py:42:14: F541 f-string is missing placeholders
```

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
> CI failed, section flask8, but I think we ignore scripts and dev folder
> 
> ```
> scripts/ci/pre_commit_yaml_to_cfg.py:96:42: F541 f-string is missing placeholders
> scripts/ci/pre_commit_yaml_to_cfg.py:111:46: F541 f-string is missing placeholders
> airflow/providers/google/cloud/example_dags/example_presto_to_gcs.py:50:12: F541 f-string is missing placeholders
> tests/executors/test_executor_loader.py:74:35: F541 f-string is missing placeholders
> airflow/jobs/scheduler_job.py:564:17: E131 continuation line unaligned for hanging indent
> tests/models/test_serialized_dag.py:123:17: F541 f-string is missing placeholders
> tests/models/test_serialized_dag.py:123:32: F541 f-string is missing placeholders
> tests/models/test_serialized_dag.py:123:47: F541 f-string is missing placeholders
> dev/send_email.py:41:12: F541 f-string is missing placeholders
> dev/send_email.py:42:14: F541 f-string is missing placeholders
> ```

This looks like flake8 released new version !

**Comment by kaxil** [comment]
> > CI failed, section flask8, but I think we ignore scripts and dev folder
> > ```
> > scripts/ci/pre_commit_yaml_to_cfg.py:96:42: F541 f-string is missing placeholders
> > scripts/ci/pre_commit_yaml_to_cfg.py:111:46: F541 f-string is missing placeholders
> > airflow/providers/google/cloud/example_dags/example_presto_to_gcs.py:50:12: F541 f-string is missing placeholders
> > tests/executors/test_executor_loader.py:74:35: F541 f-string is missing placeholders
> > airflow/jobs/scheduler_job.py:564:17: E131 continuation line unaligned for hanging indent
> > tests/models/test_serialized_dag.py:123:17: F541 f-string is missing placeholders
> > tests/models/test_serialized_dag.py:123:32: F541 f-string is missing placeholders
> > tests/models/test_serialized_dag.py:123:47: F541 f-string is missing placeholders
> > dev/send_email.py:41:12: F541 f-string is missing placeholders
> > dev/send_email.py:42:14: F541 f-string is missing placeholders
> > ```
> 
> This looks like flake8 released new version !

Created a PR to fix those https://github.com/apache/airflow/pull/8841

**Comment by kaxil** [comment]
Can you rebase the PR on the latest master, please?

**Comment by potiuk** [comment]
Oh yeah. Thanks!

**Comment by potiuk** [comment]
Done :). Thanks for fixing the flake errors @kaxil . Been distracted for a short while

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
Let's wait until it builds, it does not impact regular PRs/builds so no hurry with it

**Review by ashb — APPROVED** [review]

**Comment by felipefb** [comment]
I tried to install the azure package now and had a similar error. Is the new version already available?

```
Collecting azure-storage>=0.34.0; extra == "azure"
 Downloading azure-storage-0.37.0.zip (4.3 kB)
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ulhnvfzb/azure-storage/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ulhnvfzb/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dicvhu77
     cwd: /tmp/pip-install-ulhnvfzb/azure-storage/
  Complete output (19 lines):
  Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "/tmp/pip-install-ulhnvfzb/azure-storage/setup.py", line 55, in <module>
    raise RuntimeError(message)
  RuntimeError:
  Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
  Please install the service specific packages prefixed by `azure` needed for your application.
  The complete list of available packages can be found at:
  https://aka.ms/azsdk/python/all
  Here's a non-exhaustive list of common packages:
  - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
  - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
  - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
  - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
  ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by potiuk** [comment]
It's fixed in master If you try to install released 1.10.10 version in a stable way you should follow the  https://github.com/apache/airflow/blob/master/README.md#installing-from-pypi

```
pip install apache-airflow==1.10.10 \
 --constraint https://raw.githubusercontent.com/apache/airflow/1.10.10/requirements/requirements-python3.7.txt
```

**Pull request merged**
