### PR TITLE
Fix bugs in URI constructor for MySQL connection

### PR DESCRIPTION
**Pull request by MaksYermak**
In this PR I have fixed several bugs in the `get_uri` function in connection.py file. And also I have created unit tests for most of the use cases for this function.

Co-authored-by: Maksim Yermakou [maksimy@google.com](mailto:maksimy@google.com)
Co-authored-by: Wojciech Januszek [januszek@google.com](mailto:januszek@google.com)
Co-authored-by: Lukasz Wyszomirski [wyszomirski@google.com](mailto:wyszomirski@google.com)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
You do realize that "model/connection" is used by more than MySQL?

Are you sure you are not breaking other usages? 

It seems it does break a lot of tests at least. I'd be really cautious to modify "airflow core" connection method to fix MySQL.. This looks (without going into details) like a need to override the method in MySQL connection to do mysql-specific stuff rather than change behaaviours of all other connections.

**Comment by potiuk** [comment]
I am not saying it's wrong - but just - that -  be cautions and try to understand how this "shared" method is used elsewhere before attempting to change it.

**Comment by potiuk** [comment]
> @potiuk I think my change in `get_uri` method shouldn’t break something, conversely this change will fix current issue. Our `get_uri` function should return DB connection URL for `create_engine` function in SQLAlchemy in this format `dialect[+driver]://user:password@host/dbname[?key=value..]`. Currently Airflow has a problem, when user tries to create DB connection without `dbname`, but with `extras` user meets error. It happens, because `get_uri` function adds `extras` to the `host` without division by `/` e.g. `conn-type://login:password@:3306?charset=utf-8` is wrong URL the correct URL should look like this `conn-type://login:password@:3306/?charset=utf-8`.

Could you please point me to the docs/specs where `conn-type://login:password@:3306?charset=utf-8` is wrong ? Is it a mysql sqlalchemy or "generic" sqlachemy problem?  I am afraid that this **might** break something if this is mysql specific limitation rather than generic sqlalchemy one. 

FWIW  the URI specification https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 is quite clear that the `path` component of the URI can be empty, and empty path is different than "root path" - (indicated by "/" ) - so I wonder if this change will not have impact on any other sqlalchemy URIs  (especially with schema-less databases). 

According to the RFC - `conn-type://login:password@:3306?charset=utf-8` is perfectly good URI with "empty" path.

Can you trace down where the limitation of "require `/` path if there is a query part" comes from?

**Comment by MaksYermak** [comment]
> > @potiuk I think my change in `get_uri` method shouldn’t break something, conversely this change will fix current issue. Our `get_uri` function should return DB connection URL for `create_engine` function in SQLAlchemy in this format `dialect[+driver]://user:password@host/dbname[?key=value..]`. Currently Airflow has a problem, when user tries to create DB connection without `dbname`, but with `extras` user meets error. It happens, because `get_uri` function adds `extras` to the `host` without division by `/` e.g. `conn-type://login:password@:3306?charset=utf-8` is wrong URL the correct URL should look like this `conn-type://login:password@:3306/?charset=utf-8`.
> 
> Could you please point me to the docs/specs where `conn-type://login:password@:3306?charset=utf-8` is wrong ? Is it a mysql sqlalchemy or "generic" sqlachemy problem? I am afraid that this **might** break something if this is mysql specific limitation rather than generic sqlalchemy one.
> 
> FWIW the URI specification https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 is quite clear that the `path` component of the URI can be empty, and empty path is different than "root path" - (indicated by "/" ) - so I wonder if this change will not have impact on any other sqlalchemy URIs (especially with schema-less databases).
> 
> According to the RFC - `conn-type://login:password@:3306?charset=utf-8` is perfectly good URI with "empty" path.
> 
> Can you trace down where the limitation of "require `/` path if there is a query part" comes from?

@potiuk yes of course in sqlalchemy doc https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls has link to [RFC-1738](https://www.ietf.org/rfc/rfc1738.txt) spec. This spec in point 3.3 has this string `If neither <path> nor <searchpart> is present, the "/" may also be omitted.`. For me this string means that we should omitt `/` only in case when we don't have both of parameters `<path>` and `<searchpart>` if we have one of them the `/` should be. Correct me please if I make mistake?

**Review by potiuk — APPROVED** [review]

**Pull request merged**
