### PR TITLE
[AIRFLOW-1768] add if to show trigger only if not paused

### PR DESCRIPTION
**Pull request by alison985**
Right now you can manually trigger a DAG that is paused which will show
as running indefinitely without running any tasks and confuses the
user. This hides the “Trigger DAG” action from the user if the DAG is
paused. This is done by taking the if statement from the “Pause” column
and adds it to the “Trigger DAG” action in the links column.

Resolves: https://issues.apache.org/jira/browse/AIRFLOW-1768

### CODE REVIEW

**Comment by saguziel** [comment]
Hi, can we please use the default PR template and include a screenshot? Thanks.

**Comment by alison985** [comment]
@saguziel Where would I find the default PR template?

**Comment by Acehaidrey** [comment]
Hi @alison985 I believe the default is what comes with when you create a PR. It asks to link the jira then the description with screenshots, then tests and lastly makes sure commits follow the certain convention. If you look at other PRs you should see it.

**Comment by Acehaidrey** [comment]
PS I have also had this confuse users (work on an infrastructure team for others to build jobs on airflow) and so I'm looking forward to seeing this PR and how it works! Screenshots would be really helpful if its not too much trouble

**Comment by andres-lowrie** [comment]
What's the status of this ?

**Comment by megaserg** [comment]
Still an issue.

**Comment by Rotemlofer** [comment]
This is a nice twik! I was confused by it several times. Would be nice to have this.

**Comment by ron819** [comment]
Since it's unlikely that this PR will be merged before  https://github.com/apache/airflow/pull/4339
I think it would be better if you'll edit this PR to work with:
`airflow/www_rbac/templates/airflow/dag.html `
and drop 
`airflow/www/templates/airflow/dags.html ` since the old UI is deprecated.

better hear what @kaxil ,@verdan, @feng-tao  thinks about the status of https://github.com/apache/airflow/pull/4339

**Comment by ashb** [comment]
Rather than removing the trigger button entirely we should have it there, but make it disabled (with a tooltip saying why it's disabled -- i.e. the DAG is paused.)

Additionally there are other places where the Trigger DAG appears - on the home page, and I think there's a modal popup somewhere that has a Trigger button. (These were probably added after this PR was opened).

**Pull request closed without merging**
