### PR TITLE
[AIRFLOW-2629] Change reference of hive_hooks to hive_hook everywhere

### PR DESCRIPTION
**Pull request by eladkal**
### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-2629) 

### Description
Renaming hive_hooks to hive_hook for consistency with other packages.
Changing all references to match the update hook.

### CODE REVIEW

**Comment by ashb** [comment]
Please add a mention of this in UPDATING.md

**Comment by eladkal** [comment]
@ashb  done.

**Comment by kaxil** [comment]
We can keep it as it is. Most of the other hook file in that directory has 1 hook, whereas hive as 3 hooks. Accepting this will mean many more PRs with changing the naming convention here and there. And I know we don't have a clear rule for `contrib` vs `core`, but hive has been a part of core, I don't want users to change module import because of this change.

Maybe we can address NamingConvention when we have a 2.0 branch with a Massive Single PR that address NamingConvention across all.

What do you think @ashb

**Comment by ashb** [comment]
I don't feel strongly either way about this PR. It would be possible to rename (if we decide that's what we want to do) and to have a deprecated import to make the upgrade path easier -- it's easy to maintain this shim for a release or two past 2.0 (say to 2.1 or 2.2)

A random point: I think the naming of things is a little bit all-over the place, now that you mention it, and I think we should have something like this (as a non-representative sample):

(I am *not* saying we should make this change, it's just my immediate thought)

* Remove `_hook` suffix from the module name

  We don't need  "hook" or "hooks" in the module, as it's already there from the parent
  ```python
  from airflow.hooks.hive import HiveServer2Hook, HiveCliHook
  ```

* Have related operators in the same module: 

  Rather than

  ```python
  from airflow.operators.emr_add_step_operator import EmrAddStepOperator
  from airflow.operators.emr_create_job_flow_operator import EmrCreateJobFlowOperator
  ```

  I think we should group closely related operators together like this.

  ```python
  from airflow.operators.emr import EmrAddStepOperator, EmrCreateJobFlowOperator
  ```

* Entirely drop the `contrib` folder module.

  We as a project have a copyright grant on all code, and have to maintain it all equally. I think the contrib folder made more sense when Airflow belonged to AirB'n'B but isn't useful now.

.... This should probably be an AIP. 😀

**Comment by kaxil** [comment]
Definitely, agree with most of the points. I had raised a PR a year back :D regarding a similar thing i.e. grouping related items for GCP Storage under 1 module then to have multiple files here and there.

Regarding `contrib` - I had different plans - as hooks/Ops for AWS, GCP evolve more rapidly than the core and we didn't have frequent airflow releases - I thought it would be better to have them in seprate repos similar to Terraform Providers but that needs a bigger work and a solid plan. But looks like we are having more frequent releases now + once we are TLP we can actually make the process faster. Hence, maybe we can remove contrib completely.

**Comment by eladkal** [comment]
Hi guys, I picked it up because it was an open ticket. I see now that this task wan't actually discusses.
Is there something required here to be done or shall I close this PR?

**Pull request closed without merging**
