### PR TITLE
Enable OpenLineage Breeze integration via Marquez

### PR DESCRIPTION
**Pull request by patgarz**
This adds an option to spin up `breeze` using `--integration openlineage`, which will spin up a simple implementation of [Marquez](https://marquezproject.ai) and send metrics to namespace `airflow`.

Notes before merge -

1. Marquez in their docs require PostgreSQL 12.1, but it seems to be working with Postgres 13 and 14 as well (but not 15). I can add this to the docs, but a better option may be to spin up a separate Postgres container (though this does significantly affect resourcing). Any thoughts on appropriately handling this?
2. I was only able to get metrics to send by setting Breeze to install `2.7.0`. It did not work in the `main`. I'm not sure whether that indicates a bug in my configuration or a bug that has been introduced in the `main`.
3. Marquez webserver conflicts with Grafana in that they both spin up on Port `3000`, so the standard mapping pattern of `2<port>` does not work. I opted for `23100` so that this PR did not break `--integration all`, but if there's another preferred pattern, it's an easy fix.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Cool!  Suggestiom though: 

Should we add it to Breeze's cheathseet including ability to chnage is as env variables?

https://github.com/apache/airflow/blob/main/dev/breeze/src/airflow_breeze/utils/visuals.py#L89

**Comment by patgarz** [comment]
Easy enough; added options to configure via `<svc>_HOST_PORT` & rebased.

I did not add it to the cheatsheet as the other optional metrics integrations aren't in that cheatsheet and I hesitate to add all of the integrations there as it will increase the cheetsheet length (and possibly add confusion since these aren't core Airflow services) significantly. If you disagree, let me know and I'll go ahead and add.

**Comment by potiuk** [comment]
Needs conflict resoiving due to changes commands in main.

> This adds an option to spin up `breeze` using `--integration openlineage`, which will spin up a simple implementation of [Marquez](https://marquezproject.ai) and send metrics to namespace `airflow`.
> 
> Notes before merge -
> 
> 1. Marquez in their docs require PostgreSQL 12.1, but it seems to be working with Postgres 13 and 14 as well (but not 15). I can add this to the docs, but a better option may be to spin up a separate Postgres container (though this does significantly affect resourcing). Any thoughts on appropriately handling this?

We can print error and exit for 11 and 15 if you try to use openlineage integration. We already do similar checks  for mysql/ARM combination. Look for: `def enter_shell(**kwargs) -> RunCommandResult`. 

> 2. I was only able to get metrics to send by setting Breeze to install `2.7.0`. It did not work in the `main`. I'm not sure whether that indicates a bug in my configuration or a bug that has been introduced in the `main`.

That would be surprising. The one difference I can think of - naybe this is connected with the way openlineage provider (and any other) is used in "main" - the openlineage code is loaded directly from sources not from package. So some code might not work the same way (for example queryng package metada will not work if you run it from main (INSTALL_PROVIDERS_FROM_SOURCES="true" is set in breeze and ProvidersManager will look in sources for provider.yaml files rather than querying provider_info endpoint to get all the provider information). @mobuchowski - maybe that rings a bell?  

> 3. Marquez webserver conflicts with Grafana in that they both spin up on Port `3000`, so the standard mapping pattern of `2<port>` does not work. I opted for `23100` so that this PR did not break `--integration all`, but if there's another preferred pattern, it's an easy fix.

It's fine. We do it for others tool

**Comment by potiuk** [comment]
BTW. Even if we do not print it in cheatsheet. It might be worthwile to log information that marquez is available at this and that addreess. This can be done in the same par of "enter_shell" pre-execution code that you can use to do Postgres verification. Would be nice to extract those checks (existing ARM/mysql and new Openlineage/postgres to separate methods).

Also I am wondering what we should do if we run openlineage but NOT postgres (say mysql). I would not really want to stop this from happening. I guess we should error out similarly as with Postgres 11, 15 and print information to use Postgres 12-14.

**Comment by mobuchowski** [comment]
> Marquez in their docs require PostgreSQL 12.1, but it seems to be working with Postgres 13 and 14 as well (but not 15). I can add this to the docs, but a better option may be to spin up a separate Postgres container (though this does significantly affect resourcing). Any thoughts on appropriately handling this?

@patgarz It's probably missing some word like "minimum" or "at least" 12.1 - can you link where you found this, to fix it?
Not working on 15 must be a bug, definitely worth fixing.

> That would be surprising. The one difference I can think of - naybe this is connected with the way openlineage provider (and any other) is used in "main" - the openlineage code is loaded directly from sources not from package. So some code might not work the same way (for example queryng package metada will not work if you run it from main (INSTALL_PROVIDERS_FROM_SOURCES="true" is set in breeze and ProvidersManager will look in sources for provider.yaml files rather than querying provider_info endpoint to get all the provider information). @mobuchowski - maybe that rings a bell?

After https://github.com/apache/airflow/pull/32692 loading plugin from provider should happen regardless if providers are installed from sources or from package - provided the plugins and providers aren't lazily loaded.

**Review by uranusjr — APPROVED** [review]

**Comment by patgarz** [comment]
> It's probably missing some word like "minimum" or "at least" 12.1 - can you link where you found this, to fix it?

@mobuchowski I was referencing the requirements here: https://github.com/MarquezProject/marquez#requirements

PG15 produces the following warning in Marquez startup, and the app then exits (though we should likely migrate this conversation over there):

```txt
WARN  [2023-08-28 15:55:03,189] org.flywaydb.core.internal.database.base.Database: Flyway upgrade recommended: PostgreSQL 15.4 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 14.
```

**Comment by mobuchowski** [comment]
@patgarz sure, created issue on Marquez GH: https://github.com/MarquezProject/marquez/issues/2604

**Review by potiuk — APPROVED** [review]
Pending regeneration of breeze images.

**Comment by potiuk** [comment]
Need to solve conflicts still :(

**Comment by patgarz** [comment]
Rebased & should be all set now.

**Comment by potiuk** [comment]
Cool :)

**Pull request merged**
