### PR TITLE
Added Datascan Profiling

### PR DESCRIPTION
**Pull request by shourya116**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Need to get green first. I recommend installingpre-commit as well.

**Comment by potiuk** [comment]
Yes. the problem in this PR is that you have not run it through `pre-commit` - which means dependencies have not been regenerated and the image fails to be built, so in order to do anything about it you need to install and run pre-commit with your change first - see the CONTRIBUTNG docs and look for pre-commit if in doubt

**Comment by potiuk** [comment]
cc: @VladaZakharova and team ?

**Review by potiuk — APPROVED** [review]
LGTM - if @VladaZakharova and team have no comments.

**Review by ahidalgob — APPROVED** [review]

**Pull request merged**
