### PR TITLE
[AIRFLOW-3163] add operator to enable setting table description in BigQuery table

### PR DESCRIPTION
**Pull request by antxxxx**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3163
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

This adds a BigQuery operator to allow setting a table description

### CODE REVIEW

**Comment by kaxil** [comment]
A different operator for setting table description? I don't think it is worth it. I am ok with having a param in BQ operators to add an optional description but definitely not a separate operator.

**Comment by antxxxx** [comment]
There is not a bigquery api exposed to set the description when you want to run a query and save the results to a table - which is the main reason I wanted this.   
My flow is load data into staging tables -> aggregate data using sql and save the results to new table -> set table description on new table with metadata such as timestamp when aggregate was performed, source systems etc.      

The other use case I want it for is to include metadata such as latest extract date or load date in history tables. This obviously changes each time new data is added to the table so can not be set at table creation time, and again there does not seem an api exposed to set description when adding data to an existing table.   

I could change the existing operators to include a description parameters, and then call the hook to set the description after it has run, but it seemed simpler and more useful to add a new operator to set the description

**Comment by ron819** [comment]
@antxxxx I believe that most people add their `etl_timestamp` as a column to the table itself. In some scenario it's even the partition field of the table.

I think the better approach is to ask Google to add support for Description & Column description in their CLI commands. Currently it's supported only manually from the UI. 
https://cloud.google.com/support/docs/issue-trackers

Once google will add this feature it will be possible to modify the Airflow Operator to support it.

I don't think there should be a separated operator just for this option.

**Comment by Fokko** [comment]
PTAL @fenglu-g @tswast

**Comment by tswast** [comment]
I agree that this isn't general enough to warrant a whole operator. It would mean an explosion of operators if we provide one for every property of every resource.

Perhaps a "patch BigQuery table metadata" operator would be more appropriate? It could accept a dictionary of properties to update on the table resource. See: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables/patch

**Comment by Fokko** [comment]
Just thinking along here. We could extend the create table definition and add the description over there: https://github.com/apache/incubator-airflow/blob/master/airflow/contrib/hooks/bigquery_hook.py#L214-L284

The create table call supports supplying a description field: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource

We could template this field, so we can use `created at: {{ execution_date }}`, which will translate to `created at: 2018-06-04`. Thoughts?

**Comment by antxxxx** [comment]
@Fokko I am not explicitly creating a table - I am either loading into a new table or sending query results to a new table. With these methods you can not set the table description (this is a limitation of bigquery api)   

@tswast Having an operator to update table metadata is a good idea. I think the only things you can actually update in a patch call are description, labels and expiration. Would you expect these as 3 specific parameters to the operator, or one parameter whose value is passed to the patch call?

**Comment by tswast** [comment]
It's also possible to
* add columns to a table and make updates to schema descriptions. https://cloud.google.com/bigquery/docs/managing-table-schemas
* update the encryption key if the table was already using an encryption key. https://cloud.google.com/bigquery/docs/customer-managed-encryption#change_key

Having a separate parameter for each property seems the most consistent with other operators, but I'm not opposed to having a single "table resource" parameter.

**Pull request closed without merging**
