### PR TITLE
Make dbapi inherit get_uri from connection

### PR DESCRIPTION
**Pull request by bolkedebruin**
DBApi has its own get_uri method which does not deal
with quoting properly and neither with empty passwords.
Connection also has a get_uri method that deals properly
with the above issues.

@dimberman @ashb

### CODE REVIEW

**Review by ashb — APPROVED** [review]

**Review by potiuk — APPROVED** [review]
NICE!. 

BTW. I looked it up - the get_uri  method was added (and with plenty of tests) in Airflow 2.0.0 and already present in the 1.0 verson of all providers so it shuld be backwards-compatible in all directions. I wonder why we have not updated it then :)

**Comment by bolkedebruin** [comment]
@potiuk which one did you look up? the one in dbapi was pretty buggy and I am not sure why it worked :-). The one in connection is a bit better, but I am confused why we use so little standardization here while url encoding is actually pretty hard.

**Comment by ashb** [comment]
I have a feeling Connection.get_uri is a "relatively" recent addition, I think added for `airflow connections export` command.

**Comment by potiuk** [comment]
> I have a feeling Connection.get_uri is a "relatively" recent addition, I think added for `airflow connections export` command.

Yep. It is. And I think this is simply a very straightforward manifestation of "If is is not used, it lkely does not work". 

From what I looked today the "Connection" get_uri() was added in 2.0.0a. 
And if you look closely - there is no "REAL" usage of get_uri. There is nearly no use case for it - except displaying it in the `airflow CLI` and possibly UI (which does not matter at all if it is correct or not).

The only `actual` usage of get_uri - from what I see - is "get_sqlalchemy_engine"  which is actually hardly useful anyway. Getting sqlalchemy engine for a connection makes pretty much no sense. SQLAlchemy is really an ORM mapper, and when you have generic connection you have no object schema and SQLAlchemy is useless (you can instantiate an SQLAlchemy session and run a raw query - maybe - but then you can run query via DBApi's "run" method.

So while we likely should keep backwards compatibility I think hardly anyone uses it or make some assumptions about it's correctness.

**Comment by bolkedebruin** [comment]
Interesting! Maybe we should move away from "conn_type" etc and just rely on people specifying a URI (as happens in others systems) and allow for specifying a key or username/password?

**Comment by potiuk** [comment]
> Interesting! Maybe we should move away from "conn_type" etc and just rely on people specifying a URI (as happens in others systems) and allow for specifying a key or username/password?

I think connections need redesign badly. There are a number of ambiguities and duplications there (especially in-connection with extras and UI). And I also think @dimberman you already take steps in that direction too right ? :D.

**Pull request merged**
