### PR TITLE
Improve test coverage for the rest api modules

### PR DESCRIPTION
**Pull request by ephraimbuddy**
Related: https://github.com/apache/airflow/issues/35127

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by vincbeck — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
I can't figure out a scenario where `MultipleResultsFound` would be raised in this endpoint: https://github.com/apache/airflow/blob/d07e66a5624faa28287ba01aad7e41c0f91cc1e8/airflow/api_connexion/endpoints/task_instance_endpoint.py#L649

The error message suggests that if we have a mapped task instance, then it would result in the error but it doesn't seem so since map_index is -1 by default which the query before the exception sorts: https://github.com/apache/airflow/blob/d07e66a5624faa28287ba01aad7e41c0f91cc1e8/airflow/api_connexion/endpoints/task_instance_endpoint.py#L642
cc @Jorricks , maybe you can shed more light if you still remember

**Comment by ephraimbuddy** [comment]
Hi @potiuk, @vincbeck I added additional commits after your approvals, you can take another look, especially on test_task_instance_endpoint.py

**Review by vincbeck — APPROVED** [review]
The tests look good to me. Very nice having new tests and increasing code coverage!

**Review by potiuk — APPROVED** [review]

**Comment by Jorricks** [comment]
> except MultipleResultsFound:

Yes I vaguely remember this and thinking as well that it should never be possible that it would get two results back. If it did, it would be a programming error, which is why I made the exception handling.

**Pull request merged**
