### PR TITLE
Fix flaky supervisor conflict test

### PR DESCRIPTION
**Pull request by potiuk**
The test sometimes runs for a longer time and generates more requests - thus producing slightly different output and count of requests. This PR accepts bigger request count.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by gopidesupavan — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]

**Review by ashb — COMMENTED** [review]
This smells like a bug - once the supervisor sees the 409 it should stop making requests and kill the subproc.

I will take a detailed look in an hour

**Review by ashb — APPROVED** [review]
We can merge now if we want.

**Review by shahar1 — APPROVED** [review]

**Comment by ashb** [comment]
Ah okay I see what has happened, when we receive the failed response we enter the kill loop, and as part of letting the task shutdown cleanly we can _re-enter_ the send_heartbeat if needed bath.

PR coming to prevent that

**Comment by potiuk** [comment]
> Ah okay I see what has happened, when we receive the failed response we enter the kill loop, and as part of letting the task shutdown cleanly we can _re-enter_ the send_heartbeat if needed bath.
> 
> PR coming to prevent that

Cool.

**Comment by ashb** [comment]
Okay, it wasn't quite that, it was an artifact of the short heartbeat interval we use in the tests, and how we poll for the subprocess exit code. I don't think it will happen in practice. I've made it more-robust anyway.

Looking at this also made me notice that we don't correctly handle the wait between TERM and KILL when we kill the subprocess.

**Pull request merged**
