### PR TITLE
[Tokopedia-Airflow-V1.9] Tokopedia Airflow PR

### PR DESCRIPTION
**Pull request by topedmaria**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Hi @topedmaria, I think something went wrong with this PR. Please be careful because this will take up CI time of our Travis. Cheers, Fokko

**Comment by topedmaria** [comment]
Hi Fokko, 

 

Thank you for the information, I will be careful.


When I created a PR, I saw conflict.

 

Actually, I am just trying to do: 

 

"As the Airflow community grows, we'd like to keep track of who is using the platform. Please send a PR with your company name and @githubhandle if you may."


Thanks, 

Maria

**Comment by Fokko** [comment]
Sure, the easiest way to do this is by closing this PR. Then edit the README.md:
https://github.com/apache/incubator-airflow/edit/master/README.md

Cheers, Fokko

**Comment by bolkedebruin** [comment]
Please close this asap. It is taking build time away from other PRs.

**Comment by topedmaria** [comment]
Hi Fokko, 


Thank you for the information, I already close the PR.


I am sorry for the inconvenient.

 

Thanks, 

Maria

**Pull request closed without merging**
