### PR TITLE
add new S3MultiKeySensor

### PR DESCRIPTION
**Pull request by riastrad**
Over at @sofarocean, we found that the existing S3 sensors did not support one critical use case we had. Specifically, we needed to explicitly check for the presence of multiple S3 keys before continuing on to downstream tasks. If any of the objects were missing, downstream tasks would fail so we needed a sensor that would only resolve to `True` if all keys were accounted for.

Here is the proposed API:

```python
task = S3MultiKeySensor(
  task_id='task_id',
  bucket_name='bucket'
  bucket_keys=[
    'key1',
    'key2',
    'key3'
  ]
)
```

I'm sharing the solution we came up with in case it might prove useful to others with similar use cases. I don't have a clear picture of the broader community's preferred dev ergonomics, so if the code needs to be made more robust or if the Airflow team would prefer that I also add support for multiple buckets, full s3:// urls, etc. please just let me know and I'm happy to update this PR.

### CODE REVIEW

**Comment by o-nikolas** [comment]
Hey @riastrad!

Thanks for the contribution :)

Two notes:

1. New operators should come along with example dags and docs. You may be able to update an existing example dag/doc with this new functionality. You can see some examples for S3 [here](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/example_dags/example_s3_bucket.py) and [here](https://github.com/apache/airflow/blob/a1fd82f2a5c9edc4817b04b4ccc257d6e394f886/docs/apache-airflow-providers-amazon/operators/s3.rst).
1. I'd like to hear more about your use case. How many keys are you waiting on? If it's only a few there's nothing stopping you from kicking off several sensors in parallel waiting on keys and then have a downstream task with the trigger rule all_success (implied in chain example): `chain(start_task, [wait_for_key_1, wait_for_key_2, wait_for_key_3], end_task)`
This will create a dag like this, where `end_task` will only run after all upstream tasks have completed:
Screenshot from 2022-04-05 20-07-39


Does this satisfy your usecase, or do you still think this net-new Operator is required?

**Comment by eladkal** [comment]
I think the use case of this sensor will be covered fully with https://github.com/apache/airflow/pull/22737

**Comment by riastrad** [comment]
Thank you both for the quick responses!

@o-nikolas:
1. Thanks for heads up about doc updates. If we decide to move forward with this PR then I'll be sure to add those.
2. Our use case currently only requires 3 checks, but might need to expand to more in the future. We had considered using multiple sensors with a downstream trigger rule like you described, but our DAGs are already quite complicated and a custom sensor that only represented one task felt like the cleaner solution in this case.

@eladkal thank you for flagging #22737! I didn't see that when I initially skimmed PRs in this repo. A quick look at those changes and I agree that they should satisfy our use case quite well if/when they land in main. 

I'm definitely happy to close this PR out in favor of #22737, since that appears to be a more robust solution 👍

**Comment by vincbeck** [comment]
Exactly like @eladkal mentioned, once my PR #22737 merged, `S3KeySizeSensor` will be able to support multiple files

**Comment by vincbeck** [comment]
Happy to see there is a need for such use case :)

**Comment by eladkal** [comment]
So I'm closing this PR in favor of https://github.com/apache/airflow/pull/22737
@riastrad it would be great if you can also review https://github.com/apache/airflow/pull/22737 as you are going to use it so your perspective can be very useful.

**Pull request closed without merging**
