### PR TITLE
[AIRFLOW-2668] Improve handling of missinng optional cryptography dep

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2668

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

cryptography is a recommended, but optional dependency. It was
mistakenly made a hard dependency by a refactor. This restores that
behaviour (though without tests, as it's hard to test that in a
unittest)

In testing this I found that running `airflow initdb` would end up
printing the "crypto is missing" message 15 times, making it hard to see
what was actually going on. So I have re-worked `get_fernet()` to only
compute (and warn) once. This also makes the consuming code easier as in
the case of the dep not being installed we still have a class that
presents the same interface as Fernet.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
  no unit tests because it's hard/impossible to test the absence of a module in a unittest. Unless someone can suggest a way of testing this? I have tested this change in a venv.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x..] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by afernandez — APPROVED** [review]
+1 LGTM

**Comment by jgao54** [comment]
This is great, I've seen many people getting confused about the fernet key when first installing airflow locally because of the hard dependency.  Will take a look tonight :)

**Comment by bolkedebruin** [comment]
I'm assuming this works... (no tests?)

**Comment by ashb** [comment]
Couldn't think how to test automatically. Did manual testing and it worked

**Pull request closed without merging**
