### PR TITLE
[AIRFLOW-289] Make airflow timezone independent

### PR DESCRIPTION
**Pull request by bolkedebruin**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-289

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:

Airflow mixes datetime.now()/today() and utcnow(). This can lead
to issues in case the OS is not in UTC.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Current tests should cover this

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

@criccomini @saguziel @aoen 

Please note it should not affect systems that are running in UTC as is the best practice. It just makes it possible to run Airflow on a non UTC OS.

### CODE REVIEW

**Comment by criccomini** [comment]
This LGTM, provided the tests pass.

Agreed that this shouldn't affect anyone that's already running on UTC. I can imagine this causing some weird bug reports, though, for those not running on UTC, so I suppose we'll have to keep our eyes out.

Anyway, +1 once tests pass.

**Comment by bolkedebruin** [comment]
After this we could do fancy features like taking care of daylight savings time or use different timezones for workers... :P

**Comment by criccomini** [comment]
😱

**Comment by bolkedebruin** [comment]
Build is ok: https://travis-ci.org/bolkedebruin/airflow/builds/277895482

**Comment by lxneng** [comment]
@bolkedebruin my OS is not running on UTC, how to make this change works on my case? Thanks!

**Comment by Fokko** [comment]
Maybe stick a note in `UPDATING.md`, I can imagine that it might be confusing if you are not aware that everything is changed to UTC.

**Comment by bolkedebruin** [comment]
I can do that, but it is assumed you are running in UTC anyway. We now Made it consistent which alles you to run in non UTC environments.

**Comment by ryankennedyio** [comment]
@bolkedebruin @criccomini 

> After this we could do fancy features like taking care of daylight savings time or use different timezones for workers... :P

This would actually be fantastic. Would be helpful in finance where e.g. a task needs to be run on a stock exchange which has a local open & closing time, which obviously change with daylight savings.

**Comment by RobGoretsky** [comment]
Echoing the need / desire for making Airflow work around daylight savings - my use case, which I can't imagine is so uncommon, is that we produce reports for executives that expect to see those reports in a specific time zone (in this case, Eastern time)  So, they want to see 'all widgets sold on October 19', and expect that 'October 19' means all times between 2017-10-19T04:00+00:00  and 2017-10-20T04:00+00:00 . So I could set my Airflow scheduler to run at "04:00" UTC each day, but then this breaks when daylight savings rolls around..

**Pull request closed without merging**
