### PR TITLE
Add Airflow logo to the README

### PR DESCRIPTION
**Pull request by kaxil**
Similar to Apache Superset, adding this repo to README so that Airflow repo shows up nicely with thumbnails on various Topics pages like https://github.com/topics/airflow

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by hussein-awala — APPROVED** [review]

**Comment by hussein-awala** [comment]
It didn't work; I will check the README files in the other repositories

**Comment by jscheffl** [comment]
The logo is not served from README :-(
You need to be repo admin, go to repo settings and there add a "Social preview" image.

**Comment by jscheffl** [comment]
I assume we _could_ set it manually but a follow-up weekend activity was to check if there is an option in `.asf.yaml` or maybe a feature needs to be added there to define it programatically.

**Comment by kaxil** [comment]
You are probably right, I experimented with another repo

**Comment by kaxil** [comment]
Yup found the Superset thing - [here](https://issues.apache.org/jira/browse/INFRA-20803?jql=text%20~%20%22social%20preview%22), we could request the same.

And we should make it self-serve via `.asf.yaml`

**Comment by kaxil** [comment]
Created this ticket - https://issues.apache.org/jira/browse/INFRA-25351 for now

**Comment by potiuk** [comment]
Yeah.. I'v already added a feature there - it's Python based so it's not a rocket science https://github.com/apache/infrastructure-p6/pull/1740. - we just need to check if there is an API in GitHub that we could use for that.

The only **small** problem with it that there are no tests for it .... so .... you have to **believe** it works 😱

**Comment by jscheffl** [comment]
> You are probably right, I experimented with another repo

@kaxil I was not fast enough with response... Yes I also tried with a temporary repo which was empty yesterday... from which I made the screenshot in Slack...
I was stuck in other weekend work, such I was not able to check `asf.yaml`or propose a feature - but if nobody else is faster, I still have it on my list the next days :-D

**Comment by jscheffl** [comment]
> Created this ticket - https://issues.apache.org/jira/browse/INFRA-25351 for now

Oh, they already added it - that was FAST. Problem solved for now :-D

**Comment by potiuk** [comment]
The image though is probably not perfect (refreshed preview in LinkedIn - Facebook is similar).

Screenshot 2024-01-07 at 18 22 37

**Comment by jscheffl** [comment]
> The image though is probably not perfect (refreshed preview in LinkedIn - Facebook is similar).

In the github docs (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) they propose a resolution of 1280 by 640 pixels. Currently we have transparent background but in dark mode it looks a bit strange. Quote:
```
   When using an image with transparency, keep in mind how it may look on different color backgrounds or platforms that don't support transparency.
   Tip: If you aren't sure, we recommend using an image with a solid background.
```
Github also provides a template and they recommend having 40 pixels border around the content:
image

Shall we request another update? Is it helpful if I stitch a new logo image? Or anybody better in Gimp?
Mhm, before too much of discussion, here my non-transparent Gimp attempt:
image

**Comment by kaxil** [comment]
We have more logos at https://github.com/apache/airflow/tree/main/docs/apache-airflow/img/logos

If you'd like to take a stab, go for it @jscheffl . If not, I can ask one of our Frontend or designer folks at Astronomer to help out

**Pull request merged**
