### PR TITLE
Local Executor is used by default for MySQL/Postgres breeze

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
https://github.com/apache/airflow/pull/11791#discussion_r511063082

**Review by kaxil — APPROVED** [review]

**Review by mik-laj — APPROVED** [review]

**Comment by kaxil** [comment]
What do we think about https://github.com/apache/airflow/pull/11791 :) after the Slack chat and since the bug is now fixed too -- PR merged that fixes the bug

**Comment by potiuk** [comment]
I think it's still worth merging now and we should go ahead and fal sequential for MySQL/Postgres (see devlist)

**Comment by potiuk** [comment]
Merging now - I think it is no harm to use Local Executor by default for postgres/mysql. I think the question whether we "fail hard" airflow with Postgres/MySQL SequentialExecutor or remove Sequential altogether is another story.

**Pull request merged**
