### PR TITLE
Increase length of user identifier columns in `ab_user` and `ab_register_user` tables

### PR DESCRIPTION
**Pull request by swalkowski**
To better open Airflow RBAC to external integrations (see below), this change increases the maximum lengths of user identifies columns in `ab_user` and `ab_register_user` tables:
- `first_name` and `last_name` from 64 to 256 characters.
- `email` and `username` from 256 to 512 characters.
 
While Airflow RBAC model is represented in the fixed set of Flask App Builder `ab_*` tables, it can be integrated with a variety of authentication mechanisms. They may operate on various forms of user identifiers that can be of various lengths. For example:
- Display names like first and last name may not always be available, and some integrations may opt for defaulting those columns to the other identifiers, like username or email, which can be longer.
- Identity federation is a scenario in which user identifiers can be particularly long, like this one from Google Cloud workload identity federation: `principal://iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/subject/SUBJECT_ATTRIBUTE_VALUE`.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM. I do not see any fundamental problems witht it, however I think it would be worthwile to submit simiilar change upstream to FAB.

What others think?

**Review by Taragolis — APPROVED** [review]
I think this tables usual very small so even if we take into account that this required obtain exclusive lock it should not have any other side effect

**Comment by Taragolis** [comment]
Not particular to this PR rather than our DB structure. I wondering is it possible to replace VARCAR(n) to TEXT in case of PostgreSQL with less effort?

I think the nature of all limitations on string usual:
- DB doesn't supported "unlimited" strings.
- It has performance degradation against varying character types.

**Comment by potiuk** [comment]
> Not particular to this PR rather than our DB structure. I wondering is it possible to replace VARCAR(n) to TEXT in case of PostgreSQL with less effort?
> 
> I think the nature of all limitations on string usual:
> 
> * DB doesn't supported "unlimited" strings.
> * It has performance degradation against varying character types.

Id you can make sure cross-compatibility and easy maintenance of multiple DB changes. I doubt we ever drop MySQL (even if I'd love it). MsSQL might be easier due to its experimentao status.

**Comment by Taragolis** [comment]
I don't mean drop support of any DB, more like [with_variant](https://docs.sqlalchemy.org/en/14/core/type_api.html#sqlalchemy.types.TypeEngine.with_variant) but need to find more generic way, some specific TYPE if dialect postgres/sqlite then TEXT отhervise VARCHAR(n).

Anyway, it is not for now, just nice to have in the future:
- TEXT or DOMAIN based on TEXT
- JSONB instead of JSON for Postgres

**Pull request merged**
