### PR TITLE
Remove pylint filtering

### PR DESCRIPTION
**Pull request by potiuk**
This is a final step of implementing Pylint compatibility,
following AIP-6 vote from 11th of April 2019.

It took 1.5 years and 172 commits.

https://lists.apache.org/thread.html/f4940d36e98ded96a2473bb2ccdfa4cc648faa2c1334b2aa901c0bba%40%3Cdev.airflow.apache.org%3E

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Not yet there - we still need to get the DagRun + Dag, but it is awfully close.

**Comment by kaxil** [comment]
<3 --- finally

**Comment by potiuk** [comment]
Next:  Black + Type annotations for the core :)

**Comment by coopergillan** [comment]
Black as in the `black` library? Interesting!

**Pull request closed without merging**
