### PR TITLE
[AIRFLOW-4361] Fix flaky test_integration_run_dag_with_scheduler_failure

### PR DESCRIPTION
**Pull request by milton0825**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4361

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Add retries so that tests will not fail because of intermittent failure. 

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Fixing tests...

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by potiuk** [comment]
Whoa - I hope this might help with one of the biggest pain points we have in Travis now. Does not look like it solves the root cause but maybe it's "good enough" :). I'd love to see the effect of it after it is merged - maybe you can try to compare before/after stability after we merge it :)

**Review by potiuk — APPROVED** [review]
Looks great. Let's see if it works (I cross my fingers). Can you please squash those two commits before we merge it?

**Comment by milton0825** [comment]
I hope it helps lol

**Comment by OmerJog** [comment]
@potiuk you'll need to close the ticket and target it to 1.10.4 :)

**Comment by potiuk** [comment]
Unfortunately :(  seems that it does not help https://api.travis-ci.org/v3/job/522931912/log.txt

**Comment by zhongjiajie** [comment]
Seems still will failed random.

**Pull request merged**
