### PR TITLE
[AIRFLOW-6068] Make args of KubernetesPodOperator to get dict type

### PR DESCRIPTION
**Pull request by tyg03485**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6068

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by davlum** [comment]
Hi, it's not clear from the Jira ticket what feature or problem this is solving. Could you elaborate on this? The change you are making would be a breaking change for all users of this operator. The reason those classes exist is for backwards compatibility. In general, it is preferred to use the models from `kubernetes.client.models` instead of Airflow's custom Kubernetes models.

**Comment by tyg03485** [comment]
Hi @davlum 
I thought there are some awkward point in args of KubernetesPodOperator.
There are classes we optionally use for KubernetesPodOperator.
Port, Volume, VolumeMount, Secret, PodRuntimeInfoEnv, Resources.
But only Resource passed by `dict` type.
In my exp of 1.10.4, i was confused what args passed should be dict or class type
 
So, there are two way to unify of them.
1. Resource could be changed Resource Type
```
def __init__(self, ..., resources: Optional[Resources] = None ...)
```
But, from using KubernetesPodOperator, we need to import all using class.

2. Others args could be passed by `dict` Type.
like my PR.


But as you say, if `kubernetes.client.models` is better, we could extract only `attach_to_pod` method previous class based `K8SModel`. (e.g. `PodRuntimeInfoEnv` -> `V1EnvVar`). And just pass them all instance of kubernetes.client.models

**Comment by davlum** [comment]
I'm definitely in agreement that a more unified way of creating the pod would be ideal. In my mind the ideal would be to have [users pass the full pod spec](https://github.com/apache/airflow/blob/5b8635e8f72b84d4ae8e87c36b528980079c6598/airflow/contrib/operators/kubernetes_pod_operator.py#L166) and then we could get rid of all the additional arguments. Even though the operator is in the `contrib` section, many users rely on it being in it's current state it is very hard to justify changes like this.

**Comment by tyg03485** [comment]
yeah.. I agree that..
I wish all user would replace it to full pod spec instead additional args.
Thanks to Response on my PR.

[Close]

**Pull request closed without merging**
