### PR TITLE
Implements generation of separate constraints for core and providers

### PR DESCRIPTION
**Pull request by potiuk**
There are two types of constraints now:

* default constraints that contain all depenedncies of airflow,
  all the provider packages released at the time of the relese
  of that version, as well as all transitive dependencies. Following
  those constraints, you can be sure Airflow's installation is
  repeatable

* no-providers constraints - containing only the dependencies needed
  for core airflow installation. This allows to install/upgrade
  airflow without also forcing the provider's to be installed at
  specific version of Airflow.

This allows for flexible management of Airflow and Provider
packages separately. Documentation about it has been added.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
As discussed - we have now two versions of constraints and documentation on how to manage upgrades for providers and airflow separately. Also the "full" constraint files contain now the versions of providers released - for master those are the "latest" versions - from pypi, for previous versions of airflow, those will be versions of provider packages released at the time of preparation of that version, which will solve the problem we have with google backwards incompatible 2.0.0 provider that cannot be repeatably and easily installed via extras. I will update the constraints for 2.0.0 and 2.0.1 accordingly.

**Comment by potiuk** [comment]
I also updated the "packages and extras" reference doc to make even clearer distinction between providers and non-providers extras. The "core" extras have now a separate section, and provider extras separate one.

There are two packages that sit in both though:

* celery
* cncf.kubernetes

Those are needed for celery/kubernetes executor, but they also have their providers. I added a comment about it however and I think it is rather clear now what  is the difference. 

Note!  The `non-providers` constraints contain dependencies from all "core" extras (including cncf.kubernetes and celery) which I think makes perfect sense.

**Comment by potiuk** [comment]
One more thing I added - I also changed the 'providers' extra dependencies to not include the transitive dependencies - the extra will only have the 'apache-airflow-provider-EXTRA' dependency - and then the provider will provide the transitive dependency.

I think that was an overlook from my side that those dependencies were there in 2.0.0 and 2.0.1 -> this transitive way is much more 'future-proof' :).

**Comment by potiuk** [comment]
FYI @kaxil @ash - I already regenerated and tested good set of constraints following those changes (including non-providers constraints as well as adding apache-airflow-providers to the constraint files and it looks like it works well.

See the two last commits in https://github.com/apache/airflow/tree/constraints-2-0

**Comment by ashb** [comment]
> FYI @kaxil @ash - I already regenerated and tested good set of constraints following those changes (including non-providers constraints as well as adding apache-airflow-providers to the constraint files and it looks like it works well.
> 
> See the two last commits in https://github.com/apache/airflow/tree/constraints-2-0

That broke image builds. https://github.com/apache/airflow/runs/1904107297?check_suite_focus=true


```
ERROR: Could not satisfy constraints for 'apache-airflow-providers-amazon': installation from path or url cannot be constrained to a version
```

@potiuk We shouldn't be touching those files manually ever ideally.

**Comment by ashb** [comment]
I have reverted that constraint-master commit to un-break master :- https://github.com/apache/airflow/commit/f5406cc8789aeea8c98d1721272a9bab7ad1b956

**Comment by potiuk** [comment]
> @potiuk We shouldn't be touching those files manually ever ideally (especially not based on an un-reviewed PR.)

They were automatically generated, not manually generated (I did some manual tweaks with 2.0.1 and 2.0.0 versions but not in the master build). I will have to see why this failed, but it's not because it was manually generated. If anything - and those constraints were consistent and 'pip checkable' - I will have to see why this particular build failed but it's pretty surprising that it did (the sphinx one was not because it was pushed without running the full suite of tests due to master previously broken).

**Comment by potiuk** [comment]
And I actually run a full image build for PROD and CI yesterday with all the constraints from the scratch and it worked (I used the opportunity to refresh base python images used), so it is doubly-surprising it failed in this case. Also what is doubly surprising that the builds looks like is run  "afresh" - it does not make use of the cache whatsoever it seems but it should. For some reason it does not,  so this is really strange, I guess some way the environment prepared on self-hosted runner. 

I will take a look in the evening what's wrong there.

**Comment by ashb** [comment]
Oh hmm, sorry. I assumed that you did https://github.com/apache/airflow/commit/79ed11f9147483c4b2f6cc99d5a3e41e89d92968 manually.

**Comment by potiuk** [comment]
> Oh hmm, sorry. I assumed that you did [79ed11f](https://github.com/apache/airflow/commit/79ed11f9147483c4b2f6cc99d5a3e41e89d92968) manually.

@ashb  I think what *might* be the reason - the build assumes that the docker engine is unpopulated when it starts (we have the `docker system prune --all` as the prerequisite step - which was there for a good reason - one of them was that it always pulled latest versions of python images before the build. Removing the "cleanup" step might have changed the behaviour and some of the pre-populated images (notably python one) might be causing different behaviour (for example last week keys expired in old python images and they were re-populated by python team).  Not sure yet if that is the case but this might be the reason why cache is not actually used during the build (It will not be used if your local python version is different than the one used to build the base image).

**Comment by potiuk** [comment]
I Implemented a protection some time ago for it (we also store in github regitstry the exact python image that was used as the base for our cache and I thought I always pull it during the build process to make sure the same version is used. But maybe it is somewhat missing in this step (missing variable or smth). I will take a look at this in the evening and try to sort it out and push the right version (automatically generated) of constratints and see at the last builds to see if cache is properly used on self-hosted runners as well.

**Comment by potiuk** [comment]
I pushed it rebasing on top of the `sphinx`  limits fix, I hope it will get green this time and we can update the master constraints properly this time - after merging it. Please take a look @ashb @kaxil, I think it will solve a number of problems due to "master not failing" problem as it solves also some limits that are needed for "eager-update" case.

**Review by ashb — COMMENTED** [review]
What constraints file is the production build using? If it's still using the full file, then building the prod image will fail with this error:

> ERROR: Could not satisfy constraints for 'apache-airflow-providers-amazon': installation from path or url cannot be constrained to a version

**Comment by potiuk** [comment]
> What constraints file is the production build using? If it's still using the full file, then building the prod image will fail with this error

Yes that was the root cause of the problem - that the build file was using constraint in one of the scripts where it also installed the provider from locally prepared packages, I think this was the root cause of the problem and I have to simply fix the scripts to not do it when the constraints including providers will be used. I have to just test it in my fork. Just looking at fixing the docs build (still there)  and making sure that the build process will work after pulling constraints from my own fork.

**Comment by potiuk** [comment]
Hey @ashb  @kaxil - I fixed all the problem:

The build generally (except occasional mysql error) - succeeded as master build: 
Image build: https://github.com/potiuk/airflow/actions/runs/572616215
CI Build: https://github.com/potiuk/airflow/actions/runs/572616144

I also hope it is going to succeed now here as well as PR:

The change to constraints in master are here : https://github.com/potiuk/airflow/commit/8721c58efc1ecf0772405c4093094cd5cae44cfb

There are three types of constraints:

* constraints - the constraints including providers from PyPI
* constraints-source-providers - the constraints generated for latest sources (needed by CI when new providers or added but not yet released or when dependencies changed for providers) 
* constraints-no-providers - just "core" dependencies.

I'd love to merge this quickly and cherry-pick to 2.0 so that 2.0.2 constraints can be fully generated automatically.

**Comment by potiuk** [comment]
All green now - I'd love to merge it to get constraints covering all cases:

* installing airflow with extras/providers from pypi (constraints-PYTHON_VERSION.txt) - for users
* installling base airflow without providers, with basic extras only - ( constraints-no-providers-PYTHON_VERSION.txt) - for users
* installing airflow with 'source version" of providers (constraints-source-providers-PYTHON_VERSION.txt) - for CI builds

**Review by kaxil — APPROVED** [review]

**Pull request merged**
