### PR TITLE
Company inthewild

### PR DESCRIPTION
**Pull request by venkat-oss**
Removed Company name because company is not a direct user.
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by potiuk — CHANGES_REQUESTED** [review]
Anything changed here :) ? (except 2 spaces :))

**Comment by potiuk** [comment]
Or should we just close it ?

**Comment by di1eep** [comment]
I had actually removed a line. You can go ahead and close it.

**Comment by di1eep** [comment]
Sorry for the late reply. Github somehow didn't show your earlier comments. Thanks :)

**Comment by potiuk** [comment]
no problem :)

**Pull request closed without merging**
