### PR TITLE
[AIRFLOW-1843] Add Google Cloud Storage Sensor with prefix

### PR DESCRIPTION
**Pull request by unlitdev**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1843

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Sensor for checking if there any files in bucket at certain prefix

### Tests
- [x] My PR does not need testing for this extremely good reason:
Google doesn't provide local unittest for GCS.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by wileeam** [comment]
LGTM

And very much appreciated!
I have been neglecting writing this one in favor of reusing a ShortCircuit operator with a custom function retrieving the list of files.
This should make many DAGs cleaner and easier to read :)

**Comment by criccomini** [comment]
@litdeviant can you check the test failures?

**Comment by unlitdev** [comment]
@criccomini I did check them. My changes doesn't add or remove tests. take a look at https://travis-ci.org/litdeviant/incubator-airflow/builds/306248732 same build on my fork and everything pass. it's non determenistic bug with tornado futures and network connection doesn't relate to my changes.

**Comment by criccomini** [comment]
LGTM merged

Ignoring test failure since it's spurious

**Pull request closed without merging**
