### PR TITLE
Do not publish schedule_delay metrics if run_type is 'backfill'

### PR DESCRIPTION
**Pull request by huymq1710**
The `schedule_delay` metric is crucial for defining SLOs, but it often includes noise from backfill DagRuns.

This PR aims to exclude backfill DagRuns from the `schedule_delay` metrics to enhance data accuracy.

image

### CODE REVIEW

**Comment by huymq1710** [comment]
@uranusjr 
Coud you check this

**Comment by uranusjr** [comment]
p.s. Changing the title; the original implies we’re adding this metric. In reality the metric already exists, and this removes its emission in backfills.

> it often includes noise from backfill DagRuns

Would you mind elaborating on this? Some real cases would be helpful.

**Comment by huymq1710** [comment]
> The `schedule_delay` value is the time diff between start_date of a DagRun (the time it is started) and the data_interval_end (the time it is expected to run)
https://github.com/apache/airflow/blob/2.9.1/airflow/jobs/scheduler_job_runner.py#L1358-L1359

image

- Normal DagRuns should have a delay less than 5 mins
- We are setting our delay SLO to 10 mins
- When a schedule delay value exceeds 30 mins threshold, it is considered noisy data, and it is very likely that the data is generated by a backfill DagRun. In this case, we need to check manually

**Review by boushphong — APPROVED** [review]

**Comment by huymq1710** [comment]
@uranusjr
Coud you check this 🙇🏼

**Pull request closed without merging**
