### PR TITLE
Fix wrong casing in airbyte hook.

### LINKED ISSUE #42154: Airbyte API 0.52.0 breaks provider tests
### Apache Airflow Provider(s)

airbyte

### Versions of Apache Airflow Providers

main

### Apache Airflow version

main

### Operating System

Linux

### Deployment

Virtualenv installation

### Deployment details

Breeze tests

### What happened

Tests on main as well as PRs re-testing airbyte provider fail in pytests with:

```
(...)
airflow/providers/airbyte/hooks/airbyte.py:56: in __init__
    self.airbyte_api = self.create_api_session()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <airflow.providers.airbyte.hooks.airbyte.AirbyteHook object at 0x7f1847b62060>

    def create_api_session(self) -> AirbyteAPI:
        """Create Airbyte API session."""
>       credentials = SchemeClientCredentials(
            client_id=self.conn["client_id"],
            client_secret=self.conn["client_secret"],
            TOKEN_URL=self.conn["token_url"],
        )
E       TypeError: SchemeClientCredentials.__init__() got an unexpected keyword argument 'TOKEN_URL'

airflow/providers/airbyte/hooks/airbyte.py:71: TypeError
```

...if provider yaml in airflow/providers/airbyte/provider.yaml since airbyte-api 0.52.0 was released.

### What you think should happen instead

_No response_

### How to reproduce

run `breeze testing tests --test-type '[Providers[airbyte]'`

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
Fixes: #42154

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @marcosmarxm

**Review by jscheffl — APPROVED** [review]
That was a easy fix :-D Did not went this step but would have saved a CI run fixing it immediately :-D

**Comment by potiuk** [comment]
BTW. For the future @jscheffl  - it's best to avoid "==" pinning in our deps. It would likely be better to add `!=0.52.0` in the first PR (I will explain - using this example - on Friday).

**Comment by potiuk** [comment]
Passed the airbyte tests - merging..

**Comment by marcosmarxm** [comment]
I'm in contact with the team is responsible with the `airbyte-sdk` library. It shouldn't be changed but anyway. I'm going to keep an eye on it. Thanks a lot @potiuk and @jscheffl for the quick fix.

**Pull request merged**
