### PR TITLE
Revert "Fix `GCSToGCSOperator` behavior difference for moving single object (#40162)"

### PR DESCRIPTION
**Pull request by MaksYermak**
This reverts commit 2f2796f675e238e0b266b8d6e4fdfe5c0b7d1bf3.
These changes broke the `GCSToGCS` operator and, also, operators which rely on this operator. The most use case after these changes do not work.
For example in one of our system tests for video intelligence operator we have this operation for GCSToGCS:
```
src_Bucket=B1, src_file=video/cat.mp4
to dst_Bucket=B2, dst_file=video.mp4
```
and now the result of this operation is `B2/video.mp/cat.mp4`, but the expected result should be `B2/video.mp4`.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by MaksYermak** [comment]
@eladkal FYI

**Review by moiseenkov — APPROVED** [review]

**Comment by ahidalgob** [comment]
Should we add special release notes? (the original PR had)

**Comment by ahidalgob** [comment]
For more context, examples in the [documentation](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/_api/airflow/providers/google/cloud/transfers/gcs_to_gcs/index.html) and some system tests where the destination file is specified fully are broken before this revert.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Should we add special release notes? (the original PR had)

Yeah. I added this PR https://github.com/apache/airflow/pull/40579 and we shall discuss the note there (and agree on the version)

**Pull request merged**
