### PR TITLE
doc: providers github link

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Review by romsharon98 — APPROVED** [review]

**Comment by raphaelauv** [comment]
@romsharon98 let's add this to the `apache:v2-10-test` ?

**Comment by romsharon98** [comment]
I don't think it should be add to `apache:v2-10-test` because it does not have this hierarchy

**Comment by raphaelauv** [comment]
the current like is dead in the documentation , so we need to fix it ( otherwise it will be dead until release of airflow 3 )

**Comment by romsharon98** [comment]
Oh my mistake! I will create a PR for backporting it

**Pull request merged**
