### PR TITLE
[AIRFLOW-2662] add k8sexecutor worker pod node_selectors and affinity…

### PR DESCRIPTION
**Pull request by Cplo**
… fields

Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2662

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
In this issue(https://issues.apache.org/jira/browse/AIRFLOW-2397, pr url: https://github.com/apache/incubator-airflow/pull/3369), only the affinity function of the kubernetes operator pod is provided, and the affinity function of the kubernetes executor pod is not supported. The full affinity and nodeselector function are provided here.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Review by Fokko — COMMENTED** [review]
Can we add soms tests?

**Comment by Cplo** [comment]
@Fokko PTAL

**Review by Fokko — APPROVED** [review]
Tests are minimal, but good enough for now.

**Comment by Fokko** [comment]
I've reworked the git commit message this time, please adhere to the guidelines. Otherwise this will mess up our git logs.

**Pull request closed without merging**
