### PR TITLE
[AIRFLOW-3376] Upgrade tenacity to 5.0.2

### PR DESCRIPTION
**Pull request by villasv**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3376

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Just a version bump, no relevant changes. Required for python 3.7 compatibility.

### Tests

- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Nothing should change.

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `flake8`

### CODE REVIEW

**Comment by villasv** [comment]
This seems a naive duplicate of https://github.com/apache/incubator-airflow/pull/3723

But I did some testing and I didn't observe that error.

**Comment by villasv** [comment]
Hmmm so the tests failed for 3 of the Py27 (docker) environments but passed for one (k8s) of them... ?

Not sure how to interpret this.

**Comment by villasv** [comment]
Hmm. I think I'll give up on this PR and just force update `tenacity` on my py37 environment, though I'll leave the JIRA issue open.

**Comment by Fokko** [comment]
@villasv The K8s tests only executes a simple dag. This dag might not contain an operator that uses Tenacity. This is exactly the reason why we have the different test suites :-)

**Pull request closed without merging**
