### PR TITLE
Add recipes for installing a few common tools in Docker image

### PR DESCRIPTION
**Pull request by mik-laj**
hello,

Some developers ask how to install additional tools in the image. I have prepared instructions for a few common tools. These tools are required by some operators, but due to image size optimization, they are not included in the default installation.

Best regards,
Kamil Breguła

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by feluelle — COMMENTED** [review]
TBH I would not put this inside the airflow repo. We can have a separate repo imo.
Do you think this will be kept "up-to-date"?

Please let me know what you think.

**Comment by mik-laj** [comment]
@feluelle I would like it to be in one place along with the documentation for Docker image.  It's not a complicated code, so I don't think there are any problems with maintaining it. These are code snippets from several images that we use in production at Polidea. These tools are often required by various Airflow operators, so we should describe how to install these additional optional components in the image as this is not always obvious.

As for a separate repository, we agreed in the community that we would maintain a monorepo.  I was wondering if this should be in the documentation for `apache-airflow`, but we don't have separate documentation for the Docker image yet. For now, this is the only place that has end-user documentation for docker image. In the future, we can create a new documentation package, but it is an extra effort.  This may be a done as part of  https://github.com/apache/airflow/issues/11740 , where we will have to do some work on better documentation for the image.

Other projects that have separate documentation about Docker have such sections in the documentation.
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html

**Comment by potiuk** [comment]
> Please let me know what you think.

I think it's  good idea to add it. This is mostly documentation. however I'd add a test to build those images in CI. This way we will be sure it is up-to date. @mik-laj WDYT?

**Comment by mik-laj** [comment]
@potiuk we have a bit overloaded with our CI system, so I don't think that adding more types of tests will be a good idea, especially since building an image is not too light operation and is also crucial for the viability of our project. What do you think I'd have created a separate ticket and added these tests in the future when our CI would be a little more stable? I don't think those images would get damaged during this time. Not many people will contribute to these files, and on the other hand, external services, if they have problems with stability, will not affect our CI.

**Comment by feluelle** [comment]
@mik-laj SGTM 👍 

@potiuk I agree with Kamil, I think adding it now wouldn't help our CI :D Let's really wait for the CI to be more stable.

**Comment by potiuk** [comment]
> @potiuk I agree with Kamil, I think adding it now wouldn't help our CI :D Let's really wait for the CI to be more stable.

Agree. Hopefully soon! :crossed_fingers:

**Review by feluelle — APPROVED** [review]
LGTM

**Review by potiuk — APPROVED** [review]

**Comment by JavierLopezT** [comment]
Do you think would be a good idea to have also docker-compose-recipes doc?

**Comment by potiuk** [comment]
> Do you think would be a good idea to have also docker-compose-recipes doc?

@mik-laj works on a whole eeasy-to-generate docker-compose example to become part of the repo https://github.com/apache/airflow/issues/8605#issuecomment-759469443

All comments are welcome :)

**Pull request merged**
