### PR TITLE
Add Microsoft PSRP provider

### PR DESCRIPTION
**Pull request by malthe**
This is a Microsoft PSRP (Powershell Remoting Protocol) provider – a protocol that expands on WinRM to better match the way Powershell works.

Under the hood it uses the https://pypi.org/project/pypsrp/ library (MIT License).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
LGTM

**Comment by potiuk** [comment]
I think rebasing to latest main would be good.

**Comment by malthe** [comment]
@potiuk done

**Comment by potiuk** [comment]
Few intermittent issues but it looks good :)

**Comment by potiuk** [comment]
Cool contribution @malthe !

**Pull request merged**
