### PR TITLE
Fix DST transition in ExternalTaskSensor when using execution_delta

### PR DESCRIPTION
**Pull request by pankajkoti**
The ExternalTaskSensor works fine for both DST and non-DST 
when no execution_delta is used. But, when execution_delta is 
used, on DST switch days, the new child DAG/task runs as per the 
switched time but the parent DAG cannot match the child DAGs for 
the execution_delta DAGs runs that have run in the old time before 
the DST switch and it just hangs forever. We handle this care here 
by calculating the change for the DST switch in case of execution_delta 
and when the DAG has a non-UTC timezone.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by pankajkoti** [comment]
cc: @hkc-8010

**Comment by uranusjr** [comment]
Needing to convert to UTC and back for DST just doesn’t _sound_ right.

**Comment by hkc-8010** [comment]
@pankajkoti - I tested the logic for the below dates with the `timezone` as `pendulum.timezone("Pacific/Auckland")` and `execution_delta=timedelta(hours=24)` and the logic for the DST transition is working as expected.

```
dt1 = datetime(2022, 9, 25, 11, 0, 0)
dt2 =datetime(2023, 4, 1, 14, 0, 0)
dt3 = datetime(2023, 1, 1, 15, 0, 0)
dt4 = datetime(2022, 8, 1, 15, 0, 0)
dt5 = datetime(2023, 4, 2, 3, 0, 0)
```

**Comment by uranusjr** [comment]
I know what the problem here, but from a logical point of view, it just doesn’t make sense for the fix to be converting UTC and then back.

**Comment by pankajkoti** [comment]
> I know what the problem here, but from a logical point of view, it just doesn’t make sense for the fix to be converting UTC and then back.

yes, the problem is due to the execution_delta param with the DST switch.

**Pull request closed without merging**
