### PR TITLE
[AIRFLOW-5769] Move the S3_hook to /providers/aws/hooks

### PR DESCRIPTION
**Pull request by mingrammer**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5769
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

Of course, this update will lead to the API breaking change. Therefore, all codes using `S3_hook` should change the import module names when this PR is merged.

So if you agree with this change, it would be better to include these updates in Airflow 2.0 rather than 1.x because it is kind of specification change.

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you keep backwards compatibility and add missing tests?

**Comment by mingrammer** [comment]
Right now, I have no ideas for keeping backward compatibility with Python's case-sensitive nature.

**Comment by mik-laj** [comment]
Will this not work?
https://github.com/apache/airflow/blob/master/airflow/contrib/operators/bigquery_to_gcs.py

**Comment by mingrammer** [comment]
Ah! that is a good idea. I couldn't think about it. Thank you for help.

**Comment by mik-laj** [comment]
You should also add a note in the UPDATING.MD file

**Comment by mingrammer** [comment]
Ok. I'll do that. Thank you for guiding me 👍

**Comment by mingrammer** [comment]
@mik-laj I encountered a problem.

Some file systems (including macOS's default one) are case-insensitive, so we can't have both `s3_hook.py` and `S3_hook.py` simultaneously in those fs.

So we should use another filename to separate that both. How do you think about that move the `s3_hook.py` to `contrib/hooks` like other AWS hooks (i.e. `aws_athena_hook`, `aws_lambda_hook` etc) named as `aws_s3_hook.py` (and change the class name to `class AWSS3Hook`)?

And they (aws-*-hooks) look similar to each other.

```python
class AWSAthenaHook(AwsHook):
    """
    Interact with AWS Athena to run, poll queries and return query results

    :param aws_conn_id: aws connection to use.
    :type aws_conn_id: str
    :param sleep_time: Time to wait between two consecutive call to check query status on athena
    :type sleep_time: int
    """

    INTERMEDIATE_STATES = ('QUEUED', 'RUNNING',)
    FAILURE_STATES = ('FAILED', 'CANCELLED',)
    SUCCESS_STATES = ('SUCCEEDED',)
...
```

```python
class S3Hook(AwsHook):
    """
    Interact with AWS S3, using the boto3 library.
    """

    def get_conn(self):
        return self.get_client_type('s3')
```

**Comment by mik-laj** [comment]
We want to move this hook to a completely different package.
More information:
https://github.com/apache/airflow/pull/6439
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths
https://lists.apache.org/thread.html/d8c1a72113fc01088d77a4f6d33371e465d20f7aa0d16232d8f93559@%3Cdev.airflow.apache.org%3E

Please note that a change of class name should be done in a separate PR.

**Comment by mingrammer** [comment]
Well, I will follow the mentioned conventions. (/providers/hooks/~.py)

Yap. I’ll update this PR and send an additional PR for class name.

**Comment by mingrammer** [comment]
I'll update the `UPDATING.md` and other docs when https://github.com/apache/airflow/pull/6446 is merged to avoid conflict and inconsistency.

(based on https://github.com/apache/airflow/pull/6446/files#diff-bb7ee25332d5fdca3ead2f545d72b359)

**Comment by mingrammer** [comment]
I updated the `UPDATING.md` and other reference file.

**Comment by mingrammer** [comment]
And, Should I change the all import paths with new module path in the other files including test files? (in separate PR)

**Comment by mingrammer** [comment]
@mik-laj Please check it

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
> And, Should I change the all import paths with new module path in the other files including test files? (in separate PR)

Oh. I didn't notice your question. Yes. Other references to this class should be improved.

**Comment by mingrammer** [comment]
Ok. I'll send a PR for that!

**Pull request merged**
