### PR TITLE
Enable Black on Providers Packages

### PR DESCRIPTION
**Pull request by kaxil**
This is part of #9550 but only applies Black formatting to providers packages as they are not included in v1-10-test so the problem for cherry-picking them does not arises.

If there are any open PR, they just need to run pre-commit and everything would be taken care off

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Great idea to enable black on Providers first!

**Review by turbaszek — APPROVED** [review]
Awesome! Should we apply black on `tests/providers`?

**Comment by kaxil** [comment]
> Awesome! Should we apply black on `tests/providers`?

Yup already applied

**Comment by turbaszek** [comment]
> Yup already applied

Good! There is too much file to be able to load it all in Github 😄

**Review by ad-m — APPROVED** [review]

**Comment by sztamas** [comment]
Hi @kaxil 

Could you please also update the `isort` section in `setup.cfg` to ignore the `providers` and `api_connexion` the same way you ignore them in the pre-commit hook?

A `skip_glob=*/api_connexion/**/*.py,*/providers/**/*.py` should work.

Thanks,

Tamas

**Comment by kaxil** [comment]
> Hi @kaxil
> 
> Could you please also update the `isort` section in `setup.cfg` to ignore the `providers` and `api_connexion` the same way you ignore them in the pre-commit hook?
> 
> A `skip_glob=*/api_connexion/**/*.py,*/providers/**/*.py` should work.
> 
> Thanks,
> 
> Tamas

I have done that here https://github.com/apache/airflow/blob/master/.pre-commit-config.yaml#L190-L194. :)

**Comment by sztamas** [comment]
Thanks for the fast response! :+1:

**Comment by turbaszek** [comment]
Should we configure isort to be compatible with black?
https://github.com/TobKed/short_my_url_baby/blob/85d07e5ceffd568f7f5506983cd58658d24d29f9/.pre-commit-config.yaml#L6-L9

**Comment by kaxil** [comment]
It is even simpler by adding "black" profile to isort which is in https://github.com/apache/airflow/pull/9550 which applies black to entire airflow repo. Waiting till we are close to 2.0 and then do a big bang so we don't need to cherrypick anymore and can pause the PRs for that time

**Pull request merged**
