### PR TITLE
Remove MSSQL support form Airflow core

### PR DESCRIPTION
**Pull request by jscheffl**
This is a follow-up and split form original PR #35868 and just removes all MSSQL support from Airflow Core (w/o breeze, migrations).

As discussed and voted in https://lists.apache.org/thread/pgcgmhf6560k8jbsmz8nlyoxosvltph2

It does NOT remove the provider package, so no misunderstanding: Apache Airflow further will "work" with MSSQL and the provider package and features are not touched. All Operators keep in place. Just the metadata support is reduced to sqlite (dev only), Postgres, MySQL.
Note that for this also the build of MSSQL client code is kept inside the Docker as Provider packages rely on this availability.

### CODE REVIEW

**Comment by jscheffl** [comment]
[ ] Double check that with the removal of mssql also in CI do we have a whole in the text matrix of Python/DB editions?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
🤞

**Review by dirrao — APPROVED** [review]

**Review by Taragolis — APPROVED** [review]
Looks good.

I think we should also remove some hacks or mssql conditions from the `alembic` migrations scripts, but it could be done as follow up if we think that might bring a bit more pain if we tried to do it in one go.

**Comment by jscheffl** [comment]
> I think we should also remove some hacks or mssql conditions from the `alembic` migrations scripts, but it could be done as follow up if we think that might bring a bit more pain if we tried to do it in one go.

@Taragolis I initially cleaned migration scripts in #35868 but in the PR there was a lot of debate about how to further support legacy migrations. So I separated this out. Might be a future PR. Do you have any specific thing in mind? Maybe we can also just clean these "hacks" and leave the rest of the migrations just untouched.

**Pull request merged**
