### PR TITLE
Automate exclusion of providers in lowest-dependency tests

### PR DESCRIPTION
**Pull request by potiuk**
The "lowest" dependency tests had "hard-coded" exclusion for those providers that were excluded in specific python versions.

This change automates it:

* selective checks produce dictionary python -> excluded versions
* the dictionary (as string) is passed to unit tests in actions
* the dictionary (as string) is passed to breeze container as EXCLUDED_PROVIDERS variable
* "is_provider_excluded.py" checks if the provider is excluded and exits with success if so

Related: #41555

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
That one should also speed up "lowest dependencies" test in main - because we - erroneously excluded `papermill` from Python 3.12 (where Papermill had been added back a while ago) while we did not exclude apache.beam, so apache.beam tests actually (due to the way how the scripts work) would run ALL tests in a single thread.

**Comment by topherinternational** [comment]
I think the followup to #41967 I am writing will also address this problem.

**Comment by potiuk** [comment]
> I think the followup to #41967 I am writing will also address this problem.

We can compare and choose better one :)

**Review by eladkal — APPROVED** [review]

**Comment by topherinternational** [comment]
> > I think the followup to #41967 I am writing will also address this problem.
> 
> We can compare and choose better one :)

Or we can have defense in depth :D

**Pull request merged**
