### PR TITLE
[AIRFLOW-560] Add get_uri and get_sqlalchemy_connection to DbApiHook

### PR DESCRIPTION
**Pull request by gwax**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-560

Testing Done:
- Unit test added

### CODE REVIEW

**Comment by r39132** [comment]
@gwax Looks good. Please rebase and let me know once ready for merge. Also, follow the contributor guidelines... add a JIRA and prefix to your commit message.

**Comment by r39132** [comment]
@gwax ... also.. this is part of the "cold case" PR cleanup.. so any PRs that don't get updated in a timely manner will be closed.

**Comment by gwax** [comment]
This is an ancient PR. I'll try to find some time to update things, or I'll
reopen if it gets closed.

**Comment by r39132** [comment]
@gwax Your change looks pretty straight-forward. The rebase might be as well. Let me know how you want to proceed? I can wait till Monday..else I can close it if you don't need this change anymore.

**Comment by gwax** [comment]
@r39132 : I moved the code to DbApiHook because it only applies to sql databases (it's kind of silly to try to use it with something like s3). I have rebased and created a Jira issue.

**Comment by r39132** [comment]
Great! Thx.

**Comment by r39132** [comment]
+1

**Pull request closed without merging**
