### PR TITLE
Google have re-worked their docs site ane appear not publish objects.inv

### PR DESCRIPTION
**Pull request by ashb**
At least not on any URL I could guess at.

Removing this should un-break main.

### CODE REVIEW

**Comment by ashb** [comment]
Filed https://github.com/googleapis/google-cloud-python/issues/10814 upstream

**Review by Taragolis — APPROVED** [review]
I add locally additional simple validation for inventories (will create as follow up PR). 
The only two inventory related to google provider exists:
- `google-api-core`: https://googleapis.dev/python/google-api-core/latest/objects.inv
- `google-cloud-translate`: https://googleapis.dev/python/translation/latest/objects.inv

I'm not sure should we keep them or not

```console

#################### Fetching inventories ####################
To download 116 inventorie(s)
google-cloud-bigquery-datatransfer: Unexpected inventory header: <!doctype html>
google-cloud-automl: Unexpected inventory header: <!doctype html>
google-cloud-bigquery: Unexpected inventory header: <!doctype html>
google-cloud-bigtable: Unexpected inventory header: <!doctype html>
google-cloud-container: Unexpected inventory header: <!doctype html>
google-cloud-core: Unexpected inventory header: <!doctype html>
google-cloud-bigquery-storage: Unexpected inventory header: <!doctype html>
google-cloud-monitoring: Unexpected inventory header: <!doctype html>
google-cloud-datacatalog: Unexpected inventory header: <!doctype html>
google-cloud-kms: Unexpected inventory header: <!doctype html>
google-cloud-dlp: Unexpected inventory header: <!doctype html>
google-cloud-spanner: Unexpected inventory header: <!doctype html>
google-cloud-datastore: Unexpected inventory header: <!doctype html>
google-cloud-pubsub: Unexpected inventory header: <!doctype html>
google-cloud-language: Unexpected inventory header: <!doctype html>
google-cloud-redis: Unexpected inventory header: <!doctype html>
google-cloud-speech: Unexpected inventory header: <!doctype html>
google-cloud-storage: Unexpected inventory header: <!doctype html>
google-cloud-tasks: Unexpected inventory header: <!doctype html>
google-cloud-texttospeech: Unexpected inventory header: <!doctype html>
google-cloud-vision: Unexpected inventory header: <!doctype html>
google-cloud-videointelligence: Unexpected inventory header: <!doctype html>
Result: 94 success, 22 failed
Failed packages:
1. google-cloud-automl
2. google-cloud-bigquery
3. google-cloud-bigquery-datatransfer
4. google-cloud-bigquery-storage
5. google-cloud-bigtable
6. google-cloud-container
7. google-cloud-core
8. google-cloud-datacatalog
9. google-cloud-datastore
10. google-cloud-dlp
11. google-cloud-kms
12. google-cloud-language
13. google-cloud-monitoring
14. google-cloud-pubsub
15. google-cloud-redis
16. google-cloud-spanner
17. google-cloud-speech
18. google-cloud-storage
19. google-cloud-tasks
20. google-cloud-texttospeech
21. google-cloud-videointelligence
22. google-cloud-vision

```

**Comment by ashb** [comment]
Google are working on fixing this so we likely don't have to merge this PR

**Comment by potiuk** [comment]
It's almost fixed while we wait for Google - but we need to add spellcheck exclusions:

SynthesizeSpeechResponse
TransferRun
StartManualTransferRunsResponse
TransferConfig
ListDatasetsPager
ListTableSpecsPager
ListColumnSpecsPager

**Review by potiuk — APPROVED** [review]
Pending spellcheck adding. I think it will take a while for Google to bring the inventories back (even if they treat it as p1)

**Comment by potiuk** [comment]
> Google are working on fixing this so we likely don't have to merge this PR

I'd merge it anyway - we never know how long it will take them and whether it will be working at first try

**Comment by potiuk** [comment]
We can always simply revert it

**Comment by potiuk** [comment]
Merge it - it was green.

**Pull request merged**
