### PR TITLE
Delete old Spark Application in SparkKubernetesOperator

### LINKED ISSUE #16290: Allow deleting existing spark application before creating new one via SparkKubernetesOperator in Kubernetes
airflow version: v2.0.2
 
**Description**
calling SparkKubernetesOperator within DAG should delete spark application if such already exists before submitting a new one.

**Use case / motivation**

```
t1 = SparkKubernetesOperator(
    task_id='spark_pi_submit',
    namespace="dummy",
    application_file="spark.yaml",
    kubernetes_conn_id="kubernetes",
    do_xcom_push=True,
    dag=dag,
)
```

After first successful run, next runs fail to submit spark application 

> airflow.exceptions.AirflowException: Exception when calling -> create_custom_object: (409)
> Reason: Conflict
> 
> {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"sparkapplications.sparkoperator.k8s.io "xxx" already exists","reason":"AlreadyExists","details":{"name":"xxx","group":"sparkoperator.k8s.io","kind":"sparkapplications"},"code":409}
> 

**Expected Result**

Delete existing spark application if such exists before submitting new one.

### PR DESCRIPTION
**Pull request by theesen**
**SparkKubernetesOperator deletes any previous Spark Application with the same name**

**Current issue**:
If a Spark App is being launched you either have to template the name inside the yaml file (making it unique with a timestamp) or need to delete the previous run of the Spark App in order to prevent failure. Especially for newcomers to the topic this quickly leads to errors by design of the operator.

**Open Questions**:
I am wondering if we should delete the K8 Spark Application after a successful run as well from inside the Operator. Or at least provide a flag to enable this. 
_Downsides_: Harder to debug since container is gone in case of errors (or we keep the container if it failed)
_Upsides_: Less polluted K8 Cluster with old Spark Apps.

I would love to get some input on these thoughts.

**Minor Updates**:
As far as I could tell the docstring was not correct. You can only pass a String or Dict as `application_file` . The name of the parameter would need to be changed from my point of view as well. But since this is my first PR here, I did not want to introduce a breaking change to an Operator right away. But if someone makes sure I am doing this the right way, I am happy to adjust.

closes: #16290

### CODE REVIEW

**Comment by jherrmannNetfonds** [comment]
Hi @theesen, thank you for that PR.
I implemented the option with the flag to delete after successful run which you would like to discuss. But I implemented this in `SparkKubernetesSensor`
I delete the application on success state by default. Since if everything runs fine I do not need keep the application around. Or at least I never had the use case to look into the application.
This way I only keep failed applications and on a rerun of a successful run I do not get any error.

Independent of the implementation I would offer a flag so that the user can choose what behavior he wants.

**Comment by potiuk** [comment]
Could you please add tests to the change @theesen ?

**Comment by potiuk** [comment]
Tests failing

**Comment by theesen** [comment]
Fixed and tested the unittests locally. Should be fine now. Finger crossed.

**Comment by potiuk** [comment]
Need rebase unfortunately.

**Comment by theesen** [comment]
@potiuk can you approve the workflow?

**Review by potiuk — APPROVED** [review]

**Comment by assaf-xm** [comment]
@theesen , @potiuk , were the changes in this PR reverted in https://github.com/apache/airflow/commit/9a4f6748521c9c3b66d96598036be08fd94ccf89 ?

I can see that with the latest airflow version (2.6.2), existing sparkapplication with the same name won't be deleted by the SparkKubernetesOperator logic, and will fail to launch the new application until manually deleting the old one. Is there any flag to bring back the auto deletion logic?

**Comment by potiuk** [comment]
No idea. But you can check the code, or with the author of the change you mention - the author might be the best to discuss the change with.

**Comment by theesen** [comment]
Hey,
yeah the author of the commit linked, refactored the sequence a bit and moved the call of `delete_custom_object` into the on_kill method. Which is ok in failure cases but does not solve the original intention of my implementation. Which was removing previous runs with the exact same time. Fixing this again should be easy though.

`self.hook.delete_custom_object` needs to be called in the execute block again. Initially the approach was just to try to delete a spark app with that name, and catch the exception, if it does not exist as an expected case.

**Pull request merged**
