### PR TITLE
[AIRFLOW-1016] Allow HTTP HEAD request method on HTTPSensor

### PR DESCRIPTION
**Pull request by msempere**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1016

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
As commented on the JIRA ticket,  the HTTPSensor hardcodes the HTTP request method to `GET`, so this PR allows `HEAD` method as well.

### Tests
- [x] My PR adds the following unit tests 

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by msempere** [comment]
@mistercrunch, @artwr, @gtoonstra anything missing here or to improve?

**Review by gtoonstra — APPROVED** [review]
Other than perhaps moving the "requests"  import in the tests to the top of the file (why is it in the middle?), I can't discover anything now that seems to be a problem. The tests actually increases coverage by a good amount too.

**Comment by msempere** [comment]
@gtoonstra should I move the import to the top? I didn't want to import a module in case of testing the other test cases independently that don't require it. But I'm ok to move it to the top if that's better.

**Comment by gtoonstra** [comment]
I'd like to let the committer decide on that. I approved to indicate I looked at the code myself and don't see obvious improvements or issues and that the import in this way is not a big issue for me.

**Comment by msempere** [comment]
@gtoonstra ok, thanks for reviewing. Going to leave it like that and if @mistercrunch or @artwr or another reviewer seems that as unusual then I'll move it to the top.

**Comment by artwr** [comment]
LGTM.

**Comment by msempere** [comment]
All good then, @artwr, @gtoonstra

**Comment by msempere** [comment]
@mistercrunch, @artwr, @gtoonstra anything missing here?

**Comment by artwr** [comment]
@msempere LGTM but you seem to have merge conflicts now. If you can get those resolved, I will merge your PR.

**Comment by msempere** [comment]
@artwr I'm getting `py27-cdh-airflow_backend_sqlite` errors from `Travis` when running the tests, any idea?

**Comment by msempere** [comment]
@artwr done, go for it.

**Pull request closed without merging**
