### PR TITLE
Bump `uv` to `0.4.22`

### PR DESCRIPTION
**Pull request by kaxil**
https://pypi.org/project/uv/0.4.22

I added `--no-sources` to our `uv pip install` command, without it, it fails with following error

```
error: Failed to build: `apache-airflow @ file:///dist/apache_airflow-3.0.0.dev0.tar.gz`
  Caused by: Failed to parse entry for: `local-providers`
  Caused by: Package is not included as workspace package in `tool.uv.workspace`
```
Example: https://github.com/apache/airflow/actions/runs/11354720505/job/31582868760#step:11:2896

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by kaxil** [comment]
@potiuk Got another one 😆

**Review by potiuk — APPROVED** [review]

**Comment by kaxil** [comment]
This one fixes an issue @ashb raised: https://github.com/astral-sh/uv/issues/8041

**Comment by potiuk** [comment]
They are indeed working with lightning speed :)

**Comment by kaxil** [comment]
> Sorry for the `--no-sources` weirdness -- it'll be fixed in the next release: [astral-sh/uv#8235](https://github.com/astral-sh/uv/pull/8235)

Thanks @charliermarsh , I appreciate the quick turnaround

**Comment by potiuk** [comment]
Thanks @charliermarsh and the team (as usual :) . We are now getting more and more into using `uv workspaces` after our earlier discussions - so expect more of similar reports from us :)

**Pull request merged**
