### PR TITLE
Add `breeze generate-migration-file` command

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This helps to generate alembic migration file for ORM changes.

Closes: #39576

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
NIT. Can you also add information about this command to  to `contributing-docs/13_metadata_database_updates.rst` ?

**Comment by ephraimbuddy** [comment]
Hi @potiuk , I'm not sure what this failure means: https://github.com/apache/airflow/actions/runs/9093832549/job/24993789868?pr=39632#step:8:416.

**Comment by potiuk** [comment]
Screenshot 2024-05-15 at 07 12 45

**Comment by ephraimbuddy** [comment]
> Screenshot 2024-05-15 at 07 12 45

Other commands like `build-docs` did not create a new file like it's suggesting I create: `dev/breeze/src/airflow_breeze/commands/generate_migration_file_commands_config.py`. I thought having it in `dev/breeze/src/airflow_breeze/commands/developer_commands_config.py` is enough

**Comment by potiuk** [comment]
> Other commands like `build-docs` did not create a new file like it's suggesting I create: `dev/breeze/src/airflow_breeze/commands/generate_migration_file_commands_config.py`. I thought having it in `dev/breeze/src/airflow_breeze/commands/developer_commands_config.py` is enough

Yeah that message is not 100% correct in all cases - release_commands for example are also in a different place. It might need some improvement. But generally it's about making sure there is a group defined and used in breeze so that the `--message` in help does not land in `Common options` group.

**Comment by ephraimbuddy** [comment]
> > Other commands like `build-docs` did not create a new file like it's suggesting I create: `dev/breeze/src/airflow_breeze/commands/generate_migration_file_commands_config.py`. I thought having it in `dev/breeze/src/airflow_breeze/commands/developer_commands_config.py` is enough
> 
> Yeah that message is not 100% correct in all cases - release_commands for example are also in a different place. It might need some improvement. But generally it's about making sure there is a group defined and used in breeze so that the `--message` in help does not land in `Common options` group.

Solved it by adding it to the developer_command in dev/breeze/src/airflow_breeze/commands/setup_commands.py

**Review by vincbeck — APPROVED** [review]

**Pull request merged**
