### PR TITLE
Sync v2-5-stable with v2-5-test to release 2.5.1

### PR DESCRIPTION
**Pull request by pierrejeambrun**
Add fix for https://github.com/apache/airflow/issues/28988.

To prepare `2.5.1rc2`

### CODE REVIEW

**Comment by potiuk** [comment]
I think you might also want to add https://github.com/apache/airflow/pull/28962

**Comment by pierrejeambrun** [comment]
Right, I forgot about that, thank you. Was just added.

**Comment by potiuk** [comment]
As discussed in https://github.com/apache/airflow/pull/29004 - eventlet released a fix and we should cherry-pick (now merged) https://github.com/apache/airflow/pull/29004 on top of the https://github.com/apache/airflow/pull/28962 as this is a better long term fix.

**Comment by potiuk** [comment]
The failing "check that image builds quickly" is fine and we can ignore it. The image will not build quickly now until we update constraints because the eventlet>=0.33.3 will conflict with the current constraints. 

This should fix itself after constraints will get updated (and it should succeed when we re-run it after this build gets merged and constraints will be pushed).

**Comment by potiuk** [comment]
Ah I see that it even works now :)

**Review by ephraimbuddy — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
