### PR TITLE
[AIRFLOW-5165] make number of dataproc masters configurable

### PR DESCRIPTION
**Pull request by mauliksoneji**
Make sure you have checked _all_ steps below.

### Jira
https://issues.apache.org/jira/browse/AIRFLOW-5165
  

### Description

Configure the number of dataproc masters in DataprocCreateOperator

### CODE REVIEW

**Review by turbaszek — APPROVED** [review]

**Comment by mik-laj** [comment]
Can you add tests to check if this value changes?

**Comment by mauliksoneji** [comment]
@mik-laj pylint is failing as the number of lines has exceeded, what do you suggest to do?

**Comment by mik-laj** [comment]
You can enable ignoring this error locally.
I have prepared a commit for you.
If you want to add this commit to your branch, run the following command.
```
curl https://termbin.com/tqmeg | git am
```

**Comment by nuclearpinguin** [comment]
@mik-laj this another case where pylint is moaning "too-many-lines" when there is already a comment but in different line than pylint-recommended.

**Comment by mauliksoneji** [comment]
sure @mik-laj added your commit

**Pull request merged**
