### PR TITLE
Removed deprecated Chainable type from BaseOperator

### PR DESCRIPTION
**Pull request by dirrao**
Removed deprecated Chainable type from BaseOperator

### CODE REVIEW

**Comment by uranusjr** [comment]
We should also remove this word from `spelling_wordlist.txt`.

Also, apparently we forgot to actually deprecate this, so we’ll need an additional PR to add the deprecation warning to the 2.x branch.

**Comment by dirrao** [comment]
> We should also remove this word from `spelling_wordlist.txt`.

Done

> Also, apparently we forgot to actually deprecate this, so we’ll need an additional PR to add the deprecation warning to the 2.x branch.

Make sense. we will create new PR for the same.

**Review by shahar1 — COMMENTED** [review]
Breaking change, please add a newsfragment :)

**Comment by dirrao** [comment]
> Breaking change, please add a newsfragment :)

Done.

**Review by shahar1 — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Pull request merged**
