### PR TITLE
Replace freezegun with time-machine

### PR DESCRIPTION
**Pull request by ashb**
The primary driver for this was a niggle that the durations output for
one test was reporting over 52 years:

> 1670340356.40s call     tests/jobs/test_base_job.py::TestBaseJob::test_heartbeat

It turns out this was caused by freezegun, but time_machine fixes this.
It also might be a bit faster, but that isn't a noticeable difference for
us. (No runtime difference for the changed files, but it does make
collection quicker: from 10s to 8s)

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Love it. I've read https://github.com/adamchainz/time-machine and it's a cool, nice, small library. Much better and more versatile than freezegun, and I love the time_travel metapherore much more than the freezegun's one (who needs guns).

Kudos to the author for Delorean example in the docs in case you missed it.

**Comment by ashb** [comment]
Ci no likey! Local was fine. Curious.

**Comment by ashb** [comment]
It's an odd one: This combo of tests fails locally:

`tests/task/task_runner/test_task_runner.py::TestGetTaskRunner::test_should_support_core_task_runner  tests/sensors/test_external_task_sensor.py::TestExternalTaskSensor::test_external_task_sensor_failed_states_as_success`

```
    @mock.patch("airflow.task.task_runner.base_task_runner.subprocess")
    @mock.patch("airflow.task.task_runner._TASK_RUNNER_NAME", "StandardTaskRunner")
    def test_should_support_core_task_runner(self, mock_subprocess):
        ti = mock.MagicMock(map_index=-1, run_as_user=None)
        ti.get_template_context.return_value = {"ti": ti}
        ti.get_dagrun.return_value.get_log_template.return_value.filename = "blah"
        local_task_job = mock.MagicMock(task_instance=ti)
        task_runner = get_task_runner(local_task_job)

        assert "StandardTaskRunner" == task_runner.__class__.__name__
```

I don't quite know _what_ in that test is leaking state either!

**Comment by ashb** [comment]
OH! Main is broken with that test!

**Review by jedcunningham — APPROVED** [review]

**Pull request merged**
