### PR TITLE
[AIRFLOW-2390] Fix FlaskWTFDeprecationWarning

### PR DESCRIPTION
**Pull request by kaxil**
- Replace soon to be deprecated `flask_wtf.Form` class with `from flask_wtf import FlaskForm`

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2390
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
- Replace soon to be deprecated `flask_wtf.Form` class with `from flask_wtf import FlaskForm`

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
All checks have passed: https://travis-ci.org/apache/incubator-airflow/builds/372542672

cc @Fokko

**Comment by Fokko** [comment]
Thanks for picking this up @kaxil! Could you also fix the Form in rbac/password_auth? Thanks:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ grep -R 'wtforms[A-Za-z, ]*Form' .
./airflow/contrib/auth/backends/password_auth.py:from wtforms import Form, PasswordField, StringField
./airflow/www_rbac/views.py:from wtforms import Form, SelectField, validators
```
The files on Github:
https://github.com/kaxil/incubator-airflow/blob/AIRFLOW-2390/airflow/www_rbac/views.py#L50
https://github.com/kaxil/incubator-airflow/blob/AIRFLOW-2390/airflow/contrib/auth/backends/password_auth.py#L28

I'm still confused why the CI failed. Let me check: https://travis-ci.org/Fokko/incubator-airflow/builds/372642153

**Comment by kaxil** [comment]
@Fokko regarding the Form in `rbac/password_auth`: It uses `wtforms` library which hasn't changed. The deprecation warning is in `flask_wtf` package which is the integration of `Flask` and `wtforms` package. 

Regarding the CI failure, it for some reason picked a previous commit in this PR which I fixed.
https://travis-ci.org/apache/incubator-airflow/builds/372542672

I closed & reopened this PR and now it the CI passes

**Review by Fokko — APPROVED** [review]
Awesome thanks @kaxil

**Pull request closed without merging**
