### PR TITLE
[AIRFLOW-6231] Display DAG run conf in the list view

### PR DESCRIPTION
**Pull request by dhuang**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-6231

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
  - Show DAG run conf in the UI since it's not surfaced anywhere else. Text box won't show unless a conf is specified.

Screenshot 2020-04-17 22 34 05

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.

### CODE REVIEW

**Review by feluelle — COMMENTED** [review]
I like that 👍 But I am wondering if it would look better below the Graph View or between the `Base Date` row and the Graph View.

**Comment by kaxil** [comment]
This should not be stored/viewed in the Graph View! I am fine with having this in **Details** page or somwhere else

**Comment by dhuang** [comment]
> I like that 👍 But I am wondering if it would look better below the Graph View or between the Base Date row and the Graph View.

Good idea. I think I like it best between the Base Date and the graph so it's under where one selects the run. Below the graph seems a little too out of sight (I think generally very relevant info if one is setting `conf`), but does avoid putting the graph out of initial view if there's a large conf (although `doc_md` would have this same issue anyways).  Updated, but open for feedback.

Screenshot 2019-12-12 10 36 10


> This should not be stored/viewed in the Graph View! I am fine with having this in Details page or somwhere else

The details page is at the DAG level. Since the `conf` value is tied to a specific DagRun, I assume it should only land on a page that displays things at a per DagRun level? I think the only alternative (or perhaps show in both) is the Tree View, which I think a big `conf` blobs is too much for the DAG hover over, but maybe could put it in the modal?

**Comment by kaxil** [comment]
> > I like that 👍 But I am wondering if it would look better below the Graph View or between the Base Date row and the Graph View.
> 
> Good idea. I think I like it best between the Base Date and the graph so it's under where one selects the run. Below the graph seems a little too out of sight (I think generally very relevant info if one is setting `conf`), but does avoid putting the graph out of initial view if there's a large conf (although `doc_md` would have this same issue anyways). Updated, but open for feedback.
> 
> Screenshot 2019-12-12 10 36 10
> 
> > This should not be stored/viewed in the Graph View! I am fine with having this in Details page or somwhere else
> 
> The details page is at the DAG level. Since the `conf` value is tied to a specific DagRun, I assume it should only land on a page that displays things at a per DagRun level? I think the only alternative (or perhaps show in both) is the Tree View, which I think a big `conf` blobs is too much for the DAG hover over, but maybe could put it in the modal?

Hmm, I agree that it won't make sense on the Details page. But it definitely feels wrong to include it in Graph View. Other users would want more details like Dag Run Start and End Date, Run ID etc. Maybe we can just add this in DagRun View (`http://localhost:8080/dagrun/list/`)

**Comment by tooptoop4** [comment]
is there a way to pass in conf when triggering a dag via UI ?

**Comment by dhuang** [comment]
> Hmm, I agree that it won't make sense on the Details page. But it definitely feels wrong to include it in Graph View. Other users would want more details like Dag Run Start and End Date, Run ID etc. Maybe we can just add this in DagRun View (http://localhost:8080/dagrun/list/)

Ooh, I hadn't thought of the DAG run list view as an alternative. But can you elaborate why you're against having it on the graph view? Graph view is the one tab specific to a DAG run and the `conf` when set is likely important to be aware of when looking at a DAG run. 

> is there a way to pass in conf when triggering a dag via UI ?

Nope, not currently.

**Comment by tooptoop4** [comment]
@dhuang I think @kaxil  is saying the graph ui will get too crowded but there is plenty of space on DagRun view

**Comment by kaxil** [comment]
Yup, Graph UI can get easily crowded I think if we start adding more elements. WDYT @dhuang ?

**Comment by dhuang** [comment]
Apologies for abandoning this, moved over to list view as suggested! PR description updated with screenshots. Made it searchable as well as I think it can be useful and also makes it consistent with both list/add views.

**Comment by MelnykAndriy** [comment]
I would also love this feature to be merged

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
@dhuang Can you add a test to "When a conf is passed in DAG it appears in ListView"?

Example: https://github.com/apache/airflow/commit/ccbaf578aee5fd04580eb07d27fbbd688a2f3080#diff-948e87b4f8f644b3ad8c7950958df033

**Comment by dhuang** [comment]
> @dhuang Can you add a test to "When a conf is passed in DAG it appears in ListView"?
> 
> Example: ccbaf57#diff-948e87b4f8f644b3ad8c7950958df033

Good call, added. Thanks for providing the example.

**Review by feluelle — APPROVED** [review]

**Comment by kaxil** [comment]
Thanks @dhuang

**Pull request merged**
