### PR TITLE
Remove the limit on Gunicorn dependency

### PR DESCRIPTION
**Pull request by potiuk**
It seems that the < 20.0 limit for gunicorn was added at some point
in time without actual reason. We are already using gunicorn in
1.10 line of Airflow, so it should not be a problem to bump the
version of gunicorn, especially that the 19. line is somewhat
deprecated already.

This change came after the discussion n #15570

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Looks like all tests are passing with gunicorn 20.1.0 (the latest one). I tested it locally as well, and everything seems to be fine Airflow works with several gunicorn workers - looks like no major problems. I think we can safely merge this one.

**Review by ashb — COMMENTED** [review]
I don't feel _great_ about no upper limit here - it means Gunicorn could release a v22 that breaks us.

**Comment by uranusjr** [comment]
That's when the constraints files is useful 🙂 Python packaging encourages the "compatible unless proven guilty" approach since it's much easier for the user to add extra constraints if gunicorn 22 proves incompatible, but it's much more difficult to remove `gunicorn<22` if it causes unnecessarily conflicts.

**Comment by potiuk** [comment]
Agree with @uranusjr  - our constraints approach is designed to prevent precisely this problem and it works with most of our dependencies.

**Review by ashb — APPROVED** [review]

**Pull request merged**
