### PR TITLE
fix(helm): set worker safeToEvict properly

### PR DESCRIPTION
**Pull request by hakuno**
It improves (or fixes) the `workers.safeToEvict` usage.

Kubernetes administrators/users agree that `cluster-autoscaler.kubernetes.io/safe-to-evict` can be managed to avoid the Autoscaler to kill the worker pod when scaling nodes down.

> When this annotation is set to "true", the cluster autoscaler is allowed to evict a Pod even if other rules would normally prevent that. The cluster autoscaler never evicts Pods that have this annotation explicitly set to "false"; you could set that on an important Pod that you want to keep running. If this annotation is not set then the cluster autoscaler follows its Pod-level behavior.

So, if I set `workers.safeToEvict` to `false`, it gets nothing. The Autoscaler will kill that still. Because the Helm chart has no effect on handling that. See:

```
        {{- if .Values.workers.safeToEvict }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        {{- end }}
```

What about if I need to set that to false? I couldn't. Anybody is unable to.

A probaly **workaround** would set up `workers.podAnnotations` with map of _annotations_ and `workers.safeToEvict` falsely together.

Please, check it out carefully. Thanks in advance!

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
Yeah, it's better than the current implementation, could you add a test for it with the different values?

**Comment by hakuno** [comment]
Thank you so, @hussein-awala 

I tested the Helm Chart itself with `--validate` on a Kubernetes cluster to verify the generated manifests.

```
$ helm template --dry-run --validate --set workers.safeToEvict=false .
```

We got

```
# Source: airflow/templates/workers/worker-deployment.yaml
################################
## Airflow Worker Deployment
#################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-worker
  labels:
    tier: airflow
    component: worker
    release: release-name
    chart: "airflow-1.12.0-dev"
    heritage: Helm
spec:
  serviceName: release-name-worker
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: worker
      release: release-name
  template:
    metadata:
      labels:
        tier: airflow
        component: worker
        release: release-name
      annotations:
        checksum/metadata-secret: 8b8ce685079b3075a4b91c47e267db7b50cd8bfda2269dd36fef1e258a3a38eb
        checksum/result-backend-secret: 98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71
        checksum/pgbouncer-config-secret: 1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688
        checksum/webserver-secret-key: 1b48a02846657f40ac54dc50b230572e67e9f4a88e9a486e63bd25209173bfc4
        checksum/kerberos-keytab: 80979996aa3c1f48c95dfbe9bb27191e71f12442a08c0ed834413da9d430fd0e
        checksum/airflow-config: 520107ea8f2b203f84baed2ba60545a7afc8fc9a9f6978aa7cd45c4dba7c8dbe
        checksum/extra-configmaps: e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8
        checksum/extra-secrets: e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
...
```

And

```
$ helm template --dry-run --validate --set workers.safeToEvict=true .
```

We got

```
# Source: airflow/templates/workers/worker-deployment.yaml
################################
## Airflow Worker Deployment
#################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-worker
  labels:
    tier: airflow
    component: worker
    release: release-name
    chart: "airflow-1.12.0-dev"
    heritage: Helm
spec:
  serviceName: release-name-worker
  replicas: 1
  selector:
    matchLabels:
      tier: airflow
      component: worker
      release: release-name
  template:
    metadata:
      labels:
        tier: airflow
        component: worker
        release: release-name
      annotations:
        checksum/metadata-secret: 8b8ce685079b3075a4b91c47e267db7b50cd8bfda2269dd36fef1e258a3a38eb
        checksum/result-backend-secret: 98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71
        checksum/pgbouncer-config-secret: 1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688
        checksum/webserver-secret-key: c20aeee646c14a8ab31991c17de268a577d34f05d4a1ae045725bf974f999c69
        checksum/kerberos-keytab: 80979996aa3c1f48c95dfbe9bb27191e71f12442a08c0ed834413da9d430fd0e
        checksum/airflow-config: 520107ea8f2b203f84baed2ba60545a7afc8fc9a9f6978aa7cd45c4dba7c8dbe
        checksum/extra-configmaps: e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8
        checksum/extra-secrets: e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
...
```

And default values is same than `workers.safeToEvict=true` as expected.

Please, tell me if you know more ways to check it out.

**Comment by jedcunningham** [comment]
@hakuno, Hussein meant a test in our test suit to make sure this doesn't regress. [Here is an example](https://github.com/apache/airflow/blob/f457228bd21b13a7fdb29e154202d5357d024050/helm_tests/airflow_core/test_worker.py#L50-L65), and [some details on our helm chart tests](https://github.com/apache/airflow/blob/main/TESTING.rst#helm-unit-tests).

**Comment by hakuno** [comment]
@jedcunningham Thanks for that. Unfortunately, I've had some difficult to setup this test environment.

Thoughts?

**Comment by potiuk** [comment]
> @jedcunningham Thanks for that. Unfortunately, I've had some difficult to setup this test environment.
> 
> Thoughts?

If you do not write what kind of difficulties you had, It's hard to have more thoughts. But I recommend to follow the steps in https://github.com/apache/airflow/blob/main/CONTRIBUTORS_QUICK_START.rst to setup breeze and then the docs pointed at by @jedcunningham provide a step-by-step (almost wizard-like) approach to make it works.

**Comment by hakuno** [comment]
Thanks, @potiuk - I meant the environment setup itself. My Pytest couldn't discovery tests etc.

I'll read that docs as soon as possible... thanks again :)

**Comment by hakuno** [comment]
@jedcunningham @hussein-awala @potiuk I got it.

```
pytest helm_tests/airflow_core/test_worker.py::TestWorker::test_safetoevict_annotations
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /opt/airflow
configfile: pyproject.toml
plugins: timeouts-1.2.1, xdist-3.3.1, capture-warnings-0.0.4, instafail-0.5.0, mock-3.12.0, asyncio-0.21.1, requests-mock-1.11.0, time-machine-2.13.0, cov-4.1.0, rerunfailures-12.0, anyio-4.0.0, httpx-0.21.3
asyncio: mode=strict
setup timeout: 0.0s, execution timeout: 0.0s, teardown timeout: 0.0s
collected 2 items                                                                                                                                                                                           

helm_tests/airflow_core/test_worker.py::TestWorker::test_safetoevict_annotations[true-True] PASSED                                                                                                    [ 50%]
helm_tests/airflow_core/test_worker.py::TestWorker::test_safetoevict_annotations[false-False] PASSED                                                                                                  [100%]

============================================================================================ 2 passed in 16.65s =============================================================================================
```

**Comment by hakuno** [comment]
Ps.¹ Other Airflow components also has `safeToEvict` values.

Ps.² At another moment, I see I can contribute with other PRs. Because `workers.podAnnotations` and `airflowPodAnnotations` can fight each other whenever it has a set of annotations in common.

**Review by jedcunningham — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Pull request merged**
