### PR TITLE
Fix bug in executor_config when defining resources

### PR DESCRIPTION
**Pull request by dimberman**
Fixes a bug in 1.10.11 where the executor_config errors out when resources are specified.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
Hey @dimberman -> I am now cherry-picking all the changes for builds/reqs from master so better not merge this one (and BTW. some more description would be nice in the commit message)

**Comment by dimberman** [comment]
@potiuk sounds good, I will hold off. Also that's super weird that the PR generated without any message at all. I'll make sure to fix that once tests pass.

**Comment by pgagnon** [comment]
FYI, this is a breaking API change.

Old syntax was: `            "resources": {"request_memory": "2Gi", "limit_memory": "2Gi"},`

But now requests and limits need to be nested dicts.

It wasn't obvious to me from the changelog so we should probably document this more obviously.

@dimberman @potiuk

**Comment by dimberman** [comment]
@pgagnon has this broken the API for you?

These lines should allow that https://github.com/apache/airflow/pull/9935/files#diff-868ed785b2a336f20cb6a577dde2502aR362-R363

**Comment by pgagnon** [comment]
Yeah, I got:

```
[2020-08-31 18:05:26,015] {{scheduler_job.py:1401}} ERROR - Exception when executing execute_helper
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1399, in _execute
    self._execute_helper()
  File "/usr/local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1470, in _execute_helper
    if not self._validate_and_run_task_instances(simple_dag_bag=simple_dag_bag):
  File "/usr/local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1532, in _validate_and_run_task_instances
    self.executor.heartbeat()
  File "/usr/local/lib/python3.8/site-packages/airflow/executors/base_executor.py", line 130, in heartbeat
    self.trigger_tasks(open_slots)
  File "/usr/local/lib/python3.8/site-packages/airflow/executors/base_executor.py", line 151, in trigger_tasks
    self.execute_async(key=key,
  File "/usr/local/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 795, in execute_async
    kube_executor_config = PodGenerator.from_obj(executor_config)
  File "/usr/local/lib/python3.8/site-packages/airflow/kubernetes/pod_generator.py", line 376, in from_obj
    requests=resources['requests'],
KeyError: 'requests'
```

**Comment by dimberman** [comment]
@pgagnon can you please post the executor_config that worked before but is now broken?

**Comment by pgagnon** [comment]
@dimberman 

```
    executor_config={
        "KubernetesExecutor": {
            "annotations": {
                "iam.amazonaws.com/role": "arn:aws:iam::<account>:role/"
                "<role>"
            },
            "resources": {"request_memory": "2Gi", "limit_memory": "2Gi"},
        }
    },
```

As an argument to `PythonOperator.__init__`.

**Pull request merged**
