### PR TITLE
Rename --test-types to --parallel-test-types parameters

### LINKED ISSUE #30407: merge breeze's --test-type and --test-types options
### Description

using `breeze testing tests` recently I noticed that the way to specify which tests to run is very confusing:
 * `--test-type` supports specifying one type only (or `All`), allows specifying which provider tests to run in details, and is ignored if `--run-in-parallel` is provided (from what I saw)
 * `--test-types` (note the `s` at the end) supports a list of types, does not allow to select specific provider tests, and is ignored if `--run-in-parallel` is NOT specified.

I _think_ that the two are mutually exclusive (i.e. there is no situation where one is taken into account and the other isn’t ignored), so it’d make sense to merge them.

Definition of Done:

- --test-type or --test-types can be used interchangeably, whether the tests are running in parallel or not (it'd be a bit like how `kubectl` allows using singular or plural for some actions, like `k get pod` == `k get pods`)
- When using the type `Providers`, specific provider tests can be selected between square brackets using the current syntax (e.g. `Providers[airbyte,http]`)
- several types can be specified, separated by a space (e.g. `"WWW CLI"`)
- the two bullet points above can be combined (e.g. `--test-type "Always Providers[airbyte,http] WWW"`)

### Use case/motivation

having a different behavior for a very similar option depending on whether we are running in parallel or not is confusing, and from a user perspective, there is no benefit to having those as separate options.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by potiuk**
The --test-type and --test-types parameters were very similar, but they have enough difference to differentiate them even more:

The --test-type is specifically to run single test and it might include not only the regular "test-types" but also allow for cross-selection of tests from different other types (for example --test-type Postgres will run tests for Postgres database and they might come from Providers, Others, CLI etc.

Where --test-types was generally foreseen to be able to split the tests into "sepearated" groups that could be run in parallel.

The parameters have different defaults and even different choice of test type that you could choose from (and --test-types is a space-separated one to make it easier to pass it around in CI, where rather than passing multiple (variable number) of parameters, it's easier to pass a single, even space-separated list of tests to run.

This change is good to show the difference between then parameters and to stress that they are really quite different, also it makes it easier to avoid confusion people might have especially that the name was easy to have typo in.

In a way (but different than in the original issue it Fixes: #30407

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @vandonr-amz  - I made changes to breeze w/regards providers and I recalled the discussion from #https://github.com/apache/airflow/issues/30407 and I found that it is **really** easy to just rename the --test-types parameter to avoid confusion . Here it is.

**Comment by vandonr-amz** [comment]
renaming the parameter is a breaking change though. Won't it break the CI here in github ?

Also, I agree that the rename is a step in the right direction to reduce confusion, but I still think it's weird to have parameters that are very similar but slightly different and incompatible in their use :/

**Comment by potiuk** [comment]
I also correctedalm the Ci references. breeze is deliberately in Airflwo repo so that they can evolve together and so we do not have to care about backwards compatibility. And this paran is norlstly use d in CI - most people even if run parallel tests they would run it with default value (all tests).

We have no expectations nor need about breeze being backwards compatible :) 

I understand where  you're coming from but i think it is really the matter of wher you get 'common' part we are reusing a lot of code under the hood, and it's a bit arbitrary decision how to name parameters that internally might even consist of similar 'blocks' 

In this case i'd say separating it MORE is better because it removes confusion and typos

**Comment by potiuk** [comment]
I also correctedalm the Ci references. breeze is deliberately in Airflwo repo so that they can evolve together and so we do not have to care about backwards compatibility. And this paran is norlstly use d in CI - most people even if run parallel tests they would run it with default value (all tests).

We have no expectations nor need about breeze being backwards compatible :) 

I understand where  you're coming from but i think it is really the matter of wher you get 'common' part we are reusing a lot of code under the hood, and it's a bit arbitrary decision how to name parameters that internally might even consist of similar 'blocks' 

In this case i'd say separating it MORE is better because it removes confusion and typos

**Comment by potiuk** [comment]
But of course if you would like to propose a PR changing it + i am happy to discuss seeing the code :)

**Review by vandonr-amz — APPROVED** [review]
lgtm

**Comment by potiuk** [comment]
Small quality of life improvement in breeze.

**Review by josh-fell — APPROVED** [review]

**Pull request merged**
