### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anirudhbagri**
The original page has been archived. Updating the doc to point to the archived doc location.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by ryw — CHANGES_REQUESTED** [review]
since that is a deleted wiki page, I'd suggest pointing this link to https://airflow.apache.org/docs/stable/project.html#committers instead

**Review by ryw — APPROVED** [review]

**Comment by anirudhbagri** [comment]
@ryw Updated the link.

**Comment by ryw** [comment]
Thanks for your first contribution, @anirudhbagri 👍

**Comment by anirudhbagri** [comment]
Hey @ryw, can you add"hacktoberfest-accepted" label to this PR?
As "hactober" label was removed from the repo, this PR isn't counted as a contribution.
Thank you :)

**Comment by ryw** [comment]
fixed @anirudhbagri

**Pull request merged**
