### PR TITLE
Refactored setup.py to better reflect changes in providers

### LINKED ISSUE #13309: Refactor setup.py extras/providers/deps
We currently have depdencies, extras and providers (with extras names same as providers) in setup.py. Plus we have some aliases from 1.10 that are going to be deprecated in 3.0. 

We need to refactor this to make it less confusing, because it's difficult to say if some of the extras/providers are wrong, or missing due to that.

Ralated issues: #12548, #13308

### PR DESCRIPTION
**Pull request by potiuk**
Please review only the last commit (this one is base on an earlier LDAP change) #13308

This is a complete refactor of the setup.py providers/dependencies.

It much better reflects the current setup where we have most of
the extras 1-1 reflecting providers but also some extras that do
not have their own providers.

The pre-commits that were verifying setup versus documentation
can now be vastly simplified (no more need to parse the
comments so we can import setup.py variables directly rather
than parse it via regexps. Also we can better categorize the
extras - separate out (and verify) whether we correctly
described deprecated extras and to mark extras that install
additional providers as such.

Fixes: #13309

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
The setup.py should be much more straightforward and easier to understand now with all the extras-> providers relationships.

Also, the reference documents are now better reflecting relity and pre-commits are catching many more errors (I actually found and fixed quite a few documentation/setup inconsistencies while doing it:

Example error report printed when there are discrepancies setup.py vs. documentation:


Screenshot from 2020-12-25 21-07-24

**Review by houqp — APPROVED** [review]

**Comment by potiuk** [comment]
@houqp  I simplified it a bit more. I wanted to used NamedTuples first so I turned Dicts into Lists but this was a bad idea so I converted back `PROVIDERS_REQUIREMENTS` and `EXTRAS_DEPRECATED_ALIASES` to Dicts. That makes much more sense and simplifies some further manipulations with those, including the pre-commits.

**Comment by potiuk** [comment]
And added extra column for pre-installed providers (and verification if the docs match setup.py).

I also removed circular dependency from the preinstalled providers (provider -> airflow -> provider) and updated the package dependency to >=2.0.0 (it was >=2.0.0b2). This was not a problem in general but some tools (pipdeptree) shown the circular dependncy as a warning.

@ashb -> that means that I had to move the providers to setup.py from setup.cfg (to be able to easier verify it) but I think it makes perfect sense in this case.

Here is the updated pre-commit message printed if the setup.py gets unsynchronized with the documentation:
Screenshot from 2020-12-26 14-56-39

**Comment by potiuk** [comment]
cc: @szn -> finally I refactored the setup.py, got rid of the TODO comments (in favour of separate dictionary for aliases). That allowed to simplify and refactor your original code (finally we could import setup.py rather than parse it with regexps). Your code lives on ;).

**Comment by potiuk** [comment]
And example generated dependencies:

Screenshot from 2020-12-26 15-50-08

**Comment by potiuk** [comment]
Also updated the comments in setup.py and cleaned-up some typos with file paths that changed in the meantime.

**Comment by potiuk** [comment]
Another part of this change is vastly enriched output of 'setup-order' pre-commit. It will not only check everything for order but also will print what is being checked. I found out that several lists were wrongly ordered because some regular expressions were "stopping" comparison when there was '[" as part of requirement (so anything behind requirements with extras could be unsorted). Now you can see exactly what is being checked.

You can try yourself by:

```
pre-commit run setup-order -v --all-files
```

Screenshot from 2020-12-26 16-32-01

**Comment by potiuk** [comment]
Random failure. Merging

**Pull request merged**
