### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by malthe**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by XD-DENG — COMMENTED** [review]
May you clarify why is this an issue?

Both formats are fine, aren't they?

**Comment by malthe** [comment]
The trailing comma is weird, it means the auto formatted form must be
multiline.

søn. 6. jun. 2021 kl. 11.43 skrev Xiaodong DENG ***@***.***>:

**Comment by turbaszek** [comment]
Wasn't this format used because of #16265 ?

**Comment by malthe** [comment]
I think the story was that an upgrade to the automated formatted changed
how this syntax ought to be represented. I think a better fix then is to
remove the trailing comma altogether.

søn. 6. jun. 2021 kl. 17.16 skrev Tomek Urbaszek ***@***.***>:

**Comment by ashb** [comment]
Close as won't fix. If black is happy with it then so are we.

**Comment by malthe** [comment]
@ashb until the day where black is not happy because a trailing slash in function arguments is just weird.

**Pull request closed without merging**
