### PR TITLE
Add back envvars for mysql and postgres version options

### PR DESCRIPTION
**Pull request by potiuk**
It turned out that for quite a while we had not run backend tests for different versions of backends because the options were defined without envvars. Still tracking how long it was like that, but this PR should bring tests for the different backend versions back.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by Taragolis — APPROVED** [review]

**Comment by Taragolis** [comment]
- Need rerun this PR after we merge https://github.com/apache/airflow/pull/36914

**Comment by potiuk** [comment]
Thanks @Taragolis for noticing it!

**Comment by potiuk** [comment]
Luckily - nothing broken in neither of the versions.

**Comment by Taragolis** [comment]
> Need rerun this PR after we merge https://github.com/apache/airflow/pull/36914

Haha I wanted to draft and post this message  into the https://github.com/apache/airflow/pull/36893, but miss the tab in browser 🤦

**Comment by potiuk** [comment]
> > Need rerun this PR after we merge #36914
> 
> Haha I wanted to draft and post this message into the #36893, but miss the tab in browser 🤦

Yep. Figured it out :)

**Pull request merged**
