### PR TITLE
Fix HttpAsyncHook headers

### PR DESCRIPTION
**Pull request by ChaotX**
Fix extra fields used as headers

### CODE REVIEW

**Comment by ChaotX** [comment]
@sunank200 Can you please take a look at this? I think this was just a typo.

**Review by pankajastro — APPROVED** [review]
LGTM

**Comment by potiuk** [comment]
We should add/update test for it. One of the reasons it did not work here was that either test was wrong or missing.

**Review by sunank200 — COMMENTED** [review]
@ChaotX can you add the test for the change, please as @potiuk mentioned before we merge this PR?

**Comment by ChaotX** [comment]
I have no clue how to do that. Figuring it out would take too much time for me. I just started this with a one character fix...

**Comment by potiuk** [comment]
> I have no clue how to do that. Figuring it out would take too much time for me. I just started this with a one character fix...

Happy to guide you if you want if not, then maybe somone looking here will help and add it. but generally we do not merge a change where tests do not fail before and do not fail after, because we have no way to verify it and keep it verified in the future versions.

**Comment by potiuk** [comment]
I marked it with "good first issue" which usually indicates to people that things are up for grabs and if you won't add tests, hopefully it will drag attentions of those who can add it.

**Comment by pankajastro** [comment]
You can find http-related tests https://github.com/apache/airflow/tree/main/tests/providers/http and we are using by test so probably you will have to add a test in https://github.com/apache/airflow/blob/main/tests/providers/http/hooks/test_http.py

**Comment by ChaotX** [comment]
@sunank200 Can you please help adding these test to your contribution? I had no time to figure out how to change the test env to 3.8+ python.

**Pull request closed without merging**
