### PR TITLE
[AIRFLOW-2622] Support Confirm=False for SFTPOperator

### PR DESCRIPTION
**Pull request by caddac**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-2622) issues and references them in the PR title. 

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:
Exposes the `confirm=False` option on the Paramiko library when SFTPing a file. This feature is needed because the server I'm sending to removes files from the remote directory before I the library is able to to confirm the file transfer.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    Added method documentation (and fixed documentation for the operation param)

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Please adhere to the commit guidelines. Also the Flake8 check is failing.

**Comment by caddac** [comment]
I've updated this PR, any additional feedback?

**Comment by kaxil** [comment]
@caddac Please check the commit guidelines. The commit title is still unclear. `add confirm option` to what?

**Comment by caddac** [comment]
@kaxil Thank you for the guidance, the commit message has been updated.

**Comment by caddac** [comment]
I see the build is failing, but I'm not sure why. It previously built and the error doesn't appear to be related to the changes I made.

**Comment by Fokko** [comment]
@caddac I don't think the failing build is related to your changes.

**Review by Fokko — APPROVED** [review]
LGTM, thanks @caddac 

Merging to master

**Pull request closed without merging**
