### PR TITLE
AIRFLOW-4586 There is no need to check explicitly for queued dependen…

### PR DESCRIPTION
**Pull request by ramandumcs**
…cy as all dependencies can be checked as part of RUN_DEPS. Currently task gets stuck in queued state if QUEUE_DEPS are not met here

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
This is going to need unit tests before it gets merged, and a shorter commit subject.

**Comment by ashb** [comment]
_And_ you'll have to explain in more detail (here, not in the code) why you think this change is needed.

**Comment by ramandumcs** [comment]
We are observing that occasionally Tasks get stuck in queued state and never get executed by Airflow. On debugging it we found that one of the queued dependency was not met due to which task did not move from queued to running state. So task remained in queued state. (are_dependencies_met function returned false for QUEUE_DEPS inside _check_and_change_state_before_execution).

By looking into scheduler code it seems that scheduler does not reschedule the queued state tasks due to which task never got added to executor queue again and remained stuck in queued state. if RUN_DEPS are not met, task is moved from queued to None state(which gets picked by scheduler for rescheduling) but task remains in queued state ifQUEUE_DEPS are not met. So task should be moved to None/up_for_retry state  if QUEUE_DEPS are not met.

**Comment by ramandumcs** [comment]
@ashb 
It seems semantics of _check_and_change_state_before_execution function is to change the task state to None if RUN_DEPS are not met (so that it can be rescheduled). But It does not change anything if QUEUE_DEPS are not met. i.e task would remain in its current state. As per my understanding a task run(ti.run) can be triggered either by scheduler or through cmd line. And in _check_and_change_state_before_execution function we might not want to change the  state (if QUEUE_DEPS are not met) for tasks trigged via commandline.So it leaves their state as it is.
We have seen couple of instances where task remained stuck in queued state and is picked up by scheduler after restart.
We will debug it further and will check for alternate solutions.
Just wanted to check if this understanding makes sense to you

**Pull request closed without merging**
