### PR TITLE
fixing a typo in the docs

### PR DESCRIPTION
**Pull request by timfeirg**
I've removed the template because I don't think that'll be necessary, just fixing a typo here.

### CODE REVIEW

**Comment by saguziel** [comment]
Please use the template

**Comment by timfeirg** [comment]
I'd rather close than write hundreds of words to explain why I fixed one typo.

**Comment by saguziel** [comment]
You don't have to write a hundred words, the template is there by default.

**Comment by timfeirg** [comment]
There's blanks to fill out inside that template, which requires me to raise a jira issue, write details about my PR, understand and agree that this PR will not be reviewed until everything's checked. I cannot do as it says, and I can't agree to it, because this PR doesn't require any more information other than its diff.

I don't understand why I have to include the template while this PR clearly wouldn't be using any of its contents.

@saguziel

**Comment by nurkiewicz** [comment]
I found this issue because I wanted to fix the exact same typo. I think I'll pass on this one...

**Comment by bolkedebruin** [comment]
Your commit title reads "typo". Typo of what? Are you fixing an off by one error? Are you creating a typo? Commit messages are read without the code attached to them, so they need to be understandable.

Also Apache guidelines require us to have an jira issue for every code change or change in the code. It is there as an audit trail and it is there to protect the users of the code. If you don't like that and don't want to adhere to those guidelines then unfortunately we cannot accept your patch. That's too bad because it is could have been valuable. It isn't now. Hopefully someone will pick it up.

And yes we sometimes we allow [AIRFLOW-XXX] commits. That could have been an option here.

**Comment by timfeirg** [comment]
* every git commit that reads "typo" means it's fixing a typo, but that's just my experience, I've added to the commit message, including the `[AIRFLOW-XXX]` clause.
* I do understand the purpose of Apache guidelines and code audit in general, but this PR is really one typo fix, in the docs, it's not even code change. I think most developers will agree the things in the template are too much for this.

**Pull request closed without merging**
