### PR TITLE
[AIRFLOW-4240] Require POST for state-changing requests

### PR DESCRIPTION
**Pull request by ashb**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-4240

### Description

- [x] To make the requests POSTs and to follow the redirect that the backend
issue I turned the "toggle" buttons in to an actual form, which makes
there much less logic needed to build up the URL - the browser handles
it all for us. The only thing we have to do is set the "action" on the
URL.

  For the "link" ones (delete,trigger,refresh) I wrote a short
`postAsForm` which takes the URL and submits a form. A little bit messy,
but it works.

  No visual change.
### Tests

- [x] Updated

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
This is against the release branch. I  will create a separate one against master.

**Comment by XD-DENG** [comment]
Will need a bit more time for this since occupied by my works. Will try to check asap.

**Comment by ashb** [comment]
@Fokko PTAL if you have time. Once this (and a few other small ready-to-merge PRs are in I'm going to start the RC process for 1.10.3

**Comment by feng-tao** [comment]
Will take a look once in office

**Comment by ashb** [comment]
Thanks @feng-tao

**Review by feng-tao — APPROVED** [review]
I think overall lgtm for the change, but my js knowledge is pretty rusty, and I hope I could give better suggestion for improving the `postAsForm` function :)

cc @verdan our Airflow JS expert. 

But given our tight deadline for 1.10.3, I think we could go as it is if @verdan doesn't have a chance.

**Review by XD-DENG — APPROVED** [review]
Have very limited time today, so only managed to do some functionality tests:
- "toggle" button, trigger, delete, refresh all work fine in my tests
- tests were done for both RBAC and non-RBAC UIs.

**Comment by verdan** [comment]
LGTM 👍 
Very nice improvement overall.

**Pull request merged**
