### PR TITLE
[AIRFLOW-5450] Switching comment from HTML to Jinja.

### PR DESCRIPTION
**Pull request by aijamalnk**
It is causing trouble to the Google Analytics script.

JIRA: https://issues.apache.org/jira/browse/AIRFLOW-5450

Testing for this PR should be done by checking a staged site.

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by aijamalnk** [comment]
r: @mik-laj

**Review by ashb — COMMENTED** [review]
Don't see any problem with this change, but what effect does it have?

**Review by ashb — APPROVED** [review]
Oh, it doesn't like the first node being a comment. Sounds like a bug in GA ;)

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
I am currently working on an PR to asf-site.

**Comment by mik-laj** [comment]
https://github.com/apache/airflow-site/pull/4

**Pull request merged**
