### PR TITLE
Set load_example configuration to False by default.

### PR DESCRIPTION
**Pull request by ghost**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- Example dags are loaded by default in production.

Per Apache guidelines you need to create a [Jira issue](https://issues.apache.org/jira/browse/AIRFLOW/).

Testing Done:
There is current testing for load_examples. 

https://issues.apache.org/jira/browse/AIRFLOW-390

### CODE REVIEW

**Comment by r39132** [comment]
@redundantsun Please follow the guidelines in https://cwiki.apache.org/confluence/display/AIRFLOW/Contributors%27+Guide

Specifically, 
1. Open a Jira (eg. `AIRFLOW-XXX`) and preface your commit and PR with `[AIRFLOW-XXX]`
2. Assign the Jira to yourself
3. Set the "external_issue_url" in that JIRA to point to this PR - in other words, set it to `https://github.com/apache/incubator-airflow/pull/1702`

Once all of this is done, you can ping me here or on gitter.

**Comment by d-lee** [comment]
I don't believe this change is warranted. A real production deployment of airflow requires a number of changes to airflow.cfg anyway (e.g. executor type, Fernet key, most likely a metadata db connection, etc) thus `load_examples` can be changed in production airflow.cfg as well if needed

**Comment by r39132** [comment]
I wonder if we can add some documentation of this feature in the Getting Started guide. I do find myself always disabling this feature. But, the reason this was set to True was for newbies and I don't want to lose that. I feel a reasonable compromise would be to add documentation to the Getting Started guide about turning this on for new users. Additionally, we can remove things that depend on Hive from the examples. That's definitely a no-no. While were on this topic, the test_druid.py dag needs to be moved out of the dag folder.. and moved into contrib/examples.

**Comment by jlowin** [comment]
If accepted, this change needs to be made in both the dictionary AND the template. #1677 removes the dictionary config entirely. 

There is also a unit test that checks if `load_examples=True` that would need to be adjusted.

**Comment by ghost** [comment]
@jlowin What do you mean by template?

**Comment by jlowin** [comment]
@redundantsun sorry for the confusion -- if you look in `configuration.py` you'll see both a dictionary of defaults, the one you modified, and also a string template for `airflow.cfg`. You'll need to add your defaults in both places, preferably with comments in `airflow.cfg`. Also note that when you read the options, you'll want to use `getint()` instead of `get()` as appropriate, since they are stored as strings in airflow.cfg. Let me know if you have any questions!

**Comment by r39132** [comment]
@redundantsun This PR looks like it is abandoned. As part of [cold case PR cleanup](https://cwiki.apache.org/confluence/display/AIRFLOW/Cold-Case+PR+Resolution), I'm able to review and either merge or close this PR. However, I need this PR to be updated within the next 5 days. Let me know how you you would like to proceed. Currently, the PR shows 0 changes.

**Pull request closed without merging**
