### PR TITLE
[AIRFLOW-523] Add AltX as Airflow user

### PR DESCRIPTION
**Pull request by PedroMDuarte**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- [AIRFLOW-523](https://issues.apache.org/jira/browse/AIRFLOW-523)

Testing Done:
- Tests passing in Travis CI

### CODE REVIEW

**Comment by PedroMDuarte** [comment]
Travis CI is passing on my fork.  Looks like a test flakiness issue here.

**Comment by msumit** [comment]
@PedroMDuarte why don't you include your github handle along with the org name.

**Comment by PedroMDuarte** [comment]
@msumit Updted PR, now with my github handle :)

**Comment by r39132** [comment]
@PedroMDuarte Welcome to the community!

**Pull request closed without merging**
