### PR TITLE
Replace old Breeze with Python based implementation

### LINKED ISSUE #22827: Breeze: Update documentation for Breeze2
The documentation should be updated to reflect new Breeze changes.

### PR DESCRIPTION
**Pull request by potiuk**
Over the last few months together with Outreachy interns
we rewrote the most important functionality of the old Bash-based
Breeze with Python Based implementation.

We approached it in systematic way with capturing all our decisions
in the ADR format (dev/breeze/docs) and implementing the parts
that are used on a daily basis by the users. Breeze2 as it was
called is ready for Prime-Time with the users so we are swapping
out the old breeze wiht the new one.

The old `breeze` has been moved to `breeze-legacy` and we will
gradually parts of it that are already migrated to Python and proven
while continue rewriting the parts that are missing (mostly the
maintainer tools) and replacing the remaining CI shell scripts with
the new `breeze` commands.

We also need to make sure that there is no accidental top-level
import for extra packages added in the future, because people
who installed breeze before will not have it - so we have
a pre-commit that checks if breeze.py can be parsed and
--help executed with just rich and click installed.

This PR:

* moves `breeze` to `breeze-legacy`
* moves `Breeze2` to `breeze`
* updates documentation and screenshots where applicable
* explains old vs. new breeze in documentation
* adds protection so that no accidental top-level import is
  added to breeze.py and files imported from there

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @Bowrna  @edithturn

**Comment by potiuk** [comment]
Here it is. 

Switching to Python based Breeze. FINALLY.

Note. I would like to drag your attention to this nicely generated screenshots in our Breeze documentation :) https://github.com/potiuk/airflow/blob/swap-old-breeze-with-new/BREEZE.rst#installation

**Comment by edithturn** [comment]
@potiuk I ran it on my machine (Linux Ubuntu 20.10), wow works very nice! That part of the comments with a click is fantastic 🤩 

I ran some commands like "config"  and "start-airflow". My question is if all these options al already implemented.

* In `config`, I got no output or a warning saying that we set Python as a backend. (Maybe I don't understand exactly how is its  behavior)
* I also ran, `start-airflow`, and **tmux** session is being open on my VSC terminal, (this is so nice 👏🏼 ), my question is in the part of creating permissions (four windows). Am I  doing something wrong to get that error? or I should do an extra step to have it configure it
Screenshot from 2022-04-09 19-07-12




It is fantastic @potiuk and also is 💯 faster on my computer  👏🏼 🚀

**Comment by potiuk** [comment]
> * In `config`, I got no output or a warning saying that we set Python as a backend. (Maybe I don't understand exactly how is its  behavior)

Good Point. We should give feedback to the user ! The idea is that when you set python version, next time you get that default python version when you do not specify any python version. I.e. .

`breeze` -> Python 3.7 used by default
`breeze config --python 3.8` -> python 3.8 set as default
`breeze` -> Python 3.8 used



> I also ran, start-airflow, and tmux session is being open on my VSC terminal, (this is so nice 👏🏼 ), my question is in the part of creating permissions (four windows). Am I doing something wrong to get that error? or I should do an extra step to have it configure it

The errors are unrelated - they are also with current breeze' start-airflow - I will raise that to others as we are very close to cutting 2.3 branch I think those errors need to be fixed before.

**Comment by potiuk** [comment]
Config now is more "obvious". It also prints summary of the config (@edithturn ):

Screenshot 2022-04-10 at 11 11 36

**Comment by potiuk** [comment]
I've also added protection to not add accidentally new top-level imports in breeze.py as they would break auto-complete and self-upgrade.

**Comment by Bowrna** [comment]
@potiuk this is amazing :) you have made this change very quickly 👍

**Comment by potiuk** [comment]
Looks like Green and ready for Python's Breeze prime time!

**Comment by edithturn** [comment]
Go ahead @potiuk, let us know! 🚀 💪🏼

**Comment by potiuk** [comment]
Hwy @eladkal :). That's  IT..

**Review by eladkal — APPROVED** [review]
🎉

**Pull request merged**
