### PR TITLE
[AIRFLOW-3745] Fix viewer not able to view dag details

### PR DESCRIPTION
**Pull request by feng-tao**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3745
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
To stick with existing RBAC which Admin, Op, User, Viewer view all dags.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [ ] Passes `flake8`

### CODE REVIEW

**Comment by feng-tao** [comment]
PTAL @XD-DENG , @kaxil 

Could you test with this pr and see the issue still exists?

**Review by kaxil — COMMENTED** [review]
Can we add test by creating dummy users with each role & check they have correct permissions?

**Comment by XD-DENG** [comment]
Hi @feng-tao , I tried to cherry-pick this change into 1.10.2rc3 (I copied the change in your PR in `airflow/www_rbac/security.py` of 1.10.2rc3), seems something is wrong:

**I tried to log in using accounts with `User`/`Viewer` role, I can see `Security`/`Admin` tabs, and can even create new user or change permission of each roles.** 

I believe this is not desired. Please try and let me know if you can reproduce this issue.

**Comment by feng-tao** [comment]
thanks @XD-DENG , @kaxil , I know what is the issue now. I will work on a pr with test tonight.

**Comment by feng-tao** [comment]
@XD-DENG  correct, I don't think that is the correct behavior.

**Comment by XD-DENG** [comment]
Thanks @feng-tao

**Comment by feng-tao** [comment]
PTAL @XD-DENG , @kaxil , code updated with unit test. I have tried on my end which works(viewer couldn't see the Admin role menu). Could you test it on your end and see if there are any issues?

**Comment by feng-tao** [comment]
CI pass(k8s one is random, transient)

**Comment by XD-DENG** [comment]
Hi @feng-tao , I tried to apply your latest change. But the issue seems still there. Using `Viewer`/`User`, I can still see `Security`/`Admin` menus, and edit inside.

I'm using SQLite. Before testing, I have deleted the earlier .db file and run `initdb` again.

Not sure if I missed anything. @kaxil please help test as well so we can confirm.

Thanks!

**Comment by feng-tao** [comment]
This is the UI for a viewer / user (which doesn't have the security tab) on my end. Do you apply the latest one?
screen shot 2019-01-21 at 9 34 15 pm

**Comment by feng-tao** [comment]
@XD-DENG , could you confirm if you apply this commit(https://github.com/apache/airflow/commit/31bfb65db3282ca31253d38228d0fe4a6de1dcef)?

**Comment by XD-DENG** [comment]
@feng-tao yes, that's what I applied. But please note what I did was applying it against the `www_rbac/security.py` in `1.10.2rc3` (on biz trip with a laptop that I can't install npm). This may be why we got different results?

I trust your testing. May you please test this fix on `1-10-test` as well in case any conflict? Thank you.

**Comment by feng-tao** [comment]
@XD-DENG , I think it shouldn't matter with npm. We only use npm to build the static access which may just cause UI off. But I try with v-10-test branch which I don't see any issues.

@kaxil , do you think you could try out this branch on top v-10-test and see if you still see the issues or not?

cc @seelmann  and see if you could try out and see whether the viewer issue still exists or not.

**Comment by kaxil** [comment]
I will test this tonight. Sorry, we have an Airflow meetup tomorrow so preparing for that as well and I am on the client side as well so can't work on Airflow from 9-5.

**Comment by feng-tao** [comment]
cc @jgao54 in case you have time to try out.

**Review by ashb — COMMENTED** [review]
Does this change mean that the default roles that are created are to some extend un-editable?

**Comment by feng-tao** [comment]
@ashb , the default roles are all editable. This pr is to keep the behavior same as 10.1 which all the default roles could view the dag info detail page without Admin manually intervenes.

**Comment by ashb** [comment]
> @ashb , the default roles are all editable. This pr is to keep the behavior same as 10.1 which all the default roles could view the dag info detail page without Admin manually intervenes.

Thanks. I haven't quite grokked how the RBAC roles and the Security Manager code works yet.

**Comment by jgao54** [comment]
@feng-tao  I think the same thing could be achieved by adding `dag_perms` to viewer under `ROLE_CONFIGS`... which should generate `can_dag_read on all_dags`/`can_dag_edit on all_dags` when `init_role()` method is called in `sync_roles`, assuming that's the goal of this PR.

**Comment by feng-tao** [comment]
thanks @jgao54 , correct, either way should work :)

**Comment by jgao54** [comment]
In that case, less (code) is more :) 
I don't think we need to explicitly sync all_dag access. We explicitly sync admin is because it's not part of ROLE_CONFIGS

**Comment by feng-tao** [comment]
thanks @jgao54 . Will update the pr tonight.

**Comment by feng-tao** [comment]
@jgao54 @XD-DENG  Code is refactored. I tested it locally and worked as expected. Let me know if there is any concern.

@XD-DENG if possible, it would be good if you could test it on your side to verify as well.

**Comment by feng-tao** [comment]
The k8s test failure is unrelated(max time exceed)

**Comment by feng-tao** [comment]
PTAL @kaxil

**Comment by XD-DENG** [comment]
Hi @feng-tao . Have confirmed the fix works well. Thanks!

**Comment by feng-tao** [comment]
assume no concern. Merge now.

**Comment by kaxil** [comment]
Hi guys, sorry I was stuck with work and my health after meetup isn't that good so it got delayed. 

I just tested the viewer role and it works as expected.

image


Thanks @feng-tao and @XD-DENG

**Comment by feng-tao** [comment]
Thanks @kaxil for the confirmation. Takes care.

**Comment by ashb** [comment]
Am I reading this right - does it give Viewer role the ability to edit dags. That seems incorrect? ~Likewise for User which doesn't have any other edit permissions currently.~

**Comment by ashb** [comment]
Am I reading this right - does it give Viewer role the ability to edit dags. That seems ... incorrect?

**Comment by feng-tao** [comment]
@ashb , it came from someone(maybe XD) reporting in the dev alias that viewer could no longer view the same details as in 1.10.1. We never define what should viewer, user permission after introducing the DAG level access. Hence it is better to keep the same ATM. We could revisit the permissions for viewer if we have a consensus. User should have the same permissions as viewer. What do you observe?

**Comment by ashb** [comment]
I'm trying to debug something - I've gone from a 1.10.2 RBAC install to master, and I'm no longer able to pause DAGs

Viewer shouldn't be able to _edit_ anything though, right?

**Comment by feng-tao** [comment]
@ashb , I will submit a pr to address the viewer edit issue today.

**Comment by ashb** [comment]
@feng-tao Okay I've got a reproduction case, I'm not sure which PR it applies to:

1. Start with airflow 1.10.1 in a fresh install
2. Run `AIRFLOW__WEBSERVER__RBAC=true airflow initdb`
3. Run `airflow create_user --username op --password op --role Op --firstname op@localhost --lastname "-" --email "op@localhost"`
4. Log in with op:op
5. You should be able to pause/unpause a DAG (Refresh to check, or look at the status of the request in the browser inspector as the checkbox is updated irrespective of any error returned)
6. upgrade to 1.10.2 (including running `airflow upgradedb`)
7. Try pausing/unpausing again. Check the status - for me it failed.

For me after upgrading to 1.10.2 pause doesn't work and I get a 302 to `/login` instead. Given it's sometime between 1.10.1 and 1.10.2 it's probably not related to this PR.

(You may have to run `airflow scheduler` in there for a short while to get the DAGs in to the DB to enable pause in the Web)

**Comment by ashb** [comment]
A possibly simpler use case: Start with a fresh install on 1.10.2, add a user in the "Op" role and try to pause a DAG :)

**Comment by feng-tao** [comment]
@ashb , let's consolidate all the discussion in one place. And I could do some investigations in my night time(PST time zone). From what I understanding, your issues are:
1. you couldn't pause DAG with op role(https://github.com/apache/airflow/blob/master/airflow/www/views.py#L1657) ? Have you checked whether the refactored UI could pass the `is_paused` param to Flask? For pause, I am pretty sure it is not related to this pr.
2. your comment in https://github.com/apache/airflow/pull/4118#issuecomment-469801650 which all_dags permissions not shown until roles created.  The latest version in master has changed which create the all_dag view-menu when the webserver starts(https://github.com/apache/airflow/blob/master/airflow/www/security.py#L460). And one thing we could do with https://github.com/apache/airflow/pull/4118/files is to make sure all_dags permissions are always exist in the existing roles which means user could only remove non dag permissions. WDYT?

**Comment by ashb** [comment]
1. It never gets to L1657, `@has_dag_access` issues a 302 before the view fn is ever run.

2. I'll cherry-pick this PR (which adds the change you suggest) in to 1.10.3 which will fix the problem for new installs. Adding all_dags to the existing roles (I assume you mean Admin,User,Op, not all roles in the DB?) would "work" but it seems counter to the purpose of #4118, of letting those roles be editable by the admin of the site.

Let me have a look at how we might do this with a migration. If we could (easily, without loads of code) replace all the role syncing code at run time, which would also have the benefit of removing the mildly annoying "duplicate" log lines:

```
[2019-03-05 19:38:25,622] {security.py:437} INFO - Start syncing user roles.
[2019-03-05 19:38:25,634] {security.py:437} INFO - Start syncing user roles.
[2019-03-05 19:38:25,677] {security.py:437} INFO - Start syncing user roles.
[2019-03-05 19:38:25,684] {security.py:437} INFO - Start syncing user roles.
[2019-03-05 19:38:25,988] {security.py:195} INFO - Existing permissions for the role:Viewer within the database will persist.
[2019-03-05 19:38:26,085] {security.py:195} INFO - Existing permissions for the role:Viewer within the database will persist.
[2019-03-05 19:38:26,172] {security.py:195} INFO - Existing permissions for the role:Viewer within the database will persist.
[2019-03-05 19:38:26,183] {security.py:195} INFO - Existing permissions for the role:Viewer within the database will persist.
[2019-03-05 19:38:26,520] {security.py:195} INFO - Existing permissions for the role:User within the database will persist.
[2019-03-05 19:38:26,538] {security.py:195} INFO - Existing permissions for the role:User within the database will persist.
[2019-03-05 19:38:26,692] {security.py:195} INFO - Existing permissions for the role:User within the database will persist.
[2019-03-05 19:38:26,784] {security.py:195} INFO - Existing permissions for the role:User within the database will persist.
[2019-03-05 19:38:27,158] {security.py:195} INFO - Existing permissions for the role:Op within the database will persist.
[2019-03-05 19:38:27,165] {security.py:195} INFO - Existing permissions for the role:Op within the database will persist.
[2019-03-05 19:38:27,166] {security.py:195} INFO - Existing permissions for the role:Op within the database will persist.
[2019-03-05 19:38:27,169] {security.py:346} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2019-03-05 19:38:27,170] {security.py:346} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2019-03-05 19:38:27,173] {security.py:195} INFO - Existing permissions for the role:Op within the database will persist.
[2019-03-05 19:38:27,177] {security.py:346} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2019-03-05 19:38:27,203] {security.py:346} INFO - Fetching a set of all permission, view_menu from FAB meta-table
[2019-03-05 19:38:28,254] {security.py:299} INFO - Cleaning faulty perms
[2019-03-05 19:38:28,266] {security.py:299} INFO - Cleaning faulty perms
[2019-03-05 19:38:28,268] {security.py:299} INFO - Cleaning faulty perms
[2019-03-05 19:38:28,289] {security.py:299} INFO - Cleaning faulty perms
```

(Cos each worker runs the checks, we do this for every worker at start, and then every 30s as the new worker cycles).

**Comment by feng-tao** [comment]
@ashb , I see. Your deploy is based on 1.10.2 not on master? I think I fail to get this pr into 1.10.2 as the release timeline was pretty tight around the time. And I think someone said that just use UI to modify the permissions as a work around.

Currently it only adds to those default roles to keep it the same behaviour as 1.10.1, but not those DAG level roles. And we do plan to write a blog on how we do DAG level access at Lyft, but just don't have enough time ATM. 

In terms of migrations from 1.10.1 to 1.10.2, I am not sure if it is easy to do as Airflow doesn't have the FAB model code which makes the db migration difficult. Let me know if you figure it out the right approach.

**Comment by ashb** [comment]
Correct, yeah I've been testing the v1-10-stable branch to prepare 1.10.3 - though the problem would also apply to any upgraded install from 1.10 to what becomes master.

So I feel we need to fix this in some way that gives an upgrade path form 1.10.x now to 2.0 as it will be - that doesn't involve manually adding things in the UI.

**Comment by feng-tao** [comment]
@ashb , https://github.com/apache/airflow/pull/4845 for removing viewer edit permissions.

**Comment by feng-tao** [comment]
correct, we shouldn't rely on UI for the operations...

**Comment by ashb** [comment]
I'm sort of picturing something like (very pseudo code):

```python
from something import role_migrations as rm

def up():
    p = rm.add_permission('all_dags', 'can_dag_edit')
    rm.add_to_role('Op', p)

def down():
    rm.remove_from_role('Op', 'all_dags', 'can_dag_edit')
```

I haven't worked out the details yet, still a bit hazy (and I'm not 100% on the FAB data model around permissions, view menus, roles and all the many-to-many tables between them.)

**Comment by feng-tao** [comment]
@ashb https://flask-appbuilder.readthedocs.io/en/latest/diagrams.html FYI

**Comment by XD-DENG** [comment]
I have a question to seek @feng-tao ‘s input given we have started the discussion on this: currently Admin’s permissions will always be updated so it has ALL permissions, including each DAG’s “can_dag_view” and “can_dag_edit”. 

Let’s say we have 1000 DAGs now: then 2000 permissions will be added to Admin role in DB, and all of them will also be shown in UI if we go to Security->Roles. 

This may not be necessary as Admin role already has “can_dag_view” and “can_dag_edit” on “all_dags”. (but from another side, I also understand it’s easier to just simply give Admin ALL permissions) 

May you let me know your thoughts on this?

**Comment by feng-tao** [comment]
@XD-DENG , I don't think it will add 2000 entries to the db for admin role. It only adds the "all_dags" view-menu with the 2 permissions into the table.

**Comment by XD-DENG** [comment]
Thanks @feng-tao .
let me double-check the code later today and will let you know if I still have confusion on it.

**Comment by ashb** [comment]
Oh thanks, I hadn't seen that diagram!

**Comment by XD-DENG** [comment]
> @XD-DENG , I don't think it will add 2000 entries to the db for admin role. It only adds the "all_dags" view-menu with the 2 permissions into the table.

Hi @feng-tao please refer to https://github.com/apache/airflow/blob/dda309e66224346014ca42a0bcce4f53365f1118/airflow/www/security.py#L440-L453  By checking the code itself, seems it's simply adding all whatever permissions to Admin role.

Below is the version before my `set`-related refactoring:
https://github.com/apache/airflow/blob/c552996483f5aab5e31793317b26aba62c13332e/airflow/www/security.py#L440-L452

**Comment by feng-tao** [comment]
@XD-DENG somehow I thought it has only all_dags , but it seems it has everything. ATM, I didn't have time to dig deep to do this without a hacky solution.

I would suggest let's leave it as it is for now.

**Comment by XD-DENG** [comment]
@feng-tao sure. Maybe let me create a ticket for this later maybe. Will tag you then for our reference.

**Comment by ashb** [comment]
@feng-tao I haven't managed to finish it but I got somewhere with migrations to deal with perms:

https://gist.github.com/ashb/f43741740fb0eae59948d52634cda575

The biggest issue is working out 1) what query to run, or 2) working out how to call the right classes/methods from within fab.security.* to update.

**Comment by feng-tao** [comment]
@ashb , thanks. BTW, what do you think of moving https://github.com/apache/airflow/blob/master/airflow/www/security.py#L35-L140 inside AirflowSecurityManager so that we could redefine permission on different roles by subclassing the security manager?

**Comment by ashb** [comment]
Yes that probably makes sense to do.

**Comment by feng-tao** [comment]
@ashb , pr posted (https://github.com/apache/airflow/pull/4960)

**Pull request merged**
