### PR TITLE
[AIRFLOW-XXX] Extract operators and hooks to separate page

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
```
git diff apache/master:./integration.rst operators-and-hooks-ref.rst
```
```diff
diff --git a/docs/integration.rst b/docs/operators-and-hooks-ref.rst
index e9155bcd8..6c8085895 100644
--- a/docs/integration.rst
+++ b/docs/operators-and-hooks-ref.rst
@@ -15,8 +15,8 @@
     specific language governing permissions and limitations
     under the License.
 
-Integration
-===========
+Operators and Hooks Reference
+=============================
 
 .. contents:: Content
   :local:
@@ -29,11 +29,8 @@ ASF: Apache Software Foundation
 
 Airflow supports various software created by `Apache Software Foundation <https://www.apache.org/foundation/>`__.
 
-Operators and Hooks
-'''''''''''''''''''
-
 Software operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within software developed by Apache Software
 Foundation.
@@ -113,7 +110,7 @@ Foundation.
 
 
 Transfer operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to copy data from/to software developed by Apache Software
 Foundation.
@@ -183,18 +180,8 @@ Azure: Microsoft Azure
 
 Airflow has limited support for `Microsoft Azure <https://azure.microsoft.com/>`__.
 
-Logging
-'''''''
-
-Airflow can be configured to read and write task logs in Azure Blob Storage.
-See :ref:`write-logs-azure`.
-
-
-Operators and Hooks
-'''''''''''''''''''
-
 Service operators and hooks
-"""""""""""""""""""""""""""
+'''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within the Microsoft Azure.
 
@@ -271,19 +258,10 @@ AWS: Amazon Web Services
 
 Airflow has support for `Amazon Web Services <https://aws.amazon.com/>`__.
 
-Logging
-'''''''
-
-Airflow can be configured to read and write task logs in Amazon Simple Storage Service (Amazon S3).
-See :ref:`write-logs-amazon`.
-
-Operators and Hooks
-'''''''''''''''''''
-
 All hooks are based on :mod:`airflow.contrib.hooks.aws_hook`.
 
 Service operators and hooks
-"""""""""""""""""""""""""""
+'''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within the Amazon Web Services.
 
@@ -472,20 +450,10 @@ Airflow has extensive support for the `Google Cloud Platform <https://cloud.goog
 See the :doc:`GCP connection type <howto/connection/gcp>` documentation to
 configure connections to GCP.
 
-Logging
-'''''''
-
-Airflow can be configured to read and write task logs in Google Cloud Storage.
-See :ref:`write-logs-gcp`.
-
-
-Operators and Hooks
-'''''''''''''''''''
-
 All hooks are based on :class:`airflow.contrib.hooks.gcp_api_base_hook.GoogleCloudBaseHook`.
 
 Service operators and hooks
-"""""""""""""""""""""""""""
+'''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within the Google Cloud Platform.
 
@@ -665,7 +633,7 @@ These integrations allow you to perform various operations within the Google Clo
 
 
 Transfer operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to copy data from/to Google Cloud Platform.
 
@@ -778,7 +746,7 @@ Cloud Platform.
     `source code <https://github.com/apache/airflow/tree/master/airflow/gcp/example_dags/>`_ of the particular example DAGs.
 
 Other operators and hooks
-"""""""""""""""""""""""""
+'''''''''''''''''''''''''
 
 .. list-table::
    :header-rows: 1
@@ -800,11 +768,8 @@ Other operators and hooks
 Service integrations
 --------------------
 
-Operators and Hooks
-'''''''''''''''''''
-
 Service operators and hooks
-"""""""""""""""""""""""""""
+'''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within various services.
 
@@ -925,7 +890,7 @@ These integrations allow you to perform various operations within various servic
      -
 
 Transfer operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within various services.
 
@@ -957,11 +922,8 @@ These integrations allow you to perform various operations within various servic
 Software integrations
 ---------------------
 
-Operators and Hooks
-'''''''''''''''''''
-
 Software operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations using various software.
 
@@ -1075,7 +1037,7 @@ These integrations allow you to perform various operations using various softwar
 
 
 Transfer operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to copy data.
 
@@ -1158,11 +1120,8 @@ These integrations allow you to copy data.
 Protocol integrations
 ---------------------
 
-Operators and Hooks
-'''''''''''''''''''
-
 Protocol operators and hooks
-""""""""""""""""""""""""""""
+''''''''''''''''''''''''''''
 
 These integrations allow you to perform various operations within various services using standardized
 communication protocols or interface.

```

**Review by feluelle — COMMENTED** [review]
Should we make a note about that change somewhere?

**Comment by mik-laj** [comment]
This is a change in the documentation, not the behavior of the product. The notes should be made of non-backward compatible changes in the product. If you are worried about a link then all links are not necessary either. Note that all links will stop working when we introduce [AIP-11](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-11+Create+a+Landing+Page+for+Apache+Airflow?src=contextnavpagetreemode). I'm working on it also.

**Comment by feluelle** [comment]
How should users know that the `Integration` has moved to `Operators and Hooks`? I think it is an important change like the AIP. The website will also be announced so why not the reference for all hooks and operators. If you think it is obvious enough we don't need to mention it anywhere. I am not sure if it is that obvious.

**Comment by mik-laj** [comment]
The user will read the document and find a link to the second page in it. 

This is not very important change, because users should use a link to specific version of documentation. I don't think the documentation has to be backward compatible. 

A new site will be released in about a month. All links will be changed and documentation versioning will be introduced. This change will appear in January and then it will definitely not matter if it is a backward compatible change. It is worth noting that when we introduced the automatic generation of API refernece we were also not worried about backwards compatibility. The problem of backward  compatibility concerns the aspect of publishing documentation, but not creating documentation.  Airflow documentation was not versioned on the website and hence the problem with backward compatibility. Airflow documentation was not versioned on the website and hence the problem with backward compatibility.

**Comment by mik-laj** [comment]
To be precise, the documentation was versioned, but links to old versions were not made public.
For example: 
http://airflow.apache.org/1.10.2/
http://airflow.apache.org/1.10.3/
http://airflow.apache.org/1.10.4/

**Comment by potiuk** [comment]
I agree with @mik-laj, Integration.rst was really  "a bag of everything" (see it [here](https://airflow.readthedocs.io/en/latest/integration.html)).

With those changes where we restructure it and separate out types of integration, it is much easier to navigate with the changes above. And we are not removing any information - quite contrary we are adding a lot of "overview" information by having all the tables and splitting integration.rst in a more meaningful way.

@feluelle -> are you afraid that people are used to the old structure of documentation or just linked to the old documentation with URL links ? 

If it's the first, I think it's really well known in the community that we are working on improving documentation so they won't be surprised.

@mik-laj - maybe we can involve the community a bit more and ask them what they think (after the merge - it will be easier via "readthedocs") ? 

I think AIP is a bit overkill for this. However we could just explain community a bit more context - why we are doing it and let and let them see it before we "release it", that would be really nice and  give the community a chance to comment and influence it.

**Comment by feluelle** [comment]
> With those changes where we restructure it and separate out types of integration, it is much easier to navigate with the changes above. And we are not removing any information - quite contrary we are adding a lot of "overview" information by having all the tables and splitting integration.rst in a more meaningful way.

Don't get me wrong - I totally like it. I just thought it would be helpful for people to know where the "new" site has been moved to.

> @mik-laj - maybe we can involve the community a bit more and ask them what they think (after the merge - it will be easier via "readthedocs") ?

👍

> I think AIP is a bit overkill for this. However we could just explain community a bit more context - why we are doing it and let and let them see it before we "release it", that would be really nice and give the community a chance to comment and influence it.

No I meant it gets as much attention as AIP 11 does. Because basically without this document you won't have any documentation about the services + hooks + operators which are integrated into airflow.

**Review by feluelle — APPROVED** [review]
I am fine with it :)

**Pull request merged**
