### PR TITLE
Prevent race condition in trying to collect result from DagFileProcessor

### PR DESCRIPTION
**Pull request by ashb**
A rare race condition was noticed in the Scheduler HA PR where the
"test_dags_with_system_exit" test would occasionally fail with the
following symptoms:

- The pipe was "readable" as returned by
  `multiprocessing.connection.wait`
- On reading it yielded an EOFError, meaning the other side had closed
  the connection
- But the process was still alive/running

This previously would result in the Manager process dying with an error.

This PR makes a few changes:

- It ensures that the pipe is simplex, not duplex (we only ever send one
  data) as this is simpler
- We ensure that the "other" end of the pipe is correctly closed in both
  parent and child processes. Without this the pipe would be kept open
  (sometimes) until the child process had closed anyway.
- When we get an EOFError on reading and the process is still alive, we
  give it a few seconds to shut down cleanly, and then kill it.

---

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ashb** [comment]
This is mostly only a problem for dags with `system.exit()` in it, and is made much much worse by running tests with code coverage enabled.

**Comment by ashb** [comment]
This was noticed because it started happening a lot more in #10956

**Review by kaxil — APPROVED** [review]

**Comment by ashb** [comment]
With extra logging in scheduler HA this was what we saw:

```
[2020-10-05 22:39:36,362] {{scheduler_job.py:298}} WARNING - TEST: EOFError received on <DagFileProcessorProcess file_path='/opt/airflow/tests/dags_with_system_exit/a_system_exit.py'>
Traceback (most recent call last):
  File "/opt/airflow/airflow/jobs/scheduler_job.py", line 291, in done
    self._result = self._parent_channel.recv()
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
[2020-10-05 22:39:36,364] {{scheduler_job.py:307}} WARNING - TEST: process 9709 still alive <DagFileProcessorProcess file_path='/opt/airflow/tests/dags_with_system_exit/a_system_exit.py'>
```

**Comment by ashb** [comment]
One failure with exit 137 only. Merging.

**Pull request merged**
