### PR TITLE
[AIRFLOW-2909] Deprecate airflow.operators.sensors module

### PR DESCRIPTION
**Pull request by tedmiston**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2909
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR removes the now deprecated for 2.0 `airflow.operators.sensors` module and updates all references to its sensors to use the new `airflow.sensors.foo_sensor` layout.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Deprecated functionality.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by tedmiston** [comment]
It looks like @Fokko authored and @bolkedebruin committed the new sensors layout backwards compatibility for < 2.0 (https://github.com/apache/incubator-airflow/commit/6f00f722ba4dd8d35c7e172dcba715d5b4b8d216, https://github.com/apache/incubator-airflow/commit/33c720421208696c9cae422e1056c8e914d3329b), so perhaps either / both would be a good reviewer for this PR.

**Review by Fokko — DISMISSED** [review]
Thanks @tedmiston for picking this up, could you remove these references as well?
```
MacBook-Pro-van-Fokko:incubator-airflow fokkodriesprong$ grep -R "airflow.operators.sensors" .
grep: ./airflow/www/static/docs: No such file or directory
grep: ./airflow/www_rbac/static/docs: No such file or directory
./build/lib/airflow/contrib/sensors/sftp_sensor.py:from airflow.operators.sensors import BaseSensorOperator
./build/lib/airflow/contrib/sensors/hdfs_sensors.py:from airflow.operators.sensors import HdfsSensor
./build/lib/airflow/contrib/operators/fs_operator.py:from airflow.operators.sensors import BaseSensorOperator
```

**Comment by tedmiston** [comment]
@Fokko Sure, I just checked and I do not have this `build` directory in my incubator-airflow.  Is it possible that those files you're seeing locally are cached from a setuptools build or something?

**Comment by feng-tao** [comment]
lgtm

**Comment by feng-tao** [comment]
@Fokko , I think the files are from your local build dir. I can't find from my repo.

**Comment by feng-tao** [comment]
lgtm. @Fokko , I think those are from your local build dir. I can't find those in my repo.

**Comment by Fokko** [comment]
@tedmiston @feng-tao Oops, yes, this is some old build stuff dangling around in my airflow folder. Are we going to do `1.10.1` or directly to `2.0.0`?

**Comment by tedmiston** [comment]
I'm hoping straight to 2.0 as I've already had 1 PR merged that fully deprecates a "this will be deprecated soon" type feature (https://github.com/apache/incubator-airflow/pull/3695).  In either case, I suppose we have a trunk for 1.10 now.  On the Jira issue, I've marked this as ≥ 2.0.

**Comment by Fokko** [comment]
Makes sense @tedmiston Thanks!

**Comment by Fokko** [comment]
@tedmiston We still missed this one: https://github.com/apache/incubator-airflow/pull/3808/files

**Pull request merged**
