### PR TITLE
[AIRFLOW-3318] BigQueryHook check if dataset exists

### PR DESCRIPTION
**Pull request by ryanyuan**
Add a function to BigQueryHook to check the existence of a dataset. 
Return True if the dataset exists.
Return False if 404 error received.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow-3318](https://issues.apache.org/jira/browse/AIRFLOW-3318) issues and references them in the PR title. 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
To check the existence of a dataset in BigQuery, existing BigQueryHook only supports either 1) using get_datasets_list() to get all the datasets and then searching the target dataset from the list; or 2) using get_dataset().

However, with get_dataset(), it raises AirflowException whenever an HttpError received. So it has no capabilities to determine if the dataset exists or not.

To solve this issue, I've added a function to return a boolean value representing the existence of the dataset.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
tests.contrib.hooks.test_bigquery_hook:TestDatasetsOperations.test_check_dataset_exists
tests.contrib.hooks.test_bigquery_hook:TestDatasetsOperations.test_check_dataset_exists_not_exist

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by kaxil — CHANGES_REQUESTED** [review]
We already have a `get_dataset` method that does similar thing : https://github.com/apache/incubator-airflow/blob/23d324a2fa0dd920c06b745bf070a3eba6c8155b/airflow/contrib/hooks/bigquery_hook.py#L1438

Hence, I don't feel we should add a new method

**Comment by ryanyuan** [comment]
@kaxil At the moment, the get_dataset does not check the status of the response if any HttpErrors get caught. It only raises AirflowException so that there is no way for me to find out if the dataset doesn't exist, or something else happen. 

I can modify the get_dataset so that it returns None if 404 gets caught.

**Comment by xnuinside** [comment]
@ryanyuan,` It only raises AirflowException so that there is no way for me to find out if the dataset doesn't exist, or something else happen. ` - it put out response of server with full description and error code, or you don't want to raise error if 404? Why you cannot do try catch in code there you use this hook? I don't think what it's correct 'silence' errors from external APIs in hooks, because it's not operators and this method is get_dataset, not check exist or not - it's return dataset_info. But I'm syre what it's incorrect copy-paste full code just for except code == 404 - it could be done anythere there you call this code. When I adding this hook I talk with @kaxil  what maybe make sence add CheckDatasetOperator.  @kaxil, what do you think?

**Comment by kaxil** [comment]
Correct @xnuinside

**Pull request closed without merging**
