### PR TITLE
Update example DAG for AI Platform operators

### PR DESCRIPTION
**Pull request by vuppalli**
---
The AI platform example DAG had typos, was using older versions, and had deprecated operators. This PR is an attempt to fix these problems and corresponds to [this Github issue](https://github.com/apache/airflow/issues/9418). The relevant documentation will be updated soon (most likely next week), which corresponds to [this Github issue](https://github.com/apache/airflow/issues/8207). I look forward to getting feedback!

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by vuppalli** [comment]
@mik-laj Would you happen to know why two checks failed? And if so, how do you recommend fixing the issues?

**Review by mik-laj — APPROVED** [review]
These are flaky tests. We have problems with the stability of integration tests recentlly.

**Comment by mik-laj** [comment]
@vuppalli Fantastic contribution! What's next? 🐅

**Comment by vuppalli** [comment]
@mik-laj Thank you! I am currently updating the accompanying documentation (https://github.com/apache/airflow/issues/9418) :)

**Pull request merged**
