### PR TITLE
MAINT Fix Incorrect FutureWarning in 2,10

### LINKED ISSUE #43794: Incorrect FutureWarning possibly caused by a missing PR in 2.10.3
### Apache Airflow version

2.10.3

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

In Airflow 2.10.3 `configuration.py` file, we have

https://github.com/apache/airflow/blob/c99887ec11ce3e1a43f2794fcf36d27555140f00/airflow/configuration.py#L857-L859

The `self.sensitive_config_values` returns both `('database', 'sql_alchemy_conn')` and `('core', 'sql_alchemy_conn')` because in 2.10.3 the [deprecated_options](https://github.com/apache/airflow/blob/c99887ec11ce3e1a43f2794fcf36d27555140f00/airflow/configuration.py#L328) variable is not empty. I think it's supposed to be removed. See https://github.com/apache/airflow/pull/42126.

Hence the `self.get()` raises a warning:

```
airflow/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
```

Which confuses our users.

### What you think should happen instead?

The warning should not be raised.

### How to reproduce

1. `pip` Install Airflow 2.10.3
2. Run cli `$ airflow version`

### Operating System

Debian GNU/Linux 10 (buster)

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other Docker-based deployment

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SuccessMoses**
Fixes #43794

In airflow version 2.10, removed deprecation warning for `sql_alchemy_conn` and others in `[core]` instead of `[database]` in `airflow.cfg`

### CODE REVIEW

**Comment by potiuk** [comment]
It's not the right fix. Rather than removing the old values from deprecated list, we should suppress the warnings in this particular case where we check for sensitive values.

**Comment by zachliu** [comment]
> It's not the right fix. Rather than removing the old values from deprecated list, we should suppress the warnings in this particular case where we check for sensitive values.

isn't this my bandit fix? :grin: i just added `with self.suppress_future_warnings():` before

https://github.com/apache/airflow/blob/c99887ec11ce3e1a43f2794fcf36d27555140f00/airflow/configuration.py#L859

**Comment by potiuk** [comment]
> isn't this my bandit fix? 😁 i just added with self.suppress_future_warnings(): before

Yep. That's what it should be

**Comment by zachliu** [comment]
> suppress the warnings in this particular case where we check for sensitive values.

okie doke

https://github.com/apache/airflow/pull/44148

**Comment by potiuk** [comment]
Closing. Fixed by #44148

**Pull request closed without merging**
