### PR TITLE
Generated backport providers readmes/setup for 2020.10.29

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
I also standardised the names and capitalisation of the generated README/.py/config files.

**Comment by potiuk** [comment]
Updaed with the archive URL fix

**Comment by potiuk** [comment]
BTW. I am releasing all of them due to the .tar.gz installability fix

**Comment by potiuk** [comment]
Hey @kaxil -> I think that one will be good. I need it to release the providers :)

**Comment by potiuk** [comment]
FYI - I would love to release backport packages today while there are no changes to providers coming (otherwise I will have to regenerate the changed readimes).

**Review by kaxil — APPROVED** [review]

**Comment by QuinRiva** [comment]
I noticed that PIP requirements are still <2.0.0 for most Google libraries, are there known issues with the current 2.0 libraries?  I've been running 2020.6.24 without issues, but can't update to the backports because they are listed as being incompatible with the Google 2.0.0 packages.

**Comment by potiuk** [comment]
Yes. Github Libraries 2.0.0 are largely a rewrite and they are not backwards compatible in many cases. There are many breaking changes, and while google provides scripts that help with migration, this is a huge effort to convert to those libraries. This is something we plan to do after Airflow 2.0 release. Stay tuned.

**Pull request merged**
