### PR TITLE
[AIRFLOW-1164] No example connections if load_examples is False

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/1164) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-1164

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
If core/load_examples is set to false, the example connections are not added to the database when calling `airflow initdb`

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by NielsZeilemaker** [comment]
Any update on this pull request? Do you guys have any remarks?

**Comment by NielsZeilemaker** [comment]
@bolkedebruin is this something which could be merged? if you i'll resolve the conflicts

**Comment by ashb** [comment]
(Not a core contributor)

This possibly already exists in the form of the `airflow upgradedb` command that will just apply the migrations, but won't create any of the sample connections or reports.

**Comment by NielsZeilemaker** [comment]
@ashb we're running a docker container which always calls `airflow initdb`. 
Having set `load_examples` to `False` we expected the example_connections to also not be loaded. As the documentation says:
```
Whether to load the examples that ship with Airflow. It's good to
get started, but you probably want to set this to False in a production
environment
```

**Comment by ashb** [comment]
@NielsZeilemaker Possibly this change makes sense, or possible the docs (and the docker image) should be updated to say "use `upgradedb` in production).

**Pull request closed without merging**
