### PR TITLE
Fix s3 bucket setup code

### PR DESCRIPTION
**Pull request by gwax**
lstrip will strip 's' and '3' from the beginning of bucket names. we should be removing the first 3 characters (which are already confirmed to be 's3:' and then lstrip on '/'. This fixes that problem and brings the two places we access s3 buckets into a more unified style of code.

### CODE REVIEW

**Comment by gwax** [comment]
This code does not fully solve the problem. I am going to keep working and will notify when the fix actually works.

**Comment by gwax** [comment]
It looks like the logging is currently having issues indirectly related to s3 whereby the "os.path.exists" call right after "import boto" is returning False in the current master. It seems like the files are never being created.

I have rebased this branch back to an older version that was working for us.

**Comment by gwax** [comment]
This PR is currently working to fix the s3:/ issue relating to a misuse of lstrip but there are other issues present in master which are preventing the log files from being written in the first place.

**Comment by artwr** [comment]
@gwax Closing this because it has been superseded by work done  https://github.com/airbnb/airflow/pull/1228.

**Pull request closed without merging**
