### PR TITLE
Move help message to the google auth code

### PR DESCRIPTION
**Pull request by potiuk**
The "google-auth" 2.16.2 just released, removed the _HELP_MESSAGE that was imported by google provider auth util thus failing the imports in canary builds of ours attempting to upgrade to newver versions of released libraries.

This PR inlines the original help message into our code to make it independent from google-auth package version used.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Should fix failing "canary" main build.

**Comment by uranusjr** [comment]
I wonder if we should just move all the underscore variables.

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
> I wonder if we should just move all the underscore variables.

Yeah. I was on the fence with this one, but I realized this is far more than our test's problem. Right now if anyone uses old google provider with the new google auth, it will miserably fail, so the risk of having the imports are far bigger than inlining all the imports there. cc: @eladkal - this one SHOULD be included in the new wave of providers, as soon we might be flooded with "google provider stopped working" and we will have no other workarounds for those users but "downgrade google-auth package  to 2.16.1. When we release this in the provider, we will also be able to tell them "upgrade google provider".

**Comment by potiuk** [comment]
inlined all the constants now.

**Comment by eladkal** [comment]
> cc: @eladkal - this one SHOULD be included in the new wave of providers
Ok waiting for merge

**Comment by potiuk** [comment]
merged @eladkal

**Comment by potiuk** [comment]
Oups. I merged a bit too much. Will remove the code from _vendor that was accidentally added here

**Comment by potiuk** [comment]
#29895  removes the accidental additions

**Pull request merged**
