### PR TITLE
[AIRFLOW-2874] Enables FAB's theme support

### PR DESCRIPTION
**Pull request by verdan**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow 2874](https://issues.apache.org/jira/browse/AIRFLOW-2874) issues and references them in the PR title.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
In an effort to make Apache Airflow a white label application, we should enable the FAB's theme support. Users can then easily change the theme according to their needs. There already exists a configuration to set the Navbar Color, that can be used in conjunction with the theme option, or can simply be unset to fully utilize the theme. List of available themes are available here: https://github.com/dpgaspar/Flask-AppBuilder-Skeleton/blob/master/config.py#L88
_Note: Some of the dark themes might not work properly because of the charts that we are using at the moment._
Here are some of the screenshots from different themes:

screen shot 2018-08-08 at 11 41 17 am

screen shot 2018-08-08 at 11 42 05 am

screen shot 2018-08-08 at 11 42 48 am

screen shot 2018-08-08 at 11 43 20 am

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by feluelle** [comment]
Hey @verdan,

Thank you for adding theme support. 
What is 2nd theme (green one)? I could not find it in the available themes.

**Comment by verdan** [comment]
@feluelle the list of all available theme is attached in the description of this PR. I used random to make the screenshots.

**Comment by feluelle** [comment]
I tried almost all of them. There are even [more](https://github.com/dpgaspar/Flask-AppBuilder/tree/master/flask_appbuilder/static/appbuilder/css/themes). But I couldn't find one that work properly.

**Comment by feluelle** [comment]
webserver_config.py:
`APP_THEME = "bootstrap-theme.css"  # default bootstrap`
airflow.cfg:
`#navbar_color = #007A87`

screen shot 2019-01-23 at 11 53 36

Release 1.10.2

**Comment by feluelle** [comment]
I found one that looks nice when changing the `navbar_color` to the theme's main color.

webserver_config.py:
`APP_THEME = "flatly.css"`
airflow.cfg:
`navbar_color = #18bc9c` (flatly main color)

screen shot 2019-01-23 at 13 30 39

**Comment by darrenhaken** [comment]
How do you set this in `airflow.cfg` or is there another way to enable it? @verdan?

**Comment by manugarri** [comment]
I agree with @darrenhaken , it would be awesome to be able to use this  maybe you can add to the airflow docs how to use the styles  @verdan?

**Comment by mik-laj** [comment]
I am introducing SCSS support in one PR.
https://github.com/apache/airflow/pull/4823
This will make creating new themes much easier.

**Comment by ashb** [comment]
The problem right now is that the APP_THEME setting (which lives in `webserver_config.py`) is hard-coded to look under `/static/appbuilder/css/themes/$APP_THEME` - i.e. to use a custom theme, you have to place it inside the installed flask_appbuilder package folder in site-packages!

**Comment by manugarri** [comment]
@ashb  I see, its not ideal to have to modify appbuilder internal files.

**Comment by ashb** [comment]
Yup, not great at all. See https://github.com/dpgaspar/Flask-AppBuilder/issues/504, and if we don't fix it there in FAB we can fix something oursleves in Airflow.

**Comment by holandes22** [comment]
Seems that the flash backgrounds are missing when using themes. 

Screen Shot 2019-04-03 at 15 33 20

Found this ticket https://github.com/apache/airflow/pull/3903/files that fixed it from the default theme, but doesn't seem to apply to themes.

did anyone else encounter this?

**Comment by ashb** [comment]
@holandes22 Yeah, that fix should probably be removed from that file (which is not loaded when using an alternate them) and put in our other css file.

**Comment by holandes22** [comment]
@ashb any direction on which is the correct CSS file to place the fix? I'll gladly send a PR, but need some guidance on that

**Comment by ashb** [comment]
@holandes22 Take out of bootstrap-theme.css and put in our main.css

**Pull request merged**
