### PR TITLE
[AIRFLOW-2872] Implement 'Ad Hoc Query' for RBAC and Refine QueryView()

### PR DESCRIPTION
**Pull request by XD-DENG**
### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2872
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

To implement the **Ad Hoc Query** view for RBAC under `/www_rbac`. It's mainly based on the current implementation in `/www`.

In addition, the implementation of `QueryView()` class is refined as listed below:

- 1. The `.csv` button in `Ad Hoc Query` actually downloads a plain text file, while it should be a CSV file. Plain text file works too after changing extension to '.csv', but it would be nicer to directly respond with a CSV file.
This is addressed by changing `mimetype` to `text/csv`.

- 2. Argument `has_data` which is passed to the template is not used at all in the template `airflow/query.html` (https://github.com/apache/incubator-airflow/blob/master/airflow/www/templates/airflow/query.html). It can be removed in the `self.render()`.

- 3. We should respond with a CSV file only when user opts in for '.csv' AND the data is available ('df' is generated).  Otherwise we will encounter error below:  `UnboundLocalError: local variable 'df' referenced before assignment`.

- 4. `result = df.to_html(...)` should only be invoked when user does NOT choose '.csv'. Otherwise it's a waste of resource to invoke `df.to_html()` since the result it returns will not be used at all if user asks for CSV downloading instead of a html page.

- 5. remove a commented line.

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @bolkedebruin , sure. Will go ahead to implement the Ad Hoc Query in rbac and revise the PR accordingly. Thanks.

**Comment by XD-DENG** [comment]
Hi @bolkedebruin , as suggested, I have implemented the **Ad Hoc Query** view for RBAC under `/www_rbac`. It's mainly based on the current implementation in `/www`. 

I have updated the subject and contents of this PR accordingly as well.

**Screenshot - Nav Bar**
screen shot 2018-08-09 at 12 38 04 pm

**Screenshot - *Ad Hoc Query* view**
screen shot 2018-08-09 at 12 37 19 pm

**Comment by feng-tao** [comment]
1. All the js, css are unnecesary as they are managed by npm.
2. More importantly, Ad HOC query UI is deprecated by RBAC UI due to security concern (https://github.com/apache/incubator-airflow/blob/master/UPDATING.md).

Hence I am not sure if we need this change.

**Comment by feng-tao** [comment]
cc @bolkedebruin  who gave the initial comment.

**Comment by XD-DENG** [comment]
Thanks @feng-tao .  

Not sure whether Ad Hoc Query can be considered safe under `Admin` role. But given it's a decision already made by the community,  I'm totally ok and fully understand the reasons for what the decision was made. @bolkedebruin please given your input?

On the other hand, would it be worthwhile to merge my change on file [`airflow/www/views.py`](https://github.com/apache/incubator-airflow/pull/3718/files#diff-948e87b4f8f644b3ad8c7950958df033) (which was the initial purpose of this PR)? It's a refinement on the `/www`. It may be up to how soon we're going to remove `/www`. 

Thanks.

**Pull request closed without merging**
