### PR TITLE
[AIRFLOW-5730] Enable get_pandas_df on PinotDbApiHook

### PR DESCRIPTION
**Pull request by sekikn**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5730
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Currently, DruidDbApiHook and PinotDbApiHook disable their get_pandas_df
methods by raising NotImplementedError. But they actually work as
inherited from DbApiHook. This PR enables them.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

TestDruidHook.test_get_pandas_df in tests/hooks/test_druid_hook.py
TestPinotDbApiHook.test_get_pandas_df in tests/contrib/hooks/test_pinot_hook.py

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by sekikn** [comment]
Sorry, I submitted a wrong PR mistakenly. Will update it later.

**Comment by OmerJog** [comment]
Same issue as https://github.com/apache/airflow/pull/6057 ?

**Comment by sekikn** [comment]
Oh, Thanks! I missed that issue. I'll change my JIRA issue and this PR only about Pinot.

**Comment by sekikn** [comment]
Updated the PR. The CI failure seems to be a transient one. The newly added test works on my local environment, as follows:

```
$ git diff upstream/master 
diff --git a/airflow/contrib/hooks/pinot_hook.py b/airflow/contrib/hooks/pinot_hook.py
index e617f8e9b..0864b3584 100644
--- a/airflow/contrib/hooks/pinot_hook.py
+++ b/airflow/contrib/hooks/pinot_hook.py
@@ -90,8 +90,5 @@ class PinotDbApiHook(DbApiHook):
     def set_autocommit(self, conn, autocommit):
         raise NotImplementedError()
 
-    def get_pandas_df(self, sql, parameters=None):
-        raise NotImplementedError()
-
     def insert_rows(self, table, rows, target_fields=None, commit_every=1000):
         raise NotImplementedError()
diff --git a/tests/contrib/hooks/test_pinot_hook.py b/tests/contrib/hooks/test_pinot_hook.py
index 72cee01ea..489af15aa 100644
--- a/tests/contrib/hooks/test_pinot_hook.py
+++ b/tests/contrib/hooks/test_pinot_hook.py
@@ -34,6 +34,7 @@ class TestPinotDbApiHook(unittest.TestCase):
         self.conn.conn_type = 'http'
         self.conn.extra_dejson = {'endpoint': 'pql'}
         self.cur = mock.MagicMock()
+        self.conn.cursor.return_value = self.cur
         self.conn.__enter__.return_value = self.cur
         self.conn.__exit__.return_value = None
 
@@ -74,3 +75,14 @@ class TestPinotDbApiHook(unittest.TestCase):
         result_sets = [('row1',), ('row2',)]
         self.cur.fetchone.return_value = result_sets[0]
         self.assertEqual(result_sets[0], self.db_hook().get_first(statement))
+
+    def test_get_pandas_df(self):
+        statement = 'SQL'
+        column = 'col'
+        result_sets = [('row1',), ('row2',)]
+        self.cur.description = [(column,)]
+        self.cur.fetchall.return_value = result_sets
+        df = self.db_hook().get_pandas_df(statement)
+        self.assertEqual(column, df.columns[0])
+        for i in range(len(result_sets)):  # pylint: disable=consider-using-enumerate
+            self.assertEqual(result_sets[i][0], df.values.tolist()[i][0])
$ ./run-tests tests.contrib.hooks.test_pinot_hook:TestPinotDbApiHook.test_get_pandas_df
AIRFLOW__CORE__SQL_ALCHEMY_CONN not set - using default
Airflow home: /home/sekikn
Airflow root: /home/sekikn/repos/airflow
Home of the user: /home/sekikn


Skipping initializing of the DB as it was initialized already

You can re-initialize the database by adding --with-db-init flag when running tests

KRB5_KTNAME variable is empty - no kerberos intialisation

Starting the tests with arguments: tests.contrib.hooks.test_pinot_hook:TestPinotDbApiHook.test_get_pandas_df

.
----------------------------------------------------------------------
Ran 1 test in 0.289s

OK
[2019-10-25 07:20:36,090] {settings.py:200} DEBUG - Disposing DB connection pool (PID 3587)
```

**Comment by OmerJog** [comment]
@sekikn tests did not run yet due to flake8 error:
`tests/dags/test_impersonation_custom.py:53:1: E302 expected 2 blank lines, found 1`
@potiuk  how is it possible to get flake8 error on file that wasn't changed in the PR?

**Comment by sekikn** [comment]
Thanks @OmerJog for taking care of this PR, rebased on master to run the CI again :)

**Pull request merged**
