### PR TITLE
Pass project_id to get_job in CloudRunExecuteJobOperator

### PR DESCRIPTION
**Pull request by LeonardMeyer**
---
The project id is passed pretty much everywhere except here. From my understanding it causes the hook to fallback to the account's project id only for `get_job` method. It seemed like an oversight to me.

**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I guess you need to add / update some unit tests.

**Review by dirrao — CHANGES_REQUESTED** [review]
Can you add test cases for this change?

**Comment by LeonardMeyer** [comment]
@dirrao Done

**Comment by LeonardMeyer** [comment]
#37201 I rebased and well apparently my work was a duplicate...

**Pull request closed without merging**
