### PR TITLE
[AIRFLOW-2791] Add Hipages to list of current airflow users

### PR DESCRIPTION
**Pull request by arihantsurana**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [AIRFLOW-2791] issues and references them in the PR title. 
 - https://issues.apache.org/jira/browse/AIRFLOW-2791

### Description
- [x] Add Hipages to list of current airflow users

### Tests
- [x] does not need testing for this extremely good reason: 
 - only documentation changes

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Thanks @arihantsurana Can you add Hipages at the correct position? The list is alphabetically sorted.

**Comment by r39132** [comment]
@arihantsurana please refer to @Fokko 's note. Move HiPages before Holimetrix.

**Comment by arihantsurana** [comment]
Done.

**Comment by arihantsurana** [comment]
Squashed commits

**Review by Fokko — APPROVED** [review]
Thanks @arihantsurana! Welcome aboard!

**Pull request closed without merging**
