### PR TITLE
Move operator guides to provider documentation packages

### PR DESCRIPTION
**Pull request by mik-laj**
Part of: https://github.com/apache/airflow/issues/11423

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — COMMENTED** [review]
Do we need those in docs? Maybe we should move the providers documentation into the "airflow/providers/apache/doc" etc. folders ? 

This way we move closer to '`everything that is provider relevant should be in the "airflow/provider/PROVIDER folder' goal. And that opens up future possibility of separating the providers to separate repos if needed.

**Comment by mik-laj** [comment]
@potiuk 

The main thing that the project consists of is the application code, tests and documentation. These 3 elements are visibly divided in the project structure:
- application code - `airflow` directory
- tests - `tests` directory
 -docs - `docs` directory

I think it will be very confusing for users to include documentation in the application code directory. We might think to put everything about providers into one directory, but then we would have to think how to mark the division into these 3 areas in the directory structure. Otherwise, it will be difficult for new collaborators to understand the structure of the project.

Part of the documentation will be in the `/docs/` directory, some documentation in the `/airflow/providers/docs/` directory, and another part in` /airflow/providers/google/docs/` directory.

When keeping the current file structure, the current directory can read from the URL
```
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-google/latest/index.html
>>
/docs/apache-airflow-providers-google/latest/index.html
>>
/docs/apache-airflow-providers-google/index.html
>>
/docs/apache-airflow-providers-google/index.rest
```

**Comment by mik-laj** [comment]
There is one more problem. We must have one output directory to be able to view the documentation in the browser. Currently, the structure of the output files is similar to the structure of the input directories (except for apache-airflow, which I haven't had time to move yet).
If we move the providers documentation to the `/airflow/providers/` directory, the result files will still need to be saved in the same /docs/_build/ directory to be able to view it fully. This will be even more confusing for people who will need to find the directory with the output files.

**Comment by potiuk** [comment]
> If we move the providers documentation to the `/airflow/providers/` directory, the result files will still need to be saved in the same /docs/_build/ directory to be able to view it fully. This will be even more confusing for people who will need to find the directory with the output files.

Fine for me. We are not splitting the providers off completely and I agree we can have separate structures (It woudl be likely great to add them all under "docs/providers/airlfow-provider.... ? That woudl be much closer to existing spit:

* airflow/providers/
* tests/providers/
* docs/providers/

That would be rather consistent approach. Could we do that at the very least?

**Comment by turbaszek** [comment]
> add them all under "docs/providers/airflow-provider....

This sound reasonable for me

**Comment by mik-laj** [comment]
> That would be a rather consistent approach. Could we do that at the very least?

What do you think about moving documentation for apache-airflow to /docs/apache-airflow/?
Then we will have the following directories:
- /docs/apache-airflow
- /docs/apache-airflow-providers
- /docs/apache-airflow-providers-google
- and other.

We will then be able to have the same URL structure:
```
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow/latest/index.html
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers/index.html
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/apache-airflow-providers-google/latest/index.html
```
Then we will have a lot of freedom to add new documentation packages in the future. We won't have complex rules about creating directories, but everything will use the Pypi package name (or a name similar to the package name e.g. apache-airflow-providers). If there was time, we could, for example, create a separate package for the airflow upgrade-check command and not have to think about the package structure.

In the `/docs/` directory, in addition to the documentation directories, we will only have:
- README.rst
- start_doc_server.sh file
- extension directory 
- list-roles.sh file

**Comment by mik-laj** [comment]
I care about a simple structure of directories without directory nests because it will facilitate adding new packages with documentation (e.g. helm chart, airflow upgrade-check) but also needs a simple output directory structure to make it easy to add a documentation version selection.
Currently, it is very easy to recognize:
```
http://apache-airflow-docs.s3-website.eu-central-1.amazonaws.com/docs/<PACKAGE-NAME>/<VERSION>/<FILEPATH>.html
```
Here is the corresponding Javascript code:
https://github.com/apache/airflow-site/blob/3d3004c77159517de9223369c378504866a34fa1/landing-pages/src/js/versionSelector.js#L24-L26

**Comment by potiuk** [comment]
Fin 

> What do you think about moving documentation for apache-airflow to /docs/apache-airflow/?
> Then we will have the following directories:
> 
> * /docs/apache-airflow
> * /docs/apache-airflow-providers
> * /docs/apache-airflow-providers-google
> * and other.

Fine for me. If this is easier and faster to do, I am perfectly OK with that.

**Comment by mik-laj** [comment]
@potiuk Do you think I can do this next or should I do it before merging this change?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Feel free to merge it now :)

**Pull request merged**
