### PR TITLE
Speed up CeleryExecutor when sending only a single task to Celery

### PR DESCRIPTION
**Pull request by mik-laj**
Creating a new process is an expensive operation. In my case it lasts 100 ms. Sending the command to Redis takes 1ms only. 

CC: @auvipy

---
Make sure to mark the boxes below before creating PR: [x]

- [X] Description above provides context of the change
- [X] Unit tests coverage for changes (not needed for documentation changes)
- [X] Target Github ISSUE in description if exists
- [X] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [X] Relevant documentation is updated including usage instructions.
- [X] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by auvipy — APPROVED** [review]
looks good

**Comment by ashb** [comment]
(Somewhat surprised to find creating a process takes 100ms. It should be a fork which should)

Change makes sense though

**Review by ashb — APPROVED** [review]

**Comment by mik-laj** [comment]
Breeze on MacOS
```
Before:
Loop time: 153.950 ms
Loop time: 130.430 ms
Loop time: 138.379 ms
Loop time: 136.401 ms
Loop time: 129.030 ms
Loop time: 138.876 ms
Loop time: 136.068 ms
Loop time: 137.900 ms
Loop time: 128.807 ms
Loop time: 135.907 ms
Loop time: 131.712 ms
Loop time: 144.686 ms
Loop time: 133.606 ms
Loop time: 132.587 ms
Loop time: 141.669 ms
Average time: 136.791 ms
After:
Loop time: 0.017 ms
Loop time: 0.016 ms
Loop time: 0.006 ms
Loop time: 0.025 ms
Loop time: 0.042 ms
Loop time: 0.011 ms
Loop time: 0.008 ms
Loop time: 0.012 ms
Loop time: 0.150 ms
Loop time: 0.016 ms
Loop time: 0.009 ms
Loop time: 0.018 ms
Loop time: 0.006 ms
Loop time: 0.007 ms
Loop time: 0.010 ms
Average time: 0.144 ms
```
Native Mac OS
```
Before:
Loop time: 163.202 ms
Loop time: 135.025 ms
Loop time: 128.540 ms
Loop time: 128.556 ms
Loop time: 127.288 ms
Loop time: 132.704 ms
Loop time: 126.869 ms
Loop time: 128.493 ms
Loop time: 126.863 ms
Loop time: 130.054 ms
Loop time: 126.378 ms
Loop time: 127.801 ms
Loop time: 127.304 ms
Loop time: 127.238 ms
Loop time: 127.273 ms
Average time: 131.095 ms
After:
Loop time: 0.004 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Loop time: 0.001 ms
Average time: 0.009 ms
```
<details>

<summary> Benchmark </summary>

```python
from multiprocessing import Pool

from perf_kit.repeat_and_time import timing, repeat

REPEAT_COUNT = 15


def my_func(d):
    return d + 1

@timing(REPEAT_COUNT)
@repeat(REPEAT_COUNT)
@timing()
def pool_slow(items):
    with Pool(processes=1) as pool:
        pool.map(my_func, items)


@timing(REPEAT_COUNT)
@repeat(REPEAT_COUNT)
@timing()
def pool_fast(items):
    if len(items) == 1:
        return my_func(items[0])
    with Pool(processes=1) as pool:
        pool.map(my_func, items)


print("Before:")
pool_slow([1])
print("After:")
pool_fast([1])

```
</details>

**Comment by auvipy** [comment]
in the next release of celery 4.4.3 you can optionally use cythonize version of py-amqp in some part which should improve some performence.

**Pull request merged**
