### PR TITLE
[AIRFLOW-4536] Split jobs into package

### PR DESCRIPTION
**Pull request by BasPH**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

On master branch at the time of writing, airflow/jobs.py is 2695 lines long and I think it's time to split the file into a package. This should result in improved code structure.

In this PR I preserve the import structure by importing all job classes in `__init__.py`, so that all code importing `airflow.jobs.*` remains working.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Code in `tests/test_jobs.py` was also split, following the same structure as in `/airflow/jobs/`.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by milton0825** [comment]
Should have coordinated on jira first... https://issues.apache.org/jira/browse/AIRFLOW-4535 and https://issues.apache.org/jira/browse/AIRFLOW-4536 (sigh

**Comment by milton0825** [comment]
@BasPH How do you want to move forward? I think both of our PRs are failing the same tests and I think we should coordinate on fixing the tests.

**Comment by OmerJog** [comment]
Is this diffrent than https://github.com/apache/airflow/pull/4379 ?

**Comment by BasPH** [comment]
@milton0825 yours succeeds so let's move forward with your PR :)
@OmerJog same idea, although that PR introduces breaking changes since there are no imports in `/airflow/jobs/__init__.py`

**Comment by BasPH** [comment]
Closed in favour of https://github.com/apache/airflow/pull/5303

**Pull request closed without merging**
