### PR TITLE
DRAFT: Experimentally remove unidecode

### PR DESCRIPTION
**Pull request by ryw**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ryw** [comment]
i'm trying to understand the licensing risks we have in the project - and realized that perhaps we can just remove Unidecode from codebase - tests don't fail on this branch - can we remove?

**Comment by potiuk** [comment]
FYI. @ryw - those files are not used anymore (we were waiting for 1.10.12 to be released to remove them).  And the name is indeed misleading so no wonder you thought those are actual requirements. We are about to remove the whole directory (PR is coming). 

They've been replaced with "constraint-master", "constraints-v1-10-test" and "constraints-v1-10-stable" orphaned branches, where we keep constraint files. 

Even there - those are just "constraint" files rather than "requirements" - all the dependencies are coming from setup.py file and Unidecode there is a transitive dependency coming from 'python-nvd3~=0.15.0': python-nvd3 -> pytthon-alugify -> text-unidecode . You can see it by entering `breeze` and running `pipdeptree` and you will be able to see the whole dependency tree.

**Comment by ryw** [comment]
Thanks @potiuk who will remove these unused files + when?
I'm responding to the output of our vulnerability scanner.

**Comment by potiuk** [comment]
The PR is coming as you speak. BTW. See the https://github.com/apache/airflow/blob/master/requirements/REMOVE.md  note that I left before.

**Comment by potiuk** [comment]
BTW. The vulnerability scanner will likely still show those dependencies, if it is actually working (I would love to hear if it does).

As explained, the dependencies in our project come from setup.py and unidecode is a transitive dependency (nothing changes by removing this file). So if it will stop unidecode as dependency, it means that it does not detect the "proper" ones..

FYI. Those "constraints" files for master are here https://github.com/apache/airflow/tree/constraints-master  (you can see history of changes there) - they will show you the list of actual dependencies used by the project. They are refreshed automatically every time when master merge succeed. There are already 35 commits in there (1-2 changes a day). So if you want to have the latest "snapshot" of all dependencies used (including the transitive ones) you should look there (HEAD of "constraints-master" branch)  in case the scanner is not able to do it from the "setup.py" automatically.

More about it here: https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pinned-constraint-files

**Comment by potiuk** [comment]
PR here: https://github.com/apache/airflow/pull/10668

**Comment by ryw** [comment]
Closing this in favor of #10668

**Pull request closed without merging**
