### PR TITLE
[AIRFLOW-3002] Correctly test os.stat().st_size of local_file in goog…

### PR DESCRIPTION
**Pull request by jeffkpayne**
…le_cloud_to_local

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3002
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
N/A

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
`tests.contrib.operators.test_dataflow_operator.GoogleCloudBucketHelperTest.test_valid_object_path`
`tests.contrib.operators.test_dataflow_operator.GoogleCloudBucketHelperTest.test_empty_object`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
Good Spot. Thanks

**Review by kaxil — APPROVED** [review]
LGTM

**Comment by kaxil** [comment]
Will merge once the Travis passes.

**Comment by kaxil** [comment]
@jeffkpayne Can you please add a unit test for this as well ? Also when you push new commits remember to squash commits and make sure that the subject is limited to 50 characters (not including Jira issue reference) as we would use this in CHANGELOG.md.

Thanks. Appreciate the effort.

**Comment by jeffkpayne** [comment]
@kaxil Will do, but wrt squashed commits, I only had one commit so far ;)

**Comment by jeffkpayne** [comment]
Looks like the 2.7 builds are failing.  Looking into this...

**Comment by jeffkpayne** [comment]
Gah, found it...

**Review by kaxil — CHANGES_REQUESTED** [review]
@jeffkpayne Can you also add a test that checks file size and if it is 0 it checks it it raises an Exception.

**Comment by jeffkpayne** [comment]
@kaxil Added additional test and fixed inconsistent exception message formatting.

**Review by kaxil — APPROVED** [review]
LGTM. Thanks @jeffkpayne

**Pull request merged**
