### PR TITLE
[AIRFLOW-XXX] Split guide for operators to multiple files

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

No applicable

### Description

I divided the guides for operators into several files, because the page became very long, which made it difficult to use it.  It is worth adding that I used the glob to create a table of contents for operators for GCP.  Adding a new service is just adding a new file.

In the next step I would like to expand the `docs/howto/operator/gcp/index.rst` file. This file should contain information about the prerequisites to use operators.

Preview: http://well-to-do-action.surge.sh/

CC: @ashb 

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

No applicable

### Code Quality

No applicable

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Great! Highest time for that!

**Comment by mik-laj** [comment]
@Fokko Rebased.  Can you look? It is more necessary to divide than for connections. You have merged a similar change regarding connection types.  I would like to update all of my and my team's open PR for this change.

**Review by zhongjiajie — APPROVED** [review]
Awsome! now is easy to read and find section!

**Review by Fokko — APPROVED** [review]
Looking great @mik-laj Thanks!

**Pull request merged**
