### PR TITLE
[AIRFLOW-3384] Allow higher versions of Sqlalchemy and Jinja2

### PR DESCRIPTION
**Pull request by jlricon**
Make sure you have checked _all_ steps below.

### Jira

-  My PR addresses this JIRA issue: [AIRFLOW-3384]

### Description

- [This PR bumps up the allowed versions of sqlalchemy and jinja2

### Tests

- This PR does not add new functionality to be tested, nor changes the codebase.

### CODE REVIEW

**Review by jmcarp — CHANGES_REQUESTED** [review]
Looks like we'll need to upgrade flask-admin too.

**Comment by jlricon** [comment]
Ok, that should do it. Master is broken atm, I guess that I'll pass that final test config when master builds again.

**Comment by bolkedebruin** [comment]
@jlricon can youy please execute this on your own Travis? Opening and closing for just the sake of biuilding is costing us money. If travis fails please check why it fails and fix cases accordingly.

Obviously have your PR squashed and cleanup as well, that makes intregration a lot cleaner. Thanks!

**Comment by jlricon** [comment]
@bolkedebruin Yes, sorry for that. It was a dockerhub issue it seems. All tests pass now in my local Travis, so I'm pushing again, hopefully last time.

**Comment by jlricon** [comment]
For some reason it is not passing here even though it passed locally, it's not something in the changes I've introduced. Other contributors have also complained about Travis recently. The first time it was failing a lot of tests, now it is only one. I am going to close-open once now, and if it doesn't work I will look into it every 2 days to avoid abusing this repo's Travis.

**Comment by ncrocfer** [comment]
Hello guys,

I am not sure if it's the right place to ask it, but do you think if these upgrades will be included in the next release please ?

Thanks !

**Comment by kaxil** [comment]
@ncrocfer Yes this will be available in the next release :) - 1.10.2

**Pull request merged**
