### PR TITLE
pin responses version

### PR DESCRIPTION
**Pull request by eladkal**
Main is broken with:

```
==== Providers postgres: 43 failures, 7 errors ====

tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_bucket_if_not_bucket_exist: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_objects_key_does_not_exist: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_objects_one_key: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_objects_many_keys: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_generate_presigned_url: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_should_throw_error_if_extra_args_contains_unknown_arg: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_should_pass_extra_args: failed on setup with "TypeError: __new__() missing 1 required positional argument: 'source'"
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_bucket_if_bucket_exist: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_get_bucket_tagging_no_tags_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_get_bucket_tagging_no_bucket_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_valid_set: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_pair: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_pair_and_set: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_key_but_no_value_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_value_but_no_key_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_key_and_set_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_with_value_and_set_raises_error: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_put_bucket_tagging_when_tags_exist_overwrites: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_bucket_tagging: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/hooks/test_s3.py::TestAwsS3Hook::test_delete_bucket_tagging_with_no_tags: TypeError: __new__() missing 1 required positional argument: 'source'
tests/providers/amazon/aws/log/test_s3_task_handler.py::TestS3TaskHandler::test_close: TypeError: __new__() missing 1 required positional argument: 'source'
```

this effects tests using moto like in PR https://github.com/apache/airflow/pull/21488

The reason for this is responses releasing new version which broke moto:
https://github.com/spulec/moto/issues/4913

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
too late @eladkal :). Just rebase: https://github.com/apache/airflow/pull/22046/files

**Comment by potiuk** [comment]
Closed as duplicate of #22046

**Comment by potiuk** [comment]
Closed as duplicate of #22046

**Comment by potiuk** [comment]
I even opened our very own issue :) https://github.com/getsentry/responses/issues/511

**Comment by potiuk** [comment]
I even opened our very own issue :) https://github.com/getsentry/responses/issues/511

**Comment by eladkal** [comment]
> I even opened our very own issue :) [getsentry/responses#511](https://github.com/getsentry/responses/issues/511)

Great! though we probably don't need to wait for `responses` to fix the issue.
We just need `moto` to release new version with https://github.com/spulec/moto/pull/4914

**Comment by potiuk** [comment]
Yep. The moto maintainer reached out and commented out on our issue :)

**Comment by potiuk** [comment]
https://github.com/getsentry/responses/issues/511#issuecomment-1061125130

**Pull request closed without merging**
