### PR TITLE
stop rendering some class docs in wrong place

### PR DESCRIPTION
**Pull request by jstern**
Docs generated for providers.yandex.hooks incorrectly include docs for airflow.exceptions.AirflowException and airflow.hooks.base_hook.BaseHook in the yandex module, as if those classes had been defined in that module.

This is almost certainly a bug in autoapi or one of the libraries it uses, but I haven't tracked down the root cause. In the meantime, importing the modules and then referring to the classes using modulename.Classname avoids the issue.

UPDATE: based on advice from the community, instead of changing the way modules were imported in `providers.yandex.hooks.__init__`, reorganize the code similar to how other providers are organized to keep code out of `__init__`. 

Before this change, yandex docs include AirflowException and BaseHook under the wrong fully qualified names:

Screen Shot 2020-03-28 at 4 36 56 PM

After, yandex docs include only objects defined in that module:

Screen Shot 2020-04-03 at 8 28 46 AM

In addition to being wrong in and of itself, these docs being out of place are causing doc warnings in another PR where I have added `airflow.exceptions` to the api docs (https://github.com/apache/airflow/pull/7133).

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
I wonder if this is a more general problem elsewhere too...?

**Comment by turbaszek** [comment]
@mik-laj you are experienced with our docs

**Comment by jstern** [comment]
> I wonder if this is a more general problem elsewhere too...?

Me too. 

A cursory check just for these two cases doesn't turn anything up in the built docs in my branch:

```
11:05:07 jstern@US-C02V518BHTD7:html/ (fix-yandex-doc-imports)
$ ag "Base class for all hooks"
_modules/airflow/hooks/base_hook.html
216:<span class="sd">&quot;&quot;&quot;Base class for all hooks&quot;&quot;&quot;</span>

_sources/_api/airflow/hooks/base_hook/index.rst.txt
8:   Base class for all hooks

_api/airflow/hooks/base_hook/index.html
276:<p><p>Base class for all hooks</p>

11:05:27 jstern@US-C02V518BHTD7:html/ (fix-yandex-doc-imports)
$ ag "Base class for all Airflow's errors"

11:05:46 jstern@US-C02V518BHTD7:html/ (fix-yandex-doc-imports)
```

But perhaps there are other cases.

My hunch is that this has something to do with the fact that the doc in question is for an `__index__.py` file...

**Comment by ashb** [comment]
```python
__all__ = [YandexCloudBaseHook]
```

may work as well and is a less-obscure fix. (That controls what is "imported" when using a python module)

**Comment by mik-laj** [comment]
@turbaszek I have no solution to this problem and I am also aware of it.

**Comment by jstern** [comment]
will try the `__all__` approach locally and update the pr to use that if it works

**Comment by jstern** [comment]
```python
__all__ = ['YandexCloudBaseHook']
```

This works (needs to be a string though since it's a list of names). Thanks for the suggestion @ashb I agree it makes more sense than my first pass.

Starting to wonder if there really isn't a bug with autoapi and it's more just a thing to keep in mind about how people use `__init__` modules; I think it's pretty normal to import names into those modules to expose them more conveniently, and if you're asking people to prefer importing `a.X` over `a.b.c.X` you probably would want your docs to reflect `a.X` ... only in this case the names we're importing come from a totally different place.

**Comment by ashb** [comment]
I'm surprised that it treats `__init__` differently, but it could I guess

**Comment by jstern** [comment]
> I'm surprised that it treats `__init__` differently, but it could I guess

Well, I don't know. I'm just kind of speculating randomly :)

Any reason this can't be merged at this point?

**Comment by kaxil** [comment]
Why not move the contents of `airflow/providers/yandex/hooks/__init__.py` to `airflow/providers/yandex/hooks/yandex.py` and have an empty `__init.py` similar to https://github.com/apache/airflow/blob/master/airflow/providers/salesforce/hooks/salesforce.py

**Comment by jstern** [comment]
> Why not move the contents of `airflow/providers/yandex/hooks/__init__.py`

As someone who is in no way involved with yandex or using/maintaining the yandex provider code I felt like I should make my edits as minor as possible; reorganizing the code didn't feel like a decision it was mine to make. If the airflow committers and/or contributors of the yandex code want me to do that instead, I'm happy to do it.

**Comment by turbaszek** [comment]
@jstern I think Yandex is only available on master so we can move the code without any consequences

**Comment by jstern** [comment]
Ok @kaxil @turbaszek I'm up for making this change. It does have some ripple effects: one is that it requires minor changes to operators-and-hooks-ref.rst, which is no problem. Another is that test_project_structure fails because the new module does not have a corresponding test module. Question for the group: presumably YandexCloudBaseHook is covered by tests of airflow.providers.yandex.hooks.yandexcloud_dataproc.DataprocHook. Should I write a test suite anyway for YandexCloudBaseHook? Or should I add the new module to MISSING_TEST_FILES in tests/test_project_structure.py?

**Comment by kaxil** [comment]
> Ok @kaxil @turbaszek I'm up for making this change. It does have some ripple effects: one is that it requires minor changes to operators-and-hooks-ref.rst, which is no problem. Another is that test_project_structure fails because the new module does not have a corresponding test module. Question for the group: presumably YandexCloudBaseHook is covered by tests of airflow.providers.yandex.hooks.yandexcloud_dataproc.DataprocHook. Should I write a test suite anyway for YandexCloudBaseHook? Or should I add the new module to MISSING_TEST_FILES in tests/test_project_structure.py?

Let's keep it in MISSING_TEST_FILES for now and we can revisit it later

**Review by potiuk — APPROVED** [review]

**Pull request merged**
