### PR TITLE
Migrate executor docs to respective providers

### LINKED ISSUE #33916: Migrate Celery/Kubernetes Executor docs to providers
### Body

Now that we have Executors in providers we should migrate
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/celery.html
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/celery_kubernetes.html
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/kubernetes.html
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/local_kubernetes.html

To providers docs

and update references
https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/executor/index.html#executor-types to the providers docs.

We need also:
1. Update redirect.txt to reflect these changes
2. Make sure core docs have high level description of executors (any information that is relevant for all executors is considered high level description)  

### Committer

- [X] I acknowledge that I am a maintainer/committer of the Apache Airflow project.

### PR DESCRIPTION
**Pull request by RNHTTR**
Closes: https://github.com/apache/airflow/issues/33916

### CODE REVIEW

**Comment by RNHTTR** [comment]
Accidentally ran my commit with --no-verify... please hold!

**Comment by RNHTTR** [comment]
Seems like this test is failing in at least a couple PRs
* `Tests / Docker-compose quick start with PROD image verifying (pull_request)`

**Comment by potiuk** [comment]
Yes. All those that have not been rebased after https://github.com/apache/airflow/pull/37713

**Comment by potiuk** [comment]
(I  just rebased yours)

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
:crossed_fingers:

**Comment by potiuk** [comment]
My bad.... It was a mistake in main and I just merged a fix I though it was not needed initially #37739 :facepalm: .... rebasing again

**Comment by potiuk** [comment]
Wooo ohoooooo

**Comment by potiuk** [comment]
Well... Let's see in main and then when we release the docs :)

**Pull request merged**
