### PR TITLE
[AIRFLOW-6945] mysql 5 7 in airflow 1.10

### PR DESCRIPTION
**Pull request by potiuk**
---
Issue link: [AIRFLOW-6945](https://issues.apache.org/jira/browse/AIRFLOW-6945)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Commit message/PR title starts with `[AIRFLOW-NNNN]`. AIRFLOW-NNNN = JIRA ID<sup>*</sup>
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

<sup>*</sup> For document-only changes commit message can start with `[AIRFLOW-XXXX]`.

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by ashb** [comment]
Hmmmm is this "safe" to change the version requirement/what we test against in 1.10?

**Comment by potiuk** [comment]
That's a good question. Maybe I can add both actually. We do not run it to often so maybe adding one more travis run is not a problem.

**Comment by potiuk** [comment]
I will cherry-pick the "DB versions" when they are merged and will add both 5.6 and 5.7 to 1.10 builds.

**Comment by potiuk** [comment]
Closing - as it's been cherry-picked now from master (still leaving 5.6 as majority of MySQL tests)

**Pull request closed without merging**
