### PR TITLE
Inherit global security context

### LINKED ISSUE #34599: Openshift support is broken - some pods do not inherit global uid
### Official Helm Chart version

1.10.0 (latest released)

### Apache Airflow version

2.6.2

### Kubernetes Version

1.25.11+1485cc9

### Helm Chart configuration

uid: XXXXXX0000
gid: XXXXXX0000

### Docker Image customizations

_No response_

### What happened

An OpenShift Security Context Constraint (SCC) is triggered when installing the default helm chart.
The statsd pod won't start and this error is thrown:

```
pods "my-airflow-statsd-67cd659785-" is forbidden: unable to validate against any security context constraint: [provider "trident-controller": Forbidden: not usable by user or serviceaccount, provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "csi-smb-controller": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65534: must be in the ranges: [XXXXXX0000, XXXXXX9999], provider restricted: .containers[0].runAsUser: Invalid value: 65534: must be in the ranges: [XXXXXX0000, XXXXXX9999], provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "rsync-anyuid": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "twistlock-scc": Forbidden: not usable by user or serviceaccount, provider "trident-node-linux": Forbidden: not usable by user or serviceaccount, provider "csi-smb-node": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "velero-privileged": Forbidden: not usable by user or serviceaccount]
```

Some pods (e.g. statsd, redis) don't inherit the helm uid properly and it's not clear where the value 65534 comes from?
I assume a securityContext may be missing for statsd to inherit the global.

As a workaround I added a custom override for these pods:
```
statsd:
  securityContexts:
    pod:
      fsGroup: XXXXXX0000
      runAsGroup: XXXXXX0000
      runAsUser: XXXXXX0000
```

### What you think should happen instead

The statsd pod should start properly.

### How to reproduce

helm repo add apache-airflow https://airflow.apache.org/
helm install my-airflow apache-airflow/airflow --version 1.10.0 -f values.yml

values.yaml
```
uid: XXXXXX0000
gid: XXXXXX0000
```

### Anything else

I'm on OpenShift

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by MPParsley**
Closes: https://github.com/apache/airflow/issues/34599

### CODE REVIEW

**Review by hussein-awala — COMMENTED** [review]
I can't find `airflowPodSecurityContext` in the chart, do you want to use `airflowSecurityContext`? if so, could you fix it and update the tests?

**Comment by MPParsley** [comment]
> I can't find `airflowPodSecurityContext` in the chart, do you want to use `airflowSecurityContext`? if so, could you fix it and update the tests?
airflowPodSecurityContext is in the helpers, I took it from the webserver chart, see https://github.com/apache/airflow/blob/20b7cfc3956e404fe1a6d4ed9e363fca7161ede2/chart/templates/_helpers.yaml#L810

**Comment by jedcunningham** [comment]
It's intentional that PgBouncer, Redis, and StatsD don't use the Airflow security context. This is consistent with other aspects as well, e.g. `env`.

**Comment by MPParsley** [comment]
Hi @jedcunningham, thank you for your feedback.

**Pull request closed without merging**
