### PR TITLE
Deprecate `conf` from Task Context

### PR DESCRIPTION
**Pull request by kaxil**
This was initially added in response to https://github.com/apache/airflow/issues/168. However, we now have `ti.log_url` that is used for that; example usages:

https://github.com/apache/airflow/blob/dcd41f60f1c9b5583b49bfb49b6d85c640a2892c/airflow/models/taskinstance.py#L1362

https://github.com/apache/airflow/blob/dcd41f60f1c9b5583b49bfb49b6d85c640a2892c/providers/src/airflow/providers/smtp/notifications/templates/email.html#L28

https://github.com/apache/airflow/blob/dcd41f60f1c9b5583b49bfb49b6d85c640a2892c/docs/apache-airflow/howto/email-config.rst?plain=1#L76

So, to simplify what we need to pass from API server to the Task SDK in preparation for Airflow 3, I want to simplify and remove things that aren't needed. In this case, this is good so we don't pass/expore secrets unnecesarily via `conf`. This is removed in Airflow 3 and deprecated in 2.10.x/2.11

Mailing list Thread: https://lists.apache.org/thread/2n0l8y2oyq4442p0lsnmbbcl6rmbj3k7

PR for Airflow 3: https://github.com/apache/airflow/pull/44820

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by kaxil** [comment]
@jscheffl / @uranusjr -- Does this good look for 2.10.5/2.11?

**Review by hussein-awala — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]
Look good.

Can you please also add a deprecation note to https://github.com/apache/airflow/blob/v2-10-test/docs/apache-airflow/templates-ref.rst#deprecated-variables ?

Newsfragment would also be good!

**Comment by kaxil** [comment]
> Look good.
> 
> Can you please also add a deprecation note to https://github.com/apache/airflow/blob/v2-10-test/docs/apache-airflow/templates-ref.rst#deprecated-variables ?
> 
> Newsfragment would also be good!

Done

**Review by Lee-W — APPROVED** [review]

**Comment by uranusjr** [comment]
Should this target 2.11.0 instead? It may be weird for users if a deprecation warning starts showing up when they do a patch version upgrade.

**Comment by jscheffl** [comment]
> Should this target 2.11.0 instead? It may be weird for users if a deprecation warning starts showing up when they do a patch version upgrade.

We had this for other places as well - if we know about a deprecation we should inform users as soon as we know. I'd also propose to not hold-back the information about upcoming deprecation.

**Pull request merged**
