### PR TITLE
Improve DAG loading in Graph view when using Dynamic Tasks

### LINKED ISSUE #27483: DAG loading very slow in Graph view when using Dynamic Tasks
### Apache Airflow version

2.4.2

### What happened

The web UI is very slow when loading the Graph view on DAGs that have a large number of expansions in the mapped tasks.
The problem is very similar to the one described in #23786 (resolved), but for the Graph view instead of the grid view.

It takes around 2-3 minutes to load DAGs that have ~1k expansions, with the default Airflow settings the web server worker will timeout. One can configure [web_server_worker_timeout](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#web-server-worker-timeout) to increase the timeout wait time.

### What you think should happen instead

The Web UI takes a reasonable amount of time to load the Graph view after the dag run is finished.

### How to reproduce

Same way as in #23786, you can create a mapped task that spans a large number of expansions then when you run it, the Graph view will take a very long amount of time to load and eventually time out.

You can use this code to generate multiple dags with `2^x` expansions. After running the DAGs you should notice how slow it is when attempting to open the Graph view of the DAGs with the largest number of expansions.

```python

from datetime import datetime
from airflow.models import DAG
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
}

initial_scale = 7
max_scale = 12
scaling_factor = 2

for scale in range(initial_scale, max_scale + 1):
    dag_id = f"dynamic_task_mapping_{scale}"
    with DAG(
        dag_id=dag_id,
        default_args=default_args,
        catchup=False,
        schedule_interval=None,
        start_date=datetime(1970, 1, 1),
        render_template_as_native_obj=True,
    ) as dag:
        start = EmptyOperator(task_id="start")

        mapped = PythonOperator.partial(
            task_id="mapped",
            python_callable=lambda m: print(m),
        ).expand(
            op_args=[[x] for x in list(range(2**scale))]
        )

        end = EmptyOperator(task_id="end")

        start >> mapped >> end
    globals()[dag_id] = dag
``` 

### Operating System

MacOS Version 12.6 (Apple M1)

### Versions of Apache Airflow Providers

```
apache-airflow-providers-amazon==4.0.0
apache-airflow-providers-common-sql==1.2.0
apache-airflow-providers-ftp==3.1.0
apache-airflow-providers-http==4.0.0
apache-airflow-providers-imap==3.0.0
apache-airflow-providers-sqlite==3.2.1
```

### Deployment

Docker-Compose

### Deployment details

_No response_

### Anything else

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Josersanvil**
closes: #27483

This PR just makes a small change to the function in`www` that loads the DAG view for the Web UI.

Right now, the view loops and retrieves the mapped instances of all the expansions of a single task, that means that if a DAG created 100 expansions of a task instance, it loops through all the 100 expansions in order to retrieve the status of the 100! This makes the loading of that view very slow, and it is also not needed, applying the same logic, we only need to retrieve the mapped instances of one of the expansions to get the status of the rest (Since they all share the same Task Id).

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by pierrejeambrun — APPROVED** [review]
Indeed `get_instance_with_map` returns a summary for all mapped task and doesn't need to be run for each index.

Tested locally and looking good :)

**Comment by pierrejeambrun** [comment]
We might still have an issue with the `try_number`, but this was already the case before. (try_number is shared and will pick the value of the first mapped task to be processed in the `dag.get_task_instances` list)

**Review by hussein-awala — APPROVED** [review]
Nice catch! LGTM

**Review by bbovenzi — APPROVED** [review]

**Comment by potiuk** [comment]
Sounds like a good candidate for the next PR of the month ;)

**Comment by jedcunningham** [comment]
(#protm so @potiuk's nomination gets found by the automation!)

Congrats on your first commit @Josersanvil 🎉

**Pull request merged**
