### PR TITLE
Use plain asserts in tests.

### PR DESCRIPTION
**Pull request by jmcarp**
We have talked about switching from unittest-style assertions (like `self.assertEqual(foo, bar)`) to plain pytest-style assertions (like `assert foo == bar`) on slack and the mailing list, but it doesn't seem like we've decided so far. I wanted to send a sample PR to show how this might work. I generated these changes with a one-line command:

```
unittest2pytest -f self_assert tests/core -w
```

If we try to refactor many tests at once, we'll likely run into conflicts, but because we can auto-refactor the code easily, fixing conflicts should be straightforward too.

Note that I didn't use the `remove_class` fixer or move test setup into fixtures--this just concerns assertion style.

Does this seem like an improvement? If so, we can refactor tests module by module, or run `unittest2pytest` on all the tests at once.

cc @ashb @potiuk

### CODE REVIEW

**Comment by turbaszek** [comment]
Thanks @jmcarp for the PR!

> doesn't seem like we've decided so far

We've reached consensus that we prefer `assert x == y` but it was postponed until we release and stabilise Airflow 2.0.

**Comment by jmcarp** [comment]
Now that airflow 2.0 is out (congratulations!) I'm going to mark this ready for review. This is obviously going to accumulate merge conflicts, but they'll be straightforward to resolve.

**Comment by turbaszek** [comment]
Will it be possible to automate checking that we do not use `self.assert`? It would be good to avoid regression

**Comment by jmcarp** [comment]
@turbaszek we could include `unittest2pytest` in ci, but there's a bug in python 3.6 that causes it to fail on raw fstrings. So we could:
* Only run `unittest2pytest` in python>3.6
* Write a regex
* Document that we prefer plain assertions without enforcing programmatically. I'm guessing most people are going to copy and paste tests from existing modules, so we might not have many regressions.

**Comment by jmcarp** [comment]
I'll continue fixing merge conflicts now and then, but this is ready for review. I see that our testing docs already recommend using plain asserts.

**Review by mik-laj — APPROVED** [review]
LGTM.

**Comment by mik-laj** [comment]
@potiuk @kaxil @ashb @turbaszek WDYT?

**Review by turbaszek — APPROVED** [review]
LGTM as well! Once we merge it, it would be nice to announce this on devlist so whole community is informed. We should also keep an eye on PRs that are already open and use `self.asserts`

**Review by TobKed — APPROVED** [review]
LGTM

**Comment by turbaszek** [comment]
@jmcarp would you mind rebasing?

**Comment by jmcarp** [comment]
Rebased. Is it ok for the heisentests to fail or should I rerun?

**Comment by jmcarp** [comment]
Resolved some more conflicts. @mik-laj @turbaszek is this ok to merge once tests are passing, or should we figure out the heisentests first?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
The failed test is https://github.com/apache/airflow/pull/12951/checks?check_run_id=1675678142#step:6:890 - looking at it, I think it either should be moved to quarantine or fixed.

**Comment by jmcarp** [comment]
I'm marking that test as quarantined. It passes locally, and behavior seems inconsistent from CI.

**Comment by jmcarp** [comment]
Rebased. The last failing tests I saw seemed random and unrelated to these changes.

**Comment by turbaszek** [comment]
There's an error which seems to be present in multiple builds, so I think we should take a look at that:
```
  tests/core/test_configuration.py:518: 
915
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
916
  
917
  self = <tests.test_utils.reset_warning_registry.reset_warning_registry object at 0x7f0b78239f50>
918
  
919
      def __enter__(self):
920
          # archive and clear the __warningregistry__ key for all modules
921
          # that match the 'reset' pattern.
922
          pattern = self._pattern
923
          backup = self._backup = {}
924
          for name, mod in list(sys.modules.items()):
925
              if pattern.match(name):
926
                  reg = getattr(mod, "__warningregistry__", None)
927
                  if reg:
928
  >                   backup[name] = reg.copy()
929
  E                   AttributeError: 'str' object has no attribute 'copy'
```

**Comment by potiuk** [comment]
Hey @jmcarp -> I had to cancel this run because of this random GitHub error https://github.com/apache/airflow/runs/1699834461?check_suite_focus=true#step:10:310

Can you please --amend/push again?

BTW. We have a meeting today with INFRA and GitHub developer advocate https://cwiki.apache.org/confluence/display/INFRA/ASF+Builds+Agenda+2021-01-14, as this is releted to erratic behaviour of Github Registry

**Comment by jmcarp** [comment]
Ok, I think tests are in good shape and the failures are random (quarantined tests) or a formatting regression in setup.cfg that's already in the master branch.

**Comment by potiuk** [comment]
Yeah. There Was an extra space (!) added in setup.cfg but it has been fixed since :)

**Comment by potiuk** [comment]
Thanks for your patience @jmcarp! :) The CI problems did not make it easier.

**Pull request merged**
