### PR TITLE
Fix slow task instance modal with extra link

### PR DESCRIPTION
**Pull request by dstandish**
Overview
---------

This PR removes a line that (1) is costly and (2) as far as I can tell does not serve a purpose.

It is this line in the extra links section of `call_modal` in the `dag.html` template:

```javascript
$('[data-toggle="tooltip"]').tooltip();
```

The problem is that on tree view, in a dag with many tasks, the task instance modal loads very slowly, even over 1 minute.

Notes
------

This line was introduced as part of #5059.

On [line 493](https://github.com/apache/airflow/blob/3b32166d3f32ef70206421ecba8361e4886aa599/airflow/www/templates/airflow/dag.html#L493) you can see that the tooltip is only rendered when the extra link REST call _fails_.   When the call is successful, the tooltip is disabled.  When the call fails, the tooltip is the `error` message in the json response.

The offending line has no effect on this behavior.  But it does have a cost.

Calling `$('[data-toggle="tooltip"]').tooltip()` loads up every single task state square and then, I presume re-creates a tooltip on each of them.  But these objects already have a tooltip, so that doesn't make sense, and certainly not here -- because all of these squares already have tooltips by the time you are calling up the modal.

Removing this line resolves the latency problem and as far as I can tell, does not have any negative effect.

@milton0825 or @ArgentFalcon if interested please take a look.

Thanks

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ryw** [comment]
@ryanahamilton maybe you can review as well?

**Comment by ArgentFalcon** [comment]
From what I remember, I had to turn this on in order to get the tooltips to actually show up, but I'm also not a webdeveloper, so I could be wrong.

**Comment by dstandish** [comment]
Thanks @ArgentFalcon for looking it over 🙏.

One more bit of info here...

When trying to understand tooltip a little better I found [this SO post](https://stackoverflow.com/a/1333583/2761682) which indicates you can obtain a tooltip by putting a message in the `title` attr of an object without necessarily using tooltip plugin.

I also noticed that this line [this line](https://github.com/apache/airflow/blob/3b32166d3f32ef70206421ecba8361e4886aa599/airflow/www/templates/airflow/dag.html#L496), does that very thing.  

I wonder if this explains why the tooltip is there with or without the offending line 🤔

**Review by kaxil — APPROVED** [review]

**Comment by houqp** [comment]
Sorry I wasn't aware of this PR, but the tooltip was added to show a loading message when waiting for data from the API. The proper fix for this is to use only apply the data selector on extra links span element, see: https://github.com/apache/airflow/pull/10764

**Comment by dstandish** [comment]
From looking at the code, it seems the tooltip only has content when there is an error in the API response.  Where do you see a "waiting for response" tooltip?

Additionally, from my testing, the "on error" tooltip still renders without this line.  So I figure why fix the selector when it's not needed anyway.

**Comment by houqp** [comment]
@dstandish on error tooltip update happens after the AJAX call has completed. the onloading tooltip is shown before the client gets any response from the API, in that state, it will show `link not yet available`.

**Comment by dstandish** [comment]
Ah thanks for pointing that out, it was hiding in plain sight.

Ok so I have tested this behavior (link tooltip `link not yet available` while before the ajax call returns) with my PR ( by adding sleep seconds to get_link ).  

And again here, the tooltip is present even without the jquery selector tooltip call e.g. `extra_links_span.find('[data-toggle="tooltip"]').tooltip();`

So, it still seems to me that this call is unnecessary and that this PR does produce the correct behovior.

**Comment by houqp** [comment]
@dstandish removing the tooltip call definitely prevents the link not ready tooltip from showing up for me. Adding sleep is not the best way to confirm it since it's subject to race conditions. Try removing the tooltip call as well as commenting out the AJAX success callback code, and you will be able to reproduce the lack of tooltip issue.

**Comment by dstandish** [comment]
resolved in #10764

**Pull request closed without merging**
