### PR TITLE
[AIRFLOW-3124] Fix RBAC webserver debug mode

### PR DESCRIPTION
**Pull request by akosel**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW-3124) issues and references them in the PR title.
### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
The command `airflow webserver -d` crashes when `settings.RBAC == True`. This is because `create_app` currently returns `app, appbuilder`, which causes the app to crash with an `AttributeError`. As a side comment, it might not be ideal for the two `create_app`'s to have a difference interface, so wondering if the more proper fix is have `create_app` only return the flask application and then update the tests that rely on this to retrieve the appbuilder from the `cached_appbuilder` function. I can do that if it seems worthwhile, but figured I'd wait for feedback before doing that larger change.

### Tests

- [x] My PR adds the following unit tests

I set up the CLI to pass in the `unit_test_mode` setting to the flask app so we can disable the werkzeug reloader when running tests. If the reloader runs, there is an extra monitoring process left running after killing the main webserver process. This causes conflicts if multiple tests rely on being able to start a webserver (as the process will not be able to bind to the default socket). 

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
On the two create apps front: don't worry about it too much, the non-RBAC based UI is going to be removed

**Comment by feng-tao** [comment]
LGTM, +1 on @ashb 's feedback. Do you want to check whether the CI failure is false positive?

**Comment by akosel** [comment]
> LGTM, +1 on @ashb 's feedback. Do you want to check whether the CI failure is false positive?

It looks like CI is currently in a bad state and @kaxil is currently running some tests to get it fixed. So the failures look unrelated, but we can wait until that is fixed up to be sure.

**Comment by feng-tao** [comment]
CI pass

**Pull request merged**
