### PR TITLE
[FIX] remove python 3.6

### LINKED ISSUE #23403: Python 3.6 is still present in the main README
### What do you see as an issue?

Screenshot from 2022-05-02 14-11-06

### Solving the problem

remove 3.6 from 2.3 release

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by raphaelauv**
closes: #23403

### CODE REVIEW

**Review by potiuk — APPROVED** [review]
Nice!

**Review by eladkal — CHANGES_REQUESTED** [review]
There are more references:
https://github.com/apache/airflow/blob/03bef084b3f1611e1becdd6ad0ff4c0d2dd909ac/docs/apache-airflow/installation/installing-from-pypi.rst#L40

better to search also for pattern: `constraints-|version|/constraints-3.6.txt`


I'm marking this PR with 2.3.1 milestone as our install guide refer to a broken file so we need to fix this in next release
https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#installation-from-pypi

**Comment by potiuk** [comment]
I rebaseed it @raphaelauv  - there was a fix for Build Docs merged and build docs was hanging for your build, I think the rebase should help

**Review by potiuk — APPROVED** [review]

**Review by eladkal — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
> There are more references:
> 
> https://github.com/apache/airflow/blob/03bef084b3f1611e1becdd6ad0ff4c0d2dd909ac/docs/apache-airflow/installation/installing-from-pypi.rst#L40
> 
> better to search also for pattern: `constraints-|version|/constraints-3.6.txt`
> 
> I'm marking this PR with 2.3.1 milestone as our install guide refer to a broken file so we need to fix this in next release https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html#installation-from-pypi

We can fix the docs before release 2.3.1 too by fixing it in https://github.com/apache/airflow-site/ manually by replacing the 3.6 reference

**Comment by potiuk** [comment]
Speaking o which @kaxil  https://github.com/apache/airflow-site/pull/589 :)

**Pull request merged**
