### PR TITLE
Remove old graph

### PR DESCRIPTION
**Pull request by bbovenzi**
Remove the old graph view and redirect all requests to the new graph in the grid view.

Part of https://github.com/apache/airflow/issues/29852

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jedcunningham** [comment]
Overall this looks pretty good. One thing I noticed is the graph tab in the nav doesn't get selected. Are we able to make that work?

Screenshot 2023-08-01 at 4 42 51 PM

**Comment by bbovenzi** [comment]
> Overall this looks pretty good. One thing I noticed is the graph tab in the nav doesn't get selected. Are we able to make that work?
> 
> Screenshot 2023-08-01 at 4 42 51 PM

Got it working!
change tab

**Review by eladkal — APPROVED** [review]
LGTM but better to also be reviewed by @pierrejeambrun

**Review by hussein-awala — APPROVED** [review]
Looks good!

**Review by pierrejeambrun — COMMENTED** [review]
Looking good, glad to see this one removed in favor of our new modern graph details! :tada:

**Review by pierrejeambrun — APPROVED** [review]

**Review by jedcunningham — APPROVED** [review]

**Comment by TedHaleyPDL** [comment]
This new graph conveys much less information than the past graph and is far more difficult to follow in complex dags. Hovering over no longer isolates the upstream and downstream tasks. All the nodes are the same color, so its hard to pick out specific parts of a large dag. We should have the choice of views in the config.

**Comment by potiuk** [comment]
> This new graph conveys much less information than the past graph and is far more difficult to follow in complex dags. Hovering over no longer isolates the upstream and downstream tasks. All the nodes are the same color, so its hard to pick out specific parts of a large dag. We should have the choice of views in the config.

I suggest you look at latest version and if you have proposals how to improve, open an issue describing it. Or better. PR improving it.

**Comment by potiuk** [comment]
Ideally with screenshots before, after (latest version) and clearly marking what exactly the problem you want to solve.

**Comment by TedHaleyPDL** [comment]
Screenshot 2023-10-17 at 2 54 56 PM
Screenshot 2023-12-05 at 1 50 01 PM
Here is the same DAG before and after the update. The changes make determining individual task state much more difficult to track at a glance. There is virtually no contrast between nodes and edges. There is essentially no use of colour now to convey state, only small tags within the nodes that are easy to miss.

Screenshot 2023-12-05 at 1 32 24 PM
Highlighting task dependencies only seems to work now when the DAG is turned on.

Screenshot 2023-12-05 at 1 33 01 PM
Identifying TaskGroups is no longer done by colour, only by text describing the number of tasks that the task includes.
Expanding the TaskGroup is now only done via hyperlink text, previously the entire node you could interact with.

Screenshot 2023-12-05 at 1 39 45 PM
Screenshot 2023-12-05 at 1 39 55 PM
Logs are no longer visible when clicking on the log tab, you must also click into 'see more' to actually see the logs from the task.

Screenshot 2023-12-05 at 1 42 35 PM
There is not enough contrast between edge lines and nodes.

**Comment by TedHaleyPDL** [comment]
I think the update essentially had the inverse effect of what it was trying to accomplish. By trying to include as much information as possible within the nodes (and subsequent densification of the graph), its actually lost a lot of the readability from a high level, which defeats the purpose of the graph in the first place.

**Comment by TedHaleyPDL** [comment]
Additionally, while straight lines to show dependencies between tasks looks orderly, it is harder to follow when there are multiple parallel and overlapping lines. The edges in the previous version were far more simple to follow as they were more distinct.

**Comment by TedHaleyPDL** [comment]
I was hoping for feedback on my comments as this is THE place to discuss the changes implemented by this PR with those who made them. Opening an issue might be a waste of everyones time if my opinions of the changes are not shared, and perhaps there was a reason for these changes that I am not aware of.

**Comment by wpromatt** [comment]
@potiuk  The only thing I can't figure out with this new view is how to go to the "graph" view from a link to the task logs. The redirection doesn't work when the dag run you're trying to view in a graph is outside the default selected number of dag runs.

Link to task logs. Note how the "graph" button goes to `/dags/ninjacat_listener/graph?root=&execution_date=2024-01-17T21%3A08%3A00%2B00%3A00`.

Screenshot 2024-01-18 at 8 09 28 PM

Since this particular dag run was like 200 or so dag_runs in the past, once redirected the graph shows without a selected run. I can only go there by manually adding `&num_runs=200` to the url that graph link sends you to.

**Comment by wpromatt** [comment]
This is also true when clicking on dag_run from the list dag_run tables.

**Pull request merged**
