### PR TITLE
Don't pass auth to opensearch client with empty login and password

### LINKED ISSUE #39979: Opensearch hook passes auth even if login and password are blank
### Apache Airflow version

2.9.1

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

When leaving the login and password values blank, the opensearch hook passes empty strings to the `http_auth` parameter of opensearch which ends up generating an `Authorization` header with a mostly empty base64 encoded value.

### What you think should happen instead?

If no login or password are passed, no `http_auth` argument should be provided. The [elasticsearch provider works in this way](https://github.com/apache/airflow/blob/main/airflow/providers/elasticsearch/hooks/elasticsearch.py#L66-L69).

### How to reproduce

Don't set a login or password on an opensearch hook connection and try to use it to connect.

### Operating System

Debian GNU/Linux 11 (bullseye)

### Versions of Apache Airflow Providers

apache-airflow-providers-opensearch==1.1.2

### Deployment

Official Apache Airflow Helm Chart

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pdebelak**
This updates the opensearch hook to only pass the http_auth argument to the opensearch client if a login and password are part of the connection.

closes: #39979

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
cc @cjames23 can you take a look?

**Review by ranade1 — APPROVED** [review]
looks good.

**Comment by topherinternational** [comment]
@eladkal @cjames23 is there any review action coming on this? 

My org could really use this change, we hit AWS OpenSearch with no auth (instead we validate that the client is inside our VPC/VPN). To get around the bug, we currently subclass the OpenSearchHook to shim in pretty much this exact code change. Would be great to not have to have this subclass at all.

**Comment by topherinternational** [comment]
@eladkal ping again on reviewing this? cjames seems to be off the grid.

**Review by Owen-CH-Leung — APPROVED** [review]

**Comment by Owen-CH-Leung** [comment]
LGTM. This aligns with the Elasticsearch provider behaviour too

**Review by eladkal — APPROVED** [review]

**Pull request merged**
