### PR TITLE
[AIRFLOW-1886] Failed jobs are not being counted towards max_active_runs_per_dag

### PR DESCRIPTION
**Pull request by oyamin**
### JIRA
- [ ] My PR addresses the following issues
    - https://issues.apache.org/jira/browse/AIRFLOW-1886

### Description
- [ ] Here are some details about my PR, including screenshots of any UI changes:
    - Currently, AirFlow is not honoring the max_active_runs_per_dag in airflow.cfg when a DAG aborts. The current setup will keep submitting next scheduled DAG not counting any failed incomplete DAGs that are already in the queue. Added failed_runs to jobs.py in order to count aborted DAGs also.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
    - There are no unit tests but I have been running this fix in production for almost 6 months.

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Failed jobs are not running so why shoul they count towards max active runs?

**Comment by oyamin** [comment]
If you have 20 DAGs, each with 20-30 tasks running every 30 minutes and it takes 4 hours to resolve the issue, you end up with 160 failed DAGs and 1000+ tasks, filling up your queue instead of 40 DAGs (if you have max dag run set to 2). Because, when a task fails in DAG_1, DAG_2 comes in the queue and aborts the same task in that DAG, and so on. Much easier to manage when you need to catch up with data and restart tasks.

Possible alternative option would be to add the failed_count to airflow.cfg

**Comment by r39132** [comment]
@oyamin do you mind adding a test case for this? Also, please squash your commits.

**Comment by bolkedebruin** [comment]
I dont think this is the right fix. I like the `failed_count` or `max_failed_count` better, although that might still have issues.

**Pull request closed without merging**
