### PR TITLE
More documentation update for June providers release

### PR DESCRIPTION
**Pull request by potiuk**
The provider changelogs were already merged but they could not be
released due to unavailability of signing key in remote location
The documentation has once more been updated, including latest
merges - documentation-only changes were removed from
bugs/feetures/breaking changes lists.

Few other improvements:

* Pre-commit was added to make sure that the documentation
  in provider's index.rst files includes the latest changelog.
* Index.rst now contain includes of the CHANGELOG.rst rather
  than copy of the CHANGELOG.rst
* The `prepare-provider-package` breeze command has --non-interactive
  flag now
* generated provider package README.rst contain changelog so you can
  see the changelog directly in PyPI

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
Some static checks and Pylint are failing

**Comment by potiuk** [comment]
> Some static checks and Pylint are failing

On it. I also wanted to add some more explicit comment about Airlow 2.1+compatibility in the CHANGELOGS.

**Comment by potiuk** [comment]
@kaxil 
* Added an explicit WARNING with 2.1 compatibility in changelogs/docs
* Fixed a new `pylint` error (unrelated and "random" as it happens with pylint, so I updated it)
* The static checks turned out to be lack of tags in the fetched git repo in static check job (we are using it verify if all the changes since previous release are present in the CHANGELOG/index.rst for provider where changelog is automatically included - this way we can be sure we have not missed any change)- fixed it with adding fetch-depth 0 in static-checks job.

**Comment by potiuk** [comment]
I also realized that I do not have to copy the changelog but I can include it in the idex.rst so I fixed this. Also fixed the "suggest 
a change" link -> https://github.com/apache/airflow-site/issues/417

**Comment by potiuk** [comment]
Sounds like just unrelated MSSQL random problem @kaxil (and I also incorporated few last merges for some simple/straightforward fixes that waited for approval). 
I've gone through several iterations of that and rebasing/updating the PR and it seems to work really nice now with `..include` of changelog and commented out issues/chores that should not be included in the changelog. The changelog update works hand-in-hand with the upcoming #16419 to generate the "test status" issue and  we have a really nice way to manage and verify that we have not forgotten some changes in changelogs + get the community-driven testing via the issue with test status in an easy way to prepare and manage for release manager.

**Comment by potiuk** [comment]
All green and ready to merge!

**Review by kaxil — APPROVED** [review]

**Pull request merged**
