### PR TITLE
D401 Support - Macros to Operators (Inclusive)

### PR DESCRIPTION
**Pull request by ferruzzi**
Part of https://github.com/apache/airflow/issues/10742

D401 asserts "First line should be in imperative mood".  This is a little opaque so upon further investigation what they want is:  

```
[Docstring] prescribes the function or method's effect as a command: 
("Do this", "Return that"), not as a description; 
e.g. don't write "Returns the pathname ...".
```

We started with over two thousand violations in the repo so I'm going to take this in bites.

### PLEASE NOTE

There should be zero logic changes in this PR, only changes to docstrings and whitespace.  If you see otherwise, please call it out.

### Included in this chunk

All files located in the following modules:

- airflow/macros
- airflow/metrics
- airflow/migrations
- airflow/models
- airflow/notifications
- airflow/operators

### To test

If you uncomment [this line](https://github.com/apache/airflow/blob/main/pyproject.toml#L61) and run pre-commit in main you will get over a thousand errors.  After these changes, no files in the list above should be on the list.  After re-commenting that line and re-running pre-commits, there should be zero regressions.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Static checks need fixing :)

**Comment by aritra24** [comment]
@ferruzzi looks like you need to run pre-commit locally to regenerate an er diagram and commit that.

**Review by hussein-awala — APPROVED** [review]

**Comment by ferruzzi** [comment]
I wasn't expecting those files to be generated so I didn't include them in the commit.   This should fix it.

**Comment by potiuk** [comment]
> I wasn't expecting those files to be generated so I didn't include them in the commit. This should fix it.

Our CI is sometimes smarter than we are, indeed.

**Pull request merged**
