### PR TITLE
Update google-cloud-spanner version

### PR DESCRIPTION
**Pull request by lwyszomi**
Update package to give users possibility to install `sqlalchemy-spanner`.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by lwyszomi** [comment]
@potiuk Could you assign someone to review?

**Comment by mik-laj** [comment]
To add support for `sqlalchemy-spanner`, we should also add `get_uri` method.
https://github.com/apache/airflow/blob/33edeb2cb1c83c61f2ce5981066228d10a77df5b/airflow/providers/snowflake/hooks/snowflake.py#L216-L219

**Comment by potiuk** [comment]
Rebased it to latest main - let's see  if it works.

**Comment by lwyszomi** [comment]
@potiuk @mik-laj I was offline most of the week, Thanks for feedback I will update my PR in this week.

**Comment by lwyszomi** [comment]
@mik-laj When we add `get_uri` method we should also extend this hook and add inheritance from `DbApiHook`?

**Comment by mik-laj** [comment]
@lwyszomi , Yes. Thanks to this, we will be able to use it in other places where DBApiHook class is expected. Users will also not need to study this class specifically, as they will be able to rely on a unified interface.

**Comment by lwyszomi** [comment]
@mik-laj I have one more think in my mind, if we extend this hook maybe by default we should add `sqlalchemy-spanner` to the google provider packages, WDYT?

**Comment by mik-laj** [comment]
@lwyszomi Yes. We should do it. Thanks to this, we will avoid dependency conflicts, because problems will be detected on the CI.
https://github.com/apache/airflow/blob/774ca085d2d2d58d4292b43c3511a145cc07154b/setup.py#L513-L516

**Comment by potiuk** [comment]
Yep. Good idea.

**Comment by potiuk** [comment]
> @potiuk @mik-laj This change for now is blocked because we have a issue with the dependencies. The Airflow supporting `sqlalchemy<1.4.10,>=1.4` but `sqlalchemy-spanner` supporting `sqlalchemy<=1.3.23,>=1.1.13`. Conflict for now cannot be resolved, we need to wait when `sqlalchemy-spanner` will support `sqlalchemy<1.4.10,>=1.4`.

Too bad. I opened issue for that: https://github.com/googleapis/python-spanner-sqlalchemy/issues/204

**Comment by lwyszomi** [comment]
@potiuk thanks

**Comment by potiuk** [comment]
Apparently, support  (and test case suite) was added in January but the setup.py has not been updated :)

🤷

**Pull request closed without merging**
