### PR TITLE
Convert our internal tools to use rich_click

### PR DESCRIPTION
**Pull request by potiuk**
Rich_click provides out-of-the-box beautifying of the click command
line tools to provide 'rich' help output.

This PR changes our internal tools (including the new Breeze2
in-progress effort to use rich click to make our help nicer.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by potiuk** [comment]
cc: @Bowrna @edithturn

**Comment by potiuk** [comment]
Some screenshots :) 

Screenshot 2022-02-19 at 20 53 44
Screenshot 2022-02-19 at 20 53 14
Screenshot 2022-02-19 at 20 43 16

**Comment by potiuk** [comment]
BTW. Should we convert Airflow to use click ? Seems more and more worth it.

**Review by turbaszek — APPROVED** [review]
Love this change! 🙌

**Pull request merged**
