### PR TITLE
Add calendar view to react

### LINKED ISSUE #37902: Calendar view infinite loop for `@continuous` DAGs
### Apache Airflow version

main (development)

### If "Other Airflow 2 version" selected, which one?

_No response_

### What happened?

The `/dags/<string:dag_id>/calendar` view does not open for DAGs, that have `schedule='@continuous'`.

It happens because this loop in `airflow.www.views.Airflow.calendar` is practically infinite.
```python
while True:
    curr_info = dag.timetable.next_dagrun_info(
        last_automated_data_interval=last_automated_data_interval,
        restriction=restriction,
    )
    if curr_info is None:
        break  # Reached the end.
    if curr_info.logical_date <= prev_logical_date:
        break  # We're not progressing. Maybe a malformed timetable? Give up.
    if curr_info.logical_date.year != year:
        break  # Crossed the year boundary.
    last_automated_data_interval = curr_info.data_interval
    dates[curr_info.logical_date] += 1
    prev_logical_date = curr_info.logical_date
```

The `prev_logical_date` and `curr_info.logical_date` are both set to `timezone.utcnow()` at consecutive loop iterations. This is why `curr_info.logical_date <= prev_logical_date` never fails and `curr_info.logical_date.year != year` waits for the end of the year.

### What you think should happen instead?

I'm not sure, what is the best way to solve this:
1.  Check if `dag.timetable` is `ContinuousTimetable`
2. Limit the number of iterations
3. Check that the diff between `curr_info.logical_date` and `prev_logical_date` is at least some amount - 1 minute or so.

### How to reproduce

Make `@continuous` DAG and check the calendar view.

### Operating System

-

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### Anything else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bbovenzi**
Continue to modernize the UI by building the calendar view in React. The tab is visible when a user has no run or task selected in the grid view.

Next up, I will delete the old page and redirect to this tab.

Screenshot 2024-03-05 at 1 49 49 PM

Monthly DAG:
Screenshot 2024-03-05 at 1 50 30 PM

Tooltip:
Screenshot 2024-03-05 at 1 50 14 PM

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by bbovenzi** [comment]
Also fixes: https://github.com/apache/airflow/issues/37902

**Comment by potiuk** [comment]
Fantastic!

**Review by potiuk — APPROVED** [review]

**Review by jscheffl — APPROVED** [review]
Cool!

As it might be confusing that the old calendar is top-down and the new one is bottom-up in ordering of the years... can you remove the old one prior 2.9.0 release cut?

**Comment by bbovenzi** [comment]
> Cool!
> 
> As it might be confusing that the old calendar is top-down and the new one is bottom-up in ordering of the years... can you remove the old one prior 2.9.0 release cut?

Yes, my intention is to remove all of these legacy pages in time for 2.9

**Review by phanikumv — APPROVED** [review]

**Pull request merged**
