### PR TITLE
Revert "[AIRFLOW-5746] move FakeDateTime into the only place it is used (#6416)"

### PR DESCRIPTION
**Pull request by mik-laj**
This reverts commit adfcf67d6532350071336390bcb4dad0b99ae450.

This commit is not valid because this package is intentionally pulled into a separate file.
More information: #6098 (comment)

CC: @mr-c @potiuk @Fokko 

---

Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-XXX
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
We cannot revert it as it is because in this case database init will fail when you run 'airflow db reset'. It fails because (for whatever reason) the fake_datetime cannot be imported. We had this problem during the workshop.

I don't think we should rely on the fact that the PYTHONPATH is set properly in totally unrelated plaes 
 - where adding those test/utils is super strange. Actually I even added some time ago a comment in run-test as I did not know what it is about:

```# add test/test_utils to PYTHONPATH TODO: Do we need that ??? Looks fishy.```

Now I understand why it was done, but it was not all all obvious - I missed the #6098 discussion.

We cannot simply revert it, instead I think we should improve the test. Seeing the purpose of the test, I think it should be done a bit differently:

* PYTHONPATH should not be set in the run-tests, It should be modified by the test just before running the impersonation (and restored after). It is really bad idea to modify global PYTHONPATH in separate script in order to run one test only.
 
*  The import should be a local import inside print_today() method - rather than the top-level one that can be imported elsewhere. This way if for any reason the python file is parsed/imported it will not fail with "missing import" only when it is executed.

@mik-laj  - would you like to do those changes :) ?

**Comment by mik-laj** [comment]
> We cannot revert it as it is because in this case database init will fail when you run 'airflow db reset'. It fails because (for whatever reason) the fake_datetime cannot be imported.

This should not happen because these files are in the tests directory and should not be taken into account by normal installations.

I have to look at the whole test again, because it is possible that there is actually a better solution. For now I wanted to restore the state not worse than it was before.

**Comment by potiuk** [comment]
> I have to look at the whole test again, because it is possible that there is actually a better solution. For now I wanted to restore the state not worse than it was before.

Yet - for some reason - (not sure why) they were imported and they were impacting the new contributors installing environment and running the db init. That was a blocker from using development environment which I think is a valid reason to fix it properly rather than revert (as we know reverting will impact the new contributors).

I think we should look for a good, robust solution rather than reverse to something that we already know blocks people from contributing to Airflow.

J.

**Comment by mik-laj** [comment]
I have created a new PR that introduces the additional changes you expect.
https://github.com/apache/airflow/pull/6436

**Comment by mik-laj** [comment]
> The import should be a local import inside print_today() method - rather than the top-level one that can be imported elsewhere. This way if for any reason the python file is parsed/imported it will not fail with "missing import" only when it is executed.

I do not like to modify the input data so that the tests pass. I have moved this file to a separate directory that is not loaded by default.

**Comment by potiuk** [comment]
This is superseded by #6436

**Pull request closed without merging**
