### PR TITLE
Add volumeClaimTemplate for worker in Helm chart

### PR DESCRIPTION
**Pull request by khtee**
Problem: The current Helm chart doesn't support additional persistence volume for worker statefulset.

Resolution: Adding in new feature to add extra volumeClaimTemplates for additional persistent volume needed by statefulset.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
@KHTee can you rebase and resolve conflicts?

**Comment by KHTee** [comment]
@eladkal rebase done

**Comment by eladkal** [comment]
> @eladkal rebase done

Tests are failing :(

**Comment by eladkal** [comment]
The test added in this PR is failing

```
=========================== short test summary info ============================
FAILED helm_tests/airflow_core/test_worker.py::TestWorker::test_should_add_extra_volume_claim_templates - subprocess.CalledProcessError: Command '['helm', 'template', 'release-name', '/opt/airflow/chart', '--values', '/tmp/tmp5japxht5', '--kube-version', '1.23.17', '--namespace', 'default', '--show-only', 'templates/workers/worker-deployment.yaml']' returned non-zero exit status 1.
================== 1 failed, 319 passed in 1753.87s (0:29:13) ==================
```

**Comment by KHTee** [comment]
> The test added in this PR is failing
> 
> ```
> =========================== short test summary info ============================
> FAILED helm_tests/airflow_core/test_worker.py::TestWorker::test_should_add_extra_volume_claim_templates - subprocess.CalledProcessError: Command '['helm', 'template', 'release-name', '/opt/airflow/chart', '--values', '/tmp/tmp5japxht5', '--kube-version', '1.23.17', '--namespace', 'default', '--show-only', 'templates/workers/worker-deployment.yaml']' returned non-zero exit status 1.
> ================== 1 failed, 319 passed in 1753.87s (0:29:13) ==================
> ```

Yes, give me some time. I'm fixing the test cases.

**Comment by KHTee** [comment]
@eladkal  done fixing the test case

**Review by hussein-awala — APPROVED** [review]
I pushed a commit to simplify the render method and fix the unit test. LGTM

**Review by eladkal — APPROVED** [review]

**Pull request merged**
