### PR TITLE
[AIRFLOW-1700] Support conn_type overwrite when url scheme is invalid

### PR DESCRIPTION
**Pull request by fenglu-db**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
https://issues.apache.org/jira/browse/AIRFLOW-1700

### Description
When creating a new connection via airflow cli, the connection type is inferred from the conn-uri argument (i.e., conn_type = url scheme). However, for connection types like "hive_cli" and "google_cloud_platform", urlparse (by design) was unable to get the connection type as '_' is not a valid scheme character.

### Tests
- updated tests.core:CliTests.test_cli_connections_add_delete and local unit test passed without any issue.

### CODE REVIEW

**Comment by fenglu-db** [comment]
@criccomini  PTAL and can we also get this into 1.9.0-alpha1? 
Thank you.

**Comment by mrkm4ntr** [comment]
Sorry, this duplicates with #2525.

**Comment by fenglu-db** [comment]
Ack, missed that when I searched open issues re:conn_type. Thanks for the link.

@mrkm4ntr @criccomini 
I like the ability to parse connection details from URI, it unfortunately breaks when scheme contains '_'. Instead of making every connection field accept cmd args (as in #2525), shall we just make conn-type overwritable? My concern is that It might be confusing when conn details can be set in multiple ways. I can also revise my PR to take conn_type only when scheme is None. IOW, conn_uri takes precedence over conn-type.  LMK.

**Comment by mrkm4ntr** [comment]
@fenglu-g In my first commit, it was a fix like your suggestion to only add conn_type and overwrite it only if the schema is None. However, as discussed [here](https://issues.apache.org/jira/browse/AIRFLOW-1330),  I changed to the current fix because it is not preferable the schema of URI to be None.
I think that it is better to be able to give conn_uri which does not cause an error I think that it is better to be able to give conn_uri which does not cause an error even if contains `_`, or to give the same parameter as when registering from UI., or to give the same parameter as when registering from UI.

Anyway, if we continue discussion any further, I think I should do it [here](https://issues.apache.org/jira/browse/AIRFLOW-1330).

**Comment by fenglu-db** [comment]
The discussion is moved to  #2525, closing this PR now.

**Pull request closed without merging**
