### PR TITLE
[AIRFLOW 1149] Allow for custom filters in Jinja2 templates

### PR DESCRIPTION
**Pull request by NielsZeilemaker**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [X] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1149) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-1149

### Description
- [X] Here are some details about my PR, including screenshots of any UI changes:
I've added a user_defined_filters argument to the DAG() constructor to be able to add custom filters to the Jinja2 templating engine. See http://jinja.pocoo.org/docs/dev/api/#writing-filters for more details.

### Tests
- [X] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
I've added some new Jinja2 unit-tests, I couldn't find any existing ones.

### Commits
- [X] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Hi @NielsZeilemaker thanks for your contribution. Your tests seem a bit weirdly placed, why not just unit tests the affected functions?

**Comment by NielsZeilemaker** [comment]
@bolkedebruin I partly agree that my tests are more end-to-end than unit. I've added a test in models which verifies if a filter ends up in the jinja environment

**Comment by bolkedebruin** [comment]
@NielsZeilemaker Thanks. Can you please move your dummy_operator tests into tests/models.py? And then squash your commits? Rest LGTM

**Comment by NielsZeilemaker** [comment]
@bolkedebruin I've moved the tests and did a squashed all my commits

**Pull request closed without merging**
