### PR TITLE
feat: add Dataproc preemptibility to ClusterGenerator class

### PR DESCRIPTION
**Pull request by tqtensor**
motivation: allowing users to specify the type of VM machine in the `secondary_worker_config`, according to the enum definition from Google's [Dataproc Python client](https://github.com/googleapis/python-dataproc/blob/8d5e6d8b756bffa44227bdf5dd27223e45facd57/google/cloud/dataproc_v1/types/clusters.py#L815)

test: [test_build](https://github.com/apache/airflow/blob/f5775b648c40be6aab72581830c54fd1335fc54f/tests/providers/google/cloud/operators/test_dataproc.py#L368)

related: #28399

### CODE REVIEW

**Comment by mcoca-dst** [comment]
This improvement is very useful. I can't create Dataproc clusters from Airflow, using the `DataprocCreateClusterOperator`. When you think this improvement will be implementing?

**Comment by tqtensor** [comment]
I used to implement this fix a few weeks ago and then created a PR to merge. But I wonder why no one reviewed it even though I asked in the Slack channel to review PR. So finally, I closed the PR and could not proceed anymore.

**Comment by potiuk** [comment]
Because likely you were unlucky and not patient enough. When you have 100s of PRs to look at you can miss some of those.  Feel free to re-open it and try again. And you can watch my talk about empathy to understand why things lile that happens 

https://www.youtube.com/watch?v=G6VjYvKr2wQ

**Comment by potiuk** [comment]
(also @mcoca-dst you can just open and re-submit similar change again if @tqtensor's experience is so bad that he decides not to try again, this feature indeed ssems useful for dataproc users so it would be quite a waste to loose it due to frustration and lack of persistence and understanding that sometimes things can be simply lost between 100s of messages.

**Comment by tqtensor** [comment]
Nice to hear from you, @potiuk; I will reopen the PR again. I understand and acknowledge your message from the video. 😀

**Pull request closed without merging**
