### PR TITLE
Chart: template dagprocessor waitformigrations extraVolumeMounts

### PR DESCRIPTION
**Pull request by Aakcht**
Looks like #30990 got a bit mixed up with #30773 and the extraVolumeMounts of dagprocessor wait for migrations init container are not templated, while other extraVolumeMounts are templated.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jedcunningham** [comment]
Can you add test coverage for this as well? Thanks.

**Comment by Aakcht** [comment]
@jedcunningham, I added the tests, please  take a look. Looks like the failing check is not related to this PR.

**Review by hussein-awala — COMMENTED** [review]
I see a lot of updates on chart tests which are not related to this change, maybe we should move them to a separate PR and keep only dag-processor tests in this one.
@jedcunningham wdyt?

**Comment by Aakcht** [comment]
I'd say updates on chart tests are somewhat related to this change - I just modified the tests so they would test templating of extraVolumeMounts/extraVolumes for all components, not just for dagProcessor. But if you do think it would be better to separate the changes, please tell me - I'll move changes not related to dag-processor to a separate PR.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> I'd say updates on chart tests are somewhat related to this change  

Yeah. Those tests changes seem related, I ofen use opportunities like that to generally improve test code. Seems that thos test change still test what they were supposed to test (but better) and there is no functional change to the airflow code, so very little risk with having them in single PR.

**Comment by potiuk** [comment]
WDYT @hussein-awala @jedcunningham ?

**Review by hussein-awala — APPROVED** [review]
> But if you do think it would be better to separate the changes, please tell me

No objection on my part, LGTM

**Pull request merged**
