### PR TITLE
[AIRFLOW-4505] Correct Tag ALL for PY3

### PR DESCRIPTION
**Pull request by raphaelauv**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-4505\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4505
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

A new tag , so  we could get ALL PY3 packages ( without PY2 )

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by raphaelauv** [comment]
Do I need to base the PR on something else than master ? So the current Pypi on 1.10.3 , work directly when this PR is (I hope) merged

**Comment by potiuk** [comment]
I think we should just remove the PY3 check in master. In master we anyhow only support PY3 now. If we would like to change it in 1.10.x series we should branch it from v1-10-test, but I think there installing devel_ci would do the trick and maybe we should not introduce a new tag just for that in the 1.10.x series.

**Comment by raphaelauv** [comment]
@potiuk Thank you , I just changed the base of the PR to v1-10-test.

Yes devel_ci do the trick , but that's what I was arguing against in the issue of the PR :
https://issues.apache.org/jira/browse/AIRFLOW-4505

It's not very user friendly.

**Comment by potiuk** [comment]
OK. I looked back at it, and I have second thought.

Would not it be better to simply make devel_all conditional based on PY3 same way devel_ci is done? that would not introduce new tag, and it would magically work if you run it in py3 virtualenv :) @raphaelauv .

**Comment by raphaelauv** [comment]
@potiuk It could, but for people currently using devel_all with PY2 it would be a regression , is this a risk you want a take ?

**Comment by potiuk** [comment]
@raphaelauv What regression ? I cannot see any scenario where it could break things ? If you are using py2 it will continue working as it did before. It's just py3 will not install snakebite .

**Review by potiuk — APPROVED** [review]
That's much nicer :)

**Comment by aijamalnk** [comment]
Should this be merged now that it's approved?

**Pull request merged**
