### PR TITLE
Fix `enable_logging=True` not working in `DockerSwarmOperator`

### LINKED ISSUE #28452: TaskInstances do not succeed when using enable_logging=True option in DockerSwarmOperator
### Apache Airflow Provider(s)

docker

### Versions of Apache Airflow Providers

apache-airflow-providers-celery==3.1.0
apache-airflow-providers-docker==3.3.0

### Apache Airflow version

2.5.0

### Operating System

centos 7

### Deployment

Other Docker-based deployment

### Deployment details

Running an a docker-swarm cluster deployed locally. 

### What happened

Same issue as https://github.com/apache/airflow/issues/13675

With logging_enabled=True the DAG never completes and stays in running. 

When using DockerSwarmOperator together with the default enable_logging=True option, tasks do not succeed and stay in state running. When checking the docker service logs I can clearly see that the container ran and ended successfully. Airflow however does not recognize that the container finished and keeps the tasks in state running.

### What you think should happen instead

DAG should complete.

### How to reproduce

Docker-compose deployment:
```console
curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.5.0/docker-compose.yaml'
docker compose up airflow-init
docker compose up -d
```

DAG code:

```python
from airflow import DAG
from docker.types import Mount, SecretReference
from airflow.providers.docker.operators.docker_swarm import DockerSwarmOperator
from datetime import timedelta
from airflow.utils.dates import days_ago
from airflow.models import Variable


# Setup default args for the job
default_args = {
	'owner': 'airflow',
	'start_date': days_ago(2),
	'retries': 0
}
 
# Create the DAG
dag = DAG(
    'test_dag',         # DAG ID
    default_args=default_args,
    schedule_interval='0 0 * * *', 
    catchup=False
)

# # Create the DAG object
with dag as dag:
	  docker_swarm_task = DockerSwarmOperator(
			task_id="job_run",
			image="<any image>",
			execution_timeout=timedelta(minutes=5),
			command="<specific code>",
			api_version='auto',
			tty=True,
			enable_logging=True
		)
```

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by stavdav143**
Docker Swarm Operator was impractical as the Docker Service created was never finished in the airflow scheduler. Also logs were not received.  With this fix we make docker swarm services finite and we track their logs properly. 

The logging logic works like this:
For the current service we ask the docker API client to give us the logs with the `follow=False`. Otherwise, `follow=True` hangs for ever when the service has finished. 
We poll the docker API in 2 minute intervals, throwing logs to the console and checking if the service has terminated in order to break the loop.
 
Closes: #28452

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by eladkal** [comment]
Can you add unit test to avoid regression?

**Comment by stavdav143** [comment]
Hi @eladkal, 

Thanks for reviewing. yes I understand, I ve been facing some difficulties while trying to provide a demo gif. I will look into if I can add tests, to me it is a bit complicated as Docker infrastructure is involved and these here [docker_swarm_tests](https://github.com/apache/airflow/blob/main/tests/providers/docker/operators/test_docker_swarm.py ) look more mock. But I will look into a bit deeper and see what I can provide.

**Comment by stavdav143** [comment]
This below explains how this PR fixes the Docker Swarm Operator issues:

Bug
Below the task never ends and the logs are not being streamed (before this fix):
output_bug

With fix
Below the task ends and the logs are being streamed sychronously (this fix):
output

**Comment by potiuk** [comment]
Hmm. The way it is implemented, it will generate more and more API traffic, the longer the task is runing. Basically every two seconds we are attempting to downaload all logs. I think this is not good approach.

I do not know the CLI appi but that does not sound like a good solution

**Comment by stavdav143** [comment]
Well this issue has been open for quite some time now. 

The alternative would be to use follow=True. This will stop and hang the thread by definition. You'd need a parallel thread to check if the service has finished, as this always hangs no matter what the state of the service (Running, Started, Waiting, Done) . In the end  you didn't improve much  because instead of polling the docker API you now poll the airflow API. And you have to introduce additional code with parallelism which in Python isn't great to my knowledge.

**Comment by potiuk** [comment]
> Well this issue has been open for quite some time now.
> 
> The alternative would be to use follow=True. This will stop and hang the thread by definition. You'd need a parallel thread to check if the service has finished, as this always hangs no matter what the state of the service (Running, Started, Waiting, Done) . In the end you don't avoid polling. And you have to introduce additional code with parallelism which in Python isn't great, at least to my knowledge.

We are already doing it for other operators - K8S and  no - you do not have to poll Airflow API. In many cases - when remote logging is involved, loggers are just logging to a remote loogging service (cloudwatch for example) which takes care about streaming logs to UI for example - se yes, you can absolutely avoid polling. 

You could likely use this: 

```
since (datetime, int, or float) – Show logs since a given datetime, integer epoch (in seconds) or float (in nanoseconds)
```

And ask the logs to include timestamps and use them.

Especially if you use float (nanoseconds) you could record the last log nanosecond  + maybe store last few lines and add a few nanoseconds of overlap and de-duplicate the overlapping lines. 

This is very similar to your proposal but will avoid potentially huge, increasing traffic and potentially huge memory used to keep the logs in memory. The way you implemented it, might cause MB and GB of memory wasted to keep whole log in-memory.

**Review by potiuk — CHANGES_REQUESTED** [review]
Need to handle memory and traffic better.

**Comment by potiuk** [comment]
> Well this issue has been open for quite some time now.

So yes. let's get it well implemented and merge it. But we cannot merge a change that we know has performance issues. The problem is that people WILL use it for long running operations and it WILL crash their workers. and they WILL come to us when it happens, so we better fix it now.

**Comment by stavdav143** [comment]
Ok valid feedback 👍. I'll see if I can make it more slim using the  "since" parameter and timestamps when asking for logs.

**Review by potiuk — APPROVED** [review]
Nice! That is much better !

**Comment by stavdav143** [comment]
Thank you!

**Comment by potiuk** [comment]
Though - it needs static checks fixes. I recommmend `pre-commit install` and it would fix those while commiting .

**Comment by stavdav143** [comment]
Hey, thanks a lot !

**Pull request merged**
