### PR TITLE
Cloudant Hook

### PR DESCRIPTION
**Pull request by mtp401**
Dear Airflow Maintainers,

Please accept the following PR that
- Implements a hook for [Cloudant](https://cloudant.com).

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks for the contribution. Can you please remove the copyright remark and readd the utf-8 header?

**Comment by mtp401** [comment]
@bolkedebruin, I added the UTF-8 header and removed the copyright. Cheers.

**Comment by bolkedebruin** [comment]
Ok. Now I am looking a bit better. https://github.com/cloudant-labs/cloudant-python is deprecated. Why are you not using the new library? Is the old library python 3 compatible? 

In addition, after resolving the issues, please squash your commits and use imperative for your commit message per guidelines.

**Comment by mtp401** [comment]
Just squashed and re-worded to use imperative. AFAIK, the old library is python 3 compatible. I didn't use the new library because it is still in alpha/beta and, from personal experience, isn't quite ready for production use (as far as feature completeness is concerned). The developers also aren't guaranteeing API stability yet.

**Pull request merged**
