### PR TITLE
Fixed failing Kubernetes tests after deny_all for experimental API

### PR DESCRIPTION
**Pull request by potiuk**
The tests were broken by  #9611

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
Side note

@kaxil @dimberman @ashb @turbaszek @mik-laj - this is an example of where splitting to separate repo would have been problematic.

This change should have been committed together with #9611 and it would have been rather complex to test if the helm chart and kubernetes were separate repos. It would not work with the scheme proposed by @kaxil where we only use "released" versions of helm chart for Airflow tests and the other way round because in this case changing the backend auth to "deny_all" had to be coupled with adding new configuration value in the helm chart. 

It could work with the submodule scheme I proposed but as discussed with @dimberman yesterday - just coordinating this simple change across two PRs done in two different repos would have been a much more complex task.

And this is just one small change ...

I really think that monorepo approach and possibly split-out to separate repos with pushing only related changes (like @ryw commented) could be a much better solution.

**Comment by kaxil** [comment]
> Side note
> 
> @kaxil @dimberman @ashb @turbaszek @mik-laj - this is an example of where splitting to separate repo would have been problematic.
> 
> This change should have been committed together with #9611 and it would have been rather complex to test if the `chart` and `airflow` were separate repos. It would not work with the scheme proposed by @kaxil where we only use "released" versions of helm chart for Airflow tests and the other way round because in this case changing the backend auth to "deny_all" had to be coupled with adding new configuration value in the helm chart.
> 
> It could work with the submodule scheme I proposed but as discussed with @dimberman yesterday - just coordinating this simple change across two PRs done in two different repos would have been a much more complex task.
> 
> And this is just one small change ...
> 
> I really think that monorepo approach and possibly split-out to separate repos with pushing only related changes (like @ryw commented) could be a much better solution.

I think it should still work. If it doesn't the chart is not robust enough. In theory, the chart should allow overriding any runtime Airflow configs.

**Comment by potiuk** [comment]
> I think it should still work. In theory, the chart should allow overriding any runtime Airflow configs. In this case we could have used Environment Variable to set config. If we are not able to do we would anyway hit that limitation

In theory, theory and practice are the same. In practice, they are not.

**Comment by kaxil** [comment]
Well you could just set up Environment variable, here

https://github.com/apache/airflow/blob/master/chart/values.yaml#L94-L98

So theory and in-practise here are not different

**Comment by potiuk** [comment]
> Well you could just set up Environment variable, here
> 
> https://github.com/apache/airflow/blob/master/chart/values.yaml#L94-L98
> 
> So theory and in-practise here are not different

But this could be much more complex change needed to make this works - this is really one liner that shows how simple it is now to fix those kind of problems and how complex it could be if we split.

**Comment by kaxil** [comment]
But why not use Environment Variables to set configs. That's what we want to allow users to do too with the Chart, they would like to override any config.

**Comment by potiuk** [comment]
Having a dedicated config is much nicer solution. And if we were to do this for split repos we would have to implement "workaround" first, "good solution" in a chart repo, release the repo and finally implement a "good" solution. I am sure it is not worth it and I love how kubernetes team solved it.

**Comment by kaxil** [comment]
On the flip side changes in the Helm Chart should not affect Airflow's CI. In this case, the default of disabling API should just be a change in Airflow and should not be a change in the Helm chart version until a new Airflow version is released.

> Having a dedicated config is much nicer solution. And if we were to do this for split repos we would have to implement "workaround" first, "good solution" in a chart repo, release the repo and finally implement a "good" solution. I am sure it is not worth it and I love how kubernetes team solved it.

We already have a dedicated config `default_test.cfg` (https://github.com/apache/airflow/blob/master/airflow/config_templates/default_test.cfg) we should be using that for tests.

I don't see a need of "workaround" here?

Btw I am not against the Kubernetes way, I will look into the details and let you'll know on the thread. But as of now I am still on the "separate repo" side

**Comment by potiuk** [comment]
> On the flip side changes in the Helm Chart should not affect Airflow's CI. In this case, the default of disabling API should just be a change in Airflow and should not be a change in the Helm chart version until a new Airflow version is released.

*Should*. This is a nice idea, but until we are really stable and have all the details worked out for helm chart and dockerfile there will be hiden couplings - even beyond that. IMHO this is the same fallacy as with micro-services hype. With Micro-services in theory you have decoupled services that can be developed in isolation but in fact a lot of micro-services have hidden couplings and what you gain with separation, you loose on coordination. A lot of teams (especially those not huge ones) withdraw from micro-services approach (I'd say hype)  recently, precisely because it is not full-filing the promises (i.e. for smaller teams costs of coordination are far bigger than benefits of isolation). It's never 0-1, it's always cost-gain game.

I believe  we are still far to small (both code-wise and people-wise) and the "chart" and "dockerfile" are not big enough on it's own to get enough isolation benefits to cover the separation gain. 

> Btw I am not against the Kubernetes way, I will look into the details and let you'll know on the thread. But as of now I am still on the "separate repo" side

Please do. I think it's the "eat cake and have it too" case. We can fulfill all your expectations (separate releases, issues for users  in separate repos) while keeping much lower complexity of the development process.

**Comment by kaxil** [comment]
> > On the flip side changes in the Helm Chart should not affect Airflow's CI. In this case, the default of disabling API should just be a change in Airflow and should not be a change in the Helm chart version until a new Airflow version is released.
> 
> _Should_. This is a nice idea, but until we are really stable and have all the details worked out for helm chart and dockerfile there will be hiden couplings - even beyond that. IMHO this is the same fallacy as with micro-services hype. With Micro-services in theory you have decoupled services that can be developed in isolation but in fact a lot of micro-services have hidden couplings and what you gain with separation, you loose on coordination. A lot of teams (especially those not huge ones) withdraw from micro-services approach (I'd say hype) recently, precisely because it is not full-filing the promises (i.e. for smaller teams costs of coordination are far bigger than benefits of isolation). It's never 0-1, it's always cost-gain game.
> 
> I believe we are still far to small (both code-wise and people-wise) and the "chart" and "dockerfile" are not big enough on it's own to get enough isolation gains to cover the separation cost.
> 
> > Btw I am not against the Kubernetes way, I will look into the details and let you'll know on the thread. But as of now I am still on the "separate repo" side
> 
> Please do. I think it's the "eat cake and have it too" case. We can fulfill all your expectations (separate releases, issues for users in separate repos) while keeping much lower complexity of the development process.

I would say we should not use the Helm Chart for test until it gets stable then. WDYT?
Let's work on getting the Helm Chart to the ideal stable before using it for tests.

**Comment by kaxil** [comment]
> Please do. I think it's the "eat cake and have it too" case. We can fulfill all your expectations (separate releases, issues for users in separate repos) while keeping much lower complexity of the development process.

Yup definitely :)

**Comment by ashb** [comment]
Monorepo FTW.

**Pull request merged**
