### PR TITLE
AIRFLOW-2335 - Travis can't download jdk8

### PR DESCRIPTION
**Pull request by dimberman**
Make sure you have checked _all_ steps below.

### JIRA
- [ ] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2335
    - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a JIRA issue.

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

There is an issue with travis pulling jdk8 that is preventing CI jobs from running. This blocks further development of the project.

Reference: https://github.com/travis-ci/travis-ci/issues/9512#issuecomment-382235301

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

This PR can't be unit tested since it is just configuration. However, the fact that unit tests run successfully should show that it works.

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Documentation
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality
- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by dimberman** [comment]
@Fokko  @bolkedebruin  Assuming all tests pass could I please get a review on this? It's a pretty small change and should fix the travis issues preventing master from building.

**Comment by artwr** [comment]
LGTM overall. I'd love for this to get fixed by travis ci though...

**Comment by dimberman** [comment]
@artwr Agreed. Though they're aware of the issue so probably best to use the patch until they figure this out.

**Comment by artwr** [comment]
@dimberman done. Hopefully this gets fixed and we can remove the hack.

**Comment by Fokko** [comment]
My suggestion would be to move to OpenJDK

**Comment by artwr** [comment]
Not a bad idea. It would most likely not be subject to Oracle deciding to change the location for the download.

**Pull request closed without merging**
