### PR TITLE
Update workday example

### PR DESCRIPTION
**Pull request by john-jac**
**Updates to Workday Example in Customizing DAG Scheduling with Timetables**

The existing workday example provided a good demonstration of customizing DAG scheduling with timetables. However the benefits were somewhat limited over using a CRON string.

This PR provides a more robust example for Airflow users by adding a holiday filter to the existing weekend exclusions. The primary benefits of this change are as follows:

1. It provides a solution to a common use case for Airflow users that cannot be approximated with CRON.
2. It separates out the logic of determining whether to schedule on a given day from the common logic used by Airflow to request what the next scheduled date/time should be.

### CODE REVIEW

**Comment by potiuk** [comment]
Looks like there are related tests that need to be fixed

**Comment by potiuk** [comment]
Looks like there are related tests that need to be fixed

**Comment by john-jac** [comment]
> Looks like there are related tests that need to be fixed

Sorry Jarek...I didn't realize the sample code was being used in tests as well.  I've updated the corresponding test code and all checks have passed.

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
> Sorry Jarek...I didn't realize the sample code was being used in tests as well. I've updated the corresponding test code and all checks have passed.

No wories. This is normal :)

**Pull request merged**
