### PR TITLE
[AIRFLOW-5735][AIP-21] Move airflow.contrib.operators.s3_to_gcs_operator to core

### PR DESCRIPTION
**Pull request by louisguitton**
Make sure you have checked _all_ steps below.

### Jira

- [x] https://issues.apache.org/jira/browse/AIRFLOW-5735

### Description

- [x] Moving s3_to_gcs_operator to core. Follow-up of the Berlin ApacheCon workshop and #6424 

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

```
./breeze
run-tests tests.operators.test_s3_to_gcs_operator
run-tests tests.test_core_to_contrib
```
```
./scripts/ci/ci_docs.sh | grep -A5 WARNING
```

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by mik-laj** [comment]
Can you add a test in https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py?

**Comment by louisguitton** [comment]
> Can you add a test in https://github.com/apache/airflow/blob/master/tests/test_core_to_contrib.py?

Sure, done. Added the deprecation warning to make that test pass `run-tests tests.test_core_to_contrib`

**Comment by mik-laj** [comment]
I looked again and saw that the notes in the UPDATING.MD file were also missing. Can you add it? I'm sorry I didn't say earlier.

**Comment by louisguitton** [comment]
> I looked again and saw that the notes in the UPDATING.MD file were also missing. Can you add it?

Sure thing. Done

> I'm sorry I didn't say earlier.

No worries! In my previous PR I had touched that file => I could have realised too.

**Comment by BasPH** [comment]
Now that we have 2 ([1](https://github.com/apache/airflow/pull/6446), [2](https://github.com/apache/airflow/pull/6443)) PRs open for the AWS part of AIP-21, it would make more sense to move this operator directly to `/providers/aws/operators/s3.py` as described [here](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths#AIP-21:Changesinimportpaths-UpdatetotheoriginalpointD.(2019-10-11).).

**Comment by louisguitton** [comment]
Hey @BasPH , good point. As I can read: 

> In case of transfer operators where two providers are involved, the transfer operators will be moved to "source" of the transfer. 

Meaning in this case AWS indeed.
3 remarks from my point of view:

1. I was picking up the Jira ticket only, so if those are pretty flexible and we can change the scope mid-way no worries for me
2. I was not planning to tackle all aspects of AIP-21 in that PR (again just focussing on the Jira ticket): for example you could treat this operator for both `case 1` and `case 2`, but I was leaving `case 2` out of the scope of this PR. If it makes more sense to tackle both at the same time, let me know,
3. In the case of s3 to gcs there are 2 operators doing the job `s3_to_gcs_operator` and `s3_to_gcs_transfer_operator`. According to the quote above, they should both end up in `providers/aws` but in the case of `s3_to_gcs_transfer_operator`, it actually uses a gcp service under the hood and arguably could end up in `providers/google/gcp` 😅  . Is that rule of "source to destination" suppose to prevail anyway ?

**Comment by potiuk** [comment]
Actually I started to think that transfer operators should be placed in  "destination" rather than "source".

What do you think @louisguitton @BasPH @mik-laj ? 

Some background: Initially I thought it does not matter whether we choose source or target. But now I think differently. If we think in the future about splitting different providers to separate packages, and getting some kind of "stewardship" over the operator groups, it makes much more sense that the s3_to_gcs is under the "stewardship" of people who take care about the "providers/google" package rather than those of "providers/amazon". 

Knowing how it works, I guess people who take care about Google will be much more interested to transfer data from S3 to GCP rather than other way round. 

I will ask at the devlist if you share my feelings.

FYI @louisguitton FYI -> we are in the process of moving "providers/gcp" to "providers/google/[gcp, gsuite]" - this is the latest agreed proposal

**Comment by BasPH** [comment]
@potiuk There's something to say for both options, I don't really mind either way, as long as we pick one.

**Comment by louisguitton** [comment]
So the latest email on dev list regarding this is from beginning of October (prior to this PR's discussion) and concludes that we should use `source` as a folder https://lists.apache.org/thread.html/d8c1a72113fc01088d77a4f6d33371e465d20f7aa0d16232d8f93559@%3Cdev.airflow.apache.org%3E

I do like the destination folder idea. What do we do then for this PR and for the overall discussion?

**Pull request closed without merging**
