### PR TITLE
Move Integration tests to separate package under tests

### PR DESCRIPTION
**Pull request by potiuk**
This is the first stage of improving the way how integration tests are run in our CI - first we want to separate them in a separate packages, and then we want to run them separately - one integration each in the CI.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Looks cool. And Integration tests discovery is much faster now too. Maybe that alone will increase the stability of integration tests - because there is much lower number of Python test classes loaded during discovery for integration tests and maybe that will be enough to dcrease memory used during the tests.

**Review by Taragolis — APPROVED** [review]
Looking good.

Found interesting message in the CI, which not based on any changes in this PR.
For some reason (or maybe I just can't fully understand logic [of shell script](https://github.com/apache/airflow/blob/0d90c62bac49de9aef6a31ee3e62d02e458b0d33/scripts/in_container/check_environment.sh#L184-L188)) it shows that integrations disabled, but actually it run it 😮 
image

**Comment by potiuk** [comment]
> Looking good.
> 
> Found interesting message in the CI, which not based on any changes in this PR. For some reason (or maybe I just can't fully understand logic

Interesting :)

**Comment by potiuk** [comment]
> Found interesting message in the CI, which not based on any changes in this PR. For some reason (or maybe I just can't fully understand logic

I will fix it as part of splitting the integrations (and will remove some of the cryptic bash code serving it)

**Pull request merged**
