### PR TITLE
Add groups in CI output for parallell tasks

### PR DESCRIPTION
**Pull request by potiuk**
Some of our tasks run in parallel in CI. Their output is now grouped
one group per parallel task and printed at the end only.

Progress is displayed while the tasks are executed.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
This one addresses the problem of having nice, usable output of optimized, parallel execution of our CI jobs using the new breeze:

* building CI images
* building PROD images
* pulling images
* building constraints

In a follow-up PR I will also switch remaining tests to use it: Docker Compose, Helm and finally Regular tests to use it (which should complete Breeze converstion to Python.

What we get is:

* no more problems with ci groups overlapping each-other. The output groups of Github are non-hierarchical (one level deep) and this change follow it nicely (no further grouping if logs are already in a group)
* nicer command foldable CI output

Screenshot 2022-08-15 at 23 19 10

* nice and "smart" progresss output while the parallel execution happens. It understands what kind of output is showing real progresss for the types of outputs we know (docker build/pull/pytest etc).

Screenshot 2022-08-15 at 23 31 33

Including Pytest "%" progress

Screenshot 2022-08-15 at 23 32 45


* Folded "per-parallle-run" output that allows to see easily what happened in each run:

Folded:

Screenshot 2022-08-15 at 23 24 40


Unfolded PROD 3.7:

Screenshot 2022-08-15 at 23 26 14

**Comment by potiuk** [comment]
Would be nice to get this one merged, seems to be green - this is yet another step to get rid of Bash breeze scripts as it unblocks #25678 and #23538

**Comment by potiuk** [comment]
cc: @Bowrna  - once this one is merged, it should be easy to apply the shared "parallel" library approach to running tests in parallel (#23538) - it's really the matter of preparing List of outputs, and handling writing to a file if output is pased, instead of writing to stdout (and then adding method to show nicely the best one-line progrees from test outputs. 

So once we merge it, if you would like to rebase your change on top of it and make use of it, this would be the best approach (I am going to do that with #25678)

**Review by eladkal — APPROVED** [review]

**Comment by Bowrna** [comment]
Thanks @potiuk I am merging this changes into branch

**Pull request merged**
