### PR TITLE
[AIRFLOW-2313] Add optional TTL parameters for Dataproc operator

### PR DESCRIPTION
**Pull request by ebartkus**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-2313

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adds three extra optional parameters to the `DataprocClusterCreateOperator` and relevant unit tests as well.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

New tests:
* `test_build_cluster_data_with_autoDeleteTime` check if autoDeleteTime is added to config
* `test_build_cluster_data_with_autoDeleteTtl` check if autoDeleteTtl is added to config
* `test_build_cluster_data_with_autoDeleteTime_and_autoDeleteTtl` check if autoDeleteTime overrides autoDeleteTtl if both set

Updated tests:
* `test_build_cluster_data` additional checks for new parameters
* `test_init` additional checks for new paramteres

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### Code Quality
- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
   - There are some errors unrelated to this PR

### CODE REVIEW

**Comment by Fokko** [comment]
Like it a lot, @kaxil @fenglu-g, any comments? What are the implication of bumping the API version?

**Comment by exploy** [comment]
Looks like Travis build failed at unrelated test case `test_authorized` - can someone retry it? 

I like this change - we were looking at this option for some time already.

**Comment by Fokko** [comment]
@ebartkus Could you rebase onto master please? The flaky test has been fixed earlier.

**Comment by ebartkus** [comment]
Tests pass after rebase.

**Review by Fokko — APPROVED** [review]
Thanks @ebartkus merging!

**Comment by ebartkus** [comment]
Great, thanks!

**Pull request closed without merging**
