### PR TITLE
Mount volumes and volumemounts into scheduler and workers

### PR DESCRIPTION
**Pull request by dimberman**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — CHANGES_REQUESTED** [review]
I think we need two things here:

* We need to have json schema for the values added
* Maybe this is the right time that we start reqiuiring unit tests for all the changes in chart ? The current test coverage is spotty at best, so maybe this is the right time we switch to "do it well" mode.  

I am not talking about integration tests, I think those might be added later, but the unit tests would be great.

**Comment by dimberman** [comment]
@potiuk I think requiring unit tests is good call. Will also be glad to add json stuff (though might need to wait until tomorrow)

**Comment by dimberman** [comment]
@potiuk added tests and json

**Review by potiuk — APPROVED** [review]
LGTM :)

**Pull request merged**
