### PR TITLE
Format DAG run count

### PR DESCRIPTION
**Pull request by rafaelleinio**
DAGs with many runs are badly formatted inside the circle.

Current:
image

What I think could be better:
image

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by raphaelauv** [comment]
then I think we need to add an overlay to show the real value

**Review by jscheffl — COMMENTED** [review]
+1 to comment of @raphaelauv - really like this and I had also challenges in the past with 100k+ DAG runs in our environment.

Can you add a "title" which just renders a pop-up with you run with the mouse over it? Then I think it is OK to approve and merge.

**Comment by bbovenzi** [comment]
After @jscheffl's suggestions then I think this is good.

Ultimately, I don't know if total run state count is all that useful on the homepage. But that's a question for when we rewrite this page.

**Review by bbovenzi — APPROVED** [review]
Let's get this in for 2.10

**Pull request merged**
