### PR TITLE
Fix typo in multiple files, "overriden" is a misspelling of "overridden"

### PR DESCRIPTION
**Pull request by hugo-syn**
Fix typo in multiple files, "overriden" is a misspelling of "overridden"

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by uranusjr** [comment]
There is one additional such spelling in `.github/actions/configure-aws-credentials/dist/index.js`.

**Comment by hugo-syn** [comment]
Hi, I don't see this file in the main branch are you talking of the `main` branch ?

**Review by hussein-awala — APPROVED** [review]

**Comment by uranusjr** [comment]
Oh that’s from a submodule and needs to be fixed in https://github.com/aws-actions/configure-aws-credentials instead. Turns out we are not the only ones bad at spelling 🙂

**Review by uranusjr — APPROVED** [review]

**Comment by potiuk** [comment]
> Oh that’s from a submodule and needs to be fixed in https://github.com/aws-actions/configure-aws-credentials instead. Turns out we are not the only ones bad at spelling 🙂

deslxeia among programmes is quite comon ( ;) )

**Pull request merged**
