### PR TITLE
Dockerfile centos

### PR DESCRIPTION
**Pull request by sfc-gh-mkmak**
Hello @mik-laj and @potiuk 
   I would like to contribute to airflow and I am sending preliminary changes for dockerfile for centos.

### CODE REVIEW

**Comment by mik-laj** [comment]
@potiuk As we discussed earlier, here's a CentOS-based Dockerfile image that Snowflake uses. Hopefully, this will allow us to prepare official support for CentOS in the community.

**Comment by mik-laj** [comment]
Honestly, it wasn't our intention to merge this change, and it certainly wasn't as it was. We created this PR because you were interested to see what our image looked like and we thought you would be interested to build official support based on it. I am currently too busy with other initiatives, so feel free to take this code and develop it yourself if you want.

As for the action plan, I agree with it, but I would probably start by building this image with a minimal set of dependencies and testing it on CI. And then, as further improvements, added support for other features, such as Kerberos. Testing all dependencies is possible, but I'm afraid it can be difficult for a non-full-time contributor.

**Comment by potiuk** [comment]
I converted it to Draft then. Maybe indeed there will be time to implement it at some poin in time.

**Comment by potiuk** [comment]
Hey @mik-laj @sfc-gh-mkmak  - I looked a bit closer to that one, and I have a concern. It looks like the base container image that you used for the image is reatehr old. In Airflow, we strive for releasing our images based on the latest and greatest (i.e. with all known fixed security issues) released by the Python Software Foundation: https://hub.docker.com/_/python?tab=tags

For example, the latest version of 3.7-3.10 debian images has been pushed 2 days ago (and our CI system will automatically refresh our base images we publish to use the latest version in ~ 1 day.

The centos base python image you used `centos/python-38-centos7:20210726-fad62e9` is ratehr old in comparision and unfortunately it looks like:

1) It's been updated  last time > 1 year ago; https://hub.docker.com/r/centos/python-38-centos7
2) There are no 3.9/3.10 Python images at all released by centos organisation 

I am a little concerned with using those (and I am a little concerned you are not concerned :) ). It does not only miss the latest security fixes, but also the Python 3.8 version there is rather old there were likely 6 or 8 patchlevel releases there bringin bugfixes to the 3.8 line

Do you have any thoughts/ideass/concerns about an up-to-date base for such a centos image? 

I even looked at the "official centos image" and even that seems to be very out-dated (6-12 months) - which in the world of Security/IT and especially Supply Chain attacks is an eternity.  

I am afraid we would not be able to put our "trust" in such rarely released images - especially that our users are deeply concerned about security and we had many requests and questions about up-todatednesss and handingl some known and published CVEs in the images.

Can you think about a good/reliable/updated source for an up-todated centOS based images we could use as a base? Aren't you concerned about it in Snowflake BTW?

**Comment by potiuk** [comment]
Just merged the change that allows to work on this one. I will take a closer look shortly. Never heard of eurolinux before and I was kinda surprised it was based in Poland :)

**Comment by potiuk** [comment]
sorry for not following up yet, live intervened a bit :) but I wil get to it, I promise :D

**Comment by sfc-gh-mkmak** [comment]
Hello @potiuk thank you!

**Comment by potiuk** [comment]
Reopening. I might have some time to look back at it.

**Pull request closed without merging**
