### PR TITLE
[AIRFLOW-416] Use ordinals in README's company list

### PR DESCRIPTION
**Pull request by r39132**
Dear Airflow Maintainers,

Please accept this PR that addresses the following issues:
- https://issues.apache.org/jira/browse/AIRFLOW-416

### CODE REVIEW

**Comment by aoen** [comment]
With the numbered list we will have to update the rest of the numbers whenever a company asks to be removed or we add a new company (since we keep the list alphabetized), how about putting "over X companies use airflow:" before the list, or something similar?

**Comment by jlowin** [comment]
I agree with @aoen, this will be very difficult to maintain. However, if you number everything as "1.", Markdown will automatically increment the numbers.

```

1. my 
1. auto
1. incremented
1. list
```

renders as:
1. my 
2. auto
3. incremented
4. list

**Comment by r39132** [comment]
@aoen @jlowin thx. Both good suggestions.. I'll go with making everything `1.`.. good solution.

**Comment by r39132** [comment]
@aoen @jlowin fixed.

**Comment by aoen** [comment]
LGTM

**Pull request closed without merging**
