### PR TITLE
Allow git-sync command override

### PR DESCRIPTION
**Pull request by iJanki-gr**
I have a use case where I need to be able to specify command for the git-sync image. I wonder if we could add this. I have put the current default value.

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
I wonder what's your use csae? as far as I know you can add extra env variables to control various git command - including the ability to add some extra hook commands.  What is you want to do that it is not possible with regular git-sync command?

See https://github.com/kubernetes/git-sync and see if you can map your use case to any of these env vars before answering.

**Comment by iJanki-gr** [comment]
I have a custom k8s mutating webhook that integrates with Hashicorp vault. It needs to read the command of a container to apply the mutation.

I think in a broader sense it's good to have this in any case people want to override the gitsync image.

**Comment by potiuk** [comment]
> I have a custom k8s mutating webhook that integrates with Hashicorp vault. It needs to read the command of a container to apply the mutation.

I am not sure if I follow what mutation and what command reading is needed? Could you please explain a bit more? I have a f
That sounds like a very specific use case that is probably better to handle by making your deployment adapt (not sure? Annotations assigned to the image for example seems like standard way to be able to distinguish between different containers/pods). Using "entrypoint" for that sounds very weird so I would like to know more. Can you please explai what is exactly you need it for?

Generally the more variables and configuiration in the options - the more complex things are - for example - if you look now at your PR for example - tests are failing after your change. In order to get it mergable, you would not not only need to fix them but add a new set of unit tests that should cover regressions and add test cases for different git-sync command. And likely we need a documentation update describing when and how you would llike to use it (likely ih production guide - explaining what is the use case and why you would like to use it - so basically my question above will help you understand what kind of documentation you willl need to write).

So I am not saying it's wrong, I am saying it's quite a lot of work (for you mainly) to make it mergable, and I wonder if your use case is strong enough so that you are willing to commit to completing it and whether it is important enough to justify the added complexity.

BTW. I am not sure if we want to add anything for more configurable image, if we allow that, this is even more complexity and tests needed, and we can easily have a requirement that any replacement for git-sync image must have "/git-sync" entrypoint, so that variablity is really unnecessary complication, if your case can be handled differently

**Comment by potiuk** [comment]
BTW. Generally speaking you do not have to fork chart. You can make Airflow chart a subchart of yours and modify the Resources  you need in your chart. This is the way how you'd normally add functionality to existing charts: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/

**Comment by iJanki-gr** [comment]
I already do that, but some things are not easy to customise

**Comment by potiuk** [comment]
Yeah. That one might be tough - you basically need to copy/override the whole resources. 

But good news if that's only for your case and not generic, you can run `helm install --dry-run` and copy the resources from there. That would be an easy win.

**Comment by potiuk** [comment]
Also `helm-diff` plugin is super useful for those kind of things. You can change one variable (git-sync), run helm-diff command and only see the resources git-sync adds.

**Pull request closed without merging**
