### PR TITLE
[AIRFLOW-2103] Fix flask_login dependencies on password_auth auth

### PR DESCRIPTION
**Pull request by berna-code**
### JIRA
- https://issues.apache.org/jira/browse/AIRFLOW-2103

### Description
The change https://github.com/apache/incubator-airflow/pull/2730 broke the `password_auth` login:
```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 6, in <module>
    exec(compile(open(_file).read(), __file_, 'exec'))
  File "/src/apache-airflow/airflow/bin/airflow", line 27, in <module>
    args.func(args)
  File "/src/apache-airflow/airflow/bin/cli.py", line 696, in webserver
    app = cached_app(conf)
  File "/src/apache-airflow/airflow/www/app.py", line 176, in cached_app
    app = create_app(config, testing)
  File "/src/apache-airflow/airflow/www/app.py", line 63, in create_app
    from airflow.www import views
  File "/src/apache-airflow/airflow/www/views.py", line 97, in <module>
    login_required = airflow.login.login_required
AttributeError: module 'airflow.contrib.auth.backends.password_auth' has no attribute 'login_required'
```

### Tests
Enabling the `authenticate` on `webserver` session, forces the dependencies of `login_required` and `logout_user` to be referenced on `password_auth.py`

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
Please rebase on master, the CI has been fixed.

@NielsZeilemaker could you check?

**Comment by berna-code** [comment]
@Fokko As I mentioned above, the `flake8` is breaking:

```
airflow/contrib/auth/backends/password_auth.py:21:1: F401 'flask_login.login_required' imported but unused
airflow/contrib/auth/backends/password_auth.py:21:1: F401 'flask_login.logout_user' imported but unused
```

Should I write a dummy code using those imposts, or it is possible to ignore unused imports on  `flake8` on this specific class?


### Dummy
```python
# Fix flake8 unused import, ref: https://issues.apache.org/jira/browse/AIRFLOW-2103
_login = login_required
_logout = logout_user
```

**Comment by berna-code** [comment]
Using `# noqa` to ignore unused imposts: http://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html

**Comment by berna-code** [comment]
@NielsZeilemaker could you check?

**Comment by berna-code** [comment]
Closing due to duplicated issue: https://github.com/apache/incubator-airflow/pull/3124
BTW, the merged code has no unit test :(

**Comment by Fokko** [comment]
@bern4rdelli Please open a PR to add the tests, thanks!

**Pull request closed without merging**
