### PR TITLE
AWS RDS integration fixes

### PR DESCRIPTION
**Pull request by kazanzhy**
AWS RDS integration fixes for:
https://github.com/apache/airflow/pull/20642
https://github.com/apache/airflow/pull/20907
https://github.com/apache/airflow/pull/21231

Screenshot 2022-03-09 at 18 25 12

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by eladkal** [comment]
rds tests are failing :(

**Comment by potiuk** [comment]
Yeah will need to wait for amazon release for that one.

**Comment by kazanzhy** [comment]
Yeap. That's my own bug that I put to `moto`. Fixing it

**Comment by kazanzhy** [comment]
A new `moto` version was released recently.
So I can say that operators work as expected with real AWS and  `moto` as well.

**Review by potiuk — APPROVED** [review]
Cool. Constraints failed but it basically means we have to refresh them manually in this case I will take care of it.

**Comment by potiuk** [comment]
Updated constraints manually. Merging.

**Pull request merged**
