### PR TITLE
Sync v2-6-stable with v2-6-test to release 2.6.0

### PR DESCRIPTION
**Pull request by ephraimbuddy**
Releasing `2.6.0rc5`

### CODE REVIEW

**Review by jedcunningham — APPROVED** [review]

**Comment by ephraimbuddy** [comment]
It will be difficult for users to hit this fix, we can ignore it and do 2.6.1 as a follow up. Let me know what you think cc: @potiuk @eladkal

**Comment by eladkal** [comment]
> It will be difficult for users to hit this fix, we can ignore it and do 2.6.1 as a follow up. Let me know what you think cc: @potiuk @eladkal

+1

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
I think, unfortunately, it is easy to hit. Basically anyone who has their custom plugin will have problem with their UI assets not rendering properly - similar to what you get when you have no assets compiling and the UI is broken.

**Comment by potiuk** [comment]
I think this is small-enough change to just keep the time as is, until we get 3 +1 votes.

**Comment by potiuk** [comment]
I wil also add a unit test for that one. It's rather unexpected implicit behaviour of Flask object :( . Thanks @jedcunningham for finding and fixing it.

**Comment by ephraimbuddy** [comment]
> I think this is small-enough change to just keep the voting time as is, until we get 3 +1 votes.

It's just 2hrs to the release time. Maybe we should extend another 6hrs but I think less than 24hrs is too short?

**Comment by eladkal** [comment]
> > I think this is small-enough change to just keep the voting time as is, until we get 3 +1 votes.
> 
> It's just 2hrs to the release time. Maybe we should extend another 6hrs but I think less than 24hrs is too short?

24 hours voting is the minimum as our policy states.

**Comment by potiuk** [comment]
> It's just 2hrs to the release time. Maybe we should extend another 6hrs but I think less than 24hrs is too short?

Right .

**Pull request merged**
