### PR TITLE
make resources for KubernetesPodTemplate templated

### LINKED ISSUE #23529: Provide resources attribute in KubernetesPodOperator to be templated
### Description

Make resources in KubernetesPodOperator as templated. We need to modify this during several runs and it needs code change for each run.

### Use case/motivation

For running CPU and memory intensive workloads, we want to continuously optimise the "limt_cpu" and "limit_memory" parameters. Hence, we want to provide these parameters as a part of the pipeline definition.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by nitinmuteja**
closes: #23529

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragement file, named `{pr_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by nitinmuteja** [comment]
Added test for the change.

**Comment by potiuk** [comment]
Cool. Running tests and hopefully will include it in the next provider's release.

**Comment by eladkal** [comment]
How can we template resources? Its not a string. Its a list object of V1ResourceRequirements.

Maybe im missing something here but I would love to see an actual test that template this field.

**Comment by eladkal** [comment]
Do we mean to something like?

```
V1ResourceRequirements(
            requests={"cpu": "{{ dag_run.conf[\'request_cpu\'] }}", "memory": "8G"},
            limits={"cpu": "16000m", "memory": "128G"},
        )
```

**Comment by nitinmuteja** [comment]
@eladkal yes. This is the expected behaviour.

**Comment by talnagar** [comment]
I tried locally with kind-cluster and the templating didn't take. @nitinmuteja can you supply a usage example for it?
this is what I tried using the example_kubernetes_executor.py from the example_dags in the repo:
```
....
  with DAG(
        dag_id='example_kubernetes_executor',
        schedule_interval=None,
        start_date=pendulum.datetime(2021, 1, 1, tz="UTC"),
        catchup=False,
        tags=['example3'],
        params={
            'mem': Param(default='512Mi',type='string', description="memory"),
        }
....
 # Use k8s_client.V1ResourceRequirements to define resource limits
        k8s_resource_requirements = k8s.V1ResourceRequirements(
            requests={'memory': "{{ params['mem'] }}"}, limits={'memory': '512Mi'}
        )
```

**Comment by eladkal** [comment]
@nitinmuteja It would be great if you can add a test that verify the templating similar to:
https://github.com/apache/airflow/blob/a3c9956f79310b529a79c1e43fb881c5e173d321/tests/providers/google/cloud/operators/test_cloud_storage_transfer_service.py#L870-L887

**Comment by potiuk** [comment]
@nitinmuteja -> last call before preparing newr round of providers - do you have time/capability to add the test as @eladkal asked?

**Comment by nitinmuteja** [comment]
I can add today.

**Comment by potiuk** [comment]
Cool. I can hold on then :)

**Comment by nitinmuteja** [comment]
@talnagar I have added test cases for the requirements.

**Comment by nitinmuteja** [comment]
@potiuk please check the changes. Created a subclass from the k8s class and added class attributes to make limits and requests as template attributes.

**Review by jedcunningham — CHANGES_REQUESTED** [review]
I'm not really on board with having our own `V1ResourceRequirements` - we intentionally moved away from this pattern for a reason.

I haven't tried it, but would this pattern work instead (making this a documentation issue)?

```
resources = k8s.V1ResourceRequirements(requests={'memory': '100Mi'})
resources.template_fields = ('requests')

KPO(
...,
resources=resources
)
```

**Comment by eladkal** [comment]
> I'm not really on board with having our own `V1ResourceRequirements` - we intentionally moved away from this pattern for a reason.

I agree

**Comment by potiuk** [comment]
Agree - this one will wait move to next round of providers.

**Comment by nitinmuteja** [comment]
> > I'm not really on board with having our own `V1ResourceRequirements` - we intentionally moved away from this pattern for a reason.

@jedcunningham we are just inheriting the object and will continue using the object. The only advantage it provides us with is that the props can be templated.

**Comment by nitinmuteja** [comment]
> I'm not really on board with having our own `V1ResourceRequirements` - we intentionally moved away from this pattern for a reason.
> 
> I haven't tried it, but would this pattern work instead (making this a documentation issue)?
> 
> ```
> resources = k8s.V1ResourceRequirements(requests={'memory': '100Mi'})
> resources.template_fields = ('requests')
> 
> KPO(
> ...,
> resources=resources
> )
> ```

This one does not work as the external V1ResourceRequirements does not have template_fields class attribute.

**Comment by lior1990** [comment]
Suggestion: you can modify `_render_nested_template_fields` in `KubernetesPodOperator` and add the following code, right after the custom code that is handling `k8s.V1EnvVar`:
```
if id(content) not in seen_oids and isinstance(content, k8s.V1ResourceRequirements):
    seen_oids.add(id(content))
    self._do_render_template_fields(content, ("limits", "requests"), context, jinja_env, seen_oids)
    return
````

**Comment by akakakakakaa** [comment]
```

**Comment by akakakakakaa** [comment]
In addition to previously mentioned by @lior1990,

```
class CustomKubernetesPodOperator(KubernetesPodOperator):
    template_fields: Sequence[str] = KubernetesPodOperator.template_fields + ('k8s_resources', )

    def _render_nested_template_fields(
        self,
        content: Any,
        context: 'Context',
        jinja_env: "jinja2.Environment",
        seen_oids: set,
    ) -> None:
        if id(content) not in seen_oids and isinstance(content, k8s.V1ResourceRequirements):
            seen_oids.add(id(content))
            self._do_render_template_fields(content, ("limits", "requests"), context, jinja_env, seen_oids)
            return

        super()._render_nested_template_fields(content, context, jinja_env, seen_oids)
```

In KubernetesPodOperator, resources allocated to k8s_resources
```
self.k8s_resources = convert_resources(resources) if resources else {}
````
Instead of resource, k8s_resource should be added to template_fields.

**Pull request closed without merging**
