### PR TITLE
refactor: Make sure xcoms work correctly in MSGraphAsyncOperator with concurrent workers

### PR DESCRIPTION
**Pull request by dabla**
This pull request makes sure xcoms work correctly in a multi-threaded environment (e.g. when applying dynamic task mapping with concurrent workers) by taking the map_index into account when pushing and pulling xcoms.

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by potiuk** [comment]
Is it possible to add unit test for that to avoid  regressions ?

**Comment by dabla** [comment]
> Is it possible to add unit test for that to avoid regressions ?

That would mean a unit test using multiple threads as I need concurrency to reproduce it.  Are there any examples of unit tests using multiple threads?

**Comment by potiuk** [comment]
> That would mean a unit test using multiple threads as I need concurrency to reproduce it. Are there any examples of unit tests using multiple threads?

When I search in `tests` there are at least few `Thread(` usages.

**Comment by dabla** [comment]
> > That would mean a unit test using multiple threads as I need concurrency to reproduce it. Are there any examples of unit tests using multiple threads?
> 
> When I search in `tests` there are at least few `Thread(` usages 😄

Ok will also search then, I just asked because I know from experience that test with threads can something mess up the whole test pipeline

**Comment by dabla** [comment]
The problem with Python is that the basic threading doesn't do real multithreading, so I don't know if I will be able to reproduce it as we did encounter the issues with multiple workers being deployed across multiple pods.  So in order to test this correctly, I would be force to use the multiprocessing pyhton module.

**Comment by potiuk** [comment]
> The problem with Python is that the basic threading doesn't do real multithreading, so I don't know if I will be able to reproduce it as we did encounter the issues with multiple workers being deployed across multiple pods. So in order to test this correctly, I would be force to use the multiprocessing pyhton module.

Yeah. If it's too much of a hassle and reproducibility is difficult, then yeah we can definitely skip tests

**Review by potiuk — APPROVED** [review]

**Pull request merged**
