### PR TITLE
[AIRFLOW-2018] Make Sensors backward compatible

### PR DESCRIPTION
**Pull request by Fokko**
To keep compatibility until Airflow 2.0, we want to keep the sensors api compatible.

Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "[AIRFLOW-XXX] My Airflow PR"
    - https://issues.apache.org/jira/browse/AIRFLOW-XXX

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [ ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by Fokko** [comment]
PTAL @bolkedebruin @ashb @Acehaidrey

**Comment by ashb** [comment]
I'm not sure this works as intended:

```
In [5]: import airflow.operators

In [7]: airflow.operators.BashOperator
/Users/ash/code/python/incubator-airflow/airflow/utils/helpers.py:351: DeprecationWarning: Importing BashOperator directly from <module 'airflow.operators' from '/Users/ash/code/python/incubator-airflow/airflow/operators/__init__.py'> has been deprecated. Please import from '<module 'airflow.operators' from '/Users/ash/code/python/incubator-airflow/airflow/operators/__init__.py'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  DeprecationWarning)
Out[7]: bash_operator.BashOperator

In [8]: airflow.operators.sensors
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-3cadeea94026> in <module>()
----> 1 airflow.operators.sensors

~/code/python/incubator-airflow/airflow/utils/helpers.py in __getattr__(self, attribute)
    379             return loaded_attribute
    380
--> 381         raise AttributeError
```

**Comment by ashb** [comment]
~Wait am I testing the wrong thing -- and `airflow.operators.sensors.S3KeySensor` is the new name or the old one?~ Yes, this is the new name.

Testing with `from airflow.operators.sensors import S3KeySensor` which we use in a current DAG I don't get any import warning as I would have expected. It does continue to work though which is a plus.

**Comment by bolkedebruin** [comment]
@Fokko ? I think the deprecation warning is important, can you make sure that it works?

**Comment by Fokko** [comment]
@bolkedebruin I agree, I'll fix this today

**Comment by Fokko** [comment]
I don't get a deprecation warning on master:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ git branch -v
* master                                                 f9ddb36d [AIRFLOW-2033] Add Google Cloud Storage List 
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import airflow.operators.bash_operator
>>> 

```

**Comment by Fokko** [comment]
After looking into the code, it should trigger the deprecation warning, but I guess it is being suppressed for some reason.

**Comment by ashb** [comment]
The warning is triggered on accessing BashOperator on airflow.operator:

```
python -c 'import airflow.operators; airflow.operators.BashOperator'
```

gives a warning (on 1.9.0). I know at some point Python (I think 3.3?) changed DeprecationWarnings to be silenced by default :( But the code in `airflow.configuration` should make them noisy again.

**Comment by Fokko** [comment]
Ok, few things. This should not work, right? Why would you import this module.
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import airflow.operators
>>> airflow.operators.sensor
<module 'airflow.operators' from 'airflow/operators/__init__.pyc'>
sensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "airflow/utils/helpers.py", line 385, in __getattr__
    raise AttributeError
AttributeError
>>> 
```
When I try to import a sensor, I do get the warning:
```
Fokkos-MacBook-Pro:incubator-airflow fokkodriesprong$ python -c 'import airflow.operators; airflow.operators.TimeSensor'
airflow/utils/helpers.py:351: DeprecationWarning: Importing TimeSensor directly from <module 'airflow.operators' from 'airflow/operators/__init__.pyc'> has been deprecated. Please import from '<module 'airflow.operators' from 'airflow/operators/__init__.pyc'>.[operator_module]' instead. Support for direct imports will be dropped entirely in Airflow 2.0.
  DeprecationWarning)
```

**Comment by Fokko** [comment]
And you're right: https://github.com/apache/incubator-airflow/blob/master/airflow/configuration.py#L45-L49

**Comment by Fokko** [comment]
@ashb @bolkedebruin any further comments? Otherwise we might want to merge this to master for Airflow 1.10

**Comment by bolkedebruin** [comment]
Go. LGTM

**Pull request closed without merging**
