### PR TITLE
Add correct signatures for operators in google provider package

### PR DESCRIPTION
**Pull request by ephraimbuddy**
This PR closes part of #9942, It enforces keyword-only arguments for google provider operators

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by ephraimbuddy** [comment]
Hi, @mik-laj, I noticed that operators in natural_language module and a few others didn't use apply_default decorator. I added it but I'm wondering if there's a reason why it was not used

**Review by potiuk — APPROVED** [review]
Love it!

**Comment by potiuk** [comment]
> Hi, @mik-laj, I noticed that operators in natural_language module and a few others didn't use apply_default decorator. I added it but I'm wondering if there's a reason why it was not used

There is no reason it was missing - most likely a mistake

**Comment by ephraimbuddy** [comment]
> > Hi, @mik-laj, I noticed that operators in natural_language module and a few others didn't use apply_default decorator. I added it but I'm wondering if there's a reason why it was not used
> 
> There is no reason it was missing - most likely a mistake

Ok. Thanks!

**Pull request merged**
