### PR TITLE
 FIX: Don't raise a warning in ExecutorSafeguard when execute is called from an extended operator (#42849) Backport

### PR DESCRIPTION
**Pull request by jscheffl**
Backport of #42849 to v2-10-test branch for the next release

Relates to #41470

### CODE REVIEW

**Comment by jscheffl** [comment]
FYI @dabla

**Review by hussein-awala — APPROVED** [review]

**Comment by jscheffl** [comment]
@utkarsharma2 if 2.10.3rc2 is not (yet) cut... this would be a late arrival candidante...

**Comment by utkarsharma2** [comment]
> @utkarsharma2 if 2.10.3rc2 is not (yet) cut... this would be a late arrival candidante...

Sure I'll include it.

**Comment by dabla** [comment]
Thanks guys for backporting this fix!

**Pull request merged**
