### PR TITLE
[AIRFLOW-3012] Fix Bug when passing emails for SLA

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. 
  - https://issues.apache.org/jira/browse/AIRFLOW-3012

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

I store email recipients as a variable, test_recipient: `test1@test.com, test2@test.com`

With such dag definition:

```
email = Variable.get("test_recipients")
args = {
    'owner': 'airflow'
    , 'depends_on_past': False
    , 'start_date': datetime(2018, 8, 20, 0, 0)
    , 'retries': 0
    , 'email': email
    , 'email_on_failure': True
    , 'email_on_retry': True
    , 'sla': timedelta(seconds=10)
}
```

On sla miss, email is sent only to the first person on the list, in my example `test1@test.com`
to reproduce:

create email list variable as string and wait for sla miss

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
- `EmailTest.test_get_email_address_comma_sep_string`
- `EmailTest.test_get_email_address_colon_sep_string`
- `EmailTest.test_get_email_address_list`

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kaxil** [comment]
cc @fokko @ashb

**Comment by kaxil** [comment]
Gentle ping :) @feng-tao  @ashb @r39132

**Review by ashb — APPROVED** [review]

**Comment by feng-tao** [comment]
LGTM. Thanks.

**Review by r39132 — COMMENTED** [review]
LGTM

**Comment by Fokko** [comment]
I've closed the issue! 👍

**Pull request merged**
