### PR TITLE
[AIRFLOW-4939] Simplify Code for Default Task Retries

### PR DESCRIPTION
**Pull request by kaxil**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4939

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Review by XD-DENG — DISMISSED** [review]
LGTM
EDIT: I'll have a look at the test failure. **Revoking my approval first**.

**Comment by msumit** [comment]
I wrote the exact piece of code earlier, but 1 test won't pass due to python's nature of not re-calculating function defaults again. https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

**Comment by kaxil** [comment]
huh, you are right, @msumit - Thanks, will close this PR. We are using this type of code in many places AFAIK, we should change that too.

**Comment by ashb** [comment]
Except an integer isn't mutable -- that caveat only applies to dicts and lists I thought?

**Comment by kaxil** [comment]
😬 Yeah (not sure what I was thinking) - Fixed the test.

**Comment by msumit** [comment]
@ashb if that law doesn't apply on Integers, then the tests would pass, so IMO it does applies. @kaxil I don't think there is any value addition by changing the current code, in fact one would need to restart the scheduler after changing conf.

**Comment by ashb** [comment]
The reason the tests didn't pass was because:

- At parse time the value in the config was 0
- We then run the decorator to change the config, but this doesn't affect the default
- We then called the function, having the old default.

The warnings applies to a case like this:

```python
def append_to(element, to=[]):
    to.append(element)
    return to
```

When calling `a =append_to(1); b=append_to(2)` in which case `a is b` -- the same default object is done. But an integer can't be mutated, it's just that our attempt to change the default value at run time in the tests doesn't work.

**Comment by ashb** [comment]
> in fact one would need to restart the scheduler after changing conf

This is true with both code paths -- the airflow config file is only loaded once at process start up, so changing the config file on disk will not affect a running airflow process.

**Review by msumit — APPROVED** [review]
lgtm

**Pull request merged**
