### PR TITLE
Add Snowflake provider to boring cyborg automation

### PR DESCRIPTION
**Pull request by turbaszek**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by turbaszek** [comment]
> line 42: pre-commit: command not found
 👀

**Comment by potiuk** [comment]
Rebase. I merged a fix already.

**Review by kaxil — APPROVED** [review]

**Comment by turbaszek** [comment]
I rebased 3 times and the problem still occurs. We can probably merge this change but it would be good to know why there's an issue

**Comment by potiuk** [comment]
This is the reason: https://github.com/apache/airflow/pull/14451 -> I forgot to update PATH in basic_static_checks.sh and it is executed only sometimes, so I have not caught it before.

**Comment by potiuk** [comment]
Now rebase should help :).

**Pull request merged**
