### PR TITLE
Convert all other providers and their tests to __future__.annotations

### PR DESCRIPTION
**Pull request by potiuk**
---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Review by ashb — APPROVED** [review]
TIL that as well as large file diffs, that if you have too many diffs in a PR that GH hides many of the changes too :grin:

Also hooo boy! TP was right. If all the PRs were like this then they would be almost impossible to actually review, where as I have been able to review everything so far.

**Comment by potiuk** [comment]
> TIL that as well as large file diffs, that if you have too many diffs in a PR that GH hides many of the changes too 😁
> 
> Also hooo boy! TP was right. If all the PRs were like this then they would be almost impossible to actually review, where as I have been able to review everything so far.

Absolutely :)

**Comment by potiuk** [comment]
That's why I also had this "tests" as one big - to compress number of PRs a bit - the "test" changes are quite a bit safer than the "code" changes - basically - if the tests run and are green the tests change is "GOOD".

**Comment by potiuk** [comment]
Closing as this one will be merged as part of #26289 #26290. See https://lists.apache.org/thread/81fr042s5d3v17v83bpo24tnrr2pp0fp for details

**Pull request closed without merging**
