### PR TITLE
Housekeeping of auth backend & Update Security doc

### PR DESCRIPTION
**Pull request by XD-DENG**
- All authentication backends in `airflow/contrib/auth` are base on the `user` model which has already been removed earlier (https://github.com/apache/airflow/pull/4577)
- Security related documentation is out-dated, especially the LDAP and OAuth integration sections. It still directs user to the configuration of "old" web UI which has already been removed in master branch, while we should refer to the FAB doc instead.

---
Issue link: WILL BE INSERTED BY [boring-cyborg](https://github.com/kaxil/boring-cyborg)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by XD-DENG** [comment]
Hi @kaxil @potiuk @zhongjiajie , this is the change I mentioned in our earlier discussion https://github.com/apache/airflow/pull/4577#issuecomment-607066594 . 

I will raise another PR to address similar issue (out-dated documentation) for 1-10-x branch.

**Comment by potiuk** [comment]
Is the code really out-dated :)? I did not realise that :)

**Comment by XD-DENG** [comment]
@potiuk  It will be great if you can help take another further look and confirm.

The main reasoning is all of the `contrib/auth` backends are based on `models.User`, while `models.User` is already removed. But yes let's be careful about this.

**Review by potiuk — APPROVED** [review]
Makes sense. Looks good.

**Pull request merged**
