### PR TITLE
[AIRFLOW-4416] Revert "Reliable SynchronizedQueue used"

### PR DESCRIPTION
**Pull request by potiuk**
This reverts commit 5bf9704cc0c4f87a919193de3ed708e198a95f63.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4416
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The fix implemented as part of AIRFLOW-4401 might have some adverse side effects.

For example it very likely caused the build to stall: https://api.travis-ci.org/v3/job/524771374/log.txt
The root cause is know, but the fix need to be tested more thoroughly.

I think it's safer to revert the fix for now and invest more time in finding more robust fix.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
No need.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Review by BasPH — APPROVED** [review]
Bummer :( I have some time this weekend to dive into it, let's revert for now...

**Comment by potiuk** [comment]
@ashb let me know what you think as well and I can revert it in the v1-10 branches as well. In those branches rather than reverting commits (maybe we can simply force-push the branches as the two commits for it are the last ones)

**Comment by potiuk** [comment]
@BasPH - I also should have some time this weekend to take a look. This one is really annoying :).

**Comment by ashb** [comment]
@potiuk I have force pushed v1-10-* to remove the commits from there.

**Pull request merged**
