### PR TITLE
[AIRFLOW-2846] Add missing python test dependency to setup.py

### PR DESCRIPTION
**Pull request by holdenk**
Add missing python test dependency (tox) to setup.py dev requirement.

Make sure you have checked _all_ steps below.

### Jira

- [ X ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-2846\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2846

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ X ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Adds test dependency.

### Commits

- [ X ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [ X ] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by ashb** [comment]
Could you rebase please?

**Comment by tedmiston** [comment]
Good catch.  I'm not sure how we made it this long without `tox` in there.

I happen to install it system-wide with pipsi... I wonder if everyone else just happens to do something similar, or maybe they're running the dockerized tests setup, or maybe they're just not running against tox locally?  I wonder if there's room for us to make that clearer in the docs?  I'm not sure if we consider one of these a best practice more than the others.

**Comment by ashb** [comment]
I both have it installed globally, and don’t run with tox locally because the full test suite non-parallel takes a looong time, so I run individual test suites usually.

**Comment by feng-tao** [comment]
need to rebase.

**Comment by Fokko** [comment]
In case who missed it: https://www.youtube.com/watch?v=5Il3w2P7IcM Awesome work @holdenk for getting people inspired to contribute to open source software!

I've checked. The tox version being installed with `apt-get` by Travis is also 3.1.3. Not completely sure why this failed :-)
In the end we should rely less on Travis and move to a Dockerized setup to make testing easier. There is a great effort going on in https://github.com/apache/incubator-airflow/pull/3393/ but there are still some lose ends that need to be fixed before we can merge it.

**Comment by holdenk** [comment]
Thank y'all for the review and kind words, I've rebased on master.

**Comment by r39132** [comment]
Build failures look unrelated! Retriggering build.. let's see.

**Comment by r39132** [comment]
This is bizarre, retriggering the build/test caused it to fail the same files. @holdenk TravisCI pass on your fork? If so, let me know.

**Comment by Fokko** [comment]
I'd say that we would need to remove this tox install as well: https://github.com/apache/incubator-airflow/blob/master/.travis.yml#L98

**Comment by r39132** [comment]
@holdenk can you look at @Fokko suggestion, which I interpret as removing the tox from travis.yml but leaving it in setup.py in order to let the tests pass.

**Comment by r39132** [comment]
@holdenk friendly ping.. if this is not needed anymore, we can consider closing it.

**Comment by holdenk** [comment]
Sorry about this, had some work stuff happen but got more cycles for airlfow again, I'll update this now.

**Comment by holdenk** [comment]
The more I look at this the less sense it makes, requiring tox shouldn't cause these sorts of failures.

**Comment by ashb** [comment]
The failures do look totally unrelated to Tox or not. Given we have dockeriszed the CI and test pipelines do we need even tox anymore?

**Comment by Fokko** [comment]
@ashb I'm working on removing tox, but removing tox this isn't trivial. Since we already encapsulate the tests in Docker, tox adds another layer of abstraction, which is not required in my opinion.

**Comment by holdenk** [comment]
With the new dockerized test enviroment I don't think we need this PR anymore. I'll close it for now and switch the JIRA to Won't Fix. If folks disagree feel free to re-open it :)

**Pull request closed without merging**
