### PR TITLE
[AIRFLOW-1441] Fix inconsistent tutorial code

### PR DESCRIPTION
**Pull request by TrevorEdwards**
Dear Airflow maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW-1441) issues and references them in the PR title. 

- https://issues.apache.org/jira/browse/AIRFLOW-1441

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

The recap code is updated to say:
```
Code that goes along with the Airflow tutorial located at:
https://github.com/airbnb/airflow/blob/master/airflow/example_dags/tutorial.py
```
to match the initial code.

The initial code's DAG definition is updated to say:

```
dag = DAG(
    'tutorial', default_args=default_args, schedule_interval=timedelta(1))
```

This makes the two sections consistent.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Since this is only a small documentation consistency update, I have not added any unit tests.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by ron819** [comment]
@Fokko  is this still relevant?

**Comment by Fokko** [comment]
@ron819 I think it is a good idea to set the `schedule_interval`, but the link to the docs is old (refers to Airbnb).

**Comment by TrevorEdwards** [comment]
Updated to set the right link. Also added days=1 based on

https://github.com/apache/incubator-airflow/blob/master/airflow/example_dags/tutorial.py#L61

**Comment by Fokko** [comment]
Thanks @TrevorEdwards Looks good! 👍

**Pull request merged**
