### PR TITLE
Add upperbound to microsoft-kiota-abstractions

### PR DESCRIPTION
**Pull request by rawwar**
Currently, [MyPy check is failing](https://github.com/apache/airflow/actions/runs/11338780479/job/31532784299?pr=43020#step:6:122) as we don't have a pin on `microsoft-kiota-abstractions`.

```
roviders/src/airflow/providers/microsoft/azure/hooks/msgraph.py:51: error:
Module "kiota_abstractions.request_information" has no attribute "QueryParams";
maybe "QueryParameters"?  [attr-defined]
        from kiota_abstractions.request_information import QueryParams
        ^
providers/src/airflow/providers/microsoft/azure/hooks/msgraph.py:65: error:
"NativeResponseType" has no attribute "json"  [attr-defined]
                return response.json()
                       ^~~~~~~~~~~~~
providers/src/airflow/providers/microsoft/azure/hooks/msgraph.py:66: error:
"NativeResponseType" has no attribute "content"  [attr-defined]
            content = response.content
                      ^~~~~~~~~~~~~~~~
providers/src/airflow/providers/microsoft/azure/hooks/msgraph.py:68: error:
"NativeResponseType" has no attribute "headers"  [attr-defined]
                return {key: value for key, value in response.headers.item...
                                                     ^~~~~~~~~~~~~~~~
providers/src/airflow/providers/microsoft/azure/hooks/msgraph.py:71: error:
Signature of "handle_response_async" incompatible with supertype
"ResponseHandler"  [override]
        async def handle_response_async(
        ^
```

They recently released newer minor version which has a breaking change. 

Breaking change.
following module missing: [1.4.0](https://github.com/microsoft/kiota-python/blob/v1.4.0/kiota_abstractions/default_query_parameters.py) . vs [1.3.3](https://github.com/microsoft/kiota-python/blob/v1.3.3/kiota_abstractions/default_query_parameters.py)

They released newer version at Mon, 14 Oct 2024 17:09:01 GMT . Source: https://pypi.org/rss/project/microsoft-kiota-abstractions/releases.xml

### CODE REVIEW

**Comment by eladkal** [comment]
> They recently released newer version which has a breaking change

Is there a reason we can't just fix the problem and exclude the problematic release? We limit version only if the fix isn't easy and requires some effort

**Comment by rawwar** [comment]
> > They recently released newer version which has a breaking change
> 
> Is there a reason we can't just fix the problem and exclude the problematic release? We limit version only if the fix isn't easy and requires some effort


They have entirely removed the module. So, unless we update the provider code, just excluding the specific version won't help. I guess, we can remove the constraint once we fix the provider by removing references to the removed classes/methods

**Comment by eladkal** [comment]
> They have entirely removed the module. So, unless we update the provider code, just excluding the specific version won't help. I guess, we can remove the constraint once we fix the provider by removing references to the removed classes/methods

If the fix is easy then lets fix :)

**Comment by rawwar** [comment]
> If the fix is easy then lets fix :)

I can definitely take this work, but I don't think it's straightforward. At least not to me, as it's the first time I've worked with this provider. It failed the MyPy checks on the other [PR](https://github.com/apache/airflow/pull/43020) I'm working on. Would it be fine if I created an issue and assigned myself?

**Comment by eladkal** [comment]
> I can definitely take this work, but I don't think it's straightforward. At least not to me, as it's the first time I will be working with this provider. It failed the MyPy checks on the other [PR](https://github.com/apache/airflow/pull/43020) I'm working on. Would it be fine if I created an issue and assigned myself?

yes but please also add comment to the provider yaml and add the link to the issue so we have better tracking of it

**Review by eladkal — APPROVED** [review]

**Comment by potiuk** [comment]
Yes. Crating an issue and referring to it in the comment just above the dependency (as we do for other cases like that) is the way we do it. This makes it later very easy to check "has this issue been followed? What is the status? Should we do something with it"? This is all very difficult if we do not know what's the reason of upper-binding a dependency, so our rule-of-thumb is that we never upper-bind any dependency without a comment explaining why, what is the condition of removing the binding and linking to appropriate issue.

**Comment by potiuk** [comment]
Also once you create the issue - we could ask other people who are involved in microsoft provider -  maybe  @ambika-garg  could help with it for example ?

**Comment by ambika-garg** [comment]
Hey @potiuk ,I'd be happy to assist with this issue.

**Comment by rawwar** [comment]
> Yes. Crating an issue and referring to it in the comment just above the dependency (as we do for other cases like that) is the way we do it. 

Thanks. I've updated the PR.

@ambika-garg, I just created https://github.com/apache/airflow/issues/43036

**Pull request merged**
