### PR TITLE
Add configurable scheme for webserver probes

### PR DESCRIPTION
**Pull request by dan-vaughan**
We want to be able to terminate TLS at the webserver pod, which requires configuring the liveness and readiness probes to use https.

- Add configurable scheme to webserver probes
- Update values schema
- Add unittest

### CODE REVIEW

**Comment by potiuk** [comment]
It's not the best idea to use TLS termination in the webserver. Usually in K8S this should happen in the ingress and very rarely (if at all) you use TLS termination in application.

Why would you want to do this?

**Comment by dan-vaughan** [comment]
The k8s security standards for the company I work for require us to terminate TLS at the pod to prevent unencrypted ingress -> pod communication

**Comment by potiuk** [comment]
Interesting. I guess I will leave it to @jedcunningham and @ephraimbuddy to decide if they want to merge it, I see that might be useful for such level of a bit "paranoid" security. 

Can you please fix the static checks and tests however @dan-vaughan

**Comment by potiuk** [comment]
Static checks are still failing. I suggest to rebase and install/run pre-commit before that.

**Comment by dan-vaughan** [comment]
Hey @potiuk, I've fixed the failing static checks, please let me know if there's anything else you need from me

**Review by potiuk — APPROVED** [review]

**Pull request merged**
