### PR TITLE
Switches to ghcr.io container registry

### PR DESCRIPTION
**Pull request by potiuk**
After fixing permission problems, we can now switch to ghcr.io

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/main/UPDATING.md).

### CODE REVIEW

**Comment by uranusjr** [comment]
Hmm CI doesn’t seem to work

**Comment by kaxil** [comment]
Error response from daemon: Get https://docker.pkg.github.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)


Yeah weird

**Comment by potiuk** [comment]
> Hmm CI doesn’t seem to work
> Error response from daemon: Get https://docker.pkg.github.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Yeah. That's why I pushed it. Seems that the legacy GitHub Packages again having problems and I just fixed permission problem with `ghcr.io` so we should merge that one (note - we have to merge it "believing" that it will work).

I run two builds to test it in my fork:

* Main build: https://github.com/potiuk/airflow/actions/runs/993622080
* PR build from another account (waiting to see it works): https://github.com/potiuk/airflow/pull/157/checks?check_run_id=2972490378

**Comment by potiuk** [comment]
> Although why is it using docker.pkg in CI currently, shouldn't it be using ghcr.io?

Because it will only work after merge to main :)

**Comment by kaxil** [comment]
> > Although why is it using docker.pkg in CI currently, shouldn't it be using ghcr.io?
> 
> Because it will only work after merge to main :) (pull_request_target workflow uses main version of the workflow)

Static check job does not use `pull_request_target` workflow though I thought: https://github.com/apache/airflow/pull/16775/checks?check_run_id=2972416770#step:10:28

**Comment by potiuk** [comment]
> Static check job does not use `pull_request_target` workflow though I thought: https://github.com/apache/airflow/pull/16775/checks?check_run_id=2972416770#step:10:28

It can use both. It is (for transition period) implemented in the way that it will use either of the two - it tries to see which one is pushed and uses this one once we merge and prove that it works there is a follow up PR to remove whole lot of complexity of this "dual registry" support.

**Comment by potiuk** [comment]
So this build had a chance of succeding (but the legacy package registry fails currently)

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
I got My PR working in my fork so merging this one https://github.com/potiuk/airflow/pull/157/checks?check_run_id=2972629813 (and proceed with permanent removal of package registry once we see ghcr.io  succeeding for PRs).

**Pull request merged**
