### PR TITLE
[AIRFLOW-7113] fix gantt render error

### PR DESCRIPTION
**Pull request by cong-zhu**
---
Issue link: [AIRFLOW-7113](https://issues.apache.org/jira/browse/AIRFLOW-7113)

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Comment by kaxil** [comment]
@cong-zhu Thanks for raising this PR. I know someone reported this error too. However, I couldn't reproduce the error. Do you have an example DAG or steps I can do to reproduce this error?

**Comment by KevinYang21** [comment]
@kaxil I think if we have tasks marked as failed by the scheduler upon receiving executor event then we'll end up  having such failing tasks w/o a start date and crash the gantt chart.

@cong-zhu correct me if I'm wrong.

**Comment by KevinYang21** [comment]
The CI error looks irrelevant tho, maybe try rebase and rerun?

**Comment by cong-zhu** [comment]
@KevinYang21, yes it's correct. 

@kaxil. Tasks fail at early stage, e.g. during parsing, won't contain the start date. When handling failures, scheduler will store those failed tasks in task_fail table. Which crashes the gantt chart. To reproduce the error, you need to have a row w/o start_date in task_fail table. Entries w/o start_date in task_instance table will be fine as the query filters them out. I reverted the change on it.

**Comment by kaxil** [comment]
> @KevinYang21, yes it's correct.
> 
> @kaxil. Tasks fail at early stage, e.g. during parsing, won't contain the start date. When handling failures, scheduler will store those failed tasks in task_fail table. Which crashes the gantt chart. To reproduce the error, you need to have a row w/o start_date in task_fail table. Entries w/o start_date in task_instance table will be fine as the query filters them out. I reverted the change on it.

Shouldn't we change the Scheduler code to store the start_date and if there is any error store start_date = end_date during that time before we store in task_fail table?

**Comment by cong-zhu** [comment]
> Shouldn't we change the Scheduler code to store the start_date and if there is any error store start_date = end_date during that time before we store in task_fail table?

I think it still makes sense to store the empty start_date as it indicates the task failed before running. We just need to appropriately represent this from the UI.

**Pull request merged**
