### PR TITLE
Adding fernet key to use it as part of stdout commands

### PR DESCRIPTION
**Pull request by himank**

### CODE REVIEW

**Comment by himank** [comment]
@mistercrunch Need fernet key as well as part of stdout commands as we don't want to store it hardcoded in the template. Please review.

**Comment by patrickleotardif** [comment]
LGTM!

**Comment by himank** [comment]
@patrickleotardif Thanks!

**Comment by r39132** [comment]
@patrickleotardif @himank 

Can I ask someone to take on a card to document configuration.py? There are many ways to handle configurations for variables, connections, etc.. There is no configuration documentation, and we oft get those questions asked.

**Pull request merged**
