### PR TITLE
Fix KEDA Autoscaler connectionFromEnv

### PR DESCRIPTION
**Pull request by YuDorogov**
Set worker container first in containers, move git-sync container to bottom, beacuse KEDA get environment variables(AIRFLOW_CONN_AIRFLOW_DB) from worker container(git-sync container not contain this env variable)

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Comment by kaxil** [comment]
I am not sure I follow, can you add some details please, does changing the order of a list/array matter?

**Comment by YuDorogov** [comment]
If i use git-sync sidecar container with keda autoscaler, git-sync will be 0 in containers array, and not contain connection env's, then KEDA could not get [AIRFLOW_CONN_AIRFLOW_DB](https://github.com/apache/airflow/blob/508cd394bcf8dc1bada8824d52ebff7bb6c86b3b/chart/templates/workers/worker-kedaautoscaler.yaml#L47) variable from git-sync sidecar

**Review by dimberman — APPROVED** [review]

**Comment by dimberman** [comment]
@YuDorogov can you please get tests to pass? I can merge when they work.

**Comment by dimberman** [comment]
@YuDorogov what happened? Do you need help cleaning up the history?

**Pull request closed without merging**
