### PR TITLE
[Airflow-1737] Handle `execution_date`s with fractional seconds in www/views

### PR DESCRIPTION
**Pull request by 7yl4r**
Make sure you have checked _all_ steps below.

### Jira

- [X] My PR addresses the following [AIRFLOW-1737](https://issues.apache.org/jira/browse/AIRFLOW-1737) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-1737

### Description

- [X] Adds a simple util method to handle `execution_date` strings with and without fractional seconds based on length & uses it to address linked issue.

### Tests

- [X] does not need (additional) testing for this extremely good reason: Should be covered under existing tests

### Commits

- [X] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [X] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [X] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
well... `git diff 1b53882a7cc64358e09eed3afb53069c1fba2b94 -u -- "*.py" | flake8 --diff`
aka `git diff upstream/v1-9-test -u -- "*.py" | flake8 --diff`... yes.

### CODE REVIEW

**Comment by 7yl4r** [comment]
Oh :hankey: I just saw `parse_execution_date` on the master branch: https://github.com/apache/incubator-airflow/commit/313f5bac4a3f804094bcd583e0e5fbc3b5f405bb

Probably better to pull that method over rather than using my different one for `v1-9-*`.

My git-fu doesn't feel strong enough to cherry-pick a section of a file from a commit on different branch though.

**Comment by feng-tao** [comment]
this shouldn't be an issue for master branch any more.

**Comment by 7yl4r** [comment]
did I misunderstand the workflow here? I assumed v1-9-test is still accepting pull requests.

**Comment by feng-tao** [comment]
@7yl4r , I don't think we update 1.9 branch any more.

**Comment by bolkedebruin** [comment]
@feng-tao officially we can. We support N-1 but we haven't really been doing it until now

**Comment by ashb** [comment]
Do we still need this in 1.10/master or does the linked commit also fix the issue reported here?

We're unlikely to create a 1.9.1, so if this is still needed could you retarget against master (and I'll cherry-pick it in to the 1.10.1 branch.)

**Comment by feng-tao** [comment]
@ashb, I think this issue is only on 1.9 branch. The master branch has fixed this issue(https://github.com/apache/incubator-airflow/commit/313f5bac4a3f804094bcd583e0e5fbc3b5f405bb).

**Comment by 7yl4r** [comment]
Yes, this is only an issue in the 1.9 branch. Since there isn't a 1.9.1 planned I will close this and focus my efforts on keeping nodes up-to-date. :wink: :+1:

**Pull request closed without merging**
