### PR TITLE
The librabbitmq library stopped installing for python3.7

### PR DESCRIPTION
**Pull request by potiuk**
When preparing backport relases I found that rabbitmq was not
included in the "devel_ci" extras. It turned out that librabbitmq was
not installing in python3.7 and the reason it turned out to be
that librabbitmq is not maintained for 2 years already and it
has been replaced by py-amqp library. The pythhon py-amqp
library has been improved using cython compilation, so it
became production ready and librabbitmq has been abandoned.

We are switching to the py-amqp library here and adding
rabbitmq back to "devel_ci" dependencies.

---
Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Target Github ISSUE in description if exists
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by mik-laj — APPROVED** [review]

**Comment by mik-laj** [comment]
Here is related issue: https://github.com/celery/librabbitmq/issues/153

**Review by ashb — COMMENTED** [review]
This change seems fine so long as Celery still work with this library - I'm not sure if we check rabbitmq in our pipelines?

**Comment by mik-laj** [comment]
@ashb We consulted this change with Celery's maintainer

> actually py-amqp has been the main supported library for last two years. our all focus is on py-amqp. imho py-amqp is more feature rich. i would suggest drop librabbitmq as dependency and focus your effort to py-amqp along with the celery core team :) you can also check the recently merge cython improvements on py-amqp package :)

> this is a drop in replacement. I would try py-amqp docs first

**Review by ashb — APPROVED** [review]

**Review by kaxil — APPROVED** [review]

**Review by auvipy — APPROVED** [review]
superb!

**Comment by auvipy** [comment]
> This change seems fine so long as Celery still work with this library - I'm not sure if we check rabbitmq in our pipelines?

active celery core member here. py-amqp is the go to library for last 3 years :) though it's more older.

**Comment by potiuk** [comment]
And ... merged... Thanks @auvipy for help!

**Comment by potiuk** [comment]
> This change seems fine so long as Celery still work with this library - I'm not sure if we check rabbitmq in our pipelines?

Yep. I run integration tests with it and they all passed ... Breeze is really helpful for those kind of things.

**Comment by auvipy** [comment]
> And ... merged... Thanks @auvipy for help!

Welcome! We will be glad to improve both airflow and celery where needed!

**Comment by kaxil** [comment]
> > And ... merged... Thanks @auvipy for help!
> 
> Welcome! We will be glad to improve both airflow and celery where needed!

Thanks @auvipy . When you have time can you take a look at Celery code in Airflow to see if there are places we can optimize :)

**Comment by auvipy** [comment]
> > > And ... merged... Thanks @auvipy for help!
> > 
> > 
> > Welcome! We will be glad to improve both airflow and celery where needed!
> 
> Thanks @auvipy . When you have time can you take a look at Celery code in Airflow to see if there are places we can optimize :)

I'm already collaborating with airflow team to improve celery where needed and reviewing pr/sharing knowledge :) and will continue to do so

**Pull request merged**
