### PR TITLE
Add missing call to Super class in remaining providers

### PR DESCRIPTION
**Pull request by kaxil**
The other providers are relatively **slow-changing in nature** so I don't think a separate PR is needed but let me if you think we should separate them in different PRs

Make sure to mark the boxes below before creating PR: [x]

- [x] Description above provides context of the change
- [x] Unit tests coverage for changes (not needed for documentation changes)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [x] Relevant documentation is updated including usage instructions.
- [x] I will engage committers as explained in [Contribution Workflow Example](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#contribution-workflow-example).

---
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).
Read the [Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines) for more information.

### CODE REVIEW

**Review by potiuk — APPROVED** [review]

**Comment by mik-laj** [comment]
How do we want to protect ourselves against regression?

**Comment by potiuk** [comment]
Pylint plugin ? As separate request.

**Comment by mik-laj** [comment]
https://github.com/apache/airflow/blob/master/pylintrc#L167

**Comment by potiuk** [comment]
Yeah... :)

**Comment by zhongjiajie** [comment]
Do you have a plan to fix it?

**Comment by potiuk** [comment]
Oh yeah

**Comment by mik-laj** [comment]
I invite you to contribute. It is worth fixing it.

**Comment by zhongjiajie** [comment]
Like to do it.

**Pull request merged**
