### PR TITLE
fix(smart_sensor): runtime and unbound var errors

### LINKED ISSUE #14770: [Smart sensor] Runtime error: dictionary changed size during iteration
**What happened**:

Smart Sensor TI crashes with a Runtime error. Here's the logs:
```
RuntimeError: dictionary changed size during iteration
  File "airflow/sentry.py", line 159, in wrapper
    return func(task_instance, *args, session=session, **kwargs)
  File "airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "airflow/sensors/smart_sensor.py", line 736, in execute
    self.flush_cached_sensor_poke_results()
  File "airflow/sensors/smart_sensor.py", line 681, in flush_cached_sensor_poke_results
    for ti_key, sensor_exception in self.cached_sensor_exceptions.items():
```

**What you expected to happen**:

Smart sensor should always execute without any runtime error.

**How to reproduce it**:
I haven't been able to reproduce it consistently since it sometimes works and sometimes errors.

**Anything else we need to know**:
It's a really noisy error in Sentry. In just 4 days, 3.8k events were reported in Sentry.

### PR DESCRIPTION
**Pull request by shivanshs9**
Closes #14770

---

Fixes various runtime errors in smart sensor:
1. UnboundLocalError
```
UnboundLocalError: local variable 'query_result' referenced before assignment
  File "airflow/sensors/smart_sensor.py", line 639, in _execute_sensor_work
    self._mark_multi_state(
  File "airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "airflow/sensors/smart_sensor.py", line 470, in _mark_multi_state
    self.log.info("Marked %s tasks out of %s to state %s", count_marked, len(query_result), state)
```
2. RuntimeError
```RuntimeError: dictionary changed size during iteration
  File "airflow/sentry.py", line 159, in wrapper
    return func(task_instance, *args, session=session, **kwargs)
  File "airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "airflow/sensors/smart_sensor.py", line 736, in execute
    self.flush_cached_sensor_poke_results()
  File "airflow/sensors/smart_sensor.py", line 681, in flush_cached_sensor_poke_results
    for ti_key, sensor_exception in self.cached_sensor_exceptions.items():
```
3. InvalidRequestError (should be related to 1)
```
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: Timeout, PID: 24375 (Background on this error at: http://sqlalche.me/e/13/7s2a)
  File "airflow/sensors/smart_sensor.py", line 639, in _execute_sensor_work
    self._mark_multi_state(
  File "airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "contextlib.py", line 120, in __exit__
    next(self.gen)
  File "airflow/utils/session.py", line 32, in create_session
    session.commit()
  File "sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "sqlalchemy/orm/session.py", line 502, in commit
    self._assert_active(prepared_ok=True)
  File "sqlalchemy/orm/session.py", line 289, in _assert_active
    raise sa_exc.InvalidRequestError(
```

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — COMMENTED** [review]
cc @YingboWang @KevinYang21

**Comment by kaxil** [comment]
@KevinYang21 @YingboWang Can you take a look at this please

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
@shivanshs9 Can you rebase your PR on Main please

**Comment by shivanshs9** [comment]
@kaxil I rebased the PR and apparently the RuntimeError is fixed in another PR - https://github.com/apache/airflow/pull/14920, explained in [this comment](https://github.com/apache/airflow/pull/14920/files#r598949266).

**Review by kaxil — APPROVED** [review]

**Pull request merged**
