### PR TITLE
[AIRFLOW-3807] Fix Graph View Highlighting of Tasks

### PR DESCRIPTION
**Pull request by feluelle**
Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-3807
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Note: For the highlighting to work it is required that the **labels matches the actual css classes** that give the tasks its colors. An exception is the `null` state (`None` state in python). If a tasks state is `null` in js it will add the `no_status` css class to this node.

Main Changes:
- fixes "up_for_retry" and "up_for_reschedule" tasks when hovering over "retry"/"rescheduled" task state
- fixes "null" status when hovering over "no status" task state
- adds missing task states to stateFocusMap that will be used for highlighting tasks when clicking on task state
- updates Tree View task status labels to be the same as in the Graph View

**Before:**

**After:**

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.
  - All the public functions and the classes in the PR contain docstrings that explain what it does

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by feluelle** [comment]
Ready for Review :) PTAL @ashb @feng-tao @kaxil @Fokko when you got the time :)

**Comment by Fokko** [comment]
@verdan Any thoughts?

**Comment by ashb** [comment]
@feluelle Could you give before and after screenshots?

**Comment by verdan** [comment]
LGTM 👍 
As Ash suggested, before and after screenshots would be nice.

**Comment by feluelle** [comment]
Thanks. I think I will increase the scope of this ticket through fixing [this](https://issues.apache.org/jira/browse/AIRFLOW-3748) as well.
I will update the Jira Ticket + PR accordingly and add screenshots when I am done.

**Comment by feluelle** [comment]
Due to renaming of the tasks' status labels in the Graph View should I also rename them in the Tree View as well so it is consistent? Or can this be delayed to another PR?

**Comment by ashb** [comment]
If it's the same sort of change (i.e. the task labels are wrong in graph and tree views) then change the commit message appropriately and have one PR and Jira ticket.

**Comment by feluelle** [comment]
Btw I updated this PR (+ description) and added the Tree View changes to it. 
Feel free to merge this if you haven't any more comments :P @Fokko @ashb 

P.S. The failing check (kubernetes error) is unrelated I think.

**Comment by feng-tao** [comment]
cool, lgtm

**Pull request merged**
