### PR TITLE
Set Postgres autocommit as supported only if server version is < 7.4

### LINKED ISSUE #690: GenericTransfer and Postgres - ERROR - SET AUTOCOMMIT TO OFF is no longer supported
Trying to implement a generic transfer

``` python
t1 = GenericTransfer(
  task_id = 'copy_small_table',
  sql = "select * from my_schema.my_table",
  destination_table = "my_schema.my_table",
  source_conn_id = "postgres9.1.13",
  destination_conn_id = "postgres9.4.5",
  dag=dag
)
```

I get the following error:

```
--------------------------------------------------------------------------------
New run starting @2015-11-25T11:05:40.673401
--------------------------------------------------------------------------------
[2015-11-25 11:05:40,698] {models.py:951} INFO - Executing <Task(GenericTransfer): copy_my_table_v1> on 2015-11-24 00:00:00
[2015-11-25 11:05:40,711] {base_hook.py:53} INFO - Using connection to: 10.x.x.x
[2015-11-25 11:05:40,711] {generic_transfer.py:53} INFO - Extracting data from my_db
[2015-11-25 11:05:40,711] {generic_transfer.py:54} INFO - Executing: 
select * from my_schema.my_table
[2015-11-25 11:05:40,713] {base_hook.py:53} INFO - Using connection to: 10.x.x.x
[2015-11-25 11:05:40,808] {base_hook.py:53} INFO - Using connection to: 10.x.x.x
[2015-11-25 11:05:45,271] {base_hook.py:53} INFO - Using connection to: 10.x.x.x
[2015-11-25 11:05:45,272] {generic_transfer.py:63} INFO - Inserting rows into 10.x.x.x
[2015-11-25 11:05:45,273] {base_hook.py:53} INFO - Using connection to: 10.x.x.x
[2015-11-25 11:05:45,305] {models.py:1017} ERROR - SET AUTOCOMMIT TO OFF is no longer supported
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models.py", line 977, in run
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/generic_transfer.py", line 64, in execute
    destination_hook.insert_rows(table=self.destination_table, rows=results)
  File "/usr/local/lib/python2.7/dist-packages/airflow/hooks/dbapi_hook.py", line 136, in insert_rows
    cur.execute('SET autocommit = 0')
NotSupportedError: SET AUTOCOMMIT TO OFF is no longer supported

[2015-11-25 11:05:45,330] {models.py:1053} ERROR - SET AUTOCOMMIT TO OFF is no longer supported
```

Python 2.7
Airflow 1.6.1
psycopg2 2.6 (Also tried 2.6.1)
Postgeres destination 9.4.5

Any idea on what might cause this problem?

### PR DESCRIPTION
**Pull request by underyx**
Fixes #690.

The server-side autocommit setting was removed here http://www.postgresql.org/docs/7.4/static/release-7-4.html

### CODE REVIEW

**Comment by bolkedebruin** [comment]
Thanks for the contribution! Please follow these http://chris.beams.io/posts/git-commit/ guidelines for your commit message. It helps creating changelogs and release notes in the future. In this case please move the 'Fixes #690" to the end of your commit message.

Then I will merge.

**Comment by underyx** [comment]
@bolkedebruin Sure thing, sorry about that. I was using the github.com editor and didn't realize I went over 72 characters (thought it'd tell me) and then I was just too lazy to clone the repo & amend the commit. But I'm glad you're enforcing this rule! I've force-pushed a fixed commit.

**Comment by bolkedebruin** [comment]
Ah but then I am going to nitpick ;-)

```
Set Postgres autocommit as supported only if server version is < 7.4

The server-side autocommit setting was removed here http://www.postgresql.org/docs/7.4/static/release-7-4.html

Resolves: #690
```

**Comment by underyx** [comment]
Oh, darn, that's not nitpicking, that's just telling me that I messed up :D

I read the article a while ago so I did not check it now, and turns out I remembered the format wrong. Fixed the message, and sorry again!

**Comment by bolkedebruin** [comment]
:+1:

**Pull request merged**
