### PR TITLE
Kubernetes version bump

### LINKED ISSUE #36678: apache-airflow-providers-cncf-kubernetes requires latest kubernetes version
### Description

Update apache-airflow-providers-cncf-kubernetes to use kubernetes latest versions 
kubernetes | >=21.7.0,<24
-- | --

### Use case/motivation

Kubernetes has released latest versions recently v1.29 but airflow kubernetes is stuck with v1.23 and not compatible with the latest versions.
https://github.com/kubernetes-client/python

### Related issues

Since the kubernetes v1.23 has come to end of life and eks is not supporting the version. It would be nice to see upgraded
 apache-airflow-providers-cncf-kubernetes

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by dirrao**
close: #36678 
extension: #36684

### CODE REVIEW

**Comment by dirrao** [comment]
@potiuk 
Prod image build failing due to user constraints. How to update the user constraints file and test?

**Comment by hussein-awala** [comment]
Close and reopen to run all the tests

**Comment by dirrao** [comment]
> `#52 25.79 The conflict is caused by: [7496](https://github.com/apache/airflow/actions/runs/7676485430/job/20924456098?pr=37040#step:7:7567) #52 25.79 apache-airflow-providers-cncf-kubernetes 7.14.0.dev0 depends on kubernetes<=29.0.0 and >=28.1.0 [7497](https://github.com/apache/airflow/actions/runs/7676485430/job/20924456098?pr=37040#step:7:7568) #52 25.79 The user requested (constraint) kubernetes==23.6.0`

I am still seeing the same issue.

**Comment by potiuk** [comment]
The problem was that you manually modified the `provider_dependencies.json" file and did not modify `pyproject.toml` (they are both generated from provider.yaml being the single source of truth).  

Generally you shoudl only generate provider.yaml and all the rest should be automatically updated via pre-commit (so when you update provider.yaml, both generated/provider_dependencies.json and pyproject.toml are regenerated automatically).

I will add some protection against someone making similar mistake.

**Comment by potiuk** [comment]
Protection against such manual updates here: https://github.com/apache/airflow/pull/37052

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Seems there are some errors to fix though

**Comment by potiuk** [comment]
Looks like output of some tests is different than expected with the upgraded client (which is somewhat expected) - either the tests should be fixed or some of the "real" code updated. 

FYI @dirrao -> the way how to run k8s tests locally is described here https://github.com/apache/airflow/blob/main/contributing-docs/testing/k8s_tests.rst step-by-step

**Comment by potiuk** [comment]
You need to rebase and regenerate the deps @dirrao :+1: 

> There is a need to regenerate /home/runner/work/airflow/airflow/generated/provider_dependencies.json
You need to run the following command locally and commit generated generated/provider_dependencies.json file:

> breeze static-checks --type update-providers-dependencies --all-files

**Comment by dirrao** [comment]
@potiuk 
I have fixed rest of the issues. Thank you.

**Pull request merged**
