### PR TITLE
Add checkbox snippet

### PR DESCRIPTION
**Pull request by shubhamraj-git**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jscheffl** [comment]
Where is the checkbox to be used  in future? Or any ticket associated to the demand creating it?

**Comment by shubhamraj-git** [comment]
> Where is the checkbox to be used in future? Or any ticket associated to the demand creating it?

Yes @jscheffl , This will be used in variables list or list page, where the rows need to be selected. I didn't raise any PR thats why couldn't link any issues towards it.

**Review by jscheffl — APPROVED** [review]
Okay, then actually would have preferred to add it in a PR where needed... usually once you integrate you see the gaps. but anyway LGTM

**Comment by shubhamraj-git** [comment]
Yaa, actually I have started working on it, faced the issue, thought might rebase it, that PR will take longer to be raised.  But will keep this in mind from next time.

**Pull request merged**
