### PR TITLE
Add --conf arg in `airflow dag test` cli-command

### LINKED ISSUE #25671: `airflow dags test` command with run confs
### Description

Currently, the command [`airflow dags test`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#test) doesn't accept any configs to set run confs.  We can do that in [`airflow dags trigger`](https://airflow.apache.org/docs/apache-airflow/stable/cli-and-env-variables-ref.html#trigger) command through `--conf` argument.

The command `airflow dags test` is really useful when testing DAGs in local machines or CI/CD environment.  Can we have that feature for the `airflow dags test` command?

### Use case/motivation

We may put run confs same as `airflow dags trigger` command does.

Example:
```
$ airflow dags test <DAG_ID> <EXECUTION_DATE> --conf '{"path": "some_path"}'
```

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by pankajastro**
closes: https://github.com/apache/airflow/issues/25671

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by clellmann** [comment]
Hi, there is already a PR opened solving this problem :)

https://github.com/apache/airflow/pull/25900

**Comment by potiuk** [comment]
:D Can you take a look and agree between yourselves who's change is better :) @clellmann @pankajastro :D ? Basicly review each other's code and decide :)

**Comment by potiuk** [comment]
You can even become co-authors of that single change that gets merged :)

**Comment by clellmann** [comment]
@pankajastro As I see, I have written a dedicated unit test for the new feature. Would it then be ok for you merging my PR? :)

**Comment by pankajastro** [comment]
> @pankajastro As I see, I have written a dedicated unit test for the new feature. Would it then be ok for you merging my PR? :)

Sure, no worries, I'll close this one :)

**Comment by potiuk** [comment]
Tahat was quick :)

**Pull request closed without merging**
