### PR TITLE
[AIRFLOW-4859] Extend list of pylint good-names

### PR DESCRIPTION
**Pull request by turbaszek**
Nearly 10% of pylint errors are related to too short variable name (invalid-name error). So this PR proposes to add `cm, db, f, dr, op` to pylint good-names. Those are shortcuts for:
- op  = operator
- dr  = dag run
- f = file
- db = database
- cm = context manager

Stats:
- all pylint errors ~ 4593
(`cat _pylint.txt | grep '.py' | cut -d ":" -f 1 | wc -l`)
- unique files with errors without new good-names: 676 
(`cat _pylint.txt | grep '.py' | cut -d ":" -f 1 | uniq -c | wc -l `)
- errors related to `cm, db, f, dr, op` ~ 510
- unique files with errors with new good-names ~ 660

Pros:
- 510 less errors to fix
- 16 less files to refactor

Cons:
- New variables could be ambiguous if not used in right context

We can also try to allow this change only for tests. This could be done for example by dynamically creating `pylintrc_test` in `ci_pylint.sh`.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
  - https://issues.apache.org/jira/browse/AIRFLOW-4859

### CODE REVIEW

**Comment by turbaszek** [comment]
What are your thoughts @ashb @BasPH @potiuk @mik-laj ?

**Review by potiuk — APPROVED** [review]
I am perfectly OK ok with it. It seems that those short names are really well established in the whole Airflow codebase and fighting it might actually decrease readability of the code eventually. I think it's good we have a short list of those names often used and since we have control on adding new ones - it should be pretty easy to learn by even new users what each variable stands for. 

@BasPH  @ashb  - what do you think? I think it's fairly reasonable to use those names.

**Comment by ashb** [comment]
`cm` is the only one I'm unsure of. Does that mostly just appear in the tests?

Ah and the `cm` came directly from the python unittest docs. 👍

**Review by ashb — APPROVED** [review]

**Comment by turbaszek** [comment]
> `cm` is the only one I'm unsure of.

I also have doubts but it seems quite popular:
`105 Variable name "cm" doesn't conform to snake_case naming style (invalid-name)`

**Comment by potiuk** [comment]
@ashb @nuclearpinguin: Google search:
'ContextManager "as context_manager"' = 213 results
'ContextManager "as cm"' =  3 830 results

Not very scientific, but I think if we consider those two options, the winner is quite clear :)

**Comment by ashb** [comment]
I'm happy leaving that one, but the naming pattern I've used is like this:


```python
        with self.assertRaises(AirflowException) as caught:
            self.cloudsql_hook.import_instance(
                instance='instance',
                body={})
        err = caught.exception
        self.assertIn("Importing instance ", str(err))
```

**Pull request merged**
