### PR TITLE
Fix provider test acessing importlib-resources

### LINKED ISSUE #18225: tests/core/test_providers_manager.py::TestProviderManager::test_hooks broken on 3.6
### Apache Airflow version

main (development)

### Operating System

Any

### Versions of Apache Airflow Providers

_No response_

### Deployment

Other

### Deployment details

_No response_

### What happened

`tests/core/test_providers_manager.py::TestProviderManager::test_hooks` is broken on 3.6 by #18209 since newer `importlib-resources` versions uses a different implementation and the mocks no longer works. This was actually visible before merging; all and only 3.6 checks in the PR failed. Let’s be more careful identifying CI failure patterns in the future 🙂 

Not exactly sure how to fix yet. I believe the breaking changes were introduced in [importlib-resources 5.2](https://github.com/python/importlib_resources/blob/v5.2.2/CHANGES.rst#v520), but restricting `<5.2` is not a long-term fix since the same version is also in the Python 3.10 stdlib and will bite us again very soon.

### What you expected to happen

_No response_

### How to reproduce

```
$ ./breeze tests -- tests/core/test_providers_manager.py::TestProviderManager::test_hooks
...
tests/core/test_providers_manager.py F                                                                  [100%]

================================================== FAILURES ==================================================
_______________________________________ TestProviderManager.test_hooks _______________________________________

self = <test_providers_manager.TestProviderManager testMethod=test_hooks>
mock_import_module = <MagicMock name='import_module' id='139679504564520'>

    @patch('airflow.providers_manager.importlib.import_module')
    def test_hooks(self, mock_import_module):
        # Compat with importlib_resources
        mock_import_module.return_value.__spec__ = Mock()
        with pytest.warns(expected_warning=None) as warning_records:
            with self._caplog.at_level(logging.WARNING):
>               provider_manager = ProvidersManager()

tests/core/test_providers_manager.py:123:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
airflow/providers_manager.py:242: in __init__
    self._provider_schema_validator = _create_provider_info_schema_validator()
airflow/providers_manager.py:92: in _create_provider_info_schema_validator
    schema = json.loads(importlib_resources.read_text('airflow', 'provider_info.schema.json'))
/usr/local/lib/python3.6/site-packages/importlib_resources/_legacy.py:46: in read_text
    with open_text(package, resource, encoding, errors) as fp:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

package = 'airflow', resource = 'provider_info.schema.json', encoding = 'utf-8', errors = 'strict'

    def open_text(
        package: Package,
        resource: Resource,
        encoding: str = 'utf-8',
        errors: str = 'strict',
    ) -> TextIO:
        """Return a file-like object opened for text reading of the resource."""
>       return (_common.files(package) / _common.normalize_path(resource)).open(
            'r', encoding=encoding, errors=errors
        )
E       TypeError: unsupported operand type(s) for /: 'Mock' and 'str'
```

### Anything else

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by uranusjr**
Fix #18225.

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
(retriggering CI)

**Review by potiuk — APPROVED** [review]
Nice. TIL.

**Comment by uranusjr** [comment]
Oops sorry I didn’t see the re-trigger above.

**Comment by kaxil** [comment]
I have reverted the `importlib-resources` changes - https://github.com/apache/airflow/pull/18250. Can you add those changes in this PR again so we test it with the change.

**Comment by uranusjr** [comment]
I’ve applied the importlib-resources version bump. My change is different from #18209 in several ways:

1. I bumped to 5.2 instead of 5.0. This is because the mock behavioural change is introduced in 5.2.
2. I removed the `importlib-resources` entry from `setup.py`. This package is already installed unconditionally (in `install_requires`) and does not need to be listed in the `devel` extra.
3. I added the `python_version < 3.7'` marker. We only import `importlib_resources` for Python 3.6 (in `provider_manager.py`) so having it installed on 3.7+ is useless.

**Comment by uranusjr** [comment]
```
tests/providers/amazon/aws/hooks/test_kinesis.py::TestAwsFirehoseHook::test_insert_batch_records_kinesis_firehose:
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the
CreateDeliveryStream operation: The security token included in the request is invalid.
```

Uhhhggrrr

**Comment by uranusjr** [comment]
WTH this seems to break `mock_kinesis` somehow?

**Comment by kaxil** [comment]
> WTH this seems to break `mock_kinesis` somehow?

That looks an unrelated failure that affects main branch too: 

https://github.com/apache/airflow/runs/3607014793#step:6:8000

**Review by kaxil — APPROVED** [review]

**Comment by potiuk** [comment]
> > WTH this seems to break `mock_kinesis` somehow?

This change touches `setup.py` so it upgrades dependencies to latest.
 
Seems that Botocore patchlevel was released yesterday and it breaks the test apparently. https://pypi.org/project/botocore/1.21.42/

This is our early-warning for new dependencies breaking Airflow at its best. We should take a look at this failed kinesis test and fix it (either fix the test or limit botocore). Only PRs that are updating setup.py (and main) are affected. All other constraints are not, which limits the impact of such dependencies breaking our build.

This can be reproduced locally by building the image with newer dependencies `./breeze --upgrade-to-newer-dependencies` .
Anyone cares to fix it :) ?

**Comment by kaxil** [comment]
> > > WTH this seems to break `mock_kinesis` somehow?
> 
> This change touches `setup.py` so it upgrades dependencies to latest.
> 
> Seems that Botocore patchlevel was released yesterday and it breaks the test apparently. https://pypi.org/project/botocore/1.21.42/
> 
> This is our early-warning for new dependencies breaking Airflow at its best. We should take a look at this failed kinesis test and fix it (either fix the test or limit botocore). Only PRs that are updating setup.py (and main) are affected. All other PRs are not, which limits the impact of such dependencies breaking our build.
> 
> This can be reproduced locally by building the image with newer dependencies `./breeze --upgrade-to-newer-dependencies` .
> Anyone cares to fix it :) ?

Don't think so, we have pinned boto3 to <1.18 (https://github.com/apache/airflow/blob/29d700dd3de7ede6b5c426f397418deb3cc7a916/setup.py#L186)

Which pins botocore version: https://github.com/boto/boto3/blob/577672298d619e59b0806aad0606d2974803c561/setup.py#L17

And from CI:

```
  Collecting botocore<1.21.0,>=1.20.112
    Downloading botocore-1.20.112-py2.py3-none-any.whl (7.7 MB)
```

**Comment by potiuk** [comment]
> 
> Don't think so, we have pinned boto3 to <1.18 (
> 

Could be also another dependency :).

**Comment by potiuk** [comment]
> > Don't think so, we have pinned boto3 to <1.18 (
> 
> Could be also another dependency :).

When you look at the logs of the failed tests - this is the exact command that we can run to reproduce this exact environment (inspect the versions installed:

```
./breeze --github-image-id be3fc5475849e6ed737c0a4531ab212b9a87c7d1 --backend sqlite --python 3.9 --db-reset --skip-mounting-local-sources --test-type Providers shell
```

**Comment by kaxil** [comment]
Interesting, wr had a dev version of moto

**Comment by uranusjr** [comment]
Yay my guess is correct. The dev version was pulled because previously we had `moto~=2.2, >=2.2.1.dev9`. According to PEP 440, if the version range specifier contains a prerelease, prereleases will be considered when pulling in dependencies, which is why a dev version was pulled with `--upgrade-strategy=eager`. Moto likely made some backward incompatibility changes recently to make `mock_kinesis` not work properly, but I have absolutely zero knowledge on moto to discern what exactly broke things (and didn’t bother to do a bisect).

**Comment by potiuk** [comment]
> Yay my guess is correct. The dev version was pulled because previously we had moto~=2.2, >=2.2.1.dev9. According to PEP 440, if the version range specifier contains a prerelease, prereleases will be considered when pulling in dependencies, which is why a dev version was pulled with --upgrade-strategy=eager.

TIL! 

So it was close guess. boto and moto - only one  letter different ;). I will add a feature to show diff vs. "fixed" constraints whenever we get a failure on "eager upgrade" build and make it quite prominent with some description like.

---------------------
If you see an unexpected test failures here, it might be because of upgraded dependencies (this build was run with eager upgrade on dependencies due to changed setup.* files)

Please check if the test also fails in `main` branch and if so, it's likely that the reason is one of those:

<DIFF HERE>
---------------------

**Review by potiuk — APPROVED** [review]

**Pull request merged**
