### PR TITLE
[AIRFLOW-1291] Update NOTICE and LICENSE files to match ASF requirements

### PR DESCRIPTION
**Pull request by mistercrunch**
JIRA: https://issues.apache.org/jira/browse/AIRFLOW-1291

* Update NOTICE with proper year range for ASF copyright
* Break down LICENSE into licenses/LICENSE-[project].txt
* add license header to jqClock.min.js

### CODE REVIEW

**Comment by skudriashev** [comment]
@mistercrunch, please fix the license check.

**Comment by mistercrunch** [comment]
@bolkedebruin @skudriashev how do I fix that?

**Comment by skudriashev** [comment]
@mistercrunch I think these files just need to be excluded from the /home/travis/build/apache/incubator-airflow/scripts/ci/check-license.sh check, but I think @bolkedebruin can say for sure.

**Comment by bolkedebruin** [comment]
Add the license directory to .rat-excludes, that solves the issue.

**Comment by criccomini** [comment]
lgtm +1

**Pull request closed without merging**
