### PR TITLE
[AIRFLOW-2876] Update Tenacity to 4.12

### PR DESCRIPTION
**Pull request by Fokko**
Tenacity 4.8 is not python 3.7 compatible because it contains reserved keywords in the code:
```
[2018-08-08 21:21:22,016] {models.py:366} ERROR - Failed to import: /usr/local/lib/python3.7/site-packages/airflow/example_dags/example_http_operator.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models.py", line 363, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/airflow/example_dags/example_http_operator.py", line 27, in <module>
    from airflow.operators.http_operator import SimpleHttpOperator
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/http_operator.py", line 21, in <module>
    from airflow.hooks.http_hook import HttpHook
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/http_hook.py", line 23, in <module>
    import tenacity
  File "/usr/local/lib/python3.7/site-packages/tenacity/__init__.py", line 352
    from tenacity.async import AsyncRetrying
```

Therefore we would like to upgrade to 4.12.0.

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-2876
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-2876\], code changes always need a Jira issue.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - When adding new operators/hooks/sensors, the autoclass documentation generation needs to be added.

### Code Quality

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by r39132** [comment]
@Fokko 
I ran setup.py install on a branch based on this PR and I am getting exceptions when starting the scheduler.
Here's the version of tenacity that was installed:
```
sianand@LM-SJN-21002367:~/Projects/airflow_incubator $ pip freeze | grep tenacity
tenacity==4.12.0
```
When I run the scheduler, I see:
```

[2018-08-08 16:06:35,130] {models.py:368} ERROR - Failed to import: /usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0.dev0+incubating-py3.6.egg/airflow/example_dags/example_http_operator.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0.dev0+incubating-py3.6.egg/airflow/models.py", line 365, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0.dev0+incubating-py3.6.egg/airflow/example_dags/example_http_operator.py", line 27, in <module>
    from airflow.operators.http_operator import SimpleHttpOperator
  File "/usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0.dev0+incubating-py3.6.egg/airflow/operators/http_operator.py", line 21, in <module>
    from airflow.hooks.http_hook import HttpHook
  File "/usr/local/lib/python3.6/site-packages/apache_airflow-2.0.0.dev0+incubating-py3.6.egg/airflow/hooks/http_hook.py", line 23, in <module>
    import tenacity
  File "/usr/local/lib/python3.6/site-packages/tenacity-4.12.0-py3.6.egg/tenacity/__init__.py", line 21, in <module>
    import asyncio
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/usr/local/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by Fokko** [comment]
Auch, thanks @r39132

**Comment by dalejung** [comment]
@r39132 is the futures backport installed in your 3.6 install?

**Comment by villasv** [comment]
@Fokko do you still intend to see this PR through? Did you reproduce @r39132's error?

**Comment by Fokko** [comment]
@villasv Currently I'm quite busy, feel free to pick this up if you like.

**Comment by matrixise** [comment]
+1 for the support of tenacity and python 3.7. 3.7 has been released in june, and we are in november. 
Python 3.7 is the default version of fedora 29.

**Comment by feluelle** [comment]
I just tried to reproduce @r39132 error but I can't.
I ran `pip install .` from the current `master` branch and installed the following versions successfully in a python 3.6.5 venv.

Airflow Version: v2.0.0.dev0+
Tenacity Version: 4.12.0

After installation I ran `airflow initdb` then `airflow scheduler` then `airflow webserver` and all seems to work - no errors.

Can someone else reproduce the error? I would like to fix it if it has not already been fixed.

**Comment by dargueta** [comment]
I also can't reproduce the crash.

`apache-airflow`: 1.10.1
`tenacity`: I tried 4.11 _and_ 4.12.
Python: 3.7.2 and 3.6.8

**Comment by dargueta** [comment]
@r39132 your crash is specific to MacOS. Apple makes modifications to the vanilla install, resulting in this specific bug you're encountering; see [here](https://stackoverflow.com/questions/50953117/os-x-pip3-broken-with-brew-install-python3-6-5-1). If you install Python from the source you won't have this crash.

**Comment by r39132** [comment]
@dargueta I'll try to find some time to verify this on a linux VM and get back to you. In the meantime, can you resolve the conflicts? if it works, I'll proceed with a merge.

**Comment by dargueta** [comment]
This isn't my PR, unfortunately. @Fokko could you fix the conflicts and change the pinning to `>= 4.11.0, <5.0`? ~I think 5.x will work but it's better not to risk it right now.~

**Comment by villasv** [comment]
In #4217 I’ve tried to use tenacity>5 and tests didn’t pass. Also the example HttpOperator DAG breaks.

**Comment by Fokko** [comment]
Resolved conflicts 👍

**Comment by Fokko** [comment]
@villasv Please share the errors, so we can work on a fix to make it Tenacity 5.x compatible. Cheers

**Comment by Fokko** [comment]
I've rebased onto latest master as well.

**Comment by feng-tao** [comment]
LGTM, thanks @Fokko

**Comment by AnderEnder** [comment]
@feng-tao, could you please backport this to the `v1-10-stable` branch?
The fix is ready, but latest release and stable branch still does not contain it.

**Comment by ashb** [comment]
@AnderEnder will do - the fix version has been set to 1.10.3 in Jira which I'm slowly working through the list and cherry-picking commits and I'll check Jira before doing the release.

**Comment by feng-tao** [comment]
thanks @ashb @AnderEnder

**Pull request merged**
