### PR TITLE
[AIRFLOW-1974] Improve Databricks Hook/Operator

### PR DESCRIPTION
**Pull request by diraol**
Make sure you have checked _all_ steps below.

### JIRA
- [x] My PR addresses the following [Airflow JIRA](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/AIRFLOW-1974

### Description
- [x] Here are some details about my PR, including screenshots of any UI changes:

I've refactored the DatabricksHook and DatabricksOperator classes in order to ease the development of new DatabricksOperators that handle other endpoints than ``2.0/jobs/runs/submit``.

To do so, I've created a DatabricksOperator "base class" and refactored the previous DatabricksSubmitRunOperator class to inherit the first.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

The previous tests for DatabricksHook and DatabricksSubmitRunOperator classes were updated to be in compliance with some small changes make the respective classes. DatabricksOperator class is tested through DatabricksSubmitRunOperator child class.

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

- [x] Passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by bolkedebruin** [comment]
@andrewmchen could you review please?

**Comment by rgabo** [comment]
The PR description references the wrong JIRA issue: AIRFLOW-1794 instead of [AIRFLOW-1974](https://issues.apache.org/jira/browse/AIRFLOW-1974).

**Comment by diraol** [comment]
Thanks @rgabo , I've fixed it!

**Comment by andrewmchen** [comment]
Sorry. I must have missed the notification from @bolkedebruin the first time. What are the concrete goals for doing this refactoring? The `DatabricksOperator` as is in your PR doesn't seem to to ease any development of any other operators since there seems to be lots of business logic which implicitly assume the API call is for Runs Submit.

Also, I'm curious. What operators would you like to see? Cluster create? Run now?

**Comment by rgabo** [comment]
To add two cents from our perspective:

We would like to submit a number of jobs to the same Databricks cluster, especially when we are backfilling DAGs. To that end, we would prefer a separate operator that ensures that a cluster configuration is already running and returns its `cluster_id`. I believe this is similar to how the EMR operators can start an EMR jobflow and then use xcom to submit a number of steps to a single EMR jobflow using the jobflow_id.

This is something that we are happy to contribute and if anything makes that work easier, that's great.

**Comment by diraol** [comment]
Hi @andrewmchen 

The goal was to ease the development of new Operators indeed. Actually, these changes were made while developing a new Operator (RunNow), but instead of putting everything on the same Issue/PR I thought it was better to split it into two PRs. This is the first one, and there is another that I am holding (waiting for the result of this one).
Here is my branch with the new operator:

https://github.com/diraol/incubator-airflow/commits/fix1998-NewOperator

If one have suggestions on how to make it better, I'm open to that.

**Comment by ron819** [comment]
@diraol @andrewmchen any progress with this? I'm also starting to work with databricks

**Comment by andrewmchen** [comment]
I'm in support of adding a `DatabricksRunNowOperator`. I don't think sharing logic through a base `DatabricksOperator` is the way to go though since we may want to add other operators which do not rely on the run polling logic. I'd much prefer to lift the run polling logic out of the class as a helper function. @isknight is working on something like this for his use case.

**Comment by agolovenko** [comment]
Hi @andrewmchen , @diraol ! Looking at the documentation, currently there're only two operators for databricks: `DatabricksRunNowOperator` and `DatabricksSubmitRunOperator `. This is quite limiting as one would ideally have access to all databricks API: for instance my case demands working with `/jobs/runs/list`, `/jobs/runs/cancel`, `/jobs/reset` e.t.c

In this perspective this PR made a lot of sense. Is there currently a way to access the above mentioned endpoints from airflow?

**Comment by isknight** [comment]
@agolovenko you might be interested in this PR also:
https://github.com/apache/airflow/pull/3813
With help from @andrewmchen I added the DatabricksRunNowOperator. Albeit a lot more improvements/work has been done since then making them a lot better!

There's currently not a way to call list/reset, but cancel is used for the submit run/run now operators. 
You can see the API endpoints that are in the databricks_hook which is used by the databricks operators to call the API here:
https://github.com/apache/airflow/blob/master/airflow/contrib/hooks/databricks_hook.py#L36

How would you picture list/reset being used in a DAG in your use case?

**Pull request closed without merging**
