### PR TITLE
AIP-81 Move CLI Commands to directories according to Hybrid, Local and Remote

### LINKED ISSUE #44204: AIP-81 Split CLI Commands into Local, Remote and Hybrid Commands
### Description

AIP-81 Split CLI Commands into Local, Remote and Hybrid Commands

### Use case/motivation

[AIP-81](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-81+Enhanced+Security+in+CLI+via+Integration+of+API)

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by bugraoz93**
closes: #44204

---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/contributing-docs/05_pull_requests.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by jscheffl** [comment]
Good that you separate big re-factoring and shifting files. Let's see if CI turns green, then after short screening I have no issue for fast merge.

**Comment by bugraoz93** [comment]
> Good that you separate big re-factoring and shifting files. Let's see if CI turns green, then after short screening I have no issue for fast merge.

Some turns out red :( I will check it out shortly

**Comment by bugraoz93** [comment]
I am surprised that my local pre-commit didn't catch this. They were there but weren't added to with git :sweat:

**Review by jscheffl — APPROVED** [review]

**Review by potiuk — APPROVED** [review]
Nice!

**Comment by potiuk** [comment]
You need to rebase / solve conflicts now @bugraoz93

**Comment by millin** [comment]
This broke airflow 2.10 + apache-airflow-providers-celery 3.9.0
```python
ModuleNotFoundError: No module named 'airflow.cli.commands.local_commands'
```

**Comment by bugraoz93** [comment]
> This broke airflow 2.10 + apache-airflow-providers-celery 3.9.0
> ```python
> ModuleNotFoundError: No module named 'airflow.cli.commands.local_commands'
> ```

Thanks @millin for bringing this up!

**Comment by kurtrwall** [comment]
Thanks for the catch. When is this fix expected to be released?

**Pull request merged**
