### PR TITLE
Add dynamic task mapping example

### LINKED ISSUE #26677: Missing DAG example of dynamic task mapping
### Description

While working on implementing [custom task notes](https://github.com/apache/airflow/pull/26457) I wanted to test my changes with [Dynamic Task mapping](https://airflow.apache.org/docs/apache-airflow/2.3.0/concepts/dynamic-task-mapping.html#simple-mapping), but we don't have any example DAGs for this.
We should add an example DAG containing this.

### Use case/motivation

For showing our users how this functionality can be used and also to improve testability for new features. 

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Jorricks**
Closes https://github.com/apache/airflow/issues/26677

### CODE REVIEW

**Comment by pierrejeambrun** [comment]
We have an embedded example in the doc in `dynamic-task-mapping.rst` (which is almost the same), can we point to this example as well ?

**Comment by josh-fell** [comment]
@Jorricks You might be running up against the same test issues as in #24085 when this was attempted before. However, I do think a core example would indeed be useful if we can overcome the test failures.

**Comment by potiuk** [comment]
> @Jorricks You might be running up against the same test issues as in #24085 when this was attempted before. However, I do think a core example would indeed be useful if we can overcome the test failures.

Indeed. It would have been very useful :).

**Comment by Jorricks** [comment]
Closed this as the other MRs have more priority and I don't have the time to work on making this work unfortunately :'(

**Pull request closed without merging**
