### PR TITLE
Display parameter values from serialized dag in trigger dag view.

### LINKED ISSUE #27228: Nested Parameters Break for DAG Run Configurations
### Apache Airflow version

Other Airflow 2 version (please specify below)

### What happened

Airflow Version Used: 2.3.3

This bug report is being created out of the following discussion - https://github.com/apache/airflow/discussions/25064

With the following DAG definition (with nested params):

```
DAG(
    dag_id="some_id",
    start_date=datetime(2021, 1, 1),
    catchup=False,
    doc_md=__doc__,
    schedule_interval=None,
    params={
        "accounts": Param(
            [{'name': 'account_name_1', 'country': 'usa'}],
            schema =  {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "default": {"name": "account_name_1", "country": "usa"},
                    "properties": {
                        "name": {"type": "string"},
                        "country": {"type": "string"},
                    },
                    "required": ["name", "country"]
                },
            }
        ),
    }
)
```

**Note:** It does not matter whether `Param` and JSONSchema is used or not, I mean you can try to put a simple nested object too.

Then the UI displays the following:

```
{
    "accounts": null
}
```

### What you think should happen instead

Following is what the UI should display instead:

```
{
    "accounts": [
        {
                "name": "account_name_1",
                "country": "usa"
       }
    ]
}
```

### How to reproduce

_No response_

### Operating System

Debian Linux

### Versions of Apache Airflow Providers

_No response_

### Deployment

Composer

### Deployment details

Although I am personally using Composer, it is most likely related to Airflow only given there are more non-Composer folks facing this (from the discussion's original author and the Slack community).

### Anything else

I have put some more explanation and a quick way to reproduce this [as a comment in the discussion](https://github.com/apache/airflow/discussions/25064#discussioncomment-3907974) linked.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/airflow/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by tirkarthi**
Deserialize parameter values before resolution for display.

closes: #27228
related: #27228

### CODE REVIEW

**Comment by uranusjr** [comment]
Are there reasons why values in `dag.params` are not de-serialised? I feel they should.

**Review by mkdir700 — APPROVED** [review]

**Comment by potiuk** [comment]
> Are there reasons why values in `dag.params` are not de-serialised? I feel they should.

What do you mean by that - for me this change looks good ?

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
CC: @uranusjr ^^

**Comment by uranusjr** [comment]
The params should have been deserialised when the operator is deserialised, not in here.

**Comment by potiuk** [comment]
> The params should have been deserialised when the operator is deserialised, not in here.

Ah I see. Right

**Review by potiuk — CHANGES_REQUESTED** [review]
As @uranusjr noticed - it should be done earlier in the lifecycle of the  DAG - when it gets deserialized from the DB.

**Comment by tirkarthi** [comment]
Thanks @potiuk and @uranusjr . It seems the check to see if the param is serialized handled only dict and not list in this case. I have updated to check to handle this in serialized_objects.py instead of views.py . Thanks @uranusjr for the review.

**Review by uranusjr — APPROVED** [review]

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Cool :)

**Pull request merged**
