### PR TITLE
Replace tenacity retry with flaky marker for ssh hook test

### PR DESCRIPTION
**Pull request by dstandish**

### CODE REVIEW

**Comment by potiuk** [comment]
Yeah.. I think this is a way to go. The "quarantined" marker should be dropped eventually. There are pros/cons of quarantined tests as nicely explained here: https://dev.to/mlapierre/pros-and-cons-of-quarantined-tests-2emj and I think we have no big capacity to follow on "fixing" quarantined tests. 

I've been following some of the other strategies: https://docs.pytest.org/en/6.2.x/flaky.html#other-general-strategies - for example we already have test split into "groups". 

Though the side-effect of this is that we will "miss" those flaky tests - there is the "flaky" test report - maybe we can surface it somehow ? There is the "flaky-report" as part of this marker - maybe we can send a daily or weekly summary of the flaky tests ?

I think Ideally some kind of summary where we can "click" to create an issue from a flaky test (self-assigned :)

**Comment by dstandish** [comment]
> Yeah.. I think this is a way to go

Your language is decidedly ambiguous Jarek ;) 

Is it a good / acceptable way, or just "a way"? i.e. should we go this route or no?

**Comment by potiuk** [comment]
Sorry. Some of the "not being native speaker" toll. 

Yes. Let's go this route! this is "THE way to go" 

Some more explanation: In Polish language there is no THE/A AT ALL. We completely miss the distinction/idea and conoation those bring :)

**Comment by dstandish** [comment]
> Sorry. Some of the "not being native speaker" toll.
> Yes. Let's go this route! this is "THE way to go"
> Some more explanation: In Polish language there is no THE/A AT ALL. We completely miss the distinction/idea and meaning those bring :)

Haha! sorry

Let me say, I actually appreciate dropping the articles and often I do this myself, purely out of economy, even though maybe it makes me sound like a slavic speaker.  In many cases it is really waste of characters.  (i dropped one there too!)

**Review by ashb — APPROVED** [review]

**Comment by potiuk** [comment]
> Let me say, I actually appreciate dropping the articles and often I do this myself, purely out of economy, even though maybe it makes me sound like a slavic speaker. In many cases it is really waste of characters. (i dropped one there too!)

All right. you are part-Slavic already. I have some plans to bring some people to a very Slavic location some day to spend time together. This will be an easy one for you ;)

**Review by potiuk — APPROVED** [review]

**Comment by dstandish** [comment]
> I have some plans to bring some people to a very Slavic location some day to spend time together.

That would be super cool

**Pull request merged**
