### PR TITLE
[AIRFLOW-5480] Fix flaky impersonation test

### PR DESCRIPTION
**Pull request by mik-laj**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-5480
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### CODE REVIEW

**Comment by feluelle** [comment]
@mik-laj do you know why this is "flaky"? How does this change fix it?

**Comment by mik-laj** [comment]
Yes. I know. This is very simple. This tests check 

```
```

**Comment by mik-laj** [comment]
@feluelle II'm not sure why it worked before, but I know why it works now.  This test verifies that if we have PYTHONPATH set it will be correctly passed during interpersonation. 
We set PYTHONPATH in this place: https://github.com/apache/airflow/blob/master/run-tests#L48
This allows you to search modules from a different location. Please note that airflow modules are available because it is installed on the system - `pip install -e `.

I would like to add quote from this file:
```
# AIRFLOW-1893 - Originally, impersonation tests were incomplete missing the use case when
# DAGs access custom packages usually made available through the PYTHONPATH environment
# variable. This file includes a DAG that imports a custom package made available and if
# run via the previous implementation of impersonation, will fail by not being able to
# import the custom package.
# This DAG is used to test that impersonation propagates the PYTHONPATH environment
# variable correctly.

```

**Comment by feluelle** [comment]
Got it, thanks. 👍  Nice one! :)

**Comment by mik-laj** [comment]
It blocks my work a bit. I hope it will be accepted soon. 

One more thing that I noticed was that it could be related to what Docker image I use. A colleague did not have this problem locally if he did not re-build the Docker image.

**Pull request merged**
