### PR TITLE
[AIRFLOW-4259] Move remaining models out of models.py

### PR DESCRIPTION
**Pull request by BasPH**
This PR finalizes the move of all classes out of the infamous models.py (including test_models.py). It's a big PR since all classes are tightly coupled which made it impossible to move out one by one. Some of the non-straight-forward things to point out:

- To preserve backwards compatibility, `airflow/models/__init__.py` imports all (sub)modules (So you can still import `airflow.models.DAG` instead of `airflow.models.dag.DAG`).
- Additionally (resulting from discussion below), `Connection` was imported everywhere as `airflow.models.connection.Connection`, which I now also imported in `airflow/models/__init__.py`, so that can now be imported as `airflow.models.Connection`.
- Classes `DAG` and `DagModel` are in the same file since they both depend on the `get_last_dagrun()` function.
- I placed classes and variables related to fernet in `airflow/models/crypto.py`.
- I had to fix (i.e. disentangle) several weird imports along the way which broke and didn't make sense. Mostly related to `airflow.models` importing absolutely everything in the Airflow project, and other files depending on the import in `airflow.models` instead of the actual module. Some examples:
	- `AirflowException` was imported in `airflow/models/__init__.py` and multiple other files imported from `airflow.models` while it's defined in `airflow.exceptions`.
	- Same for TriggerRule, this was imported in `airflow/models/__init__.py` and multiple other files imported TriggerRule from there. However, it's defined in `airflow.utils.trigger_rule.TriggerRule`, so I removed it from models and corrected those imports.
	- Same for `airflow.utils.timezone`.
	- `tests/test_models.py` turned out to import `State` twice, once via `from airflow.models import State as ST` and once via `from airflow.utils.state import State`. I removed the `ST` import.
	- Some mocks had to be changed because you have to mock from the location where you use the function/var/whatever. For example, in tests/test_models.py:TaskInstanceTest.test_email_alert I had to change `@patch('airflow.models.send_email')` into `@patch('airflow.models.taskinstance.send_email')` because it's now called from there and not airflow.models.
- The `global _CONTEXT_MANAGER_DAG` gave some trouble because a global cannot be shared over multiple files, which made it impossible to split the BaseOperator and DAG. So, I placed the `_CONTEXT_MANAGER_DAG` in airflow/settings.py, and simply import from there. The added benefit is that `global` isn't even needed! Bye bye global :-) More info: https://stackoverflow.com/a/13034908/3066428

I have 3 questions:

1. ~Since this PR relates to AIRFLOW-3456, AIRFLOW-3460, AIRFLOW-3465, AIRFLOW-3466, AIRFLOW-3470, AIRFLOW-3473 and AIRFLOW-3579, what title should I give the PR? Perhaps we could make a parent JIRA issue and place all these items as subissues. @Fokko any thoughts?~ Created parent JIRA ticket and referenced that.
2. ~In the previous moves we did not preserve backwards compatibility, i.e. models are not imported in airflow.models, instead you now have to do e.g. `from airflow.models.slamiss import SlaMiss`. Should we fix these and import all not-imported models in `airflow.models` after all? And if so: in this PR or separate PR?~ Imported all already moved classes in `airflow/models/__init__.py`.
3. ~Classes `DAG` and `DagModel` are in the same file since they both depend on the `get_last_dagrun()` function. Any strong opinions on keeping it this way, or moving the `get_last_dagrun()` function elsewhere so we can split `DAG` and `DagModel`?~ Left as is.

---------

Make sure you have checked _all_ steps below.

### Jira

- [x] My PR addresses the following [Airflow Jira](https://issues.apache.org/jira/browse/AIRFLOW/) issues and references them in the PR title. For example, "\[AIRFLOW-XXX\] My Airflow PR"
  - https://issues.apache.org/jira/browse/AIRFLOW-4259
  - In case you are fixing a typo in the documentation you can prepend your commit with \[AIRFLOW-XXX\], code changes always need a Jira issue.
  - In case you are proposing a fundamental code change, you need to create an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)).
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

See above.

### Tests

- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

No new tests, only split tests/test_models.py into modules corresponding to airflow.models.

### Commits

- [x] My commits all reference Jira issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain docstrings that explain what it does
  - If you implement backwards incompatible changes, please leave a note in the [Updating.md](https://github.com/apache/airflow/blob/master/UPDATING.md) so we can assign it to a appropriate release

### Code Quality

- [x] Passes `flake8`

### CODE REVIEW

**Comment by ashb** [comment]
1. probably a bit unwieldy to do `[AIRFLOW-3456][AIRFLOW-3460][AIRFLOW-3465][AIRFLOW- 3466]...` :D so a single Jira makes sense here to me.

2. Yes please, for users etc I think it makes sense to still `from airflow.models. import X` - it's an internal implementation detail that we moved them to separate files that I don't think is useful. No preference on this PR or others.

3. I'm fine with them being in the same file - they are very closely related.

**Comment by BasPH** [comment]
Thanks.

1. Fokko placed all issues under a parent issue so I'll reference that.
2. Will import the other classes in this PR too.
3. 👍

**Comment by BasPH** [comment]
@ashb all green now, ready for review :)

**Review by Fokko — APPROVED** [review]

**Review by feng-tao — APPROVED** [review]

**Comment by Fokko** [comment]
Thanks @BasPH for taking the time to fix this.

**Comment by Fokko** [comment]
How I have to rebase my PR's 💯

**Comment by ddelange** [comment]
Hey @BasPH @Fokko @ashb, why was `user.py` [removed](https://github.com/apache/airflow/blame/50343040ff4679e32e01f138ead80bc4bcef4b47/airflow/models/__init__.py#L38-L41) in `master`?

 

It is still used by multiple auth backends on `master` (there's also no mention of this removal in `UPDATING.md`):

https://github.com/apache/airflow/blob/88989200a66291580088188f06a6db503ac823e2/airflow/contrib/auth/backends/kerberos_auth.py#L48
https://github.com/apache/airflow/blob/88989200a66291580088188f06a6db503ac823e2/airflow/contrib/auth/backends/github_enterprise_auth.py#L38
https://github.com/apache/airflow/blob/88989200a66291580088188f06a6db503ac823e2/airflow/contrib/auth/backends/google_auth.py#L38
https://github.com/apache/airflow/blob/88989200a66291580088188f06a6db503ac823e2/airflow/contrib/auth/backends/ldap_auth.py#L127
https://github.com/apache/airflow/blob/88989200a66291580088188f06a6db503ac823e2/airflow/contrib/auth/backends/password_auth.py#L54

How would I now on `master` create an API user for instance?

Below workflow will work on `v1-10-test` but will fail on `master`:

airflow.cfg
```sh
[api]
# https://airflow.apache.org/security.html?highlight=impersonation#password
auth_backend = airflow.contrib.auth.backends.password_auth
```

upon startup I now use models.User to create a PasswordUser:
```py
import os

from airflow.contrib.auth.backends.password_auth import PasswordUser
from airflow import models
from airflow.settings import Session


def delete_users(session, username):
    """Delete all users with username"""
    query = session.query(models.User)
    to_delete = [user.id for user in query.all() if user.username == username]
    for user_id in to_delete:
        session.delete(query.get(user_id))
    if to_delete:
        session.commit()


def create_user(session, username, password):
    """Create a new user with password"""
    user = PasswordUser(models.User())
    user.username = username
    user.email = "REST_API"
    user.password = password
    session.add(user)
    session.commit()


def set_or_overwrite_api_user():
    """Add REST API user (BasicAuth), or delete if env var is unset."""
    username = os.environ.get("AIRFLOW__API_USERNAME", "api_user")
    password = os.environ.get("AIRFLOW__API_PWD")
    session = Session()  # sqlalchemy.orm.session under the hood
    delete_users(session, username)
    if password:  # empty env var treated as missing env var
        create_user(session, username, password)
    session.close()
```

**Comment by functicons** [comment]
@BasPH I have a question regard this code:
https://github.com/apache/airflow/blob/64c2eea7e86c2dc8a01256880c5c3cae8728b5eb/airflow/models/baseoperator.py#L1207-L1209

One job in our platform is hitting the "recursion depth exceeded" error. Based on the comments, it seems to be a known issue. Could you elaborate on what "Hack sorting double chained task lists by task_id to avoid hitting max_depth on deepcopy operations" means? Or any related info will be appreciated.

Thank you very much!

**Pull request merged**
