### PR TITLE
Remove  azure-storage-common from microsoft azure providers

### PR DESCRIPTION
**Pull request by pankajastro**
---
**^ Add meaningful description above**
Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/main/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code changes, an Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvement+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in a newsfragment file, named `{pr_number}.significant.rst` or `{issue_number}.significant.rst`, in [newsfragments](https://github.com/apache/airflow/tree/main/newsfragments).

### CODE REVIEW

**Comment by pankajastro** [comment]
Look like now we can remove `azure-storage-common` as dependency from Microsoft azure provider

**Comment by eladkal** [comment]
> Look like now we can remove azure-storage-common as dependency from Microsoft azure provider

Why do we have it if we don't use it?
Did we remove some functionality and forgot to remove the library?

**Comment by pankajastro** [comment]
> Why do we have it if we don't use it?
> Did we remove some functionality and forgot to remove the library?

yes I believe should have been removed in my previous PR. Look like this was a dependency for `azure-storage-file` and `azure-storage-blob`
azure-storage-file got updated in PR https://github.com/apache/airflow/pull/33904 and azure-storage-blob https://github.com/apache/airflow/pull/25426

**Review by potiuk — APPROVED** [review]

**Comment by potiuk** [comment]
Less dependencies is better :). And seems that all tests pass :)

**Pull request merged**
