### PR TITLE
Add KPO pod-template-file jinja template support.

### LINKED ISSUE #15892: KubernetesPodOperator pod_template_file content doesn't support jinja airflow template variables
KubernetesPodOperator  pod_template_file content doesn't support jinja airflow template variables. pod_template_file  is part of templated_fields list. 
https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L165

template_fields: Iterable[str] = (        'image',        'cmds',        'arguments',        'env_vars',        'labels',        'config_file',        'pod_template_file',    )

But pod_template_file content is not supporting template variables. pod_template_file can be implemented the way SparkKubernetesOperator implemented using template_ext

https://github.com/apache/airflow/blob/master/airflow/providers/cncf/kubernetes/operators/spark_kubernetes.py#L46
 template_ext = ('yaml', 'yml', 'json')

### PR DESCRIPTION
**Pull request by drdenzy**
This PR adds jinja template support for KubernetesPodOperator
`pod-template-file`.

fixes #15892 

---
**^ Add meaningful description above**

Read the **[Pull Request Guidelines](https://github.com/apache/airflow/blob/master/CONTRIBUTING.rst#pull-request-guidelines)** for more information.
In case of fundamental code change, Airflow Improvement Proposal ([AIP](https://cwiki.apache.org/confluence/display/AIRFLOW/Airflow+Improvements+Proposals)) is needed.
In case of a new dependency, check compliance with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
In case of backwards incompatible changes please leave a note in [UPDATING.md](https://github.com/apache/airflow/blob/master/UPDATING.md).

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by theodickson** [comment]
Just pointing out this was a breaking change - if you previously were using values in templated fields which ended in any of these strings, but were _not_ meant to be references to template files, the scheduler now throws an error when it tries to run the task as it tries to treat the string as a local file and load it.

**Comment by eladkal** [comment]
@theodickson This PR was released in cncf provider 2.0.0 which is a major release (previous was 1.2.0) there can be breaking changes when upgrading a major version. We also mention it in the docs:
https://airflow.apache.org/docs/apache-airflow-providers/#community-maintained-providers

**Comment by theodickson** [comment]
Sorry I should have been clearer, I realise it was mentioned in the release notes but as a feature not a breaking change. It's not exactly a huge deal and we found the issue and fixed quickly, but it's definitely a breaking change - code we were running successfully before resulted in an error after upgrading!

**Comment by oscarrobertson** [comment]
I agree that this is a breaking change, it does feel like something that could be made clearer in the release notes.

I think the code that uses this param to check the extensions also is just checking `endswith`, it's not parsing to find an extension:  
https://github.com/apache/airflow/blob/main/airflow/models/baseoperator.py#L1047

In other operators the leading `.` of the extension is included: https://github.com/apache/airflow/blob/main/airflow/operators/sql.py#L107

This means this change is probably overly inclusive of parameters being considered files.

**Pull request merged**
